### ISSUE TITLE
`controlsAboveOverlay: true` not respected when using `canvas.loadFromJSON`

### ISSUE THREAD

**Issue by jaydenseric** [kangax/fabric.js#1012]
`controlsAboveOverlay: true` canvas option is not respected when using `canvas.loadFromJSON`. Using `console.log` on the JSON I can see that the option has been correctly preserved, it is just not being used when being loaded for some reason.

**Comment by asturur** [comment]
The point is that in loadFrom json we do not restore anything but objects, overlay and background. There is nothing restoring "propertiesToInclude"

to fix: We clone the json object, we delete objects and the overlays/background, and the we setOptions(clonedJson);

it should works
