### ISSUE TITLE
Handle img onerror on setBackgroundImage

### ISSUE THREAD

**Issue by kdamevin** [kangax/fabric.js#1015]
Hi,

I would need to be able to specify the onerror method when using setBackgroundImage on my canvas.

Something like that would work for me:
``` 
setBackgroundImage: function (url, callback, options, errorCallback) 
``` 

This would mean adding a new parameter to loadImage as well as follow:
``` 
function loadImage(url, callback, context, errorCallback) 
``` 

and just set the img.onerror to that errorCallback if passed as a parameter.

I guess it could be passed as an option of setBackgroundImage as well.

Would it be possible to implement this simple feature?

Cheers,
Kim

**Comment by asturur** [comment]
I added a check to do not set image if the load fails.
