### ISSUE TITLE
IText additions/fixes 2.0

### ISSUE THREAD

**Issue by Kienz** [kangax/fabric.js#1028]
- [x] Delete selection with `backspace` or `delete` key didn't work if selection begins in line 0 char 0
- [x] Mouse click after line should set cursor to this line - at the end of the line
- [x] Mouse selection should select line if you hover over previous line *[1]*
- [x] Fire `text:changed` in canvas context and `changed` in text context
- [x] Set cursor to mouse click point if editMode is entered (one click if object is still active) - double click still selects word that is clicked
- [ ] Use cursor `vertical-text` if object is rotated (similar to cornerControls)
- [x] Select text if mouse moves outside of the textBox

*[1] Mouse selection (eg. MS Word)*
![image](https://f.cloud.github.com/assets/954545/1684153/515e50c8-5dc7-11e3-83fc-95a083ffb082.png)

**Comment by asturur** [comment]
i marked this:
**Set cursor to mouse click point if editMode is entered (one click if object is still active) - double click still selects word that is clicked**

it actually works.

**Comment by asturur** [comment]
for this
**Select text if mouse moves outside of the textBox**

It  would work (i  think )if we could initialize on the canvas the mousemovehandler instead that just on the object.

**Comment by kangax** [comment]
True, let's try that

**Comment by asturur** [comment]
@kienz @kangax i did even word selection from not editing, then i trashed it because i thought i gave bad meaning to the request.
for double click is ok, triple click was not very good but could be improve of course.
i do not like it as a behavour but if is a necessary function i think i have it

**Comment by kangax** [comment]
I think "Select text if mouse moves outside of the textBox" is really the most important thing here — it makes it significantly easier to work with iText and all other decent editors have it. Once we have it, we can close this one (vertical cursor seems like a minor detail to me)

**Comment by asturur** [comment]
PR #2007 to tick "Select text if mouse moves outside of the textBox"

**Comment by kangax** [comment]
Closing this one
