### ISSUE TITLE
`clipTo` context origin should be from left/top

### ISSUE THREAD

**Issue by raichu** [kangax/fabric.js#1040]
Inside the clipTo function, the origin (0,0) appears to be the middle of the image (even after the recent centerX/centerY changes), and also the width/height appears to be wrong:

Here's an example that demonstrates the problem
http://jsfiddle.net/jfsVS/

**Comment by InsomniumBR** [comment]
+1

I stuck on this problem all the day:
https://github.com/kangax/fabric.js/issues/2717

And I can't figure out how to solve it and I think the problem is related to this origin when using flipX.
The solution on the link just doesn't work for me.
I had a function that calculates the clipping and it was working well until I mixed it with flipping.

I really can't understand the new origin and coordinates after flipping... =/
I am trying values to understand it, but with no success.

**Comment by InsomniumBR** [comment]
Thanks god I found a way.
Sorry about not having a fiddle example, it's a complex interface to do a sample.

My normal clipping (rect parameters):
        clipParameters = {
            left: ((img.width / 2) * -1) - img.left,
            top: ((img.height / 2) * -1) - img.top,
            width: div.width(),
            height: div.height(),
            clippingRadius: radius
        };

My flipped clipping:
        if (flipped) {
            clipParameters.left = (img.width / 2) + img.left;
            clipParameters.width *= -1;
        }

Now I got it.
After flipped the X axis of the context is inverted.
I was missing inverting my "width".
I still fell a lot dumb about these math, but now it works.
Let's try angles now... =O

**Comment by InsomniumBR** [comment]
I ended up using another solution, so much better and easy to understand.
I have applied transformations on the clipping rectangle, similar to this thread:
http://stackoverflow.com/questions/16437696/multiple-clipping-areas-on-fabric-js-canvas

Thanks

**Comment by ekulabuhov** [comment]
If anyone is looking for a fix to the origin not being in top/left corner, check this: https://jsfiddle.net/wethrw20/

These lines are what you need to add:
```JavaScript
clipTo: function (ctx) {
      ctx.save();
      ctx.setTransform(1, 0, 0, 1, 0, 0);
      polygon.render(ctx);
      ctx.restore();
 }
```

**Comment by asturur** [comment]
This will not work on most mobile devices or retina screen

```
clipTo: function (ctx) {
      ctx.save();
      ctx.setTransform(retinaScaling, 0, 0, retinaScaling, 0, 0);
      polygon.render(ctx);
      ctx.restore();
}
```
