### ISSUE TITLE
Why call the callback when image fail to load ?

### ISSUE THREAD

**Issue by butch2k** [kangax/fabric.js#1079]
Hi,

i noticed that you call the callback in the loadImage function even when image fail to load which in turn result in an error at the upper level. Indeed if you serialize a canvas with an image in there and then make sure the url used for the image return a 404 the whole canvas fail to load because of an attempt to get a the width of a null.

```
      /** @ignore */
      img.onerror = function() {
        fabric.log('Error loading ' + img.src);
        callback && callback.call(context, null, true);
        img = img.onload = img.onerror = null;
      };
```

**Comment by asturur** [comment]
this is fixed.
