### ISSUE TITLE
Possible I-Text Enhancement - Call renderChar once for each style

### ISSUE THREAD

**Issue by GordoRank** [kangax/fabric.js#1105]
Currently when any individual styles apply to characters on I-Text objects we render each character individually, resulting in a huge amount of unnecessary ```fillText()``` calls.

In a similar fashion to the way we recently optimized ```renderSelection()``` we should be able to calculate and render each style in a single ```fillText()``` call.

i.e.

LOGIC : 

1. Store current style
2. Loop through chars, when style differs, render previous text at previous style
3. update current style to previous style.
4. If linebreak occurs, render text at current style.

etc...

This way performance for I-Text objects should be greatly improved especially since most bodies of text are likely to only have a few differing text styles.

I'll work on this now.

**Comment by asturur** [comment]
I ended up noticing the same thing and i thing i fixed it.

- renderChar is called once for every group of letter that use the same style (this was like this also before)
- during renderChar that happens on stroke and fill, we stroke and fill only if necessary. double passes disappeared or at least are reduced by a lot, maybe some improvement is still possible.
```
if (decl) {
        charHeight = this._getHeightOfChar(ctx, _char, lineIndex, i);
        shouldStroke = decl.stroke;
        shouldFill = decl.fill;
        textDecoration = decl.textDecoration;
      }
      else {
        charHeight = this.fontSize;
      }

      shouldStroke = (shouldStroke || this.stroke) && method === 'strokeText';
      shouldFill = (shouldFill || this.fill) && method === 'fillText';

      decl && ctx.save();

      charWidth = this._applyCharStylesGetWidth(ctx, _char, lineIndex, i, decl || {});
      textDecoration = textDecoration || this.textDecoration;

      shouldFill && ctx.fillText(_char, left, top);
      shouldStroke && ctx.strokeText(_char, left, top);
```
- a check for presence of style has been added to avoid not drawing when fill and stroke where both empty but some style was present
