### ISSUE TITLE
Feature Request - Move cursor/selection onto separate, temporary canvas

### ISSUE THREAD

**Issue by GordoRank** [kangax/fabric.js#1106]
Despite several recent optimizations, text selection rendering is still slow when dealing with I-Text objects that have lots of individual character styles.

I would like to propose moving the cursor/selection rendering onto a separate canvas element.

We could create the element in ```enterEditing()``` and destroy it again in ```exitEditing()``` inserting it below the ```upperCanvasEl```  but above the ```lowerCanvasEl``` in the element stack;

While in editing mode ```renderAll()``` would not be called at all unless the text has changed.  Currently it fires every frame meaning that the whole I-Text object as well as any other objects in the scene have to be re-rendered, despite the fact that they are not changing at all.

This way cursor movement and selection should always be extremely responsive regardless of the complexity level of the I-Text object.

@kangax / @Kienz any thoughts?

**Comment by kangax** [comment]
This is now done :)
