### ISSUE TITLE
fabric.IText.instances never cleared?

### ISSUE THREAD

**Issue by 1am** [kangax/fabric.js#1122]
Hi

I'm experiencing an issue with IText selecting when multiple objects were added and removed quite a few time. Each time i add/remove an object it stays in the fabric.IText.instances variable. I looked through the code and from what i can see it's never really cleared. The main problem this causes is the abortCursor animation is executed for all of them and the time to handle later mousedown events starts taking forever to complete.

**Comment by asturur** [comment]
Is this still an issue?

**Comment by asturur** [comment]
No there is that line anymore.
