### ISSUE TITLE
clipping zone (like mask) is black instead of transparent

### ISSUE THREAD

**Issue by ptravassos** [kangax/fabric.js#1153]
The clipping zone is black when there is no image on the area or if the image has transparency in it.
Is there a way for the clipping zone to become transparent when we drag de image half way out.

Here is an example of what's happening: 
http://jsfiddle.net/q4nHP/12/ (image jpg)
http://jsfiddle.net/q4nHP/13/ (image with transparency)

**Comment by asturur** [comment]
For the old fiddles updated:
http://jsfiddle.net/q4nHP/30/ and http://jsfiddle.net/q4nHP/29/
if you are using a path to clip, and use the render() method, please set the fill to none.
Not setting fill, goes on the standard black default.
