### ISSUE TITLE
Exclude certain properties from toObject export

### ISSUE THREAD

**Issue by PayteR** [kangax/fabric.js#1186]
Hi, it would be cool to have some option for object to exclude them from toObject methot, something like "excludeExport: true", is it possible?

**Comment by asturur** [comment]
We still want this? is an easy add for next release.
Is a property, a line of code, 3 lines of docs, 100 lines of tests.

**Comment by asturur** [comment]
We are gonna use this property to exclude both from toObject and toSVG export.

**Comment by cyberhck** [comment]
I want to exclude overlay image from exported image, but this looks like doesn't work for images, only for json, object and svg, is there something else?

**Comment by asturur** [comment]
set it visible = false before exporting, an then set it back to true.
