### ISSUE TITLE
Optimization: use canvas *Rect functions if possible

### ISSUE THREAD

**Issue by rcmaniac25** [kangax/fabric.js#1198]
I've been doing some [performance tests (rect)](http://jsperf.com/canvas-frameworks) for a project I'm working on, and found that rect functions, such as fillRect, are multitudes faster then path drawing for rect.

In addition, I have the same tests for [circle](http://jsperf.com/canvas-frameworks-circle), [path](http://jsperf.com/canvas-frameworks-path), [text](http://jsperf.com/canvas-framework-text), and [image](http://jsperf.com/canvas-frameworks-image). Rect showed such dramatic performance over other functions that I figured it would be worth-while to mention as a possible feature/improvement.

**Comment by asturur** [comment]
I do not think that a peformance boost from lineTo to fillRect would be worth the code changes regarding renderFill and renderStroke. Things as shadows kill performance anyway. Do you think we can close this issue?

**Comment by asturur** [comment]
This feature request is either not applicable or based on old needs that are replaced by new functions or features.
The feature also did not receive attention from other developers.
I will reopen by request if other may find it interesting.
