### ISSUE TITLE
Support dblclick (double click) events

### ISSUE THREAD

**Issue by rcmaniac25** [kangax/fabric.js#1202]
Support for double click would be useful, either with the dblclick event, or it seems there is a manually handled version for IText.
##

**Comment by DonovanCharpin** [comment]
This feature would be really nice!

I have a rect and a text in a group and I would like to be able to modify one item on a dblclick event on this group targeting the good object. 

If I had this event, I could ungroup this group, let the user do the modification on the rect and regroup it.

**Comment by butch2k** [comment]
U can use fabric.ext which overload fabric with some extra eventhandlers. 
https://github.com/mazong1123/fabric.ext





On Fri, Jun 17, 2016 at 4:42 PM +0200, "Donovan" <notifications@github.com> wrote:












This feature would be really nice!



I have a rect and a text in a group and I would like to be able to modify one item on a dblclick event on this group targeting the good object. 



If I had this event, I could ungroup this group, let the user do the modification on the rect and regroup it.

**Comment by DonovanCharpin** [comment]
Thanks @butch2k! I saw this library before but I'm not fan to overload my library with extensions. But this time, I think I'm gonna do it.

**Comment by butch2k** [comment]
I use it on my own project w/o any issue. 






On Fri, Jun 17, 2016 at 4:56 PM +0200, "Donovan" <notifications@github.com> wrote:












Thanks @butch2k! I saw this library before but I'm not fan to overload my library with extensions. But this time, I think I'm gonna do it.

**Comment by DonovanCharpin** [comment]
Hoo nice feedback! I'm more confidente to use it now.

**Comment by asturur** [comment]
i was thinking to put it outside and use for all classes. We will see. I'm a bit overloaded now.
