### ISSUE TITLE
fabric.Itext dont fire canvas "object:modified" event

### ISSUE THREAD

**Issue by Kureev** [kangax/fabric.js#1239]
After "editing:exited" event i expect to get canvas "object:modified", if i changed something in the text

**Comment by QasimK** [comment]
@kangax I don't think they are enough because

1. You expect to get the `object:modified` event when the text has been edited but this event is not fired
2. Combining these events is not nice to do (i.e. you have to duplicate some code since you cannot do something like `object:modified, text:changed`)

**Comment by kangax** [comment]
Fair enough, I reopened it for now.

**Comment by asturur** [comment]
closed with 1.6.2 release

**Comment by abhi06991** [comment]
What event is available to check if the text has been changed?

**Comment by asturur** [comment]
object:modified, text:changed

**Comment by abhi06991** [comment]
awesome...it works like a charm

**Comment by guzuomuse** [comment]
@abhi06991 ,still not working for me ,i'm using version:1.63

`canvas.on({
                                    'object:modified':deal_function,
                                    'text:changed':deal_function
                                });`
can you give some jsfiddle? thanks.

**Comment by asturur** [comment]
canvas.on( 'object:modified', deal_function);

canvas.on('text:changed', deal_function);

not sure about the way you wrote it

**Comment by guzuomuse** [comment]
@asturur ,thanks for you reply,here is [https://jsfiddle.net/1fybz0h2/1/]
you can see that: when you edit the text  ; the text:changed will be fired but  "bold button click" not.
whether i have to manually use "canvas.trigger()" or not in this way?

**Comment by asturur** [comment]
fabricjs is not gonna trigger everything for you. if you have a button than execute some code and change some property, fire object modified by yourself.

**Comment by guzuomuse** [comment]
ok,thx.
