### ISSUE TITLE
StrokeWidth very thin when image is scaled (only on Safari on OSX and iOS)

### ISSUE THREAD

**Issue by jafferhaider** [kangax/fabric.js#1261]
This jsFiddle illustrates the bug: http://jsfiddle.net/gtyL8/2/

In non-Safari browsers, both rounded and non-rounded strokes will have the same width for each image size. But on Safari, the width of the stroke with rounded line join style is incorrect (thinner) when the image is scaled to be smaller.

I put some debug logs in the `_setStrokeStyles()` and `render()` functions and it doesn't seem to be a case of Fabric passing incorrect strokeWidth values. They're the same on all browsers. 

So this seems like a Safari bug. Any strategies to handle bugs like these in the Fabric codebase?

**Comment by asturur** [comment]
do not think we will ever fix this for older safari.
New safari looks ok.
