### ISSUE TITLE
Animation module missing

### ISSUE THREAD

**Issue by Robster79** [kangax/fabric.js#1262]
Hi,
in Version 1.4.4 and 1.4.o, the gestures module is missing. If I download a custom build from the fabric.js website, I get a working gestures module, but for custom builds, there is no option to include the animation module. How do I get both modules?
##

**Comment by daniel** [comment]
+1. There's is still no option to include the animation module on the custom build page (http://fabricjs.com/build/).

**Comment by asturur** [comment]
custom build reworked.
