### ISSUE TITLE
SVG Export (Text)

### ISSUE THREAD

**Issue by Lethiel** [kangax/fabric.js#1264]
Hi

Originally i posted the bug in Google Groups forum (https://groups.google.com/forum/#!topic/fabricjs/Y84MAkRh_n0), but i thought it would be better to post the bug here.

There is an error in exporting multiline text. It also appears in the official examples:
http://fabricjs.com/test/svg_export/text.html

Thanks in advance.
Best Regards

**Comment by asturur** [comment]
To me after lot investigation, looks like it happens because sometimes fabricjs export line tests with Itext and text method, mixing. I will try again after the new commit merge, and this should be closed as well.

**Comment by asturur** [comment]
This issue is fixed.
