### ISSUE TITLE
Select another object should fire "before:selection:cleared" event

### ISSUE THREAD

**Issue by Colmea** [kangax/fabric.js#1279]
Hello,

First of all, thank you for your amazing work ;)

Here is my issue:
When you select an object and then click on a white space, before:selection:cleared event is correctly fired.
But when you select an object and then click on another object, this event is not fired (and so selection:cleared).

JSFiddle: http://jsfiddle.net/xB5KR/

I guess it's not a bug, but shouldn't canvas fire selection:cleared event **whenever**  it loses focus ?
The thing is that there is no other (native) way (or I'm missing something) to get previous selected object  if "before:selection:cleared" event is not fired when selecting another object, and that's a problem if you want to update selected object before he loses focus.

As you said in previous posts, you can check if previous selected object is the same as the new one, but I think an event (before:selection:cleared or a new one) should be fired whenever an object loses focus.

What is your opinion ?
##

**Comment by archirayan3** [comment]
i am facing same issue. is there any solution for this?

**Comment by butch2k** [comment]
This choice has puzzled me for some time, and frankly i fail to understand the logic behind it. Indeed it makes a some things more complex than necessary. For instance consider you apply a filter on a selected item, clicking on anotherit one should apply the filter on the newly slected item and remove from the first one.

Currently you can't do it easily because the dispatchAllWithEvents is not properly triggered when coming from an activeObject to an object which is selectable.
This all comes down to this piece of code:

```
    _shouldClearSelection: function (e, target) {
      var activeGroup = this.getActiveGroup(),
          activeObject = this.getActiveObject();

      return (
        !target
        ||
        (target &&
          activeGroup &&
          !activeGroup.contains(target) &&
          activeGroup !== target &&
          !e[this.selectionKey])
        ||
        (target && !target.evented)
        ||
        (target &&
          !target.selectable &&
          activeObject &&
          activeObject !== target)
      );
    },
```
Commenting out the 
`  !target.selectable &&` in this code make the dispatch fires even if the target is selectable which resolves the issue at hand with no side-effect that i could think of looking at the code.

**Comment by awehring** [comment]
Stumbling about this too. As a work around in my application is quite nasty, I'm hoping for an implementation of this feature.

The following solution appears logical to me:

- An additional event `object:deselected`  fires, whenever an object looses the selection, for whatever reason. (This would complement the existing `object:selected` event.)
- The `before:selection:cleared`  and the `selection:cleared` events fire, when no object at the canvas remains selected. 

E.g. If a group of two objects is selected and one object within it is deselected, the `object:deselected` event fires.
If the remaining selected object is deselected too, all three  events fire `(object:deselected`, `before:selection:cleared`, `selection:cleared`).

Maybe `before:object:deselected` is usefull too.

**Comment by asturur** [comment]
we have the event now. Selecting another object fires at object level and at canvas level

**Comment by MegaCookie** [comment]
Just for anyone wondering how to use this new event. The event adds an optional `deselected` array of fabric objects to the event object. So use something similar like this:
```js
handleSelection = (event) => {
    const deselectedObjects = event.deselected;
    deselectedObjects?.forEach((deselectedObject) => { // or use: deselectedObjects && deselectedObjects.forEach
        // do stuff with the deselectedObject
    });
};


canvas.on('selection:updated', handleSelection);
canvas.on('selection:created', handleSelection);
canvas.on('selection:cleared', handleSelection);
```
