### ISSUE TITLE
Rotating entire pattern (not individual "chunks")

### ISSUE THREAD

**Issue by kirosaki** [kangax/fabric.js#1291]
I am having trouble in rotating pattern, as you can see in the example the pattern image go out of visible area when we rotate it because its axis is at top left corner. Is there a way I can rotate pattern at 90' degree.

http://fabricjs.com/dynamic-patterns/

Thanks & regards
##

**Comment by dumaron** [comment]
I'm interested too, there's any news about?

**Comment by asturur** [comment]
The solution would be introduce a globalAngle and rotate the canvas before calling the fill method and before applying the translation of -width/2 -height/2 that i think we are doing now.

this is renderFill function of object.class.js
```diff
      if (this.fill.gradientTransform) {
        var g = this.fill.gradientTransform;
        ctx.transform.apply(ctx, g);
      }
      if (this.fill.toLive) {
+      ctx.rotate(degreesToRadians(fill.Angle));
        ctx.translate(
          -this.width / 2 + this.fill.offsetX || 0,
          -this.height / 2 + this.fill.offsetY || 0);
      }
      if (this.fillRule === 'evenodd') {
        ctx.fill('evenodd');
      }
      else {
        ctx.fill();
      }
```
This would work for gradient also.

as an immediate solution you can add to your pattern, after you do setPatternFill, the gradientTransform property with a rotate matrix you can craft.

Then someone will ask scaling and skewing. And i'm gonna jump from the window.

**Comment by asturur** [comment]
merge with issue #3499
