### ISSUE TITLE
Make possible to use stack operation with multiple selections

### ISSUE THREAD

**Issue by spyridonas** [kangax/fabric.js#1301]
I was trying to keep a single object on top of everything on my project , and noticed that the group selection does not respect the "sendToFront()" of my object. After some experimenting i discovered (and you can do it in the kitchensink of fabric) that if you select 2 object as group with your mouse and type in the console "canvas.getActiveGroup().sendToBack()" the two objects duplicate with an offset and by selecting and moving one of them you actually move the cloned one too.
This bug aside , is it possible to have a specific object always on top of everything? As of right now i captured the events for everything on fabric (object:selected, moved,rotated, etc) and force my desired object on top using bringToFront() but it doesn't work with group. As i understand groups have other order of appearance than Objects.

**Comment by asturur** [comment]
I'm going to track this now, i know you are probably not interested anymore, but yes it should be fixed.

I think that if we send to back or to top or forward an active group, we should just cycle to all the elements of the group and move them in the stack.
