### ISSUE TITLE
SVG parsing transform matrix , result wired

### ISSUE THREAD

**Issue by lukluk** [kangax/fabric.js#1337]
```
<rect width="2560" height="1600" transform="matrix(0.2777 0 0 0.2777 608.3976 -209.6664)">
		</rect>
```

try it , all controll become very small and hard to drag that object

**Comment by asturur** [comment]
I tried to use all the code in this example to fix the behaviour
There is one problem.
Not every matrix can be decomposed in its original part, and there is nothing we can do about it.
