### ISSUE TITLE
Odd height / width canvas blurs centered images

### ISSUE THREAD

**Issue by psynnott** [kangax/fabric.js#1350]
Fabric Version: 1.4.6 (edge) (commit 53bf9d3213b03da05745ea6a09c72e8b29af874c)
Fiddle: http://jsfiddle.net/psynnott/5xhk3/
(Hit start and watch the image blur)

What I did:
- Create canvas width 401, height 401
- Add image (non-selectable)
- Create a cropping guide (draggable) 
- Use .toDataURL using cropping guide to obtain width, height, left, top properties

What I expected:
- Image obtained through .toDataURL is the exact image within the cropping area

What happened:
- Image was seen to be blurred after several edits/saves.

Workaround:
- Set canvas width to even dimensions (e.g. 400 x 400)

Investigation:
- It appears to be a combination of using .center() on an image placed on a canvas with odd x/y, then using .toDataURL to obtain a cropped image.  .center() appears to divide by 2, but not round up or down.  Either Fabric or the canvas element is then blurring the image to make up for this half a pixel remainder on an odd-dimension canvas.

**Comment by asturur** [comment]
This bug was relative to imageSmoothingEnable resetting after setting canvas width or height.
With current 1.6, if imageSmoothingEnable is false, the image does not blur regardless of odd/ even.
With imageSmoogthingEnable true, it blurs.

**Comment by psynnott** [comment]
Hi asturur,

Unfortunately I am able to replicate it in 1.6.0-rc.1 (current version on github)

I have updated the fabric.js file referenced by the jsfiddle in my bug report.  URL for convenience is 
http://jsfiddle.net/psynnott/5xhk3/

As you can see, I have imageSmoothingEnable set to false.

**Comment by asturur** [comment]
http://jsfiddle.net/5xhk3/4/

check a version with latest version built from sources.
Fix is younger than latest build.

I changed jpg to png so we do not confuse also jpg blurring from canvas blurring.

My server will prompt you for security alerts, please accept the certificate.

**Comment by psynnott** [comment]
Hi asturur,

Thanks for the speedy reply.  I opened http://jsfiddle.net/5xhk3/4/ and ran the demo.  The image is not blurring, however it is losing 1 pixel off the width and 1 pixel off the height per save.

Granted, this takes many saves to heavily impact the image, but there is still a problem when an odd width+height are used.  Even odd/height do not have the lost pixels issue.

**Comment by asturur** [comment]
I do not think there is a way of exporting half pixel.
If you divide something odd by 2, you round up or down.

**Comment by psynnott** [comment]
I agree - it is impossible to export half a pixel.  

However, I wonder if there is a way for Fabric to determine the canvas size is not an even number upon initialisation and recreate the canvas 1 pixel smaller (width and/or height as necessary).  Just a thought.

I still believe Fabric should handle this rounding issue internally.

**Comment by psynnott** [comment]
Any updates on this?  Has it been fixed as it has been labelled as a bug, yet it is marked as closed?

**Comment by sumit3sep** [comment]
I have to blur part of the image on click event and wants to implement functionality in such a manner during mouse move the part of the image make blur.
Could not understand how should I proceed? Please help me out of thisl
