### ISSUE TITLE
Segmentation Fault when accessing image from site with htpasswd - using Node.js

### ISSUE THREAD

**Issue by samdoidge** [kangax/fabric.js#1355]
Lost a bit of time debugging this. An incorrect URL for an image when using loadFromJSON with Node JS will throw an error you can trace, an url on a site using htpasswd gives Segmentation Fault D:

**Comment by heijmerikx** [comment]
This is probably correct. I also experience segmentation faults when trying to reference AWS S3 images which are not accessible.
