### ISSUE TITLE
Problems free drawing on canvas after I add an image

### ISSUE THREAD

**Issue by theappdeveloper** [kangax/fabric.js#1382]
I am trying to use the camera to add an image to the canvas on an app that I have built using Phonegap and fabric.js.

This works, in so much as that it adds the image onto the screen. I have then managed to save it to the database and can re-display it after.

function onPhotoURISuccessCanvas(imageURI){

  var canvas = new fabric.Canvas('cx0'); 
  canvas.setDimensions({width: 400, height: 600});

 fabric.Image.fromURL(imageURI, function(img) {
canvas.insertAt(img.set({ left: 400, top: 0, angle: 90, lockMovementX:true, lockMovementY: true,lockScaling: true, LockRotation:
true,selectable: false,isDrawingMode: true}).scale(0.25)),0; });

//this is the call to show the images
thisImage = serializeCanvasByIDx();

}

function serializeCanvasByIDx() {
    var canvas = document.getElementById('cx0');
    var serializedVal = 'data:,';
    if (canvas.toDataURL) serializedVal = canvas.toDataURL(); 
    return serializedVal;
    } 

I now want to be able to enable freedrawing so that I can sketch over the image

    function deviceReady() {

    var canvas = new fabric.Canvas('cx0');
    canvas.setDimensions({width: 400, height: 600});
    var mode = document.getElementById('drawing-mode');

    mode.onclick = function() {
    canvas.isDrawingMode = !canvas.isDrawingMode;
    if (canvas.isDrawingMode) {
        mode.innerHTML = 'Enter edit mode';
    }
    else {
        mode.innerHTML = 'Enter draw mode';
    }
 };

    canvas.freeDrawingBrush = new fabric['PencilBrush'](canvas);
    canvas.freeDrawingBrush.color = 'Black';
    canvas.freeDrawingBrush.width = 4;

}
Drawing mode enables but as soon as i sketch, the image I added dissappears, I have tried quite a few different techniques, but can't see where I am going wrong.

All ideas appreciated. Thanks

**Comment by asturur** [comment]
https://jsfiddle.net/asturur/9ocer5cm/1/

it works fine.
If it should be any problem we can still re open it.

**Comment by mossen** [comment]
@kangax can you check the jsfiddle @asturur provided? try to draw lines.

**Comment by asturur** [comment]
the current linked fabric version has a bug on freedrawing that has been
fixed but not pushed out yet

**Comment by mossen** [comment]
@asturur Thanks for your reply. Is there any way to get the version or patch as soon as possible as I am using it in a project I need it urgently.

**Comment by asturur** [comment]
can t you build it from here?

**Comment by RMTY** [comment]
@asturur Even if this bug is fixed on the code, I guess there are still some under-development features and build it and use it could cause some new issues, isn't?

I guess we should wait for a new release, imho.

**Comment by asturur** [comment]
@RMTY i m sure 2.0.0 will be bugged. i ll mark as a release as soon as i m sure i have not to change api later and who has to transition from 1.x has all the tools.

I have no many other ways to fix bugs if people do not find them. I find some, not all.

**Comment by janoonaj** [comment]
@asturur (I'm RMTY, with a different account).

Sorry, for your message written one week ago I understood it was already fixed but not pushed. So I though it would be fixed on next release. I understand that's not the case.

thanks

**Comment by asturur** [comment]
should be ok on fabricjs.com/kitchensink.

isn it?

**Comment by panthar1** [comment]
Hello,

Here is a jsfiddle https://jsfiddle.net/t2mgy7dr/ that demonstrates the issue. It seems to be an issue with fabric events. having to do with free draw The issue is, that when you change the freeDrawingBrush (or the drawing mode for that matter), within the MouseDown event function, the freeDrawingMode/freeDrawingBrush does not get updated on the current path your drawing, until the MouseUp event occurs.

This essentially means, that it's using the old freeDrawingBrush, until the mouseUp happens, and when it does occur, the path gets updated with proper values. Pretty sure now that I know what's going on, I can hack together a fix in my code, but, this is not expected behavior.

**Comment by asturur** [comment]
This fiddle is unrelated. can you open a issue for it?

**Comment by panthar1** [comment]
Sorry my bad, created a new issue for it instead. Thought that might of been the cause of his imaging going blank, guess not.
