### ISSUE TITLE
hoverCursor on selectable:false

### ISSUE THREAD

**Issue by Tilogorn** [kangax/fabric.js#1392]
When setting 'selectable:false' to an object, the property hoverCursor doesn't have anymore influence. Is that intended? Mouseover-Events are still fired. Seems illogical for me (in most cases, you won't need a hoverCursor on non-selectable elements, but at least you could have the choice).

http://jsfiddle.net/4qcAL/

**Comment by wriahi** [comment]
I have selectable = false and objets should link to another page, so I need to set hoverCursor = pointer on a mouseover event.
Is there a way around this?

**Comment by cmnt** [comment]
I Agree.  I also made buttons !

**Comment by asturur** [comment]
yes non selectable but clickable events should be considered as an option

**Comment by jamescram** [comment]
It looks like this was reverted without any discussion in issue #3634. I have the same reason for needing this feature as other commenters on this issue - namely creating "buttons" on a fabric.js canvas that should show a pointer icon on hover, but should not be selectable/editable.

Perhaps this should be made an option, since it seems both behaviours are desirable in different circumstances?

**Comment by asturur** [comment]
i think there is a way to change cursor on hover with selectable false. let me check.

**Comment by maxhudson** [comment]
@asturur This is causing issues for me as well - it does not work in this example:

```
fabricObject.set({
        selectable: false,
        hoverCursor: 'pointer'
});
```

**Comment by tscislo-lingaro** [comment]
Same for me. Only setting selectable to true, which is not what I need allows me to change the cursor type...

**Comment by tscislo-lingaro** [comment]
There is a workaround to have a cursor pointer and not interactive element with those props:

           selectable: true,
            lockMovementY: true,
            lockMovementX: true,
            hasBorders: false,
            hasControls: false,
            hoverCursor: 'pointer',

**Comment by SoLoGHoST** [comment]
This does not work.  Have tried this on objects and cursor still does not show.

**Comment by mt404** [comment]
Seems a bit presumptuous to dictate what cursors people can can't use in certain situations.  

No Cursor for you!

With great power comes great responsibility.  yada yada.  Let us choose to make bad design choices if we want to.  You're not the boss of my cursor.  I am.

**Comment by asturur** [comment]
@mt404  i m not sure what was the message you wanted to give to us.

I may have done bad decisions building features for fabricJS. This issues is from 2017 and i m not sure what is the current situation.

The whole controls/cursors are under rewriting with a more permissive model

**Comment by codingenvy** [comment]
As a follow-up to tscislo-lingaro's excellent solution: if you would like to have the default hoverCursor back just set hoverCursor: '' (i.e. empty string)

**Comment by whatisor** [comment]
Hi,
This is a bad suggestion. Because it keeps searching non-selectable object while mouse moving.
Such as we have gird objects, it is bad performance.

**Comment by asturur** [comment]
The objects needs either to be skipped or not skipped, won't change that much.
You can set them as evented: false if you want to skip them entirely

**Comment by whatisor** [comment]
Yeah, I found that option while finding solution, it works well.
