### ISSUE TITLE
API to set the css dimensions of the canvas elements without changing the element height/width

### ISSUE THREAD

**Issue by Bnaya** [kangax/fabric.js#1395]
I want to be able to set different values for the canvas element width & height properties and the css width & height.

 You can see it in action here:
http://jsfiddle.net/Bnaya/4TP9Q/

Just need to find a better api for that and if its breaks functionalities.

I've closed #1393 , it was not clear and not good as a PR

**Comment by asturur** [comment]
we have this now on setDimensions. I do not remember when it has been introduced
