### ISSUE TITLE
[DOCS] object coordinates are switched to center origin when doing scaling or rotating.

### ISSUE THREAD

**Issue by thomasf1** [kangax/fabric.js#1409]
When rotating a group in fabric.js, the .left and .top values of the group "jump". Is that a fabric.js bug or somehow explainable/intended?

```
group.on "moving", ->
    #Yields values of about 100 px, also after the group was rotated

group.on "rotating", ->
    #Yields values of about 130 px
```

JSFiddle -> http://jsfiddle.net/thomasf1/X76X9/2/
##

**Comment by asturur** [comment]
I think that during rotation the group is originated in the center.
http://jsfiddle.net/ZSk74/2/

**Comment by KJTsanaktsidis** [comment]
yup, @asturur is right, this is also the case for scaling objects too it would appear. If you actually want to know the top left hand corner of the object, use `object.getPointByOrigin('left', 'top')`

**Comment by asturur** [comment]
So is confirmed, not really a bug not an issue....
More another documentation issue.
