### ISSUE TITLE
Preselected IText can't be copied

### ISSUE THREAD

**Issue by Tilogorn** [kangax/fabric.js#1428]
Programmatically selected IText (i.e. on page load) can't be copied via Strg-C.

http://jsfiddle.net/p8udu/

It surely is a problem of the focus.

**Comment by Kitanotori** [comment]
Copy and paste not working here either. Still no solution after almost 2 years?

**Comment by asturur** [comment]
I do not know what is stopping you crom copying.
fabricjs can copy from system clipboard fine, at least on mac and windows. If you have any other failing case report it precisely.

If you want to copy/paste "programmatically" use ".getSelectedText()" and put it in your system clipboard using js. If  you need to copypaste with ctrl+c be sure to have the focus on the hiddenTextArea of iText/textBox.
When calling "enterEditing" it should do automatically
I updated the fiddle with latest version.

http://jsfiddle.net/p8udu/6/
