### ISSUE TITLE
Group selection using mouse drag not working over top nonselectable objects

### ISSUE THREAD

**Issue by nexttech** [kangax/fabric.js#1506]
When attempting to group select objects by dragging the mouse, if the starting point is over top of a unselectable object then the group selection box is not even initiated.

This is a bug that came somewhere between version 1.4.7 & 1.4.8

It can be easily verified here: http://fabricjs.com/customization/ 
Under "Unselectable object" example
##

**Comment by jhundley9109** [comment]
I am also running into this issue. Dragging and making an empty selection makes group selection starting on the unselectable object not possible.

As mentioned before, go to http://fabricjs.com/customization/
Then under unselectable, make an empty selection, and then begin your selection on the unselectable object. It does not have expected results.

**Comment by asturur** [comment]
@kangax, should the selection start if we are starting from the unselectable area?
Which is the desired behaviour?

**Comment by jhundley9109** [comment]
I would like to implement something along the lines as seen in this fiddle. This is not my fiddle, I just found it among searches... Starting the selection in the rectangle only works if you select an active object and then click in the square.

http://jsfiddle.net/PromInc/ZxYCP/

This bug is apparent in this example as well. With the way it is now, I would not be able to do a solution like this. Is there a workaround possibly?

**Comment by kangax** [comment]
> @kangax, should the selection start if we are starting from the unselectable area?
I think it should. It just shouldn't affect unselectable object, obviously, but might affect others.

**Comment by asturur** [comment]
gonna check it.

**Comment by gandhimaulik** [comment]
is this fixed yet ?
I also have experienced same issue.

**Comment by asturur** [comment]
_shouldClearSelection: function (e, target) {
            var activeGroup = this.getActiveGroup(),
                activeObject = this.getActiveObject();

            return (
            !target
            ||
            (target &&
            activeGroup &&
            !activeGroup.contains(target) &&
            activeGroup !== target &&
            !e.shiftKey)
            ||
            (target && !target.evented)
            ||
            (target &&
            !target.selectable) // also return true if the target is present but non selectable
            ||
            (activeObject &&
            activeObject !== target)
            );
        }

**Comment by asturur** [comment]
i need to fix it for my own things. so the time has come!
