### ISSUE TITLE
Rotation controll can be and corner

### ISSUE THREAD

**Issue by dmitrirussu** [kangax/fabric.js#1539]
Sorry, I want to use [tr] instead of [mtr]. I want to do disable of [mtr] and to be posible to choose [tr] or [mr] after that to be posisble to put a image as rotation controller, or to be default simple circle. 
Can be improved some thing?

**Comment by jeffkillian** [comment]
I'm not sure where to comment this, but I'm encountering this issue as well, and would love to see corner rotation implemented.

**Comment by seekshiva** [comment]
I would love to have this feature too!

**Comment by asturur** [comment]
so put a +1 here: https://github.com/kangax/fabric.js/issues/1947

**Comment by asturur** [comment]
duplicate of #1947
