### ISSUE TITLE
Width animation bug

### ISSUE THREAD

**Issue by ehallstr** [kangax/fabric.js#1562]
http://jsfiddle.net/jDP84/3/

1. Resize the rectangle's width slightly, it will be animated to 100px width. 

2. Try to resize it again, the width change, but it will not be animated back to 100px. It does still think the rectangle is 100px wide.

**Comment by asturur** [comment]
http://jsfiddle.net/jDP84/6/

This is a misunderstaing of scaling versus changing width.
If you resize it the rect goes from 50 to 100. Then is 100 wide, no matter how much you scale it.
It will be wide 100 with a scaleX factor of 20 , getting 2000 pixel on the screen, but always the width property is 100.
