### ISSUE TITLE
IText cursor positioning not in sync with hidden textarea's

### ISSUE THREAD

**Issue by mochidusk** [kangax/fabric.js#1581]
To recreate the problem:

1. Move the hidden IText's textarea to a visible part of the screen to see it's cursor.
2. Type out Lorem ipsum dolor sit amet in the IText's box.
3. Move the cursor up. The cursor in the textarea is now at the 'm' in Lorem, but the Itext's cursor is at the beginning of the sentence. Although this would be the correct expected behavior for both cursors relative to their environment, they are now out of sync.
4. Type in a word. The text in the IText's box is now at the textarea's cursor location. 

![1](https://cloud.githubusercontent.com/assets/6126638/3864712/8cf12fc2-1f67-11e4-92b9-c3b4134c0f72.png)

![2](https://cloud.githubusercontent.com/assets/6126638/3864713/94e7c916-1f67-11e4-905d-085617ef408b.png)

![3](https://cloud.githubusercontent.com/assets/6126638/3864714/9843ee28-1f67-11e4-8553-245176813929.png)

Actual text being typed is displayed relative to the textarea's cursor and not IText's cursor, which is fine but to the end user typing into the IText's box it appears as if the cursor jumps out of position. 

A temporary quick fix is to set the hidden textarea's width and height to be the same as when defining the IText's width and height. But this forces font size of the IText to be same as the hidden textarea's which would be impractical. 

I'm implementing text wrapping and adjustable textbox width/height for my app but haven't been able to find a viable solution to syncing the cursors..

**Comment by asturur** [comment]
taking care of it in #1872

**Comment by asturur** [comment]
closed via #1872.
