### ISSUE TITLE
Weird coordinates after rotating, and checking object:modified

### ISSUE THREAD

**Issue by walliski** [kangax/fabric.js#1587]
Hi

http://jsfiddle.net/Walliski/c6mcbtvx/

To reproduce:

1. Move rectangle to see coordinates in developer console (move by 1-2 px)
2. Rotate to see new weird coordinates, (1-2º is enough)
3. Move again 1-2 px, and new coordinates...

in step #2, the coordinates are set from middle of the rectangle, instead of being from the top left corner as otherwise.

Is this intended behavior, or is it a bug? Anyone else that got a similar issue, and know a workaround? Or should I use anything else than object:modified for capturing info on changed objects (size, angle and coordinates)?

**Comment by asturur** [comment]
Use object property:
```centeredRotation: false```
to rotate around top left corner and not having coordinates bumping.
