### ISSUE TITLE
Canvas parent animate : incorrect values

### ISSUE THREAD

**Issue by Arioch171** [kangax/fabric.js#1596]
I've implemented a "scrolling" function for my project.
Basically I use jQuery's animate function to scroll my div which is containing a canvas element.
Everything worked just fine until fabric.js 1.4.10 version.

Expected behavior (1.4.9): http://jsfiddle.net/ehjcn3h8/2/
Behavior in 1.4.10 : http://jsfiddle.net/p8co7vat/2/

Thank you.

**Comment by asturur** [comment]
jsfiddle.net/p8co7vat/2

later but better than nothing. the fiddle was just bad made.
removed oldmovx/y from code and it works smooth.
