### ISSUE TITLE
Text distorted when scaling (Ubuntu)

### ISSUE THREAD

**Issue by Wexcode** [kangax/fabric.js#1599]
I'd like to use a `fabric.Group` element to scale all of the objects on my canvas, but I'm running into an issue with `fabric.Text` when I apply the scale to the group.

In short:

    text = new fabric.Text('foo', {
        fontSize: 10,
        left: 100,
        top: 10
    });

produces something different than this:

    text = new fabric.Text('foo', {
        fontSize: 1,
        scaleX: 10,
        scaleY: 10,
        left: 100,
        top: 10
    });

![fabricjs](https://cloud.githubusercontent.com/assets/698259/3945114/edb07a08-262d-11e4-9fc0-f9f2ead080f8.png)

See for yourself: http://jsfiddle.net/Wexcode/y7kLzj78/

I originally [asked this question on StackOverflow](http://stackoverflow.com/questions/25346704/scaled-text-distorted-when-using-scale-in-fabric-js-ubuntu), but I just discovered that the issue is actually not reproducible on my iPhone (Chrome), but it is on my computer (Chrome) - so I think it's a bug.

**Comment by asturur** [comment]
No they should not look identical.
I would not define this as a bug.
