### ISSUE TITLE
Callback function not call when cloning object

### ISSUE THREAD

**Issue by anhle82** [kangax/fabric.js#1629]
Hello,

First of all, awesome library :+1: 

I ran into a little problem, seem like callback function is not called when cloning text object. Please take a look at jsfiddle http://jsfiddle.net/p0L4xfmx/

On the other hand, callback function executed correctly when cloning an image object.

Did I implement it wrong? Thanks

**Comment by Aubron** [comment]
Just providing feedback here, this also stumped another developer using fabric.js for a light implementation today. I feel like a line in the documentation at least might help this become a little less of a stumbling point.

@ Other Developers running into this via google, http://stackoverflow.com/a/18267515 will give you a potential solution, or at least put you down the right path.
