### ISSUE TITLE
performance issue in all browser

### ISSUE THREAD

**Issue by harish19** [kangax/fabric.js#1659]
If we use bigger canvas(8000*5000). Objects rendering very slowly.
find link here
http://jsfiddle.net/Q3TMA/544/
just zoom in 5 to 6 times and try to move objects it will render very slowly.

**Comment by asturur** [comment]
on a 2d context, 40M Pixel will be slow if we do clearRect of entier canvas every time.
This is closed untill we implement dirtyrects OR webgl.
