### ISSUE TITLE
ActiveGroup of groups selection bug.

### ISSUE THREAD

**Issue by spearson2010** [kangax/fabric.js#1685]
See JSFiddle:  http://jsfiddle.net/rV79j/5/

I have four shapes on the canvas, two rectanges added directly to the canvas (in a reddish hue), and two rectangles each within their own group added to the canvas (in orange).

If you drag a selection box around the two orange individually grouped rectangles, the shapes look to be correctly grouped and bound, but if you move your mouse over the top left corner of the canvas you'll notice the 4-way arrow mouse cursor and if you click and drag you will move the right orange rectange of the active group.

If you do the exact same thing to the red rectangles you do not get this result.

Am I missing something, or is this a bug?

Thanks
- Steve

**Comment by asturur** [comment]
http://jsfiddle.net/rV79j/8/
I updated the fiddle con latest 1.5.0 and this problem is not happening anymore.
Shift click to deselect does not work anyway, but is unrelated.

@kangax i would close it.
