### ISSUE TITLE
IText cursor position off for certain fonts

### ISSUE THREAD

**Issue by jafferhaider** [kangax/fabric.js#1709]
The cursor moves to the left/right of the actual place where characters are added. This only seems to happen for certain fonts and certain characters.

To recreate:
1. Go to http://fabricjs.com/kitchensink
2. Select an IText and select the **Plaster** font
3. Type different characters and notice difference between where cursor is rendered and where new characters are added.

Doesn't seem to be effected by scale. Seems to be worse on Chrome OSX than Chrome Windows.

**Comment by asturur** [comment]
If you disable caching for itext, the issue goes away. So this is confirmed as a BUG. Same bug of doing operation on fonts that are not yet loaded.

**Comment by erlik28** [comment]
Hi guys, I'm getting this issue after loading the canvas object from a json string with loadFromJSON.

**Comment by jafferhaider** [comment]
If simply using a web font loader isn't working for you, try adding a DOM element with the font family (after you've loaded the font with a loader) inside the DOM before using it in the Canvas tag. Helped in my case.

**Comment by erlik28** [comment]
Thanks for the suggestion, that's exactly what I'm doing, but from what I debugged the width property of the IText object is smaller after loading from a json string. It's like it recalculates the width based on a different font. I set the cache property to false on the object but it doesn't seem to help.

**Comment by matheusczi** [comment]
erlik28, how did u solve this problem?

**Comment by asturur** [comment]
refer to #2612
