### ISSUE TITLE
Issue with control box

### ISSUE THREAD

**Issue by kangax** [kangax/fabric.js#1711]
Just noticed this on http://fabricjs.com front page:

![screenshot 2014-09-29 17 37 02](https://cloud.githubusercontent.com/assets/383/4444735/2ced3062-47f3-11e4-9664-7a749c10d6d4.png)

/cc @asturur

**Comment by asturur** [comment]
i will try to flag the pathgroup parsed with some flag that means:
width and height has to be determined.
Then at the end of parsing i will calculate width and height and apply to pathgroup.
is this ok?

**Comment by kangax** [comment]
Sounds good
