### ISSUE TITLE
loadFromJSON with Pattern only shows black - jsfiddle included

### ISSUE THREAD

**Issue by samdoidge** [kangax/fabric.js#1726]
How can I resolve this issue? : [JSFIDDLE](http://jsfiddle.net/d9ghqe5q/15/)

Thanks

**Comment by asturur** [comment]
We can solve this.
Here there are 1 missing feature and one long standing bug.

The missing feature is that we do not export to object the pattern source when element is an object ( canvas element in this case )

The long standing bug is that, once we solve the above, we are missing a real load async method for json. So it will load black but then as you click on it everything will be fine.

Of course cors and security madness kills any jsfiddle i tryed to do.

check this:
http://www.deltalink.it/andreab/fabric/asd.html
