### ISSUE TITLE
Group ignores Text positioning with explicitly set positioning / origin

### ISSUE THREAD

**Issue by mkMoSs** [kangax/fabric.js#1729]
As per this example: http://jsfiddle.net/1ow02gea/5/

Having a fabric.Text in a fabric.Group that both have set their left, top options and originX/Y to left/top explicitly, the text is centered within that Group which is definitely an unwanted/unexpected behavior.
The tutorial (http://fabricjs.com/fabric-intro-part-3/#groups) states that setting left and top options would override the default center-all behavior, which doesn't work for text.
This makes grouping texts virtually unusable. And weird things happen when grouping multiple texts

**Comment by asturur** [comment]
@kangax 
check this
https://github.com/kangax/fabricjs.com/pull/69

And please tell me where in the source code we should link this new demo/test
