### ISSUE TITLE
Onscreen keyboard doesn't enter text into IText on Android

### ISSUE THREAD

**Issue by kenrett** [kangax/fabric.js#1747]
I tried this with both the stock browser and Chrome. Seems to be an issue with android itself... Darbs commented on another issue that android doesn't support keypress events, which is why it doesn't work, but I have not checked this myself.

**Comment by eric-schleicher** [comment]
confirmed....  chrome on my note2 also does not pull up.

**Comment by taozhan2014** [comment]
We are facing the same problem. Itext doesn't show the text entered by onscreen keyboard. External keyboard works fine. (Fabric.js v1.4.13 + Android v. 4.4.2 + chrome v. 41.0.2272.96).

Our app needs to run in android + chrome stack. Is there any plan to fix this issue in future release of fabric.js?

BTW fabric.js is awesome and save us a huge work on developing canvas related UI by ourselves.

Thanks,

Tao

**Comment by asturur** [comment]
can you try here?

www.deltalink.it/andreab/fabric/kitchensink.html

i think is fixed.

**Comment by asturur** [comment]
oh no, it does not work. but it was working again some builds ago... :(
i m on android 5.0.2

**Comment by taozhan2014** [comment]
I tried http://fabricjs.com/test/misc/itext.html as well, and it doesn't work.

**Comment by asturur** [comment]
consider there is a fix, it will be taken again on development as soon as 1.5.0 is out.

there is some thread for it, search "accent language" in the issues. you ll find it and subscribe it so you will be notified when things start to move again

**Comment by taozhan2014** [comment]
Cool, Thanks. I will watch it out.
