### ISSUE TITLE
Selection handles for group remain

### ISSUE THREAD

**Issue by kirschkern** [kangax/fabric.js#1751]
The selection handles for a selected group remain when moving the selection to front on select event.
See: http://jsfiddle.net/d5vb7op9/

**Comment by asturur** [comment]
Still happening with 1.5.0

**Comment by sapics** [comment]
canvas objects has not event.target.
Therefore, I guess that http://jsfiddle.net/sapics/d5vb7op9/6/ would be ok.

**Comment by asturur** [comment]
ok now i see more clearly.
So is an application problem.
@sapics thanks you so much again.

**Comment by sapics** [comment]
Welcome! (dou itashimashite) :)
