### ISSUE TITLE
iText range letters with same style

### ISSUE THREAD

**Issue by prodes** [kangax/fabric.js#1777]
Hi people,

iText is a real great feature in Fabric.JS! We like it a lot. 
There is only one thing i think would improve a lot. 

Fabric is adding a style for every letter that has a specific style. 
We use FabricJS for people creating cards with text so if someone selects a whole paragraph with 600 and sets a style for it we have 600 keys added in the object. I think it would be much smarter to add 1 key to the object with a range. 

For example this text: 
Th<style="font-family: "strangefont; font-size: 13.3334;">is is a text</style>  

In the current FabricJS style would become:
"2": {
                        "fontSize": "13.3334",
                        "fontFamily": "strangefont",
                        "fill": "#4a4a4a"
                    },
                    "3": {
                        "fontSize": "13.3334",
                        "fontFamily": "strangefont",
                        "fill": "#4a4a4a"
                    },
                    "4": {
                        "fontSize": "13.3334",
                        "fontFamily": "strangefont",
                        "fill": "#4a4a4a"
                    },
                    "5": {
                        "fontSize": "13.3334",
                        "fontFamily": "strangefont",
                        "fill": "#4a4a4a"
                    },
                    "6": {
                        "fontSize": "13.3334",
                        "fontFamily": "strangefont",
                        "fill": "#4a4a4a"
                    },
                    "7": {
                        "fontSize": "13.3334",
                        "fontFamily": "strangefont",
                        "fill": "#4a4a4a"
                    },

In my idea it would become:
 "2": {
                        "fontSize": "13.3334",
                        "fontFamily": "strangefont",
                        "fill": "#4a4a4a"
                        "untill": 7
                    },

Hope you like this plan! 
It would solve a lot for us! 
##

**Comment by asturur** [comment]
almost 3 year after i m gonna close this issue.
The new text code has some sort of optimization for style, it keeps it clean.
It does not come in ranges but it can be kept smaller.
