### ISSUE TITLE
Rotation and dragging causing freezes on chrome mobile 38 and Android 4.4.4

### ISSUE THREAD

**Issue by flodev** [kangax/fabric.js#1784]
Open http://fabricjs.com/freedrawing/
Draw something in free drawing mode.
Cancel drawing mode.
Drag the brush around until the browser freezes. I guess its a memory leak but just guessing.
Tried with fabric 1.4.11 and 1.4.12.
##

**Comment by asturur** [comment]
closing this.
We do not really have this kind of support for mobile browsers.
