### ISSUE TITLE
lineHeight should not be applied to the first line

### ISSUE THREAD

**Issue by jafferhaider** [kangax/fabric.js#1814]
According to the [proper typography definition](http://en.wikipedia.org/wiki/Leading) of line height, it is the distance between baselines of successive lines of text. This means that the first line in a Text item shouldn't have any offset from the top. Only successive lines should change their Y axis position. This is how it is implemented in most word processing applications and Textbox controls.

This is not the case in the current codebase. The first line gets shifted down if you increase lineHeight. 

## Suggested fix
The fix is a simple tweak in how `_getHeightOfLine` in `itext.class.js` returns:
```
  if(lineIndex > 0) {
    return maxHeight * this.lineHeight
  }
  return maxHeight;
```

Should I create a pull request?

**Comment by fahadnabbasi** [comment]
@jafferhaider I know the default beahviour is not to apply lineHeight on first element but if I wanted to, how can I do that?

**Comment by fahadnabbasi** [comment]
@asturur Andrea? Any help would really be appreciated, I asked the question on stackoverflow as well

https://stackoverflow.com/questions/45381310/fabricjs-text-with-uniform-lineheight-for-each-line
