### ISSUE TITLE
toDataURL() for OverlayImage throws SecurityError on iOS

### ISSUE THREAD

**Issue by mobidev111** [kangax/fabric.js#1836]
A canvas with solely an overlay image throws a Security Exception when creating a snapshot with toDataURL - only on iOS7.

```javascript
        canvas.setOverlayImage('img/test.svg',
            function() {
                canvas.renderAll.bind(canvas);
                var canvas_snapshot = canvas.toDataURL('image/png');
                console.log(canvas_snapshot);
            }, {
                crossOrigin: ''
            });
```

```
[Error] SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.
	__toDataURL (fabric_.js, line 12590)
	toDataURL (fabric_lib.js, line 12570)
```

This bug occurs on Apple iOS7.
The code however works on Apple iOS8, Chrome & Safari Desktop. 

Problem: iOS7 acounts still for 50% of all Apple devices for the foreseeable future.

This means, I cannot use overlay images on mobile.

Do you know how to work around this?

**Comment by asturur** [comment]
Updating to fabricJS 1.5.0 solved
