### ISSUE TITLE
Extern for Closure Compiler

### ISSUE THREAD

**Issue by tinussky** [kangax/fabric.js#1837]
When compiling your application with google's closure compiler with --compilation_level=ADVANCED a "extern" is needed to prevent the compiler from renaming fabricjs functions, variable, object names and such.

Creating an extern is not quite difficult, but a lot of work (mostly trail and error based). It might be a nice extra feature (if you can somehow automate it, managing this by hand might be a bit over the top) to have a ready made & downloadable extern for fabricjs.

There are already many externs for different libraries:
https://github.com/google/closure-compiler/tree/master/contrib/externs
and more to be found on google.
##

**Comment by joshpearce** [comment]
Closure Compiler, in advanced mode, will leave out the parts of JavaScript files which are not used by the application, or so they claim. The fabric build script let's the developer do this quite nicely, but there is an extern available for fabric already. The ClojureScript people have a bunch of them wrapped up in their own version of an external dependency reference. Here:

https://github.com/cljsjs/packages/blob/master/fabric/resources/cljsjs/fabric/common/fabric.ext.js

**Comment by asturur** [comment]
To me the ext.js looks like just a compy of the lib with no code.
Is this right? While it may be obtained using some for loop, toString and regexp.

I wonder:
What if the user add it's on properties on the objects?
What if we just give fabric.js as the extern for closure compiler?
