### ISSUE TITLE
Selection handles on newly created group leave the contained objects behind when moved

### ISSUE THREAD

**Issue by nitinforgithub** [kangax/fabric.js#1840]
Following code creates three paths and makes a Group out of them which is set active. When rendered the group has selection handles and can be moved around as expected. If we click anywhere else on the canvas and then try to move the group again -  only the selection handles move and not the actual objects. This behavior is observed in fabric.js. 1.4.0 thru latest version.

<html>
<body>

	<canvas id="fabric-canvas" width=800 height=350></canvas>

	<script type="text/javascript">

		
		var canvas = new fabric.Canvas('fabric-canvas');
		
		var myObjects = [];
		
		var path1 = new fabric.Path('M 0 0 L 40 0 L 40 40 L 25 40 M 0 0 L 0 10');
		path1.set({strokeWidth: 3, stroke: '#555', fill:null, strokeLineCap: 'round' });
		path1.set({top:100, left:150, angle:0});
		myObjects.push(path1);
		
		path1.clone(function(clonedObj){
			clonedObj.top=150;
			myObjects.push(clonedObj);
		});
		
		path1.clone(function(clonedObj){
			clonedObj.left=250;
			myObjects.push(clonedObj);
		});
		
		
		var myGroup = new fabric.Group(myObjects);
		myGroup.set('active',true);
		
		canvas.add(myGroup);
		canvas.setActiveGroup(myGroup);

	</script>

	
</body>
</html>

**Comment by asturur** [comment]
https://jsfiddle.net/5fthvew5/

This is the fiddle with your code changed.
```diff
    var myGroup = new fabric.Group(myObjects);
-    myGroup.set('active',true);

    canvas.add(myGroup);
-   canvas.setActiveGroup(myGroup);
+   canvas.setActiveObject(myGroup);
```

With this code it works as expected.
