### ISSUE TITLE
clipTo is not working on Android

### ISSUE THREAD

**Issue by mk-90ED** [kangax/fabric.js#1850]
hi, i am using Fabric.js for clipping with a SVG path. It'w working fine in all desktop browsers, even in Chrome for iPhone and Safari. But i could not make it work in Android. I could see the SVG path but not the clipped image. I just see the black mask

I entered to the examples site of Fabric.js from the device, to ensure that it was not my app, and i could not see the clipping example working.

i am using this CDN version:

http://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.4.0/fabric.min.js

any ideas?

**Comment by jagi** [comment]
Maybe post your `clipTo` function code here. I was checking https://developer.mozilla.org/samples/canvas-tutorial/6_2_canvas_clipping.html and it works on Android 4.4 in different browsers. What version of Android do you have?

**Comment by jagi** [comment]
I've checked clipTo on Android 4.4 with Fabric 1.4.13 and everything works as it should. Try this example http://fiddle.jshell.net/Jagi/efmbrm4v/1/show/

**Comment by asturur** [comment]
@mk-90ED if it is still reproducible, ping here, i will reopen the issue ( and actually investigate that )
