### ISSUE TITLE
free drawing path is not saved correctly after dragging it on canvas

### ISSUE THREAD

**Issue by shareit** [kangax/fabric.js#1853]
Here are the steps used to reproduce the issue on fabricjs.com/kitchensink/ demo web site:
1. create a free path
2. dragging it anywhere in the canvas
3. export the SVG with console.log(canvas.toSVG()) in Execute tab
4. clear the canvas and load the SVG that was exported on previous step

Result: the SVG is displayed on the initial position. 
Expected: the SVG need to be displayed on the position where it was dragged before export.

**Comment by asturur** [comment]
ohhh i found nasty bug. gonna fix it.
