### ISSUE TITLE
Performance issue with a big canvas

### ISSUE THREAD

**Issue by shareit** [kangax/fabric.js#1855]
I have an big image (17126 x 7677) that supports zooming and panning with a third party component.
A fabric canvas is displayed over this image and it is synchronized as size and position with the container of the image. On this canvas the user can draw anything (free drawing). The drawings are also synchronized as size and position with the container of the image. Usually only one drawing is displayed once and the user can choose what drawing wants to see. 
At full zoom, the fabric canvas reaches to the size of 17126 x 7677 and user cannot create a free drawing because the browser responds very slow. No drawing is displayed (or added on canvas with visible = false) in this situation. Also the zooming and panning are working very hard if the canvas is rendered in the page. Without fabric canvas, the panning and zooming works good.
Unfortunately the user can choose the image that is rendered in the page and the system must support images of maxim 4GB, so the image can be bigger than this one.
What solutions do I have ?
Please advice.

**Comment by shareit** [comment]
Hi! To use the image as background I need to load the full image (max 4GB) in a window browser and this is not a solution. I think is not a good idea to load the big image in the browser.
In my case, I have a service that process the image and creates the tiles and the tiles are loaded into window browser using leaflet (http://leafletjs.com).

**Comment by coulix** [comment]
You can not have a smooth canvas at this resolution.

**Comment by shareit** [comment]
I have created a sample for this issue: http://jsfiddle.net/3ap9p3k3/1/.
Please try to draw something in the canvas and the browser window will crash.

**Comment by asturur** [comment]
Firefox survive, chrome crashes.
Is not fabric related issue.

**Comment by jwmao** [comment]
@shareit Have you found a solution for the issue that you had? I'm also having performance issue when canvas size is large.
