### ISSUE TITLE
[node-canvas] Image or Canvas expected on canvas.add(img)

### ISSUE THREAD

**Issue by jagi** [kangax/fabric.js#1871]
Hi, I have problem with Fabric.js with node-canvas probably related to last update. When I try to run such code:

```js
var img = new Image();
img.src = fs.readFileSync('/path/to/file.png');
var canvas = fabric.createCanvasForNode(200, 200);
canvas.add(new fabric.Image(img));
```

I get following error: `TypeError: Image or Canvas expected at at klass.fabric.Image.fabric.util.createClass._render (/home/jagi/workspace/fabric/packages/fabric/.build.fabric/npm/node_modules/fabric/dist/fabric.js:17387:28)`

I was trying to find source of this error. At first I've found that some people had the same [error](https://github.com/Automattic/node-canvas/issues/338). Someone noticed that version of node-canvas didn't work with fabric. But it worked 2 days ago and yesterday suddenly stopped working. I assumed that it was because of update of fabric to version 1.4.13. However I've tried running different versions but without success.

After thorough investigation I've found solution.
This piece of code makes it work:

```js
var createCanvasForNode = fabric.createCanvasForNode;

fabric.createCanvasForNode = function () {
  var canvas = createCanvasForNode.apply(this, arguments);
  canvas.nodeCanvas = new Canvas(canvas.width, canvas.height);
  canvas.contextContainer = canvas.nodeCanvas.getContext('2d');
  return canvas;
};
```

It appears that Canvas created using `fabric.createCanvasForNode` or the context are in the wrong "format".

I have to mention that I'm not using Fabric.js directly in Node.js but as a package for Meteor framework. However it shouldn't be cause of problems.

Do you know what can be source of my problems? I think I didn't make any correction to my code that could influence my fabric code. It worked 2 days ago. I've came back to it and suddenly it doesn't work anymore.

**Comment by jsarafajr** [comment]
Had the same issue. Fixed this by changing node-canvas version to the same version that fabric uses.
