### ISSUE TITLE
toJSON within event handlers breaks groups

### ISSUE THREAD

**Issue by slashgrin** [kangax/fabric.js#1876]
See this fiddle, pointing at fabric.js master:

<http://jsfiddle.net/2yy2t5nw/2/>

- Select both objects as a group
- Rotate the group
- Move the group
- Fiddle to your heart's content

Observe that bad things happen, like objects jumping around when you start to drag them, and the rotation snapping to straight up when moving the objects.

I've also zoomed the canvas, because that makes the effects even more interesting--specifically, the group box doesn't move with the objects properly when you drag it, and rotation goes around the wrong point.

My use case for wanting to do this is that I create complete snapshots of the canvas for undo/redo. (It's perfectly fast enough doing it like that for my needs.)

My current understanding is that the approach of discarding the current group and then recreating it is causing the problem. From `static_canvas.class.js`:

    _toObjectMethod: function (methodName, propertiesToInclude) {

      var activeGroup = this.getActiveGroup();
      if (activeGroup) {
        this.discardActiveGroup();
      }

      var data = {
        objects: this._toObjects(methodName, propertiesToInclude)
      };

      extend(data, this.__serializeBgOverlay());

      fabric.util.populateWithProperties(this, data, propertiesToInclude);

      if (activeGroup) {
        this.setActiveGroup(new fabric.Group(activeGroup.getObjects(), {
          originX: 'center',
          originY: 'center'
        }));
        activeGroup.forEachObject(function(o) {
          o.set('active', true);
        });

        if (this._currentTransform) {
          this._currentTransform.target = this.getActiveGroup();
        }
      }

      return data;
    },

But I'm not familiar enough with the fabric.js codebase to suggest a non-invasive fix if one is possible, or what a better approach to serialising might be that doesn't require discarding and re-creating the active group.

**Comment by slashgrin** [comment]
Howdy, @riaan53 

> The other method im using atm (but unable to get it 100%) is to destroy the active group, read the properties and then add the group back again and make it active. It works nicely except if the group was rotated then the new active group will not be at that angle. If a add the angle to the group then the group is rotated again by that angle. A fiddle to demonstrate the issue as well as my stackoverflow question (with no answer yet :( ).

If I understand correctly, this is essentially what `_toObjectMethod` is doing.

I feel like the current approach to this in Fabric of destroying the group and then trying to fix things up to the state they were in before is inherently trouble-prone, and trying to fix it and make *stay* fixed may be an exercise in chronic frustration.

I'm thinking about putting a bounty on this one if someone's interested in discussing a more permanent and generally-applicable solution to this: e.g. ability to perform certain operations like `toJSON` in a way that "looks through" certain objects like the selected group or another specified group in a way that makes the result appear as though the group/selection didn't exist.

Is this something that the maintainers might be interested in? ( @asturur ? )

**Comment by slashgrin** [comment]
Ok, here we go. These are the requirements that a solution would satisfy in order to claim whatever bounty I end up placing on this:

R1. `canvas.toJSON()` should be a pure function.
---

To clarify, I don't actually care if there is some internal state that gets tweaked in some way for whatever reason, but it should behave as a pure function from the caller's perspective, whether that caller may be a handler for some Fabric event, on a timer, or wherever it may happen to be.

If this is achieved, then my original example (http://jsfiddle.net/2yy2t5nw/2/) should behave exactly the same from the user's perspective whether the line `canvas.toJSON();` is present or removed. Specifically, all permutations of selecting the objects into a group, moving them, rotating them, deselecting them, etc. should be unaffected by the call to `canvas.toJSON()`.

I feel fairly strongly that the best way to do this won't involve creating and destroying groups as is done today, but if a robust solution can be found that still does this, I'm not going to be picky about the details. As far as the bounty is concerned, if it works, it works.

R2.  `canvas.toJSON()` must not be upset by zoom or pan.
---

I believe this only *exacerbates* the main problem, as can be observed in my original example: http://jsfiddle.net/2yy2t5nw/2/. But just to be on the safe side, I'm going to state explicitly that however `canvas.toJSON()` (and its subordinate functions) end up being implemented, they should work just as well whether the canvas is zoomed, panned, or in its default state.

R3. Solution must be accepted and merged by upstream.
---

Solution should be accepted and merged by the maintainers of the main branch at (https://github.com/kangax/fabric.js). Implementor benefits when everyone benefits.

**Comment by slashgrin** [comment]
Feedback on those requirements is welcome and encouraged, especially if I've missed anything important.

Now to figure out how this bug bounty system works!

**Comment by slashgrin** [comment]
@kangax @asturur I had a look into Bountysource, and I can't say I'm too keen on just giving them my money up front and leaving it there for an indefinite amount of time on the off chance that someone might be willing to pick up the bounty.

Is there another way you'd be ok with me posting bounties for this project? E.g. if I were to verify my identity to the maintainers (for everyone's peace of mind), and then deposit the bounty to a successful bounty hunter directly?

**Comment by asturur** [comment]
Hi, @slashgrin , i may be wrong, but this is just a normal bug, and it will be addressed soon or later.

It is not about the prize, nor about the importance of the bug.
We are planning 1.5.0 release, i'm stuck with text problem (mainly because of lack of free time) there are some bugs to address here and there, and even this one.

So do not worry about the bounty now, i don't think any reasonable bounty would make me overcome other priorities now. i just need to sit down in front of computer, finish some things, and i'm sure that then even this bug will be addressed.

cheers
Andrea

**Comment by kangax** [comment]
@slashgrin Jeff, like @asturur said, we're in the process of pushing out version 1.5 (taking care of some long-standing bugs, etc.) so this could be taken a look at after release. As for bounty — it's certainly appreciated — not so much because of money but because of incentive. For example, whichever bounties I close, I "shift reward" towards "site redesign" for potential designer(s) to have more interest in it — https://www.bountysource.com/issues/393629-site-redesign I'm not sure how @bountysource-support works in this regard (whether you can withdraw at some point) but it would probably be still the most efficient way of doing it (unless it's some sort of private agreement).

**Comment by KJTsanaktsidis** [comment]
I believe this should be fixed by https://github.com/kangax/fabric.js/pull/1999.

**Comment by kangax** [comment]
Closed via #1999
