### ISSUE TITLE
originX & originY have different values in rotation and movement

### ISSUE THREAD

**Issue by igisev** [kangax/fabric.js#1893]
Example:
http://jsfiddle.net/3gjt2hLj/10/

1. If drag circles separately - no problems.
2. If you create a group and rotate it - no problems too.
3. **BUT**, if you drag a group, the function CALC_COORDS gives an incorrect result because originX & originY will change.

As you can see, the calculation of the coordinates of a small circle is correct only if originX and originY equal to "center".
I think that in this case the right should be calculated for values "left" and "top". Or am I wrong?

If you check originX and originY group directly inside the function CALC_COORDS, it can be solved.
But what the correct way to determine the actual coordinates of the object that is in a group?

PS. the previous version of the fabric.js (~01 dec) did not have this problem.

**Comment by asturur** [comment]
After deeper inspection, this is not really an issue with fabric itself, but with a function you were using that counted for groups having origin in center.
