### ISSUE TITLE
rotating and scaling events not being triggered in fabric.js 1.4.13 on multi-touch displays

### ISSUE THREAD

**Issue by ggmendez** [kangax/fabric.js#1896]
Hi everyone, 

I have updated Fabric.js from version 1.4.12 to 1.4.13. My code works mostly fine, but my application is not able to detect the 'rotating' and 'scaling' events for fabric objects anymore ( using the object.on({'moving', function(){} }); sintaxis ). 

I am working with a Wacom multi-touch display and these events are only triggered when performed with the mouse. If the input comes from the touch screen or the stylus, only the 'moving' event is detected. 

The same code worked with no problems with previous versions but not with the latest release, so I assume this is an issue.

Cheers,
Gonzalo Gabriel

**Comment by cannontechnology** [comment]
Touch events are not working on a Surface Pro 3 / IE 11.   Will test on another windows device asap.

**Comment by jafferhaider** [comment]
Were touch events on IE11 working prior to 1.4.13? I was able to use a friend's Surface Pro 3 and sure enough, touch is not working.

**Comment by handersen** [comment]
We managed to get it running with Explorer 11 in 1.4.12 by setting

body {
    touch-action: none;
}

Setting this blocks the browser zooming of Explorer when using touch.

Tested with explorer 11 at Win 8.1.

It works as single touch (resize, rotate etc) and not multi touch like Chrome.

**Comment by ggmendez** [comment]
Hi everyone,

Just to let you all know that the reported issue is still present in the 1.5.0 version of fabric.js released yesterday. I have run the tests reported in my original issue and the behaviour is the same. :/

**Comment by asturur** [comment]
@ggmendez can yuo tell me again on what hardware / platform ther problem is still present?

**Comment by ggmendez** [comment]
I am running my system using a Wacom Cintiq 24HD touch. The problem is present both on Windows and Mac; and it happens with any Fabric.js version after the 1.4.12. The problem has prevented me from updating to other releases. When I made a video of what happens when I try the code at: http://jsfiddle.net/Kienz/mc35myjs : https://youtu.be/x2PR_R1Leps?list=UUmfvC2V0COpK2XI8OCbfG2g

**Comment by ggmendez** [comment]
I can confirm that this issue is not happening any longer (under the conditions mentioned above). I just tried my code with fabric.js-1.6.0-rc.1 and it is working with no problems. Keep the great work, guys! Thanks!

**Comment by asturur** [comment]
ok please have a double check and close the issue.
