### ISSUE TITLE
IText copy issue with shift + arrow selection

### ISSUE THREAD

**Issue by riaan53** [kangax/fabric.js#1897]
Hi,

Go to http://fabricjs.com/kitchensink/

Do the following:
1. Double click on one of the IText objects and use shift plus arrow key to select text.
2. cmd + c
3. Select place to past.
4. cmd + v

Results: The previously copied text will be pasted if any.

Tested on Chrome (Version 39.0.2171.95 (64-bit)) and Safari (Version 8.0 (10600.1.25.1)) on a mac.

Thanks.

Regards,
Riaan

**Comment by asturur** [comment]
Sorry, i'm taking care of Itext a little bit, but i cannot understand your issue.
What do you mean by "The previously copied text will be pasted if any." ?

Something that you copied BEFORE the last copy command is being pasted?

**Comment by riaan53** [comment]
Yes that is correct. Im seeing very funny things when using `shift+arrow` for selecting iText text and then copy and pasting it with `cmd + c` and `cmd + v` . Sometimes it even pasts the whole iText text from cursor position till end. Just play around with copy and past without using the mouse at all on the kitchensink demo that starts with the two iText objects. 

It works 100% when using the mouse to highlight the text that you want to copy and past.

Please let me know if you want some more info or unable to reproduce.

**Comment by asturur** [comment]
Found the bug and fixed it.
Mouse operation where handled by setSelection methods which updated the hidden textbox that reacts to copy pastes. Keyboard operation where handled by direct access to properties, so not triggering the textbox update.

**Comment by riaan53** [comment]
Awesome!! 

Thank you :)

**Comment by asturur** [comment]
Closed via #1872
