### ISSUE TITLE
Setting Your Own Type On Objects

### ISSUE THREAD

**Issue by mdiener** [kangax/fabric.js#1899]
Currently if I set my own type on an object everything works fine until I save and load the canvas again (through the toJSON and loadFromJSON functions). The toJSON works fine, however, the loadFromJSON throws an error. This is somewhat expected, as the type is not recognized upon loading. Since I can set the type, however, it should not happen.

I've written a small fix, but it might be worthwhile investigating more time into this. Something along the line of making an internal type that is used upon loading/saving. I've opted for a more 'quirky' move and just added the option to 'subclass' types:

In the function `fabric.utils.enlivenObjects` I changed the following lines:
```diff
diff --git a/src/lib/fabricjs/fabric.js b/src/lib/fabricjs/fabric.js
index e421ba7..2fdac62 100644
--- a/src/lib/fabricjs/fabric.js
+++ b/src/lib/fabricjs/fabric.js
@@ -619,9 +619,12 @@ fabric.Collection = {
           onLoaded();
           return;
         }
-        var klass = fabric.util.getKlass(o.type, namespace);
+
+        var type = o.type.split(':');
+        var klass = fabric.util.getKlass(type[0], namespace);
         if (klass.async) {
           klass.fromObject(o, function (obj, error) {
+            obj.type = o.type;
             if (!error) {
               enlivenedObjects[index] = obj;
               reviver && reviver(o, enlivenedObjects[index]);
@@ -631,6 +634,7 @@ fabric.Collection = {
         }
         else {
           enlivenedObjects[index] = klass.fromObject(o);
+          enlivenedObjects[index].type = o.type;
           reviver && reviver(o, enlivenedObjects[index]);
           onLoaded();
         }

```

If the user is not supposed to set their own type, this should be specified in the documentation.

**Comment by kangax** [comment]
Yeah, type is not meant to be changed. Can I ask why you're doing it?

**Comment by mdiener** [comment]
Well I was/am writing a program that requires saving and loading of data. One thing is that we're using custom objects, like stars, special arrows, etc. which are all done with the poly line. Now instead of extending the whole thing, which is not really what I want since I do not need new functionality at all, was to just set the type and differentiate this way what object the user has drawn.

But as you stated that it is not supposed to be changed I will look for another way around this the next time I touch this piece of code. It currently works but I will just assume that after an update it will probably break.

One thing I would still like to mention is that since this type is exposed in the documentation, maybe you could add a little note saying that it shouldn't be changed, as it breaks the loading/saving if it is.

**Comment by kangax** [comment]
> One thing I would still like to mention is that since this type is exposed in the documentation, maybe you could add a little note saying that it shouldn't be changed, as it breaks the loading/saving if it is.

Thanks, I added a note.

**Comment by alvarezmario** [comment]
@kangax where is that note added? In the subclassing documentation there is an example that exposes a custom class that has a `labeledText` type and doesn't say anywhere I've read that types can't be changed.

**Comment by asturur** [comment]
if you  create a class called LabeledText, the type will be labeledText. if the class is a Rect, type rect, you cannot change it to labeledRect.
