### ISSUE TITLE
"fill":null and "clipTo":null should be set to false

### ISSUE THREAD

**Issue by softvar** [kangax/fabric.js#1903]
When I saved the canvas as JSON, it contains `"clipTo":null and "fill":null` which I suppose are used to provide the same exact free drawing without including the start to end fill color(black as default). The problem is when I saved this data and retrieve it later, these null value keys are automatically get stripped and when I use `canvas.loadFromJSON(saved_json_obj)`, the black area comes into picture. Shouldn't the null value keys be set to either `0` or `false` to deal with this issue.

http://stackoverflow.com/questions/27580844/firebase-remove-object-keys-with-null-values

Please provide the alternative @kangax . I'm using Firebase to store/retrieve the data.
Thanks
##

**Comment by kangax** [comment]
Where exactly are those values being stripped? In Fabric or in whatever else you're using? If it's not Fabric, then it should be fixed or worked around there. `null` are just as valid values as `0` or `false`, meaning that they're "not set"

**Comment by softvar** [comment]
It's not fabric :) but it's weird that stripping those null valued keys have a major impact on canvas. I have used the most annoying hack for now:

```
function recursivelyReplaceNullToZero(j) {
    for (var i in j){
        if (typeof j[i] === "object") {
            recursivelyReplaceNullToZero(j[i]);
        }
        if (j[i] === null) {
            j[i] = 0;
        }
    }
}
recursivelyReplaceNullToZero(_json);
```

**Comment by asturur** [comment]
cannot workaround firebase features.
