### ISSUE TITLE
Feature Request: Mask Smoothing for Chrome [$100]

### ISSUE THREAD

**Issue by NewsteadEric** [kangax/fabric.js#1915]
(See also https://groups.google.com/forum/#!topic/fabricjs/k_fFQ6Iu9dI)

When clipping masks are applied in fabric.js, they render smoothly (anti-aliased) in most browsers, except for Chrome.

An example of how this plays out on a basic (non-fabric) canvas is shown here: http://jsfiddle.net/cXJMW/

This is apparently related to a Chrome browser issue report that's been open for a while now at https://code.google.com/p/chromium/issues/detail?id=124756

For example, applying the following circle shape as a clip to an image in fabric.js will produce this effect as well:
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="400px" height="400px" viewBox="0 0 400 400" enable-background="new 0 0 400 400"> <circle fill="#aaaaaa" fill-opacity=".3" cx="200" cy="200" r="200"/> </svg>

Varying the fill and fill-opacity parameters will mitigate some of the effect, but it seems that an actual solution will require additional operations on the canvas clipping operation itself.

A pertinent (non-fabric) question (with a suggested solution provided by someone) can be found here: http://stackoverflow.com/questions/9536257/how-to-anti-alias-clip-edges-in-html5-canvas-under-chrome-windows

@kangax has expressed that he would be fine pulling this into fabric.js as a feature if someone takes on the implementation.

I'm putting up a bounty for the implementation as a fabric.js feature, to fix this Chrome rendering issue.

The implementation must also work with the recently-implemented ResizeFilters (see https://github.com/kangax/fabric.js/issues/1741) and with masked transparent and non-transparent images.

A fast resolution would be greatly appreciated!

Thank you!
##

**Comment by NewsteadEric** [comment]
Is there anyone interested in taking this on?

**Comment by asturur** [comment]
I would eventually try to find a nice fabric solution, but really no free time now. Maybe in a some days. If i get the idea how to solve it, this may speed up, sit down and try all the composite operation to check the good one really no time now. Is not a matter of money.
The 2px border solution seems a no go fo me, it works just for full colors.

I feel i can add that solution must work for clipping object and clipping canvas, and clipping canvas over a background eventually.

**Comment by asturur** [comment]
Anyway there is an update here from 9 january

#10 lafo...@google.com
Migrate from Cr-Blink-Rendering to Cr-Blink-Layout
Labels: -Cr-Blink-Rendering Cr-Blink-Layout 

So maybe they are solving

**Comment by jardakotesovec** [comment]
Issue you referenced has *duplicate* status. [This one](https://code.google.com/p/chromium/issues/detail?id=424291) should be relevant I believe.  And [here](https://code.google.com/p/chromium/issues/detail?id=7508#c77) is workaround suggested. I have not tried it.. as secretly hope that it gets fixed sometime soon :-).

**Comment by NewsteadEric** [comment]
Anyone still looking to take this on as an update?

**Comment by kangax** [comment]
@asturur might be able to do it once he gets some free time but I'm not sure

**Comment by NewsteadEric** [comment]
Checking in to see if anyone has had a chance to look into this?

**Comment by asturur** [comment]
i gave it a shot, a came with an idea.
i do not know if it will work but i will try to implement it, if it will works but i will not like the  code amount or style, i will give it to you but i will not ask for a pull request or bounty.

The idea is more or less this:

if the "smoothingHack" is enabled we render the object on a separate context.
instead of clipping we draw the clipping shape in white. then with the discussed globalCompositeOperation we draw the object over the clipping area.
At the end of rendering stack for the object ( after fill and stroke ) we draw this temporary canvas like an image in the right place.

i think it will make the code complicated and it will not be fast.
Also we need to activate it just for chrome.

**Comment by ncou** [comment]
@asturur : the Chrome bug seems fixed (07/07/2016). This ticket could be closed ?

**Comment by asturur** [comment]
I think yes, now chrome smooth by itself.

**Comment by asturur** [comment]
@NewsteadEric check if you can claim back the bounty.
If not i will claim it for fabricjs.
