### ISSUE TITLE
Cloning and Adding multiple objects makes the cloned object not selectable.

### ISSUE THREAD

**Issue by ikedumancas** [kangax/fabric.js#1916]
Hi there!

 I am trying to copy and paste objects using the code I found on JSFiddle: 

http://jsfiddle.net/ikedumancas/tkfGs/235/

I don't know why the copied objects cannot be selected and cannot be moved even if I activate it and add controls to it programmatically.

Please help. Is this a bug or something?

**Comment by kangax** [comment]
There must be something on an app level that makes it not work. There's certainly no known bugs about immovable objects (created properly via clone). If you still think there's a bug, please reopen this but with _minimal_ relevant test case. Thanks for your understanding!

**Comment by asturur** [comment]
I think the mistake is:
object is being cloned with its group property set to something.
group object is not aware of those objects. when group get destroyed clicking outside, the cloned object don't get top and left restored. Something like that.
You should clone the object and update the group with the new cloned object.

**Comment by ncou** [comment]
Here is a working fiddle (only for group clone) :

https://jsfiddle.net/5pnrpt6g/9/

Now fabric.js have clone with callback function for sync and asynch objects (and probably a better cloning engine).

PS : You need to deselect the group before the paste, else you will get the weird behaviours with the objects moved in the top left canvas.

Hope this help.
