### ISSUE TITLE
Shadows affected by the canvas zoom level

### ISSUE THREAD

**Issue by ggmendez** [kangax/fabric.js#1917]
Hi everyone,

When the canvas zoom level is modified, the shadows of objects are affected. When zooming in, their offset is increased and when the canvas is zoomed out, the shadows sometimes disappear (as their offset eventually is set to zero, I presume). It seems to me that this is because the values for shadows offset remain absolute; that is, they do not take into account the changes on the canvas zoom level. 

The problem is specially evident when using the stroke property of fabric objects. I have placed an example to illustrate this at: http://jsfiddle.net/Lo9kxb0j/1

Cheers,
Gonzalo Gabriel

**Comment by asturur** [comment]
i remember we recently modify the shadow behaviour to reflect the zooming and scaling.
The zooming part looks inverted to me.
I will check it as soon as possible.
