### ISSUE TITLE
crop cloned image

### ISSUE THREAD

**Issue by fingerpich** [kangax/fabric.js#1918]
what i did
1- make a group of object
2- group.clipTo a rectangle smaller than the group
3- group.cloneAsImage

the result image is similar with group in size
but I need it to be similar with rectangle

**Comment by asturur** [comment]
Are you trying to crop the image? or do you have other aims?
Because now fabric has support to crop image to given rectangle. Aligning the image on the left center right ( for the x ) and top center bottom ( for the y )

**Comment by fingerpich** [comment]
when you clip a group of objects, and Clone it as image, the result image's width and height is the same as the original group size, this means that the clipping does not affect on the result image size
http://jsfiddle.net/fingerpich/sevoz2fp/2/
skip alerts and run it again

**Comment by asturur** [comment]
yes, the group is cloned as image. it doesn t mean that the group will be smaller than the original one because has a clipTo function. 

it works like that and i think it is fine.
