### ISSUE TITLE
issue with observing mouse:over / out

### ISSUE THREAD

**Issue by heaversm** [kangax/fabric.js#1920]
Hi - I am trying to resolve an issue wherein an object I create on mouse:over of another object(a tooltip drawn when a user rolls over a dot on a map) is not destroyed on mouse:out, in rare occasions where a user has moved quickly from one dot to another. In the process of trying to troubleshoot this, I noticed an odd behavior in with fabric in which it was trigger the observe(mouse:over) behavior when actually I was rolling *out* of an object.

A quick screencast of the tooltip not disappearing can be seen here:

http://goo.gl/Ns6QPs

and the issue of the mouse:over triggering on mouse:out can be seen here

http://goo.gl/r4c2uB

The code I'm using is below:

```
self.canvas = new fabric.Canvas('canvas');

self.canvas.observe('mouse:over',function(e){

      console.log(self.toolTip);

      if(e.target.id){
        var coords = {x: e.target.left, y: e.target.top };
        var memberID = e.target.id;
        var member = self.getMemberByID(memberID);

        e.target.animate({'radius': self.config.circleSizes[2]/2}, {
          onChange: self.canvas.renderAll.bind(self.canvas),
          onComplete: self.changeFill(e.target,self.config.fillActive),
          duration: 300,
          easing: fabric.util.ease.easeOutBack
        });

        self.drawTooltip(member,coords);
      }
    });

    self.canvas.observe('mouse:out',function(e){
      if(e.target.id){
        e.target.animate({'radius': e.target.circleSize/2}, {
          onChange: self.canvas.renderAll.bind(self.canvas),
          onComplete: self.changeFill(e.target,self.config.fill),
          duration: 300,
          easing: fabric.util.ease.easeOutBack
        });
        self.hideTooltip();
      }
    });
```

**Comment by asturur** [comment]
@heaversm would you be able to reproduce the issue now with latest fabric and a fiddle?
