### ISSUE TITLE
fabric js Fonts Issue for web fonts

### ISSUE THREAD

**Issue by ashishbhattb** [kangax/fabric.js#1922]
Helllo,

http://jsfiddle.net/vvL6f/6/
http://jsfiddle.net/ashishbhatt/20byuo7p/

Please check the above examples and try check the fonts\

Local fonts are working perfectly but goolge or webfonts are not working properly 

Please guide me how can i resolve the issue ?

As i want to use the google font but not getting properly while change the fonts but works once click on canvas or switch with other fonts 

Please guide me for the same

**Comment by asturur** [comment]
@ashishbhattb  i read the help of webfont.js and solution was there.

http://jsfiddle.net/vvL6f/91/
