### ISSUE TITLE
fabric.pathGroup property "fill" don`t working

### ISSUE THREAD

**Issue by Anisotropic** [kangax/fabric.js#1928]
var shape = fabric.util.groupSVGElements(objects, options);
..
shape.fill = "#ff0000";  //don`t working
shape.setFill("#ff0000");  //are working

fiddle: 
http://jsfiddle.net/Anisotropic/j3wL4gj3/

**Comment by kangax** [comment]
Well, "fill" is meant to be changed via `setFill` (as is everything else) so this is by design.
