### ISSUE TITLE
Click on line and curve

### ISSUE THREAD

**Issue by HtmlRanger** [kangax/fabric.js#1938]
Are there any realization of the event click on the line or curve? Now there is only a click event on the square of the line.

**Comment by asturur** [comment]
Yes, you can enable perPixelTargetFind.
You can check in the docs and in the demos:
http://fabricjs.com/per-pixel-drag-drop/

**Comment by HtmlRanger** [comment]
Thanks for the answer! I tried this, but again failed. What am I doing wrong? I need to by clicking on the curve back to its object, but returns 'undefined'.
http://jsfiddle.net/HtmlRanger/1bx8b29b/3/

**Comment by asturur** [comment]
http://jsfiddle.net/1bx8b29b/4/

You were using 1.4.0 and you unluckily triggered a bug with your specific path.
The path was considered 0 height so it was not selectable.
I updated your fiddle to use 1.4.13 and it works.

I close, from here you should go on by yourself.
