### ISSUE TITLE
Text Shadow and SVG result

### ISSUE THREAD

**Issue by hellomaya** [kangax/fabric.js#1940]
Hello all, when I have added a Text with shadow on the canvas, and export it to SVG, it give me this SVG result, you can see instead adding a filter in SVG, the text node used another way to present the shadow, and it's not displayed correctly in chrome/safari, but the text node do have a style element named "filter" and filter ID, so I am thinking it might be a valid issue? So I put the the SVG here, and I am using 1.4.13 by the way, and the text is IText not Text.
 
![2015-01-21 11 41 56](https://cloud.githubusercontent.com/assets/4657101/5839144/2d04bd94-a1c7-11e4-9fae-9b4b0c7d450f.png)

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="846.1714285714286" height="617" xml:space="preserve"><desc>Created with Fabric.js 1.4.13</desc><defs></defs><g transform="translate(313.45 241.01) scale(2.1 4.62)">
<text font-family="Arial" font-size="24" font-weight="normal" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: black; fill-rule: nonzero; opacity: 1;filter: url(#SVGID_0);" transform="translate(-86.01 25.2)"><tspan x="6.04" y="-13.08" fill="rgba(0,0,0,1)">CLICK TO EDIT</tspan><tspan x="0" y="-15.6" fill="black">CLICK TO EDIT</tspan></text>
</g>
<line x1="0" y1="-271.9836734693877" x2="0" y2="271.9836734693877" style="stroke: black; stroke-width: 1; stroke-dasharray: 2 2; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 0.8;" transform="translate(35.26 307.24)"/>
<line x1="0" y1="-271.9836734693877" x2="0" y2="271.9836734693877" style="stroke: black; stroke-width: 1; stroke-dasharray: 2 2; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 0.8;" transform="translate(808.4 307.24)"/>
<line x1="-386.569387755102" y1="0" x2="386.569387755102" y2="0" style="stroke: black; stroke-width: 1; stroke-dasharray: 2 2; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 0.8;" transform="translate(421.83 35.26)"/>
<line x1="-386.569387755102" y1="0" x2="386.569387755102" y2="0" style="stroke: black; stroke-width: 1; stroke-dasharray: 2 2; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 0.8;" transform="translate(421.83 579.22)"/>
<rect x="-4.4071428571428575" y="-309.5" rx="0" ry="0" width="8.814285714285715" height="619" style="stroke: black; stroke-width: 1; stroke-dasharray: 2 2; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: transparent; fill-rule: nonzero; opacity: 0.6;" transform="translate(423.59 309)"/>
</svg>
```

**Comment by asturur** [comment]
This issue is  fixed in the upcoming text PR #1872.
Yes the svg shadow was emulated with an offsetted tspan, now is normal shadow. Since sunday.
Now you can put even gradients in the text, things that was not possible before and export them in SVG.

**Comment by hellomaya** [comment]
Thanks, I just cloned the repo and compile it with all modules, then I tried, still the same SVG (even worse, google chrome show me the xml is incorrect), is there anything I got wrong? If it didn't include in latest version, that's fine, I am going to fix it because its urgent issue in my current work, and I checked the latest commit, and it's 

commit 7dc77530a6e63eaba31dd8cb1513464c2f27e7ff
Merge: 49d6872 2f6021f
Author: Juriy Zaytsev <kangax@gmail.com>
Date:   Tue Jan 20 22:14:04 2015 +0100

    Merge pull request #1936 from asturur/fix-travi
    
    trying to fix travis

**Comment by asturur** [comment]
https://github.com/kangax/fabric.js/issues/1872

Pull this if is very urgent.

**Comment by hellomaya** [comment]
thank you, I am going to try it, and if it's not working, I will fix it just for my current work, and late I will upgrade it with new version which have this fixed. Thanks again.

**Comment by asturur** [comment]
cosed via #1872
