### ISSUE TITLE
getBoundingRect for object in an active multiple selection returns group-relative bounding rect

### ISSUE THREAD

**Issue by lastobelus** [kangax/fabric.js#1941]
Is this intentional?

If so, is there a way to get the canvas-relative bounding rect of an object that is in an active multiple selection? 
##

**Comment by asturur** [comment]
Good question. I don't know if it si intentional or if this is a side effect.
Take in consideration that you have originalLeft and originalTop in the object, you can still make a simple method or function that uses those two to restore the values you need.

**Comment by kangax** [comment]
Hm, don't think it's intentional. Need to look into it more but probably a bug.

**Comment by Alysander** [comment]
@asturur I would have thought that originalLeft and originalTop would become invalid as soon as the group is moved/scaled.

**Comment by asturur** [comment]
I think you are right, i spoke too soon.
Is marked for 1.5.1 milestone, so we are looking into it very soon.
Suggestions and hints are always welcome.

**Comment by Alysander** [comment]
I think that having the coordinates relative to the selection group is a massive pain.  You still need to know the canvas coordinates of objects in groups. For example, when clicking on them to remove them from the selection (which is broken partly because Fabric expects oCoords to always be relative to the canvas ) https://github.com/kangax/fabric.js/issues/2170.  I'd like a way to easily get the canvas coordinates of an object, regardless if it's selected or in a group selection or not so I don't have to do a bunch of conversions and setCoords all the time.

**Comment by asturur** [comment]
you mean it should be like that?
![image](https://cloud.githubusercontent.com/assets/1194048/7737764/1429cbae-ff4e-11e4-863f-5a68ea75220c.png)
black square is bouding box

**Comment by Alysander** [comment]
No, I am talking about an internal change.  The group bounding box itself should be rotated if the user has rotated it. Everything should look the same to the user but the stored coordinates for the objects inside the group (left, top, oCoords) should never be made changed from the canvas coordinates to coordinates relative to group (done in _updateObjectCoords function in group.class).  Parts of the library already expect oCoords never to be changed and yet here they are. It would mean refactoring code around the corner handles resize/rotate/move operations but that is only one place whereas at the moment it requires everyone using the library to know about this internal detail and have two code paths whenever they are dealing with objects in group selections (but not individually selected objects or unselected objects).

**Comment by asturur** [comment]
I'm sorry i wrote a terrible answer, not comprensible.

The boundingBOX is rectangular and always aligned to the axis.
Controls are rectangular as well and not aligned to axis if we are rotating, controls are not argument of this issue.

The current error is that if the object is inserted in group and it does not have oCoords calculated, setCoords get calculated with actual changed coords relative to center of group, as you noticed.

The black outline is a debug drawing that i made up to check if i was effectively calculating the canvas related position of the objects inside the group, in this way to me they look correct.

getBBoundingBox should return a rectangle, axis aligned, that touch the corners of the object.
Do you agree?

**Comment by asturur** [comment]
i can solve in different ways.
We have 2 different problem here:
oCoords get calculated just if not already done ( ok good ), we do not know if it has been calculated in group coordinates or normal coordiantes.
We may assume that is in group coordinates and correct  them.

But do we really need that objects inside groups has oCoords relative to group? this make even hard sub targeting the objects in group, do the shift + click selection in active group.

Would not be better that setCoords always return canvas relative coordinates?

**Comment by menelike** [comment]
In our case we *commit* every change on canvas objects with help of `object:modified`. When a group of objects is moved the resulting item coords have strange values. A later reload of previously saved states result it displaced items.

> But do we really need that objects inside groups have oCoords relative to group?

imho this is the proper solution, if a single item is moved, it's position is relative to canvas, if multiple items are moved they should behave the same and therefore be relative to canvas and not relative to it's group.

**Comment by asturur** [comment]
fixed in 2.0 branch.
