### ISSUE TITLE
Duplicating i-text

### ISSUE THREAD

**Issue by 24ozcoffee** [kangax/fabric.js#1942]
When a single i-text element is added to a canvas, subsequent iteration of the canvas show two i-text objects.

var canvas = new fabric.Canvas('c');
var text = new fabric.Text('hello world', { left: 100, top: 100 });
canvas.add(text);
var obj = canvas.getObjects();
for (var i in obj) {
	if(obj[i].type == 'i-text'){
		console.log(obj[i].typee);
	} 
}

**Comment by asturur** [comment]
After checking and correcting your script,
i got this:
```
// clear canvas
canvas.clear();

// remove currently selected object
canvas.remove(canvas.getActiveObject());

var text = new fabric.IText('hello world', { left: 100, top: 100 });
canvas.add(text);

var obj = canvas.getObjects();
for (var i in obj) {
console.log(obj[i].type);
} 
```
Please execute in www.fabricjs.com/kitchensink in the execute tab, and check yourself that this is not happening. If it would happen, please report us.

**Comment by 24ozcoffee** [comment]
I found my error, sorry for wasting your time with a false error report.
