### ISSUE TITLE
bounding box too big

### ISSUE THREAD

**Issue by johnstonmatt** [kangax/fabric.js#1943]
After using freedraw the height of the bounding box is *inconsistently* 100x the size of the original height, sometimes the width does it too and sometimes there is no problems. setCoords doesnt fix it either :(

**Comment by kangax** [comment]
Using latest version? I can't reproduce on http://fabricjs.com/kitchensink/

**Comment by johnstonmatt** [comment]
yes i am using the latest version, I sent a link on Gittr

**Comment by johnstonmatt** [comment]
I think this issue is caused by assigning a freedrawBrush.width to a string. It was appending the stroke width to the 'currentHeight' property instead of adding them as integers I think.

**Comment by kangax** [comment]
@asturur mind taking a alook?

**Comment by boonkerz** [comment]
I have the same Issue:
![image](https://cloud.githubusercontent.com/assets/277321/6251822/6c7da208-b796-11e4-8fa6-5bd2001e8955.png)

**Comment by boonkerz** [comment]
Ok i think we should remove the approximation values in the boundingbox, height calculation stuff.

I have removed it and generate the height with pixel methods:
![image](https://cloud.githubusercontent.com/assets/277321/6267597/a8134336-b845-11e4-81ba-539003451205.png)

**Comment by asturur** [comment]
@boonkerz this issue is specific for freedraw brush.
Di you have problem with text, iText or both?

**Comment by boonkerz** [comment]
Yea look @ http://fabricjs.com/kitchensink/ -> export svg

**Comment by asturur** [comment]
As of now that demo page has outdate code.
I m sure we should have an intro: "what happened in fabric.js latest week" and we will have hlaf issue.
@boonkerz please download latest github folder, compile fabric js by yourself e try again, and tell us.

**Comment by boonkerz** [comment]
http://jsfiddle.net/VPd2H/6/ click on save svg

**Comment by asturur** [comment]
You linked to outdated fabric.js

**Comment by boonkerz** [comment]
yea but i have the same issue with fresh compiled sources

**Comment by boonkerz** [comment]
I have updated the http://jsfiddle.net/VPd2H/7/ with an fresh compiled version of fabricjs

**Comment by asturur** [comment]
i will check asap. i think is a caching issue. where i will find that font?

**Comment by boonkerz** [comment]
this issue is not font releated because it's the same with arial
http://jsfiddle.net/VPd2H/8/

**Comment by asturur** [comment]
Something is terribly off, i will treath it as a priority.
This particular case of simple iText does not work.
Is not a svg export issue but a rendering issue

As you see text decoration is aligned properly, so is a something else problem. i know even what...
So strange it does not happen with anything else ( like iText in kitchensink demo )

![image](https://cloud.githubusercontent.com/assets/1194048/6373310/229a12b0-bd0a-11e4-9070-716fe346a40f.png)

**Comment by asturur** [comment]
i think i found the issue and a solution.
Too much busy to take a full test.

SVG:
![image](https://cloud.githubusercontent.com/assets/1194048/6374161/685a185e-bd0f-11e4-954f-b0d0ea197f0c.png)

Canvas
![image](https://cloud.githubusercontent.com/assets/1194048/6374178/7e5e8838-bd0f-11e4-8759-9ec597d5c9b8.png)

Solution is this:
in itext class:

from this
```
    _renderTextLine: function(method, ctx, line, left, top, lineIndex) {
      // to "cancel" this.fontSize subtraction in fabric.Text#_renderTextLine
      // the adding 0.03 is just to align text with itext by overlap test
      top += this.fontSize * (this._fontSizeFraction + 0.03);
      this.callSuper('_renderTextLine', method, ctx, line, left, top, lineIndex);
    },
```

to this:
```
    _renderTextLine: function(method, ctx, line, left, top, lineIndex) {
      // to "cancel" this.fontSize subtraction in fabric.Text#_renderTextLine
      // the adding 0.03 is just to align text with itext by overlap test
      if (!this.isEmptyStyles()) {
        top += this.fontSize * (this._fontSizeFraction + 0.03);
      }
      this.callSuper('_renderTextLine', method, ctx, line, left, top, lineIndex);
    },
```

**Comment by asturur** [comment]
If someone is interested to take a full test round trip use this kitchensink clone or link the library to any jsfiddle.

http://www.deltalink.it/andreab/fabric/kitchensink.html

lib : http://www.deltalink.it/andreab/fabric/fabric.js

**Comment by boonkerz** [comment]
Ok i have pushed it to my repo with this fix and the fiddle works.
The Boundingbox for itext looks better as before
