### ISSUE TITLE
[Question] How to move objects in group and expand group to new size

### ISSUE THREAD

**Issue by jagi** [kangax/fabric.js#1944]
Hi, I have question like in the topic. I want to move objects within group and to calculate new dimensions of this group without creating new group. I would like to just update group bounding rect, left, top properties after moving its sub-objects.

**Comment by kangax** [comment]
Please ask questions on google group — https://groups.google.com/forum/#!forum/fabricjs

The issue tracker is only for bugs and feature requests. Thanks for your understanding!
