### ISSUE TITLE
Cursor position and Text rendering

### ISSUE THREAD

**Issue by knospe-** [kangax/fabric.js#1948]
I am using fabricjs in my responsive webpage. I am trying to add some text to the canvas. So far this works ok.

Because the webpage is responsive, the canvas container changes in size according to the viewport. I would like that the canvas always takes 90% of the container element. Therefore I am scaling the canvas and all elements inside it so that they keep the same relative positions but take the 90% of the container. ( -> Is there any better way to do this?)

Everything works ok, except for the text rendering when the canvas loads for the first time. The text elements seemed to be shrunken. Other elements (Rect, Graphic) are added ok.

![itext_ok](https://cloud.githubusercontent.com/assets/4748089/5901991/fd1e86ec-a576-11e4-8c57-4e431e23511a.png)

This is how it should look like. And when I click on the canvas or enable developers tools of a browser, the iText elements get "stretched" to the correct size.

![itext_error](https://cloud.githubusercontent.com/assets/4748089/5901993/02f59ede-a577-11e4-815a-a78cd84e573d.png)

I have tried using object.setCoords() on iText object and also canvas.calcOffset() which is suggested in many posts that I've come accross, but unfortunately with no success.

And by iText element I also have a problem with the cursor position - when I click on the element and try to edit it's content, the coursor is not displayed in between the characters (where would normaly be) but on the caracters.

![itext_cursor_error](https://cloud.githubusercontent.com/assets/4748089/5901995/087466ec-a577-11e4-87dc-4111bbbbd500.png)

Did somebody else come across this problem?
(What are your techniques in using fabricjs in responsive design, when the size of a canvas container changes?)

**Comment by matheusczi** [comment]
Hi, can you share your solution?
