### ISSUE TITLE
Image disappears on image change, then reappears when I move the image

### ISSUE THREAD

**Issue by pmudahar** [kangax/fabric.js#1949]
This is what I'm trying to do:
What I want to do:
1. Select the object on the canvas
2. Click change image to change the selected image on the canvas

What is happening:
1. Image disappears, but reappears as the new image when you try to move the empty area.

Code is pretty straightforward.  Any ideas?  Thanks in advance.

```
<body>
	<div>

	<button id="click" onclick="up()">Change Image</button>

	<canvas id="canvas" width="1000" height="500" ></canvas>
	
	<script>
		var canvas = new fabric.Canvas('canvas');

		fabric.Image.fromURL("https://www.filepicker.io/api/file/jGVMrkPuQ8eNGn5BpsiB", function(oImg) {
			canvas.add(oImg);
		});

		var up = function(){
			var tmp = canvas.getActiveObject();
			var el = tmp.getElement();
			
			el.setAttribute('src', "https://www.filepicker.io/api/file/l8hjrB6JTduyAuog2BNY");

			canvas.renderAll();
			canvas.calcOffset();
		}

	</script>
</div>
</body>
```

**Comment by pmudahar** [comment]
So it looks this happens because renderAll is called before the image is loaded, and then called again when I click inside the image.  Any way to automatically call renderAll when the image has finished loaded?

**Comment by pmudahar** [comment]
Ok so instead of changing the src of the element, I used the setSrc method and called renderAll in the callback.  Works!

```
tmp.setSrc("https://www.filepicker.io/api/file/l8hjrB6JTduyAuog2BNY", function(){
				canvas.renderAll();
				canvas.calcOffset();
			});
```

**Comment by asturur** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Using_images

There is a nice tutorial on MDN to using image elements

**Comment by pmudahar** [comment]
Thanks @asturur.  Using the load event listener for images would have also worked.
