### ISSUE TITLE
Object._getLeftTopCoords gets left center point

### ISSUE THREAD

**Issue by jagi** [kangax/fabric.js#1950]
I've noticed that function `Object._getLeftTopCoords` look like follows:

```js
function () {
  return this.translateToOriginPoint(this.getCenterPoint(), 'left', 'center');
} 
```

This function is used for transforming canvas for text rendering and maybe there is the reason to take left, center point but as name suggests it should take left, top point. Am I right? :)

**Comment by asturur** [comment]
Yes you are right, this is wrong.
Luckily this function does not get called by any situation as of now.
