### ISSUE TITLE
Underline used in fabricjs does not match the underline in the ttf font file

### ISSUE THREAD

**Issue by smeetsmeister** [kangax/fabric.js#1955]
The distance between the underline is different in Fabricjs then the font in the ttf font file. The distance between the text and the underline is too much. Text with the same size and font with underline looks different in Fabricjs then for an example Word or another program that can put underline on a text. I want to use Fabricjs in an application where users can design things, and it is necessary that the design matches 100%.

Is it possible to make the distance between underline and the text the same in FabricJS as in the TTF font file?

**Comment by asturur** [comment]
please check the latest code in repository. i tried to fix it as much as possible. is drawn over the font not under as by css spec.

**Comment by kangax** [comment]
Please reopen with reproducible test case.
