### ISSUE TITLE
Resize SVG by viewBox

### ISSUE THREAD

**Issue by hellomaya** [kangax/fabric.js#1956]
I have this required to keep the quality of image when converting SVG to PDF, and I looked the code, I found that I can just add another option value in toSVG, so I can resize SVG by this in toSVG from static canvas : 
```
if (options.documentSize) {
        width = options.documentSize.width;
        height = options.documentSize.height;
      }
      else {
        width = this.width;
        height = this.height;
        if (!this.svgViewportTransformation) {
          vpt = this.viewportTransform;
          width /= vpt[0];
          height /= vpt[3];
        }
      }
```

The original source is : 

```
if (options.viewBox) {
        width = options.viewBox.width;
        height = options.viewBox.height;
      }
      else {
        width = this.width;
        height = this.height;
        if (!this.svgViewportTransformation) {
          vpt = this.viewportTransform;
          width /= vpt[0];
          height /= vpt[3];
        }
      }
```

The problem is that I saw the `vpt` part, and I am not sure if I can use `vpt` to do the same thing, so is this a valid way to do so? About the viewBox and how it works, http://tutorials.jenkov.com/svg/svg-viewport-view-box.html#coordinate-system-units

**Comment by hellomaya** [comment]
When we export canvas to SVG, the document size is based on canvas size in fabric.js, and it usually small, so when we convert the SVG to PDF, the image is with low quality, to resolve that, we think we should resize SVG (much more efficient than resize Canvas), and then we found that we can use document size of SVG and viewBox attribute to achieve that.

Then we turned back to fabricjs toSVG function, see if we can change document size & viewBox attribute, the result is we found that we can use viewBox attribute, but we don't know how to change document size, like this : <svg width="{document width}" height="{document height}"...

So we added that documentSize option just for temporary use, I think fabric.js should have that option, just don't know if it had or not, and how to use.

**Comment by asturur** [comment]
You should do that:

"w" is canvas width in pixels
"h" is canvas height in pixels

you put viewBox="0 0 w h" in the svg tag.

in svg tag you can put then
width="1000m" height="1000m"
to have 1km past 1km big svgs.

or widht="21cm" and height="297mm" to have an A4 sixed svg
or you can express them in pixels.

Of course if you have images inside they will be pixellated.

But i think the problem is in your svg library, in mine, even if the svg is small, when i put in a pdf and i enlarge it, the quality is good.

i hope i helped you.

We could even support this in fabricjs i think.

**Comment by hellomaya** [comment]
Thanks, and I hope fabricjs support that too.

**Comment by rmorse** [comment]
To be honest I think this is a great suggestion.

I'm not having a problem with the quality at all - I love the SVG functionality - however my use case is as follows:

I allow the user to design a layout in fabric, then save as PDF - so they can get it printed anywhere .

The SVG exported is posted to the server, mPDF (php library) then converts this to a fully linked PDF.

This is flawless and couldn't be happier with it.

However the SVG is not the size I want it on import - I actually want to place 9 of these on page in a grid, which means the SVGs need to have specific dimensions - so resizing (scaling) the SVG itself before its processed externally is an absolute must for me...  

There has to be a bunch of use cases for wanting to do this, such as using svgs in regular html files at specific dimensions.

I'm going to try the modification by @hellomaya  - thanks for that btw!

**Comment by solex16** [comment]
If it helps, I do a search and replace on the SVG string:
    scaleSVG = 200
    viewBoxX = 300;
    viewBoxY = 200;
    regex = 'width="(.*)" height="(.*)" xml:space="preserve">';
    re = new RegExp (regex);
    replace = 'width="'+scaleSVG+'%" height="'+scaleSVG+'%" viewBox="'+viewBoxX+' '+viewBoxY+' $1 $2" xml:space="preserve">';
     svg = svg.replace(re, replace);

**Comment by rmorse** [comment]
Hey @solex16 thanks so much for this - it worked after a bit of modding ;)

Basically I couldn't get the regex to work (dimensions etc were not being replaced) so I did it manually and this was almost there - it was definitely scaling..

However the width/height was being taken from the container element - so it was taking up my whole screen  - as I knew the dimensions I wanted to output this to I also added them in manually (they were locked to aspect ratio) and everything works perfect!

So I ended up using:
`theSVG = theSVG.replace('width="390" height="546" xml:space="preserve"', 
						'width="188" height="264" viewBox="0 0 390 546" xml:space="preserve"')`

I much prefer the idea of using your regex though so will battle on and see if I can get it working in my setup.

@hellomaya - I tried your method, but after a second look, it doesn't seem modify the functionality of fabric, it just renames viewBox to documentSize - and the current viewBox functionality is not what I was after - it needed to scale the whole thing (ie set the final output dimensions)

Thanks!

**Comment by rmorse** [comment]
Updating here with what worked for me:

`var theSVG = this.canvas.toSVG(svgOptions);
		destWidth = 188;
		destHeight = 264;
		regex = 'width="(.*?)" height="(.*?)" xml:space="preserve">';
		re = new RegExp (regex);
		replace = 'width="'+destWidth+'" height="'+destHeight+'" viewBox="0 0 $1 $2" xml:space="preserve">';
		theSVG = theSVG.replace(re, replace);`

This allows you to supply a destination width and height at the top and if its the same aspect ratio works perfectly - haven't tested with an aspect ratio that doesn't match the source.

**Comment by hellomaya** [comment]
I think this feature could be added to fabricjs too, so I will reopen it.

**Comment by solex16** [comment]
@rmorse glad to be of help..and thx for sharing your update

@hellomaya thx for reopening..would be great to get scaling the SVG supported in fabricjs as nervous about using the regex hack in production code..

**Comment by asturur** [comment]
Viewbox will be implemented and it will be tied to canvas Zoom and Pan. So it will help you to have a svg that represent the canvas, how it should be. ( i do not remember how it works now )

To make bigger or smaller SVGS we can add a parameter to toSVG method, including width and height desired.

toSvg(options)...

**Comment by asturur** [comment]
i used this feature recently.

 I realized that in svg header we should have:

width: arbitary width we want our document
height: arbitrary height we want our document
viewbox: x1 x2 x3 x4
x1 and x2 are panning
x3 and x4 should be related to width of canvas in pixels / viewport scaling X

i did this to export a small canvas to svg in A0 format ( 80cm past 119 cm) and the result is pretty good because we delegate the zooming factor to viewbox rendering of svg viewer or converter.

**Comment by spearson2010** [comment]
Yeah, I agree with this.  I just recently needed to write a different width and height to the svg header (had to do via replace after the svg was generated), but it'd be nice if I could list the height and width and viewbox to get my desired result.

Ex:

```javascript
            var svg = canvas.toSVG({
                width: "100%",
                height: "100%",
                viewBox: {
                    x: xpt,
                    y: ypt,
                    width: wid,
                    height: hgt
                }
            }, reviver);
```

**Comment by asturur** [comment]
We implemented and pull this some days ago.

I really think yuo should never specify viewbox. Leave viewbox to viewport handling and just specify width and height.
