### ISSUE TITLE
Bounding Issue

### ISSUE THREAD

**Issue by ashishbhattb** [kangax/fabric.js#1959]
I am trying to make skew based image, for that i needs outline to draw and fill the image,
outline will display in backend for settings  and skew based image will display in frontend.

my problem is for bounding and scaling the object after the resize of the object

Here all working fine but once i scale image then apply my positions for x, y or shape its not working

Please guide me for the same, below is the JS for the same 
http://jsfiddle.net/6CDFr/89/

I am trying to making the shape based on the cap, skew based shape and will put image on it 

Also let me know how can i fill image in polygon shape, not pattern i already tried but not work for me 

Thanks

**Comment by ashishbhattb** [comment]
I am trying to make skew based object which is very difficult but get some help from the polygon so trying with that

**Comment by asturur** [comment]
I'm very sorry, but i cannot understand what you want to do.

**Comment by ashishbhattb** [comment]
Hmm. needs to fix issue for reset the points
for eg. if you re-size it woks, then change the x position or y position for setting up the skew 
its again reset to original position.

so whenever you resize and adjust skew x or skew y its not updating with new but taking old points only.

i hope now you will get idea

**Comment by ashishbhattb** [comment]
Basically i needs to make skew based object, as we cant handle the skew from controls but we can make skew by setting up the positions X and y axis.

X axis and Y axis settings are working for points, which makes the polygon, BUT ISSUE COME WHEN WE SCALE THE OBJECT AND THEN APPLY THE SETTINGS FOR X & Y AXIS, ITS RESIZE TO ORIGINAL POSITION WHICH I DON'T WANT, ITS SHOULD STAY AS PER THE SCALE RATIO.

If this code works then i needs to set image according to the polygon shape

**Comment by ashishbhattb** [comment]
Hi,

I fix with the skew part as i want 
http://jsfiddle.net/6CDFr/97/

As it will work as admin side, and now i want to take the parameters from the poly points and make a image for frontend.

You can see the image is already in the cap, i will get blank imprint area in frontend, if any user place the image it should place like a poly shape as i made for admin

I hope now you can understand, i needs to add image in polyshape only 

i don't want to add pattern as it will not work here, just needs to add image but image shape will be like poly as i made for admin 

Regards,
Ashish Bhatt

**Comment by ashishbhattb** [comment]
Can i make same bounding box to rectangle, while doing skew only  ?

needs same feature for rectangle is that possible ?

http://jsfiddle.net/6CDFr/108/

**Comment by kangax** [comment]
Please ask questions on google group
