### ISSUE TITLE
Potential fabric.Path bug

### ISSUE THREAD

**Issue by kangax** [kangax/fabric.js#1965]
From the email:

First I would like to say that I'm using fabric js and enjoying it. There is however a bug I've encountered in the latest version 1.4.13. I'm using fabric.Path to draw a circle with an 'X' that crosses it. A strange thing happens: If I draw just one item, everything looks fine, but if I draw another one, the bounding box of the second item gets bigger, if I draw a third one the bounding box again gets bigger, and so on (the drawn item stays the same). I've noticed that this problem doesn't occur in version 1.4.11, but there you have a different bug: the left and top properties of the active group are wrong. This is my code:

```js
var obj1 = new fabric.Path("M 0, 0 L 17, 17 M 69.36, 0 L 52.36, 17 M 69.36, 69.36 L 52.36, 52.36 M 0, 69.36 L 17, 52.36 M 35, 35 m -25, 0 a 25,25 0 1,0 50,0 a 25,25 0 1,0 -50, 0", {
                          fill: 'black',
                          stroke: 'black',
                          left: 100,
                          top: 100
                      });

canvas.add(obj1).renderAll();

var obj2 = new fabric.Path("M 0, 0 L 17, 17 M 69.36, 0 L 52.36, 17 M 69.36, 69.36 L 52.36, 52.36 M 0, 69.36 L 17, 52.36 M 35, 35 m -25, 0 a 25,25 0 1,0 50,0 a 25,25 0 1,0 -50, 0", {
                          fill: 'black',
                          stroke: 'black',
                          left: 250,
                          top: 250
                      });

 canvas.add(obj2).renderAll();
```

**Comment by asturur** [comment]
i guess si something with parsing dimension of lowercase a command, divided in beizer.

**Comment by asturur** [comment]
@kangax 

when i do this:

'''
      bound = getBoundsOfCurve(fromX, fromY, segs[i][0], segs[i][1], segs[i][2], segs[i][3], segs[i][4], segs[i][5]);
      bound[0].x += fx;
      bound[0].y += fy;
      bound[1].x += fx;
      bound[1].y += fy;
      bounds.push(bound[0]);
      bounds.push(bound[1]);
      fromX = segs[i][4];
      fromY = segs[i][5];
'''

with the function getBoundsOfCurve i m returning a cached value.
immediately after i m incrementing the values.
am i also incrementing the cached copy?

that would explain the bug.

**Comment by kangax** [comment]
@asturur yes, if whatever your return from `getBoundsOfCurve` is the same object, you're then accessing its [0].x/y values and changing properties of that same object.

**Comment by asturur** [comment]
so this is the bug. i cannot correct it today, i m abroad just with smartphone, but solution is clear, clone cache instead of returning it.

glad that the cache is hitting at least.

**Comment by asturur** [comment]
@kangax Can i extend fabric.util.object.clone to get deep with nested objects?

**Comment by kangax** [comment]
@asturur hm, maybe only as an additional option/flag or even a separate method
