### ISSUE TITLE
Null reference error

### ISSUE THREAD

**Issue by Lenggries** [kangax/fabric.js#1967]
inside applyFilters() there is a reference to filter's type value without first checking if filter is null, which can easily happen if a client removes a filter:

        if (!forResizing && filter.type === 'Resize') {

this should be:

        if (!forResizing && filter && filter.type === 'Resize') {

**Comment by asturur** [comment]
thanks for pointing out. i ll fix it

**Comment by Lenggries** [comment]
Awesome! Thank you so much!
