### ISSUE TITLE
StrokeWidth without padding on image

### ISSUE THREAD

**Issue by guillaume23** [kangax/fabric.js#1968]
Hello, 
I would like to make a stroke width on an image without adding a padding on it.
```javascript
                        var canvas 		= getCurrentCanvas();
			var obj 		= canvas.getActiveObject();
			var size 		= infosImages[obj.imID];
			obj.width = parseInt(size.width + value);
			obj.height = parseInt(size.height + value);
			obj.set('strokeWidth', value);
			obj.set('stroke', hex);		
			canvas.renderAll();
```
you can see images before and after strokeWidth.
Sorry for my english, i'm french.
Thanks

![2015-02-11_174032](https://cloud.githubusercontent.com/assets/4788787/6151313/36ebf760-b215-11e4-9abb-718547510a8b.png)
![2015-02-11_174047](https://cloud.githubusercontent.com/assets/4788787/6151312/36e98138-b215-11e4-8323-ad14e5d038cc.png)

**Comment by asturur** [comment]
you mean that you would like to have a border that goes just inside and not half outside and half inside? if this is correct, just make a group with an unfilled rect with the strokewidth you desire and adjust rect width to be same as image. then group them.

**Comment by guillaume23** [comment]
Ok, i almost understand what you mean, 
if i've understood, i nedd to make a rect around the image ? Right ?
Thanks

**Comment by kangax** [comment]
Please ask questions on google group — https://groups.google.com/forum/#!forum/fabricjs
