### ISSUE TITLE
Is there a way to specify the image dpi

### ISSUE THREAD

**Issue by zefta** [kangax/fabric.js#1970]
Hi,

I would like to generate a png file with 150dpi but I always get an image with 72dpi. Is there a simple way to achieve that with toDataURL ? Or an other function.

**Comment by jagi** [comment]
I assume that you are talking about generating png file from canvas. As far as I know there is no such feature in Fabric.js but you can cheat here a little bit. The generated png file will not going to have dpi information but you can just scale canvas and viewport by a given factor `150 / 72 = 2.083333333`.

```js
var scaleFactor = 150 / 72;
canvas.setWidth(canvas.getWidth() * scaleFactor);
canvas.setHeight(canvas.getHeight() * scaleFactor);
canvas.setZoom(scaleFactor);
```

**Comment by zefta** [comment]
Hi, thanks for your answer. But this will generate a bigger image only? like if I need a png 1000x1000px with 150dpi this will generate a 2000x2000px ? Is there a way to generate 150dpi? Convert the canvas to any type of data that imagemagick can reuse ?

**Comment by asturur** [comment]
Look, yesterday i made a research, just to answer.
I suspected that canvas does not care about DPI during toDataUrl ( that is a native method).
I could not find any way to specify dpi.

Of course you can use imageMagick to do that.
this should sound plain and simple to you:
- If you to change dpi setting, you upload the todataURL string to a server.
- You strip away the url part, and decode the base64 string, you get a binary string.
- you save the binary string in a file on the server.
- you run  the iMagick class (php for example) or run a prompt based version of imageMagick with the dpi convert options ( i do not rember them actually ).
you save back the image in png or which format you prefer, imageMagick on the prompt normally works on files, so you have to save and read back.

Depending on which server and infrastructure you are doing that you may find problems.

If you want to change just dpi this is a solution, not related to fabricJs.
If you want to change DPI and mantain the dimension, you have to do what jagi suggested.
Depending what you have on canvas, enlarging it may be useless pixel growing but not details added.
Did you consider using SVGs if it may apply?

**Comment by kangax** [comment]
DPI setting is done in image headers and unfortunately we don't have access to that from within Javascript (and so Fabric.js), as far as I know.

**Comment by Sashkan** [comment]
Any update about this ? It seems like ToDataURL is still creating a 72 DPI png file

**Comment by asturur** [comment]
i have written a library to do this, won t be part of fabricjs, and i m waiting an ok to release it as opensource.

**Comment by alinmircea** [comment]
All you need is https://github.com/murkle/rewrite-png-pHYs-chunk
+ handleCodePoints function from here if your image is large https://github.com/mathiasbynens/String.fromCodePoint/issues/1

Here's the fiddler http://jsfiddle.net/j0k0jnff/11/ tested in chrome

As for the explanation, DPI is nothing more than metadata in image files, 72 is the default in some image processing tools (when no DPI is actually set).

Resources:

http://www.libpng.org/pub/png/spec/1.1/PNG-Chunks.html#C.pHYs
http://www.apptools.com/examples/dpi.php

**Comment by asturur** [comment]
Oh well if i found it before, it would have saved me some headache.
Mine version is smaller, is built for PNG or JPEG coming from a canvas.
It is a little bit less invasive since it does not require you to convert the image in dataArray, but can operate on dataurl or blob. I really hope i can release it soon!

**Comment by asturur** [comment]
@Sashkan if you still want to know about dpis, finally the library is about to be released, is no a private github repository and will be turned public soon.

**Comment by xql279671304** [comment]
@alinmircea  it's works

**Comment by vincentcox** [comment]
@asturur, can you link to your library?

**Comment by asturur** [comment]
The link is the one in the message above your question. Is still there.
