### ISSUE TITLE
Canvas custom font rendering inconsistent

### ISSUE THREAD

**Issue by jardakotesovec** [kangax/fabric.js#1971]
Hi,
I know that it is not likely issue of fabric, but I don't know better place to ask as here are people that care about web2print issues, hope its ok.

I have been testing custom fonts via css font-face. It works, but there are differences in thickness and letter spacing, depending on browser and platform. In some cases the differences are very significant. I used IText to create this example, but it just uses ctx.fillText, so it seems to be just issue of browser having different rendering engines.

I wonder how you guys deal with it? Customer does not get real picture what will go to the printer. Any ideas how to compensate it? Do you know why some fonts I tried (ttf,otf) have such significant differences in spacing? 

Next step for me is to make node-canvas work and see how it looks there. 

All images are aligned and same size so its easy to flick through and see the differences. [Here is](https://dl.dropboxusercontent.com/u/12126978/font%20test%202.zip) zipped folder so you can easily download them.  

Thank you for any feedback!

chrome (osx):
![canvas_chrome_osx](https://cloud.githubusercontent.com/assets/1590681/6184891/e6b20150-b367-11e4-8c7c-7cbf18b12834.png)
chrome (win81):
![canvas_chrome_win81](https://cloud.githubusercontent.com/assets/1590681/6184892/e6cc47e0-b367-11e4-8db0-e88f5d75aa7a.png)
firefox (osx):
![canvas_firefox_osx](https://cloud.githubusercontent.com/assets/1590681/6184893/e6dbbb8a-b367-11e4-8606-e0acb685752f.png)
firefox (win81):
![canvas_firefox_win81](https://cloud.githubusercontent.com/assets/1590681/6184895/e6dceba4-b367-11e4-87cb-c0a4918c190f.png)
ie11 (win81):
![canvas_ie11_win81](https://cloud.githubusercontent.com/assets/1590681/6184894/e6dc9028-b367-11e4-9d91-81fe42405568.png)
safari (osx)
![canvas_safari_osx](https://cloud.githubusercontent.com/assets/1590681/6184896/e6df7d7e-b367-11e4-957d-2ae16a71176f.png)

**Comment by asturur** [comment]
Can i ask you on wich version of fabric did you test it? cause there is a merged text changes that changes some things.
Did you download source from GITHUB and make the buld? Because in standard build is not available yet. otherwise we are talkin about replaced code and it would be useless.
Also to my untrained eyes, it looks like we are speaking about different font subhinting / antialias techs... may it be?

**Comment by jardakotesovec** [comment]
I used 1.4.13 from dist folder on [git](https://github.com/kangax/fabric.js/blob/master/dist/fabric.js) and made sure via breakpoints that it just calls ctx.fillText.  We also did similar test with using just svg (without fabric.js) and the differences were similar, which really suggest just that its caused by different browser engines.

For example if you check chrome and safari on osx screenshots. You can download them and open both in preview so you can switch between them and see that some lines are significantly wider in chrome..  

So subhinting / antlias is definitely one issue, but also letter spacing which therefore produce text with different widths..

**Comment by asturur** [comment]
Ok, if you are interested in checking even font underline and striketrought, please build the fabric.js file from the folder you dowloaded. Do not use prebuilt one for this matter.

**Comment by jagi** [comment]
If you want to have almost the same font displaying experience on all OS'es I would suggest replacing standard fillText with drawing paths using opentype.js. It could be nice feature if introduced in Fabric.js. There could be a flag that determines if developer want to display font using standard fillText or opentype.js.

**Comment by jardakotesovec** [comment]
@jagi Thanks! That might be something I am looking for :-). I will take a look.

**Comment by jardakotesovec** [comment]
@jagi I created same test using opentype.js and it looks very good, differences across browsers are negligible, just some small anti-aliasing differences. So it seems to be way to go for my use case. So thanks a lot again :+1:

**Comment by kangax** [comment]
Yep, unfortunately this is how native rendering works — there's slight differences among platforms/browsers. Like @jagi says, replacing native `fillText` with somethign else is one way to fix it. But this usually brings another set of problems. We used to have Cufon.js for exactly this purpose and the rendering was indeed consistent but then you need a specially-formatted definition file (.js) for each font, the rendering performance is significantly worse. There was more issues, which pershaps @asturur might remember.

**Comment by kangax** [comment]
This was the performance page — http://fabricjs.com/text-performance/
Notice "use native" which no longer matters since we got rid of Cufon only a month ago, but without native (using Cufon) you could barely drag that large chunk of text; was very laggy.

**Comment by kangax** [comment]
@jagi yeah, it's an option (although not trivial)

**Comment by asturur** [comment]
There was a pr for this, called like turbo code or something like that. From GordoRank.
Something we should take back in hands after:

1.5.0 Release, TextBox merge, dirty rects anyone? , curveText feature,  skewing support, tspan support, svg masks, svg patterns...

**Comment by kangax** [comment]
Ah... the wonders of open source project :)

**Comment by jagi** [comment]
Everything is possible :) Community want to help :)

**Comment by eric-schleicher** [comment]
I've encountered this chain in search of a method to convert text to curves for export in fabric.

@jagi is there an implementation (or examples) of using opentype with fabric?  

before I found this thread, this was emerging solution path (working opentype into my implementation) glad to see that i wasn't the only one with this thought..  googling hasn't revealed an prior art of the two in use with eachother.

i'm very interested in this functionality being natively present in fabric FWIW, and would do a bountysource for a legit solution if anyone is interested in taking it up.

**Comment by jagi** [comment]
@eric-schleicher I don't think that there is solution for that using OpenType but implementing it by yourself shouldn't be hard task. However the best performance you would achieve when combining it with caching which is not something that you're gonna see soon. However maybe it will be good for you without caching. I would like to see comparison between using native text rendering and OpenType one.

**Comment by eric-schleicher** [comment]
My immediate objective is to get the font paths into an SVG. and to leave the SVG fonts out upon export.

any thoughts on the best approach.  right function(s) to offerride or create?
