### ISSUE TITLE
Error in importing and saving files using toDataURL()

### ISSUE THREAD

**Issue by Lenggries** [kangax/fabric.js#1972]
As seen in this jsfiddle page (http://jsfiddle.net/Lenggries/orgnsnL6/1/  -- please note that it is not a full product and does not include every test I have made. Also note that the behavior varies across browsers) there is an issue with the simple task of creating an image from an image tag and saving it via toDataURL(). In other words, consider the following line of code (where imgElement references an HTML <img> tag):

    imgElement.src = new fabric.Image(imgElement).toDataURL();

In theory, the image should not change, but unfortunately it does. This can result in offset images that grow in size or get blurry with every save.

The primary culprit appears to be the bounding rectangle, which exceeds the image size by a half-pixel on every side. In the version of fabricjs that we use, I believe the root problem exists in object_geometry.mixin.js->setCoords(). However, in the master branch, the portion of code has been moved to object_interactivity.mixin.js->_calculateCurrentDimensions():

    strokeWidth = this.strokeWidth,

This forces an increase in the bounding rectangle even if no stroke is used. Changing that line to: 

    strokeWidth = this.stroke ? this.strokeWidth : 0,

seems to fix the problem, at least in my version. However, I am not familiar enough with the inner workings of fabricjs to recommend this change be made outright. I hope someone with a much better understanding can examine my suggestion and either implement this change or find a better resolution to the problem.

Thank you

ps. As a side, note, in setCoords(), I recommend using atan2() rather than atan(), as it handles the division by zero issue natively. And it may be worthwhile to attempt to perform some rounding as those trigonometric functions do produce some floating point issues even when dealing with a simple image that hasn't been rotated at all.

**Comment by asturur** [comment]
Using this ```strokeWidth = this.stroke ? this.strokeWidth : 0``` bring accuracy problem to svgs with lot of lines.

Please just put 

``` this.strokeWidth = 0 ```

to objects you do not intend to use stroke.

Will look into this matter of atan2() , and maybe skip them if there is no angle to deal with.
I do not remember the logic of that hypotenuse story is near the atan function.

**Comment by Lenggries** [comment]
Downwind effects like the SVGs you described are exactly why I don't feel qualified to directly contribute source here. That said,I would still argue that loading and saving an image via

    imgElement.src = new fabric.Image(imgElement).toDataURL();

should produce no changes when default settings are applied. Not sure how you can elegantly get there, though.

That said, thank you for your suggestion of a workaround.

**Comment by asturur** [comment]
Look, the problem is that ```strokeWidth = 1``` and ```strokeWidth = this.stroke ? this.strokeWidth : 0```
have been default for ages.
Then 20 November, after an issue, we came out with this pr : https://github.com/kangax/fabric.js/commit/f4385b2de9bf08ac3dae514bc809dba8ba98f669

Tha was fixing some importing problem very good.

Also we were thinking that and user, when changing color of stroke, should not expect changes in dimension of object, because he just changed a color.
So passing strokeWIdth = 0 as default was the second thing.
This on the otherway would surprise all other developer that updating fabricjs would see theyr border disappear because they set up just the color.

I agree with you that the toDataUrl should not produce changes.

**Comment by Lenggries** [comment]
Understood. That's a pickle of a problem. Thanks again

**Comment by asturur** [comment]
image strokeWidth is now default at 0.
