### ISSUE TITLE
How can i keep fixed size on some elements of a group object while the rest elemets are scaling?

### ISSUE THREAD

**Issue by tornado1979** [kangax/fabric.js#1973]
hello, 
 
i use fabric.group() , to group some objects together and rotate , move as one object.
But when i scale that object (group object), i want some elements to have stable size while some others scale responsivly.

this is a working example in jsfiddle where i have a circle object and around it another 12 circles, i need to scale that object but the surround small circles should remain at the same size.

link: https://jsfiddle.net/tornado1979/g1Lpq3ud/45/

please can anyone tell me how can i keep on some elements the same size/scale,radius etc, when i scale a group object?

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group — https://groups.google.com/forum/#!forum/fabricjs — where someone will usually assist you.

The issue tracker is only for bugs and feature requests.

Thanks for your understanding!
