### ISSUE TITLE
IText letter spacing

### ISSUE THREAD

**Issue by m2broth** [kangax/fabric.js#1974]
Does Fabric supports the functionality as letter spacing? If not, how can i implement it by the simple way?

**Comment by kangax** [comment]
We have it on the [roadmap](https://github.com/kangax/fabric.js/wiki/Roadmap,-TODO). Perhaps in the next few months or so.

**Comment by m2broth** [comment]
https://jsfiddle.net/hms4y9hq/ I have implemented the base feature of the letter spacing for the IText

**Comment by m2broth** [comment]
I will be glad to comments

**Comment by kangax** [comment]
@m2broth there's couple more things to account for. I just added a wiki section on what to account for when adding new feature — https://github.com/kangax/fabric.js/wiki/How-to-contribute-to-Fabric

**Comment by asturur** [comment]
I m more worried about performance, with this draft it looks like you are gonna render char by char even if letterSpacing is default.

Also SVG export should be take in account with tons of TSPAN. ( as of now TSPAN is required just for make new lines ).

**Comment by m2broth** [comment]
Andrea, you are right. But in the my project this is more optimized way as to use any other solutions. In additional, i can to render the text to the path (use svg glyphs), but it is very huge solution. But, anyway, this is not the end result. Thanks for the reply

**Comment by alexFC89** [comment]
m2broth, How do I use the code you wrote? 
I tried to add it to the src but textlines is null.

**Comment by ghazaltaimur13** [comment]
I tried implementing this feature and came up with this https://jsfiddle.net/ghazaltaimur/bx0f4qpg/1/ by extending _renderChar. I have made a couple of additions. The code allows letter spacing to be applied on the selected text instead of only on the whole object.
Plus itext selection ,bounding box and cursor position have to be taken into account if letter spacing is to be added. I have tried to cover these aspects as well. There might be a couple of issues which still need to be fixed plus.

**Comment by asturur** [comment]
Ideally we want support letterspacing on
Text object and all derivates + style on all object that supports it.

If you want to try implementing it i will review your pr till it is adequate for integration, if you have no time do not worry.

**Comment by asturur** [comment]
https://github.com/kangax/fabric.js/pull/3097/files

this is a working branch, some defect to fix with cursor at end of line.

**Comment by asturur** [comment]
I pushed in the code support to get charspacing (text.charSpacing, numeric in thousandth of fontSize). SVG support and unit tests will come later.

**Comment by saadqbal** [comment]
@ghazaltaimur13 Can you implement it for Text as well?

**Comment by asturur** [comment]
feature is releases officially

**Comment by temuri416** [comment]
@asturur What is the estimate for implementing charSpacing in SVG export?

Thanks!

**Comment by asturur** [comment]
mmmm i ll give a shot tomorrow to figure out how much is hard.

**Comment by AvaelKross** [comment]
https://github.com/kangax/fabric.js/pull/3718
