### ISSUE TITLE
Record and playback of all activity happened on fabric canvas

### ISSUE THREAD

**Issue by zigs** [kangax/fabric.js#1977]
Hi,

Can fabric keep track of event fired in canvas and related object(upon which event was fired ) in one big set (in short Recording of fabric canvas), so that by iterating over that set we can actually play back and show all activity performed on canvas.

Have a look at this:
link: http://ramkulkarni.com/blog/record-and-playback-drawing-in-html5-canvas/
source: http://ramkulkarni.com/temp/2012-10-03/js/RecordableDrawing.js
demo: http://ramkulkarni.com/temp/2012-10-03/

I have made such a plugin like this, but only problem i had is about free drawing mode of fabric (I can get point on "mouse:up" but for that i have to get every property like style, strokewidth, color of point and store them along with point, which is very hard for me as of now!!).

So, can anyone look at link i have provided and replay whether is it possible or not?

Already had a look at #1431 but this doesn't make sense.

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group — https://groups.google.com/forum/#!forum/fabricjs — where someone will usually assist you.

The issue tracker is only for bugs and feature requests.

Thanks for your understanding!
