### ISSUE TITLE
Export SVG with external image

### ISSUE THREAD

**Issue by christianhxc** [kangax/fabric.js#1980]
I need to edit the exported svg with Illustrator, but the problem is that when I include an image object with the src from an external server, Illustrator can't open it, I think it is because this image needs to be embedded. If I open the same svg in IE it loads correctly but after the image referenced has been downloaded. Here is an example of the exported svg, if you see the content it has an image element with xlink:href, is it possible that this image can be embedded?

I'm using the function loadSVGFromURL to include other svg files and when exported I'm not having problems. I couldn't find a similar function to do the same job but for other type of images (png for example).

Here is the link of the svg file with the problem: https://www.dropbox.com/s/j0xlnv0ilrqpogr/exported.svg?dl=0

**Comment by asturur** [comment]
look is an issue i found also for me and i was planning an alternative.

**Comment by cmelendezapparkitekt** [comment]
@asturur what other alternatives you think there are? I was even planning to convert the image to svg before adding it to the canvas so I can use the loadSVGFromURL, but I haven't found how to do it yet.

**Comment by asturur** [comment]
i didn't mean other alternatives than this, i meant that i wanted to have images embedded, and so i was thinking something like that. toSVG(embed true or false). Is a fresh problem for me and i was still arguing what is best.

**Comment by christianhxc** [comment]
@asturur and if anyone else face the same problem, I found a solution based on this question http://stackoverflow.com/questions/6249664/does-svg-support-embedding-of-bitmap-images

So, what I did was to encode to base64 the image and replace the content with the URL, here is the corrected svg http://stackoverflow.com/questions/6249664/does-svg-support-embedding-of-bitmap-images

When I open it with Illustrator it doesn't give me any error :)

In case you are wondering how to encode the image, with nodejs you can do it like this: http://stackoverflow.com/questions/17124053/node-js-get-image-from-web-and-encode-with-base64

**Comment by asturur** [comment]
@christianhxc  do not worry, solution is clear and doable with existing fabric.js code.
We have image toDataURL and of course we can substitute it.
For every image in the canvas we have correspondent img element wich has data in it, so we do not need to grab image from web. is already there. just use toDataURL.

**Comment by christianhxc** [comment]
@asturur thanks, you are right, I I'll use toDataURL :)
