### ISSUE TITLE
Top/Left values are not relative to object's center

### ISSUE THREAD

**Issue by flyingL123** [kangax/fabric.js#1983]
Hello, I was reading over the "Fabric gotchas" here:

https://github.com/kangax/fabric.js/wiki/Fabric-gotchas 

And noticed that it says newly created objects will have their top/left values based on the object's center, but from what I've seen this is not true. It seems that objects top/left values correspond to their top and left by default, meaning, originX = left and originY = top.

Is this just outdated information or am I doing something wrong? I'm new to fabric.js.

The following seems to contradict the information on the page:

    var circle = new fabric.Circle({ top: 140, left: 230, radius: 75, fill: 'green' });
    circle.originX; //outputs 'left'
    circle.originY; //outputs 'top'

**Comment by kangax** [comment]
Yep, it's an old information. Sorry about confusion! We should update the wiki.

**Comment by kangax** [comment]
Updated
