### ISSUE TITLE
DrawBorders fuzzyness

### ISSUE THREAD

**Issue by coulix** [kangax/fabric.js#1984]
While investigating fuzzy borders when updating my old fork I realized that borders and corners are "redrawn" several times over. The result is not obvious but once I added 

https://github.com/kangax/fabric.js/blob/master/src/mixins/object_interactivity.mixin.js#L283

   ctx.beginPath();

Everything was much sharper.

**Comment by asturur** [comment]
can you provide a comparision screen?
becauae i never noticed fuzzyness.

take in consideration that now if you updated an old fork, the control may be on an half pixel offser. this may bring to fuzzyness

**Comment by coulix** [comment]
Looking back at it it must have been from my fork rotten code as the demos on fabric look fine.
