### ISSUE TITLE
Focus craziness on iOS with iText

### ISSUE THREAD

**Issue by KJTsanaktsidis** [kangax/fabric.js#1985]
In the current fabric release, typing text in an iText in Chrome causes the window to scroll to the top of the screen. In order to fix this, I cherry picked https://github.com/kangax/fabric.js/commit/b716a56e2cbbaa3c53fab9a3ed4fa9459b93045e into my copy of fabric.js. This fixed the focus issue on Chrome, but led to even worse things on iOS.

With the above cherry picked into my fabric, typing in iText on iOS causes the window to scroll to the bottom of the screen. This is because the textarea is `position: fixed;`, which on iOS allows the page to scroll behind the position fixed thing.

To fix this in our project, I have duck-punched window.fabric.iText.prototype.initHiddenTextarea to put the hidden textarea at the same vertical position as the iText. When the iText moves relative to the DOM for whatever reason, the position of the hidden textarea should be updated.

My monkey patch looks like this.
```javascript
//Apply violence to the stupid hidden input stuff to make iOS show the keyboard

(function(){
    var __initHiddenTextarea = window.fabric.IText.prototype.initHiddenTextarea;

    function initHiddenTextarea(){
        this.hiddenTextarea = fabric.document.createElement('textarea');

        this.hiddenTextarea.setAttribute('autocapitalize', 'off');
        this.hiddenTextarea.style.cssText = 'position: absolute; opacity: 0; font-size: 1pt;' +
                                            ' left: -9999px; width: 8888px; height: 10px; z-index: -999;';
        if (this.canvas && this.canvas.wrapperEl) {
            this.canvas.wrapperEl.appendChild(this.hiddenTextarea);

            this.on('event:scaling', this.canvas.updateHiddenTextareaPosition.bind(this.canvas));
            this.on('event:moving', this.canvas.updateHiddenTextareaPosition.bind(this.canvas));
            this.canvas.updateHiddenTextareaPosition();
        } else {
            fabric.document.body.appendChild(this.hiddenTextarea);
        }

        //This was in the original initHiddenTextarea
        fabric.util.addListener(this.hiddenTextarea, 'keydown', this.onKeyDown.bind(this));
        fabric.util.addListener(this.hiddenTextarea, 'keypress', this.onKeyPress.bind(this));
        fabric.util.addListener(this.hiddenTextarea, 'copy', this.copy.bind(this));
        fabric.util.addListener(this.hiddenTextarea, 'paste', this.paste.bind(this));

        if (!this._clickHandlerInitialized && this.canvas) {
          fabric.util.addListener(this.canvas.upperCanvasEl, 'click', this.onClick.bind(this));
          this._clickHandlerInitialized = true;
        }
    }

    //We need to slap this on fabric, so that if we do something to change the position of the
    //textarea on the screen by e.g. resizing or zooming the canvas, we can move the hidden
    //textarea appropriately.
    function updateHiddenTextareaPosition() {
        //The text's bounding rectangle, IN CANVAS SPACE (not fabric logical coordinates)
        var itextObject = this.getActiveObject();
        if (itextObject && itextObject.isEditing) { //If not iText, will return false
            if (itextObject.hiddenTextarea.parentNode === this.wrapperEl) {
                var rect = itextObject.getBoundingRect();
                itextObject.hiddenTextarea.style.top = rect.top + 'px';
            }
        }
    }

    window.fabric.util.object.extend(window.fabric.IText.prototype, {
        initHiddenTextarea: initHiddenTextarea,
    });

    window.fabric.util.object.extend(window.fabric.Canvas.prototype, {
        updateHiddenTextareaPosition: updateHiddenTextareaPosition,
    });
})();
```

This seems to be working for me as expected. My questions are twofold.
- Are there any other circumstances in which `canvas.updateHiddenTextareaPosition()` will need to be called? Zooming comes to mind, but I'm not sure what the right events are to listen on.
- Is this an approach which the fabric maintainers agree with? If so, I'm happy to convert this into a proper PR

**Comment by Stefanoviic** [comment]
Any update / fix for this problem that is approved?

**Comment by Stefanoviic** [comment]
For my tool, this did the trick:

/**
   * Initializes hidden textarea (needed to bring up keyboard in iOS)
   */
  initHiddenTextarea: function() {
	  
	var object = canvas.getActiveObject();
	var offset = $("#canvas").offset();
	var totalleft = offset.left + object.left;
	var totaltop = offset.top + object.top;
	
    this.hiddenTextarea = fabric.document.createElement('textarea');

    this.hiddenTextarea.setAttribute('autocapitalize', 'off');
    this.hiddenTextarea.style.cssText = 'position: fixed; top: '+totaltop+'px; left: '+totalleft+'px; opacity: 0;'
                                        + ' width: 0px; height: 0px; z-index: -999;font-size:0pt;';
    fabric.document.body.appendChild(this.hiddenTextarea);

    fabric.util.addListener(this.hiddenTextarea, 'keydown', this.onKeyDown.bind(this));
    fabric.util.addListener(this.hiddenTextarea, 'input', this.onInput.bind(this));
    fabric.util.addListener(this.hiddenTextarea, 'copy', this.copy.bind(this));
    fabric.util.addListener(this.hiddenTextarea, 'paste', this.paste.bind(this));

    if (!this._clickHandlerInitialized && this.canvas) {
      fabric.util.addListener(this.canvas.upperCanvasEl, 'click', this.onClick.bind(this));
      this._clickHandlerInitialized = true;
    }
  },

**Comment by asturur** [comment]
@kangax do you have ipad to check if this fiddle http://jsfiddle.net/asturur/7fsw81mp/12/ still suffer from focus problem on itext editing?
I modified the way the hidden input is positioned.

**Comment by kangax** [comment]
@asturur I don't see any text on iPad at all

**Comment by asturur** [comment]
i have broken lib on my repo. all my fiddles are down.
