### ISSUE TITLE
can't  load back the exported  JSON with loadFromJSON

### ISSUE THREAD

**Issue by jothikannan** [kangax/fabric.js#1994]
Hi,

i want to export the svg created with the fabric.js, so am doing follow to load and save

check my fiddle : http://jsfiddle.net/7sewwjn4/4/

but it sounds like a bug, that my JSON have some elements like 

`'\n': {"source":"function () {\n patternSourceCanvas.setDimensions({\n width: img.getWidth() + padding,\n height: img.getHeight() + padding\n });\n return patternSourceCanvas.getElement();\n }` 

so it causing the error when load it back with the `loadFromJSON`. is this is the bug or what kind of issue this is? am trying myself to fix it by last one week. help me.

**Comment by asturur** [comment]
in the code you post there is many things i cannot even figure out what they are doing.
there are button with load svg that are loading a png and buttons that does not exist.
please make a minimal test case that expose what you think is a bug.

anyway your pattern has a function as src. i do not know if this is supported.

**Comment by jothikannan** [comment]
Hi @asturur 

check the modified fiddle : http://jsfiddle.net/7sewwjn4/6/

i thought that my pattern have the function as src, that is the problem here. i checked over that if we created the dynamic pattern, it cause this kind of problem.

**Comment by jothikannan** [comment]
Hi @kangax 

i have posted the questions in both google groups and stackoverflow, but still i didn't get any assist form anyone.kindly look on it. and let me know what is wrong. am new to fabric.js.

**Comment by jothikannan** [comment]
Hi @kangax 

i can see that you are replied for some other issues posted here and google group also. but am not getting any answer from your end for my question? is am doing anything wrong ? let me  know this is bug or issue from my end. so i can decide what i want to do. waiting for your assist.

**Comment by asturur** [comment]
@jothikannan i have looked in the issue also, i dedicated at it at least 20 minutes to both fiddles.
We do not have any magic wand ( @kangax if you have and you never told me, you are bad! ) sometimes is very hard to find out if is a deep, never found bug, if is a missing feature never requested ( like pattern to object missing ).
Are you sure is not possible to do a smaller test case?
We'll do our best, does not mean we are so fast.

**Comment by jothikannan** [comment]
Hi @asturur 

thanks for the reply. Actually am not expert with the fabric.js. i tried my level best to fix it. but unfortunately none of my test cases are not working. so am posted the issue here.

**Comment by kangax** [comment]
@jothikannan hm, let's say you have a full-time job + get few questions on google group every day + few issues on GitHub every day + few issues on other projects on GitHub every day + occasional emails every day, and each one of those might take anywhere from 5 mins to 1+ hour of your time (if you need to think about issue, understand it, possibly fix it, write about it, and so on). How do you fit it in your 8-10 hours available for work? Let's say you spend 6 of those hours on work, 1 hour on reading/catching up with the latest development, etc., and so you have 1-3 hours left on open source work. Let's average that to 2 hours. So we have ~5 questions + ~5 issues + ~5 issues + ~5 emails. That's approximately 20 things. Each could take anywhere from 5 mins to 1hour. If we average that to 30 mins, that's 20 x 30 mins = ~10 hours. Now, how do we fit 10 hours worth of work into 2 hours? If you have an answer to that question, I'll gladly hear it out.

**Comment by jothikannan** [comment]
Hi @kangax 

Thanks for your advice. Am not doing as you said everyday `get few questions on google group every day + few issues on GitHub every day + few issues on other projects on GitHub every day + occasional emails every day`. Am just posting what am getting. is am posting irrelevant posts or doing something wrong ?
I am trying my level best to resolve the issues am facing. if am not then only am posting the issue to concern branch. is it wrong ? and i concluded that it is looks like a bug. so only posted the question here. and am not expert like you in fabric.js am newbie. if am doing anything wrong here. am extremely sorry about it. if i fix the issue i will surely post the answer here.

**Comment by asturur** [comment]
@jothikannan,
kangax was simply saying, we got lot of request, we do not have time to manage them all.
some are easy and immediate amd we clear them, other require time.
i do not want to sound dull, you have just to wait.

**Comment by jothikannan** [comment]
Hi @asturur 

i can understand that we can't fix this kind of bugs in short time, it need some time to resolve it. but i just asked here that it is a bug or it is my mistake, if it is my mistake i will try my level best to complete it. Anyhow am also working to fix it, lf i get fixed it i will post the answer

**Comment by Godweed** [comment]
I am facing the same issue, is there any advice to fix it. I can not serialized canvas if dynamic pattern is applied to object.

**Comment by serkyen** [comment]
I am having the same problem two years later. Anyone know how to fix this? 

- Applying dynamic pattern onto object.
- Saving the canvas to MongoDB using...
- Loading the canvas using 'loadFromJSON'
- getting error 'Uncaught ReferenceError: patternSourceCanvas is not defined'

Any help would be much appreciated.

**Comment by vee2046** [comment]
Now I am having the same problem, anyone know how to fix this?

**Comment by asturur** [comment]
Hi @vee2046 please include a jsfiddle link where your specific problem is reproducible within a small test case
