### ISSUE TITLE
loadFromDatalessJSON svg fill color do not applied

### ISSUE THREAD

**Issue by Godweed** [kangax/fabric.js#1995]
if the svg object is multi color, fill color of svg objects paths do not stored when you use the toDatalessJSON and loadFromDatalessJSON functions.

**Comment by Godweed** [comment]
when I added full path it able to load some of svg files but mainly gives below error file 
/usr/lib/node_modules/fabric/node_modules/xmldom/dom-parser.js:187
	    throw error;
	          ^
end tag name: g
   is not match the current start tagName:undefined
error: Forever detected script exited with code: 8
error: Script restart attempt #3
unclosed xml attribute 
@#[line:3,col:1]

unclosed xml attribute 
@#[line:5,col:3]
end tag name: g

   is not match the current start tagName:undefined 
@#[line:18,col:7]

/usr/lib/node_modules/fabric/node_modules/xmldom/dom-parser.js:187
	    throw error;
	          ^
end tag name: g

svg file can be loaded in client side without problem but the same svg file could not be loaded in server side. but some svg s able to load without problem in client and server side

**Comment by Godweed** [comment]
I have several svg file in library that you can add without problem in client side but none of them loaded in server side. only one svg is able to loaded without problem . Also another issue is when you change the fill color of the path group server side did not change the color, the scale vs works but fill color change of paths inside the svg file remains the same at server side

**Comment by kangax** [comment]
Please create a minimal example
