### ISSUE TITLE
Tainted Canvas issue with Google Cloud Storage

### ISSUE THREAD

**Issue by paulcanning** [kangax/fabric.js#2008]
I am currently having issues after moving my application over to Google App Engine and Cloud Storage.

My application(written in PHP) gathers object data from the database (text and images) and creates a JSON object that is then passed to a View, and interpreted by FabricJS' "loadFromJSON" method.

The images are stored on GCS and the URLs are created in the PHP script using the GCS API. The bucket they are stored in also has an "Access-Control-Allow-Origin" header set to *, to allow access from anywhere.

LoadFromJSON loads the images fine, all correct and present. However, when trying to use "toDataURL" I get the error "Uncaught SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': tainted canvases may not be exported."

Now, I understand some methods for loading images (such as fabric.util.loadImage()) allow a cross domain setting. But loadFromJSON doesn't.

So, why would the error appear despite the CORS settings being correct?

And, how do I fix this? I need to use loadFromJSON.

EDIT - I made a quick jsFiddle (here - http://jsfiddle.net/hs9spxL4/) that shows the issue. the two images are served from GCS, using "getImageServingUrl". If you access them directly, you should see the Access-Control-Allow-Origin header set to *. But if you click the button, you should see the error message in the console about the tainted canvas.

**Comment by Kienz** [comment]
You can just set `crossOrigin: "anonymous"` for you image objects.
http://jsfiddle.net/hs9spxL4/2/
