### ISSUE TITLE
Padding bounding box bug

### ISSUE THREAD

**Issue by m2broth** [kangax/fabric.js#2009]
When you set the padding of the object on the canvas (e.g obj.set({padding:30})) the bounding box is displaying correctly, but the area for the mouse events of the bounding box corners is broken. It's make problem for scaling and rotating objects with a padding property. This bug appears only in the 1.4.13 version

**Comment by asturur** [comment]
I cannot replicate the bug on kitchensing.
I have bot bounding box and corner working good.
Can you make a fiddle?

**Comment by m2broth** [comment]
Oh, this bug according to the previous version of the fabricjs. The Bower can't get the last commit of the fabric js. Can you know why this happens?

**Comment by asturur** [comment]
Last version is 1.4.13. Probably bower has this still loaded.
After 1.4.13 ( 3 months ) we pushed many fixes.

Please before submitting a bug, always try the lastest code.

**Comment by m2broth** [comment]
Can you fix the bower issue?

**Comment by asturur** [comment]
I think that bower will be updated with 1.5.0, or if we are too slow with version 1.4.14
But till it stays 1.4.13 i think bower will stay like that.
