### ISSUE TITLE
Clone isn't supported same way among object types

### ISSUE THREAD

**Issue by hellomaya** [kangax/fabric.js#2010]
Even though, method clone from the docs among all object types is described same, but it really doesn't work the same way, for example, Circle didn't support callback, instead it will return cloned instance directly, but Group does support callback, and no cloned instance returned directly.

var cloned = el.clone(...); // Circle, correct
var cloned = el.clone(...); // Group, wrong

el.clone ( function (c) {....}, ...) // Circle, wrong
el.clone ( function (c) {...}, ...) // Group, correct

**Comment by kangax** [comment]
This is something we want to fix (make consistent). It's because some objects are async (e.g. images, or groups, that could contain images) and others are not — circle, rect, path, etc.
