### ISSUE TITLE
Clone doesn't really including properties correctly

### ISSUE THREAD

**Issue by hellomaya** [kangax/fabric.js#2011]
If we go with el.clone (function (c) {}, ['a', 'b', 'c']), and we do have a, b, c new properties, this time, c is an object which it will include Objects, then the cloned instance will share the same reference to those Objects, not really clone them with new Objects but same value.

**Comment by asturur** [comment]
yes clone as of now stops at first level of objects.

**Comment by hellomaya** [comment]
Got it, so I used JSON.parse(JSON.stringify(target.c)) manually its fine too, thanks for your reply.
