### ISSUE TITLE
Trouble loading text from SVG

### ISSUE THREAD

**Issue by stevesherri** [kangax/fabric.js#2014]
I am building an online playing card builder with FabricJS which is working great, but I have one problem...  The app saves the card design on our server as an svg.  I want them to be able to go back and edit the svg in the app.  I have been able to have the app load the svg into separate objects on the canvas, but the text is a text object and I need it to be an iText object.  When I load all the specs (fontSize, fontFamily) I can programmatically recreate the text as an iText object, but it has 2 issues-
1) The top and left positions are not placing the iText in the correct position
2) (Bigger issue) the line breaks from the original text object are not carried over into the iText object... all the text comes in on one long line.

I apologize in advance if I have done this wrong as I've never used github, but here is a link to the repo I set up:

https://github.com/stevesherri/SVG-Text

If you want to see the actual it is:

http://playingcardsrus.com/SVG-IText/index.php

I appreciate any assistance you can offer.

Any Suggestions?
Thanks!
Steve

**Comment by asturur** [comment]
Please SVG is not a format to store information, use just for output.
Use the object form of fabricJs for loading / restoring purpouse.

Exported SVG cannot be imported again, and for this we have no immediate solution.
Neither plan to fix it soon.

**Comment by asturur** [comment]
did you solve the issue using load from object and saving to object?

**Comment by flappymonkey** [comment]
did this problem solved? @stevesherri

**Comment by flappymonkey** [comment]
Exported SVG cannot be imported again, and for this we have no immediate solution.
did you have solution now? @asturur

**Comment by asturur** [comment]
text spans are still not supported, but generally the svg import has improved
