### ISSUE TITLE
callback is not optional in fabric.Image.fromURL

### ISSUE THREAD

**Issue by flyingL123** [kangax/fabric.js#2015]
According to the documentation, the callback parameter in fabric.Image.fromURL should be optional. However, if I try to load an image without passing in a callback, I get an error saying `undefined is not a function`.

For example, running this:

    var img = fabric.Image.fromURL('/path/to/img')

will return an error that `undefined is not a function`. Looking at the source for this function, I don't see anything indicating this parameter is optional. It looks like the function calls `util.loadImage`, for which the callback is required, so this is probably just a documentation error for `fabric.Image.fromURL`.

**Comment by kangax** [comment]
It should be optional. Fixed in https://github.com/kangax/fabric.js/commit/1dff79c2adf081b480a3530048f81f75e29f38c6 Note that created image object is passed to a callback; it's not returned from a function (as in your example).
