### ISSUE TITLE
how to add tooltip to object icons like rotate

### ISSUE THREAD

**Issue by myselfgaurav** [kangax/fabric.js#2017]
i have added few icon to object control
like remove icon 

removeIcon = new Image();
removeicon.src='a.png';

now i want to add tooltip to this icon how can i do it please guide. or is there already feature to trigger any action on hover like alert or else

**Comment by lukluk** [comment]
tooltips from title property?

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group — https://groups.google.com/forum/#!forum/fabricjs — where someone will usually assist you.

The issue tracker is only for bugs and feature requests.

Thanks for your understanding!
