### ISSUE TITLE
How to create more custom shapes with fabric for example Heart shape

### ISSUE THREAD

**Issue by Noumankhan80** [kangax/fabric.js#2019]
Hi Kangax, Thanks for making a great API that is very helping for developer like us. Can you tell me that how I can create custom shapes that may be complex. If I uses path then I can not give it color I have to make it through canvas. Can you give me example , Can you make heart shapes that work with fabric. , Thanks in advance

Sorry for my english.

**Comment by sapics** [comment]
I found good example at http://jsfiddle.net/drzaus/u4g55sxm/.

**Comment by asturur** [comment]
For generic shapes you have to use the "path"object and build your path with some vector graphic tool.
There won't be a special class for every shape. The fiddle posted is a correct example.

**Comment by Noumankhan80** [comment]
@asturur @sapics  This fiddle example is good but the issue with creating shapes via path is that I can not change its color as I can change color or basic shapes. Is there any way to do that ?

**Comment by asturur** [comment]
no you are wrong. please check better the fabricjs.docs.
Il 07/mar/2015 22:06 "Noumankhan80" <notifications@github.com> ha scritto:

**Comment by Noumankhan80** [comment]
@asturur I am little confuse.May be I am wrong , I want to re-confirm that.... Can I change the color via color element while working live with color changing option using color control (as we can change color of text and basic shapes )  or shapes that created from path element. Also as you said " build your path with some vector graphic tool. " Would you suggest any online tool. 

Thanks in advance for help.

**Comment by sapics** [comment]
@Noumankhan80 Do you wish to change color from text box? I forked the fiddle and created example at http://jsfiddle.net/sapics/ja7hfyLa/. Sorry, I am not good at English. Is this example enough for you?

**Comment by Noumankhan80** [comment]
@spaics Thanks Bro, This is I am looking I will add this to my code and see its working. If goes to wrong side I will let you know and will be thankful to you on your feedback. 

I have another issue hope you can solve this too... Its about iText . When we scale text object , text with this control stretch too. regard to image or shapes or path its correct. but for text its not good . can we change its function and create space on scaling so the looked wrap . Understand ?

**Comment by sapics** [comment]
@Noumankhan80 I'm glad I was of help to you!
I guess that your issue is https://github.com/kangax/fabric.js/pull/1778, which will be merged soon.

**Comment by Noumankhan80** [comment]
@spacis, how can I convert vector image into path... As you created heart via path is there any source that help to generate that code ? for example if I need to create tick mark so how I convert that shapes into path code

**Comment by asturur** [comment]
you should check some svg based clipart and extrat path you need. otherwise you can draw them with inkscape.
that code is standard path drawing commands.

**Comment by Noumankhan80** [comment]
@asturur Thanks for your reply. But my question was not design vector image its about converting vector image and get code to create path shapes. As heart example is given I do not know how to get these code and added to path so get the perfect shape. Is there any online converter tool or learning site that help to understand how to draw or create path command for drawing. 

I am new in this section, So please do not mind my question.

**Comment by asturur** [comment]
adobe illustrator probably. or corel draw, inkscape. raster to vector is not a simple task. is easier to google for the path you need. like "checkmark svg" or "checkmark vector"

**Comment by Noumankhan80** [comment]
@asturur , No I think I am not explaining well what I want. I want to create shapes in fabric, as I got this example of making heart with path class below. 

var path = new fabric.Path('M 272.70141,238.71731 \
    C 206.46141,238.71731 152.70146,292.4773 152.70146,358.71731  \
    C 152.70146,493.47282 288.63461,528.80461 381.26391,662.02535 \
    C 468.83815,529.62199 609.82641,489.17075 609.82641,358.71731 \
    C 609.82641,292.47731 556.06651,238.7173 489.82641,238.71731  \
    C 441.77851,238.71731 400.42481,267.08774 381.26391,307.90481 \
    C 362.10311,267.08773 320.74941,238.7173 272.70141,238.71731  \
    z ');    

I do not know how to create that codes to make heart shapes. So is there any online tool that give those code or any website that is teaching how to make those code to create shapes. 

Understand what I want ?

**Comment by asturur** [comment]
you explained perfectly. 

the answer is that. draw your shape in illustrator, save as svg, open svg with notepad and extract the path data.

Or google for the svg you are searching, download it, open with notepad and extract path data.

there is no tool to convert from jpg to path in easily way.

**Comment by Noumankhan80** [comment]
@asturur Yes Now you got my point and tell me exact what I have to do. That's work. I have another issue and need help in those area should I create new repository for that or we can discuss over there. ?

**Comment by gunjaliagarwal** [comment]
Hi Kangax,
I got this http://jsfiddle.net/drzaus/u4g55sxm/ for heart shapes.
My issue is i want to give image except red color for canvas object.Can u help?

**Comment by neilliang** [comment]
//Replace the color 'red' to the color you need.
path.set({ left: 20, top: 0, scaleX: scale, scaleY: scale,  fill: 'red', });
