### ISSUE TITLE
Regarding Text control wrapping.

### ISSUE THREAD

**Issue by Noumankhan80** [kangax/fabric.js#2026]
@jafferhaider Your created example is waht I am looking . Textcontrol behaviour when scaling is the correct way I needed. , Here is your example : http://jsfiddle.net/jafferhaider/51u08n39/18/ 

I only need to make Text wrapping working. In current fabric Itext . when we scale text , text goes large. It should wrap as in your example. Can you send me updates separately ? Which file need to update and what more code need to add ? I am new user of fabric . Also sorry for my poor english.

**Comment by asturur** [comment]
Please use google group for generic questions about coding.

use github for file issue or for feature request.

if there is an open issue regarding what you are looking for, use that already open. (#1778)
