### ISSUE TITLE
CANVAS DRAWING MODE NOT WORKING AFTER APPENDING ANY HTML ELEMENT USING FABRIC JS

### ISSUE THREAD

**Issue by rajagunasekaran** [kangax/fabric.js#2028]
1.While drawing on canvas, the pointer not pointing corretly when the new element created before canvas element
2.Look demo link: http://jsfiddle.net/szzGa/17/ 
See the differences of drawing , before clicking the APPEND DIV button and after clicking that button.
3.The drawing mode not pointing correctly when i click the APPEND DIV button. Its working properly after clearing the div element using CLEAR button.

Any help would be appreciated...

**Comment by rajagunasekaran** [comment]
One more info, its working While right click  on canvas element and selecting the inspect element after appending the div element with canvas

**Comment by sapics** [comment]
@rajagunasekaran By adding canvas.calcOffset() after append div, it works correctly. http://jsfiddle.net/sapics/xjenL5gn/
