### ISSUE TITLE
A grouped text can select at empty position.

### ISSUE THREAD

**Issue by sapics** [kangax/fabric.js#2029]
After two texts selected by mouse, each text can select at empty position. http://jsfiddle.net/sapics/wgcvbe2L/

![text](https://cloud.githubusercontent.com/assets/11169954/6591682/b432de76-c806-11e4-967b-823cc356d2aa.png)

I could not identify an underlying cause, thus, I fixed ad hocker way which grouped object cannot be a target.
https://github.com/sapics/fabric.js/commit/bd5646e7b00dbd5161788eb1c1379c6325713d7b#diff-9dc132ed9a0787568f773999ba577e2bR789

**Comment by kangax** [comment]
I don't understand the issue here. Could you explain?

**Comment by sapics** [comment]
Sorry, about my bad English.
Now, there is a same issue at #2034.
Therefore, I close this issue.
