### ISSUE TITLE
Mouse hover coordinates are incorrect with Grouped objects

### ISSUE THREAD

**Issue by gordyr** [kangax/fabric.js#2034]
When you have one or more objects grouped, the mouse does not interact at the correct points (most of the time).

This bug is very easily reproducible. Load up the Kitchensink demo and perform a mouse selection to group the two ```IText``` objects.  Then move the mouse cursor to the left of the group and you will see that the cursor stays set to the ```move``` cursor.

Strangely this only occurs when your mouse cursor is higher than the ```center``` of the group.  If you move the mouse below the ```group``` is hit detected correctly by the cursor and changes accordingly.

If, while in this state you click the canvas, the ```Itext``` object on the left will be selected since fabrics coordinate system believes that the object is underneath the cursor when in fact it is not.

Here is a screenshot showing the grouped object being detected by the mouse even though the cursor is to the left of the group itself.

![problem](https://cloud.githubusercontent.com/assets/1015403/6608376/56591f62-c83e-11e4-8c4b-f8a93e49c902.jpg)

**Comment by gordyr** [comment]
**Update**

Okay I have been able to fix the issue with a single line in ```_searchPossibleTargets```

And I know understand why this bug exists...

When moving the mouse fabric first checks for any active groups and performs a check to see if the mouse is over them. If so it returns ```true```.

If not... then fabric calls ```_searchPossibleTargets``` which loops through all objects and checks to see if the mouse is over them.

This works perfectly.... However when you create an active ```group``` fabric internally moves the coordinates of the grouped objects.  e.g. a ```Rect``` might be at ```left : 500``` but when it is in an active group it could be ```left : -300```.since we are now inheriting the transformation of the ```group itself```.

The problem here is that when there is an active group ```_searchPossibleTargets``` will return a ```target``` for those grouped objects, which are now on a different coordinate system.

Since we are already checking for hits in active groups and returning beforehand an easy fix is to skip the checking of any objects which are currently in an active group like so:

```
_searchPossibleTargets: function(e) {

            // Cache all targets where their bounding box contains point.
            var target,
                pointer = this.getPointer(e, true),
                i = this._objects.length;

// Add check below to skip any objects which are currently in a group
            while (i--) {
                if (!this._objects[i].group && this._checkTarget(e, this._objects[i], pointer)){
                    this.relatedTarget = this._objects[i];
                    target = this._objects[i];
                    break;
                }
            }

            return target;
        }
```


This totally corrects the problem.  Another solution would be to account for grouped objects within ```_checkTarget``` by using the ```originalLeft``` and ```originalTop``` values instead of checking against ```oCoords```....  

But that seems totally unnecessary.

Although I don't have much time for this stuff right now I'll create a quick PR since it is such a tiny fix.

**Comment by asturur** [comment]
ocoords keep differnt data than originalLeft and originalTop. those are canvas space coordinates precalculated to speed up the checks with mouse coords.

**Comment by gordyr** [comment]
@asturur Indeed, I am well aware of that.  

My point was that, checking against the ```oCoords``` for an object within a group, will produce false target matches since their ```oCoords``` are different while grouped.  

If we really wanted to check for matches of grouped objects (instead of the group as  whole) we can still do so currently by accessing the ```originalLeft``` and ```originalTop``` properties that exist for grouped objects so that their previous positions and thus coordinates can properly be restored when a group selection is destroyed.  Taking those values into account, we could engineer an effective check.

But I can't see any reason for needing to  check for individual targets within a group selection, therefore my simple one liner above should be the most elegant solution.

I hope that makes sense.

**Comment by asturur** [comment]
i think it make sense. my comment was just about the original left and original top that are not usable to check target. not about your proposed solution.
