### ISSUE TITLE
Issue with drawing svg onto canvas

### ISSUE THREAD

**Issue by sudheer496** [kangax/fabric.js#2037]
Hi,
I tried to draw the following svg from fabric onto canvas.
http://fabricjs.com/assets/116.svg  
The drawing is not exactly matching the preview.
Currently I used fabric version:"1.4.0".
Here is the fiddle. Try running multiple times you will get the output.
http://jsfiddle.net/oLLvzqa0/

My observations:
When I tried to render the same svg using fabric latest version: "1.4.13" , the drawing is perfect.

So can you let me know the exact commit that fixed the issue with drawing , so that I can merge into my local fabric library.

And also, When I tried to use fabric.loadSVGFromURL to load svg from external url , I got the following error.
"XMLHttpRequest cannot load http://fabricjs.com/assets/116.svg. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access."

But when I tried to load it multiple times it worked for me :) , What's the reason ?

Thanks,
Sudheer

**Comment by asturur** [comment]
better you upload all new fabricjs and commit later some patch if you break some functionality.

svg import was a big effort, is no just some commit.

sorry

**Comment by sudheer496** [comment]
And this is the output with fabric 1.4.13
http://jsfiddle.net/s2x5yk75/


Even merging was huge for me.I modified a lot in fabric.js.
Atleast can you give idea on what are the API's that affect the behaviour like parser or path group etc., so that I can replace/diff only those areas.

**Comment by asturur** [comment]
if you have a custom fabric,
take in consideration parser.js, element-parser.js, for the guitar line.class.js and path.class.svg
misc.js in util folder.

probably more...

lot  of rendering tweaks in each shape.

**Comment by sudheer496** [comment]
Mostly I observed issue with ellipse drawings

**Comment by asturur** [comment]
i fixed most svg import, it has been a long and reiterate effort, that is why i suggest you to update whole library ( swapping file ) and fixing some backward incompatibility eventually

**Comment by sudheer496** [comment]
Some how I manged to fix the issue by changing 'polygon , ellipse, circle classes entirely and render method of fabric.object class'.

That lefts me with only one already mentioned issue.
Can you help me get over this one and whats the reason?
Issue:
"XMLHttpRequest cannot load http://fabricjs.com/assets/116.svg. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access."

**Comment by asturur** [comment]
you cannot load svg from fabricjs.com website from another website with xmlhrtprequest if the.owner of fabricjs does not set  the accesscontrolalloworigin header. copy the svg on your domain.

**Comment by sudheer496** [comment]
Yeah I know that, but what I wondered is when try the  same url to load for 3 to 4 times it got loaded.

Is there any way I can pass 'Anonymus' so that the server can set headers on the response , same as provided for loading image urls

**Comment by asturur** [comment]
http://jsfiddle.net/s2x5yk75/1/

i do not know why you wrap a normal function in jquery bracket. executing as normal js works at first try.

**Comment by sudheer496** [comment]
It doesnt load for me for the first time even with your fiddle, it sometimes loads for the first time aswell.

Attached screen shot, you can find the error in the console
http://postimg.org/image/tom7cnh9x/
