### ISSUE TITLE
Npm expects node < 1.0.0

### ISSUE THREAD

**Issue by leebenson** [kangax/fabric.js#2038]
Minor issue, when building the NPM I get:

`fabric@1.4.13: wanted: {"node":">=0.4.0 && <1.0.0"} (current: {"node":"0.12.0","npm":"2.5.1"})`

**Comment by kangax** [comment]
Is this a problem? :)

**Comment by leebenson** [comment]
Nope, but I get alerts on warnings during the build process, and this one keeps popping up... just an FYI.

**Comment by kangax** [comment]
But... why is there a warning in the first place? 0.12.0 is <1.0.0, isn't it?

**Comment by leebenson** [comment]
actually, that's a very good point! No idea... I'll just suppress the warnings, it's not affecting anything else...

**Comment by friday** [comment]
I also get this warning. Does npm understand the "&&"syntax? I haven't seen it before, but I'm new to this. Otherwise "^0.4.0" means "compatible with "0.4.0", or any 0.x.x version above 0.4.0

**Comment by leebenson** [comment]
I think the syntax should be:

`"0.4.0 - 1.0.0"`

... according to https://github.com/npm/node-semver

**Comment by friday** [comment]
That would include 1.0.0. `"0.4.0 - 0.9999.9999"` should work though.

`"version1 - version2"` is the same as `">=version1 <=version2"`
