### ISSUE TITLE
Angle is missing after importing objects from a SVG

### ISSUE THREAD

**Issue by shareit** [kangax/fabric.js#2039]
I have a problem with some objects that I have imported from a SVG (that has been saved with fabric library). It seems that the rotation angle is not exported or imported correctly from the SVG string.

Here you can find a jsFiddle sample: http://jsfiddle.net/tqLxn0mL/. Open the browser console to see the results.

Thanks,

**Comment by kangax** [comment]
1.4.0 is really old. Please try with 1.4.13

**Comment by asturur** [comment]
Rotation angle will never be imported good from SVG.
There is no rotation angle in svg.
It works like that:

In the moment of exporting a canvas to SVG every object get its: angle, top, left and scale expressed in a transformation matrix. That looks like that: ```matrix(2.3, 0.3242, -0.231, 3, -456, 34)```
When importing back this matrix get applied to the object and does not go back to original left top angle and scale properties.

**Comment by shareit** [comment]
Ok, I understand but .. maybe do you have any suggestion for my issue. 

I have a canvas with fabric where users can add predefined shapes or can draw with a pencil (free drawing). The canvas is saved on the server side as SVG and the SVG is loaded into the canvas to show to the user what he draw on the canvas.

At some moment, the user(s) can see two canvases and they could copy a shape or a free drawing from one canvas to another canvas. The problem is that the two canvases does not have the same size and I need to check if the bounding rect of the shape is smaller or equal with the other canvas size. For this I was plan to use the method getBoundingRect together with the rotation angle.

Is there another method(s) that can be used to find the bounding rect of a rotated shape ?

**Comment by asturur** [comment]
yes.
First of all use canvas.toObject() related methods  to save and reload everything.
Bugs found there will be fixed.

Also use yourshape.oCoords , this object contains:
tl (topleft), tr(topright), bl(bottom left), br(bottom right) corners  in canvas coordinats.
Using those, and selecting maximum X, minimum X, maximum Y, minimum Y you can have idea of an axis oriented rectangle that contains your rotated object.

guys, if you open those questions on SO, you make us a favor.
Someone get reputation ( not me necessary ) , github repo stay clean, we focus on bugs.

I do not know how to explain those concepts without sounding unpolite.

Regards,
Andrea.
