### ISSUE TITLE
Canvas.setOverlayImage callback not being executed when data URL is used

### ISSUE THREAD

**Issue by lzrski** [kangax/fabric.js#2046]
```coffee-script
url = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAfQAAAGLCAYAAAAxomCeAAAgAElEQ…qhe8gTrzjrwxq4v+f8fD4ucdih+9lVdOPQoUeQZZnyqKb/D8zc9x9rCbKKAAAAAElFTkSuQmCC"
canvas.setOverlayImage url, =>
  # This code won't run :(

  canvas.overlayImage.scaleX = canvas.width  / 800
  canvas.overlayImage.scaleY = canvas.height / 800

  do canvas.renderAll
```

I tested that in Chromium Version 41.0.2272.76 and Firefox Developer Edition 38.0a2 (2015-03-12) on Ubuntu 14.04 (64-bit).

The loading isn't synchronous, so calling `.renderAll` after `.setOverlayImage` will render canvas without overlay. The nasty workaround I came up with is to `setTimeout` and render in it's callback.

The interesting side note is that 0 timeout (a'la Node's `setImmediate`) works in Chromium but in Firefox it doesn't.

**Comment by Kienz** [comment]
The loading of images is async even for dataURL images. Only if the image source is available in the ["list of available images"](https://html.spec.whatwg.org/multipage/embedded-content.html#list-of-available-images) the loading is synchronous.
http://stackoverflow.com/a/4807114/2323945

**Comment by lzrski** [comment]
@Kienz Thanks for the links, but I'm not sure how does it relate to the issue.

The problem is not whether it's sync or async. The problem is that callback is not being called. Please consider reopening the issue, as it still affects me.

**Comment by Kienz** [comment]
@lzrski I've created small jsfiddle testcase. The callback of `canvas.setOverlayImage` is called.
http://jsfiddle.net/Kienz/0ok1entw/

Which version of fabric.js do you use?
