### ISSUE TITLE
CanvasRenderingContext2D.webkitImageSmoothingEnabled is deprecated in latest Chrome version

### ISSUE THREAD

**Issue by lorenzopolidori** [kangax/fabric.js#2047]
Chrome version 41.0.2272.89 m shows this warning on the javascript console:
`CanvasRenderingContext2D.webkitImageSmoothingEnabled` is deprecated. Please use `CanvasRenderingContext2D.imageSmoothingEnabled` instead.

**Comment by kangax** [comment]
Well, we're already using `imageSmoothingEnabled` but still need webkit version for older engine versions. I'm afraid nothing we can do about warning.

**Comment by petewalker** [comment]
What about wrapping it in:

```js
if (typeof(ctx.imageSmoothingEnabled) !== 'undefined') {
  ctx.imageSmoothingEnabled       = this.imageSmoothingEnabled;
  return;
}
```

If `imageSmoothingEnabled` is available, it should be type `boolean`. Otherwise it'll be `undefined`.

**Comment by kangax** [comment]
That might work
