### ISSUE TITLE
Image position issue after scaling the image.

### ISSUE THREAD

**Issue by vignesh-indian** [kangax/fabric.js#2048]
I have uploaded two images, I "scaled" those images and positioned it according to my need. Then I exported the canvas to JSON using 'JSON.stringify(canvas)' and saved it to the database. I attached the canvas image below for reference

![final](https://cloud.githubusercontent.com/assets/11572954/6752492/07ffee2e-cf35-11e4-88f7-58506fb07cb0.png)

Now my issue is, when I "import" the saved JSON from database into the canvas, the image position is changed (X & Y axis). I attached that image below 

![issue](https://cloud.githubusercontent.com/assets/11572954/6752538/6c3be942-cf35-11e4-96ed-c2f015e578ae.png)

I have used the fabric for printing solutions. So I need a help to get the image position accurate.

**Comment by asturur** [comment]
could you check your scale factor?
Fabric rounds down to 2 decimal.
You can increment the precision manipulatinc fabric.object.NUM_FRACTION_DIGITS

**Comment by vignesh-indian** [comment]
want to change these two and where?

scaleX: toFixed(this.scaleX, NUM_FRACTION_DIGITS),
scaleY: toFixed(this.scaleY, NUM_FRACTION_DIGITS),

**Comment by asturur** [comment]
Did you check your scale factor before going on?
how much is it?
Check BEFORE going JSON and after.

**Comment by vignesh-indian** [comment]
I have changed the decimal point from '2' to '10'. 
Its working now thank u @asturur

**Comment by DangerD256** [comment]
Same issue i have now on latest 2 version, what should i change now?
 fabric.object.NUM_FRACTION_DIGITS - undefined

**Comment by DangerD256** [comment]
Ah sorry, works, copied "object" lowercase from your old post
