### ISSUE TITLE
Mouse Support in StaticCanvas

### ISSUE THREAD

**Issue by darkfrog26** [kangax/fabric.js#2052]
There seems to be no easy way to receive mouse events for Objects without also having all the baggage of Canvas.  I'm writing a game and want to detect clicking on Objects, but I don't want selection or controls.  I simply want StaticCanvas + mouse events.

**Comment by kangax** [comment]
You can disable selection and controls individually (canvas.selection=false, fabric.Object.prototype.hasControls=false, etc.) Also see customization demo on fabricjs.com

**Comment by darkfrog26** [comment]
canvas.selection does not seem to do anything, and though hasControls is helpful it still shows an outline when I click on the element (to signify selection) as well as the mouse cursor and the ability to drag the element.

**Comment by kangax** [comment]
Hm, not sure what you're seeing. Works for me in http://fabricjs.com/customization/ (both selection off and no controls/borders). If there's still some bug, js fiddle would be great.

**Comment by sklipnoty** [comment]
I stumbled  uppon the same issue. It's not about showing something, it's about the underlying events still being present regardless of what is being shown. (border no border).
