### ISSUE TITLE
i-text with ios 8.2

### ISSUE THREAD

**Issue by alghraibeh** [kangax/fabric.js#2056]
first i am sorry for my english language .

i have problem with i-text in ios after update to 8.2 on safari browser 

when i add more than one text ,text go to visible , i can keep text , just if i am apply style to char 

![image](https://cloud.githubusercontent.com/assets/9897827/6797794/02c96188-d20f-11e4-9d11-20e00abfb23e.png)

note : problem appear after update

**Comment by kangax** [comment]
I don't understand the problem here
