### ISSUE TITLE
loadFromJson, applyFilters Image given has not completed loading

### ISSUE THREAD

**Issue by DanieleSassoli** [kangax/fabric.js#2057]
Hy,
I'm trying to load a json of a canvas in NodeJS, but when i call 
```javascript 
canvas.loadFromJson(jsonString, function(){
    canvas.renderAll()
}); 
```
the problem is that I get an error: 
canvasEl.getContext('2d').drawImage(imgEl, 0, 0, imgEl.width, imgEl.heig
                                ^
Error: Image given has not completed loading
    at klass.fabric.Image.fabric.util.createClass.applyFilters (path/to/node_modules/fabric/dist/fabric.js:17326:33)

I noticed that the problem doesn't appear of the frist image but after that some images are loaded correctly.
I'm sure everything was rendering fine a month ago, I launched a npm update and maybe there where some compatibilities issues between new versions of modules, FYI I'm using fabricjs v1.4.13 and node-canvas v1.2.1. 
I'm I the only one experiencing this?

**Comment by asturur** [comment]
there is already an open issue for that in 1,5,0 milestone.

**Comment by DanieleSassoli** [comment]
Ok, but I'm not managing to render anything, I'm sure this didn't before, is there any temporary fix I can use? even installing older versions of node-canvas is acceptable for me.

**Comment by asturur** [comment]
Can we see your json?
can you setup a js fiddle ? ( i know jsfiddle is not nodejs )

**Comment by DanieleSassoli** [comment]
I can post my json with no problem but it contains some custom options, http://pastebin.com/01UTevKp, I don't think you will be able to load it without our custom classes. Iì'll try to setup a fiddel.

**Comment by DanieleSassoli** [comment]
I tried downgrading to node-canvas 1.1.6, but (obviously,I'd say) didn't work, I'm quite worried about this thing, I can't render anything, just a couple of weeks ago every thing was working fine, have you got a clue of why this happens? I didn't touch my code and I'm rendering the same json as I used to render before...

**Comment by asturur** [comment]
If you updated fabric, some image classes changes happened.
I do not want to sound stupid, but, you said you are loading same json of some time ago.
I see some session here
```
"http://192.168.99.153/pixelity/downloadFile?sessionId=fb89172d22ea12310dcdfa4f8c65f336&assetKey=4d0a4b28f9c54a196a1648edc9bc0d8f
```
Do not get offended, but are you sure problem is not in this kind of link? session expired... or something like that?
That is why we always ask to create minimal case.
We do not and we cannot provide general problem assistance, we are not enough people.
Point us a certain bug and we will do best we can... please try to obtain the same bug with smallest  json possible

**Comment by DanieleSassoli** [comment]
I'll try to recreate the problem, no it's not a problem of expired session or so, don't worry, that wasn't so "stupid" after all.

**Comment by DanieleSassoli** [comment]
Solved the mistery, the files of some images where broken, think it could be related to https://github.com/Automattic/node-canvas/issues/486 . Sorry for the waste of time.
