### ISSUE TITLE
Groupborders don't resize when zooming

### ISSUE THREAD

**Issue by suroh1994** [kangax/fabric.js#2060]
I have noticed that when you created a group, select it and then zoom in the groups borders don't resize correctly.
I created this short fiddle showing what i'm talking about:
http://jsfiddle.net/hf83y7wd/2/
In order to reproduce the bug you need to select both objects and move them somewhere so that the code deselects them and then reselects them. now you have the manually created group and with this group zooming does not work.

I need to deselect all objects in my programm in order to update their positions and everything else.
If this is a bug it would be great if you could show me a different approach to this issue.

**Comment by sapics** [comment]
@suroh1994
Without [deselect all objects], group border resize looks working.
http://jsfiddle.net/sapics/h4bzq826/.
The question is how to [deselect all objects]?
Or my jsfiddle is enough for you?

**Comment by suroh1994** [comment]
I see what you did but that won't help me :(

The problem is i need to get my objects to update their position so that i can detect these changes and send them to another user so his canvas can update correctly.

I tried _restoreObjectsState() to update my objects without deselecting them which resulted in them moving outside the group borders, so i would need a function to update these!

**Comment by sapics** [comment]
@suroh1994 I understand what you want.

It might be possible that your written code [activate to diactivate] in
http://jsfiddle.net/hf83y7wd/2/
works well by some additional tips, I have not succeeded yet.
However, when you rotate group, user experience has changed.
Is it not problem for you?

**Comment by suroh1994** [comment]
I don't understand what you changed in comparison to my code. 
If someone can provide me a way to have my objects update their attributes without deselecting them i'm totally fine with that! Right now i'm only deselecting the active group to apply the changes since i don't want to recalc for example where to place an object after a group was rotate since just adding the angle to the original objects rotates it in place.

**Comment by sapics** [comment]
Sorry, I write jsfiddle just for reference. It is exactly what you create.
Sorry, my bad English.

Some days ago, I try to do similar.
But I did not do because of bad User Experience.

Between this two code, the boundary of rotated group is changed.
http://jsfiddle.net/hf83y7wd/2/
http://jsfiddle.net/sapics/hf83y7wd/4/

**Comment by suroh1994** [comment]
I can definitely see your point and i thought about this too since it looks stupid and not intuitive. Yet i am trying to get as much out of the already implemented functions of fabric as possible so i was playing around with this.

Maybe someone can come up with a good solution!

**Comment by sapics** [comment]
To avoid changing user experience, how about this?
1. Create clone of active group whose children are the cloned Rectangles.
2. Destroy cloned group.
3. Send data from cloned Rectangles which are not grouped.
4. Remove cloned Rectangles.

**Comment by suroh1994** [comment]
thanks for the hint! I ended up changing it like you explained it and it works fine.
http://jsbin.com/cisoluziyu/1/ (for some reason i could not save my fiddles so here a bin-link)
Note: cloning a group does not clone it's object but instead hands them over as references!
