### ISSUE TITLE
I need to add event on all itext change

### ISSUE THREAD

**Issue by mina-thomas** [kangax/fabric.js#2063]

**Comment by mina-thomas** [comment]
I tried 
canvas.on('text:changed', function(){})
but it's not working

**Comment by sapics** [comment]
How about using `canvas.on('text:editing:exited', function(){});`?

**Comment by Kienz** [comment]
@mina-thomas What changes? If chars inserted/removed you can use `canvas.on('text:changed', function (e) { ... });`.
