### ISSUE TITLE
Text position issue in SVG

### ISSUE THREAD

**Issue by vignesh-indian** [kangax/fabric.js#2070]
When I use text inside the canvas, the text position is exactly where I placed. 

![svg in canvas](https://cloud.githubusercontent.com/assets/11572954/6912438/f62ad45e-d78e-11e4-8df6-8e39c85aec3d.png)

But when I convert the canvas content to SVG and opening it in the browser, the text position is changed.

![svg in browser](https://cloud.githubusercontent.com/assets/11572954/6912447/2b0a5136-d78f-11e4-8c63-052d3572545d.png)

Please help me to rectify this problem.

**Comment by asturur** [comment]
Please use the very latest fabric.js.
Please create a jsfiddle that recreate the problem.

**Comment by vignesh-indian** [comment]
Hi asturur,

The above text position issue is cleared after using the version 1.4.13, but the image position is changed. The sample i designed in the canvas


![canvas](https://cloud.githubusercontent.com/assets/11572954/6914216/e96e9752-d7a5-11e4-8d12-00cd0fde6f87.png)


but after converting the canvas contents to SVG, and opening the saved SVG in the browser makes the image position issue

![svg in browser](https://cloud.githubusercontent.com/assets/11572954/6914250/3a8ec13e-d7a6-11e4-80e0-b7bf33eebb4d.png)

Here is the code i used to save as SVG

var frontCanvasImageStreamString = frontCanvas.toSVG();
