### ISSUE TITLE
Image position issue in SVG

### ISSUE THREAD

**Issue by vignesh-indian** [kangax/fabric.js#2071]
The canvas contents I used is
![canvas](https://cloud.githubusercontent.com/assets/11572954/6914810/115f1218-d7ac-11e4-8299-667ea8f252a9.png)
but after converting the canvas contents to SVG, and opening the saved SVG in the browser makes the image position issue after scaling the images
![svg in browser](https://cloud.githubusercontent.com/assets/11572954/6914835/616c7912-d7ac-11e4-9d53-062f3c7f7195.png)
Here is the code i used to save as SVG

var frontCanvasImageStreamString = frontCanvas.toSVG();

Please help to rectify this problem.

**Comment by vignesh-indian** [comment]
Here is the jsFiddle link 
https://jsfiddle.net/Vignesh160/43nbo682/

Please scale those images after rendering, and then click to SVG. While opening the SVG in the browser, the image position is changed

**Comment by asturur** [comment]
Consider changing fabric.object.NUM_FRACTION_DIGIT from 2 to 10.

**Comment by vignesh-indian** [comment]
ya, I already changed it to '10'. Its works fine inside canvas after changing to 10, but not in toSVG.

**Comment by vignesh-indian** [comment]
@asturur , No solution for this????

**Comment by asturur** [comment]
The solution is there.
Use latest fabric 1.4.13 and with your fiddle this is the output:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="396" height="300" xml:space="preserve"><desc>Created with Fabric.js 1.4.13</desc><defs></defs><line x1="188" y1="0" x2="-188" y2="0" style="stroke: #000000; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #000000; fill-rule: nonzero; opacity: 1;" transform="translate(198.5 25.5)"/>
<g transform="translate(72.5 90.5) scale(0.25 0.25)">
<image xlink:href="http://fabricjs.com/lib/pug.jpg" x="-250" y="-250" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" width="500" height="500" preserveAspectRatio="none"></image>
</g>
<g transform="translate(198.5 90.5) scale(0.25 0.25)">
<image xlink:href="http://fabricjs.com/lib/pug.jpg" x="-250" y="-250" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" width="500" height="500" preserveAspectRatio="none"></image>
</g>
<g transform="translate(324.5 90.5) scale(0.25 0.25)">
<image xlink:href="http://fabricjs.com/lib/pug.jpg" x="-250" y="-250" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" width="500" height="500" preserveAspectRatio="none"></image>
</g>
</svg>
```

that is perfectly fine.

**Comment by vignesh-indian** [comment]
@asturur, please scale those images and try. Without scaling it is perfecr

**Comment by vignesh-indian** [comment]
@asturur , No solution for this????

**Comment by asturur** [comment]
Even with small scaling factor the picture are still aligned.
Are you sure you changed the fabric.Object.NUM_FRACTION_DIGITS to 10?

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="396" height="300" xml:space="preserve"><desc>Created with Fabric.js 1.4.13</desc><defs></defs><line x1="188" y1="0" x2="-188" y2="0" style="stroke: #000000; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #000000; fill-rule: nonzero; opacity: 1;" transform="translate(198.5 25.5)"/>
<g transform="translate(18.5 36.5) scale(0.034 0.034)">
<image xlink:href="http://fabricjs.com/lib/pug.jpg" x="-250" y="-250" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" width="500" height="500" preserveAspectRatio="none"></image>
</g>
<g transform="translate(143 35) scale(0.028 0.028)">
<image xlink:href="http://fabricjs.com/lib/pug.jpg" x="-250" y="-250" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" width="500" height="500" preserveAspectRatio="none"></image>
</g>
<g transform="translate(268 34) scale(0.024 0.024)">
<image xlink:href="http://fabricjs.com/lib/pug.jpg" x="-250" y="-250" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" width="500" height="500" preserveAspectRatio="none"></image>
</g>
</svg>
```

**Comment by vignesh-indian** [comment]
s, i have changed - fabric.Object.NUM_FRACTION_DIGITS = 10;

**Comment by vignesh-indian** [comment]
Please make scaling exactly like i have done above and check.

**Comment by asturur** [comment]
Why you do not simply post the canvas.toObject() and canvas.toSVG() strings here?

**Comment by vignesh-indian** [comment]
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="396" height="300" xml:space="preserve"><desc>Created with Fabric.js 1.4.0</desc><defs></defs><line x1="376" y1="25" x2="0" y2="25" style="stroke: #000000; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #000000; opacity: 1;"/><g transform="translate(83.85 101.85) scale(0.3 0.3)"><image xlink:href="http://fabricjs.com/lib/pug.jpg" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); opacity: 1;" transform="translate(-250 -250)" width="500" height="500" preserveAspectRatio="none"></image></g><g transform="translate(324.38 90.62) scale(0.25 0.25)"><image xlink:href="http://fabricjs.com/lib/pug.jpg" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); opacity: 1;" transform="translate(-250 -250)" width="500" height="500" preserveAspectRatio="none"></image></g><g transform="translate(210.1 78.9) scale(0.2 0.2)"><image xlink:href="http://fabricjs.com/lib/pug.jpg" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); opacity: 1;" transform="translate(-250 -250)" width="500" height="500" preserveAspectRatio="none"></image></g></svg>

**Comment by vignesh-indian** [comment]
<svg xmlns="http://www.w3.org/2000/svg" 

xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="396" 

height="300" xml:space="preserve"><desc>Created with Fabric.js 

1.4.0</desc><defs></defs><line x1="376" y1="25" x2="0" y2="25" 

style="stroke: #000000; stroke-width: 1; stroke-dasharray: ; stroke-

linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: 

#000000; opacity: 1;"/><g transform="translate(83.85 101.85) scale

(0.3 0.3)"><image xlink:href="http://fabricjs.com/lib/pug.jpg" 

style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-

linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: 

rgb(0,0,0); opacity: 1;" transform="translate(-250 -250)" width="500" 

height="500" preserveAspectRatio="none"></image></g><g 

transform="translate(324.38 90.62) scale(0.25 0.25)"><image 

xlink:href="http://fabricjs.com/lib/pug.jpg" style="stroke: none; 

stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-

linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); opacity: 

1;" transform="translate(-250 -250)" width="500" height="500" 

preserveAspectRatio="none"></image></g><g transform="translate(210.1 

78.9) scale(0.2 0.2)"><image 

xlink:href="http://fabricjs.com/lib/pug.jpg" style="stroke: none; 

stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-

linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); opacity: 

1;" transform="translate(-250 -250)" width="500" height="500" 

preserveAspectRatio="none"></image></g></svg>

**Comment by vignesh-indian** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="no" ?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg 
xmlns="http://www.w3.org/2000/svg" 
xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="396" height="300" xml:space="preserve"><desc>Created with Fabric.js 1.4.0</desc><defs></defs><line x1="376" y1="25" x2="0" y2="25" style="stroke: #000000; stroke-width: 1; stroke-dasharray: ; stroke-
linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #000000; opacity: 1;"/><g transform="translate(197.56 108.27) scale (0.32 0.32)"><image xlink:href="http://fabricjs.com/lib/pug.jpg" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); opacity: 1;" transform="translate(-250 -250)" width="500" height="500" preserveAspectRatio="none"></image></g><g transform="translate(332.17 81.58) scale(0.21 0.21)"><image xlink:href="http://fabricjs.com/lib/pug.jpg" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); opacity: 
1;" transform="translate(-250 -250)" width="500" height="500" 
preserveAspectRatio="none"></image></g><g transform="translate(63.14 
81.14) scale(0.21 0.21)"><image xlink:href="http://fabricjs.com/lib/pug.jpg" style="stroke: none; 
stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-
linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); opacity: 
1;" transform="translate(-250 -250)" width="500" height="500" 
preserveAspectRatio="none"></image></g></svg>

**Comment by vignesh-indian** [comment]
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="396" height="300" xml:space="preserve"><desc>Created with Fabric.js 1.4.0</desc><defs></defs><line x1="376" y1="25" x2="0" y2="25" style="stroke: #000000; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #000000; opacity: 1;"/><g transform="translate(81.36 99.36) scale(0.29 0.29)"><image xlink:href="http://fabricjs.com/lib/pug.jpg" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); opacity: 1;" transform="translate(-250 -250)" width="500" height="500" preserveAspectRatio="none"></image></g><g transform="translate(204.81 78.6) scale(0.2 0.2)"><image xlink:href="http://fabricjs.com/lib/pug.jpg" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); opacity: 1;" transform="translate(-250 -250)" width="500" height="500" preserveAspectRatio="none"></image></g><g transform="translate(321.63 93.37) scale(0.26 0.26)"><image xlink:href="http://fabricjs.com/lib/pug.jpg" style="stroke: none; stroke-width: 1; stroke-dasharray: ; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); opacity: 1;" transform="translate(-250 -250)" width="500" height="500" preserveAspectRatio="none"></image></g></svg>`

**Comment by vignesh-indian** [comment]
@asturur , image position issue occurs only when scaling through manual.

**Comment by asturur** [comment]
It is so bright and clear that you are not following what i say and just going on your own road.

https://jsfiddle.net/43nbo682/4/

Here is an updated fiddle where i put latest fabric for you , and i put fabric.Object.NUM_FRACTION_DIGITS = 10, that you were not doing in the fiddle.

Scale manually how do you think is better and try to make svg.
If you manage to get a wrong SVG in this fiddle, then we see if there is a bug.

**Comment by vignesh-indian** [comment]
i have changed this in the codes that i have used in the project, but it is not getting the exact position

**Comment by asturur** [comment]
if your SVG is coming out with "scale(0,24, 0,24)" is not using more digits than 2.
And you will have positioning issue.
If you see my svg it comes out with 0.232331231 and is aligned.

**Comment by vignesh-indian** [comment]
The problem is, the objects that are created using 1.4.5. does not supports the toSVG() using 1.4.13.
Thanks @asturur
