### ISSUE TITLE
No Free Drawing Documentation

### ISSUE THREAD

**Issue by darkfrog26** [kangax/fabric.js#2072]
Though free drawing is mentioned in part 4 of the tutorial (http://fabricjs.com/fabric-intro-part-4/#free_drawing) there is no reference to isDrawingMode in the docs (http://fabricjs.com/docs/fabric.Canvas.html).  Documentation is incredibly frustrating when it only covers part of the functionality of a framework. :-p

**Comment by kangax** [comment]
Sorry! And thanks for finding it. If you can send PR, that would be awesome. Or one of us will try to get to it as soon as we can.

**Comment by darkfrog26** [comment]
I'll try to get to a PR if I can find the time.  You also have some pretty major bugs in the tutorial as well.  The most common is that all the example code in part 1 and part 2 don't reference using originX = 'center' and originY = 'center', but in order to make it look like the examples portray they must be.

**Comment by kangax** [comment]
Actually, we've been updating some of that stuff literally in the past couple days — https://github.com/kangax/fabricjs.com/commits/gh-pages

**Comment by kangax** [comment]
More stuff here — https://github.com/kangax/fabricjs.com/issues/22 (any help with those is welcome, as always)

**Comment by darkfrog26** [comment]
Great to hear.  I'm actually writing a wrapper around FabricJS with my own framework (http://hyperscala.org).  Oh, and keeping the CDN updated would appreciated as well as 1.4.0 (the current CDN version) is incredibly buggy.

**Comment by kangax** [comment]
As soon as we push 1.5.0 (any day now)!
