### ISSUE TITLE
scaleToWidth doesn't work after setElement change image src

### ISSUE THREAD

**Issue by CSI68** [kangax/fabric.js#2076]
Hi,

I try to change simply change src of an image by using setElement like explain in the doc. But after replacement the image is bigger (source too). So I try to restore original size width scaleToWidth or setWidth, but nothing work.

Here my code :

fabric.util.loadImage(newUrl, function(img) {
    obj.setElement(img, function(){
	obj.scaleToWidth(width);
	width=obj.getWidth();
	console.log("apres :"+width);
	obj.setCoords();
	customize.canvas.renderAll();
});
});

How can I do this ?

Thanks

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group — https://groups.google.com/forum/#!forum/fabricjs — where someone will usually assist you.

The issue tracker is only for bugs and feature requests.

Thanks for your understanding!
