### ISSUE TITLE
setZoom breaks IText cursor top positioning

### ISSUE THREAD

**Issue by jafferhaider** [kangax/fabric.js#2077]
If the canvas is zoomed to a value other than 1, the top offset of IText's cursor remains unchanged and hence is rendered in between or in extreme cases on the wrong line.

Test case in the following jsFiddle:
http://jsfiddle.net/jafferhaider/ksfcjggt/1/

**Comment by asturur** [comment]
mmm now that the cursor is drawn on the uppercanvas we have this problem
Ok i will add a zoom to the upper canvas , it get restored after cursor rendering, so should not be a problem.

**Comment by asturur** [comment]
@jafferhaider jaffer, can i ask you to search in your fabric.js the 
renderCursor function and change the top part with:

```diff
-      var ctx = this.canvas.contextTop || this.ctx;
-
-      ctx.save();
-      this.transform(ctx);
+      var ctx; 
+      if (this.canvas.contextTop) {
+        ctx = this.canvas.contextTop;
+        ctx.save();
+        this.transform(ctx);
+        this.upperCanvas.scale(
+          this.canvas.viewportTransform[0],
+          this.canvas.viewportTransform[3]
+        );
+      } else {
+        ctx = this.ctx;
+        ctx.save();
+      }
```

( i just discovered the diff tag)

**Comment by jafferhaider** [comment]
It breaks stuff. Here is an updated fiddle with the change you asked for.

http://jsfiddle.net/jafferhaider/ksfcjggt/2/

**Comment by asturur** [comment]
sorry i think messed up, sorry for wasting your time, this evening i ll look into it.
Consider more or less this is the solution, scale the upperCanvas context with the viewport transform.
probably i should write ctx.scale(...) instead of this.upperCanvas.scale(...)

**Comment by jafferhaider** [comment]
Sure, I'll wait for your final fix. Thanks!

**Comment by jafferhaider** [comment]
The cursor is fixed. But the blue selection rectangle is broken. It does not highlight the text exactly if you're not at 100% zoom level.

**Comment by jafferhaider** [comment]
@asturur Another bug (not related to this zoom issue). Create a new IText with one line of text in it. Add a few newlines by clicking in and hitting Enter. Now move the IText item around with the mouse and the newlines go away.

I'm testing with the latest code right now.

**Comment by jafferhaider** [comment]
@asturur disregard my last comment about newlines going away. That was a bug in my application level code ... not related to FabricJS.

**Comment by asturur** [comment]
ok, i looked for it, i could not make it happen and i thought it was related to small issues i fixed around.
i will build my branch and upload somewhere.to have a look. there are 2 bugs i cannot get rid of.
they are stated in #2101
