### ISSUE TITLE
Removing controls programmaticaly

### ISSUE THREAD

**Issue by sathio** [kangax/fabric.js#2078]
Hi, great library, I'm very happy to have found it.
I'd like to make sure that when calling this function all controls from objects are removed.
I left bl:true as a test and via console.log i can see that they are correctly set. only problem is that they're still there, I think I should call some canvas.renderAll(); function, but it doesn't re-render.

    function rasterize(){

      obj = canvas.getObjects();

      for(i=0;i<obj.length;i++){
        obj[0].hasControls=false;
        obj[0].setControlsVisibility({
                tl: false,
                tr: false,
                br: false,
                bl: true,
                ml: false,
                mt: false,
                mr: false,
                mb: false,
                mtr: false
            });

      }
      canvas.renderAll();
      //window.open(canvas.toDataURL('png'));
    }

    _controlsVisibility: Object
    bl: true
    br: false
    mb: false
    ml: false
    mr: false
    mt: false
    mtr: false
    tl: false
    tr: false

**Comment by sathio** [comment]
oops, nevermind I was being blonde... 
now, how do I delete this..?

**Comment by asturur** [comment]
cannot delete. it will be here forever as a proof of your hurry to file an issue.

:)

**Comment by sathio** [comment]
I'll also tattoo it on my wrist. 

ciao  :)
