### ISSUE TITLE
Bower download breaks module bonuses

### ISSUE THREAD

**Issue by nesteant** [kangax/fabric.js#2087]
Using bower doesn't allow to use modularity of the fabricjs.
<b>Expected behavior 1:</b> bower installation downloads all modules which can be then injected to the project separately
<b>Expected behavior 2:</b> bower installation downloads fully featured version of fabricjs
<b>Expected behavior 3:</b> bower installation downloads several files with the most popular builds
<b>Actual Behavior:</b> bower downloads next version of build: node build.js modules=ALL exclude=gestures,cufon,json

**Comment by asturur** [comment]
Does not bower download similar to npm?
Can you provide more details on what is not good from your point of view?

**Comment by asturur** [comment]
I don't think this will change.
We provide the latest build already built, plus the file necessary to make a custom build.
