### ISSUE TITLE
Issue with text parser

### ISSUE THREAD

**Issue by asturur** [kangax/fabric.js#2088]
Sample SVG
```xml
<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg width="100%" height="100%" version="1.1" xmlns="http://www.w3.org/2000/svg">
<text x="30" y="50">AAAAA	AAAA		AAAAAAAAAAAAAAAAAAA
BBBBBBBBBBBBBBBBBBBBBBBBBBB
cccccccccccccccc
       
	        
			       
				          
						             DDDDDDD</text>
</svg>
```

sample rendering from browsers
![image](https://cloud.githubusercontent.com/assets/1194048/7003917/fc04ef80-dc62-11e4-8df6-187496db2a3e.png)

![image](https://cloud.githubusercontent.com/assets/1194048/7003919/084ab9a0-dc63-11e4-80c2-f756ad582678.png)

rendering from kitchensink

![image](https://cloud.githubusercontent.com/assets/1194048/7003987/963e8952-dc64-11e4-96c7-e671052d8fa5.png)

as you see we have to make some cleaning of the text during parsing.
And of course not consistent behaving between firefox and chrome

**Comment by asturur** [comment]
cleaning the text solves the problem
proposed regex:
```
    var textContent = element.textContent.replace(/\n+/g, '').replace(/[\s]+/g, ' ');
    var text = new fabric.Text(textContent, options),
```

![image](https://cloud.githubusercontent.com/assets/1194048/7004168/492dbb80-dc67-11e4-9e68-0151375581dd.png)


old problem with charts cleaned:
![image](https://cloud.githubusercontent.com/assets/1194048/7004154/0d225ede-dc67-11e4-910c-5f8c15657059.png)

**Comment by kangax** [comment]
Nice! Btw, no need for capturing group in `/[\s]+/`. Can just be `/\s+/g`
