### ISSUE TITLE
performance move many objects on the canvas

### ISSUE THREAD

**Issue by SvenWangChina** [kangax/fabric.js#2094]
I create a canvas 7312*5328px, I add 33 image objects to it, when I move the image, it  goes so slowly. How can i improve the performance?

**Comment by hellomaya** [comment]
That's interesting, I am curious about why you create such a large canvas? There are many way to zoom in/out canvas, so if you really need hight quality output, you don't really have to do that, and that might be the problem.

**Comment by SvenWangChina** [comment]
I create the canvas(1920*1080)，add two small images, and then I zoom in to 7680*4320, it also goes too slowly. Do you any idea to improve the performance?

**Comment by asturur** [comment]
Please @svenWangChina provide a test page or a fiddle to understand your code, we will try to help you if possible.

**Comment by SvenWangChina** [comment]
Thanks a lot. Here is my code, I add a rect, but it also goes too slowly when I move it.


<canvas id="icanvas" width="1920" height="1080"></canvas>
<script type="text/javascript" src="http://api.jquery.com/jquery-wp-content/themes/jquery/js/jquery-1.11.2.min.js"></script>
<script type="text/javascript" src="http://fabricjs.com/lib/fabric.js"></script>
<script type="text/javascript">
	$(document).ready(function () {
		var canvas = new fabric.Canvas('icanvas');
		canvas.setZoom(4)
			.setWidth(canvas.getWidth() * 4)
			.setHeight(canvas.getHeight() * 4);
		canvas.add(new fabric.Rect({
			left: 100,
			top: 100,
			fill: '#EEE',
			width: 100,
			height: 100
		}))
	});
</script>

**Comment by SvenWangChina** [comment]
<canvas id="icanvas" width="1920" height="1080"></canvas>
		var canvas = new fabric.Canvas('icanvas');
		canvas.setZoom(4)
			.setWidth(canvas.getWidth() * 4)
			.setHeight(canvas.getHeight() * 4);
		canvas.add(new fabric.Rect({
			left: 100,
			top: 100,
			fill: '#EEE',
			width: 100,
			height: 100
		}));

**Comment by hellomaya** [comment]
讓我寫點中文在這裏，好像我們都是一個地方來的，呵呵。其實，我想說，比如你把canvas放大這麼大，是不是有必要呢？從這個角度考慮，不知道能否解決問題，只是不知道你為甚麼要放大canva這麼大，我很想知道原因，因為沒有遇到過，想了解下。

Let me put some Chinese here, from Your name, seems we are from same country? Actually, I want to ask you, why you use that large canvas? Is it necessary? From this point, could you change it smaller, and does the performance getting better when it smaller? I don't know if this helps or not, just want to know why, because that's not usually I have known, just for learning curiosity. 

Sorry @asturur, I put some idea in my native language Chinese here, just want to know why he want that large canvas, that's an interesting situation. I hope my Chinese is better than the explanation of my question in English.

**Comment by SvenWangChina** [comment]
@hellomaya Nice to meet you here! I wanna use the large canvas to display more objects. For example, there is a whiteboard, I wanna make sure it is large enough to hold more objects, when many people are doing a research about a topic.

**Comment by asturur** [comment]
I tried your code on the kitchensink demo, on my i3 machine is very smooth.
firefox and chrome tested.
What other javascript is running there? what browser?

![image](https://cloud.githubusercontent.com/assets/1194048/7066660/0ee8ec64-dec5-11e4-9d62-87bfe03ccd95.png)

**Comment by SvenWangChina** [comment]
@asturur I test the code with chrome, mac pro Retina, 13-inch, Late 2012
There isn't other javascript, this demo is small slowly. If i add more objects. It will become too slowly.
I tried kitchensink with follow code, it become too slowly.
for (var i = 0; i < 10; i++) {
  fabric.Image.fromURL('https://www.google.com.sg/images/srpr/logo11w.png', function(img) {
            img.setCoords();
canvas.add(img);
        },{
    left: 100 + i * 10,
    top: 100 + i * 10
  });
}
canvas.setZoom(10);
canvas.setWidth(canvas.getWidth() * 10);
canvas.setHeight(canvas.getHeight() * 10);

**Comment by hellomaya** [comment]
@SvenWangChina Thanks, good to know, and that's interesting.

**Comment by asturur** [comment]
i do not know, the canvas in your example is laggy on an i3, but still is a 7000x5000 canvas.
Probably the clearing and the drawing of that 10 big images is the issue, we are not doing so many code rather than cycling trought the 10 images and draw them.
