### ISSUE TITLE
Hitboxes for border controls broken

### ISSUE THREAD

**Issue by Alysander** [kangax/fabric.js#2100]
Once padding has been applied the hitboxes for the border controls are not calculated correctly. I have attached a screenshot of where padding has been set to 20 and I have enabled some commented out code in _findTargetCorner that shows where the hitboxes have been drawn so the dots in the screenshot indicate the corners of the actual hitboxes.

@kangax what would be a good approach to fixing this? It looks to me like the code in drawControls could possibly just use the values in oCoords instead of calculating anything itself.

![screen shot 2015-04-09 at 2 53 41 pm](https://cloud.githubusercontent.com/assets/9831748/7060636/42abe3dc-dec8-11e4-9f05-cb3d296dcff6.png)

**Comment by asturur** [comment]
Are you using latest version? 

I tried to replicate but i could not:
![image](https://cloud.githubusercontent.com/assets/1194048/7061312/77d065de-de90-11e4-86db-8fea411db058.png)
Sorry for the little dots, other than a 1 pixel approximation they are correct.

**Comment by Alysander** [comment]
Ah yep, I am on an older version and it looks like you fixed it in https://github.com/kangax/fabric.js/commit/a7022c1bef445096ab29cd30e7d30eaa57cb9840
Awesome
