### ISSUE TITLE
It cannot input chinese character

### ISSUE THREAD

**Issue by acekingke** [kangax/fabric.js#2104]
# HI, The Text cannot input chinese character
![image](https://cloud.githubusercontent.com/assets/7586502/7110153/09ecf76a-e1df-11e4-95fa-225e6f624e49.png)

**Comment by asturur** [comment]
duplicate of #2051.

there is a fix that will be completed after next major release.

**Comment by YangChueng** [comment]
May I ask again whether the feature above has been supported or fixed now?
Because the demo still doesnt work and if it's ok how could I make it?
PS:I used window and sogou Input.
http://www.deltalink.it/andreab/fabric/kitchensink.html

**Comment by asturur** [comment]
no yet.

**Comment by YangChueng** [comment]
Ok,thanks.
