### ISSUE TITLE
Safer json loading

### ISSUE THREAD

**Issue by sapics** [kangax/fabric.js#2105]
This issue has been already pointed out in [stackoverflow](http://stackoverflow.com/questions/29561911/are-there-any-secure-methods-to-open-other-peoples-json-text-in-fabric-js).
As written in [stackoverflow](http://stackoverflow.com/questions/29561911/are-there-any-secure-methods-to-open-other-peoples-json-text-in-fabric-js), there would be risks (any function would get executed) at opening other person's created json.

I would like to suggest to add a feature **safe mode**, which makes disable `new Fuction` of `object.clipTo` and `pattern.source`, or allow only limited functions which checked by regex.
It might be better to make new feature, for example, mask type group (first or last object in `group._objects` decide the masked shape), or add prototype like `simpleClip` or `clipPath` (String or Array or Object type which include information for clipping to rectangle,circle,path,,,), and so on.
##

**Comment by kangax** [comment]
These are valid concerns, but I'm hesitant to include more and more features to already quite big Fabric. One solution is to just strip/sanitize `clipTo`, `source`, etc. manually before parsing JSON (which should be pretty trivial).

**Comment by sapics** [comment]
Thank you for your answer! I understand that it will be better to check by manually method.
