### ISSUE TITLE
Itext and clipTo controls misaligned

### ISSUE THREAD

**Issue by zefta** [kangax/fabric.js#2106]
Hi,

I'm trying to clip an IText object to a Rect. Everything is working very well but the cursor is misaligned.
I let you see my code http://jsfiddle.net/w82mxwav/ 
I must be missing something but I don't know what.

Thanks

**Comment by asturur** [comment]
http://jsfiddle.net/w82mxwav/1/

apart that your fiddle is not working on chrome, i do not get why, in your clip function you are restoring the canvas without saving it, killing the transform stack

I added ctx.save() and it works ok.
