### ISSUE TITLE
Loading Image URL on Ipad Mini with photo dimension on 2100px higher was not working

### ISSUE THREAD

**Issue by decemarie23** [kangax/fabric.js#2107]
I'm trying to upload and insert image on a fabric image but I got the message
Error Loading (URL)... failed to load the image and insert it to the canvas.

Does anyone knows how to adjust or manipulate the setting for Ipad Mini... Iphone, android and desktops work on uploading/loading the image, it just only on the Ipad. Thank you for the help.

**Comment by asturur** [comment]
@decemarie23 if you still have this problem and you are able to write a jsfiddle that demonstrate the issue, i will reopen the issue and investigate the problem.
