### ISSUE TITLE
How to forbidden the interactive mode ?

### ISSUE THREAD

**Issue by acekingke** [kangax/fabric.js#2108]
I just want to draw the image on canvas , do not need interactive the graph, how to make it?

**Comment by asturur** [comment]
create a fabric.staticCanvas instead of fabirc.Canvas

**Comment by acekingke** [comment]
But when I use fabric.staticCanvas , the code like 
```
 canvas.on('mousedown', function(options) {
				  
				  console.log("click" ,options.e.clientX, options.e.clientY);
				});
```
do not work

**Comment by asturur** [comment]
ok, so pleaese, explain us what do you mean by interactive mode.
