### ISSUE TITLE
IText Glitches post 1.5.0 release

### ISSUE THREAD

**Issue by coulix** [kangax/fabric.js#2109]
![image](https://cloud.githubusercontent.com/assets/26057/7155668/3712fba8-e3ac-11e4-989f-9fc89b8876b8.png)
![image](https://cloud.githubusercontent.com/assets/26057/7155672/3b28aa44-e3ac-11e4-86ee-0575b34d81fb.png)
![image](https://cloud.githubusercontent.com/assets/26057/7155674/400de2fe-e3ac-11e4-926f-c3e5c51800ac.png)

From http://fabricjs.com/test/misc/itext.html.

The [a] which appears as a non capital char should have been capitalized. The whole list of styles seems to be off by one.

The same happens when selecting and replacing the content with a new character, the styles of preexisting chars is not kept and every styles get shifted.

**Comment by asturur** [comment]
I add it in the iText fixings for 1.5.0.1 
With style problem when justify, space problem when justify.
In this case i think that just newlines are counted while shifting style

**Comment by asturur** [comment]
From http://fabricjs.com/test/misc/itext.html
![image](https://cloud.githubusercontent.com/assets/26057/7156562/49228fc8-e3b3-11e4-8172-316e090355d6.png)

An animation from my custom fork.
![image](http://public.coulix.s3.amazonaws.com/itext_boundary_bug.gif)

As soon as a new char is entered the bounding box is properly calculated. I tried to call `setCoord` and `calcOffset` without success.

**Comment by asturur** [comment]
I think that internal style change does not trigger a cache clearing.

**Comment by coulix** [comment]
`this._clearCache();` seems to be called, strange.

**Comment by asturur** [comment]
i add #760
