### ISSUE TITLE
Itext fontSize style update does not trigger a bounding box update.

### ISSUE THREAD

**Issue by coulix** [kangax/fabric.js#2110]
From http://fabricjs.com/test/misc/itext.html
![image](https://cloud.githubusercontent.com/assets/26057/7156562/49228fc8-e3b3-11e4-8172-316e090355d6.png)

An animation from my custom fork.
![image](http://public.coulix.s3.amazonaws.com/itext_boundary_bug.gif)

As soon as a new char is entered the bounding box is properly calculated. I tried to call `setCoord` and `calcOffset` without success.

**Comment by asturur** [comment]
Please file iText related bug on the first post. i'm gonna take them down all togheter.
Let's not open lots of issue, will kill my time.
