### ISSUE TITLE
Can't apply a fill (pattern) to an image object

### ISSUE THREAD

**Issue by bcruddy** [kangax/fabric.js#2112]
I've got some plain white image objects that I'd like to overlay a pattern on. Looking at the docs for fabric.Image the method `setPatternFill()` seems like it should do this but it doesn't. The method works perfectly with i-text objects.

I just grabbed an image and pattern image from the fabric site for the example [JSFiddle](http://jsfiddle.net/QT3pa/36/).

To change the color of these image objects I've been using the tint filter and while working through this pattern issue I came to find that the `setFill()` method doesn't seem to change the fill image objects either (or accessing it direclty via `obj.fill = '#xxxxxx'`, which would make this much less of a bug and more of an error in the docs.

**Comment by asturur** [comment]
image does not have renderFill and renderStroke directly.
RenderStroke is emulated with a rect around the image to give it a border.

The fill would be eventually under the image and visible under trasparent pixels OR over it and the image would be visible where pattern is transparent ( like watermarking ).

The bad thing is that it looks like i was thinking about this morning.
If i got a super power like "guess next open issue" is the most useless super power i could get.

**Comment by kangax** [comment]
I guess I'll mark it as possible feature.

**Comment by mjskraju** [comment]
is this issue still being worked on?, can any body share the status of it?, I was trying to follow documentation and apply some effects on the image object that is drawn on canvas. But I couldn't get some of the features or effects like, this one(setPatternFill), setColor and fill to work as it is documented. While this feature are still being worked upon, I would like to know if there is any way to apply patterns & colors to image objects using fabric js.
Thanks.

**Comment by Sride** [comment]
Any updates? can any body share the status of it?

**Comment by RevelsGit** [comment]
+1

**Comment by asturur** [comment]
i think this will go togheter with object caching. Once objects are cached as images, we can apply filters over them.

**Comment by asturur** [comment]
this will be a 2.0 feature. The old json objects will get a black background because the current image background has always been exported as rgb(0,0,0) and now it would get rendered in black

**Comment by nphuocnguyen2000** [comment]
ssss### da đá ad**đá asd _ád asdad**asd ááda**sd**_ adasd`đâs`
