### ISSUE TITLE
Negative scaling of images does not work on IE8

### ISSUE THREAD

**Issue by bernardofd** [kangax/fabric.js#2113]
Hello;

I was following a bug report from a user, which led me to fill in this issue. Whenever a image has a negative scale (either from manually scaling or setting `flip[XY]` parameters to `true`), it is not rendered on (ex)canvas.

To reproduce this, follow these steps:
1. Open the Kitchensink demo on IE8
2. Clear the canvas
3. Add & select a image (screenshot below)
![before](https://cloud.githubusercontent.com/assets/2365802/7168802/8d77a9d2-e396-11e4-8d4d-c698797c680d.png)
4. Scale it down horizontally, until it flips
5. :cry: (screenshot below)
![after](https://cloud.githubusercontent.com/assets/2365802/7168965/944b7562-e397-11e4-977b-d1e7b0282bb8.png)

I wouldn't know if this is a FabricJS issue, or a ExCanvas issue, or even a VML issue. I just hope this isn't another item on the [Fabric limitations on old IE](https://github.com/kangax/fabric.js/wiki/Fabric-limitations-in-oldIE) list.

Any clarifications would be appreciated.

Many thanks!
##

**Comment by bernardofd** [comment]
Addendum: This seems to be applicable only to images. So far I've tested with paths, path-groups and geometry and everything works just fine.

**Comment by bernardofd** [comment]
Another update: Scaling an image without respecting its aspect ratio and then rotating it also doesn't work as expected.

As shown in the screenshot below, a image can be deformed normally if its angle is zero:
![before1](https://cloud.githubusercontent.com/assets/2365802/7210310/2421a810-e527-11e4-89f7-22552460fd6e.png)

But, if you try to rotate it, the deformation is ignored and *this* happens:
![after1](https://cloud.githubusercontent.com/assets/2365802/7210332/40f5b22e-e527-11e4-8c32-02240eaa3584.png)

I'm beggining to think that VML's inability to handle pixel data is to be blamed, here...

**Comment by kangax** [comment]
@bernardofd ugh... good old VML. If you could narrow down the cause (perhaps check if this happens with just excanvas, not fabric) that would be fantastic of course.

**Comment by bernardofd** [comment]
@kangax I'll try to generate a isolated test case as soon as I have the opportunity to do so.

**Comment by bernardofd** [comment]
@kangax I've managed to do a couple of canvas only test cases, loading excanvas on IE8 (Gist [here](https://gist.github.com/bernardofd/5104fa62434b3009868f)):
* [image negative scale](http://rawgit.com/bernardofd/5104fa62434b3009868f/raw/f07e306b6c1124a78ff05b29c6d447882c71a6c4/negativeScaling.html)
* [image rotation with deformed image](http://rawgit.com/bernardofd/5104fa62434b3009868f/raw/d58cb32bd1005088120b1cfcb6ce972b1d6535a0/rotateAndScale.html)

Unless I did something wrong, it seems that excanvas is unable to flip images, as seen here:
* Before
![ie8 - before](https://cloud.githubusercontent.com/assets/2365802/7377527/49fc2076-edbd-11e4-9e65-4cd098fa4477.png)
* After 
![ie8 - after](https://cloud.githubusercontent.com/assets/2365802/7377547/6ab3312e-edbd-11e4-9db4-addef79c81fe.png)

When rotating the image, things got weirder:
* Before
![ie8 - before rotate](https://cloud.githubusercontent.com/assets/2365802/7377577/b1fe29d0-edbd-11e4-875a-e070bd697381.png)
* After
![ie8 - after rotate](https://cloud.githubusercontent.com/assets/2365802/7377586/b9db790a-edbd-11e4-85a5-0b1a6e32d9a3.png)

I don't know if what I did is indeed how fabric rotate a image on canvas (probably not, since a image is rotatable on IE8). But I hope this helps clarify this issue.

Best Regards

**Comment by kangax** [comment]
Might be related — https://code.google.com/p/explorercanvas/issues/detail?id=25

**Comment by asturur** [comment]
since i removed ie9 and below from supported browsers, this can be closed
