### ISSUE TITLE
ActiveGroup has incorrect layering

### ISSUE THREAD

**Issue by inssein** [kangax/fabric.js#2118]
Fiddle:
https://jsfiddle.net/2zs3wy56/

If you select the orange rectangle on the left, and then shift + click orange rectangle on the right, it will properly create an active group of two, but now the third red rectangle is behind both.

This is probably because the active group is rendered in the upper canvas right?

**Comment by asturur** [comment]
No.
everything is rendered on main canvas more or less.
the activeGroup is rendered later and so in on top.

to do it different enable cancas.preserveObjectStacking = true.

it will then render fine.

**Comment by inssein** [comment]
@asturur ah I was just editing my post as I discovered the same. 

That said, the fix you suggested introduces a new bug. It render's the orange rectangles in the top left.

Fiddle: https://jsfiddle.net/knr61L12/

**Comment by asturur** [comment]
@kangax is gonna kill me.

**Comment by inssein** [comment]
@asturur haha, hope not. I am available to help on this, just trying to think of what the correct fix is.

Issue: preserveObjectStacking is drawing the objects which are grouped, but its not going through transform() since the group's render() function is not called, correct?

**Comment by asturur** [comment]
i know what is wrong, i m gonna put it back

**Comment by inssein** [comment]
@asturur awesome thanks!

**Comment by asturur** [comment]
PR #2120 fix it.
