### ISSUE TITLE
v1.5.0 Issue - Circle fill not saving correctly when converted to JSON

### ISSUE THREAD

**Issue by noctivityinc** [kangax/fabric.js#2119]
Just upgraded to 1.5 and found an immediately problem.

Im generating a group with the following circle and text:

![screen shot 2015-04-16 at 2 19 36 pm](https://cloud.githubusercontent.com/assets/78850/7188177/ee0fc718-e443-11e4-931a-343e39025654.png)

The circle is generated easily with:

    circle = new fabric.Circle
    radius: 12,
    fill: 'rgb(255,255,255)'
    stroke: '#dddddd'
    strokeWidth: 1
    originX: 'center'
    originY: 'center'

But when I ```JSON.stringify(canvas)``` the canvas the fill for the circle is stored as

    rgb(0,0,0)

Thanks,

Josh

**Comment by sapics** [comment]
Thank your for teaching!
I made the PR #2101 for fix this problem, and your post makes me think more about consistency with previous version.

**Comment by asturur** [comment]
regarding this issue, @noctivityinc you say the value is not stored correctly.
The PR #2101 is about loading back json, not storing it.

Could you be more precise if this is about storing or loading back?
Can you paste here your JSON string?

thanks.
