### ISSUE TITLE
Fabric JS native arrow shape support

### ISSUE THREAD

**Issue by ModestasM** [kangax/fabric.js#2125]
Hello,

It would be nice if fabric JS would support new kind of shape - arrow. Arrows are widely used and would nicely fit in other fabric JS shapes like rectangle/triangle/circle/line...

**Comment by kangax** [comment]
This is out of scope for the Fabric core, at the moment (but should be easy to implement on an app level)

**Comment by ModestasM** [comment]
why it is out of scope? we have rectangles/lines/circles why arrow is out of scope?

**Comment by kangax** [comment]
For one, it's a compound shape. It could be made with triangle and a line combined into a group. So it's not on the same level of abstraction in my eyes (comparing to line, circle, etc.). Second, there's a multitude of different aspects of arrows I can think of. Which ones do we implement? Fabric is already huge. We're trying hard not to suffer from the featuritis. Which options would arrows have? Everyone might want it slightly different. This will add more stuff to the library, more maintenance, more weight. Arrows are sometimes requested but it's not the most popular feature by far, so we'd be adding complexity in exchange of questionable value. I hope this explains it.

**Comment by mdtahmid** [comment]
We want arrows!

**Comment by asturur** [comment]
fabricjs is flexible
should not be hard to create a custom class that does it for you.
for sure not something we want to do in the base lib.

**Comment by butch2k** [comment]
You could create a class relying on an svg image for display. 






On Fri, Mar 3, 2017 at 10:14 AM +0100, "Andrea Bogazzi" <notifications@github.com> wrote:












fabricjs is flexible

should not be hard to create a custom class that does it for you.

for sure not something we want to do in the base lib.

**Comment by krunal** [comment]
I have recently written a blog to about how to draw an arrow with fabricjs which also includes jsfiddle example. I hope this will someone. https://blog.thirdrocktechkno.com/how-to-draw-an-arrow-using-html-5-canvas-and-fabricjs-9500c3f50ecb

**Comment by HeyWrecker** [comment]
@krunal I saw that your "how to draw a line" article is still up, but the one about drawing an arrow does not seem to be available any longer. Do you still have a link for it somewhere?
