### ISSUE TITLE
Find better formula for sepia filter, and keep one filter.

### ISSUE THREAD

**Issue by hellomaya** [kangax/fabric.js#2132]
Here is the original one, and the result color is closed to pink somehow : 

```
avg = 0.3  * data[i] + 0.59 * data[i + 1] + 0.11 * data[i + 2];
data[i] = avg + 100;
data[i + 1] = avg + 50;
data[i + 2] = avg + 255;
```

We used this matrix in SVG to achieve Sepia effect : 

```

"0.30 0.30 0.30 0 0 ',
'0.25 0.25 0.25 0 0 ',
'0.20 0.20 0.20 0 0 ',
'0.00 0.00 0.00 1 0"
```

From that, we got this formula : 

```
var r, g, b;
r = parseFloat(data[i]);
g = parseFloat(data[i + 1]);
b = parseFloat(data[i + 2]);

data[i] = 0.3 * (r + g + b);
data[i + 1] = 0.25 * (r + g + b);
data[i + 2] = 0.20 * (r + g + b);
```

The result is more close to this : 

![abc](https://cloud.githubusercontent.com/assets/4657101/7230467/c9e64460-e7a0-11e4-9320-c75703fdb553.png)
##

**Comment by asturur** [comment]
We also have sepia2 filter, did you try if the result looks more natural?
Is there any reference from some open source graphic tool to do a standard sepia filter or the "Sepia" tone is just a general guideline and implementation dependant?

**Comment by hellomaya** [comment]
@asturur from [http://en.wikipedia.org/wiki/Sepia_(color)](http://en.wikipedia.org/wiki/Sepia_(color)), I think Sepia is closed to brown, currently sepia and sepia2 seems not close, sepia is a bit red, and sepia2 is a bit yellow. Check this, [http://fabricjs.com/image-filters/](http://fabricjs.com/image-filters/)

**Comment by hellomaya** [comment]
I googled, and there are many different color matrix, I think this one looks good:

```
new float[] {.393f, .349f, .272f, 0, 0}, 
new float[] {.769f, .686f, .534f, 0, 0}, 
new float[] {.189f, .168f, .131f, 0, 0}, 
new float[] {0, 0, 0, 1, 0}, 
```

Here is the reference [https://code.msdn.microsoft.com/windowsapps/ColorMatrix-Image-Filters-f6ed20ae](https://code.msdn.microsoft.com/windowsapps/ColorMatrix-Image-Filters-f6ed20ae)
