### ISSUE TITLE
Shadows not appearing 'below' rects in 1.5.0 release

### ISSUE THREAD

**Issue by philiptyler** [kangax/fabric.js#2134]
After upgrading to 1.5 release w/Interaction, Text, Shadows and Pattern from 1.4 w/ same packages, shadows do not appear 'under' the Rects I create.  Here's how I was creating the Rects and their shadows in 1.4:

            var rackRect = new fabric.Rect({
                left: model.getLeftOffset(),
                top: model.getTopOffset(),
                height: rackHeight,
                width: rackWidth,
                stroke: 'black',
            });

...then later in the code...

            rackRect.scale(scaleFactor);
            rackRect.setTop(relativeCenterDiff.top * scaleFactor + centerOfCanvas.top);
            rackRect.setLeft(relativeCenterDiff.left * scaleFactor + centerOfCanvas.left);
            rackRect.setShadow({
                color: 'rgba(0,0,0,0.6)',
                blur: 20,
                offsetX: 10,
                offsetY: 10,
                opacity: 0.6,
                fillShadow: true,
                strokeShadow: true
            });
            rackRect.setCoords();

Now in 1.5 this code results in a single shadow at the bottom right corner of the canvas.  (see figure attached)

![badshadow](https://cloud.githubusercontent.com/assets/5661626/7240614/3f75ae3a-e767-11e4-85ea-b0c36051b9ab.PNG)

**Comment by philiptyler** [comment]
I have also tried setting the shadow in the Rect constructor options and using setShadow after creating the new Rect.  Both result in the same bottom right corner shadow.

**Comment by asturur** [comment]
How big is scale factor?
Some time ago we fixed shadow to take in consideration the scale factor.

**Comment by philiptyler** [comment]
It varies based on user data, but in this case it is 31.589338598223105

**Comment by asturur** [comment]
With a offset of 10 , by 31, you have shadow 310 pixel away from your rect more or less, that could be that bottom right corner.
try to divide offset by scale factor and see if everything comes back to usual.

**Comment by philiptyler** [comment]
This worked!


                rackRect.setShadow({
                    color: 'rgba(0,0,0,0.6)',
                    blur: 20 / scaleFactor,
                    offsetX: 10 / scaleFactor,
                    offsetY: 10 / scaleFactor,
                    opacity: 0.6,
                    fillShadow: true,
                    strokeShadow: true
                });
