### ISSUE TITLE
Canvas JSON representation inconsistent between 1.5.0 and v1.4.x

### ISSUE THREAD

**Issue by pjanik** [kangax/fabric.js#2139]
When I serialize FabricJS canvas in v1.4.11 (`var state = canvas.toJSON()`) and then load it in v1.5.0 (`canvas.loadFromJSON(state);`), I don't get the same scene - positions of paths are different. Other shapes seem to work fine.

In general the internal representation of path has been changed recently in an incompatible manner (between v1.4.11 and v1.5.0). While we can update our code to handle that (it's simple), the inconsistency in JSON representation is more problematic. We have a lot of stored JSONs that were created by users of our FabricJS-v1.4.11-based app and we still need to be able to load them correctly.

**Comment by asturur** [comment]
would you be so kind to sum up the differencies?

**Comment by pjanik** [comment]
Sure. 

Here is an example scene (the main part is FabricJS canvas, 800x600px) with a path created using Fabric's free drawing brush:
![screen shot 2015-04-21 at 21 20 51](https://cloud.githubusercontent.com/assets/767857/7260711/5821fda2-e86c-11e4-98d9-ff6b93e5d2ae.png)

I've tried to recreate the same scene in app based on Fabric v1.5.0 and v1.4.11, but of course it's not perfectly identical. Good enough to easily see the differences in serialization though.

The main difference is that in v1.4.11 path coordinates are starting from (0,0) and `pathOffset` seems to be always (0,0). While in v1.5.0 path coordinates are starting from bounding box (left, top) and `pathOffset` is equal to (left, top).

BTW, I can't say any of these patterns make sense to me. I would expect either some offset and coordinates starting from (0,0) or real coordinates without any offset. But obviously I don't know the internals, just saying.

I can correctly import v1.4.11 JSON into v1.5.0 if I manually set `pathOffset` to (width * 0.5, height * 0.5) - don't ask me why, I can see it works.

Fabric v1.5.0 `canvas.toJSON()` result:
```
{
    "objects": [
        {
            "type": "path",
            "originX": "center",
            "originY": "center",
            "left": 328.25,
            "top": 286.13,
            "width": 37.5,
            "height": 32,
            "fill": null,
            "stroke": "#333",
            "strokeWidth": 8,
            "strokeDashArray": null,
            "strokeLineCap": "round",
            "strokeLineJoin": "round",
            "strokeMiterLimit": 10,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "clipTo": null,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "globalCompositeOperation": "source-over",
            "lockUniScaling": false,
            "path": [
                [
                    "M",
                    309.5,
                    270.125
                ],
                [
                    "Q",
                    309.5,
                    270.125,
                    310,
                    270.125
                ],
                [
                    "Q",
                    310.5,
                    270.125,
                    310.25,
                    270.625
                ],
                (...)
                [
                    "Q",
                    346,
                    302.125,
                    346.5,
                    302.125
                ],
                [
                    "L",
                    347,
                    302.125
                ]
            ],
            "pathOffset": {
                "x": 328.25,
                "y": 286.125
            }
        }
    ],
    "background": "#fff"
}
```

Fabric v1.4.11 `canvas.toJSON()` result:
```
{
    "objects": [
        {
            "type": "path",
            "originX": "center",
            "originY": "center",
            "left": 330.75,
            "top": 284.63,
            "width": 32,
            "height": 29,
            "fill": null,
            "stroke": "#333",
            "strokeWidth": 8,
            "strokeDashArray": null,
            "strokeLineCap": "round",
            "strokeLineJoin": "round",
            "strokeMiterLimit": 10,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "clipTo": null,
            "backgroundColor": "",
            "lockUniScaling": false,
            "path": [
                [
                    "M",
                    0,
                    0
                ],
                [
                    "Q",
                    0,
                    0,
                    0.5,
                    0
                ],
               (...)
                [
                    "Q",
                    32.5,
                    28,
                    32.5,
                    28.5
                ],
                [
                    "L",
                    32.5,
                    29
                ]
            ],
            "pathOffset": {
                "x": 0,
                "y": 0
            }
        }
    ],
    "background": "#fff"
}
```

**Comment by pjanik** [comment]
BTW, do you try to keep JSON format compatible between different FabricJS versions at all?
I mean if it's an explicit requirement during the development or if it's just random and not guaranteed.

**Comment by asturur** [comment]
We of course try.
The problem is that from 1.4.11 the path went trought lot of rewrites to fix the rendering issue from SVG and general rendering problem.
I took care of that and i'm sure i didn't check json output, so i may have created the issue.
This is not intended behaviour of course. Not sure if this is fixable now.
