### ISSUE TITLE
Canvas to JSON - custom object properties getting cleared

### ISSUE THREAD

**Issue by T-Thomas** [kangax/fabric.js#2142]
For printing solution, I am saving canvas data in JSON format into database. Then , I fetch those data from database and bind them in canvas. Here custom added object's properties are getting cleared sometimes at the time of updating the modified objects into database (i.e., I can't get any custom objects' properties). 

My coding is as below,

`` <canvas id="canvasFrontPage" runat="server" clientidmode="static" style="border: 2px solid #444;"></canvas> ``

`` var frontCanvas = new fabric.Canvas('canvasFrontPage', {
                    backgroundColor: '#ffffff'
                });``

`` frontCanvas.renderAll(); ``

Now I am adding text from textbox with some properties by clicking a button as below ,

`` $("#btnFrontPageAddText").click(function (e) {
                    var enteredTxt = $.trim($("#txtFrontPageInsertText").val()).replace(/ +(?= )/g, '');
                    var lockVal = ($("#ddlFrontPageLock").val().toLowerCase() == "2") ? true : false;
                    var lockType = $("#ddlFrontPageLock").val(); ``

                    if (enteredTxt.length > 0) {
                        var txt = new fabric.Text(enteredTxt, {
                            fill: $("#txtFrontPageColor").val(),
                            fontSize: $("#ddlFrontPageFontSize  option:selected").text(),
                            fontFamily: $("#ddlFrontPageFontFamily option:selected").text(),
                            fontWeight: $("#ddlFrontPageFontWeight option:selected").text(),
                            textAlign: $("#ddlFrontPageTextAlign option:selected").text(),
                            fontStyle: $("#ddlFrontPageFontStyle option:selected").text(),
                            textDecoration: $("#ddlFrontPageTextDecoration option:selected").text(),
                            lineHeight: $("#ddlFrontPageLineHeight option:selected").text(),
                            opacity: $("#ddlFrontPageOpacity option:selected").text(),
                            optionType: 2,
                            colorFilled: $("#txtFrontPageColor").val(),
                            fontSizeVal: $("#ddlFrontPageFontSize").val(),
                            fontFamilyVal: $("#ddlFrontPageFontFamily").val(),
                            fontWeightVal: $("#ddlFrontPageFontWeight").val(),
                            textAlignVal: $("#ddlFrontPageTextAlign").val(),
                            fontStyleVal: $("#ddlFrontPageFontStyle").val(),
                            textDecorationVal: $("#ddlFrontPageTextDecoration").val(),
                            lineHeightVal: $("#ddlFrontPageLineHeight").val(),
                            opacityVal: $("#ddlFrontPageOpacity").val(),
                            lockScalingX: true,
                            lockScalingY: true,
                            lockType: lockType,
                            lockMovementX: lockVal,
                            lockMovementY: lockVal,
                            lockRotation: lockVal
                        });

                        txt.toObject = (function (toObject) {
                            return function () {
                                return fabric.util.object.extend(toObject.call(this), {
                                    optionType: this.optionType,
                                    colorFilled: this.colorFilled,
                                    fontSizeVal: this.fontSizeVal,
                                    fontFamilyVal: this.fontFamilyVal,
                                    fontWeightVal: this.fontWeightVal,
                                    textAlignVal: this.textAlignVal,
                                    fontStyleVal: this.fontStyleVal,
                                    textDecorationVal: this.textDecorationVal,
                                    lineHeightVal: this.lineHeightVal,
                                    opacityVal: this.opacityVal,
                                    lockScalingX: this.lockScalingX,
                                    lockScalingY: this.lockScalingY,
                                    lockType: this.lockType,
                                    lockMovementX: this.lock,
                                    lockMovementY: this.lock,
                                    lockRotation: this.lock
                                });
                            };
                        })(txt.toObject);

                        txt.optionType = 2;
                        txt.colorFilled = $("#txtFrontPageColor").val();
                        txt.fontSizeVal = $("#ddlFrontPageFontSize").val();
                        txt.fontFamilyVal = $("#ddlFrontPageFontFamily").val();
                        txt.fontWeightVal = $("#ddlFrontPageFontWeight").val();
                        txt.textAlignVal = $("#ddlFrontPageTextAlign").val();
                        txt.fontStyleVal = $("#ddlFrontPageFontStyle").val();
                        txt.textDecorationVal = $("#ddlFrontPageTextDecoration").val();
                        txt.lineHeightVal = $("#ddlFrontPageLineHeight").val();
                        txt.opacityVal = $("#ddlFrontPageOpacity").val();
                        txt.lockScalingX = true;
                        txt.lockScalingY = true;
                        txt.lockType = lockType;
                        txt.lock = lockVal;

                        frontCanvas.add(txt);
                    }  
 `` frontCanvas.renderAll(); ``

Then I convert the canvas in json format as below and saved it in database .

`` var frontPageJSONData = JSON.stringify(frontCanvas); ``    

Then I bind those data from  database into canvas as below,

`` frontCanvas.loadFromJSON($("frontPageJSONData ").val()); ``
``  var frontCanvasObject = frontCanvas.getObjects();
                        var frontCanvasObjectLength = frontCanvasObject.length;
                        for (var i = 0; i < frontCanvasObjectLength; i++) {
                            var frontItemOptionType = frontCanvasObject[i].optionType;
                            if (Number(frontItemOptionType) == 2) {
                                var color = frontCanvasObject[i].colorFilled; ``

                                var fontSize = frontCanvasObject[i].fontSizeVal;

                                var fontFamily = frontCanvasObject[i].fontFamilyVal;

                                var fontWeight = frontCanvasObject[i].fontWeightVal;

                                var textAlign = frontCanvasObject[i].textAlignVal;

                                var fontStyle = frontCanvasObject[i].fontStyleVal;

                                var textDecoration = frontCanvasObject[i].textDecorationVal;

                                var lineHeight = frontCanvasObject[i].lineHeightVal;

                                var opacity = frontCanvasObject[i].opacityVal;

                                var lockType = frontCanvasObject[i].lockType;

                                var lockVal = (lockType == "2") ? true : false; ``

                                var txt = frontCanvasObject[i];
                                txt.toObject = (function (toObject) {
                                    return function () {
                                        return fabric.util.object.extend(toObject.call(this), {
                                            optionType: this.optionType,
                                            colorFilled: this.colorFilled,
                                            fontSizeVal: this.fontSizeVal,
                                            fontFamilyVal: this.fontFamilyVal,
                                            fontWeightVal: this.fontWeightVal,
                                            textAlignVal: this.textAlignVal,
                                            fontStyleVal: this.fontStyleVal,
                                            textDecorationVal: this.textDecorationVal,
                                            lineHeightVal: this.lineHeightVal,
                                            opacityVal: this.opacityVal,
                                            lockScalingX: true,
                                            lockScalingY: true,
                                            lockType: this.lockType,
                                            lockMovementX: this.lock,
                                            lockMovementY: this.lock,
                                            lockRotation: this.lock
                                        });
                                    };
                                })(txt.toObject);

                                txt.optionType = 2;
                                txt.colorFilled = color;
                                txt.fontSizeVal = fontSize;
                                txt.fontFamilyVal = fontFamily;
                                txt.fontWeightVal = fontWeight;
                                txt.textAlignVal = textAlign;
                                txt.fontStyleVal = fontStyle;
                                txt.textDecorationVal = textDecoration;
                                txt.lineHeightVal = lineHeight;
                                txt.opacityVal = opacity;
                                txt.lockType = lockType;
                                txt.lock = lockVal;
                            }
               frontCanvas.renderAll(); ``

Here, I couldn't get properties of text object.

**Comment by asturur** [comment]
if i m not wrong, when you call toObject method, you can pass an array of properties that extend the normal toObject serialization.

in this array you can pass the custom properties you want to serialize.

**Comment by T-Thomas** [comment]
Hi @asturur ,

For the first time, it works. Again saving the canvas as json in database after updating the objects, "sometimes" the custom properties are cleared.
For eg.,  I got this problem when

    1. Adding multiple images in canvas
    2. Scaling image too many times.

**Comment by T-Thomas** [comment]
Hi @kangax  ,
         This issue creates a big problem to me in printing purpose. So, it will be better to have solution for this.

**Comment by hellomaya** [comment]
@T-Thomas 

In my experience, the custom properties shouldn't be object, but simple value, e.g. 

```
text.customProperty = {title: "hello world", name: ...} // wrong

// better
text.customPropertyTitle = "hello world";
text.customPropertyName = ".."; 
```
Also take care if the object is shared among many instance, then it could wrong too
Hope it helps.

**Comment by T-Thomas** [comment]
Hi @hellomaya ,
                              Currently, I am saving the canvas objects as template in JSON format. Then for     re-assigning those objects back, I am using the format as below,

    `` var txt = frontCanvasObject[i];
                            txt.toObject = (function (toObject) {
                                return function () {
                                    return fabric.util.object.extend(toObject.call(this), {
                                        optionType: this.optionType,
                                        colorFilled: this.colorFilled,
                                        fontSizeVal: this.fontSizeVal,
                                        fontFamilyVal: this.fontFamilyVal,
                                        fontWeightVal: this.fontWeightVal,
                                        textAlignVal: this.textAlignVal,
                                        fontStyleVal: this.fontStyleVal,
                                        textDecorationVal: this.textDecorationVal,
                                        lineHeightVal: this.lineHeightVal,
                                        opacityVal: this.opacityVal,
                                        lockScalingX: true,
                                        lockScalingY: true,
                                        lockType: this.lockType,
                                        lockMovementX: this.lock,
                                        lockMovementY: this.lock,
                                        lockRotation: this.lock
                                    });
                                };
                            })(txt.toObject);

                            txt.optionType = 2;
                            txt.colorFilled = color;
                            txt.fontSizeVal = fontSize;
                            txt.fontFamilyVal = fontFamily;
                            txt.fontWeightVal = fontWeight;
                            txt.textAlignVal = textAlign;
                            txt.fontStyleVal = fontStyle;
                            txt.textDecorationVal = textDecoration;
                            txt.lineHeightVal = lineHeight;
                            txt.opacityVal = opacity;
                            txt.lockType = lockType;
                            txt.lock = lockVal;
                        }
            
I already assigned simple values to text object. For reference see above coding...

**Comment by kangax** [comment]
Can't reproduce. Custom properties are "exported" properly when specifying argument in `toObject`
