### ISSUE TITLE
Minify option for uglifyjs

### ISSUE THREAD

**Issue by sapics** [kangax/fabric.js#2147]
At version 1.5.0, the size of [fabric.min.js](https://github.com/kangax/fabric.js/blob/0e0816aca59499de0466cff2f823608645bb6973/dist/fabric.min.js) is **228,077** bytes, now, the size of [fabric.min.js](https://github.com/kangax/fabric.js/blob/master/dist/fabric.min.js) in kangax/master is **306,149** bytes.

There are not big changes to fabric.js between them, but size of minified version has big difference.
I guess that it depends on build enviroment like version of uglifyjs.

For me, smaller size is better for using in web.
Is it possible to add uglifyjs option in build.js, or, is it better to add option by manually each user?
For example, at https://github.com/kangax/fabric.js/blob/master/build.js#L56,
```diff
-    mininfierCmd = 'uglifyjs ' + amdUglifyFlags + ' --output fabric.min.js fabric.js' + sourceMapFlags;
+    mininfierCmd = 'uglifyjs ' + amdUglifyFlags + ' --compress --mangle --output fabric.min.js fabric.js' + sourceMapFlags;
```
https://github.com/mishoo/UglifyJS2#usage
In unit test, it has no change with fabric.js.

It makes fabric.min.js size to 227,090 bytes in my enviroment!

**Comment by kangax** [comment]
I'm pretty sure we had mangling on at one point when it was probably on by default. Could you please submit a PR? And good catch, thanks!

**Comment by sapics** [comment]
Sure!!
