### ISSUE TITLE
Not able to capture onMouse* events

### ISSUE THREAD

**Issue by srikanthguduru** [kangax/fabric.js#2152]
Hi , 

I am using fabric with node, with build option "ALL" . The issue i am facing is with "freeDraw" feature, such that nothing is getting drawn. 

Also I have checked the https://github.com/kangax/fabric.js/wiki/Fabric-gotchas,, the issue/nature defined in first para is what i am observing with a nested Canvas and a div being added to my original Canvas tag. Will create jsfiddle if you need it.

**Comment by asturur** [comment]
if you can create the jfiddle with the bug i will reopen the issue
