### ISSUE TITLE
IText clone error

### ISSUE THREAD

**Issue by m2broth** [kangax/fabric.js#2154]
Hi,

It is an error after cloning an iText object (use the fabric.util.object.clone function). After the iText object has been cloned it can't be edited (fabric doesn't go to the editing text mode)

**Comment by asturur** [comment]
Could you post a jsFiddle that show the problem?

Thanks.

**Comment by m2broth** [comment]
Sure. Here is http://jsfiddle.net/3jk3jvy7/1/

**Comment by m2broth** [comment]
I don't have time now to investigate this issue. I will be very grateful If you will provide to me the solution

**Comment by asturur** [comment]
This happens because click is not initialized.
Try this:

clonedItext.initBehavior();
http://jsfiddle.net/3jk3jvy7/2/

**Comment by m2broth** [comment]
Thanks!

I knew that the problem in this function, but didn't find the way to fix it in the clonning

**Comment by m2broth** [comment]
One moment.

We are used 1.4.13 version. Try this - https://jsfiddle.net/3jk3jvy7/3/. The text will be editable, but only one time. Any ideas how to fix this issue?

**Comment by asturur** [comment]
I suggested wrong solution.
We should not use clone to clone instances of fabricJs objects, but just normal javascript objects.

solution should be something like that, using the combination of toObject and fromObject.
https://jsfiddle.net/3jk3jvy7/4/

But as you see there is an error anyway. Not sure what is wrong here.

**Comment by asturur** [comment]
https://jsfiddle.net/3jk3jvy7/5/

oh ok, double error from me, iText is not async.
This is how you should use cloning.

**Comment by paulcanning** [comment]
I was having the same issue, so I have moved to using the fromObject method. However, some of my custom properties are not being copied to the new IText. How can I fix this, other then redefining each custom property?

**Comment by bcruddy** [comment]
@paulcanning [toObject](http://fabricjs.com/docs/global.html#toObject) accepts an array argument with the properties you want to include.

**Comment by paulcanning** [comment]
@bcruddy brilliant, thanks! I'll try it out later. I also noticed that fabric.Image.fromObject() doesn't seem to work too well either. Maybe the same thing?

**Comment by asturur** [comment]
what do you mean by "does not work well"?

**Comment by paulcanning** [comment]
Well, I tried "fabric.Image.fromObject(image.toObject())" and it simply didn't work!

**Comment by asturur** [comment]
it is async if i'm not wrong, so it should be:

```
fabric.Image.fromObject(image.toObject(), function(img) {
...
})
```

**Comment by paulcanning** [comment]
What should be put in the callback? Do I _need _a callback? I don't for IText...

**Comment by asturur** [comment]
```
  /**
   * Creates an instance of fabric.Image from its object representation
   * @static
   * @param {Object} object Object to create an instance from
   * @param {Function} [callback] Callback to invoke when an image instance is created
   */
  fabric.Image.fromObject = function(object, callback) {
    fabric.util.loadImage(object.src, function(img) {
      fabric.Image.prototype._initFilters.call(object, object.filters, function(filters) {
        object.filters = filters || [ ];
        fabric.Image.prototype._initFilters.call(object, object.resizeFilters, function(resizeFilters) {
          object.resizeFilters = resizeFilters || [ ];
          var instance = new fabric.Image(img, object);
          callback && callback(instance);
        });
      });
    }, null, object.crossOrigin);
  };
```

fromObject does not return anything in image.class
so something like:

```
var myClonedImage;
fabric.Image.fromObject(myImage.toObject(), function(cloned) {
  //if you need it later
  myClonedImage = cloned;
  //or just
  canvas.add(cloned);
});
```
