### ISSUE TITLE
1.5 Error Only: Cannot read property 'async' of undefined

### ISSUE THREAD

**Issue by noctivityinc** [kangax/fabric.js#2159]
I am trying to upgrade from 1.4.13 to 1.5.0 but no matter what I do I get 

```Uncaught TypeError: Cannot read property 'async' of undefined```

when trying to load a 1.4.13 JSON into 1.5.0 using loadFromJSON.

How can we load a 1.4.13 canvas object into 1.5.0?  Any way to see more debugging information than just that error message?

**Comment by kangax** [comment]
Can you please paste JSON

**Comment by noctivityinc** [comment]
In case you need the canvas object and yes, there are some custom elements saved with my JSON representation.

    {
        "objects": [{
            "type": "group",
            "originX": "left",
            "originY": "top",
            "left": 343.55,
            "top": 371.17,
            "width": 272.16,
            "height": 176.85,
            "fill": "rgb(0,0,0)",
            "stroke": null,
            "strokeWidth": 1,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeLineJoin": "miter",
            "strokeMiterLimit": 10,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "clipTo": null,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "globalCompositeOperation": "source-over",
            "metatype": "imageGroup",
            "url": "/ideas/3604",
            "id": 3604,
            "item_id": 2221,
            "objects": [{
                "type": "image",
                "originX": "left",
                "originY": "bottom",
                "left": -118.58,
                "top": 70.92,
                "width": 248.64,
                "height": 153.33,
                "fill": "rgb(0,0,0)",
                "stroke": "#f0eee4",
                "strokeWidth": 0,
                "strokeDashArray": null,
                "strokeLineCap": "butt",
                "strokeLineJoin": "miter",
                "strokeMiterLimit": 10,
                "scaleX": 1,
                "scaleY": 1,
                "angle": 0,
                "flipX": false,
                "flipY": false,
                "opacity": 1,
                "shadow": {
                    "color": "rgba(50, 50, 50, 0.5)",
                    "blur": 2,
                    "offsetX": 0,
                    "offsetY": 2
                },
                "visible": true,
                "clipTo": null,
                "backgroundColor": "",
                "fillRule": "nonzero",
                "globalCompositeOperation": "source-over",
                "src": "http://s3.amazonaws.com/Wecora-assets-dev/items/photos/000/002/221/large/open-uri20140426-69393-2vq6p3?1398534521",
                "filters": [],
                "crossOrigin": "Anonymous",
                "alignX": "none",
                "alignY": "none",
                "meetOrSlice": "meet"
            }, {
                "type": "circle",
                "originX": "center",
                "originY": "center",
                "left": -118.58,
                "top": 70.92,
                "width": 24,
                "height": 24,
                "fill": "rgb(255,255,255)",
                "stroke": "#dddddd",
                "strokeWidth": 1,
                "strokeDashArray": null,
                "strokeLineCap": "butt",
                "strokeLineJoin": "miter",
                "strokeMiterLimit": 10,
                "scaleX": 1,
                "scaleY": 1,
                "angle": 0,
                "flipX": false,
                "flipY": false,
                "opacity": 1,
                "shadow": null,
                "visible": true,
                "clipTo": null,
                "backgroundColor": "",
                "fillRule": "nonzero",
                "globalCompositeOperation": "source-over",
                "radius": 12,
                "startAngle": 0,
                "endAngle": 6.283185307179586
            }, {
                "type": "text",
                "originX": "center",
                "originY": "center",
                "left": -118.58,
                "top": 70.92,
                "width": 7.63,
                "height": 12,
                "fill": "#272822",
                "stroke": null,
                "strokeWidth": 1,
                "strokeDashArray": null,
                "strokeLineCap": "butt",
                "strokeLineJoin": "miter",
                "strokeMiterLimit": 10,
                "scaleX": 1,
                "scaleY": 1,
                "angle": 0,
                "flipX": false,
                "flipY": false,
                "opacity": 1,
                "shadow": null,
                "visible": true,
                "clipTo": null,
                "backgroundColor": "",
                "fillRule": "nonzero",
                "globalCompositeOperation": "source-over",
                "text": "B",
                "fontSize": 12,
                "fontWeight": "normal",
                "fontFamily": "Roboto",
                "fontStyle": "",
                "lineHeight": 1,
                "textDecoration": "",
                "textAlign": "left",
                "path": null,
                "textBackgroundColor": "",
                "useNative": true
            }]
        }, {
            "type": "group",
            "originX": "left",
            "originY": "top",
            "left": 11.84,
            "top": 39.54,
            "width": 383.07,
            "height": 304.47,
            "fill": "rgb(0,0,0)",
            "stroke": null,
            "strokeWidth": 1,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeLineJoin": "miter",
            "strokeMiterLimit": 10,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "clipTo": null,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "globalCompositeOperation": "source-over",
            "metatype": "imageGroup",
            "url": "/ideas/5965",
            "id": 5965,
            "item_id": 3507,
            "objects": [{
                "type": "image",
                "originX": "left",
                "originY": "bottom",
                "left": -174.04,
                "top": 134.74,
                "width": 600,
                "height": 469,
                "fill": "rgb(0,0,0)",
                "stroke": "#f0eee4",
                "strokeWidth": 0,
                "strokeDashArray": null,
                "strokeLineCap": "butt",
                "strokeLineJoin": "miter",
                "strokeMiterLimit": 10,
                "scaleX": 0.6,
                "scaleY": 0.6,
                "angle": 0,
                "flipX": false,
                "flipY": false,
                "opacity": 1,
                "shadow": {
                    "color": "rgba(50, 50, 50, 0.5)",
                    "blur": 2,
                    "offsetX": 0,
                    "offsetY": 2
                },
                "visible": true,
                "clipTo": null,
                "backgroundColor": "",
                "fillRule": "nonzero",
                "globalCompositeOperation": "source-over",
                "src": "http://s3.amazonaws.com/Wecora-assets-dev/items/photos/000/003/507/large/open-uri20140213-1290-t6w6i8?1426608233",
                "filters": [],
                "crossOrigin": "Anonymous",
                "alignX": "none",
                "alignY": "none",
                "meetOrSlice": "meet"
            }, {
                "type": "circle",
                "originX": "center",
                "originY": "center",
                "left": -174.04,
                "top": 134.74,
                "width": 24,
                "height": 24,
                "fill": "rgb(255,255,255)",
                "stroke": "#dddddd",
                "strokeWidth": 1,
                "strokeDashArray": null,
                "strokeLineCap": "butt",
                "strokeLineJoin": "miter",
                "strokeMiterLimit": 10,
                "scaleX": 1,
                "scaleY": 1,
                "angle": 0,
                "flipX": false,
                "flipY": false,
                "opacity": 1,
                "shadow": null,
                "visible": true,
                "clipTo": null,
                "backgroundColor": "",
                "fillRule": "nonzero",
                "globalCompositeOperation": "source-over",
                "radius": 12,
                "startAngle": 0,
                "endAngle": 6.283185307179586
            }, {
                "type": "text",
                "originX": "center",
                "originY": "center",
                "left": -174.04,
                "top": 134.74,
                "width": 7.93,
                "height": 12,
                "fill": "#272822",
                "stroke": null,
                "strokeWidth": 1,
                "strokeDashArray": null,
                "strokeLineCap": "butt",
                "strokeLineJoin": "miter",
                "strokeMiterLimit": 10,
                "scaleX": 1,
                "scaleY": 1,
                "angle": 0,
                "flipX": false,
                "flipY": false,
                "opacity": 1,
                "shadow": null,
                "visible": true,
                "clipTo": null,
                "backgroundColor": "",
                "fillRule": "nonzero",
                "globalCompositeOperation": "source-over",
                "text": "A",
                "fontSize": 12,
                "fontWeight": "normal",
                "fontFamily": "Roboto",
                "fontStyle": "",
                "lineHeight": 1,
                "textDecoration": "",
                "textAlign": "left",
                "path": null,
                "textBackgroundColor": "",
                "useNative": true
            }]
        }, {
            "type": "i-text",
            "originX": "left",
            "originY": "top",
            "left": 457.32,
            "top": 97.52,
            "width": 107.34,
            "height": 23.4,
            "fill": "#ffffff",
            "stroke": null,
            "strokeWidth": 1,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeLineJoin": "miter",
            "strokeMiterLimit": 10,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "clipTo": null,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "globalCompositeOperation": "source-over",
            "text": "This is some text",
            "fontSize": 18,
            "fontWeight": "normal",
            "fontFamily": "LouisianaRegular",
            "fontStyle": "",
            "lineHeight": 1.3,
            "textDecoration": "",
            "textAlign": "left",
            "path": null,
            "textBackgroundColor": "#9ebd9c",
            "useNative": true,
            "styles": {
                "0": {
                    "1": {},
                    "2": {},
                    "3": {},
                    "4": {},
                    "5": {},
                    "6": {},
                    "7": {},
                    "8": {},
                    "9": {},
                    "10": {},
                    "11": {},
                    "12": {},
                    "13": {},
                    "14": {},
                    "15": {},
                    "16": {}
                }
            }
        }],
        "background": "white"
    }

**Comment by noctivityinc** [comment]
JSON posted as requested.

**Comment by noctivityinc** [comment]
Any update / thoughts on this?  Thanks.

**Comment by asturur** [comment]
http://jsfiddle.net/asturur/9ocer5cm/2/

I took a simple jsfiddle with basic canvas and with the code posted i can load back from jsfiddle.
Can you be more specific about the problem? i did not get the erro.

**Comment by asturur** [comment]
@noctivityinc  did you had chance to check my jsfiddle? any update?

**Comment by noctivityinc** [comment]
@asturur sorry we just did a major release today.  Im going to try it out on Monday.  If it worked for you Im assuming its something I am doing in the object processor:

    , (e, object) ->
      object.set({
        lineHeight: 1,
      })

      object.setControlsVisibility 
        tl: true
        tr: true
        br: true
        bl: true
        ml: false
        mt: false
        mr: false
        mb: false
        mtr: true          

      object.on 'editing:exited', (ev) ->
        saveCanvas(canvas)

But Ill let you know.

**Comment by asturur** [comment]
The posted json works good.
