### ISSUE TITLE
top/left coordinates on rotation acting weird

### ISSUE THREAD

**Issue by balajmarius** [kangax/fabric.js#2161]
Top, left on rotation is acting weird when the object is rotated.

Is this intentional?
Does anybody has some idea how to solve this?

http://jsfiddle.net/5KKQ2/300/

**Comment by asturur** [comment]
as you can find in other issue, during rotation and scaling, the object is temporarly with origin in the center.

you can compensate this using half dimensions as offset or you can work with origin in center all the time.

**Comment by balajmarius** [comment]
Thanks, you can mark as solved!
