### ISSUE TITLE
Shift click can't remove objects from group selection

### ISSUE THREAD

**Issue by Alysander** [kangax/fabric.js#2170]
The kitchensink demo doesn't allow objects to be removed from the selection using shift click even
though there is code in the canvas_grouping.mixin that is apparently intending to support this inside _updateActivteGroup .

I had a look and _shouldClearSelection is now always clearing the entire selection if the target is contained in the group selection. Is removing individual objects a feature that's meant to be supported?

**Comment by kangax** [comment]
Yes, it's meant to be supported. Might be a regression.

**Comment by Alysander** [comment]
Adding objects to a scaled group is also broken, probably because getCenterPoint on the group doesn't seem to consider scale properly. Here's a screen grab from the kitchensink.

![group center point broken](https://cloud.githubusercontent.com/assets/9831748/7553451/2254756c-f73d-11e4-8f23-ae0f5ccc21d2.gif)
