### ISSUE TITLE
Skew Object and Fabric Control 

### ISSUE THREAD

**Issue by ashishbhattb** [kangax/fabric.js#2172]
Please check the below Fabric Js Example, How can i fix the control in skew position ?

Fabric js is not supporting Skew, any one has tried to fix ?

http://jsfiddle.net/Rq7hk/41/

Please guide me if any one has get success in this issue 

Regards,
Ashish Bhatt

**Comment by asturur** [comment]
We are working on that, there is not an immediate fix for control box, that is really the only thing we need to skew properly.

**Comment by kangax** [comment]
Duplicate of #726
