### ISSUE TITLE
How to identify the corner square box of a selected object is hovered?

### ISSUE THREAD

**Issue by rihanrahul** [kangax/fabric.js#2174]
Hi,

Is there any event to identify if mouse entered to the corner square boxes of a selected object? 
Because you are showing different mouse pointers on hovering different sides of boxes.

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group — https://groups.google.com/forum/#!forum/fabricjs — where someone will usually assist you.

The issue tracker is only for bugs and feature requests.

Thanks for your understanding!
