### ISSUE TITLE
mouse scaling bug

### ISSUE THREAD

**Issue by sapics** [kangax/fabric.js#2177]
A scaling by mouse might have a bug.

The scaled size of Line is twice larger than a expected size. The strokeWidth of object might cause this size difference.

http://jsfiddle.net/sapics/tt5zjjot/1/

![ezgif com-gif-maker 1](https://cloud.githubusercontent.com/assets/11169954/7507823/f9684946-f4b0-11e4-9493-7434eafb14ef.gif)

**Comment by asturur** [comment]
Have a little bit patience with this...

height is not defined in currentTransform... intentional or problem?
Width is defined bad. I think that strokewidth should be considered here. With particular attention to lines ( horizontal and vertical limit case ).

```
      this._currentTransform = {
        target: target,
        action: action,
        scaleX: target.scaleX,
        scaleY: target.scaleY,
        offsetX: pointer.x - target.left,
        offsetY: pointer.y - target.top,
        originX: origin.x,
        originY: origin.y,
        ex: pointer.x,
        ey: pointer.y,
        left: target.left,
        top: target.top,
        theta: degreesToRadians(target.angle),
        width: target.width * target.scaleX,
        mouseXSign: 1,
        mouseYSign: 1
      };
```


Past this in kitchensink execute tab to see even stranger behaviour in both horizontal and vertical scaling.
```
// clear canvas
canvas.clear();

// add red rectangle
canvas.add(new fabric.Line([100,100,100,200],{
      fill: 'red',
      stroke: 'red',
      strokeWidth: 500,
    }));


```

**Comment by sapics** [comment]
kitchensink code is much stranger!!
kitchensink use other build version of fabric.js?

As you noticed, width and height in currentTransform looks strange.

By the way, newScaleX is calculated in _setObjectScale at canva.class.js, as
`transform.newScaleX = localMouse.x / (target.width + strokeWidth / 2);`
If localMouse.x has analogy with size of width, I guess that newScaleX should be calculated as,
`transform.newScaleX = localMouse.x / (target.width + strokeWidth);`
Dose localMouse.x have analogy with size of width?

**Comment by asturur** [comment]
is stranger because i crafted code intentionally to make the bug bigger.

it needs a coherent check with ongoing and planned change :/
