### ISSUE TITLE
IText can't catch input via IME

### ISSUE THREAD

**Issue by jcppman** [kangax/fabric.js#2179]
Hi there,

multi-character input method editor (like most Chinese, Japanese IME) won't trigger `keypress` event when typing. So IText won't catch those input behaviors and won't render anything. 

To reproduce this problem, try to type Chinese or Japanese.

maybe listen to `input` event will solve this.

![image](https://cloud.githubusercontent.com/assets/5248918/7534644/1cc9302c-f5af-11e4-9c2e-937f5a584f8f.png)

**Comment by asturur** [comment]
Duplicate of #2051.
Yes listening to input event is indeed the solution.
We are working on it.

**Comment by FrankFang** [comment]
Hi, any update?
