### ISSUE TITLE
CORs issue in google chrome - it never unbinds drag when you release mouse

### ISSUE THREAD

**Issue by joshribakoff** [kangax/fabric.js#2185]
I have a canvas, and I have called `.loadFromJSON()` on it.

I have noticed if I load a json that has image objects blocked by CORs, I see this in the console (expected behavior):
```
Image from origin '' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin ' is therefore not allowed access.
```

What is not expected is that when I attempt to drag any items that are visible on the canvas, they start moving when I do a "mouse down", but when I do a "mouse up" & release the mouse button, the images continue to be dragged around. I can never unselect the object.

If the document I loaded doesn't have any images that were blocked by CORs, selecting & dragging objects works fine.

Is this expected behavior? How can I fix it?

**Comment by maddyingnam** [comment]
I was having the same issue when calling `.Image.FromURL` on SVG images served over AWS S3. I did CORS configuration on my AWS S3 bucket and it works fine.

**Comment by joshribakoff** [comment]
By the way in regards to my original question about "How can I fix it?" I fixed it by wrapping my calls to Fabric, and validating the URLs & ensuring any invalid URLs are "fixed" before passing them into Fabric, this way the error condition in Fabric is never exposed. Still seems like a bug in Fabric even though it was easy enough to work around.

**Comment by Bnaya** [comment]
Well you can look at it as a contractual and not a defensive api,
in js you don't need to even try to glitch apis

In that case its looks like the library ignores image loads failures (even 404) 
https://github.com/kangax/fabric.js/blob/master/src/shapes/image.class.js#L557-L561
On failure the fabric.util.loadImag callback param would be null
https://github.com/kangax/fabric.js/blob/master/src/util/misc.js#L241

**Comment by noctivityinc** [comment]
@maddyingnam can you post your CORS settings that fixed this issue?  Do you also have a bucket security policy setup?  Thanks.

**Comment by joshribakoff** [comment]
@Bnaya The author forgot some error handling logic. Its not really feasible to "fix" this library's private state from outside the library. This has nothing to do with JS, please don't put down JS as a language, that is very subjective.

@noctivityinc Try outputting a CORs header like this (if using PHP for backend):
```php
header('Access-Control-Allow-Origin:*');
```

**Comment by noctivityinc** [comment]
@joshribakoff Thanks but were not clear on your response.  We're using Rails but we dont know what you mean by outputting the CORS header.  The images we have are stored on S3, not our own server, but were still having these issues.

Also, how would you monkey patch fabric.js to handle these issues if it is a fabric issue?  I have no problem patching my local copy.

**Comment by joshribakoff** [comment]
@noctivityinc  I'm not familiar with FabricJS internals, but I reckon you'd have to move the "mouseup" and/or "mousedown" event handlers to both either occur before, or both occur after the image loading. This way, if an error occurs & halts execution either both events are bound, or both not bound. (as opposed to only 1 of the events being bound). I'm not clear if this is the actual issue, but I'm guessing it is.

As far as your cors header, I found this S3 documentation - http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html Normally you would not need a CORs header to load a simple image, but if its loading the image via an XHR request you would need the header. You could probably also use a cname on your DNS to include the s3 bucket into your domain namespace, to circumvent cors restrictions.

**Comment by noctivityinc** [comment]
Thanks.



Joshua Lippiner  
.:t 704.323.5661
.:e jlippiner@noctivity.com (mailto:jlippiner@noctivity.com)
