### ISSUE TITLE
[IText] style duplication on inserting new line

### ISSUE THREAD

**Issue by milan-w** [kangax/fabric.js#2188]
Given the following situation: a text has mutliple lines. One line has styles, the preceding and the following line have no styles. If a new line is inserted somewhere before the line with styles, the styles get duplicated on the preceding line.

This is due to the function shiftLineStyles copying styles from line to line +1 but never overwriting or deleting the old style.

See http://jsfiddle.net/cygvj607/1/ (the fiddle shows two fixes, the error can be seen when clicking "fixed insertNewlineStyleObject")

**Comment by asturur** [comment]
Can i ask you on which version are you making tests?
Because AFTER 1.5.0 we changed style handling.

Did you check on latest code?

**Comment by milan-w** [comment]
Yes, all tests are made on the latest master (1.5.0)
