### ISSUE TITLE
text.set('globalCompositeOperation','xor');

### ISSUE THREAD

**Issue by webmak** [kangax/fabric.js#2192]
var textContent = $(this.JQ_TEXT_CONTENT_IND).val();
var text = new fabric.Text(textContent, { left: 100, top: 100 });
text.set('globalCompositeOperation','xor');
this.mainCanvas.add(text).setActiveObject(text);
text.center().setCoords();

globalCompositeOperation 'xor' again not working

**Comment by asturur** [comment]
as you see from this screenshot with your code, it works.
Look the 'adsadasdasd' test, it is XORing with the yellow background.

![image](https://cloud.githubusercontent.com/assets/1194048/7591710/aadd4880-f8cf-11e4-9daf-125933461a20.png)

Please if you need further assistance, first create a jsfiddle where the bug is clearly visible.
If it is of not immediate understanding add an explanation of why you think it is not working.

**Comment by webmak** [comment]
Funny, in my side I have problem, ok I'll will look why.
Thanks

**Comment by webmak** [comment]
thanks for quick support.

**Comment by webmak** [comment]
![2015-05-12 19 21 05](https://cloud.githubusercontent.com/assets/10329044/7592473/161ea574-f8dc-11e4-9a8c-4644e5be4431.png)

**Comment by webmak** [comment]
here I try the same but it is not working

**Comment by webmak** [comment]
It work fine in chrome but in firefox it is not working

**Comment by asturur** [comment]
Operative system and firefox version?

Windows and firefox here is fine.

![image](https://cloud.githubusercontent.com/assets/1194048/7592696/1618a6ee-f8d5-11e4-8ffb-b39b2c5802d6.png)

**Comment by webmak** [comment]
debian jessie  
iceweases 31.6.0
AMD FX-8320 FD8320FRHKBOX
GIGABYTE GA-970A-DS3 
MSI GeForce GT640 N640-1GD5/LP
GOODRAM 8 GB DDR3 1333 MHz (GR1333D364L9/8G)
Seagate Barracuda 7200.14 ST1000DM003 
Chieftec A-80 CTG-600-80P

**Comment by webmak** [comment]
xor is working, but with text not.

**Comment by webmak** [comment]
I have the same problem with svg, but I hav finde some solution
setGlobalCompositeOperation: function(object, type){
        if(object.imageType == 'svg'){
            for (var i = 0; i < object.paths.length; i++) {
               this.setGlobalCompositeOperation(object.paths[i], type);
            }
        }else{
            object.set('globalCompositeOperation', type);
        }
    }
object.imageType is my fabricjs override, you need use some else to check image type
If you do not want to my notes just say, I wrote it for help other who will look for this
