### ISSUE TITLE
Circle.setRadius doesn't return anything

### ISSUE THREAD

**Issue by joewashear007** [kangax/fabric.js#2196]
While looking through the source code, I discovered that Circle.setRadius() doesn't return a value, though the JSDoc says it does. This can be seen in the code easily. Is this an issues with the documentation or the code?

Code from Github:
```
    /**
     * Sets radius of an object (and updates width accordingly)
     * @return {Number}
     */
    setRadius: function(value) {
      this.radius = value;
      this.set('width', value * 2).set('height', value * 2);
    },
```

Version: Github Master
Reproduce:
```
var c = new fabric.Circle();
c.setRadius(5)  // <-- returns undefined
```

**Comment by asturur** [comment]
i should check, bu i think it should be chainable like other methods.

**Comment by joewashear007** [comment]
That would make sense. I think there might be some other functions in that
need top be updated to make them chainbale
Joe

Joseph Livecchi
jjprograms.com
