### ISSUE TITLE
Gradient forObject ?

### ISSUE THREAD

**Issue by joewashear007** [kangax/fabric.js#2198]
Is the function supposed to be fromObject?
Found in <https://github.com/kangax/fabric.js/blob/master/src/gradient.class.js>, line 375

```
/**
     * Returns {@link fabric.Gradient} instance from its object representation
     * @static
     * @memberof fabric.Gradient
     * @param {Object} obj
     * @param {Object} [options] Options object
     */
    forObject: function(obj, options) {
      options || (options = { });
      _convertPercentUnitsToValues(obj, options.coords, 'userSpaceOnUse');
      return new fabric.Gradient(options);
}
```

**Comment by asturur** [comment]
not really is a little bit different.
When restoring gradient from object form ( options is the object form of the gradient ) we need to know on whick object it will be applied to construct it properly.
I don't think is a mispell. But i never noticed it before anyway.

**Comment by kangax** [comment]
It's used like this — https://github.com/kangax/fabric.js/blob/d3c446d7928f7d0fa102a3886f1ca6002587525c/src/shapes/object.class.js#L1331
