### ISSUE TITLE
Can I draw svg on canvas using loadImage in place of loadSVGFromURL?

### ISSUE THREAD

**Issue by sudheer496** [kangax/fabric.js#2199]
Hi 

I tried loading svg using loadImage , instead of loadSVGFromURL as shown in the given fiddle.
http://jsfiddle.net/93f4nd3h/17/
I found no issues using this approach.So I just want to confirm with you guys whats the intention behind implementing such a huge parser ? 
My question would be , Can I go ahead with this approach ?
If not why should I render it using loadSVGFromURL(), Are there any advantages if I use loadSVGFromURL() instead of loadImage()?

Thanks,
Sudheer

**Comment by asturur** [comment]
when loaded as an image the svg is like any other image. you can use filters on it and crop it.

when loaded as a pathgroup the svg keeps all its original vector informations, you can acces every piece and modify aspect and properties. you can exctract shapes and use for clipping.
