### ISSUE TITLE
Fabricjs 1.5 with gesture

### ISSUE THREAD

**Issue by CSI68** [kangax/fabric.js#2200]
Hello,

Is it any way to get Fabricjs 1.5 with gesture support ?
If I download from custom build, animate is not include...
And on the demo page it's Fabricjs 1.4

Thanks,

Clément

**Comment by sudheer496** [comment]
Download the source code from here 
https://github.com/kangax/fabric.js/releases/tag/v1.5.0

And build it using node 
node build.js modules=ALL

**Comment by asturur** [comment]
better you download the latest one. we did mainly bugfixing, some of them very important.

**Comment by CSI68** [comment]
Ok thanks but I don't know about Node.js. Is there any cdn version ?

**Comment by sudheer496** [comment]
you can find the steps to build under Building section in the below link
https://github.com/kangax/fabric.js

**Comment by kangax** [comment]
I updated it to 1.5.0
