### ISSUE TITLE
i-text border selection when font weight changed for selected styles

### ISSUE THREAD

**Issue by sarath-prohaktiv** [kangax/fabric.js#2201]
This issue exist even in the kitchen sink demo. To replicate do the following steps

#1) Select some text [inside the i-text]
#2) Change font size large or small
#3) again select the i-text
#4) The border selection broken now.

Please see the screen shot
![image](https://cloud.githubusercontent.com/assets/7422434/7666101/6f4fd4e0-fbf4-11e4-91ca-76ed7e817e1e.png)

**Comment by asturur** [comment]
ok i have to force cacheclear on any font change.

**Comment by asturur** [comment]
Do you use setSelectionStyle to change the style of the text?
Or you manually access the style property?

**Comment by sarath-prohaktiv** [comment]
This example is from the fabric demo server.
You can reproduce this by calling setSelectionStyles with property fontSize

**Comment by asturur** [comment]
i see the error, i was asking if you found out in some other way.
Found the problem:
```
      this._setTextStyles(ctx);

      if (this._shouldClearCache()) {
        this._initDimensions(ctx);
      }
```
Even if we clear cache manually, at next render cycle, _initDimensions is performed just if shouldClearCache() returns true.
We should have some boolean  to enforce running _iniDimensions OR we should check in shouldClearCache() the check over style ( performance hit on big text chunks with lot of style )
