### ISSUE TITLE
snapping i-text on grid

### ISSUE THREAD

**Issue by fix2015** [kangax/fabric.js#2205]
Hey, i am try to snapping on grid, like this http://jsfiddle.net/S9sLu/802/, but have some pb with i-text obj, if i use default font all fine but if i use different for example Arial i have some space with grid line
![2015-05-18 10 58 02](https://cloud.githubusercontent.com/assets/3988392/7676919/ab2a3066-fd50-11e4-8eb3-bb8b7074bfdc.png)

Maybe somebody have same pb and know have fix it?

**Comment by fix2015** [comment]
but i need like this
![2015-05-18 11 29 57](https://cloud.githubusercontent.com/assets/3988392/7676987/3ddfead6-fd51-11e4-9c9c-bcb01d595424.png)

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group — https://groups.google.com/forum/#!forum/fabricjs — where someone will usually assist you.

The issue tracker is only for bugs and feature requests.

Thanks for your understanding!

**Comment by fix2015** [comment]
Sorry, but i think its bug, because i-text have some strange space, and it will be good if can delete this space
![2015-05-18 12 10 28](https://cloud.githubusercontent.com/assets/3988392/7684186/d42b0a44-fd8c-11e4-9af4-389d44a29c6b.png)

**Comment by fix2015** [comment]
Если что я могу и сам исправить, только мне нужно небольшие напутствия чтобы я знал куда двигаться.

**Comment by sapics** [comment]
@fix2015 I guess that a space come from FONT.
Adobe Illustrator has same behavior.

![ws000022](https://cloud.githubusercontent.com/assets/11169954/7716793/2f84fe22-fed2-11e4-8b44-15fab838ede4.png)

**Comment by asturur** [comment]
thanks @sapics for putting time on this

**Comment by sapics** [comment]
:smile:

**Comment by fix2015** [comment]
thx for information
