### ISSUE TITLE
Fabric JS IText object cursor position is off.

### ISSUE THREAD

**Issue by chetanbura** [kangax/fabric.js#2210]
Hello Kangax,

Fabric JS IText object while editing the text, when I am clicking in between the text then cursor position is correct but when I am clicking end of line with some additional white space the cursor position is going to next line.
You can find this issue on fabric demo
http://fabricjs.com/test/misc/itext.html
Check the Lots of text (performance test) example.

**Comment by asturur** [comment]
note:
https://github.com/asturur/fabric.js/blob/itext-cursorposition/src/mixins/itext_click_behavior.mixin.js#L181

**Comment by kangax** [comment]
Yep, definitely need to fix
