### ISSUE TITLE
SetOverlayImage issue in 1.5.0

### ISSUE THREAD

**Issue by fahadnabbasi** [kangax/fabric.js#2212]
If you look at this function
transform: function(ctx, fromLeft) {
            if (this.group && this.canvas.preserveObjectStacking && this.group === this.canvas._activeGroup) {
                this.group.transform(ctx);
            }
            var center = fromLeft ? this._getLeftTopCoords() : this.getCenterPoint();
            ctx.translate(center.x, center.y);
            ctx.rotate(degreesToRadians(this.angle));
            ctx.scale(
                this.scaleX * (this.flipX ? -1 : 1),
                this.scaleY * (this.flipY ? -1 : 1)
            );
        },

It should be like this

transform: function(ctx, fromLeft) {
            if (this.group && this.preserveObjectStacking && this.group === this.canvas._activeGroup) {
                this.group.transform(ctx);
            }
            var center = fromLeft ? this._getLeftTopCoords() : this.getCenterPoint();
            ctx.translate(center.x, center.y);
            ctx.rotate(degreesToRadians(this.angle));
            ctx.scale(
                this.scaleX * (this.flipX ? -1 : 1),
                this.scaleY * (this.flipY ? -1 : 1)
            );
        },

error in this line 

 if (this.group && this.canvas.preserveObjectStacking && this.group === this.canvas._activeGroup)

this.canvas.preserveObjectStacking  should be this.preserveObjectStacking

**Comment by asturur** [comment]
can you explain why this is an error?

**Comment by fahadnabbasi** [comment]
Actually preserveObjectStacking is the main property of Fabric class and there is no canvas.preserveObjectStacking property. When you add an overlay image with transformation, it throws error

**Comment by asturur** [comment]
There is no fabric.Object.preserveObjectStacking nor fabric.Image.preserveObjectStacking.
There is only fabric.staticCanvas.preserveObjectStacking.

If you are using latest code from github ( not prebuilt 1.5.0 ) and you are getting some error about preserveObjectStacking, please open a fiddle with a minimal test case that show the but / error.
Otherwise we cannot help.
