### ISSUE TITLE
Grouping Objects together, the fill becomes black

### ISSUE THREAD

**Issue by Terry-Fedirko** [kangax/fabric.js#2213]
Just uploaded 1.5.0 from 1.4.14 and found an issue when grouping objects together.    If you have 2 objects.  Say a circle that is red filled and a triangle that is blue filled.  When I tried to grouping these 2 objects together, the fill in both objects turn black.   It does not retain the original color (red and blue or any other color other than black).  Example below:

![figure 1 - 2 objects blue cirle and greentriangle](https://cloud.githubusercontent.com/assets/10421654/7712834/bd148334-fe41-11e4-99a0-0e188948ab9e.png)

Figure #1 - Both objects are created

![figure 2 - 2 objects blue cirle and greentriangle selected](https://cloud.githubusercontent.com/assets/10421654/7712835/bd15f980-fe41-11e4-8cda-90d6f2311f3d.png)

Figure #2 - Both objects are selected

![figure 3 - 2 objects blue cirle and greentriangle grouping command](https://cloud.githubusercontent.com/assets/10421654/7712837/bd1a7334-fe41-11e4-979d-1c8b340f38c4.png)

Figure #3 - Grouping them (programmed group into the context menu)

![figure 4 - 2 objects blue cirle and greentriangle now black after grouping](https://cloud.githubusercontent.com/assets/10421654/7712836/bd175ad2-fe41-11e4-9db9-65940d129c06.png)

Figure #4 - After grouping occurs, both objects turn black.

Note: this problem does NOT occur in 1.4.13.

**Comment by asturur** [comment]
If you submit a bug, please try to reduce code to the minimum to show the bug.
open a fiddle or something similar to explain it.

**Comment by asturur** [comment]
I suppose you are  using some saving, loading from JSON.
if you can reproduce the bug without custom code in some jsfiddle we will reopen the issue.

**Comment by spearson2010** [comment]
I'm not sure if this is the scenario the original poster had, but it seems similar.   I'm loading JSON data, and when the data passes through fabric.util.enlivenObjects, the objects within the group inherit the fill set on the group.

Here is a fiddle: http://jsfiddle.net/SxBfp/64/
Change the group fill, and it will override the fill specificed on each unit.  A color or blank (no fill) value will be inherited.  Completely remove the fill attribute from the group, and the objects in the group maintain their original fill.  

I'm not sure if this is by design or a bug.

**Comment by sapics** [comment]
@spearson2010 Thank you for giving information!
We have changed group initialization function recently, thus, the behavior would change in 1.5.1.

This is the current kangax/master builded version http://jsfiddle.net/sapics/SxBfp/65/.
Is this a what you expected one?

**Comment by spearson2010** [comment]
The fill of each item in the group is maintained, so that works for me.  Question though, if I remove the fill attribute on each item, the fill becomes black.  Is this a default, or should it then inherit the red fill from the group?

**Comment by rgwoodiii** [comment]
I'm having a similar issue, but right now I'm confused on what exactly fabric.util.enlivenObjects is. Does somebody mind explaining it to me?

**Comment by asturur** [comment]
is the function that switch from object form to class instances.
Maybe is a rought exaplanation.

from {type: 'rect', width : 50.... } to fabric.Rect

**Comment by Daomaster** [comment]
Hey Guys

I have the same issue when I try to group the objects in the active group, it fill everything in black.

Any Idea why?

![image](https://cloud.githubusercontent.com/assets/4971573/12932723/0b67ebb6-cf39-11e5-80d2-e7d4af544484.png)

![image](https://cloud.githubusercontent.com/assets/4971573/12932732/1d23f368-cf39-11e5-9688-a15a67f5634c.png)




http://jsfiddle.net/unu2xLj9/

**Comment by creaz35** [comment]
I have the exact same problem. 
Does not seem to be fixed?
Thanks

**Comment by asturur** [comment]
hi @creaz35 this is an issue from 2016.
On what version of fabric are you?
