### ISSUE TITLE
`toDataURL` not working when added SVG image on canvas 

### ISSUE THREAD

**Issue by ingnam** [kangax/fabric.js#2216]
When I add svg image served over AWS S3 on canvas, it gets loaded on canvas but when I call `toDataURL` on canvas, it gets blank and I get following error on console:
`Uncaught SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.`
I did CORS configuration on AWS S3 bucket. At this point it works fine on firefox but not in other browsers. 
I'm using `fabric.Image.fromURL` to add image on canvas and when I added `crossOrigin:"anonymous"` in that function I get error Image from origin blocked. 
`No 'Access-Control-Allow-Origin' header is present on the requested resource.`
I also used `fabric.loadSVGFromURL` with `crossOrigin:"anonymous"` to add image on canvs and got error 
`Mixed Content: The page at 'https://' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint.` 
In both cases, image didn't get loaded in canvas.

**Comment by asturur** [comment]
@ingnam can you provide a fiddle with this code still failing? What version of fabricJS are you using?
