### ISSUE TITLE
LoadSVGFromString gives empty array.

### ISSUE THREAD

**Issue by TimmNL** [kangax/fabric.js#2220]
I've tried to load some SVG strings, that are made with the toSVG function of fabric.js, with the following code:
fabric.loadSVGFromString(svg, function (objects, options) {
        obj = fabric.util.groupSVGElements(objects, options);
        canvas.add(obj);
        obj.setCoords();
    });

the objects variable is an empty array.
Did the way to load an SVGString change in any way?

**Comment by asturur** [comment]
Can you post a fiddle with the bug if possible?

**Comment by TimmNL** [comment]
It took me a while to get it right, but here it is:
http://jsfiddle.net/nb5mwhx0/

I hope this is the information you need. The Svg that i put in the fiddle is one that I created using the toSVG() code of fabric.

**Comment by TimmNL** [comment]
Is this enough confirmation?

**Comment by asturur** [comment]
sorry @TimmNL did not have time to get trought it.
i have some bugs to squash first.
i ll get a look in couple of hours to see if is not a bug.

**Comment by sapics** [comment]
@TimmNL I guess that you need to add svg tag.
Is this (http://jsfiddle.net/sapics/nb5mwhx0/11/) what you want?

**Comment by asturur** [comment]
yes, svg tag is missing.
@sapics thank you.

**Comment by TimmNL** [comment]
In my case I also had a previous 1.5.0 version! I didn't know that you were working in the 1.5.0 version and made big changes like that. Might be useful to have those changes in the changeling as well.
