### ISSUE TITLE
Cannot drag/move a small image on my canvas after canvas.add

### ISSUE THREAD

**Issue by MartinB83** [kangax/fabric.js#2221]
I'm a huge fan of fabric.js - thanks a lot for this. From time to time I encounter small performance problems such as this one:

I am uploading images via REST and Amazon S3. I fetch the URL and put the uploaded image on my canvas with the following logic:

`fabric.Image.fromURL(url, function(img) {
    canvas.add(img);
});`

This works for all kind of images perfectly. I can handle the image on my canvas, can resize it, center it, whatever interactions I prefer.
However, uploading a SMALL image (e.g. 78x78px) will not make the image draggable on the canvas. I just cannot move it around, it is stuck. No interaction possible.
I implemented moving images on my canvas with arrow keys but that cannot be a longterm solution.

Do you know where this comes from and how can I solve it? It feels like a bug to me, hence I report this here.
TY

**Comment by asturur** [comment]
PLease provide a fiddle with such loading problem and we will investigate.

**Comment by MartinB83** [comment]
See this: http://jsfiddle.net/6ydPq/75/

I found out that the problem only occurs in combination with the centerH() method.

**Comment by asturur** [comment]
Even the big image has the same problem.

Try to dragg the puppy from its left ear.
You can't.

After centerH and centerV you have to call setCoords for the object.
