### ISSUE TITLE
i-text: when pressing delete key at the end of a text i behaves like backspace key

### ISSUE THREAD

**Issue by sarath-prohaktiv** [kangax/fabric.js#2222]
i-text: when pressing delete key at the end of a text it behaves like backspace key.
This behavior can reproduce from http://fabricjs.com/kitchensink/

Thanks

**Comment by asturur** [comment]
i cannot reproduce.
What browser are using? And on what os, windows, linux or Mac?

**Comment by sarath-prohaktiv** [comment]
windows8 and chrome

**Comment by sarath-prohaktiv** [comment]
This can also reproduce in firefox

**Comment by sarath-prohaktiv** [comment]
"foo bar
baz
quux"

Move cursor after "x" then click delete button. you can see "x" is removing

**Comment by asturur** [comment]
Ok on last line is confirmed.
On all the others line is ok.
minor bug, to fix.
