### ISSUE TITLE
Using convolution filter and an adjustable filter at the same time extremely slow

### ISSUE THREAD

**Issue by packofbadgers** [kangax/fabric.js#2224]
I have several custom filters, some of which are read from ACV files. These work flawlessly.

I'm also using the brightness filter and I've set the slider to update the brightness on input instead of on change (simultaneously updating while it's moving). The brightness filter works well enough (a bit slow but that's to be expected).

The issue arises when I attempt to adjust the brightness filter while the convolution filter (sharpen or blur) is applied, it's significantly slower. When adjusting brightness while one of the custom filters is applied their no noticeable slow down.

Is there a work around somewhere in fabric for this? I'd prefer not to hack together some unholy combination of fabric and glfx.js just for sharpen and blur.

**Comment by asturur** [comment]
not too much slow and significant slower are too relative to understand.

Please can you post some fiddle showing how big images are you using, custom filters code ( if possible )

did you try some analisys with chrome dev tools to see where most of the time is spent?

**Comment by packofbadgers** [comment]
I'm going to close the issue as it's way too vague. I'm not sure the 2d canvas context was ever intended for realtime filter application.

**Comment by kangax** [comment]
I'd love to see these filters in action to get an idea of how slow they really are. There might be some room for optimization although it wouldn't be our first priority, as I hope you understand. A jsfiddle would be perfect.
