### ISSUE TITLE
Try fill and fill-opacity attribute on SVG element

### ISSUE THREAD

**Issue by hellomaya** [kangax/fabric.js#2229]
I used imagemagick to convert a SVG to PDF, and I found it didn't support fill and opacity in style to create transparent fill, but instead fill and fill-opacity is supported well, e.g.

```
<!-- This will be transparent fill, and working well in imagemagick -->
<rect fill="green" fill-opacity="0"...
```

```
<!-- transparent isn't supported in imagemagick, and it will be white instead -->
<rect style="fill:transparent;opacity:1.0...
```

**Comment by asturur** [comment]
as an additional note, adobe illistrator does not support rgba(r,g,b,a) in colors, and will give solid colors.

**Comment by kangax** [comment]
We should create a page in the wiki with support of different environments

**Comment by kangax** [comment]
https://github.com/kangax/fabric.js/wiki/SVG-issues-in-various-environments Please add whatever else in there
