### ISSUE TITLE
Cannot add text on top of overlay image with bringToFront

### ISSUE THREAD

**Issue by MartinB83** [kangax/fabric.js#2230]
See: http://jsfiddle.net/6ydPq/80/

Additional hints:
Setting an overlay image and calling indexOf shows "-1"
After adding text and calling bringToFront sets indexOf the text to "0" and should technically be displayed on top of the stack.

**Comment by asturur** [comment]
no, overlayImage is rendered after the stack.

it s always over any other object, no render occurs after it other than controls if "controlAboveOverlay" is set to true.

use a normal image without events if you want to  emulate an overlay image in the stack.

**Comment by MartinB83** [comment]
In my project I want to be able to drag/control an image behind another image (which is transparent). I tried to solve it with an overlay image but the limitations are that adding text won't work anymore. How would you solve it?

**Comment by asturur** [comment]
try to put an image as big as you need with evented equal to false. it should allow you to pass trought the clicks to the underlying objects and it should not move around. i may be wrong, i do not know all the event related properties very good. ( evented, selectable, movement related... etcetera.)

**Comment by alexburgos** [comment]
I had a similar issue and figured it out. But I'm encountering a second issue. If I add a big image with no events or selectable as an "overlay" and want to resize or move the one behind it, it brings that one to the front. So I'm not sure if `evented: false` isn't working for me or I'm approaching this wrong.

**Comment by asturur** [comment]
if we had object as overlay, and so group would be allowed, would it be fine?

**Comment by ahmadlatif1084** [comment]
I want to add text over an overlay-image on top,i used as an overlay image because i want to drag/drop/resize behind a transparent image and can add more objects/text over an canvas.

**Comment by durga598** [comment]
overlay-image will stay on top always.

**Comment by ahmadlatif1084** [comment]
how can i add text over a canvas/overlay image with an image behind it.Because my requirement is that i need to resize/crop and other functionalities on back image.

**Comment by ahmadlatif1084** [comment]
Is there any other solution to achieve this.Please guide me on this.

**Comment by asturur** [comment]
overlay is on top.  you can still put images one over the other and text on top without using the overlay

**Comment by ahmadlatif1084** [comment]
how can you please give me a fiddle?  Thanks. or some link helpful for
that.

**Comment by asturur** [comment]
add 2 images and add a text, the text will fit on top of image.

**Comment by ahmadlatif1084** [comment]
but one image doesn't go beside an transparent image. i want to add image
behind an transparent image. so i can able to drag or resize.it just give
me the functionality of overlay image, but due to text functionality on top
it doesnot meet my requirement and overlay image always stay on top. Now
Please further guide me. Thanks.

**Comment by asturur** [comment]
you can set the top image as evented=fasle, so it does not interact with the mouse.

**Comment by ahmadlatif1084** [comment]
Can you please set this and give me a demo.Please.
https://jsfiddle.net/ahmadlatif1084/4pu97hzm/2/

**Comment by thiscafer** [comment]
> Can you please set this and give me a demo.Please.
> https://jsfiddle.net/ahmadlatif1084/4pu97hzm/2/

Did you find any solution?
