### ISSUE TITLE
border is appending to image when I'm trying to save edited image on canvas.

### ISSUE THREAD

**Issue by krishna565** [kangax/fabric.js#2231]
Hello All,

   I am using fabric.js to develop an image editor through which user can scribble, text, sign and perform scaling and rotate operations. To save the edited image on canvas, I'm using the following function. But when saving that image, a black border is appending to image everytime. saveAjaxCall is a function which sends an AJAX call to save the image on server. May I know where I'm doing mistake. 

        canvas.discardActiveGroup().renderAll();
	var objs = canvas.getObjects().map(function(o) {
		return o.set('active', false);
	});
	var group = new fabric.Group(objs, {
		originX: 'center', 
		originY: 'center'
	});
	saveAjaxCall(group.toDataURL());
	group._restoreObjectsState();

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group — https://groups.google.com/forum/#!forum/fabricjs — where someone will usually assist you.

The issue tracker is only for bugs and feature requests.

Thanks for your understanding!
