### ISSUE TITLE
Fabric JS IText object cursor position is off on copy/paste.

### ISSUE THREAD

**Issue by chetanbura** [kangax/fabric.js#2233]
I-Text object  with having lots of text and after we just copy 5 line and then  paste it any where in the same I-Text then see from last line the cursor position is off, and on click of last line or 2nd last line and onward the cursor position is off with some characters.
you can see this in fabric official site 

http://fabricjs.com/test/misc/itext.html

with Lots of text (performance test) example

**Comment by chetanbura** [comment]
Any update / thoughts on this? Thanks.

**Comment by chetanbura** [comment]
Any update / thoughts on this? Thanks.

**Comment by asturur** [comment]
@chetanbura  would you try on this updated version if it is fixed?
because i cannot reproduce it on normal itext demo as you asked.
http://www.deltalink.it/andreab/fabric/kitchensink.html


if this works for you please close the issue

**Comment by chetanbura** [comment]
Thank you ,this is working fine on new updated version of fabric js.
