### ISSUE TITLE
Running in Chrome App broken due to CSP (Content Security Policy)

### ISSUE THREAD

**Issue by francislavoie** [kangax/fabric.js#2239]
When loading the lib in a Chrome App, I get the following error:

    Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' chrome-extension-resource:".

This is because of `new Function()` eval calls which are not allowed in Chrome Apps.

After changing the calls in the block here: https://github.com/kangax/fabric.js/blob/master/dist/fabric.js#L767-L777, it no longer gave me that error. 

These are the changes I've made:

    if (!proto[getterName]) {
      proto[getterName] = (function(property) {
        return function() {return this.get(property)};
        //return new Function('return this.get("' + property + '")');
      })(propName);
    }
    if (!proto[setterName]) {
      proto[setterName] = (function(property) {
        return function(value) {return this.set(property, value)};
        //return new Function('value', 'return this.set("' + property + '", value)');
      })(propName);
    }

I don't know if this is still correct. Does this lib really need the evals? Should there be a release without evals? I dunno.

**Comment by kangax** [comment]
Duplicate of #1621
