### ISSUE TITLE
ClipTo use current object as data for clip

### ISSUE THREAD

**Issue by NistorCristian** [kangax/fabric.js#2240]
I want to make a `clipTo` for an image based on image width and height of the current object. I want the clipTo function to have the height and width from the active object. My problem is that I don't know how to make the function to be visible after I load the Json.

    var activeObject = canvas.getActiveObject();
    activeObject.set({
        clipTo: function (ctx) {
            ctx.rect(0, 0, activeObject.get('width')/4,activeObject.get('height')/4);
        }        
    });

The clipTo works but if I want to load the json it gives me the error that `activeObject` it is not defined. (and obviously it isn't). But how can I acces the height and width of the `activeObject`?

I made a jsFiddle to understand better what I want to do:

[JsFiddle][1]

Please click Make Json and it will do the clip and the json will be like:

    "clipTo":"function (ctx) {\n                ctx.rect(0, 0, activeObject.get('width')/4,activeObject.get('height')/4);\n            }"

But if I click Load Json I get:

    Uncaught ReferenceError: activeObject is not defined

    (function(ctx
    /**/) {
    
                    ctx.rect(0, 0, activeObject.get('width')/4,activeObject.get('height')/4);
                
    })

Any help whould be great. Thank you.

  [1]: http://jsfiddle.net/9c2g9ev4/

**Comment by sapics** [comment]
How about using this as http://jsfiddle.net/sapics/9c2g9ev4/1/ ?

**Comment by NistorCristian** [comment]
Yes ... this works. Thank you.
