### ISSUE TITLE
Trim issue in parseStyleString while parseSVGdocument

### ISSUE THREAD

**Issue by maertz** [kangax/fabric.js#2241]
Safari 5 fails on "parseSVGdocument" while it tries to "parseStyleString".

You except always to have at least two elements while splitting the "chunk" but for some reason in Safari 5 it returns just a single empty string, not sure why was to lazy to fully trace it down.

Following simple check worked for me on Line: [3089] (https://github.com/kangax/fabric.js/blob/master/dist/fabric.js#L3089)
```
  function parseStyleString(style, oStyle) {
    var attr, value;
    style.replace(/;$/, '').split(';').forEach(function (chunk) {
      var pair = chunk.split(':');

      if ( pair.length > 1 ) {

        attr = normalizeAttr(pair[0].trim().toLowerCase());
        value = normalizeValue(attr, pair[1].trim());

        oStyle[attr] = value;
      }
    });
```

**Comment by asturur** [comment]
sorry can you post the svg you where parsing? maybe there is some malfoned style.

**Comment by maertz** [comment]
looks like the ending whitespace on the SVG element makes the trouble, also reproducible in modern browser e.G first example.

http://codepen.io/amcharts/full/48deb24b8ea12573c230eec57194bb53/

**Comment by asturur** [comment]
i confirm the space is breaking import.
Also style on svg element does not have any effect on the resulting pathGroup (at least for width and height )

**Comment by maertz** [comment]
thanks for hanging in
