### ISSUE TITLE
Changing Font Family "shifts" text object in 1.4.0

### ISSUE THREAD

**Issue by paulcanning** [kangax/fabric.js#2242]
I am using a dropdown menu to change the font family for a text object on my canvas, that is set to left text alignment and has an origin of top left as well.

When the font is changed, the text object "shifts" position as if the text had a center origin.

I checked in the Kitchen Sink demo and it doesn't happen there.

Here is my code:

    var activeObject = canvas.getActiveObject();
    
    activeObject.fontFamily = font // set via dropdown + jQuery

    activeObject.setCoords();

    canvas.renderAll();

    canvas.calcOffset();

JSFiddle link http://jsfiddle.net/6jxbrxy9/

In the JSFiddle, select the text, and click the button. you will see the font change and the blue box shrink inwards slightly. then click off the text, somewhere on the canvas. The text will shift back into place.

**Comment by kangax** [comment]
Does this happen with 1.5?

**Comment by paulcanning** [comment]
It doesn't.

However I have found another bug in 1.5 regarding shadows which means I may not be able to upgrade.

**Comment by asturur** [comment]
would be better to open an issue for a possible bug of current release than an old bug of old release.

**Comment by asturur** [comment]
1.4.0 is not supported with bug fixing and shadow bug is discussed in #2244 ( @paulcanning please create a fiddle if  you want the bug to be discovered and evenutally fixed faster )
