### ISSUE TITLE
Text "selection" box incorrect when using Google Fonts

### ISSUE THREAD

**Issue by paulcanning** [kangax/fabric.js#2245]
I have added some text to my canvas, using loadFromJson, and the selection box, when I click the text, is incorrect.

http://www.awesomescreenshot.com/image/276275/db355a5c2bfe3dd6ff2ddd284f453c65

It looks to be using the size as if the text was still using Arial as its font family. The font I have set it to is Archivo Black (a Google Font).

If i change the font size, or the family again, the box resizes to the correct size.

**Comment by asturur** [comment]
look this is either duplicare of #1108 or anyway fixed by some commit of some days ago, where style change was not considered for cleaning cache.
