### ISSUE TITLE
version 1.5.0 has bug.

### ISSUE THREAD

**Issue by leeyo** [kangax/fabric.js#2246]
http://jsfiddle.net/ULsr4/9/   .please visit my code.

i set image transformMatrix to  [0.5095541477203369, 0, 0, 0.5102040618658066, 0, 0] ,it is expected to be   show at the point of : 0,0 .but as you see,the outline border is not transform to fit the image.so it is not at the right position.

and this is version 1.4.0 , http://jsfiddle.net/ULsr4/10/  ,this is good.

**Comment by asturur** [comment]
in 1.4.0 the rendering is completely not correct, as you see also the controls are transformed from transformMatrix. This is not a desired behaviour.

This bug is reported in: #1520.

**Comment by leeyo** [comment]
@asturur     I see,version 1.4 put image at the top left corner of the controls, version 1.5 put image at the center of the controls.
but i have some problem about this, you see ,the matrix is [0.5095541477203369, 0, 0, 0.5102040618658066, 0, 0]. In fact,I expect it to put the image start at Coords : x:0,y:0,it's not,but the controls is~  so I think may be the problem is,the controls's width and height should be the same as the image.so I make my code like this:http://jsfiddle.net/ULsr4/17/
