### ISSUE TITLE
canvas to svg converting in fabricjs has problems

### ISSUE THREAD

**Issue by PrameshHarshana** [kangax/fabric.js#2247]
After design on canvas in fabricjs i convert it to SVG.but there is a problem with converting itext.itext is misplaced.how to solve this problem.any idea or example would be apriciated.thank you.
before convert
![adad](https://cloud.githubusercontent.com/assets/12692063/7907873/7579db44-085c-11e5-8458-501bf2e00180.jpg)
after convert
![xcd](https://cloud.githubusercontent.com/assets/12692063/7907879/789b56b8-085c-11e5-8750-e9ed68844973.jpg)

**Comment by asturur** [comment]
can you post s fiddle with the bug?
which version of fabricjs ard you using?

**Comment by PrameshHarshana** [comment]
I use  Fabric.js 1.4.13 version.It cannot post in fiddle.bcoz its little bit larger project.What i do is,i design some shapes on canvas and convert canvas to SVG.then save SVG code in DB.after i retrieve the SVG code it looks diferent.only itext change their positions little bit.

**Comment by asturur** [comment]
I think that you have a version with the bug of itext height in svg when not styled.
Just to try apply some style to your itext and check if it solves.
if it does, please upgrade to 1.5.0 and later to 1.5.1 as soon as it is out.

**Comment by PrameshHarshana** [comment]
I tried fontStyle: 'italic' and nothing happened.if i  upgrade to 1.4.13 to 1.5.0, is it change other things?

**Comment by asturur** [comment]
Sorry, do not change fontStyle per object, but per character in object.
change the style property of the object, not fontStyle itself.

Anyway give 1.5.0 a try, it is faster.

**Comment by PrameshHarshana** [comment]
thank you.new version is good.it works.
