### ISSUE TITLE
Rotate arount top left corner

### ISSUE THREAD

**Issue by Hamsterkacke** [kangax/fabric.js#2250]
I'm trying to achieve the following scenario:

I have a image or Text inside a canvas. I want to rotate the text not around its center point but arount the top left point (or right middle point). So that the text could be better aligned on a imaginary left line. (I use it for a product designer software)

Is there something i missed or is this a feature that is not implemented?

Best regards,
Philipp

**Comment by kangax** [comment]
Nothing like this built-in.

**Comment by asturur** [comment]
i may be wrong.
But i just found out that setting:

```object.centeredRotation = false;```
The rotation will be around its originX and originY.
So not independent from origin, but still better than nothing.
