### ISSUE TITLE
Images do no appear in IE10 and below

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [kangax/fabric.js#2251]
No idea what I'm doing wrong here, but apparently I've upset IE10 somehow. I've got a bit of FabricJS that looks simple enough. It works in everything except IE10 and below. Not sure why?

```
var canvas = new fabric.Canvas('imageCanvas', {
    backgroundColor: 'rgb(240,240,240)'
});

var imgElement = document.getElementById('imageSource');
var fabricImg = new fabric.Image(
    imgElement, {
        selectable: false,
        evented: false,
        hasControls: false,
        hasBorders: false
     }
);

canvas.add(fabricImg);
```

Screenshot showing IE10 (left) and IE11 (right):

![GitHub Logo](http://i.stack.imgur.com/PJ5lu.jpg)

**Demo:** https://jsfiddle.net/Lr3Lycuw/

If you open in the above link in IE10 and below there will not be an image.

I've tweaked every option I can think of and looked through the FabricJS documentation for `fabric.Image`, but I can't see where I might have done something to anger IE. Pulling my hair out now!
##

**Comment by JohnnyWalkerDesign** [comment]
The problem was the CSS marking the source image as display:none.

Using Image.fromURL worked instead.

**Comment by JohnnyWalkerDesign** [comment]
Can anyone confirm if this is a bug or not? Thanks.

**Comment by JohnnyWalkerDesign** [comment]
I'm working with FabricJS again at the moment. Is this still an issue?

**Comment by asturur** [comment]
I can only suggest to set the display to block and then again none if you detect ie10 and below.
(maybe detaching the image from the document).
We support ie9 and ie10 but i would not add an hack for this that looks like a browserBug.

**Comment by JohnnyWalkerDesign** [comment]
Ok, but I don't see how you can say you support IE9 and 10 if you don't handle their quirks. Thanks.

**Comment by asturur** [comment]
fabricjs works with some limitation on those  old browsers, from missing dasharray to limited support of some clip rules. the point is just that an offscreen image element will work normally. there is no hack i can do to make it work, while dev can clone the element, give it display different from none and have it working.

**Comment by JohnnyWalkerDesign** [comment]
Ok, thanks for explaining.
