### ISSUE TITLE
group scaling bug

### ISSUE THREAD

**Issue by sapics** [kangax/fabric.js#2253]
Please look at http://jsfiddle.net/sapics/tt5zjjot/32/
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/11169954/7926790/663af562-0912-11e5-8bc0-dec8ca095b91.gif)

90 degree rotated `red` rectangle scaling looks strange.

**Comment by asturur** [comment]
is same bug you posted on my pr. just extreme situation

**Comment by sapics** [comment]
I see. is it better to rewrite an general situation which is wrtten in your pr, or better to close?

**Comment by sapics** [comment]
I see. thanks. I would create another issue with more general situation as same as in your pr.

**Comment by asturur** [comment]
is an old bug already present in issues. we have to introduce skew, then we have to find a logic ( not that hard ) that from a combination of scale and rotate can extract scale, rotate and skew components. something old to take care of. no meed of new issue.

**Comment by sapics** [comment]
I see. Thanks!
