### ISSUE TITLE
i-text cursor position issue after copying multiple lines

### ISSUE THREAD

**Issue by sarath-prohaktiv** [kangax/fabric.js#2255]
![image](https://cloud.githubusercontent.com/assets/7422434/7932885/f6273f0c-0938-11e5-99f8-ebad5c5d1a0d.png)

#1) Goto http://fabricjs.com/kitchensink/
#2) Copy first text content to the second text
#3) Try to click on 3rd or 4th line.
#4) Cursor left position is not correct

Please refer screenshot for more details

**Comment by asturur** [comment]
carriage return breaking the character position.
