### ISSUE TITLE
Sprite image blurred after setting the width and height of canvas

### ISSUE THREAD

**Issue by Julyyq** [kangax/fabric.js#2259]
If I don't set canvas's size, sprite image is clear as original, but when I try to set:

    canvas.setWidth(widthValue);
    canvas.setHeight(heightValue);

or:

    canvas.setDimensions({
        width: widthValue,
        height: heightValue
    });

then the image is blurred. Is this a bug?

**Comment by asturur** [comment]
can you show us with a jsfiddle?

**Comment by Julyyq** [comment]
@asturur My application is little bit complicated, can't easy show u the entire code, but the blurred issue comes with a code snippet:

    initCanvas: function() {
      var screenWidth = window.screen.width;
      
      this.canvas.setDimensions({
        width: screenWidth*2,
        height: screenWidth*2
      });
      
      this.canvas.setWidth(screenWidth);
      this.canvas.setHeight(screenWidth);
    }

the screen shots:

![true](https://cloud.githubusercontent.com/assets/2620575/8123135/a52fde54-10f6-11e5-8e39-04b0a42c3247.png)

![screen shot 2015-06-12 at 11 25 21](https://cloud.githubusercontent.com/assets/2620575/8123142/c263cad0-10f6-11e5-84c0-ae60d0853f06.png)

and I found that `setWidth` and  `setHeight` disabled the `setDimensions` method.

**Comment by Julyyq** [comment]
It's not about this library's issue, even not a bug. It's about the difference between canvas size and dimension. Set the dimension double size to the css size, then use a double size sprite picture, then more clear than ever.

I use chrome mobile device emulator to do test stuff, it makes me confused for resolution. The screenshot 1 is from iPhone6 emulator, and the screenshot 2 is from iPhone6 plus emulator. Chrome's emulator is not always reliable, which is a import point that I forgot. With using my real mobile device, it's always blurred.

So, this issue should be closed. Thank you anyway!

**Comment by asturur** [comment]
Thank you for reporting back after solving.
