### ISSUE TITLE
Fabric.loadSVGFromString Fails on Empty Path

### ISSUE THREAD

**Issue by timkendall** [kangax/fabric.js#2264]
Fabric: `1.5.0`
Running Fabric in Node.js `0.12.4`

 When parsing an SVG with a `<path>` that has an empty or no `d` attribute Fabric fails to load the SVG and throws `'path' argument is required`. This behavior is not ideal for our use case as we are dynamically rendering complex SVGs that may have empty paths. Perhaps this could be an option in Fabric to ignore empty paths?

Failure example: `<path fill="#ccc"/>`

**Comment by kangax** [comment]
Hm, perhaps we can `console.warn` instead? /cc @asturur @Kienz

**Comment by asturur** [comment]
i think we can just parse it without warning and skip rendering.
i think is fine.
