### ISSUE TITLE
JSON.stringify(canvas) has Deserialization problem

### ISSUE THREAD

**Issue by PrameshHarshana** [kangax/fabric.js#2268]
JASON code 
{"objects":[{"type":"rect","originX":"left","originY":"top","left":60,"top":70,"width":25,"height":25,"fill":"DarkSalmon","stroke":"black","strokeWidth":0.3,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","rx":5,"ry":5}],"background":""}

**Comment by PrameshHarshana** [comment]
After convert canvas to jason, background attribute is empty.so when reload that json code nothing show.then i change code like this. background="rgba(0,0,0,0)".after change it shows all objects.so how can solve that problem?. to JSON.stringify(canvas) has Deserialization problem


JASON code 
{"objects":[{"type":"rect","originX":"left","originY":"top","left":60,"top":70,"width":25,"height":25,"fill":"DarkSalmon","stroke":"black","strokeWidth":0.3,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","rx":5,"ry":5}],"background":""}

**Comment by asturur** [comment]
Please, provide a jsFiddle with your problem so we can investigate further
