### ISSUE TITLE
Load SVG elements seperately to be later selected

### ISSUE THREAD

**Issue by kwokeith1989** [kangax/fabric.js#2271]
I have an application that can draw freely and use the selecting tools to transform and translate those drawn element. I would then serialize the elements to a SVG file. It works perfectly as expected and I would like to use this chance to thanks for the great work.

However, this application would also be required to deserialize the SVG and put the elements back to the canvas again; using loadSVGFromString and utils.groupSVGElements, the canvas would load a single element, the path group, onto the canvas which loses the ability to be selected path by path and therefore the ability to be transform and translate again.
```javascript
fabric.loadSVGFromString(data, function(objects, options){
    var obj = fabric.util.groupSVGElements(objects, options);
    this.canvas.add(obj).renderAll();
}.bind(this));
```
So I add the loaded element path by path onto the canvas, now every element can be selected individually;
```javascript
fabric.loadSVGFromString(data, function(objects, options){
    objects.forEach(function(object){
        object.selectable = true;
     }.bind(this));
     this.canvas.add.apply(this.canvas, objects);
 }.bind(this));
```
 However, when loaded, the path loses its transform and translate effect earlier the user apply to them (the attribute transform in the svg file).

How to load elements in svg file path by path while keeping their transform and translate effect as specified in the svg file?

**Comment by asturur** [comment]
when loading back the svg, every element get a transformMatrix attribute.
this attribute is not yet supported in the interactive mode.
there is an ongoing pr in the pr list, to support this feature. unfortunately fabricjs make a large use of the translate attribute that is the hardest to support from my experience.

as always, we suggest to use json to load back content and not svg.

**Comment by kwokeith1989** [comment]
@asturur, thanks for your promptly reply,
So, If I use json instead of svg file for saving and loading the elements,
 the loaded back content can be selected individually.

**Comment by asturur** [comment]
yes.

consider also, when svg ungrouped will be supported ( after 1.5.1 i m gonna do that ) transformation will be imported back differently.


when you rotate a square, in canvas and in loaded back json, you get a rotated square. angle will be  different from 0 as you rotated it.

when you load an svg with a rect that has transform attribute "rotate(30)" you get a rect that has a rotation transformMatrix but angle of 0.

if you take an svg with 3 rects and give them transform attribute:

rotate(30) translate(10,10) scale(1.3)

translate(10,10) scale(1.3) rotate(30)

scale(1.3) rotate(30) translate(10, 10)

you will get 3 different positioned rectangle.
that is why we just merge the transform in a unique matrix and use it as it is.

svg is still a import and export feature, but just for some kind of situation, like when you want to use some drawings, recycle some complex paths.
