### ISSUE TITLE
after use the function "loadFromJSON ",the items in one group will be wrong in position 

### ISSUE THREAD

**Issue by moxuanyuan** [kangax/fabric.js#2280]
after use the function "loadFromJSON ", items in one group width "left" and 'top' value will change

http://jsfiddle.net/moxuanyuan/7bcmwpza/12/

**Comment by sapics** [comment]
As http://jsfiddle.net/sapics/7bcmwpza/17/, how about using group.addWithUpdate?

**Comment by dpacmittal** [comment]
I'm hitting this same bug. I'm using groups toJSON() to export and fabric.Group.fromObject() to import the object. I manually checked the export and the 'top' and 'left' values are correct, but I checked the output of fabric.Group.fromObject() and it gives modified values of 'top' and 'left'.

**Comment by asturur** [comment]
http://jsfiddle.net/7bcmwpza/18/

There is a fix for fabric group load from json after 1.5.0
In the updated fiddle there is no problem restoring the group from json.
