### ISSUE TITLE
Object pattern from another object or from a fabric Image

### ISSUE THREAD

**Issue by NistorCristian** [kangax/fabric.js#2281]
Hi,
I want to make a rect and I want to apply a pattern:

```fabric.util.loadImage('myurl', function(img) {```
	 ```     rect.fill = new fabric.Pattern({```
	    ```source: img,```
	    ```repeat: 'repeat'```
	  ```});```
	  ```canvas.renderAll();```
	```});```

My problem is if I do:

`window.open(
	      'data:image/svg+xml;utf8,' +
	      encodeURIComponent(canvas.toSVG()));`

The SVG is ok in browser because it takes the url but if I save it the pattern is not shown.

Is there a way to make an object and make it as a new fabric.Image and then apply it as a pattern? I want to export the final product as a SVG and I want to see the pattern if I open it with Illustrator. Is there a way to do such a thing?

**Comment by asturur** [comment]
if you save SVG, and then load it in a firefox or chrome tab ( drag and dropping the file in the address bar ) does it show correctly?

if yes then is an illustrator problem. ( that we can always take care of )

**Comment by NistorCristian** [comment]
Yes it does show correctly but if I upload the SVG to my canvas (or Illustrator) it doesn't show correctly .

**Comment by NistorCristian** [comment]
This is the link to my SVG. With pattern applied. Ok in browser but not locally.

https://www.wetransfer.com/downloads/9ef55f65b8a4d8e274eb0a514e11bab820150611150024/eecc11bfd1398659c3a2787d2dc0b33620150611150024/73f71c

**Comment by asturur** [comment]
![image](https://cloud.githubusercontent.com/assets/1194048/8110417/706d5a1a-105c-11e5-97f9-cdacff900201.png)
this is open locally with crome.
Is this fine?

**Comment by NistorCristian** [comment]
Ok... locally was a bad term for me, sorry. Let's say I want to edit this svg. And I want to edit it in my canvas that I made it. If I upload the svg the pattern doesn't show. (I didn't tried with json, only with file upload). Same thing happens in Illustrator. My question is can I do the pattern from an existing object from canvas (like a new fabric.Image etc...) or a Static Canvas? Thanks for support.

**Comment by asturur** [comment]
We cannot yet parse patterns from SVG.
Loading back from JSON should work.

And yes you can create a pattern using some other fabric objects.
Please check the file brush-pattern class file to have a hint how to create a function that acts like a pattern.

You will do something fill = function () {  .... code ....  }

I'm sorry i'm not pattern expert.

**Comment by NistorCristian** [comment]
Thank you ... I will try to make my own function based on PatternBrush class.

**Comment by NistorCristian** [comment]
Hi @asturur I'm back with my froblem and a jsFiddle. http://jsfiddle.net/jo8j5ogg/.
Inside the canvas I have a pug (image), a circle, a text and a pattern (the flower).

If you press Zoom in the quality of the pattern will be bad ever if it is a svg. My problem is that if I click Make json and try to load it back in console I have an error that patternSourceCanvas is not defined ... and obvoisly it isn't bacause it is outside the function of variable pattern. How can I make the json to work ? 
I don't want to use `fabric.util.loadImage('http://nistorcristian.com/comixer/wp-content/uploads/2015/05/boobary1.svg', function(img)` because I can't change the size of the svg inside the pattern.

**Comment by asturur** [comment]
Hey this is another problem.
First of all you should provide a clean jsfiddle like i modified:

http://jsfiddle.net/jo8j5ogg/2/ (please check easier canvas scaling i wrote there ).

Also you should check if this problem is already reported by someone:
https://github.com/kangax/fabric.js/issues/935
same problem not efficently reported:
https://github.com/kangax/fabric.js/issues/1994
