### ISSUE TITLE
SVG id attribut is missing

### ISSUE THREAD

**Issue by dgodard** [kangax/fabric.js#2285]
I want to manage my object imported from SVG by their ID.
But, the 'id' attribute is missing in FabricsJS.

The SVG 'id' attribute is removed in parseUseDirectives function  by the line : el2.removeAttribute('id');

**Comment by asturur** [comment]
that line should remove id attribute from cloned object that was referenced by use tag. it is correct like that.

the id attribute is not parsed. please check the parsedAttribute array and add "id" there.

check any object fromElement method to see the corret spelling of this array name.

**Comment by dgodard** [comment]
The parsed attributes used by fromElement are defined in fabric.SHARED_ATTRIBUTES (in header.js).

This is my modified version :
```javascript
/* _FROM_SVG_START_ */
/**
 * Attributes parsed from all SVG elements
 * @type array
 */
fabric.SHARED_ATTRIBUTES = [
  "id",
  "display",
  "transform",
  "fill", "fill-opacity", "fill-rule",
  "opacity",
  "stroke", "stroke-dasharray", "stroke-linecap",
  "stroke-linejoin", "stroke-miterlimit",
  "stroke-opacity", "stroke-width"
];
/* _FROM_SVG_END_ */
```

Do you think I have to modify object.class.js to manage it as default property of an object ?

**Comment by asturur** [comment]
i do not know why is not parsed by default.
We should discuss if it is worth parsing, or if you have to extend the class and override it.

maybe a
```fabric.SHARED_ATTRIBUTE.push('id');```
in your application is enough.

**Comment by kangax** [comment]
I wouldn'd mind adding support for parsing id! Marking as feature.

**Comment by asturur** [comment]
Ok i do a quick PR.
