### ISSUE TITLE
Error in regex in parseAttributes

### ISSUE THREAD

**Issue by dgodard** [kangax/fabric.js#2287]
There is a problem with regex in Parser.js in parseAttributes line 763 :
```javascript
// if there's a parent container (`g` or `a` or `symbol` node), parse its attributes recursively upwards
      if (element.parentNode && /^symbol|[g|a]$/i.test(element.parentNode.nodeName)) {
```

`^symbol|[g|a]$` match also for "svg" element node name because it tests if nodeName starts with "symbol"  or contains "g" or "a" char at the end

It needs parenthenses : It must be `^(symbol|[g|a])$` for an exact match "symbol" "a" or "g".

**Comment by kangax** [comment]
Good catch, thanks! This looks like a regression, since we added symbol recently and I missed the simplest mistake of grouping and anchors :P

If you could send a PR, that would be great. Or one of us will get to it eventually. Also, a minimal failing test case would be perfect!

**Comment by asturur** [comment]
@dgodard  what svg was failing with this error?
