### ISSUE TITLE
Only runs when browser tab is active

### ISSUE THREAD

**Issue by kraghack** [kangax/fabric.js#2288]
Fabric uses `requestAnimationFrame` at the core of its animation system which does not run unless the browser tab is active.

Even with time-delta logic on tab focus to catch animation up with elapsed time, it gets further complicated if the user, for example, daisy-chains animations together using their `onComplete` callbacks.

How are people generally addressing the issue of tab blur?

I don't have much experience in this space, but one solution I can think of is to modify the core `requestAnimFrame` function
(https://github.com/kangax/fabric.js/blob/fe0f4b4de8092ab8d29f8fc1e2c5a90ecbf0bdbf/dist/fabric.js#L2389-L2396) so that it's aware of the window's blurred vs focused state. Then it could dispatch `requestAnimationFrame` when the window is focused and `setTimeout(cb, 1000 / fps)` when the window is blurred.

Of course, when a tab is blurred, `setTimeout` is limited to run once per second in most browsers, but I believe this `setTimeout` fallback behavior would be a better default than to not run entirely.

**Comment by kangax** [comment]
Interesting, this is the first time I hear about rAF doing less work being a problem :) Usually it's a good thing that inactive tab is not running anything. I can mark this as a possible feature and we'll see if anyone else is interested in this.

**Comment by amkazan** [comment]
yes we need this as possible_feature

**Comment by asturur** [comment]
dupliclate of #2518
