### ISSUE TITLE
Cusor stays at position 0 when the iText is textAlign='right

### ISSUE THREAD

**Issue by kob-e** [kangax/fabric.js#2289]

**Comment by kob-e** [comment]
when using iText with textAlign='left' the cursor is moving when typing text.
in textAlign='right' the cursor stays in position 0.

**Comment by asturur** [comment]
did you try last code base?
we fixed this problem.

**Comment by kob-e** [comment]
Yes i am using the last version (updated 27 days ago)
this is my code for adding text:

var Text = new fabric.IText(DefaultText, {
                    fontFamily:  'Arial',
                    textAlign : 'right',
                    originX : 'right',
                    left: points.x,
                    top: points.y,
                    lockRotation: true,
                    hasControls: true,
                    lockMovementX: false,
                    fontSize: DefaultFontSize,
                    fill: '#000000',
                    fontStyle: 'normal',
                    fontWeight: 'normal',
                    textDecoration: 'none'
                });

**Comment by asturur** [comment]
please try the one downloadable from github.com with latest fixes.

**Comment by kob-e** [comment]
In the demo of  "kitchensink": http://fabricjs.com/kitchensink/
it also happen. set the Origin X to right and textAlign to right and the cursor stays at the 0 position.

**Comment by asturur** [comment]
Cannot reproduce.

**Comment by kob-e** [comment]
the fix is here:
https://github.com/kangax/fabric.js/issues/2374
