### ISSUE TITLE
FreeDrawingBrush cuts start of line in half

### ISSUE THREAD

**Issue by TimmNL** [kangax/fabric.js#2290]
When you start to draw in free drawing mode it sometimes cuts the start of the line in half.
So instead of it starting as a circle it starts as a square.
I have no idea how to recreate this, so it might be hard to get the solution for this.
I did notice it happens more often when you draw form the right to the left.
##

**Comment by asturur** [comment]
I can't reproduce it.
Can you have a secure way of make it happens.

**Comment by TimmNL** [comment]
I can't make a fiddle if that's what you mean.
I do have a screenshot of the problem:
![schermafbeelding 2015-06-18 om 11 30 01](https://cloud.githubusercontent.com/assets/12426276/8228468/3378d97e-15af-11e5-9633-18fd87646885.png)

As you can see the red line on the right starts of the wrong way.

**Comment by asturur** [comment]
may it be a very "hard turn" of the brush? i m gonna try it

**Comment by asturur** [comment]
![image](https://cloud.githubusercontent.com/assets/1194048/8228514/ac0330f6-15af-11e5-8c4c-63a7a09af7b1.png)

Ok you have to behave bad with the mouse to obtain this effect.
I think there is some aliasing on the path... or some error in drawing commands.

**Comment by asturur** [comment]
```
0: Array[3]
  0: "M"
  1: 653.5
  2: 194
  length: 3
1: Array[5]
  0: "Q"
  1: 653.5
  2: 194
  3: 654
  4: 194
  length: 5
2: Array[5]
  0: "Q"
  1: 654.5
  2: 194
  3: 441.25
  4: 196.5
  length: 5
3: Array[5]
  0: "Q"
  1: 228
  2: 199
  3: 161.5
  4: 194
  length: 5
```

This starting point plus 2 quadratic curve from the same point finishing in the starting point itself are doing the problem. It is something to be looked at.

**Comment by asturur** [comment]
i removed "bug" label.
the code is correct, the point are calculated correctly.
The problem lies ( in my opinion ) in how a big strokeWidth bends on small curves.

We could take in consideration the strokeWidth in moment of drawing ad make some decision on point interpolation based on that. But as i see it is not a bug but more an improvement.
any comment is welcome

**Comment by asturur** [comment]
i think we fixed this!
