### ISSUE TITLE
lineWidth/strokeWidth cause resize issues

### ISSUE THREAD

**Issue by PervertPrayer** [kangax/fabric.js#2293]
## Environment
**Fabric version:** 1.5.0
**Browser:** chrome 43.0.2357.124 m (latest stable)
**OS:** windows 7/8

## Description
All objects, that have lineWidth/strokeWidth set as > 1 would resize (using  selection box edges) as they have incorrect scale, jumping from some incorrect scale to mouse position

## Steps to reproduce
1) Draw some path using drawMode with lineWidth > 1 (for example current version of this demo already have default lineWidth setted as 30 http://fabricjs.com/freedrawing/) or create another shape/line with strokeWidth > 1
2) Select this object and try to scale it using selection box

## Excepted behaviour
Object with lineWidth/strokeWidth > 1 scales as it scales with lineWidth/strokeWidth setted to 1

## Actual behaviour
It scales with some weird "jumping scale" glitch.

## Showcase
This demo is reproducing bug http://fabricjs.com/freedrawing/. If you need other showcase i would post it.

**Comment by asturur** [comment]
Yes i can confirm this, but i thought we fixed it.
I will check deeper.

**Comment by asturur** [comment]
i m sorry i was wrong, this has been fixed somewhere between 1.5.0 and current code.

try here
http://www.deltalink.it/andreab/fabric/kitchensink.html
