### ISSUE TITLE
The way to collect paths into the new path-group.

### ISSUE THREAD

**Issue by off-border** [kangax/fabric.js#2295]
Hi!

I looking for way to add a path object, created with the free drawing mode on Fabric JS canvas. I know how I can get the single created path with an event listener for the 'path:created' event. But I need to group all the drawed paths in one path-group object. Not just a group of elements with fabric.Group.

I tried to do that such way:

<code> new fabric.PathGroup( my_paths_array );</code>

But the created group has no proper dimensions. It has the left and top position as 0, and the same for the width and height.

**Comment by kangax** [comment]
Try using fabric.Group instead. In the future please ask questions on our Google group or stackoverflow (GitHub is only for issue reports or feature requests).
