### ISSUE TITLE
Converting canvas to string has different results in different browsers.

### ISSUE THREAD

**Issue by gabehayes** [kangax/fabric.js#2296]
Let me begin by saying that I'm not sure if fabric code is the cause of this issue, or if it is the browsers implementation of canvas.

That said, this issue is fairly straightforward. I have a fabric canvas that I am storing as a string via `JSON.stringify(canvasElement)`.

All works great, except that the returned string varies between Chrome and Safari (have not tested additional browsers).

#### Chrome
```
{"objects":[{"type":"i-text","originX":"left","originY":"top","left":353.14,"top":205.04,"width":91.62,"height":28.84,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","text":"I haz bug?","fontSize":22,"fontWeight":"normal","fontFamily":"Times New Roman","fontStyle":"","lineHeight":1.16,"textDecoration":"","textAlign":"left","textBackgroundColor":"","styles":{"0":{"1":{},"2":{},"3":{},"4":{},"5":{},"6":{},"7":{},"8":{},"9":{},"10":{}}}}],"background":""}
```

#### Safari
```
{"objects":[{"type":"i-text","originX":"left","originY":"top","left":353.14,"top":205.04,"width":93,"height":28.84,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","text":"I haz bug?","fontSize":22,"fontWeight":"normal","fontFamily":"Times New Roman","fontStyle":"","lineHeight":1.16,"textDecoration":"","textAlign":"left","textBackgroundColor":"","styles":{"0":{"1":{},"2":{},"3":{},"4":{},"5":{},"6":{},"7":{},"8":{},"9":{},"10":{}}}}],"background":""}
```

Upon closer inspection, there is a difference in the `width` reported for the `i-text` node. Chrome is reporting `"width":91.62` while Safari shows `"width":93`.

From all of the tests that I have ran on my end, it seems like this only occurs with text nodes.

So, I'm not sure if this is browser-level or within fabric, but definitely an oddity worth reporting I think.

Thanks!

**Comment by sapics** [comment]
Sadly, it would be come from browser-level, there are more informations at #331.

**Comment by kangax** [comment]
Yes, this is simply due to a difference in text/font rendering in browsers. Unfortunately nothing we can do about it (unless we switch to other text/font rendering engine or some such)
