### ISSUE TITLE
Position of object changed after scaling a group of object

### ISSUE THREAD

**Issue by pr-j** [kangax/fabric.js#2299]
Link: http://fabricjs.com/kitchensink/

Steps to reproduce:
1. Add two objects
2. Rotate one object
3. Select both objects and scale the group horizontally or vertically
4. Clear the selection

Result:
The rotated object has changed its position

Scaled group of object :
![scaled object](https://cloud.githubusercontent.com/assets/12932148/8231389/cd5b7656-15e5-11e5-8619-2534ae86fc07.png)

Position changed after clearing selection:
![positionchanged](https://cloud.githubusercontent.com/assets/12932148/8231402/eeb09624-15e5-11e5-8639-10291bf880c9.png)

**Comment by asturur** [comment]
This is a well known bug, and is a part of adding skew support.
