### ISSUE TITLE
Cant set shadow of free drawing

### ISSUE THREAD

**Issue by TimmNL** [kangax/fabric.js#2300]
With the latest version, that is available in the dist folder, i've tried to set a shadow behind a couple of free drawings. I've tried to add shadow the same way that this is done in kitchensink, but it doesn't work.
Is the dist version the most recent one?

**Comment by asturur** [comment]
what you find in DIST is what you find on kitchensink.
Can you show us code?

**Comment by TimmNL** [comment]
I've put the kitchensink one and the one from the dist folder next to eachother and they are different.
So i think that is the problem. I also checked my problem with the kitchensink version and now it works. So it might be a new bug or the dist folder isn't up to date.
