### ISSUE TITLE
 user controlled multiple background images in fabric js like normal image,

### ISSUE THREAD

**Issue by pixlharish** [kangax/fabric.js#2301]
I am building a new app with fabric js,
in this i need

1.) user controlled multiple background images in which behave like normal image, user can rotate, dragg, resize it,
it done some stuff like this for multiple BG,

// 1st img
var img = new Image();
img.onload = function(){
   canvas.setBackgroundImage(img.src, canvas.renderAll.bind(canvas), {
		originX: 'left',
		originY: 'top',
		left: 100,
		top: 100
	});
};
img.src = "site_image/temp/zig3.jpg";

// 2nd img
var img1 = new Image();
img1.onload = function(){
   canvas.setBackgroundImage(img1.src, canvas.renderAll.bind(canvas), {
		originX: 'left',
		originY: 'top',
		left: 300,
		top: 300
	});
};
img1.src = "site_image/temp/zig1.jpg";

But first BG is replaced by second one,
multiple backgrounds controlled by user are possible or not ?

2.) one more issue i faced,
i have json of fabric js, which include an image(normal image not background),
when i will show it to user i want that this image will become background of canvas,

**Comment by asturur** [comment]
which is the difference between 
multiple background images that user can rotate, drag and resize
AND
multiple images that user can rotate, drag and resize?

Why they have to be background images?

**Comment by pixlharish** [comment]
Sorry, i studied more about this issue, and i found that background images cant fulfill my task, i need multiple overlay images on a canvas, but i tried this, first overlay image is replaced by second image,

**Comment by darbs** [comment]
@pixlharish You can force the order of the images you want to act as an overlay.

**Comment by kangax** [comment]
Only 1 overlay image is supported for now

**Comment by pixlharish** [comment]
okkkk, thanks
