### ISSUE TITLE
is freeDraw with multiple fingers possible?

### ISSUE THREAD

**Issue by lethanhquang** [kangax/fabric.js#2303]
Hello Guys,

I'm new in fabric, in my project, I would like to use freeDraw function to serve for multiple people in the same time.

Is this possible with fabric? And how can I do that? I can't find any direction on docs.

Thanks,

**Comment by kangax** [comment]
I don't think it works now, although we do support gestures (through optional gestures module) for rotating/resizing object with 2 fingers. It should be possible to make free drawing work too. Pull request is super welcome, as always!

**Comment by asturur** [comment]
duplicate of #992.
