### ISSUE TITLE
i-text italic font change adding extra space and change reflects only after clicking outside the text area

### ISSUE THREAD

**Issue by sarath-prohaktiv** [kangax/fabric.js#2305]
![image](https://cloud.githubusercontent.com/assets/7422434/8348658/542e4918-1b33-11e5-8087-5040468f7c1a.png)
Steps to reproduce
#1) goto http://fabricjs.com/kitchensink/
#2) Select the second text box "foo bar

baz
quux"

#3) Apply italic to current font
#4) Select font family "Engagement"
You can no change in the text box. But the change will reflects once click outside the text area. Also it creates extra space at the end of text.

Note: Make sure to clear cache

**Comment by kangax** [comment]
This is due to font file not being loaded and is an expected behavior outside of Fabric. You can preload font before or observe its load state, then render canvas.

**Comment by sarath-prohaktiv** [comment]
This is not working even after preloading the font
