### ISSUE TITLE
i-text font underline with opacity

### ISSUE THREAD

**Issue by sarath-prohaktiv** [kangax/fabric.js#2306]
![image](https://cloud.githubusercontent.com/assets/7422434/8351611/4fa04130-1b4c-11e5-8df0-b8a493a40dae.png)

Steps to reproduce
1) Goto http://fabricjs.com/kitchensink/
2) Click "Add Text" from "Simple" tab
3) Apply underline for the newly added text box
4) Try to change opacity
Now you can see transparancy effect not reflecting on underline

**Comment by sarath-prohaktiv** [comment]
Applicable for background color too

**Comment by asturur** [comment]
I can confirmi just for background color and text lines background color.
Text decoration behaves fine for me.

**Comment by sarath-prohaktiv** [comment]
For underline you have to add a new text box as described above

**Comment by asturur** [comment]
i'm sorry, i did not check carefully the description. I was doing in iText.
I will correct those bugs easily.
