### ISSUE TITLE
setFontSize don't change object width

### ISSUE THREAD

**Issue by CSI68** [kangax/fabric.js#2307]
Hi,

I think I found a bug in Text object.
When I change font size with Text.setFontSize() function, then the object width don't change with Text.getWidth() function.

Here is my code:

console.log('FONT SIZE : '+obj.getFontSize()+' --- WIDTH : '+obj.getWidth());
obj.ctzParams.percent.fontSize=size;
obj.ctzParams.percent.width=obj.getWidth()/custengine.canvas.getWidth()*100;
obj.setFontSize(size);
custengine.canvas.renderAll();
console.log('FONT SIZE : '+obj.getFontSize()+' --- WIDTH : '+obj.getWidth());

Result :
FONT SIZE : 20 --- WIDTH : 27
FONT SIZE : 200 --- WIDTH : 27

What's wrong ?

Thanks

**Comment by asturur** [comment]
for performance reason text has some function cached.

you should manually call the function to calculate again the width of the object.

i ll try to find out wich one is it and tell you. you can check in text.class.js

**Comment by CSI68** [comment]
Thx asturur,

But I'm noob, where can i find text.class.js ? And how to call function ?
Perhaps you have an example to give ?

Thanks a lot

**Comment by asturur** [comment]
obj,_initDimensions();

will recalcuate the obj ( text and itext ) width eight.

**Comment by CSI68** [comment]
obj._initDimensions() returns me 'undefined'

**Comment by asturur** [comment]
It does not return anything:

```
    _initDimensions: function(ctx) {
      if (this.__skipDimension) {
        return;
      }
      if (!ctx) {
        ctx = fabric.util.createCanvasElement().getContext('2d');
        this._setTextStyles(ctx);
      }
      this._textLines = this.text.split(this._reNewline);
      this._clearCache();
      var currentTextAlign = this.textAlign;
      this.textAlign = 'left';
      this.width = this._getTextWidth(ctx);
      this.textAlign = currentTextAlign;
      this.height = this._getTextHeight(ctx);
    },
```

Just call it:

```
console.log('FONT SIZE : '+obj.getFontSize()+' --- WIDTH : '+obj.getWidth());
obj.ctzParams.percent.fontSize = size;
obj._initDimensions();
obj.ctzParams.percent.width = obj.getWidth()/custengine.canvas.getWidth()*100;
obj.setFontSize(size);
custengine.canvas.renderAll();
console.log('FONT SIZE : '+obj.getFontSize()+' --- WIDTH : '+obj.getWidth());
```

Is the only solution i can think of.

**Comment by CSI68** [comment]
Don't works,

console.log('FONT SIZE : '+obj.getFontSize()+' --- WIDTHH : '+obj.getWidth());
obj.ctzParams.percent.fontSize=size;
obj.ctzParams.percent.width=obj.getWidth()/custengine.canvas.getWidth()*100;
obj.setFontSize(size);
obj._initDimensions();
custengine.canvas.renderAll();
console.log('APRES FONT SIZE : '+obj.getFontSize()+' --- WIDTHH : '+obj.getWidth());

Result :
FONT SIZE : 200.65678550092 --- WIDTH : 27
FONT SIZE : 115.98513319216723 --- WIDTH : 27

**Comment by kangax** [comment]
We should document this better!

**Comment by CSI68** [comment]
Any idea Kangax for a solution ?

Thx

**Comment by typeslower** [comment]
Just wanted to say that this worked perfectly for me! I am so glad I randomly happened across this.

**Comment by mijaelcohen** [comment]
@CSI68 solutiondidnt work for me... not completley sure if works everywhere, but i came across this solution,
apparently other method that triggers the initDimensions internally is the `setFontSize` method... idk why doesnt work when initDimensions is called mannually...but if you resize by 1 and you set it back to normal then it calculates objects witht and set boundries to the end of the object... in my case doesnt quite fill the overall with off the text (icluding shadow) but its the closest i came across with 
```
this.canvas.forEachObject((o)=> {
      // clear cache ftw in style properties, thx guys
      o._clearCache()
      o.setFontSize(o.fontSize+1);
      o.setFontSize(o.fontSize);
    })
    this.canvas.renderAll()
```

I hope this helps somebody :P

**Comment by asturur** [comment]
on what version are you working?

**Comment by mijaelcohen** [comment]
^1.7.11

**Comment by asturur** [comment]
There is a list of dimensionsAffectingProps:

```javascript
_dimensionAffectingProps: [
      'fontSize',
      'fontWeight',
      'fontFamily',
      'fontStyle',
      'lineHeight',
      'text',
      'charSpacing',
      'textAlign',
      'styles',
    ],
```

every time you set one or some of those with the .set method `.set('lineHeight', value)` the initiDimensions gets called and width and height adjusted.

If this does not happen, please create a reproducible fiddle to investigate.
