### ISSUE TITLE
Scaling properties not saved on JSON.stringify(canvas)

### ISSUE THREAD

**Issue by mdiener** [kangax/fabric.js#2309]
Hello Kangax

I've noticed that the properties for lockScalingX / lockScalingY / lockUniScaling are not saved when calling `JSON.stringify(canvas)`. If you look at the jsfiddle (https://jsfiddle.net/55h9et9n/6/) you'll see that upon hitting the reload button, the object becomes scalable in all directions. When looking at the console output of the `JSON.stringify(canvas)` command you'll also see that there is no mentioning of lockUniScaling. I assume this has just been forgotten maybe?

Cheers,
Michael

**Comment by kangax** [comment]
Not all properties are included by default (this is intended), but you can always add them yourself — http://fabricjs.com/docs/fabric.Canvas.html#toJSON

**Comment by mdiener** [comment]
Hah! Now I feel stupid! Anyway, thanks for the quick response. Still one of the most comprehensive libraries I've seen out there! Great job!

If you're ever interested for what I'm using it head over to http://dizmo.com! We're using your library for various "dizmos" that provide sketching and graphing utilities :)

Again, thanks for the quick response and love how the library develops!

**Comment by kangax** [comment]
No worries, it's a reasonable thing to ask about. I'll check dizmo and maybe tweet about it!
