### ISSUE TITLE
Kitchen sink can not load its own exported SVG

### ISSUE THREAD

**Issue by sibbaldl** [kangax/fabric.js#2312]
Hi.
I'm evaluating FabricJS for an upcoming project and I've ran in to a pretty fundamental problem straight out of the gate, and hope someone here can help (I'm probably doing somethings stupid).

I created a simple jsFiddle to demonstrate the issue here https://jsfiddle.net/d9ky4d24/

The gist of the issue is that by using the svg export and import functionality included in the kitchensink demo I am unable to reliable load in the *ungrouped* SVG that was exported by the kitchensink.
Loading in grouped SVG appears to work (albeit the bounding box takes up the whole canvas rather than a calculated size based on the objects loaded, but that's another matter). When I load the same SVG without grouping, however, the bounding boxes are offset by an order of magnitude that renders the SVG useless for interaction.

You can test this yourself in the kitchensink demo. Simply clear the canvas, add a few simple shapes and position them as you like, export to SVG, copy the generated svg from the new page source, go back to kitchen sink and paste in to the Load SVG tab. Be sure to press "load without grouping" to see the problem I'm trying - badly, probably - to describe here. Hopefully the jsFiddle will demonstrate the issue clearer.

Cheers (great work by the way :+1: ) 

Lee

**Comment by asturur** [comment]
duplicate of #1520

please check PR #2215 for a possible solution.
It will be fixed officially asap.

Please consider doing a bit of reasearch on old issue before opening new one.

**Comment by sibbaldl** [comment]
I did search this forum and google in general and did not find the ticket you have linked to. I'll take a look though, thanks for the pointer.
