### ISSUE TITLE
Is there any way so object/img will be hidden behind transparent area of canvas' background image?

### ISSUE THREAD

**Issue by JugnuPathak** [kangax/fabric.js#2313]
We would like to hide newly added object/images when they are in transparent area of canvas's background image. 

![1015_2053](https://cloud.githubusercontent.com/assets/12165539/8407187/c37f94e2-1e81-11e5-84df-f70b01f057d0.png)

So newly added object/images will be only shown in black area while it will become hidden in transparent area in above image. All design will be visible only in black image area.

**Comment by asturur** [comment]
it depends. there are different ways.

1) you could use an overlay image that cover the canvas and is transparent just where the background image is not

2) you could use a clipping shape to do not draw anything outside this shape ( canvas.clipTo)

3) you could use a compositeoperation between object and canvas as "destination in". in that way objects over the transparent area will not be draw
you should put every object but not the background image as globalCompositeOperation = 'destination-in'

if you start a basic jsfiddle with the canvas and background set i can help you with examples.

**Comment by JugnuPathak** [comment]
@asturur  I have created a fiddle. What i want is to circle should be visible only in black area and should be hidden in transparent area.  
https://jsfiddle.net/jugnu_pathak/gs1L69fj/6/

**Comment by asturur** [comment]
example1: ( global composite operation )
https://jsfiddle.net/gs1L69fj/9/

example2: ( inverted overlay )
https://jsfiddle.net/gs1L69fj/8/

Clipping function is too complicated for me to wirte it from scratch, you should create a path that represent the black area.

**Comment by JugnuPathak** [comment]
Thanks for reply. We will try to implement this solution in our project and let you know if its working or will need your help further.
