### ISSUE TITLE
Can't set stroke svg path with Fabric.js

### ISSUE THREAD

**Issue by sarah0730** [kangax/fabric.js#2314]
fabric.loadSVGFromURL('2.svg', function(objects, options) {
			var loadedObject = fabric.util.groupSVGElements(objects, options);
				loadedObject.set({
				left: 252,
				top: 252,
				angle: 0,
				padding: 0,
				fill:'red',
                                strokeWidth : 8,
                                stroke : 'rgb(0,0,0)',
			});
				loadedObject.setCoords();
				canvas.add(loadedObject);
				canvas.calcOffset();
			});

This question is very important to me,Please help me to solve it.thanks

**Comment by asturur** [comment]
add this before groupSVGElements to set each object strokewdith.

```
for(i in objects) {
  objects[i].set({
    strokeWidth: 8,
    stroke: 'rgb(0,0,0)'
  });
}
```

**Comment by sarah0730** [comment]
i want to click my button to change stoke and stokewidth ,it's doesn't work

**Comment by asturur** [comment]
svg pathgroup does not have stroke like rect and circle in a meaning of border of bounding box. could you try to show us what are you trying to get?

**Comment by sarah0730** [comment]
> I means how I can choose the svg object and change it's attribute ?
Thanks.

**Comment by asturur** [comment]
as you did, but svg ( pathgroup ) does not have stroke and strokewidth attribute.

**Comment by sarah0730** [comment]
It display on canvas and how I can select it and change it's attribute ?

**Comment by asturur** [comment]
fill stroke strokewidth have no effect on svg.
please make a jsfiddle to demostrate issue or for general help use stackoverflow or googlegroup.
