### ISSUE TITLE
IText Broken on Android

### ISSUE THREAD

**Issue by keeganmccallum** [kangax/fabric.js#2318]
Due to this issue: https://code.google.com/p/android/issues/detail?id=42904#c15 text is uneditable for me on android in a cordova app. traced it to this part of the code:

      /**
       * Handles keyup event
       * @param {Event} e Event object
       */
      onKeyDown: function(e) {
        if (!this.isEditing) {
          return;
        }
        if (e.keyCode in this._keysMap) {
          this[this._keysMap[e.keyCode]](e);
        }
        else if ((e.keyCode in this._ctrlKeysMap) && (e.ctrlKey || e.metaKey)) {
          this[this._ctrlKeysMap[e.keyCode]](e);
        }
        else {
          // since keycode is always 0, we end up here every time. 
          return;
        }
        e.stopImmediatePropagation();
        e.preventDefault();
       this.canvas && this.canvas.renderAll();
      },

Not sure if anyone has any ideas, i've been manually setting the itext.text property equal to the value of the hiddenTextarea in this specific case, any other workarounds/bugfixes (which are a little cleaner) would be appreciated

**Comment by darbs** [comment]
@keeganmccallum I looked into this a while ago but i still think its the case that android chrome does not fire keypress event. This should probably be mapped to key up.

**Comment by keeganmccallum** [comment]
I looked into that, and there is no keypress event, that is correct, but the larger issue is that the keycode does not get passed in any event including keyup and keydown, this is apparently a security decision by android....but makes life difficult in this case...

**Comment by asturur** [comment]
we will move on oninput event.
it already prooved to solve lot of issues.
we need time to do it
