### ISSUE TITLE
Using fabric.js, using color from color picker in gradient colorstops is not working

### ISSUE THREAD

**Issue by technidhi** [kangax/fabric.js#2319]
I am trying to use color from color picker.

shape.setGradient('fill', {
			  type: 'linear',
			  x1: -shape.width / 2,
			  y1: 0,
			  x2: shape.width / 2,
			  y2: 0,
			  colorStops: {0 : '"'+$("#gradColor1").val()+'"' ,1 : '"'+$("#gradColor2").val()+'"'} ,
			});

But it is not working and showing error in console

TypeError: source is undefined
 return 'rgb(' + source[0] + ',' + source[1] + ',' + source[2] + ')';

jsfiddle link is http://jsfiddle.net/37hgdjda/11/

Please tell me, why color from color picker is not working with gradient colorstops?

**Comment by asturur** [comment]
http://jsfiddle.net/37hgdjda/13/

not fabricjs related.

**Comment by technidhi** [comment]
Hi Andrea,
 
Thanks alot for your help .

I am doing silly mistake and because of that wasting many hours, I am not able to find the solution.

Actually, what I am trying do is to apply gradient by selecting number of gradient color from drop down.
I am using variable gstops like colorStop : gstops

jsfiddle is http://jsfiddle.net/technidhi/0eyt736y/

Please tell me, will variable gstops 
work in place of  
{0 : '"'+$("#gradColor1").val()+'"' ,1 : '"'+$("#gradColor2").val()+'"'} ,

**Comment by asturur** [comment]
http://jsfiddle.net/0eyt736y/2/
you were creating colorstops as string, it must be an object.

Please check the offset x1 and x2, that were wrong ( set to -shape.width/2 +shape.width/2, while it should be 0 to shape.width)

We cannot give this kind of support here, it is outside the scope of this website and we do not have time, really.

**Comment by technidhi** [comment]
Hi Andrea,

Thanks alot once more for your help.

Thanks for informing me about the problem with code.

I have tried to find solution for this on different websites including stackoverflow but when I was not able to find solution nor I was able to fixed it myself then I joined this website and shared my problem.
