### ISSUE TITLE
Serious CORS oddities with loadFromJSON

### ISSUE THREAD

**Issue by noctivityinc** [kangax/fabric.js#2321]
We are having massive issues with CORS when trying to use loadFromJSON.  We stringify the canvas object, save it to an object in the database.  Here is a gist:

https://gist.github.com/noctivityinc/ec1c8f37f2649adb587c

Then we are using loadFromJSON to try to redraw the canvas.  Unfortunately, at random times random images will not appear on the canvas and we will get a CORS error:

    Cross-origin image load denied by Cross-Origin Resource Sharing policy.

We have now tried to use PXloader to preload the images before using loadFromJSON, but this still doesn't make a difference.  We are seeing this randomly in Chrome and Safari on Windows and Macs.

Refreshing sometimes helps, sometimes does not.  It's infuriating.  Also, as mentioned, this doesnt happen on EVERY canvas just randomly and, as you can see in the attachment, sometimes some of the images appear while others are blocked!?

Attached is a screen shot of what the canvas looks like when it fails to load.
![screen shot 2015-07-03 at 2 38 00 pm](https://cloud.githubusercontent.com/assets/78850/8503737/0d7ec44c-2192-11e5-94ae-d8285d8fe8f4.png)

<img width="1392" alt="screen shot 2015-07-03 at 12 03 46 pm" src="https://cloud.githubusercontent.com/assets/78850/8503735/05d711e0-2192-11e5-887f-b1616d0f1ea7.png">

**Comment by noctivityinc** [comment]
It's possible this has something to do with trying to load cached images using loadFromJSON.  When I uncheck DISABLE CACHE in dev tools I get the broken loaded images more frequently then anything else.

**Comment by moarsel** [comment]
I had similar problems when I was setting up my project, and I was sure it was a fabric.js bug at first. However, as I did some digging into the settings on my CDN, it turned the CORS headers were being set slightly wrong on the server side. Also make sure you clear your image cache before testing it again.

**Comment by 0mega** [comment]
I'am having a similar issue.
I have a site with Basic Authentication, so all assets are fetched from server using `Authorization: Basic ...`header. However, when I restore the canvas using `#loadFromJSON`, it (very frequently) tries to fetch the image without including the `Authorization` header. This results in unauthorized request and thus no image in canvas.

I'll try to solve this, so if anyone has some extra information or more extensive testing that can help, please post.

**Comment by noctivityinc** [comment]
I would that the issue had to do with the cache buster that was added to the images.  Once I used js to remove the cache buster all was well.

**Comment by asturur** [comment]
cache buster?

**Comment by 0mega** [comment]
I see, because in that case the page doesn't have to fetch the image again right?

But anyway it shouldn't fail fetching an image, the problem is somewhere when creating the <img> tag and assigning the src (maybe it doesn't have access to context or something and that's why the headers are not populated).

**Comment by asturur** [comment]
Did someone findout if this problem need a fabricjs fix?

**Comment by stewartmatheson** [comment]
Was there ever a fix for this? I'm having a similar issue to the one @noctivityinc has described however the issue I'm facing comes from loading SVG's. Loading in the canvas JSON never causes an issue nor does loading images, for me it's just SVG's. Again sometimes it will work and sometimes it won't. The issue happens in chrome and safari however in Firefox everything works. 

The odd thing is that the error message suggests that the 'Access-Control-Allow-Origin' header is not set in the response. This header in the case of S3 will only get set if the request header includes "Origin: Somewhere.com". So is it possible that chrome it's self is not setting this header? Why else would it complain about not getting the allow control allow origin header response if not for that? I'm not even sure how to debug the chrome request as it does not seem to appear in the network tab. Any ideas around this. It's very strange.
