### ISSUE TITLE
Select object (svg) don't work

### ISSUE THREAD

**Issue by livemirsi** [kangax/fabric.js#2322]
Hello. This code don't work.
<code>
	fabric.loadSVGFromURL('http://fabricjs.com/assets/2.svg', function(objects, options) {
      var loadedObject = objects[0];
      loadedObject.set({left: 450, top: 200});
      canvas.add(loadedObject);
    });
canvas.setActiveObject(canvas.item(0));
</code>
I can't set active object after imported svg file. Is it bug  ?

**Comment by asturur** [comment]
just error in your code.
When you call
```
canvas.setActiveObject(canvas.item(0)); 
```

the item is not loaded yet.
