### ISSUE TITLE
Error drawing generated svg 'rectangle class' in corel draw X7

### ISSUE THREAD

**Issue by alexeymakarov90** [kangax/fabric.js#2325]
When making a simple rect fabric wrights to it rx="0", ry="0".
Corel does not understand generated svg with `<rect x="200" y="10" rx="0" ry="0" ..>`
But works fine with `<rect x="200" y="10" rx="" ry="" ..>`
No troubles in adobe illustrator.
How to make svg generation to watch rect class and remove 'rx' 'ry' if they have 0 value?

Default:
![invalid](https://cloud.githubusercontent.com/assets/9444261/8522401/61773064-23f6-11e5-99b9-802002af2735.JPG)

After fix:
![correct](https://cloud.githubusercontent.com/assets/9444261/8522402/6178cdd4-23f6-11e5-9aaa-967ac678bc02.JPG)

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group — https://groups.google.com/forum/#!forum/fabricjs — where someone will usually assist you.

The issue tracker is only for bugs and feature requests.

Thanks for your understanding!
