### ISSUE TITLE
Text rendering on nodejs significantly different from browser

### ISSUE THREAD

**Issue by DanieleSassoli** [kangax/fabric.js#2326]
Hi,
I'm trying the awesome new textbox by @jafferhaider  that is now under review. Everything works well for me in the browser,  but when I get to render the text on node the result differs significantly from the what I see in the broswer. 
this is the view in the browser 
![i20 cimgpsh_orig](https://cloud.githubusercontent.com/assets/4007741/8549042/e1b75092-24c8-11e5-90b0-6805da374d5b.PNG)
And this is the rendered image(don't take any notice on the yellow triangle in the first image)
![200-c0](https://cloud.githubusercontent.com/assets/4007741/8549057/f63276fa-24c8-11e5-8788-1efee6f1b7d4.jpg)
I've seen that probably it is related to point 2 and 3 of [this] (https://github.com/kangax/fabric.js/wiki/Fabric-limitations-in-node.js) list of limitations for nodejs. I tried looking for some workaround but didn't really find anything. Is there something  I can do? 
I don't think code will be useful in this case, but if yo uwant I'll post it. I just export the json from the browser and load it with the loadFromJson function on nodejs.

**Comment by DanieleSassoli** [comment]
Hi,
The only solution i've found, was to create an html template with handlebarsjs and then render it using slimer, the result is identical to the browser view. Just leaving this is in case someone in the future needs it.

**Comment by vitalniko** [comment]
>I'm trying the awesome new textbox by @jafferhaider 
Could you point me to it?

**Comment by inssein** [comment]
@DanieleSassoli any chance you could try it again, now that is it merged in master. There are no changes in rendering in the textbox implementation, so I am surprised there is such a big difference. Have you tried the same text in IText or Text just for rendering purposes?

**Comment by DanieleSassoli** [comment]
@vitalniko Sorry looks like I missed the notification on that, anyway now it has been merged in master. 
@inssein I'm not sure what you mean with:" Have you tried the same text in IText or Text just for rendering purposes?" 
I have tried it again now that is merged but the result is the same.
I could have render it with phantomjs to make it headless, but i used slimer because I had better perfomances.

**Comment by inssein** [comment]
What I meant was that have you tried recreating the Textbox in IText or
Text class and seeing if the rendering is the same?

**Comment by DanieleSassoli** [comment]
That's wat I did before, and with IText the rendering was almost correct.

**Comment by inssein** [comment]
Ah ok, that is a pretty critical issue for Textbox then. Hopefully we can create some simple test cases and see where the errors are, and resolve them soon.

**Comment by DanieleSassoli** [comment]
I solved this issue in a different way in the end, any news if this is still an issue with the new test box? or can we close this?

**Comment by DanieleSassoli** [comment]
I think this issue isn't relevant anymore since the textbox has changed significantly since I opened this issue. Closing
