### ISSUE TITLE
imageSmoothingEnabled not set after call to setDimensions

### ISSUE THREAD

**Issue by kirschkern** [kangax/fabric.js#2331]
When I set imageSmoothingEnabled to false on initializing my context still uses smoothing because I've used setWidth or setHeight to change the canvas size. It seems like imageSmoothingEnabled will be reset for the context by the browser when changing width or height of the canvas.

**Comment by asturur** [comment]
http://jsfiddle.net/asturur/a5w37u05/1/ confirmed
