### ISSUE TITLE
Issue with serializing / deserialzing SVGs

### ISSUE THREAD

**Issue by sobanhameed** [kangax/fabric.js#2333]
Hi folks,

I am doing a basic serialization and deserialization test on fabric js by adding a svg like this:

    var path = fabric.loadSVGFromString(svgContent,function(objects, options) {
     var obj = fabric.util.groupSVGElements(objects, options);      
      obj.scaleToHeight(canvas.height-10)
         .set({ left: canvas.width/2, top: canvas.height/2 })
         .setCoords();
      canvas.add(obj).renderAll();
    });

Then I am using the following code to serialize the canvas and deserialize to see if I can save the state and recreate it later.

    // Test Serialization
    var json = JSON.stringify(this.state.canvas.toJSON());

    console.log(json);

    this.state.canvas.clear();

    var canvas = this.state.canvas;

    // and load everything from the same json
    this.state.canvas.loadFromJSON(json, function() {
        // making sure to render canvas at the end
        canvas.renderAll();
    });

    json = JSON.stringify(this.state.canvas.toJSON());
    console.log(json);

I have attached the output. Somehow the svg group doesn't seem to be interpreted & placed correctly. The JSON logged in both steps are identical.
![before](https://cloud.githubusercontent.com/assets/5161456/8661446/63f18fb2-296c-11e5-837c-d737e2af96aa.png)
![after](https://cloud.githubusercontent.com/assets/5161456/8661453/6e287e78-296c-11e5-991a-894b71a48bff.png)

**Comment by asturur** [comment]
please provide SVG and possibly a JSfiddle.

**Comment by sobanhameed** [comment]
JSFiddle: https://jsfiddle.net/sobanhameed/e4yk6m9e/5/

------------- SVG ----------

<?xml version="1.0" encoding="UTF-8" standalone="no"?> <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">   <svg width="100pt" height="148pt" viewBox="0.00 0.00 100.00 148.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"> <g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 144)"> <title>%3</title> <polygon fill="white" stroke="none" points="-4,4 -4,-144 96,-144 96,4 -4,4"/>  <g id="node_1436825277891" class="node"><title>node_1436825277891</title> <path fill="#caff70" stroke="#caff70" stroke-width="0.5" d="M40.1667,-110.5C40.1667,-110.5 49.8333,-110.5 49.8333,-110.5 54.6667,-110.5 59.5,-115.333 59.5,-120.167 59.5,-120.167 59.5,-129.833 59.5,-129.833 59.5,-134.667 54.6667,-139.5 49.8333,-139.5 49.8333,-139.5 40.1667,-139.5 40.1667,-139.5 35.3333,-139.5 30.5,-134.667 30.5,-129.833 30.5,-129.833 30.5,-120.167 30.5,-120.167 30.5,-115.333 35.3333,-110.5 40.1667,-110.5"/> <text text-anchor="middle" x="44.7992" y="-120.2" font-family="Courier,monospace" font-size="16.00">2</text> </g>  <g id="node_1436825277892" class="node"><title>node_1436825277892</title> <path fill="#caff70" stroke="#caff70" stroke-width="0.5" d="M17.1667,-44.5C17.1667,-44.5 26.8333,-44.5 26.8333,-44.5 31.6667,-44.5 36.5,-49.3333 36.5,-54.1667 36.5,-54.1667 36.5,-63.8333 36.5,-63.8333 36.5,-68.6667 31.6667,-73.5 26.8333,-73.5 26.8333,-73.5 17.1667,-73.5 17.1667,-73.5 12.3333,-73.5 7.5,-68.6667 7.5,-63.8333 7.5,-63.8333 7.5,-54.1667 7.5,-54.1667 7.5,-49.3333 12.3333,-44.5 17.1667,-44.5"/> <text text-anchor="middle" x="21.7992" y="-54.2" font-family="Courier,monospace" font-size="16.00">1</text> </g>  <g id="edge1" class="edge"><title>node_1436825277891&#45;&gt;node_1436825277892</title> <path fill="none" stroke="black" d="M40.1223,-110.427C37.0729,-101.942 33.0812,-90.8347 29.6205,-81.2048"/> <polygon fill="black" stroke="black" points="32.2113,-80.1348 26.8707,-73.5532 26.9413,-82.0288 32.2113,-80.1348"/> </g>  <g id="node_1436825277893" class="node"><title>node_1436825277893</title> <path fill="#caff70" stroke="#caff70" stroke-width="0.5" d="M64.1667,-44.5C64.1667,-44.5 73.8333,-44.5 73.8333,-44.5 78.6667,-44.5 83.5,-49.3333 83.5,-54.1667 83.5,-54.1667 83.5,-63.8333 83.5,-63.8333 83.5,-68.6667 78.6667,-73.5 73.8333,-73.5 73.8333,-73.5 64.1667,-73.5 64.1667,-73.5 59.3333,-73.5 54.5,-68.6667 54.5,-63.8333 54.5,-63.8333 54.5,-54.1667 54.5,-54.1667 54.5,-49.3333 59.3333,-44.5 64.1667,-44.5"/> <text text-anchor="middle" x="68.7992" y="-54.2" font-family="Courier,monospace" font-size="16.00">3</text> </g>  <g id="edge2" class="edge"><title>node_1436825277891&#45;&gt;node_1436825277893</title> <path fill="none" stroke="black" d="M50.0898,-110.427C53.2717,-101.942 57.437,-90.8347 61.0482,-81.2048"/> <polygon fill="black" stroke="black" points="63.7302,-82.027 63.9176,-73.5532 58.4868,-80.0607 63.7302,-82.027"/> </g>         </g> </svg>

**Comment by sobanhameed** [comment]
Let me know if you need anything else to look at this issue.

**Comment by asturur** [comment]
removed useless code to work on it later.
https://jsfiddle.net/asturur/e4yk6m9e/7/
I think probably some text or path rare property not exported by default in object version.
(still have to look at it)

**Comment by asturur** [comment]
https://jsfiddle.net/asturur/e4yk6m9e/9/

ok we are missing this.transformMatrix in toObject default values.
i think it should be there, is crucial for serializing pathGroups.

**Comment by sobanhameed** [comment]
Great work guys in figuring out the issue. I will watch our for this fix and test it once its ready.

**Comment by sobanhameed** [comment]
@asturur - Can you tell me how I can get a drop of the fabric.js build with this fix? Should I clone and build myself or you guys release periodically? Appreciate the help.
