### ISSUE TITLE
controls are at wrong position when moving a transformed shape

### ISSUE THREAD

**Issue by gprasanth** [kangax/fabric.js#2338]
related issue: #1520 
code in [this](https://github.com/kangax/fabric.js/issues/1520#issuecomment-109122794) comment by aearly seems to be working (the image is not offset by 200 as originally written) in version 1.5.0, but only until the object is moved around.

with this [fiddle](http://jsfiddle.net/m0yzzugk/),

notice how the image is with in the controls, but try moving the image to see it "jump" to 200, 200 but the controls stay put.

**Comment by asturur** [comment]
please stick to #1520.
