### ISSUE TITLE
toSVG fails in presence of Textbox

### ISSUE THREAD

**Issue by mochidusk** [kangax/fabric.js#2339]
I am trying out the new Textbox and when I call toSVG, I get "Uncaught RangeError: Maximum call stack size exceeded". 

The error appears to be coming from callSuper method being triggered by _setSVGTextLineText. Looks like it's stuck in some kind of infinite loop.

**Comment by inssein** [comment]
Ah that could be very easily true, I have never used the SVG functionality and probably didn't test it in the implementation. I am little bit swamped right now, but perhaps over the weekend I could try to take a look.

**Comment by asturur** [comment]
There is a loop in the callsuper i m not able to solve.
@kangax is there anyway we can callSuperSuper in an elegant way?
Also some modification are needed to get textbox working with latest changes:

1) set the width in the array this.__lineWidths[]
2) create StyleMap everytime splitTextLines is called
3) search around for direct access to style object and replace with the methods that allows the textbox to use the stylemap

**Comment by jafferhaider** [comment]
I had reported this callSuper issue in my original pull request as well. call super doesn't seem to work if the current class has a grandparent class. Only works if there is one level of inheritance.

As a work around I had manually called IText's function instead of using callSuper. Better solution is to redo callSuper to work with multiple levels of inheritance.

**Comment by asturur** [comment]
How did you call it manually? i tried but failed.
i tried fabric.Itext.functionName(.....)  but getting no luck because i'm missing something.
can you share?

**Comment by asturur** [comment]
i found it:
fabric.Text.prototype._setSVGTextLineText.call(this,
+              lineIndex, textSpans, height, textLeftOffset, textTopOffset);

i was doing
fabric.Text.prototype._setSVGTextLineText.apply(this,
+              lineIndex, textSpans, height, textLeftOffset, textTopOffset);

and getting no luck.

**Comment by jafferhaider** [comment]
@asturur Yep, that is what I was doing. Sorry for the delay in responding ... I was on vacation.
