### ISSUE TITLE
SVG rendering incorrectly

### ISSUE THREAD

**Issue by anonymos-kaled** [kangax/fabric.js#2341]
I can convert my svg fabric in js.
I find it a problem between version 1.4 and 1.5

Example SVG : 
http://jsfiddle.net/pj7773aa/

Test with Google Chrome

Against it by a regression with version 1.5 in this example fabricjs.

http://fabricjs.com/kitchensink/

**Comment by asturur** [comment]
```xml
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" width="480" height="650">
    <defs>
        <linearGradient id="MotifVitrageAuto" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" stop-color="#a0d8ef" stop-opacity="1"/>
            <stop offset="35%" stop-color="#ddf1f9" stop-opacity="1"/>
            <stop offset="100%" stop-color="#feffff" stop-opacity="1"/>
        </linearGradient>

        <filter id="OmbreG">
            <feGaussianBlur in="SourceAlpha" stdDeviation="1" result="lightblur"/>
            <feComposite in="SourceGraphic" in2="specOut" operator="arithmetic" k1="0" k2="1" k3="1" k4="0" result="lighted" />
            <feGaussianBlur in="SourceAlpha" stdDeviation="0.5" result="blurred" />
            <feOffset in="blurred" result="shadowoffset" dx="1.5" dy="1.5"/>
            <feMerge> <feMergeNode in="shadowoffset"/> <feMergeNode in="lighted"/> </feMerge>
        </filter>

        <!-- Definition Motif Verre remplissage -->
        <pattern id="MotifVitrage" patternUnits="userSpaceOnUse" width="115" height="115" >
            <image width="115" height="115" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOkAAADpCAYAAADBNxDjAAAgAElEQVR4Xoy953Ncy5bll1XwAAEQjkCRBEDQ8977bHeP/mLpgxQKaRShaU1Mh2Zao1G0pp+9hp4ESHjvPapK8Vs7d548B8Wnqde3SQJVdc7J3GbttU3WVrc23rRDbboWQght/V+o8Q/+kr3q9XrYPTwIH758De34y+6urtBq86F2GOjrC796/jy0W/ZbfUf8Gv/ukH2v3qN3tEKo1Ys3x2vad9RCu9kMbxc/h8vmTbg7PBJePXoUPnxdDqvbW6HZbIbJ0dHw6xcvwrsvX8LG9k54dL8RpienQr1WC61WS9/RxYVqdd1rd70Wtg8Pw9rmZji/vAyT4+NhaKAvrG5uh8G+3nBxdR1+ePpMN8ej+ater4XuWi1ct1qhXquHr+trYf/4OHz/+HH4sr4Rdg4OwsN7U2FmajL0dHXrWu1QCxtbW2FlazNMjI2F/aOjcHNzEwb7+8N1sxlezc+Hrno9LK6vhaPTs8Aa87o7PBwGe3vD3uFhuGq2wrO52TA0OBiW1tbC4fFxaLZaevYXjx6FkTvDod1u6T978R3Vv+c/i++ptYo9zt9ePHH8nupn04qUBUTXjPtY+k355+wHr57urnB4dByWN9a1R1c3Te3N+MhI6Onr07r5Jyfu3g1TE+Ph8/JKuNM/EBrT06HF87aD1uzg+Dh8WV8NL+Yfhb7ePpPJ0Aq1eD/tuB78u1avhfPz87C2vR3a7XZotZtaLj7T09sbhvr7w9idO9rnrf39cHZ+rvcNDQyE+Qf3tfcuF+1WS48s8Qp1yb2uxa2129KBGr9Ny1IP7VYzk6muQkeiviQd5DdRX2prGxtb7Vptii+UYkTt4Uayz2khWZhfPn4MR6enUsrHDx+G3u6ecHByHL5ubITvFhbC3ZERKUd6ZYqv73RFjUrg10gXc8XWe2vh+uYmvFn8HC6urmQcFu4/CCdnZ2Fzbz/...
removed....
moY6xAKhKiruaPnxgvUwSTQn1rKdD+rOhMaJg6uC8xr+FuFNqoyX65PS7xndBKXZ4OidqILXcofsOSpqe0zWja47S6wK6oHtpXwKZlQhiSOr26uFdiRmYtzr/WdUWvfR4+Oab/WoZjSHVzGZYY4k5jsbbu//1aX/B+fI/Ke1UZwNAAAAAElFTkSuQmCC"/>
        </pattern>
        <!-- Definition Motif remplissage : un seul par porte -->
        <pattern id="MotifBois" patternUnits="userSpaceOnUse" width="100" height="100">
            <image width="100" height="100" xlink:href="file://F:\CORSAIR\1_SiFAST\Projets\2014\Menuiserie\Couleur_Motif\image-motif\Anteak.png"/>
        </pattern>

        <svg id="Imposte" width="465" height="130">
            <rect x="15" y="15" width="435" height="100" stroke="none" fill="url(#MotifVitrageAuto)"/>
            <g fill="#EAE6CA" stroke="none" filter="url(#OmbreG)">
                <rect x="145" y="15" width="15" height="100"/>
                <rect x="305" y="15" width="15" height="100"/>
                <rect x="120" y="40" width="65" height="50"/>
                <rect x="280" y="40" width="65" height="50"/>
                <rect x="7.5" y="7.5" width="450" height="115" fill="none" stroke="#EAE6CA" stroke-width="15"/>
            </g>
        </svg>

        <svg id="Lateral" width="120" height="515">
            <rect x="15" y="15" width="90" height="485" stroke="none" fill="url(#MotifVitrage)"/>
            <g fill="#EAE6CA" stroke="none" filter="url(#OmbreG)">
                <rect x="15" y="125" width="90" height="15"/>
                <rect x="15" y="250" width="90" height="15"/>
                <rect x="15" y="375" width="90" height="15"/>
                <rect x="7.5" y="7.5" width="105" height="500" fill="none" stroke="#EAE6CA" stroke-width="15"/>
            </g>
        </svg>

        <svg id="PanneauStd" width="225" height="500">
            <image width="225" height="500" stroke="none" preserveAspectRatio="none" filter="url(#OmbreG)"
                   xlink:href="http://simuleo-bo.sifast.fr/uploads/media/couleurvantail/0001/01/aac6644aa7fc65bf5e20ba5171651974f4402ee3.png"/>
            <!-- Dessin du cadre Ouvrant -->
            <rect x="7.5" y="7.5" width="210" height="485" fill="none" stroke="red" stroke-width="15" filter="url(#OmbreG)"/>
        </svg>

        <svg id="PanneauMono" width="225" height="500" preserveAspectRatio="none" filter="url(#OmbreG)">
            <image x="-15" y="-15" width="255" height="515" stroke="none" preserveAspectRatio="none" filter="url(#OmbreG)"
                   xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAdEAAAPoCAYAAACBKcTXAAAgAElEQVR4Xuy9Wa/ta3afNedae59TzamyY5etuBoninADCFkgZEX5FhAhZJexPwB3fA5AjiUu+CCu3KIoEAEWSEjgchKlhLiJnRu7ymXX2Xs16Dee8bxjzHn2KQphwwWZR1V7rbn+zduM9jea9/qd/+o/e738689f2wp8/NHHl0/fffpjn/9519x/v3//0M/5Lp/9Pr+7//5+QD5vX+81Pu9Df/trW7i7B2cM/1++//+tef51vufjj78A
... removed ...
fXz6o8+8Jn/L9/67L/i8v/m8Qyd3z93Pur/2Q/d86Hk/yTv2s36SZ/x1rvG/fvb/v1bg63/v25frf/j1Xygl+vpnn
ElFYJVDuQ9ZLiFKjUHP10Q4S6KXNa5GHNKuF4iyll/iQkZEOHI8tf4SUqT8ErITEnn27NkdjmJXLkP1oeipw7PKYWiMIxcBp7CNG6mIj+8ckSHP1yh/3o/Iq+7x8Z3qLD1bWts1REYb1AEZ6n4NYe66dx5SbgmhgQzru4oA72v/gyC9NSS1hpAqQtulLghsG2Li+7YhsooE75uPn/R7IdFvf/4vpo9Nr6XleXUItqWuLiFWEKfkOYEki4Ehz/AmFze62buc/vCLX/j3/wV8TKd5B4rxtAAAAABJRU5ErkJggg=="/>
        </svg>

        <path id="CadreDormantVantail" d="M7.5,515 v-507.5 h240 v507.5" fill="none" stroke="#EAE6CA" stroke-width="15" filter="url(#OmbreG)"/>

        <!-- Dessin paumelle -->
        <path id="paumelle" d="M12.5 55 v23 M12.5 255 v23 M12.5 455 v23" stroke="#606060" stroke-width="5" stroke-linecap="round" stroke-dasharray="9,5"/>
        <!-- Dessin poignee -->
        <g id="poigneD" fill="#F6DC12" stroke="gray" stroke-width="0.7" strok-opacity="0.7">
            <circle cx="22.5" cy="250" r="6"/>
            <rect x="20" y="246.5" width="40" height="7" rx="15" ry="3.5"/>
            <circle cx="22.5" cy="275" r="6"/>
            <path fill="none" stroke-linecap="butt" stroke-width="2" d="M22.5,270 v10"/>
        </g>
    </defs>

    <!-- 4 Cadre Mono Vue Interne : Dessin cadre avant Vantail -->
    <g transform="translate(0,10)">
        <rect x="15" y="15" width="435" height="615" fill="url(#MotifVitrageAuto)"/>
        <use xlink:href="#CadreDormantVantail" transform="translate(105,115)"/>
        <use xlink:href="#Lateral" transform="translate(0,115)"/>
        <use xlink:href="#Lateral" transform="translate(345,115)"/>
        <use xlink:href="#Imposte" transform="translate(0,0)"/>
        <use xlink:href="#PanneauMono" transform="translate(120,130)"/>
        <use xlink:href="#paumelle" transform="translate(105,115)"/>
        <use xlink:href="#poigneD" transform="translate(105,115) scale(-1,1) translate(-255,0)"/>
    </g>
</svg>
```
loads better in 1.4.12 than in 1.5.0. Both situation not correct.
Many unsupported features

**Comment by asturur** [comment]
The problem is in the inner svg elements.
We recently changed a regex in parser to do not consider svg tagname as valid containers.
But we were wrong, property should descend from svg also.

**Comment by kangax** [comment]
Hm, I didn't even know there could be nested svg's — http://sarasoueidan.com/blog/nesting-svgs/

**Comment by anonymos-kaled** [comment]
Thank you for the answer, but I know why I can not parse the SVG :
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" width="480" height="650">
   <desc>Created with Snap</desc><defs><filter id="Sic5wmaub2" filterUnits="userSpaceOnUse"><feGaussianBlur in="SourceAlpha" stdDeviation="4"></feGaussianBlur><feOffset dx="-2" dy="2" result="offsetblur"></feOffset><feFlood flood-color="#000000"></feFlood><feComposite in2="offsetblur" operator="in"></feComposite><feComponentTransfer><feFuncA type="linear" slope="1"></feFuncA></feComponentTransfer><feMerge><feMergeNode></feMergeNode><feMergeNode in="SourceGraphic"></feMergeNode></feMerge></filter><pattern x="0" y="0" width="150" height="150" patternUnits="userSpaceOnUse" id="Sic5wmaub6" viewBox="0 0 150 150"><image xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http://simuleo-bo.sifast.fr/uploads/media/vitrage/0001/06/a602557251b284527714f054893db7fb8748fce5.png" preserveAspectRatio="none" x="0" y="0" width="150" height="150"></image></pattern></defs><g transform="matrix(0.8955,0,0,0.6213,735.3724,189.5598)" id="global_group"><rect x="0" y="0" width="255" height="515" rx="0" ry="0" stroke="none" fill="url('#Sic5wmaub6')" style=""></rect><g transform="matrix(1,0,0,1,0,0)" filter="url('#Sic5wmaub2')"><image xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http://simuleo-bo.sifast.fr/uploads/media/couleurvantail/0001/02/ff256c27b77497a948fbc6d42b9aee494a2186f9.png" preserveAspectRatio="none" x="15" y="15" width="225" height="500"></image><path d="M242.5 55 v23 M242.5 255 v23 M242.5 455 v23" stroke="#f5f5fa" style="stroke-width: 5px; stroke-linecap: round; stroke-dasharray: 9px, 5px;"></path></g><rect x="22.5" y="22.5" width="210" height="485" rx="0" ry="0" stroke="#2b3136" fill="none" filter="url('#Sic5wmaub2')" transform="matrix(1,0,0,1,0,0)" style="stroke-width: 15px;"></rect><image xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http://simuleo-bo.sifast.fr/uploads/media/accessoire/0001/06/3327cfcf569a4ac03c67fb8758840aacf496dfa6.png" preserveAspectRatio="none" x="0" y="0" width="225" height="500" transform="matrix(1,0,0,1,0,0)"></image><g></g><g></g><g></g><g fill="none" stroke="#2b3136" filter="url('#Sic5wmaub2')" id="cadreSimulation" style="stroke-width: 15px;"><path d="M7.5,515 v-507.5 h240 v507.5" transform="matrix(1,0,0,1,0,0)"></path></g></g></svg>
    

Example : http://jsfiddle.net/masmoudi/pj7773aa/5/

**Comment by anonymos-kaled** [comment]
Thank you for the answer, but I know why I can not parse the SVG :

<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" width="480" height="650">
   <desc>Created with Snap</desc><defs><filter id="Sic5wmaub2" filterUnits="userSpaceOnUse"><feGaussianBlur in="SourceAlpha" stdDeviation="4"></feGaussianBlur><feOffset dx="-2" dy="2" result="offsetblur"></feOffset><feFlood flood-color="#000000"></feFlood><feComposite in2="offsetblur" operator="in"></feComposite><feComponentTransfer><feFuncA type="linear" slope="1"></feFuncA></feComponentTransfer><feMerge><feMergeNode></feMergeNode><feMergeNode in="SourceGraphic"></feMergeNode></feMerge></filter><pattern x="0" y="0" width="150" height="150" patternUnits="userSpaceOnUse" id="Sic5wmaub6" viewBox="0 0 150 150"><image xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http://simuleo-bo.sifast.fr/uploads/media/vitrage/0001/06/a602557251b284527714f054893db7fb8748fce5.png" preserveAspectRatio="none" x="0" y="0" width="150" height="150"></image></pattern></defs><g transform="matrix(0.8955,0,0,0.6213,735.3724,189.5598)" id="global_group"><rect x="0" y="0" width="255" height="515" rx="0" ry="0" stroke="none" fill="url('#Sic5wmaub6')" style=""></rect><g transform="matrix(1,0,0,1,0,0)" filter="url('#Sic5wmaub2')"><image xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http://simuleo-bo.sifast.fr/uploads/media/couleurvantail/0001/02/ff256c27b77497a948fbc6d42b9aee494a2186f9.png" preserveAspectRatio="none" x="15" y="15" width="225" height="500"></image><path d="M242.5 55 v23 M242.5 255 v23 M242.5 455 v23" stroke="#f5f5fa" style="stroke-width: 5px; stroke-linecap: round; stroke-dasharray: 9px, 5px;"></path></g><rect x="22.5" y="22.5" width="210" height="485" rx="0" ry="0" stroke="#2b3136" fill="none" filter="url('#Sic5wmaub2')" transform="matrix(1,0,0,1,0,0)" style="stroke-width: 15px;"></rect><image xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http://simuleo-bo.sifast.fr/uploads/media/accessoire/0001/06/3327cfcf569a4ac03c67fb8758840aacf496dfa6.png" preserveAspectRatio="none" x="0" y="0" width="225" height="500" transform="matrix(1,0,0,1,0,0)"></image><g></g><g></g><g></g><g fill="none" stroke="#2b3136" filter="url('#Sic5wmaub2')" id="cadreSimulation" style="stroke-width: 15px;"><path d="M7.5,515 v-507.5 h240 v507.5" transform="matrix(1,0,0,1,0,0)"></path></g></g></svg>
    

Example : http://jsfiddle.net/masmoudi/pj7773aa/5/

**Comment by asturur** [comment]
i do not understand neither yuor post nor your requests.
The second svg you posted is white anyway, and full of unsupported features by fabricjs
filtes, patterns.

it does not open with chrome or firefox at all.
