### ISSUE TITLE
Any way to minimize  the  huge text box size?

### ISSUE THREAD

**Issue by vitalniko** [kangax/fabric.js#2343]
Is it possible to minimize the text box around text object to the text itself?

It always has a huge padding(s) around it like: 
![ ](http://i.stack.imgur.com/9ht97.jpg) or 
![ ](http://i.stack.imgur.com/RHzJe.jpg)

**Comment by asturur** [comment]
No.
This padding accounts for capital letters and lineHeight.
Try to reduce lineHeight of text if you are not interested in multi line text.

**Comment by vitalniko** [comment]
I'm interested in the multi-line text, but i'm not in outer paddings.
I tried to play with the lineHeight, but  with no result
Any way to calculate these outer paddings and reduce the  box size?

There's definitely something wrong with calculations.
Here's the  examle of text object (fontSize:44, lineHeight:1)
The first letter is capital. But the box has a very big top padding. But  the bottom line intersects with the letters
![](http://dl2.joxi.net/drive/0010/0913/717713/150715/391fab932d.jpg)

**Comment by asturur** [comment]
The box is calculated in this way:
```
this._fontSizeMult:             1.13

_getHeightOfLine: function() {
      return this.fontSize * this._fontSizeMult * this.lineHeight;
 },
```

So for a 44px font you will have at least 44 * 1.13 pixel box.

No real height of font is calculated because actually javascript does not have a way to check it.
Some external libraries may be used, but we do are not doing it yet

**Comment by vitalniko** [comment]
Thank you, Andrea
 
>Some external libraries may be used, but we are not doing it yet

Could you point me to some?
