### ISSUE TITLE
Resize cursor appears when scale is locked.

### ISSUE THREAD

**Issue by vitalniko** [kangax/fabric.js#2351]
The resize cursor appears over controls when the resize options are locked.
*Steps to recreate:*
Run the following code
```javascript
canvas =  new fabric.Canvas('canv');
var txt = new fabric.Text('Text string', {lockScalingX:true,lockScalingY:true,top:30,left:30});
canvas.add(txt);
```
https://jsfiddle.net/vital_n/205n1qfe/1/

Mouse over any of the corner controls, see the "resize" cursor hiniting that the resize is available.

*Expecting result*
There shouldn't be a resize cursor over a control when the scale of the object  is locked.

**Comment by asturur** [comment]
Yes you are right, cursor should not appear as resize.
You should consider disabling the corners completely if you do not intend to scale the object nor on X or Y.

**Comment by vitalniko** [comment]
Yes i tried to disable he controls but  the frame  looks more elegant with corners )

**Comment by asturur** [comment]
will give a check for custom corner icons on control customization
