### ISSUE TITLE
Textbox alignment and textdecoration out of sync

### ISSUE THREAD

**Issue by marcovdijk** [kangax/fabric.js#2355]
I have found a small bug related to text alignment and text decoration when using a textbox (merged from this [pull request](https://github.com/kangax/fabric.js/pull/2237) by @inssein, thanks btw, great feature! ). When you align the text to center or right and have text decoration like underline the text decoration is drawn on the wrong position. I've been looking at the code but can't find the direct cause. Example: [jsFiddle](https://jsfiddle.net/b6a3gpx7/3/).

**Comment by asturur** [comment]
we are taking care in #2354.

the text decoration issue came out after the opacity fix recently.

**Comment by marcovdijk** [comment]
Thanks for the quick response. I'll close this issue.
