### ISSUE TITLE
SVG Parse Problem

### ISSUE THREAD

**Issue by MariusTurcu** [kangax/fabric.js#2357]
Hi, 
I made some test on the http://fabricjs.com/kitchensink/ .
If i save the design i made as an svg when I load the svg generated by fabricjs i seems everythink is wrong.
I used canvas,toSVG() for save the svg.
I'm doing something wrong? I need to  use this feature in my project and i need to know if is working.
Thanks

**Comment by asturur** [comment]
load the svg as grouped.

or 

if you need to restore canvas design completely use toObject and fromObject methods.
