### ISSUE TITLE
hoverCursor overrided by "move" cursor on click and drag

### ISSUE THREAD

**Issue by nodegin** [kangax/fabric.js#2360]
```coffee
c = new fabric.Circle { radius: 16, fill: 'rgba(255, 255, 255, .4)', left: cx - 8, top: cy - 8, opacity: .5 }
c.hasControls = c.hasBorders = no
c.lockMovementX = c.lockMovementY = yes
c.hoverCursor = 'default'
@canvas.add c
```

It will add a circle with "default" cursor, but if I click on it and try to drag

the cursor will become "move"? How can I fix that

**Comment by asturur** [comment]
That is default behavour, drag cursor on fabricJs is not customizable.

**Comment by nodegin** [comment]
Is it due to browser limitation or something else? It just looks odd since
I have locked the X, Y movement, it would be nice if there's a new feature
to customize the hover cursor, thanks.

**Comment by asturur** [comment]
i marked as possible feature indeed.
I'm releaseing a little bit of fixes here and there.
I will release 1.6.1 and then i will work on control customization, in that part there may be also cursor customization.

**Comment by nodegin** [comment]
Sounds good👍

**Comment by asturur** [comment]
I understad that bad.
Because i did not read the code ( specify pleaseeee )
You meant that if the object is **LOCKED** the cursor should not change to moveCursor, because is not gonna move.
And  that is good.

**Comment by nodegin** [comment]
Yes, when you locked the movement of the object and try to drag it (just
mousedown & mousemove) and you will see the defined cursor are overridden
by the "hand".
