### ISSUE TITLE
Bounding box position breaks on canvas mouse up

### ISSUE THREAD

**Issue by sibbaldl** [kangax/fabric.js#2361]
Hi everyone

Cross posting this here from google groups for extra coverage:

https://jsfiddle.net/sibbaldl/uutL3oje/

There's some instructions in the Fiddle JS but in a nutshell, if we draw a doodle on to a canvas, group the individual paths, and then set active the group, everything seems fine. We can move the paths around as a single group. However, if we then click away from the object so that it is deselected, the bounding box position remains in the correct location but the actual path group itself jumps to a bottom right offset. 
I've tried adjusting the grouping code to see if I could affect the outcome but nothing really makes much difference - I thought setCoords() might be responsible but removing it doesn't help.

Note that in 1.6RC1 the paths actually disappear rather than be shown at an offset (unless the offset is absolutely miles away and I just can't see it).

[EDIT] Changing setActiveGroup() to setActiveObject() appears to avoid the issue with the bounding box, suggesting this is where the possible bug lies
Any help gratefully received

Cheers

Lee

**Comment by asturur** [comment]
setActiveGroup and activeObject are two differents things.

check this file to see how fabric handle creation of active group
https://github.com/kangax/fabric.js/blob/master/src/mixins/canvas_grouping.mixin.js

Just to clarify:
An active object is a selected object, a group set as active Object is a selected broup.

An activeGroup is a group created by selection and that can be updated with the addition or removal of object by mouse click.
I do not even know if there a good supported way to replicate this structure by code.

**Comment by sibbaldl** [comment]
Ah, ok, wow I totally misunderstood the meaning of setActiveGroup. Perhaps an issue of semantics as well but regardless I appreciate the feedback, thanks :)
I'll close this off since my only aim here is to group paths in to a single grouped object.
