### ISSUE TITLE
missing svg shadow description for pathGroups (toSVG)

### ISSUE THREAD

**Issue by MohamedElamry** [kangax/fabric.js#2363]
1. Load some svg files into canvas
2. Apply some effects like shadow on them.
3. Export to svg using canvas.toSVG()
4. Open the resulted svg in browser or editor.
Result:
1. Objects without shadows are visible.
2. Objects with shadow disappear even though they exist in svg source.

see http://jsfiddle.net/Rafie/29n4zo54/

**Comment by asturur** [comment]
it looks like you are the first one that put a shadow on a pathgroup.
Effectively the pathgroup get exported with a filter = "shadow" prodperty, but that filter does not get created.
A bug.

**Comment by MohamedElamry** [comment]
I found the same happen if I apply shadow to image objects too.

**Comment by MohamedElamry** [comment]
I checked the code and found that _createBaseSVGMarkup() is not called inside toSVG() in either path-group nor image classes.

I'm working on a pull request now but not sure if my changes will have side effects or not.

**Comment by asturur** [comment]
Do not worry, it is missing for group, path-group and image.
I'm gonna do that now.
