### ISSUE TITLE
No shadow in Free drawing mode

### ISSUE THREAD

**Issue by DanieleSassoli** [kangax/fabric.js#2367]
Hi,
I'm trying to add shadows in free drawing mode, I wanted to see how it worked in one of the demos, so iI opened the free drawing demo and started drawing a bit after setting the shadow, but no shadows appear. [This](http://fabricjs.com/freedrawing/) is the demo I used,  I'm getting something wrong or is this a bug?

**Comment by asturur** [comment]
i checked demo code and looks like it is not using the
brush.setShadow(options) method.

it is populating the properties directly but the brush class does not uses them.


please check the src/pencil/basebrush.class 

there is a setShadow method that should work.

**Comment by asturur** [comment]
i confirm you the shadow freedrawing is working in kitchensink.
The demo you linked is old probably and needs an update.

**Comment by DanieleSassoli** [comment]
Hi, yes it's working in kitchensink, thank's for pointing it out to me.
