### ISSUE TITLE
Hover Cursor - When outside of canvas clipTo

### ISSUE THREAD

**Issue by inssein** [kangax/fabric.js#2372]
Does it make sense that findTarget() is able to find targets outside of the Canvas' clipTo area? It currently does that, which also means that its found in the mouseMove which take care of applying hover cursors.

Problem: I currently have a canvas that has a clipTo applied so that the rendering area has a margin (for customized object controls). However, mouse moves in this blank area are causing the mouse cursor to change.

**Comment by inssein** [comment]
Anyways, not sure if this functionality is suitable for fabric.js, but my own Canvas class has 4 margin variables (left, top, right, bottom) that I use for clipping the canvas. I extended _checkTarget to ensure pointer is within margins, and it works for me.

I could submit a PR, but I don't think this will be useful for anyone else.

**Comment by kangax** [comment]
Yeah, this is desired behavior. Clipping only influences visibility, so the objecs are still technically behind and so are their controls (together with appropriate cursor changes). We even have a way to display controls above clipping area.
