### ISSUE TITLE
Textbox style not preserved when converted to svg

### ISSUE THREAD

**Issue by mochidusk** [kangax/fabric.js#2375]
![1](https://cloud.githubusercontent.com/assets/6126638/8971963/73669104-360a-11e5-9e74-7eaedeca449b.png) Figure 1. Canvas

![2](https://cloud.githubusercontent.com/assets/6126638/8971973/831ed804-360a-11e5-8805-20a56d31f9f9.png) Figure 2. SVG

When converting to svg the text styles are ignored. In the example I set bold, change font family and font size of the word "superfluous" but it still retains Courier font family and font size 13 (default values I passed in to Textbox). Not shown in this example, if text is set to justify, the svg is still aligned left.

**Comment by azeemgujjar** [comment]
issue closed without solving your problem? strange
