### ISSUE TITLE
object:modified not firing when dragged to the same x/y point

### ISSUE THREAD

**Issue by onassar** [kangax/fabric.js#2377]
Not sure if this belongs here, but I'd love a way to ensure the `object:modified` event fires when an object is dragged to the exact same point.

At the moment, it doesn't, which makes it difficult to run code after an object has been dragged, regardless of whether it's in the same position from where it started.

**Comment by kangax** [comment]
There's frequent events like object:moving that should be easy to use for this. object:modified is meant to check initial and final states for any differences, so naturally, if it was returned to the same position, it's like nothing changed.

**Comment by onassar** [comment]
Okay thanks @kangax
Forced to rely on `this.canvas.on('mouse:move', ...)`, but it works well-enough (albeit likely not great on performance)
