### ISSUE TITLE
Grouped path object does not maintain position when exported to JSON and imported 

### ISSUE THREAD

**Issue by sibbaldl** [kangax/fabric.js#2379]
So I seem to have all kinds of problems with grouping paths in to a single object, then exporting, then importing (imagine a drawing app that can save/load drawings).

here's a fiddle: https://jsfiddle.net/sibbaldl/4pb6hnvk/1/

if you draw a doodle using more than one path, then export and import, the positions are all over the place. 

Anyone got any thoughts on this?

Cheers! :)

**Comment by asturur** [comment]
This is a bug of 1.5.0 that we solved with the help of @sapics.
Please see your fiddle with the updated library that is working normally.
If you use 1.6.0rc you should be ok.

https://jsfiddle.net/4pb6hnvk/3/

I have placed a copy of library on a server that has certificate issue on https, so please, open the link of external resource and allow your browser to load content from there, then reload the fiddle.
To me it works fine.

If you manage to make it works, please close the issue.

**Comment by sibbaldl** [comment]
Hey, thanks for the super fast reply! I did a quick check on my iPad and it appeared to work fine but will have a closer look tomorrow and close this off if it works.

Thanks a million, guys!

**Comment by sibbaldl** [comment]
Yep, works great using RC1 - top work chaps (Y)
