### ISSUE TITLE
Text box is entering into edit mode when clicked/touched on any of the re-size controls

### ISSUE THREAD

**Issue by sudheer496** [kangax/fabric.js#2380]
Hi,

Observed that upon click/touch of any re-size controls , text box is going into edit mode.
Its not a major one but good to be fixed.
I have captured this here.
http://goo.gl/OdgtxY

Thanks
Sudheer

**Comment by asturur** [comment]
@kangax should this considered a bug or a possible feature?
is just about how we intend the controls to behave.
similar to #1570 when small objects come into play.

If the text object is really small, then i have difficulties to click it inside.

**Comment by kangax** [comment]
I think it's a bug. Controls should be for rotating/resizing not entering editing.

**Comment by sudheer496** [comment]
Thanks..
