### ISSUE TITLE
fabric.loadSVGFromURL Undefined object

### ISSUE THREAD

**Issue by NistorCristian** [kangax/fabric.js#2384]
I'm trying to propery load a SVG into canvas. The SVG is loaded and it is on canvas but if I do a console.log(canvas.item(0)) I get undefined.

`var canvas = new fabric.Canvas('canvasWorld');
	fabric.loadSVGFromURL('type.svg', function(objects, options) {

	var loadedObject = fabric.util.groupSVGElements(objects, options);

		loadedObject.set({
			left: 20,
			top: 20,
		})
		.setCoords();
		canvas.add(loadedObject);
                canvas.renderAll();
	});

	console.log(canvas.item(0));`
Am I missing something?

**Comment by asturur** [comment]
the async type of loadsvg.

please put console.log() inside the callback of loadsvg.

**Comment by NistorCristian** [comment]
I get the object if I put console.log() inside fabric.loadSVGFromURL. Bu what should I do ?

**Comment by serkyen** [comment]
I am having this same problem. How can we wait for the value and get it from outside the callback?
