### ISSUE TITLE
Pixelate leaves strange blue/Other issues

### ISSUE THREAD

**Issue by LIDJungle** [kangax/fabric.js#2385]
I am working on a project where I need to scale up low resolution images created with Fabric.

I am converting the text to images and then trying to use the Pixelate filter to give me a "pixel by pixel" representation of how the text will look.

At certain blocksizes, I get blue artifacts from pixelating white text. There are also many times where I get the "end" of the image cut off on the right and moved to the left side of my text and seen in the red presentation linked.

In the linked examples, the factor for zoom was "10". Blocksize should have been 2.5. Anything I can check to try and fix this?

![88](https://cloud.githubusercontent.com/assets/5067415/9065256/92063afe-3a9e-11e5-992e-708c5894491e.png)

![js](https://cloud.githubusercontent.com/assets/5067415/9065264/9bb8e0ce-3a9e-11e5-95bf-73c2957935b6.png)

    my.zoom = function (factor, canvas) {
        canvas.imageSmoothingEnabled = false;
        var filter = new fabric.Image.filters.Pixelate({
            blocksize: (factor / 4)
        });
        canvas.setHeight(canvas.getHeight() * factor);
        canvas.setWidth(canvas.getWidth() * factor);
        if (canvas.backgroundImage) {
            // Need to scale background images as well
            var bi = canvas.backgroundImage;
            bi.width = bi.width * factor; bi.height = bi.height * factor;
        }
        var objects = canvas.getObjects();
        for (var i in objects) {
            var scaleX = objects[i].scaleX;
            var scaleY = objects[i].scaleY;
            var left = objects[i].left;
            var top = objects[i].top;

            var tempScaleX = scaleX * factor;
            var tempScaleY = scaleY * factor;
            var tempLeft = left * factor;
            var tempTop = top * factor;

            objects[i].scaleX = tempScaleX;
            objects[i].scaleY = tempScaleY;
            objects[i].left = tempLeft;
            objects[i].top = tempTop;
            objects[i].setCoords();

            if (objects[i].type == 'i-text') {
                console.log("We have found a text object.");
                objects[i].cloneAsImage(function (clone) {
                    console.log("New Image", clone);
                    clone.set({
                        left: objects[i].left,
                        top: objects[i].top
                    });

                    clone.filters.push(filter);
                    clone.applyFilters(canvas.renderAll.bind(canvas));
                    canvas.add(clone);

                    canvas.remove(objects[i]);
                    canvas.renderAll.bind(canvas);
                });
            }
        }
        canvas.renderAll();
    }

**Comment by asturur** [comment]
blocksize needs to be an integer. it cannot be 2.5
If is not integer, the rgba pixels can finish in wrong place i suppose.
( red value in green place, or alpha value in blue place  and so on)
