### ISSUE TITLE
Characters disappear when resizing object

### ISSUE THREAD

**Issue by Faradey** [kangax/fabric.js#2391]
Browser: Google Chrome ver. 44.0.2403.130 m (64-bit)
OS: Windows 8
Font: BickhamScriptTwo.ttf - https://drive.google.com/file/d/0BwcWF1RzBeJVejZzS3FBS19remc/view?usp=sharing

Video: https://drive.google.com/file/d/0BwcWF1RzBeJVbVgzcHpTOFNLTVE/view?usp=drivesdk

JsFiddle: http://jsfiddle.net/Faradey/thh0g4oq/16/embedded/result/

**Comment by asturur** [comment]
Please provide font file and replicate in a jsfiddle.
Thanks.

**Comment by Faradey** [comment]
I added a link to the font and jsfiddle

**Comment by asturur** [comment]
http://wedindiy.tt/uploads/designs/fonts/BickhamScriptTwo.otf

Font fle not downloadable.

**Comment by Faradey** [comment]
http://jsfiddle.net/Faradey/thh0g4oq/15/embedded/result/ - normal downloaded

**Comment by asturur** [comment]
![image](https://cloud.githubusercontent.com/assets/1194048/9133597/42163fa6-3cfd-11e5-92b4-56d3b6ffedf1.png)

is this the font?

![image](https://cloud.githubusercontent.com/assets/1194048/9133607/51994b6c-3cfd-11e5-85ec-126beb1b574b.png)

i cannot reach it.

**Comment by Faradey** [comment]
I'm sorry. Fixed Now
http://jsfiddle.net/Faradey/thh0g4oq/16/embedded/result/

**Comment by asturur** [comment]
Cannot reproduce on Firefox, Chrome and IE.
Can you give more detail on how to make the bug happen?

**Comment by Faradey** [comment]
I, too, is normal in Firefox and IE, but Chrome's exactly as video and jsfiddle too. Which parameters to provide more?

**Comment by asturur** [comment]
chrome version and operaitng system

2015-08-07 12:23 GMT+02:00 Faradey <notifications@github.com>:

**Comment by Faradey** [comment]
Browser: Google Chrome ver. 44.0.2403.130 m (64-bit)
OS: Windows 8

**Comment by asturur** [comment]
I installed chrome 64 bit on windows 7 just for checking and still i cannot reproduce.
It may be a specific bug of your video card driver / situation.

Could you start a private chrome session with acceleration disabled, just to check? i do not think this is something we can solve.

**Comment by asturur** [comment]
Ok sorry i can confirm is an hardware acceleration issue on chrome 64bit.
At least on my intel integrated hardware.
i think we should close, you should open a ticket on chrome bug tracker.

**Comment by Faradey** [comment]
Thank you for your help
