### ISSUE TITLE
Overlay image changes when drag selecting

### ISSUE THREAD

**Issue by thejsn** [kangax/fabric.js#2392]
If you have an overlay image and start a drag selection anywhere on the canvas then it looks like the overlay image gets duplicated.

This seems to happen in all browsers and with any image, fabricjs version 1.5.0.

Here is an example: http://jsfiddle.net/d4nmpg2h/

Probably the same issue: https://groups.google.com/forum/#!searchin/fabricjs/overlay/fabricjs/zhU-mo5dpbY/xfOlAefDWQgJ

**Comment by asturur** [comment]
nice find.

**Comment by asturur** [comment]
```diff
    renderTop: function () {
      var ctx = this.contextTop || this.contextContainer;
      this.clearContext(ctx);

      // we render the top context - last object
      if (this.selection && this._groupSelector) {
        this._drawSelection();
      }

      // delegate rendering to group selection if one exists
      // used for drawing selection borders/controls
      var activeGroup = this.getActiveGroup();
      if (activeGroup) {
        activeGroup.render(ctx);
      }

+      this._renderOverlay(ctx);

      this.fire('after:render');

      return this;
    },
```

When we drag selection we call renderTop.
In renderTop we could be rendering again the activeGroup and for that reason we repaint over also the overlay image otherways the activeGroup would pop out.

One solution could be putting the overlayImage in the same "if" condition of activeGroup.
I'm  asking myself why we repaint the activeGroup.

But this solution would not solve the problem when the active group is present.

@kangax this is an old bug from 2013 already checked by @Kienz, do you have any idea?

**Comment by asturur** [comment]
I checked all past commits of static_cavans.class.js.

In first place renderAll was drawing activeGroup always on the contextTop.

Later the ```ctx = contextTop || contextContainter``` has been introduced and active group went on the lowercanvas.

renderTop staied the same with the activeGroup reRendered on the top canvas.

Then this commit from @kangax added the overlayImage re rendering:

**Comment by kangax** [comment]
@asturur I think you're right about it being unnecessary and I noticed this re-re-rendering before as well. Don't recall why I added that line, but probably safe to remove it now.

**Comment by asturur** [comment]
because overlayImage was on uppercanvas for a long time.

then you moved on lowercanvas probably to fix the canvas.ToDataURL not reproducing it.

there is a pr already for this, where i wanted to writedown reason for this deleting.

i ll do anyway as soon as i find time.
