### ISSUE TITLE
IText Clone object, pass reference to style object instead of cloning it.

### ISSUE THREAD

**Issue by rijint** [kangax/fabric.js#2396]
1) Add an IText with some initial text eg:-sample, delete all characters(sample) using delete key/backspace key  type new content (eg:-mytext).
    
2) Take clone of edited IText
3) Update color of single character the changes reflected to parent also
    change the color by selecting "my" in mytext

**Comment by asturur** [comment]
please post a fiddle, help us checking the bugs faster.

**Comment by rijint** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7856892/9150021/8e3cb4ec-3de2-11e5-804e-ec2198533cad.png)
screenshot

**Comment by asturur** [comment]
Can you show us how you clone the itext? otherways is not possible to help you.

**Comment by rijint** [comment]
var obj = canvas1.getActiveObject();

            obj.clone(function (res) {
                res.set({
                    left: 200,
                    top: 100
                });
                canvas1.add(clone);
            });

**Comment by rihanrahul** [comment]
Here is the fiddle... http://jsfiddle.net/rihanrahul/6zmu0zce/

Please follow the steps mentioned above to reproduce the issue.

**Comment by asturur** [comment]
changing the util.extend function with something like this solve the problem 

I m really not able to identify potential drawbacks here,
need @kangax help here. :)

```
  function extend(destination, source) {
    // JScript DontEnum bug is not taken care of
    for (var property in source) {
      var _source = source[property];
      if( Object.prototype.toString.call(_source) === '[object Array]' ) {
        destination[property] = extend([ ], _source);
      }
      else if (_source && typeof _source === 'object'){
        destination[property] = extend({ }, _source );
      }
      else {
        destination[property] = _source;
      }
    }
    return destination;
  }
```
