### ISSUE TITLE
Default Object OriginX/OriginY documentation is incorrect

### ISSUE THREAD

**Issue by jeffkillian** [kangax/fabric.js#2403]
A change was done to [change the default object orientation to left/top from center center](https://github.com/kangax/fabric.js/commit/330784ac2c7297cd34c2c7fbe6ea69c8079b9e85). However, the documentation still states:
> Left position of an object. Note that by default it's relative to object **center**. You can change this by 
> setting originX={left/center/right}

The documentation should indicate that it is relative to left of object by default, rather than center.

**Comment by kangax** [comment]
Closed in #2404
