### ISSUE TITLE
Input Vertical font for Itext

### ISSUE THREAD

**Issue by lxYang** [kangax/fabric.js#2408]
Hi.

How can i get actual vertical text and not the rotated text,i shown below.

V      t
e      e 
r       s
t       t
i       t
c      e
a     s
l      t

t   
e
x
t

Edit-model is from top to bottom for Itext.
Please Help. Thanks!

yang

**Comment by kangax** [comment]
Vertical text is not supported at the moment.

**Comment by BhuvaneshwaranR** [comment]
Hi @kangax ,
           Is there any update on vertical text?
