### ISSUE TITLE
loadSVGFromURL breaks when SVG contains namespaced elements

### ISSUE THREAD

**Issue by PaRoxUs** [kangax/fabric.js#2412]
As a result if you try to load a SVG that contains namespaces the loadSVGFromURL breaks without giving any error. 

For example I found my SVG file polluted with sodipodi:nodetypes="cc" and inkscape:connector-curvature="0" and as a result the callback function did't even get executed.

fabric.loadSVGFromURL('svg.svg', function(objects, options) {
     console.log(objects, options);
     var obj = fabric.util.groupSVGElements(objects, options);
     canvas.add(obj);
});

**Comment by asturur** [comment]
Please provide svg file.

**Comment by PaRoxUs** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 16.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="-123.3 -12.9 1024 1024" enable-background="new -123.3 -12.9 1024 1024">
       <path id="path3037" sodipodi:cy="261.60583" sodipodi:cx="252.26277" sodipodi:arg1="0.52662727" sodipodi:r2="139.41531" sodipodi:r1="278.83063" sodipodi:type="star" sodipodi:sides="3" display="inline" d="
						M875.248,160.379c-1.941,3.34-36.478,3.352-38.399,0c-1.922-3.352,15.359-33.28,19.2-33.28
						C859.889,127.1,877.19,157.04,875.248,160.379z"/>
</svg>
```

**Comment by asturur** [comment]
The svg is not correct and cannot be parsed.
The namespace sodipodi is missing.

This svg should have this attribute in svg tag:
```
xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
```
otherways is not valid.
