### ISSUE TITLE
__onMouseDown expects middle button instead of left

### ISSUE THREAD

**Issue by gsrtergdrtsrsf0** [kangax/fabric.js#2420]
In canvas_events.mixin.js, in __onMouseDown, there is the following line:
`var isLeftClick  = 'which' in e ? e.which === 1 : e.button === 1;`
According to https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button, e.button being 1 usually means middle click. This probably hasn't been noticed because most browsers support (the apparently non-standard) e.which.

**Comment by asturur** [comment]
yes you are right. e.button is 0 on left click.
