### ISSUE TITLE
Set rotation point around corner

### ISSUE THREAD

**Issue by ankitshah-hs** [kangax/fabric.js#2421]
Hello,

I have tried to customize default rotation point around the corner. I set a rotation point +10 from tr.x point and -3 from tr.y location. When I rotate the object, then x and y coordinates of the tr is changed. So when I add +10 to tr.x and -3 to tr.y the location of the new rotate point is changed. 

Is it possible to set the rotation point at same location when object is rotate? I want to set rotation point to all 4 corner.

Here I have attached image before and after the rotation.
![2015-08-13_20-03-46](https://cloud.githubusercontent.com/assets/13797072/9273569/5ec2a87a-42ab-11e5-8347-83026202c676.png)
![2015-08-13_20-06-24](https://cloud.githubusercontent.com/assets/13797072/9273570/5f2bec04-42ab-11e5-9c4f-3315efadb466.png)

**Comment by ankitshah-hs** [comment]
I have changed some functionality in core library but it's not work for me.

trr = new fabric.Point(tr.x + cosTh * 18, tr.y + sinTh * 20); //right

this.oCoords = {
                // corners
                tl: tl, tr: tr, br: br, bl: bl,
                // middle
                ml: ml, mt: mt, mr: mr, mb: mb,
                // rotating point
                mtr: mtr, trr: trr
            }; 


 _findTargetCorner: function (pointer) {
            if (!this.hasControls || !this.active) {
                return false;
            }

            var ex = pointer.x,
				ey = pointer.y,
				xPoints,
				lines;

            for (var i in this.oCoords) {

                if (!this.isControlVisible(i)) {
                    continue;
                }

                if (i === 'mtr' && !this.hasRotatingPoint) {
                    continue;
                }

                // Custom - For rotation right corner
                if (i === 'trr' && !this.hasRotatingPoint) {
                    continue;
                }

                if (this.get('lockUniScaling') &&
				   (i === 'mt' || i === 'mr' || i === 'mb' || i === 'ml')) {
                    continue;
                }

                lines = this._getImageLines(this.oCoords[i].corner);

               xPoints = this._findCrossPoints({ x: ex, y: ey }, lines);
                if (xPoints !== 0 && xPoints % 2 === 1) {
                    this.__corner = i;
                    return i;
                }
            }
            return false;
        },



_getControlsVisibility: function () {
            if (!this._controlsVisibility) {
                this._controlsVisibility = {
                    tl: true,
                    tr: true,
                    br: true,
                    bl: true,
                    ml: true,
                    mt: true,
                    mr: true,
                    mb: true,
                    mtr: true,
                    trr: true
                  };
            }
            return this._controlsVisibility;
        }



 _getActionFromCorner: function (target, corner) {
            var action = 'drag';
            if (corner) {
                action = (corner === 'ml' || corner === 'mr')
				  ? 'scaleX'
				  : (corner === 'mt' || corner === 'mb')
					? 'scaleY'
					: (corner === 'mtr' || corner === "trr")
					  ? 'rotate'
					  : 'scale';
            }
            return action;
        },



_setCornerCursor: function (corner, target) {
            console.log(target.oCoords.tr.x);
            if (target.oCoords.tr.x > 0 && target.oCoords.tr.x < 21 && target.oCoords.tr.y < -21) {
                corner.log("inside")
            }
            if (corner in cursorOffset) {
                this.setCursor(this._getRotatedCornerCursor(corner, target));
            }
            else if (corner === 'mtr' && target.hasRotatingPoint) {
                this.setCursor(this.rotationCursor);
            }
            else if (corner === 'trr' && target.hasRotatingPoint) {
                this.setCursor(this.rotationCursor);
            }
           else {
                this.setCursor(this.defaultCursor);
                return false;
            }

        },

**Comment by asturur** [comment]
Use google group for generic question.
Open issues only for current problems / bug in library.
