### ISSUE TITLE
Image resize not working in IE11 

### ISSUE THREAD

**Issue by alrazamc** [kangax/fabric.js#2422]
var newImage = new fabric.Image(img, {
            width: 80,
            height: 80,
            left: 0,
            top:0
        });

image is not resized in IE11 but works in chrome.

tried to resize after add into canvas but still doesn't work

**Comment by asturur** [comment]
Please provide a fiddle with this code setup.
We will test in IE11 and chrome.

**Comment by alrazamc** [comment]
asturur , thanks for reply

http://test.jcatpk.com

Implemented the drage and drop via modernizr.min.js
when I drop a shape in chrome, it is resized to 80 * 80 as programmed but its not working in IE 11

**Comment by asturur** [comment]
we need a test case with minimal code, on jsfiddle.
