### ISSUE TITLE
Problem with zoom and scale

### ISSUE THREAD

**Issue by Envo** [kangax/fabric.js#2425]
Hi there,

I have a little problem with the zoom functionality, and i don't see where i miss the point. Can anyone solved this before?
Video about the effect (look at the scale borders): https://www.youtube.com/watch?v=0QBtZF8szOE

And a code which i use:
```javascript
zoom: function(factor) {
	designer.ctx.setHeight(designer.ctx.getHeight() * factor);
	designer.ctx.setWidth(designer.ctx.getWidth() * factor);
	if (designer.ctx.backgroundImage) {
		var bi = designer.ctx.backgroundImage;
		bi.width = bi.width * factor;
		bi.height = bi.height * factor;
	}
	var objects = designer.ctx.getObjects();
	for (var i in objects) {
		var scaleX = objects[i].scaleX,
			scaleY = objects[i].scaleY,
			left = objects[i].left,
			top = objects[i].top,
			width = objects[i].width,
			height = objects[i].height;
					
		var tempScaleX = scaleX * factor,
			tempScaleY = scaleY * factor,
			tempLeft = left * factor,
			tempTop = top * factor;

		objects[i].scaleX = tempScaleX;
		objects[i].scaleY = tempScaleY;
		objects[i].left = tempLeft;
		objects[i].top = tempTop;
		objects[i].setCoords();
	}
	designer.ctx.calcOffset();
	designer.ctx.renderAll();
}
```

**Comment by asturur** [comment]
Please try to use fabricjs own zoom functions:

canvas.setZoom(x) 

We cannot support custom zooming function when there is one built in.

**Comment by Envo** [comment]
I tried that too, but gives me the same result.

**Comment by asturur** [comment]
please share a fiddle that demonstrate the problem.

**Comment by Envo** [comment]
hm, seems working here: https://jsfiddle.net/Envo/tdzoygc4/10/
But i don't get it why it doesn't work under my project... :-/ The scale borders still stays at the original place.
