### ISSUE TITLE
Clone selection objects after selection cleared

### ISSUE THREAD

**Issue by alghraibeh** [kangax/fabric.js#2426]
Hello ,
I have problem when select more than one object as you see in image 
![untitled-2](https://cloud.githubusercontent.com/assets/9897827/9324099/bde51aea-458f-11e5-8219-9d485f9c534f.png)

and after cleared selection it is make clone of objects like this
![untitled-4](https://cloud.githubusercontent.com/assets/9897827/9324134/1b8f3bbc-4590-11e5-820d-82d7b9fdd7a2.png)

Note :do this step :
1- select more than one object.
2-then move objects together .
3-then click on empty area to clear selection .
4-then click on one of selected object and move it .

Then you will the problem .

thank you ..

**Comment by asturur** [comment]
Create a jsFiddle or the issue will bi closed.

**Comment by alghraibeh** [comment]
This problem appear on my project just ,
