### ISSUE TITLE
Need contrast filter

### ISSUE THREAD

**Issue by armsmani** [kangax/fabric.js#2431]
Hi fabricjs Team,

Is it possible to add contrast filter function in fabricjs. it will help me lot..

**Comment by kangax** [comment]
Should be easy to roll your own using something like this, for example http://www.dfstudios.co.uk/articles/programming/image-programming-algorithms/image-processing-algorithms-part-5-contrast-adjustment/

**Comment by armsmani** [comment]
thank you kangax
