### ISSUE TITLE
Image added to canvas disappears on click

### ISSUE THREAD

**Issue by krusk** [kangax/fabric.js#2433]
Hi all,

I am using the following to add an image from my computer to a fabric.js canvas. It loads the image onto the canvas, but once I click on the image to resize or move, the image disappears.

HTML:
  
     <input type="file" id="imageLoader" name="imageLoader" />

JS:

      var canvas = new fabric.Canvas('c');
      
        var imageLoader = document.getElementById('imageLoader');
        imageLoader.addEventListener('change', handleImage, false);
        var ctx = canvas.getContext('2d');

        function handleImage(e) {
            var reader = new FileReader();
            reader.onload = function (event) {
                var imgAdd = new Image();
                imgAdd.onload = function () {
                    canvas.width = imgAdd.width;
                    canvas.height = imgAdd.height;
                    ctx.drawImage(imgAdd, 0, 0);
                }
                imgAdd.src = event.target.result;
            }
            reader.readAsDataURL(e.target.files[0]);
        }

**Comment by asturur** [comment]
https://jsfiddle.net/rw0thvjg/

**Comment by krusk** [comment]
Very helpful and I see where I need to leverage fabrics' canvas.add
