### ISSUE TITLE
Fabric.Image object with stroke and shadow renders strangely.

### ISSUE THREAD

**Issue by acharris22306** [kangax/fabric.js#2436]
First, thank you for creating such a useful API for the HTML5 <canvas> element. It has really made life easier.

My concern is that when I insert an image onto the canvas with 
````javascript
fabric.Image.fromURL( ... )
````

and later add a stroke and shadow, the result looks like the following:

![unknown](https://cloud.githubusercontent.com/assets/12211559/9412519/1bbd5e04-47fa-11e5-862d-0840ebc9ad89.png)
where the blue is the stroke and the red is the shadow. It seems like the stroke is casting a shadow over the image. Is this the intended effect? Here is the function I call to add an image to the canvas:

````javascript
function insertImgOnCanvas(imgUrl){
  fabric.Image.fromURL(imgUrl, function(oImg) {
	  oImg.set({
		left: mousePos.x,
		top: mousePos.y,
		strokeWidth: currentStrokeThickness, 
		strokeDashArray : currentStrokeStyle,
		stroke: currentStrokeColor,
		opacity: currentOpacity, 
		originX: "center", 
		originY: "center"
	  });
	  oImg.scaleToWidth(currentWidth);
	  oImg.setShadow({
		  color:	currentShadowColor,
		  blur:currentShadowBlur,
		  offsetX:currentShadowOffsetX,
		  offsetY:currentShadowOffsetY
	  });
	  canvas.add(oImg);
  });
  canvas.renderAll();	
  saveState(); //saves canvas object into Undo cache
}
````
I am currently using Fabric.js version 1.5.0

While this isn't more than a minor issue for me (users are unlikely to have both a shadow and stroke on an image in my application), the rendering does not appear to return what is expected.

Thank you for your help

**Comment by asturur** [comment]
Could you try to use the shadow property:
'affectStroke' and set to false?

I do not know if the image will cast shadow by herself.

We could consider stroking before filling, but then the shadow will be over the stroke.

**Comment by acharris22306** [comment]
Unfortunately, the 
````javascript
canvas.getActiveObject().shadow.affectStroke = false;
````

doesn't seem to solve the problem. 

Maybe something in the rest of my code is affecting it? The full application can be found at:

https://getunfused.com/tutoring.php

Thanks for the help.

**Comment by asturur** [comment]
![image](https://cloud.githubusercontent.com/assets/1194048/9421661/9c3a472c-4877-11e5-9d19-e03e86a18616.png)

Can you make it happen on kitchensink demo? for me is rendering fine.

**Comment by acharris22306** [comment]
it seems to be working fine in the kitchensink demo. maybe this is an issue with the version i am using. according to the source code , the demo uses version 1.6.0 rc1, which is newer than the version i am using:
````javascript
//version used in the demo:
var fabric = fabric || { version: "1.6.0-rc.1" };

//version I am using:
var fabric = fabric || {  version: "1.5.0" };
````

thanks for the help. it looks like the issue was fixed in the new release.

**Comment by saran110313** [comment]
I'm receiving this error originating from fabric.js

Uncaught TypeError: Cannot read property 'apply' of undefined

function klass() {
(ln: 1690) --> this.initialize.apply(this, arguments);
}

**Comment by saran110313** [comment]
Uncaught TypeError: url.indexOf is not a function

 if (url.indexOf('data') !== 0 && typeof crossOrigin !== 'undefined') {
        img.crossOrigin = crossOrigin;
      }
 this function error in fabric.js
Uncaught TypeError: url.indexOf is not a function
fabric.util.loadImage	  @fabric-1.16.0.js:617
fabric.Image.fromURL	@fabric-1.16.0.js:17798
addnewImage	@	board.js:151
addobjectoncanv	@	board.js:186
(anonymous function)	@	board.js:190
Emitter.emit	@	socket.io.js:1335
Socket.onevent	@	socket.io.js:879
Socket.onpacket	@	socket.io.js:837
(anonymous function)	@	socket.io.js:1197
Emitter.emit	@	socket.io.js:1335
Manager.ondecoded	@	socket.io.js:395
(anonymous function)	@	socket.io.js:1197
Emitter.emit	@	socket.io.js:1335
Decoder.add	@	socket.io.js:5967
Manager.ondata	@	socket.io.js:385
(anonymous function)	@	socket.io.js:1197
Emitter.emit	@	socket.io.js:1335
Socket.onPacket	@	socket.io.js:1955
(anonymous function)	@	socket.io.js:1773
Emitter.emit	@	socket.io.js:1335
Transport.onPacket	@	socket.io.js:2394
Transport.onData	@	socket.io.js:2386
ws.onmessage	@	socket.io.js:3453

**Comment by echo954** [comment]
Set the shadow's affectStroke member to true and you'll see the bug. It's rendering the stroke's shadow on top of the object.

**Comment by asturur** [comment]
yes with fabricjs we rende stroke and fill separately, and so on shadow will cover the other. That is why affect stroke is default to false.

**Comment by echo954** [comment]
So you're saying that this is the correct behavior? The only time that would be useful is if I have a transparent fill. 
![fabric stroke shadow](https://cloud.githubusercontent.com/assets/2278263/16524226/49190eca-3f75-11e6-8110-8defae42e66c.png)

**Comment by asturur** [comment]
is not "correct" is how canvas handles shadow. I really cannot do anything about it other that redoing all the rendering piepline.

**Comment by contact2mayurkukadiya** [comment]
I have also same problem. stroke shadow and object shadow both are show at a same time with same offsetX and offsetY, that's why this shadow look like this.
Can you please help me if possible (I am using fabric js version 1.7.22)

There is no shadow visible if fill color is transparent (I want shadow of stroke when object have transparent color). for that issue I apply one patch like below :

`fabric.Object.prototype._renderStroke = function (ctx) {
    if (!this.stroke || this.strokeWidth === 0) {
        return;
    }
    if (this.shadow && !this.shadow.affectStroke) {
        this._removeShadow(ctx);
    }
    ctx.save();
    // if (this.strokeUniform)
    ctx.scale(1 / this.scaleX, 1 / this.scaleY);
    this._setLineDash(ctx, this.strokeDashArray, this._renderDashedStroke);
    this._applyPatternGradientTransform(ctx, this.stroke);
    ctx.stroke();
    ctx.restore();
};`

After apply patch , when object have following property :

Stroke : 'black',
StrokeWidth: 10,
fill: '#ff000000',
shadow: {
      color: '#00ff00',
      blur: 10,
      offsetX: 10,
      offsetY: 10
}

my view like this :



But when set fill color it will look like this :
