### ISSUE TITLE
Add shadow support to groups

### ISSUE THREAD

**Issue by jrett** [kangax/fabric.js#2439]
Would it be doable to add shadow support to groups? From what I can tell this means only a couple of lines of code added to the group 'render' method.

**Comment by asturur** [comment]
i think we did already. what version are you using?

**Comment by jrett** [comment]
I'm using 1.5.0

**Comment by asturur** [comment]
can you try 1.6.0 rc1? i think it has group shadow support.

**Comment by asturur** [comment]
We added on 8 August, so you have to download and build latest fabricjs.
