### ISSUE TITLE
Exclude draw object from canvas object count

### ISSUE THREAD

**Issue by SpwebBindu** [kangax/fabric.js#2441]
Hey i am using fabric.js for my canvas application. now i want to track the count of every object i created on  canvas. like list all objects on canvas i created. but there is a problem i cant get tract of object which i draw because there is not any way to select draw object at once user complete his drawing and call canvas.renderAll() method. so i want to exclude these draw object from my count to get accurate listing count. is there any way to do that.pls help . Thanx in advance

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group — https://groups.google.com/forum/#!forum/fabricjs — where someone will usually assist you.

The issue tracker is only for bugs and feature requests.

Thanks for your understanding!
