### ISSUE TITLE
Image filter reloading slow on chrome 

### ISSUE THREAD

**Issue by JugnuPathak** [kangax/fabric.js#2442]
I have a check box for applying biur filter on image, but time taken for applying filter is increasing each time when you check or uncheck it.I have implemented it using demo shown at http://fabricjs.com/image-filters/  , where same issue already exists (code is also same) .

Do anybody have any idea about it??

Another issue is  im showing loader on check box's change and hiding it on applyfilers 's callback function, but loader is just showing for fraction of time and hiding quickly while process is running longer lets say 5-6 sec.

**Comment by asturur** [comment]
If you need support with custom code, please crate a working jsfiddle.

**Comment by JugnuPathak** [comment]
@asturur  code is same as on  http://fabricjs.com/image-filters/

**Comment by asturur** [comment]
You are linking: http://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.4.0/fabric.min.js
Please use latest fabric.js 1.6.0rc1 to open an issue.

**Comment by JugnuPathak** [comment]
@asturur  new fiddle with fabric version 1.6.0-rc.1 and jquery 2.1.4

**Comment by asturur** [comment]
Cannot get what is happening.
First execution of filter requires X millisecond,  the next one requires X*3 milliseconds ( more or less )

**Comment by JugnuPathak** [comment]
@asturur  any progress?

**Comment by asturur** [comment]
on a fast machine the time is X*10, so first execution is 90ms, second execution is 850ms. so strange.

**Comment by asturur** [comment]
http://jsfiddle.net/emeagcnx/5/

remove jquery code and added the important functions inside the fiddle, just to check them easily.
No clue.

**Comment by JugnuPathak** [comment]
@kangax please could you provide any help???

**Comment by asturur** [comment]
http://jsfiddle.net/asturur/emeagcnx/7/

updated fiddle to give it another shot.

**Comment by asturur** [comment]
![image](https://cloud.githubusercontent.com/assets/1194048/11239760/485b0224-8dee-11e5-9bfd-7e0830bed264.png)

so strange.

**Comment by kangax** [comment]
Hm, I don't see it being slow

**Comment by asturur** [comment]
Look at the graph, first execution is 80ms, second is 2000ms.
in my latest fiddle you should read the console.log for timings:

filter applied, time:123 (applied first time)
(index):60 filter applied, time:16 (removed)
(index):60 filter applied, time:1995 (applied)
(index):60 filter applied, time:15 (removed)
(index):60 filter applied, time:1990 (applied)
(index):60 filter applied, time:13 (removed)
(index):60 filter applied, time:1987 (applied)
(index):60 filter applied, time:15 (removed)
(index):60 filter applied, time:1989 (applied)

**Comment by kangax** [comment]
WebKit/Safari are good too; so this looks Chrome specific

**Comment by kangax** [comment]
@asturur have you tried regular image (not data url)?

**Comment by asturur** [comment]
i have so many crossorigin issue i cannot really test now. I'll see, now that firefox and safari are ok, i care less about this.

I thought it was some failing optimization because we read the image array jumping grom one row to another, but i do not get why it should get slower *AFTER* first time.

**Comment by JugnuPathak** [comment]
any update on this issue?

**Comment by asturur** [comment]
just updated, firefox still ok, chrome still broken.
I think i'm gonna open 3 bug issue on chrome this evening.

**Comment by abhi06991** [comment]
@asturur:
Has this bug been fixed? It happens in chrome only when we apply convolute filters like blur or sharpen
Firefox works like charm

**Comment by asturur** [comment]
i have no time to demonstrate the bug on chrome issue tracker. it does not look related to fabricjs.

**Comment by abhi06991** [comment]
It happens only with convolute filters type, rest other work absolutely fine in chrome.

**Comment by asturur** [comment]
http://jsfiddle.net/emeagcnx/13/
opened bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=648154&q=&sort=-modified%20id&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by asturur** [comment]
i close this. Is not our competence and we'll see if they can fix or not.
