### ISSUE TITLE
Bug when rendering jpg with mask

### ISSUE THREAD

**Issue by Exelicer** [kangax/fabric.js#2443]
Hi,

when I try to render a canvas as jpg with a svg mask inside I always get a black background. I guess it's a bug since nobody posted a solution in google groups and I also tested alot different settings.

https://groups.google.com/forum/#!topic/fabricjs/3skymk1lNJw

fabric.js 1.5.0

**Comment by asturur** [comment]
Please provide a jsfiddle with the necessary functionality to test code.
Also provide svg source.

**Comment by asturur** [comment]
https://github.com/kangax/fabric.js/issues/1153
Also check the modified fiddle in my last answer in this closed issue, to see if your problem is similar.

**Comment by Exelicer** [comment]
Thanks for your answer.

Already tested the fill option set to '' or 'none'. Didn't made any difference for me. I'll make an fiddle

**Comment by Exelicer** [comment]
I'ts really dirty code in fiddle but I hope it's ok for an example:
http://jsfiddle.net/avg9y0or/1/

**Comment by asturur** [comment]
I think is ok like it is.
If canvas has default pixel value of rgba(0,0,0,0) and nothing is filling the clipped pixels with anything else than rgba(0,0,0,0), when exporting to jpg, the alpha channel is lost and you get only rgb(0,0,0) that is black.

Do not know if we can consider this a bug.

**Comment by Exelicer** [comment]
But I set:
canvas.setBackgroundColor('#FFFFFF'); // Set a Backgroundcolor (Default is black)
canvas.renderAll();
right before rendeirng into a jpg to have a backgroundcolor. The red object is also in an white area in the jpg result. But the outer side of the mask keeps to be black

**Comment by Exelicer** [comment]
And when I switch to fabric 1.5.0 in fiddle is totaly broken, strange

**Comment by asturur** [comment]
But the background is clipped away by your canvas clipTo.
So that part of background does not get filled.

**Comment by Exelicer** [comment]
Shouldn't be there any option to set a default background color for cliped content?

**Comment by asturur** [comment]
there is an open PR marked as possible feature, code change is very simple, you can copy it in your application.
https://github.com/kangax/fabric.js/pull/1875/files


For the fiddle with 1.5.0, look here:
http://jsfiddle.net/avg9y0or/3/
Simply the loadsvg from string is async, so you should put the export part of the code in the callback, not in the normal execution of script.

**Comment by Exelicer** [comment]
Ah ok, I'll try it. Thank you!

Btw, have you changed anything in the fiddle 3? Don't see any difference

**Comment by Exelicer** [comment]
Is this feature already added to the 1.6.0 rc1?

**Comment by asturur** [comment]
no is not merged and maybe it won't.
In the fiddle i just moved the code inside the callback of loadsvgfrom string
