### ISSUE TITLE
Chrome 44.0.2403.157 (latest as of Aug 24, 2015) does not display path-groups loaded from JSON. Other browsers still work.

### ISSUE THREAD

**Issue by teewuane** [kangax/fabric.js#2444]
I have an app that allows a user to draw on a canvas. They draw their name on a canvas and click save. I call `toSVG()` on the canvas and take the svg string and store it in my database.

The user can then later add that SVG string to a new canvas, I call...

```
fabric.loadSVGFromString(svg_string, function(objects, options) {
    var group = new fabric.PathGroup(objects, options);
    canvas.add(group);
    canvas.calcOffset();
    canvas.renderAll();
    group.setCoords();
});
```

That adds the svg image to the canvas just fine and the type is 'path-group'.

Now when the user clicks 'save' I call `var my_string = canvas.toObject()`. Then I submit that json string to my server and save it with `JSON.stringify(my_string)`.

The SVG is now converted to JSON and I store that entire JSON string in a database.

I allow the user to come back and edit that canvas image again. I load the json string into the canvas with...

```
var json = my_string;
var serialized = (typeof json === 'string') ? JSON.parse(json) : json;
canvas.loadFromJSON(serialized, function(){
    canvas.renderAll.bind(canvas);
});
```

This worked just fine in Chrome until about three days ago. It will still load the images and text just fine and it even adds a 'path-group' object to the canvas. However, the path group does not display.

It will display in just fine in Safari and Firefox. (I haven't tested IE yet)

I was using Fabric 1.4.9 and now I've upgraded to 1.5.0 (just to see if it would fix the issue) then I upgraded to 1.6.0.rc1. It still will not work in Chrome but it will work in Safari and Firefox.

So it will read and parse the SVG and convert it to JSON then add it to the canvas just fine but when adding it from a JSON string it chokes.

Here is a [JSFiddle Example](http://jsfiddle.net/1nugvfz8/4/)

Open that link in Chrome and you'll see it won't display. Open it in Safari or Firefox and you'll see "Travis".

**Comment by asturur** [comment]
I still did not get that version on my pc. I will check as soon as it updates.

**Comment by asturur** [comment]
it is an hardware acceleration issue.
if you disable hardware acceleration it runs fine. Nothing we can fix here.
You should open a ticket on the chrome developer website.

**Comment by teewuane** [comment]
@asturur I just confirmed this. That is bizarre... Thanks for looking into it.

**Comment by teewuane** [comment]
I'm keeping an eye on the ticket I submitted with Chromium. What they discovered is that this is causing the problem... `"strokeDashArray": [null, null]` When you change it to.. `"strokeDashArray": [1, 0]` it fixes what is happening and the paths appear. So I'm going to detect that on my end but they also recognize that it shouldn't break just because hardware acceleration is running vs software acceleration.

**Comment by asturur** [comment]
and strokeDashArray : null, does it work?

**Comment by teewuane** [comment]
@asturur Setting it to `null` does work. I noticed by default that a `path-group` has `"strokeDashArray": null` and not `"strokeDashArray": [null, null]` like a 'path' object does.

**Comment by asturur** [comment]
correct default value is null, because we evaluate it and we do not set it.

probably array of null evaluates to true and we set a native method with strange values i do belive it may crash some implementation.

setting to array 1, 0 does work because you are painting a dashed array that looks like a full line, but wasting performance i think.

**Comment by teewuane** [comment]
Just did a quick test and you're right.

    var abc = [null, null];
    if (abc) {
        alert('hi');
    } // this will alert 'hi'. 

    var def = null;
    if (def) {
        alert('hello');
    } // this will obviously not alert 'hello'

So chrome is probably testing for `abc` if true, then do something with its items values?

When Chrome's hardware acceleration is enabled, then `[null, null]` is true, and when it is disabled, `[null, null]` is false. I'm going to test this in just a second (have to restart browser to disable hardware acceleration. Will update soon.)

For my solution, I'm just going to look for `"strokeDashArray": [null, null]` and change it to `"strokeDashArray": null`.

**Comment by asturur** [comment]
no simply we evaluate that and ask chrome to to a dashed stroke.
the hardware acceleration lib wants to do it and when it finds two null instead of 2 numbers it crashes.

i m just guessing of course.
