### ISSUE TITLE
zoomToPoint does not center correctly

### ISSUE THREAD

**Issue by tino** [kangax/fabric.js#2446]
The docs for zoomToPoint state: `Sets zoom level of this canvas instance, zoom centered around point`, but it does not do that.

See http://jsfiddle.net/qv989nzs/. The dot is not centered.

**Comment by spearson2010** [comment]
The size of your canvas also plays a role.  Your canvas is only 300 by 300, so you can't center on 100, 100 on a zoom level of 2.  If you zoom higher, you can tell that it eventually does center the zoom around 100,100.

**Comment by tino** [comment]
Well, with a canvas of 500x500 and a zoom level of 9 it still does not center, so I don't think that that is the problem: http://jsfiddle.net/qv989nzs/15/.

Btw, using `setViewportTransform` you can zoom to something that is near the edge, is there anything in `zoomToPoint` that prevents that?

**Comment by tino** [comment]
@kangax could you reopen this?

**Comment by asturur** [comment]
http://jsfiddle.net/qv989nzs/17/

Please look here.
Your comments are correct.
I always belived that ZoomToPoint was an absolute function.
Set to zoom to X and center the canvas on a point that is z,y when is unscaled.

Current implementation is not like that, it consider current zoom level and it does some relative coordinate work. It increment the point of zoom instead of setting it somewhere.
It looks like a pan the zoom somewhere.

My fiddle shows a hacked and patched up version of the function to work differently.
Here there is either a bug or a misleading function name / docs.

@tino check it.

**Comment by asturur** [comment]
The current behaving of the function is:
zoomToPoint(zoomLevel, destination) =
take destination as a pixel value, a mouse pointer value, and transform with inverted viewport to calculate where that point would be in plain canvas coordinates.
Set zoom level to zoomLevel
take the calculated canvas coordinates and transform them with new viewport
then increment current translation with difference of specified destination and transformed destination.
This latest point is very unclear to me.

The name is misleading a bit.

edited the comment to be more precise.

**Comment by asturur** [comment]
@kangax i need your attention here.

**Comment by krtenn** [comment]
@asturur Really late here. Your modification is exactly how I expected this to work. I agree name should be modified or your implementation should be taken / added in for it. Thanks. 

In my project I'm using it to draw a route along subway line, showing stops along the way - if the route is a short distance I zoom in closer to the map (calculating the mid point between the two departure and arrival stations as the center point to zoom on). With the hacked up version you provided it actually zooms and centers correctly.

**Comment by asturur** [comment]
i totally forgot the thing. but now that 2.0 is in progress it should be changed, or paired with alternatives.

**Comment by chrisranderson** [comment]
If someone else comes here struggling, try this:

```javascript
fabric.Canvas.prototype.zoom_in = function(e) {
  let mouse_point = this.getPointer(e.e, true)
  let zoom = this.getZoom()

  this.zoomToPoint(
    new fabric.Point(mouse_point.x, mouse_point.y), 
    Math.min(Math.max(zoom + (e.e.deltaY/150), .5), 6)
  )
}
```
The fix for me was using `true` for the `ignoreZoom` parameter: `this.getPointer(e.e, true)`.
