### ISSUE TITLE
Textstyle on textbox not set on all words after editing

### ISSUE THREAD

**Issue by marcovdijk** [kangax/fabric.js#2448]
When you add a textbox object you can edit the styles just fine like changing the fontSize and textDecoration etc. But when you edit the text and then try changing the style the changes don't apply to the newly added words:

http://jsfiddle.net/kg9weds5/8/

**Comment by asturur** [comment]
I see that when inserting new letters a style object for them is created.
While it should not if the surrounding text has no style.

**Comment by ozooner** [comment]
Came across same issue (can confirm)

**Comment by danmindru** [comment]
Easy to reproduce in the fiddle ->
!['Bug'](http://cdn.makeagif.com/media/9-09-2015/g118j2.gif)

**Comment by asturur** [comment]
Running the fiddle with a recent version of library instead of pasting the full library on the fiddle.
It works as expected.
http://jsfiddle.net/kg9weds5/10/

**Comment by marcovdijk** [comment]
Awesome, thanks!
