### ISSUE TITLE
Unexpected font-weight behavior with white text

### ISSUE THREAD

**Issue by PaRoxUs** [kangax/fabric.js#2455]
![skarmavbild 2015-08-31 kl 08 40 49](https://cloud.githubusercontent.com/assets/1275755/9575593/37589668-4fd1-11e5-8ca8-5fb4850fdb84.png)
![skarmavbild 2015-08-31 kl 11 11 17](https://cloud.githubusercontent.com/assets/1275755/9575594/377e4066-4fd1-11e5-9048-a93fcd3ec8f9.png)

As you can see in these two screenshots the text gets bolder when it is filled with a white color. I have experienced this before with Raphael. The difference gets clearer when the text is smaller! It is like the browser increases the font weight automatically if it detects that the text is white. 

For example both examples here will render the same font weight although one is set to normal and the other bold. This is only tested in Chrome.

	var text = new fabric.Text('lol', {
		top: 0,
		left: 0,
		fontFamily: 'Arial',
		fill: #000',
		fontWeight:'bold',
		hasBorders:false,
		fontSize:20
	});

	var text = new fabric.Text('lol', {
		top: 0,
		left: 0,
		fontFamily: 'Arial',
		fill: #fff',
		fontWeight:'normal',
		hasBorders:false,
		fontSize:20
	});

**Comment by kangax** [comment]
Interesting. Could you please make a JSFiddle showing this problem?

**Comment by PaRoxUs** [comment]
https://jsfiddle.net/utnqae6a/2/

**Comment by asturur** [comment]
![image](https://cloud.githubusercontent.com/assets/1194048/9718970/8949d086-5580-11e5-9278-e5afc41d4199.png)

As i suspected, happened also with tests in browser, it's a "clearType" problem.
If i deactivate clearType from windows the fonts are identical.

**Comment by asturur** [comment]
i think this is operating system dependant or at least clearType dependant.
I don't think we can take care of it here.
@kangax what do you think?

**Comment by kangax** [comment]
Yep, this is OS-dependent
