### ISSUE TITLE
Gradients from SVG to pathgroup, exported with JSON does not look the same when imported back again

### ISSUE THREAD

**Issue by bonny** [kangax/fabric.js#2456]
We have and SVG image that we import to Fabric. After import it looks ok.
If we export the Fabric canvas to JSON and then import the JSON again, the image does not look the same any longer.

Attached is an image where the left image is the correct look. Both the SVG logo and the look of the Fabric canvas at first is like this. The right image show the image after we have exported the fabric canvas to JSON and then imported it back again to a new fabric canvas object. As you see it looks slightly different, the bottom right shadow have moved to the left (I think, because that area is much darker now).

jsbin with example code to replicate this:
http://jsbin.com/teyoyu/1/

![fabricjs-svg-import-export-bug](https://cloud.githubusercontent.com/assets/221570/9578349/4870915e-4fe9-11e5-8a8d-b69de9013d90.png)

**Comment by asturur** [comment]
Thanks for correct issue preparation.
I will look into it as soon as possible.

**Comment by bonny** [comment]
If it helps, here is the same (or just similar?) problem happening with another image:

http://jsbin.com/buqokapora/1/

![fabric-export-import-bug-2](https://cloud.githubusercontent.com/assets/221570/9729072/c710a14c-560c-11e5-8219-15b5db7d00e7.png)

**Comment by asturur** [comment]
Ok found, is an easy fix at least.

**Comment by bonny** [comment]
Thanks for the quick fix. My tests also show that it works correct now.
