### ISSUE TITLE
Is it possible to trim the canvas to the size of the drawing inside it?

### ISSUE THREAD

**Issue by abnersouza** [kangax/fabric.js#2457]
Hi guys,

I'm not reporting a bug, is more a question.

I'm using the canvas with drawing, I created a control similar to an electronic signature. When I export the canvas to Svg, I would like to have the canvas cropped to the exactly size of the signature, because in code I have the crop method but requires too much memory.

What I found so far:

1)canvas.relatedTarget.width and canvas.relatedTarget.height, that one doesn't work for me because one get the size of the last draw path.

2)canvas.getObjects(), doesn't work as well because in that case i can get each element width and height but not the total height and width.

My idea would be, to get the signature total height and width, then resize the canvas to that size, and move the paths to be centralized in canvas. Because I need to keep the same signature.

Someone know if there is any way to trim 

the canvas to have only the paths? And in this case export to SVG the canvas to the exactly signature size? 

![signature_image](https://cloud.githubusercontent.com/assets/3270632/9598580/c227140a-5084-11e5-8565-edd94fc14129.PNG)

Thanks

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group (https://groups.google.com/forum/#!forum/fabricjs) or on StackOverflow (http://stackoverflow.com/questions/tagged/fabricjs) where someone will usually assist you.

The issue tracker is only for bugs and feature requests.

Thanks for your understanding!
