### ISSUE TITLE
Object starts sliding & moving on rescale, when the scale is limited.

### ISSUE THREAD

**Issue by 555ea** [kangax/fabric.js#2458]
If you limit the object scaling by certain amount, like 

canvas.on( "object:scaling", function ( e ) {
        var shape = e.target;
        if ( shape.maxScale != undefined ) {
          maxScale = shape.maxScale;
          if ( !isNaN( maxScale ) && shape.scaleX >= maxScale ) {
            shape.set( { scaleX: maxScale } )
          }
          if ( !isNaN( maxScale ) && shape.scaleY >= maxScale ) {
            shape.set( { scaleY: maxScale } )
          }
        }
      }
![15](https://cloud.githubusercontent.com/assets/13518952/9598744/c3430ce2-5096-11e5-8aa2-65b72d93de60.gif)

This 'moving' is not considered as real moving and is not triggered by "object:moving", thus there's no way to remove this buggy moving without disabling scaling at all.

**Comment by gprasanth** [comment]
@555ea have you set `lockScalingFlip` to true?

I noticed similar behaviour in following code:

```
// clear canvas
canvas.clear();

canvas.add(new fabric.Rect({
  width: 50,
  height: 50,
  fill: 'rgb(255,0,0)',
  lockScalingFlip: true
}));

canvas.on('object:scaling', function (e) {
  var obj = e.target;
  if (obj.scaleX < 1)
    e.preventDefault();
});
```

try using the left middle control to scale down, notice the object moves to the right

**Comment by asturur** [comment]
It is your maxScale implementation that is done in wrong place.
You should overrid the canvas._setObjectScale Method and insert the limit there.
https://github.com/kangax/fabric.js/blob/master/src/canvas.class.js#L637
