### ISSUE TITLE
Blurry images when  width/height are set.

### ISSUE THREAD

**Issue by vitalniko** [kangax/fabric.js#2459]
When canvas is set width/height, either via html or via .setWidth/.setHeight methods images become blurry.
When i use a canvas without any width/height set images look good as originals.

Please have a look at https://jsfiddle.net/0p9s8hus/2/

**Comment by asturur** [comment]
is related to #2337.

use ```canvas.imageSmoothingEnabled = false``` to have them not 'blurry'
Please close the isse if in this case the behaviour is consistent

**Comment by vitalniko** [comment]
Thanks Andrea!
But in 1.5.0 It works only in constructor
new fabric.Canvas('canvas', {imageSmoothingEnabled:false});
And cannot be reset  after canvas resize.
As i understand it's already fixed in 1.6.rc1
