### ISSUE TITLE
Unselectable objects can be selected with Shift+click in specific cases (all browsers)

### ISSUE THREAD

**Issue by nrossol** [kangax/fabric.js#2460]
First off: I love Fabric JS; it has made my current project a joy to implement! Thank you!

However, I have found a bug with group selections that can allow the selection of unselectable objects (i.e. objects with "selectable: false") through shift+clicks. 

**To recreate:**
1: You can go to the fabric.JS customization demo (http://fabricjs.com/customization/) and scroll down to the "Unselectable object" demo.

2: Select at least 2 of the selectable (green) objects (i.e. so that they are both selected at the same time).

3: You can now use Shift+click to select the "unselectable" middle circle object and add it to the group selection.

**Notes:** 
The bug seems to specifically require that 2 or more objects be selected in a group selection first. Selecting only one object, and then trying to add unselectable objects with Shift+click seems to not cause the bug to appear. The issue is consistent across Firefox, Chrome, and IE/edge.

**Comment by 555ea** [comment]
recreated, yep, that's true

**Comment by asturur** [comment]
reproduced
