### ISSUE TITLE
when create a rectangle with strokeWidth property, controls will have unexpect size

### ISSUE THREAD

**Issue by tnlin** [kangax/fabric.js#2464]
What I got : http://jsfiddle.net/svkfhfzL/5/ (with strokeWidth)
What I expected : http://jsfiddle.net/svkfhfzL/6/

it is clear that controls doesn't show up on the position I expect
especially when rectangle's width and height are big (like 200px, in my case)
you will notice that controls are disappear
http://jsfiddle.net/svkfhfzL/7/ (outside the canvas)

I wonder this is a bug or feature?

**Comment by asturur** [comment]
nor bug or feature.
Simply strokeWidth has to be a number, not a string.

**Comment by tnlin** [comment]
thanks a lot !!
