### ISSUE TITLE
Controls should always have highest z-index

### ISSUE THREAD

**Issue by jafferhaider** [kangax/fabric.js#2468]
Resize and rotation controls for the active object get occluded by items in the canvas that have a higher "z index" than the active object. This causes usability issues. Resize/rotation controls should always be visible and not occluded by items on the poster.

**Comment by asturur** [comment]
there is "controlsAboveOverlay" for this, a canvas property.
the real problem is that controls mix with the globalCompositeOperation if not drawn on top.

i have opened a pr, called renderAll improvements that other than simplify code put controls on top of stack, above or under the overlay.

**Comment by jafferhaider** [comment]
Ah, thanks @asturur. This flag works for this particular issue. My bad ... I had completely forgotten about this flag.

**Comment by kangax** [comment]
Folks, please don't forget to close issues when they're resolved just so that we can save time in the future :)
