### ISSUE TITLE
Replace canvas-container class

### ISSUE THREAD

**Issue by MULLAINATHAN** [kangax/fabric.js#2469]
Hi, 
I just want to know how to replace existing canvas-container class with New canvas-container class. Because In my project more number of canvas-container classes are created. Please help me to fix it.

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group (https://groups.google.com/forum/#!forum/fabricjs) or on StackOverflow (http://stackoverflow.com/questions/tagged/fabricjs) where someone will usually assist you.

The issue tracker is only for bugs and feature requests.

Thanks for your understanding!
