### ISSUE TITLE
Cannot center text vertically in version v1.5 (but versions 1.4 and below work)

### ISSUE THREAD

**Issue by premudriy** [kangax/fabric.js#2472]
In version 1.4 and below setting originY: 'center' for fabric.Text used to precisely center the text vertically on the specified coordinate, but in version 1.5 it's off (a bit off to the 'top' direction). 

In 1.5 I can't see any way to make text vertically and precisely centered on a coordinate except adding/subtracting pixels to y-coordinate to fake the centering, which is sub-optimal (need to avoid any unnecessary calculations for speed).

Here's example in version 1.4, text is vertically centered on the line: https://jsfiddle.net/97n8vL1y/1/

And here's the same example in 1.5 where vertical centering is not happening: https://jsfiddle.net/97n8vL1y/

Last thing, I also tried to use "native: true" on Text, still the same issue in 1.5

**Comment by asturur** [comment]
OriginY: center is in the center of bouding box and not in the center of text.
Performance wise, text is very heavy, little calculation won't change the performance.
Since 1.5 text has been reworked and its position is a little bit different in order to support overline text decoration.

**Comment by premudriy** [comment]
I see. Alright, I guess I'll be adding 1px to each text element to get stuff to center vertically. Thanks for your help!
