### ISSUE TITLE
Version 1.6.0-rc.1.  Cannot input Chinese character in iText in Chrome, windows 7

### ISSUE THREAD

**Issue by astw** [kangax/fabric.js#2473]
Test version 1.6.0-rc.1 on windows 7.  iText can not input Chinese characters in Chrome. 

Tested in firfox 39.0, IE10, Chrome 45.0.2454.85 
This issue only happens on Chrome. 
Whatever key is pressed,  the key displays in iText as English Character.  No Chinese input interface is activated .  

Before this I tried 1.5.0 version,  the Chinese input interface was activated,  but can not input Chinese characters as well.

**Comment by asturur** [comment]
can you make a jsfiddle that fails in chrome and works in firefox?
Would it be possible that you selected a different IME in chrome by error?

**Comment by astw** [comment]
@asturur  Here is example in jsfiddle

http://jsfiddle.net/6wa0wr00/7/

I use the same IME. IE and firefox both work, but Chrome doesn't.  I am using google IME.

**Comment by astw** [comment]
@asturur can you confirm it is an issue?

**Comment by Eamonnzhang** [comment]
I use the latest fabric version,but I can‘t type chinese in Firefox 42.0 by sougou input on itext
it can type chinese in chrome 47.0.2526.106 m (64-bit),but itext will record every keypress whatever is there any character input on it, it will change the keypress to space.
the jsfiddle that @astw maked also has this problem.
