### ISSUE TITLE
.toDataURL({ multiplier: 2 }) on single object goes wrong. The image data contains both original object and multiplied object

### ISSUE THREAD

**Issue by roywijmans** [kangax/fabric.js#2474]
Using toDataURL on an object like a text, textBox or iText  and using the multiply option is causing a problem. You get an image with the text at original scale and the text at multiplied scale. It's both in the same image.
The text at original scale should not be there. 
This bug is introduced since version 1.5.0 Older versions don't have this problem

  { 
var text = new fabric.Text("A very fancy italic text",{
        top: 10,
        left: 10,
        width: 100,
        height: 100,
        textAlign: 'center',
        fontFamily: 'Impact',
        stroke: '#c3bfbf',
        strokeWidth: 3
    });

    canvas.add(textbox);

    $("#btn-save").click(function () {
        var src = textbox.toDataURL({ multiplier: 2 });
        var img = document.getElementById("image");
        img.src = src;
    });

}
![image](https://cloud.githubusercontent.com/assets/14233737/9815738/a16b48b4-5898-11e5-8e07-de6dc79661eb.png)

Thanks

**Comment by asturur** [comment]
Post a jfiddle with the described problem

**Comment by roywijmans** [comment]
http://jsfiddle.net/roywijmans/2hpcqsxj/

**Comment by roywijmans** [comment]
http://jsfiddle.net/roywijmans/2hpcqsxj/


Van: Andrea Bogazzi [mailto:notifications@github.com]
Verzonden: vrijdag 11 september 2015 15:26
Aan: kangax/fabric.js <fabric.js@noreply.github.com>
CC: Roy Wijmans <roy@gigaprint.nl>
Onderwerp: Re: [fabric.js] .toDataURL({ multiplier: 2 }) goes wrong. The image data contains both original object and multiplied object (#2474)


Post a jfiddle with the described problem

**Comment by asturur** [comment]
Yes, canvas.toDataURL works fine, text not.
need to check it.

**Comment by roywijmans** [comment]
Version 1.4 works fine. Thanks for looking into it.

**Comment by roywijmans** [comment]
Problem is introduced by this commit
toDataURL via StaticCanvas #1892
