### ISSUE TITLE
load svg not apply gradient color on text

### ISSUE THREAD

**Issue by kuldipem** [kangax/fabric.js#2475]
HI,

```javascript
svg2='<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="163 47 527 66" preserveAspectRatio="xMidYMid meet" zoomAndPan="disable"><defs id="svgEditorDefs"><linearGradient gradientUnits="objectBoundingBox" id="lrgd2-e1" spreadMethod="pad" x1="0%" x2="100%" y1="0%" y2="0%"><stop offset="0%" stop-color="lightblue"/><stop offset="100%" stop-color="#ef5b2b"/></linearGradient></defs><rect id="svgEditorBackground" x="0" y="0" width="1121" height="561" style="fill: none; stroke: none;"/><text fill="url(&quot;#lrgd2-e1&quot;)" style="font-family: Arial Black; font-size: 35.4px; font-weight: bold;" x="216" y="91" id="e1_texte">THIS IS iKanvas Lib.</text></svg>';     

          fabric.loadSVGFromString(svg2, function(objects) {
           


 canvas.add.apply(iKanvas.activeFabricObj, objects);
            canvas.renderAll();
          });
```

![screenshot from 2015-09-14 10 23 00](https://cloud.githubusercontent.com/assets/2017625/9842375/00bd55ee-5acb-11e5-8516-7410a8dbbf5c.png)
![screenshot from 2015-09-14 10 23 48](https://cloud.githubusercontent.com/assets/2017625/9842376/00c58660-5acb-11e5-83c4-edda1e61e0b6.png)

**Comment by kuldipem** [comment]
Background for second image is manually set.....there is problem with gradient.

**Comment by asturur** [comment]
you should explain better what is your issue, or close this.
A jsfiddle is necessary most of the times

**Comment by kuldipem** [comment]
Issue is that, text  is not filled with gradient..

**Comment by asturur** [comment]
@kuldipem did you solve?

**Comment by kuldipem** [comment]
not yet,  as per your suggestion I have changed "light-blue" color to any defined color but and also formate proper gradient id...but didn't work.
