### ISSUE TITLE
svg setGradient only works first time, after that can not change obj.fill

### ISSUE THREAD

**Issue by Godweed** [kangax/fabric.js#2476]
I am adding one color svg file to canvas in kitchensink demo page.
Able to add gradient for the first time to the svg object
obj.setGradient('fill', 
                       { type:'linear',
                        x1: 0, 
                        y1: 0, 
                        x2: 0, 
                        y2:100,
                        colorStops: { 0 : 'rgba(0,255,0,1)', 1 : 'rgba(0,0,255,1)'} });

gradient applied without problem but when trying to change obj.fill I am getting Uncaught TypeError: (this.getObjects(...)[0].get(...) || "").toLowerCase is not a function(…) message. When I applied this gradient to itext object it works without problem, I am ablt to apply gradient to text object several times without any problem. But when try to change fill to imported svg file; it only works first time, after that it begins to give error message during setGradient

**Comment by asturur** [comment]
i think there is a recent fix that solved this.
i rember we fixed something regarding toLoweCase.

check in your versione the function:
```
    isSameColor: function() {
      var firstPathFill = this.getObjects()[0].get('fill') || '';
      if (typeof firstPathFill !== 'string') {
        return false;
      }
      firstPathFill = firstPathFill.toLowerCase();
      return this.getObjects().every(function(path) {
        var pathFill = path.get('fill') || '';
        return typeof pathFill === 'string' && (pathFill).toLowerCase() === firstPathFill;
      });
    },
```

if it is not like that you have the bug.

because old version assumed fill was a string, while after you set it to gradient, it is no more a string.

**Comment by Godweed** [comment]
I have updated version to 1.6-rc1 but the same issue without error now. 
if it is the first time I am able to set gradiant to svg object, it works properly. But I can not change fill again fot that object. Only the main object.fill get changed,paths array elements  object.paths[0].fill object.paths[1].fill  object.paths[2].fill remain the same. 

object.setGradient('fill', {
                           			  type: 'linear',
                                       x1: 0,
                                         y1: -object.height / 2,
                                         x2: 0,
                                         y2: object.height / 2,
                                      colorStops: {
        0: 'rgb(166,111,213)',
        0.5: 'rgba(106, 72, 215, 0.5)',
        1: '#200772'
    }
                                
                                });

**Comment by asturur** [comment]
Svg does not have a fill property.
The svg, imported as a group of path under a path-group, has lot of objects with a fill property.

The problem is that when you set the fill property of a pathgroup, there is a check that says "if all the path inside have the same fill, let's fill all of the same new color".
That is poorly implemented and also useless in most of the situation.
You should manually replace the fill property of each path inside the pathgroup, and not rely on the fill property of the pathgroup itself, that is not rendered at all.

I hope i explained myself.
