### ISSUE TITLE
Composing subclasses.

### ISSUE THREAD

**Issue by armoucar** [kangax/fabric.js#2477]
Hi,

on Fabric Introduction tutorial part 3, it's shown how to creates subclasses based on fabric types:
http://fabricjs.com/fabric-intro-part-3/#subclassing

instead writing direct in the canvas context, I was thinking on what I should do to reuse fabric's types on my specialised type

Example: http://codepen.io/armoucar/pen/ojbQRV?editors=101

Is it ok to use the `render` method as I did? My problem on this example is the position of the text. If use `render` is correct, why the text is center positioned?

By the way, just started using fabric.js and it is fantastic, thank you.

**Comment by asturur** [comment]
I would not create a new text label every render.
I would just define a label property, as a new fabric.Text and then i would call label._render.
http://codepen.io/anon/pen/bVpYvG?editors=101

But in this situation you are showing, a normal group would just work and would have less issue in positioning object.

**Comment by armoucar** [comment]
Yeah, I realised it is completely fine to use the `render` method. I was facing some troubles with that but just because was being dumb about it.

The API is great, I love how it is structured. Highly reusable and do things in a very simple way.

By the way, this issue can be closed as there's no problem at all. Thanks!
