### ISSUE TITLE
How come double click doesn't work, even though the code seems to be there?

### ISSUE THREAD

**Issue by premudriy** [kangax/fabric.js#2480]
I see that the code for double click is in the source code and issue #1642 states that double click functionality was added, but I still cannot get the double click event to fire.

I'm adding it as:
    fabricCanvas.on('mouse:dblclick', function(e){ ........});

What am I doing wrong? Does double click conflicts with something else in the current Fabric version? (using v1.5)

**Comment by asturur** [comment]
this is the actual list of event listeners:
```
    /**
     * Adds mouse listeners to canvas
     * @private
     */
    _initEventListeners: function () {

      this._bindEvents();

      addListener(fabric.window, 'resize', this._onResize);

      // mouse events
      addListener(this.upperCanvasEl, 'mousedown', this._onMouseDown);
      addListener(this.upperCanvasEl, 'mousemove', this._onMouseMove);
      addListener(this.upperCanvasEl, 'mousewheel', this._onMouseWheel);

      // touch events
      addListener(this.upperCanvasEl, 'touchstart', this._onMouseDown);
      addListener(this.upperCanvasEl, 'touchmove', this._onMouseMove);

      if (typeof eventjs !== 'undefined' && 'add' in eventjs) {
        eventjs.add(this.upperCanvasEl, 'gesture', this._onGesture);
        eventjs.add(this.upperCanvasEl, 'drag', this._onDrag);
        eventjs.add(this.upperCanvasEl, 'orientation', this._onOrientationChange);
        eventjs.add(this.upperCanvasEl, 'shake', this._onShake);
        eventjs.add(this.upperCanvasEl, 'longpress', this._onLongPress);
      }
    },
```
the pr you mention has never been merged.
can you point out the code that is related to dblclick that you saw?

**Comment by premudriy** [comment]
I just searched the downloaded dev build of Fabric for 'dblclick' and saw references to it. I saw that those come as part of Gestures module (part of Event.js), so I assumed dblclick is supported.

**Comment by asturur** [comment]
it is emulated on itext, to enter editing.
Il 18/set/2015 12:47 AM, "premudriy" <notifications@github.com> ha scritto:

**Comment by premudriy** [comment]
Understood, thank you for you help
