### ISSUE TITLE
about options and properties

### ISSUE THREAD

**Issue by sereepap2029** [kangax/fabric.js#2481]
can you list all possible properties and options objects in document
EX:
var canvas = new fabric.Canvas('c', {
  backgroundColor: 'rgb(100,100,200)',
  selectionColor: 'blue',
  selectionLineWidth: 2
  // ...you says other options here but I don't know where to find all posible options are please list all properties  that possible put in here not only in "fabric.Canvas"  but all other function too if you can point where to find it please tell me i'm new on programming plrase help
});

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group (https://groups.google.com/forum/#!forum/fabricjs) or on StackOverflow (http://stackoverflow.com/questions/tagged/fabricjs) where someone will usually assist you.

The issue tracker is only for bugs and feature requests.

Thanks for your understanding!
