### ISSUE TITLE
stroke color issue of text object

### ISSUE THREAD

**Issue by mukeshcp** [kangax/fabric.js#2488]
Hi,
  once applied stroke color to text object and then after scaling that text object. So stroke color size of text object is increased as per scaling. Then finally generate svg file using canvas.toSVG(). This svg file gives perfect output while open in browser, but no in illustrator.
     Can we show exact design of canvas in illustrator ?
     I need whatever we designed on canvas, it should be show in illustrator.
    can we stop only stroke size while scaling text object? I mean fixed stroke size while scaling object on canvas.
   I have designed on canvas in fabric js 1.5 and generate svg. It gives perfect output in browser & not in illustrator. Please find attachments
![image_gg](https://cloud.githubusercontent.com/assets/12266888/9975702/98609746-5ee3-11e5-8d1a-699b192d4977.png)
![image_k6](https://cloud.githubusercontent.com/assets/12266888/9975706/a866cfc0-5ee3-11e5-8ee4-383c60a7e006.png)

.

**Comment by asturur** [comment]
if you open in inkscape, internet explorer, chrome, firefox, what do you get?

it may be the illustrator svg import filter that is wrong.

**Comment by mukeshcp** [comment]
Hi,
 thanks for your reply.

I need illustrator svg import filter.

**Comment by asturur** [comment]
so best thing you can do is extend the classes, write a toIllustratorSVG method in which you compensate differencies. i think we are exporting as per w3c specification.

what other differencies you found other than unscaled borders?

**Comment by mukeshcp** [comment]
Hi,

Svg import filter for backgroundColor of canvas is not work in inkscape.

**Comment by kangax** [comment]
Yep, Illustrator's SVG support is often not up to par and there's not much we can do about it.
