### ISSUE TITLE
FlashCanvas instead of explorercanvas

### ISSUE THREAD

**Issue by ollym** [kangax/fabric.js#249]
It's now widely regarded that FlashCanvas is much faster tahn explorercanvas and supports much more of the API. The developers of explorercanvas have also now moved onto other things - can we have this dependency within fabric.js updated please?

**Comment by asturur** [comment]
copying uucanvas notices here
http://uupaa-js-spinoff.googlecode.com/svn/trunk/uuCanvas.js/README.htm

https://github.com/kangax/fabric.js/blob/master/src/util/misc.js#L342-L356

**Comment by kangax** [comment]
I'm not sure it's worth supporting old IE anymore. Most of the major sites and libraries dropped it a while ago.

**Comment by asturur** [comment]
i agree
