### ISSUE TITLE
Possible bug when clicking on empty space will having target in event

### ISSUE THREAD

**Issue by nodegin** [kangax/fabric.js#2492]
Here's a piece of my code
<img width="541" alt="screen shot 2015-09-23 at 15 09 39" src="https://cloud.githubusercontent.com/assets/8536244/10039493/2c299eb8-6205-11e5-869f-55bc3c068fd2.png">

This is how I produce it, the white crosshair is my cursor

Normally if I click on empty space the ```opt.target``` should be ```undefined```

<img width="887" alt="screen shot 2015-09-23 at 15 07 16" src="https://cloud.githubusercontent.com/assets/8536244/10039558/dbdef65a-6205-11e5-8c79-deb3c43c754f.png">

However sometimes I clicked on down empty space

the ```opt.target``` returns a line that shouldn't appears in that position

and the line stroke changed to green

<img width="887" alt="screen shot 2015-09-23 at 15 07 33" src="https://cloud.githubusercontent.com/assets/8536244/10039559/ddc32374-6205-11e5-8d21-1a649461a57f.png">

**Comment by asturur** [comment]
You should replicate with a simple jsfiddle without too much custom code.
then if it is in coffe script i cannot help.
