### ISSUE TITLE
[Textbox] Alignment doesn't work when any style is applied to a selection

### ISSUE THREAD

**Issue by fahadnabbasi** [kangax/fabric.js#2493]
There is a bug. If you add a textbox and apply the formatting on selection (not whole textbox). Now if you try to align the text, it won't align

Here is the fiddle, can anyone help me? 

http://jsfiddle.net/fahadnabbasi/kLdng24p/10/

Double click the textbox, make selection, click on "Apply formatting", now try to align the text and it won't

**Comment by marcovdijk** [comment]
Possibly related to #2448

**Comment by asturur** [comment]
With recent builds it works properly.
