### ISSUE TITLE
fabric.Image.fromURL error

### ISSUE THREAD

**Issue by Mistifyed** [kangax/fabric.js#2495]
Trying to add an image from url:

     fabric.Image.fromURL('/assets/cursor_arrow.png', function(oImg) {
         canvas.add(oImg);
     });

I get this error:

     canvas.js?body=1:93 Uncaught TypeError: Cannot read property 'join' of undefined
          canvas.on.object:added @ canvas.js?body=1:93r @ fabric.min.js?
          body=1:2fabric.StaticCanvas.fabric.util.createClass._onObjectAdded @ fabric.min.js?
          body=1:3fabric.Collection.add @ fabric.min.js?body=1:2(anonymous function) @ 
          VM708:3(anonymous function) @ fabric.min.js?body=1:7fabric.util.loadImage.i.onload @ 
          fabric.min.js?body=1:2

**Comment by kangax** [comment]
Does the image exist (via the url)?

**Comment by Mistifyed** [comment]
Yep, tried both absolute and relative. I went back just now and tried again, this time it worked after debugging a bit, out of nowhere, I'm still wondering what really happened.
