### ISSUE TITLE
pinch to zoom gesture is broken - due to Skew changes

### ISSUE THREAD

**Issue by mobidev111** [kangax/fabric.js#2496]
The pinch to zoom gesture is broken in current master.

Root cause: canvas_gestures.mixin.js has not been updated to changes introduced with the Skew changes

The Skew changes in https://github.com/kangax/fabric.js/pull/2482 introduced a new parameter "dim" to the _setObjectScale() method: https://github.com/kangax/fabric.js/commit/cda061132663459478e30f1c700c7eff6e49a2c0#diff-9dc132ed9a0787568f773999ba577e2bR637

canvas_gestures.mixin.js has not been updated to reflect this change: https://github.com/kangax/fabric.js/blob/4a6001e3561de546c24b6f8cc4b61db990c43367/src/mixins/canvas_gestures.mixin.js#L140
```javascript
     this._setObjectScale(new fabric.Point(t.scaleX * s * dim.x, t.scaleY * s * dim.y),
        t, lockScalingX, lockScalingY, null, target.get('lockScalingFlip'));
```

The lacking parameter causes an exception during calculation. 

Just adding the missing parameter unfortunately does not resolve the gesture issue - please investigate.

**Comment by asturur** [comment]
When you add parameter, do you have still calculation error?
I have no gesture device, so i cannot test properly.

If you have time to spare:
```diff
var constraintPosition = target.translateToOriginPoint(target.getCenterPoint(), t.originX, t.originY),
-        dim = target._getNonTransformedDimensions();
+        dim = target._getTransformedDimensions();

      this._setObjectScale(new fabric.Point(dim.x * s, dim.y * s),
        t, lockScalingX, lockScalingY, null, target.get('lockScalingFlip'), dim);
```

and if you want to try it on a skewed object to see if it feels ok.

**Comment by kangax** [comment]
ping @mobidev111

**Comment by kangax** [comment]
Actually I see @mobidev111 said that "Just adding the missing parameter unfortunately does not resolve the gesture issue" so we'll need to check more

**Comment by mobidev111** [comment]
@asturur regarding touch devices: 

a) cheap hardware - the easiest way would be e.g. a cheap android tablet with current android version.

b) simulate multi-touch - you can simulate touch devices in the Chrome browser. 
https://developer.chrome.com/devtools/docs/device-mode#touch-emulation
https://frontify.com/blog/how-to-emulate-touch-events-in-chrome/
