### ISSUE TITLE
Create a "nightly build" - for usage in jsfiddles -> better manual tests

### ISSUE THREAD

**Issue by mobidev111** [kangax/fabric.js#2497]
Just as a recommendation: 

Please create somewhere nightly build of the current master branch - with different configurations - e.g. the ALL build flag - using your continuous integration server) and put that online.

This would help users to create jsfiddle demonstrations of problems in the current master branch without going through the build process -> thus it helps to better & more frequently do the manual tests

Or even better: provide a separate demo page (based on http://fabricjs.com/demos/) which utilizes the most recent master branch in conjunction with all the demos

**Comment by kangax** [comment]
You can always refer to current master distribution file directly from github.

**Comment by kangax** [comment]
This is the "nightly" version I mentioned — https://rawgit.com/kangax/fabric.js/master/dist/fabric.js

**Comment by mobidev111** [comment]
This excludes e.g. the gestures module - so I cannot demonstrate touch-focused problems in the js-fiddle --> add a variant /dist/fabric_all.js with all modules

**Comment by handersen** [comment]
That would be great and allow ongoing touch/event testing as well.

**Comment by mobidev111** [comment]
The following issues would be better demonstrable: 
https://github.com/kangax/fabric.js/issues/2496
https://github.com/kangax/fabric.js/issues/2586

**Comment by mobidev111** [comment]
@kangax ping

**Comment by kangax** [comment]
@mobidev111 I guess we can include the version with gestures in dist; please feel free to send a PR (need to update build file) unless one of us gets to it first, although I don't know when — lots to do, too little time.

**Comment by handersen** [comment]
Any updates on an updated build which includes Gestures?
The release https://github.com/kangax/fabric.js/releases/tag/v1.6.0-rc.1 seems to be from juli 2015.
Or are there any other ways to create an up2data version which includes Gestures to support multitouch.
Thanks in advance.
