### ISSUE TITLE
unable to set stroke on loaded SVG

### ISSUE THREAD

**Issue by atomicjeep** [kangax/fabric.js#2499]
setting a stroke on a loaded SVG does not appear to work, the last release where this worked was v1.4.8 - the properties are being set on the object but it's being reflected on the visible canvas.

using v1.4.8 - http://jsfiddle.net/atomicjeep/r5q05apb/
using v1.6.0 RC1 - http://jsfiddle.net/atomicjeep/3ghgb1sh/

**Comment by asturur** [comment]
Yes we changed approach, pathgroup does not leak fill and stroke to its paths.
You have to do it.
There are so little situation on wich this is usefull, most of the time it gives an not desired effect.

**Comment by atomicjeep** [comment]
ahh ok thanks, I was unknowingly relying on a bug.  Any pointers to how I could replicate this again?

**Comment by asturur** [comment]
Yes
```
for (var i = 0; i < mypathgroup.paths.length; i++) {
   mypathgroup.paths[i].stroke = '#FF00FF';
}
```

you can use any array iterator i think.

**Comment by atomicjeep** [comment]
thanks @asturur that worked for me

**Comment by atomicjeep** [comment]
sorry to be a pain is there anything I can do to ensure that stroke information is saved & retrieved - it seems to be lost during save/load - I can always loop round the objects on load but just if there was any other way…

**Comment by asturur** [comment]
save and load how? with JSON it stays.

**Comment by atomicjeep** [comment]
I'm saving via toDatalessJSON, so I guess that explains it
