### ISSUE TITLE
example broken right on the fabricjs.com page

### ISSUE THREAD

**Issue by andreinitescu** [kangax/fabric.js#2501]
When selecting the object, the selection box is off the object.
This is the last example at the bottom on fabricjs.com

![1](https://cloud.githubusercontent.com/assets/743918/10108034/518c5484-63c7-11e5-973b-bef0db7d5097.jpg)

**Comment by asturur** [comment]
we noticed that some time ago, i think is an outdated json representation.

**Comment by asturur** [comment]
fixed some days ago.
