### ISSUE TITLE
Fabric js: SVG cannot import from url

### ISSUE THREAD

**Issue by dineshsinghchauhan** [kangax/fabric.js#2504]
I am working with fabric js , & i am getting problem in importing SVG from url on local system

fabric.loadSVGFromURL('svg/1.svg', function(objects, options) {
  var obj = fabric.util.groupSVGElements(objects, options);
  canvas.add(obj).renderAll();
});
& try also

var site_url =  'svg/1.svg';
fabric.loadSVGFromURL(site_url, function(objects) { 
          var group = new fabric.PathGroup(objects, { 
          left: 165, 
          top: 100, 
          width: 295, 
          height: 211 
        }); 
        canvas.add(group); 
        canvas.renderAll(); 
          });
& getting error in console for both codes
XMLHttpRequest cannot load file:///home/.../designtool2/svg/1.svg. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.request @ fabric.js:2300(anonymous function) @ fabric.js:3752svgCache.has @ fabric.js:3422extend.loadSVGFromURL @ fabric.js:3742(anonymous function) @ designtool.html:395
fabric.js:2300 
Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'ile:///home/.../designtool2/svg/1.svg.'.

can anyone help to resolve this how to import svg from local system
Thanks in advane

**Comment by kangax** [comment]
This is unrelated to Fabric and is the way browsers work.
