### ISSUE TITLE
node-canvas 1.2.9 producing broken jpegs

### ISSUE THREAD

**Issue by inssein** [kangax/fabric.js#2506]
I was going to submit a pull request that modifies the package.json to point to node-canvas 1.2.8 (the last working version) instead of 1.2.*, but I realized than the package will no longer support node 4.0.

What is the appropriate thing to do here?

**Comment by inssein** [comment]
Should be fixed after https://github.com/Automattic/node-canvas/pull/635 gets merged.

**Comment by inssein** [comment]
Should be fixed in 1.2.10. Will confirm tomorrow (or somebody else can confirm today).

**Comment by inssein** [comment]
Can't test with 4.2.0 yet.. installation is broken (same error as travis, seems to be a problem with jsdom).

**Comment by asturur** [comment]
jsdom or contextify and some problem with NaN also. i tried so much to fix compilation with node 4 but i was limited to try different packages versions because i m not node expert

**Comment by inssein** [comment]
@asturur just sent a PR (https://github.com/kangax/fabric.js/pull/2547).

**Comment by asturur** [comment]
closed with #2872 and canvas 1.3.x
