### ISSUE TITLE
Mouse up returning target of mouse down after performing drag operation

### ISSUE THREAD

**Issue by bbbalabhaskar** [kangax/fabric.js#2508]
In following fiddle I am trying to create line between two circles, using mouse but mouse up is returning target even if there is none. 

http://jsfiddle.net/9v8jt6ts/1/

**Comment by asturur** [comment]
It looks like you are getting the target from mousedown.

**Comment by bbbalabhaskar** [comment]
thx it is working after I kept selectable: false

**Comment by asturur** [comment]
There is something to investigate anyway.
In both mouseup and mousedown we are doing findTarget(e).
