### ISSUE TITLE
$localStorage Changed

### ISSUE THREAD

**Issue by sahalswappo** [kangax/fabric.js#2509]
I using this with angular but when I run 
> canvas.add(polygon);

It modified my $localStorage . 
If I comment this line this doesn't happen.

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group (https://groups.google.com/forum/#!forum/fabricjs) or on StackOverflow (http://stackoverflow.com/questions/tagged/fabricjs) where someone will usually assist you.

The issue tracker is only for bugs (with reproducible minimal test case) and feature requests.

Thanks for your understanding!

**Comment by sahalswappo** [comment]
Here it is . 

>http://plnkr.co/edit/GQnOIat1x1kMYvI3Vp4j?p=preview

**Comment by sahalswappo** [comment]
@kangax no luck .

Here it is http://plnkr.co/edit/GQnOIat1x1kMYvI3Vp4j?p=preview
