### ISSUE TITLE
"selectable" attribute not saved using canvas.toJSON() 

### ISSUE THREAD

**Issue by jacopo2405** [kangax/fabric.js#2511]
"selectable" attribute not saved using canvas.toJSON() so goes wrong when reload it with loadFromJSON.
tried with 1.5 and also 1.6 (this fixs some errors with grouping and colors but not this)

**Comment by jacopo2405** [comment]
also custom attributes are not saved. ie. group.set('code', "abc123")

**Comment by ozooner** [comment]
In order to export custom attributes, you have to specify them when casting canvas to JSON:
e.g canvas.toJSON([ 'selectable', '_controlsVisibility', 'code'])

**Comment by jacopo2405** [comment]
thx it is working !
Just out of curiosity, why even "selectable" has to be specified? it's not a custom attribute

**Comment by asturur** [comment]
mostly we export attributes relative to rendering to recreate the canvas.

and there is that extension option for all the others.

**Comment by jacopo2405** [comment]
thx again
