### ISSUE TITLE
problem between an image and its edges

### ISSUE THREAD

**Issue by jobnet2008** [kangax/fabric.js#2513]
Example and simple there in https://www.lulufrenchie.com/fr/lab
I seek to put the edges of an image to the frame eyeglasses keeping the image on the inside, I search with the z-index proprieté unfortunately I have not found a solution anyone can help me?
here is my code insertion image
function inser_valide(imageObj1){
		
		
if($("#pitcos").html()!=""){
		imageObj1.src=$("#pitcos").html();
		
		}
		else
		imageObj1.src=$("#imagews").html();

imageObj1.onload = function() {
	 oImg1=imageObj1.src;
	 
fabric.Image.fromURL(oImg1, function(oImg1) {
  // scale image down, and flip it, before adding it onto canvas
// oImg1.set({left:canvas1.width / 2+60,top:canvas1.height/2+80});
 //oImg1.set({width:240,height:90,angle:180,borderColor:"black"});

  oImg1.set({left:80,top:15});
 oImg1.set({width:w,height:h,angle:0,zIndex:100});
oImg1.borderSize=100;
  oImg1.borderColor = 'black';
 
  
			oImg1.cornerColor = 'black';
			oImg1.cornerSize = 20;
			
			alert(canvas1.getObjects().indexOf(oImg1.border));
var props="";
for (prop in oImg1){ props+= prop +  " => " +oImg1[prop] + "\n"; }
//alert(props);
oImg1.scale(3).setFlipY(false);
   oImg1.scale(2).setFlipX(false);
oImg1.on('selected', function() {
  console.log('selected a rectangle');
});

canvas1.add(oImg1);

});
};
			 
	   $( "#image_gche" ).dialog( "close" );
 
			
		}
	$("#image_g").click(function(){
		
		
	   
	    
	      $("#image_gche").load("im_gauche.php", function() {
			   $(this).dialog({
				
	             height: 'auto',
	             width:'30%',
	             modal: true,
	            
	             overlay: {

	                     backgroundColor: '#000',
	                     opacity: 0.5
	             },
				 buttons: {
        "Inserer": function() {
			inser_valide(imageObj1);},	
		"Retour": function() {
          $( this ).dialog( "close" );
        }
      }	
			});$("#ahrefg").click(function(){$("#image_gche").dialog( "close" );}); 
		});});

**Comment by asturur** [comment]
You need to print an image over the lenses or over the plastic frame of the glasses?

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group (https://groups.google.com/forum/#!forum/fabricjs) or on StackOverflow (http://stackoverflow.com/questions/tagged/fabricjs) where someone will usually assist you.

The issue tracker is only for bugs (with reproducible minimal test case) and feature requests.

Thanks for your understanding!
