### ISSUE TITLE
FabricJS toDataURL Multiplier Not Returning Correct Height/Scaling Correctly

### ISSUE THREAD

**Issue by krusk** [kangax/fabric.js#2516]
I have a FabricJS canvas that has to be converted to a PDF that matches the exact fractional inches for print production as follows:

    Width (Inches): 38.703111
    Height (Inches): 25.999987

Since the requirements are a DPI of 300, I obtained the pixels by multiplying the width and height x 300 as follows:

    38.703111 inches x 300 =  11610.9333 px
    25.999987 inches x 300 = 7799.9961 px

With these measurements in hand, I created a FabricJS canvas that users could edit and then convert to an image (will need to figure out how to convert it to a PDF server side later/suspecting node.js with the pdfkit module). 

Since it is not usable to have a 11610 x 7799px Canvas on a page, I set the size of the canvas as follows:

    Width: 650px
    Height: 436.6571863 (Orginal Height * New Width / Orginal Width = new height)

Here is what my Canvas looks like (HTML) and corresponding JavaScript code to render it:

    <canvas id="c" width="650" height="436.6571863" style="border:1px solid"></canvas>

    var canvas = new fabric.Canvas('c', {});

Users are able to edit the canvas and then convert it to an image, but this is the problem occurs. I attempt to scale the canvas via FabricJS' toDataURL method using a multiplier of 17.86297431 (Original Width in Pixels / New Width in Pixels and Original Height in Pixels / New Height in Pixels both equal a multiplier of 17.86297431) as follows:

    var dataURL = canvas.toDataURL({
        format: 'png',
        multiplier: 17.86297431
    })

    document.write('<img src="' + dataURL + '"/>');

However, once it scales, the width of my outputted image appears correct at 11610, but the height is off at 7788 when it should be 7799. This output does not show fractions, but rather just the whole pixels when I inspect the element.

My question is, how can I get my FabricJS Canvas to properly scale up to the pixels (or inches) so I can have my PDF (converted from my PNG) in the correct dimensions? Is this an issue with pixel fractions not being respected/what can I do about this?

**Comment by asturur** [comment]
That is perfectly normal.
Height of 436.65 get rounded to 436.
I really doubt a canvas element can have franction of pixel.
0.65 x 17.86 is more or less 11 pixel missing.

You have to print out a 38.7 x 26 inch.
Do not tell me you have a printer that can do 25.999987.
So just use a canvas of  774 x 520 pixel ( 20 multiplier over inches ) so you do not have to mess up with fractions. Then export with a multiplier of 15 ( 20 x 15 = 300 )

Other than that is not a fabricjs issue.

**Comment by krusk** [comment]
Hi Andrea,

My printer is a large scale printer (imagine billboards), so it is that exact. Does FabricJS support multipliers with fractions, and if so, to what place? I sounds like any fractions in pixels will not work/does the Web even support decimals for Canvases? I will try your idea of multipliers, but what do you recommend for rounding/getting something to fit within a 650 Width Canvas.

Thanks,

K.

**Comment by gox-ai** [comment]
@asturur am stuck with a similar problem is it possible to have a WidthMultiplier and HeightMultiplier?

**Comment by asturur** [comment]
no, the export will keep the same aspect ratio, so will keep a single multipliere

**Comment by Othman2001** [comment]
@krusk  i don't know if this logic is suitble for you or not but i had similar problem and fixed it,
i have something called printWidth which is the size of canvas to be printed for example (9000px x 9000px) for t-shirts (this value varies from product to product ) 
so i had to calcluate dynamic multiplier by this equation =  
` const multiplier = printWidth / canvasWidth;` 
then i use this multiplier in canvas.toDataUrl 
but the trick is to use `Math.round(multiplier)` by that you will have the exact number of muliplier you need 
good luck ☺️

**Comment by AlvesJorge** [comment]
@asturur just came across this issue with 5.3, and an image thats 1500x2000 turns into 1500x1999. Playing around with how the multiplier is is rounded I can get it to work, on certain images. 
<img width="811" alt="image" src="https://github.com/fabricjs/fabric.js/assets/60895482/234e77b6-adf3-475b-af20-7518c8e6893f">

**Comment by sobh7771** [comment]
I have the same issue when using `multiplier` the height of the image is cropped!

![image](https://github.com/fabricjs/fabric.js/assets/51163804/18d2cd81-87cd-4289-b39f-aeacd5285ac5)

The image should cover the entire width and height of the canvas

The desired dimensions are 7087x9449 I scaled both the canvas and the image to 500x666.6 and when using `toDataUrl` I set the `multiplier` to (7087 / 500)
