### ISSUE TITLE
Image filters Grayscale (maybe in others) not rendered in nodejs (in browser worked fine)

### ISSUE THREAD

**Issue by RWizard** [kangax/fabric.js#2517]
v1.6rc1 
 NodeJs 0.12.4 (OSX)

**Comment by RWizard** [comment]
Original image in browser canvas
![2015-10-16 0 18 40](https://cloud.githubusercontent.com/assets/190453/10527922/d684fb30-739b-11e5-8ea6-d3ddc2e5064e.JPG)
After filter Grayscale
![2015-10-16 0 18 55](https://cloud.githubusercontent.com/assets/190453/10527932/e2de675e-739b-11e5-8450-e684db44fffb.JPG)
After render in node.js (0.12.4)
![2015-10-16 0 20 07](https://cloud.githubusercontent.com/assets/190453/10527943/f4c036be-739b-11e5-9582-ae9027df7e29.JPG)

Would you like resolve the problem?

**Comment by RWizard** [comment]
Additional information: NodeJs render on OSX worked fine, problem on Linux (Ubuntu 14).

**Comment by alexfigueiredo** [comment]
+1

**Comment by engrsandeep** [comment]
is there any solution for this.. got same problem

**Comment by asturur** [comment]
is anyone able to make a "fiddle" in cloud9? i'm willing to help as always but i m not good with nodejs.

**Comment by gmapis** [comment]
did anyone ever figure this out? i'm having the same issue.

**Comment by asturur** [comment]
Is anyone willing or able to make a colud9 fiddle with nodejs? if you can set me up a basic case i will investigate the issue.

**Comment by asturur** [comment]
filters are working correctly now
