### ISSUE TITLE
Animation problems: 1) is not linear 2) stops when tab is not active

### ISSUE THREAD

**Issue by amkazan** [kangax/fabric.js#2518]
animation stops when you change the tab...

Sequence animation located in OnComplete is not linear and stops every time like a tramway. Does it need to rest to move on? It has a hard breathing? Or does it have an overwheight? 
How to make it just go forward without stops? smooooooooothly and ravnomerno

**Comment by asturur** [comment]
for 1) not being linear you commented other issues where they explained you that default animation is not linear. use a linear one from the available.

for 2) choking on sequence (if i understand good) please open a fiddle with latest version and with minimal code to demonstrate the issue.

issues without fiddles get closed

**Comment by amkazan** [comment]
there is no linear animation in the available. Every easing option is bouncy or jumpy or smth else, and default is not linear either. what do you mean linear? where is it?

upd:
ok, i found here http://fabricjs.com/solar-system/ linear easing. Please add it to fabric.util.easing.linear = easing: function(t, b, c, d) { return c*t/d + b; }

here is the fiddle. It has a little stop in the middle anyways
http://jsfiddle.net/omt395d1/3/

**Comment by asturur** [comment]
I do not see any shuttering worth investigation.
On my pc, chrome, intel i3, is smooth.
I can see a microshuttering but i think is because the animation is stopping and restarting.
It has to complete, then start the new one.
