### ISSUE TITLE
Text Stroke inline / outline

### ISSUE THREAD

**Issue by MULLAINATHAN** [kangax/fabric.js#2519]
Hi,
I just try Text Stroke. It's creating inline stroke along with outline. Please help me to resolve this problem.
Thanks in advance.

**Comment by asturur** [comment]
Is not a problem, it works like that on canvas.
If you want just outline you have to reverse order of filling and stroking.
Any stroking on canvas is both side of the line, left and rigth, or in the case of a close shape is in and out.

**Comment by MULLAINATHAN** [comment]
Hi, 
Thanks for your quick response, Can i have any samples.?

**Comment by asturur** [comment]
Is not something you can obtain from using the library, but you can modify this:

in this file 
https://github.com/kangax/fabric.js/blob/master/src/shapes/text.class.js#L379

change in this way:
```
    _renderText: function(ctx) {

      this._translateForTextAlign(ctx);
      this._renderTextStroke(ctx);
      this._renderTextFill(ctx);
      this._translateForTextAlign(ctx, true);
    },
```

and rebuild.

I do not know if this will be an official feature ever.

**Comment by MULLAINATHAN** [comment]
Thank you.
