### ISSUE TITLE
resizing a path by its command array

### ISSUE THREAD

**Issue by dumaron** [kangax/fabric.js#2520]
Hi everyone, 
I think I've found a bug on `setCoords`. 
I need to load an SVG containing path with curves and expand them by an arbitrary ratio (to fit the screen, for example). The only way I've found is to multiply all coordinates of every path by the ratio, and the result looks as expected.
After that I call `setCoords` but the clickable area is not the expected one, it's like the original one. You can see what I mean in [this jsfiddle](https://jsfiddle.net/30fwwkfo/1/).

I've looked in previous issues like [this one](https://github.com/kangax/fabric.js/issues/1157), but didn't find any help.

Am I expanding the paths in a wrong way? Or it's a bug?

**Comment by asturur** [comment]
You are modifying the path after it has been initialized.

Try to use:
``` yourpath._setPositionDimensions() ```

it should update the calculated width and height.

Or if applicabale, just apply a scale factor and divide the strokewidth where applicable by the scale factor.

Also consider that expanding the path by points will not produce good results with gradients.

**Comment by dumaron** [comment]
I've tried with this function and it resizes the bounding rect correctly but it also applies a strange offset to the paths and I don't undestand where it comes from. You can look at [this jsfiddle](https://jsfiddle.net/30fwwkfo/3/).

The problem is that I have to resize them whenever the window is resized, so I can't modify the paths before their creation.

**Comment by asturur** [comment]
What stops you from using normal scaling functions?

**Comment by dumaron** [comment]
I can't scale because in my software I add a background image to the paths and if they're scaled the image will look "pixellated". I am essentially following your first advice from [the previous issue](https://github.com/kangax/fabric.js/issues/2304) I've opened.

**Comment by asturur** [comment]
https://jsfiddle.net/30fwwkfo/6/

While this is not perfect, it still a hint toward right direction.
you can do it better for sure.

**Comment by dumaron** [comment]
I was working on a solution which updates the `path.oCoords` variables, but yours is more elegant.
It works, thank you a lot.

**Comment by davidagee** [comment]
I'm working in 1.5.x and had a similar issue, I managed to resolve it without using the clone/destroy/create method above. After updating your Path.path commands array, add the following two lines:

```
            path.pathOffset = null;
            path._setPositionDimensions();
```

Where `path` is your `Path` instance. This is because `_setPositionDimensions` does not update `pathOffset`, it checks for an existing value and uses it if it exists (path.class.js:132).
