### ISSUE TITLE
SVG output when items are scaled

### ISSUE THREAD

**Issue by orionorigin** [kangax/fabric.js#2521]
Hello,
When i try to export this canvas to svg http://prntscr.com/8nxvdm, i get this when i open the SVG in a browser: http://prntscr.com/8nxvqs

Something to know is that the canvas and items on it might have been rescaled. Does anyone know how to fix this?

**Comment by asturur** [comment]
Please provide a fiddle with the canvas setup and an svg export button.
Or provide the json of that canvas to be loaded in kitchensink

**Comment by orionorigin** [comment]
{"objects":[{"type":"rect","originX":"left","originY":"top","left":375,"top":225,"width":50,"height":50,"fill":"rgb(79, 113, 185)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"rx":10,"ry":10,"lockMovementX":false,"lockMovementY":false,"lockScalingX":false,"lockScalingY":false}],"background":"","backgroundImage":{"type":"image","originX":"center","originY":"center","left":400,"top":250,"width":262.53,"height":500,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"src":"http://localhost/wpc-boilerplate/wp-content/uploads/2014/10/m2.png","filters":[],"crossOrigin":"","alignX":"none","alignY":"none","meetOrSlice":"meet"}}

Thank yoyu.

**Comment by asturur** [comment]
http://localhost/wpc-boilerplate/wp-content/uploads/2014/10/m2.png

you have to provide accessible link for the image.

**Comment by orionorigin** [comment]
Oh sorry: http://static.orionorigin.com/m2.png

**Comment by asturur** [comment]
this json works ok
