### ISSUE TITLE
Fabric js canvas rotate image along with drawn objecs

### ISSUE THREAD

**Issue by priyadharsini721** [kangax/fabric.js#2522]
Am trying to rotate the canvas along with objects, so i just added the objects to a group and tried rotating it, but the objects are misplaced. Following is my code.  
              var origItems = canvas1._objects;
                var center = canvas1.getCenter();
                if (group == undefined) {
                    var arr = [];
                    for (var i = 0; i < origItems.length; i++) {
                        arr.push(canvas1.item(i).clone());
                    }
                    //group = new fabric.Group(arr);
                    group = new fabric.Group();
                    group.set({
                        width: size.width,
                        height: size.height,
                        top: center.top,
                        left: center.left,
                        angle: angleInDegrees
                    });
                    for (var i = 0; i < arr.length; i++) {
                        group.add(arr[i]);
                    }
                    canvas1.clear().renderAll();
                    canvas1.add(group);
                } else {
                    group.rotate(angleInDegrees);
                }

Initially my canvas will be lik this,
![zerodegree](https://cloud.githubusercontent.com/assets/14977115/10279629/da86cb06-6b84-11e5-94f5-a824c1e4bb08.png)

After rotating by 90 degress, my canvas should look lik this
![degree90](https://cloud.githubusercontent.com/assets/14977115/10279638/f3092d90-6b84-11e5-9ec1-3c1fd8b8e091.png)

Please help me this as soon as possible.

**Comment by asturur** [comment]
Please provide a fiddle with this setup.

**Comment by priyadharsini721** [comment]
This is my fiddle, please check it.
https://jsfiddle.net/w0Lndnrw/

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group (https://groups.google.com/forum/#!forum/fabricjs) or on StackOverflow (http://stackoverflow.com/questions/tagged/fabricjs) where someone will usually assist you.

The issue tracker is only for bugs (with reproducible minimal test case) and feature requests.

Thanks for your understanding!
