### ISSUE TITLE
Add 'remove image' button next to rotation handler

### ISSUE THREAD

**Issue by seekshiva** [kangax/fabric.js#2523]
I would like to do `targetCanvas.remove(designObj)` if the user chooses to delete an image.

Is it possible to add a 'remove design' button next to the rotation handler to do this?

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group (https://groups.google.com/forum/#!forum/fabricjs) or on StackOverflow (http://stackoverflow.com/questions/tagged/fabricjs) where someone will usually assist you.

The issue tracker is only for bugs (with reproducible minimal test case) and feature requests.

Thanks for your understanding!
