### ISSUE TITLE
Can't clone Path if "constructor.fromObject"

### ISSUE THREAD

**Issue by dumaron** [kangax/fabric.js#2525]
Sorry to bother again, I might have found a real bug this time.

I'm trying to clone a path that was previously created from another object (like the ones in [this jsfiddle](https://jsfiddle.net/30fwwkfo/6/), by @asturur) but it seems that I can't.
Trying to read the fabric code, I've found out that I'm calling the function `.clone` on [line 11657 of the fabric.js file](https://github.com/kangax/fabric.js/blob/master/dist/fabric.js#L11771).

When `this.constructor.fromObject` is true the first case is executed and, in the case of a Path object, it **returns** the result of the function on [line 16095](https://github.com/kangax/fabric.js/blob/master/dist/fabric.js#L16095). This has two problems:

1. this function doesn't have any `return`, so the cloned path is `undefined`
2. this function makes `callback` a required argument, when it shouldn't be if I don't need to post-process the clone

**Comment by asturur** [comment]
For fabric 2.0 @kangax wanted to make the api consistent   about this.
As of now some return the clone , some not.
Cloning cannot be sync because it may involve reloading images from urls from what i remember.

Not really a bug, more a known inconsistence.

**Comment by dumaron** [comment]
Yeah, probably a promise here will be useful.
If someone will ever have the same problem, I've resolved it only in the synchronous case with these lines:
```
var clone = new fabric.Path(object.path, object);
return callback ? callback(clone) : clone;
```

**Comment by asturur** [comment]
this will work good in case no image pattern are present, or something that goes trought a imageLoad, ajax request and so on.
