### ISSUE TITLE
Exporting canvas to an image with hight resolution.

### ISSUE THREAD

**Issue by shobhitpokhriyal** [kangax/fabric.js#2526]
Hi, I am getting serious problem while exporting image from fabric canvas. Actually I have 600*400 canvas but need high resolution like(1200*800) while exporting it to image. I have already used toDataURL built-in function and send width,height and quantity parameters to it but the content not scaling at all.

Thanks in Advance

**Comment by kuldipem** [comment]
you can use  this feature ```canvas.toDataURLWithMultiplier(imageType,4)```.

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group (https://groups.google.com/forum/#!forum/fabricjs) or on StackOverflow (http://stackoverflow.com/questions/tagged/fabricjs) where someone will usually assist you.

The issue tracker is only for bugs (with reproducible minimal test case) and feature requests.

Thanks for your understanding!
