### ISSUE TITLE
CMYK color to text

### ISSUE THREAD

**Issue by MULLAINATHAN** [kangax/fabric.js#2530]
Hi,
I have a need to fill CMYK color to text. I try for it. But, I can't found solution. Is it possible to apply CMYK color to text.?
Please help me. Thanks in advance.

**Comment by asturur** [comment]
i do not know if canvas element support cymk colors.
If you tried to do "text.fill = cymk(0,100,0,0)" and it did not work, use the forumla for conversion:

**CMYK to RGB conversion formula**

The R,G,B values are given in the range of 0..255.

The red (R) color is calculated from the cyan (C) and black (K) colors:

R = 255 × (1-C) × (1-K)

The green color (G) is calculated from the magenta (M) and black (K) colors:

G = 255 × (1-M) × (1-K)

The blue color (B) is calculated from the yellow (Y) and black (K) colors:

B = 255 × (1-Y) × (1-K)
