### ISSUE TITLE
Applying small mask on big image

### ISSUE THREAD

**Issue by DanieleSassoli** [kangax/fabric.js#2531]
Hi,
I'm trying to apply a mask on an image. If the mask is of the same size of the image everything works fine, but when I use a bigger image, the output is incorrect. 
I've created 2 fiddles, [one with the correct image](http://jsfiddle.net/88LRm/45/) and [one with the big image](http://jsfiddle.net/88LRm/46/). 
I think the problem could be in:

    for ( i = 0; i < imageData.width * imageData.height * 4; i += 4 ) {
         data[ i + 3 ] = maskData[ i + channel ];
    }
    context.putImageData( imageData, 0, 0 );

Because it iterates over imageDatawidth * imageDataHeight which is 1600 * 1200, instead the mask is only 375 * 375, so probably this is the problem. I'll work on this, but in the meantime I was wondering if I'm mistaking something o if someone else has already find a solution?

**Comment by DanieleSassoli** [comment]
I managed to solve this issue, [here](http://jsfiddle.net/88LRm/47/) is a working fiddle. 
All I did was drawing the mask on a canvas as big as the image and then putting the canvas inside maskData, at this point the iteration dosn't exceed the limits of maskData anymore(because it's as big as the image) and the mask is applied correctly. If this is considered an issue, and this is the correct fix, I'll be glad to submit it.

**Comment by asturur** [comment]
I did not give you any comment yet, i did not have time to check how mask is supposed to work.
What happens if a small small image is used as mask? does it get stretched to full canvas now? is this a desired behaviour?

**Comment by DanieleSassoli** [comment]
Basically if the image si 1600 * 1200 and the mask is 375 * 375, the mask gets applyed only on the first 375 * 375 pixels of the original image, I changed this and now the mask is applied correctly because I draw it on a canvas big as the orignal image before applying it. So this is what happens in the fiddle.
In real life, I have a custom image class(which I think I will create a pool request for, sooner or later) 
that allows you to modify the image without stretching it, and you can even crop and clip the image with ease, this is relevant because I'm struggling with applying the mask on clipped images, once I have solved this issue I'll see if I can create a pull request.

**Comment by asturur** [comment]
i think your solution here is correct.

**Comment by DanieleSassoli** [comment]
I've already created the pull request with this fix.

**Comment by asturur** [comment]
yes i was refferring to that.
