### ISSUE TITLE
Font name start with number is not applied on canvas text and font size is reduced 

### ISSUE THREAD

**Issue by upardhi** [kangax/fabric.js#2533]
Hi, I have applied fontfamily name start with a number or number in font family at that time text behaves like a stranger, fontFamily is not applied on text and font size automatic reduces. I think  need to add quotes to fontfamily if font family name start with a number or number in the font family.
 
Please check this issue

**Comment by kangax** [comment]
Please show the example code that fails.

**Comment by upardhi** [comment]
Hi Kangax, 

 Please Check  below Jsfiddle

http://jsfiddle.net/upardhi/hx40tgfw/

**Comment by asturur** [comment]
i will chek if we are parsing the name as a generic font style decleration.

**Comment by asturur** [comment]
Ok, if you call a font 9 arial, the style declaration becomes:
normal 16px 9 Arial.

looks like Canvas element cannot parse this declaration because is not well formed.
If you quote your font name like "9 Arial" it will works.
