### ISSUE TITLE
Problem in using clipto() with canvas setzoom(x)

### ISSUE THREAD

**Issue by JugnuPathak** [kangax/fabric.js#2536]
We are using setZoom(x) for canvas zoom in and zoom out, and using clipto() on it but its not respective to canvas zoom level. any workaround for achieving desired result???

**Comment by asturur** [comment]
how are you clipping? can you show your clipping function?

**Comment by JugnuPathak** [comment]
Initial clipTo :
       canvas.clipTo = function (ctx) {
            ctx.beginPath();
            ctx.rect(left, top, width, height);
            ctx.closePath();
        }
after zooming in/out canvas: 

  var zoompoint, zoomLevel;
  // flag for whether to zoom in/out
   if (flag) {
        zoomLevel += .1;
        zoompoint -= .1;
        canvas.setZoom(zoomLevel);
    }
    else {
        zoomLevel -= .1;
        zoompoint += .1;
       canvas.setZoom(zoomLevel);
    } 
  canvas.clipTo = function (ctx) {
        ctx.beginPath();
        ctx.rect(canvas.left * zoompoint, canvas.top * zoompoint, canvas.width * zoomLevel,  canvas.height * zoomLevel);
        ctx.closePath(); 
    };
