### ISSUE TITLE
Bug Fabricjs 1.5/1.6 + Scale and CurvedText

### ISSUE THREAD

**Issue by neopheus** [kangax/fabric.js#2539]
Hi,

I have a Bug with Scale and CurvedText (on fabricjs 1.5/1.6)

1 - Open : https://jsfiddle.net/EffEPi/qpJTz/
2 - Scale the CurvedText Selection
3 - Change the Text (CurvedText)
4 - BUG : The CurvedText is in wrong position

Do you know how to fix this problem?

Thx a lot

**Comment by asturur** [comment]
The bug is probably in your custom curved text.
Looks like _calcBounds is not working properly.
I do not think is something we can suppor here, we do not have curved text in the build yet.

**Comment by ashishbhattb** [comment]
Hmm,

Same issue i have face for many other features like slant text, curved text, clockwise text, anticlockwie text

But its Just not working in "1.6.0-rc.1" old versions its working fine, once we add 1.6.0-rc.1 its not working 

Check in 1.5.0
https://jsfiddle.net/qpJTz/225/

**Comment by asturur** [comment]
That is because who wrote those classes wrote them for 1.5.0
When 1.6.0 will be out they can be updated from the creators.
Untill they are not in the main code line, we cannot support them here.
Code refactoring is necessary sometimes to keep fabric clean and maintanable.
