### ISSUE TITLE
Export Canvas to JPEG

### ISSUE THREAD

**Issue by armsmani** [kangax/fabric.js#2540]
Hi Kangax,

Is it possible to convert Canvas to JPEG. can you please help me to overcome this problem..

Thanks,
Manikandan M

**Comment by duraik3** [comment]
Hi Manikandan M,
try
canvas.toDataURL('image/png');

**Comment by taveras** [comment]
[In the Documentation](http://fabricjs.com/docs/fabric.Canvas.html#toDataURL) you can see that you can call `toDataURL( {format: 'jpeg' })` on any instance of `fabric.Canvas`

**Comment by duraik3** [comment]
canvas.toDataURL({
    format: 'jpeg',
})

**Comment by armsmani** [comment]
Thank you All for your support...
Thank you Durai, I was tried canvas.toDataURL({format: 'jpeg',}) method and its working fine.

**Comment by unitedsol** [comment]
i am using this but not working in my case

var imageSaver = document.getElementById('ftdownload');
	imageSaver.addEventListener('click', saveImage, false);

	function saveImage(e) {
	    this.href = canvas.toDataURL({
	        format: 'png',
	        quality: 0.8
	    });
	    this.download = 'frontside.png'
	}
