### ISSUE TITLE
Find Applied Filter

### ISSUE THREAD

**Issue by MULLAINATHAN** [kangax/fabric.js#2541]
Hi,
I just want to know how to find applied filter to image.?

Thanks in advance.

**Comment by upardhi** [comment]
Find out active object and check filter property array.
Eg. Canvas.getActiveObject().filters

-----Original Message-----

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group (https://groups.google.com/forum/#!forum/fabricjs) or on StackOverflow (http://stackoverflow.com/questions/tagged/fabricjs) where someone will usually assist you.

The issue tracker is only for bugs (with reproducible minimal test case) and feature requests.

Thanks for your understanding!
