### ISSUE TITLE
Shadows don't appear when no fill

### ISSUE THREAD

**Issue by ncote** [kangax/fabric.js#2548]
When we apply a shadow to a rectangle with transparent fill, the shadow doesn't appear.

http://jsfiddle.net/5acw9ez3/

![image](https://cloud.githubusercontent.com/assets/2867460/10476013/e4b7b8c6-7217-11e5-90d7-6c11e72f43c6.png)

**Comment by asturur** [comment]
set shadow.affectStroke to true.
