### ISSUE TITLE
Canvas convert to JPG with white background

### ISSUE THREAD

**Issue by armsmani** [kangax/fabric.js#2551]
Hi Kangax,

I was tried to convert Canvas to JPG but transparent area shown with black color. How can i set white background while converting Canvas to JPG.

Thanks,
Manikandan M

**Comment by asturur** [comment]
set background color of canvas to white before exporting, set it back to what you want after export

http://fabricjs.com/docs/fabric.StaticCanvas.html#setBackgroundColor

**Comment by armsmani** [comment]
Thanks Asturur.... It helps lot..

**Comment by monis01** [comment]
Hi
I did same, but still I am getting black color. I need preview of an image and later to send data to server as well (In both cases I need white background for canvas). I did :
```
var canvasCopy = $.extend(true, {}, canvas); //@ to avoid mess with reference
canvasCopy.setBackgroundColor('rgba(255, 255, 255, 1)', canvasCopy.renderAll.bind(canvasCopy));
var based64 = canvasCopy.toDataURL({format:'jpg'});
$('#preview_img').attr("src", based64);

```

but unfortunately same black color, something I am missing?

Thanks

![screenshot from 2018-04-24 16-59-08](https://user-images.githubusercontent.com/7036532/39184454-0904531e-47e1-11e8-9dc4-ed61ab74c101.png)
