### ISSUE TITLE
SVG ClipTo

### ISSUE THREAD

**Issue by MULLAINATHAN** [kangax/fabric.js#2555]
I had Post my question also in Google Groups. But, yet i didn't get any response for following question.
Export to JSON after applying clipTo to image by using SVG.
Please help me.

**Comment by solex16** [comment]
I had same problem reproducing my clipTo data in the toSVG() method..

As a workaround I applied this code to create a clipPath element in the SVG string:

```javascript
clipPath = '<clipPath id="'+rct.name+'">';
clipPath += '<rect x="'+ -imgWidth/2 + '" y="' + -imgHeight/2 + '" width="' + rct.width / scaleX + '" height="' + rct.height / scaleY + '" />';
clipPath += '</clipPath>';
```
where my clipTo function in the canvas object looked like this:

```javascript
// -- crop the image to fit the pane --
clipTo: function (ctx) {
      ctx.rect(-imgWidth/2, -imgHeight/2, rct.width / scaleX, rct.height / scaleY);  // -- from top left --
},
```

hope this helps?..
