### ISSUE TITLE
get the left, top, height, width of the image on perPixelTargetFind

### ISSUE THREAD

**Issue by gitlovenotwar** [kangax/fabric.js#2557]
Hi,

Is there any way to get the actual top,left,height, width of an image? You see I have an image that most of it is transparent and just a certain part is the actual image(I have a reason why is it so), using the perPixelTargetFind properties works just fine. I'm able to click on the image not on its bounding box, but the actual image. Is there any way to detect or set the(ex. fabric.Text) to center both horizontal/vertical on that image(usually on load)? Please help. Thanks.

<pre>
var canvas = new fabric.Canvas('canvas-id', {
   perPixelTargetFind: true,
   ...,
});

// some image source with a lot of transparent
fabric.Image.fromURL('../some-source', function(img) {
   // adding the image
   canvas.add(img);

   // now here, I want this text to be centered on the the image
   var text = new fabric.Text('some-image-name');
});

</pre>

**Comment by asturur** [comment]
Easiest thing i can think of is write a filter that discards the transparent pixels and gives you back the cropped image.

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group (https://groups.google.com/forum/#!forum/fabricjs) or on StackOverflow (http://stackoverflow.com/questions/tagged/fabricjs) where someone will usually assist you.

The issue tracker is only for bugs (with reproducible minimal test case) and feature requests.

Thanks for your understanding!
