### ISSUE TITLE
Problems when canvas zoom < 1 with new renderAll

### ISSUE THREAD

**Issue by DanieleSassoli** [kangax/fabric.js#2558]
Hi,
I was trying out the new renderAll by @asturur, it looks awesome and it makes more sense than the preciding one, but I found a problem when I set a zoom < 1, to the canvas. I create a [fiddle](http://jsfiddle.net/kyh0Lwyt/1/), as you can see it looks like the objects get re-drawn on every mouse:move, which is correct, but they never get removed. The behaving is quite strange, so I suggest you look at the fiddle to have a better understanding of the problem, just try dragging the objects around....

**Comment by asturur** [comment]
Ok, fabric is doing clear() with zoom already set.
So is clearing a smaller area of the screen.

**Comment by asturur** [comment]
@DanieleSassoli i submitted #2559. I guessed the fix and i cannot test it now.
If you have time please give it a shot. i will not try it before evening. If you can confirm it works we speed up the process.

**Comment by DanieleSassoli** [comment]
@asturur yes, this fixes the problem, it also fixes another issue I was going to submit, with some fonts that where rendered really bad.

**Comment by asturur** [comment]
Please paste the fiddle here anyway, i wanna see what goes wrong.

**Comment by DanieleSassoli** [comment]
[here's](http://jsfiddle.net/kyh0Lwyt/3/) the fiddle. But nothing goes wrong now, in my opinion. The objects and the fonts are rendered correctly.

**Comment by DanieleSassoli** [comment]
@asturur does everything look good to you? for what it concerns me this issue can be closed.
