### ISSUE TITLE
Issue with retina display and toDataURL

### ISSUE THREAD

**Issue by mbaudry** [kangax/fabric.js#2562]
I have an issue with retina displays when I make a dataURL of the canvas. I don't have the entire canvas in the output. I have fixed the issue in my code by multiplying the width and height options of the `toDataURL` function based on fabric.devicePixelRatio. Is this a good solution or have I missed some internal options?

Thank you for your help.

**Comment by asturur** [comment]
can you make a simple fiddle? i will try to use it on a mac. javascript, not coffee script

**Comment by mbaudry** [comment]
My mistake. Sorry for the inconvenience !

**Comment by mbaudry** [comment]
I do not have the problem with a jsfiddle. I'll try to make an example as soon as possible.

**Comment by mbaudry** [comment]
Hi !

I finally found the problem. I'm using fabric.js on master branch, so I can't test it on jsfiddle... But when I use the version 1.6.0-rc1 of fabric, I don't have the issue. So I searched the commit in master where the bug appears, and it seems to be that the problem arises from the commit [33cdaa1](https://github.com/kangax/fabric.js/commit/33cdaa1289d1f05174c04c2d14b7f1572b7661b3). I hope it can help.

**Comment by asturur** [comment]
Did you try reverting that commit and checking if it works?

**Comment by mbaudry** [comment]
I think the problem lies elsewhere. Even if I revert the commit  [33cdaa1](https://github.com/kangax/fabric.js/commit/33cdaa1289d1f05174c04c2d14b7f1572b7661b3), when I add an object in the canvas (always in retina display), it's inserted at the top/left, smaller.

**Comment by asturur** [comment]
I think that retinazoom does not work with toDataUrl.
I have to check it, because there are 2 or 3 things overlapping.

**Comment by mbaudry** [comment]
Thank you for your help ! If I build fabric on master branch (with the latest commit [7cdf9cf](https://github.com/kangax/fabric.js/commit/7cdf9cf76ef5e19b32cdf12766c530b68ec9c3ac)), I have an issue when I add an object in the canvas (wrong resolution I think).

**Comment by asturur** [comment]
Look i close this issue and i merge with the other one that is exactly same.
