### ISSUE TITLE
Objects index don't show correctly on canvas

### ISSUE THREAD

**Issue by CrackerakiUA** [kangax/fabric.js#2564]
I have sorting layers which modifies correctly _objects, i am testing after sort all object have correct index, but in the canvas objects are still as it was when i have created them. I do renderAll after sort.
An example of what i have is:
obj1 index 0
obj2 index 1
obj1 is above obj2 in the canvas
when i sort them it get like:
obj1 index 1
obj2 index 0
but still in canvas obj1 is above obj2 in the canvas

**Comment by asturur** [comment]
fabricjs provide some methods for objects ordering.
are you using them?

**Comment by CrackerakiUA** [comment]
no, i saw those 4, but i tried them also and end up with same result.

**Comment by CrackerakiUA** [comment]
Oh, it's my bad, i was testing it with black words ...
