### ISSUE TITLE
Problems with SVG transform matrix and viewBox

### ISSUE THREAD

**Issue by dumaron** [kangax/fabric.js#2569]
Hi again,
I'm trying to load into fabric some SVG with a viewBox that has the initials two values different from zero but in some SVG I'm encountering issues. In [this jsfiddle](https://jsfiddle.net/30fwwkfo/7/) you can see that the viewBox is parsed correctly: it has 30 horizonal and vertical offset, and if you change these values the rects on the canvas moves.

But if you look in [this jsfiddle](https://jsfiddle.net/nhbure8s/) you can see that the initial values of the viewBox (867.827637 and 1298.600342) don't have any effects on the final result. You can try it by changing them to 0, and see that the canvas looks exactly the same. I also have to do some additional adjustments to the transformMatrix to make the canvas looks like the original SVG. 

Can SVG with transform matrix break the viewBox parsing (and other things as well) or I'm doing something wrong?

Thank you

**Comment by asturur** [comment]
Yes, you are doing something wrong ( no offense of course ).
you are adding to canvas a ungrouped svg, an unsupported feature as of now.
Please check #1520, the code is nearly done, i need time to sit down and finish it.
I can share what i have done so far of course, but is very ugly.

Please check current version of fabric.util.qrDecompose in the files of #2549

with your code you are:
calculating wrong angle  ( you have to do Math.atan2(matrix[1] / matrix[0]) )
you ard discarding the translation effect ( matrix[4] and matrix[5] set to 0 ) that is what the viewbox first two values are there for.
And trashing scaling ( of viewbox and transformMatrix ).

**Comment by dumaron** [comment]
Can you please explain me what do you mean with "ungrouped"?

**Comment by asturur** [comment]
You are adding all the objects to canvas.
Current procedure is to call:

 var obj = groupSVGElements(elements, options);

https://jsfiddle.net/nhbure8s/1/

I added a functiona width and height to the SVG in the header just to make it small, otherways is not manageable.
As you see, now the svg looks correct and is grouped, is one solid block.
You can still manipulate every object inside but not with mouse.
