### ISSUE TITLE
loaded Images blurred and/or offset since 1.6

### ISSUE THREAD

**Issue by n0rb** [kangax/fabric.js#2570]
if you open these two fiddles side by side in chrome 45, the second one will have the loaded image blurred and offset by 1 pixel

http://jsfiddle.net/gpxLs2kz/
http://jsfiddle.net/yrgg9j8r/

the fiddle code is the same, but the first fiddle uses fabric.js 1.5.0 and the second fiddle uses fabric.js 1.6.0-rc1 from the repo's dist folder

opening the second fiddle in firefox or safari does not blur the image like chrome does, but you can notice the offset by switching the tabs

edit: blurring/offset happens in IE11 as well

**Comment by asturur** [comment]
fabric.Image.prototype.strokeWidth = 0
and it renders as 1.5.0

After 1.5.0 we uniformed object width calculation and started to count strokeWidth even when it has no strokeColor.
