### ISSUE TITLE
Loading from JSON with SVG

### ISSUE THREAD

**Issue by KoIIIeY** [kangax/fabric.js#2571]
Example 1:
```
            fabric.Image.fromURL('/userboards/board-img/stickers/'+id+'.svg', function (oImg) {
                canvas.centerObject(oImg);
                canvas.add(oImg);

                canvas.setActiveObject(oImg);
            });
```
Example 2:
```
         fabric.loadSVGFromURL('/userboards/board-img/stickers/'+id+'.svg', function(objects,options){
                var sticker = new fabric.util.groupSVGElements(objects,options);
                sticker.set({ scaleX: $scope.zoom / 100, scaleY: $scope.zoom / 100 })
                    .setCoords();

                canvas.centerObject(sticker);
                canvas.add(sticker);

            }, function(item, object){

            });
```

After saving to JSON and reloading, in first example all ok, in second example, SVG drawed incorrectly.
SVG for test - http://board.sa-wd.ru/userboards/board-img/stickers/1.svg

**Comment by KoIIIeY** [comment]
Inkscape can't load linked SVGs, so I need second variant to work.

**Comment by asturur** [comment]
you should specify what is drawed incorrectly.
Example 1 and Example 2 differences have nothing to do with linked SVG, in first example you are loading svg as an image.

Please use the latest source code from github, build the library and the problem should be gone.
i think is related to #2456.

Please search in old issues before opening new.
