### ISSUE TITLE
Allow for a number when using originX and originY

### ISSUE THREAD

**Issue by VictorHagsand** [kangax/fabric.js#2572]
Would it be possible to add type = number when setting originX and originY to allow us to set any position as the origin?

**Comment by asturur** [comment]
it would be a huge change.
would be easier to override the transform method and add an additional translation relative to object center.

what use case do you see for this?

**Comment by VictorHagsand** [comment]
I just thew it out here since i had no idea if it was a big change or not.
The use case for me is to be able to add additional origins like baseline for text and that top is supposed to be top-line of text, not top of box (i use external stuff to get those values).
Feel free to reject if you thing the job it to big for the value : )
