### ISSUE TITLE
StrokeDashArray not work when using toDataURL()

### ISSUE THREAD

**Issue by dannyto** [kangax/fabric.js#2573]
Hi there!

I'm new one, i have using fabric to render image from json, but after render i use toDataURL() to get base64string. it does not show dash line.
My code look like:
cans = fabric.createCanvasForNode(widthImg, vHeight);
cans.loadFromJSON(jsonObj);
cans.toDataURL();

Someone can help please!

**Comment by asturur** [comment]
Please add a jsFiddle that demonstrate the bug.
