### ISSUE TITLE
Text backgroundcolor with paddding

### ISSUE THREAD

**Issue by CrackerakiUA** [kangax/fabric.js#2574]
When i am adding padding with backgroundColor to an itext all text background get colored, but padding is empty, is possible to add that background to padding also?

**Comment by asturur** [comment]
No, padding is the distance between object and controls.

**Comment by CrackerakiUA** [comment]
Any other way to success that?

**Comment by asturur** [comment]
You can group with a rect, but you will loose editing capability.
You can extend iText class and override the renderBackground method to include padding.

**Comment by friday** [comment]
If someone finds this issue looking for help: I've created a small wrapper to make background color span all the way to the controls.
http://codepen.io/fullkornslimpa/pen/YpOwWm?editors=1010
https://gist.github.com/friday/1835832abff3b467607c1378c178a417

It's not very well tested (you'll likely need to tweak/hack it further).

**Comment by brijeshb42** [comment]
Here is a solution that I implemented - 

```js
var TextboxWithPadding = fabric.util.createClass(fabric.Textbox, {
  _renderBackground: function(ctx) {
    if (!this.backgroundColor) {
      return;
    }
    var dim = this._getNonTransformedDimensions();
    ctx.fillStyle = this.backgroundColor;

    ctx.fillRect(
      -dim.x / 2 - this.padding,
      -dim.y / 2 - this.padding,
      dim.x + this.padding * 2,
      dim.y + this.padding * 2
    );
    // if there is background color no other shadows
    // should be casted
    this._removeShadow(ctx);
  }
});
```

But with new fabric updates, this method will have to be synced with that of `fabric.object`.

**Comment by friday** [comment]
I found a more "direct" approach, by overriding the methods used to get dimensions (moving padding from `_calculateCurrentDimensions()` to `_getNonTransformedDimensions()`). It seems to be working better than the suggestion above for making sure the padded background aligns with the controls and scales proportionally.

I removed `strokeWidth` from the `_getNonTransformedDimensions()` calculation, since I don't think it applies to text (at least not in my tests).

```js
fabric.Text.prototype.set({
  _getNonTransformedDimensions() { // Object dimensions
    return new fabric.Point(this.width, this.height).scalarAdd(this.padding);
  },
  _calculateCurrentDimensions() { // Controls dimensions
    return fabric.util.transformPoint(this._getTransformedDimensions(), this.getViewportTransform(), true);
  }
});
```

**Comment by rohitgargi** [comment]
Hi One query... @friday 
While creating a box with **_getNonTransformedDimensions** and  **_calculateCurrentDimensions**, it is perfectly working. But if I save this to server and then trying setting these two properties, that time it is not rendering. 

I am using canvas.getObjects() to traverse all the objects and setting these two  properties as you mentioned.

And finally calling canvas.renderAll() function.
Fabric version - 2.4.6

Please suggest something.

**Comment by SakifKhan98** [comment]
Hi @friday Sorry, I am a bit late to the party.

I have been working with fabricJS now for a few months. For adding "padding" in textbox I have used @brijeshb42 's method. But the padded background does not align with the control box perfectly. Then I used the methods you have declared in your last comment in this thread, but it also do not fix the problem. 

The control box distance remain the same whether I scale the object to bigger or smaller. Can you please put some light on this regard? that how to apply your mentioned method perfectly? TIA

**Comment by bilal-uforia** [comment]
> I found a more direct approach, by overriding the methods used to get dimensions (moving padding from `_calculateCurrentDimensions()` to `_getNonTransformedDimensions()`). It seems to be working better than the suggestion above for making sure the padded background aligns with the controls and scales proportionally.
> 
> I left out `strokeWidth` from the original `_getNonTransformedDimensions()` calculation, since I don't think it applies to text (at least not in my tests).
> 
> ```js
> fabric.Text.prototype.set({
>   _getNonTransformedDimensions() { // Object dimensions
>     return new fabric.Point(this.width, this.height).scalarAdd(this.padding);
>   },
>   _calculateCurrentDimensions() { // Controls dimensions
>     return fabric.util.transformPoint(this._getTransformedDimensions(), this.getViewportTransform(), true);
>   }
> });
> ```
> 
> Update 2021: If anyone is having issues with this solution please try to fix it yourself. Don't tag me. I haven't touched this code in years.

This will add padding  to this.width and this.height to textbox every time when textbox width or height is changed through controls if object width is moved to 600 and we have padding of 100 then it will move to 700
