### ISSUE TITLE
warning at line 6130

### ISSUE THREAD

**Issue by haider-ali** [kangax/fabric.js#2577]
i think this will resolve it

ctx.imageSmoothingEnabled   =  ctx.webkitImageSmoothingEnabled || ctx.mozImageSmoothingEnabled || ctx.msImageSmoothingEnabled|| ctx.oImageSmoothingEnabled ;
ctx.imageSmoothingEnabled       = this.imageSmoothingEnabled;

**Comment by asturur** [comment]
would not be better this?

ctx.imageSmoothingEnabled = ctx.imageSmoothingEnabled || ctx.webkitImageSmoothingEnabled || ctx.mozImageSmoothingEnabled || ctx.msImageSmoothingEnabled || ctx.oImageSmoothingEnabled;
ctx.imageSmoothingEnabled = this.imageSmoothingEnabled;
