### ISSUE TITLE
Post Large Base64 Data

### ISSUE THREAD

**Issue by pranavcp** [kangax/fabric.js#2579]
Hi,
With fabric I have exported based64 data. but for the large images base64 response showing blank in ajax. is there any way we can compress the base64 data or post the same to the server from canvas?

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group (https://groups.google.com/forum/#!forum/fabricjs) or on StackOverflow (http://stackoverflow.com/questions/tagged/fabricjs) where someone will usually assist you.

The issue tracker is only for bugs (with reproducible minimal test case) and feature requests.

Thanks for your understanding!
