### ISSUE TITLE
Calculate Canvas Filled Pixels

### ISSUE THREAD

**Issue by MULLAINATHAN** [kangax/fabric.js#2583]
Hi, I need to find out canvas filled area ( Total filled pixels count ). 
Please let me know the solution ASAP.
Thanks in advance.

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group (https://groups.google.com/forum/#!forum/fabricjs) or on StackOverflow (http://stackoverflow.com/questions/tagged/fabricjs) where someone will usually assist you.

The issue tracker is only for bugs (with reproducible minimal test case) and feature requests.

Thanks for your understanding!
