### ISSUE TITLE
Skew feature

### ISSUE THREAD

**Issue by uimos** [kangax/fabric.js#2585]
I glad that they added skew feature in to fabric.js#1.6.0-rc.1

I tried it personally but I didn't get it to work. Anyone have this problem?

I try to simulate in jsfiddle but it work just coordinate is not right.

Here is sample code. You are able to shift-drag to skew but the location of object is off.
http://jsfiddle.net/uimos/wxte50gg/

**Comment by asturur** [comment]
The fiddle works good.
You press shift, you fo with cursor over mt or mb corner and you go right left to skewX
You press shift, you fo with cursor over ml or mr corner and you go right left to skewY

**Comment by uimos** [comment]
Now that you mention. I notice that it work find on my windows but not my mac. 

I tried to change my mac resolution, the location still off though.

**Comment by asturur** [comment]
Location of what? can you be more specific or post a screenshot or a video?

**Comment by uimos** [comment]
As you can see in the gif I capture, I click circle but it selected triangle.

![skew](https://cloud.githubusercontent.com/assets/7019896/10758729/271c9c00-7cee-11e5-82da-acc416a90633.gif)

**Comment by asturur** [comment]
I think is some issue with retina scaling.
Can you check if with latest commit, https://github.com/kangax/fabric.js/pull/2580 the problem has been solved?

**Comment by uimos** [comment]
I have tried checkout the latest commit and it didn't work.

Other than that, I noticed that skew feature is not working perfectly with clip. Once I skew an image, it will go outside the clipping area.
http://jsfiddle.net/uimos/bntepzLL/1/

**Comment by asturur** [comment]
No the clipping aera get skewed with the image.
I have to try it on a really mac or emulating the dpi scale.

**Comment by asturur** [comment]
http://jsfiddle.net/wxte50gg/1/

can you check this for the original problem? leave out clipping problem for now.

**Comment by uimos** [comment]
Yup, this is working for me, the code is from #2580 ?

**Comment by asturur** [comment]
yes. I was killing retina scaling each renderAll.
So i close this issue, clipTo has so little rules and restriction and behaves unpredicatably in my opninion.if you are  clipping the object and not the canvas, the clip area is getting the object transformation, and so skewing.

**Comment by uimos** [comment]
@asturur thanks. Since you doing the math of skew, do you know the math to reverse it? The clipTo have to give the reverse calculation so that skewing, enlarge won't affect the clipping area. 

For example:
```javascript
// get object scaleX and scaleY, reverse it by using 1/scaleX
var scaleXTo1 = (1 / this.scaleX);
var scaleYTo1 = (1 / this.scaleY);

//apply reverse scale value to scale
ctx.scale(scaleXTo1, scaleYTo1);
```

So I think what I need is:
```javascript
//get the calculation of reverse skewX and skewY
var skewXReverse = ...
var skewYReverse = ...

//apply transform method
ctx.transform(0, skewXReverse, skewYReverse, 0, 0, 0, 0) 
```

Really appreciate if you can help with this.
Thanks.

**Comment by asturur** [comment]
I check the clipTo function with a bit of time and i tell you if we can reverse.
i think there is no problem.
