### ISSUE TITLE
1.6.0-rc1 multitouch not working with gesture

### ISSUE THREAD

**Issue by handersen** [kangax/fabric.js#2586]
Multitouch support seems to be broken with 1.6.0-rc1 (works with 1.5)

Tested a build with NODE build.js modules=ALL based on the current version from https://github.com/kangax/fabric.js (downloaded as zip 27 oktober 2015)

Everything seems fine except multitouch support is not working.

Is this a know issue?
Any help with this is really appriciated. 
Thanks in advance.
----
/* build: `node build.js modules=ALL minifier=uglifyjs` */

/*! Fabric.js Copyright 2008-2015, Printio (Juriy Zaytsev, Maxim Chernyak) */
 

var fabric = fabric || { version: "1.6.0-rc.1" };

if (typeof exports !== 'undefined') {

  exports.fabric = fabric;

}

**Comment by mobidev111** [comment]
This is an unresolved issue: https://github.com/kangax/fabric.js/issues/2496

**Comment by asturur** [comment]
@handersen http://jsfiddle.net/asturur/mu78qc7a/

Could you try here please?

**Comment by handersen** [comment]
Hi Asturur,

**Comment by asturur** [comment]
Yes i noticed the problem.
I'm not event or event.js expert, it will require time for me. At least is not broken anymore.

The point is that it looks like the event is fired continuosly instead of everytime we move finger.

**Comment by pepijnolivier** [comment]
Hi @asturur @handersen 

I'm also experiencing this issue, where scaling is happening way too fast. How should be go about fixing this. I've tried throttling the function but to no avail.

**Comment by asturur** [comment]
gonna check this evening. i ll report here.

**Comment by asturur** [comment]
my touch device is not working tonight,
I have uploaded a fix-try for the touch zooming error, can someone try:
http://jsfiddle.net/asturur/mu78qc7a/

please be sure you reload all the cache and do not use the old fabric.js i uploaded a new one now.

**Comment by asturur** [comment]
ok it looks like it is working good now!

**Comment by handersen** [comment]
Works well now. Thanks for your work with this. Verified it works with iPad, iPhone, Notebook with touch, Samsung Galaxy Tab S.  I updated the jsfiddle to use http instead of https as there seems to be missing a certificate at your domain. But after that it runs. Updated http://jsfiddle.net/mu78qc7a/4/

**Comment by asturur** [comment]
great! yes i have self signed certificate that nowadays means that your device is gonna explode or something bad will soon happen 
:( i m friendly hosted there.

**Comment by pepijnolivier** [comment]
Thanks for the quick fix @asturur, you're a lifesaver

**Comment by handersen** [comment]
a small observation - minor issue. I did further test and noticed that the center for the transformation seems to be the center point of the image and not the center point of the multi touch event. It was the same problem in 1.5 so not a new issue but it would be great if it can be improved in the future. Try zoom using multitouch in the center of the image. Eveything works perfect. Then reload and try zoom in the corner of the image and the zoom offsets.

**Comment by asturur** [comment]
When you scale the object, top and left have to be changed to mantain position of the object
Actually fabricjs supports center and the 8 corners around as "anchors". it does not support center of touch point or any other point.

**Comment by darjiyogen** [comment]
Above changes in `_setObjectScale` works fine for Image but breaks for Textbox.

 this._setObjectScale(new fabric.Point(t.scaleX * dim.x * s / target.scaleX, t.scaleY * dim.y * s / target.scaleY),t, lockScalingX, lockScalingY, null, target.get('lockScalingFlip'), dim);

I am facing issue with Textbox when use two finger scaling, slightly scaling the text object dramatically and make it impossible to use.

I am using fabric 1.6 and Event.js with modified __onTransformGesture version.

Can anyone please help me to resolve above issue?
