### ISSUE TITLE
Removing moving object throws error

### ISSUE THREAD

**Issue by VictorHagsand** [kangax/fabric.js#2587]
When doing object.remove, canvas.remove(object) or similar on a moving object, the object gets removed but i also get an error:
fabric.js:19636 Uncaught TypeError: Cannot read property 'split' of undefined

When removing all objects in a group it does not throw an error but it leaves an empty object behind even though i recalculate the group (works perfectly on a group not moving).

**Comment by asturur** [comment]
Hello, i know this issue is old now, but do you have a simple setup to let me check the bug and actually fixing it?

**Comment by VictorHagsand** [comment]
This was quite some time ago : )
Either we worked around it somehow or it was fixed since i reported it cause its not showing up in our current build of the software.

**Comment by asturur** [comment]
```
// clear canvas
canvas.clear();

// remove currently selected object
canvas.remove(canvas.getActiveObject());

// add red rectangle
var r = new fabric.Rect({
  width: 50,
  height: 50,
  left: 50,
  top: 50,
  fill: 'rgb(255,0,0)'
});

r.on('moving', function() {
  if (r.left > 300) {
    canvas.remove(r);
  }
});

canvas.add(r);
```

tried this in kitchensink and everything looks fine.
