### ISSUE TITLE
Multiplier in toDataURL not working 

### ISSUE THREAD

**Issue by Stefanoviic** [kangax/fabric.js#2589]
I can't seem to get the multiplier within toDataURL working with the latets fabric from github. It is multiplying the canvas width/height, but the content within is not multiplied. See here: http://jsfiddle.net/9WWtV/24/

Any thoughts?

**Comment by asturur** [comment]
I think is related to one of latest fixes.
http://jsfiddle.net/9WWtV/25/

you built the library after #2545 but before #2580.
Se updated fiddles, it is fixed.
(be aware my server has problem with https and you have to manually accept the connection to it)

**Comment by bpiviqd** [comment]
is It already fixed? i'm using v1.6.0-rc.1 and having the same issues. The canvas is multiplied but the object inside it isn't.

**Comment by asturur** [comment]
build the latest version and it should be ok.

**Comment by bpiviqd** [comment]
Thank you @asturur  I get the latest build from your answer in #2592
