### ISSUE TITLE
Change default image strokeWidth to 0

### ISSUE THREAD

**Issue by asturur** [kangax/fabric.js#2590]
I propose this change to avoid fuzzyness of images in standard setups.

Also i would add a comment in the property of fabric.Image.prototype.strokeWidth that using even numbers produce better results.

Update of tests is necessary of course.

@kangax, put approved label or trash the issue.

**Comment by kangax** [comment]
Is current strokeWidth == 1? How would this look differently?

**Comment by asturur** [comment]
current strokeWidth is inherited from fabric.Object and is 1.

a border that is wide 1 pixel create a displacement of the picture of half pixel, with drawing across pixels and blurriness.

border of 0 or 2 does not create this issue.

i think we should change it for image class.
