### ISSUE TITLE
Text object with whitespaces in the end of line doesn't render correctly on node engine

### ISSUE THREAD

**Issue by bambinnesss** [kangax/fabric.js#2591]
Hi!
I found an issue, it can be a bug in fabric library.

Text object that consists from two lines and has align "center", has different results on rendering in browser and on node side if it has whitespaces in the end of line. I checked with fabric 1.5.0 and 1.6.0-r.c.1 versions and both has same results.

Node:
![nodeengine](https://cloud.githubusercontent.com/assets/3115283/10792888/e2aa032c-7d8e-11e5-9560-ac2dd895ccc0.jpg)

Browser:
![captureeditor](https://cloud.githubusercontent.com/assets/3115283/10791943/eafec098-7d8a-11e5-85eb-fa3bcbddfda9.PNG)

 Text object shode have next properties:
 text value: "Line1         \nSecond line" 
align: "center"

Seems like whitespaces trimmed on node side but in browser it looks good.

**Comment by asturur** [comment]
Most of the differences from nodejs and browser are from how libcairo renders whitespaces of text.
I do not think this is a fabric bug.

**Comment by bambinnesss** [comment]
thanks for info @asturur! I'm also was trying to find a reason in fabric and can't find it. True, perhaps it's a libcairo bug.
Maybe fabric can handle it, what is a priority of bugs like this?

**Comment by asturur** [comment]
I would prefer to help libcairo bugs than make a patch in fabricjs.
we cannot fix it here. Maybe node canvas could manage it in some way. I'm not really expert of node or so much c++ expert to go there and check.

**Comment by bambinnesss** [comment]
ok, thanks for advice! Maybe I will try to create some local workaround to prevent cases like this
