### ISSUE TITLE
Group Serialization.

### ISSUE THREAD

**Issue by CrackerakiUA** [kangax/fabric.js#2594]
When i create an group and add it to canvas, in time i serialize the canvas, by default "_objects" of that group is not saved. When i add them into toObject('_objects') it saved it, but later when i am loading them, i am getting error that `this._objects[0].get is not a function`. I guess that we can't save those objects in this way.

**Comment by asturur** [comment]
as always post a fiddle please or we cannot provide help.

**Comment by CrackerakiUA** [comment]
i build one, but i see that is in the newest version that is fixed so iit's not a bug. http://codepen.io/Crackeraki/pen/YyvZYx?editors=101
