### ISSUE TITLE
strokeLineCap messes strokeDashArray up

### ISSUE THREAD

**Issue by k3sh** [kangax/fabric.js#2595]
First off: thank you guys for this library, great work :+1: 

There is a little bug in my use case of fabric.js:

I'm drawing a dashed line and a dashed rect, but there is an issue when setting the strokeWidth too high for the line/rect to draw the strokeDashArray properly.

Example:
if ```strokeDashArray: [10,2] ``` and the ```strokeWidh: 1``` everything's fine, but if I set ```strokeWidh: 5``` (anything higher than 1)  the line/rect isn't dashed anymore.

I found out, that setting ```strokeLineCap: 'square'``` messes it up

Fiddle - Example: [jsfiddle](https://jsfiddle.net/kesh23/bf56wtkc/)

Expected behaviour: The dashed line/rect should be drawn correct regardless of strokeWidth

**Comment by asturur** [comment]
Is not messed up. is how square workds. you  have to make strokeDash with more space between "black and white".

**Comment by k3sh** [comment]
thanks for the explanation :)
