### ISSUE TITLE
Multitouch zooming is buggy on Android

### ISSUE THREAD

**Issue by finom** [kangax/fabric.js#2597]
There are problems appear when I try to resize object with 2 fingers. An object goes smaller and I cannot do anything with it.

Open [this page](http://fabricjs.com/touch-events/) on Android browser (not Chrome) and try to zoom with 
2 fingers.

I have this problem on Android 5, don't know does it appear on android 4 or 6.

Let me show you some screenshots. They just reproduce what do I see on my Android.

The original dog: 
![](http://i.imgur.com/xH61i7e.png)

And that's what I get after I touch an object with 2 fingers:
![](http://i.imgur.com/AcZhEb7.png)

Any thoughts? As quick and dirty solution can you tell me how to turn off multitouch?

**Comment by asturur** [comment]
@finom please could you try if at least it works here?
i do not know which version is on fabricjs.com now.

This is latest source + #2599

http://jsfiddle.net/asturur/mu78qc7a/

**Comment by asturur** [comment]
this is with skewed image.
http://jsfiddle.net/asturur/mu78qc7a/1/

**Comment by finom** [comment]
@asturur Used your code + provided fabric version [on jsbin](http://output.jsbin.com/dehema/) and it still doesn't work.

**Comment by asturur** [comment]
I tried on chrome and standard android browser on my phone with android 5.1.1.
It zoom correctly. The problem is that the action is continuos. So you scale a bit, you leave fingers on, and it shrinks continuosly or enlarge continuosly. I should see a console.log() of the parameter that we are receiving, but on mobile i do not know how to do it.

Anyway you should see a different behaving from when you opened the issue, am i right?

**Comment by asturur** [comment]
https://jsfiddle.net/asturur/mu78qc7a/2/embedded/result/
(so i can open from my phone)

**Comment by finom** [comment]
@asturur yes I have another behavior using version you provided (1.6.0-rc.1) but it still very buggy. It zooms up the page, flips an object etc. Your latest link doesn't work on my Android browser at all.

**Comment by asturur** [comment]
yeah i noticed. too slow the canvas and does not load image at all...

**Comment by goodcode** [comment]
We observe the same issue with version 1.6.5 on my Android 7.0 phone. When touched with two fingers the image sometimes becomes too small or too big or it twists around.It happens every time in our project and in that way the touch gestures are unusable. On the jsfiddle demo it's a little hard to reproduce but still after a few two finger gestures you will notice it:
https://jsfiddle.net/wengn8e6/11/
