### ISSUE TITLE
positioning broken with retinaScaling on 1.6.0-rc.1

### ISSUE THREAD

**Issue by kazkovsky** [kangax/fabric.js#2600]
Hello. There is a problem with elements positioning with retinaScaling enabled. Upper canvas has original (not modified) width and height, and lower canvas has modified width and height with pixel ratio. I'm using clipping:

```
let clipRect = new fabric.Rect({
      left: clipping.left,
      top: clipping.top,
      width: clipping.width,
      height: clipping.height,
      fill: 'rgba(0,0,0,0)',
      transparentCorners: false    });

    this.fabric.clipTo = function(ctx) {
      clipRect.render(ctx);
    };
```

And clipping is not scaled properly (appears on different positions with retina enabled), also adding objects (top/left) positions are broken - top/left positions are not scaled for higher retina displays.

IMHO it should be transparent, and all positions dimensions should be scaled automatically when entering retina mode. Now, programmer must detect retina by himself and try to adjust width/height every time he is adding objects/clipping getting and setting positions.

**Comment by asturur** [comment]
Can you post a jsfiddle with your particular problem?

**Comment by kazkovsky** [comment]
I tried to reproduce this error on this version of -rc.1:

http://fabricjs.com/lib/fabric.js

It works OK

But on my project there was this version:

https://raw.githubusercontent.com/kangax/fabric.js/master/dist/fabric.js

And it doesn't work well. Maybe it's older build without recent fixes for retina?

**Comment by asturur** [comment]
Or with recent fixes that break retina.
Please provide a jsfiddle with your setup.

this is a built version with latest source. https://www.deltalink.it/andreab/fabric/fabric.js

**Comment by kazkovsky** [comment]
With this version embedded: https://raw.githubusercontent.com/kangax/fabric.js/master/dist/fabric.js
Here is the error: https://jsfiddle.net/79sb50tn/

It seems, that new version fixes that, please check

**Comment by hdogan** [comment]
toDataURL (left/top/width/height calculations) for the fabric.Image still buggy with retina displays.

**Comment by asturur** [comment]
can you post a fiddle with the problem?
