### ISSUE TITLE
mousewheel function

### ISSUE THREAD

**Issue by saran110313** [kangax/fabric.js#2602]

**Comment by saran110313** [comment]
how to solved the image object mousewheel zooming function server to client .

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group (https://groups.google.com/forum/#!forum/fabricjs) or on StackOverflow (http://stackoverflow.com/questions/tagged/fabricjs) where someone will usually assist you.

The issue tracker is only for bugs (with reproducible minimal test case) and feature requests.

Thanks for your understanding!
