### ISSUE TITLE
How could I change the layer of Image?

### ISSUE THREAD

**Issue by YangChueng** [kangax/fabric.js#2604]
![image](https://cloud.githubusercontent.com/assets/8767429/10932747/5b28c00c-830e-11e5-8a8b-e3cba3651a33.png)

Here's the demo! I wonder if there were some methods to change the layer of each images.
The latter added image like the green circle could be covered over by the earlier one like blue?

**Comment by asturur** [comment]
please check fabricjs staticCanvas documentation on fabricjs.com.
Search for bringForward and bringFront methods.

**Comment by YangChueng** [comment]
yeah,so I am not familiar with API.Thank U very much.
And if you dont mind,can you tell me how to get the previous object of current active one?

**Comment by asturur** [comment]
what do you mean by previous?
Previously selected or previous in stack?

**Comment by YangChueng** [comment]
its previous in stack

**Comment by asturur** [comment]
canvas.getObjects() gives you array of objects on canvas.
canvas.getActiveObject() gives you reference of the selected Object.
Go trough array, compare the values with the activeObject when it matches, take the index -1.
This is only thing that comes to my mind.

**Comment by YangChueng** [comment]
Tanks a lot.
I have tried and it works.
At first, i thought already there had some defined method about it.
Anyway,have a good day.

**Comment by asturur** [comment]
Maybe is an idea for a feature.
something like "getObjectStackIndex()"
