### ISSUE TITLE
Aligning guideline: wrong position when zoom and pan

### ISSUE THREAD

**Issue by Colmea** [kangax/fabric.js#2606]
When using the aligning guideline lib, if you zoom and pan canvas, the guideline's position are wrong (snap and detection is ok, it's just the render of the guideline).

Here is a JSFiddle to reproduce the bug: https://jsfiddle.net/x25d4wss/1/
Steps:
1. Zoom (mouse scroll) => zoom and pan is updated
2. Move a box next to another one to test the aligning guideline
3. Guideline is at a wrong position.

Important point: after some tests, it appears that **panning** canvas is the only action to do to have this bug (I think zoom is not involved).

**Comment by kangax** [comment]
Sorry but aligning guidelines are not officially supported anymore.

**Comment by Gilbishkosma** [comment]
@kangax what's the other way you suggest to enable guidelines in the canvas?
