### ISSUE TITLE
Strange behavior of the "mouse:out" event?..

### ISSUE THREAD

**Issue by django43ru** [kangax/fabric.js#2611]
I try to work with mouse events. An element of a group must change its color to green on "mouse:over" , and change the color to red on the event "mouse:out". The code looks like this:  (Пытаюсь работать с событиям. Когда указатель мыши находится над некой группой элементов, один из элементов группы меняет свой цвет на зеленый, когда мышь покидает группу, тот же элемент группы меняет свой цвет на красный. Код выглядит так):
```javascript
(function(){
  var html = document.createElement('canvas');
  document.body.appendChild(html);
  
  var canvas = new fabric.Canvas(html, {
    hoverCursor: "pointer",
    selection: false,
  });
  canvas.setHeight(200);
  canvas.setWidth(200);
			
  var s = html.style;
  s.position = "fixed";
  s.left = "100px";
  s.top = "100px";
  s.border = "1px silver solid";

  var rect = new fabric.Rect({
    fill: 'red',
    width: 100,
    height: 100,
    originX: 'center',
    originY: 'center'				
  });
  var text = new fabric.Text('A', {
    fontSize: 30,
    originX: "center",
    originY: "center"
  });
  var card = new fabric.Group([rect, text], {
    left: 10,
    top: 10,
    width: 100,
    height: 100,
    hasControls: false,
    hasBorders: false,
    selectable: false
  });
  canvas.add(card);

  canvas.on("mouse:over", function(e){
    rect.setFill("green");
    canvas.renderAll();
  });
  canvas.on("mouse:out", function(e){
    rect.setFill("red");
    canvas.renderAll();
  });
})()
```

http://jsfiddle.net/django43ru/y9cc5rps/

That works fine, but when only the mouse leaves the group from the top or the left side. When the mouse leaves the group from the bottom/right side, "mouse:out" doesn't work. I did something wrong? (Этот код работает, но только если мышь покидает расположение группы с ее левой стороны, или сверху. Если же мышь покидает группу снизу или справа, то событие  "mouse:out" не срабатывает. Я делаю что-то не так?..)

**Comment by asturur** [comment]
http://jsfiddle.net/y9cc5rps/1/

Yes the wrong part is setting style of the canvas element after fabric.Canvas is created.
