### ISSUE TITLE
Uncaught TypeError: this.text.split is not a function

### ISSUE THREAD

**Issue by apoolla-cb** [kangax/fabric.js#2613]
I have a jsfiddle here: http://jsfiddle.net/anandpoolla/ry76jseh/1/

If you add a custom text, it throws that error in fabric.min.js on line 6.

Can you please take a look?

Thanks,
Anand

**Comment by asturur** [comment]
you are passing to a text constructor an istance of fabric.Text instead of an actual normal TEXT.

**Comment by apoolla-cb** [comment]
@asturur thank you very much! I have understood and fixed the problem. The jsfiddle is updated with the fix.
