### ISSUE TITLE
Color and Pattern for iText

### ISSUE THREAD

**Issue by tmbnh1** [kangax/fabric.js#2617]
Hi everybody,

Please help me this problem. How to fill color and pattern with svg for iText? The same is background-image is [file.svg] and background-color is [color].

Thank you!

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group (https://groups.google.com/forum/#!forum/fabricjs) or on StackOverflow (http://stackoverflow.com/questions/tagged/fabricjs) where someone will usually assist you.

The issue tracker is only for bugs (with reproducible minimal test case) and feature requests.

Thanks for your understanding!
