### ISSUE TITLE
toDataURLWithMultiplier leaves 1px top and left

### ISSUE THREAD

**Issue by MartinB83** [kangax/fabric.js#2619]
My Canvas:
``<canvas id="js--fabric-canvas" width="400" height="225"></canvas>``

I add an image to my canvas:
```
var canvas = new fabric.Canvas('js--fabric-canvas');
  function initCanvas() {
    url = 'https://s3.eu-central-1.amazonaws.com/eventbaxx/coupon-missing.png'
    fabric.Image.fromURL(url, function(img) {
        img.width = 400;
        img.height = 225;
        canvas.add(img);
        img.selectable = false;

      }, {crossOrigin: 'Anonymous'});
    };
```
Now when exporting the image:
``canvas.toDataURLWithMultiplier("png",2,1)``

I get an image with the dimensions 800*250px as expected.
However, the image is not properly scaled. It leaves exactly ONE pixel on the top and ONE pixel on the left side in transparent behind, crewing up my layout.
This is the image that was exported, so you can see if you open it in photoshop:

https://s3-eu-west-1.amazonaws.com/eventbaxx-uploads/sponsorships/d9ab575691f048?1447237876

**Comment by asturur** [comment]
Please check: #2535 and #2570.
regards.

**Comment by MartinB83** [comment]
thx
