### ISSUE TITLE
fabric.Image.fromObject() doesn't set cookies from Chrome on OS X with fabric.js 1.6.0-rc.1 (and 1.5.0)

### ISSUE THREAD

**Issue by Eli-TW** [kangax/fabric.js#2622]
Smallest case to replicate at http://pastebin.com/YVxrNixX

Creating an image with fabric.Image.fromURL() requests the image via a request that includes cookies correctly. However, fabric.Image.fromObject() does not include the cookies when requesting the source image.

This issue occurs on Chrome Version 46.0.2490.86 (64-bit) but not on Firefox 42.0, on OS X. Firefox sends the ~~headers~~ cookies in both requests.

**Comment by datr** [comment]
Here's a fiddle demonstrating what's happening:

https://jsfiddle.net/f4oef3dg/3/

Both `fabric.Image.fromURL()` and `fabric.Image.fromObject()` call `fabric.util.loadImage()`. See the definition here: https://github.com/kangax/fabric.js/blob/master/src/util/misc.js#L246

The difference is that on the first call crossOrigin is undefined and on the second call it's an empty string. Line 272 sets the crossOrigin property of the image dom element to the empty string which is invalid.

Now according to https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes:

> An invalid keyword and an empty string will be handled as the anonymous keyword.

Setting that to anonymous means no cookies are sent. (I'm not sure this is correct behaviour by the browser for non-cross-origin requests but that's what happens).

**Comment by tgabi333** [comment]
It is still not working in chrome.  The problem is when you serialize image, it gives back 
`crossOrigin: ""` and the condititon when unserializing

`
      if (url.indexOf('data') !== 0 && typeof crossOrigin !== 'undefined') {
        img.crossOrigin = crossOrigin;
      }
`

So it will set `img.crossOrigin = ""` which is a not a valid value so chrome set it to `anonymous`

**Comment by asturur** [comment]
thanks for spotting the problem.

**Comment by saran110313** [comment]
i have add in image function in fabric.js. but free drawing function normal using in node.js. but first i have add in image file and second i have add in path function.but path function move to other position so i remove the image file in server side.how to solve this problem.

**Comment by asturur** [comment]
This has been fixed.
If you know it isn't please tell me.

**Comment by BxB00T** [comment]
This does not appear to be fixed while testing in Chrome
