### ISSUE TITLE
First letter is not accepted in IText and Text when editing

### ISSUE THREAD

**Issue by alexiskattan** [kangax/fabric.js#2628]
I'm having an issue that also appear to be present in http://fabricjs.com/kitchensink/.

First I select everything in a text box, by either pressing ctrl+a, manually, or by triple clicking.  Then I press the letter 'a'.  Nothing happens.  Then I press the letter 'a' again and all the text goes away and the letter 'a' appears.  Is there a way to make it so that all the text will go away on the first letter press?

**Comment by asturur** [comment]
This has been fixed.
Present kitchensink is not updated.
Please download latest source and rebuild the lib.

**Comment by alexiskattan** [comment]
Thanks.  

I rebuilt it (1.6.0-rc.1) and the key is entered on the first time.  However, when I double click the text it doesn't select the whole row/block anymore.  Is that the expected behavior?

**Comment by asturur** [comment]
mmm it should work fine.
i will try with a fiddle as soon as i have time.
