### ISSUE TITLE
canvas backgroundColor does not accommodate for zoom and panning of the canvas

### ISSUE THREAD

**Issue by jtweku** [kangax/fabric.js#2631]
if the canvas has fill color and you start zooming and panning the canvas the background is only showing up the original width and height. this javacript code in the **static_canvas.class.js** below supposed to fix that. 

```javascript
_renderBackgroundOrOverlay: function(ctx, property) {
      
      var object = this[property + 'Color'];
      if (object) {
        ctx.fillStyle = object.toLive
          ? object.toLive(ctx)
          : object;
        ctx.fillRect(
           (-this.viewportTransform[4] * 1/this.viewportTransform[0]),
           (-this.viewportTransform[5] * 1/this.viewportTransform[0]),
          this.width * 1/this.viewportTransform[0],
          this.height * 1/this.viewportTransform[0]);
      }
      object = this[property + 'Image'];
      if (object) {
        object.render(ctx);
      }

    },

**Comment by asturur** [comment]
```
ctx.fillRect(
           -this.viewportTransform[4] / this.viewportTransform[0],
           -this.viewportTransform[5] / this.viewportTransform[3],
          this.width / this.viewportTransform[0],
          this.height / this.viewportTransform[3]);
```

Just in case let's use proper x and y scaling for x and y.
Anyway this need further investigation. I do not know if backgroundImage is supposed to scale or not.
Also gradients should be checked.

**Comment by jtweku** [comment]
thanks,
I made a sample code. if you start zooming out and pan the background color is becoming white.

https://jsfiddle.net/rvj293xw/1/

**Comment by asturur** [comment]
https://jsfiddle.net/asturur/rvj293xw/2/

See updated fiddle with fixed behaviour.
Yes there was a bug in the library.

**Comment by jtweku** [comment]
thank you @asturur !

**Comment by asturur** [comment]
closed via https://github.com/kangax/fabric.js/pull/2632
