### ISSUE TITLE
Serialization / Deserialization not working

### ISSUE THREAD

**Issue by Rhywden** [kangax/fabric.js#2633]
Basic code it boils down to after I banged my head against the wall for some time: 

    canvas.isDrawingMode = true;
    canvas.on('mouse:up', function(options) {
        var t = JSON.stringify(canvas);
        canvas.loadFromJSON(t);
      }
    });

This code does not work as it should. The canvas is drawn upon (DrawingMode is enabled) and what I actually expect is that there should be no changes.

What I'm getting: The drawn lines VANISH after the mouse-up event. And REAPPEAR on mouse-down. Only to vanish again upon mouse-up.

The actual intent was to transmit the stringified canvas to other clients - think of a shared painting website. Obviously, with the loadFromJSON() function not really working, this is a no-go.

**Comment by asturur** [comment]
canvas.isDrawingMode = true;
canvas.on('mouse:up', function(options) {
    var t = JSON.stringify(canvas);
    canvas.loadFromJSON(t);
    canvas.renderAll();
  });

Did you try to render the canvas after reloading it all?
