### ISSUE TITLE
backgroundImage constructor error "Uncaught TypeError: object.render is not a function"

### ISSUE THREAD

**Issue by deenfoxx** [kangax/fabric.js#2635]
See http://jsfiddle.net/wsdwmqta/2/

    // This gives error...
    //   "Uncaught TypeError: object.render is not a function"
    // ...but only when using backgroundImage.
    // Comment out the backgroundImage: line in the construction
    //   below and it will no longer give an error.

    var canvas = new fabric.Canvas('c', {
        backgroundColor: 'skyblue',
        backgroundImage: 'http://fabricjs.com/assets/jail_cell_bars.png'
    });

Found this when attempting to follow tutorials from http://fabricjs.com/fabric-intro-part-1/#canvas

It also gives the same error trying to set the backgroundImage outside of the constructor as documented...

    canvas.backgroundImage = 'http://...';

Also the same error using StaticCanvas... See http://jsfiddle.net/wsdwmqta/3/

**Comment by jarinwhite** [comment]
+1 to this. Having the same problem with both 1.5.0 and 1.6.0-rc1. Any suggestions by any chance?

**Comment by deenfoxx** [comment]
Yes, you SHOULD actually be setting the background via setBackgroundImage(image, callback, options) [see http://fabricjs.com/docs/fabric.StaticCanvas.html#setBackgroundImage].

I left @kangax this issue primarily to let him know that if we are not allowed to set an image in the constructor, then he should should probably update his tutorial with the proper method of setting a background image. And it probably wouldn't hurt to somehow create a workaround so that it could be initialized in the constructor... better than breaking at least.

**Comment by kangax** [comment]
Yep, we need to update tutorial. /cc @asturur @Kienz

**Comment by asturur** [comment]
updated tutorial, you can close this if you merge this other:

https://github.com/kangax/fabricjs.com/pull/103
