### ISSUE TITLE
Docs for Object events are broken

### ISSUE THREAD

**Issue by VictorHagsand** [kangax/fabric.js#2636]
Docs says:
Fires:
    event:added
    event:removed
    event:selected
    event:modified
    event:rotating
    event:scaling
    event:moving
    event:mousedown
    event:mouseup

But in reality its:
Fires:
    added
    removed
    selected
    modified
    rotating
    scaling
    moving
    mousedown
    mouseup

**Comment by asturur** [comment]
this is ok in the source code, i think we just need to rebuild docs.

**Comment by asturur** [comment]
https://github.com/asturur/fabric.js/blob/doc/dist/fabric.js#L10805

**Comment by asturur** [comment]
I close it, i rebuilt the docs.
