### ISSUE TITLE
Problem with dimension calculation of i-text

### ISSUE THREAD

**Issue by niekjansenPRODES** [kangax/fabric.js#2637]
We use Fabric to export the canvas as JSON and trying to rebuild the i-text elements in HTML, but we notice there is an difference between de spacing around the i-text characters and the spacing around characters in HTML (while using the same text-options).

Can someone give me a detailed description of the calculation of the dimensions of the i-text element and the difference between the dimensions of the text in HTML? Also keeping in mind different font-sizes, font-families and line-height.

For an more detailed description with example, see the attached document.

[fabric-question.pdf](https://github.com/kangax/fabric.js/files/39833/fabric-question.pdf)

**Comment by niekjansenPRODES** [comment]
Does anyone have an idea on this issue?

**Comment by asturur** [comment]
![image](https://cloud.githubusercontent.com/assets/1194048/6820510/4133f372-d2d0-11e4-8a3d-0fcda6f997e1.png)

took me a bit to find.
This is how we calculate positions in iText...
This come out after comparing how other text editors behave, we did not follow any w3c reccomendation.

hope it helps.

**Comment by niekjansenPRODES** [comment]
Hi asturur,

Wow, thnx for the really clear answer!! This is awesome!
We gonna look into your drawing next week (really busy right now), we'll let you know if we worked it out!

Thnx for the response!
