### ISSUE TITLE
canvas initial size

### ISSUE THREAD

**Issue by n0rb** [kangax/fabric.js#2638]
Hi,

I've searched all over the issues for a few hours but couldn't find anything that explains this behavior:
Since a change in v1.6.0-rc1 the canvas is sized differently.
Before you could set width/height on the canvas HTML element, or setWidth/setHeight on the fabric canvas object.
all working as expected https://jsfiddle.net/7k4922qj/

But since a (imho undocumented) change, the canvas (or just the lower-canvas ?) is sized half of the set width/height
https://jsfiddle.net/nff5un6n/1/

However the upper-canvas seems to be sized correctly, so now the controls don't fit the rendered elements anymore.

How do you correctly set the width and height of the canvas with the recent v1.6.0-rc1 dist ?

**Comment by asturur** [comment]
Are you on a MAC with retina display? on my pc they both look ok.

If so, please download the very latest version from github and build it with the included command.

**Comment by n0rb** [comment]
Oh yes, that seems to be the problem!
here a fiddle with the latest nightly build: https://jsfiddle.net/7j1sy4ca/1/ 
works perfectly fine.

Thanks a lot for the help asturur! 
I actually have the retina resolution disabled due to multiple monitors, but it still seems to play a role in the canvas sizing.

**Comment by asturur** [comment]
fabricjs check for retina presence and implements a scaling hack, doubling ( or whatever is necessary ) the dimensions of the lowercanvas. Then your retina aware internet browser will show you full resolution of the canvas.
