### ISSUE TITLE
text/Itext/textbox textAlign: justify is ignored in svg export

### ISSUE THREAD

**Issue by n0rb** [kangax/fabric.js#2639]
it seems like as if in the current codebase, textAlign: 'justify' on a fabric Textbox is ignored when exporting the canvas to SVG.

see: 
https://jsfiddle.net/7j1sy4ca/2/

in the canvas the text is justified fine.
but if you check the console the same canvas is also exported to svg, and that svg is not aligning the textblocks justified.

here is a fiddle of the exported svg: https://jsfiddle.net/x99gztyx/

**Comment by asturur** [comment]
justified text in svg is not supported. not even in normal text.
This would require creating a tspan for each word with its own positioning.

Is not hard, it just require time.
Do you need it for something important or you just noticed it bu chance?

**Comment by n0rb** [comment]
Well I actually do need it for my project. And the weird thing is, I have
an older Revision of 1.6.0rc-1 saved which does exactly as you are saying.
I am currently AFK but when I get home Ill post said version and also try
to compare them.
Am 20.11.2015 6:45 nachm. schrieb "Andrea Bogazzi" <notifications@github.com

**Comment by asturur** [comment]
i do not think so.
I may be wrong of course, but i did all the svg export things and i remember that text/iText justify was not there.

**Comment by asturur** [comment]
```javascript
    _setSVGTextLineText: function(i, textSpans, height, textLeftOffset, textTopOffset) {
      var yPos = this.fontSize * (this._fontSizeMult - this._fontSizeFraction)
        - textTopOffset + height - this.height / 2;
      textSpans.push(
        '<tspan x="',
          toFixed(textLeftOffset + this._getLineLeftOffset(this._getLineWidth(this.ctx, i)), NUM_FRACTION_DIGITS), '" ',
          'y="',
          toFixed(yPos, NUM_FRACTION_DIGITS),
          '" ',
          this._getFillAttributes(this.fill), '>',
          fabric.util.string.escapeXml(this._textLines[i]),
        '</tspan>'
      );
    },
```

Sadly every tspan contain a text line entirely.
I mark as a  but so maybe someone will fix it as soon as he has time.

**Comment by n0rb** [comment]
oh yeah that makes sense ...
Now I'm a bit confused on what I thought I saw the other day with a half-way working implementation ... 

Anyway, thanks for pointing me to the right functions. 
I might be able to come up with something next week.

**Comment by asturur** [comment]
i made some fixing to normal text export, i will try to fix also the Itext / textbox one.
Not an easy task thought, lot of code needs checking.
