### ISSUE TITLE
Event mousedown doesn't behave properly on Images

### ISSUE THREAD

**Issue by psibi** [kangax/fabric.js#2640]
Minimal code:

```js
var imgUrl = "/some_img.png";
fabric.Image.fromURL(imgUrl, function(delImg) {

    delImg.on('mousedown', function() {
        console.log('mouse down');
    });
    canvas.add(delImg);
}
```

As soon as the image is loaded on the canvas, you can click on the top of the image and see that `mouse down` is printed on the console. Now, move the image to a new position in the canvas and then click over it. Now callback isn't triggered and no `mouse down` messages appears on the console. If you rather click on the original position of the image, then actually the callback is triggered.

**Comment by asturur** [comment]
how did you move the image? programmatically or manually by mouse cursor?

**Comment by psibi** [comment]
@asturur  Manually by mouse cursor.

**Comment by asturur** [comment]
closing as not reproducible.
code for kitchensink
```javascript
fabric.Image.fromURL('http://fabricjs.com/assets/pug.jpg', function(delImg) {
    delImg.on('mousedown', function() {
        console.log('mouse down');
    });
    canvas.add(delImg);
});
```
