### ISSUE TITLE
Memory leak on Pattern

### ISSUE THREAD

**Issue by sorabh86** [kangax/fabric.js#2641]
If you create an offset canvas as pattern to some shape in fabric.js, its renders on every mouse over. its mean source:attribute is updated simultaneously. There may be bug there, code is eating unwanted memory.

var pcanvas = new fabric.StaticCanvas();
var canvas = new fabric.Canvas();

var obj = new fabric.Rect({
    x: 0,
    y: 0,
    width: 200,
    height: 200,
});

var pattern = new fabric.Pattern({
            source:function() {
                pcanvas.setDimensions({
                    width: obj.width,
                    height: obj.height
                });
                console.log('setting pattern');
                return pcanvas.getElement();
            }.bind(this),
            offsetX: (obj.width / 2),
            offsetY: (obj.height / 2),
            repeat: 'no-repeat'
        });

obj.fill = pattern;
canvas.add(obj);

**Comment by asturur** [comment]
I would add a option "static" default to false to creation of pattern. if static is true, the source:function() is executed once and the result is stored.

Memory leak or not this can be an improvement.
