### ISSUE TITLE
Rotation at the central point of picture?

### ISSUE THREAD

**Issue by YangChueng** [kangax/fabric.js#2647]
Is there any default value?Because i used the code below.
  var angle = canvas.getActiveObject().get('angle');
   canvas.getActiveObject().set('angle',angle-90);
   canvas.renderAll();
And the picture easily ran out of the canvas.It seemed to have changed the value of right and left.

**Comment by LeeJim** [comment]
u can just use the function 'object.setAngle(angle)'

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group (https://groups.google.com/forum/#!forum/fabricjs) or on StackOverflow (http://stackoverflow.com/questions/tagged/fabricjs) where someone will usually assist you.

The issue tracker is only for bugs (with reproducible minimal test case) and feature requests.

Thanks for your understanding!
