### ISSUE TITLE
Blurry Text on Mac Retina When Using setHeight/setWidth

### ISSUE THREAD

**Issue by Nelvision** [kangax/fabric.js#2650]
Hello - We're making an effort to scale the canvas to space available in the browser window. It works great on Windows machines, but I'm having an issue with how text is displayed on a MacBook Pro with Retina display when using the setWidth/setHeight properties for the fabric canvas. 

This fiddle shows an example of the code we're using to set the width/height -
http://jsfiddle.net/xmfw65qg/15/

Here's a screenshot from the retina machine -
https://www.dropbox.com/s/9r4h8ayo1jl1t42/MacBook-Retina-setWidth-setHeight.png?dl=0

Here's the same fiddle without using setWidth/setHeight -
http://jsfiddle.net/xmfw65qg/17/

And the screenshot from the retina machine -
https://www.dropbox.com/s/r4alzj5ug08u876/MacBook-Retina-no-setWidth-no-setHeight.png?dl=0

Is there some other means available to do the resize?

Thanks!

**Comment by asturur** [comment]
This problem has been fixed recently.
i belive that if you apply the changes described in this PR:
https://github.com/kangax/fabric.js/pull/2623/files
you should be fine.
You (ALL) should try to search a bit in the closed issue often bugs are already reported and get fixed "quickly".

If it does not fix, comment here, i will reopen the issue.

**Comment by Nelvision** [comment]
I added that new "this._initRetinaScaling();" line to the 1.6.0-rc.1 source and tested, but it introduces two new issues where 1) the selectable area is larger than the actual textbox, and 2) scaling for the textbox doesn't occur unless you additionally call setZoom with an equal zoom factor ratio to that of the setHeight/setWidth. Worth mentioning though that it does fix the issue if I add that new line to the fabric.js hosted on your site (http://fabricjs.com/lib/fabric.js).

This screenshot shows the selectable area is actually 2x the size of the textbox -
https://www.dropbox.com/s/jtblqytpibbdp6d/fabric-2x-selectable.png?dl=0

And here you can see the enlarged cursor -
https://www.dropbox.com/s/0570v1w92zc42cv/fabric-2x-Cursor.png?dl=0
