### ISSUE TITLE
Canvas selection color is gone when clicking the uneditable IText

### ISSUE THREAD

**Issue by jtweku** [kangax/fabric.js#2651]
When I click and edit the un-editable IText, and exit the IText, the canvas selection is not drawing properly, I can still select multiple object but it does not show me the selection rectangle.

http://jsfiddle.net/jtweku/01xp62oo/2/

**Comment by asturur** [comment]
yes something is wrong

**Comment by asturur** [comment]
http://jsfiddle.net/01xp62oo/3/ see updated fiddle, there is a bug, i'm gonna send a PR.
