### ISSUE TITLE
Retina Display v1.6.0-rc.1 - Enlarged (x2) Selectable Area for IText

### ISSUE THREAD

**Issue by Nelvision** [kangax/fabric.js#2652]
I added the new "this._initRetinaScaling();" line to the 1.6.0-rc.1 source in order to remove the blurred text (https://github.com/kangax/fabric.js/pull/2623/files). But it introduces three new issues that I don't yet see reported -
1) the selectable area is larger than the actual textbox, and 
2) scaling for the textbox doesn't occur unless you additionally call setZoom with an equal zoom factor ratio to that of the setHeight/setWidth. 
3) Standard device pixel ratio renders differently than the retina version.

1) View this fiddle on a Mac with Retina and you'll notice the selectable area for the textbox is twice the size as the actual textbox and is shifted down and to the right -
Note: fiddle must be viewed on a Mac with Retina to see the problem
http://jsfiddle.net/xmfw65qg/26/

This screenshot shows the selectable area is actually 2x the size of the textbox -
https://www.dropbox.com/s/jtblqytpibbdp6d/fabric-2x-selectable.png?dl=0

2) This fiddle does setZoom to the same ratio and the textbox scales appropriately, but it still also has the aforementioned problem above -
Note: fiddle must be viewed on a Mac with Retina to see the problem
http://jsfiddle.net/xmfw65qg/25/

And here you can see the enlarged cursor -
https://www.dropbox.com/s/0570v1w92zc42cv/fabric-2x-Cursor.png?dl=0

3) The same fiddle above renders differently on a standard device pixel ratio - 
Note: view this on a standard device pixel ratio
http://jsfiddle.net/xmfw65qg/26/

Here's how that looks -
https://www.dropbox.com/s/9phw2le3oy0u9oe/fabric-1.6-rc.1-with-blur-fix.png?dl=0

Thanks!

**Comment by Nelvision** [comment]
I should add, perhaps there's a better way for me to handle this? Maybe I should make the canvas twice the size for retina or something like that?

**Comment by asturur** [comment]
did you try to download the very latest source code from here and use it all? i may have been too general when i told you to apply that fix, maybe you should just download all the fixes till that pr. or just use latest version.

**Comment by Nelvision** [comment]
Yes, Version 1.5 from this site works quite well except for the blurred text. Ok, I'll try downloading fixes up to that pr. Thanks.
