### ISSUE TITLE
Removing event handler causes error

### ISSUE THREAD

**Issue by forrert** [kangax/fabric.js#2653]
I have a canvas with the following setup:
* event handler 1 registered for 'object:modified' (could be any event, but the error happens as long as I'm working with handlers for the same event)
* event handler 2 registered for 'object:modified'
* event handler 1 unregisters event handler 2 when executing

When the event is triggered, handler 1 runs and removes handler 2. But fabric still wants to execute handler 2 but it has already been unregistered. The following error is printed to the console:
``fabric.js:166 Uncaught TypeError: Cannot read property 'call' of undefined``.

[JS Fiddle](http://jsfiddle.net/qny6q64w/1/)

The error is not always a problem (in that it breaks the application), but it often does not finish the current action (e.g. resizing an object). I think it should be possible to remove handlers for an event, while that event is being handled.

**Comment by asturur** [comment]
http://jsfiddle.net/qny6q64w/2/

testing suggestion of @inssein about settimeout

**Comment by asturur** [comment]
i wenr back on this issue. Regestiring the events in the correct order does not cause any problem.
http://jsfiddle.net/qny6q64w/3/
Do not really know if this is a bug or a misuse.

**Comment by asturur** [comment]
check on #2706
