### ISSUE TITLE
Set defaultCursor in fabric.js more than once

### ISSUE THREAD

**Issue by morninj** [kangax/fabric.js#2655]
I can set `canvas.defaultCursor`, but I can't change it to something else once it's already set. Is this possible?

Here's my code:

    var canvas = new fabric.Canvas('c');

    function setCursor(cursorType) {
        if (cursorType == 'move') {
            canvas.defaultCursor = 'move';
        } else if (cursorType == 'crosshair') {
            console.log('Changing cursor to crosshair'); // this works
            canvas.defaultCursor = 'crosshair'; // this doesn't work
        }
    }

    setCursor('move'); // this works

    // ...

    setCursor('crosshair');

**Comment by asturur** [comment]
i answered on stackoverflow.
