### ISSUE TITLE
I can't select the object by canvas.item(i) 

### ISSUE THREAD

**Issue by xutyne** [kangax/fabric.js#2661]
I  click the button to add image  by Fabric.ImageFromURL ,but  i cant  select the object by   canvas.setActiveObject(canvas.item(i)) ,the consoel    display   the  tips   : (Uncaught TypeError: Cannot read property 'set' of undefined)  ,i cant  solve  this

**Comment by asturur** [comment]
For this kind of questions please use stackoverflow or fabricjs googlegroup
