### ISSUE TITLE
Missing callback calls when cloning objects

### ISSUE THREAD

**Issue by Kitanotori** [kangax/fabric.js#2662]
When cloning canvas shapes (i.e. non-images), most of the respective 'fromObject' methods are missing calls to the callback function. I made a simple patch to the 'clone' method which fixed the issue in my case:

    /**
     * Clones an instance
     * @param {Function} callback Callback is invoked with a clone as a first argument
     * @param {Array} [propertiesToInclude] Any properties that you might want to additionally include in the output
     * @return {fabric.Object} clone of an instance
     */
    clone: function(callback, propertiesToInclude) {
      if (this.constructor.fromObject) {
        var clone = this.constructor.fromObject(this.toObject(propertiesToInclude), callback);
        clone && callback && callback(clone); // Most of the 'fromObject' methods fail to call the callback, so call it here instead
        return clone;
      }
      return new fabric.Object(this.toObject(propertiesToInclude));
    },

**Comment by golive** [comment]
Your code will invoke the callback twice if the fromObject call uses it (for example, on images).
What it will be good is to unify the `fromObject` method for all Object subclasses and always use the callback.

**Comment by kangax** [comment]
This will be changed in 2.0 (they're missing callback because they're synchronous and have different API)
