### ISSUE TITLE
isTouchSupported detection.

### ISSUE THREAD

**Issue by JixunMoe** [kangax/fabric.js#2664]
When Chrome (Canary, 49.0.2578.0) is set to mobile emulation (Android or iPhone), `"ontouchstart" in fabric.document.documentElement;` will always return false.

Which disables touch event binding, `mouse:down` event does nothing.

**Comment by kangax** [comment]
Is there a better check?

**Comment by ncou** [comment]
@asturur : I think that if the test in header.js (line 31) is changed from :

'ontouchstart' in fabric.document.documentElement;
to
'ontouchstart' in window;

It will work. I have made a quick test with the ChromeDev tool and it work fine.
It's also this test who is executed in the touch event lib to detect mobile device or emulator (line 803 for the event.js file).

**Comment by jordan-acosta** [comment]
I ran into this problem today. Touch support detection doesn't seem to work at all, either in desktop Chrome, or Safari Mobile on my iPad.

If no one's working on this, I can submit a PR.

**Comment by asturur** [comment]
i have a surface 4 pro and i got it for this kind of things. I have much to learn about touch detection and touch events, so if you want to open a PR and start talking about it, is welcome

**Comment by jordan-acosta** [comment]
@asturur , I'm developing in Chrome (in mobile mode with the dev tools open), and testing on an iPad Pro 12" with the Apple Pencil, and a Galaxy Note 4 with it's stylus.

Opened a PR with that one line change. Be great if it's really that simple.
