### ISSUE TITLE
Anti-aliasing for scaled down high res images

### ISSUE THREAD

**Issue by benjwalker** [kangax/fabric.js#2665]
When high resolution images are scaled down they quickly become jagged around the around the edge. This could potentially be fixed by applying some form of anti-aliasing such as the step down method.

A good example of this issue is the robot at http://fabricjs.com/ try sizing this down and you'll see the image becomes jagged around the edge as it's sized down and multiple pixels are forced into the space of just one.

![capture](https://cloud.githubusercontent.com/assets/16132800/11557772/6e9a106a-99a6-11e5-9005-6c7d476225dc.PNG)

**Comment by asturur** [comment]
to apply stepdown, when loading image you can setup some resize filter.
there is also the stepdown hack.
https://github.com/kangax/fabric.js/issues/1741
