### ISSUE TITLE
loadFromJSON with custom type(createClass)

### ISSUE THREAD

**Issue by KoffeinKaio** [kangax/fabric.js#2668]
I'm trying to load a json string, but it fails (maybe because of the custom Type)
Error:
TypeError: klass is undefined

at this part:
```javascript
        var klass = fabric.util.getKlass(o.type, namespace);
        if (klass.async) {
          klass.fromObject(o, function (obj, error) {
            if (!error) {
              enlivenedObjects[index] = obj;
              reviver && reviver(o, enlivenedObjects[index]);
            }
            onLoaded();
          });
        }
        else {
          enlivenedObjects[index] = klass.fromObject(o);
          reviver && reviver(o, enlivenedObjects[index]);
          onLoaded();
        }
```

My code:

```javascript
    var canvas = new fabric.Canvas('canvas');
	
	var NamedRect = fabric.util.createClass(fabric.Rect, {
	  type: 'NamedRect',
	  initialize: function(options) {
		options || (options = { });
		this.callSuper('initialize', options);
		this.set('name', options.name || '');
		this.set('roomNumText', options.roomNumText || '');
		this.set('label', options.label || '');
	  },
	
	  toObject: function(options) {
		return fabric.util.object.extend(this.callSuper('toObject'), {
		  name: this.get('name'),
		  selectable: this.get('selectable'),
		  roomNumText: this.get('roomNumText'),
		  label: this.get('label')
    	});
	  },
	_render: function(ctx) {
		this.callSuper('_render', ctx);

		//draw room number
		ctx.font = '20px Arial';
		ctx.fillStyle = '#d3d3d3';
		ctx.fillText(this.roomNumText, -this.width/2+5, this.height/2-5, this.width-10);
		
		//draw label
		ctx.font = '21px Arial';
		ctx.fillStyle = '#0000ff';
		var txtwidth=ctx.measureText(this.label).width;
		ctx.fillText(this.label, -(this.width/2-this.width/2)-txtwidth/2, -this.height/2 + 20, this.width-10);
		
	}
	  
	});
	
	var json='{"objects":[{"type":"NamedRect","originX":"left","originY":"top","left":5,"top":50,"width":50,"height":140,"fill":"lightgrey","stroke":"black","strokeWidth":2,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","rx":0,"ry":0,"name":"room_stairs","selectable":false,"roomNumText":"","label":""}],"background":""}';
	canvas.loadFromJSON(json);
```

**Comment by asturur** [comment]
outside the class costruction, you are missing the:

```javascript
NamedRect.fromObject = function(options) {
    return new NamedRect(options);
}
```

check it from another class to see what i mean


if it won't solve open a stackoverflow question.

**Comment by gjijon** [comment]
Hi KoffeinKaio. If you remember, did you find a solution?

**Comment by KoffeinKaio** [comment]
Hey,
Yeah - exactly what asturur said. I missed the fromObject definition.

Lazy copy of my running object:
`	fabric.NamedRect = fabric.util.createClass(fabric.Rect, {
	  type: 'NamedRect',
	  initialize: function(options) {
		options || (options = { });
		this.callSuper('initialize', options);
		this.set('name', options.name || '');
		this.set('roomNumText', options.roomNumText || '');
		this.set('label', options.label || '');
		this.set('lbl_font', options.lbl_font || '16px Arial');
		this.set('rnr_font', options.rnr_font || '16px Arial');
		this.set('lbl_color', options.lbl_color || 'Black');
		this.set('idoit_type', options.idoit_type || '');
	  },
	
	  toObject: function(options) {
		return fabric.util.object.extend(this.callSuper('toObject'), {
		  name: this.get('name'),
		  selectable: this.get('selectable'),
		  roomNumText: this.get('roomNumText'),
		  label: this.get('label'),
		  lbl_font: this.get('lbl_font'),
		  rnr_font: this.get('rnr_font'),
		  lbl_color: this.get('lbl_color'),
		  idoit_type: this.get('idoit_type')
    	});
	  },
	_render: function(ctx) {
		this.callSuper('_render', ctx);

		//draw room number
		ctx.font = this.rnr_font;;
		ctx.fillStyle = '#d3d3d3';
		ctx.fillText(this.roomNumText, -this.width/2+5, this.height/2-5, this.width-10);
		
		//draw label
		ctx.font = this.lbl_font;
		ctx.fillStyle = this.lbl_color;
		var txtwidth=ctx.measureText(this.label).width;
		ctx.fillText(this.label, -(this.width/2-this.width/2)-txtwidth/2, -this.height/2 + 20, this.width-10);
		
	}
	  
	});
	fabric.NamedRect.fromObject = function(options) {
		return new fabric.NamedRect(options);
	}`

**Comment by zmiju** [comment]
Great solution. And how to code it in angular/typescript?
