### ISSUE TITLE
Shadow in SVG is displaying in wrong location when the object is rotated

### ISSUE THREAD

**Issue by jtweku** [kangax/fabric.js#2669]
the SVG generated from shadow for the rotated object is not in the same position as the in canvas. I am assuming that the x and y position of the shadow does not accounted for the angle in the object's shadow. 

http://jsfiddle.net/1fgk6qoo/

**Comment by asturur** [comment]
Omg, i never noticed this. In the canvas the shadow is managed like a shadow, while in svg we emulate it with a filter that makes a copy of the shadow displaced.
We have to change the shadow offset when exporting to svg to take in account of current rotation.

**Comment by asturur** [comment]
Not a simple fix. i tried couple of hours thinking that rotating shadow offset would help me, but is not that easy. Rotation repeats every 90 degrees and i cannot guess easily the algorithm behind canvas shadow.

**Comment by jtweku** [comment]
I think this should fix it, calculating the rotation modifying the area for the filter to accounted for the rotation.

http://jsfiddle.net/3hnghy3d/

**Comment by asturur** [comment]
Yes it does.
I did same thing, just i did not do "360 - angle"
how did you get to that conclusion? why not just angle?

**Comment by asturur** [comment]
i will make a pr later, so we merge this.

**Comment by jtweku** [comment]
thanks @asturur 
I just playing around and notice that after rotating it the value of offset X and offset Y was the opposite. so I figure it must be in the wrong quadrant.

**Comment by asturur** [comment]
no it is totally right, i m stupid.

if i rotate the object of x, i have to rotate back the shadow of -x to leave it in its original position.

that's all :)

**Comment by asturur** [comment]
closed with latests commit
