### ISSUE TITLE
support RTL languages in ITEXT

### ISSUE THREAD

**Issue by talavishay** [kangax/fabric.js#2673]
i want to implement support RTL languages in ITEXT...
can anyone point me in the right direction ?
or have any recommendations on this issue?

thanks in advanced for any help on this issue..

**Comment by talavishay** [comment]
i now see fabric.js does not support RTL languages...
as mentioned here:
#2374 
is it still true?

i so want to implement that support ..
could you point me in the right direction ? 
or have any recommendations on this issue?

**Comment by talavishay** [comment]
@kangax is there an official statments about RTL support?

im developing an "Ilustrator&phtoshop&indesign" for an 
Online Book Editing App with **backbone & fabric** 

our issue when **editing bulk text in RTL** is a blocking issue for me..
do you think fabric.js can be adapted to RTL ?

or maybe an external solution is more adequate for my niche App
I Must support RTL text editing as if it was reguler html editing like in the google docs..

possible soultion in my mind right now is a new fabric.Text/Image/Object ( just for RTL text editing ) .
this object will have  edit&view modes..
going from edit -> view will result in a rendering of html2Canvas -> to  fabric.Image 
 the power of HTML text editing with the power of a fabric object..
(resize of window/resize of object   will be taken care of by the view.mode of this new fabric.object mechnizm)

besides this issue everything is GREAT and THANK YOU very much for your awesome project..
demo for the app will be post as soon its out of the oven..

**Comment by kangax** [comment]
RTL would definitely be nice to have but unfortunately I can't tell when someone will start working on it. We have lots of issues, requests, etc. and only 2 people maintaining Fabric in a barely part-time sort of way.

**Comment by kangax** [comment]
Contributions are always super welcome!

**Comment by YaakovHatam** [comment]
@talavishay @davidjrice @maxim please look at the issue #2374 i am developing a RTL version please test it
