### ISSUE TITLE
Incorrect object left/top position after group scale and deselect

### ISSUE THREAD

**Issue by scottmilward** [kangax/fabric.js#2676]
I have two rectangle objects both of which have originX and originY set to center.
I then select both of these objects and then modify the groups scaleX  to be larger than 1.
Once I deselect the group the resulting top/left of the left most object seems to be incorrect/changed?

This issue does not seem to happen when both rectangle objects origins are set to left/top.

**Comment by asturur** [comment]
I cannot reproduce.
Can you reproduce on kitchensink and give detailed steps?

**Comment by scottmilward** [comment]
Yes I was able to reproduce the problem on kitchen sink.
- Just draw two rectangles on the canvas side by side.
- Set both rectangles originX and originY to center.
- Take note of the first rectangles left position value before grouping the two.
- Select both rectangles adding them to a group.
- Via the middle right grip point scale the group out to the right a bit.
- Once you deselect the group you will notice the left position value of the first rectangle has changed.

**Comment by asturur** [comment]
this is normal. this happen also for originX left.

the value changes because you need to see the rect in the same position.

you may also be tricked from the transparent border. put strokeWidth to 0 to avoid any visual movement given by the increasing scale factor of the border.
