### ISSUE TITLE
toDataURL Max Multiplier Size

### ISSUE THREAD

**Issue by krusk** [kangax/fabric.js#2678]
I am using toDataURL with multiplier, but it seems to be hitting a max multiplier when I multiply by 30 times (ex. it fails when trying to pass a large file that has been multiplied to a directory or the page crashes all together). Is there a max multiplier? I don't see it documented. Is multiplier tied to system performance?

**Comment by asturur** [comment]
No there is not.
What makes you think you are hitting a cap?

If the page crashes it means you are hitting some limit of the canvas. Do not expect canvas element to produce a 15.000x20.000 png. it will not make it.

**Comment by krusk** [comment]
If I try a large multiplier, the nodejs code I have to filestream crashes. A typical upscaled canvas in my use case is 25799x16743

**Comment by asturur** [comment]
it won't work.
It is 1.7Gigabyte of memory just for the canvas.
Plus the pictures and all other things you have in memory

If you need to make big print files canvas + PNG is not the solution. Not with canvas or node-canvas.

**Comment by krusk** [comment]
If I increased the RAM on the Webserver, would that help. What solutions/options do I have to this issue?

**Comment by asturur** [comment]
This is a per browser limit:

Chrome:
Maximum height/width: 32,767 pixels
Maximum area: 268,435,456 pixels (e.g., 16,384 x 16,384)

Firefox:
Maximum height/width: 32,767 pixels
Maximum area: 472,907,776 pixels (e.g., 22,528 x 20,992)

IE:
Maximum height/width: 8,192 pixels
Maximum area: N/A

IE Mobile:
Maximum height/width: 4,096 pixels
Maximum area: N/A

For node-canvas you should ask to them. They probably now.

**Comment by krusk** [comment]
Thank you.

**Comment by kangax** [comment]
@asturur which IE was it? I'm curious about Edge (new version of "IE")

**Comment by asturur** [comment]
i found this table from oct 2014., edge we can test i have a windows 10 here.

**Comment by krusk** [comment]
I was testing on Chrome and it crashed on something outputted to 25799x16743

**Comment by krusk** [comment]
The solution will need to go cross-browser, but users are expected to be on the latest browsers

**Comment by asturur** [comment]
most people use 32bit version of the browsers, where limit per thread is 2gb. i do not think a  1.7Gb canvas will fit. You have to reconsider your spec or find different solutions.

**Comment by krusk** [comment]
Thanks, I believe one approach is to upload the small canvas (no multiplier) then use something like this to resize in Node: https://github.com/lovell/sharp

Appreciate the guidance!
