### ISSUE TITLE
Last added SVG not removing

### ISSUE THREAD

**Issue by Samvherck** [kangax/fabric.js#2679]
When removing the last added svg object the functionality gets disabled (not selectable anymore) but the SVG itself keeps showing.

This only happens with the last added SVG. For example when adding 3 SVG objects the 2 that are placed first get removed like expected and immediately disappears, it is the last SVG only that shows this issue.

```javascript
fabric.loadSVGFromURL("images/svg/image.svg", function(objects) {
	var object = new fabric.Group(objects);
	canvas.setBackgroundImage(object);
	object.set({ left: 300, top: 300});
	canvas.add(object);
	canvas.remove(object); // Fully removed.
});
fabric.loadSVGFromURL("images/svg/image.svg", function(objects) {
	var object = new fabric.Group(objects);
	canvas.setBackgroundImage(object);
	object.set({ left: 500, top: 500});
	canvas.add(object); 
	canvas.remove(object); // Only functionality removed, but still showing. Does get removed when adding another SVG because it will nog be the last anymore.
});
```

**Comment by asturur** [comment]
It still shows because it is in the background image.
Removing from the canvas as an object does not mean "do not render" it if it is referenced as backgroundImage for the canvas.
