### ISSUE TITLE
Does Fabric support a backing canvas

### ISSUE THREAD

**Issue by krusk** [kangax/fabric.js#2681]
Hi all,
Does Fabric support a backing canvas, and if not, will this be incorporated in the future? I want a small workspace but large output.
Thanks,
K.

**Comment by asturur** [comment]
excuse my ignorance... what is a baking canvas?

**Comment by krusk** [comment]
Apologies for taking a while to reply. I don't believe its an official term, but check this out:
http://stackoverflow.com/questions/23003522/rendering-html-canvas-images-at-high-resolution?lq=1

And these two:
http://output.jsbin.com/kegohufu/1/
http://output.jsbin.com/qomiqoqi/1/

**Comment by kangax** [comment]
We support retina and expose devicePixelRatio — https://github.com/kangax/fabric.js/blob/30c64ec9c115276f14fd83e76ca800002d8f31c1/HEADER.js#L67
