### ISSUE TITLE
loadFromJSON Invalid url

### ISSUE THREAD

**Issue by Samvherck** [kangax/fabric.js#2684]
When using JSON.stringify(canvas) I get a json string as expected with all the objects and SVG background:
```javascript
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABYIAAAObCAYAAADuZfVxAAAgAElEQ…YBDFiWNah/Ks5AAQpQgAIUoAAFKEABClCAAhSgAAWeXeAfixEZAdzf09EAAAAASUVORK5CYII="
```
	
If I use this json string as paramater for the loadFromJSON() method, the canvas gets cleared and rerenderd with the json string data:

```javascript
var json = JSON.stringify(canvas);
canvas.loadFromJSON(json, canvas.renderAll.bind(canvas));
```

The problem happens when I first save it to a .json file and than try to use the json (even if the JSON is completely the same).

```javascript
$.getJSON("json/map.json", function(json) {
	canvas.loadFromJSON(json, canvas.renderAll.bind(canvas));
});
```

This results in an ERR_INVALID_URL:

```javascript
GET data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABYIAAAObCAYAAADuZfVxAAAgAElEQ…YBDFiWNah/Ks5AAQpQgAIUoAAFKEABClCAAhSgAAWeXeAfixEZAdzf09EAAAAASUVORK5CYII= net::ERR_INVALID_URL
	Error loading data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABYIAAAObCAYAAADuZfVxAAAgAElEQ…YBDFiWNah/Ks5AAQpQgAIUoAAFKEABClCAAhSgAAWeXeAfixEZAdzf09EAAAAASUVORK5CYII=
```

**Comment by asturur** [comment]
please provide a jsfiddle with minimal test case.

**Comment by Samvherck** [comment]
Fiddle is giving me trouble using SVG files but I'm working on it. In the mean while I found out that this error only happens using SVG background. A JPG background results in a json object with:
```javascript
"src"="http://localhost/images/bg.jpg"
```
which works so I guess the problem must have something to do with the long SVG URL
```javascript
image/png;base64,iVBORw0KGgoAAAANSUhEUgAABYIAA...
```

**Comment by princ09** [comment]
I am adding SVG using loadSVGFromString. Its work perfectly. then i stored my canvas as json, later when i call loadFromJSON() its gives error saying GET 400 bad request.
Probably bcoz its internally using LoadSVGFromDataUrl or something like this.
Any solution for this?
