### ISSUE TITLE
can i use the data from toDatalessJSON on various devices?

### ISSUE THREAD

**Issue by LeeJim** [kangax/fabric.js#2687]
if i have a json from toDatalessJSON on 1920 x 1080px canvas.
then,how do i use the json data on 1366 x 768px canvas.
ps: if one element's left = 1px; others left = 1920px;

**Comment by krio** [comment]
Instead of resizing the actual canvas and changing the resolution why don't you keep it the same size and then use CSS to scale it on the various devices? That way the internal coordinates will always be the same.

**Comment by asturur** [comment]
you have also viewport option:
canvas.setZoom(Math.max(oldWidth/newWidh, oldHeight/newHeight));

or Math.min as you prefer.

**Comment by LeeJim** [comment]
@asturur 
thanks, it works. but it have a bug.
ii will let every elements zoom even  the element later added

**Comment by asturur** [comment]
If you want to apply same logic but on objects, cycle for objects and
change theyr scale to the same scale you would do on canvas.
This kind on dimensions switching is a custom behaviour for wich fabricjs
is not responsible, you have to build it in your application.


2015-12-18 3:14 GMT+01:00 LeeJim <notifications@github.com>:

**Comment by LeeJim** [comment]
@asturur 
em,i had fixed it.thanks a lot.bro
