### ISSUE TITLE
Changing canvas attributes to not break naming-conventions

### ISSUE THREAD

**Issue by Samvherck** [kangax/fabric.js#2690]
I'm trying to save a canvas object to seperate SQL tables. For this I stringify the json object and send to my MVC Controller, all the binding happens automatically when the model and attributes matches the json object.

The issue is that because the key values from the canvas json-object are backgroundImage,.. I need to break the naming-convention rules for my models, attributes and database. For example backgroundImage should become Background with the necessary capitalized attributes. This  is importent because the FabricJS application will become part of a larger sized application in the future.

Can I change the keys and/or attributes from the canvas object before sending it to my Controller?

```javascript
var cvas = JSON.stringify(canvas);

$.ajax({
   data: cvas
   ....
});

// MVC Controller
[HttpPost]
public void Save(Canvas cvas)
{
    // Handle canvas save
}
```

**Comment by asturur** [comment]
How many of them do you need to change? there is no feature built in for this. You may think of overriding the toObject method with one made by you, but then you have to do same in the "fromObject" method to restore the canvas if you need to.

**Comment by Samvherck** [comment]
I prefer to change all the ones I need: 
- backgroundImage
- icon
- path
- pathOffset
And capitalize their attributes.
If there is no feature for this I guess overriding the toObject/fromObject is a good solution. I'll look in to that, thanks.

**Comment by kangax** [comment]
Yep, it's easy to override and morph into your own version via some sort of a map or some such.
