### ISSUE TITLE
Scaled strokeWidth while resize

### ISSUE THREAD

**Issue by rowdyroad** [kangax/fabric.js#2695]
While I'm resizing object (rect), strokeWidth is resized too.

Can I resize object without strokeWidth resize or it is a bug?

**Comment by asturur** [comment]
No you cant, you are not resizing, you are "scaling"
there is not support in fabricjs for resizing with mouse ( not possible with many shape).
You can , during resizing, change the strokeWidth with strokeWidth / scaling factor.

**Comment by rowdyroad** [comment]
Thanks a lot, worked. But I have scaleX, scaleY factors, that why my top and bottom strokeWidth doesn't match left and right strokeWidth. Can I fix it?
