### ISSUE TITLE
canvas toSVG not saving ids

### ISSUE THREAD

**Issue by suomilapsi** [kangax/fabric.js#2697]
Hello,

It is possible to load SVG with IDs to canvas. With toJSON it is possible to save IDs. With toSVG there seems to be no way to retain IDs?

https://jsfiddle.net/suomilapsi/r9q8anky/1/

Best regads,
suomilapsi

**Comment by suomilapsi** [comment]
https://jsfiddle.net/suomilapsi/r9q8anky/6/
updated

**Comment by asturur** [comment]
Yes, we do not export id to svg elements.

**Comment by dumaron** [comment]
Hi,
I had a similar problem and I've resolved modifying a bit fabric, maybe it can be useful to you too. It's old code, so maybe I'm forgetting something.

Basically I changed this code (in last version on [line 7106](https://github.com/kangax/fabric.js/blob/master/dist/fabric.js#L7106)):
```
markup.push(instance.toSVG(reviver));
```
wtih this:
```
markup.push(instance.toSVG(function(path) {
    return reviver(path, instance);
}));
```

By doing this, you're giving to the `reviver` function the object from where the single piece of the SVG is generated, so you can read from it the id (and every personalized attribute) and update the SVG element (the first argumento of reviver, `path` in my example) accordingly.

**Comment by asturur** [comment]
i do not know if adding option of having a callback and let user add pieces to svg is worth over just exporting the id for everything.
The only bad thing is going around all classes and adding

```javascript
if (this.id && this.id !=='') {
  markup.push('id=',  this.id)
}
```

**Comment by dumaron** [comment]
You're right. It was more a temporary solution for @suomilapsi , although I think this is a simple and straight forward way to give user more power over the SVG generation.

**Comment by asturur** [comment]
Yes true. But at same time i prefer to listen issues of people with svgs, because i would catch potential good features that could be lost with a "solve it by yourself" approach.
