### ISSUE TITLE
`dispose` should clear `activeInstance`

### ISSUE THREAD

**Issue by gonsfx** [kangax/fabric.js#2701]
If it doesn't (current state), the last instance is always leaked even after disposed and removed.

**Comment by asturur** [comment]
You mean something like this?

```javascript
    /**
     * Clears a canvas element and removes all event listeners
     * @return {fabric.Canvas} thisArg
     * @chainable
     */
    dispose: function () {
      this.clear();
      this.interactive && this.removeListeners();
      if (fabric.Canvas.activeInstance === this) {
        fabric.Canvas.activeInstance = null;
      }
      return this;
    },
```

**Comment by gonsfx** [comment]
Exactly.

**Comment by asturur** [comment]
i do not really know the use of tha activeInstance property. track the canvas variable and clean it? and in case of multiple canvases?

**Comment by kangax** [comment]
I agree that we should be clearing it

**Comment by asturur** [comment]
this is a fast pr.

**Comment by asturur** [comment]
proposed this in a PR in dispose method:
```diff
+      var klass = fabric[fabric.util.string.capitalize(this.type)];
+      if (klass.activeInstance === this) {
+        klass.activeInstance = null;
+      }
```

**Comment by kangax** [comment]
@gonsfx out of curiosity, how are you using `activeInstance` and would you be OK if we removed it entirely (as it seems to belong on an application level)?

**Comment by gonsfx** [comment]
@kangax I'm not using it at all, just found out that it can lead to leaks.

**Comment by asturur** [comment]
on #2702 we are deleting it.
