### ISSUE TITLE
Cross origin issues

### ISSUE THREAD

**Issue by armsmani** [kangax/fabric.js#2702]
HI kangax, Is it possible to fix cross origin issues in Fabricjs and AWS? i was tried lot of ways still facing same issues..

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group (https://groups.google.com/forum/#!forum/fabricjs) or on StackOverflow (http://stackoverflow.com/questions/tagged/fabricjs) where someone will usually assist you.

The issue tracker is only for bugs (with reproducible minimal test case) and feature requests.

Thanks for your understanding!
