### ISSUE TITLE
the problem of scaling the group after execute 'canvas.toObject()' in some events

### ISSUE THREAD

**Issue by Eamonnzhang** [kangax/fabric.js#2704]
the #2694 #2549 has been fixed in the latest build version of fabirc,but today I found another problem,
here is the fiddle
https://jsfiddle.net/eamonnzhang/d6oo40nn/1/
If I bind 'mouse:up' event on canvas and execute 'canvas.toObject()' in the listener
After I discard the group,the problem arises again.
If I don't execute  'canvas.toObject()',everything goes well.
I update the fiddle
https://jsfiddle.net/eamonnzhang/d6oo40nn/2/
bind the 'object:modified' event

**Comment by Eamonnzhang** [comment]
I need to save the json of canvas to database after object is modified.is there any other way?

**Comment by asturur** [comment]
if you want to save the json of canvas, after a modification, using object:modifed event is the right thing to do.
