### ISSUE TITLE
Text layer focus/cursor area after setting text attributes

### ISSUE THREAD

**Issue by vniko** [kangax/fabric.js#2705]
If a text layer is  set fontFamily or fontSize attribute (any  that would affect the layer size)
The selectable/focusable  area remains the old (previous) layer size
For example http://jsfiddle.net/vital_n/205n1qfe/14/ 
if you hover a mouse over the text string you can see that the cursor becomes default (not "move") after "r"
Event if you force initDimensions
http://jsfiddle.net/205n1qfe/17/
The focusable area becomes correct only after you click(select) the layer and deactivate it

Probably there's a method to force recalculate these coordinates but i ca't find it. 

I hope i managed to explain the issue )

**Comment by asturur** [comment]
You load the txt on canvas when the font is not loaded yet.

```
var canvas = new fabric.Canvas('canv');

 WebFont.load({
    google: {
      families: ['Montserrat']
    },
   active: function () {
     //all fonts are loaded
     var txt = new fabric.Text("This is a text string",{fontFamily:"Montserrat", fontSize:28});    
     canvas.add(txt);
     canvas.renderAll();
   }
  });
```
