### ISSUE TITLE
Observable::fire - Throws an error in specific situations

### ISSUE THREAD

**Issue by inssein** [kangax/fabric.js#2706]
This is the same issue as: https://github.com/kangax/fabric.js/issues/2653 - but stated differently, and I will probably open a PR once we can agree on a fix.

The Problem: 
If you bind to an event, lets say "mouse:up", and then, onMouseUp, unbind it, it will throw off the count in https://github.com/kangax/fabric.js/blob/master/src/mixins/observable.mixin.js#L102.

The Solutions:
1) Clone the array before iterating over it
2) Unbind inside setTimeout(function(){...}, 0)
3) ...?

The first solution introduces some performance considerations, but I am not sure if it's avoidable. Can someone think of a better solution?

**Comment by inssein** [comment]
@kangax how would you like me to confirm this issue? I have referenced an issue that contains a a jsfiddle, and @asturur also proposed a solution based on what I have mentioned here (via a fiddle).

**Comment by kangax** [comment]
@inssein hm, I marked it "needs_confirmation" more for the reason of not being sure what to do about this (is this something we consider bug and want to fix or not?)

**Comment by asturur** [comment]
Doing this:

```diff
    for (var i = 0, len = listenersForEvent.length; i < len; i++) {
      // avoiding try/catch for perf. reasons
-      listenersForEvent[i].call(this, options || { });
+      listenersForEvent[i] && listenersForEvent[i].call(this, options || { });
    }
```

would bring to bad performance?

**Comment by inssein** [comment]
@asturur I believe that would solve one of the two potential edge cases. 

Edge cases:
- The length of the array is 1 greater than it should be (this is what you have fixed)
- One of the events may not fire

Example for the second case:
If the first ```listenersForEvent[i].call(this, options || { })``` unbinds the same event, the ```listenersForEvent``` array will shift(). The next iteration will be at i = 1, but the callback that should be fired is now at i = 0.

**Comment by asturur** [comment]
maybe instead of shifting we should just make them "false", and shift them at the end of the loop?

**Comment by inssein** [comment]
@asturur then you would have to keep track when you are looping through the callbacks. I don't know if there is a good solution here. Maybe its fine to leave this as is, and just document it somewhere.

**Comment by asturur** [comment]
I meant if removeEventListener
```
 /**
   * @private
   * @param {String} eventName
   * @param {Function} handler
   */
  function _removeEventListener(eventName, handler) {
    if (!this.__eventListeners[eventName]) {
      return;
    }

    if (handler) {
      fabric.util.removeFromArray(this.__eventListeners[eventName], handler);
    }
    else {
      this.__eventListeners[eventName].length = 0;
    }
  }
```

would just set `__eventListeners[eventName]` to false instead of removing to array,
and the next `fire` iteration would skip the false and at the end of for loop would clean the array.

too hackish?

**Comment by inssein** [comment]
@asturur I think that is pretty hacking. In my opinion, the right way to do it would be to know when we are executing the events array (firing[event] = true, firing[event] = false).

If we add or remove events while the events are firing, we should add them in a queue (array) and perform those operations after firing.

This also solves the problem of adding events while the same event is added (if on mouse:down I add another mouse:down callback, it will also get called for the same event, which is wrong).

**Comment by asturur** [comment]
I see the point on the mousedown example.

But setting a particular index of
`this.__eventListeners[eventName]`
from handler to 'markedfordeleting' is exactly what i was proposing.
using a `null` or a `false`.

Can you explain me what you see wrong in this?

The "newly added event" can be solved by reading `this.__eventListeners[eventName].length` just once.

**Comment by inssein** [comment]
@asturur I don't see anything wrong with your solution, I was just proposing a different one. I think your solution is probably more efficient in this case, as this is called many times. And yeah, the length check is probably a lot safer for the case when you add an event.

**Comment by asturur** [comment]
When you said "I think that is pretty hacky" i thought you spotted some bad coding behaviour that i was not seeing. I think i will try to put togheter a PR that can take care of array shortening and growing.

**Comment by inssein** [comment]
I thought it was hacky because it only solved one of the problems (removing an event). Didn't realize it was so simple to fix the add as well.
