### ISSUE TITLE
export dataulr without overlayimage

### ISSUE THREAD

**Issue by guzuomuse** [kangax/fabric.js#2709]
in some situation, need export dataurl without overlayimage;
for example: you may just use overlayimage as mask or background when edit;
so any feature already exists right now? any ideas? thanks!

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group (https://groups.google.com/forum/#!forum/fabricjs) or on StackOverflow (http://stackoverflow.com/questions/tagged/fabricjs) where someone will usually assist you.

The issue tracker is only for bugs (with reproducible minimal test case) and feature requests.

Thanks for your understanding!
