### ISSUE TITLE
Cotton feel when using in mobile.

### ISSUE THREAD

**Issue by YangChueng** [kangax/fabric.js#2716]
The system is andriod 5.0.1. Running in webkit bowser.
And the version is 1.5. When the image loaded becoming more and more, the cotton feel obviously. I wonder what cause that and if there is any solutions to it

**Comment by asturur** [comment]
How many image are you loading?

**Comment by YangChueng** [comment]
Sometimes a larger image may caused cotton feel.Generally,four or five images.
