### ISSUE TITLE
TextBox feature request

### ISSUE THREAD

**Issue by smatthews1999** [kangax/fabric.js#2722]
Using TextBox in 1.6.0RC.

Working very nicely.

Thanks!

Just wanted to mention that I noticed that Shadows are not supported.

**Comment by asturur** [comment]
can you post a screen + code? or a fiddle?

**Comment by smatthews1999** [comment]
Here is a fiddle demonstrating that it does in fact work.  

http://jsfiddle.net/smatthews1999/ZxYCP/263/

Thanks, my bad!

**Comment by smatthews1999** [comment]
There seems to be a minor issue with TextBox and setting the Shadow.

It works if set in the constructor, and if using setShadow(), but not if setting the object 'shadow'.

Here is a fiddle to demonstrate. 
http://jsfiddle.net/smatthews1999/ZxYCP/265/

I am new to fabric js so if this is not an issue then please close.

Thanks.

**Comment by asturur** [comment]
http://jsfiddle.net/ZxYCP/335/

shadow expect a shadow object. In constructor and setShadow there is a check for a string parameter that invokes automatically the shadow constructor. if you do manually you have to create the shadow first.
