### ISSUE TITLE
Animated polygon and free hand drawing

### ISSUE THREAD

**Issue by KristjanLiiva** [kangax/fabric.js#2723]
In my application the user is able to add animated arrows to the canvas. To create the moving arrow I used the approach showed in Animating polygon points demo.

However while the animation is on the canvas, free hand drawing preview is no longer visible (or flashing occasionally). I assume this is because the canvas is continuously redrawn? To reproduce this, you can just use the Animating polygon points demo on fabric site and enable isDrawingMode on the canvas. I am using Chrome.

Is there a way to avoid this problem?

**Comment by asturur** [comment]
It would be nice to move the drawing of freedrawing on top canvas, while animating the lower canvas
