### ISSUE TITLE
Facing CORS issue on updation of image src of image fabric object

### ISSUE THREAD

**Issue by upardhi** [kangax/fabric.js#2724]
Hi ,

I am trying to update src of image fabric object. After src update is completed, Cross-origin error is thrown and image object is empty. Below is the detailed error message:

"Image from origin 'http://localhost:3505' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:1534' is therefore not allowed access."

**Comment by asturur** [comment]
Please refer to stackoverflow for this kind of questions.
