### ISSUE TITLE
perPixelTargetFind precision

### ISSUE THREAD

**Issue by davidelanfranchi** [kangax/fabric.js#2725]
Hello everyone,
I'm trying to use fabric but I've encountered this issue: I'm not able to hover and select the images that I add to the canvas with precision.

You can see the issue here: https://jsfiddle.net/kwu9bzs5/1/

I would like to use png images, all of the same dimension, and use the perPixelTargetFind property to allow the user to hover and select them with a click.
However, it seems that the library triggers the mouse events outside of the image, in an area that seems moved by some pixels to the right. You can notice the issue in the fiddle. To understand what I say, just hover on the shapes starting from the right.

Does anyone encountered this issue?
Do you think that this could be due to the fact that I use a rectangular png, with a lot of transparent pixels?

Thank you for any advice!

(I had to insert the images as Data URI because I was not able to solve the Cross Origin Resource Sharing block and use an image hosting service. For this reason the javascript panel is very long. Any advice on how bypass this problem is welcome :) )

**Comment by asturur** [comment]
https://jsfiddle.net/kwu9bzs5/2/

It looks like a css issue. If you remove "width: 90%" from the css it works.

Should be marked as bug?

**Comment by davidelanfranchi** [comment]
Thank you!
Should I close the issue?

**Comment by asturur** [comment]
Let it open, i wait for @kangax confirm that we do not support "width: 90%" on canvas elements, just to be sure. Then i'll close it.
