### ISSUE TITLE
problem with wordcloud svg with fabric js

### ISSUE THREAD

**Issue by nvadgama** [kangax/fabric.js#2730]
Hi,
Fabric is fabulous product thanks for giving support to us for create such a great t-shirt designer tool.
All SVG is working fine and i can add any SVG on canvas but have an issue with wordcloud svg. when i try to add wordcloud svg by loadSVGFromString then its disturb svg's styles. I have attached a screenshot and also check your demo.

Its only with <text> tag in svg element. Can you please advise ?

SVG code find in .txt file.

![screenshot-demo veesys com 2016-01-11 19-03-37](https://cloud.githubusercontent.com/assets/16375551/12234927/3ab48b40-b896-11e5-9526-7af898bfdf5e.png)
 
[test.txt](https://github.com/kangax/fabric.js/files/85792/test.txt)

Thanks
Rajeev

**Comment by asturur** [comment]
the problem is missing space between rotate and translate transformation.
I mark it as a svgimport bug. if i have time to read the svg spec and be sure the space is optional i will fix this. Chrome open the svg correctly.

IF you add the spaces fabricjs can open it too.
![image](https://cloud.githubusercontent.com/assets/1194048/12281315/5bff03b6-b995-11e5-95d3-214a80f31efb.png)

i did not add them all.

**Comment by asturur** [comment]
space looks mandatory by w3c spec
```
transform-list:
    wsp* transforms? wsp*
transforms:
    transform
    | transform comma-wsp+ transforms
transform:
    matrix
    | translate
    | scale
    | rotate
    | skewX
    | skewY
matrix:
    "matrix" wsp* "(" wsp*
       number comma-wsp
       number comma-wsp
       number comma-wsp
       number comma-wsp
       number comma-wsp
       number wsp* ")"
translate:
    "translate" wsp* "(" wsp* number ( comma-wsp number )? wsp* ")"
scale:
    "scale" wsp* "(" wsp* number ( comma-wsp number )? wsp* ")"
rotate:
    "rotate" wsp* "(" wsp* number ( comma-wsp number comma-wsp number )? wsp* ")"
skewX:
    "skewX" wsp* "(" wsp* number wsp* ")"
skewY:
    "skewY" wsp* "(" wsp* number wsp* ")"
number:
    sign? integer-constant
    | sign? floating-point-constant
comma-wsp:
    (wsp+ comma? wsp*) | (comma wsp*)
comma:
    ","
integer-constant:
    digit-sequence
floating-point-constant:
    fractional-constant exponent?
    | digit-sequence exponent
fractional-constant:
    digit-sequence? "." digit-sequence
    | digit-sequence "."
exponent:
    ( "e" | "E" ) sign? digit-sequence
sign:
    "+" | "-"
digit-sequence:
    digit
    | digit digit-sequence
digit:
    "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
wsp:
    (#x20 | #x9 | #xD | #xA)
```

on the other side, adding and asterisk in the regExp solve the problem.
What do you  think kangax?
