### ISSUE TITLE
seems calcOffset not working pls guide way to fix it

### ISSUE THREAD

**Issue by myselfgaurav** [kangax/fabric.js#2732]
i am using fabric js with ionic framework , with tabs and canvas in all tab view

issue if that if i reload tab with canvas that particular canvas work where as other canvas on next tab does not work i tried to call **"calcOffset"** on tab click .

Below is my code 

    jQuery( "a.tab-item" ).click(function() {
    		console.log('clicked');
    		canvas.calcOffset();canvas.renderAll();
    		canvas1.calcOffset();canvas1.renderAll();
    	});

link of my code on codepen: http://codepen.io/anon/pen/QygEaZ

To replicate issue:
1: open 
http://s.codepen.io/boomerang/5e1bcbe77d401481158ec7c658b545cd1452513640770/index.html#/tab/tab1

here tab 1 is active with canvas1 

when u click tab 2 u can not see color in canvas2 means calcOffset not works

2: open 
http://s.codepen.io/boomerang/5e1bcbe77d401481158ec7c658b545cd1452513640770/index.html#/tab/tab2

here tab 2 is active with canvas2

when u click tab 1 u can not see color in canvas1 means calcOffset not works

**Comment by asturur** [comment]
It looks like you are asking for help on custom code. We cannot investigate this without more knowledge on your system and css setup.

Stackoverflow is the right place for this kind of question.

http://stackoverflow.com/questions/34720478/fabric-js-canvas-tab-not-working-with-calcoffset?noredirect=1#comment57187648_34720478

**Comment by myselfgaurav** [comment]
hey it is not custom code it is just angular tab can u please check
