### ISSUE TITLE
Background color as pattern rendered only after a click on the canvas

### ISSUE THREAD

**Issue by Kumidan** [kangax/fabric.js#2737]
I'm having trouble setting a background pattern on the canvas, this is the code
```
    var canvas = new fabric.Canvas('canvas');
    canvas.backgroundColor = new fabric.Pattern({source: 'back.bmp'});
    canvas.setWidth(700);
    canvas.setHeight(500);
    canvas.renderAll(); // I've tried with and without this, same result
```
As I open the page the canvas appears, but the background is black, the background pattern (same as Photoshop's transparent background) appears only if I click on the canvas.
Is that a bug or it's me to do something wrong?

I've tried Firefox 43.0.4, Chrome 47 and IE11 on Windows 8.1

**Comment by asturur** [comment]
Image load is asyncronous in javascript.
Please refer to stackoverflow for this kind of problems where usually someone will assist you.
