### ISSUE TITLE
Aligning objects inside group after group is scaled

### ISSUE THREAD

**Issue by ewape** [kangax/fabric.js#2739]
I have a function that aligns all items inside active group to group boundaries. However, after entire group is scaled there is a problem:
http://codepen.io/pi/pen/WrXbYP
What would be correct way to approach this?

**Comment by ewape** [comment]
Hi,
Is there any chance for feeedback? Can I do something to improve my question?

**Comment by ewape** [comment]
I was able to solve the issue by removing and inserting items inside the group on scaling event:
`group.forEachObject(function(item) {
        group.removeWithUpdate(item);
        group.addWithUpdate(item);
});`

**Comment by asturur** [comment]
we do not support custom code on the project issue tracker, sorry.
Happy that you solved it anyway.

**Comment by mickeyckm** [comment]
@ewape do you have a sample code that works with your fixes? im encountering the same issue.

**Comment by ewape** [comment]
@mickeyckm I updated my codepen sample, with the latest version of fabric.js:
http://codepen.io/pi/pen/WrXbYP
