### ISSUE TITLE
setSelectionStyles behaviour not same on all characters selected

### ISSUE THREAD

**Issue by 24ozcoffee** [kangax/fabric.js#2740]
Once a text selection is made, I cannot change the font size for the entire itext object.

// clear canvas
canvas.clear();
var t = new fabric.IText("Hello world !", {
  top: 100,
  left: 100,
  fontSize: 12,
});

canvas.add(t);
canvas.setActiveObject(t);
t.selectAll();
var style = { };
style['fontSize'] = 84;
style['textBaseline'] = 'bottom';
t.setSelectionStyles(style);
canvas.renderAll();
canvas.discardActiveObject();
canvas.setActiveObject(t);
t.setFontSize(48);
canvas.renderAll();

**Comment by asturur** [comment]
that is true, and you can found an another issue. A style object cleaning is necessary. i mark it as a bug till i found the other issue.

**Comment by asturur** [comment]
I was wrong as labelling as a bug.
You are setting the font Size for all selection, so this is gonna stay untill you remove it.

There is a little bug anyway in setSelectionStyle that is adding too much properties to the latest style object in the selection.

I will investigate.
