### ISSUE TITLE
mouse click offset canvas

### ISSUE THREAD

**Issue by AlexRomijn** [kangax/fabric.js#2742]
Hi,

I have a issue with the canvas. I have made a grid of rectangles. On hover, opacity changes. When the window has scrolled a little, the canvas is thinking it's somewhere else. So if I hover over an item on row 10, it is thinking he's on row 2. I found already that this happend with other people and some messages about that it was an issue which was fixed, but with 1.5.0 I still came across this issue. 
I do however use it with fabricjs-viewport(https://github.com/rstgroup/fabricjs-viewport), so maybe it a conflict between it. I can fix the issue by making the canvas position:absolute or fixed.

Does anyone has the same experience? And fixed it? I already tried using calcoffset(). 

Thanks,

Alex

**Comment by asturur** [comment]
do you have a fiddle showing the problem? did you solve someway?

**Comment by asturur** [comment]
did you try with 1.6.0, and with the built in viewport?
