### ISSUE TITLE
Disallow NaN and Infinity to be set as values when a number is expected

### ISSUE THREAD

**Issue by StephanBijzitter** [kangax/fabric.js#2745]
One of our customers managed to crash our application, and it is most-probably triggered by some code I wrote which in turn bubbles all the way down to Fabric, but I believe this can be prevented by Fabric itself.

The width of one of the text objects turned into NaN, which in turn caused all further calculations to become NaN or Infinity. The only solution was to remove the text object, allowing the application to function properly again. However, because of these values, the textbox did not appear on the canvas anymore, which means the customer could not possibly remove the textbox that had been corrupted.

I am fully aware that this is probably an issue on our end, but I believe Fabric itself can also implement some checks to make sure this cannot happen as easily. I am proposing that `Infinity` and `NaN` cannot be set as value for the keys that relate to sizing and positioning. Likewise, `null` and `undefined` might also need to be excluded, or cast to zero by a simple bitwise operation: `val |= val`.

I will continue to investigate this issue, and hopefully submit a pull request myself, but any help would be appreciated.

The following code is the `_calculateCurrentDimensions` function as in v1.5.0, modified a bit to add a `debugger` object for newer browsers, which acts as conditional breakpoint.

![screen shot 2016-01-19 at 15 19 28](https://cloud.githubusercontent.com/assets/1649903/12421115/e924dfd8-bec0-11e5-9855-d080e69bb568.png)

**Comment by asturur** [comment]
i think this should be taken care of at application level.
