### ISSUE TITLE
CSS3 rgba notation not supported in the `fill` property for svg `styles`

### ISSUE THREAD

**Issue by pedrofs** [kangax/fabric.js#2746]
Hi guys,

I'm using inkscape in the backend to scale up an svg that was created using your awesome fabric.js. The inkscape scales the svg up, exports it as png and sends it to the user.

The problem for now is that I have some circles created using the Circle brush and it adds the fill color as rgba. The inkscape does not recognize css3 rgba inside `fill` property.

I'm planning to fork the project and workaround this to somehow use the `opacity` style property for setting the alpha.

Do you have any advice for dealing with this? Any advice is welcome.

Thanks and best.

**Comment by asturur** [comment]
Would you check if on w3c specsification of svg, the fill attribute can be rgba?

**Comment by pedrofs** [comment]
Hi @asturur. Thanks for you quick reply.

https://www.w3.org/TR/SVG/types.html#DataTypeColor It seems that the SVG specification doesn't yet accept CSS3 color notations.

Should it be something to fix then?

Thanks again.

**Comment by asturur** [comment]
i think yes.

**Comment by woncay** [comment]
Hello! I am running into the same issue as pedrofs, and I when I read the upcoming release notes, I waited until 1.6.2 was ready.  To me, though, unless I am misunderstanding something, this issue isn't fixed.  Even on the home page of this site, if you click the 'toSVG' button, you see the version set to 1.6.2, and plenty of rgba() functions in fills throughout.  What am I missing?  Thanks!

**Comment by asturur** [comment]
did i fix it bad? i'm gonna check

**Comment by asturur** [comment]
Cannot find none in svg from homepage or from kitchensink. Can you post an example how to get them?

**Comment by woncay** [comment]
OK, now I feel like a dope. I can’t reproduce it now, but when I posted the comment, I was getting the 1.6.2 in the header, and rgba() functions for all the fills.  Now, they are all hex colors like they are supposed to be.

Trouble is, I still can’t get them to work correctly in my code.

[cid:image002.png@01D1AF63.07D52F90]



[Description: Description: Description: Description: Description: Description: cid:image002.jpg@01CE5142.21373280]
_______________________________________________________________________________
William Oncay | Chief Technology Strategist  | LADDAWN
155 Jackson Road, Devens, MA  01434
•: 978.563. 6187 | 800.446.3639, ext. 6187 | Ê: 978.772.7792 |  www.laddawn.com<http://www.laddawn.com/>

**Comment by asturur** [comment]
you should get hex notation and separate fill-opacity and stroke-opacity. Do you get them like this? What is the problem with your code?

**Comment by woncay** [comment]
![svg](https://cloud.githubusercontent.com/assets/11065665/15293841/bd14e2a0-1b57-11e6-8eaf-e4ae20c6adb8.png)

**Comment by woncay** [comment]
This is what I get when I do a toSVG export. Note the correct fabric version, but the multiple rgba() functions for fill. This is the same behavior I saw on fabricjs.com earlier, but it has resolved itself.

**Comment by asturur** [comment]
nahhh i'm the dope one. I did just if opacity !== 1. i hate 0 day bugs. I'm gonna patch it now.

**Comment by asturur** [comment]
I patched it, you have to rebuild the lib or wait that i can rebuild it.

**Comment by woncay** [comment]
Thanks very much for your quick response!



[Description: Description: Description: Description: Description: Description: cid:image002.jpg@01CE5142.21373280]
_______________________________________________________________________________
William Oncay | Chief Technology Strategist  | LADDAWN
155 Jackson Road, Devens, MA  01434
•: 978.563. 6187 | 800.446.3639, ext. 6187 | Ê: 978.772.7792 |  www.laddawn.com<http://www.laddawn.com/>
