### ISSUE TITLE
Sharing the canvas in the social networks

### ISSUE THREAD

**Issue by GiseleLima** [kangax/fabric.js#2749]
How best to share a fabricjs canvas on social networks using server side? Is there any explanation for that?

**Comment by kangax** [comment]
Please ask questions on Fabric's Google Group (https://groups.google.com/forum/#!forum/fabricjs) or on StackOverflow (http://stackoverflow.com/questions/tagged/fabricjs) where someone will usually assist you.

The issue tracker is only for bugs (with reproducible minimal test case) and feature requests.

Thanks for your understanding!
