### ISSUE TITLE
Hard to click bounding box controls on touch devices

### ISSUE THREAD

**Issue by manelio** [kangax/fabric.js#2752]
Using fabric on a touch device, it's very difficult to tap precisely the control boxes.

I think it's needed a way to detect points of interest by priority (control boxes > object itself > canvas) within a "tolerance radius" when canvas is tapped, like does the brower when clicked on a link.

I'll examine the source code to find where the touch events are captured.

But, is there any plan to fix this?

Thanks. And very good work!

**Comment by asturur** [comment]
I agree that on activeobject we should give priority on controlboxes, i do not know if it is like this now. Instead of tolerance you can enlarge the control boxes.
