### ISSUE TITLE
Make _setupCurrentTransform() public.

### ISSUE THREAD

**Issue by jpcaram** [kangax/fabric.js#2753]
It's useful to the user to run `canvas._setupCurrentTransform()`, but at this time it is marked as private and cannot be relied upon. 

My specific need for this was to be able to drag an object differently (click, drag, click, or key, drag, key, etc) than it is implemented by default (mouse down, drag, mouse up). 

Can this be make public as well as `canvas._currentTransform`?

**Comment by asturur** [comment]
i think i saw your stackoverflow question. You want to drag an item without using the pressed button right?

**Comment by jpcaram** [comment]
Exactly. I posted an answer to my own question in stackoverflow that seems ideal: http://stackoverflow.com/questions/34981369/fabric-js-move-object-without-holding-mouse-button/35019294 , but using the private property and method mentioned.

Making these public opens up a lot of possibilities, not just my current specific need of dragging without holding the mouse button.

**Comment by asturur** [comment]
Yes but opens lot of errors if people use it not properly. So is hard to evaluate possible drawback of it.

**Comment by jpcaram** [comment]
I agree. Specially on my side, as I only started looking into the source this morning, and I'm seeing side effects of my solution already.

But I wonder if you can see the limitation (basically, the hard-coded (or private) behavior of click-drag-release) and the flexibility that would be added if there was a safe/clean way to override these behaviors in users space?

**Comment by asturur** [comment]
too much application specific, i cannot see a way to support with uniformity scale, drag, rotate and so on using just keys.
At least something that does not fit in the core library
