### ISSUE TITLE
Grouping origin

### ISSUE THREAD

**Issue by dbroadhurst** [kangax/fabric.js#2757]
I'm running into an issue with group positioning. I'm trying to place text at the bottom / center of a group and the following code works as expected

```
      var text = new fabric.Text('text', {
        fontSize: 18,
        originX: 'center',
        originY: 'bottom',
        fill: 'white'
      });

      var frame = new fabric.Rect({
        width: 80,
        height: 80,
        originX: 'center',
        originY: 'bottom',
        fill: 'blue'
      });

      var node = new fabric.Group([frame, text], {
        width: 80,
        height: 80,
      });

```

However I'm confused why I need to set originY to bottom / center in the frame and text. I would expect the code below to work but instead of placing the text at the bottom it's placed above the top left position.

```

      var text = new fabric.Text(type, {
        fontSize: 18,
        originX: 'center',
        originY: 'bottom',
        fill: 'white'
      });

      var frame = new fabric.Rect({
        width: 80,
        height: 80,
//        originX: 'center',
//        originY: 'bottom',
        fill: 'blue'
      });

      var node = new fabric.Group([frame, text], {
        width: 80,
        height: 80,
      });
```  

Any ideas ?

**Comment by asturur** [comment]
you need to either set originX to center or put top and left correctly.

If not specified objects have top and left equal to 0 and originX/Y top and left and group are dimensioned automatically.

If you do not specifiy top and left you have to specify origins.
