### ISSUE TITLE
toDataURL seems to be broke for node

### ISSUE THREAD

**Issue by jhundley9109** [kangax/fabric.js#2758]
It appears since the build on 10/22 (5fd994e4b4d89591a56afa9749a0c7ca1bdd3679) fabric on node does not correctly export image data with toDataURL. I have tried to rebuild fabric with the head commit and I have tried to use fabric that was released on 12/24 (5d0524a6bdc3090418ef0f9cb50192f64a84bd6f) and I get the same results. Maybe this is somehow related to #2744 ? I did verify everything seems to be working with the same version of fabric in the browser. 

I am running node v0.12.9 and npm 3.5.2

Before the 10/22 release
I get a sucessful 360 x 360 png. It is quite a bit of data, so it is omitted.

After the 10/22 release and to current builds today this is all the image data toDataURL returns the data pasted below. All images I attempt to generate appear to output the same data. 

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAWgAAAFoCAYAAAB65WHVAAAABmJLR0QA/wD/AP+gvaeTAAACDklEQVR4nO3BAQ0AAADCoPdPbQ43oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgzwDq0QABdx4XtQAAAABJRU5ErkJggg==

**Comment by jhundley9109** [comment]
I have traced this issue down to 07234dfdf698c82d92685ea19fecfd24a45b114d

**Comment by asturur** [comment]
Look i'm behind this as well.
Until  #2625 everything was ok.
#2632 was broken but we did not notice.

As you can see from #2712 not only toDataUrl is broken, but also getImageData gives array of all zeroes.
With node 4 as i'm trying here: https://ide.c9.io/asturur/nodefabric-nodecanvas
imageData works in some situation but not in others.

Any hint you get is appreciated.

**Comment by jhundley9109** [comment]
I lied... it was even earlier than that. It appear it was on this commit... 6886d377b75e627306bd01bc9fa05e17d39757a1 I'm still digging into the exact problem and hopefully a solution.

**Comment by asturur** [comment]
Look now that you point at this commit, i ask myself why we were rendering all on top on toDataUrl. Some node-canvas peculiarity i ignore?

**Comment by jhundley9109** [comment]
It looks like it. I'm going to test a couple things here and see what I can find. It looks like it might have to do something with the clearContext. I'll let you know when I find more.

**Comment by jhundley9109** [comment]
I won't pretend to know exactly all the inner workings of fabric, but it seems that possibly node uses the contextTop vs contextContainer a little differently. Maybe in some cases node draws on the contextTop when it is supposed to be drawing on the contextContainer? It was simple enough to put in the allOnTop logic and everything should work as expected. I just wonder if that is actually masking another bug that is in node.

**Comment by jhundley9109** [comment]
Okay, I have found some more information about this. It seems it is going to be a problem to use toDataURL with custom fonts as indicated here. http://fabricjs.com/fabric-intro-part-4/

It looks like we are no longer using the contextTop to output the data image. I imagine we will have to always add the custom fonts to the contextContainer. I found a fairly simple fix that should be able to safely fix the issue on the commit that broke it. However, it seems that doesn't solve the issue for the current head commit. I will do more research and report back.

**Comment by asturur** [comment]
toDataURL under node does not work with or without text.
Text may be another issue still i did not discover.
Please continue this discussion on #2712 where there are some tests running and a cloud9 online setup.
Let's not have information splitted in 2 threads.
