### ISSUE TITLE
Mask two images

### ISSUE THREAD

**Issue by nomi416** [kangax/fabric.js#2760]
Is it possible to mask two images using fabric js?
For example: I have a colored shape(heart). I have another images and I want to mask it over heart such that that new image is only displayed as heart.

**Comment by asturur** [comment]
Please, ask this kind of question on stackoverflow or googlegroup of fabricjs.
This hub is just for tracking issues and bugs.
When opening a question try to setup a little fiddle to help people to answer.

Thanks for your understanding.
