### ISSUE TITLE
Spray brush color changes to black after storing canvas to JSON and populating back from JSON

### ISSUE THREAD

**Issue by poohitan** [kangax/fabric.js#2761]
I have a canvas in freeDrawingMode; I draw something on it using SprayBrush for example one time with green color and one time with red.
Then I save my canvas into JSON somewhere:

 `var canvasContent = canvas.toJSON()`

Then I try to populate canvas content from that JSON:

`canvas.loadFromJSON(canvasContent, canvas.renderAll.bind(canvas));`

And what I get are black coloured sprays. 
So: **all the spray objects turn to black after canvas -> JSON -> canvas flow.**

After looking into JSON representation of my canvas I saw that "main" spray object (the group of dots) have fill property always set to `rgb(0,0,0)`. While every single dot of that big spray object have proper fill property value (for example `#ff0000` in case of red color). Maybe the point is here.

Thanks

**Comment by poohitan** [comment]
Please check out this fiddle https://jsfiddle.net/5px18ka6/4/

**Comment by asturur** [comment]
I think that if you update to 1.6.0rc1 it will solve by itself.

**Comment by poohitan** [comment]
Yes, it's fixed in 1.6.0rc1. Thanks!
