### ISSUE TITLE
Handles not aligned on fabricjs.com homepage

### ISSUE THREAD

**Issue by costa974** [kangax/fabric.js#2762]
On your homepage, the last two shapes (on the bottom), don't have handles properly aligned and the same happens on my site. I tried with Chrome and Firefox (both latest release)

**Comment by asturur** [comment]
i think is just a not update json string to create the homepage.

**Comment by asturur** [comment]
fixed

**Comment by costa974** [comment]
When do think you can release a rc2 o final release? my www.pitturo.com suffer of this bug! :)

**Comment by asturur** [comment]
that was not a bug. please share more of your bug.

**Comment by costa974** [comment]
Sorry I can't! My products are bugfree! :)
