### ISSUE TITLE
Wrong oCoords after setAngle even with setCoords

### ISSUE THREAD

**Issue by jacopo2405** [kangax/fabric.js#2763]
I've this issue when rotating a complex polygon with setAngle even if I rise setCoords
i.e.: poly1.setAngle(180).setCoords();
after that I find oCoords cordinates rotated: tl is positioned br and br is positioned  tl and so on ... without considering the rotation of the object

is this a normal behaviour or not?
thanks

**Comment by asturur** [comment]
would you post a fiddle, with latest version, that demonstrate the issue?

**Comment by jacopo2405** [comment]
yes @asturur , I mean exactly that
I thought that TL remains always the top left corner regardless of object rotation as I need the min\max coords of the object: as I understand I've to calculate them instead of simply take the tl\br coords.

**Comment by asturur** [comment]
it depends what you need to do.
we have a bounding box, based on oCoords, where tl is always TL.

On a 45 degree rotation of a square, which corner would you define top left?

**Comment by jacopo2405** [comment]
I've to snap objects on a (not shown) grid
I could use the top\left of the bounding box and find the br with width and height
thanks @asturur
