### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hasRotatingPoint' of undefined

### ISSUE THREAD

**Issue by muxahuk** [kangax/fabric.js#2764]
So, I'm trying to add an object to group
I need that object to be added on specific key ( so i could later update it ). To acheve that i'm using `Group.insertAt( object, key, true )`, `true` becouse key will be changed automatically for `objects.length + 1` value, but as i sad i need to keep key for later updates..

But there's an error in `render` function ( http://fabricjs.com/docs/fabric.js.html#line16687 )
```
// the array is now sorted in order of highest first, so start from end
      for (var i = 0, len = this._objects.length; i < len; i++) {
        this._renderObject(this._objects[i], ctx);
      }
```
Wich doesn't work with custom keys and thinks that all keys are from `0` to `objects.length`

and eventualy throws an error `Uncaught TypeError: Cannot read property 'hasRotatingPoint' of undefined` becouse it connot find `this._objects[i]` and passes it as `undefined`.

Could u please fix these issue ?
About version i use: i have a cdn link that includes ceveral modules along with core.

**Comment by asturur** [comment]
Yes keys are always from 0 to object.length ( - 1 ).
There is no plan to change this now.
