### ISSUE TITLE
Arabic strange behavior in textBox 

### ISSUE THREAD

**Issue by ahmadissa** [kangax/fabric.js#2766]
when using arabic text with textBox (fabricjs 1.6) 

aligning is not working
you can not enter text properly, letters are placed in wrong places
"." at the end of the text is displayed somewhere in the middle.

i think its the encoding, not sure how to solve it.

you can check the example below

https://jsfiddle.net/bxk04vcs/12/

**Comment by milan-w** [comment]
possible duplicate to #2673

**Comment by asturur** [comment]
mix of rtl problem and custom fonts.
thanks @milan-w

**Comment by asturur** [comment]
#2374.

**Comment by YaakovHatam** [comment]
@milan-w @ahmadissa @davidjrice  please look at the issue #2374 i am developing a RTL version please test it

**Comment by davidjrice** [comment]
I only had a quick look at this via web and it is fantastic work 🙌
