### ISSUE TITLE
Update Canvas to 1.3.9

### ISSUE THREAD

**Issue by mahnunchik** [kangax/fabric.js#2767]
Hi @kangax 

Could you please update `canvas` node module to 1.3.9 for compatibility with node v4 and v5.

**Comment by asturur** [comment]
we have a compatibility problem for node4 regarding jsdom.
As of now we cannot make fabricjs compatible both with node 0.12 and node4.

**Comment by mahnunchik** [comment]
@asturur Maybe there is sense to drop support for node 0.12 and maintain only node v4 and v5?

**Comment by Joesmi** [comment]
Hello,

I am a bit new to node so I am perhaps misunderstanding, so bear with me kindly.
When I check the version of node-canvas that fabric is using, I get version 1.1.6.
The current version of node-canvas is 1.3.10.
I don't need a newer version of node as @mahnunchik but is it possible to upgrade node-canvas that fabric is using?

I am scrambling to get flipX-ed itext to be positioned the same way in node-fabric as in browser fabric, so I thought perhaps upgrading node-canvas would help????

Thanks in advance for any pointers.

Joesmi

**Comment by asturur** [comment]
You can update by yourself to latest canvas, ot works good with node 0.12, while in needs changes if you update jsdom.

This will not help with text handling under node as far as i know.

**Comment by Joesmi** [comment]
Thanks @asturur 
Pity about the text handling problem.

**Comment by asturur** [comment]
That depends on how libpango and libcairo (don t remember which one) handles text whitespace.

**Comment by mahnunchik** [comment]
https://github.com/mahnunchik/fabric.js works perfect with Node 5 on Linux and Mac

**Comment by asturur** [comment]
does it work without updating jsdom? because here on travis it fails compilation if i put node 4 on and i do not put jsdom 6.5.x

**Comment by Joesmi** [comment]
Thanks for the info, @asturur

**Comment by hugomrdias** [comment]
pls update this .. i'm stuck in node 0.12 only because of this

**Comment by asturur** [comment]
we updated to canvas 1.3.x and jsdom 3.x, allowing for node compatbility from 0.10 to 5
When 1.6.0 hits npm you should be fine.
