### ISSUE TITLE
Uncaught TypeError: obj.setupState is not a function

### ISSUE THREAD

**Issue by wahidrahim** [kangax/fabric.js#2768]
I am using fabric.js with socket.io. When a user draws a path, I send the path to other users:

```
// client side
canvas.on('path:created', function(e) {
  socket.emit('add path', e.path);
});
...
// server side
socket.on('add path', function(path) {
  socket.broadcast.emit('add path', path); // same as e.path
...
// other users (client side)
socket.on('add path', function(path) { // same as e.path
  canvas.add(path);
}
```

But this gives an error:

`Uncaught TypeError: e.setupState is not a function              fabric.js:6448`

which points to this bit here:

```
    /**
     * @private
     * @param {fabric.Object} obj Object that was added
     */
    _onObjectAdded: function(obj) {
>     this.stateful && obj.setupState();
      obj._set('canvas', this);
      obj.setCoords();
      this.fire('object:added', { target: obj });
      obj.fire('added');
    },

```
I'm not sure what is going on. As the same path object can be drawn using `canvas.add` elsewhere.

**Comment by asturur** [comment]
StackOverflow is a better place for this kind of problems.
We do not give user support for custom code here

Thanks for your understanding.

http://stackoverflow.com/questions/35168635/how-to-send-path-data-and-redraw-a-from-json-in-fabricjs/35171360#35171360
