### ISSUE TITLE
setBackgroundImage issue when using svg images

### ISSUE THREAD

**Issue by dainiuska8** [kangax/fabric.js#2769]
We need to use svg image as background image and we have problem with this images loading. Quite often is not showing all image elements. For example look at image:

![wrong_svg](https://cloud.githubusercontent.com/assets/608825/12815146/f5505d30-cb4c-11e5-8d9b-c7f6a4354a15.png)

After page refresh image looks fine. For example:

![good_svg](https://cloud.githubusercontent.com/assets/608825/12815117/bfbcc370-cb4c-11e5-8f48-dcbb44fbc03a.png)

Also I have attached svg image which is using on canvas: [svg.txt](https://github.com/kangax/fabric.js/files/117407/svg.txt)

Is it possible to fix this problem?

**Comment by asturur** [comment]
please attach a working jsfiddle, so we can check if this is a custom code problem or a fabricjs problem.

**Comment by dainiuska8** [comment]
Working jsfiddle example: https://jsfiddle.net/bsuLr54b/53/

**Comment by ModestasM** [comment]
Managed to reproduce with safari browser:
http://postimg.org/image/dswtqlyn5/

but after refresh everything is loaded..

@asturur maybe any solution is available?

**Comment by asturur** [comment]
I think is the asyncronous loading of the png in the svg.
Does this fix after a renderAll() of the canvas, or you have to refresh page?

**Comment by ModestasM** [comment]
render all did not helped.
only full page refresh.. but I cannot truly say that refresh helped, this is a random issue. Sometimes you see that it is partial loaded sometimes you see that it is fully loaded. 
Was not able to debug, root cause sorry.

**Comment by asturur** [comment]
I think the problem rely on the asyncronous loading of the image inside the svg. I do not think we can help here. Reducing the jsfiddle to something as small as:
https://jsfiddle.net/bsuLr54b/54/
works very reliably on all my computer with or without full refresh

**Comment by darxx** [comment]
On IE11 https://jsfiddle.net/bsuLr54b/54/ don`t work
