### ISSUE TITLE
ctx.bezierCurveTo

### ISSUE THREAD

**Issue by dbroadhurst** [kangax/fabric.js#2772]
I'm looking for the equivalent of ctx.bezierCurveTo in fabricjs.

I've tried to just call ctx.bezierCurveTo but the canvas render overwrites my canvas updates.

Any ideas?

**Comment by asturur** [comment]
there is no direct equivalent.

to do something like that

```
ctx.beginPath();
ctx.moveTo(20,20);
ctx.bezierCurveTo(20,100,200,100,200,20);
```

do:

```
new fabric.Path("M20,20 C20,10 200,100 200,20");
```

you have to use path syntax.
Please for any other question of this kind use stackoverlflow.

Thanks for your understanding.
