### ISSUE TITLE
Wrong badge for download count

### ISSUE THREAD

**Issue by lehni** [kangax/fabric.js#2776]
While looking at the README I found this curiosity:
```md
[![Downloads per month](https://img.shields.io/npm/dm/localeval.svg)](https://www.npmjs.org/package/fabric)
```
I think you mean to use `https://img.shields.io/npm/dm/fabric.svg` instead? It'll give you a nice bump in stats too : )

**Comment by kangax** [comment]
Thanks! 442 → 4k :)
