### ISSUE TITLE
triangle's fill in a group not getting deserialized properly

### ISSUE THREAD

**Issue by nmorado** [kangax/fabric.js#2778]
sample serialized object of a line and an arrow in a group. fill of triangle is not being picked up properly.

`var config = {
            "type": "group",
            "originX": "left",
            "originY": "top",
            "left": 375.5,
            "top": 115.39,
            "width": 170.11,
            "height": 230.11,
            "fill": "rgb(0,0,0)",
            "stroke": null,
            "strokeWidth": 1,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeLineJoin": "miter",
            "strokeMiterLimit": 10,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "clipTo": null,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "globalCompositeOperation": "source-over",
            "objects": [{
                "type": "line",
                "originX": "left",
                "originY": "top",
                "left": -85.05,
                "top": -95.95,
                "width": 146,
                "height": 206,
                "fill": "rgb(0,0,0)",
                "stroke": "#FF355E",
                "strokeWidth": 5,
                "strokeDashArray": null,
                "strokeLineCap": "butt",
                "strokeLineJoin": "round",
                "strokeMiterLimit": 10,
                "scaleX": 1,
                "scaleY": 1,
                "angle": 0,
                "flipX": false,
                "flipY": false,
                "opacity": 1,
                "shadow": null,
                "visible": true,
                "clipTo": null,
                "backgroundColor": "",
                "fillRule": "nonzero",
                "globalCompositeOperation": "source-over",
                "x1": -73,
                "x2": 73,
                "y1": 103,
                "y2": -103
            }, {
                "type": "triangle",
                "originX": "center",
                "originY": "center",
                "left": 63.45,
                "top": -93.45,
                "width": 30,
                "height": 30,
                "fill": "#FF355E",
                "stroke": null,
                "strokeWidth": 1,
                "strokeDashArray": null,
                "strokeLineCap": "butt",
                "strokeLineJoin": "miter",
                "strokeMiterLimit": 10,
                "scaleX": 1,
                "scaleY": 1,
                "angle": 35.33,
                "flipX": false,
                "flipY": false,
                "opacity": 1,
                "shadow": null,
                "visible": true,
                "clipTo": null,
                "backgroundColor": "",
                "fillRule": "nonzero",
                "globalCompositeOperation": "source-over"
            }]
        };`

**Comment by nmorado** [comment]
looks like if i added a fill on the group object itself, it works.

**Comment by asturur** [comment]
In which version are you? This looks like an old 1
.5.0 bug.
