### ISSUE TITLE
How to make line endpoints draggable?

### ISSUE THREAD

**Issue by Kitanotori** [kangax/fabric.js#2779]
Related to http://stackoverflow.com/questions/31706847/fabricjs-line-coordinates-after-movement/35285630#35285630.

I want draggable line endpoints for which I add fabric.Circle anchors to the line endpoints. The problem is, I can't get correct coordinates. I'm running following code after each 'mouse:up' event, but the anchors do not get set to correct positions:

```
startAnchor.set({
  left: line.x1 + line.left,
  top: line.y1 + line.top
});

endAnchor.set({
  left: line.x2 + line.left,
  top: line.y2 + line.top
});
```
What am I doing wrong?

**Comment by asturur** [comment]
Stackoverflow is completely fine for this kind of question. We cannot handle them here.

**Comment by Robinyo** [comment]
Yes, Andrea Bogazzi helped me on stackoverflow :)

This may help: http://robferguson.org/2016/01/21/adding-support-for-ports-and-connectors-to-fabric-js/

I can draw lines and add arrows (triangles) to the lines and re-position the lines (move between ports).

See: https://github.com/Robinyo/my-2d-diagram-editor/blob/master/client/app/components/angular-ui-fabric/src/ui-fabric-factory.js
