### ISSUE TITLE
toObject works incorrectly on Textbox styles resulting in unstyled svg text when exported

### ISSUE THREAD

**Issue by mochidusk** [kangax/fabric.js#2780]
Currently, any styled text using Textbox that are exported to svg will be not be styled completely. The tspans are styled based upon the Textbox's style attribute. However, it is improperly set when toObject is called. For example, if I have 4 lines of text, only the first 2 are registered.

![untitled-1](https://cloud.githubusercontent.com/assets/6126638/12946275/0072ace0-cfa8-11e5-964e-a8f0fb8ccc9a.png)

I couldn't figure out how to set the styles attribute correctly. My workaround was to skip checks for `this.styles[lineIndex]`. Inside the _setSVGTextLineChars method, `styleDecl = this.styles[lineIndex][i]` was changed to `styleDecl = this._getStyleDeclaration(lineIndex, i)`

Here is result:
![untitled-5](https://cloud.githubusercontent.com/assets/6126638/12946375/d1e96a34-cfa8-11e5-9efc-5c4612bf335f.png)

Summary:
1. to svg does not style text; incomplete styling
2. Textbox.style attribute is not set properly
3. using `_getStyleDeclaration(lineIndex, i)` is more reliable for setting the style declaration.

**Comment by asturur** [comment]
"using _getStyleDeclaration(lineIndex, i) is more reliable for setting the style declaration."

Yes it is, because textbox uses a styleMap function.
I missed this during a refactor of textbox.
I'm working on exporting also textFonts that are not available in the exported svg as of now.
I will take care also of this, or if you do not mind, make a pr.

**Comment by mochidusk** [comment]
I forgot to mention that problem occurs only when the textbox automatically wraps the text (which of course will be 99% of use cases). If i type "Apple" [hit return] "Berry" [hit return] "Carrot" .. all three lines will have correct styles. But if I set the textbox width to be small so that typing "Apple Berry Carrot" will auto wrap into 3 lines, then the styles for the last line will be missing.
