### ISSUE TITLE
Selection - inconsistent behaviour of getActiveGroup

### ISSUE THREAD

**Issue by klinki** [kangax/fabric.js#2784]
Hi, 
I just discovered inconsistent behaviour of getActiveGroup() function on canvas.

Right now, when you select 1 object, it returns null. But when you select multiple objects, it returns array of those objects. I think it would be much better (and more consistent) if it returned array containing 1 object, when 1 object is selected. And maybe it could also return empty array when no object is selected, instead of returning null.

**Comment by asturur** [comment]
getActiveGroup does not return array. it return the group on canvas that keeps track of Multiple selection. If there is no multiple selection, there is no activeGroup.
