### ISSUE TITLE
Apply Tint filter on non-white images

### ISSUE THREAD

**Issue by Kepra** [kangax/fabric.js#2792]
I'm trying to use tint filter on some images in canvas, it works great with white images but not with colored ones, it keeps the image's original color and apply the tint color on top of it, so it gives the wrong color.
this is the tint class i'm working with : 
`fabric.Image.filters.Tint = fabric.util.createClass({
type: 'Tint',
/**
* Constructor
* @memberOf fabric.Image.filters.Tint.prototype
* @param {Object} [options] Options object
**/
initialize: function(HexColor) {
this.color = HexColor;
},
/**
* Applies filter to canvas element
* @param {Object} canvasEl Canvas element to apply filter to
*/
applyTo: function(canvasEl) {
var context = canvasEl.getContext('2d'),
imageData = context.getImageData(0, 0, canvasEl.width, canvasEl.height),
data = imageData.data;

var rUser = ((this.color).toString ()).substr(0,2);
var gUser = ((this.color).toString ()).substr(2,2);
var bUser = ((this.color).toString ()).substr(4,2);

for (var i = 0, len = data.length; i < len; i += 4) {
r = data[i];
g = data[i + 1];
b = data[i + 2];
data[i] = parseInt ((r * parseInt (rUser, 16))/255);
data[i + 1] = parseInt ((g * parseInt (gUser, 16))/255);
data[i + 2] = parseInt ((b * parseInt (bUser, 16))/255);
}
context.putImageData(imageData, 0, 0);
},
/**
* Returns json representation of filter
* @return {Object} json representation of filter
*/
toJSON: function() {
return {
type: this.type,
color: this.color
};
}
});`

example: 
this filter is applied on white image with the color (#D42E12)
![tint_1](https://cloud.githubusercontent.com/assets/8673371/13044177/998c6aea-d3c4-11e5-842a-87aee1f0d03f.png)

this filter is applied on a gray image with the same color (#D42E12), as you can see the difference is clear 
![tint_2](https://cloud.githubusercontent.com/assets/8673371/13044245/fc038e10-d3c4-11e5-99c4-c502d3d6d1fa.png)

could be there a solution to this issue ? or a workaround to get it work properly ?

**Comment by asturur** [comment]
I think is normal behaviour of tint filter. It is not supposed to replace colors, but just recolor them.

If you tint with red a grayscale image you should get a red scaled image.

**Comment by Kepra** [comment]
So I think I'm misunderstanding the tint filter concept here, so is there a way using fabric to recolor images ?

**Comment by asturur** [comment]
Please open a question on stackoverflow, with the start image and desired result. We do not provide  support here.

Thanks for your understanding.
