### ISSUE TITLE
Table Inserting in canvas

### ISSUE THREAD

**Issue by sushant357** [kangax/fabric.js#2795]
Dear,
I am inserting the table into canvas but after clicking anywhere in the screen it will get disapper.
please check code
`$scope.addTable = function () {
      var
        row_cnt = eval($('#Rows').val()),
        col_cnt = eval($('#Cols').val());
      var trs = '', table = '<table id="CreatedTbl" border="1" cellpadding="5" cellspacing="0">';
      for (var temprow = 0; temprow < row_cnt; temprow++) {
          var tds = '';
          for (var tempcol = 0; tempcol < col_cnt; tempcol++) {
              tds += '<td>Data' + temprow + tempcol + '</td>';
          }
          trs += '<tr>\n' + tds + '</tr>';
      }
      table = table + trs + '</table>';
      $('#tablePreviewArea').html(table);
      var CreatedTbl = $('#CreatedTbl').html();
      //var canvas = document.getElementById("canvas");
      var ctx = canvas.getContext("2d");
      var data = "<svg xmlns='http://www.w3.org/2000/svg' width='600' height='450' >" +
                   "<foreignObject width='100%' height='100%'>" +
                     "<div xmlns='http://www.w3.org/1999/xhtml' style='font-size:20px;'>" + "<table cellpadding='5' cellspacing='0' border='1' width='100%'>" + CreatedTbl + "</table>" +
                     "</div>" +
                   "</foreignObject>" +
                 "</svg>";
      var DOMURL = self.URL || self.webkitURL || self;
      var img = new Image();
      var svg = new Blob([data], { type: "image/svg+xml;charset=utf-8" });
      var url = DOMURL.createObjectURL(svg);
      var coord = getRandomLeftTop();
      var scrollVal = $('#canvasScroll').scrollTop() + 250;
      img.onload = function () {
          ctx.drawImage(img, 10, scrollVal);
          DOMURL.revokeObjectURL(url);
      };
      img.src = url;
  };`

**Comment by asturur** [comment]
you cannot draw directly on fabricjs canvas context.
This get cleared on any refresh.
You have to create a table object if you need it.

Please refer to stackoverflow for this kind of questions.

**Comment by sushant357** [comment]
Can you please do jsfiddle & share example ?

**Comment by asturur** [comment]
No, i m really sorry i do not have the time. Is a long process is not a 2 steps jsfiddle.

**Comment by sushant357** [comment]
Thanks a lot :)
