### ISSUE TITLE
Text shadows rendered incorrectly, off by pixels

### ISSUE THREAD

**Issue by panthar1** [kangax/fabric.js#2801]
Hey There,

Since it looks like this is a active issue queue, here is another bug with shadows. See the below SVG. The shadow renders in the incorrect x/y offset position inside fabric.js when compared with browser/svg viewer. I know this is an extreme example of 100 pixel X offset, but it illustrates there is some bug with your shadow pixel calculations. Think I have some other bugs I found as well. I will add them when I have a better handle on them. 

```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="300" height="300" style="background-color: rgba(0,0,255,0.3)" viewBox="0 0 300 300" xml:space="preserve">
<desc>Created with Fabric.js 1.6.0-rc.1</desc>
<defs></defs>
<filter id="SVGID_3" y="-20%" height="140%" x="-33%" width="166%" >
	<feGaussianBlur in="SourceAlpha" stdDeviation="0"></feGaussianBlur>
	<feOffset dx="100" dy="0" result="oBlur" ></feOffset>
	<feFlood flood-color="rgb(0, 0, 0)"/>
	<feComposite in2="oBlur" operator="in" />
	<feMerge>
		<feMergeNode></feMergeNode>
		<feMergeNode in="SourceGraphic"></feMergeNode>
	</feMerge>
</filter>
	<g transform="translate(392.5 110.17)">
		<text font-family="Times New Roman" font-size="195" font-weight="normal" style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: #00ff00; fill-rule: nonzero; opacity: 1;filter: url(#SVGID_3);" >
			<tspan x="-392.5" y="61.42" fill="#00ff00">Some text</tspan>
		</text>
	</g>
</svg>
```

**Comment by asturur** [comment]
please attach screenshot of svg rendered in browser and fabricjs canvas.

**Comment by panthar1** [comment]
See screenshot, the one on the left is what is rendered in browser/other svg renders, and the right is what is rendered in fabric.js

![Browser vs Fabric  SVG](https://cloud.githubusercontent.com/assets/289302/13188931/a6ea76e6-d711-11e5-82b8-d98e0a652c40.png)

**Comment by asturur** [comment]
Please attach code you used to generate the fabric object

**Comment by panthar1** [comment]
http://jsfiddle.net/1z67v7d5/

This illustrates all 3 problems, the shadow pixel calculation problem, the alpha blending problem, and the strokes on the shadow problem.

**Comment by panthar1** [comment]
BTW- I was fiddling around a bit more with some of these bugs, these same bugs also seem to apply to image shadows, and probably all the other object types as well.

**Comment by asturur** [comment]
The alpha blending bug, if referred to the text background color is indeed a bug. The background color should return a shadow also in svg.

For the position of shadow i cannot see any problem in the fiddle.

For text Stroke, you should use in cavas affectStroke = true in the shadow object if you want a faithfull copy in svg.

**Comment by panthar1** [comment]
Oh Awesome, did not know about the affectStroke setting! Thanks so much.

Position of the shadow is definitely a bug, look at where the start of the red "S" is on the fabric.js Vs the SVG version. The higher the X offset is for the shadow, the more apparent the bug becomes because it's off by more and more pixels as you increase the X offset. This same bug is not just in the browser, it's also visible in stand alone SVG viewers.

As far as the alpha goes, this bug is actually more than just background color in my testing, but that was a good example of it.

**Comment by panthar1** [comment]
Also, while I am looking at this, there is a bug with the affectStroke setting.

http://jsfiddle.net/1z67v7d5/4/

Notice how the red stroke on the "S" goes through through the green S. The Red S's stroke should render behind the green S.

**Comment by panthar1** [comment]
Well, I did some investigation into this.  Can't quite figure out what the fix is though... Either javascripts shadow.offsetX and shadow.offsetY are incorrect when it comes to where it renders the shadow, or the toSvg() function is incorrectly calculating the position in the svg.  Either way, I don't know how to make them the same in the JS/SVG after fiddleing with this for a bit. Hope this helps nail down the bug though:

```
_setShadow: function() {
    if (!this.shadow) {
      return;
    }

    var ctx = this.canvas.contextTop;

    ctx.shadowColor = this.shadow.color;
    ctx.shadowBlur = this.shadow.blur;
    ctx.shadowOffsetX = this.shadow.offsetX;
    ctx.shadowOffsetY = this.shadow.offsetY;
  },
```


   ```
 toSVG: function(object) {
      var fBoxX = 40, fBoxY = 40, NUM_FRACTION_DIGITS = fabric.Object.NUM_FRACTION_DIGITS,
          offset = fabric.util.rotateVector({x: this.offsetX, y: this.offsetY},
            fabric.util.degreesToRadians(-object.angle)), BLUR_BOX = 20;

      if (object.width && object.height) {
        //http://www.w3.org/TR/SVG/filters.html#FilterEffectsRegion
        // we add some extra space to filter box to contain the blur ( 20 )
        fBoxX = (toFixed((Math.abs(offset.x) + this.blur) / object.width, NUM_FRACTION_DIGITS) * 100 )+ BLUR_BOX;
        fBoxY = (toFixed((Math.abs(offset.y) + this.blur) / object.height, NUM_FRACTION_DIGITS) * 100) + BLUR_BOX;
      }

      return (
        '<filter id="SVGID_' + this.id + '" y="-' + fBoxY + '%" height="' + (100 + 2 * fBoxY) + '%" ' +
          'x="-' + fBoxX + '%" width="' + (100 + 2 * fBoxX) + '%" ' + '>\n' +
          '\t<feGaussianBlur in="SourceAlpha" stdDeviation="' +
            toFixed(this.blur ? this.blur / 2 : 0, NUM_FRACTION_DIGITS) + '"></feGaussianBlur>\n' +
          '\t<feOffset dx="' + toFixed(offset.x, NUM_FRACTION_DIGITS) +
          '" dy="' + toFixed(offset.y, NUM_FRACTION_DIGITS) + '" result="oBlur" ></feOffset>\n' +
          '\t<feFlood flood-color="' + this.color + '"/>\n' +
          '\t<feComposite in2="oBlur" operator="in" />\n' +
          '\t<feMerge>\n' +
            '\t\t<feMergeNode></feMergeNode>\n' +
            '\t\t<feMergeNode in="SourceGraphic"></feMergeNode>\n' +
          '\t</feMerge>\n' +
        '</filter>\n');
```

**Comment by asturur** [comment]
Canvas shadow is something different from svg copy, blur and offset. There is no direct equivalent. 

If there is some little pixel differences is not something we will fix easily. The background color shadow and alpha can be fixed easy.

**Comment by asturur** [comment]
Simple offset rotation is not enough, we need to calculate flipping also.

**Comment by panthar1** [comment]
Problem is, it's not a small pixel difference. It's apparent with even a small shadow, off by 30-40% or more.  

And I hear ya, after looking at this, it's definitely complicated. Even if we could a better approximation within 1-2 pixels, that would be better than this 30-40% off.

**Comment by asturur** [comment]
Give me a canvas json with the faulting examples. Do not overload it with features that will render the eye-checking process complicated.
I ll check it.

**Comment by panthar1** [comment]
Not sure if this is exactly what you wanted, but here is a jsfiddle with the regular JS canvas way, the Fabric way, and the SVG way.

http://jsfiddle.net/ue3udaxL/

What's interesting, is the JS and the SVG version line up, it's only the fabric version that's off. Perhaps that's good news.

**Comment by asturur** [comment]
Are you using a retina screen?

**Comment by asturur** [comment]
I confirm another retina screen logic error.
Because the shadow offset on canvas does not depend on the scaling factor of the canvas, we have to manually enlarge the offset to follow retina scaling.

**Comment by panthar1** [comment]
I am running on 3 normal computer screens. But, I just tested this some more, and I figured out what's causing it! It's the browser zoom! Try zoomiing in in the browser and running that jsfiddle again.

It looks like the images match up at 100% browser zoom, so I can repeat what you see! But once you zoom in (or out), the bug starts happening, see my screenshot below.

![2016-02-23_0618](https://cloud.githubusercontent.com/assets/289302/13252723/7dd68420-d9f5-11e5-963a-4eb2ae1be406.png)

**Comment by panthar1** [comment]
And if I zoom in even further, it's even further off, look at this. This is only 175% zoom in the browser:

![2016-02-23_0641](https://cloud.githubusercontent.com/assets/289302/13253289/997b0428-d9f8-11e5-98c6-473914ef8e6d.png)

**Comment by asturur** [comment]
Can you try the code i left in #2806?
it fixes situation for shadow on retina screen.
For zoom level of browser higher than 100% we do not care i think.

**Comment by panthar1** [comment]
I do not have a retina screen, just browser zoom, but I tried the code and it seems to have an error:

Uncaught TypeError: this.canvas.isRetinaScaling is not a function

```
		 if (this.canvas && this.canvas.isRetinaScaling()) {
         multX *= fabric.devicePixelRatio;
         multY *= fabric.devicePixelRatio;
       }
```

However, when I delete 
`if (this.canvas && this.canvas.isRetinaScaling()) {`

it actually appears to works that way! Thank you.

**Comment by panthar1** [comment]
Oh I do see one issue still.

It's actually with the SVG output.  IF you have a shadow offsetX of 100,  move the text so that the green text is partially off the screen (IE- left: -100 ), the resulting SVG will display a shadow that is cut off by, when it should not be cut off at all.

Not sure I can provide a JS fiddle until fabric has been updated, but I hope that's a good description, see screenshot.

![2016-02-24_2313](https://cloud.githubusercontent.com/assets/289302/13311518/4f1257c4-db4c-11e5-80e8-09560e2fda8e.png)

**Comment by panthar1** [comment]
Hmm not sure if this is fully fixed, some of the SVG exports I have done actually produce 1/2 images in chrome. It results from a double negative on the y= and x= in the SVG for the shadow. Funny because rsvg seems to render it correctly, but the double negative creates a problem for chrome's SVG anyhow.

I been actually trying to get npm to install fabric, but I am stuck like other windows users have reported with the with the gyp dependency for some reason not being found, yet it's there/been installed!   I would like to contribute some of this stuff directly, as I think I can fix a few of these issues.

```
<filter id="SVGID_6" y="--20%" height="60%" x="--19%" width="62%">
	<feGaussianBlur in="SourceAlpha" stdDeviation="0"></feGaussianBlur>
	<feOffset dx="1" dy="0" result="oBlur"></feOffset>
	<feFlood flood-color="rgb(0, 0, 0)"></feFlood>
	<feComposite in2="oBlur" operator="in"></feComposite>
	<feMerge>
		<feMergeNode></feMergeNode>
		<feMergeNode in="SourceGraphic"></feMergeNode>
	</feMerge>
</filter>
```

**Comment by asturur** [comment]
How do you get the double negative there?

**Comment by panthar1** [comment]
Uhg, so I just re-applied your #2806  patch and it seems to be working again. Still having the Uncaught TypeError: this.canvas.isRetinaScaling is not a function problem though, just have to comment out that line.

Sorry, this is difficult to work with, when I am editing fabric.js directly, and not through the source code like I would prefer.
