### ISSUE TITLE
Text alpha blending with rgba values incorrect

### ISSUE THREAD

**Issue by panthar1** [kangax/fabric.js#2802]
Here is another bug;

This is just an example, but when I apply a rgba color to a text background with a shadow in it, fabric.js  renders the background color incorrectly through the alpha, creating two colors in the background, when there should only be one.  See the SVG below. This bug also seems to have incorrect rendering with strokes and alpha as well when compared with a svg viewer as well, so it's not just just limited to text shadows/backgrounds, but this is a good example of the issue. Looks to me, like something is incorrect with how your rendering the alpha when rgba values are used for any/all of the colors on the Text object.

```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="300" height="300" viewBox="0 0 300 300" xml:space="preserve">
<desc>Created with Fabric.js 1.6.0-rc.1</desc>
<defs></defs>
<filter id="SVGID_88" y="-20%" height="140%" x="-29%" width="158%" >
	<feGaussianBlur in="SourceAlpha" stdDeviation="0"></feGaussianBlur>
	<feOffset dx="100" dy="0" result="oBlur" ></feOffset>
	<feFlood flood-color="rgba(196, 65, 65, 0.99)"/>
	<feComposite in2="oBlur" operator="in" />
	<feMerge>
		<feMergeNode></feMergeNode>
		<feMergeNode in="SourceGraphic"></feMergeNode>
	</feMerge>
</filter>
	<g transform="translate(603 140.46)">
		<rect opacity="0.52" fill="rgb(255,0,0)" x="-572" y="-160.46" width="1144" height="320.92"></rect>
		<text font-family="Times New Roman" font-size="284" font-weight="normal" style="stroke: rgba(0, 0, 0, 0.62); stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0, 255, 0); fill-rule: nonzero; opacity: 1;filter: url(#SVGID_88);" >
			<tspan x="-572" y="89.46" fill="rgb(0, 255, 0)">Some text</tspan>
		</text>
	</g>
</svg>
```

**Comment by asturur** [comment]
please attach screenshot of svg rendered in browser and fabricjs canvas.

**Comment by panthar1** [comment]
See screenshot, the one on the left is what is rendered in browser/other svg renders, and the right is what is rendered in fabric.js.

As I said in the original post, this issue is not only with shadow/background color, and alpha values, it also seems to apply to stroke/fill colors. Seems like the whole alpha calculation has a bug when with rgba colors are used.

![Browser Vs Fabric.js SVG](https://cloud.githubusercontent.com/assets/289302/13189060/6c9b8998-d712-11e5-913c-fe036676da42.png)

**Comment by panthar1** [comment]
I also wanted to mention these issues, it could also just be a issue with facric.js's conversion to SVG. I don't really know, as I am of course unfamiliar with the actual code.

**Comment by asturur** [comment]
Can you attach the code use to generate the fabric js text?

**Comment by panthar1** [comment]
http://jsfiddle.net/1z67v7d5/

This illustrates all 3 problems, the shadow pixel calculation problem, the alpha blending problem, and the strokes on the shadow problem.
