### ISSUE TITLE
Space appears on the wrong line in a Textbox object

### ISSUE THREAD

**Issue by onassar** [kangax/fabric.js#2804]
## Version
1.6.0

## Test Case
https://jsfiddle.net/eucht4sd/28/

## Steps to reproduce
Add a Textbox object to the canvas. Depending on the font size and and font family, a space will be pushed to the next line.

## Expected Behavior
The space before the word "me" should be applied to the previous line, since there is enough room.

## Actual Behavior
The space appears on the second line, before the word "me"

Please note that I am using the distribution-release from December 24th.
Thanks

**Comment by asturur** [comment]
https://jsfiddle.net/eucht4sd/28/

Modified the fiddle with no padding for more clarity and to show that normally there are no spaces at the end or start of lines. So there must be a bug with the first word space.

**Comment by onassar** [comment]
Here it is without padding: https://jsfiddle.net/eucht4sd/33/

**Comment by Rad1calDreamer** [comment]
hi, why if i type space on the end of line generated new line?
