### ISSUE TITLE
SVG showing wrong on Internet Explorer EDGE

### ISSUE THREAD

**Issue by dainiuska8** [kangax/fabric.js#2805]
## Version

1.5.0
## Test Case

https://jsfiddle.net/sjbdwxgx/1/
## Steps to reproduce
1. Open link: https://jsfiddle.net/sjbdwxgx/1/ on Internet Explorer EDGE. Only on IE EDGE SVG image showing wrong. 

When I try to open image direct from the link I can see correct svg image, but problem appears when image is loading on fabric canvas background.
## Expected Behavior

Should show correct image like this:
![correct](https://cloud.githubusercontent.com/assets/608825/13244805/cbb465d8-da11-11e5-931b-c63348eae5cf.png)
## Actual Behavior

Show wrong image:
![incorrect](https://cloud.githubusercontent.com/assets/608825/13244818/de7d8a82-da11-11e5-80fd-15d9a46fc617.png)

**Comment by asturur** [comment]
I'm sorry but this is an svg generated not by fabricjs, and is loaded by fabricjs as an image.
When you open the SVG in edge, without fabricjs, but just loading the svg file in a browser tab, does it display good or bad?

**Comment by dainiuska8** [comment]
It display good when open svg file in a browser tab (Look here: http://imgh.us/diagram_9.svg).

**Comment by asturur** [comment]
i got my windows 10 back, i will try to check it.

https://jsfiddle.net/sjbdwxgx/4/
