### ISSUE TITLE
Text shadow multi level casting

### ISSUE THREAD

**Issue by asturur** [kangax/fabric.js#2807]
## Version
1.6.0 latest

## Test Case
![image](https://cloud.githubusercontent.com/assets/1194048/13307425/71b63d4e-db6b-11e5-8c9d-46a0bbb1247c.png)

## Steps to reproduce
go on kitchensink, add a text and add background color to both text and itext. Shadowify them.

## Actual Behavior
shadow of text drops over text background that also drop shadow on object background.

## Expected Behavior
is this what we really want? 3 leves of shadows?

**Comment by asturur** [comment]
This is a proposed alternative solution.

![image](https://cloud.githubusercontent.com/assets/1194048/13305766/1e3b409a-db5e-11e5-8b93-d02f1ab0b5f5.png)

**Comment by asturur** [comment]
@kangax if interested in this change, a demo pr is already available.

**Comment by kangax** [comment]
2nd version definitely looks better! Good stuff :)

**Comment by asturur** [comment]
needs svg rebase and close it.
