### ISSUE TITLE
Issue with loading svg on canvas

### ISSUE THREAD

**Issue by sobanhameed** [kangax/fabric.js#2812]
## Version
Latest

## Test Case
https://jsfiddle.net/sobanhameed/wz10ekck/

## Steps to reproduce
Just load the svg in fiddle to the canvas.
[file.svg.zip](https://github.com/kangax/fabric.js/files/146110/file.svg.zip)

## Expected Behavior
It should be rendered like this:
![image](https://cloud.githubusercontent.com/assets/5161456/13312598/da04b124-db4c-11e5-854e-d4e26b4fd990.png)

## Actual Behavior
Text alignment is all off in the rendered svg
![image](https://cloud.githubusercontent.com/assets/5161456/13312615/ffb18c80-db4c-11e5-9505-a2a572ebb002.png)

**Comment by asturur** [comment]
Missing support for tspan.
Closing as a duplicate.
