### ISSUE TITLE
loss properties to convert the object to json

### ISSUE THREAD

**Issue by urielcastrillon08** [kangax/fabric.js#2814]
thanks for the tool

## Version
1.6.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Steps to reproduce
1 create canvasFabric
     var canvas = new fabric.Canvas('canvas');

2 remove handling properties of the text object

      var text = new fabric.Text("text test", {"hasRotatingPoint":false,"hasControls":false,"hasBorders":false,"transparentCorners":false});
        canvas.add(text);

3 get the json
        var json = JSON.stringify(canvas);

4 load the json
      canvas.loadFromJSON(json);

## Expected Behavior
that the properties remain as defined

{"hasRotatingPoint":false,"hasControls":false,"hasBorders":false,"transparentCorners":false});

## Actual Behavior
The properties are not in the object.

Thanks in advance for your attention

**Comment by asturur** [comment]
we do not export those propery by default.
use:
var json = JSON.stringify(canvas.toObject(['hasRotatingPoint', 'hasControls', 'hasBorders', 'transparentCorners']));

**Comment by urielcastrillon08** [comment]
thank you very much, works perfect!

**Comment by asturur** [comment]
please accept the other answer and just upvote mine. But at least accept one.

**Comment by asturur** [comment]
sorry that answer was not for you
