### ISSUE TITLE
stickman example using fabric js does not persist line coordinate logic after load from json

### ISSUE THREAD

**Issue by hkundnani** [kangax/fabric.js#2815]
I am trying to save fabricjs stickman example by using JSON.stringify and load it back using canvas.loadFromJSON, I even add the properties of circle line1, line2, line3 and line4 explicitly to the JSON using the following way

`var jsonSave = JSON.stringify(canvas.toJSON(['line1', 'line2', 'line3', 'line4']));`

Although i can see that the saved JSON contains the above mentioned properties, but when I load from JSON and try to move the circle I get an error as Uncaught TypeError: p.line1.set is not a function and the stickman breaks.

I have also attached the fiddle link below. To reproduce the scenario

Try to move any circle after fiddle loads.
Click on the save button. (you can go to developers tool and see under the resources tab for the JSON stored in the sessions storage.)
Click on load button.
Try to move any circle and look at console tab in developers tool.
[(http://jsfiddle.net/hkundnani/h0sf3x5h/5/)]

Is there any way to get the save and load functionality to work for stickman?

**Comment by asturur** [comment]
You need to enlive the lines from obj forms to fabric.Line instances.
This is a question for stackoverflow or similar system.

When you use canvas to object, line1 to line4 get exported as simple properties, not as object to be restored later in instances.

**Comment by hkundnani** [comment]
I have even posted it on stackoverflow and its been more than 2 months but i didn't get any reply which could make save and load work for stickman. Please I really need this functionality to work. Any small example to demonstrate this functionality will also do.

**Comment by asturur** [comment]
Please link to so question

**Comment by hkundnani** [comment]
Am sorry i didn't get you. I have provided the link to the question above. I will provide it again
[http://stackoverflow.com/questions/34319962/stickman-example-using-fabric-js-does-not-persist-line-coordinate-logic-after-lo](url)

**Comment by asturur** [comment]
I answered. I normally do not answer question that are already answered with a good answer. The code i left on the answer / fiddle needs to be finished, but you will see the lines are attacched to circles again.

**Comment by asturur** [comment]
Please accept the answer from the other guy that is more general to the problem.
Upvote mine if you think is good, but do not leave the question unanswered please.

**Comment by hkundnani** [comment]
I have checked the answer and added a comment and I am really sorry for replying late. I really appreciate the answer and thanks for adding a fiddle
