### ISSUE TITLE
Unexpected side-effect while playing around with window.x variable

### ISSUE THREAD

**Issue by seekshiva** [kangax/fabric.js#2818]
## Version
1.5.0

## Steps to reproduce
I ran the following commands in the console as I was experimenting with something
```
x = { a: 4 }
x.__proto__.y = () => { x = 5; console.log(x) }
```
and suddenly I noticed that when I hover my mouse over the canvas in the page, I get this error log
```
TypeError: Cannot read property 'y' of undefined
  _findCrossPoints @ fabric.js:12408
  containsPoint @ fabric.js:12361
  containsPoint @ fabric.js:8208
  _checkTarget @ fabric.js:8739
  _searchPossibleTargets @ fabric.js:8763
  findTarget @ fabric.js:8704
  __onMouseMove @ fabric.js:9674
  _onMouseMove @ fabric.js:9321
```

I'm just playing around with window.x, and suddenly it has a side effect in fabric JS? This doesn't seem right.

**Comment by asturur** [comment]
x is an object, you extended its prototype with y as function.
Suddendly every object carry this y.
So when we are doing for ( i in obj )  we catch that y,
if we do not expect it to be there we look for a sub sub property and here is the error.

you are not playing with window.x but with every object prototype. And that is dangerous if i'm correct.

Please if i said something wrong correct me.
