### ISSUE TITLE
IText/Textbox - The first character is ignored when you type 

### ISSUE THREAD

**Issue by MajaToplicanin** [kangax/fabric.js#2819]
## Version
1.6.0

## Test Case
http://jsfiddle.net/Da7SP/16/

## Steps to reproduce
text is my Itext class
canvas.add(text);
canvas.setActiveObject(text);
text.selectAll();
text.enterEditing();
text.hiddenTextarea.focus();

## Actual Behavior
My Itext object is selected and when i start typing first character don't show.This is worked earlier,but I update my fabric.js library some day before(when you update issues for retina displays), and now don't work again. My fabric.js version is:"1.6.0-rc.1". This is related on this issue :  https://github.com/kangax/fabric.js/issues/2451.

**Comment by asturur** [comment]
Closed as not reproducible on test case.

**Comment by MajaToplicanin** [comment]
Ok, when i use library which you send me the first character show, but don't work download on retina displays.
Here is my code for download(just don't work on retina displays):
function downloadCanvas(link, canvasId, filename) {
            link.href = canvas.toDataURL();
            link.download = filename;
        }
  document.getElementById('download').addEventListener('click', function() {

            if( window.devicePixelRatio !== 1 ){

            var c = canvas.getElement(); 
            var w = c.width, h = c.height;

          // Scale the canvas up by two for retina
          // just like for an image
            c.setAttribute('width', w*window.devicePixelRatio);
            c.setAttribute('height', h*window.devicePixelRatio);

          // then use css to bring it back to regular size
          // or set it here
          //    c.setAttribute('style', 'width="'+w+'"; height="'+h+'";')
          // or jQuery  $(c).css('width', w);
          //      $(c).css('width', w);
          //      $(c).css('height', h);

            // finally set the scale of the context
            c.getContext('2d').scale(window.devicePixelRatio, window.devicePixelRatio);

            }
            downloadCanvas(this, canvas, 'image.png');
        }, false);

**Comment by MajaToplicanin** [comment]
Hello, 
here is your demo: http://fabricjs.com/kitchensink/.
I execute my code:
// clear canvas
canvas.clear();
var text= new fabric.IText('Make your statement!', 
{
            fontFamily: 'Open Sans',
            left: 10,
            top: 20 ,
            })
            canvas.add(text);
            canvas.setActiveObject(text);
                text.selectAll();
                text.enterEditing();
                text.hiddenTextarea.focus();

Here, you can see that the first character is ignored when you type.
Can you check please, this is very important for me?

**Comment by asturur** [comment]
Please refer to the jsfiddle and you will see it works.
Probably the fabricjs.com version is older than the github build you linked.

**Comment by MajaToplicanin** [comment]
Yes, you are right!
I use fabricjs.com version and there work my functionalities on retina diplays too(just ignored first character when you type)
My problem is : when i introduce library which you send me first character work, but don't work well on retina displays , and i need both features to work.
