### ISSUE TITLE
Image isn't displaying properly if I reduce the size of the canvas 

### ISSUE THREAD

**Issue by upardhi** [kangax/fabric.js#2822]
Hi ,

 I have found one bug in fabric .js If I create small static canvas image objects not looks good like actual image. It looks like blurs if I use antiAlising flag and if I remove this flag it looks very sharp. Please suggest me solution over this. Please check attachment for the issue . In this attachment I use antiAlising flag

![issue](https://cloud.githubusercontent.com/assets/6356988/13457355/c502a966-e08d-11e5-9b6f-c74834cab067.png)

**Comment by asturur** [comment]
This is not a bug.
This is how canvas resize images natively.
Please see issue: https://github.com/kangax/fabric.js/issues/1741 and solutions.
