### ISSUE TITLE
Bug Texbox in Explorer/Edge for selected text

### ISSUE THREAD

**Issue by handersen** [kangax/fabric.js#2823]
## Version
1.6.0-rc.1

## Test Case
http://jsfiddle.net/2o46nnka/20/

Fails in Edge and partly in Chrome

## Steps to reproduce
Use Edge 
1. Manually select a part of the text  (ex ou in Your) and key a replacement text 12
The text is messed up in Edge not replacing the selected text.

2. Second test select - behaviour in Edge depends on the selection is made from left to right or right to left.
Select a part of the word (ex ou in Your) and select by marking from right to left  then key 12
Result is You12r

Test once again but select from left to right.
The result is now Y1ou2r

3. Chrome
Seems to work in Firefox and Chrome. BUT if you reduce the box there are also some mess up in Chrome.
Reproduce in this fiddle where the Width parameter is omitted
http://jsfiddle.net/y6rzoxu2/1/
Select ou and key 12
Result in Chrome is Yo12 and not Y12r
Seems to relate to the cursor position. 

Try again http://jsfiddle.net/y6rzoxu2/1/  - position the cursor before Y and press BACK.
Y disappears !
Somehow Textbox loose track of the cursor position.

## Expected Behaviour
The selected text should be replaced with the text keyed.

## Actual Behaviour
The text entered is mixed with the text to be replaced. Seems to be depending on the direction of the selection.

**Comment by asturur** [comment]
I confirm issue with internet explorer 11.

**Comment by asturur** [comment]
I confirm the bug with edge.
