### ISSUE TITLE
ISSUE FOUND ON INCORRECT SIZE of pattern on RECT object

### ISSUE THREAD

**Issue by sorabh86** [kangax/fabric.js#2830]
Bug found in 1.5.0 version.
If you apply an image base64 pattern on fabric.Rect then preview in browser is perfect, but when you open that svg in illustrator nothing seem correct. Here are example below:

>>> index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Export Pattern</title>
	<script src="http://localhost.www/fabricjs/1.5.0/fabric.js"></script>
</head>
<body>
	<canvas id="canvas" width="800" height="400"></canvas>
	<script>
		var canvas = new fabric.Canvas('canvas');

		var img = document.createElement('img');
		img.src = "http://localhost.www/localheromx/graphics/site2en/images/backgrounds/chrome-gold.png";

		img.onload = function(){
			img.onload = null;

			var tc = document.createElement('canvas');
				tctx = tc.getContext('2d');
			tc.width = img.width;
			tc.height = img.height;
			tctx.drawImage(img,0,0);

			img.src = tc.toDataURL();

			var rect = new fabric.Rect({
				left: 100,
				top : 100,
				width:200,
				height:200,
				fill:new fabric.Pattern({
					source: img,
					repeat: 'repeat'
				})
			});
			canvas.add(rect);

			var svg = canvas.toSVG();
			postData("upload.php", {svg:svg}, 'post');

		};

		function postData(url, params, method) {
			var form = document.createElement('form');
			form.setAttribute("method", method);
			form.setAttribute("action", url);

			for(var key in params) {
				if(params.hasOwnProperty(key)) {
					var hiddenField = document.createElement('input');
					hiddenField.setAttribute("type","hidden");
					hiddenField.setAttribute("name",key);
					hiddenField.setAttribute("value",params[key]);
					form.appendChild(hiddenField);
				}
			}

			form.submit();
		};
	</script>
</body>
</html>

>> upload.php
<?php 
if(isset($_POST['svg'])) {
	$svg = $_POST['svg'];

	$handle = fopen("output.svg", "w");
	fwrite($handle, $svg);
	fclose($handle);
}
?>

![image](https://cloud.githubusercontent.com/assets/1220531/13721676/b92e127e-e853-11e5-98d6-378f03e796f7.png)

![image](https://cloud.githubusercontent.com/assets/1220531/13721689/f7629ad8-e853-11e5-94b7-fe10d9501fc5.png)

![image](https://cloud.githubusercontent.com/assets/1220531/13721709/5d9eed56-e854-11e5-9632-a69801995e6a.png)

I don't know what is problem here, but i think this is a bug if you want to edit before printing in illustrator, i don't know this problem are common to other svg editor or not.

**Comment by asturur** [comment]
We do not support all the peculiarities of illustrator. Can you provide code for fabricjs, screenshot of canvas and screenshot in browser vs illustrator?
