### ISSUE TITLE
Fabricjs, apply different opacity on content and border

### ISSUE THREAD

**Issue by DanieleSassoli** [kangax/fabric.js#2835]
Hi, 
I'm not sure if this is a bug or a desired behaviour, but when I change the opacity of an object(text, image or path) if changes the border opacity too, I'd like to be able to have a different opacity for the borders of my object. I tried messing around with globalAlpha and amanged to achieve something similar for images, but can't get my head around paths and text, any ideas? Is this even possible? 
Thanks

**Comment by asturur** [comment]
It is possible of course but not implemented. Did you check ( because i did
not) if it is possible to stroke and fill with rgba values?

So you could leave opacity at 1 and play with colors.
Il 15 mar 2016 12:29, "Daniele Sassoli" <notifications@github.com> ha
scritto:

**Comment by DanieleSassoli** [comment]
Hi, thanks, no I didn't try, very good idea, I'll check if I can do this, I think it would take a lot of effect to accomplish it this way, but  I'll let you know ASAP

**Comment by asturur** [comment]
Hi Daniele,
did you something at the end? something worth to share?

**Comment by DanieleSassoli** [comment]
Hi @asturur , sorry for not answering! No, I didn't manage to produce anything worth sharing! We worked around the issue... but I'm pretty sure that the solution you proposed would have worked in a not-as-much-edited fabric project as ours!

**Comment by asturur** [comment]
Do not worry. I did not mark as possible feature because i think that we are currently overloaded with options. I prefere to have full rgba support all around the library than adding another property.

**Comment by DanieleSassoli** [comment]
yes, sounds reasonable!
