### ISSUE TITLE
Microsoft Edge and IE 11 __toDataURL uses system font for text objects with custom font

### ISSUE THREAD

**Issue by StephanBijzitter** [kangax/fabric.js#2836]
## Version
1.5.0

## Test Case
http://jsfiddle.net/Da7SP/22/
* Load the page on IE11 or Edge
* Press the run button

You have to press the run button, because the first time the css won't be loaded in time.
Note that the test case runs v1.6.0, because I was unable to replace the version with v1.5.0. The console showed that fabric was not defined.

http://rawgit.com/kangax/fabric.js/v1.5.0/dist/fabric.js

## Steps to reproduce
When a text object is deselected, we create a png image of it and display that instead. This significantly increases performance on mobile devices, especially when dragging text.

* Add a text
* Change the font to a custom font (not supported by browser/os) (it will show fine)
* Deselect text
* The created png image contains the system font

## Expected Behavior
![screen shot 2016-03-15 at 14 00 58](https://cloud.githubusercontent.com/assets/1649903/13778490/600c4a20-eab6-11e5-8cee-571094d81e7a.png)

## Actual Behavior
![screen shot 2016-03-15 at 14 14 51](https://cloud.githubusercontent.com/assets/1649903/13778848/58a3cd24-eab8-11e5-99d4-f2fc0de20274.png)

**Comment by asturur** [comment]
Does it happen only on edge?
Il 15 mar 2016 13:06, "Stephan Bijzitter" <notifications@github.com> ha
scritto:

**Comment by StephanBijzitter** [comment]
@asturur Works correctly on the following setups:
* Windows
  * Chrome / Opera
  * Firefox
  * IE11 (being tested right now, will edit)
* OS X

**Comment by asturur** [comment]
http://jsfiddle.net/Da7SP/56/

Please try here. I think is just a slow font loading issue.

**Comment by asturur** [comment]
Any update on my fiddle? it looks working to me.

**Comment by StephanBijzitter** [comment]
Will try tomorrow at the office.

**Comment by asturur** [comment]
Please if you find it still problematic, we will reopen the issue for more discussion/test cases.

**Comment by arminbusatlic** [comment]
This has not been fixed. Microsoft Edge still does not load in the custom font when using toDataURL.

**Comment by Clemweb** [comment]
I confirm it's a bug on Edge and IE11
Fiddle : https://jsfiddle.net/709k7abu/1/
