### ISSUE TITLE
This is hard to drag line

### ISSUE THREAD

**Issue by Cartman34** [kangax/fabric.js#2837]
## Version
1.6.0

## Test Case
http://jsfiddle.net/Da7SP/23/
Try it to understand !

## Steps to reproduce
You are not able to drag line, below steps to succeed.

1. Select line by exceeding the top
2. Try to scale line, this is not possible but you unlock drag feature
3. Now, drag the line (selected or not)

## Expected Behavior
Line is always draggable, or immediatly if selected

## Actual Behavior
Line is not easily draggable

## Comments
My editor UI will be able to help user to select the line but not to drag it, fabric.js has to do it correctly.

## Browser
I am currently using Chrome 49

**Comment by asturur** [comment]
Please use stackoverflow for this kind of questions.
You forgot to call a function after resizing the object.

**Comment by Cartman34** [comment]
Yep, you are right but i am lost in tutorial and documentation, i did not find any mention to update object.
I find in sources that using setCoords() could help and it does the job, everything is ok now.
Thank you for your help & all contributors for this great lib !

**Comment by asturur** [comment]
http://jsfiddle.net/Da7SP/24/
yep this was what i prepared, just i did not link because this is not a support forum
I help on stackoverflow, here not.
