### ISSUE TITLE
v 1.6?

### ISSUE THREAD

**Issue by alexiskattan** [kangax/fabric.js#2838]
Hi. I love fabric and have been using it for a while.  I'm using version 1.4 and want to upgrade it.  Do you happen to know, very approximately, when 1.6 will be released?

**Comment by Anruin** [comment]
Hi, I'm using 1.6rc1, because 1.5 lack required features. Can you also build and use it? It seems to be quite stable.

**Comment by ashishbhattb** [comment]
Hi,

Please let us know for 1.6 Releases

As we like the skew feature but cant use without final release build



On Wed, Mar 16, 2016 at 9:04 AM, Egor Pristavka <notifications@github.com>
wrote:

> Hi, I'm using 1.6rc1, because 1.5 lack required features. Can you also
> build and use it? It seems to be quite stable.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kangax/fabric.js/issues/2838#issuecomment-197218395>
>



-- 
Ashish Bhatt

**Comment by tgabi333** [comment]
+1 for that, since v1.5 afaik not compatible with node 4+

**Comment by asturur** [comment]
Released, not on NPM yet. compatibility with node 4 and node 5 added.

**Comment by tgabi333** [comment]
Thank @asturur! What do you think when will it be published to npm?
