### ISSUE TITLE
IText copy not working in IE and Edge

### ISSUE THREAD

**Issue by Kitanotori** [kangax/fabric.js#2839]
Reproduce: try to copy text with IE and Edge from an IText textarea on http://fabricjs.com/test/misc/itext.html

I tried to catch the copy event, but no matter how I tried with Angular (ng-copy), jQuery ($('...').on('copy', ...), and plain JavaScript addEventListener, I couldn't catch copy events in IE and Edge. Does anyone in which way IE and Edge handle copy event differently than other browsers?

ps. paste seems to work, though

**Comment by asturur** [comment]
I didi with ctrl+c on edge and windows 10 and it goes.

**Comment by Kitanotori** [comment]
That's strange, because I did it both in my Windows 10 PC and in my Mac running Windows 10 inside VirtualBox.

**Comment by Kitanotori** [comment]
By using clipboard.js (https://clipboardjs.com/) and launching copy via a button, the event fires (in this case the browser first requires permission to access clipboard), but by ctrl+c the event does not fire.

**Comment by asturur** [comment]
In windows 7 + ie 11 does not copy. Windows 10 and edge does. ( i should double check again ).
I fighted with it a bit, it looks like the hiddenTextarea does not receive the copy event.

If we handle it like a CUT command ( sniffing CTRL+C) it works.
http://www.deltalink.it/andreab/fabric/iphone.html
