### ISSUE TITLE
IText Ionic Android Keyboard 

### ISSUE THREAD

**Issue by lfelisiak** [kangax/fabric.js#2843]
Hi, some strange behaviour its happening with Itext in Ionic Android app, when i load the text and click it to edit the keyboard shows up but when yo want to tap/click another letter or area of the itext the keyboard hides but the cursor  still blinking, What could be ?  

Fabric 1.6
Ionic v1 
Android 5.0

**Comment by asturur** [comment]
Can you test this demo page?
http://www.deltalink.it/andreab/fabric/iphone.html

If it behave better please tell me.

**Comment by lfelisiak** [comment]
Yeah its working from the browser just like the other, but once replaced mine fabric.js with your fabric,js from the above link, doesnt work either ... what I can see... the error happens if you tap fast, i.e if 1 take more than 2 seconds between tap and tap , it works perfectly , but if the taps are with a difference lower than 2 secs , the keyboard hides... and there is no way to show it again unless you cancel the edit of the itext.

**Comment by asturur** [comment]
what is "ionic android keyboard"?
