### ISSUE TITLE
Object movement direction broken after rotate whole canvas

### ISSUE THREAD

**Issue by YarinSl** [kangax/fabric.js#2846]
## Version
1.4.8

## Test Case
http://jsfiddle.net/virtualandy/ysppZ/

## Steps to reproduce
Rotate the canvas, then try to drag and move an object.

## Expected Behavior
The selected object will move according to the correct mouse movement x,y axis

## Actual Behavior
The object being dragged to the opposite x,y axis

**Comment by asturur** [comment]
Css modification to canvas are not supported.
