### ISSUE TITLE
Background image not stretched after rotate

### ISSUE THREAD

**Issue by YarinSl** [kangax/fabric.js#2847]
## Version
1.6.0

## Test Case
http://jsfiddle.net/YH9yD/169/

## Steps to reproduce
1. Set background image to canvas, 
2. Change the canvas width and height.
3. Rotate the background image with 90 degrees
4. set the background image width and height to the new canvas's width and height

## Expected Behavior
The background image will cover the canvas

## Actual Behavior
The background image changed its position and not covering the canvas

**Comment by asturur** [comment]
if the image is rotated, the width and height are swapped. This behavior is correct.

**Comment by YarinSl** [comment]
OK,
I swapped the width and height,
and now i get a different behavior but still not a good one - 
the image not covering the canvas

see the demonstration - 
http://jsfiddle.net/YH9yD/170/

Thanks!

**Comment by asturur** [comment]
http://jsfiddle.net/YH9yD/178/

To make it work easily put the image origins in center, setup top and left as canvas center and it works.

**Comment by hnviradiya** [comment]
I am still facing this issue. even with given jsfiddle solution it is not working.
