### ISSUE TITLE
shadow disapear when rotating image object

### ISSUE THREAD

**Issue by keanass** [kangax/fabric.js#2848]
hello
i've found a bug with shadows
it disapear when applying shadow and rotating an image object.
i'm using chrome Version : 49.0.2623.87 m and think it not working on all browsers, any ideas?

**Comment by asturur** [comment]
please attach a test case.

**Comment by keanass** [comment]
here is an image showing the issue : 
    Shadow disapear imediatlly after begin rotating the object.

![sample](https://cloud.githubusercontent.com/assets/4174024/13968968/c3f73d62-f077-11e5-86f4-778dc0850ca1.png)


thanks.

**Comment by keanass** [comment]
@asturur any help ?

**Comment by keanass** [comment]
no help :( @asturur @kangax

**Comment by asturur** [comment]
We need a sample code that fails.
I can apply shadow to object, rotate as much as i want and everything is fine.
Please attach the code or close the issue.

**Comment by keanass** [comment]
here is a jsfiddle showing the issue : 

https://jsfiddle.net/keanass/jf3719vs/1/

the object is shadow applied but not showing because it rotated, and here is without rotation : 

https://jsfiddle.net/keanass/jf3719vs/

**Comment by keanass** [comment]
working on firefox and IE but not in chrome and opera (webkit)

chrome : 49.0.2623.87
opera :    36.0.2130.32

**Comment by asturur** [comment]
working for me.
try to disable hardware acceleration from your browser and check if it makes any difference.

**Comment by keanass** [comment]
it dosn't make any difference. still not working here is a gif showing it :

![demo_shadow](https://cloud.githubusercontent.com/assets/4174024/14074927/abd70f06-f4cc-11e5-8ce5-773d60ed6518.gif)

**Comment by asturur** [comment]
Can you share some detail on your os version, videocard and browser using. I got no problem with firefox or chrome. Did not try ie11 to be honest.

**Comment by keanass** [comment]
it win 7 64bit, chrome : 49.0.2623.87 (latest) ,  opera : 36.0.2130.32 (latest), videocard: Radeon HD 7690 XT

the issue is present just in those browsers, firefox and IE7 is working perfect.
Thanks.

**Comment by asturur** [comment]
I will try to get same chrome version tonight. Not planning to install opera. They are on blink rightnow, not webkit anymore. I think safari is the only one on standard webkit.
Are you sure you disabled hw acceleration and restartrd browser? It does not look like sonething that we can fix.

**Comment by keanass** [comment]
i disabled hw acceleration and restartrd browser, and the issue is still there, i tested on other computer and it the same problem for those browsers.

**Comment by asturur** [comment]
it is a browser bug i presume. Problem with chrome.

**Comment by keanass** [comment]
so no solution for the moment !?

**Comment by asturur** [comment]
Solution will not come from us, because 2 weeks ago everything was fine on
chrome and still is on chromium.

You should have been writing on chrome  issue report since start.
Of course you have to make a plain canvas example with no fabricjs and they
are strict about issue opening.

But this is how it should be.
Il 30 mar 2016 00:25, "keanass" <notifications@github.com> ha scritto:

**Comment by pavelKozlov** [comment]
I got the same issue.
As @asturur suggested, I create an issue in chromium bug tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=602933

**Comment by asturur** [comment]
thank you. i m going to confirm it and also open one for problem with
patterns.

**Comment by keanass** [comment]
thank you @pavelKozlov .

**Comment by asturur** [comment]
FIXED by the chrome team.

**Comment by keanass** [comment]
Not fixed for me on Version 50.0.2661.94 m

**Comment by pavelKozlov** [comment]
Not sure if Chromium has released this fix.
And have no idea how to check it.

**Comment by keanass** [comment]
they have fixed the problem but the fix is not applied yet.
here is the commit maded by chromium team:
https://chromium.googlesource.com/chromium/src/+/d21fd4984450f9b8cca710bf76a05beec62e243a

**Comment by ncou** [comment]
The fix is present in the Chrome version : Version 50.0.2661.94 m

**Comment by zenmash** [comment]
Not fixed on Version 50.0.2661.102 m, any idea?

**Comment by asturur** [comment]
Yes is bugged again i noticed also.

**Comment by echo954** [comment]
Still seeing this bug in Chrome version 51.0.2704.106 m. I changed the angle property to an image and the shadow no longer renders.

**Comment by asturur** [comment]
it looks like they fixed it if you read the changelog of the bug, maybe when chrome 52 gets out...
