### ISSUE TITLE
Error loading numeric IText text content from JSON

### ISSUE THREAD

**Issue by whereswaldon** [kangax/fabric.js#2849]
## Version
1.5.0

## Test Case
http://codepen.io/whereswaldon/full/ZWKGEd/

## Steps to reproduce
Look in the javascript console on the codepen to see the error.

To reproduce for yourself:
- Create a canvas
- Add an IText with content that consists ONLY of numeric characters
- Export the canvas to JSON
- Load that JSON back into a canvas

## Expected Behavior
The canvas should, as far as I am aware, load its own exported contents without issue. The IText should be added back into the canvas.

## Actual Behavior
The load process resolves the text content of the IText to be of type Number and attempts to call split on said Number. Since Number.split() isn't defined, it throws an error and fails to load.

**Comment by asturur** [comment]
Nice find!

**Comment by asturur** [comment]
Closed as not reproducible with load/save toJSON on latest version
I will reopen if you can provide a jsfiddle with this behaviour.
Current codepen does not load for me.

**Comment by whereswaldon** [comment]
Currently cannot reproduce on 1.6.0rc
