### ISSUE TITLE
iText - cusor animate should fire after:render

### ISSUE THREAD

**Issue by inssein** [kangax/fabric.js#2850]
I have written a few plugins that perform actions on the upper canvas after the canvas is done rendering, but it is all erased when editing text.

This is because the cursor animation clears the entire selection context. Would it be appropriate to ```obj.canvas.fire('after:render');``` after https://github.com/kangax/fabric.js/blob/master/src/mixins/itext_behavior.mixin.js#L117? If so, I could submit a PR.

**Comment by asturur** [comment]
Hello @inssein 
About this i'm not entirely shure, "after:render" we fire after renderAll() while we offloaded the cursor rendering to the top canvas.
I think that firing this event after the cursor animation would be confusing.
I would ne more for another event, even a new one.

i would be more appriopriat to fire something like "topCanvas:beforeRender" and "topCanvas:afterRender".

Or we could even stop clearing ALL the top context for just the cursor animation, i remember someone was already complaining about that.

**Comment by asturur** [comment]
I don't really know here, cursor animation is fast, it can be up to 60 fps.
I don't think firing events there is good.
Maybe more clearing the small rect where the cursor is flashing and nothing else.
What do you think?
