### ISSUE TITLE
SVG Export Text with Stroke

### ISSUE THREAD

**Issue by MULLAINATHAN** [kangax/fabric.js#2851]
Hi,
   I tried to export canvas which has text stroke. On SVG file text fill missed. Please help me on this.
   Reference: 
![original](https://cloud.githubusercontent.com/assets/8257075/13977492/6e0a598e-f0ef-11e5-867e-4dc42027938b.png)
![result](https://cloud.githubusercontent.com/assets/8257075/13977493/6e0ea82c-f0ef-11e5-9c70-56fcb15a9b10.png)

**Comment by asturur** [comment]
Can you please some fiddle that represent what you re doing?

**Comment by MULLAINATHAN** [comment]
Hi asturur,
Herewith I have update my sample fiddle & it's result.  

Fiddle Link:

[https://jsfiddle.net/mullainathan/bv286h81/](url)

Result:

![uotput](https://cloud.githubusercontent.com/assets/8257075/14071479/b55e2090-f4d2-11e5-8d3a-da67e9867622.png)

**Comment by asturur** [comment]
You should mention that you are using a custom function for rendering that is swapping stroke and fill order.
In this way svg export ( that first fill and then stroke ) will not be same as canvas.

**Comment by MULLAINATHAN** [comment]
Hi asturur,
Thanks for your quick response.  By default stroke placed inside object. 
But, I want it should be placed outside of th object, That's why i'm using custom function. 
How to get my expected result without using custom function.? 
Please help on this. 
Thanks in advance.
