### ISSUE TITLE
issue getWidth() and getHeight() not returning the correct number

### ISSUE THREAD

**Issue by jtweku** [kangax/fabric.js#2860]
## Version
1.6.0

## Test Case
http://jsfiddle.net/tLbsqcod/2/

## Expected Behavior
getWidth() and getHeight() should return the width and height value of the object.

## Actual Behavior
getWidth() and getHeight() returning the width and height value + 1, why ?

**Comment by onassar** [comment]
I ran into this in the past @jtweku
It's because the default strokeWidth is not 0. Set it this way, and things should be fine:
`fabric.Object.prototype.strokeWidth = 0;`

**Comment by asturur** [comment]
getWidth and getHeight are a misleading different getters for actual width and actual height.
Born as shortcut for width*scaleX and height*scaleY, now they give you the full dimension of the object, including scaling, skew and border width.

Too widely used, dropping them would cause more confusion that explaining the difference.

Adding the strokeWidth in the calculation of width and height was a trivial decision, made necessary to have an higher precision in importing svgs.

**Comment by jtweku** [comment]
@onassar, @asturur thanks for the explanation

**Comment by awehring** [comment]
Not sure, if I can comment on a closed issue, but trying.

I think the full explanation should be added to the documentation for _getWidth(), getHeight()._

I ran into this issue too and it cost me quite some time.

**Comment by asturur** [comment]
yes getWidth and getHeight are "deprectaed" they should at least be renamed.
