### ISSUE TITLE
todataUrl with negative multiplier

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#2863]
Hi,

I try to made some thumbnail, so i use todataurl with a negative multiplier to have a 1/5 size of my original canvas size.

But the result is always a white picture.

Does the multiplier could be negative ? i doesn't see in the doc this information.

Thank you.

LKeep up the good work.

**Comment by asturur** [comment]
you need to use a multiplier between 0 and 1 to zoom out a negative multiplier would flip the image on both axis bringing the image on the top left quadrant
