### ISSUE TITLE
canvas.dispose() does not clear the html element created for initialization

### ISSUE THREAD

**Issue by aush** [kangax/fabric.js#2864]
After posting a [question on SO](http://stackoverflow.com/questions/36357627/objects-arent-selectable-after-disposing-and-creating-fabric-canvas-over-the-sa), I've reflected a bit on it and now I think it looks more like an actual issue with fabric.js, so I'm posting it here

## Version
1.5.0, 1.6.0-rc.1 (I've found [this issue](https://github.com/kangax/fabric.js/pull/2708), so gave it a try too)

## Test Case
http://codepen.io/aush/pen/dMVNdz - 1.5.0
http://codepen.io/aush/pen/dMVvYK - 1.6.0-rc.1

## Steps to reproduce
```javascript
let fabricCanvas = new fabric.Canvas('c');
fabricCanvas.add(new fabric.Rect({ left: 10, top: 10, fill: 'red', width: 20, height: 20 }));
fabricCanvas.dispose();
fabricCanvas = new fabric.Canvas('c');
fabricCanvas.add(new fabric.Rect({ left: 100, top: 100, fill: 'red', width: 20, height: 20 }));
```

## Expected Behavior
The rectangle should be selectable

## Actual Behavior
It isn't

The actual behavior probably means there is some state mutated by Fabric which isn't restored on dispose, which implies a leak.

I've got this problem not out of curiosity, but working on actual React/Redux app where I want to keep a state of my canvas in my Redux store (serialized to JSON) and applying it on render (deserialize JSON to a new Fabric.Canvas (but the same html canvas element, because React...)).

**Comment by asturur** [comment]
gonna check this.

**Comment by asturur** [comment]
![image](https://cloud.githubusercontent.com/assets/1194048/14210034/809e8dba-f827-11e5-9c52-a8c695bd4208.png)

Double wrapping.
It is not more selectable because i **think** the first dispose clear the events on the wrapper.
Then the new initialization wrap again the canvas and attach events, but probably we do not reach the new element with the mouse clicks anymore.

Bad usage or bug, this i cannot say.

Can you describe a little bit more your need to dispose?

**Comment by aush** [comment]
> Can you describe a little bit more your need to dispose?

I want to dispose in two parts of my app, I've come up with a workaround for the first one (which from my examples are taken), but I still want to dispose in another part, the code for it looks something like that:

````javascript
const newCanvas = new fabric.Canvas();
newCanvas.loadFromJSON(getState().canvas.serializedCanvas, () => {
  newCanvas.add(new fabric.Rect({ left: 150, top: 100, fill: 'red', width: 20, height: 20, angle: 45 }));
  
  next(JSON.stringify(newCanvas));

  newCanvas.dispose();
});
````

This code is placed inside a Redux's reducer, this allows me have a history of changes. And this code is called a lot. My background is C#, so for dispose I expect a contract 'clear all resources' (though, I understand that in JS there is no such contract, but because this expectation is quite common, if Fabric has different contract, it probably should be mentioned in docs to avoid confusion) and I could be sure, that this code wouldn't result in some performance issues, related to leak of resources.

If you're right on your assumption about the reason for this issue, I guess, I shouldn't face problems because of that, but if some resources actually leak, it might be a problem.

I'm not sure about this one yet, but I think I can come up with another use case, where this double wrapping might cause problems by itself and it's a server side rendering: if I render my react app on a server with Node and then render it on a client, I would have to have a new instance of Fabric.Canvas (I cannot transfer it from server to client, so I would have to dispose the first one on a server and then instantiate a new one on a client). Though, I'm not so familiar with server side rendering with react, so for now this is only my expectations.

Anyways, it would be nice at least to understand better what dispose does and what can I expect from it.

**Comment by asturur** [comment]
The double wrapping causes problem, this is out of question and the double wrapping will be solved.
Dispose will also remove the wrapping as soon as i have time to fix it in proper way.

Dispose clear elements, clear events, and make the canvas "dead". So that should include removing the new html elemnts created for it.
