### ISSUE TITLE
Animating Zoom/Pan for canvas?

### ISSUE THREAD

**Issue by dhakan** [kangax/fabric.js#2870]
I've successfully implemented working zooming and panning, using canvas functions `fabric.Canvas.zoomToPoint` and `fabric.Canvas.relativePan` respectively.

I would like to go about animating these two operations. Unfortunately, calling these functions consecutively in a row to simulate animation is not performant at all, hence the question of whether or not there is support for this.

Is this possible?

**Comment by asturur** [comment]
did you try using the animate functions in fabricjs?

**Comment by dhakan** [comment]
Since the functions I try to animate reside on the Canvas object I don't believe this is possible. How would I go about doing what you're describing? An example perhaps?

**Comment by dhakan** [comment]
There's a reference to http://fabricjs.com/polygon-animation/ from several places which seems to be doing animations with a `fabric.util.animate` function, but the link to this example seems to be broken.

**Comment by asturur** [comment]
If you can go trought the effort of opening a stackoverflow question properly done with a starting fiddle, I, or someone faster, will help you.

**Comment by kpomservices** [comment]
I added animation for canvas zoom using fabric.util.animate as below 

        this.canvas.on('mouse:wheel', function(opt) {
            var delta = opt.e.deltaY;
            var newzoom = self.canvas.getZoom();
            newzoom = newzoom + delta/200;
            if (newzoom > 5) newzoom = 5;
            if (newzoom < 0.1) newzoom = 0.1;

            fabric.util.animate({
              startValue: self.canvas.getZoom(),
              endValue: newzoom,
              duration: 500,
              onChange: function(zoomvalue) {
                
                self.canvas.zoomToPoint({ x: opt.e.offsetX, y: opt.e.offsetY }, zoomvalue);
                self.canvas.renderAll();
              },
              onComplete: function() {
                  opt.e.preventDefault();
                  opt.e.stopPropagation();
                  self.canvas.renderAll();
              }
            });
        })
