### ISSUE TITLE
Is there the interface to create freedraw`s line with the paramter?

### ISSUE THREAD

**Issue by 7demo** [kangax/fabric.js#2871]
As we know, i can do the freedraw with the mouse or gesture. But I hope i can draw a freedraw line just with  the others`s  freedraw path data sometimes.  for example:

`var fd = new fabric.Freedraw(["M",46.62041884816754,98.1675392670157],["Q",46.62041884816754,98.1675392670157,47.12041884816754,98.1675392670157],["Q",47.62041884816754,98.1675392670157,47.37041884816754,98.1675392670157],["Q",47.12041884816754,98.1675392670157,47.5130890052356,98.1675392670157]);
canvas.add(fd);
canvas.renderAll();`

I know i should post this question on stackflow or google groups. However, nobody can help me there .
Can give me some tips?  I can`t get some useful infomation in the doc.

Thanks.

**Comment by asturur** [comment]
That is a stackoverflow question.
Anyway you can just do:

```
var fd = new fabric.Path(["M",46.62041884816754,98.1675392670157],["Q",46.62041884816754,98.1675392670157,47.12041884816754,98.1675392670157],["Q",47.62041884816754,98.1675392670157,47.37041884816754,98.1675392670157],["Q",47.12041884816754,98.1675392670157,47.5130890052356,98.1675392670157]); canvas.add(fd);
```

At the end of freedrawing what you get is a path object.

**Comment by 7demo** [comment]
Thanks for your tips.But I had tried this way before i post the question.
 And it`s so sad it didn`t not work. It shows some shapes not the freedraw line.

This is the demo : https://jsfiddle.net/SAMPAN7/nnuLhqmo/

**Comment by asturur** [comment]
The path is there in your fiddle. showing. You should know that default fill is black and that if you want something different from it you have to specify it.

https://jsfiddle.net/nnuLhqmo/1/

Please, for any other question about this topic, open a stackoverflow question.
