### ISSUE TITLE
Resize Filter broken on serialized canvas

### ISSUE THREAD

**Issue by csvehla** [kangax/fabric.js#2874]
Hello, when the canvas is serialized by calling JSON.stringify(canvas), the filters object did not serialize all of its parameters. For example, a resize filter has parameters: type, scaleX, scaleY, rcpScaleX, rcpScaleY, but after converting to JSON or toObject, rcpScaleX and rcpScaleY are missing. Also when I reload from JSON it tries to apply the resize filter again which makes my image even smaller.

I noticed that these were common issues in #1741 , but I thought they were supposed to be resolved. I have tested on master and also v1.6.0-rc.1 and I am still seeing these problems.

JSON before resize filter
`"{"objects":[{"type":"image","originX":"left","originY":"top","left":0,"top":0,"width":1670,"height":2327,"fill":"rgb(0,0,0)","stroke":"#000000","strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"filters":[],"src":"http://local.wordpress.dev/wp-content/uploads/digiwidgets-temp/down35.jpg","crossOrigin":"","alignX":"none","alignY":"none","meetOrSlice":"meet"}],"background":"rgba(0, 0, 0, 0)","canvasWidth":"200","canvasHeight":"300","templateTitle":"Small Vertical","borderStrokeStyle":"black"}"`

JSON after resize filter
`"{"objects":[{"type":"image","originX":"left","originY":"top","left":0,"top":0,"width":215.2986678126343,"height":300,"fill":"rgb(0,0,0)","stroke":"#000000","strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"filters":[{"type":"Resize","scaleX":0.1289213579716373,"scaleY":0.1289213579716373,"resizeType":"sliceHack","lanczosLobes":3}],"src":"http://local.wordpress.dev/wp-content/uploads/digiwidgets-temp/down34.jpg","crossOrigin":"","alignX":"none","alignY":"none","meetOrSlice":"meet"}],"background":"rgba(0, 0, 0, 0)","canvasWidth":"200","canvasHeight":"300","templateTitle":"Small Vertical","borderStrokeStyle":"black"}"`

**Comment by asturur** [comment]
rcpScaleX and rcpScaleY are temp vars not supposed to be serialized.

Would you mind to setup a simple fiddle where an image serialized with the filter and restored does not come back as expected?

**Comment by csvehla** [comment]
Here is the fiddle [https://jsfiddle.net/csvehla/c77ymgze/](url)

You can see in the console that after a json load the resize gets applied again. I believe this is the same issue that was appearing in #1741 .

**Comment by asturur** [comment]
i see is strange, i have to think what is the best way to handle this.

**Comment by csvehla** [comment]
Yeah is there anyway to keep the original image height and width the same or maybe keep it stored. The way we use fabricjs is for an image editor and the problem I am experiencing is that people come in with large images and when they shrink them down they are horrible quality. The resizing fixes this but that also means that I need to apply a resize only when they shrink the image after a certain amount. Also then what about reversing the image then and going back up to the original size do I need to do that through resize also?

**Comment by asturur** [comment]
The problem here is just width and height values. The image element has the same number of bytes.
I think that we should keep some original width and original height in the image as we keep original element after filtering.

Do you know that those resize filters can be also applied during scaling, instead that once at initialization? you can put the filter for resize in the resizeFilters array instead of filters. In this way the image is resized dinamically and not once at load.

**Comment by csvehla** [comment]
Yes, I have tried the dynamic resizing, but for some reason, the performance using the dynamic was extremely slow.  This is why I wanted to catch it only for certain examples, but I can try the dynamic resizing again and see what I think about the performance.

We use fabricjs as a really nice image editor in a plugin for wordpress. We have tried to make this editor as photoshop like as possible, and with fabricjs' help we have achieved something very similar to this.

**Comment by asturur** [comment]
It is slow of course, it resizes every scaling.
I'm trying to give the filters an help with webgl. i'll see what happen.

**Comment by csvehla** [comment]
Any news on this?

**Comment by csvehla** [comment]
Just checking up on the progress on this?

**Comment by asturur** [comment]
not yet, i have some other feature/bugs to close first.

About your question to restore the image as it was before, you have a copy of the original image in image._originalElement.  i think you can do image._element = image._originalElement to restore things.
