### ISSUE TITLE
Stroke Text gap alignment

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#2876]
Hi,

There is a gap in the alignment of the stroke around the text.
In the example below, on some letters there as a few pixels between the stroke and the letter.

http://jsfiddle.net/6CDFr/353/

Keep up the good work.

**Comment by asturur** [comment]
It happens on some browsers/ os/ videocard drivers.
For example in my screen there is no gap.
Can you post a picture of it?

**Comment by ncou** [comment]
![m](https://cloud.githubusercontent.com/assets/16743322/14413232/ed8eabb4-ff73-11e5-844d-b7a930b504b5.png)
![s](https://cloud.githubusercontent.com/assets/16743322/14413233/ed8f328c-ff73-11e5-8d02-035d8fd29045.png)

You can see the Gap in the "S.png" file, if i strech the letters a bit more you can see the gap in the "M.png" file.

Hope this help.

**Comment by asturur** [comment]
this is just about hardware acceleration. disable it and you will notice changes. i do not know why sometimes it happens

**Comment by ncou** [comment]
yes you are right, if i disable the accelleration, everything is right.
very strange !

thank you for your quick answer.
I will close this ticket.
