### ISSUE TITLE
applyFilters() not working with toDataURL()

### ISSUE THREAD

**Issue by kimgault** [kangax/fabric.js#2881]
When using .applyFilters(), it is rendered on the canvas, but the toDataURL() results in the object without the filter.

## Version
1.6.0-rc.1

## Test Case
http://jsfiddle.net/kimgault/unv746tr/

## Steps to reproduce
1. Declare the filter as a variable.
2. Push the filter to the image.
3. applyFilters() to the image.
4. Add image to the canvas.
4. Use toDataURL() to retrieve image. The resulting image is different than what's on the canvas.

## Expected Behavior
Image should be the same as what's rendered on the canvas.

## Actual Behavior
The image is without any of the filters.

**Comment by asturur** [comment]
applyFIlter is async and takes a callback as argument.
check:

http://jsfiddle.net/unv746tr/3/
