### ISSUE TITLE
Bugs in Docs on fabricjs.com

### ISSUE THREAD

**Issue by wovvan** [kangax/fabric.js#2882]
## Test Case
Bugs with demo links in all Docs. http://fabricjs.com/static_canvas/ --> 404 error
should be http://fabricjs.com/static_canvas

**Comment by asturur** [comment]
yes, github pages now requires a index.html for every link like that.

**Comment by asturur** [comment]
missing filters, mixins, shapes, utils and i cleared them.
So boring.

**Comment by asturur** [comment]
filters done..
