### ISSUE TITLE
Chrome, dynamic pattern render problem

### ISSUE THREAD

**Issue by IceCreamCremo** [kangax/fabric.js#2884]
hi, 

i just play the demo dynamic pattern on the chrome (http://fabricjs.com/dynamic-patterns)
and when i use 'no-repeat' it will make image extend and blur (i don't know the technical word to called it)

thanks

![screen shot 2559-04-12 at 1 08 25 pm](https://cloud.githubusercontent.com/assets/7889484/14452515/5a0df204-00b9-11e6-88b2-820f245630f7.png)

**Comment by asturur** [comment]
technically is smudging.
 we have same issue already in the tracker.

thanks for reporting anyway

**Comment by pehamraza** [comment]
getting same problem, is it fixed yet?

**Comment by asturur** [comment]
no, i should make a pure js demo, without fabricjs and report on chrome issue tracker. But i had no time yet.

**Comment by pehamraza** [comment]
ok, please share if you know any workaround with this issue.
