### ISSUE TITLE
toDataURL with browser zoom

### ISSUE THREAD

**Issue by filiperoberto** [kangax/fabric.js#2886]
## Version
1.6.0

## Test Case
http://jsfiddle.net/vk16uhbL/4/

## Steps to reproduce

1. Add some zoom to your browser (CTRL+Scroll in chrome)
2. Open http://jsfiddle.net/vk16uhbL/4/ (must be after zoom or reload the page after zoom)
3. Select the robot and click show toDataURL

## Expected Behavior
The result image should be the entire image (this is the behavior for zoom 100%):

![image](https://cloud.githubusercontent.com/assets/1403736/14469302/5f9ce814-00ba-11e6-9b5d-82e4ed6f1a3b.png)

## Actual Behavior

But I'm getting this:
![image](https://cloud.githubusercontent.com/assets/1403736/14469322/7c02f52a-00ba-11e6-9c1a-ed470e020936.png)

**Comment by filiperoberto** [comment]
Setting fabric.devicePixelRatio = 1; I was able to fix this problem, but I don't know how it's gonna affect retina displays.

http://jsfiddle.net/vk16uhbL/23/

**Comment by asturur** [comment]
Thank you very much for the notice. We should see if it is possibile to discern the pixelRatio from the actualbrowser zoom with another property somewhere.

**Comment by asturur** [comment]
Or at least read the device pixel ratio at page load and Assume that is the 100% one

**Comment by asturur** [comment]
retina screen ( devicePixelRatio ) is multiplied with userBrowserZoom and there is no way to find one of the factor exactly to divide the multiplied number. ( maybe safari / chrome offer a non standard one? )

There is no way here now. Only thing i can think of is to add a parameter to allow devs to disable retina multiplier from the dataURL. @kangax, @kienz any comment?
