### ISSUE TITLE
clone an itext will never called the callback function

### ISSUE THREAD

**Issue by Catlite91** [kangax/fabric.js#2892]
when clone an itext object:
return this.constructor.fromObject(this.toObject(propertiesToInclude), callback);

then call the function:
fabric.IText.fromObject = function(object) {
    return new fabric.IText(object.text, clone(object));
};

and the callback function never called.

**Comment by asturur** [comment]
It think that the generic clone function return the clone immediately and call a callback only if the class is async.

Something that will be addressed for clarity on newer versions.

**Comment by asturur** [comment]
i will address this in 1.6.3 if it does not create strange issues.
We can still return the element AND run the callback with element as first argument.
