### ISSUE TITLE
Unable to draw SVG on Canvas in IE Edge.

### ISSUE THREAD

**Issue by gurmukhp** [kangax/fabric.js#2897]
## Version
1.6.0

## Steps to reproduce
Load ANY SVG into FabricJS into IE 10 and IE Edge.

## Expected Behavior
SVG should load on both browsers.

## Actual Behavior
SVG loads on IE 11 but gives an error on IE 10. No errors in console.

Is this a known issue? Has anyone got a working example of a SVG on IE 10 without errors? Every framework I've tried (with the exception of canvg) doesn't seem to work.

Thanks

**Comment by asturur** [comment]
Please, attach a simple jsfiddle where you show what svg you load and how you load it ( like an image, or if you let fabric parse it).

is not a know issue.

**Comment by gurmukhp** [comment]
It's now working, the problem now only lies with PixiJS unable to render the SVG, I'll raise a bug with them. Thanks

**Comment by gurmukhp** [comment]
I've created a JSFiddle that works on IE 11 with no problems but causes an error in IE 10:

http://jsfiddle.net/gurmukh/9ffjpj7b/

**Comment by asturur** [comment]
ok this i can check as soon as i get back on a windows machine.

**Comment by asturur** [comment]
![screenshot_2016-04-17-07-08-37](https://cloud.githubusercontent.com/assets/1194048/14586595/ac463cb0-046b-11e6-8cc2-edff24cb0887.png)

you made the fiddle with 1.4.0 -.-

**Comment by gurmukhp** [comment]
My bad!

I've updated to 1.6, but the error still exists:

Unable to get property 'id' of undefined at return data.dataset.id

Hope this helps?

**Comment by asturur** [comment]
still searching for a internet explorer 10...

**Comment by asturur** [comment]
Net render 10
![image](https://cloud.githubusercontent.com/assets/1194048/15090631/3d1f0cf4-142e-11e6-80c5-2d1d18e278ae.png)

Error happens here:
http://headwayapp.co/assets/js/widget/app-938859d308.js

Is not about fabricJS is jsfiddle.

**Comment by gurmukhp** [comment]
It seems to only happen on edge on Windows 7. Edge on Windows 10 is fine.

**Comment by asturur** [comment]
edge on windows 7?
