### ISSUE TITLE
No perspective free transform on objects !

### ISSUE THREAD

**Issue by keanass** [kangax/fabric.js#2898]
Hello
any suggestions to make fabric objects perspective transformed, an issue has been opned in the past https://github.com/kangax/fabric.js/issues/27 
in 2011 there was no possibilities to make this hapen, but now i think it possible, @kangax , @asturur 
here are some links where the perspective transform works on canvas 2d context:

http://jsbin.com/toyuzakiya/edit?html,js,output
http://www.leven.ch/canvas/perspective.html

thanks and Best regards.

**Comment by keanass** [comment]
Can i contribute ?

**Comment by keanass** [comment]
no ideas about this ?

**Comment by asturur** [comment]
We are not going to support this for now.
This can't be exported to SVG, it does not fit with our control box schema, is not something that fits in the core library.

I think an external optional plugin can be written from anyone that feels like.

**Comment by keanass** [comment]
i think this will give fabric a very big popularity, will give it new look, please have a look at this : http://jsfiddle.net/xjHUk/86/

**Comment by asturur** [comment]
i know what a perspective transform is.
The problem is handling it in a coherent way across the library. How are we gonna produce this kind of transformation on svg output?
there are so many big feature missing about thia, i m not gonna implement it now.
If you want to make a PR with all the necessary changes feel free to do it, i lack time.

**Comment by asturur** [comment]
Also the fiddle posted is not canvas related at all.

**Comment by gvmafra** [comment]
8 years later, is this feature now supported?

**Comment by asturur** [comment]
Is not a feature we support nor want to support.
I have this perspective free transform and i have long running ticket at the place i work on to opensource it.
Is just hard to get a bit of traction to actually get it looked at.
