### ISSUE TITLE
Make JSON2 shim external

### ISSUE THREAD

**Issue by leesei** [kangax/fabric.js#2899]
I suggest making the JSON2 shim external.

With the data form [caniuse](http://caniuse.com/#search=json), we can update the [supported browsers](https://github.com/kangax/fabric.js#supported-browsers) list and drop those not supported:
- Firefox since 3.5
- Safari since 4
- IE since 8
- Opera since 11

**Comment by asturur** [comment]
i think the JSON module is external.
when i built the dist i forgot to exclude the JSON inclusion.
i ll rebuild it.

**Comment by asturur** [comment]
rebuilt dist, json2 excluded as it should be.
