### ISSUE TITLE
Install without Node.js

### ISSUE THREAD

**Issue by scottialex** [kangax/fabric.js#2900]
Hello, first of all thank you very much in advanced.

I need to implement fabric.js on a JavaScript/Java environment. Before I get my hands dirty with this, is it actually possible to implement fabric.js on a Java environment?

I will begin looking for a standalone JS alternative. All I really need is to be able to render Illustrator files on the browser without any other features, just read and render.

Any help is highly appreciated!

Alejandro

**Comment by asturur** [comment]
if you mean an "ai" file, no is not supoorted.
if you mean an SVG yes.

**Comment by asturur** [comment]
@scottialex can you clarify what kind of files you need to render or close the issue please.

**Comment by scottialex** [comment]
Hi, I was looking for .ai file support specifically but after further research I found no such feature anywhere. When people say "Adobe Illustrator file support" they are referring to SVG format.

I will close this ticket now.

Thank you.
