### ISSUE TITLE
'mouse:over' event is not triggered on canvas when moving mouse cursor from out of the canvas to canvas object

### ISSUE THREAD

**Issue by pavelKozlov** [kangax/fabric.js#2906]
# Version
1.5.0

# Test Case
http://jsfiddle.net/o07eeww5/1/

How it works: rectangle changes it's color to green on mouseover and to red on mouseout.

# Steps to reproduce
* Move mouse cursor over square. It changes color to green ('mouse:over' event)
* Move mouse cursor to the right out of canvas through rectangle. Color changes to red ('mouseout' event on canvas). But I expected 'mouse:out' event to be fired that also could be a bug.
* Move mouse to the left to hover rectange
# Expected Behavior
'mouse:over' event triggered on canvas (rectange changed it's color to green)

# Actual Behavior
* 'mouse:over' is not fired

**Comment by asturur** [comment]
similar to this i was investigating today.

https://github.com/kangax/fabric.js/issues/2416

MouseUP does not fire also if we come from outside the canvas.

**Comment by asturur** [comment]
mmm not really.

```
var upperCanvas = canvas.getSelectionElement();
$(upperCanvas).on('mouseout', function(e) {
  canvas._hoveredTarget = null;
	setColorAndAppendText('#ff0000', 'canvas mouse out');
});
```

if you plan to monitor yout events on the element directly, you should voi the _hoveredTarget when canvas mouse out happens.

**Comment by pavelKozlov** [comment]
I expected 'mouse:out' event triggered and canvas._hoveredTarget cleared when I move cursor out of the canvas because mouse cursor doesn't hover object anymore.
Is there any reason to not clear it?

**Comment by asturur** [comment]
when you move out of the canvas we do not have any events over it.
That is why you bound your own event there. Maybe we could support it, but definitely not a bug.

**Comment by pavelKozlov** [comment]
Thank you, @asturur.
