### ISSUE TITLE
Installing in Ionic breaks Android build. iOS OK.

### ISSUE THREAD

**Issue by helloejsulit** [kangax/fabric.js#2909]
Hi guys,

I have a problem installing it in Ionic. I used 

`bower install fabric`

to use it in my Ionic project, but then, building it in android gives me an error:

![screenshot 2016-04-22 18 12 24](https://cloud.githubusercontent.com/assets/8594565/14803778/3f1142ae-0b8f-11e6-8044-0e9eca4b12cc.png)

Running on iOS seems to be working fine. 

What could possibly be the problem? Thanks!

**Comment by asturur** [comment]
Please attach some log. Here we see only android log.

**Comment by helloejsulit** [comment]
Well, that only shows up when I install fabric to ionic. I don't know what am I missing here, I've been working on this for 2 weeks

**Comment by asturur** [comment]
Yes but as you can see, the message is about your manifest.xml
Please che the @drawable/icon on your resources xml and check that you did not delete the file or that you picked up something then overwritten by the installation of fabric.js
If you track it down to fabricjs, write again here i will reopen it.

**Comment by helloejsulit** [comment]
So I have checked it and uninstalled fabricjs from my ionic project:

![screenshot 2016-04-26 09 36 53](https://cloud.githubusercontent.com/assets/8594565/14804082/8badaaaa-0b92-11e6-855d-4bc5734117c9.png)

then I ran 

`ionic build android`

![screenshot 2016-04-26 09 36 09](https://cloud.githubusercontent.com/assets/8594565/14804085/99cebdd6-0b92-11e6-90cf-32a68dcd74b7.png)

then I install fabricjs again with 

`bower install fabric`

![screenshot 2016-04-26 09 41 06](https://cloud.githubusercontent.com/assets/8594565/14804129/15a56e46-0b93-11e6-8db6-fc475f86a802.png)

then I ran 

`ionic build android`

again, and then this

![screenshot 2016-04-26 09 42 32](https://cloud.githubusercontent.com/assets/8594565/14804147/3abaeb8e-0b93-11e6-91dd-cdcbbddd2f86.png)

Thank you for your time helping me through this.
