### ISSUE TITLE
Installing Fabric.js in Ionic still breaks Android build. iOS OK.

### ISSUE THREAD

**Issue by helloejsulit** [kangax/fabric.js#2910]
So I have uninstalled fabricjs from my ionic project then I ran

`ionic build android`

![screenshot 2016-04-26 09 36 53](https://cloud.githubusercontent.com/assets/8594565/14804554/195cd1d8-0b97-11e6-9756-1c26a4be217c.png)

![screenshot 2016-04-26 09 36 09](https://cloud.githubusercontent.com/assets/8594565/14804543/0b47cddc-0b97-11e6-81d1-0d795fce6348.png)

then I install fabricjs again with

`bower install fabric`

![screenshot 2016-04-26 09 41 06](https://cloud.githubusercontent.com/assets/8594565/14804568/35ca602e-0b97-11e6-94d2-7a8b927dc5e8.png)

then I ran

`ionic build android`

again, and then this

![screenshot 2016-04-26 09 42 32](https://cloud.githubusercontent.com/assets/8594565/14804571/3f532f90-0b97-11e6-9440-d0c688a3eef8.png)

When it comes to iOS build, everything works OK:

![screenshot 2016-04-26 10 22 22](https://cloud.githubusercontent.com/assets/8594565/14804780/cfcef198-0b98-11e6-8aa4-451afab66a5f.png)

**Comment by asturur** [comment]
As i explained before this is more an android fault or ionic framework.
Did you try running with --stacktrace option as suggested from the help?

**Comment by asturur** [comment]
moved on stackoverflow by user.

**Comment by andrescruz** [comment]
Were you able to come up with a solution for this? I noticed this issue as well with a blank starter app.

**Comment by helloejsulit** [comment]
Yes I did. Just keep fabric.js file inside the dist folder and remove the other 3 files in it and you're good to go.

**Comment by andrescruz** [comment]
I was able to even leave fabric.min.js. Probably had something to do with the fabric.min.js.gz file.

**Comment by helloejsulit** [comment]
Good thing all functionalities are still there. Awesome!

**Comment by penniath** [comment]
Removing the GZ file is the only way to get Fabric working on Ionic?
It has to be a fancier way to solve this.
