### ISSUE TITLE
setFill in parts of an image

### ISSUE THREAD

**Issue by GiseleLima** [kangax/fabric.js#2911]
Hello,
First I would like to inform you that I asked the question in the stackoverflow:
http://stackoverflow.com/questions/36868521/how-to-insert-fill-color-in-image-with-fabricjs

I consulted the manual:
http://fabricjs.com/docs/fabric.Image.html

But still not clear to me if the fabricjs allows fill coloring parts of an image

**Comment by asturur** [comment]
StackOverflow is the perfect place to ask those things.
As soon as i have time, i will answer there.
