### ISSUE TITLE
Fabric JS Text Curve Issue while adding multiple objects

### ISSUE THREAD

**Issue by ashishbhattb** [kangax/fabric.js#2912]
## Version
1.6.0
Text Curved Issue

## Test Case
http://jsfiddle.net/qpJTz/335/

## Steps to reproduce
Added 2 Fabric Object 

## Expected Behavior
It Should Work properly while selecting controls and moving the objects

## Actual Behavior
Here in below URL its working fine if we added 1 single object 
http://jsfiddle.net/qpJTz/333/

**Comment by asturur** [comment]
Take https://rawgit.com/EffEPi/fabric.curvedText/master/fabric.curvedText.js  and uncomment line 436 and 468.
We do not support that extension here.
