### ISSUE TITLE
when is rendering completed ?

### ISSUE THREAD

**Issue by ajoslin103** [kangax/fabric.js#2913]
How can I find out when rendering is completed?

I find renderAll() to be async - my debugger shows it to be completed and then additional after:render events keep coming in until everything is rendered. 

My canvas consists of groups, each one containing a text or an image, which allows me to easily apply labels and borders and such like to each text or image object.

I have implemented a listener on the after:render which tells me when those events have stopped firing for a threshold number of milli's -- but this is coincidental at best.

I need to know when rendering is done after each user action (adding/deleting objects, aligning them, resizing them, etc...) so that I can push the canvas state into my undo stack.

If I understood how and where rendering is done I'd be glad to work towards emitting an event, or running a callback, or something...

Can anyone provide any insights or other solutions ?

thanks

**Comment by asturur** [comment]
renderAll should be sync, absolutely, sync and on main thread.
after:render fires at the end of render.

But consider that when you move or scale an object, at least 10 or 20 renderAll occurs.
Is this clear to you?

**Comment by ajoslin103** [comment]
Ok, that explains why I continue to see after:render events even after my call to renderAll().  But my problem remains - how can I know when rendering has completed?

**Comment by asturur** [comment]
if you want detect user interactions ( moving, scalign ,rotatin and skewing ) use object:modified.
Rendering completes with after:render and starts with before:render.
What do you mean by "rendering complete"?

**Comment by ajoslin103** [comment]
I've been working a lot on this this morning and have realized that it's the initial loading of my canvas that is the issue -- some of the items are remote images and they were coming in later.

I add all the objects and then after that all the after:renders show up.  Not all the objects I add are remote, and even those don't render until after I'm done adding everything -- I think that is where I must have gotten the idea that the renderAll was async.

Now that I've got a better idea about how things actually are happening -- I think I'll just count the after renders, there are the same number of them as the number of objects that I added.

Thanks for helping me to understand what was really going on

**Comment by ajoslin103** [comment]
Ah, now I see what was confusing me -- the two images I add using fabric.Image.fromURL() don't seem to result in after:render events 

Why is that ?

**Comment by keanass** [comment]
I had the same problem and fixed it manually.

**Comment by ajoslin103** [comment]
@keanass - I don't understand what you mean.
@asturur - I was miscounting, the one's added via fromURL() are indeed resulting in after:render events

**Comment by ajoslin103** [comment]
@asturur - sorry, no I was right. The one's added via fromURL() are not resulting in after:render events

**Comment by asturur** [comment]
Ok Guys let's make thing clearer.

- after:render fires only from renderAll funcion, that is a fact.
- Every canvas.add or canvas.remove result in renderAll unless differently asked by "renderOnAddRemove" parameter.

At this point or @ajoslin103 post  its code or better move to stackOverFlow.

**Comment by ajoslin103** [comment]
thanks you for the clarity

I am convinced that the problem is somewhere in my code

I am closing this issue
