### ISSUE TITLE
globalCompositeOperation and shadows

### ISSUE THREAD

**Issue by VictorHagsand** [kangax/fabric.js#2914]
Im having a Rect that i place in the background using globalCompositeOperation: 'destination-over', and to this i want to have a shadow, but this does not work as the shadow does not "follow" the Rect and stays on top of everything and it looks really ugly.
## Version

1.6.0
## Steps to reproduce

Create a Rect with globalCompositeOperation: 'destination-over'
Attach a shadow to it
## Expected Behavior

Shadow to follow object when using globalCompositeOperation: 'destination-over'
## Actual Behavior

Shadow stays on top

**Comment by asturur** [comment]
Hello victor, please leave a working fiddle, for me is very time saving in checking, deciding what to do and propose a fix or an alternative. Thanks.

**Comment by VictorHagsand** [comment]
I understand, sorry.
Here you go:
http://jsfiddle.net/bLke645p/

**Comment by asturur** [comment]
it is ugly as hell.
i think this can be solved in one way only, drawing the rect + shadow in a separate context, and use that as a source image, object cache more or less.

those days i'm working a lot on fabricjs but i have no short term fix for this.

**Comment by VictorHagsand** [comment]
Thanx for looking into this, i was afraid it was not easy to solve, since it seems like its how the html canvas works as well. Drawing in á separate context is a good idea, will have a look at it.

**Comment by asturur** [comment]
this is one of those things that will look different between fabric with cache and without.
And i can do little about it.
