### ISSUE TITLE
IText (/Textbox) buffer bug when implementing placeholder?

### ISSUE THREAD

**Issue by ajck** [kangax/fabric.js#2920]
## Version
1.6.1

## Test Case
http://jsfiddle.net/Da7SP/67/

There are two separate (but probably related) problems:

## First problem:
Double click in the IText to enter editing mode. Type a single character on your keyboard. Character will appear normally. Type a second character. Character will appear but the placeholder text will also appear added onto the string. This should be impossible as the placeholder text was cleared from the string when the first character was typed. Is it appearing from an internal buffer or something?

## Second problem:
(When the IText is empty with the placeholder showing and not in editing mode)
Double click in the IText to enter editing mode. Type a single character on your keyboard. Character will appear normally. Now hit backspace to delete the character you just typed. Placeholder will appear. Now type another character. Nothing appears. Console logging and testing shows that this is because in the case of this character although "text:changed" event is firing, the new character has not been added to the IText string so that the string comparison on line 37 of the Fiddle sees the IText contents as the same as the placeholder (it should be different because the newly typed character should have been added to it). If you now press a second character it will behave as it should - the character is added in and the placeholder disappears.

## Additional question:
When the placeholder is visible is there a way to keep the cursor at position 0? E.g. user can click/tap elsewhere in the placeholder to move the cursor there, but this should not be allowed when the placeholder is visible.

**Comment by asturur** [comment]
http://jsfiddle.net/Da7SP/68/

try to update a this._updateTextarea where i did.
the onInput event works with the textarea content that does not get synced during a setText().

I really do not know if this is a bug or a misuse of textChange event.

You are trying to simulate a placeholder functionality but i do not know if with the current structure of onInput is possible.  this._updateTextarea may look fine, but i know it would kill the onCompositionUpdate and so japanese text.

Consider to do obj._hiddenTextarea.text = object.text if you do not want to update ALL the textarea properties.

**Comment by ajck** [comment]
OK, thanks for the suggestion, looks like it works but I don't want to screw up Japanese etc. text!

**Comment by asturur** [comment]
so you should not update the text by yourself while typing. you should try to hide a img between your textbox with the placeholder that then you hide as an alternative

**Comment by ankit0405** [comment]
Hi, I noticed that this issue still prevails. Has anyone done anything about it?
