### ISSUE TITLE
iText select all (Command + A) doesn't work on Mac

### ISSUE THREAD

**Issue by AdamMerrifield** [kangax/fabric.js#2929]
## Version
1.6.1

## Test Case
https://jsfiddle.net/Da7SP/69/

## Steps to reproduce
Open the test case on a Mac. Try to select all with key combo (Command + A)

## Expected Behavior
All the text should be selected

## Actual Behavior
Nothing happens

It appears that [this commit](https://github.com/kangax/fabric.js/commit/036bc9ab840b0431f42ed23827f0060c9255a8fa) broke this. It moved "CTRL + Key" combinations to keyup. Sadly [on Mac when the Command key is pressed the keyup event is NOT fired](https://stackoverflow.com/questions/27380018/when-cmd-key-is-kept-pressed-keyup-is-not-triggered-for-any-other-key). As far as I can tell select all is the only thing that needs to be in onKeyDown.

I'd also like to add while "Command + A" does not work, "Control + A" runs `selectAll` when it should not.

**Comment by asturur** [comment]
Thanks for the info! i actually lack a MAC.
Does CTRL + A select all actually? I mean, does user have a chance to do selectAll()?

**Comment by asturur** [comment]
Also i see that select All on key UP is ugly by a user experience point of view.
I will move back to keydown.
Copy has to stay on keyUP for some bad internet explorer behaviour.

**Comment by AdamMerrifield** [comment]
When I hold the `control` key and press `A` `selectAll()` DOES run, but this is incorrect behavior according to [Apple](https://support.apple.com/en-us/HT201236).

> Control-A	Move to the beginning of the line or paragraph.

**Comment by asturur** [comment]
ctrl + A going line start is sick...
you ll get a pr soon for the selectAll.

**Comment by AdamMerrifield** [comment]
I agree. Thank you for looking into this!
