### ISSUE TITLE
object.borderScaleFactor

### ISSUE THREAD

**Issue by asturur** [kangax/fabric.js#2930]
We have a property:
borderScaleFactor that is the inverse of the thickness of the object control box border.
Influences borders but not the borders of controls when drawn in transparent mode.

@kangax @kienz, someone of you remember why has been introduced?

I'm inclined towards making it the border tickness and not the inverse of and apply it to controls borderds. ( actually a borderScaleFactor of 2 produces a border of 0.5 pixel, counter intuitive)

OR

remove it

Any suggestion?

**Comment by kangax** [comment]
Probably best to remove since it's so specific...

**Comment by asturur** [comment]
Yes i see an utility now in this mood of controls customization, but at least used as a multiplier and not a divider.
