### ISSUE TITLE
Error in createSVGFontFacesMarkup function - char is a reserved keyword

### ISSUE THREAD

**Issue by haloween** [kangax/fabric.js#2934]
Hello,

createSVGFontFacesMarkup uses a variable named "char", that's a reserved keyword and yui compressor in sencha touch doesn't allow to compress the app source. 

`var markup = '', fontList = { }, obj, fontFamily,
style, row, rowIndex, char, charIndex,
fontPaths = fabric.fontPaths;`

The variable name should be changed to something that's not reserved. 
http://www.w3schools.com/js/js_reserved.asp

Thanx

**Comment by asturur** [comment]
my bad for sure. i ll correct it.
