### ISSUE TITLE
Text dissapear from a canvas when caching property is false

### ISSUE THREAD

**Issue by m2broth** [kangax/fabric.js#2937]
## Version
1.6.1

## Test Case
http://jsfiddle.net/Da7SP/70/

## Steps to reproduce
Create an i-text object and set the "caching" property to false
## Expected Behavior
Text dissapears from text box
## Actual Behavior
Text renders correctly

**Comment by asturur** [comment]
that's new...

**Comment by m2broth** [comment]
Could you tried to set this property to false and type some text?

**Comment by asturur** [comment]
@m2broth would you try the fix i proposed?

after` this.caching && (this._charWidthsCache[cacheProp] = width);`
add `return width;`

**Comment by m2broth** [comment]
Hi
I have checked the issue and it was fixed. Thanks
