### ISSUE TITLE
Image Filters: Blend filter dosen't extend from fabric.Image.filters.BaseFilter

### ISSUE THREAD

**Issue by tartexs** [kangax/fabric.js#2938]
Blend filter does not extend from baseFilter (file: https://github.com/kangax/fabric.js/blob/master/src/filters/blend_filter.class.js)

then don't have support for toJSON method when canvas.toJSON is called.

**Comment by asturur** [comment]
Closed via https://github.com/kangax/fabric.js/commit/c4911406ac1af99730ea9879f79fec650f01bb07

**Comment by asturur** [comment]
and thanks
