### ISSUE TITLE
toDataUrl multiplier not applied to shadow's values

### ISSUE THREAD

**Issue by plainview** [kangax/fabric.js#2939]
## Version
1.6.1

## Test Case
http://jsfiddle.net/yfzv4x87/

If you are on retina screen then you must scroll all the way to the bottom right in jsfiddle render.  The image is very large on retina.  Not so big on 1:1 pixel ratio screen.

Screen shot of jsfiddle:
![screen shot 2016-05-04 at 2 57 48 pm](https://cloud.githubusercontent.com/assets/232863/15025705/9a114d1e-1208-11e6-8200-b1842064d4bb.png)

On top is canvas, on bottom is img.  Notice shadow in img.

## Steps to reproduce
1. Create textbox with shadow
2. Take toDataUrl of textbox with multiplier of 5
3. Insert data url into image

## Expected Behavior
Image's shadow matches canvas shadow

## Actual Behavior
Image shadow appears less offset and less blurred than canvas original

Screen shot of canvas:

![screen shot 2016-05-04 at 10 32 50 am](https://cloud.githubusercontent.com/assets/232863/15025607/0c9eb886-1208-11e6-905e-b1e6b3cd4062.png)

Screen shot of image, after multiplier applied to data URL:

![screen shot 2016-05-04 at 10 32 56 am](https://cloud.githubusercontent.com/assets/232863/15025624/1f0dad92-1208-11e6-8539-414ebbfda9ff.png)

**Comment by asturur** [comment]
https://github.com/kangax/fabric.js/blob/master/src/mixins/canvas_dataurl_exporter.mixin.js#L128

Problem is here.
html canvas never scale the shadows. We scale the shadow keeping track of the multipliers from canvasZoom and objectZoom and retinaZoom.

When we set a direct ctx.scale() like that we fail at recovering it later when is time to render the shadows.
