### ISSUE TITLE
Groups loadFromJSON makes everything rgb(0,0,0)

### ISSUE THREAD

**Issue by wushan** [kangax/fabric.js#2941]
I was making some subclasses from fabric.Group and give it a custom type name, but when loading them back to the scene via loadFromJSON, it turns everything in the group to black (rgb(0,0,0))

I forked this fiddle from kangax's demo, and please help with this. Am I doing anything wrong ?

[jsFiddle](http://jsfiddle.net/wushan/sn9xtmoq/)

**Comment by asturur** [comment]
http://jsfiddle.net/sn9xtmoq/1/
You subclassed group from 1.5.0, there was a bug there.
Please check updated init and fromObject.
