### ISSUE TITLE
Can't load an SVG into setOverlay Image in Firefox

### ISSUE THREAD

**Issue by timwright12** [kangax/fabric.js#2945]
## Version

1.6.1
## Test Case

http://codepen.io/timwright12/pen/zqyjWN
## Steps to reproduce

Load an SVG into the canvas via setOverlayImage()
## Expected Behavior

SVG loads into the canvas overlay
## Actual Behavior

No image displayed

**Comment by asturur** [comment]
strange indeed.
Is not a scaling issue.
and also the svg does not import good..
```xml
<svg id="numbers" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 7.6 10.23"><defs><style>.cls-1,.cls-2{fill:none;stroke:#231f20;stroke-width:1.01px;}.cls-2{stroke-linecap:round;stroke-linejoin:round;}</style></defs><title>9</title><path class="cls-1" d="M717.59,551c-0.1-1.37,1.18-2.89,2.93-3.36,2.41-.65,3.48.51,3.64,1.52,0.23,1.49-1.42,3.25-3.25,3.52S717.68,552.22,717.59,551Z" transform="translate(-717.08 -546.91)"/><path class="cls-2" d="M717.77,556.64a8.92,8.92,0,0,0,4.64-2.81,11.12,11.12,0,0,0,1.68-3.85" transform="translate(-717.08 -546.91)"/></svg>
```

**Comment by asturur** [comment]
The image get loaded with width 0 and height 0. I think is a firefox svg parsing problem.

**Comment by asturur** [comment]
I checked again this bug. Is Firefox fault, i opened a bug but we can work around it.

**Comment by asturur** [comment]
well looks like the only way to have a clue about that image dimension is appending it to DOM and then reading width and height. I do not want fabric to append things to DOM just overcome this. i guess we have to stick with 300 and 150 ( naturalWidth and  naturalHeight ) default values if the browsers does not help us. I opened an issue to firefox bug tracker just in case is worth to fix

**Comment by asturur** [comment]
ok i talked to soon, is a firefox bug, here: https://bugzilla.mozilla.org/show_bug.cgi?id=700533
Open since 2011, i do not think it will be fixed soon.

**Comment by niyotaa** [comment]
Hi asturur, can you please provide a workaround for the issue?

**Comment by ncou** [comment]
Hi,

I think for the moment you need to use a .png instead of the .svg file.
Same behavior in the IE11 browser...

**Comment by asturur** [comment]
Sorry i never replied, the only workaround is to provide a width and height to svg file

**Comment by asturur** [comment]
surrended to the idea of fast appending an image to the doc, since we are doing the same with the hiddenTextarea, we are doing this also for svg dataurls now.
