### ISSUE TITLE
Applied filters are not exported using canvas.toDataURL

### ISSUE THREAD

**Issue by AubreyHewes** [kangax/fabric.js#2947]
## Version
1.6.1

## Test Case
https://jsfiddle.net/ojt42731/

## Steps to reproduce
* Add an image to a canvas
* Apply a filter on the image
* Export the canvas to an image via `toDataURL`

## Expected Behavior
Filter is also exported via `toDataURL`

## Actual Behavior
Filter is not exported via `toDataURL`

**Comment by asturur** [comment]
https://jsfiddle.net/ojt42731/1/

apply filter is async. please check updated code.
