### ISSUE TITLE
Underline problem with align = justify

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#2953]
Hi,

I got an error whith the justify text align if i use underline.

I made a codepen here :
http://codepen.io/anon/pen/KzJXQN

The steps to reproduce are :

- Edit the text to select the word 'Click to' and use underline : you got the following picture (two word are underlined) :  
![image](https://cloud.githubusercontent.com/assets/16743322/15099134/e42d4a5e-154d-11e6-8200-c75199d97d51.png)

Now click on the "align justify" button, the underline is lost beetween the 2 words : 
![image](https://cloud.githubusercontent.com/assets/16743322/15099137/12be1538-154e-11e6-8fd2-74e81a0ce714.png)

If you click on the button "align right" the underline is back to the normal.

On some other tests it' become from : 
![image](https://cloud.githubusercontent.com/assets/16743322/15099151/5d23dab8-154e-11e6-8acf-ef258ecbc0d5.png)
to (once the justify mode is applyed) : 
![image](https://cloud.githubusercontent.com/assets/16743322/15099158/734f4be2-154e-11e6-8335-c3952488d4d8.png)

Do you have an idear ?

**Comment by asturur** [comment]
With  text justify there are no whitespaces between words, so the underline does not get painted.
the other  example i have no idea how did you do it.

**Comment by ncou** [comment]
there is something strange beetween : i select the text and i apply an align style, and i directly select the textbox and i apply a style.

for example : 
- 1) click on the textbox (without editing it). click on "align justify", click on the "underline". i got : 
![image](https://cloud.githubusercontent.com/assets/16743322/15100152/3be7e0b2-156a-11e6-830e-147beb4656fc.png)

-2) click on the textbox and edit the content (double click). Select all the text => click on "align justify", click on the "underline" still with the selection text. i got : 
![image](https://cloud.githubusercontent.com/assets/16743322/15100162/84248c2c-156a-11e6-81c6-e95b84e643ba.png)

It's really strange.I got other strange behaviours on my site web, i am trying to reproduce them on the codepen example.

**Comment by asturur** [comment]
Yes there is difference if you underline the textbox or you underline the single characters.
Nothing i can fix as of now. I do not know how we should handle the underline of full textbox, if with or without spaces.
