### ISSUE TITLE
Trouble saving current canvas

### ISSUE THREAD

**Issue by nikksan** [kangax/fabric.js#2958]
Hey ,
I am having issues with saving the canvas state.Some thing is wrong on our side.
For example , if I try to save the current canvas and load it again,I get different result.(It is actually the same however its zoomed in a weird way).
Please have a look - http://kineticmall.com/index.php?route=product/product/customize&category_id=88
You can replicate the issue easily - use:
` canvas.loadFromJSON(JSON.stringify(canvas))`
Is there anything wrong with the svg?

**Comment by asturur** [comment]
You are on 1.4.13.

Please make a test on 1.6.1 on jsfiddle and i will reopen the issue.

**Comment by nikksan** [comment]
It works ! 
Thank you!
