### ISSUE TITLE
Inconsistent rendering with '*.center()' function in 1.6.1

### ISSUE THREAD

**Issue by quantumjockey** [kangax/fabric.js#2959]
On startup, '*.center()' function places associated object in the middle of the canvas space, but bounding box for mouse events seems to remain in the upper left-hand corner of the canvas overlapping origin. 

Here's a JSFiddle demonstrating this behavior: 
https://jsfiddle.net/quantumjockey/v4svfaoj/20/

After clicking in the upper-left-hand corner within the area that the rectangle has covered though, expected behavior ensues.

**Comment by asturur** [comment]
you have to call setCoords() after modifyong object position. or first center it, then add to canvas.

**Comment by quantumjockey** [comment]
Okay, cool! (Sorry about that and thanks much!)
