### ISSUE TITLE
'*.selectable=false' prevents dragging, etc of object, but bounding box remains (1.6.1)

### ISSUE THREAD

**Issue by quantumjockey** [kangax/fabric.js#2960]
When non-selectable objects are rendered it seems that a bounding box shows upon click, implying selection and manipulation capability where those capabilities are neither available nor expected.

Here's a JSFiddle demonstrating this behavior: 
https://jsfiddle.net/quantumjockey/e6Ldma7q/4/

When clicking on the movable square (red) the bounding box shows up and behaves as expected, but when the non-selectable/static square (blue) is clicked the manipulator box shows. This is confusing and not behavior I see in earlier versions of the library.

I remember reading somewhere in the documentation that mouse-events would be fully-supported for non-selectable objects in later versions. Is this behavior consequent to an implementation of those features that is in progress?

**Comment by asturur** [comment]
this i have to check.

**Comment by a5ync** [comment]
If I am not missing anything else, setting hasBorders and hasControls of the non-selectable object to false seems to fix this inconsistency

staticSquare.hasBorders = false;
staticSquare.hasControls = false;
https://jsfiddle.net/a5ync2/La6p0tLw/

**Comment by asturur** [comment]
Ok is a regression already fixed in current codebase.

fixed here: https://github.com/kangax/fabric.js/pull/2924/files

Thanks for spotting anyway.
