### ISSUE TITLE
double click ITEXT and TEXTBOX does't select text

### ISSUE THREAD

**Issue by fahadnabbasi** [kangax/fabric.js#2962]
## Version
1.6.1

## Test Case
http://jsfiddle.net/fahadnabbasi/154dbmtt/

## Steps to reproduce
Double click on text to edit
Once in editing state, double or tripple click

## Expected Behavior
select one word on double click
select one line on tripple click

## Actual Behavior
nothing happens, previously it used to select one word or one line

**Comment by asturur** [comment]
it works for me.
Please add:
operating system, browser used. Touch or mouse device.

**Comment by fahadnabbasi** [comment]
Windows 10
Chrome Version 50.0.2661.94 m
Mouse

**Comment by fahadnabbasi** [comment]
Just confirmed that it works fine on Firefox and Opera, the problem is only in chrome

**Comment by fahadnabbasi** [comment]
It is fixed automatically, I don't know what happened but now it is working fine and I didn't do anything
