### ISSUE TITLE
Unable to add function to custom Fabric object

### ISSUE THREAD

**Issue by quantumjockey** [kangax/fabric.js#2965]
I'm not sure that this is a bug or if I'm implementing this improperly, but considering that adding functions to a "superclass" of another object is doable in many other contexts I'm not sure why I'm getting this error. 

Here's a JSFiddle demonstrating my issue and the error it's generating:
https://jsfiddle.net/quantumjockey/r4gagmL9/

Basically, all I'm trying to do is over-ride the fabric.Image.fromURL() function in the 'Frindle' class, which is a custom object based on fabric.Image. This object has properties in excess of what fabric.Image provides, formalized in this custom object definition for preservation purposes during serialization/deserialization to/from JSON. Since those properties are all that differentiates this object from a normal image, it made sense to me that the fromURL function could be called and content for the base fabric.Image object initialized as expected.

Instead, the image doesn't display and I'm getting the (console) error:
'VM616:103 - Uncaught TypeError: fabric.Frindle.fromURL is not a function'

Are custom objects intended only to have custom properties, i.e. are custom functions not configurable within custom objects? If not, is there a possibility that this workflow will exist in future iterations of FabricJS?

**Comment by asturur** [comment]
I do not have so good undersdaing in how we do inheritance.
But image fromURL is not in the class if you go to see how it is defined in the source code.

Check how i modified the fidde:
https://jsfiddle.net/r4gagmL9/2/

Please be aware that type of Frindle has to be 'frindle'
