### ISSUE TITLE
object coordinates bug when it was scrolled in fixed position.

### ISSUE THREAD

**Issue by devhak2** [kangax/fabric.js#2966]
## Version

1.6.1
## Test Case

https://jsfiddle.net/devhak/0veLsh4x/2/
## Steps to reproduce
1. Click add file and choose a proper image file that is smaller than canvas.
2. a bit scrolling down.
3. drag image to outside of canvas
## Expected Behavior

top value increases gradually
## Actual Behavior

top value decreases suddenly
## Explain image

<img src="http://i.imgur.com/d88rqOu.jpg" />

**Comment by ncou** [comment]
Hi,

It looks like the "span" tag is messing with the calculation.
If you include your span in the dummy div you have set below the span, it work fine.
https://jsfiddle.net/0veLsh4x/3/
