### ISSUE TITLE
IText area doesn't enlarge in width, while typing text. When textAlign: 'justify'

### ISSUE THREAD

**Issue by OperKH** [kangax/fabric.js#2967]
## Version
1.6.1

## Test Case
http://jsfiddle.net/2ogffpwq/

## Steps to reproduce
1. Press at the middle of "add_letters_here" word.
2. Start typing a lot of letters inside this word without spaces.

## Expected Behavior
IText area should be enlarged in width, when first string became to large to fit in IText area.

## Actual Behavior
IText area didn't changed in size.
Instead of that a big word stars overflow other words in string, and even could be wider, then IText 
http://recordit.co/xROvhWYti1

## Additional info
This bug doesn't appears when textAlign is "left", "center" or "right".

**Comment by asturur** [comment]
thanks for posting from the twitter.

**Comment by OperKH** [comment]
And reducing width on justified IText, whe deleting letters, doesn't work to.
http://recordit.co/KetJPrw2kp

**Comment by asturur** [comment]
Ok the problem here is that we allow for negative space width. thanks for spotting

**Comment by asturur** [comment]
Just a note of things to solve:
Forcing the text in left justify solves majority of things.
exporting in svg has some defect, not related to this bug but to fix before merging.
