### ISSUE TITLE
Cloning Groups not working [$5]

### ISSUE THREAD

**Issue by FeaRCODE** [kangax/fabric.js#2974]
## Version

1.6.2
## Test Case

Initial Test: https://jsfiddle.net/mk9egte7/
Attempted Correction: https://jsfiddle.net/mk9egte7/6/
Expected Result: https://jsfiddle.net/mk9egte7/4/

Posted Question on StackOverflow: http://stackoverflow.com/questions/37192881/fabricjs-clipboard-implementation-copy-paste
## Description

For my Copy/Paste implementation, I clone objects/groups (and determine whether to use async clone or not). My working code tries the following (in order of test cases):
- Simply add the group to the canvas
- iterate though all objects in the group and add them to the canvas
- Added `canvas.deactivateAll();` after addition of all objects to canvas 
## Expected Behavior (in order of description)

Simply, when I create a group via selecting or programmatically, I should be able to simply add the new group to the canvas with `canvas.add(group);`. Then I should be able to simply set the active Group as this new group. 
## Actual Behavior (in order of description)

Instead, of the expected result, my objects get thrown into the upper left corner of the canvas and I can neither select or move them; however an invisible controls box is selectable/movable on screen.

**Comment by asturur** [comment]
this has something to do with deep cloning. would you try a trick to use group toObject, json.stringfiy, json.parse and finally fromObject?

something to be investigated anyway. i see group hai its own fromObject method but misses clone.
Can you clone normal groups?

**Comment by FeaRCODE** [comment]
I haven't tried cloning normal groups. I just assumed cloning would work all the way around, and adding a group to the canvas should simply duplicate everything. Again, I am VERY new to FabricJS and still am learning JavaScript personally :)

**Comment by asturur** [comment]
https://jsfiddle.net/mk9egte7/7/

I do not think cloning group is supported. In the updated fiddle you see that going trought string helps you avoiding strange behaviour ( i deleted everything except group cloning ). But the pasted group is a group. not an active selection. We should see if the library can handle this by itself.

**Comment by FeaRCODE** [comment]
@asturur I am still having issues trying to make a Copy/Paste implementation. I get some VERY strange behavior when randomly copy and pasting. 

Check out this [JSFIDDLE](https://jsfiddle.net/7g3troyu/), try and copy/paste a group. There are two issues wrong with this, the first being the fact the groups is not offset by 10 AND the groups are acting as one object, not just a selected group (where i can move each individual item). 

I realize I can use: `.forEachObject(function(e)` and add the objects,. however this seems to randomly place items onto the canvas without a consistent order. I am literally trying to mimic basic Copy/Paste functionality in Photoshop, etc.

**Comment by FeaRCODE** [comment]
@asturur I am assuming this is an issue with cloning AND adding groups to the canvas?

**Comment by asturur** [comment]
I think this is an issue with how clone of group is done.
I think that "clone" itself has been lazy made with toObject -> FromObject, whitout thinking of implications ( like deeping cloning objects ).
Cloning an activegroup is even worse.

I cannot put this in 1.6.3 because i'm very busy those days, with fabric, job, new job, girlfriend's birthday.
I submitted that solution with strings that "works". I will be back on this issue because i will need it for other things. Just i need some days, do not worry if you do not see updates.

**Comment by FeaRCODE** [comment]
@asturur Yes, but the groups are no longer separate objects. They act as one object. Is there a way for me to move individual items after i deselect the group?

**Comment by asturur** [comment]
Yes, take with a grain of salt but:
var objects = canvas.getActiveGroup.getObjects();
canvas.deselectAll();
iterate objects and clone them all,
add to a second array and add them to canvas.
Create a group with this array of object
Do not add group to canvas.
canvas.setActiveGroup(newgroup);

it should work in this way.

**Comment by ncou** [comment]
Here is a working fiddle (only for group clone) :

https://jsfiddle.net/5pnrpt6g/9/

Now fabric.js have clone with callback function for sync and asynch objects (and probably a better cloning engine).

PS : You need to deselect the group before the paste, else you will get the weird behaviours with the objects moved in the top left canvas.

Hope this help.

**Comment by samael205** [comment]
I will try Soon. thanks @ncou

**Comment by vijaygurjar** [comment]
Hello,
When is set canvas zoom on 2 and try to copy paste then selection area not draw properly and also try to move selected group not working properly. I am new in Fabric js. I am facing this issue. Please help to solve this issue

**Comment by asturur** [comment]
I think i can mark this as solved

**Comment by princ09** [comment]
Hi , I tried above all solution suggested here but nothing working as expected. 
My requirement is , Copy every property including extended properties of objects. Clone feature provided in documentation doesnot copy extended properties so i decided to use loadash cloneDeep method. This method worked perfectly but somehow internally copied and original object remain conneccted. If I scale copied object , original object also get scaled, same from other methods. 
following is my code,
```
copyObject()` {
		if (this.canvas.getActiveObject()) {
			this.copiedObject = this.canvas.getActiveObject();
		}
	}

	pasteObject() {
		let self = this;
		this.canvas.discardActiveObject();
		if (this.copiedObject) {
			let clonedObj = _.cloneDeep(this.copiedObject); // loadash deep clone
			//  console.log(this.copiedObject===clonedObj); false
			clonedObj.set({
				left: clonedObj.left + clonedObj.width * clonedObj.scaleX,
				top: clonedObj.top + clonedObj.height * clonedObj.scaleY,
			});
			const newCoordInv = this.getCoordsInv(clonedObj.left, clonedObj.top, this.rotation || 0);
			let coord = { left: newCoordInv.x, top: newCoordInv.y, scaleX: this.zoom, scaleY: this.zoom, angle: clonedObj.angle - this.rotation };
			self.extend(clonedObj, { id: self.randomId(), coord: coord }); //extended properties
			if (clonedObj.getObjects()) {
				clonedObj.getObjects().forEach((obj) => {
					self.extend(obj, { id: self.randomId() });
					self.extend(obj, { groupId: clonedObj.toObject().id });
				});
			}
			// console.log(this.copiedObject===clonedObj); false
			self.canvas.add(clonedObj);
			self.addStamp(clonedObj, self.currentPage);
		}
		this.canvas.discardActiveObject();
		this.canvas.renderAll();
	}
```
I know i need to provide fiddle for better understanding but its complicated code and i am not sure how to make it independent and produce same behaviour.
Still please give it try , any suggestion will be helpful.

**Comment by asturur** [comment]
You can't use lodash to clone an instance.
If clone on a group with extended props does not work, there is a bug that should be fixed.
Please reproduce the issue in a fiddle, outside your application, demonstrate the problem and open a new issue

**Comment by AmPhIbIaN26** [comment]
Cloning a group onto another canvas messes up it's controls. I have recreated it in the [jsFiddle](https://jsfiddle.net/AmPhIbIaN26/z67kr0p8/43/). After the rectangle is cloned if I select it and click on anywhere on the second canvas it messes up the controls of the rectangle.
