### ISSUE TITLE
drawing from first point position

### ISSUE THREAD

**Issue by adu42** [kangax/fabric.js#2978]
Why not separation of control and drawing positioning?
Scenes:
Drawing a polygon by mouse down, I want begin first point,center is O point, polygon fixed at a certain point.  But actually center O' is calc by {minX,minY}, when mouse down {minX,minY} will be change,then center O' change, polygon position change...

## Version
1.6.2

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
