### ISSUE TITLE
Strange controls area on importing svg

### ISSUE THREAD

**Issue by themaniac** [kangax/fabric.js#2981]
Hello all, 

on the kitchensink demo, i'm trying to load this svg (grouped):

```
    <?xml version="1.0" standalone="no"?><svg xmlns="http://www.w3.org/2000/svg" version="1.1">
    <g id="DEFAULT" display="visible">
    <path d="M291.94 240.98L292.64 240.79M292.64 240.79L293.16 240.27M293.16 240.27L293.35 239.57"
    fill="none" stroke="black" stroke-width="0.5"/>
    <path d="M293.35 208.24L293.16 207.54M293.16 207.54L292.64 207.02M292.64 207.02L291.94 206.84"
    fill="none" stroke="black" stroke-width="0.5"/>
    <path d="M293.35 208.24L293.35 239.57"
    fill="none" stroke="black" stroke-width="0.5"/>
    <path d="M231.12 223.91L231.12 223.91"
    fill="none" stroke="black" stroke-width="0.5"/>
    <path d="M231.12 223.91L231.12 239.57"
    fill="none" stroke="black" stroke-width="0.5"/>
    <path d="M231.12 223.91L231.12 208.24"
    fill="none" stroke="black" stroke-width="0.5"/>
    <path d="M232.52 206.84L231.82 207.02M231.82 207.02L231.31 207.54M231.31 207.54L231.12 208.24"
    fill="none" stroke="black" stroke-width="0.5"/>
    <path d="M231.12 239.57L231.31 240.27M231.31 240.27L231.82 240.79M231.82 240.79L232.52 240.98"
    fill="none" stroke="black" stroke-width="0.5"/>
    <path d="M232.52 206.84L291.94 206.84"
    fill="none" stroke="black" stroke-width="0.5"/>
    <path d="M232.52 240.98L291.94 240.98"
    fill="none" stroke="black" stroke-width="0.5"/>
    </g>
    </svg>
```

results is :

<img src='http://s32.postimg.org/e3hneg0lh/Senza_nome.png' border='0' alt="Senza nome" />

as you can see, i have strange selected area... how i can fix the svg in order to obtain correct control area on selecting object? 

thanks in advance

**Comment by asturur** [comment]
is not strange. The svg has no dimensions specified, the path is in the bottom corner, you are parsing a document and so you get controls from the 0,0 to the bottom right corner. maybe it can be optimized, but i wrote it recently, if i included 0,0 inside there was some reason.

**Comment by themaniac** [comment]
where i must put dimension? into <g> element?

**Comment by asturur** [comment]
Not that easy. Is this the svg you have to import? or you have many of them like this?

**Comment by themaniac** [comment]
i've some dxf files, exported to svg... probably inkscape is the problem (sincerely, i don't know if it's the best solution for converting dxf2svg)... i need to find a correct svg structure and i think i've found it (Generated with QCAD SVG Exporter PG):

<?xml version="1.0" encoding="UTF-8"?>

<svg width="250.06561486354894" height="714.0000000000009" viewBox="3044.099179216021 -1222.914029038109 250.06561486354894 714.0000000000009" version="1.1" xmlns="http://www.w3.org/2000/svg" style="stroke-linecap:round;stroke-linejoin:round;fill:none">
    <g transform="scale(1,-1)">
        paths
    </g>
</svg>

**Comment by asturur** [comment]
Yes this with viewbox will translate the object in the right position.

**Comment by themaniac** [comment]
thank you, you can suggest me the best procedure for converting dxf to svg?

**Comment by asturur** [comment]
can't help with dxf files.
The svg import feature, while is enough good, can still gets lot of benefits from importing as a normal group and respecting the group structure as already discussed here: #899
