### ISSUE TITLE
LTR CSS issue with i-text

### ISSUE THREAD

**Issue by radykal** [kangax/fabric.js#2982]
Just put direction: rtl; in body in kitchensink: http://fabricjs.com/kitchensink

Then double-click on a i-text and you see the texts are misplaced. I think it has to do with the hidden textarea and the position calculation for it, which is not working well with rtl websites.

**Comment by asturur** [comment]
rtls is not supported yet. we should specify direction: ltr in our hidden textarea.

**Comment by asturur** [comment]
duplicate of #2374
