### ISSUE TITLE
deadcode: Polyline.prototype._applyPointOffset 

### ISSUE THREAD

**Issue by djusv** [kangax/fabric.js#2983]
## Version
1.6.2

The polyline class has the following "deadcode", I couldn't find where it is called but if even it was called it would fail because the Polygon prototype doesn't have this function (anymore).

```javascript
  **
   * Polyline class
   * @class fabric.Polyline
   * @extends fabric.Object
   * @see {@link fabric.Polyline#initialize} for constructor definition
   */
  fabric.Polyline = fabric.util.createClass(fabric.Object, /** @lends fabric.Polyline.prototype */ {
....
    _applyPointOffset: function() {
      return fabric.Polygon.prototype._applyPointOffset.call(this);
    }
```

**Comment by asturur** [comment]
thanks for spotting. It was in polygon class and it was called from som shared method in the polygon _render method. Now it has been preplaced by a translation.
