### ISSUE TITLE
isContainedWithinObject reacts not on path

### ISSUE THREAD

**Issue by SkHCrusher** [kangax/fabric.js#2985]
## Version
1.6.2

## Test Case
https://jsfiddle.net/ya3u95h9/2/

## Problem
I want to check if an image is complete inside in a defined shape (in my Test Case the green area is the positive shape).
If the image leaves the shape, the border becomes red and thicker.
I check this with the “isContainedWithinObject” function, but when I place the image in the white area on the middle of the top inside the bounding area of the shape, the function returns also a true.
When you place the image a little outside of the bounding box, the result is correct - but not inside.

Is there a bug fix or a solution for that problem?

Thank's

**Comment by asturur** [comment]
Our bounding box check is with the bounding box and to the shape inside.
No solution for now, just to write the missing code.
