### ISSUE TITLE
V1.62 setZoom(v>1) not work

### ISSUE THREAD

**Issue by zingers** [kangax/fabric.js#2988]
I notice the canvas.setZoom() work normally in 1.5.0
when switch to 1.6.2 latest
setZoom(<1) work finely
setZoom(>1) not work 

hope helps

**Comment by asturur** [comment]
Please explain with a fiddle or example of what is not working.

**Comment by asturur** [comment]
Hello can you explain the problem a little bit better?

**Comment by virror** [comment]
http://jsfiddle.net/hhy0eu4s/
Not sure what version fiddle uses, but seems to work here, just change the zoom value to something bigger than 1.
