### ISSUE TITLE
fabric js does not retain properties when converted to JSON 

### ISSUE THREAD

**Issue by rak13** [kangax/fabric.js#2999]
## Version
1.6.2

## Test Case
var canvas =  new fabric.Canvas('c');
var rect = new fabric.Rect({
    left: 100,
    top: 100,
    fill: 'red',
    width: 100,
    height: 100,
    selectable: false
});

canvas.add(rect);
canvas.renderAll();
var tmp = JSON.stringify(canvas);
canvas.loadFromJSON(tmp);
canvas.renderAll();

## Expected Behavior

A red rectangle that "CANNOT" be selected and moved

## Actual Behavior
A red rectangle that can be selected and moved

**Comment by samael205** [comment]
These behavior is normal when you not add aditional custom data to export, when you exports to JSON.

Go here for more information: 

https://github.com/kangax/fabric.js/wiki/Adding-additional-object-properties-to-serialized-JSON

**Comment by asturur** [comment]
exactly.
please give a look at docs at

http://fabricjs.com/docs

we have also pretty ads to look at or click
