### ISSUE TITLE
setZoom method doesn't work after applying relativePan or absolutePan

### ISSUE THREAD

**Issue by shankscript** [kangax/fabric.js#3002]
## Test Case
https://jsfiddle.net/Shanksript/4Lqpv4cz/34/

## Steps to reproduce
set pan to point 0,0 (using relativePan or absolutePan) and try to setZoom after that.

## Expected Behavior
canvas should zoom accordingly

## Actual Behavior
zoom methods have no effect

**Comment by asturur** [comment]
yes, translate viewport is set to nan.
your fiddle is not complete. bt is not declared.

**Comment by asturur** [comment]
My bad, as most users/dev i did not read the docs before answering.

http://fabricjs.com/docs/fabric.StaticCanvas.html

search for absolutePan and relativePan documentation.
