### ISSUE TITLE
general selection logic - difficulties

### ISSUE THREAD

**Issue by DanieleSassoli** [kangax/fabric.js#3004]
Hi,
If I add 2 SVG shapes to the kitchensink sample and overlay them I'm unable to use the controls of the bottom one because the top one gets automatically selected, this didn't happen before the last update. 
Any clue of what this could be?

**Comment by asturur** [comment]
I was playing with this problem yesterday.
Can you be more specifici with a screenshot that show how they are overlaid?

It should happen with anyshape. Our selection logic select the topmost object when you click, regardless of what you selected before ( execption made for active group that is checked before ).

I was checking the code and there is some duplicate logic here and there. You can see in the PR #2997 i changed something. But i think that active object should be checked on top of the other things. before or after activeGroup.

Are you sure that this was not happening before? I remember seeing this since long.

**Comment by alanmastro** [comment]
In fact the problem is more generic and occurs with any type of element. The problem occurs with individual elements and element groups whenever there is an overlap

**Comment by DanieleSassoli** [comment]
Actually, if you say it was happening before then maybe I hadn't encountered it before, so no I'm not sure anymore. 
I'll attach a screenshot of one simple case, as you can see there are also 2 lines from the central-top controls that lead to nowhere. 
@alanmastro is right, it happens with any tipe of element! 
![immagine](https://cloud.githubusercontent.com/assets/4007741/15470929/952af382-20f3-11e6-9cbc-10a8ad302491.png)

**Comment by asturur** [comment]
The lines are probably running to 0,0 and mayne are a problem of your hardware. i cannot make them happen.
Those lines could be some strange issue with drawing the rotation handle, that is a line.
What browser are you using?

For the selection logic as of now it is like that:

on click:
is there any activegroup and the active group contains point clicked?
if yes target is activegroup and another selection process start.

No, there is no active group or we clicked outside it, so run trought all elements and return the topmost that contains point ( or makes happy other conditions with trasparencies, controls... ).

There is no check for the activeObject that has been selected. And i think there should be.

**Comment by asturur** [comment]
tipically when you have on canvas 70 elements you have difficulties selecting whatever is on the back, you have to move away top objects so that they not interfere with click.
Svgs are tricky because normally they have bigger bounding boxes than single shapes.

**Comment by DanieleSassoli** [comment]
I'm using Chrome 50.0.2661.102. I can imagine that testing all the user interaction can be big pain, I'd be very scare to make big regressions my self! 
Yes probably there should be a check fot the activeObject, I've never looked inside this part of Fabric though...

**Comment by alanmastro** [comment]
Any news?

**Comment by asturur** [comment]
@DanieleSassoli, any particular idea here? I added a key + click combination to retrieve the last rendered object during click if someone should find it usefull.

**Comment by alanmastro** [comment]
What is the combination of keys to use?

**Comment by asturur** [comment]
either control or alt. Please check file canvas.class.js in current master for default value of lastRenderedKey.
