### ISSUE TITLE
Polygon perPixelTargetFind

### ISSUE THREAD

**Issue by Uaargh** [kangax/fabric.js#3005]
## Version
1.6.2

## Test Case
https://jsfiddle.net/5t4mfu7r/6/

I create 2 Polygons, one is transparent, one isn't (the transparent one is left to the other). Both have "perPixelTargetFind" true. 

The Polygon should just be selected, when the click is located inside the object

Both get selected if you click outside of it (but inside its bounding box)

**Comment by asturur** [comment]
I think is a regression introduced recently :( i will try to fix with next release.

**Comment by asturur** [comment]
this is about grouping object that is not check the transparency check. It looks like is a bug since 1.4.13

**Comment by asturur** [comment]
That is why on per pixel drag and drop demo selection on canvas is disabled?
