### ISSUE TITLE
v 1.6.2 toDataURL with multiplier does not scale background image

### ISSUE THREAD

**Issue by rlisowski** [kangax/fabric.js#3007]
## Version
1.6.2

## Test Case
http://jsfiddle.net/jp8rL7pg/

## Steps to reproduce
click "render preview" button

## Expected Behavior
Canvas background image should be scaled up.
Image with red rectange on blue background.

## Actual Behavior
Background image is not scaled. I see green canvas background color.

**Comment by asturur** [comment]
Thanks, that is a bug, i add it to fast resolution for next release.

**Comment by rlisowski** [comment]
The same issue is with overlay image.

**Comment by butch2k** [comment]
I played a bit with the patch and experienced refreshing issues, the image being scaled up or down on zoom but the viewport was not correctly refreshed resulting in a mirrors in mirrors effect. Same effect happens on moving anything on the canvas.

It looks like the Transform matrix is being applied on each background refresh resulting in the bg being scaled down or up multiple time.

Check it out here, click the button then try to click on the canvas
http://jsfiddle.net/jp8rL7pg/5/

Either the patch relies on other patches to work correctly or there is an issue.

**Comment by butch2k** [comment]
I expect this while zooming in
![iexpect](https://cloud.githubusercontent.com/assets/961507/15719968/a23f6de6-2832-11e6-8e10-694f3632cd93.jpg)

I get this
![iget](https://cloud.githubusercontent.com/assets/961507/15719985/ad7334c2-2832-11e6-8338-568d7a1d6a4d.jpg)

**Comment by asturur** [comment]
your function 
```javascript
    /**
     * @private
     * @param {CanvasRenderingContext2D} ctx Context to render on
     * @param {string} property 'background' or 'overlay'
     */
    _renderBackgroundOrOverlay: function(ctx, property) {
      var object = this[property + 'Color'];
      if (object) {
        ctx.fillStyle = object.toLive
          ? object.toLive(ctx)
          : object;

        ctx.fillRect(
          object.offsetX || 0,
          object.offsetY || 0,
          this.width,
          this.height);
      }
      object = this[property + 'Image'];
      if (object) {
		if (this[property + 'Vpt']) {
          ctx.save();
          ctx.transform.apply(ctx, this.viewportTransform);
        }
        object.render(ctx);
      }
    },
```
the one in master:

```javascript
    _renderBackgroundOrOverlay: function(ctx, property) {
      var object = this[property + 'Color'];
      if (object) {
        ctx.fillStyle = object.toLive
          ? object.toLive(ctx)
          : object;

        ctx.fillRect(
          object.offsetX || 0,
          object.offsetY || 0,
          this.width,
          this.height);
      }
      object = this[property + 'Image'];
      if (object) {
        if (this[property + 'Vpt']) {
          ctx.save();
          ctx.transform.apply(ctx, this.viewportTransform);
        }
        object.render(ctx);
        this[property + 'Vpt'] && ctx.restore();
      }
    },
```

did you apply the patch manually?
i want to see this game anyway.

**Comment by butch2k** [comment]
Thanks a lot that did it !
I indeed patched manually failing to see the other change.

But i encountered another issue, this time after compiling the pre-1.6.3 full:
- Use two json one with just the serialized background and another with both the background and an image.
- use canvas.loadFromJSON with first json: it's ok
- Now test with the second one containing the bg image and the other image(s): the images load ok BUT the bg doesn't, it's not enlivened, backgroundImage is set to null.

Here is a quick test case (jsfiddle complains about cross-origin)
json load just an image and not the BG and json_no_image loads the BG as it should.

`		var myfabric = new fabric.Canvas("sketchpad",{borderColor:"rgba(128,0,128,0.8)",selectionLineWidth:2,backgroundColor:"#000000"});
		myfabric.setWidth(600);
		myfabric.setHeight(600);
		
		var json = {
			"objects" : [ {
					"type" : "image",
					"originX" : "left",
					"originY" : "top",
					"left" : 480,
					"top" : 540,
					"width" : 128,
					"height" : 128,
					"fill" : "rgb(0,0,0)",
					"stroke" : null,
					"strokeWidth" : 0,
					"strokeDashArray" : null,
					"strokeLineCap" : "butt",
					"strokeLineJoin" : "miter",
					"strokeMiterLimit" : 10,
					"scaleX" : 0.47,
					"scaleY" : 0.47,
					"angle" : 0,
					"flipX" : false,
					"flipY" : false,
					"opacity" : 1,
					"shadow" : null,
					"visible" : true,
					"clipTo" : null,
					"backgroundColor" : "",
					"fillRule" : "nonzero",
					"globalCompositeOperation" : "source-over",
					"transformMatrix" : null,
					"skewX" : 0,
					"skewY" : 0,
					"lockMovementX" : false,
					"lockMovementY" : false,
					"lockScalingX" : false,
					"lockScalingY" : false,
					"lockRotation" : false,
					"selectable" : true,
					"evented" : true,
					"prCharID" : "npc_57529c885c877",
					"prName" : "aboleth02",
					"prType" : "npctoken",
					"prStates" : [],
					"prBars" : [],
					"src" : "http://www.planeteroliste.com/SMF/mgal_data/albums/Galleries_des_Membres/Dir_5/69802_4c0421fddeab6fed00cad74161d777ed.png",
					"filters" : [],
					"resizeFilters" : [],
					"crossOrigin" : "anonymous",
					"alignX" : "none",
					"alignY" : "none",
					"meetOrSlice" : "meet"
				},
			],
			"background" : "#000000",
			"backgroundImage" : {
				"type" : "image",
				"originX" : "left",
				"originY" : "top",
				"left" : 0,
				"top" : 0,
				"width" : 1820,
				"height" : 870,
				"fill" : "rgb(0,0,0)",
				"stroke" : null,
				"strokeWidth" : 0,
				"strokeDashArray" : null,
				"strokeLineCap" : "butt",
				"strokeLineJoin" : "miter",
				"strokeMiterLimit" : 10,
				"scaleX" : 1,
				"scaleY" : 1,
				"angle" : 0,
				"flipX" : false,
				"flipY" : false,
				"opacity" : 1,
				"shadow" : null,
				"visible" : true,
				"clipTo" : null,
				"backgroundColor" : "",
				"fillRule" : "nonzero",
				"globalCompositeOperation" : "source-over",
				"transformMatrix" : null,
				"skewX" : 0,
				"skewY" : 0,
				"lockMovementX" : false,
				"lockMovementY" : false,
				"lockScalingX" : false,
				"lockScalingY" : false,
				"lockRotation" : false,
				"selectable" : false,
				"evented" : false,
				"prName" : "bgImage",
				"prType" : "bg",
				"src" : "http://www.planeteroliste.com/SMF/mgal_data/albums/Galleries_des_Membres/Dir_5/78243_8c9bb283d688652ece12ef11a24be62d.jpg",
				"filters" : [],
				"resizeFilters" : [],
				"crossOrigin" : "anonymous",
				"alignX" : "none",
				"alignY" : "none",
				"meetOrSlice" : "meet"
			}
		};
		
		
		var json_no_images = {
			"objects" : [
			],
			"background" : "#000000",
			"backgroundImage" : {
				"type" : "image",
				"originX" : "left",
				"originY" : "top",
				"left" : 0,
				"top" : 0,
				"width" : 1820,
				"height" : 870,
				"fill" : "rgb(0,0,0)",
				"stroke" : null,
				"strokeWidth" : 0,
				"strokeDashArray" : null,
				"strokeLineCap" : "butt",
				"strokeLineJoin" : "miter",
				"strokeMiterLimit" : 10,
				"scaleX" : 1,
				"scaleY" : 1,
				"angle" : 0,
				"flipX" : false,
				"flipY" : false,
				"opacity" : 1,
				"shadow" : null,
				"visible" : true,
				"clipTo" : null,
				"backgroundColor" : "",
				"fillRule" : "nonzero",
				"globalCompositeOperation" : "source-over",
				"transformMatrix" : null,
				"skewX" : 0,
				"skewY" : 0,
				"lockMovementX" : false,
				"lockMovementY" : false,
				"lockScalingX" : false,
				"lockScalingY" : false,
				"lockRotation" : false,
				"selectable" : false,
				"evented" : false,
				"prName" : "bgImage",
				"prType" : "bg",
				"src" : "http://www.planeteroliste.com/SMF/mgal_data/albums/Galleries_des_Membres/Dir_5/78243_8c9bb283d688652ece12ef11a24be62d.jpg",
				"filters" : [],
				"resizeFilters" : [],
				"crossOrigin" : "anonymous",
				"alignX" : "none",
				"alignY" : "none",
				"meetOrSlice" : "meet"
			}
		};		
		
		myfabric.loadFromJSON(json,myfabric.renderAll.bind(myfabric));`
