### ISSUE TITLE
canvas "mouse:up" event executed 3 times when left clicking

### ISSUE THREAD

**Issue by QuentinIUT** [kangax/fabric.js#3013]
## Version
1.6.2

## Steps to reproduce
place a "mouse:up" event on a canvas, calling a function with a simple console.log('poke'). Click on the canvas with the left mouse button

## Expected Behavior
console is logging 'poke' one time

## Actual Behavior
console is logging 'poke' three times. It seems the event is fired 3 times when clicking with the left button but only one time with the right button or wheel button.

## Additional info
I'm working with a canvas integrated in a ImpressJS slide, the aime of the click on some of the canvas element is to change slide. If I right click all is ok, but if I left click, the change is called 3 times and so the slide is not changing properly.

**Comment by asturur** [comment]
can you reproduce in a small jsfiddle?

**Comment by QuentinIUT** [comment]
It's a bit hard as I'm using a lot of dependencies and my application has become a bit complex. But I found that all is OK with the "mouse:down" event, the event is fired with left click one time, and is not fired with right click of wheel click. The problem still remain on the "mouse:up" event.

I'm sincerely sorry for the difficulties to reproduce this issue...

**Comment by asturur** [comment]
Make a fiddle, place a canvas, place an object, register event over it. If it fires 3 times is my bug, is not is yours.
Just that.

**Comment by awehring** [comment]
I had a similar bug in my application.
I had several canvases and inadvertently registered an event at several of them. So all fired (correctly).
Check carefully each of the returned event objects from where it comes.

**Comment by Uaargh** [comment]
I got the same with the new version, it works fine with the old.

**Comment by asturur** [comment]
https://jsfiddle.net/oab0utwe/1/

if i can fix it like this i cannot flag as a bug.
The eventListener array is for private use.  canvas.off is how it should be handled this.

with old version worked but there are other bugs. Now the events are handled differently ( a little bit ) so you can't use the array directly ( and you should not before ).

Anyone wants to demonstrate the problem in different way?
