### ISSUE TITLE
Adding extra properties to object is not visible in json format.

### ISSUE THREAD

**Issue by nksingh2** [kangax/fabric.js#3020]
I am adding extra properties to object,for example i am adding extra property "isObjectLocked=true" to rectangle object for the reference and when I converted this object to JSON then i cant see my added property their.

## Version
1.6.2

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

p.s. on docs check for fabric.Object class and toObject method.
