### ISSUE TITLE
Failed to load SVG to canvas  ignore svg namespace.

### ISSUE THREAD

**Issue by nikksan** [kangax/fabric.js#3026]
Hey there,
We are trying to load svg to the canvas.The svg is generated using PDFJS library ,and is quite different.

http://jsfiddle.net/5KKQ2/648/

**Comment by asturur** [comment]
make a fiddle with fabricjs loading it and explaing the problem you encounter.
try to post full svg and remove the namespaces.

**Comment by nikksan** [comment]
http://jsfiddle.net/5KKQ2/648/
