### ISSUE TITLE
iText Edit/Transform Bug

### ISSUE THREAD

**Issue by FeaRCODE** [kangax/fabric.js#3027]
## Version
1.6.2

## Test Case
http://jsfiddle.net/j1wo0d26/

## Steps to reproduce
1) Select All the Text and Delete it.
2) Re-Select the IText box and expand/skew.
3) Press a key (or simply type).

**Note:** Do this on the IText test page and the entire page goes blank (white).

## Expected Behavior
Text should just be added normally with scaling/skew in mind.

## Actual Behavior
I am assuming the canvas jumps so far off the page (or expands) that the entire page turns white.
Also, in some instances VERY stretched text is seen in the textbox.

## Final Notes:
- **Possible solution is to delete empty text instances when focus/edit mode is lost.**
-  Do this on the IText test page and the entire page goes blank (white).
- Maybe keep the page/canvas from scrolling when you are entering text that continues off canvas view.

## Bug 2
- I also noted that when transforming the Itext, the height/width do not change? The only time they change is when you keep typing. When you skew/expand the width/height don't actually update.

**Comment by asturur** [comment]
the bug comes from the fact that you are transforming a 0 width element. That makes every transformation get very high values for scale and skew, so when you put back some text, everything is amplified.
We should avoid transformation if some cases. I mark it as bug low priority for now.

**Comment by FeaRCODE** [comment]
The important part is we found it. I don't think it effects me too much. Ill try and find a way around this.
