### ISSUE TITLE
No background colour after loadFromJSON when image present.

### ISSUE THREAD

**Issue by otarsko** [kangax/fabric.js#3028]
## Version
1.6.2

## Test Case
https://jsfiddle.net/oxz3r51u/6/

## Steps to reproduce

1. Serialize canvas with background colour set and with image
2. Try to load canvas from JSON above
3. Image is there but no background colour

## Expected Behavior

Background colour should be restored from JSON.

## Actual Behavior
No background colour set.

## Note 
1. After downgrade to 1.6.0 - bug could not be reproduced (1.6.1 not tested)
2. There is similar ticket - https://github.com/kangax/fabric.js/issues/3024 but it's poorly formatted.

**Comment by asturur** [comment]
if you switch the property from background to backgroundColor it goes. Guess what happened... i'm gonna look at it.

**Comment by otarsko** [comment]
Yes, I see. Also I am using **setBackgroundColor** method to set background colour. 
Also as wrote, it fails only if there is image on canvas.

**Comment by butch2k** [comment]
Actually the problem is even more acute in 1.6.3 (did not test on 1.6.2) as if you set a background image it is not enlivened if images are present in the JSON.

**Comment by butch2k** [comment]
Ok found out where the issue comes form:

in loadFromJSON
`
    delete serialized.objects;
    delete serialized.backgroundImage;
    delete serialized.overlayImage;
    delete serialized.background;
    delete serialized.overlay;
`
Comment out the  delete serialized.background; and it should fix your issue, mine is related if i comment out delete serialized.backgroundImage; i get my images AND the background.

**Comment by butch2k** [comment]
I believe data is being deleted before this._enlivenObjects() has finished it's job. Better to call the deletes in  _this._setBgOverlay's callback i believe.
Async loading is sometimes a real pain.

**Comment by asturur** [comment]
it is a recent regression and butch2k is right. i have to delete data in the callback and restore properties.
