### ISSUE TITLE
No backgroundVpt option in /dist/fabric.js

### ISSUE THREAD

**Issue by wgrzebieniowki-kontakt** [kangax/fabric.js#3030]
## Version
1.6.2

## Test Case
http://jsfiddle.net/Da7SP/94/

## Steps to reproduce
Use any transform function and watch the background.

## Expected Behavior
According to the docs, when passing `backgroundVpt: true` option ( even without it, as it's true by default ) background should zoom along with circle.

## Actual Behavior
Background is not zoomed. As you can see [in the source](https://rawgit.com/kangax/fabric.js/master/dist/fabric.js) this option is not present in the built library. I'm using version provided by npm and the behavior is the same.

**Comment by asturur** [comment]
it is a new option and i still did not rebuild the dist folder, not released the 1.6.3
You checked the master branch that is the latest developmente build.
We push to master small changes that we are reasonably sure they work well. But master is not latest release. is just latest.

**Comment by wgrzebieniowki-kontakt** [comment]
Oh! Ok. I thought master contains latest release. Sorry for that.
