### ISSUE TITLE
Try make «fixed»  strokeWidth on scaling

### ISSUE THREAD

**Issue by Rad1calDreamer** [kangax/fabric.js#3031]
Hi, find some solutiuons of «scaling strokeWidth problem» in http://jsfiddle.net/av4hxjyr/
But it have some strange reposition effect

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

**Comment by Rad1calDreamer** [comment]
thx

**Comment by asturur** [comment]
i generally help on stackoverflow. But cannot manage all here.
