### ISSUE TITLE
Group canvas objects by defining a rectangle box programmatically instead of using mouse to drag out a selection box

### ISSUE THREAD

**Issue by manesvenom** [kangax/fabric.js#3032]
If it could create a Group by defining an area/rectangle box which canvas objects falls within the the area/rectangle box becomes a Group. 

My approach is to loop through all objects and check if an object's oCoords.tl.x, oCoords.tl.y is within the area and add it to the group.

I would suggest to create a new method GroupSelectionByRect(Rect) to return a group that contains all objects in the Rect.

**Comment by DennisSmolek** [comment]
You could do this on your own with hit detection `intersectsWithObject`

Disable renderOnAddRemove
Draw your rectangle, insert it
Do a loop with getObjects() 
Now you have all the items
remove your rectangle
reEnable renderOnAddRemove

**Comment by asturur** [comment]
There is also a method _maybeGroupObject that does this internally to fabricjs. it takes in consideration 2 points that maybe can be set outside the standard procedure.

You should look at it.
