### ISSUE TITLE
What is custom builds and what Fabric custom build with touch capability really means

### ISSUE THREAD

**Issue by gabrielstuff** [kangax/fabric.js#3033]
Hi,

I'm trying to understand what behind : 
> This demo uses custom version of Fabric with touch events enabled. Try dragging an image, shaking, longpressing it or changing orientation.

We have noticed that, this demo works really neat and it is a pleasure to use with a touch screen.
Un fortunately the same example with fabric installed from npm does not give the same level of fidelity. Even importing events.js library does not help.

Would you mind giving us more details about the custom build process and how to achieve it from npm.

Thanks !

Link: http://fabricjs.com/touch-events

**Comment by asturur** [comment]
to include touch events you should run from a prompt where nodejs is available:
fabric.js-folder> node build.js modules=ALL exclude=JSON

this will create the complete library minus the JSON polyfill that i do not think you need.
