### ISSUE TITLE
Clear doesn't fully remove objects

### ISSUE THREAD

**Issue by paulsohops** [kangax/fabric.js#3034]
## Version
1.6.2

## Steps to reproduce
Add a selectable object to the canvas then call `canvas.clear()`. You will still be able to select and drag around an invisible object (the object's "ghost") where the old one used to be. This ghost can overlap other objects and make them unselectable.

## Expected Behavior
Calling `canvas.clear()` should fully clear the canvas to the initial clean state.

## Actual Behavior
Ghosts everywhere. Calling `canvas.remove(object)` produces the correct/expected behavior of fully removing the object.

**Comment by asturur** [comment]
i think this has been fixed with this: #3023 
can you make a fiddle to test it?

**Comment by paulsohops** [comment]
I'm using the latest commit (https://github.com/kangax/fabric.js/commit/9ef51ff77d80dc3df8808538c5f7670473629b68)

**Comment by asturur** [comment]
please jsfiddle. i need help to fix things here.

**Comment by asturur** [comment]
did you build the library or just using latest commit?
