### ISSUE TITLE
I am working on svg parsing project  in elicpse. I have also included the fabric.js file the project but stiil I got the error.  Uncaught ReferenceError: fabric is not defined

### ISSUE THREAD

**Issue by ashish-tupate** [kangax/fabric.js#3035]
## Version
1.6.2

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
