### ISSUE TITLE
Scrolling Text Object

### ISSUE THREAD

**Issue by Powersurge** [kangax/fabric.js#3037]
Hi, I'm new to Fabric JS and I am trying to make a text object scroll like a ticker when it gets placed on the canvas.  Is this possible and if so, could somebody be so kind as to post sample code or a jsfiddle on how this can be accomplished?  Thank you!

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

**Comment by Powersurge** [comment]
Hi, I couldn't find any info on this in the docs or the StackOverflow forum and this is not a bug, so I guess this would be a new feature.  I am looking for an easy way to customize the look of a ticker from an RSS feed and this library looks like the best fit.  I would want it to work similar to adding a text object, but it would also have properties for scroll direction, speed, & loop.  If something like this can already be accomplished, then could somebody please point me in the right direction?  Thank you!

Date: Thu, 9 Jun 2016 02:43:41 -0700

**Comment by asturur** [comment]
i was just asking to ask this on stackoverflow, not here.
Also specify what is a ticker because if do not know i cannot help.

**Comment by Powersurge** [comment]
Sorry, I appologize. Here's a sample jquery news ticker:
http://www.jqueryscript.net/demo/jQuery-Plugin-For-Horizontal-Text-Scrolling-Simple-Marquee/

Ok, I'll try asking this question on stackoverflow. Thank you!

**Comment by Powersurge** [comment]
I don't think I am going to receive an answer on stackoverflow.  Can we reopen this issue as a feature request?

**Comment by Nosferatu31** [comment]
Since I got to this same issue, I'll leave a snippet here:
https://codesandbox.io/s/fabric-marquee-text-nmps73?file=/src/index.js

**Comment by ShaMan123** [comment]
Thank you @Nosferatu31 
Great job
Related/duplicate #9410 #3050
