### ISSUE TITLE
wide Itext content in mobile device -> moving page

### ISSUE THREAD

**Issue by Rad1calDreamer** [kangax/fabric.js#3038]
## Version
1.6.2

## Test Case
http://jsfiddle.net/Da7SP/107/

open jsfiddle on mobile device and type a lot off text in Itext. If it will be realy a LOT OF, page will moving and show horizontal scrollbar

To fix need remove border and padding on hiddenTextarea

**Comment by asturur** [comment]
its a bug tracked by also by #2986.
Also the position of the hiddentextarea should never go over the canvas width / height.

**Comment by Rad1calDreamer** [comment]
its not mobile only bug.
Fabric.js tests · IText tests in Chrome - same result. I cant understand how absolute position element can did this....
![animation](https://cloud.githubusercontent.com/assets/7055577/15935289/73da1ad0-2e6f-11e6-8805-60d984e4c638.gif)

**Comment by asturur** [comment]
yes as i said we should not move the textarea out of the canvas.
i move the textarea with the typing curosr to help with japanese input.
it is good but needs to be limited limit.

Is the browser behaviour that wants to keep the focus on it.

**Comment by MichaelHindley** [comment]
Just chiming in that , for me, this only occurs in version 1.6.1 and 1.6.2, 1.6.0 is not affected.

**Comment by asturur** [comment]
just to note that #3038 is going to fix this.
It started when i had the idea of moving textbox to support chinese/japanese characters.

**Comment by Rad1calDreamer** [comment]
> It started when i had the idea of moving textbox to support chinese/japanese characters.

may be i can off support chinese/japanese character? i dont need support this languages

**Comment by Rad1calDreamer** [comment]
in 1.6.4 on ipad in textbox  reproduce again

**Comment by asturur** [comment]
so we moved again the textbox position in the document or IE would not work.
textbox should be costrained inside canvas.
i can try your fiddle on my phone, but i do not have ipad

**Comment by asturur** [comment]
cannot reproduce on phone.
Can you share your page setup?

**Comment by Rad1calDreamer** [comment]
check now on emulation in chrome: textarea init with border 1px - so it placed on page.

**Comment by asturur** [comment]
? please be more esplicit on what should i look.
