### ISSUE TITLE
selection styles on I-Text break serialization

### ISSUE THREAD

**Issue by coolfeature** [kangax/fabric.js#3039]
textBackgroundColor set as a selection style seems to break the alignment on deserialised canvas.

## Version
1.6.2

## Test Case
https://jsfiddle.net/coolfeature/y405wsmh/

## Steps to reproduce
uncomment the selection style code and run the fiddle

## Expected Behavior
Canvas is recreated with proper text alignment

## Actual Behavior
Text alignment is left and letters overlap

**Comment by FeaRCODE** [comment]
@coolfeature Simply adding `canvas.renderAll();` after you import your JSON fixes the issue.

```
...
canvas.loadFromJSON(json, finished);
canvas.renderAll();
```

**Comment by coolfeature** [comment]
Not sure how it works but it does.

**Comment by coolfeature** [comment]
closing
