### ISSUE TITLE
clone and cloneAsImage creates objects larger than original (retina related)

### ISSUE THREAD

**Issue by jhiswin** [kangax/fabric.js#3041]
This worked normally in 1.5.0 (unless this is an intended breaking change?).

Both clone() and cloneAsImage() creates a cloned object that is larger than the original.

**Comment by asturur** [comment]
can you make a fiddle that shows it please?

**Comment by jhiswin** [comment]
I'm having a hard time simplifying my code.  On looking deeper, it seems like SVG paths and SVG images in general is misbehaving, even without cloning.
Originally I had been using minX, minY to get positions before/after cloning, and straight cloning SVG preserved the original sizes, but now it seems that cloning complicated SVG objects gets resized and altered and just handled very differently.

**Comment by jhiswin** [comment]
It seems like scaling SVG images before adding to patterns and static canvases also behaves differently.  I can't seem to get SVG images to resize/scale and then be applied as patterns correctly.

**Comment by jhiswin** [comment]
I made a simplified demo showing cloneAsImage misbehaving.  I'm trying to make a demo for clone() misbehaving, but can't get a simplified example yet..
http://jsfiddle.net/5KKQ2/653/

**Comment by jhiswin** [comment]
Update:
I've figured out the problem.  Retina scaling seems to break things for me.
Is there a best practice so that my code will work even after retina scaling (which I do want)?

**Comment by butch2k** [comment]
I ended up deactivating retina support as I encountered issues with todataurl not behaving correctly. Now everything works fine. 


		_____________________________

**Comment by asturur** [comment]
we are improving retina screen support.
meanwhile you can just disable it before calling clone as image and reactivate it again later.

fabric.canvas.enablerRetinaScaling = false; should do the trick.

**Comment by butch2k** [comment]
Yes that's what I resorted to. 






On Fri, Jun 10, 2016 at 12:32 AM +0200, "Andrea Bogazzi" <notifications@github.com> wrote:












we are improving retina screen support.

meanwhile you can just disable it before calling clone as image and reactivate it again later.



fabric.canvas.enablerRetinaScaling = false; should do the trick.

**Comment by jhiswin** [comment]
Just an FYI, StaticCanvas and patterns are also affected.  Reactivating it causes problems, even when scaling is done, so I had to permanently turn off retina on the StaticCanvas being used as a pattern fill.

But, SVG shapes on the main canvas are significantly sharper than before.

**Comment by jhiswin** [comment]
But, SVG shapes on the main canvas are significantly sharper than before (I just have to remember to scaleToHeight(originalHeight) after cloning), which is quite nice. It'd be great if there was a workaround for sub-Canvases and pattern fills.
If anyone knows of a workaround that doesn't require turning off retina scaling, let me know,

**Comment by asturur** [comment]
would you so kind to open a jsfiddle showing patterns problems so i can mark this as a bug?

**Comment by butch2k** [comment]
IIRC: create a rect, copy it as an image position it at the same position as the rect. On standard desktop no issue, both are same position and same size. On a retina the image is half size the rect and not correctly positionned (iirc).
I'm unable to create a fiddle rightnow.

**Comment by jhiswin** [comment]
@butch2k I posted a fiddle for that already.  asturur is talking about another issue related to patterns.
@asturur I'll try to put a fiddle together for you tomorrow.  Basically it is: create a pattern from an SVG, turn off retina, scale it, render the shape and clone an image, etc.  Then, turn retina back on and it will be the wrong size.

**Comment by butch2k** [comment]
@jhiswin Yes i encountered it as well when using a hexagon pattern fill using an svg pattern.

I'm under the feeling that it's related to the way dpr is handled in the __toDataURLWithMultiplier function. on a retina the multiplier is passed to the function being multiplied by the dpr. It's then divided back to it's original value (newZoom) ????

Basically it means you do not retinascale when dataURLing.

`
 __toDataURLWithMultiplier: function(format, quality, cropping, multiplier) {
(...)
        zoom = this.getZoom(),
        newZoom = zoom * multiplier / fabric.devicePixelRatio;
`

**Comment by jhiswin** [comment]
@butch2k Ah that makes sense.  That explains why turning off retina scaling on a StaticCanvas works around the problem.
I thought at first it was because pattern fill requires the original HTMLImageElement, rather than the scaled fabric Object.

**Comment by jhiswin** [comment]
@asturur After further testing: turning off retina during cloneAsImage was enough to resolve the pattern issue (I clone multiple times and had turned it off in the wrong place).

Do you still need a fiddle for patterns?

**Comment by asturur** [comment]
i think that cloneAsImage should be retina disabled unless required by dev with a parameter. Otherwise cloning the same object mutipletime will end in a bigger and bigger object everytime.

**Comment by asturur** [comment]
@butch2k  that newzoom variable is an hack to let the shadow scale properly. when we dataurl we create a new canvas with all the stuff over and i disable the retinaScaling but i enable a zoom that is twice the original. So that
