### ISSUE TITLE
PatternBrush.source on Ipad

### ISSUE THREAD

**Issue by Rad1calDreamer** [kangax/fabric.js#3043]
## Version
1.6.2

When i use PatternBrush with imageHtml as source on ipad - pattern more than img. Like 4k scale.
But if i create fabric.Image from this imageHtml  -> all ok. Its only on ipad. On Windows PC - all ok

**Comment by butch2k** [comment]
It's the same issue as this one: https://github.com/kangax/fabric.js/issues/3041
desactivate retina support in fabric and it will work nicely.

**Comment by jhiswin** [comment]
Interesting that it works okay when you create fabric.Image.  I still have issues even after wrapping in an Image.
Can you post a simplified jsfiddle?  It'll also save me the trouble of creating a simplified test case :p

It seems like the issue may be with using the source element rather than the actual fabric.Image class?

**Comment by Rad1calDreamer** [comment]
i reproduce my code, but cant now check on Ipad
http://jsfiddle.net/u2g3zgxq/10/

**Comment by jhiswin** [comment]
@Rad1calDreamer Just a quick tip for you: in Chrome Dev tools you can emulate a device (used to be Emulate screen), which will let you see how retina would look.

**Comment by Rad1calDreamer** [comment]
ofc i know it. 
I think we need some pattern's settings like "repeat" and "size (aka background size)"

**Comment by asturur** [comment]
i'll take care of this ticket as soon as i can release 1.6.3
I'm spending lot of time on retina screens lately to fix lot of issues.

**Comment by asturur** [comment]
oh you know your demo is super inspiring for fixing: #851

**Comment by Rad1calDreamer** [comment]
can somebody advice me free screencat app on ipad?

**Comment by Rad1calDreamer** [comment]
hi, it's still reproduce
