### ISSUE TITLE
Troubles with StaticCanvas & relativePan

### ISSUE THREAD

**Issue by wsc1992** [kangax/fabric.js#3047]
Hello!

I am currently trying to use your StaticCanvas and the function relativePan to "cut out" areas from a canvas  using the following code:

`
/**
 * To SVG function.
 */
PosterEditor.prototype.toSvg = function() {
	var json = this.toJson(true);

	tmpcanv = new fabric.StaticCanvas('c2');
	
	tmpcanv = tmpcanv.loadFromJSON(json, tmpcanv.renderAll.bind(tmpcanv));

	function checkSvgRendered() {

		var curSvg = tmpcanv.toSVG({
			viewBox : {
				x : 0,
				y : 0,
				width : tmpcanv.getWidth(),
				height : tmpcanv.getHeight()
			}
		});
		
		if (curSvg.length <= 700) {
			console.info("toSvg working");
			window.setTimeout(checkSvgRendered, 2000);
		} else {

			// Cut montage and shift
			tmpcanv.setWidth(editor.canvas.getWidth() - editor.montageWidth * 2 - 1);
			tmpcanv.setHeight(editor.canvas.getHeight() - editor.montageWidth * 2 - 1);

			var delta = new fabric.Point(-editor.montageWidth,-editor.montageWidth - 1);
			tmpcanv.relativePan(delta);
						
			// Remove bleed marker/highlight objects
			tmpcanv
					.forEachObject(function(obj) {
						if (obj.itemCat == 'bleedArea'
								|| obj.itemCat == 'montageArea') {
							obj.remove();
						}
					});
	
			var curSvg = tmpcanv.toSVG({
				viewBox : {
					x : 0,
					y : 0,
					width : tmpcanv.width + editor.montageWidth * 2 + 1,
					height : tmpcanv.height + + editor.montageWidth * 2
				}
			});

			console.info("toSvg finished");

			editor.svg = curSvg;
		}
	}
	checkSvgRendered();

}

/**
 * To JSON function.
 */
PosterEditor.prototype.toJson = function(forSvg) {

	console.log("toJson");

	editor.canvas.renderAll();

	var json = editor.canvas.toJSON([ 'itemCat', 'customStyles', 'mediaId' ]);

	// Remove objects we dont want to save since they are just controls
	var filteredJson = {
		objects : []
	};

	filteredJson.objects = $.grep(json.objects,
			function(obj, index) {

				if (forSvg) {
					if (obj.itemCat == 'addBlockBtn'
							|| obj.itemCat == 'styleBtn'
							|| obj.itemCat == 'actionBtn'
							|| obj.itemCat == 'highlight'
							|| obj.itemCat == 'indicatorBtn'
							|| obj.itemCat == 'togglerBtn'
							|| obj.itemCat == 'gridLine') {
						return false;
					} else {
						return true;
					}
				} else {
					if (obj.itemCat == 'paintAreaBorder'
							|| obj.itemCat == 'addBlockBtn'
							|| obj.itemCat == 'styleBtn'
							|| obj.itemCat == 'actionBtn'
							|| obj.itemCat == 'highlight'
							|| obj.itemCat == 'indicatorBtn'
							|| obj.itemCat == 'customBorder'
							|| obj.itemCat == 'togglerBtn'
							|| obj.itemCat == 'gridLine') {
						return false;
					} else {
						return true;
					}
				}

			});

	return filteredJson;
}`.

To put it simple, the following lines should copy the currently (visible canvas) into a hidden StaticCanvas which will be manipulated using .relativePan:

`var json = this.toJson(true);
tmpcanv = new fabric.StaticCanvas('c2');
tmpcanv = tmpcanv.loadFromJSON(json, tmpcanv.renderAll.bind(tmpcanv));
.....
var delta = new fabric.Point(-editor.montageWidth,-editor.montageWidth - 1);
tmpcanv.relativePan(delta);
`
When I call tmpcanv.toSVG I get a svg graphic, but in this graphic the pan is simply NOT applied, why ?! In an older version of fabricjs this was still working - the pan was applied!

I am very thankful for any tips what I did wrong or what the problem could be.

**Comment by asturur** [comment]
the relative pan it is applied with the viewbox. If you overwrite the viewbox with one you supply then you override the pan.
