### ISSUE TITLE
New Group misplaced borders when zoomed

### ISSUE THREAD

**Issue by mistic100** [kangax/fabric.js#3049]
## Description

I want to programatically select a bunch of objects, so I instanciate a new `Group`  and call `canvas.setActiveGroup`. It works well, unless there is a global zoom applied to the canvas : the borders and controls have an offset, and the group "jumps" when you resize it.
## Version

1.6.2
## Test Case

https://jsfiddle.net/egg67ssy/
Comment line 5 to see the correct behaviour when there is no zoom.
## Steps to reproduce

Move and resize the group.
## Expected Behavior

The borders and controls should stay aligned with the group + when resizing the group it should behaves correctly.
## Actual Behavior

The borders and controls have an increasing offset as you move the group + if you moved the group it behaves strangely when resized.

**Comment by asturur** [comment]
i think is the creation of activegroup programmatically that creates the problem. I will check

**Comment by asturur** [comment]
https://jsfiddle.net/egg67ssy/4/

**Comment by ssalawria** [comment]
I also facing the same issue please check https://jsfiddle.net/09dyeL4v/1/ is there any solution for this?

**Comment by asturur** [comment]
this has been fixed in current master.
Please when creating activeGroup, pass canvas in the options. activeGroup is not on canvas but has canvas property set good.

**Comment by ssalawria** [comment]
Could you please give some example?

**Comment by ssalawria** [comment]
textbox object is not working in the latest version(1.7.0)

**Comment by asturur** [comment]
textobject has been fixed. But you have to download library and build it.
