### ISSUE TITLE
SVG render bug

### ISSUE THREAD

**Issue by mbriggs** [kangax/fabric.js#3051]
First of all, thank you guys for building/maintaining this awesome library. Really love that this project exists :) 

I have a weird issue with an SVG I got from a designer (believe it was made in illustrator). There are some areas filled black that should be transparent.

## Version
1.6.2

## Test Case
http://jsfiddle.net/f8yepcsg/2/

## Steps to reproduce
 - load the provided svg (http://matt.dev.s3.amazonaws.com/dieline.svg) via `fabric.loadSVGFromURL`
 - make a `PathGroup` with `fabric.util.groupSVGElements`
 - add group to `Canvas`

## Expected Behavior
![image](https://cloud.githubusercontent.com/assets/89260/16103922/af2a4fda-334a-11e6-8c47-50b852e9102c.png)

## Actual Behavior
(the outer outline is just the canvas from the jsfiddle test case)
![image](https://cloud.githubusercontent.com/assets/89260/16103913/a32f293a-334a-11e6-95c7-d457d5a0abe1.png)

**Comment by asturur** [comment]
svg is not accessible.

**Comment by mbriggs** [comment]
derp, sorry about that. made it public

**Comment by mbriggs** [comment]
uploading it here for posterity [dieline.svg.zip](https://github.com/kangax/fabric.js/files/318493/dieline.svg.zip)

**Comment by asturur** [comment]
it has to be a problem with styling. i have to check if multiple classes declaration are supported. Is this the only svg giving you problem? do you have any other similar that is working fine?

**Comment by mbriggs** [comment]
this was sort of a test svg given to me by my designer, he is going to work on others today. Ill mention the multiple class thing and see if he knows what im talkiing about, but pretty sure he is just using illustrator and exporting as svg

**Comment by mbriggs** [comment]
ok, here are another few from the designer. Both have similar issues
[svg.zip](https://github.com/kangax/fabric.js/files/334031/svg.zip)

**Comment by asturur** [comment]
![image](https://cloud.githubusercontent.com/assets/1194048/16513746/59223638-3f67-11e6-8797-2079422db403.png)


can you show me how it should look like?

**Comment by asturur** [comment]
dumb question i opened svg.
