### ISSUE TITLE
Objects are incorrectly transparent when perPixelTargetFind is true

### ISSUE THREAD

**Issue by dhakan** [kangax/fabric.js#3054]
I've been having issues trying to utilize the `perPixelTargetFind ` property on `fabric.Object` in order to be able to select and drag an object with respect to its content and not its bounding box. The issue is that the objects that were selectable and draggable before this property was included are not selectable anymore. I've been trying this on `fabric.Circle`, `fabric.Line` and `fabric.Text.` It seems that the checks for this property tries to determine whether or not the object is transparent, which is never true in the case of the objects I'm using. 

From source:

```
if ((this.perPixelTargetFind || obj.perPixelTargetFind) && !obj.isEditing) {
          var isTransparent = this.isTargetTransparent(obj, pointer.x, pointer.y);
          if (!isTransparent) {
            return true;
          }
        }
```

I've compared to the working example of http://fabricjs.com/per-pixel-drag-drop and cannot find any noticable differences except for the fact that these shapes are images loaded by url. 

Version of fabric: 1.6.0-rc.1, have also tried with 1.6.2.

**Comment by asturur** [comment]
Are you on retina screen?

**Comment by butch2k** [comment]
There seems to be several issues with isTargetTransparent.
Indeed while making some masking test (i build a mask from a group cloned as image with transparency and global-compo to make a kind of clipto) i discovered that testing isTargetTransparent for coordinates beyond the viewport always return true even if the object being tested extend beyond this boundary and is not transparent at the point being tested.

**Comment by asturur** [comment]
today i m fixing bugs here and there. yes testing outside canvas always return false. trying to get a look at this also. can you share some code to create the objects you are testing with?

**Comment by butch2k** [comment]
Not easily unfortunately as i have layers implemented and a ton of stuff around.

Basically what i do: 
- i draw a grid usins a pattern over a BG image
- when editing fog of war i can add shapes like rect or circles etc and change status of each rect of the grid from being visible to masked, here is an example of a shape:
![2q](https://cloud.githubusercontent.com/assets/961507/16178521/fb5bfb80-364a-11e6-9a73-30cc2c3582db.jpg)
The white thingy is the visible area.

When in player mode the view is such as this one:
![2q](https://cloud.githubusercontent.com/assets/961507/16178552/dd1ece94-364b-11e6-879d-07614e93acbb.jpg)

How is this made:
- objects (the white rects) are grouped along with a transparent rect covering all the BG then this group is converted to an image through cloneasimage.
W/o the proper globalcompositeoperation it would look like this:
![z](https://cloud.githubusercontent.com/assets/961507/16178561/4fa09e16-364c-11e6-93a7-c2409ef46aea.jpg)

With 'destination-atop' it looks like the player view.

**Comment by asturur** [comment]
sorry @dhakan  i need to understand better, in order to close it or fix it.
The transparency check is made on a temp canvas where we draw just the object of the findTarget.
What are you checking the transparency of? it may be tricky with multiple layers.

I love this game, is available somewhere?

**Comment by asturur** [comment]
@dhakan  i made a couple of changes to transparency check, could you give it a look? thanks.

**Comment by asturur** [comment]
i iwll reopen if you let me know that transparency is still broken
