### ISSUE TITLE
Unable to select foreground object if object behind is selected

### ISSUE THREAD

**Issue by ozooner** [kangax/fabric.js#3055]
So, with the latest build there seems to be a bug where if two objects overlap each other, it is not possible to select the 'front' object if the object in the 'back' is active. Following fiddle is using latest fabric build of 17.06.2016:
[https://jsfiddle.net/ozooner/sfa1jk31/3/](https://jsfiddle.net/ozooner/sfa1jk31/3/)
Steps to reproduce:
1)Select red rectangle
2)Try selecting the green circle
I have traced the bug to following commit that broke the behaviour:
[https://github.com/kangax/fabric.js/commit/0c6a665bcbb26de1dc253dce631c0ea1dd104ae1](https://github.com/kangax/fabric.js/commit/0c6a665bcbb26de1dc253dce631c0ea1dd104ae1)
(Using retina screen if it matters)

**Comment by asturur** [comment]
known issue :( will be fixed soon.
I like the idea of retrieving the last selected object. i did not understand that it would break selections in that way. I'm thinking to put this feature under keycombo. Enabled by default if you are working with "preserveObjectStacking = false" or available with Ctrl + click OR alt + click or whatever we can have.
