### ISSUE TITLE
Group center positioning potential bug

### ISSUE THREAD

**Issue by bgaillard** [kangax/fabric.js#3056]
I, here is a Fiddle which shows that 2 triangles using `center` origin are not both centered in their group.

https://jsfiddle.net/bgaillard/t8agoms5

I need this to emulate inner borders in our project (the values of the second triangle are calculated to have a border of `10px` between the 2 triangles).

So why the triangles are not both centered in the group ? 

Also i'm not 100% sure but if the triangles have a height which is lower than the width the bug does not appear, strange.

Thanks

**Comment by butch2k** [comment]
It is mathematically centered !
distance between top yellow and top black is equal to distance from bottom black to bottom yellow.

**Comment by butch2k** [comment]
You need to use the triangles' incenter not the centroids.
https://en.wikipedia.org/wiki/Incenter

**Comment by bgaillard** [comment]
Hi @butch2k and thanks for your quick response, you're absolutly right ! 

So now I have to find a way to shift the yellow triangle of the right distance so that its inner center is at the same position as the black triangle inner center position.

Thanks again, i'll try to compute this and it should work ! 

So I close the issue because its not a bug.

**Comment by butch2k** [comment]
Found this on Stackoverflow, it might be of help:
http://stackoverflow.com/questions/36554898/algorithm-for-putting-double-border-around-isosceles-triangle/36555443
