### ISSUE TITLE
FreeDraw: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Rad1calDreamer** [kangax/fabric.js#3059]
dowload https://github.com/kangax/fabric.js/pull/3057 this master state. 
When isDrawingMode true, sometimes have erros from handlers in console
![21 06 2016 10-08](https://cloud.githubusercontent.com/assets/7055577/16220860/1f045020-3798-11e6-88d7-bbe2f657eb72.png)

`    
    _handleEvent: function(e, eventType, targetObj) {
      var target = typeof targetObj === undefined ? this.findTarget(e) : targetObj,
          targets = this.targets,
          options = { e: e, target: target, subTargets: targets };

      this.fire('mouse:' + eventType, options);
      target && target.fire('mouse' + eventType, options);
      for (var i = 0; i < targets.length; i++) {
        targets[i].fire('mouse' + eventType, options);
      }
    },
`

**Comment by asturur** [comment]
my bad. i think that onMouseMove in drawing mode does not run a findTarget, so it can't run the subtargets check. i ll fix it later.
