### ISSUE TITLE
text selection in RTL leng is incorrect 

### ISSUE THREAD

**Issue by Yosi-Azulay** [kangax/fabric.js#3061]
hi 

We uses fabric to ruder text and we have text in Hebrew.
the rendering of the text is OK but when we select a text we get the copy (ctrl + C) wrong and the word selection is wrong.

ex: IText.text = "ניסיון לכתוב בעיברית"
Ctrl+C on the first word on the right (RTL) will copy the first word on the left.

we will be glad for a fix or sum giddiness and we will fix it.

tnx

**Comment by asturur** [comment]
duplicate of #2374

**Comment by YaakovHatam** [comment]
@Yosi-Azulay  please look at the issue #2374 i am developing a RTL version please test it
