### ISSUE TITLE
targetFindTolerance -- does not work at horizontal or vertical lines / edges

### ISSUE THREAD

**Issue by awehring** [kangax/fabric.js#3062]
The _canvas.targetFindTolerance_ has no influence on horizontal or vertical lines or edges. At diagonals it works as expected.

Therefore it is quite difficult to select horizontal or vertical lines if they are narrow.

## Version
1.6.2

## Test Case
http://jsfiddle.net/Da7SP/122/

## Steps to reproduce

- Execute the jsfiddle
- Move the cursor close to the diagonal edge of the triangle --> it becomes selectable a bit outside, as it should.
- Move the cursor close to the bottom, horizontal edge of the triangle --> it becomes selectable just at the edge.
- Try the same with the horizontal and diagonal lines --> it is quite difficult to select the horizontal line.

## Expected Behavior
When _canvas.targetFindTolerance_ is set to some positive number, a line should be easily selectable, regardless if it is horizontal or diagonal.
The same should happen at horizontal / diagnal edges of objects.

## Actual Behavior
It works as expected only with diagonal lines / edges.

**Comment by asturur** [comment]
Transparency check does not work on overy mouse move. You have to hover a target in its bounding box and it will perform transparency check.
The horizontal line has a small bounding box.
I suggest you to include a little bit of padding in on controls to help you selecting horizontal lines.
