### ISSUE TITLE
findTarget not work whit a selected objects (activegroup)

### ISSUE THREAD

**Issue by blucobalto** [kangax/fabric.js#3063]
## Version
1.6.2

## Test Case
http://jsfiddle.net/blucobalto/Da7SP/124/

## Steps to reproduce

- Set <pre><code>canvas.perPixelTargetFind = true;</code></pre>

- Create 2 object like this:
<pre><code>var circle = new fabric.Circle({
  radius: 20, fill: 'green', left: 100, top: 100
});
var triangle = new fabric.Triangle({
  width: 20, height: 30, fill: 'blue', left: 50, top: 50
});
canvas.add(circle, triangle);</code></pre>

- Select all objects

## Expected Behavior
I expect that the selection (activegroup)  works

## Actual Behavior
The selection (activegorup) not works.

## The problem
Hi,
I think there is a problem in the "findTarget" function.

If there is an active group  the var "pointer" is undefined.
This is because pointer is declared after the call of function "_checkTarget".
Look current code:
<pre><code>
        // first check current group (if one exists)
        // avtive group does not check sub targets like normal groups.
        // if active group just exits.
      var activeGroup = this.getActiveGroup();
      if (activeGroup && !skipGroup && this._checkTarget(pointer, activeGroup)) {
        return activeGroup;
      }

      var pointer = this.getPointer(e, true),
          objects = this._objects;
      this.targets = [ ];
</code></pre>

Modified code (work):
<pre><code>
        var pointer = this.getPointer(e, true);

        // first check current group (if one exists)
        // avtive group does not check sub targets like normal groups.
        // if active group just exits.
        var activeGroup = this.getActiveGroup();
        if (activeGroup && !skipGroup && this._checkTarget(pointer, activeGroup)) {
            return activeGroup;
        }

        var objects = this._objects;
        this.targets = [];
</code></pre>
Thanks a lot,
Blu

**Comment by asturur** [comment]
Thanks! for sure i messed it up. Do you want to submit a PR to fix it?

**Comment by blucobalto** [comment]
Ok. Done.
Thanks a lot,
Blu
