### ISSUE TITLE
Textbox border on lineheight < 1

### ISSUE THREAD

**Issue by websuvius** [kangax/fabric.js#3066]
## Version
1.6.2

## Test Case
http://jsfiddle.net/Da7SP/131/

## Steps to reproduce
Add a textbox with a lineHeight < 1 and select it to edit.

## Expected Behavior
Borders should wrap all the rows.

## Actual Behavior
Borders doesn't wrap all the rows.

**Comment by asturur** [comment]
this has to be checked.
