### ISSUE TITLE
i-text group selection bug.

### ISSUE THREAD

**Issue by FeaRCODE** [kangax/fabric.js#3068]
## Version
1.6.2 (most recent build)

## Test Case
http://jsfiddle.net/w735nLk1/1/

## Steps to reproduce
Select any of the iText objects and scale it. After scaling group select (by click dragging mouse). When the selection is made, the scaled iText will revert to the old scaling or something similar?

## Expected Behavior
Normal group selection without scaling being changed.

## Actual Behavior
the scaled iText will revert to the old scaling or something similar.

**Comment by asturur** [comment]
absolutely not normal.

**Comment by FeaRCODE** [comment]
Not sure how I found this one, but I think it's an easy one to fix. (Hopefully)

**Comment by asturur** [comment]
is completely broken. completely

**Comment by FeaRCODE** [comment]
Well I spoke too soon. At least we found it somewhat early.

**Comment by asturur** [comment]
I rebuilt the library and the bug looks disappeared. Could you check that is really so and in case close the issue?

**Comment by FeaRCODE** [comment]
Sure I will do it sometime today. So was it literally a compilation issue? That's pretty odd.

**Comment by FeaRCODE** [comment]
I closed the issue but I am still confused on how recompilation fixed the issue.

**Comment by asturur** [comment]
https://github.com/kangax/fabric.js/pull/3078/files#diff-3fc6312401a476d0cca802b695bad03dR13419

maybe this was the problem.
