### ISSUE TITLE
Add to Group Bug

### ISSUE THREAD

**Issue by darkfrog26** [kangax/fabric.js#3070]
## Version
1.6.2

## Test Case
https://jsfiddle.net/9a4spksL/6/

## Steps to reproduce
Simply try adding an item to a group after it has been added to the canvas.

## Expected Behavior
Adding an Object to a Group should re-render the Group showing the new element in the proper position.

## Actual Behavior
The Object doesn't appear until you interact (causing a re-render) and even then the positioning seems to be offset from the last added Object in the group instead of relative to the Group's left and top.

This makes Fabric.js incredibly buggy to try to use with Groups when dynamically adding and removing Objects on-the-fly.

**Comment by darkfrog26** [comment]
Okay, I figured out if I use `addWithUpdate` and then call `renderAll` then it seems to display properly.  Shouldn't adding an entry cause a re-render anyway?

**Comment by asturur** [comment]
no i think not.
I'm really willing to remove automatic renderAll from a lot of places. it always end up that people uses high level function with renderAll in for loops and re render lot of times when is not necessary. It is ok to renrender automatically when using the mouse, but not for a code approach.
At least that is my opinion.

Don't if @kangax has different idea

**Comment by butch2k** [comment]
Agreed, i prefer to have control over the rendering. As i'm not certain of when it happens currently i tend to add renderonaddremove conditions whenever i'm adding or removing lot of objects from screen.
On this regard my only wish is consistency. One should not have to look at the code to know if the rendering is automatic or not.

**Comment by asturur** [comment]
it should be not. this is a library to help you use canvas, not a editor without buttons.
So i'm ok with rendering on mouse actions ( because othewise you have to hook events to render ) but not to setCenter, setZoom, and all this stuff.

**Comment by butch2k** [comment]
Exactly. Mouse stuff should be automatic but otherwise it should be the responsibility of the coder to decide when it should render.
