### ISSUE TITLE
Event Support in Object is not Documented

### ISSUE THREAD

**Issue by darkfrog26** [kangax/fabric.js#3072]
If you go to the documentation here: http://fabricjs.com/docs/fabric.Object.html there is no documentation defining the event handling methods for Object. They are explained on StaticCanvas, but seem to be excluded from the Object documentation.

**Comment by butch2k** [comment]
Yes because handlers are at the canvas level not at the object level. Objects fire events, canvas handles them.

**Comment by asturur** [comment]
we just say this:

```
fires
event:added
event:removed
event:selected
event:modified
event:rotating
event:scaling
event:moving
event:skewing
event:mousedown
event:mouseup
event:mouseover
event:mouseout
```

then you know that going  object.on('moving', function() {}); will work
