### ISSUE TITLE
[Feature Request] Lock Movement in one Direction

### ISSUE THREAD

**Issue by thingNumber1** [kangax/fabric.js#3079]
It would be nice if you could lock the movement in only one direction. There are 2 post in Google Group ([1](https://groups.google.com/forum/#!topic/fabricjs/23-M-o0av4c), [2](https://groups.google.com/forum/#!topic/fabricjs/ySDsbAuFrVM)) of people asking for something that would be possible with this feature.

An example of use where this may be required are games: If I want the player to be allowed to move an object only to the left, then I would lock movement on Y and Right; or if I have a draggable object and I want it not to get out of the screen, I would need to block the movement to Up if its position in Y is iqual to `0`, to lock only the movement to left if the position in X is iqual to `0` and so on, always with the open possiblity to move it to the opposite side.

The only thing I think one needs to be aware is that `lockMovementRight` and `lockMovementLeft` work well in combination with `lockMovementX`; in a similiar way  `lockMovementUp` and `lockMovementDown` would work well in combination with `lockMovementY` (but I guess shouldn't be so hard).

Looking foward for an answer. =)

**Comment by asturur** [comment]
too many flags and features, cannot add also those.
Too much application specific also.
Sorry that took so long for getting an answer.
