### ISSUE TITLE
Rendering of the canvas after removing an object with object.remove() is not immediatly invoked

### ISSUE THREAD

**Issue by MDSLKTR** [kangax/fabric.js#3083]
Hello,

## Version

1.6.3

## Test Case
http://pixolith.github.io/fabricjs-customise-controls-extension/example/index.html

## Steps to reproduce

* Select a canvas element
* Click the Trash icon which invokes remove() on the object

## Expected Behavior
Object is removed and the canvas is immediatly re-rendered.

## Actual Behavior
Objects is removed and the canvas is **not** immediatly re-rendered but instead updated on the next select/deselect event.

## Long Text
after updating to fabric 1.6.3 invoking remove() on a fabric object will not immediatly re-render the canvas.

You can see it here:
http://pixolith.github.io/fabricjs-customise-controls-extension/example/index.html

It also happens with bringForward() and SendBackwards() methods. The Canvas will only be re-drawn once a select or deselect event is fired. My Canvas does not have manual add/remove Rendering enabled, so there is no reason why it shouldn't immediatly update. My guess is when looking at the lines concerning remove() in the the core, is that renderAll is not properly invoked on the correct canvas object.

Regards,
Simon

**Comment by asturur** [comment]
i think is a problem with the extensions.
on kitchensink doing canvas.getActiveObject().remove() remove the object immediately.

**Comment by MDSLKTR** [comment]
Thanks yes, i can see it working in the kitchensink, i shall investigate further.

**Comment by MDSLKTR** [comment]
@asturur It seems like invoking remove() via a corner event doesn't clear or readds the activeObject() back to the canvas object which ,since the renderAll() method has been changed to test for the activeObject(), will still render it event though it is removed. Testing renderAll() in fabric 1.6.3 vs 1.6.2 will resolve this issue.

**Comment by MDSLKTR** [comment]
this now fixed on my end.

**Comment by InsomniumBR** [comment]
Same problem.
I used a SetTimeout with 10 ms... just to get out of the event... and it works..
Not beautiful at all, but it works..
