### ISSUE TITLE
IText editing cursor not shown when rotation viewportTransform is applied to canvas

### ISSUE THREAD

**Issue by anton-kapelyushok** [kangax/fabric.js#3084]
## Version
1.6.3
## Test Case
1.6.1 http://jsfiddle.net/oq8dctp8/ - works properly 
1.6.3 http://jsfiddle.net/nkm4uoon/ - does not work
## Steps to reproduce
1. Set canvas viewportTransform to [0, 1, -1, 0, 300, 0]
1. Add IText element to canvas
1. Try to edit text

## Expected Behavior
Editing cursor is shown
## Actual Behavior
No editing cursor

**Comment by asturur** [comment]
you cannot set viewportTransform like this. rotation of canvas is not supported in this way.
please verify that with a viewport that has element 0 and 3 made of positive numbers, everything works correctly.

**Comment by anton-kapelyushok** [comment]
What is the proper way to rotate canvas then?

**Comment by anton-kapelyushok** [comment]
Well, redefining `canvas.getZoom()`  function like the following fixes the issue: 
```
    canvas.getZoom = function() { 
    return Math.sqrt(this.viewportTransform[0] * this.viewportTransform[0] 
                   + this.viewportTransform[1] * this.viewportTransform[1]);
    };
```
Basically, it calculates scaling on X coordinate.
Here is the working example with different rotation angles: [http://jsfiddle.net/pzeb7dhk/](url)

But I still don't understand how to rotate canvas properly. There is no rotate method in fabric canvas, so changing viewport is the only solution I came up with. I also tried to rotate it using CSS, but when I add `transform: rotation(90deg)` property to canvas, it breaks mouse events.

**Comment by asturur** [comment]
you cannot rotate full canvas, just single objects.
no support for canvas rotation yet

**Comment by anton-kapelyushok** [comment]
By the way, what calculates standart `getZoom` method? If we do not call `setViewportTransform `explicitly, `viewportTransform[0]` and `viewportTransform[3]` both equal to current zoom, since the only method changing `viewportTransform `is `zoomToPoint`, which assigns both the same value.
And when we call the `setViewportTransform`, this implementation just does not work properly.

**Comment by asturur** [comment]
exactly, setViewportTransform can t be used freely
