### ISSUE TITLE
Suggestions for working around the lack of multiple overlay image support

### ISSUE THREAD

**Issue by mbriggs** [kangax/fabric.js#3085]
I have several "foreground layers" and several "editable" layers. Is there any way to either "pin" a layer position to take it out of the auto bringToFront behavior, or just to disable the behavior all together for an object?

EDIT: I think what i am actually asking for is a workaround for lack of support for multiple overlay layers

## Version
1.6.2

## Test Case
http://jsfiddle.net/5j838ahe/1/

## Steps to reproduce

 - drag blue half over red
 - select red

## Expected Behavior

would like some way to keep red under blue

## Actual Behavior

blue jumps over red

**Comment by Envo** [comment]
It also happens with 1.6.3

**Comment by mbriggs** [comment]
after some more api exploration, everything is working as intended. This ticket is more asking if anyone has any suggestions for working around the lack of support for multiple overlay objects

**Comment by asturur** [comment]
canvas.preserveObjectStacking = true

if it does not work there is a bug.

**Comment by awehring** [comment]
_canvas.preserveObjectStacking = true_ works in the jsFiddle as expected.

@mbriggs: For an application with several layers, the best way is to use a layer scheme like Photoshop or Illustrator does. fabric.js does not support it yet, but there are some suggestions to work around. 
Take a look at #3000

**Comment by mbriggs** [comment]
Awesome, thanks guys :D 🍺

**Comment by monis01** [comment]
Hi
Is there any update for multiple overlay image ?
Thanks

**Comment by asturur** [comment]
Make a group and set the group as an overlay. That is the way to do it as of now, won't change easily.

**Comment by monis01** [comment]
Thanks @asturur 
it worked
