### ISSUE TITLE
how to convert object to klass?

### ISSUE THREAD

**Issue by msi008** [kangax/fabric.js#3086]
hi @kangax @garg @davidjrice @maxim @miracle2k 

I have a problem，When I look for an object，klass and The difference between Klass and object，
Index is always -1
<pre><code> var objects = this.getObjects();
 index = objects.indexOf(arguments[i]);
</code></pre>
How to solve the problem, or there is a better API for Canvas contains elements

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
