### ISSUE TITLE
Group Selection is not working under some situation.

### ISSUE THREAD

**Issue by wpyip7** [kangax/fabric.js#3087]
I currently using fabric to do something. Now , when I updated to fabric 1.6.2 . I found that group selection is not working under the following situation.

First, I put a big rectangle at first (with selection =  false.) , then put some small rectangles on top of the big rectangle . Dont know the reason why sometime group selection by mouse drag does not work.

Here is the problem demo.
https://jsfiddle.net/wpyip7/j8zkybuo/1/

**Comment by asturur** [comment]
if you mean selectable false, yes it stops selection by drag. is a known issue. use evented false to overcome it.
