### ISSUE TITLE
Poor performance on mobile devices

### ISSUE THREAD

**Issue by matanasa66** [kangax/fabric.js#3089]
## Version
1.6.2

## Test Case
http://jsfiddle.net/Da7SP/146/

## Expected Behavior
High performance on mobile devices

## Actual Behavior
Canvas' performance is very poor while dragging, resizing, or doing any gesture on mobile devices.

**Comment by butch2k** [comment]
You need to be more specific on the issues you encounter: device, OS, version...
Indeed I manipulate very complex canvases on multiple mobile devices w/o performance issues.

**Comment by matanasa66** [comment]
Samsung Galaxy S4, Android 5.0.1 tested in Chrome 51.0.2704.81
The issue is that the objects that I drag are being dragged very slowly and laggy.
everything is a bit delayed.

**Comment by butch2k** [comment]
It happens on the fiddle you posted or on a more complex code ?

**Comment by matanasa66** [comment]
In the fiddle I posted, even in the most simple use of fabric I've experienced poor performance.
In addition, I've checked in Firefox 47.0 on the same phone, works a little better.
And, checked on Nexus 6P with the latest 7.0.2 android and it works flawlessly.
It's making me feel like my phone's the problem, let me know what you think.

**Comment by butch2k** [comment]
That's my take as well. I used fabric on a lot of mobile devices w/o much trouble. Such a simple test case should work flawlessly on any device. I'll check tonite on a low end device.

**Comment by matanasa66** [comment]
Thank you very much!

**Comment by butch2k** [comment]
Tested on low end androïd devices, i encountered no performance issue. It definitely looks like a problem with your S4.

**Comment by whatisor** [comment]
I prefer to modify homepage to make it run smoothly in mobile.
http://fabricjs.com/
it is very low performance on mobile. ( Moto G8 Power)
