### ISSUE TITLE
1.6.3 broke mouse selection totally.

### ISSUE THREAD

**Issue by virror** [kangax/fabric.js#3090]
I updated our project from 1.6.0 to 1.6.3 and mouse clicks stopped working so i cant select objects anymore. Multi select still works using mouse drag but not single select. Downgraded to 1.6.2 and everything seems to work as expected again.

**Comment by asturur** [comment]
1.6.3 is on website, i do not see anything like that. can you be more specific on what is not working?

**Comment by virror** [comment]
Yeah, sorry, i was a bit quick on filing a report : /
Looking into it now.

**Comment by virror** [comment]
Sorry, stupid mistake from my part...
