### ISSUE TITLE
When a field is in the same spot as a widget for a selected field, that widget can not be used.

### ISSUE THREAD

**Issue by virror** [kangax/fabric.js#3091]
## Version
1.6.3

## Test Case
http://jsfiddle.net/z1vgcg5h/

## Steps to reproduce
Try to rotate the selected object

## Expected Behavior
You should be able to rotate the selected object regardless of any other object behind it.

## Actual Behavior
You select and move the other object instead.

**Comment by butch2k** [comment]
confirmed, targeting the handlers should not pass the events to the
underlying object.

**Comment by asturur** [comment]
i close this and i discuss that in #3095. please follow there.
