### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not an object throws at /resource/1467967858000/ChartJS/Chart.js-2.1.6/dist/Chart.bundle.min.js:7:30077

### ISSUE THREAD

**Issue by pinga24** [kangax/fabric.js#3092]
I am using chartjs version 2.1.6. I have created lightening dashboard component using Chart JS. 
For that i have used Chart.bundle.min.js on my page but whenever any data is changed on back end and i try to refresh my page i am getting following error : 

Uncaught TypeError: Right-hand side of 'instanceof' is not an object throws at /resource/1467967858000/ChartJS/Chart.js-2.1.6/dist/Chart.bundle.min.js:7:30077.

This does not happen each time.

**Comment by asturur** [comment]
Please refer to chartjs issue tracker
