### ISSUE TITLE
Unselect object in group with shiftKey and zoomToPoint

### ISSUE THREAD

**Issue by berezmax** [kangax/fabric.js#3096]
https://jsfiddle.net/xof2p2qw/  - if ZOOM = 1 - work unselect with shiftKey, if ZOOM < 1 - not work.

**Comment by asturur** [comment]
i does not work in 1.5.0 onward.
It has to do with the fact that we calculate ocoords with vpt effect, and that we do not recalculate them when we change zoom if inner group.
And vpt gets applied multiple times.
