### ISSUE TITLE
Multi selection condition on the canvas

### ISSUE THREAD

**Issue by mbaudry** [kangax/fabric.js#3102]
Hello,

I have a request for you, about object selection in the canvas. When I apply a group selection, I would like to apply the selection on the element only if it's entirely in the selection rectangle, not when it's only a part of it. I saw in the code the function `_collectObject` which permits to select the objects. I solved my request when I removed the two conditions `intersectsWithRect` and `containsPoint`. Is there a solution to solve my problem without modify the source code or a possible feature to do that ?

Thanks you for your help.

**Comment by asturur** [comment]
we ll se if is a super super super super easy flag we can also implement.
But do not get too much hope

**Comment by asturur** [comment]
long time later someone did it.
@mbaudry if you are still interested, this has been done.
