### ISSUE TITLE
Problem with custom class and loadFromJSON

### ISSUE THREAD

**Issue by godzie44** [kangax/fabric.js#3104]
# Version

1.6.3
# Test Case

http://jsfiddle.net/a83g2qx4/2/
# Steps to reproduce

Try to save and load custom class objects. Inside constructor must be create another object in object:added event, but it fail when use loadFromJSON method.

# Temporary solution
in fabric.util.enlivenObjects change `_this.insertAt(obj, index, true);` to `_this.insertAt(obj, index, false);`

**Comment by asturur** [comment]
Yes i think you are right. splice is safer most of the time.
