### ISSUE TITLE
Cannot move active group when perPixelTargetFind is true

### ISSUE THREAD

**Issue by AdamMerrifield** [kangax/fabric.js#3107]
## Version
1.6.2

## Test Case
http://codepen.io/merrifield69/full/VjyXxx/

## Steps to reproduce
Set `perPixelTargetFind: true` on the `fabric.Canvas`
Create an active group of 2 or more objects.
Hover your mouse over the active group (notice the cursor).
Try to move the active group.

## Expected Behavior
The group should actually move when trying to move it.

## Actual Behavior
Does not move the group, just starts a new selection.

## Possible Solution
I believe this is occurring because the transform on the group is being run twice. 

During `canvas.findTarget` [we send `canvas._checkTarget` the `activeGroup`](https://github.com/kangax/fabric.js/blob/master/src/canvas.class.js#L967) 

After which `canvas._checkTarget` [sends the `activeGroup` to `canvas.isTargetTransparent`](https://github.com/kangax/fabric.js/blob/master/src/canvas.class.js#L1014)

Inside of `canvas.isTargetTransparent` we set the transform and then `render` the object, but `render` of a group sets the transform itself as well.

I believe that we would need to add [the second `noTransform` parameter to the group's `render` method](https://github.com/kangax/fabric.js/blob/master/src/shapes/group.class.js#L266)

If this is the correct assumption I should be able to submit a pull request for this problem. Just want to make sure I'm not overlooking something.

**Comment by asturur** [comment]
![image](https://cloud.githubusercontent.com/assets/1194048/16895022/b187cdc6-4b68-11e6-863a-2ff91c5701bf.png)

this is the situation of transparency check with an activeGroup. i fixed short time ago. we definitely need more visual tests of various kind.
