### ISSUE TITLE
What are key differences with Two.js?

### ISSUE THREAD

**Issue by 0x80** [kangax/fabric.js#3110]
I am having a hard time choosing between Fabric.js and Two.js. I would appreciate it if someone could list a few key differences besides the WebGL output.

**Comment by asturur** [comment]
Looks like that two.js is an animation library with no interactivity support ( at object level ) but i may be wrong. 
It depends on what project are you starting.

**Comment by 0x80** [comment]
Thanks. I think you're right. It's mainly the lack of interactivity that sets them apart. I'm mainly interested in the drawing api though.

I've since learned that webgl is not really an option for the kind of graphics I'd like to do. If you scale a circle with a fixed strokewidth for example the geometry texture is recomputed and transferred to the gpu on every frame making it incredibly inefficient.

Thing that are missing from Two.js for me at the moment are the ability to fill with patterns and the use of dasharray on stroke.
