### ISSUE TITLE
Itext getSelectedText does not return the selected text

### ISSUE THREAD

**Issue by zedryas** [kangax/fabric.js#3113]
Hello,

I'm using version 1.6.3
It seems IText has issue with retriving selections:
getSelectedText() does not return the selected text. It often has an offset of one character either on the right or on the left
I've looked at the object and found that the value of selectionStart and selectionEnd do not have consitent behaviour.

Am i doing something wrong ?
Thanks in advance

**Comment by asturur** [comment]
can you add some fiddle demonstrating the problem?

**Comment by zedryas** [comment]
Will do

Le lundi 18 juillet 2016, Andrea Bogazzi <notifications@github.com> a
écrit :
