### ISSUE TITLE
Error: Cannot resolve native modules such as 'canvas' using latest webpack

### ISSUE THREAD

**Issue by kristianmandrup** [kangax/fabric.js#3115]
Installed via npm, using Fabric in Electron React app

When I run my app:

```
ERROR in ./~/fabric/dist/fabric.js
[0] Module not found: Error: Cannot resolve module 'canvas' in /Users/kristianmandrup/repos/electron-apps/fuse-ide/node_modules/fabric/dist
[0]  @ ./~/fabric/dist/fabric.js 804:15-32 25135:15-32 25136:14-31
```

Offending code: `require('canvas')`

```
    createImage: function() {
      return fabric.isLikelyNode
        ? new (require('canvas').Image)()
        : fabric.document.createElement('img');
    },
```

After install of *fabric* there is no `canvas` module in `node_modules`

https://www.npmjs.com/package/canvas

https://github.com/Automattic/node-canvas/wiki/Installation---OSX

**Comment by kristianmandrup** [comment]
After solving canvas error, I get the following:

```bash
ERROR in ./~/canvas/lib/bindings.js
[0] Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/canvas in /Users/kristianmandrup/repos/electron-apps/fuse-ide/node_modules/canvas/lib
```

**Comment by kristianmandrup** [comment]
Finally solved it by adding `canvas` module to `externals` in `webpack.config.base.js`

```js
  externals: [
    'canvas'
  ],
```

**Comment by playground** [comment]
hi @kristianmandrup I'm getting similar issue with fabric.js in webpack

ERROR in ./~/canvas/build/Release/canvas.node
Module parse failed: /Users/ljeff/git_repo/sandbox/node/ow-dig/node_modules/canvas/build/Release/canvas.node Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '�' (1:0)
    at Parser.pp$4.raise (/test1/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/Users/ljeff/git_repo/sandbox/node/ow-dig/node_modules/webpack/node_modules/acorn/dist/acorn.js:2756:10)

adding externals: ['canvas'] still gets that warning

WARNING in ./~/bindings/README.md
Module parse failed: /test1/node_modules/bindings/README.md Unexpected token (2:3)
You may need an appropriate loader to handle this file type.

**Comment by Madhivarman** [comment]
i am new to ionic and i am getting same error ... where i can find webpack.config.base.js to add canvas in my project..  :)

**Comment by Madhivarman** [comment]
@kristianmandrup when i add   `externals` in **webpack.config.js**  and after run the project  it shows run time error..

canvas is not defined

> ReferenceError: canvas is not defined
    <anonymous>
    main.js:46914
    __webpack_require__()
     main.js:20
      <anonymous>
     main.js:146178
     <anonymous>
      main.js:146007
   __webpack_require__()
       main.js:20
     <anonymous>
       main.js:107505
     __webpack_require__()

**Comment by kristianmandrup** [comment]
Perhaps try using `node` config object:

```js
node: {
  canvas: 'empty'
}
```

This is required for all modules that are by default included by node and thus should be ignored in the resolve phase. Haven't tested it, but seen it working for several similar error cases.

**Comment by Madhivarman** [comment]
i tried but still there is an same error..:(

**Comment by asturur** [comment]
if you are using fabric in the browser and and building with webpack under nodejs, please remove node module from your custom build. that should help.

**Comment by Madhivarman** [comment]
i am using CamanJs for image filter..i am not using fabric..

**Comment by asturur** [comment]
so why you ask here?

**Comment by Madhivarman** [comment]
no response there..i am stuck in this error more than two days...i  am new to native applications..so its helpfull for me if i got some help here..

**Comment by asturur** [comment]
Some of your file is doing `require('Canvas')`. Find that file and tell us wich is it.

**Comment by Madhivarman** [comment]
mm...in the file webpack.config.js

**Comment by theasia-Ashish** [comment]
I solve it by adding following in webpack :
{
        test: /\.node$/,
        use: 'node-loader',
},
resolve: {
    extensions: ['.node'],
  },
