### ISSUE TITLE
Textbox - "selection:changed" event fires twice.

### ISSUE THREAD

**Issue by belfz** [kangax/fabric.js#3116]
## Version
1.6.2

## Test Case
http://jsfiddle.net/rrrgye4u/

## Steps to reproduce
1. Add canvas and Textbox.
2. Put a cursor in the text. Move the cursor with left/right arrows on the keyboard.
3. Observe the counter above the canvas - the `'selection:changed'` event fires twice each time.

## Expected Behavior
`'selection:changed'` should fire only **once** per each cursor position change.

## Actual Behavior
`'selection:changed'` event fires **twice** per each cursor position change.

**Comment by asturur** [comment]
yes i think somewhere we call setSelectionStart and setSelectionEnd togheter.

**Comment by asturur** [comment]
i checked all selection:changed events and made some changes. Would you give a check again?

**Comment by belfz** [comment]
It seems to be working fine now. Thanks!
