### ISSUE TITLE
Fabric.js touch events

### ISSUE THREAD

**Issue by 5ello** [kangax/fabric.js#3118]
I created a program and tested it and everything is fine, but then i tested it on an iPad but the only touch events that is working are the click and drag.

I tested the demo provided by this link http://fabricjs.com/touch-events and its working on the device.

I also noticed that when I dont include the fabric.min.js library the touch events work but other functionalities dont (get allot of errors).

I did download the custom fabric file and i did select gestures so it should be supported, and the fabric.js and fabric.min.js are version 1.6.3.

Is there any implementations i need to do? Thank you for your time and efforts for this amazing library, looking forward to hearing from you.

**Comment by butch2k** [comment]
Actually i encountered the very same issue, and given my large codebase still in beta i did not investigate further thinking i had probabbly messed up something. I coded my own pinch gesture using e.self.scale as a basis, as a quick fix.

**Comment by asturur** [comment]
please clone the folder of the project with git and run the command npm run build_with_gestures.
That should you give a fabricjs version with buildein gestures module.
