### ISSUE TITLE
Points x and y values doesn't change even after modifying/expanding shape/resizing it

### ISSUE THREAD

**Issue by ManjunathBiradar** [kangax/fabric.js#3123]
## Version
1.6.2

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Steps to reproduce
1) draw a triangle on canvas
2) expand the shape using any one of the point 
3) get the points values 
4) Points x and y value remains as that of initial
## Expected Behavior
point.x and point.y value must change if resize/expand/drag the shape
## Actual Behavior
point.x and point.y values remain same no matter where they are on canvas

**Comment by asturur** [comment]
Yes points stays the same.
If you want to get the updated points get the transformMatrix ( object.calcTransformMatrix() ) and multiply every point with it.

**Comment by ManjunathBiradar** [comment]
Thank you
I will try this one but matrix is [0][6] order right? and Multiply each point with this matrix, Can you please bit elaborate on this on how to achieve

**Comment by ManjunathBiradar** [comment]
@asturur 
This what I have done, but its rendering my object at some other place when I pass these points.
var matrix=[];
matrix=polygon.calcTransformMatrix();
var translatedPoints = polygon.get('points').map(function(p) {
              return { 					 
                         x: (p.x*matrix[0]) + (p.y*matrix[2]) + matrix[4],
                         y: (p.x*matrix[1]) + (p.y*matrix[3]) + matrix[5]

         };
});

**Comment by ManjunathBiradar** [comment]
@asturur 
This is my whole set of code. After getting new updated points , I am directly passing these points to draw the polygon but its not exactly placing the object when compare with modified object.
Please help me , I am struck here.

<!DOCTYPE html>
<head>
	<meta charset="UTF-8" />
    <title>Fabric</title>
	<script src="js/fabric.canvasex"></script>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
   <script src="fabric.js\dist\fabric.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.5.0/fabric.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js"></script>
   <script src="http://rawgit.com/kangax/fabric.js/master/dist/all.js"></script>
   <style>
    #canvas-container {
    position: relative;
    width: 800px;
    height: 600px;
    box-shadow: 0 0 5px 1px black;
    margin: 10px auto;
    border: 5px solid transparent;
   }
  #canvas-container.over {
    border: 5px;
  }
  #images img.img_dragging {
    opacity: 0.4;
  }

 </style>
</head>

<body>
<div id="images">
    <img draggable="true" id="triangle" src="Images\triangle.png" width="50" height="50"></img><br/>
    <img draggable="true" id="pentagon" src="Images\polygon.png" width="50" height="50"></img><br/>
    <img draggable="true" id="rectangle" src="Images\square.png" width="50" height="50"></img><br/>
	<img draggable="true" id="hexagon" src="Images\hexagon.png" width="50" height="50"></img><br/>
</div>

<div id="canvas-container">
    <canvas id="canvas" width="640" height="480"></canvas>
</div>

<script>
		$(document).ready(function() {
	
var canvas = new fabric.Canvas('canvas');
canvas.setBackgroundImage('file:///D:/New folder/Images/roi_image.png', canvas.renderAll.bind(canvas), {
  width: canvas.width,
  height: canvas.height,
  backgroundColor:'white',
  // Needed to position backgroundImage at 0/0
  originX: 'left',
  originY: 'top'
});
function handleDragStart(e) {
    [].forEach.call(images, function (img) {
        img.classList.remove('img_dragging');
    });
    this.classList.add('img_dragging');
}

function handleDragOver(e) {
    if (e.preventDefault) {
        e.preventDefault();     
   }

    e.dataTransfer.dropEffect = 'copy'; 
    return false;
}

function handleDragEnter(e) {
    // this / e.target is the current hover target.
    this.classList.add('over');
}

function handleDragLeave(e) {
    this.classList.remove('over'); // this / e.target is previous target element.
}

function handleDrop(e) {
    // this / e.target is current target element.

    if (e.stopPropagation) {
        e.stopPropagation(); 
		e.preventDefault();// stops the browser from redirecting.
    }

    var img = document.querySelector('#images img.img_dragging');

    console.log('event: ', e);
	console.log('image: ', img.id);
	if(img.id === 'triangle') {
		var id="shape"+0;
		var points=regularPolygonPoints(3,30);
		var triangle =  new fabric.Polygon(points,{
						id:id,
						fill: "transparent",
		                                strokeWidth:0.75,
		                                stroke:'rgb(255,0,0)',
						borderColor: 'red',
                                                cornerColor: 'green',
						cornerSize: 6,
						top:e.layerY,
						left:e.layerX,
						transparentCorners: false
                });
		canvas.add(triangle);
		
	 }else if(img.id === 'rectangle'){
	          var points1=regularPolygonPoints(4,30);
	          var rect = new fabric.Polygon(points1,{
						fill: "transparent",
		                                strokeWidth:0.75,
		                                 stroke:'rgb(255,0,0)',
						borderColor: 'red',
                                                cornerColor: 'green',
						cornerSize: 6,
						top:e.layerY,
						left:e.layerX,
						transparentCorners: false
                });
             canvas.add(rect);	         
	}else if(img.id === 'pentagon'){
	
	          var points=regularPolygonPoints(5,30);
	          var pentagon = new fabric.Polygon(points,{
						width: 50, 
						height: 50,
						fill: "transparent",
		                                strokeWidth:0.25,
		                                stroke:'rgb(255,0,0)',
						borderColor: 'red',
                                                cornerColor: 'green',
						cornerSize: 6,
						top:e.layerY,
						left:e.layerX,
						transparentCorners: false
						
                });
             canvas.add(pentagon);	         
	}else if(img.id === 'hexagon'){
	
	var points=regularPolygonPoints(6,30);
	          var pentagon = new fabric.Polygon(points,{
						fill: "transparent",
		                                strokeWidth:0.25,
		                                stroke:'rgb(255,0,0)',
						borderColor: 'red',
                                               cornerColor: 'green',
						cornerSize: 6,
						transparentCorners: false,
						left: e.layerX, 
						top: e.layerY
                });
             canvas.add(pentagon);	         
	}else{
                        var newImage = new fabric.Image(img, {
                        width: img.width,
                        height: img.height,
						fill:"rgb(0,0,255)",
						borderColor: 'red',
						cornerColor: 'green',
						cornerSize: 6,
						transparentCorners: false,
						left: e.layerX,
						top: e.layerY
      });
             canvas.add(newImage);
	}

    return false;
}

function regularPolygonPoints(sideCount,radius){
    var sweep=Math.PI*2/sideCount;
    var cx=radius;
    var cy=radius;
    var points=[];
    for(var i=0;i<sideCount;i++){
        var x=cx+radius*Math.cos(i*sweep);
        var y=cy+radius*Math.sin(i*sweep);
        points.push({x:x,y:y});
    }
 console.log("points  "+JSON.stringify(points));
    return(points);
}

function handleDragEnd(e) {
    // this/e.target is the source node.
    [].forEach.call(images, function (img) {
        img.classList.remove('img_dragging');
    });
}
    var images = document.querySelectorAll('#images img');
    [].forEach.call(images, function (img) {
        img.addEventListener('dragstart', handleDragStart, false);
        img.addEventListener('dragend', handleDragEnd, false);
    });
    // Bind the event listeners for the canvas
    var canvasContainer = document.getElementById('canvas-container');
    canvasContainer.addEventListener('dragenter', handleDragEnter, false);
    canvasContainer.addEventListener('dragover', handleDragOver, false);
    canvasContainer.addEventListener('dragleave', handleDragLeave, false);
    canvasContainer.addEventListener('drop', handleDrop, false);

//THIS WHERE I HAVE IMPLEMENTED YOUR SOLUTION TO GET UPDATED POINTS
    canvas.on('object:modified',function(e){

       		var polygon = e.target;
		var matrix=[];
		matrix=polygon.calcTransformMatrix();
		console.log("Matrix : "+JSON.stringify(matrix);

               var translatedPoints = polygon.get('points').map(function(p) {
                                return { 
                   
					  x: (p.x*matrix[0]) + (p.y*matrix[2]) + matrix[4],

                                         y: (p.x*matrix[1]) + (p.y*matrix[3]) + matrix[5]
					

                             };
		 
             });
        	console.log("Modified points :"+JSON.stringify(translatedPoints));	
    });

	fabric.Canvas.prototype.getItemById = function(id) {
	  var object = null,
	      objects = this.getObjects();

	  for (var i = 0, len = this.size(); i < len; i++) {
	    if (objects[i].id && objects[i].id === id) {
	      object = objects[i];
	      break;
	    }
	  }
	  return object;
	};

});
	
    </script>
</body>
</html>

**Comment by ManjunathBiradar** [comment]
`
This is my whole set of code. After getting new updated points , I am directly passing these points to draw the polygon but its not exactly placing the object when compare with modified object.
Please help me , I am struck here.
<!DOCTYPE html>
<head>
	<meta charset="UTF-8" />
    <title>Fabric</title>
	<script src="js/fabric.canvasex"></script>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
   <script src="fabric.js\dist\fabric.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.5.0/fabric.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js"></script>
   <script src="http://rawgit.com/kangax/fabric.js/master/dist/all.js"></script>
   <style>
    #canvas-container {
    position: relative;
    width: 800px;
    height: 600px;
    box-shadow: 0 0 5px 1px black;
    margin: 10px auto;
    border: 5px solid transparent;
   }
  #canvas-container.over {
    border: 5px;
  }
  #images img.img_dragging {
    opacity: 0.4;
  }

 </style>
</head>

<body>
<div id="images">
    <img draggable="true" id="triangle" src="Images\triangle.png" width="50" height="50"></img><br/>
    <img draggable="true" id="pentagon" src="Images\polygon.png" width="50" height="50"></img><br/>
    <img draggable="true" id="rectangle" src="Images\square.png" width="50" height="50"></img><br/>
	<img draggable="true" id="hexagon" src="Images\hexagon.png" width="50" height="50"></img><br/>
</div>

<div id="canvas-container">
    <canvas id="canvas" width="640" height="480"></canvas>
</div>

<script>
		$(document).ready(function() {
	
var canvas = new fabric.Canvas('canvas');
canvas.setBackgroundImage('file:///D:/New folder/Images/roi_image.png', canvas.renderAll.bind(canvas), {
  width: canvas.width,
  height: canvas.height,
  backgroundColor:'white',
  // Needed to position backgroundImage at 0/0
  originX: 'left',
  originY: 'top'
});
function handleDragStart(e) {
    [].forEach.call(images, function (img) {
        img.classList.remove('img_dragging');
    });
    this.classList.add('img_dragging');
}

function handleDragOver(e) {
    if (e.preventDefault) {
        e.preventDefault();     
   }

    e.dataTransfer.dropEffect = 'copy'; 
    return false;
}

function handleDragEnter(e) {
    // this / e.target is the current hover target.
    this.classList.add('over');
}

function handleDragLeave(e) {
    this.classList.remove('over'); // this / e.target is previous target element.
}

function handleDrop(e) {
    // this / e.target is current target element.

    if (e.stopPropagation) {
        e.stopPropagation(); 
		e.preventDefault();// stops the browser from redirecting.
    }

    var img = document.querySelector('#images img.img_dragging');

    console.log('event: ', e);
	console.log('image: ', img.id);
	if(img.id === 'triangle') {
		var id="shape"+0;
		var points=regularPolygonPoints(3,30);
		var triangle =  new fabric.Polygon(points,{
						id:id,
						fill: "transparent",
		                                strokeWidth:0.75,
		                                stroke:'rgb(255,0,0)',
						borderColor: 'red',
                                                cornerColor: 'green',
						cornerSize: 6,
						top:e.layerY,
						left:e.layerX,
						transparentCorners: false
                });
		canvas.add(triangle);
		
	 }else if(img.id === 'rectangle'){
	          var points1=regularPolygonPoints(4,30);
	          var rect = new fabric.Polygon(points1,{
						fill: "transparent",
		                                strokeWidth:0.75,
		                                 stroke:'rgb(255,0,0)',
						borderColor: 'red',
                                                cornerColor: 'green',
						cornerSize: 6,
						top:e.layerY,
						left:e.layerX,
						transparentCorners: false
                });
             canvas.add(rect);	         
	}else if(img.id === 'pentagon'){
	
	          var points=regularPolygonPoints(5,30);
	          var pentagon = new fabric.Polygon(points,{
						width: 50, 
						height: 50,
						fill: "transparent",
		                                strokeWidth:0.25,
		                                stroke:'rgb(255,0,0)',
						borderColor: 'red',
                                                cornerColor: 'green',
						cornerSize: 6,
						top:e.layerY,
						left:e.layerX,
						transparentCorners: false
						
                });
             canvas.add(pentagon);	         
	}else if(img.id === 'hexagon'){
	
	var points=regularPolygonPoints(6,30);
	          var pentagon = new fabric.Polygon(points,{
						fill: "transparent",
		                                strokeWidth:0.25,
		                                stroke:'rgb(255,0,0)',
						borderColor: 'red',
                                               cornerColor: 'green',
						cornerSize: 6,
						transparentCorners: false,
						left: e.layerX, 
						top: e.layerY
                });
             canvas.add(pentagon);	         
	}else{
                        var newImage = new fabric.Image(img, {
                        width: img.width,
                        height: img.height,
						fill:"rgb(0,0,255)",
						borderColor: 'red',
						cornerColor: 'green',
						cornerSize: 6,
						transparentCorners: false,
						left: e.layerX,
						top: e.layerY
      });
             canvas.add(newImage);
	}

    return false;
}

function regularPolygonPoints(sideCount,radius){
    var sweep=Math.PI*2/sideCount;
    var cx=radius;
    var cy=radius;
    var points=[];
    for(var i=0;i<sideCount;i++){
        var x=cx+radius*Math.cos(i*sweep);
        var y=cy+radius*Math.sin(i*sweep);
        points.push({x:x,y:y});
    }
 console.log("points  "+JSON.stringify(points));
    return(points);
}

function handleDragEnd(e) {
    // this/e.target is the source node.
    [].forEach.call(images, function (img) {
        img.classList.remove('img_dragging');
    });
}
    var images = document.querySelectorAll('#images img');
    [].forEach.call(images, function (img) {
        img.addEventListener('dragstart', handleDragStart, false);
        img.addEventListener('dragend', handleDragEnd, false);
    });
    // Bind the event listeners for the canvas
    var canvasContainer = document.getElementById('canvas-container');
    canvasContainer.addEventListener('dragenter', handleDragEnter, false);
    canvasContainer.addEventListener('dragover', handleDragOver, false);
    canvasContainer.addEventListener('dragleave', handleDragLeave, false);
    canvasContainer.addEventListener('drop', handleDrop, false);

//THIS WHERE I HAVE IMPLEMENTED YOUR SOLUTION TO GET UPDATED POINTS
    canvas.on('object:modified',function(e){

       		var polygon = e.target;
		var matrix=[];
		matrix=polygon.calcTransformMatrix();
		console.log("Matrix : "+JSON.stringify(matrix);

               var translatedPoints = polygon.get('points').map(function(p) {
                                return { 
                   
					  x: (p.x*matrix[0]) + (p.y*matrix[2]) + matrix[4],

                                         y: (p.x*matrix[1]) + (p.y*matrix[3]) + matrix[5]
					

                             };
		 
             });
        	console.log("Modified points :"+JSON.stringify(translatedPoints));	
    });

	fabric.Canvas.prototype.getItemById = function(id) {
	  var object = null,
	      objects = this.getObjects();

	  for (var i = 0, len = this.size(); i < len; i++) {
	    if (objects[i].id && objects[i].id === id) {
	      object = objects[i];
	      break;
	    }
	  }
	  return object;
	};

});
	
    </script>
</body>
</html>
`

**Comment by ManjunathBiradar** [comment]
@asturur @kangax 
1) When i expand the shape and check for transform matrix, it is : [2.677685950413222,0,0,1,327.25206611570246,146.35576211353316]

2) And when i get the updated points using fabric.util.transformPoint(point, matrix) method  with the matrix above and pass the updated points to draw the polygon, the transform matrix i get for newly drawn polygon is : [1,0,0,1,428.04028925619826,176.73076211353316]

3) So the position tx and ty has got significantly changed.

Please help me, fabric.util.transformPoint method is not returning right set of points because of which polygons "POSITION " is getting changed.

**Comment by ManjunathBiradar** [comment]
@asturur 
Hey, I am using  https://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.5.0/fabric.js  plugin for my use case. Is that ok?

**Comment by ManjunathBiradar** [comment]
@asturur 
var translatedPoints = polygon.get('points').map(function(p) {
              return { 
					x: matrix[0] * p.x  + matrix[2] * p.y + matrix[4] - 77.5,
                    y: matrix[1] * p.x  + matrix[3] * p.y + matrix[5] - 30
             };
		 
        }); 

This is rendering my object right at the same place since I have subtracted some random values to adjust the extra left and top position

**Comment by ManjunathBiradar** [comment]
https://jsfiddle.net/sL2np4wj/7/

**Comment by asturur** [comment]
use latest versions, older are not supported. i ll try to get a look as
soon as i can

**Comment by ManjunathBiradar** [comment]
@asturur  can you please tel me the latest version?  Currently I am using 1.6.3

**Comment by ManjunathBiradar** [comment]
@asturur can you please keep this issue open?
Below code gives me right set of new updated points but WITHOUT ROTATE OPTION
If I keep ROTATE ENABLED and get the updated points using below code , then I get wrong set of points.
So for now , I have disabled ROTATE option.
So how do I get the right set of updated points with ROTATE enanbled??
canvas.on('object:modified', function(e) {
        var newCoordinates = "";
        var matrix = [];
        var polygon = canvas.getItemById(e.target.id);
        matrix = polygon.calcTransformMatrix();
        var translatedPoints = polygon.get('points').map(function(p) {
            return {
                x: p.x - polygon.pathOffset.x,
                y: p.y - polygon.pathOffset.y
            };
        });
        for (var i = 0; i < translatedPoints.length; i++) {
            translatedPoints[i].x = matrix[0] * translatedPoints[i].x + matrix[2] * translatedPoints[i].y + matrix[4];
            translatedPoints[i].y = matrix[1] * translatedPoints[i].x + matrix[3] * translatedPoints[i].y + matrix[5];
        }
        var temp = JSON.stringify(translatedPoints);
      });

**Comment by ManjunathBiradar** [comment]
@asturur 
Can  you please help me regarding the above comment please??
Only thing after rotate with above code I am not getting right set of new modified points.
Please waiting for your reply.

**Comment by asturur** [comment]
i think i answered something identical on stackoverflow. can you give a look? is on my answer and there was code and working snippet

**Comment by ManjunathBiradar** [comment]
@asturur 
Can you please provide the link. It would be of great help

**Comment by asturur** [comment]
http://stackoverflow.com/questions/38999034/how-does-transforming-points-with-a-transformmatrix-work-in-fabricjs/39072194#39072194

**Comment by ManjunathBiradar** [comment]
@asturur 
Thanks a lot. I will take a look at it
