### ISSUE TITLE
Custom build with gesture module fabric 1.6.3

### ISSUE THREAD

**Issue by JugnuPathak** [kangax/fabric.js#3126]
We have upgraded from fabric 1.5.0 to 1.6.3 but fabric gesture are not supported in current build, also we are unable to create custom build using node.js as cario's installation process of cario is not well documented. Can you provide any full tutorial/link [](http://fabricjs.com/build/) for creating custom build 
for fabric?

**Comment by asturur** [comment]
you should not need cairo to build fabricjs.
create a folder and clone fabricjs repository there.
once cloned, do not need to do npm install, do npm run build mdules=ALL
exclude=json
minification will fail if you do not have uglifyjs.
nodecanvas requires libcairo, on theyr github repo they explain how to do.

**Comment by JugnuPathak** [comment]
Thanks its working!!!

**Comment by niketaOptimumnbrew** [comment]
> Thanks its working!!!

Hi, Can you please tell me How your things done because I have same issue and it's not resolved yet.
