### ISSUE TITLE
Transparent fill is not restored from json

### ISSUE THREAD

**Issue by alexeyovdienko** [kangax/fabric.js#3127]
I've created custom class with 2 objects: React object and IText. I set fill for react as transparent and stroke with black color. When i add it to canvas - it renders like it should ( button with text inside). Then i load canvas tojson via toJSON() and send it to backend and save to json field of postgresql.
On other view I'd like to restore json into canvas.  I'm loading it via loadFromJSON() and it give all objects correct, except this button, In json objects aka buttons with text have fill #000. 
How to save into json trasparent value?

**Comment by asturur** [comment]
did you try to use fill= ''?

**Comment by alexeyovdienko** [comment]
@asturur, I've tried this, and it didn't help.
R&D gave me some picture for more details about the problem.
I created a custom class by
`fabric.Tag = fabric.util.createClass(fabric.Group, {
    type: 'Tag',

    initialize: function (options, objects, isAlreadyGrouped) {
        if (!options) {
            objects = [];
            options = {};
            options.top = 20;
            options.left = 10 + leftCoords;

            var defaults = {
                width: 200,
                height: 40,
                originX: 'center',
                originY: 'center'
            };

            objects[0] = new fabric.Rect(extend({}, defaults, {
                fill: '',
                stroke: '#000',
                strokewidth: 4,
                rx: 5,
                ry: 5
            }));

            objects[1] = new fabric.IText('Смотреть     >', extend({}, defaults, {
                textAlign: 'center',
                fontFamily: 'Roboto',
                fontSize: 20
            }));
        }
        leftCoords += objects[0].width + padding_buttons;
        this.callSuper('initialize', objects, options, isAlreadyGrouped);
    }
});`

set a fill in object[0] and it is transparent on canvas, when I save to json it gives and object with 2 objects in it:
![image](https://cloud.githubusercontent.com/assets/20338033/17138073/3df2381a-5347-11e6-95b7-aef3fc74407c.png)

parent object "Tag" is filled #000 and inner object[0] has hardcoded transparent

**Comment by asturur** [comment]
which version are you using?

**Comment by alexeyovdienko** [comment]
@asturur, "fabric": "^1.6.3",

**Comment by alexeyovdienko** [comment]
@asturur, maybe I should redefine some inner methods of fabric like loadfromjson or smth?

**Comment by asturur** [comment]
i don t think so. i have to find some minite to check it to see if there is a bug or an error from your side

**Comment by alexeyovdienko** [comment]
@asturur ,
```

fabric.LabeledRect = fabric.util.createClass(fabric.Rect, {
    type: 'labeledRect',
    initialize: function (options) {
        options || (options = {});
        this.callSuper('initialize', options);
        this.set('label', options.label || '');
    },
    toObject: function () {
        return fabric.util.object.extend(this.callSuper('toObject'), {
            label: this.get('label')
        });
    },
    _render: function (ctx) {
        this.callSuper('_render', ctx);
        ctx.font = '20px Helvetica';
        ctx.fillStyle = '#333';
        ctx.fillText(this.label, -this.width/2 + this.width/4, -this.height / 2 + this.height/1.6);
    }
});
fabric.LabeledRect.fromObject = function (object, callback) {
    var _enlivenedObjects;
    fabric.util.enlivenObjects(object.objects, function (enlivenedObjects) {
        delete object.objects;
        _enlivenedObjects = enlivenedObjects;
    });
    return new fabric.LabeledRect(_enlivenedObjects, object);
};

fabric.LabeledRect.async = false;
```

I've tried another option AKA labeled rect from habrhabr example
It has the same story, I can draw on canvas and save like image, but tojson, from json gives me empty canvas body, and in upper left corn empty object. I can zoom more and remove to other position, and it is empty.

**Comment by asturur** [comment]
```
fabric.Tag.fromObject = function (object, callback) {
    var _enlivenedObjects;
    fabric.util.enlivenObjects(object.objects, function (enlivenedObjects) {
        delete object.objects;
        _enlivenedObjects = enlivenedObjects;
    });
    var isAlreadyGrouped = true;
    return new fabric.Tag(object, _enlivenedObjects, isAlreadyGrouped);
};
```

please as we do for groups, valorize the value third parameter of constructor with true. This will stop delegated properties to go over the inner objects.
