### ISSUE TITLE
Custom Object with Custom Controls

### ISSUE THREAD

**Issue by meriturva** [kangax/fabric.js#3129]
We know that it is possible to write custom object as: 
https://developer.tizen.org/community/tip-tech/creating-custom-objects-fabric.js?langswitch=en
http://jsfiddle.net/jrdiaz/mVQKL/

But i don't find a way to add custom controlls to custom objects. For example we have to create a Donut where user could change start and end angles.

Something like:
https://jsfiddle.net/asturur/on0xg64k/3/

What do you think? could be possible to do it?

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
