### ISSUE TITLE
Editing of IText is broken for Chrome on Android:.

### ISSUE THREAD

**Issue by mike-hogan** [kangax/fabric.js#3130]
View this page on using Chrome on Android:

http://fabricjs.com/test/misc/itext.html

Double-tap on one of the test elements and it just zooms the page. Long tap does nothing, except initial a drag, it seems.

It seems editing of IText is broken on mobile.

**Comment by neopheus** [comment]
What is your Android version ?

**Comment by mike-hogan** [comment]
I'm sorry - I did not see your question on Aug 11.

Back them it was Android 6.x.  Not it's 7.0.  But when I go to that link on my mobile or my laptop, I get a blank page and an error in the javascript console saying

Uncaught TypeError: this.getObjectScaling is not a function
