### ISSUE TITLE
How to resize large canvas(image) to fixed width& height

### ISSUE THREAD

**Issue by devbikshu** [kangax/fabric.js#3131]
How to resize large canvas(image) to fixed width& height canvas where it is having another canvas (logo)on top of it which is interactive.

And then merge these two canvas to download. my site url is : http://cricmovie.com/bbb-imagecrop1/
I want to built site like http://wallpapergenerator.thehobbit.com 

Thanks.

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
