### ISSUE TITLE
IText/Textbox - selecting a word via double click doesn't work

### ISSUE THREAD

**Issue by belfz** [kangax/fabric.js#3132]
## Version
1.6.3

## Test Case
http://jsfiddle.net/bn8vaw2e/

## Steps to reproduce
Double click on either of the words. It doesn't get selected. Same bug for both IText/Textbox.
Used to work fine in v.1.6.2 (downgrading however is not an option - in v.1.6.2 selecting a text with click&drag to left/right didn't work).

## Expected Behavior
As per [IText documentation](http://fabricjs.com/docs/fabric.IText.html), `select word` should work on `double click`.

## Actual Behavior
Double clicking on word does not highlight (select) it.

**Comment by asturur** [comment]
this works. there was a bug in rendering the selection area, the word was anyway selected.
Fixed with latest build.

**Comment by belfz** [comment]
Have you released the fixed code to npm? Because the freshly-installed npm version (1.6.3) still has these bugs.
