### ISSUE TITLE
IText/Textbox - creating selection with click & shift+click doesn't work

### ISSUE THREAD

**Issue by belfz** [kangax/fabric.js#3133]
## Version
1.6.3

## Test Case
http://jsfiddle.net/bn8vaw2e/

## Steps to reproduce
Position the cursor just after last letter of the text. Shift click on the beginning of the text (to the left of the first letter). No selection is created.
Used to work fine in v.1.6.2 (downgrading however is not an option - in v.1.6.2 selecting a text with click&drag to left/right didn't work).

## Expected Behavior
As per [IText documentation](http://fabricjs.com/docs/fabric.IText.html), `create selection` should work on `click & shift + click`.

## Actual Behavior
Positioning a cursor via click and then performing `shift+click` doesn't create a selection.

**Comment by asturur** [comment]
Can you check again on your fiddle with the updated build? it looks working to me.

**Comment by belfz** [comment]
That's surprising. It seems to be working fine now. Did you actually fix that without releasing new version?

**Comment by asturur** [comment]
npm is still 1.6.3 as it was.
Master branch contains 1.6.3 And fixes for:
Improvement: Ignore svg: namespace during svg import. #3081
Improvement: Better fix for lineHeight of iText/Text #3094
Improvement: Support for gradient with 'Infinity' coordinates #3082
Improvement: Generally "improved" logic of targeting #3111
Fix: Selection of active group with transparency and preserveObjectStacking true or false #3109
Fix: pattern brush now create the same pattern seen while drawing #3112
Improvement: added numeric origins handling fomr 0 to 1. #3121
Fix: Fix a defect with shadow of objects in a scaled group. #3134
Improvement: Do not fire unecessary selection:changed events. #3119

**Comment by asturur** [comment]
as soon as  i manage to clear all the things i tagged with 1.6.4 i will release 1.6.4 to cdn and npm.

**Comment by asturur** [comment]
Let me know if i can close this issue.

**Comment by belfz** [comment]
@asturur thank you very much for clarification. Yes, this can be closed. Cheers!
