### ISSUE TITLE
Rotating does not give instant property update to left/top properties

### ISSUE THREAD

**Issue by Fidel90** [kangax/fabric.js#3140]
## Version
1.6.3

## Test Case
https://jsfiddle.net/gvj7tz7p/5/

## Steps to reproduce
Scale, rotate and move the red rectangle on the canvas and watch the properties (left, top, width, height, scaleX, scaleY, angle) diplayed below. 

## Expected Behavior
When moving, scaling or rotating and listening to the associated events should give an instant update to all the watched parameters of the rectangle.

## Actual Behavior
1. When moving, the coordinates left/top are updated instantly as expected.
2. When scaling, the properties left/top/scaleX/scaleY are only updated in the "object:modified" handler. (I'm not able to reproduce this everytime, needs some more investigation by myself)
3. When rotating, the properties left/top are only updated in the "object:modified" handler. The angle property gets updated instantly as expected.

**Comment by asturur** [comment]
registering over object:scaling and object:rotating may help instead of 3 time object:moving

**Comment by Fidel90** [comment]
@asturur: I have seen my copy/paste error and edited the fiddle some hours ago. Maybe you are watching to an older version. Please take a look to this: https://jsfiddle.net/gvj7tz7p/5/

The issue 3. is not resolved by this.

**Comment by Fidel90** [comment]
Could someone please reopen this issue? Check my jsFiddle above. Properties top and left are not updated while the rectangle is rotated. The update only happens via the "object:modified" handler but not instantly in "object:rotating".

**Comment by asturur** [comment]
there is no issue.
during rotation top and left are moved to center of object, and on modified
they are moved back. during rotation there is no really any change that is
why they look not updated.
