### ISSUE TITLE
Passing transformPoints  renders object at different position

### ISSUE THREAD

**Issue by ManjunathBiradar** [kangax/fabric.js#3141]
## Version
1.6.3

## Test Case
 https://jsfiddle.net/sL2np4wj/7/

## Steps to reproduce

1. Drag and drop the polygon onto canvas at desired position
![screenshot 2](https://cloud.githubusercontent.com/assets/20626305/17360783/cd1b38a4-598a-11e6-9092-1cd1af5d036e.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/20626305/17360782/ccb826ce-598a-11e6-890d-8e04496acf50.png)

2. Expand/modify the shape

3. Get the transform points

4. Pass these transform points to draw the polygon

## Expected Behavior
Object should be at the same position as that of modified shape
## Actual Behavior
Object is at some other position

**Comment by ManjunathBiradar** [comment]
@asturur My jsfiddle is https://jsfiddle.net/sL2np4wj/7/ and I have provided screen shots of initial and final result

**Comment by asturur** [comment]
duplicate. Please do not open duplicates.
