### ISSUE TITLE
Objects added during the page load are not selectable.

### ISSUE THREAD

**Issue by ManjunathBiradar** [kangax/fabric.js#3142]
## Version
1.6.3

## Steps to reproduce
1. add the polygon objects during on load function

2. try to select the added objects
## Expected Behavior
objects added to canvas during page load must be selectable 
## Actual Behavior
objects added to canvas during page load are not selectable but after page load whichever objects I add only those objects are selectable

**Comment by asturur** [comment]
jsfiddle that demonstrate the problem.
