### ISSUE TITLE
Front object not selectable after setting PreserveObjectStacking to false

### ISSUE THREAD

**Issue by saadqbal** [kangax/fabric.js#3149]
When the PreserveObjectStacking is set to true, the object on top of the selected object is not selectable anymore. you have to deselect the object and then select the top object.

[https://jsfiddle.net/sfa1jk31/4/](https://jsfiddle.net/sfa1jk31/4/)

**Comment by neopheus** [comment]
It's same problem like : https://github.com/kangax/fabric.js/issues/3095

**Comment by asturur** [comment]
duplicato of #3095
