### ISSUE TITLE
Can't update size of existing group

### ISSUE THREAD

**Issue by daer-ru** [kangax/fabric.js#3151]
Hi. I'm sory what i created an issue but i realy need help :(
I created question on stackoverflow and google groups but there is still no answer.

I have problem with update size of existing group.

I have group of objects (or group of groups) alredy added on canvas. I changed position of one or all objects (groups) in group and parent group size is not changing.

I tried canvas.renderAll() and obj.setCoords() it's not help.

This is fiddle with simple example https://jsfiddle.net/daer/y2ekvsbL/

I have one quick and dirty solution  but unfortunately i can't use it because i have complex position calculation which don't allow remove object and recalculate position :(
I need calculate position inside group. 

I don't now it's bug or it's i'm stupid...

**Comment by asturur** [comment]
https://jsfiddle.net/y2ekvsbL/3/

you can update the bounding box, but recalculating the position will not be so simple.
destroying and recreating the group does this automatically if you can do that ( i do not see why not.
