### ISSUE TITLE
unexpected behaviour of the "selection" option on canvas

### ISSUE THREAD

**Issue by gengshenghong** [kangax/fabric.js#3153]
check the jsfiddle code for details.
http://jsfiddle.net/qp8x7a5w/3/

It is a very simple example of interactive free drawing of rect on canvas. The "selection" option works for the object/rect you draw, but why the "green" rect in the code is always selectable (you can select and move it)? Logically, it should behavior same, I cannot understand where it is wrong.

**Comment by neopheus** [comment]
Like this : http://jsfiddle.net/qp8x7a5w/5/ ?

**Comment by gengshenghong** [comment]
@neopheus yes, I know setting "selectable" on the "green" rect works. But I am just a little confused why the original code does not work. I want to use it to enable/disable "selectable" of the whole canvas (all objects on it) dynamically, I've not tested, but not sure whether that will be an issue.

**Comment by neopheus** [comment]
i know
Try this : http://jsfiddle.net/qp8x7a5w/6/

canvas.selection = false disables multiple object selection (by mouse or by shiftKey).

Or selectable: false object selection is disable

**Comment by neopheus** [comment]
`canvas.selection = false;
canvas.forEachObject(function(o) {
  o.selectable = false;
});`

**Comment by gengshenghong** [comment]
Thank you for the suggestion, I'll try that and use it as a workaround. There is no builtin property to disable whole canvas selectable (which is very common feature to create a drawing app like windows painter)?

Just my 2 cents, fabricjs may provide a way for people to disable this easily like setting "isDrawingMode". The bad thing is, with "isDrawingMode", you cannot disable the builtin free drawing feature. Setting "selectable = false" on all objects may be a performance issue if there are too many objects. Maybe a feature request is to have 2 property to control the events handling:
1. isDrawingMode/selectable (for whole canvas)
-> in this mode, you'll not be able to select any object, user can capture "mouse:up/down/move" to do the interactive drawing.
2. enableFreeDrawing
Only when isDrawingMode is true and enbaleFreeDrawing is true, it will run the builtin free drawing feature.

**Comment by gengshenghong** [comment]
@neopheus It is still not working perfectly with setting "selectable = false". To make it easy to show the issue, I've created the full logic of a simple draw app.
http://jsfiddle.net/qp8x7a5w/19/
In "draw" mode, I want to free drawing "rect" using mouse down and move. In "select" mode, I want to select object with "mouse down/click". A very common behavior of many software.

It is buggy in above jsfiddle code, it works in "draw mode". But when I click "Select Mode" button, the rect I've draw just now, cannot be selected. It only works when I first "group select" them, after that, the object becomes selectable.

Below is a gif to show the issue (I've clicked on the 3 rect before 'group selection', they cannot be selected):
![optimized](https://cloud.githubusercontent.com/assets/1018468/17578447/3ebd3670-5fbb-11e6-8ff6-7ed941cb3271.gif)

**Comment by gengshenghong** [comment]
It can also be reproduced with below operations (only using 1 rect): 1. Draw a rect 2. click "Select mode", and press mouse down and then move to select the rect (only select one rect), the object can be selected (selection controls show), but when you click on the object again, or try to change the object size, the selection controls disappear directly....I must first select at least 2 rect (group selection?) and then the object can be selected and changed correctly. I've tried with fabric 1.6.0 to 1.6.2 and are same.

**Comment by neopheus** [comment]
Try this : http://jsfiddle.net/qp8x7a5w/23/

**Comment by gengshenghong** [comment]
@neopheus did your changes saved? I do not see any differences in the code and behaviour is same too. (sometimes, jsfiddle does not upload your changes correctly...)

**Comment by neopheus** [comment]
Refresh, it's not the same code

```

var rect, isDown, origX, origY;

var canvas = new fabric.Canvas('c');
canvas.selection = false;

var isDrawing = true;
$('#text').html("current: drawRectMode");

$('#drawRectMode').on('click', function() {
  $('#text').html("current: drawRectMode");
  isDrawing = true;

  // disable selection
  canvas.selection = false;
  canvas.forEachObject(function(o) {
    o.selectable = false;
  });
  canvas.renderAll();

});

$('#selectMode').on('click', function() {
  $('#text').html("current: selectMode");
  isDrawing = false;

  // enable selection
  canvas.selection = true;
  canvas.forEachObject(function(o) {
    o.selectable = true;
  });
  canvas.renderAll();

});


canvas.on('mouse:down', function(o) {
  if (!isDrawing) {
    return;
  }
  isDown = true;
  var pointer = canvas.getPointer(o.e);
  origX = pointer.x;
  origY = pointer.y;
  var pointer = canvas.getPointer(o.e);
  rect = new fabric.Rect({
    left: origX,
    top: origY,
    originX: 'left',
    originY: 'top',
    width: pointer.x - origX,
    height: pointer.y - origY,
    angle: 0,
    fill: 'rgba(255,0,0,0.5)',
    transparentCorners: false,
    selectable: false
  });
  canvas.add(rect);
});

canvas.on('mouse:move', function(o) {
  if (!isDrawing) {
    return;
  }

  if (!isDown) return;
  var pointer = canvas.getPointer(o.e);

  if (origX > pointer.x) {
    rect.set({
      left: Math.abs(pointer.x)
    });
  }
  if (origY > pointer.y) {
    rect.set({
      top: Math.abs(pointer.y)
    });
  }

  rect.set({
    width: Math.abs(origX - pointer.x)
  });
  rect.set({
    height: Math.abs(origY - pointer.y)
  });

  canvas.renderAll();
});

canvas.on('mouse:up', function(o) {
  if (!isDrawing) {
    return;
  }

  isDown = false;
});

```

**Comment by gengshenghong** [comment]
@neopheus Not work and same behavior, the only change you made is "selectable: false" when create the rect, right?

The issue is I cannot come back to normal select mode (click "Select Mode" button) after draw rect.

**Comment by neopheus** [comment]
try this : http://jsfiddle.net/qp8x7a5w/24/

I have no problem with this version

**Comment by asturur** [comment]
http://jsfiddle.net/qp8x7a5w/28/

the point is adding rect.setCoords() after you modify rect dimensions.

**Comment by gengshenghong** [comment]
@neopheus @asturur Thank you very much, it works!

**Comment by brendler** [comment]
It looks like this code has a small bug. Try to drag a selected rectangle and you will notice that it will move but at the same time create a new triangle.
