### ISSUE TITLE
Extending Polygon class not reading type to set up 'klass'

### ISSUE THREAD

**Issue by moeloubani** [kangax/fabric.js#3158]
fabric.PolygonWithID = fabric.util.createClass(fabric.Polygon, {

        type: 'polygon-with-id',

        initialize: function(points, options) {
            options || ( options = { });
            this.callSuper('initialize', points, options);

            this.set('name', options.name || '');
            this.set('id', options.id || '');
        },

        toObject: function() {
            return fabric.util.object.extend(this.callSuper('toObject'), {
                name: this.get('name'),
               id: this.get('id'),
            });
        }

    });

    fabric.PolygonWithID.fromObject = function(object, callback) {
    callback && callback(new fabric.PolygonWithID(object.points, object, true));
    };

    fabric.PolygonWithID.async = true;

I'm using the above to try to add a couple of custom settings to the Polygon class but for some reason I am getting the 'async undefined' error when loading from JSON (object draws fine on the screen). I've double and triple checked to make sure that I'm using fabric.PolygonWithID and I've console.log(o.type) right before it does the getKlass call and everything seems to be looking good, it's just when it hits that getKlass call that it fails for some reason - the 'type' name is the exact same when I declare it above and when it's called here

    var klass = fabric.util.getKlass(o.type, namespace);

I've double and triple checked that things are right above, I hope it's not something I'm missing!

**Comment by neopheus** [comment]
jsfiddle that demonstrate the problem.

**Comment by asturur** [comment]
```javascript 
   getKlass: function(type, namespace) {
      // capitalize first letter only
      type = fabric.util.string.camelize(type.charAt(0).toUpperCase() + type.slice(1));
      return fabric.util.resolveNamespace(namespace)[type];
    },
```
so if you have PolygonWithID  type has to be polygonWithID

**Comment by moeloubani** [comment]
cant believe i didnt just click on the getKlass and look into that, thanks so much!
