### ISSUE TITLE
Italic doesn't work for fabric.Text in Mozilla Firefox

### ISSUE THREAD

**Issue by pavelKozlov** [kangax/fabric.js#3159]
## Version
^1.4.0

## Test Case
http://fiddle.jshell.net/m8acgkL5/2/
http://fiddle.jshell.net/1vv8gr82/4/

## Steps to reproduce
open http://fiddle.jshell.net/1vv8gr82/4/ in FF.

## Expected Behavior
_italic_ text displays as _italic_ and **_bolditalic_** as **_bolditalic_** 

## Actual Behavior
_italic_ text displays as normal and **_bolditalic_** as **bold**

If you open the same link (http://fiddle.jshell.net/1vv8gr82/4/) in Google Chrome, it displays ok.
But when you open http://fiddle.jshell.net/m8acgkL5/2/, there are no fabric text but <p> with different font styles and it displays ok in both browsers

**Comment by asturur** [comment]
Probably jester does not have any italic information insdid the font file.
Chrome make the italic version by its own, firefox refuses to do it ( and i agree ).
I hit the same issue using google font lately, if there is not the right variant, firefox will not paint it.

**Comment by pavelKozlov** [comment]
@asturur, thank you for your answer.
But how would you explain that if apply the same font to text in html markup without fabricjs, there is italic version?
Please, open this link in Firefox: http://fiddle.jshell.net/m8acgkL5/2/

**Comment by StephanBijzitter** [comment]
@pavelKozlov does this also reproduce in FF using the native canvas, without fabricjs?

**Comment by pavelKozlov** [comment]
Indeed, native canvas doesn't render italic font style: http://fiddle.jshell.net/m8acgkL5/3/.
