### ISSUE TITLE
uniScaleTransform flag not enforced (always true)

### ISSUE THREAD

**Issue by sirrodgepodge** [kangax/fabric.js#3162]
## Version
1.6.2

The "uniScaleTransform" flag is not actually enforced if false (the default) because of an accidental "or" where an "and" should be 

fixed here:
https://github.com/kangax/fabric.js/pull/3163

**Comment by sirrodgepodge** [comment]
https://github.com/kangax/fabric.js/pull/3163

**Comment by asturur** [comment]
answered in the PR.
To obtain the same effect void the uniscaleKey.
