### ISSUE TITLE
Control not selectable with controlsAboveOverlay: true

### ISSUE THREAD

**Issue by saadqbal** [kangax/fabric.js#3167]
When you set the controlsAboveOverlay: true and the control are overlaying an object, they are not selectable.

[https://jsfiddle.net/ecvctazk/39/](https://jsfiddle.net/ecvctazk/39/)

Select the red box and try to resize it from the right control above the black one. It won't resize. It will select the black box instead.

**Comment by neopheus** [comment]
it's ok : https://github.com/kangax/fabric.js/pull/3165

**Comment by asturur** [comment]
duplicate of #3095
