### ISSUE TITLE
Remove an area path image clipped

### ISSUE THREAD

**Issue by nguyenhiep2906** [kangax/fabric.js#3168]
Hi all
Can you help me.
I want to remove an path of image after i clipped it.
How i do.
![1](https://cloud.githubusercontent.com/assets/10969673/17691618/cc5e5326-63bf-11e6-9b8d-9a7ebfea9f7f.png)

![2](https://cloud.githubusercontent.com/assets/10969673/17691624/d7d394b4-63bf-11e6-9780-7c0d7c1d0445.png)

This is source code

var canvas = document.getElementById('img-canvas');
	var ctx = canvas.getContext('2d');
	var img = document.createElement('IMG');

	img.onload = function() {
	    var OwnCanv = new fabric.Canvas('img-canvas', {
	        isDrawingMode: true
	    });

	    var imgInstance = new fabric.Image(img, {
	        left: 0,
	        top: 0,
	    });
	    OwnCanv.add(imgInstance);
	    OwnCanv.freeDrawingBrush.color = "white"
	    OwnCanv.freeDrawingBrush.width = 1

	    OwnCanv.on('path:created', function(options) {
	        var path = options.path;
	        OwnCanv.isDrawingMode = false;
	        OwnCanv.remove(imgInstance);
	        OwnCanv.remove(path);
	        OwnCanv.clipTo = function(ctx) {
	            path.render(ctx);
	        };
	        OwnCanv.add(imgInstance);
	    });
	}

**Comment by asturur** [comment]
Please open a working snippet on StackOverflow i will help you there,
