### ISSUE TITLE
character width calculation wrong with some font which can make auto indent

### ISSUE THREAD

**Issue by minzojian** [kangax/fabric.js#3170]
![wrong character width](https://cloud.githubusercontent.com/assets/361781/17740521/7a76a9d4-64cb-11e6-9c69-522aada3a65c.png)

i create a normal textbox and type some "i"s inside,the font  i use is Lobster1.3,as you can see,i just selection one character,but the result is not correctly
![true end character position](https://cloud.githubusercontent.com/assets/361781/17740595/c8ca0a2c-64cb-11e6-8b18-71d162e7776f.png)
and this is the last character position while in selection.
it looks that some font like Lobster1.3 which can make auto indent can make some character width calculation wrong

**Comment by asturur** [comment]
i think is autoKerning. is there a way to measure the kerning from the font?

**Comment by minzojian** [comment]
i have no idea so far
anyway,i wanna add a letter spacing function into fabric,so i decide to render character separately,one by one,in that case,the text is look weird,
![image](https://cloud.githubusercontent.com/assets/361781/17759838/8a24688c-652d-11e6-9753-1dffa3a76abd.png)
and if i render the same text in node (export pdf in node side),it looks like this
![image](https://cloud.githubusercontent.com/assets/361781/17759870/c5392732-652d-11e6-994b-bbf3521aaf88.png)
code is the same,but result is different,
in browser (client side),the character "i",has a short tail,but in node (server side),it has a long tail.
especialy,the character become wider in node side,and makes a wrap.why that?

**Comment by asturur** [comment]
letter spacing is in the latest master lib

**Comment by minzojian** [comment]
yes,noticed
however,the result i use the lastest master lib is the same as what i did in the first post.
![image](https://cloud.githubusercontent.com/assets/361781/17763553/fd9961b4-654b-11e6-9c8b-7942ec4ca1ff.png)
character width calculate is wrong,what i current selection is not a empty space,but the last "i".
yet another,what the character "i" with same font  render in node side has a longer tail,is another issue.

**Comment by asturur** [comment]
can you build a fiddle with this font?

**Comment by minzojian** [comment]
sorry,i tried,but failed,jsfiddle is hard to host font style (or i have no clue to handle that)
http://jsfiddle.net/minzojian/o4mu5b6k/1/
this fiddle can work but that style is not ok,cause that font file can not be access from jsfiddle.

about the long tail and short tail with the "i" character,i guess it would be font protection or something,but i am not sure about that.cause in node side,it rendered fine.
at last,i found a ttf replaced otf file i used before,and rendered fine in browser now.

so the next issue is the character with calculation....

**Comment by neopheus** [comment]
try this : http://jsfiddle.net/o4mu5b6k/4/

**Comment by saadqbal** [comment]
I confirm this issue. check the jsfiddle below:

[http://jsfiddle.net/o4mu5b6k/5/](http://jsfiddle.net/o4mu5b6k/5/)

Every time you add letter, there is an extra space applied

**Comment by neopheus** [comment]
I don't see the bug, on Chrome :

![ya5ph6eqb4](https://cloud.githubusercontent.com/assets/5160844/17786802/c83707d4-6586-11e6-82b6-842a0c228917.gif)

**Comment by asturur** [comment]
did you set up bold on the font in firefox?

**Comment by minzojian** [comment]
![whathappen](https://cloud.githubusercontent.com/assets/361781/17804201/1620a9a4-662d-11e6-9b19-1081aca4af14.gif)
i found it is only happen when  the font has not been loaded yet,as you can see,when at the second time,i just click the run button to refreash,because that font has been loaded,fabric then rendered ok

**Comment by neopheus** [comment]
it's a font load problem

Try this : http://jsfiddle.net/o4mu5b6k/8/

**Comment by neopheus** [comment]
A new code : http://jsfiddle.net/o4mu5b6k/10/

Font load + update dynamic of textbox width

**Comment by asturur** [comment]
i m happy is not a bug. check fontfaceobserver. is easy to use and let you call the font on load complete.
