### ISSUE TITLE
Different behaviour for .set("angle", angle) and .setAngle(angle)

### ISSUE THREAD

**Issue by Fidel90** [kangax/fabric.js#3172]
## Version

1.6.3
## Test Case

https://jsfiddle.net/Fidel90/ewgtouye/4/
## Steps to reproduce

Select the triangle. Rotate.
## Expected Behavior

The inner, red filled path should rotate the same as the border path does.
## Actual Behavior

The red path shows weird rotating behaviour.
## How to solve

```
border.on("rotating", function () {
    //works well
    fill.setAngle(this.angle).setCoords();

    //works not so well
    //fill.set({angle:this.angle}).setCoords();
});
```

**Comment by neopheus** [comment]
https://jsfiddle.net/ewgtouye/1/

`fill.setAngle(this.angle).setCoords();`

is equal at :

```
  fill._setOriginToCenter();
  fill.set({angle: this.angle}).setCoords();
  fill._resetOrigin();
```

**Comment by Fidel90** [comment]
Hi neopheus and thanks for your reply.

So this is an expected behaviour? Honestly I thought that this stuff is handled in a private `._set()` function. It's often very convenient to set a bunch of properties via `.set({})` and I would not expect to call some extra private functions just because I'm setting an angle.

**Comment by asturur** [comment]
to me that internal setAngle does not make sense. i would like to remove it.

**Comment by Fidel90** [comment]
@asturur: Well, but if you remove `setAngle()` I would expect `set("angle", angle)` to show the same behaviour. I guess it's not meant to use `_setOriginToCenter()` and `_resetOrigin()` each time by hand? Or is there any usecase where this would be not needed?

**Comment by asturur** [comment]
i think that we should only set the property. i see no reason to set origin bycenter and then reset it.

**Comment by asturur** [comment]
totally unexpect behaviour for me, need to check if it is a path thing or every object.

**Comment by Fidel90** [comment]
@asturur: I made a fiddle with Rectangles, same behaviour: https://jsfiddle.net/32qr9koj/1/

**Comment by Fidel90** [comment]
Even when setting `centeredRotation` to `true` on both objects, doesn't help: https://jsfiddle.net/32qr9koj/2/

**Comment by neopheus** [comment]
It's with originX & originY like this : https://jsfiddle.net/32qr9koj/3/

**Comment by Fidel90** [comment]
Hmm...and what is `centeredRotation` for? It seems not to make any difference if set to true/false.

**Comment by awehring** [comment]
Stumbled about the same issue. 

`centeredRotation` influences only the center of rotation for mouse operations. There is a - somewhat lengthy - work around: http://jsfiddle.net/Kienz/5uR4U/

It was suggested here: #1093. I'm not sure, why it was closed.

**Comment by akash31** [comment]
hoe to set Rounded rectangle in fabricjs?

**Comment by Cartman34** [comment]
So, what is the solution for this issue ? I am getting some trouble setting angle with set() and getting an unexpected result...

**Comment by asturur** [comment]
the answer is not immediate.
i guess that setAngle should be renamed as setRotation and set('angle', angle) should continue to do what it does now.

I could remove this behaviour completely but i m scared of side effects.

**Comment by asturur** [comment]
those 2 rects are same but different origin

```
// remove currently selected object
canvas.remove(canvas.getActiveObject());

// add red rectangle
canvas.add(new fabric.Rect({
  width: 50,
  height: 50,
  left: 100,
  top: 100,
  fill: 'rgb(255,0,0)',
  angle: 45,
  originX: 'right',
  originY: 'bottom'
}));

// add red rectangle
canvas.add(new fabric.Rect({
  width: 50,
  height: 50,
  left: 100,
  top: 100,
  fill: 'rgb(255,0,0)',
  angle: 45
}));
```

and render like this:

![image](https://cloud.githubusercontent.com/assets/1194048/19830933/fe95cdaa-9dfe-11e6-9b2a-5e01d16c8280.png)

So i guess is better do not change this and rename the function to avoid confusion. Or remove it.

**Comment by asturur** [comment]
removed in fabric2 branch, with `rotate`. there was also an alias for it.
setAngle was really confusing also for me.
