### ISSUE TITLE
Object above currently active object could not be selected

### ISSUE THREAD

**Issue by vudduu** [kangax/fabric.js#3175]
Object above currently active object could not be selected on 1.6.3

Test:
https://jsfiddle.net/vudduu/ukez8j4w/2/

clone: #1188, #1204

**Comment by saadqbal** [comment]
try this: [https://jsfiddle.net/ecvctazk/48/](https://jsfiddle.net/ecvctazk/48/)

Solution by @neopheus

**Comment by neopheus** [comment]
https://github.com/kangax/fabric.js/pull/3178

**Comment by asturur** [comment]
Duplicate of #3095
