### ISSUE TITLE
[feature request] Knuth-Plass line breaking algorithm

### ISSUE THREAD

**Issue by belfz** [kangax/fabric.js#3176]
Hello,

I've been recently implementing  a serious text editor based on iText/Textbox components of fabric. While the line wrapping algorithm provided (I'm mostly referring `_wrapLine` method on `Textbox.prototype`) works very well, I know that more sophisticated algorithms exist, like a [Knuth-Plass line breaking](http://wiki.apache.org/xmlgraphics-fop/KnuthsModel), which is heavily used in TeX and Apache FOP. There was even an attempt to implement this algorithm in JavaScript - see [bramstein/typeset](https://github.com/bramstein/typeset) (it also supports canvas).

I was wondering whether the authors or supporters ever thought about introducing K/P algorithm to fabric? Were there any attempts?

If this is not a subject for possible near-future implementation, could you please give some directions on which parts of the code should I focus in order to "merge" the Knuth-Plass algorithm into fabric? I'm mostly concerned with the fact, that while the output of fabric's `_wrapLine` method is just an array of strings (representing the individual lines of text), the output of KP algorithm (bramstein's implementation) is much more detailed - it consists of objects representing lines, with nested objects representing either boxes, glues or penalties). The other part  of the "problem" is how to integrate that with internal fabric's fields, which hold the state of styles, selections and cursor positions.

**Comment by asturur** [comment]
i can help you in some way but i do not think it will find a place in the library.
