### ISSUE TITLE
Textbox with textAlign=center and styles to set some bold characters don't center correctly

### ISSUE THREAD

**Issue by Gulix** [kangax/fabric.js#3177]
## Version

1.6.2
## Test Case

Here's the JSON code used in the Kitchensink : 

```
{
  "objects":
  [
    {
      "type":"textbox",
      "left":0,"top":14,"width":400,
      "text":"Lorem ipsum dolo",
      "fontSize":40,"fontFamily":"helvetica",
      "textAlign":"center",
      "styles":
      {
        "0":
        {
          "6":{"fontWeight":"bold"},"7":{"fontWeight":"bold"},"8":{"fontWeight":"bold"},"9":{"fontWeight":"bold"},"10":{"fontWeight":"bold"}
        }
      }
    }
  ],
  "background":""
}
```
## Steps to reproduce

I clear the canvas in the kitchensink, paste the above JSON code in the designated area, and load the JSON. 
## Expected Behavior

The text shoul be displayed centered between 0 and 400.
## Actual Behavior

The text appears on the right, outside the box.

![capture 20160819-1405-43](https://cloud.githubusercontent.com/assets/9212910/17809320/120fe6b6-6616-11e6-8c47-14f9a649434f.png)

If I click on the item (edition mode), it changes to the good behaviour. But my application don't provide edition mode.

![capture 20160819-1408-36](https://cloud.githubusercontent.com/assets/9212910/17809382/779f77a8-6616-11e6-9dd4-7e4eda5a0380.png)

Also, if I remove the `styles` property of my JSON code, it's all good. Or if I set the `textAlign` property to `left`. `right` also acts weirdly.

**Comment by Gulix** [comment]
Anybody ever had this problem ? Or a way to pass through it ?

**Comment by asturur** [comment]
i cannot reproduce with current 1.6.6 and latest fixes.

**Comment by Gulix** [comment]
Will try it with current version in the week and keep you updated on it.

**Comment by Gulix** [comment]
I confirm that the issue is not reproduced in current version. Thanks !
