### ISSUE TITLE
Add "hasOwnProperty"

### ISSUE THREAD

**Issue by neopheus** [kangax/fabric.js#3182]
Do you think it would be wise to add "hasOwnProperty" (Possible iteration over unexpected (custom / inherited) members)

Replace for example :

```
    if (prop !== 'prototype') {
      fabric.Canvas[prop] = fabric.StaticCanvas[prop];
    }
```

by

```
    if (fabric.Canvas.hasOwnProperty(prop) && prop !== 'prototype') {
      fabric.Canvas[prop] = fabric.StaticCanvas[prop];
    }
```

**Comment by asturur** [comment]
What part of the code are you referring to?

**Comment by neopheus** [comment]
for example in canvas.class.js line 1466

**Comment by asturur** [comment]
i do not know why that cycle is there.
Whey canvas should need a special inheritance while rect over object does not?
