### ISSUE TITLE
text.class.js - Invalid number of arguments

### ISSUE THREAD

**Issue by neopheus** [kangax/fabric.js#3184]
Problem on text.class.js - Invalid number of arguments

Example : https://github.com/kangax/fabric.js/blob/master/src/shapes/text.class.js#L364

`this.height = this._getTextHeight(ctx);`

or

https://github.com/kangax/fabric.js/blob/master/src/shapes/text.class.js#L412
```
    /**
     * @private
     * @return {Number} Height of fabric.Text object
     */
    _getTextHeight: function() {
      return this._getHeightOfSingleLine() + (this._textLines.length - 1) * this._getHeightOfLine();
},
```
no arguments in the function but "ctx" in line 364

The same problem when use functions _renderChars, _getWidthOfWords, _getHeightOfLine, (in the same file)

**Comment by asturur** [comment]
text code is messy. some functions are shared between text itext and textbox. other overrides needs the argument

**Comment by neopheus** [comment]
I know
