### ISSUE TITLE
optionalDependencies

### ISSUE THREAD

**Issue by thecotne** [kangax/fabric.js#3187]
https://github.com/kangax/fabric.js/blob/master/package.json#L41
i am confused by optionalDependencies of this package are thous dependencies 
only for development?

if so can we remove optionalDependencies before publishing to npm and so package will be installed much faster

**Comment by asturur** [comment]
no optional depdencies are dependencies for node side. nodeCanvas mainly.

**Comment by thecotne** [comment]
installing fabric js with `time npm install fabric --no-optional` takes 1 second to complete
and installing with `time npm install fabric` takes 11-12 seconds 
but i can't specify in package.json that i don't need optionalDependencies of fabric js 
is there any solution for this? @asturur 

my npm install takes 2 minute and i really don't like it so i want to make it as fast as i can

**Comment by asturur** [comment]
we have nodecanvas as a dep. it takes a bit to install. no you cannot make anything that i m aware of to speed it up.
