### ISSUE TITLE
Support for React?

### ISSUE THREAD

**Issue by Kitanotori** [kangax/fabric.js#3192]
Are there any plans to support [React](https://github.com/facebook/react)? It seems that the architecture of Fabric goes against React model, so I'm a bit at lost on how to build a React app that relies heavily on Fabric.

**Comment by asturur** [comment]
No.
There is no reason to do that.
I m building an application that is react based and makes heavy use of fabricjs, after the initial tries to create components that should manage fabricjs object and canvas, we realized that there is no reason to do that.
We have a store for fabricjs state that we update on certain events and our component read from that store. Everything is ok.

**Comment by Kitanotori** [comment]
Is there any example anywhere on how to use React and Fabric.js without hassle regarding state and event management? Would you recommend to use e.g. Redux for managing Fabric.js state?

**Comment by DonovanCharpin** [comment]
Hi @Kitanotori, we use fabric with react too and everything work well 👍

**Comment by js7744** [comment]
@DonovanCharpin  can you give me sample or Demo how I use fabric.js with react ..

**Comment by rravithejareddy** [comment]
I also need a sample, rravithejareddy@gmail.com

**Comment by kprocks86** [comment]
@DonovanCharpin  can you provide me sample also 
email: laniyakrunal@gmai.com

**Comment by NgemilDulu** [comment]
Can you also send me a sample?
email: wiandonosaputro@gmail.com

**Comment by asturur** [comment]
In what kind of react support are you mostly interested?

**Comment by dalladirosa** [comment]
Do you know how to add image in fabric js with react?

**Comment by asturur** [comment]
To add an Image in fabricjs with react you use the same old code.
You probably to run a function after the component mounted in the `DidMount`.

What we can offer is an "official" way to start a canvas with fabricJS in react.
But not something like `<Canvas><Image /></Canvas>` it does not make much sense to me.

**Comment by dalladirosa** [comment]
I can adding image to canvas. When i add IText and image, every i change IText color the activeObject on Itext always gone so i have to click IText again it's very disturb. But when i didn't add the image, the activeObject is not gone, so i can change the color without click the IText again.
Do you know why? this is my code
![image](https://user-images.githubusercontent.com/29054050/54036957-7c4e3480-41ef-11e9-9465-f8df8d19921c.png)

**Comment by asturur** [comment]
you should not try to manage fabric canvas like this in react.

Managing react state and fabricJS state together is complicated. Can you describe your flow better?
