### ISSUE TITLE
Calling renderAll function at the end of moveTo

### ISSUE THREAD

**Issue by grandariel** [kangax/fabric.js#3193]
I believe that moveTo function should not call renderAll at the end as it unables usage of moveTo function in overridden _render function of fabricjs objects (it creates infinite loop and causes "maximum call stack size exceeded error").

**Comment by neopheus** [comment]
for this function  : https://github.com/kangax/fabric.js/blob/cf5f327f55d13921579e256bf9986a805914ff0d/src/static_canvas.class.js#L1550 ?

**Comment by asturur** [comment]
i think that fabricJS 2.0 will have a one flag only to say automaticRender true or false.
THe mouse interaction will have rendering automatically of course but all the other functions will be defaulted to false.
If this will not look good to me while implementing i think we should at least provide a _moveTo equivalent that does everything but not rendering.

**Comment by grandariel** [comment]
@neopheus Yes, exactly
@asturur I've seen people asking why renderAll isn't called automatically and others (like me) why renderAll in some cases is called automatically, so flag would be the best for both groups I think
