### ISSUE TITLE
Move Back/Forward doesn't work on kitchen sink

### ISSUE THREAD

**Issue by otterslide** [kangax/fabric.js#3194]
## Version
1.6.2

## Test Case
http://fabricjs.com/kitchensink

## Steps to reproduce
Overlap two objects and click 
Send backwards  
Send to back
Bring forwards  
Bring to front

## Expected Behavior
The object should move back/forward.

## Actual Behavior
Nothing happens.

Additionally, how do I prevent clicking on an object to trigger "Bring to Front" ? The older version I had would not bring to front automatically, but this one seems to do it as soon as the object is clicked.

**Comment by neopheus** [comment]
it's a same problem : https://github.com/kangax/fabric.js/pull/3178

**Comment by asturur** [comment]
it works fine.
You have to enable "preserveObjectStacking: true" if you want to see the effect before deselection.
