### ISSUE TITLE
Grouping not working correctly when canvas is zoomed

### ISSUE THREAD

**Issue by deepdoon** [kangax/fabric.js#3196]
## Version
1.6.3

## Test Case
[http://jsfiddle.net/Q3TMA/1118/](http://jsfiddle.net/Q3TMA/1118/)

## Steps to reproduce
1. Click on ZoomIn button. (canvas along with two text objects will be zoomed) 
2. Select both text objects. 
3. Click on group. (objects will form a group)

## Expected Behavior
Its should form a normal group with objects within the group and same location as of objects. 

## Actual Behavior
Group is formed but no longer selectable. If we click on character '2' of 2nd text object  the we can see the selection of group but the problem is objects are where they are expected but group is at different location. 

P.S It works fine when not zoomed In

**Comment by YannLeBihan** [comment]
Hi,

First of all, congratulations for such a great project as Fabric !

I am facing the exact same problem as deepdoon and will just add following observation, based on his jsfiddle :

1. zoom out
2. select one object
3. shift-select the second object
4. try to resize the group without clicking the "Group" button : although the handles are visible, they can't be manipulated.

This doesn't happen when selecting the objects with a single drag. Only when adding them one by one.

**Comment by asturur** [comment]
i solved something like that recently. are you linked on 1.6.3 or current master?

**Comment by YannLeBihan** [comment]
Thanks, I just tested with both on my project and you're right : with current master, handles behave correctly in the case I describe.

However, the problem described by deepdoon remains : when created by code at a zoom factor different from 1, groups seem to get a wrong bounding rect - even after applying setCoords(). This doesn't happen for single objects, just code-created groups.

**Comment by asturur** [comment]
i think we have a similar ticket for this. i ll see.

**Comment by asturur** [comment]
Would you be so kind to update the fiddle on the latest master?

**Comment by deepdoon** [comment]
Hi @asturur  any luck solving this issue?

**Comment by asturur** [comment]
not yet.

**Comment by deepdoon** [comment]
Hi @asturur is this issue resolved?

**Comment by asturur** [comment]
not yet.

2016-09-17 12:46 GMT+02:00 Deepak Dhiman <notifications@github.com>:

**Comment by deepdoon** [comment]
Can we add this to a milestone atleast? @asturur

**Comment by asturur** [comment]
guys i m really overloaded.
i ll try.to look at it, i see is a nasty bug

**Comment by asturur** [comment]
found the root cause of this thing. full resolution needs a revamp of coordinate system, but we can put a patch now to fix it.

**Comment by vishwajeets7** [comment]
With this update, facing an error - "RangeError: Maximum call stack size exceeded" when the object is cloned using....fabric.util.object.clone()
