### ISSUE TITLE
Crop Image using the clone of same image(with opacity:0.5) on the top of image 

### ISSUE THREAD

**Issue by by12** [kangax/fabric.js#3198]
I am trying to crop the image using the clone of same image on the top of the original image by setting opacity of 0.5. I set the fixed height and width of the image to crop and lock scaling and moving events. I overwrite the _render method for image object. So add the clipping parameter to draw image.  

 elementToDraw && ctx.drawImage(elementToDraw,
                                            this.cx,
                                            this.cy,
                                            this.cw,
                                            this.ch,
                                           x + imageMargins.marginX,
                                           y + imageMargins.marginY,
                                           imageMargins.width,
                                           imageMargins.height
                                          );

Now i am able to scale and move the clone object and calculating the cx,cy,cw,ch.  Everything is working fine until object have no angle. 
Question is How to calculate the cx,cy when image have an angle set.

**Comment by neopheus** [comment]
jsfiddle that demonstrate the problem.

**Comment by by12** [comment]
I have made a quick fiddle. i hope it will demostrate the problem. 

1- first start cropping with out seting the angle and see results by scaling and moving the object.
2. then remove the clone image and set the angle and again active the crop mode. when i scale it or move then i have wrong clipping info.

https://jsfiddle.net/MirzaG/qunh3har/

**Comment by asturur** [comment]
guys for those kinds of things you have to post on stackoverflow
