### ISSUE TITLE
Move all objects when dragging one reaching an edge

### ISSUE THREAD

**Issue by henryhu712** [kangax/fabric.js#3199]
I want the feature: dragging an object, reaching an edge and keep going, then all objects moving in the opposite direction. The effect is like that I am dragging an object and trying to find a proper place to drop it down on a map.

Is there any fabric plugin to implement it?

**Comment by neopheus** [comment]
like this : https://codepen.io/janih/pen/EjaNXP ?

**Comment by asturur** [comment]
if you mean automatic acroll on edge of canvas there is not something like
that.
