### ISSUE TITLE
Selection Context problem

### ISSUE THREAD

**Issue by wajipk** [kangax/fabric.js#3200]
## Version
1.6.2

I am building a very big application that's why i can't make fiddle.
**The problem is** I am adding 2 SVGs then making a connector between them and after connecting them the selection (blue rectangle of Upper Canvas) is not showing.

Steps:
- Add SVGs as normal
- Disabling selection on canvas and objects  
```
canvas.selection = false;  
canvas.forEachObject(function(element) {
        element.selectable = false;
});
```
- add connector with property `object.selectable = false;`
- Enabling selection on canvas and objects (Only SVGs) 
```
canvas.selection = true;  
canvas.forEachObject(function(element) {
        element.selectable = (element.class=='connector' ? false : true);
});
```

And after these step the rectangle on upper canvas isn't shown while dragging.

@kangax @asturur Can you help me in this.

**Comment by neopheus** [comment]
jsfiddle that demonstrate the problem.
