### ISSUE TITLE
Firefox Animation leads to Melting/Juddering (esp. with Text) after opening Dev Tools

### ISSUE THREAD

**Issue by SebastianKG** [kangax/fabric.js#3201]
## Version
1.6.3

## Test Case
http://jsfiddle.net/re1o7xrv/1/

### For overall animation problems:

- Animate any shape using the .animate() function
- Pop open Dev Tools (F12)
- compare Firefox and Chrome, and notice that Firefox performance is much less smooth. Especially noticeable with fabric.Text shapes.
- Keep popping open Dev Tools to see more and more pronounced effects

### For our specific issue:

It's difficult to reproduce our bug without running the full game, which is currently in production. We could privately share a link to the running game if you would be willing to look at the bug.

If you had access to the game:

- Sign in with a custom username (this causes text to be displayed)
- Pop open the dev tools
- Most of the time, this will result in the whole world dissolving into artifacting on Firefox (see http://imgur.com/iDvI9t0)

Since this happens with the dev tools popping open, it may be relevant that we resize in this fashion:

```
function scaleCanvas(canvas) {
    canvas.setHeight(window.innerHeight);
    canvas.setWidth(window.innerWidth);
    canvas.renderAll();
}
```

...however, F11 (fullscreen) spam does _not_ cause any problems, so resizing alone may not be the culprit.

## Expected Behavior
In Chrome:

- Fiddle runs smoothly even after opening and closing dev tools a lot
- GIF of our full game working correctly: http://imgur.com/xTZdxI6

## Actual Behavior
On Firefox:

- Fiddle judders and does not animate correctly after opening and closing dev tools
- GIF of our full game melting and becoming unusable: http://imgur.com/iDvI9t0

**Comment by asturur** [comment]
i do not think i can help much if firefox has some problem.
Opening the console is not something someone should do while playing.
And firefox is going down with canvas performances i do not know why.
If you want to share a link to help i can try, but i cannot keep as an issue here.
(did you check that firefox performance monitor is not ON and querying the dom with lot of stuff?)
