### ISSUE TITLE
[Documentation] .clone() is same for fabric.Object and fabric.Path

### ISSUE THREAD

**Issue by Fidel90** [kangax/fabric.js#3203]
I think I stumbled over a copy&paste error in the documentation.  As I've read [here](http://stackoverflow.com/a/18267515/2577116) when cloning an object it's important to know if it's an `async` object or not. So the use of the `clone` function must be different between regular objects (rect, circle, etc.) and paths for example. Anyway the documentation for both `clone` function is the same:

http://fabricjs.com/docs/fabric.Object.html#clone
http://fabricjs.com/docs/fabric.Path.html#clone

When cloning a simple Rect this won't be true for the `Object.clone` documentation:

> Callback is invoked with a clone as a first argument

On the other hand when cloning a path this wont be true in for the documentation of the `Path.clone` function:

> Returns:
> clone of an instance

So IMO both are partly right and wrong.

**Comment by asturur** [comment]
clone is in a bad state IMO.
I need to find time to release 1.6.4 that has lot of small changes.
I ll try to bump to 1.7.0 making all clone with callback ( and returning the element if sync) at least we have one way to clone them all.

**Comment by Fidel90** [comment]
Kind of the same issue: https://github.com/kangax/fabric.js/issues/2010
