### ISSUE TITLE
Bug: toDataURL with enableRetinaScaling = false and multiplier = 1 has incorrect canvas zoom

### ISSUE THREAD

**Issue by Arencia** [kangax/fabric.js#3206]
## Version
1.6.3

## Test Case
https://jsfiddle.net/15488qdn/ (version with bug)
https://jsfiddle.net/0cpqx8vo/ (fixed version)

## Steps to reproduce
Click the button below the canvas to generate the image dataURL.

The first fiddle is what's wrong, the second is a fixed version.
When calling toDataURL on the canvas with enableRetinaScaling = false and multiplier = 1 the image doesn't have the correct size.

To fix this I added an extra function named __toDataURLNoMultiplier (see below) and changed
```
if (multiplier !== 1) {
  return this.__toDataURLWithMultiplier(format, quality, cropping, multiplier);
}
else {
  return this.__toDataURL(format, quality, cropping);
}
```
to
```
if (multiplier !== 1) {
  return this.__toDataURLWithMultiplier(format, quality, cropping, multiplier);
}
else {
  return this.__toDataURLNoMultiplier(format, quality, cropping);
}
```

I'm not sure if this is the correct way but it fixes the issue for me.

```
__toDataURLNoMultiplier: function(format, quality, cropping) {
    var zoom = this.getZoom(),
        newZoom = zoom / fabric.devicePixelRatio;

    this.setZoom(newZoom);

    var data = this.__toDataURL(format, quality, cropping);

    this.setZoom(zoom);

    return data;
  }
```

**Comment by neopheus** [comment]
i don't have bug with : https://jsfiddle.net/15488qdn/ 
on Chrome (MacOsX - version 52)

**Comment by Arencia** [comment]
Forgot to mention this but the problem only happens on devices with retina display. I tested it on a macbook pro. Not sure if you tested it with retina display?

**Comment by asturur** [comment]
https://jsfiddle.net/15488qdn/2/
The problem is that you have to set retinascaling on canvas start.
If you do not do that the canvas is retina scaled ad will export like that.
If you want to export just without retina scaling, use a multiplier that is 1/devicepixelRatio.

I think also recently an option has been added:
https://github.com/kangax/fabric.js/pull/3147/files

that works when exporting single obkjects: https://jsfiddle.net/15488qdn/4/

**Comment by Arencia** [comment]
Thanks for clarifying this. It indeed solves my issue.

> If you want to export just without retina scaling, use a multiplier that is 1/devicepixelRatio.

This does not work if the multiplier is `1 / fabric.devicePixelRatio`. (https://jsfiddle.net/15488qdn/5/ - Make sure to test it on a device with retina display)
It works for every other value except for 1. The result is the same as the first fiddle in my original post.
However, it does work on the second fiddle where the zoom is changed before `__toDataURL` is called. (https://jsfiddle.net/0cpqx8vo/1)

I don't need it myself, just setting `enableRetinaScaling = false` is enough for me. But other people might need this so maybe it's worth investigating?

**Comment by evolutionjay** [comment]
@asturur  `1/devicepixelRatio` not work. Plz try on retina screen

**Comment by asturur** [comment]
i ll do, no worries. i m a bit busy
