### ISSUE TITLE
Node js custom font rendering after 1.6.0-rc.1 - jsdom - canvas 

### ISSUE THREAD

**Issue by Godweed** [kangax/fabric.js#3208]
Hello I have a problem with custom font rendering after upgrade
When I am using with node 0.12. with the following versions
fabric@1.6.0-rc.1 node_modules/fabric
├── canvas@1.1.6 (nan@1.2.0)
└── jsdom@1.1.0 (contextify@0.1.15)
custom fonts rendered successfully node.js

but when I updated to node 4. or 5. or 6. with below config
/var/www/node_fabric
└─┬ fabric@1.6.3 
  ├── canvas@1.4.0 
  └── jsdom@3.1.2 
custom fonts begins to rendered with small font size with default font. I look a search in node-canvas also and could not figure out.

**Comment by asturur** [comment]
All custom fonts? what names have this custom fonts?

**Comment by Godweed** [comment]
Hi @asturur 
All of them; there are several custom fonts serving through my application. If it is a system installed font it works as expected. But when I made update it doesn't seem to work anymore.There is default font rendered with small size.  Also canvas.toDataURL creates empty png in case of upgrade. I tried with different versions node 4, 5 and 6 could not able to fix issue. But when in I downgrade to node 0.12 and fabric@1.6.0-rc.1 
├── canvas@1.1.6 (nan@1.2.0)
└── jsdom@1.1.0 (contextify@0.1.15)
to these versions it begins to operate correctly again. I guess this is related with versions conflict with node-canvas could not able to figure out.

**Comment by asturur** [comment]
are you able to provide me a js file to run under node that reproduces the bug? thanks.

**Comment by Godweed** [comment]
if (canvas.getObjects("i-text").length != 0) {       
    var array = canvas.getObjects("i-text");

    async.each(array, function(item,  callback) {     
            
     var fontfamily = item.get('fontFamily'); 
    
     fontfamily = fontfamily.split(",")[0];
   
    if ( doesFontExist(fontfamily)){

     http.get("http://www.bayk.us/api/fonts/"+fontfamily, function(res) {
       var body = '';         
         res.on('data', function(chunk) {
             body += chunk;
         });
         res.on('end', function() {
           var spResponse = JSON.parse(body);
           var title = spResponse.title;       
           var font = new canvaso.Font(title,"/var/blala/kustomz/public" + spResponse.spree_font_attachments[0].font_face_url); 
           if (spResponse.spree_font_attachments.length > 1) {
           spResponse.spree_font_attachments.forEach(function(item,index) {
             if (index > 0) {                    
              font.addFace('/var/www/blala/public' + spResponse.spree_font_attachments[index].font_face_url, spResponse.spree_font_attachments[index].font_face_styles.forEach(function(item) {item}));
              
              if (index == spResponse.spree_font_attachments.length-1){
                canvaso.contextContainer.addFont(font);  // when using createPNGStream or createJPEGStream
                canvaso.contextTop.addFont(font); 
                callback(); 
              } 
             }
                       
           });
          }else{
            canvaso.contextContainer.addFont(font);  // when using createPNGStream or createJPEGStream
            canvaso.contextTop.addFont(font); 
            callback(); 
          }     
         });              
     }).on('error', function(e) {
       console.log("Got error: " + e.message);
     });          
    }else{
      callback();
    }
  }, function(err) {
      if (err) return next(err);
      done();
  });
}else{
  done();
}   
}
