### ISSUE TITLE
Different behavior creating a group in the mouse:down event if the polygon is selected

### ISSUE THREAD

**Issue by DonovanCharpin** [kangax/fabric.js#3209]
## Version
1.6.3

## Test Case
This test case create a group on the mouse:down event. I ungroup it on the mouse:up event restoring the state of each object. The group behavior is not the same if I select the text or the polygon to start moving the group.

https://jsfiddle.net/avpk81rt/2/

## Steps to reproduce
Move the square selecting the text : everything should be fine
Move the square selecting the polygon : it seems the polygon move twice as far as the text

## Expected Behavior
When I move the group selecting the polygon, the text and the polygon should stay in their position within the group

## Actual Behavior
The polygon coordinates are wrong when moving the group if I select the polygon

**Comment by asturur** [comment]
i suspect is something with the code you wrote. What stops you from creating normal groups and move them on the normal way without specifing top and left during mouse move?

**Comment by DonovanCharpin** [comment]
My real use case is much more complicated that the js fiddle I provided. 

I have a lot of objects in this polygon that need to be selected alone but when I move the polygon, I need that all objects within the polygon move together.

Is there another way to do it? I already tried catching subtarget through a group but I can't do what I want. Instead, the trick was to keep all my single object and group them only when I needed. All objects are moving with the polygon (images, text, rect, circle), only the polygon doesn't move with the group.

**Comment by asturur** [comment]
i think polygon is getting moved from classic drag operation and your mouse move. can you try setting lockMovementX and lockMovementY for the polygon and see if it moves?

is a such weird case i canno consider a bug

**Comment by DonovanCharpin** [comment]
Oh yeah thanks it works!

I agree it's a weird case but it can happen if you have like an artboard like photoshop with objects inside and you want to move all the artboard. It's easier to group them while moving the artboard instead of update the position of all object.
