### ISSUE TITLE
While I am changing the Font-family text container not adjusting by itself.  

### ISSUE THREAD

**Issue by atul-vt** [kangax/fabric.js#3214]
On 'Add text' button Click below function adding text over canvas - 
=================================================
jQuery('.addtext').click(function () {

	jQuery('.text_canvas-shape-size-container').css('display','block');

	previewPhotoCanvas(function(){
		var iText = new fabric.IText('Double click to edit text', {
			left: 70,
			top: 140,
			fontFamily: 'Hoefler Text',
			fontSize: 20,
			// fill: '#ff0000',

			//padding: 7,

		});

		canvas.add(iText);
		iText.center();
		iText.setCoords();
		if(for_color!="" && for_color!=undefined){
			iText.fill=for_color;
		}
	canvas.setActiveObject(iText);
	return;
  });
  
 }); 

Its working fine. Ref. One.png
![one](https://cloud.githubusercontent.com/assets/21309979/18051637/649ca496-6e13-11e6-9a2f-785ef3a3e10c.png)

=================================================

While we are changing the font-family then container not adjusting to new font-family size. here is code that I am using once user select font-family from dropdown- 
=================================
function setFont(font){
	var activeObject = canvas.getActiveObject();
	if (activeObject ) {
		activeObject.fontFamily = font;
		setTimeout(function(){
			canvas.renderAll();
		},1000);
		canvas.renderAll();
		jQuery('.dropdown-menu').slideToggle('200');
	} else {
		alert("Please click the text area first");
		jQuery('.dropdown-menu').slideToggle('200');
	}
}

Its not behaving right. Ref. -two.png
![two](https://cloud.githubusercontent.com/assets/21309979/18051557/f14759a0-6e12-11e6-8254-18fbb98e0a31.png)

=================================
please help me to sort it out. 

   

## Version
1.6.2

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by asturur** [comment]
it looks like your font is not properly loaded when rendering. ensure font finished loading

**Comment by atul-vt** [comment]
Hi Asturur,  how to ensure font loaded properly because in second image you can see font-family applied, n this is done through **function setFont(font)**  . Can you plz look in to this and let me know what I m missing in this function.

**Comment by asturur** [comment]
check fontfaceobserver on github. easy to use, does the job.

**Comment by atul-vt** [comment]
no, its not working for me.

**Comment by j0hn** [comment]
I've experienced this same issue with custom fonts. I believe what's happening is that you get a "ghost" or transparent text to edit, and another text is drawn on the background of it. The transparent font is not being drawn with the propper font so it has a different character width.

You can experience this on [kitchensink](http://fabricjs.com/kitchensink) by changing the font family to Engagement. When you try to edit the text, you'll notice a difference between the position of the character that you're editing and the one that you're actually being drawn on the screen.

I've done a test myself and the width of the container is the same when you do not draw a font and when you do.

Without font: 

![screenshot from 2016-09-21 12-18-09](https://cloud.githubusercontent.com/assets/172606/18717356/04733fa4-7ff6-11e6-92c4-d2f28e57faa2.png)

Without font and with one character selected:

![screenshot from 2016-09-21 12-17-54](https://cloud.githubusercontent.com/assets/172606/18717357/0478096c-7ff6-11e6-94be-493ca933f9df.png)

With Font

![screenshot from 2016-09-21 12-16-43](https://cloud.githubusercontent.com/assets/172606/18717354/0470da70-7ff6-11e6-8a4f-cf791ebaa43a.png)

With font and first character selected:

![screenshot from 2016-09-21 12-16-57](https://cloud.githubusercontent.com/assets/172606/18717355/04724856-7ff6-11e6-9994-f0e1cb301a31.png)
