### ISSUE TITLE
Update DEPENDENCIES

### ISSUE THREAD

**Issue by neopheus** [kangax/fabric.js#3215]
Hi :)

Do you think it would be a good idea to update all dependencies ? 
https://david-dm.org/kangax/fabric.js?type=dev
and 
https://david-dm.org/kangax/fabric.js?type=optional

Thk

**Comment by asturur** [comment]
jsdom we can t update for now. the other.ones we have to try.
for jscs 3.x we have to fix something in the code. have a shot updating jscs and uglifyjs and see what 's happen to tests.

**Comment by kangax** [comment]
Need to switch from JSCS to ESLint

**Comment by neopheus** [comment]
what is the problem for jsdom ?

**Comment by asturur** [comment]
removal of node before 4. thing we are not doing now.
Juriy i m using eslint now, i think i can switch easily. do you know name
of profile we are using now in fabricjs?

**Comment by asturur** [comment]
uglify updated, jscs and jshint removed in favor of eslint.
