### ISSUE TITLE
Changing brush width in free drawing mode results in weird bounding boxes

### ISSUE THREAD

**Issue by Fidel90** [kangax/fabric.js#3220]
## Version
1.6.4

## Test Case
https://jsfiddle.net/Fidel90/7kmf3jz2/2/

## Steps to reproduce

1. draw something with default values
2. change brush size to something bigger
3. draw something
4. change brush size to something smaller
5. draw something
6. repeat 2. to 5. to get different results
7. exit drawing mode
8. move the objects you have drawn

## Expected Behavior
Objects will have correct bounding boxes and can be moved when clicked inside them.

## Actual Behavior
Bounding boxes are sometimes either too big or too small.

## Screenshot
![jsfiddle](https://cloud.githubusercontent.com/assets/12855941/18159089/580eb654-7027-11e6-8b3b-a8d693da18be.PNG)

**Comment by Fidel90** [comment]
Well, I found that I have to `parseInt` the value from the `input` element before applying it to the `freeDrawingBrush.width`:

`canvas.freeDrawingBrush.width = parseInt(this.value, 10);`

Somehow applying a `String` works for painting, but the bounding boxes are not working with this.

**Comment by asturur** [comment]
does docs says number or do not specify?

**Comment by Fidel90** [comment]
Number. I just forgot that inputs return their values as strings -.-
