### ISSUE TITLE
[Feature] Customize color of controls when object is modified

### ISSUE THREAD

**Issue by Fidel90** [kangax/fabric.js#3222]
Looking into this [demo](http://fabricjs.com/controls-customization) I was wondering if it could be possible to customize the color of the control points while the object is modified. You can change the color for the controls (via `cornerColor`) but when you start moving/scaling/whatever the set color changes to something lighter. I would like to have an adittional property where I can set the color that should be used while the object is modified.

Same should be true `borderColor`:

```
var rect = new fabric.Rect({
    transparentCorners: false,
    cornerColor: "red",
    borderColor: "rgba(123, 234, 0, .5)",
    cornerColorOnModify: "#000",
    borderColorOnModify: "#fa30b1"
  });
```

**Comment by asturur** [comment]
we have too many flags for controls. i ll update that demo so that i add also the new ones from 1.6.2 i would add color and border for the active corner. the effect you want can be achieved using onscaling, onrotate, onmoving

**Comment by Fidel90** [comment]
Thanks, I think I'm gonna stick with `borderOpacityWhenMoving`. That'll do for now :)
