### ISSUE TITLE
Is there a way to make cloud shapes?

### ISSUE THREAD

**Issue by ssaras** [kangax/fabric.js#3223]
I'm trying to get something like the cloud at the top right of [this image.](https://carolhagen.files.wordpress.com/2014/08/bluebeam-line-styles.jpg)

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
