### ISSUE TITLE
why repeat pattern has a little gap? meanwhile,fixed a bug about pathgroup parseDimensionsFromPaths

### ISSUE THREAD

**Issue by minzojian** [kangax/fabric.js#3224]
![image](https://cloud.githubusercontent.com/assets/361781/18197798/c039e8f2-712b-11e6-87a1-6a658f7eefa6.png)

i expand fabric and add a new feature to support load svg file as background,also fixed a bug about pathGroup dimensions calculation
check the comments in this jsfiddle
http://jsfiddle.net/o4mu5b6k/15/
i load that svg file and render it into a canvas,and use that canvas as the pattern's source.
however,**there always has a little gap between each tile**,but when i export the canvas into a svg file,that gap dispear,ofcourse,what i did in svg exporting is differen with what i did when render background in canvas, no longer use canvas as pattern,but place the paths into svg pattern tag.

**Comment by asturur** [comment]
Hello, can you please explain more clearly the big you found and how you prpose to solve it?

**Comment by minzojian** [comment]
well,i try to use a svg as pattern,
i load it as pathgroup at first,then render that pathground into a canvas,
later,i use that canvas as the pattern's source
however,as you can see in that snapshot,the edge of that tile,has a one pixel gap,i want a seamless pattern
