### ISSUE TITLE
[Feature] Alternative free drawing mode

### ISSUE THREAD

**Issue by Fidel90** [kangax/fabric.js#3225]
As far as I know current drawing mode creates a path from whatever you were drawing as soon as you release the mouse. This path, that was originally drawed on the upperCanvasEl is now added to the canvas itself and the topCanvas is cleared. This happens for every line you draw.

As a result you end up with a lot of objects when you decide to leave drawing mode. Even worse in my opinion, when drawing with semi-transparency all those objects are visibly drawn over each other, adding up transparency. This can be solved with the `globalCompositeOperation` set to `xor` but this would also affect other objects on the canvas.

My idea would be a drawing mode where, when drawing, the data is kept on the `topCanvas`. It only is transformed to an object on the canvas itself when you leave drawing mode, **not** on `mouseup`. This object may be a group of paths or an image (grouping and converting to `dataURL`). It should then also be possible to draw semi-transparent as on the `topCanvas` no other objects would interact with a custom `globalCompositeOperation` like `xor`.

I don't know how big the impact would be neither if anyone else would be interested in it. I see it as a possibly great feature as it mimics the behaviour of every graphic editor I know of (see drawing of masks in PS Lightroom, CaptureOne, etc.).

PS: I already addressed the issue with semi-transparency in free drawing mode [here](http://stackoverflow.com/questions/38764235/fabricjs-canvas-blend-mode-in-free-drawing-mode) but as you can see, at the moment it's only possible to change the `globalCompositeOperation` of each created path and only after the mouse has been released (so while drawing transparency still adds up).

**Comment by asturur** [comment]
well, there are a couple of things here.
first of all we should have an event for every kind of free drawing, i do not know if now for any class of brush we fire path:created.
in that case grouping all the path on one single group is something easy and doable at application level.
for the global composite operation i agree we need to be able to handle it at group level and not at global canvas level. this needs to be addressed at library level

**Comment by Fidel90** [comment]
Currently messing around a bit with source code, just for imagination:
https://jsfiddle.net/Fidel90/rd1q27e4/4/

What you can already see in the fiddle is what it should look like _while_ drawing (well, path rendering is a bit weird but that's gonna be fixed easy I guess). What's missing for now is the image/group creation when switching mode (how to recognize this?). If someone with deeper knowledge can improve this (espacially rendering and whatever else I've messed up), I'll be glad about it :)

**Comment by Fidel90** [comment]
Why is this closed?

**Comment by asturur** [comment]
There is no space for a freedrawing feature as of now. 
Other than that XOR method works good only with 0.5 transparency, all other settings produce unwanted result.
