### ISSUE TITLE
Node js svg pattern loading problem

### ISSUE THREAD

**Issue by Godweed** [kangax/fabric.js#3226]
When I am adding a svg file as dynamic pattern in client side ( upload it with  fabric.Image.fromURL)  it is working correctly and rendered in web browser. But When I tried to recreate the canvas in with node js  if the uploaded file is svg it is not rendered. 
I am getting object as empty width height etc. If I use a png with file fabric.Image.fromURL it works in both client and server side. But in case of svg file it only works in client.

{ filters: [],
  resizeFilters: [],
  _element: [Image],
  _originalElement: [Image],
  width: 0,
  height: 0,
  originalState: 
   { top: 0,
     left: 0,
     width: 0,
     height: 0,
     scaleX: 1,
     scaleY: 1,
     flipX: false,
     flipY: false,
     originX: 'left',
     originY: 'top',
     transformMatrix: null,
     stroke: null,
     strokeWidth: 0,
     strokeDashArray: null,
     strokeLineCap: 'butt',
     strokeLineJoin: 'miter',
     strokeMiterLimit: 10,
     angle: 0,
     opacity: 1,
     fill: 'rgb(0,0,0)',
     fillRule: 'nonzero',
     globalCompositeOperation: 'source-over',
     shadow: null,
     clipTo: null,
     visible: true,
     backgroundColor: '',
     alignX: 'none',
     alignY: 'none',
     meetOrSlice: 'meet',
     skewX: 0,
     skewY: 0 },
  canvas: 
   { _objects: [ [Circular] ],
     lowerCanvasEl: [Canvas 0x0],
     contextContainer: { canvas: [Canvas 0x0], _imageSmoothing: true },
     width: 0,
     height: 0,
     viewportTransform: [ 1, 0, 0, 1, 0, 0 ],
     _offset: { left: 0, top: 0 } },
  oCoords: 
   { tl: { x: 0, y: 0, corner: [Object] },
     tr: { x: 0, y: 0, corner: [Object] },
     br: { x: 0, y: 0, corner: [Object] },
     bl: { x: 0, y: 0, corner: [Object] },
     ml: { x: 0, y: 0, corner: [Object] },
     mt: { x: 0, y: 0, corner: [Object] },
     mr: { x: 0, y: 0, corner: [Object] },
     mb: { x: 0, y: 0, corner: [Object] },
     mtr: { x: 0, y: -40, corner: [Object] } } }

**Comment by asturur** [comment]
i will reopen if you can post SVG file
