### ISSUE TITLE
I load a large image (> 2 megapixels) on iOS, the image get's distorted when I scale it. 

### ISSUE THREAD

**Issue by LemonStudioZeus** [kangax/fabric.js#3228]
hen I load a large image (> 2 megapixels) on iOS, the image get's distorted when I scale it. There are two fixes out there but I couldn't get them to work because they are not compatible with the way fabric.js handles the canvas element.

Please take a look at the fixes that work for regular (non fabric.js) canvas:

HTML5 Canvas drawImage ratio bug iOS

https://github.com/stomita/ios-imagefile-megapixel

Maybe one of you guys can point me in the right direction how to modify the fix so that it works with fabric.js canvas.

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
