### ISSUE TITLE
Error when trying to remove filter

### ISSUE THREAD

**Issue by virror** [kangax/fabric.js#3231]
## Version
1.6.4

## Steps to reproduce
Create a filter and apply it, try to remove it by then setting it to null.

## Expected Behavior
Filter should be removed.

## Actual Behavior
Error in fabric apply filter function.

This did work in 1.6.3 but not in the latest version.
What are the recommended way of removing a filter at a specified position?

**Comment by asturur** [comment]
setting to null should work.
![image](https://cloud.githubusercontent.com/assets/1194048/18250831/d260ce04-7385-11e6-9f42-57ee9f76a358.png)

If filter is `null`, should not pass the && and the applyTo should not be called.
What kind of error ar you getting?

**Comment by virror** [comment]
The problem is the else case above, if filter is null there things gets ugly.
Solved the issue by using splice instead, but i thought it might be good to fix for compatibility.

**Comment by asturur** [comment]
can you set up a fiddle case?
i do not understand the problem

**Comment by virror** [comment]
: )

**Comment by asturur** [comment]
i fixed this an rebuilt dist on the master branch.
Can you give a look with your setup?

**Comment by virror** [comment]
Cant do that atm, but looked at the changes and it looks sane to me.
I will report back if i find any issues, so silence = ok : )
