### ISSUE TITLE
Node js svg pattern toDataURLwith multiplier

### ISSUE THREAD

**Issue by Godweed** [kangax/fabric.js#3234]
I don't know if this is feature request or bug but;

After creating canvas in server side with node js, exporting  canvas to dataurl with multiplier works as expected. But when an object has a pattern object which is svg a file. The Quality of the pattern looks poor, svg objects scaled without problem but if object's pattern is svg. Pattern quality looks poor. Also if pattern object is image using resizeFilters works and I am able to create bigger canvas without any quality loss. 

the below image is created by todataurl multiplier 7; there is 2 elements in canvas. One is i-text and the other is bob marley svg whichs has a pattern of svg object. Bob marley and text objects scaled without quality loss but pattern have a poor quality. 

![36](https://cloud.githubusercontent.com/assets/260298/18271123/3ace4350-7439-11e6-9f97-489edd1aa4ca.png)

**Comment by asturur** [comment]
to investigate this i need a js file i can run in node to prpduce the output. can you make it?

**Comment by Godweed** [comment]
@asturur I tried to simplify the code hope this helps. 

var canvas = fabric.createCanvasForNode(2500, 2500);
var data = {"objects":[{"type":"path-group","originX":"left","originY":"top","left":216.83,"top":153.82,"width":315.49,"height":286.84,"fill":"","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":0.35,"scaleY":0.35,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"backgroundURL":"/uploads/spree/design/icon/620/om-zentangle.svg","scaleXWB":36,"repeatB":"repeat","paths":"http://www.bayk.us/uploads/spree/design/icon/331/Bob_Marley.svg","sourcePath":"http://www.bayk.us/uploads/spree/design/icon/331/Bob_Marley.svg"}],"background":"","overlayImage":{"type":"image","originX":"center","originY":"center","left":270,"top":200,"width":318,"height":448,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"src":"http://www.bayk.us/spree/editor_product_attachment/file/22/t-shirt_sablon.png","filters":[],"resizeFilters":[],"crossOrigin":"","alignX":"none","alignY":"none","meetOrSlice":"meet"}};


canvas.loadFromDatalessJSON(data, function() { 
   canvas.setOverlayImage(null, canvas.renderAll.bind(canvas));
   canvas.forEachObject(function(item){
	 fabric.loadSVGFromURL('http://www.bayk.us'+item.backgroundURL, function(ob,op){

	    var img =  new fabric.PathGroup(ob, op);   
  		if( item.scaleXWB != null){
		  img.scaleToWidth(item.scaleXWB*2);
  		}
  		if( item.angleB != null){
  		   img.setAngle(item.angleB);
  		}
  		if( item.paddingB != null){
  		   padding = item.paddingB;
  		}

      var patternSourceCanvas = new fabric.StaticCanvas();
  	patternSourceCanvas.add(img);

  	var pattern = new fabric.Pattern({
  	  source: function() {
  	 	 patternSourceCanvas.setDimensions({
  	 		 	   width: img.getWidth()+ padding,
  	 			   height: img.getHeight()+ padding
  	 	      });
  	 	      return patternSourceCanvas.getElement();
  	 	   },
  	  	     repeat: item.repeatB || 'repeat'
  
  	     });

   		if( item.offsetXB != null){
   		   pattern.offsetX = item.offsetXB;
   		}
   		if( item.offsetYB != null){
   		   pattern.offsetY = item.offsetYB;
   		}
   		if( item.repeatB != null){
   		   pattern.repeat = item.repeatB;
   		}
      if (item instanceof fabric.PathGroup) {
        item.getObjects().forEach(function(o) { 
   		 o.fill = pattern;
		 //console.log(img);
     	});	 
    	}else {
    	   item.fill = pattern;
   	  } 
	 });
   });
   
});


		var dataURL = canvas.toDataURL({
    		format: 'png',
			multiplier: 7,
			quality: 1
		});
	    var data = dataURL.replace(/^data:image\/png;base64,/, '');
        var random = Math.floor((Math.random() * 100) + 1);      
     // Write PNG file
        fs.writeFile('/var/www/svg/'+random+'.png', data, 'base64', function(err) {
            if (err)
                console.log('Error saving PNG: ' + err);
         
     });

**Comment by Godweed** [comment]
@asturur I think the problem is the pattern object do not scaled when the canvas is zoomed or exported to image using todataurlwithmultiplier. The upsized pattern looks in poor quality even it is captured from svg. Any advices to solve this problem?

**Comment by Godweed** [comment]
I am closing the issue as it looks like cario bug.

**Comment by umangvyas** [comment]
Hello Godweed,

Did you solve the issue?

**Comment by asturur** [comment]
i m not exactly sure the issue is solvable, it may also be that svg patterns do not scale with context.

**Comment by umangvyas** [comment]
@asturur, I have also added the issue @ [5884](https://github.com/fabricjs/fabric.js/issues/5884)

DataURL with multiplier doesn't work as expected while using patterns.
