### ISSUE TITLE
[Feature] IText: paste formed text

### ISSUE THREAD

**Issue by OperKH** [kangax/fabric.js#3235]
Is it possible to paste into IText object text, that already formatted e.g bold, color, font-size, font-family, etc.

Could we get style information from the "paste" event data `event.clipboardData.getData("text/html")`? And convert inline html styles to FabricJS-compatible styles?

**Comment by asturur** [comment]
we could yes. acutally we are pasting just style copied from other objects.
we have a style parser, guess if we can reuse it.

**Comment by asturur** [comment]
too much application specific.
Fabric has the inner parts to handle that, but you have to write your own copy paste handler. 
Not something we want to do here.
