### ISSUE TITLE
svg output is not prper

### ISSUE THREAD

**Issue by mukeshcp** [kangax/fabric.js#3236]
hi, i have loading json into canvas then it properly loaded but when i am generating svg for it its not proper.

this is jsosn which i am loading into canvas : 
{"objects":[{"type":"text","originX":"center","originY":"center","left":250,"top":156.81,"width":7,"height":5,"fill":"#FFFFFF","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":50,"scaleY":50,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"objectPerWidth":"100","exactHeight":173.095703125,"boxUpperGap":43.1884765625,"boxLowerGap":83.7158203125,"text":"SD","fontSize":5,"fontWeight":"normal","fontFamily":"Times New Roman","fontStyle":"normal","lineHeight":1,"textDecoration":"","textAlign":"left","textBackgroundColor":""},{"type":"text","originX":"center","originY":"center","left":250,"top":418.99,"width":4,"height":5,"fill":"#FFFFFF","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":80,"scaleY":80,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"objectPerWidth":"100","exactHeight":276.953125,"boxUpperGap":69.1015625,"boxLowerGap":133.9453125,"text":"G","fontSize":5,"fontWeight":"normal","fontFamily":"Times New Roman","fontStyle":"normal","lineHeight":1,"textDecoration":"","textAlign":"left","textBackgroundColor":""},{"type":"text","originX":"center","originY":"center","left":250,"top":557.54,"width":2,"height":5,"fill":"#FFFFFF","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":133.33,"scaleY":133.33,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"objectPerWidth":"100","exactHeight":49.153645833333336,"boxUpperGap":392.51302083333326,"boxLowerGap":358.3333333333334,"text":"-","fontSize":5,"fontWeight":"normal","fontFamily":"Times New Roman","fontStyle":"normal","lineHeight":1,"textDecoration":"","textAlign":"left","textBackgroundColor":""}],"background":"#000000"}

when it loaded into canvas its showing properly : refer below image for after json loaded:
![json_output](https://cloud.githubusercontent.com/assets/12266888/18306896/95d46022-750b-11e6-810d-58b4fed3c293.png)

but after generating svg its not proper. refer below image of svg .
![svg-output](https://cloud.githubusercontent.com/assets/12266888/18306943/c4178f72-750b-11e6-90b5-b6aa88b458a4.png)

this is the generated svg file : 
[generated_svg.txt](https://github.com/kangax/fabric.js/files/458749/generated_svg.txt)

below is generated svg code : 

<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="500" height="791.9113590218926" style="background-color: #000000" viewBox="0 0 500 791.91" xml:space="preserve">
<desc>Created with Fabric.js 1.6.4</desc>
<defs></defs>
	<g transform="translate(250 156.81) scale(50 50)">
		<text font-family="Times New Roman" font-size="5" font-style="normal" font-weight="normal" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(255,255,255); fill-rule: nonzero; opacity: 1;" >
			<tspan x="-3.5" y="1.57" fill="#FFFFFF">SD</tspan>
		</text>
	</g>
	<g transform="translate(250 418.99) scale(80 80)">
		<text font-family="Times New Roman" font-size="5" font-style="normal" font-weight="normal" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(255,255,255); fill-rule: nonzero; opacity: 1;" >
			<tspan x="-2" y="1.57" fill="#FFFFFF">G</tspan>
		</text>
	</g>
	<g transform="translate(250 557.54) scale(133.33 133.33)">
		<text font-family="Times New Roman" font-size="5" font-style="normal" font-weight="normal" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(255,255,255); fill-rule: nonzero; opacity: 1;" >
			<tspan x="-1" y="1.57" fill="#FFFFFF">-</tspan>
		</text>
	</g>
</svg>

pls tell me what is issue i have try with differnt version but still not getting proper svg file.
pls provide me solution. what is the problem ?? why it happening ??

**Comment by asturur** [comment]
cannot reproduce in kitchensink.

**Comment by asturur** [comment]
![image](https://cloud.githubusercontent.com/assets/1194048/18818015/589b8ed0-836e-11e6-8f1d-c5cc8047691c.png)

this is the output svg.  completely fine for me.
