### ISSUE TITLE
svg is not proper in kitchsink demo

### ISSUE THREAD

**Issue by mukeshcp** [kangax/fabric.js#3237]
hi ,
i have added text and scaled it in full size in kitchen sink demo then generate svg for it. but generated svg is not proper. means after scaling  text object svg generated is not proper . pls refer below scrnshot of kitchen sink demo  

![demo_json](https://cloud.githubusercontent.com/assets/12266888/18307940/19c3d166-7510-11e6-9134-632f8bfeb5c5.png)

this the generated svg scren shot of kitchen sink demo
![demo_svg](https://cloud.githubusercontent.com/assets/12266888/18308067/9e19da5a-7510-11e6-93b4-46045a0b584c.png)

pls provide me solution. i am struggling with this issue from many days.

**Comment by asturur** [comment]
what is the difference?

**Comment by ncou** [comment]
The "ipsum" text seems to be overwritted by the letters "es" from the word "testing".

**Comment by mukeshcp** [comment]
asturur @ The "ipsum" text seems to be overwritted by the letters "es" from the word "testing". Also check position of other characters.
