### ISSUE TITLE
Missing canvas event "object:deselected"

### ISSUE THREAD

**Issue by Fidel90** [kangax/fabric.js#3238]
I know when selecting an object canvas fires `object:selected` and when deselecting a single object it fires `selection:cleared`. I think this is misleading at best.

As there are events for selecting a single object (`object:selected` / `selected`) I would expect the given `deselected` for objects to have its counterpart `object:deselected` on canvas as well.

Instead it fires `selection:cleared` which I would expect only to fire when a selection (grouping by user) is cleared. Well, it fires `selection:created` for grouping, doesn't it?

So, IMO, at least one event is missing and given events sometimes do wrong things. I think better would be:

A single object gets selected -> fire `object:selected` and `selected`.
A single object gets deselected -> fire `object:deselected` and `deselected`.
User creates a grouping of objects -> fire `selection:created`.
User ungroups -> fire `selection:cleared`.

**Comment by asturur** [comment]
it is mainly a doc issue that would create backward incompatible changes. big one.

**Comment by Fidel90** [comment]
The current workaround I use checks for the `e.target` in the `selection:cleared` event. If the target is `null` we deselected a group, otherwise the target is the object that has been deselected. At this point one may trigger a custom `object:deselected` event on the canvas.

Anyway the current naming and mixed responsibilities of those events feels a bit cumbersome.

**Comment by asturur** [comment]
is still the story of back incompat.
group is null.if deselected because it gets destroyed and i cannot send back a reference.to something that is no more.
is just naming anyway, is one time effort of reading event list, then it works.
maybe in 2.0 we can change some names and divide the 2 things.

**Comment by Fidel90** [comment]
Dividing object and group deselection would be a great thing for 2.0 :+1:  For now I'm fine with my workaround. As said, it works but feels wrong and inconsistent among the other events.

**Comment by awehring** [comment]
There is another related issue: #1279

**Comment by schang933** [comment]
I have this issue as well, but the solution posted by @Fidel90 does not work for me. Specifically:

> when deselecting a single object it fires `selection:cleared`

The `selection:cleared` event does not fire when selecting another object deselects the single object that is currently selected.

Saving the last selected element as mentioned in #1279, although inelegant, does work. Is there a better solution in the current version of Fabric js?

**Comment by asturur** [comment]
i will just update the docs.
I cannot think that users that start a project with fabricjs will not read docs.
I would just create problem to existing softwares.
I guess a big note over selection:cleared is enough.
