### ISSUE TITLE
[Bug] BoundingBox is too large when object is scaled up

### ISSUE THREAD

**Issue by Fidel90** [kangax/fabric.js#3239]
## Version
1.6.4

## Test Case
https://jsfiddle.net/my5wf6e4/

## Steps to reproduce

1. Select the circle in the middle of the canvas
2. Scale it up

## Expected Behavior

The bounding box should tightly fit the circle.

## Actual Behavior

The bounding box is way too large.

You can change the initial radius of the circle. You will see, that on bigger radius, the bounding box error is shrinking. Anyway, the effect is visible to me up to an initial radius of 25 (even beyond, depending on how much you scale the circle).

PS: This error also affects other objects like rectangles and triangles!

**Comment by Fidel90** [comment]
Updated fiddle with added triangle/rectangle: https://jsfiddle.net/my5wf6e4/1/

**Comment by asturur** [comment]
its an edge case..please give stroke a color or set strokewidth equal 0.

**Comment by Fidel90** [comment]
Ah, `strokeWidth` is the bad boy, thanks for pointing that out. Works great now :)
