### ISSUE TITLE
custom properties in the backgroundImage object, are not serialized in JSON

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3241]
Hi,

I am using the v1.6.3 of the library.
I have added a custom attribute on the backgroundImage using something like :: 

canvas.setBackgroundImage('http://cssdeck.com/uploads/media/items/4/4OIJyak.png', canvas.renderAll.bind(canvas), {left:100, customattribute:"TEST1"});

And it's not serialized in the canvas.toJSON(["customattribute"]) methode.

If i move my custom attribute, on the canvas it's work fine.
I checked on the code source and it seems that the "propertiesToInclude" array is ok on the image class.

PS : If i display my custom attribute in the console with "canvas.imageBackground.get('customattribe')" it's showing the right value.

any idear ? it seems to be a bug

Thank you for your help. and keep up the good work. this library is amazing

**Comment by asturur** [comment]
checking if is a bug i ll fix it otherway just close it
