### ISSUE TITLE
Using insertat to exchange objects in fabricjs doesn't update controls

### ISSUE THREAD

**Issue by BlackEon** [kangax/fabric.js#3243]
## Version
1.6.3

## Test Case
Same example, but now working (the https broke things)
http://jsfiddle.net/r4ye1wgw/3/

## Steps to reproduce
1. Create a new group
2. Exchange an element from the group with an other of different size
```
group = new fabric.Group( [ elsvg.svg1, elsvg.svg2 ] );
canvas.add( group );
group.insertAt(elsvg.svg3, 0, true );
```

## Expected Behavior
Automatically update the bounding box/controls or a method to do so manually.

## Actual Behavior
Moving or changing elements within that group does not update the controls/bounding box, and I've found no way to do so.

**Comment by asturur** [comment]
The expected behaviour is wrong. as soon as possible i will make a clean method to recalculate group boundaries if possible. You can still do with actual code destroying and recreating the group.
