### ISSUE TITLE
Font family not changing properly

### ISSUE THREAD

**Issue by xxvii27** [kangax/fabric.js#3244]
http://fabricjs.com/kitchensink

The font-family doesnt appear to be really changing, just alternating between 2 families? I'm on ubuntu chrome 52

**Comment by asturur** [comment]
maybe there is a better implementation to do for font loading in kitchensink.
Try moving the text element around after font changes, i can see the the font change.
I do not think we are loading fonts from google there maybe your system does not have those kind of fonts?

**Comment by xxvii27** [comment]
im using standard fonts, for example arial and helvetica seems the same. I am encountering this problem, on a site, and kitchensink seems to demonstrate the problem also
