### ISSUE TITLE
Missing test on null lines 18403 & 18404

### ISSUE THREAD

**Issue by thaxyz** [kangax/fabric.js#3245]
## Version
1.6.4

## Test Case
Load canvas with various filters

Error in Sub function      filters.forEach(function(filter) { }

filter can be null.

Lines 18403 & 18404
Replace 
          scaleX = filter.scaleX;
          scaleY = filter.scaleY;
With
          scaleX = filter && filter.scaleX;
          scaleY = filter && filter.scaleY;

Thanks

**Comment by asturur** [comment]
we fixed this with 
https://github.com/kangax/fabric.js/commit/86e99899bc1ea467faede556da7a8d4322cb75e0
