### ISSUE TITLE
adding a Image object to a group

### ISSUE THREAD

**Issue by buddyspence** [kangax/fabric.js#3255]
Hello everybody,

i have a problem at adding Images to a group on fabric.js.
I want to add the image to my canvas in these 3 steps:

1. Create the elements (rect, text, image)
2. Add the elements to a group
3. add the group to my canvas

That sounds simple, but i cant find a way of creating a image element without adding it to the canvas.
everything looks like this:

`fabric.Image.fromURL('my_image.png', function(oImg) {
  canvas.add(oImg);
});`

Can i do it wothout the 'canvas.add(oImg); ?

With simple elements is that no problem:

`var rect = new fabric.Rect({
                    fill: 'red',
                    width: 10,
                    height: 100,
                    id: 'square'
    });`

Please can someone help me, i tried it on Stackoverflow first but i dont got the answers that i need.
Is this even possible. 

I found something where they made it nearly as i want, but i cant do this because the image is not in my DOM:

`var imgElement = document.getElementById('my-image');
var imgInstance = new fabric.Image(imgElement, {
  left: 100,
  top: 100,
  angle: 30,
  opacity: 0.85
});`

I hope you know what i want. Thank you in advance.

**Comment by AyobKafrashian** [comment]
Follow the link below
https://stackoverflow.com/questions/33934760/how-to-add-image-in-group-in-fabric-js/71109395#71109395
