### ISSUE TITLE
Applying fontWeight and fontStyle not working on nodejs server 

### ISSUE THREAD

**Issue by dannyto** [kangax/fabric.js#3257]
Hi!

Have anyone get this error when load canvas in nodejs server

Thanks

**Comment by asturur** [comment]
what error? please show error and code used for loading.

**Comment by dannyto** [comment]
I just make sample on my nodejs server like this:

var text = new fabric.Text('Hello world', {
  fontFamily: 'Arial',
  fontSize: 30,
  fontWeight: 'bold',
  fontStyle: 'italic',
  left: 100,
  top: 100,
  fill: 'red'
});
canvas.add(text);

but the fontWeight and fontStyle not working. It work on chrome, i dont know why

Thanks

**Comment by belfz** [comment]
You are not being descriptive enough. How do you infer that it doesn't work?
You have to show more code. And use proper formatting of the posts (surround the code snippet with tripple backslash).
