### ISSUE TITLE
canvas.renderAll.bind(canvas) does not work inside callback function loadFromJSON ¿[BUG]?

### ISSUE THREAD

**Issue by samael205** [kangax/fabric.js#3258]
## Version
1.6.4

## Test Case
https://jsfiddle.net/samael205/asnz785a/7/

## Steps to reproduce
Load the fiddle
## Expected Behavior

When the page is loaded, you should see a rectangle

## Actual Behavior
the page executes the finalizarCarga(), but not renders the canvas, ¿Why?

**Comment by samael205** [comment]
Now, i know the function finalizarCarga() runs, but, the canvas.renderAll.bind(canvas) not render the canvas, why?

**Comment by belfz** [comment]
`Function.prototype.bind()` returns a new function. You have to call that new function afterwards:
either 
`canvas.renderAll.bind(canvas)();`
or 
```
const render = canvas.renderAll.bind(canvas);
render();
```

**Comment by asturur** [comment]
thanks for helping out with this. For this kind of question i generally send people to StackOverflow, where, when i have time i help. I cannot manage an issue tracker with always more than 180 issue, no matter how many i close, there are always more than 180.

**Comment by samael205** [comment]
Many Thanks, guys. Sorry for this issue.
