### ISSUE TITLE
How to fit screen when coorperation

### ISSUE THREAD

**Issue by yanzhou-share** [kangax/fabric.js#3259]
Hi, @kangax :
I'm use this plugin to coorperation, but how to fit screen(somebody the screen is 1600*900 pix, I draw some line, but another client screen is 800*450).

I want everyone to see the same area.

Thanks.

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically, We cannot handle help request here.
