### ISSUE TITLE
Bug with image in setBackgroundColor

### ISSUE THREAD

**Issue by Toby84** [kangax/fabric.js#3260]
Hi!

I use the following code to add a backgroundimage, and it works fine:
canvas.setBackgroundColor({source: src, repeat: 'repeat'}, canvas.renderAll.bind(canvas));  

Then, when I want to remove it I use canvas.setBackgroundColor('#FFFFFF', canvas.renderAll.bind(canvas));

This works fine in firefox, and sometimes in Chrome. Other times it fails. When using only colors for background (not images), it's fine. I'm using 1.6.4

Thanks!

**Comment by asturur** [comment]
please add a fiddle with the problem that reproduce the bug. It has to fail everytime.
