### ISSUE TITLE
different clip area size and coords in different OS

### ISSUE THREAD

**Issue by ansaus** [kangax/fabric.js#3264]
## Version
https://rawgit.com/kangax/fabric.js/master/dist/fabric.js

## Test Case
https://jsfiddle.net/ansaus/8gv95y57/5/

## Steps to reproduce
run the test case

## Expected Behavior
in windows OS we see the clip area with one size (it covers all the mug) like this http://take.ms/M2J1X
## Actual Behavior
in other OS the clip area is smaller than expected(we expect to cover all the mug on the left top corner)
for example this one http://take.ms/qaoU0 made in ubuntu 16.04 and the same in android

**Comment by ansaus** [comment]
just found that it depends on devicepixelratio and that fabricjs should support it already but why my fiddle doesnt work on retina devices yet? it uses last fabricjs version

**Comment by asturur** [comment]
i wanted to ask you about hardware.
i have to check the fiddle yet. you should not have cliparea problems.

**Comment by asturur** [comment]
please check answer to this issue.
https://github.com/kangax/fabric.js/issues/3301
