### ISSUE TITLE
freeDrawingColor and freeDrawingLineWidth

### ISSUE THREAD

**Issue by abnersouzarocket** [kangax/fabric.js#3265]
Hi guys, 
I having issues to set both freeDrawingColor and freeDrawingLineWidth using it in typescript, I have two versions one using javascript only and one using typescript.

## Version
1.5.0 (using this version because is the latest DefinitelyTyped I found)

## Steps to reproduce
1. Create a fabric.Canvas passing the ICanvasOptions and setting freeDrawingColor and freeDrawingLineWidth.

`
  this.canvasControl = new fabric.Canvas('my-canvas', {
        backgroundColor: 'blue',
        isDrawingMode: true,
        freeDrawingCursor: 'default',
        freeDrawingColor: '#ff0000',
        freeDrawingLineWidth: 5
  });
`

## Expected Behavior
To set the line width and line color according to the parameters.

## Actual Behavior
It doesn't set both properties.
Using only javascript works perfect, I set it different because I have the freeDrawingBrush object then I can do this:
`
canvasControl = new fabric.Canvas('main-canvas', {
    backgroundColor: 'transparent',
    isDrawingMode: true,
    freeDrawingCursor: 'default'
});

if (canvasControl.freeDrawingBrush) {
    canvasControl.freeDrawingBrush.color = '#FF0000';
    canvasControl.freeDrawingBrush.width = 5;
    canvasControl.freeDrawingBrush.shadowBlur = 0;
}
`
I check the d.ts and notice that IBaseBrush has those properties, but not sure how to set it instead of ICanvasOptions.

The workaround was to parse the ICanvas to any and set like this:
`
(<any>this.canvasControl).freeDrawingBrush.color = '#FF0000';
(<any>this.canvasControl).freeDrawingBrush.width = 5;
`

Is there any other way to set it?

Thanks

**Comment by asturur** [comment]
we do not support older version.
What do you mean by 'latest DefinitelyTyped I found'?

**Comment by abnersouzarocket** [comment]
Hi @asturur  the lastest d.ts file (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/fabricjs)

I'm using the same js file version of the d.ts.

Any suggestion?

**Comment by asturur** [comment]
never heard of those properties. Sorry.

**Comment by abnersouzarocket** [comment]
@asturur Just because you haven't heard you had closed it?

![image](https://cloud.githubusercontent.com/assets/20269820/18671392/cbcc48b8-7f3b-11e6-87f4-d9d2c98466aa.png)

This definitions are in the Type Definitions for fabricJS
// Type definitions for FabricJS v1.5.0
// Project: http://fabricjs.com/
// Definitions by: Oliver Klemencic <https://github.com/oklemencic/>, Joseph Livecchi <https://github.com/joewashear007/>, Michael Randolph <https://github.com/mrand01/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

Those two properties doesn't exist in the .js file.

This is the workaround to make it work
![image](https://cloud.githubusercontent.com/assets/20269820/18671549/71adc158-7f3c-11e6-96ae-c2bc73385aae.png)

I have to cast the object to any and set the freeDrawingBrush Color and Width.

**Comment by asturur** [comment]
no i closed it because:
1) those are not fabricjs properties if are not in the js files
2) fabricjs is not in typescript and so this issue does not belong here.

it belongs to the DefinitelyTyped github issue tracker.
