### ISSUE TITLE
Multiplier Property is not working as Expected with cropping

### ISSUE THREAD

**Issue by abhi06991** [kangax/fabric.js#3266]
I am using **fabricjs version 1.6.2**. 
When I am using the **toDataURL** function, with cropping and multiplier, I am getting only the top left portion of an image

Here is the fiddle demonstrating the problem:

http://jsfiddle.net/7T8WC/36/

When you click on the Enhance Image button, only a part of image can be seen

**Comment by asturur** [comment]
fixed in 1.6.5
(please remove clipTo before exporting to dataurl)

**Comment by abhi06991** [comment]
@asturur thank you so much.It works perfectly. Our website is heavily powered by fabricjs, cant thank you guys enough for your work
