### ISSUE TITLE
[API / Documentation] .getActiveObject() / .getActiveGroup() on fabric.StaticCanvas

### ISSUE THREAD

**Issue by Fidel90** [kangax/fabric.js#3267]
Hey, I'm not sure if I missed something but to me it's weird that `fabric.StaticCanvas` provides functions to get the active object/group. On the other hand setting an object/group as active on a StaticCanvas is not possible, ofcourse, as it's not interactive.

So, what's the point of having these two methods?

**Comment by asturur** [comment]
no point.
sure it does not return null? maybe some.compatibility issue with other methods

**Comment by Fidel90** [comment]
Yes, `getActiveObject()` does return `null` on a StaticCanvas. I'm just curious why these functions are available on the first place...

**Comment by asturur** [comment]
I think for some common method that calls them. I have to check and in case remove.
