### ISSUE TITLE
font family not working with 1.6.4

### ISSUE THREAD

**Issue by danielleamty** [kangax/fabric.js#3273]
## Version
1.6.4

The font family is not working anymore, this was working in the previous version tho. 
Is there a new format i should be using, or is this a bug?

var font = new fabric.Textbox("Im some heading!", {
            fontFamily: "'Roboto Condensed', sans-serif",
            fill: "#000",
            fontSize: 40
});

Thanks

**Comment by danielleamty** [comment]
why did you close this

**Comment by asturur** [comment]
duplicate of https://github.com/kangax/fabric.js/issues/3261
