### ISSUE TITLE
IText focus issue on Edge

### ISSUE THREAD

**Issue by medialwerk** [kangax/fabric.js#3279]
## Version
1.6.3

## Test Case
http://jsfiddle.net/zr4s54o7/2/

## Steps to reproduce
1. Click on the canvas
2. Write new text 

## Expected Behavior
The entered text appears on the canvas

## Actual Behavior
On Edge browser the entered text does not appear. It could be related to this ie issue: http://www.mkyong.com/javascript/focus-is-not-working-in-ie-solution/. After wrapping "customtxt.enterEditing();" within "setTimeout"  it works fine. But i think fabricjs should care about this browser issue.

Thanks!

**Comment by asturur** [comment]
are you trying with 1.6.3 or current master?

**Comment by medialwerk** [comment]
Actually I'm trying with the 1.6.3 npm package version. The jsfiddle is mistakenly 1.6.4, but there is the issue also.

**Comment by asturur** [comment]
Is enough to put the event on mouseup.
I guess is the mouse event interacting with the newly created textbox.
Is a very particular case to be taken care by the library itself. There are no errors no warning.

**Comment by medialwerk** [comment]
I switched to the mouseup event and it works fine, thanks!
