### ISSUE TITLE
textbox.wrong autocomlite inserts on mobile device

### ISSUE THREAD

**Issue by Rad1calDreamer** [kangax/fabric.js#3280]
## Version
1.6.4 (https://rawgithub.com/kangax/fabric.js/master/dist/fabric.js )

## Test Case
http://jsfiddle.net/a6rsbek1/1/

## Steps to reproduce
open in Ipad (or another mobile device), try type some words use autocomplite panel (attach1
![21 09 2016 11-18](https://cloud.githubusercontent.com/assets/7055577/18703129/42ec3eba-7fed-11e6-86df-bf1d05521d78.png))  

words inserts with missing some first or last letters

**Comment by asturur** [comment]
I have android phone and i have to click suggestion twice to make it insert.
Any suggestion on how debug js events on those devices/browsers?

**Comment by asturur** [comment]
Did you solve?

**Comment by Rad1calDreamer** [comment]
stop repropduce. cant understand why. hate ios =)
