### ISSUE TITLE
High DPI for user zooming

### ISSUE THREAD

**Issue by raj-sidhu** [kangax/fabric.js#3281]
Hi,

I needed to get the high DPI code working for user zoom. The existing issue ([https://github.com/kangax/fabric.js/commit/fb22168f488830878cb55f6006ab2611f2d157b8]) works only on initialisation so I made some changes:

1> put fabric.devicePixelRatio = ... into a function (_getPixelRatio)
2> Take out the !this.interactive where this._initRetinaScaling gets called.
3> Change _initRetinaScaling so that it calls the previous function instead of the initial value
4> Call this._initRetinaScaling in the _onResize event.

cheers.

**Comment by asturur** [comment]
what is the _onResize event?

**Comment by raj-sidhu** [comment]
Sorry the _onResize: function in fabric.js (all the changes in this file).

I also had to send an initial resize when I setup the canvas initially and created the fabric object.

`        this.canvas = new fabric.Canvas(this.htmlID, {containerClass: this.htmlID, enableRetinaScaling: true});

        // high DPI
        setTimeout(() => {
            this.canvas._onResize();
        }, 0);
`
