### ISSUE TITLE
Mouse over event for selected object broken (and other stuff)

### ISSUE THREAD

**Issue by virror** [kangax/fabric.js#3282]
## Version
1.6.4

## Test Case
http://jsfiddle.net/zr4s54o7/4/

## Steps to reproduce
Mouse over the box, note that it changes color.
Move mouse out, does not change color back until you move mouse outside of canvas.
Select the square (must use drag select)
Mouse over, now it does not change color anymore.

## Expected Behavior
Box should be selectable with single click.
Mouse out should work properly
Mouse over should work even if object is selected.
## Actual Behavior
The opposite

**Comment by asturur** [comment]
http://jsfiddle.net/zr4s54o7/5/

a reference to non existent $ symbol was breaking the fiddle.
Everythin ( in this fiddle ) works
Please be more carefull.

**Comment by virror** [comment]
Because of shortcuts? I would still think of that as a bug though. I hope it's going to be fixed?

**Comment by asturur** [comment]
yes the findTarget return early and does not go trough the hovering events firing.
Before was happening just on preserveObjectStacking = false, that is the default behaviour.
Is gonna be fixed is really easy.

**Comment by asturur** [comment]
https://github.com/kangax/fabric.js/pull/3285/files
