### ISSUE TITLE
[BUG] iText demo page is broken

### ISSUE THREAD

**Issue by temuri416** [kangax/fabric.js#3284]
## Version
1.6.4

## Test Case
http://fabricjs.com/test/misc/itext.html

## Steps to reproduce
Open http://fabricjs.com/test/misc/itext.html in Chrome

## Expected Behavior
Tests should render

## Actual Behavior
JS error in the console "TypeError: this.getObjectScaling is not a function /lib/fabric.js:12488"

**Comment by asturur** [comment]
fixed with latest release
