### ISSUE TITLE
Bug not exported chart gradient colors

### ISSUE THREAD

**Issue by nepos87** [kangax/fabric.js#3288]
I need to export a chart to jpeg with gradientOrientation vertical. Taking for example the graph in demo, this is the code:

![screenshot_20160926_122956](https://cloud.githubusercontent.com/assets/9459917/18831245/00e340ee-83e5-11e6-9aee-d759751ce4f1.png)

var chart = AmCharts.makeChart( "chartdiv2", {
"type": "serial",
"rotate": false,
"theme": "light",
"autoMargins": false,
"marginTop": 30,
"marginLeft": 80,
"marginBottom": 30,
"marginRight": 50,
"dataProvider": [ {
"category": "Evaluation",
"excelent": 20,
"good": 20,
"average": 20,
"poor": 20,
"bad": 20,
"limit": 78,
"full": 100,
"bullet": 65
} ],
"valueAxes": [ {
"maximum": 100,
"stackType": "regular",
"gridAlpha": 0
} ],
"startDuration": 0,
"graphs": [ {
"valueField": "full",
"showBalloon": false,
"type": "column",
"lineAlpha": 0,
"fillAlphas": 0.8,
"fillColors": [ "#19d228", "#f6d32b", "#fb2316" ],
"gradientOrientation": "vertical",
}, {
"clustered": false,
"columnWidth": 0.3,
"fillAlphas": 1,
"lineColor": "#000000",
"stackable": false,
"type": "column",
"valueField": "bullet"
}, {
"columnWidth": 0.5,
"lineColor": "#000000",
"lineThickness": 3,
"noStepRisers": true,
"stackable": false,
"type": "step",
"valueField": "limit"
} ],
"columnWidth": 1,
"categoryField": "category",
"categoryAxis": {
"gridAlpha": 0,
"position": "left"
}
} );

The result after export is the image in the attached. The color gradient is gone and there is only a single color corresponding to an extreme of "fillColors".

![chart_exported](https://cloud.githubusercontent.com/assets/9459917/18831197/b41a08a6-83e4-11e6-9f95-c0d3bd5258b6.jpeg)

I am using fabricjs version 1.6.4.

**Comment by asturur** [comment]
please attach fabricjs code or i will close the issue.

**Comment by nepos87** [comment]
I use base64 to export the chart:

// WAIT UNTIL CHART HAS BEEN RENDERED
chart.addListener( "rendered", function( e ) {

// WAIT FOR FABRIC
var interval = setInterval( function() {
if ( window.fabric ) {
clearTimeout( interval );

// CAPTURE CHART
e.chart["export"].capture( {}, function() {

// SAVE TO JPG
this.toJPG( {}, function( base64 ) {

// LOG IMAGE DATA
console.log( base64 );
} );
} );
}
}, 100 );

} );
