### ISSUE TITLE
SVG Line coordinates mismatch after .loadFromJSON() method

### ISSUE THREAD

**Issue by nikksan** [kangax/fabric.js#3289]
Hey there , 
I have a problem with line coordinates(x1,x2,y1,y2) when loading from json.
[Here is an example.](https://jsfiddle.net/pmuopyfn/3/)
First I create simple line , and console.log its coordinates later I load the same canvas again and as you can see the x1,x2,y1,y2 attributes dont match , which results in wrong SVG.

**Comment by nikksan** [comment]
Anyone ?

**Comment by asturur** [comment]
i need to check this is a long standing issue.

**Comment by asturur** [comment]
i checked this again.
The coordinate can changes, it is rendered same.
What svg problem do you see? i do not see any.
If you add more specific problem we can reopen the issue.
