### ISSUE TITLE
Render Issue - Shadow on (i)text object - (only Firefox in version 49.0.1)

### ISSUE THREAD

**Issue by inovek** [kangax/fabric.js#3292]
## Version
Tested with FabricJS 1.6.3 and 1.6.4 (today from this repository)

## Test Case
http://fabricjs.com/kitchensink/

## Steps to reproduce
1. Visit Kitchensink
2. Click "Simple"-Tab
3. Click "Add Text"-Button
4. Click "Controls"-Tab
5. Click "Shodify"

## Expected Behavior
Shadow for Text and iText-Objects.

## Actual Behavior
- No Shadow on Text and iText-Objects in Mozilla Firefox 49.0.1. (tested on Windows 10 and OSX)
- Firefox 48.0.2 and below works fine (both operating systems).
- Current Safari and Chrome works fine, too.
- Tested in my own FabricJS based editor, in Kitchensink and older jsFiddle-expamples. (everywhere same result)

**Comment by asturur** [comment]
looks a firefox problem. are you able to reproduce in plain javascript and report to firfox bug tracker?

**Comment by inovek** [comment]
I'm not able to do this. I'm used to use FabricJS for such jobs. (Sorry)

**Comment by asturur** [comment]
on bugzilla is reported as fixed in firefox 50.
