### ISSUE TITLE
BackgroundImage not cleared on LoadFromJSON

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3296]
Hi,

A)
I think there is a bug in the LoadFromJSON with an empty json string.

I init a canvas with a shape+a background color+an background image

I try to load a new JSON, or an empty JSON (based on the static EMPTY_JSON string), and the shape+background color is cleared, but the background image stay.
I need to explicitely set it to null to clear the background image (with the setter function, i tried to set it to null or '' in the json, but it doesn't work this way).

This look like a wrong behaviours.

Here is a basic example, using the fabric 1.6.4 library.
http://codepen.io/anon/pen/mAwzYO?editors=1111

B)
And the clear signal seem to be called 2 time ??? it's strange. I have added a bind on the onclear event, and the event is fired 2 times when i load a json file. Is that also a bug ?

Thank you for your help. keep up the good work.
Sorry for my poor english

Kind regards.

**Comment by inovek** [comment]
Can confirm this issue.

**Comment by asturur** [comment]
yes image and overlay are not removed on canvas.clear.
I guess if i have to modify clear or modify load from json.

**Comment by asturur** [comment]
i can check but that is minor annoyance. the clear funtion does very littlr
