### ISSUE TITLE
Issue with Bounding Box and Stroke Size Changes on Shapes

### ISSUE THREAD

**Issue by html5andblog** [kangax/fabric.js#3299]
## Version
1.6.4

## Test Case
http://codepen.io/html5andblog/pen/cd502bc15bf07e78d66ef215ed2f620b

## Steps to reproduce
I've set the number input to adjust the stroke sizing. If you change the stroke size on the text then the bounding box is correct, but when you do the same on the shape it jumps to the dimensions of the canvas making it hard to select and resize. It's also hard to select once it's been deselected.

## Expected Behavior
Expected behavior is how it works on the text. The stroke size would change, but the bounding box would remain largely unchanged. 

## Actual Behavior
Bounding box on shapes becomes the size of the canvas.

**Comment by asturur** [comment]
i cannot reproduce on kitchensink. can you?

**Comment by html5andblog** [comment]
I've just tried and I can't replicate it on the kitchen sink. That's strange, I used the exact same code.

**Comment by asturur** [comment]
can you inspect the object after setting the strokewidth? how much is it in the console.log?

**Comment by html5andblog** [comment]
I've just been doing some more testing and it seems like it might be an issue with how it's getting the HTML input value. Using parseInt seems to have solved it, `obj.strokeWidth = parseInt($(this).val());`. I'll close the ticket now.

Thanks for your help.
