### ISSUE TITLE
Skew, Rotate and Alignment issue 

### ISSUE THREAD

**Issue by ashishbhattb** [kangax/fabric.js#3300]
Skew, Rotate and Alignment issue 

## Version
1.6.4

## Test Case
http://jsfiddle.net/Rq7hk/152/

## Steps to reproduce
Make any Html div with border with skew, rotate 
Add image in same position and check width height and alignment

## Expected Behavior
as per the html width height and positions of rotate and skew should apply for fabric js image which were added

## Actual Behavior
Its Not aligning and not happening as per positions as same properties are given to the image

**Comment by asturur** [comment]
http://jsfiddle.net/Rq7hk/153/

you should check how fabricjs apply transform. if you apply same transform you will notice that it is in the same shape at at least.
Fabric is made to have same transformation as SVG, HTML is not taken into account.

**Comment by ashishbhattb** [comment]
Hi,

Can you guide me for the same as i will get html object and needs to put fabirc object according to html object

if possible solve my issue.

**Comment by ashishbhattb** [comment]
http://jsfiddle.net/Rq7hk/156/

I have tried for the same. but not happen still, please help me as stuck badly

**Comment by ashishbhattb** [comment]
http://jsfiddle.net/Rq7hk/157/

Near to the target but get controls out as not expected

**Comment by asturur** [comment]
that is completely custom code i have no time for it, i m sorry.
