### ISSUE TITLE
Using setTransform in clipTo function is bugged on some browsers

### ISSUE THREAD

**Issue by skflowne** [kangax/fabric.js#3301]
## Version
from 1.6.0 to 1.6.4

## Test Case
https://jsfiddle.net/wethrw20/

## Steps to reproduce
1. Create a canvas, add a background image
2. Create a new fabric.Rect with transparent fill
3. Add another image with its clipTo function that resets the transform like so
`clipTo: function(ctx){
      	ctx.save();
        ctx.setTransform(1, 0, 0, 1, 0, 0);
        clipZone.render(ctx);
        ctx.restore();
      }`
Where clipZone is the previous Rect.

## Expected Behavior
The image should be only visible in the area of the clipping Rect
## Actual Behavior
[Here is a screenshot](https://postimg.org/image/vvtfu9po7/)
The transform is not reset correctly, it actually is set to half, as if `ctx.setTransform(0.5, 0, 0, 0.5, 0, 0);` was called instead. 
Also the Rect is rendered twice, once at normal size, once with the clipping method it seems.

This happens to me on a Mac using Chrome and Safari.
However it doesn't happen on Firefox on the same machine and it also doesn't happen on a Windows Chrome.

Downgrading to 1.5.0 fixes the bug everywhere.

**Comment by asturur** [comment]
So the point is that in this way, using ctx.setTransform you are killing retina scaling and that is why you get  clipping area exactly at half position where you expect it to be.
If you want to clip with absolute positions i suggest you you check if retinaScaling is active and use a different transform matrix. why this happens just on some browsers is very strange.

On my retina macbook this does not happen. while it should

**Comment by asturur** [comment]
https://jsfiddle.net/wethrw20/4/

something like this

**Comment by skflowne** [comment]
I was completely unaware of this retina thing. I was mistaken about the browsers. I have dual screen, so opening different browsers on different screen made it look like it wasn't working based on the browser. But I just restested with my previous code and it's actually the screen that does the difference.

This works perfect, thanks, this is a real life saver as I need 1.6 for my app which I need to demo in the coming week!
