### ISSUE TITLE
Transform Matrix Property has Control Issue

### ISSUE THREAD

**Issue by ashishbhattb** [kangax/fabric.js#3303]
Transform Property has Control Issue

## Version
1.6.4

## Test Case
http://jsfiddle.net/Rq7hk/157/

## Steps to reproduce
Add Image with transform Matrix Get controls out

## Expected Behavior
Control should work properly like bounding box

## Actual Behavior
Add Image with transform Matrix Get controls out

**Comment by asturur** [comment]
duplicate of #1520
