### ISSUE TITLE
JSON Serialization ignores custom attributes in fabric.js after loadFromJSON

### ISSUE THREAD

**Issue by bbcCorp** [kangax/fabric.js#3318]
## Version
1.6.5

## Test Case
https://jsfiddle.net/bbcstar/9x48kk7f/

## Steps to reproduce

1. Create a group object with custom attributes
2. Add to canvas
3. Serialize canvas state to JSON
4. Use loadFromJSON to bring back the object state
5. Serialize canvas state again

## Expected Behavior
Custom attributes that were added get represented in the JSON structure

## Actual Behavior
When we serialize canvas after loading from JSON, custom attributes are not getting included.

**Comment by asturur** [comment]
```toJSON(["includeCField1", "includeCField2","includeCField3","includeCField4"])```
you have to pass an arraya
