### ISSUE TITLE
Text background color with padding

### ISSUE THREAD

**Issue by wajipk** [kangax/fabric.js#3319]
## Version
1.6.5

## Test Case
http://jsfiddle.net/7T8WC/45/

Is it possible that background color fills whole text with padding?

**Comment by asturur** [comment]
no.
padding is for controls only.
Text background color is for the text line.
You can try backgroundColor instead.

**Comment by wajipk** [comment]
@asturur please check this jsfiddle I find same behaviour with `backgroundColor` too.
https://jsfiddle.net/wajipk/2yL3mvrx/

**Comment by asturur** [comment]
Padding is not included in the object is just for selection.
If you want you can check on:
http://fabricjs.com/docs/fabric.Object.html
the property
selectionBackgroundColor
to see if it can help you.

**Comment by friday** [comment]
@wajipk: I just created a small wrapper to make background color span all the way to the controls
http://codepen.io/fullkornslimpa/pen/YpOwWm?editors=1010
https://gist.github.com/friday/1835832abff3b467607c1378c178a417

It's not very well tested, but hopefully it will work for you.

**Comment by otseobande** [comment]
@friday your solution saved my day.

**Comment by ThakurKarthik** [comment]
@friday your solution works but it has a catch,Now the overall area increased for the text so even though corners seem to be in their right place , they respond when we click outside of the them with the added padding distance.

**Comment by usamaejaz** [comment]
@ThakurKarthik 

Renaming `padding` to `textPadding` works great.

```javascript
fabric.Text.prototype.set({
  _getNonTransformedDimensions() { // Object dimensions
    return new fabric.Point(this.width, this.height).scalarAdd(this.textPadding);
  },
  _calculateCurrentDimensions() { // Controls dimensions
    return fabric.util.transformPoint(this._getTransformedDimensions(), this.getViewportTransform(), true);
  }
});
```

**Comment by usamaejaz** [comment]
@ThakurKarthik May be renaming padding to `textPadding` can work good?
```javascript
fabric.Text.prototype.set({
  _getNonTransformedDimensions() { // Object dimensions
    return new fabric.Point(this.width, this.height).scalarAdd(this.textPadding);
  },
  _calculateCurrentDimensions() { // Controls dimensions
    return fabric.util.transformPoint(this._getTransformedDimensions(), this.getViewportTransform(), true);
  }
});
```

**Comment by mspanish** [comment]
@friday is there any way to adjust your code (which is fantastic, the perfect fix for auto text boxes!) - to allow for radius? Sure would be nice to have resizable rounded rects with such little fuss!

**Comment by friday** [comment]
I haven't touched that code or used Fabric in years. It's basically a copy of the original function, but using a different way to compute the size/padding. It might be possible to improve it to fix the issues both of you are having, but someone else would have to do that in this case.

**Comment by mspanish** [comment]
Thanks I figured it out with help from @asturur in this thread here #6309

**Comment by friday** [comment]
Nice @mspanish! I think you understand this code better than I ever did now :+1:

**Comment by carloslema** [comment]
@friday your solution still works and saved my day too.

**Comment by SakifKhan98** [comment]
@carloslema does @friday 's solution works when we scale objects? For me it does not work, when scaling objects, the control box does not fit just outside the background color. It feels like that it remains with constant padding.

**Comment by SakifKhan98** [comment]
Hi, I was facing some cotrol box issues after object scaling. I took inspiration from @friday 's code. And just changed the _calculateCurrentDimension function as below:

`_calculateCurrentDimensions() {
        // Controls dimensions
        return fabric.util
          .transformPoint(
            this._getTransformedDimensions(),
            this.getViewportTransform(),
            true
          )
          .scalarAdd(this.padding * this.scaleX * 2);
      },`
