### ISSUE TITLE
Drawing object above selected item

### ISSUE THREAD

**Issue by virror** [kangax/fabric.js#3325]
Im trying to draw a text object above everything else (tooltip), but i cant find a way to draw it over a selected item. Send to font does not work, i guess the selected object is not in the regular z-array.
How can i accomplish this?

**Comment by asturur** [comment]
it depends if you are using preserveObjectStacking true or false. ( canvas property default to false )

either you plan an overly html element over the canvas or you setup a drawing function that you call in the after:render event of canvas, that will draw last and so over everything else.

you have also the topcanvas available but that gets cleared at every click i do not know if is your use case.

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

**Comment by virror** [comment]
Ok, i will try the after:render, did not see that at first since it was in staticCanvas
