### ISSUE TITLE
[$200] Introduce cross-browser CI testing

### ISSUE THREAD

**Issue by jedateach** [kangax/fabric.js#3326]
Travis CI is only running tests on Node.js. This is not sufficient for fast-paced cross-browser CI testing, and quickly ensuring changes are not breaking across all supported browsers.

I would like to suggest we get Fabric.js running on saucelabs open-source offering: https://saucelabs.com/open-source

Here's instructions for hooking into Travis:
https://docs.travis-ci.com/user/gui-and-headless-browsers/

I have managed to run Fabric.js tests using the testem test runner:
![screen shot 2016-10-04 at 9 33 01 pm](https://cloud.githubusercontent.com/assets/1356335/19101830/cb8f33e0-8b27-11e6-933a-200f2e2670e5.png)
As you can see, there are failing tests that need to be looked into.

Testem is a great tool for test-driven-development across multiple browsers at the same time.

We can set up a similar testem setup for hooking into saucelabs, like Ember.js:
https://github.com/emberjs/ember.js/blob/master/testem.dist.json

<svg xmlns="http://www.w3.org/2000/svg" width="168" height="20"><linearGradient id="b" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><mask id="a"><rect width="168" height="20" rx="3" fill="#fff"/></mask><g mask="url(#a)"><path fill="#555" d="M0 0h87v20H0z"/><path fill="#129e5e" d="M87 0h81v20H87z"/><path fill="url(#b)" d="M0 0h168v20H0z"/></g><g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11"><text x="43.5" y="15" fill="#010101" fill-opacity=".3">bountysource</text><text x="43.5" y="14">bountysource</text><text x="126.5" y="15" fill="#010101" fill-opacity=".3">$200 bounty</text><text x="126.5" y="14">$200 bounty</text></g></svg>

**Comment by asturur** [comment]
i would like this much.  i will get a look into this now

**Comment by jedateach** [comment]
That PR may help.
It isn't configured to be the `npm test` script, but could be set that way at some stage.

**Comment by asturur** [comment]
i m gonna read it carefully and try to activate it on travis. for now i opened the opensauce account

**Comment by asturur** [comment]
So:
- testem would be a new dev dependency.
- the script sauce:launch can be taken directly from ember repo? it looks project indipendent
- then i need a script that run a simple node http server for sauce connect to come here and read that test page, right?

also

i see testem.dist.json and testem.json, why 2 files?

**Comment by asturur** [comment]
for now i tried to run it on my machine with low results:
- i installed testem as a dev dep, how it should install on travis probably.
- i see you linked qunit from a folder ```bower_``` that i do not have. so i added qunit and the other lib in the served files of testem but chrome is crashing and does not allow me to see dev tools to check what went wrong.

node are passing in testem

**Comment by asturur** [comment]
we have this page for browser testing:
http://fabricjs.com/test/unit/

i would essentially replicate this page, serve it in the simplest way travis allow me ( they show rackup command in examples ) ask sauce connect to test this page, grab the output of test.

**Comment by jedateach** [comment]
Yes - testem would need to become a dev dep.

Ah yes - apologies about the bower inclusion. I used that to make use of qunit version 1.20 in the test fixture file. I believe that if you update the qunit files inside the lib folder to version 1.20, then things should work properly in chrome. (Note that qunit 2 didn't work for me)

What you've linked me to at http://fabricjs.com/test/unit/ looks just like what testem opens up in a browser automatically, except I modified the output slightly so that it only shows failed tests. The page is generated from the tests.mustache file.

![screen shot 2016-10-05 at 10 26 04 pm](https://cloud.githubusercontent.com/assets/1356335/19107878/c58dfeb8-8b4a-11e6-88fb-96648de5bfe7.png)

I don't think an http server is needed. Testem sets one up for us, and renders the mustache file, and serves the files you specify in the testem.json file.

Regarding the saucelabs integration - I haven't done such an integration before. However, my theory is that the testem server boots up on Travis, and then saucelabs' browsers connect to that server. The results would automatically feed back into testem, as it does with local browsers.

The travis saucelabs docs seem consistent with this theory:
https://docs.travis-ci.com/user/sauce-connect/#Setting-up-Sauce-Connect

Testem github provides another saucelabs config example here: https://github.com/testem/testem/blob/master/examples/saucelabs/testem.json

**Comment by jedateach** [comment]
I'm not exactly sure why ember has multiple testem files, but perhaps they are just providing some flexibility for running tests in different environments.

**Comment by jedateach** [comment]
I'm happy to try and do the saucelabs integration if you like, but it makes sense if you guys hold the keys to the saucelabs account. I'm not sure if they allow multi-user permission etc. I could also just try setting up saucelabs for my own fork to then share back in a PR.

**Comment by asturur** [comment]
So the point is that, from what i could understood from a fast read around and fast try:

- testem open a test server but you can just test installed browser. i do not think i can test internet explorer inside travisCI, so for that opensauce is better. i made an account what i missing is how i tell opensauce to open a specifice test page served by travis ci.

- i see anyway ember is using chrom and firefox inside travis and the rest on opensauce

- i opened an open sauce account.

- the open sauce connector in travis let you open a tunnell between your travis container and opensauce VMs where the browsers are. Then you add some code to quint setup so that you can report to opensauce how test ended. But how you report this in the travis again is still unclear to me.

**Comment by jedateach** [comment]
I think Travis just expects a return code to state that all tests have passed or failed.

You could have Travis run all of the browser types together using testem. 

Or - If you want to list all browsers seperately in Travis, like the node versions currently are, then I think you would need to set an environment variable to the specific browser to test on. That variable can be passed on to the testem command with the -l launcher flag.

**Comment by asturur** [comment]
i ll read better ember approach and try to replicate it.
i do not want the browser tests to spin up for every node env instance

**Comment by jedateach** [comment]
Making some progress FYI:
https://saucelabs.com/open_sauce/user/jedateach
https://travis-ci.org/jedateach/fabric.js/builds/165434180

**Comment by asturur** [comment]
thanks i'll look. yesterday i tried, i followed instructions, i got bad results i was demotivated, i went bug fixing bug/writing code. thank for your efforts.

**Comment by asturur** [comment]
can you keep a pr open? so i see file changes i see what is going on and how.

**Comment by jedateach** [comment]
Yeah no problem

**Comment by asturur** [comment]
To show our appreciation for the work done so far, and to support you in completing it, we posted a bounty of 200$ over it.

**Comment by jedateach** [comment]
Wow, thats awesome - thank you. I'll look at the last issue when I get a chance.

**Comment by jedateach** [comment]
Pull requests appear to be working now. It turns out we don't need to use the travis jwt and sauce-connect addons.

I reduced the NODE versions down to the major version only.
I have also ordered the travis build matrix a bit better so the interesting results are first - I've assume most use of fabric.js will be in chrome.
I've also just selected the latest of the modern browser versions.

I've added the saucelabs badge to the README file.

There are a few failures across different platforms to be addressed.

**Comment by jedateach** [comment]
Some build matrix configurations seem to fail for unclear reasons.

I'm wondering if we keep hitting the sauce labs concurrency limits. We can set concurrency limits within travis, but I'm not sure that would help if there are many pull requests at once.
Here's how: https://docs.travis-ci.com/user/customizing-the-build#Limiting-Concurrent-Builds

**Comment by asturur** [comment]
Hello Jeremy, thanks for bringing till here.
What i would do now is merge in another branch your PR so that we can try it.
I will add you to my account and we will see if it runs on that branch, then we merge to master.
Node has to stay as it is untill we release 2.0, so we keep old version for whoever may be still using it.
could you open a pr on ```mastercopy``` branch?

**Comment by asturur** [comment]
sorry, i see is already good as it is.
Please add back the old node instances and we merged it.
Please support me on mastering how it works so that i will add visual tests ( finally ).

**Comment by jedateach** [comment]
done - but that time it got the intermittent failure. Can you set that travis concurrency setting? or view sauce labs dashboard?
https://travis-ci.org/kangax/fabric.js/jobs/167319567

It would be nice if more info was presented on the command-line output.

**Comment by asturur** [comment]
Jeremy on which timezone are you? would be nice if we can setup a chat / call whatever is ok for you so that you can introduce me a little bit on what is missing / required. I'm in europe, i' m working right now and i cannot put the attention this thing deserves.
Would you contact me on my email? is visible on my github profile.

**Comment by jedateach** [comment]
Yes, I've sent and email.

**Comment by asturur** [comment]
Hello Jeremy any chance to finished this togheter? i m available at any hour if necessary.

**Comment by asturur** [comment]
i keep logged in gitter. so if you popup we can talk. I just did not check good how it works, and need some direction.

**Comment by jedateach** [comment]
What was the solution to this?

I've recently been fixing the testem configuration on the master branch,
which can be configured for cross-browser testing.

**Comment by asturur** [comment]
There wasn't solution since one year, i decided to close and pull back the bounty because i got an email from bounty source about 0% fee limited period.
I had not idea you still worked on it.
I can reopen it back, i sincerly thought it has been abandoned.

**Comment by jedateach** [comment]
Ok - thats fair enough. You weren't to know I was working on this. It's coincidental that I happened to be working on this as it was closed.
A pull request will be coming soon.

I think it's always a good idea to leave a reason for closing an issue.
