### ISSUE TITLE
Is there any way to skip Objects in sendToBack operation?

### ISSUE THREAD

**Issue by shaktippatel** [kangax/fabric.js#3329]
I have created safe margin and cut margin line on canvas

Is there any way to skip Objects (safe margin and cut margin) in sendToBack operation?

**Comment by asturur** [comment]
if you want those object to be always under the other objects ( if this is your request), no there is no built in way. Either render those objects with a svg as background image or try to remove them from the canvas object array and render them differently.

**Comment by halilozanyilmaz** [comment]
@shaktippatel I used following trick, The items:

> 0-Safe Margin
> 1-Object A
> 2-Object B

Below code peace will work because when you trigger `sendToBack `function first time on Object A or B, it moves the Safe Margin to array location 1. Then you can move it back to its previous place. 

```
canvasObj.sendToBack( activeObject );
canvasObj.sendToBack( canvasObj.item(1));
```

**Comment by samritichandel** [comment]
I also want the same functionality, but is stuck how to do it. Any help is appreciated
