### ISSUE TITLE
Textbox.dynamicMinWidth not updated after wrap

### ISSUE THREAD

**Issue by mbyrne00** [kangax/fabric.js#3330]
## Version
1.6.5

## Test Case
http://jsfiddle.net/m7xo9g5e/2/

## Steps to reproduce
 - Type unbroken text until textbox stretches
 - Place cursor in middle and type a space character to force a line break
 - `Textbox.dynamicMinWidth` does not reflect the current longest word width, but the previous longest word width

## Expected Behavior
We would expect that `dynamicMinWidth` should always reflect the longest word width. We are using this field to shrink the textbox width back down where possible if it was previously stretched due to a long word.

If you type another space, then `dynamicMinWidth` is updated correctly.

## Actual Behavior
`dynamicMinWidth` is not updated to represent the shorter words.

If there is a workaround to try to force `dynamicMinWidth` to be re-calculated on `text:changed` event, or use another event that would be great.

**Comment by asturur** [comment]
dynamicMinWidth is always updated everytime dimension of textbox change.
If you examine the property during the after:render event you will see that is in sync.

http://jsfiddle.net/m7xo9g5e/3/
