### ISSUE TITLE
background images of controls are stretched.

### ISSUE THREAD

**Issue by astw** [kangax/fabric.js#3333]
I need to put some border background image to itext control to decorate itext.  But when I resize the itext,  the image is stretched.

I would like to see the effect of border-image-slice in css3, like below.  How can I do it?  or can I add a div into canvas as a workaround? 

http://tympanus.net/codrops/css_reference/border-image-slice/ 
http://jsfiddle.net/FranWahl/8hwnU/

Thank you so much!

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
