### ISSUE TITLE
IText does not react to changes in its 'opacity' property

### ISSUE THREAD

**Issue by ziomio** [kangax/fabric.js#3334]
## Version
1.6.5

## Test Case
https://jsfiddle.net/wrfw0gqh/

## Steps to reproduce
Launch newest Firefox (I have Firefox v49.0.1) and see that IText does not respect changes in *opacity* property. I tested it in Mac OS X 10.9

## Expected Behavior
Text with opacity 0.2 should be almost invisible.

## Actual Behavior
It displays as if opacity == 1, but it was set to 0.2

**Comment by asturur** [comment]
they are messing up with some canvas update i think because also shadow for text got some problem.

**Comment by ziomio** [comment]
If working with canvas directly - there is no problem in Firefox
https://jsfiddle.net/7gxLqecf/

**Comment by asturur** [comment]
You are fooling yourself setting the color with a 0.2 value in opacity

https://jsfiddle.net/7gxLqecf/1/

check corrected filter.

**Comment by ziomio** [comment]
Transparent text is the feature I need.
If the only way to achieve it via setting its color alpha channel to 0.2 like so:
  `ctx.fillStyle = "rgba(0, 0, 0, 0.2)";`
 - then I am OK with it.

**Comment by asturur** [comment]
you may be ok with it. There is still a bug in firefox for the normal opacity.
Unless they fix the bug, yes this is the only way to obtain it.

**Comment by ziomio** [comment]
>There is still a bug in firefox for the normal opacity.
Stupid question, but do they know about this bug? If not - we should inform them!

**Comment by asturur** [comment]
I m also wrong because ctx.opacity is not a context property.

https://jsfiddle.net/7gxLqecf/2/

So there is something strange going on with how fabric draw text and firefox. Because in chrome it is ok, while in firefox no.

**Comment by Aubron** [comment]
Having the same issue in a fabric webapp, affected versions confirmed at 49.0 Firefox Release

**Comment by Aubron** [comment]
This is not fixed in FF 50 Beta or FF 51 Aurora

**Comment by asturur** [comment]
i see it fixed in firefox 49.0.2 that popped up today on my mac.
