### ISSUE TITLE
Image filters are slow

### ISSUE THREAD

**Issue by jbeja** [kangax/fabric.js#3336]
The more filters I put in the filters array in an image the more slow it gets. I suppose it because on each application from the applyFilters method call the applyTo method of all filters objects, which on every examples seems to go over the canvas's image data again and again, correct?

**Comment by asturur** [comment]
yes.
plain js filters are that slow.
we are planning to insert webgl filters but for now i did not have time.

**Comment by jbeja** [comment]
@asturur Is there any recommandation to change the code so all the filters can be apply in one loop?
