### ISSUE TITLE
Text fontStyle doesn't apply in nodejs

### ISSUE THREAD

**Issue by dannyto** [kangax/fabric.js#3338]
Hi there,

I have a problem with fontStyle in "italic" when load text object from json

My code as below:

var fabric = require('fabric').fabric;
var cans = fabric.createCanvasForNode(600, 300);
var json = '{"objects":[{"type":"text","originX":"left","originY":"top","left":53.6,"top":117,"width":160,"height":19.8,"fill":"black","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"square","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":4.58,"scaleY":4.58,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"Text static","fontSize":"20","fontWeight":"bold","fontFamily":"tahoma","fontStyle":"italic","lineHeight":"0.72","textDecoration":"","textAlign":"left","textBackgroundColor":"","charSpacing":0}],"background":""}'
canvas.loadFromJSON(json);
canvas.renderAll();

// output result

![pic](https://cloud.githubusercontent.com/assets/13778373/19264041/61d754fe-8fc9-11e6-85c5-4d59da67ae03.png)

I use fabric 1.6.4.
Anybody ever had this problem ? Or the way to fix it?

Thanks so much!

**Comment by asturur** [comment]
when you first create the object does it render properly?

**Comment by dannyto** [comment]
It render properly when I create the object in web , after I saved it and load in server side, only the fontStyle not work

**Comment by asturur** [comment]
do you have italic font on node? wich wersion of node are you using cairo or pango backed?
Please refere to node-canvas issue tracker to see if there is something already open in the topic. Looks like not a fabricjs issue.

**Comment by dannyto** [comment]
I use version 1.6.4.
I dont have italic font on node.
I just wonder why it work on chrome browser but not work on nodejs.

**Comment by asturur** [comment]
Chrome just render fake fonts when it does not have the proper style loaded.
