### ISSUE TITLE
BUG on method __toDataURLWithMultiplier on class canvas

### ISSUE THREAD

**Issue by Terroristadoomad** [kangax/fabric.js#3339]
scaledHeight = (cropping.width || this.getHeight()) * multiplier,

the correct should be : 

scaledHeight = (cropping.height|| this.getHeight()) * multiplier,

it should use height for height croping, if not we get a square.

**Comment by asturur** [comment]
we fixed it couple of hour ago. soon 1.6.6 fix release

**Comment by Terroristadoomad** [comment]
Thx much apreciated.
