### ISSUE TITLE
Feature Request: Setting selectable area to only *inside* a clipTo

### ISSUE THREAD

**Issue by Aubron** [kangax/fabric.js#3340]
am currently using Fabric.js for a web application that allows users to input and manipulate the canvas objects in a structured way.

One of our mechanisms for providing structure is to have 'bounding boxes' into which a user can place an image. When an image is placed into these, they can be panned and zoomed, but are clipped to the original bounding box's size and location.

Example: [A clipped image](https://i.stack.imgur.com/zMdHq.png)

Here we see the clipped area, with its controls visible outside of it's clipped zone.

This is fine. The user can pan the image around, and the clipping box stays static. We are find with this.

However, if the client adds another image, and this image is underneath the area where the first image spans (but is not visible due to clipping) we cannot select the second object.

Example:

[A selection obscured, clipped image](https://i.stack.imgur.com/DRrdf.png)

Here the face image is underneath where the golf image extends, outside of its clip range. The face image is not selectable without deselecting. One can imagine that if all three are here, it's possible to obscure the selection area of the face image such that deselection is impossible, requiring moving or of the other two images to reach it.

I've created a jsfiddle to illustrate this in a sandbox environment: http://jsfiddle.net/Aubron/jjLe9wps/89 . Note that if you select the google logo, the pug isn't selectable until the google logo is moved awkwardly, because it's extended area overlaps the pug. I'm hoping that I'm not alone in thinking that at least an option to allow selection events to pass through clipped areas of images would be helpful.

As a backup, I've posted this to stackoverflow to try and figure out a work-around, as this is needed to have a good client experience with the product.
https://stackoverflow.com/questions/39983812/clip-selection-area-to-clipto-fabric-js

**Comment by Aubron** [comment]
Turns out this is a feature of perPixelTargetFind, and I wasn't aware, I assumed it would only work for png transparency, not clipping transparency.

Thanks!

**Comment by asturur** [comment]
well there are many way to approach this thing.
I have in my todo list the introduction of cropping so that you just crop the image. giving a x,y value starting from top and changing width and height.
Sadly i did not have time and probably i will not have soon.
What is stopping me is the actual support of svg features but maybe i can work around it.

**Comment by asturur** [comment]
just to mention there will be not interface for mouse cropping, there will be just properties to crop an image. oh well... will see.

**Comment by Aubron** [comment]
Hey it would be useful to me!
