### ISSUE TITLE
Fabric is not working on node. TypeError: Cannot read property 'devicePixelRatio' of undefined

### ISSUE THREAD

**Issue by peleteiro** [kangax/fabric.js#3342]
## Version
1.6.5

## Test Case
```node -e "require('fabric')" && echo 'ok' ```

## Steps to reproduce
Run: ```node -e 'require("fabric")'```

## Expected Behavior
No error

## Actual Behavior
```
~/Projects/biblebox/site (master)$ node -e 'require("fabric")' && echo 'ok'
/Users/peleteiro/Projects/biblebox/site/node_modules/fabric/dist/fabric.js:73
fabric.devicePixelRatio = fabric.window.devicePixelRatio ||
                                       ^

TypeError: Cannot read property 'devicePixelRatio' of undefined
    at Object.<anonymous> (/Users/peleteiro/Projects/biblebox/site/node_modules/fabric/dist/fabric.js:73:40)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
```

**Comment by peleteiro** [comment]
I figure it out. canvas, jsdom and xmldom are now optional dependencies, and they are need to work on node.

It would be good to point that out on docs or error message.

**Comment by asturur** [comment]
we moved to optional to let people work with npm on normal web project where the node dependncies are not required. Otherwise a fail installing canvas would stop the application install

**Comment by jeroengijsman** [comment]
@asturur we are still having this issue.

my dependencies:

```
  "dependencies": {
    "canvas": "1.4.x",
    "fabric": "1.7.x",
    "jsdom": "9.8.x",
    "xmldom": "0.1.x"
  },
```

im still getting the `TypeError: Cannot read property 'devicePixelRatio' of undefined` error

**Comment by asturur** [comment]
on what line  where? does newest jsdom have window?

**Comment by kevinyun** [comment]
Anyone have any updates? I am stuck on this issue
