### ISSUE TITLE
Setting % to the Canvas Width and Height

### ISSUE THREAD

**Issue by abnersouzarocket** [kangax/fabric.js#3344]
## Version
1.6.5

## Steps to reproduce
**Create a HTML with a div and a canvas:**

`<div style="width: 200px; height: 200px">
	   <canvas id="c" style="border: 1px solid black"></canvas>
    </div>`

**Initialize the fabric.Canvas**
`
var canvas = new fabric.Canvas('c', {
				isDrawingMode: true,
				freeDrawingCursor: "default",
				backgroundColor: "transparent"
			});
`
**Set the dimensions to with percentage/px/em and set cssOnly true**
`canvas.setDimensions({width: '100%', height: '100%'}, {cssOnly: true});`

**Open the browser, and draw on the canvas.**

## Expected Behavior
The Canvas should have css sizing only and it should not be stretched

## Actual Behavior
![image](https://cloud.githubusercontent.com/assets/20269820/19343217/2cffceae-912d-11e6-913d-c18272407763.png)

Checking the HTML, It sets width: 300 and height: 150, looks like a default values to it.
![image](https://cloud.githubusercontent.com/assets/20269820/19343323/b08a0442-912d-11e6-8e80-6a324fb50b05.png)

The same issue happened if try to set px. If I just set a number for width and height without the cssOnly option works fine:
`canvas.setDimensions({width: 300, height: 300});`
![image](https://cloud.githubusercontent.com/assets/20269820/19343406/0315cfe8-912e-11e6-8e0c-d0a8b84ab83b.png)

**Comment by asturur** [comment]
everything is fine here.
Normal canvas is 300x150 by specs.
When you apply css only dimensions it get stretched, by css.
