### ISSUE TITLE
IText bad behavior when you exit edit mode

### ISSUE THREAD

**Issue by samael205** [kangax/fabric.js#3346]
## Version
1.6.5

## Test Case
IText bad behavior when you exit from edit mode.

## Steps to reproduce

Create a new itext instance, with any text. Edit clicking in it, and exit from edit mode.

## Expected Behavior
the itext element must return to be able to handle with the mouse

## Actual Behavior

You can not move it on the canvas, leaving no operating controls

**Comment by asturur** [comment]
i cannot reproduce on current master. Yesterday i was able for a little bit, today completely not. Could you please make a fiddle again to help me find it out? so we can fix it.

**Comment by asturur** [comment]
there is a mouse:move event bug anyway, the event mouse move queque builds up and does not get deregistered, i ll look into that in mean time.

**Comment by asturur** [comment]
Please check again with release 1.6.6 in case you do not see the problem close the issue.
If you see it, please report any console message or make a non working fliddle that show the problem on 1.6.6

**Comment by samael205** [comment]
Ok, i Will check tomorrow. Many thanks

**Comment by samael205** [comment]
Works Fine. Thanks Asturur, close the issue
