### ISSUE TITLE
Group "controls" stuck with moving-style on click

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3348]
Sorry for the poor issue label, i couldn't find the right sentense to describ the bug content.
It's a bug in the version 1.6.5, if i try with the 1.6.2 version it's working fine.

Here is the bad behaviour (it looks like a nimor bug) :
- You select multiples objects in the canvas. 
=> You got a blue square for the group selection
- You click on the group selection (not on an object but still in the group selection area - red dot in the screenshot)
=> The blue square is now with an half opacity (it's the moving style)
=> The opacity should come back to normal once your release the click (because there is no movement so we shouldn't have the moving style), but it's stuck with the moving style.

Bug in v1.6.5
http://codepen.io/anon/pen/mAGRxB

Ok in v1.6.2
http://codepen.io/anon/pen/wzEgYE

For example if you click on the red dot the controls group style is stuck with the blue with half transparency : 

![image](https://cloud.githubusercontent.com/assets/16743322/19419145/28d50d84-93d1-11e6-8dad-77baa2e05a7c.png)

**Comment by ncou** [comment]
Perhaps the mouse:move bug mentionned in the issue :
https://github.com/kangax/fabric.js/issues/3346

**Comment by asturur** [comment]
i cannot reproduce. It works fine on both the codepen you posted.

**Comment by ncou** [comment]
I made the test with firefow, and IE11, and i got the bug only with chrome.
My version is "Version 53.0.2785.143 m", but i don't understand why it's work with the fabric.js v1.6.2 and not with v1.6.5.

**Comment by asturur** [comment]
i m on chrome 54 and i cannot see the problem.
Between 1.6.2 and 1.6.5 lot of things changed as usual. Can you try with the fresh released 1.6.6?

**Comment by ncou** [comment]
hi,

My browser updated to the Version 54.0.2840.59 m, and i can't reproduce the bug.
I tried to test on some alternative browser (like Baidu Browser) but it's also working fine.

Looks like i made you lost your time :(
I will close this ticket. In any case, thank you for your investigation.
