### ISSUE TITLE
IText, RTL text bug when applying color on selection

### ISSUE THREAD

**Issue by noammazuz** [kangax/fabric.js#3352]
## Version
1.6.5

## Test Case
After adding IText with RTL text and selecting part of the text to set color or bg color, the text not display correctly. 

## Steps to reproduce
Add ITEXT with "היי מה המצב?"
Then select only part of the sentence.
Set color to this part

## Expected Behavior
The text need to stay the same and only the selected part need to be effected by the color

## Actual Behavior
![bugggg](https://cloud.githubusercontent.com/assets/5702207/19439748/f5d303ca-9487-11e6-94c7-e14040372200.JPG)

Text not display correctly.

**Comment by asturur** [comment]
RTL is unsupported at the moment.
When i say unsupported i mean that i m not yet went over it and current code does not have capability to handle it properly.

**Comment by noammazuz** [comment]
ok thank you, i will try to help adding support to RTL:)

**Comment by YaakovHatam** [comment]
@noammazuz  please look at the issue #2374 i am developing a RTL version please test it
