### ISSUE TITLE
Apply filters with Workers HTML5

### ISSUE THREAD

**Issue by samael205** [kangax/fabric.js#3353]
We can use workers to apply filters, using workers in HTML5 to prevent the user interface to crash.

it can be possible, encapsulating application logic filter in a worker?

regards.

**Comment by asturur** [comment]
yes probably we can. My effort lately have been in enabling webgl filtering that is very fast.
it will not be released soon but it will be released.

**Comment by asturur** [comment]
The idea is supporting webgl ( released in days , available in the beta build ).
Web workers are out of question for now.

**Comment by samael205** [comment]
Thanks!
