### ISSUE TITLE
changing font in fabricjs results in text without color

### ISSUE THREAD

**Issue by nermion** [kangax/fabric.js#3354]
I am using fabricjs to implement meme generator. I added option to change font. Everything works except when the font is changed for first time then I get text without color, just with outline. It looks like this: [https://i.stack.imgur.com/HkQDt.png](https://i.stack.imgur.com/HkQDt.png)
After I change again and change back to same font then text has color.

Here is my code:
```
$('#font').on('change', function() {
    topText.set({fontFamily: this.value});
    bottomText.set({fontFamily: this.value});
    canvas.renderAll();
});
```

you can test it here [http://imageshare.code4fun.io/meme/existing/4](http://imageshare.code4fun.io/meme/existing/4)

## Version
1.6.5

## Test Case
http://imageshare.code4fun.io/meme/existing/4

## Steps to reproduce
Create iText
```
var topText = (new fabric.IText('Top Text', {
          fontFamily: 'impact',
          left: 200,
          top: 30 ,
          stroke: '#000',
          fill: '#fff',
          textAlign: 'center',
          fontSize: 70,
        }));
```

add select inside html

```
<select class="form-control custom" id="font">
    <option value="Impact">
        Impact
    </option>
    <option value="PT Sans">
        PT Sans
    </option>
    <option value="Montserrat">
        Montserrat
    </option>
    <option value="Merriweather">
        Merriweather
    </option>
</select>
```

```
add select change listener and change font
        $('#font').on('change', function() {
            console.log("changing font: "+this.value);
            topText.set({fontFamily: this.value});
            bottomText.set({fontFamily: this.value});
            canvas.renderAll();
        });
```

## Expected Behavior
Font is changed and fill of the text remains.
## Actual Behavior
Font is changed but fill of text dissappears.

**Comment by nermion** [comment]
Solved

**Comment by barisdemirhan** [comment]
Could you share the solution? Thank you.
