### ISSUE TITLE
JavaScript Syntax error with proxies that change HTML responses

### ISSUE THREAD

**Issue by yaronuliel** [kangax/fabric.js#3355]
Though this is not a core Fabric.js issue - it can be treated as one, to prevent errors in some malfunctioning browsers

When the Fabric.js library is loaded on a browser with HTTP proxy that manipulates HTML responses based on a simple search and replace (e.g. organizational tools, time tracking systems or malwares) - there is a syntax error due to the appearance of an HTML structure in the JavaScript source [See this line](https://github.com/kangax/fabric.js/blob/28c2654a2310a675f22f8b500fd5984fd03de4ff/HEADER.js#L17) 
Which turns into

`.jsdom("<!DOCTYPE html><html><head><script src="http://example.com/added_script.js"></script></head><body></body></html>");`
And leads into syntax error (quotations inside string)
## Version

1.6.5
## Steps to reproduce

Load the javascript library with some proxy tool that manipulates HTML based on HTML structure
## Expected Behavior

The library should be loaded without any syntax error
## Actual Behavior

Browser throws a JavaScript syntax error exception - and the library doesn't load at all (nor the rest of the page's JavaScript in some situations)
## Suggested Solution

Don't store the initial DOM structure as a simple HTML string. Instead, use an encoded string and decode it

`.jsdom(decodeURIComponent("%3C!DOCTYPE%20html%3E%3Chtml%3E%3Chead%3E%3C%2Fhead%3E%3Cbody%3E%3C%2Fbody%3E%3C%2Fhtml%3E"));`

**Comment by asturur** [comment]
i ll give it a shot. if node does not complain i m fine with it.
