### ISSUE TITLE
canvas.clear() makes the canvas background transparent

### ISSUE THREAD

**Issue by paulcredmond** [kangax/fabric.js#3356]
## Version
1.6.5+

## Test Case
https://jsfiddle.net/6z5vay2e/

## Steps to reproduce
Clear the canvas using canvas.clear()

## Expected Behavior
canvas.clear() does not affect the background color

## Actual Behavior
canvas.clear() removes the canvas background color

**Comment by paulcredmond** [comment]
It's possible to set the background colour and render the canvas after it has been cleared, I'm just wondering why this is happening now. This wasn't present in earlier versions.

**Comment by cmnt** [comment]
Hello,

This is normal behavior : http://fabricjs.com/docs/fabric.Canvas.html#clear 
> Clears all contexts (background, main, top) of an instance

I prefer that it keeps the background

**Comment by asturur** [comment]
Well, i did not write that function in first place.
One user some weeks ago came here and complained the opposite.
Then i read the jsdoc part and it said that cleared everything, and i just did it.

So in my opinion, clear is ok like it is.
On canvas we objects, background, backgroundColor, overlya, overlaycolor.
Everyone of them can be cleared setting a property, so either clear does everything or it does not have any reason to exist.

I m open to discussion anyway.

**Comment by stephenkillingsworth** [comment]
I would definitely say if canvas.clear() clears all properties, then there needs to be another function, like canvas.clearObjects(), to handle the far-more-typical use case of simply removing all objects from the canvas.

**Comment by asturur** [comment]
does not canvas.remove(canvas.getObjects()) work?

**Comment by asturur** [comment]
no, it does not, and you cannot do 
```
canvas.forEachObject(function(o){
  o.remove();
})
```

**Comment by paulcredmond** [comment]
In my mind I would think the `clear()` method would delete all objects and not the canvas properties. There is some subjectivity here, but I understand that is by design and so is not a bug.

**Comment by cAstraea** [comment]
Can we have a parameter for this without removing the background ? Like in previous 1.5 version ? http://jsfiddle.net/InferOn/fx05t621/2/

**Comment by asturur** [comment]
Well to remove all objects and nothing else you can still do `canvas.remove(...canvas.getObjects())` or `canvas.remove.apply(canvas, canvas.getObjects())` too many flags or options are complicated.

**Comment by milahu** [comment]
> Well to remove all objects and nothing else you can still do `canvas.remove(...canvas.getObjects().concat())` or `canvas.remove.apply(canvas, canvas.getObjects().concat())`

thanks for the snippet, can we add this to the docs of `canvas.remove()` ?

also, why do we need `concat()` ?  
why cant we just say `canvas.remove(...canvas.getObjects())` ?
concat makes no difference in my case

also we should set `canvas.renderOnAddRemove = false` for this, no?

**Comment by asturur** [comment]
concat is not needed, since long getObjects() returns always a new array.

concat() with no arguments is a quick way to return a copy of an array, similarly to slice(0).

**Comment by oroafrica** [comment]
why not just create a new canvas and initialize with original properties
