### ISSUE TITLE
how can i use a image as backgroundColor,  witch CORS problem

### ISSUE THREAD

**Issue by syaka-yin** [kangax/fabric.js#3358]
i use a image repeat as backgroundColor, but the image is fetch from a cdn server,  how can i solve this problem ？

is this code be fine ? thank you
```
canvas.setBackgroundColor({
  source:  // cdn image resouce,
  repeat: 'repeat',
  crossOrigin: 'anonymous',
  originX: 'left',
  originY: 'top',
}, canvas.renderAll.bind(canvas));
```

**Comment by asturur** [comment]
http://fabricjs.com/docs/fabric.StaticCanvas.html

We have documentation to read before posting. There is an example for your use case.
