### ISSUE TITLE
font kerning not showing in SVG

### ISSUE THREAD

**Issue by archirayan3** [kangax/fabric.js#3359]
Hello,

I have some fonts which supports kerning. and i am writing some texts like "AV", "Ty" which shows kerning on canvas. if you see this image https://www.printhubpro.co.uk/images/canvas.png you can see how some characters are overlapping. that shows font kerning(we can say that fabric supports kerning here?). Now while i am exporting canvas to SVG it looks like this https://www.printhubpro.co.uk/images/svg.png you can see spacing is different in this image. However i checked SVG and seems like fabricJs generates wrong X and Y co-ordinates for each kerned letter. 

Here is the fiddle https://jsfiddle.net/60uh4wop/3/
Just follow below steps to see bug.

(if you cant see any text in canvas then just click on canvas. it will load fonts in canvas)
1)double click on textbox to edit it, and add any letter at the end.
2)click on "generate svg button"
3)you can see "Ty" is different in SVG
Here is the video showing steps
http://screencast.com/t/gYVMk4Gj

I am facing this issue for printing purpose. If you compare both SVG you will see difference of font spacing in canvas and in SVG.

**Comment by asturur** [comment]
links not working.
Please open a fiddle with your problem or the issue will be closed.
We need clear fiddle where there is just the code that replicate the problem.

**Comment by archirayan3** [comment]
okay let me upload it somewhere

**Comment by archirayan3** [comment]
Here it is, How it is showing in canvas, https://www.printhubpro.co.uk/images/canvas.png And how it is showing in SVG https://www.printhubpro.co.uk/images/svg.png

**Comment by archirayan3** [comment]
Here is the fiddle https://jsfiddle.net/60uh4wop/3/
Just follow below steps to see bug.

(if you cant see any text in canvas then just click on canvas. it will load fonts in canvas)
1)double click on textbox to edit it, and add any letter at the end.
2)click on "generate svg button"
3)you can see "Ty" is different in SVG
Here is the video showing steps
http://screencast.com/t/gYVMk4Gj

**Comment by archirayan3** [comment]
Here is the another fiddle which may explain more 
https://jsfiddle.net/60uh4wop/5/

**Comment by asturur** [comment]
https://jsfiddle.net/60uh4wop/6/

kenring is repsectd if there is no style in text. If there is some style the fonts get rendered individually and kerning disappear, both on canvas and svg.

**Comment by archirayan3** [comment]
If you see this [image](http://printhubpro.co.uk/images/error.png). you can see kerning is not disappearing in canvas. how can we disable that?

**Comment by asturur** [comment]
in your fiddle numbered 3, the text has some empty style..that is why the kerning was not respected. is not a choice, is a consequence if rendering font char by char

**Comment by archirayan3** [comment]
So if i just double click on textbox and add some character will generates empty styles. right?
