### ISSUE TITLE
Textbox shows wrong cursor position when font has kerning

### ISSUE THREAD

**Issue by archirayan3** [kangax/fabric.js#3360]
Hello,

I have [fiddle](https://jsfiddle.net/60uh4wop/5/)
If you edit textbox and check the position of "Ty" in line 1, you will see cursor is so far the "y"
See this [image](https://www.printhubpro.co.uk/images/cusror.png)

So when font has kerning, text position is different and cursor goes wrong in position.
Is there any way to disable kerning in fabric? or we should improve fabric?

**Comment by asturur** [comment]
The svg is correctly generated if there is no style for the object.
Fabric measure chars individually and does not know about kerning.
I do not think there is an easy way to read a kerning from a font file. It there is, i would like to implement it.

**Comment by archirayan3** [comment]
If you see this example [here](https://www.printhubpro.co.uk/text-to-svg/test/browser.html). Then click "get svg". you can see font has not kerning. Now tick checkbox for "kerning" and again click "get svg". YOu will see that font is kerned now. So they have some way in script to read kerning from font.

**Comment by asturur** [comment]
please check #3377
