### ISSUE TITLE
Error while loading data from JSON using loadFromDatalessJSON

### ISSUE THREAD

**Issue by asgriksen** [kangax/fabric.js#3361]
Hi.

I'm trying to implement auto-save feature for my designing platform using fabrics.js.

I'm using `toDatalessJSON()` and `loadFromDatalessJSON()` to save and restore the work.

When I have SVG image in the work, `toDataLessJSON()` generates object of item type `shape` and I can save it in the browser cache.

But when I'm trying to restore the canvas from the above JSON using `loadFromDatalessJSON()`, I'm getting following error.

`Uncaught TypeError: Cannot read property 'async' of undefined`

Here's the fiddle for that.

https://jsfiddle.net/asgriksen/mhf2kqzo/14/

**Comment by asturur** [comment]
there is strange stuff in that json you posted on the fiddle. It looks like this is not a fabricjs toObject / toJSON string. how did you saved to JSON?

**Comment by asgriksen** [comment]
@asturur I used `toDatalessJSON()` to get that JSON string

**Comment by asturur** [comment]
```
{"objects":[{"type":"i-text","originX":"left","originY":"top","left":100,"top":150,"width":230.05,"height":228.71,"fill":"#333","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"lorem ipsum\ndolor\nsit Amet\nconsectetur","fontSize":40,"fontWeight":"normal","fontFamily":"Helvetica","fontStyle":"","lineHeight":1.16,"textDecoration":"","textAlign":"left","textBackgroundColor":"","charSpacing":0,"styles":{"0":{"0":{"fill":"red","fontSize":20},"1":{"fill":"red","fontSize":30},"2":{"fill":"red","fontSize":40},"3":{"fill":"red","fontSize":50},"4":{"fill":"red","fontSize":60},"6":{"textBackgroundColor":"yellow"},"7":{"textBackgroundColor":"yellow"},"8":{"textBackgroundColor":"yellow"},"9":{"textBackgroundColor":"yellow"}},"1":{"0":{"textDecoration":"underline"},"1":{"textDecoration":"underline"},"2":{"fill":"green","fontStyle":"italic","textDecoration":"underline"},"3":{"fill":"green","fontStyle":"italic","textDecoration":"underline"},"4":{"fill":"green","fontStyle":"italic","textDecoration":"underline"}},"2":{"0":{"fill":"blue","fontWeight":"bold"},"1":{"fill":"blue","fontWeight":"bold"},"2":{"fill":"blue","fontWeight":"bold"},"4":{"fontFamily":"Courier","textDecoration":"line-through"},"5":{"fontFamily":"Courier","textDecoration":"line-through"},"6":{"fontFamily":"Courier","textDecoration":"line-through"},"7":{"fontFamily":"Courier","textDecoration":"line-through"}},"3":{"0":{"fontFamily":"Impact","fill":"#666","textDecoration":"line-through"},"1":{"fontFamily":"Impact","fill":"#666","textDecoration":"line-through"},"2":{"fontFamily":"Impact","fill":"#666","textDecoration":"line-through"},"3":{"fontFamily":"Impact","fill":"#666","textDecoration":"line-through"},"4":{"fontFamily":"Impact","fill":"#666","textDecoration":"line-through"}}}},{"type":"i-text","originX":"left","originY":"top","left":400,"top":150,"width":124.53,"height":150.06,"fill":"#333","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"foo bar\nbaz\nquux","fontSize":40,"fontWeight":"normal","fontFamily":"Helvetica","fontStyle":"","lineHeight":1.16,"textDecoration":"","textAlign":"left","textBackgroundColor":"","charSpacing":0,"styles":{"0":{"0":{"fill":"red"},"1":{"fill":"red"},"2":{"fill":"red"}},"2":{"0":{"fill":"blue"},"1":{"fill":"blue"},"2":{"fill":"blue"},"3":{"fill":"blue"}}}}],"background":""}
```

This is a standard ToDatalessJSON string from fabricjs.
You is very different, it looks like actually serialized the real object without passing fro the toJSON method.
You have in json string also the occords, the doubleclick times.
Something is wrong on your code to serialize.
Can you share it?

**Comment by asgriksen** [comment]
Oh, I saved extra attributes.

`var bulk = iModel.runtime.design.cPage.canvas.toDatalessJSON(["__skipDimension", "oCoords", "minScaleLimit", "editable", "_textLines", "__lineWidths", "__lineHeights", "__maxFontHeights", "__widthOfSpace", "_cacheLinesWidth", "__lastClickTime", "__lastLastClickTime", "__lastPointer", "originalState", "__fontSize", "__fontWeight", "__fontFamily", "__fontStyle", "__lineHeight", "__stroke", "__strokeWidth", "__text", "__textAlign", "skipTextAlign", "_controlsVisibility", "reference", "fillData", "title", "vd", "chain", "tLocked", "includeInForm", "eLocked", "isReference", "hideContext", "selectable", "evented", "lockScalingY", "lockScalingX", "lockRotation", "lockMovementY", "lockMovementX"]);`

**Comment by asturur** [comment]
https://jsfiddle.net/mhf2kqzo/15/

you have some wrong type: ```shape``` in the code. Probably you do not have a shape class or you implemented it in wrong way.

**Comment by asgriksen** [comment]
It turned to be my fault.
http://stackoverflow.com/questions/24384804/fabric-js-subclassing-fabric-group-error-cannot-read-property-async-of-und
