### ISSUE TITLE
Custom fonts issue in Chrome

### ISSUE THREAD

**Issue by DangerD256** [kangax/fabric.js#3362]
## Version
1.6.6

## Test Case
http://mediatours.ca/fabric.html

JSFIDDLE Added;
http://jsfiddle.net/tkxkp609/

## Steps to reproduce
Load template using loadFromJSON

## Expected Behavior
All looks fine like as in Firefox =)

## Actual Behavior
Custom webfont shows as Arial (or some other default page font) on some textboxes, when clicking on it, font changes to correct one, but still has issue with center positioning at all textboxes even with correct font.

Also getting those errors in console:
Failed to decode downloaded font: URL
OTS parsing error: invalid version tag

Seems like it's not fabric js issue, but i need somehow fix that bug...)

**Comment by archirayan3** [comment]
can you please set the fiddle for that? so we can assist you in detail.

**Comment by ncou** [comment]
plz create a fiddle with your error.
From memory i got a problem like this because the custom font was not fully loaded when the canvas was showed, and when you click the textbox it could force a "render()" so the font is show correctly.

Try something like this in your html "head" section (change with the name of you custom fonts like "MinionPro"...etc)  :

<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
   <script>
     WebFont.load({
       google: {
         families: ['Droid Sans', 'Anton', 'Shadows Into Light']
       },
       active: function(){ 
           //when fonts loaded, refresh the canvas
           canvas.renderAll();
         }
     });
   </script>

Let us know if this work for you.

**Comment by DangerD256** [comment]
The problem is that the fontloader didn't have some custom fonts, so that's not a solution.

http://jsfiddle.net/tkxkp609/

**Comment by asturur** [comment]
you have to use a fontloader that inform you when the font finished loading.
There are couple that i know of and one is specific for google font, another is more generic.
https://github.com/typekit/webfontloader
i used this and it works good.

**Comment by DangerD256** [comment]
After update to latest version text position stopped work well in firefox also, previous fabric js version worked well (except bug that some elements was not shown after loading from json)
![untitled](https://cloud.githubusercontent.com/assets/17032489/19651017/f45c553c-9a13-11e6-8b24-1eec23a90a65.jpg)

**Comment by DangerD256** [comment]
> you have to use a fontloader that inform you when the font finished loading.
> There are couple that i know of and one is specific for google font, another is more generic.
> https://github.com/typekit/webfontloader
> i used this and it works good.
I tried to use fontloader and than make calls to create fabricjs canvas or tried to make 10 seconds timeout to ansure all is loaded (in Firefox is solves this problem which appears only sometimes), but nothing helps with chrome...

**Comment by asturur** [comment]
please you have to give us a ```small and reproducible use case```. Because when i have to choose if read lot of code from your app or fix a small bug clearly shown from someone else, i choose the second.

**Comment by DangerD256** [comment]
Updated fiddle with 5 seconds delay and i've moved :
http://jsfiddle.net/tkxkp609/4/

A bit cleared part of code, only left decode part of saved example and zoomout function to resize canvas as it too big to check issue

**Comment by asturur** [comment]
how do i resize canvas? it looks fine to me

**Comment by ncou** [comment]
I have add the code from my first post, and it's work fine : 

http://jsfiddle.net/tkxkp609/8/

PS :
I think your setTimeout is useless because you load the canvas after 5 seconds. You should load the canvas and use a setTimeout on a renderAll() call.

does this help ?

**Comment by DangerD256** [comment]
It doesn't help since some fonts like trajanpro is not available in google fonts and i need them to load locally

**Comment by asturur** [comment]
if you have fonts locally the same logic apply.
Create a font face for the browser to see the font.
Make the browser load it from yoir domain.
