### ISSUE TITLE
fireRightClick: true works not on fabric.Group

### ISSUE THREAD

**Issue by kurtknippschild** [kangax/fabric.js#3364]
I have on my canvas to objects, one fabric.Group und one fabric.Rect

Here my code:
var canvas = new fabric.CanvasEx('imsCanvas', { selection: true, preserveObjectStacking:true, stopContextMenu: true, });

```
    task[task_nr] = new fabric.Rect({
        width: 120,
        height: 60,
        angle: 0,
        rx: 10, 
        ry: 10,
        fill: 'rgba(0,0,0,0.0)',
        strokeWidth: 2, 
        stroke: 'rgb(0,0,0)',
          fireRightClick: true,
          originX: 'center',
          originY: 'center'
      });

        task_text[task_nr] = new fabric.IText(activities_1_text, {
          fontSize: 10,
          fontFamily: 'Arial',
          textAlign: 'center',
          hasBorders: true,
          fireRightClick: true,
          originX: 'center',
          originY: 'center'
        });

        task_group[task_nr] = new fabric.Group([ task[task_nr], task_text[task_nr] ], {
        transparentCorners: false,
        hasRotatingPoint: false,
          lockScalingX: true,
          lockScalingY: true,
          left: 10,
          top: 10,
          hasBorders: false,
          cornerColor: 'rgba(166,32,72,0.5)',
          cornerSize: 8,
          fireRightClick: true,
          imsID: 'global_ctx_nr_' + global_ctx_nr,
          imsOBJ_ID: '0',
            imsType: 'activitie',
            imsOG_ID: '0',
            imsOG_NAME: '0',
            imsOG_ID_VIRTUELL: '0',
            imsOK_ID: '0',
            imsOBJ_NAME: '0'
        });
        task_group[task_nr].setControlsVisibility({tl: false, tr: false,bl: false, br: false,});

    subtask[subtask_nr] = new fabric.Rect({
        width: 120,
        height: 60,
        angle: 0,
        rx: 10, 
        ry: 10,
        fill: 'rgba(0,0,0,0.0)',
        strokeWidth: 2, 
        strokeDashArray: [5, 3],
        stroke: 'rgb(0,0,0)',
          //originX: 'center',
          //originY: 'center'
        transparentCorners: false,
        hasRotatingPoint: false,
          lockScalingX: false,
          lockScalingY: false,
          left: 10,
          top: 10,
          hasBorders: false,
          cornerColor: 'rgba(166,32,72,0.5)',
          cornerSize: 8,
          fireRightClick: true,
          imsID: 'global_ctx_nr_' + global_ctx_nr,
          imsOBJ_ID: '0',
          imsType: 'activitie'
      });
```

After save to DB with:
            var imsCanvasInhalt = JSON.stringify(canvas.toJSON(['fireRightClick', 'imsID', 'imsOBJ_ID', 'imsType','imsOG_ID', 'imsOG_NAME', 'imsOG_ID_VIRTUELL', 'imsOK_ID', 'imsOBJ_NAME', '_controlsVisibility', 'hasRotatingPoint', 'hasBorders', 'cornerSize', 'cornerColor', 'borderColor', 'transparentCorners', 'lockScalingX', 'lockScalingY']));

and read from DB with:
                canvas.loadFromJSON(<%= diaDiagramm %>, canvas.renderAll.bind(canvas));

RightClick works only on fabric.Rect.
Here my code for the RightClick:

```
  canvas.on('mouse:down', function (options) {
      //console.log('canvas mousedown');
      if (options.e.which === 3) {
          console.log('Canvas right mouse down.');
                var aktivesObjekt = canvas.getActiveObject();
                        var imsType = aktivesObjekt.get('imsType');
                        console.log('imsType = ' + imsType);
                        if(imsType === 'activitie') {
                        console.log('2 imsType = ' + imsType);
                        var aPosX = aktivesObjekt.get("left");
                        var aPosY = aktivesObjekt.get("top");
                        var aPosW = aktivesObjekt.get("width");
                        var aPosH = aktivesObjekt.get("height");
                            var posX = aPosX + aPosW;
                            var posY = aPosY + aPosH;
                        console.log('posX = ' + posX);
                        console.log('posY = ' + posY);
                            $('#contextMenueActivities').css('top', posY);
                            $('#contextMenueActivities').css('left', posX);
                            $('#contextMenueActivities').css('display', 'block');
                        }
                        else
                            {
                                                            console.log('3imsType = ' + imsType);
                            }              
      }
  });
```

**Comment by asturur** [comment]
please make a fiddle. i cannot help otherway. i need to sit, try, check, flag as bug or close.

**Comment by kurtknippschild** [comment]
Hi Andrea,

here is the Url for the fidele:
https://jsfiddle.net/KurtKnippschild/my0uo4jb/
<https://jsfiddle.net/KurtKnippschild/my0uo4jb/21/>

But on the fidele fireRightClick works also on fabric.Group.
I dont know why not in my local project.
Somethimes after a rightclick you can see the ContextMenue from the browser.

VG Kurt

mit freundlichen Grüßen
 
Kurt Knippschild
 
Kurt Knippschild
Am Kränzenberg 17
64646 Heppenheim
 
Telefon:            +49 6252 9679817
Mobil:              +49 170 3851198
Telefax:            +49 6252 670611
EMail:              kurt@knippschilds.de
<mailto:kurt@ingenieurbuero-knippschild.de>
Internet:            www.knippschilds.de
<http://www.ingenieurbuero-knippschild.de/>

Von:  Andrea Bogazzi <notifications@github.com>
Antworten an:  "kangax/fabric.js"
<reply+015cbfe852f011e08bc1770a1dd0ea8188dbef62f444756b92cf00000001142446189
2a169ce0b01fce5@reply.github.com>
Datum:  Sonntag, 23. Oktober 2016 um 11:34
An:  "kangax/fabric.js" <fabric.js@noreply.github.com>
Cc:  Kurt Knippschild <kurt@knippschilds.de>, Author
<author@noreply.github.com>
Betreff:  Re: [kangax/fabric.js] fireRightClick: true works not on
fabric.Group (#3364)

**Comment by asturur** [comment]
The mouse:down event was stopped before because it was not left click.
I just made the code flow normally in case of a different button.
Now the point is that if sometimes you see the canvas context menu on right click, it could mean that you have some other function registered to the event that is not stopping the event from firing the default action.

Without a failing fiddle i cannot really investigate anything.

**Comment by asturur** [comment]
any chance to get a failing fiddle?
