### ISSUE TITLE
[Feature Request] Image object getContext(2D)

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3365]
feature request :

Hi,

Do you think it's possible to have a getContext() function on the image object ? from my comprehension, image object are also canvas. and you can get the imageData using a filter once the "applyFilter()" function is called.

I want to get the dominant color from the image (and apply it to the canvas background), and to get the pixels array, i need the context.
The filter mecanisum can manipulate the pixel array but not interact with the canvas (except if you set a global var for the canvas, but it's a bit dirty coding).

Do you think it's possible to add a function to access directly to the canvasEl.getContext(2D) function on the image object ?

Think you for your insights.

Kind regards.

**Comment by asturur** [comment]
In an application there is nothing bad in having a reference to your own canvas instance in my opinion.
Anyway as of now images in fabricjs are images, not canvases.
What you can do very easily is to use the context cache we have on the canvas and paint the image over there.

```canvas.contextCache.drawImage(myImage._element, 0, 0, canvas.getWidth(), canvas.getHeight())```

once you loaded contextCache with the data you need, getImageData and process at will.

Or create an additional canvas on the fly to do that.
