### ISSUE TITLE
Access the webgl context propertie

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3367]
Hi,

I see in the road map, that the webGL filtering is not actualy supported.
I try to access the "canvasEl.getContext("webgl")" or "canvasEl.getContext("experimental-webgl")" in the filtering .js template but without success.

Is there not a workaround to acces those properties ? I understand that you can't use both 2D and webgl context, so is it a fabric.js limitation or is there a possibility to access those context ?

PS : I was trying to implement a WebGL Matrixtransformation filter in fabric.js (work fine in standalone mode, but not in fabric filter template).

Thank you for your help, sorry if my post is not in the right section.

**Comment by asturur** [comment]
i have working code for webgl fitlering, it will be pushed in a later release.
Is not about the context itself, is all the logic to handle textures and filtering for non webgl users that is missing.

**Comment by ncou** [comment]
Good news.

I see the function applyFilter create a 2D context, so i suppose it's for that i can access the webgl context.
By the way, i was trying to implement this WebGL convolutionmatrix (at the end of the article), i add the link in case you have not already see this article.

https://madebymike.com.au/writing/canvas-image-manipulation/

There is also some tips to improve the ImageData array manipulation, it's could perhaps boost a little the existing filters.

In any case, thank you again for your great work and disponibility.
Have a good day, i will close this ticket once i am at home.

**Comment by asturur** [comment]
if you refer to the 32 bit access, i tried it and really makes no difference.
What you gain in less iteration you loose on bit operation to extract colors.
I speed boost i found on canvas2d filtering ( and this i will release asap ) is on multi layer filters, where we should not putImageData every layer but just pass on the data array. that helps a bit.

**Comment by ncou** [comment]
Yes i was refering to the 32bit access.
Great news if there a speed boost soon released.
