### ISSUE TITLE
Feature: Rotation snap

### ISSUE THREAD

**Issue by virror** [kangax/fabric.js#3369]
It would be nice to allow for pressing a modifier key and making the rotation snap to 90 degree steps.
Even better would be to allow the user to set their own snap angle, but not really needed as much i guess.

**Comment by asturur** [comment]
i think an extension or an official suggestion/demo is enough?

**Comment by virror** [comment]
Sure thing, it was just an idea of something that might be useful to other ppl as well : )

**Comment by asturur** [comment]
We have a nice function for rotation snap. I'm guessing if have it in the object class as a function to manually bind to the "rotating" event, or to have as a function of the lib.

**Comment by virror** [comment]
Just to clarify a bit, i have no problems implementing this myself, and are already using the function for snap in another scenario. I just posted this here as an idea cause it seemed like a logical feature.

**Comment by asturur** [comment]
yes no problem. A guy implemented rotation snap with treshold, mergeable with the code, few lines, he was evaluating if putting the function under a modifier key or not.

**Comment by asturur** [comment]
@virror give a check to the feature

**Comment by virror** [comment]
Will do, don't have time today but will do tomorrow

**Comment by virror** [comment]
Looking good when looking at the code and example. I totally understand that it might be to specific to add it as a feature.

**Comment by asturur** [comment]
now is in.
just use the 2 new properties
