### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by virror** [kangax/fabric.js#3370]
Its great that we can choose which modifier key to use for different actions like 'centeredKey'. But i see no way of removing the use of those. In my project i dont want ppl to be able to rotate around the center using the altKey at all, so it would be great to be able to pass in 'none' or something similar to disable the feature.

**Comment by asturur** [comment]
in my current project i m passing null to them, and they are blocked. I see that is not documented. I  m gonna add a line in the jsdoc.

**Comment by virror** [comment]
Cool, that's perfect : )

**Comment by virror** [comment]
This does not look right:
"If `null` or 'none' or any other string that is not a modifier key feature is disabled feature disabled."

**Comment by asturur** [comment]
oh sorry. damn hurry to do stuff.

**Comment by asturur** [comment]
still an hint that bring people to the point.

**Comment by virror** [comment]
: )
