### ISSUE TITLE
[iOs] Keyboard still appear on IText blur

### ISSUE THREAD

**Issue by ivelfan** [kangax/fabric.js#3374]
## Description

When the focus leave the text editing area, keyboard stay in.
## How to reproduce

Add an IText on an empty canvas.
Edit IText element, keyboard go up.
Click anywhere on blank canvas, focus aren't in IText element but keyboard is still visible.
## Version

1.6.6

**Comment by asturur** [comment]
Does it happen with older version?

**Comment by ivelfan** [comment]
Yes, since version 1.6.0.
I didn't make test on older version.

**Comment by itsjoesullivan** [comment]
In this fiddle: http://jsfiddle.net/q0ures6q/1/, on my iphone 5, os 9.3.2, I do not observe this issue. The keyboard goes away when tapping outside of the text box.

**Comment by asturur** [comment]
on Ios 10.0.1 the bug is confirmed.
A simple blur on textarea element looks like can solve it.
I guess i will add it.

**Comment by asturur** [comment]
http://jsfiddle.net/LLpwpaon/1/

check if this fiddle solves for you
