### ISSUE TITLE
itext/textbox font kerning not supported with styles

### ISSUE THREAD

**Issue by asturur** [kangax/fabric.js#3377]
Canvas text rendering supports font kerning automatically if the text is drawn in strings.
When using iText style features, every character is rendered on its own and that make font kerning not working.

I searched the web for a nice font kerning js support library to parse kerning table from font but i could not find anything worth.

This affects:
svg output, cursor position, rendering on canvas.

**Comment by adrianmawer** [comment]
@asturur, would a bounty be likely to get this char spacing/kerning/SVG issue looked at?
Regards,
Adrian.

**Comment by asturur** [comment]
i have 2 finish 2 bigger prs and then i would like to look at this.
text needs a bigger reorganization and clean up.
Last 10 days i had no chance to work on this project.

i will probably do this anyway, if you like the project or need it for awork you can post a bounty, but that will not make me speedier or increment chance of success.

**Comment by adrianmawer** [comment]
@asturur - could you possibly enable bountysource for this issue? Thank, Adrian.

**Comment by asturur** [comment]
i think you can go on bounty source directly and do from there. i did not manage to insert the plugin in the issue

**Comment by MichaelJDK** [comment]
Just want to make sure that this issue is the same as what I have just experienced.

https://jsfiddle.net/xx37jpms/

The output SVG after changing the text (not just deleting part of it) removes the styling and thereby the stroke.

**Comment by asturur** [comment]
#3680
