### ISSUE TITLE
Select and delete text in Textbox object does not clear the selection

### ISSUE THREAD

**Issue by prokilogrammer** [kangax/fabric.js#3378]
## Version
1.6.5

## Test Case
http://jsfiddle.net/1azfo9t6/

## Steps to reproduce
1. Create a canvas with `selection = false`
2. Initialize a Textbox object
3. Write text that wraps to multiple lines
4. Select all the text inside the box
5. Press "backspace" or "delete" to delete all the text

## Expected Behavior
All the text gets deleted AND selection also gets cleared

## Actual Behavior
All the text gets deleted BUT selection does NOT get cleared

**Comment by asturur** [comment]
oh ok. i see the bug :)

**Comment by prokilogrammer** [comment]
Do you have a fix in mind? I tried taking a stab at it but didn't get too far. Looks like oldWidth and oldHeight of IText are being set to the shrunken box dimensions after removing characters - https://github.com/kangax/fabric.js/blob/master/src/shapes/itext.class.js#L314-L321. I tried setting oldWidth/oldHeight in `removeChars()` (https://github.com/kangax/fabric.js/blob/master/src/mixins/itext_key_behavior.mixin.js#L606) but no effect.

I would be happy to send a PR if you guide me in the right direction.

**Comment by asturur** [comment]
Yes the fix is clear the right part of the screen. i m heavely working on text those days for other reason, if i step into it, i will drop a notice here.
