### ISSUE TITLE
Browser will not allow to save larger canvas size 

### ISSUE THREAD

**Issue by Vivek-KT** [kangax/fabric.js#3379]
Hi to all,
Here, we have working in fabric.js with creating design tool.We just set canvas width and canvas height more than "10000px" . for example, we assume that canvas width and height 8640px x10800px (96" inches x 120" inches) and  2160px x 5400px ( 24 x 60 inches ) and so on. We have facing issues related browser especially google chrome results "Aw , Snap !" issues while saving many object (like rectangle, circle, Image, Text) and Internet explorer showns "Not enough storage is available to complete this operation". What is issues and how to resolve it ? we have facing that problem only in large canvas resolution size.

![cid_image004_png 01d22a45](https://cloud.githubusercontent.com/assets/4013115/19763325/2da8d164-9c5b-11e6-9819-02ea9d1569aa.png)

Kindly review it and let me know your feedback.

THANKS
VIVEK KT.

**Comment by asturur** [comment]
chrome and firefox works fine with canvases up to 16kx16k, they are slow, and not suggested for realtime editing. you have to work with a canvas that is as big as your visible area, not more, or you'll have performance problems.
Internet explorer stops at 8kx8k i think or 5kx5k. i do not really remember.

work with small canvas and use pan and zoom to move around a larger virtual area, export in the big resolution you need according to browser limits.
