### ISSUE TITLE
Justify alignment doesn't work with multiple spaces

### ISSUE THREAD

**Issue by bandrzejczak** [kangax/fabric.js#3380]
## Version

1.6.5
## Test Case

http://jsfiddle.net/9d83q443/1/
## Steps to reproduce
1. Create a text with `textAlign = 'justify'`
2. Write some sentence so it fills up available line
3. Put the cursor after the first word of the sentence
4. Write multiple spaces
## Expected Behavior
- cursor is in the right position
- there is more space between first and second word than there were before
## Actual Behavior
- cursor is starting to fall out of place and after a few spaces is hovering over a next word
- space between first and second word doesn't really change

The problem probably lies in `fabric.Text.prototype._renderTextLine` method which renders words on canvas.

**Comment by asturur** [comment]
i thought we somehow fixed the use of multiple text spaces in the same justified line.
looks like not.

**Comment by asturur** [comment]
this is fixed with #3676
