### ISSUE TITLE
Grouping is not applied for clipped objects

### ISSUE THREAD

**Issue by karthickvkumar** [kangax/fabric.js#3382]
Hi @kangax @asturur   I have created an rectangle shape and clipped an image using clipto function in fabricjs. Then I want to group the two objects and drag then as one object, using fabric.group method. But while grouping an clipped objects it throw error.I herewith added an [jsfiddle example](http://jsfiddle.net/karthickvkumar/b9pa8255/) for that scenario.

**Comment by asturur** [comment]
The fiddle is very complicated and full of custom code. Please make a fiddle with 2 simple objects and minimal amount of code.

**Comment by karthickvkumar** [comment]
Hi @asturur @kangax I would like to implement a photo collage, where i want to upload image to shapes and that uploaded image can be resize with in the shape object.  To achieve that in fabric i used to clip the uploaded image to shape object. Here this is that [jsfiddle example to clip an image to shape](http://jsfiddle.net/karthickvkumar/xcgm64mt/), Then after clipping that i want to **drag both (image and shape) as single object**. For that i use group function to merge both as single object. Here is that [jsfiddle to group both the object](http://jsfiddle.net/karthickvkumar/b9pa8255/), while grouping it through error for the clipped objects 

If there is any other way to drag both the clipped image and shape as a single object, plz let me know

Thanks in Advance

**Comment by karthickvkumar** [comment]
Hi @asturur, I have mentioned fiddle in the last comment
