### ISSUE TITLE
[Feature] Event mouse:in

### ISSUE THREAD

**Issue by samael205** [kangax/fabric.js#3384]
Hi asturur,
I want to use in fabric the event "mouse: in" to know when I'm inside the canvas.
Currently works when the mouse leaves the canvas with mouse: out, but do not jump when you walk into the canvas, you Could implement a "mouse: in" to jump when you walk with the mouse on the canvas?.

regards

**Comment by asturur** [comment]
there is a mouse:over event, now i do not remember if it fires everytime the cursor is over the shape or just the first time

http://fabricjs.com/docs/fabric.Canvas.html

does mouse:over work?

**Comment by samael205** [comment]
the mouse:over fires every time when the cursor is over a shape, but doesn't when the cursor is outer the canvas and enter inside canvas

**Comment by asturur** [comment]
ok this could be a nice addition. if we mouse:out on exit canvas, maybe we can mouse:over on canvas enter. i will take a look.

**Comment by asturur** [comment]
closed via #3389  @samael205 get a check if it is ok.

**Comment by samael205** [comment]
Ok, i will try soon, Many Thanks Guys @stefanhayden  && @asturur

**Comment by samael205** [comment]
Hi, works fine!.
Thank you so much guys.
Regards!
