### ISSUE TITLE
Duplicated IText elements show an error when one of the is removed

### ISSUE THREAD

**Issue by human-a** [kangax/fabric.js#3387]
## Version

1.6.6

## Example fiddle
https://jsfiddle.net/human_a/04ygc15h/

## Steps to reproduce

If you duplicate an IText object using the fabric.util.object.clone method, and then remove one of the text elements you will get an error in the console upon moving the text element.
## Expected Behavior

Should be able to duplicate text elements and then remove one without a problem
## Actual Behavior

Instead, you will get the following error in the console every time you want to move the text element.

```
fabric.js:24220 --> Uncaught TypeError: Cannot read property 'getPointer' of undefined(…) 
onMouseDown @ fabric.js:24220fire @ fabric.js:183_handleEvent 
@ fabric.js:10253__onMouseDown @ fabric.js:10401_onMouseDown @ fabric.js:10099
```

**Comment by human-a** [comment]
I added a fiddle https://jsfiddle.net/human_a/04ygc15h/. Please take a look at the browser console once you remove the duplicated/cloned text.

I also noticed today that the cloned text will no longer behave as a textBox element if you try to resize the bounding box if the newly cloned text it will scale the element.

**Comment by ncou** [comment]
Here is a working example :
https://jsfiddle.net/04ygc15h/2/

You should use the .clone(callback) function to clone fabric objects.
From my understanding, the classe fabric.util.clone should be used on non fabric object (but i don't really know in witch case you can manipulate non fabric_object ? ).

**Comment by human-a** [comment]
Worked like a charm, thanks for the help.

**Comment by human-a** [comment]
@ncou while this method works to avoid the issues mentioned above however if your element's object has custom attributes (mine does) they will not be cloned along with the item.

To fix this, using [ES6 spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator) I clone the object and set all attributes to the new cloned object like so:

```
object.set({
    "top": object.top+5,
    "left": object.left+5,
     ...canvas.getActiveObject()
})
```

using fabric.util.clone there is no need to do the above hack, but it generates errors mentioned above.

**Comment by ncou** [comment]
You could add to the clone function a list of properties to keep :

clone(callback, propertiesToIncludeopt)

example with custom attribute "toto" and "tutu"
https://jsfiddle.net/04ygc15h/3/

**Comment by asturur** [comment]
so just to make it clear, ```fabric.util.object.clone``` is an internal utily  to clone javascript objects.
To clone an instance you need to use its .clone method, preferably using the callback arguments.

```fabric.util.object.clone``` is a sort of small utility like the one you find in lodash library. Its meaning is to semplify recursive copy of things that otherways would be reference to objects.
(style of itext, properties with sub properties.... )

**Comment by wearehappybits** [comment]
Could anybody provide a proper way of cloning? @ncou jsfiddles does not work any more as I see. 

I also have the same issue.

**Comment by asturur** [comment]
what is wrong with the clone method?

**Comment by wearehappybits** [comment]
Just solved this. Thanks
