### ISSUE TITLE
Redefine the "initialize()" methode

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3390]
Hi,

I want to add a custom attribute each time a new object is created.
I want to redefine the "initialize()" function to add my own JSON option string with my custom attribute.

Like this :

`fabric.Object.prototype.initialize = (function(initialize) {
	            return function() {
	                return fabric.util.object.extend(initialize.call(this), {
	                    uniqueid: 123456
	                });
	            };
        	})(fabric.Object.prototype.initialize);`

But i got an error : "cannot set propertie uniqueid of undefined()". It seems the object is not yet created when the option try to apply the new custom attribute.

I tried with the "toObject" methode and it work fine. Is this a bug in the initialize function ? or is it not possible to change the initialize methode ? or is it my code who is lame ?

Let me know if i should create a jsfiddle.
Thank you. Keep up the good work.

**Comment by asturur** [comment]
that seems overcomplicated to me.
Where this unique id comes from?
The object initialize function is so small and simple that you can ovverride it instead of try to send code inside it and getting crazy with the meaning of THIS keyword inside nested functions.

**Comment by asturur** [comment]
i warn you this is a stackoverflow forum use case.

**Comment by ncou** [comment]
The unique id come from a nonce function. if you think it's not a bug, i will close the ticket and try my luck on the stackoverflow.

**Comment by asturur** [comment]
so to get an id to every object, without explicitely calling it in the application code you can do:

fabric.Object.prototype.initialize = function(options) {
  options.uniqueId = mycustomFunction();
  .... copy the rest of the original function here ....
}

Be aware that some classes do not call this function directly so you have to extend theyr own initialize method.

Or try to do the same logic to the .setOptions method. that should be really unique to all classes.

If you need something more complicated to put an id to an object, i think there is some design complication somewhere else.

**Comment by ncou** [comment]
Thank you. Effectively some class like itext or pathgroup doesn't call the mother class function object.initialize() so il will need to redefine the initialize function for at least 3 times.

It was not a bug but my lame code. I will close the ticket.
Have a good day.

**Comment by asturur** [comment]
try to redefine ```.setOptions```. that is unique. and everyone calls it.

**Comment by ncou** [comment]
i was thinking the setOptions was called each time there is an attribute modification but after a test, it's not the case.
So yes i can use the setOptions function to redefine it and add unique ID. thank you !

By the way, it's not really important, but the setOptions() is called twice for the image & pathgroup, but only one time for the itext object (at least in my application using a console.log).
