### ISSUE TITLE
globalCompositeOperation not working when having backgroundColor 

### ISSUE THREAD

**Issue by karthickvkumar** [kangax/fabric.js#3391]
Hi @asturur @kangax, When i use globalCompositeOperation (like source-atop) for an object, its working fine without background. But when i mention some background color for canvas its not working Here is the [jsfiddle code](https://jsfiddle.net/karthickvkumar/k1fk1b9s/) 

`output without background Color for canvas`
![capture](https://cloud.githubusercontent.com/assets/11032434/19880284/b85edb5e-a021-11e6-8887-57fd3ad8163f.JPG)

`output with background Color for canvas`
![captured](https://cloud.githubusercontent.com/assets/11032434/19880288/c605907c-a021-11e6-9ced-dd706faf1ca1.JPG)

Thanks in Advance

**Comment by asturur** [comment]
This is how global composite operation works.
If you want to mix the 2 shapes without the background you have to mix them in a separate canvas and the paint that canvas over fabricjs as an image.

Or you should clip the image with that shape.

**Comment by karthickvkumar** [comment]
thanks @asturur
