### ISSUE TITLE
Multiple shadows support?

### ISSUE THREAD

**Issue by DangerD256** [kangax/fabric.js#3393]
Does Fabric supports the functionality of adding multiple shadows? If not, how can i implement it by the simple way?
Needed to create more solid text glows

`setShadow('0 0 25 rgba(255,0,0,1), 0 0 25 rgba(255,0,0,1)');`

**Comment by asturur** [comment]
we use canvas shadow that is only one. if you want to create text glow you should clone your text as image ( function available ) and then put some filters over it.

**Comment by DangerD256** [comment]
Hmm, need to keep text editable, can you please point me to that function so I can proceed
Thanks in advance

**Comment by asturur** [comment]
i do not think fabric is ready yet for this. It requires a lot of custom code.
In fabric 2.0 object caching should be on by default, and filters will be applicable to all objects.

Then it will be easier to do something like that without digging too much in canvas api.

Object caching is planned for 1.7.0 and is quite ready, there is a PR open.
2.0 is in a branch but require still lot of work to be released as functional.

**Comment by DangerD256** [comment]
Okay, so making it as image object, tried image filter blur here:
fabricjs.com/image-filters
It doesn't work, so any other filters in canvas is that can achieve more stronger text blur?

**Comment by DangerD256** [comment]
Resolved it by cloning several times text object with shadow and merging it to group, but i had to rewrite a lot of code to update each cloned element if user changes some shadow effect/text/font size etc.

**Comment by asturur** [comment]
and you have also risk of some shadow going over something else with colors that havr opacity lesser than 1. this is the reason why i told you that in my opinion is not ready yet.

can i see a screen of result?

**Comment by DangerD256** [comment]
![image](https://cloud.githubusercontent.com/assets/17032489/20057690/968fc424-a4f5-11e6-9127-ff6a931382cf.png)
left text - simple text wit shadow
right text - cloned texts several times (Adjustable by multiplier input)

**Comment by asturur** [comment]
good idea. i will keep in mind if i need to obtain some multiple shadow effects.

**Comment by zhe-he** [comment]
Will this feature be added in 6.0 ？
Multiple shadows support ?

**Comment by kkm** [comment]
+1
