### ISSUE TITLE
Pixel manipulation with FabricJS

### ISSUE THREAD

**Issue by kevinnascimento** [kangax/fabric.js#3394]
Hi,

I'm using FabricJS  v1.5.0 and have a problem when manipulated pixel by pixel on the canvas.

```
this.canvas = new this.fabric.Canvas('canvas');
let imageData = this.canvas.contextContainer.getImageData(0, 0, this.canvas.getWidth(), this.canvas.getHeight());
//here a changed imageData

this.canvas.contextContainer.putImageData(imageData, 0, 0);
//data seted in canvas.

let imageAdd = new this.fabric.Image(image, {
          left: 100,
          top: 100,
          width: 100,
          height: 100
        });
this.canvas.add(imageAdd).setActiveObject(imageAdd);
//in this moment, the canvas don't have more the imageData setted
```

Why add image clear imageData? I need to transform imageData in FabricJS Object to add in canvas?

**Comment by asturur** [comment]
the canvas get cleared every render.
The only way to keep custom image data on the canvas is creating an image from it, and display it as an image.
so put your image data on an a canvas element
dataurl that canvas element in a url
load an image from that url
use that image as background or as an image object.

Different approach from this may work ma but require some custom coding.
