### ISSUE TITLE
Objects will look like wireframe

### ISSUE THREAD

**Issue by tzahimaimon** [kangax/fabric.js#3395]
## Version
1.6.5

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by tzahimaimon** [comment]
Hi all thank you very much for a great library. what i'm trying to do is to create wireframe for objects meaning the object itself is unvisible but the border around will be visible even of other object is selected... I know of drawBorders function but when I try using it it shows the bounding box at the top middle of the canvas and not where it is really.  i'll appericate your help. thank you.

**Comment by tzahimaimon** [comment]
I'm sorry for the Close Issue :-) the subject is not yet to be solved...

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
