### ISSUE TITLE
Textbox objects become skewed when moved as part of a Group

### ISSUE THREAD

**Issue by danielbonnell** [kangax/fabric.js#3397]
## Version
1.6.6

## Test Case
https://jsfiddle.net/pdc9qs28/2/
https://jsfiddle.net/pdc9qs28/3/

## Steps to reproduce
Place two objects on the canvas with `canvas.selection === true`. One object must be a `Textbox`. Once objects have been initialized, scale them (`object.scaleX`/`object.scaleY`) by a factor (e.g. .75). Then select both objects as a group and move them. Running a check on their before/after `scaleX` and `scaleY` shows that the `Rect` object was properly scaled, but that the `Texbox` object was scaled only on the Y axis, giving the illusion of stretching.

## Expected Behavior
When moving grouped objects, objects should not become skewed or distorted.

## Actual Behavior
This seems to be a bug with scaling for `Textbox` objects. I've created two fiddles to reproduce it. The first demonstrates the bug when only the `Textbox` is scaled. The second more closely represents a production app in which the entire canvas is scaled, and thus objects within it are scaled to match the canvas' scale.

I've attached two screenshots to demonstrate the effect. See also the Fiddles above.

![1](https://cloud.githubusercontent.com/assets/8513877/20023246/3c6152de-a2b5-11e6-90d5-b743553f1bfa.png)
![2](https://cloud.githubusercontent.com/assets/8513877/20023247/3c61886c-a2b5-11e6-9d81-710ffa3335b8.png)

**Comment by asturur** [comment]
textbox is made that it cannot be scaled on group. If you are looking for a canvas zoom feature, plese use embedded one that handles cases like this canvas.setZoom(0.75).

textbox should always have scale equal to 1 when grouped.

**Comment by danielbonnell** [comment]
Using `canvas.setZoom()` does seem to solve this, but also requires a complete rework of how my app handles canvas zoom. If `Textbox` is not meant to be scaled as you say, then it shouldn't have a `scaleX` and `scaleY` property.

**Comment by asturur** [comment]
there is a special logic on grouped scaling. textbox as been contributed as it is, i do not agree with thisc scaling logic, but that is it. using canvase set zoom solve the problem because you would not need to scae objects individually.

**Comment by danielbonnell** [comment]
There is no particular reason I know of for scaling things individually except that that is how the project that I based my app on was designed. For now I've just disabled grouping because it appears I need to rewrite all the scaling logic within my app to use `canvas.setZoom`, which is probably better in the long run, but frustrating at the moment.
