### ISSUE TITLE
How to set Transparent in canvas Background in fabric Js

### ISSUE THREAD

**Issue by Vivek-KT** [kangax/fabric.js#3398]
Hi to all,
Here, we have working in fabric.js with creating design tool. We need to set Transparent Background in canvas background. We already set Background color changes for canvas. But we need to set transparent option in background in canvas. Sample BG transparent option in Canvas.

![d](https://cloud.githubusercontent.com/assets/4013115/20054424/f1d2fca4-a502-11e6-8502-52438fe65e35.jpg)

Kindly review it and let me know your feedback.

THANKS
VIVEK KT.

**Comment by samael205** [comment]
Set to null backgroun Color with canvas.backgroundColor = null;
after that, call canvas.renderAll.bind(canvas)();

**Comment by Vivek-KT** [comment]
@samael205 Here, we have tried to set null for backgroundImage but it will not apply. 

```
e("#grid-btn").click(function() {
           w.backgroundColor = null; 
	    t.set("backgroundColor", null);
	    et();
	   }
 });
```

We already tried but not working fine for us.Kindly review it and let me know your feedback.

**Comment by samael205** [comment]
@Vivek-KT have you tried call function canvas.renderAll.bind(canvas)() after?

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
