### ISSUE TITLE
Barcode fonts are taller than bounding box.

### ISSUE THREAD

**Issue by jakrzysztow** [kangax/fabric.js#3399]
We are trying to use some commercial barcode fonts with fabric in a Text() and they render taller than the bounding box.

I've noticed several issues that seem to be similar and would like to know if there is a work around or fix for this?

Below is one of the font families. Each is the same font size but a different font face. The bounding box is the same for all of them, but the barcode itself extends higher than that.

![code39 human readable l](https://cloud.githubusercontent.com/assets/457132/20076968/07a06768-a500-11e6-97b9-c71cb04bb854.jpg)
![code39 human readable m](https://cloud.githubusercontent.com/assets/457132/20076967/079f46da-a500-11e6-97e0-23d9f4294fd7.jpg)
![code39 human readable s](https://cloud.githubusercontent.com/assets/457132/20076970/07a14e6c-a500-11e6-9f1b-d2186c52e85c.jpg)
![code39 human readable xl](https://cloud.githubusercontent.com/assets/457132/20076971/07a25596-a500-11e6-99c8-84fece3ef8dd.jpg)
![code39 human readable xxl](https://cloud.githubusercontent.com/assets/457132/20076969/07a0be52-a500-11e6-866a-047a3e23422d.jpg)

**Comment by asturur** [comment]
Bounding box height is based on font size.
If the font size for 40px is giving 200px height fonts, there is nothing we can do now.
