### ISSUE TITLE
Shadow & Background Problem

### ISSUE THREAD

**Issue by arminbusatlic** [kangax/fabric.js#3401]
I'm not sure what I'm doing wrong here, but whenever I apply a shadow to my IText which has a background, the shadow is applied on the whole block, instead of just the text.

When I run the same code I have in the JSFiddle, it appear correctly. http://jsfiddle.net/busatlic/smwtdvnp/

However, when I run it having it integrated in my code, the shadow appears around the entire box.

**Comment by samael205** [comment]
Why are you creating Two I-text with the same text?, I do not understand.

**Comment by arminbusatlic** [comment]
I've created it so that I can have the stroke appear outside of the fill. The only way I could think of doing this is to have a foreground and a background object. 

When I use one object, I run into two problems. 

1. When I apply a shadow along with a background, the shadow appears around the entire box, instead of just the text.

2. When I add the stroke, the stroke expands towards the inside and outside of the text, which is not what I want. 

I think the main problem with all of these is the execution order of things. I need the execution order to be as follows:
1. Apply Stroke
2. Apply background
3. Apply fill
4. Apply shadow.

If it's in that order, all of my problems are resolved :) ... but it's not and I don't know where do modify the code to ensure that the order of execution is correct.

**Comment by arminbusatlic** [comment]
I figured out the problem. There is a bug on this latest version. When adding a shadow to text that has a background, the shadow is added to the entire object, instead of just the text. This is quite a big bug.

**Comment by samael205** [comment]
I figured that your problem is related because the shadow is generated from non-transparent canvas pixels. When you are setting the backgroundColor, that area becomes non-transparent, and the generation of the shadow interpret that the area of shadow is the entire box of text.

But i'm not sure.

**Comment by arminbusatlic** [comment]
You are correct. That is exactly what is happening. However, this was not the case in Fabric 1.5.0. Somewhere along the updates evolved a glitch causing the shadow to be generated on the entire area of the text box instead of just the text. This should definitely be marked as a bug.

In the meantime, is there a way to change the order of execution of what canvas draws first? If the background is applied after the shadow is generated, this would not be a problem, but I'm not sure where I could go about changing this in the fabric code.

**Comment by asturur** [comment]
is not a bug. shadow is made by rhe object itself, not just text. is coded and commented like that. is a feature.

shadow in the other way look very bad.

changes before 1.6 if i remember correctly, but is in changelog if you want to verify

**Comment by arminbusatlic** [comment]
How would I go about achieving this then?

http://jsfiddle.net/busatlic/5rkfLhzx/

I want the shadow to be on the text, even when I have a background. Is this no longer possible?

**Comment by asturur** [comment]
you have to do with a group probably, drawing a rect and text over.

is that backgroundcolor or textbackground for lines?

**Comment by arminbusatlic** [comment]
Its text background. I tried textBackgroundColor, but same result. Shadow appears around the whole box.

The problem with group is that I can't group IText. I lose the entire event handling functionality when I do it. I honestly don't understand why this change was made. Why is there no control to set the shadow on the text. 

How would I go about changing the order of execution for canvas, so that the background is filled AFTER shadow is set?

There has to be a way to achieve this without grouping.

**Comment by arminbusatlic** [comment]
Does anyone know of a way to achieve this? I just want to place a shadow on text that has a set background color, similar to this example: http://jsfiddle.net/busatlic/5rkfLhzx/

This was possible before 1.6.0.

**Comment by asturur** [comment]
i need to find the original pr to figure out the errors that brought to this decision.

**Comment by arminbusatlic** [comment]
@asturur Thanks! I will be awaiting your response :)

**Comment by asturur** [comment]
https://github.com/kangax/fabric.js/issues/2807

this was the original issue.

The general look and feel of shadow felt wrong.
Also text decoration ( underline ) was dropping shadow over text because it was coming with a separate draw command.
Svg export of svg with shadow was not respecting canvas situation.

You can solve by overriding.
There is a function in text class, that calls ```renderTextFill```, add a ```this._setShadow(ctx)``` before that call and you should be good to go because you re enable shadow before drawing.

Also getting shadow just for the outer object is a requirement for using object caching, a feature that i should release as soon as i get time, and we would end up on something like  this anyway.

I would not suggest to stay on 1.5.0 because the text functionalities got lot of fixes during 1.6.0 and up.
