### ISSUE TITLE
IText cursor leaving a trail

### ISSUE THREAD

**Issue by danielocdh** [kangax/fabric.js#3402]
## Version
1.6.6

## Test Case
https://jsfiddle.net/ep71546d/

## Steps to reproduce
On a canvas where selection is set to false, delete text from the end of an IText with backspace.  
tested on windows 7 x64 latest chrome, firefox and IE

## Expected Behavior
No trail

## Actual Behavior
The cursor leaves a trail

**Comment by asturur** [comment]
we fixed it in a recent pr.

**Comment by Rad1calDreamer** [comment]
When I change fontsSize on itext with focus - this reproduce again
step1 - enter edit to i-text object
step2 - press the button
http://jsfiddle.net/Da7SP/251/
