### ISSUE TITLE
OriginX/Y not exported in JSON (with includeDefaultValues=false) on Image object

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3403]
Hi,

I want to export the canvas data as json, and keep the OriginX/Y value, and not the default values.
I have used an array with the value "originX" and "originY" for the .toJSON() function.

The JSON generated doesn't keep the json node for the Image object. it work fine for the other objects.

Here is the fiddle :
http://jsfiddle.net/pec86/122/

I got the following result :
`{"objects":[{"type":"circle","left":150,"top":150,"width":100,"height":100,"fill":"#0B61A4","originX":"center","originY":"center","radius":50,"startAngle":0,"endAngle":6.283185307179586},{"type":"image","width":150,"height":150,"src":"http://fabricjs.com/assets/pug_small.jpg","filters":[],"resizeFilters":[],"crossOrigin":""}],"background":""}`

The originX/Y node is present for the circle object, but not for the Image object.

Seems like a bug with the "includedefaultvalues" parameter.

Keep up the good work

**Comment by asturur** [comment]
going to check this asap.

**Comment by asturur** [comment]
i do not think is a bug, simply after exporting default values are deleted if they are equal to default.
I do not think we can change this, there is no reason.
Also originX and originY are exported by default and adding them to additionalProperties should not do any change.
i guess a small note on the parameter is required.

**Comment by ncou** [comment]
Hello,

Yes i undestand the exported values are filtered after the export if there are the same than the default value, and there is no reason to change this.

But in my fiddle i force at the beginning of the script the originX/Y for all the objects to center : 
`fabric.Object.prototype.set({..., originX: 'center', originY: 'center'});`

By default the originX/Y for an Image Object is 'top' and 'left' (if i refer to the documentation it's an heritage of object : http://fabricjs.com/docs/fabric.Object.html#originX).

So in my fiddle the originX/Y for the Image object is changed (from top to center, and from left to center), so it should be exported (and not deleted after the export).

PS : But it's correctly exported for the circle object.

Am i missing something ? Am i clear enough ?

**Comment by asturur** [comment]
yes clear enough. i ll recheck. propably i read too fast. i ll check the image toObject method, maybe is wrong.

**Comment by asturur** [comment]
so the wrong one is circle.
The default value is center, center in your fiddle. So it should not be exported.
I see some classes explicetely remove defaults right after the object creation, other do just in the to Object Method.

**Comment by asturur** [comment]
So i was wrong:

the current code is:
make object, delete defaults, extend with custom properties.
That would mean that originX and originY would stay.

Some classes delete defaults twice. And this is wrong in my opinion.
If the properties specified with custom array would survive the default deletion, that would not be a good thing because we would loose the opportunity to have a clean export.

If the defaults deletion deletes custom properties the developer has the opportunity to do not specify a default value for it and so they can survive anyway.

So i m moving the code in
make object,  extend with custom properties., delete defaults.

And remove the double deletion for the other classes.

**Comment by ncou** [comment]
it's a bit complicated with my current english level comprehension, so i will try the code once the modifications are mades.

In my case, i need to have the right orignX/Y attribute to be keeped, because if i export the json stream and reload it the result is messed up because the originX/Y is reset to top/left and my left/top pixel value is keeped. So i get a strange result.

I think from your post it's the "delete twice" who is at fault for losing the customized attributes originX/Y.

But i will try the new code to be sure to understand correctly the wanted behaviour.

Sorry for my poor english.

**Comment by asturur** [comment]
in your fiddle the defaults are center/center.

so who has center center should be deleted, if some object has top/left should be kept.

I opened a pr that should fix this,

**Comment by ncou** [comment]
thank you i will try the modifications once it's released.
Have a good night.
