### ISSUE TITLE
Unit tests are failing.

### ISSUE THREAD

**Issue by belfz** [kangax/fabric.js#3404]
## Version
1.6.6

## Steps to reproduce
Follow the official instruction on [Testing](https://github.com/kangax/fabric.js#testing).

## Expected Behavior
Unit tests should pass on master branch.

## Actual Behavior
Unit tests fail with the following error:
```
Global error: Uncaught ReferenceError: QUnit is not defined at http://localhost:7357/1692/test/unit/util.js, line 3

Uncaught ReferenceError: QUnit is not defined at http://localhost:7357/1692/test/unit/canvas_static.js, line 156
Uncaught ReferenceError: QUnit is not defined at http://localhost:7357/1692/test/unit/canvas.js, line 84
Uncaught ReferenceError: QUnit is not defined at http://localhost:7357/1692/test/unit/circle.js, line 3
Uncaught ReferenceError: QUnit is not defined at http://localhost:7357/1692/test/unit/collection.js, line 5
Uncaught ReferenceError: QUnit is not defined at http://localhost:7357/1692/test/unit/color.js, line 3
```

I deduced, that qunit is not correctly loaded in the browser's testing context. The problem seems to lie within `tests.mustache` file, line 5:
```
<script src="/bower_components/qunit/qunit/qunit.js"></script>
```

Replacing this line with following:
```
<script src="/node_modules/qunitjs/qunit/qunit.js"></script>
```
seems to make the tests run correctly. However, the result is following:
```
     Chrome   ┃      Node                                                                                                                   
  824/825 ✘   ┃    0/1 ✘   
```

**Comment by belfz** [comment]
Additionally, the result in Chrome browser mentions this:
```
Tests completed in 23237 milliseconds.
3999 tests of 4001 passed, 2 failed.
```

**Comment by jedateach** [comment]
@belfz You may be interested in this PR: #3331 We've been working to get test suite running in real browsers on saucelabs.

It fixes the first issue you mention, but there is just a little more work to do before the PR can be merged in. See the PR discussion.
