### ISSUE TITLE
Deleting large chunks of text causes a significant lag.

### ISSUE THREAD

**Issue by belfz** [kangax/fabric.js#3405]
## Version
1.6.6

## Test Case
http://jsfiddle.net/2qa39t6g/2/

## Steps to reproduce
1. Click on the text and make sure the cursor is displayed.
2. Hit ctrl+a (cmd+a on macOS) to select all the text.
3. Hit backspace on your keyboard.

## Expected Behavior
The text should be removed immediately.

## Actual Behavior
There is a noticeable lag when removing large chunks of text.
This is caused by a time-expensive call to `this._splitTextIntoLines()` inside `fabric.IText.prototype._removeSingleCharAndStyle` (which is called for every character eligible for removal).

I will send a Pull Request shortly.

**Comment by asturur** [comment]
that is the same reason why pasting is slow.
sadly this is the only way to make text style work in any condition. if you try to change some code be aware of complicated style situation and necessity of shifting styles with chars deleted.

**Comment by belfz** [comment]
@asturur please take a look [at my PR](https://github.com/kangax/fabric.js/pull/3406).
I also have a fix for paste action in a project I am working on. It has a similar solution. Should you accept this PR, I will create another one for speeding up paste action.

**Comment by belfz** [comment]
Thank you @asturur - I have closed the [pull request](https://github.com/kangax/fabric.js/pull/3406) because it indeed broke the styles.

In the project I am working on, I have introduced similar optimisation for paste. Turns out, I will have to roll it back, because it also breaks the styles. I have tried to change the logic and still have both - speed and correct styles. After spending 2 days on that I gave up - seems that calling `_splitTextIntoLines()` is the only way to maintain correct values of line lengths, positions of line breaks and styles.

Let's keep this bug open however. Looks like IText/Textbox may indeed require solid rewrite. I was also thinking, that most of the problems are caused by the fact, that text and styles are kept in two separate objects (string and array), which always need to be kept in sync. Future rewrite may take into consideration keeping a single array of objects, which would describe a character and associated style. What do you think?

**Comment by asturur** [comment]
i m aiming at a rewrite for:

1) better style management, probably char and style in one object
2) slower but steadier rendering ( not crazy optimization of style swaps )
3) separation of measuring code from rendering code
4) put kerning inside in some way.

Object caching is in now, so text will not be rendered every move or every rotation / scale ( there are different levels of caching ) i do not care for a little bit slowlier text if it can be subclassed easier.

I m using fabric in a big application and text is giving me headaches.

The plan is to release 1.7.0 with object caching, understand if i can release webgl filtering, and then tackle text. I guess all the fun features have to wait.

**Comment by asturur** [comment]
anyway we have an issue for this. i close that and reference here.

**Comment by belfz** [comment]
Thanks, that clears up a lot.

**Comment by asturur** [comment]
with latest master this situation has changed.
Is not perfect yet but i would say the slowness on pasting / deleting is done. Style handling is faster.
The whole meauring and wrapping process is slower, but is more precise and maybe can be optimized.
