### ISSUE TITLE
Stretching centered object on X orY axis causes top/left values to become NaN

### ISSUE THREAD

**Issue by danielbonnell** [kangax/fabric.js#3409]
## Version
1.6.6

## Test Case
https://jsfiddle.net/17p318wn/

## Steps to reproduce
Add an object to the canvas center and then stretch it on either the X or Y axis. The bug seems to go away when I don't set `originX` and `originY` for the object and `canvas.selection === false`, however that prevents group selection, which is a critical feature. The bug seems to be related to group selection somehow.

## Expected Behavior
The object should stretch as expected. The position should be unaffected. The object's `top` and `left` coordinates should remain unchanged.

## Actual Behavior
Stretching a centered object on the X or Y axis causes the opposing coordinate value to become `NaN`. For example, stretching a `Rect` on the X axis causes `top === NaN` while stretching it on the Y axis causes `left === Nan`. As a result, the object appears to fly off the canvas to the top left corner where it remains unselectable even if `canvas.selection === true`. This behavior occurs with other object types such as `Circle` and `Textbox`. Note that stretching on both X an Y axis using a corner bounding box does not trigger this behavior.

See before/after screenshots:
![1](https://cloud.githubusercontent.com/assets/8513877/20179974/7c5dfcc8-a726-11e6-94f3-2844e2d012bb.png)
![2](https://cloud.githubusercontent.com/assets/8513877/20179973/7c5d049e-a726-11e6-849f-547fc81cbf12.png)

**Comment by asturur** [comment]
ok i was tricked for a bit.
originX cannot take top, it needs left, right or center.
same apply for originY.
