### ISSUE TITLE
Group and controls box has wrong position. The group has offset

### ISSUE THREAD

**Issue by sharok** [kangax/fabric.js#3410]
## Version
1.6.6

## Test Case
http://jsfiddle.net/pevtwgcL/

## Steps to reproduce
Group is created with the following options:
 ```
 var oGridGroup = new fabric.Group([],
            {
                left: 0,
                top: 0,
                width: width,
                height: height,
            });
```
Try to select grid in the demo, somewhere at the top. You will see that controls box has wrong position.
If you delete `width` and `height` properties then `width` and `height` have 0 and controls box is not visible, but grid has right position.  If you check coordinates in the `getGrid` function you will see that lines have correct coordinates.
## Expected Behavior
Grid should be at left=0 and at top = 0, controls box has correct position.
## Actual Behavior
Controls box and grid have wrong position.

**Comment by asturur** [comment]
has been asked in other issue too, actually there is no way to create a group WHERE you want to.
The group is gonnah ave top and left created from the object it contains.
To have control box  to be coeherent with objects, please call  oGridGroup.addWithUpdate(); at the end of your functions.
Please if you are interested just search the old issue about groups ( is open ) and +1 it.
