### ISSUE TITLE
includeDefaultValues parameter ignored for the propertie "backgroundImage" (and backgroundColor with pattern)

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3413]
Hi,

The parameter "includeDefaultValues" seems to be ignored for the propertie "backgroundImage"when i export my canvas to JSON I still get all the default properties (skewX...etc).

I think there is also the problem if you use a pattern for the backgroundColor propertie (I still see the default offsetX/Y values).

http://jsfiddle.net/pec86/125/

**Comment by asturur** [comment]
bug confirmed. i will fixit asap
