### ISSUE TITLE
deep cloning stackoverflow

### ISSUE THREAD

**Issue by Rad1calDreamer** [kangax/fabric.js#3421]
if object have shadow, fabric.util.object.extend call stackpverflow error
https://github.com/kangax/fabric.js/pull/3262
## Version
1.6.7

**Comment by asturur** [comment]
can i ask you a fiddle?
fabric.util.object.extend is not meant to clone a fabricObject, for that you use  Rect.clone() or Line.clone().

fabric.util.object.extend extends js objects, like `{a:1, b:4}`

**Comment by asturur** [comment]
@eschnabel

**Comment by Rad1calDreamer** [comment]
@asturur i dont understand why this dont reproduce in fiddle 
http://jsfiddle.net/pyvxcsup/30/

**Comment by Rad1calDreamer** [comment]
my console
![image](https://cloud.githubusercontent.com/assets/7055577/20298351/71d77bd6-ab26-11e6-8f5d-03568fc92c7a.png)

**Comment by asturur** [comment]
Can we replicate with some code?

```
this.canvas.forEachObject(function(obj) {
            if (!obj.id) {
               var _obj2 = obj.toObject(['x1', 'y1', 'x2', 'y2', 'objID', 'selectable']),
                  _obj;
               if (obj.type === 'path') {
                  _obj = new fabric.Path.fromObject(_obj2, function(foo) {
                        _tmpCanvas.add(foo);
                     }
                  );
               } else {
                  _obj =
                     new fabric [fabric.util.string.camelize(fabric.util.string.capitalize(obj.type))].fromObject(_obj2);
                  _tmpCanvas.add(_obj);
               }

            }
         });
```

On kitchensink with 1.6.7 i can clone objects and restore from json objects with shadows with no problem.

Where are you using the clone function in the code provided?

**Comment by Rad1calDreamer** [comment]
i need create png image of my canvas, excluding object with id, to make illusion of freedraw under objects.
I create static canvas, add all of objects i needed, and create <img> which i append in canvas container

**Comment by asturur** [comment]
Can you just replicate a situation in wich calling extend or clone is gonna fail?

**Comment by Rad1calDreamer** [comment]
call Stack for crash
![image](https://cloud.githubusercontent.com/assets/7055577/20299300/6e9668d8-ab2b-11e6-8fab-86eaa5cc1171.png)

**Comment by asturur** [comment]
i need to see what is inside `source` var.
Can you make it on a fiddle? Is there any technical stop to replicate the problem and isolate it?

**Comment by Rad1calDreamer** [comment]
while i try create fiddle, send one more screenshort
![image](https://cloud.githubusercontent.com/assets/7055577/20299703/1cdf74f6-ab2d-11e6-95f0-4afb53133835.png)

**Comment by asturur** [comment]
ok i can stop you now.
That extend with deep cannot clone functions.
I guess that is why you get the error.
Is an internal tool to clone stuff like styles and properties. Has problems with functions.
I can detect if there is a function and just send the reference of it.
Better than error anyway. I think you should use something like lodash if you need a deep clone function that works always.

**Comment by Rad1calDreamer** [comment]
i add hasOwnProperty in "for in" to "fix" this

**Comment by asturur** [comment]
fix the error but is gonna change the function result.
Do you think you can make up a fiddle with the error? can you make the error appear with plain fabric and some code?
