### ISSUE TITLE
Select an Object and it gets moving on the Z-Axis 

### ISSUE THREAD

**Issue by Uaargh** [kangax/fabric.js#3422]
## Version
1.6.7

## Test Case
http://jsfiddle.net/z7koh0h4/1/

## Steps to reproduce
Select a polygon and it gets moved to the Front
after a selection it should move back, but this never happens

## Expected Behavior
The Polygon should move back after it got selected

**Comment by asturur** [comment]
If you want object selection not to jump in front you need to use canvas.preserveObjectStacking = true;

When you see the object in front is just a rendering effect of rendering the active object after all the rest.
