### ISSUE TITLE
fabric.Textbox::toJSON() doesn't return selectionColor and selectionBackgroundColor

### ISSUE THREAD

**Issue by Sysaninster** [kangax/fabric.js#3423]
## Version
1.6.7

## Test Case
https://jsfiddle.net/mh8h87tt/1/

## Steps to reproduce

1 Run the example on jsfiddle

## Expected Behavior

- The key *textboxJson.selectionColor* has value *RGBA(255,0,0,0.3)*
- The key *textboxJson.selectionBackgroundColor* has value *RGBA(0,255,0,0.3)*
- The key *textboxJson.fontFamily* has value *arial*

## Actual Behavior

- The key *textboxJson.selectionColor* is undefined (wrong)
- The key *textboxJson.selectionBackgroundColor* is undefined (wrong)
- The key *textboxJson.fontFamily* has value *arial* (right)

**Comment by asturur** [comment]
https://jsfiddle.net/mh8h87tt/2/

those properties are not exported unless you specify them.
As same as borderColor, padding, and other stuff.
