### ISSUE TITLE
Fabricjs 167 + node image not working

### ISSUE THREAD

**Issue by CSI68** [kangax/fabric.js#3424]
Hello,

Since I have updated Fabricjs to 1.6.7 node server fail to render canvas with image :

ypeError: Image or Canvas expected
    at TypeError (native)
    at klass.applyFilters (/var/www/html/clemweb/public_html/vendor/custengine/lib/node_modules/fabric/dist/fabric.js:18504:33)
    at klass.setElement (/var/www/html/clemweb/public_html/vendor/custengine/lib/node_modules/fabric/dist/fabric.js:18274:14)
    at klass._initElement (/var/www/html/clemweb/public_html/vendor/custengine/lib/node_modules/fabric/dist/fabric.js:18648:12)
    at klass.initialize (/var/www/html/clemweb/public_html/vendor/custengine/lib/node_modules/fabric/dist/fabric.js:18234:12)
    at klass.initialize (/var/www/html/clemweb/public_html/vendor/custengine/lib/node_modules/fabric/dist/fabric.js:1739:52)
    at new klass (/var/www/html/clemweb/public_html/vendor/custengine/lib/node_modules/fabric/dist/fabric.js:1787:23)
    at /var/www/html/clemweb/public_html/vendor/custengine/lib/node_modules/fabric/dist/fabric.js:18734:18
    at Object._initFilters (/var/www/html/clemweb/public_html/vendor/custengine/lib/node_modules/fabric/dist/fabric.js:18677:21)
    at /var/www/html/clemweb/public_html/vendor/custengine/lib/node_modules/fabric/dist/fabric.js:18732:45

Node v: 6.9.0

Any idea ?

Thx !

**Comment by asturur** [comment]
Can i see the code that is failing?
What was the latest verision you used without problems?

**Comment by CSI68** [comment]
Hi, Asturur,

See my node code (not complet, just image treatment part):

`canvas.forEachObject(function(obj){

				if(obj.isType('image')){
					nbImgs++;
					imgsToLoad.push(obj);

				}else if(obj.isType('text')){
					console.log('> Load font "'+obj.fontFamily+'" - "'+obj.ctzParams.fontFile+'" - '+dir+ '/_custengine/fonts/'+obj.ctzParams.fontFile);
					font = new canvas.Font(obj.fontFamily, dir+ '/_custengine/fonts/'+obj.ctzParams.fontFile);
					//font = opentype.loadSync(__dirname + '/../web/_custengine/fonts/'+obj.ctzParams.fontFile);
					canvas.contextTop.addFont(font);
					nbTxts++;
				}else{
					// Only text can have shadow, other must be disabled
					obj.setShadow(0);
				}
				// Disable main clip
				obj.clipTo=null;

				


			});

			canvas.renderAll.bind(canvas);
			canvas.deactivateAll().renderAll();
			console.log('> NUMBER OF IMAGE : '+nbImgs);
			console.log('> NUMBER OF TEXT : '+nbTxts);
			var tabImgsSizes=[];
			if(imgsToLoad.length>0){

				console.log('> Resize images...');
				imgsToLoad.forEach(function(obj){
				
					tabImgsSizes[obj.ctzParams.id]={width:obj.getWidth(), height:obj.getHeight()};
					console.log('> Load old url image : '+obj.src);
					newUrl=obj.src.replace(/(size=).*?(&)/,'$1' + newMaxSize + '$2').replace(/(mode=).*?(&)/,'id_customer='+id_customer+'&token=dd0js1oc!&');
					console.log('> Load new url image : '+newUrl);
					fabric.util.loadImage(newUrl, function(img) {

						obj.setElement(img, function(){
							iImg++;
							obj.set({
								width:tabImgsSizes[obj.ctzParams.id].width,
								height:tabImgsSizes[obj.ctzParams.id].height
							});
							canvas.renderAll();

							if(iImg<nbImgs){
								return false;
							}else{
								
								canvas.renderAll.bind(canvas);
					      canvas.deactivateAll().renderAll();
					   		console.log('> End image rendering call write...');
								ctzCreateImg(res);
							}
						});
					});
				});
			}else{
				console.log('> No image rendering call write...');
				ctzCreateImg(res);
			}
		}catch(e){
			console.log('> JSON loading error : '+e.message);
		}` 

With Fabricjs166 that work like a charm... just do a npm update to get lastest fabric version.

Thx for your help

**Comment by asturur** [comment]
i do not see any changes between 166 and 167 that may be harmfull to image.
Can you make a small plain js file to run under node and investigate further?

**Comment by asturur** [comment]
your error stack seems coming from an image.fromObject, like if the image failed loading.
The code you posted seems no relavant to me.

**Comment by CSI68** [comment]
Hi,

I have entire reinstall node fabric (1.7.1) and now it's ok.

I don't know why...

Thx
