### ISSUE TITLE
not able to draw rect on existing <canvas> which rendered PDF using pdfjs

### ISSUE THREAD

**Issue by hiitskiran** [kangax/fabric.js#3425]
@kangax 

## Version
1.6.7

## Test Case
https://jsfiddle.net/hiitskiran/wgz8qore/2/
1. run the above jsfiddle
2. you can see the fabric rectangle is hiding behind the rendered pdf
3. click on the pdf canvas area to see the fabric objects

## Steps to reproduce
1. Have a canvas in your page 
   eg: < canvas id="pdfCanvas" >
2. create a fabric canvas for existing canvas
   eg: new fabric.Canvas("pdfCanvas");
3. have mouse.down, mouse.up, mouse.move methods to enable drawing rectangles
4. render pdf in the above canvas "pdfCanvas" using PDF.js
5. browser now shows the rendered PDF
6. now draw rectangles on the pdf, it hides the rendered canvas but it does draw objects

## Expected Behavior
able to draw rectangles on already rendered pdf canvas
## Actual Behavior
when I draw rectangles on the pdf, it hides the rendered canvas but  it does draw objects, objects should have been on top of rendered pdf

**Comment by hiitskiran** [comment]
I created a ticket at stackoverflow and I got a response:
http://stackoverflow.com/questions/40668947/not-able-to-draw-rect-on-existing-canvas-which-rendered-pdf-using-pdfjs/40671477#40671477

I didn't realized pdfjs page.render() is a promise, initializing fabric stuff inside promise fixed the issue (updated the fiddle as well) but is setting the backgroundimage everytime i navigate to a pdf page is the correct way or is there any other efficient way to solve this?

**Comment by asturur** [comment]
Well depends, you could have 2 layered canvas independent from them and draw separately. It really depends on our your application works and what kind of feature it has to offer.

**Comment by asturur** [comment]
i guess that having a separate canvas for fabric to display what you want to display, to overlay over pdfjs canvas, saves a draw operation, to redraw the background ( pdfpage ) everytime you do something on the fabric canvas.
Please for this kind of questions open stackoverlow question and in case ping me directly, but is not an issue we can track here.

**Comment by hiitskiran** [comment]
how do I overlay canvas over canvas? I couldnt find an example

**Comment by asturur** [comment]
just have 2 different canvas elements. overlay them with css.
FabricJS ( probably used for annotations ) on top of pdfjs.

If you need to export as a single image, the you make up something like painting fabric one with drawImage over the pdfjs or viceversa.
Depends on functionalities you need. There is not a universal valid answer.

**Comment by hiitskiran** [comment]
I am currently using : 
fcanvas.setBackgroundImage(bg, fcanvas.renderAll.bind(redactCanvas));

Are you saying I should use this instead and have 2 separate cavases:
fcanvas.setOverlayImage(pdfCanvas.toDataURL(), fcanvas.renderAll.bind(fcanvas));

as mentioned at https://groups.google.com/forum/#!topic/fabricjs/Z796c9BO7p4 ?

**Comment by sumanbogati** [comment]
@asturur, Is it good idea to have two different canvas one for pdf.js and and other for shapes(eg:-rectangle)? If we do so, what could happen when we achieve the zoom effect for both pdf on canvas and shapes on canvas?  Will the objects of both canvas zoomed with same proportionally ?

**Comment by asturur** [comment]
@sumanbogati if you need to mix 2 different rendering pipelines, maybe  overlaying to canvases is better.
It really depends on the kind of interaction you want to create.

fabricjs can zoom objects and pan the whole canvas easily, you should find a way to syncronize it with the other canvas, depending which one is driving interaction with user mouse/keyboard
