### ISSUE TITLE
moveTo causes null pointer error in deactivateAll

### ISSUE THREAD

**Issue by otterslide** [kangax/fabric.js#3426]
## Version
1.6.7

## Steps to reproduce
http://codepen.io/otterslide/pen/VmKRoz
Single Click on the right-side pug.

## Expected Behavior
Single click, only select the pug.

## Actual Behavior
The image will continue dragging even though you single clicked.

DeactivateAll should have a null check before calling:  allObjects[i].set('active', false);
allObjects[i] may be null . Calling moveTo a certain z-index may add null objects.

**Comment by asturur** [comment]
we should avoid both null objects and add the check. thanks.

**Comment by otterslide** [comment]
Just to clarify, I'm good with the way moveTo works. It's working great for me. I do need that null placeholder for future objects at that z-index.
It's just the way the null is being handled.
