### ISSUE TITLE
width value for group include the padding value

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3427]
Hi,

The width returned for a group take into the value the padding parameter.

Steps :

Use this fiddle and set the padding to "5", select an OBJECT. The width returned in the console is 150px.
Increase the padding value, and redo the test, the width is still 150px.

Try the same test but select a GROUP. the width returned will change depending of the padding value defined in the parameter (460px is returned when the padding is 5px, and 550px is returned when you set the padding at 50px).

http://jsfiddle.net/yvo89upg/1/

I suppose the padding shouldn't influence the group width value (to have the same behaviour as the Object class).

**Comment by asturur** [comment]
with good timing this time, this PR, merged one or 2 day before your issue solves the problem
https://github.com/kangax/fabric.js/pull/3420

Dist are not built yet in the repo, you have to build for yourself or wait 1.7.0 release.

**Comment by ncou** [comment]
Hi,

Thank you for the 1.7.0 release, now the padding is no more added to the object.

With my test i found something strange when the object have a scale value.

If i scale up, an image and a rect object, if i made a selection with both objects, the blue control have more space than the image object.
It seems to me there is by default 1px beetween the blue frame and the object, but in the case of "rect" object the space beetween the object and the frame is also scaled.

Not really sure to explain correctly myself, here is a pic, you can see the gap beetween the frame and the rect object, but not with the image object.

![image](https://cloud.githubusercontent.com/assets/16743322/20498362/37211ba8-b02d-11e6-909c-482a9c1aada7.png)

Here is the fiddle. Select both object to reproduce.

Is this normal or possibly a bug ? should i open a new ticket ?

Thank you for your help.
