### ISSUE TITLE
not fire 'object:modified' when set any properties(x or y or another) without mouse operation

### ISSUE THREAD

**Issue by hardikradixweb** [kangax/fabric.js#3432]
I have given functionality to set x & y of object using one button, when user click on that but I am setting x & y of selected object. it is setting x & y of object correctly and set position correctly but it is not fire "object:modified" event. When I am doing same thing using mouse(means if I move object using mouse) it is fire "object:modified" event.

**Comment by asturur** [comment]
the point of the event is firing on behalf of user actions. if you have a button and a function on its onclick, why not calling `object.fire('modified')` at the end of your function? or `canvas.fire('object:modified')` ?
