### ISSUE TITLE
Canvas inside another canvas

### ISSUE THREAD

**Issue by MULLAINATHAN** [kangax/fabric.js#3438]
Hello,

**Version**

1.5.0

**Expected Behaviour**

I need to apply slave canvas inside master canvas. Is it possible.? Please help me on this.

**jsfiddle :** [https://jsfiddle.net/mullainathan/55dw0aLt/1/](url)

**Comment by asturur** [comment]
please be more specific.
start a fiddle, explain what you need to do.

**Comment by awehring** [comment]
@MULLAINATHAN:

your jsfiddle link is broken.

**Comment by MULLAINATHAN** [comment]
Just copy & paste & Enter it on URL.

**Comment by awehring** [comment]
I get an Error 404 from jsfiddle.

**Comment by MULLAINATHAN** [comment]
Somewhat issue. Just leave it. Thanks for your response.
