### ISSUE TITLE
Custom Polygon not working properly specially on large screen resolution

### ISSUE THREAD

**Issue by farrukh-altaf** [kangax/fabric.js#3439]
Hi, 

I am working on a project for one of my client and using fabricjs. The library is amazing and I must say well done for creating this masterpiece. I haven't came across any issue in the library apart from one which is when I tried to make **Custom Polygon Shapes**. Issue explained below.   

## Version
1.6.7

## Test Case
http://jsfiddle.net/Kienz/ujefxh7w/

## Steps to reproduce

- Screen resolution 1920x1080
- In the example on jsfiddle click on blank area to enable drawing
- Click again to start drawing custom polygon
- Complete drawing custom polygon 

## Expected Behavior

- The custom polygon should start to be drawn from where the mouse is clicked exactly.
- the controls and polygon should be aligned for easy actions.

## Actual Behavior

- When mouse is click to draw polygon, it starts drawing polygon from top even out of the canvas (_specially on bigger screen resolutions_). It makes it useless for the user because the polygon calibration is out of focus. 
- The controls for the drawn polygon are also not on the object (see attached).
![image](https://cloud.githubusercontent.com/assets/23547294/20473574/84dd4444-afb9-11e6-870a-1968bad2eb86.png)

**Comment by asturur** [comment]
There is an answer for that on stackoverflow here:
http://stackoverflow.com/questions/26219238/fabric-js-how-to-draw-a-polygon-by-mouse

upvote answer and look at fiddle.
