### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'save' of undefined" when creating a new Textbox object

### ISSUE THREAD

**Issue by make2514** [kangax/fabric.js#3440]
I have encountered the error when using fabric.js version: 1.7.0.
Textbox is working well on fabric.js version: 1.6.7
Here is a jsfiddle for the issue:
https://jsfiddle.net/make2514/26u33c7j/

Any insights would be really appreciated! Thank you very much!

**Comment by asturur** [comment]
thanks 1.7.0 is fresh of release, there is a new functionality i have to still write docs for.
Getting this bug max priority
