### ISSUE TITLE
onTextChange Incorrect Width

### ISSUE THREAD

**Issue by arminbusatlic** [kangax/fabric.js#3442]
When the even text:changed is fired on my local server, the text width prints the previous width of the text object. However, running this same example on JSFiddle outputs the updated width of the text object as expected.

https://jsfiddle.net/busatlic/4ug4z9b6/

I feel that the execution of my local server happens too fast to get the updated width. Is that possible?

Not sure what I can do to fix this.

Any help is much appreciated.

**Comment by asturur** [comment]
How this run on you server? via browser? via node? please add more details

**Comment by arminbusatlic** [comment]
Yes, through Chrome. Basically, the onTextChanged event was executed before the object's width was updated. I added a setTimeout function to display the width and even when setting the timeout at 50ms, it would show correctly, but not when it had no delay.

To fix it, I did this:

text.set( [updated text] );

before measuring the width and it works :)

**Comment by asturur** [comment]
are you using 1.7.0 on your local?
so if you cal .set() the width is recalculated automatically.
If you just change it by code this.text = 'new text' is recalculate at next render.
I have no idea when the the text:changed event is called, if before the render or after.
