### ISSUE TITLE
Feature Request: Rich Text Editor

### ISSUE THREAD

**Issue by Immortalin** [kangax/fabric.js#3443]
A rich text editor such as Quilljs would really benefit fabric.js as it would make insertion of rich text content much easier. The editor however will probably have to interact with the IText() fabric API

**Comment by samael205** [comment]
I think that feature is not compatible with Canvas FabricJS. If you want a Text Editor, have WYSIWYG Editors like Froalla and Quill. You can call a new iframe wich contain a page that load QuillJS when you do Right Click on itext Instance on canvas. That is an example

**Comment by Immortalin** [comment]
What I mean is a way to set IText formatting a la a traditional rich text toolbar/tooltip with Bold/Italic/fonts etc. because right now we have to reinvent the wheel every single time in order to allow users to change text styles etc.

**Comment by samael205** [comment]
Create your own API to do that... Creating your own interface

**Comment by asturur** [comment]
This feature is out of scope for the library.
Fabricjs provide an easy way to work with canvas.
Itext and textbox have already lot of advanced features and lot of advanced bugs.
I cannot see how we could accomplished something like this without a very big effort.

There is somewhat a similar request that is the one of pasting formatted text in itext.

fabric should anyway support SVG TSPANs and so get some kind of rich text import, but html parsing of text is not included.

You can still write a function that parse rich text output and write styles object for fabricJS.

**Comment by redlive** [comment]
How to implement that kind of toolbar ? I mean how to apply style changes on selected text?
I need to change color and font size either of a textbox or just selected text.

![screen shot 2017-09-29 at 4 01 42 pm](https://user-images.githubusercontent.com/5912122/31039089-956986e4-a52f-11e7-8046-84d9dfcf6b66.png)

http://fabricjs.com/test/misc/itext.html

Tnx
