### ISSUE TITLE
Text align justified (left-justified)

### ISSUE THREAD

**Issue by DangerD256** [kangax/fabric.js#3444]
![2016-11-16 1](https://cloud.githubusercontent.com/assets/17032489/20527035/73b0bdce-b0cf-11e6-9076-a7e2461c620c.png)
Any solution to make it as on the right side? (Last line aligned to left)
In html it's ok.

**Comment by asturur** [comment]
i thought it behaved like that.
Doesn't it?
Wich text are you using?

**Comment by DangerD256** [comment]
fabric.Textbox

**Comment by DangerD256** [comment]
Any updates with that?

**Comment by DangerD256** [comment]
Anybody there?

**Comment by asturur** [comment]
Me, as always.
I just released 1.7.1 to fix some bugs.
Text needs a rewrite, i do not want to run to put patches around.
I m major concentrated on a feature I like, finally, and webgl filtering for images.
After that i need to take on this Text rewrite and fix as much things as possible.

**Comment by asturur** [comment]
Hello, i know is passed one year today, but by chance we fixed this last week with @JSteunou contribution
