### ISSUE TITLE
loadFromJSON dosen't work with clipto

### ISSUE THREAD

**Issue by kemal-atila** [kangax/fabric.js#3445]
loadFromJSON dosen't work with clipto parameter even I tried on kitchensink.
Could you help me?

http://fabricjs.com/kitchensink

{"objects":[{"type":"rect","originX":"left","originY":"top","left":241,"top":253,"width":50,"height":50,"fill":"#06980e","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":5.59,"scaleY":5.59,"angle":0,"flipX":false,"flipY":false,"opacity":0.8,"shadow":null,"visible":true,"clipTo":"function (ctx) {\n        ctx.arc(0, 0, radius, 0, Math.PI * 2, true);\n      }","backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"rx":0,"ry":0}],"background":""}

**Comment by asturur** [comment]
radius in your clipTo function is not defined. it cannot be global it must be a local var to function.

**Comment by kemal-atila** [comment]
Thanks @asturur, I think it will be better to fix on "kitchensink".

**Comment by kemal-atila** [comment]
How can I solve this? Probably Issue about this part of code.

  ```
  $scope.clip = function() {
        var obj = canvas.getActiveObject();
        if (!obj) return;

        if (obj.clipTo) {
            obj.clipTo = null;
        }
        else {
            var radius = obj.width < obj.height ? (obj.width / 2) : (obj.height / 2);
            obj.clipTo = function (ctx) {
                ctx.arc(0, 0, radius, 0, Math.PI * 2, true);
            };
        }
        canvas.renderAll();
    };
```
