### ISSUE TITLE
path parsing still not good.

### ISSUE THREAD

**Issue by dnanusevski** [kangax/fabric.js#3446]
## Version
1.7.0 and  most earlier versions,  
object made in 1.5.0 that i am still using.

image of object made in 1.5.0
![1 5 0](https://cloud.githubusercontent.com/assets/12953253/20543563/9703b4b6-b106-11e6-9412-a7e70ad366f7.jpg)

image of object loaded in 1.7.0
![1 7](https://cloud.githubusercontent.com/assets/12953253/20543584/a778d34e-b106-11e6-9e36-7eb849460ed8.jpg)

Object code:

var labialniLukGore=new fabric.Path(' \
M 190 155 Q  180 170 160 155\
L 120 115 \
C 85 75 125 45 150 70\
L 165 85\
Q 170 88 185 80 \
Q 220 60  263 60\
\
M 338 155 Q 346 170  366 155\
L 406 115\
C 440 75  400 45 376 70\
L 360 85\
Q 356 88 340 80\
Q 306 60 263 60  ',	
{top:55,scaleY:0.95,id:"labialniLuk",stroke:"red",fill:'transparent',padding:5,strokeWidth: 2,lockMovementX:true,lockMovementY:true,hasControls:false});

**Comment by asturur** [comment]
can you create a fiddle with failing case?

**Comment by dnanusevski** [comment]
https://jsfiddle.net/jf03bbc3/1/

**Comment by asturur** [comment]
![image](https://cloud.githubusercontent.com/assets/1194048/20558840/5edf4e26-b172-11e6-9602-6d4c8e10ef4f.png)

Ok this is how 1.4.13 was rendering it.
Bad also.
That is not an easy fix.

**Comment by asturur** [comment]
for now to fix the visual missing part, you can give to this shape object the property  `objectCaching = false`

**Comment by mariotacke** [comment]
May I suggest that we rename this issue to include the word "clipping" or "clip"? When I submitted my issue, I was unable to find this discussion.

@asturur Can you modify/create a fiddle to show where to apply the `objectCaching = false` option, please?

**Comment by asturur** [comment]
that doc i linked does not report it?

**Comment by asturur** [comment]
that doc i linked does not report it?

**Comment by mariotacke** [comment]
You are right, I guess that works.

**Comment by asturur** [comment]
![image](https://cloud.githubusercontent.com/assets/1194048/23939703/41ce63c4-0962-11e7-93a8-a5e7ab05e90b.png)

yeeeee

closed thanks to @by12 and #3774
