### ISSUE TITLE
setBackgroundImage setting wrong image size  when page is zoomed

### ISSUE THREAD

**Issue by dnanusevski** [kangax/fabric.js#3447]
## Version
1.7.0 and most earlier versions.
Problem is not present in version  1.5.0

Image of CANVAS1 for passing to function  toDataURL
![1 7 0 zoomerror](https://cloud.githubusercontent.com/assets/12953253/20544660/682818c6-b10b-11e6-8e08-b6afc762769d.jpg)

Calling function updateimage()
{
var backgroundc1=canvas.toDataURL();
canvas2.setBackgroundImage(backgroundc1,canvas2.renderAll.bind(canvas2));
}

And resulting CANVAS2

![1 7 0 zoomerrorb](https://cloud.githubusercontent.com/assets/12953253/20544715/a5ca0518-b10b-11e6-8f66-24ab71aa7272.jpg)

**Comment by asturur** [comment]
can you reproduce in a fiddle please?
looks like retina problem.

**Comment by asturur** [comment]
sorry i read now. yes if zoomed there is nothing you can do. zoom gets mixed with pixel ratio. also this happens only if you load the app with page already zoomed.
can t really be fixed unless browers expose zoom somewhere.

**Comment by dnanusevski** [comment]
Can this help. 
https://github.com/kangax/fabric.js/issues/3447
This is a serious issue for my application, users are constantly reminding me. So i had to go back to 1.5.0
Sry for bothering

**Comment by asturur** [comment]
you do not need to go back to 1.5.0 you can simply disable retinascaling with the appropriate option at canvas init. please search the docs for enableRetinaScaling.
