### ISSUE TITLE
LoadFromJson not working with fabric text with new line

### ISSUE THREAD

**Issue by vxrai** [kangax/fabric.js#3449]
LoadFromJson does not load the text containing new line on canvas.
But it works perfectly when the entire text is in one line.
The issue is with both fabric.Text and fabric.IText
Please suggest a fix.

**Comment by vxrai** [comment]
@asturur hope you could help with this as well

**Comment by asturur** [comment]
please attach a fiddle that show JSON code to load and code used to load it.

**Comment by vxrai** [comment]
@asturur - My bad, while creating the fiddle for the issue I found out that the issue isn't with fabric js. But when i fetch the json from the database, and apply in loadFromJson() the \n changes to a new line causing the issue. Need to find a fix for that now.

**Comment by asturur** [comment]
ok not fabric related then. i can close.

**Comment by dabcorp** [comment]
Hello ,

LoadFromJson with Line Break not work : 

SyntaxError: JSON.parse: bad control character in string literal at line 1 column 1234 of the JSON data : 

```
{"objects":[{"type":"i-text","originX":"left","originY":"top","left":1000,"top":3030,"width":2,"height":72.32,"fill":"#000","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"","fontSize":64,"fontWeight":"normal","fontFamily":"Gotham","fontStyle":"normal","lineHeight":1.16,"underline":false,"overline":false,"linethrough":false,"textAlign":"center","textBackgroundColor":"","charSpacing":0,"styles":{}},{"type":"textbox","originX":"center","originY":"center","left":4050,"top":3400,"width":800,"height":156.21,"fill":"#000","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"88 rue Bataille
69008 Lyon","fontSize":64,"fontWeight":"normal","fontFamily":"Arial","fontStyle":"normal","lineHeight":1.16,"underline":false,"overline":false,"linethrough":false,"textAlign":"center","textBackgroundColor":"","charSpacing":0,"minWidth":20,"styles":{}}],"backgroundImage":{"type":"image","originX":"left","originY":"top","left":0,"top":0,"width":5433,"height":3779,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"crossOrigin":"","alignX":"none","alignY":"none","meetOrSlice":"meet","src":"http://localhost/ui/produits/flyers/Flyer1.jpg","filters":[]}}
```
Please help.

**Comment by asturur** [comment]
is a json parsing error. check the 1234th char. what is it, what is before?

**Comment by dabcorp** [comment]
Hello,

1 - I save Canvas to Mysql : JSON.stringify
2- I load Canvas from Json : loadFromJSON
3 - My canvas contains a textbox with lines break
4 - Without lines break , loadFromJson work

When i load this , Json Error "SyntaxError: JSON.parse: bad control"

thx

**Comment by asturur** [comment]
i think you are not preserving slashes when saving to mysql.
please check that the json string before database insertion is the same you retrive on reload.

i think that the \n are becoming real new lines.

**Comment by SarathMohandas** [comment]
Hi All, this is a piece of code I have been trying to convert, but the loadFromJson is not working(NB: we reproduce this code in this link by replacing the _var json='';
_   [http://jsfiddle.net/fabricjs/fmgXt/](http://jsfiddle.net/fabricjs/fmgXt/) ). Shows this error

`
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at klass._splitTextIntoLines (fabric.js:26564)
    at klass._splitText (fabric.js:25527)
    at klass.initDimensions (fabric.js:25544)
    at klass.callSuper (fabric.js:2758)
    at klass.initDimensions (fabric.js:27331)
    at klass.initDimensions (fabric.js:2711)
    at klass.initialize (fabric.js:25489)
    at klass.initialize (fabric.js:2711)
    at klass.callSuper (fabric.js:2757)
    at klass.initialize (fabric.js:27277)
    at resolvePromise (zone-evergreen.js:1209)
    at zone-evergreen.js:1116
    at fulfilled (tslib.es6.js:73)
    at ZoneDelegate.invoke (zone-evergreen.js:368)
    at Object.onInvoke (core.js:28494)
    at ZoneDelegate.invoke (zone-evergreen.js:367)
    at Zone.run (zone-evergreen.js:130)
    at zone-evergreen.js:1272
    at ZoneDelegate.invokeTask (zone-evergreen.js:402)
    at Object.onInvokeTask (core.js:28481)
`

**Related Code is shown below**

var json1= '{"version":"4.3.1","objects":[{"type":"i-text","version":"4.3.1","originX":"left","originY":"top","left":485.51,"top":129.32,"width":142.6,"height":56.5,"fill":"#93f401","stroke":"rgba(0,0,0,1)","strokeWidth":0.5,"strokeDashArray":null,"strokeLineCap":"butt","strokeDashOffset":0,"strokeLineJoin":"miter","strokeUniform":false,"strokeMiterLimit":4,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","skewX":0,"skewY":0,"id":"585cc86e-2f91-4809-9f56-3a2847a51dc5","styles":{},"name":"SELECT :5f"}],"background":"#2d2d2d"}';

What I'm missing during the conversion of **i-text**, the son is working for other types- **rect, circle,** etc. Kindly help me.
Sarath Mohandas

**Comment by kantsverma** [comment]
I am also facing the same issues for  \n text canvas not loadin in case of font  \n in text object.
Did you resolved this ?

**Comment by asturur** [comment]
if you have a full non working example please make a fiddle and show the issue in detail with as little code as possible. Generating the json in the fiddle and not pasting it from other sources

**Comment by kantsverma** [comment]
@asturur   Here you can see the fiddle in script code you can see var =json_0, json_1 variable both JSON are the same only difference is the height of the text object and \n in text values. First JSON rendering fine without \n and 2nd not working 

[Fiddle](https://jsfiddle.net/kantsverma/7jq2yro6/8/)
![json_diffrence](https://user-images.githubusercontent.com/6929043/111772942-81144b80-88d3-11eb-88c1-aac00b7a95a2.png)

**Comment by asturur** [comment]
Can you generate the JSON directly from the app rather than copy pasting it from somewhere else?
if the JSON is pre-generated we have no idea where the bug is.

**Comment by kantsverma** [comment]
@asturur I find the bug bus is in the text object. I am using the text area input fields to add the multiline text and in case of adding new line text added like this "text":"textline1\ntextline2\ntextline3" this is creating the problem If i added the \\n instead on \n it works fine but now there is another issue i am trying to replace \n with  \\n but json picking only \n

**Comment by SarathMohandas** [comment]
@kantsverma , I fixed that issue by Serialization. Would you check this link [(http://fabricjs.com/fabric-intro-part-3#serialization)].
All you need to do is work with **toObject** method — either completely replacing it or extending it.

**Comment by kantsverma** [comment]
@SarathMohandas 
Thank you yes we can do that also but my requirement was something different. But yes your approach can also helpful for many.
Thank you once again.

**Comment by SarathMohandas** [comment]
Hi @asturur,
These are the steps I follow, during the uploading and downloading of the canvas. This project is doing in angular.
Step 1 - I save Canvas to DB/Text Files using: JSON.stringify              (Working well with Serialization)
Step 2 - I load Canvas from that TextFile for editing: loadFromJSON (Uploads Correctly)
Step 3 - Making some changes in the Uploaded Canvas and uploading again the **text, Itext** extended classes are truncated.



![image](https://user-images.githubusercontent.com/49875195/113257885-d7788580-92e8-11eb-814b-b83b1f53a438.png)

Supporting  Codes are given below.
```
/// 
/// SAVING TO TEXT FILE FORMAT
///
async onSave(layoutName:any) {
    this.layoutName =layoutName;      
    console.log(JSON.stringify(this.canvasJson));  
    if(this.canvasJson) {
      let blob = new Blob([JSON.stringify(this.canvasJson)], { type: 'text/plain' });
      FileSaver.saveAs(blob, this.layoutName + '.text'); 
      this.layoutName = null; 
    }   
    this.fabricService.addGrid(this.fabricService.canvas);
    this.addNameModel.hide();
  }

///
/// TEXT FILE TO CANVAS
///
async onChange(event:any): Promise<void> {
  const files = event.target.files;
  let file = files[0];  
  if(file) {
    const data = await new Response(file).text(); // .json()   
    console.log(data);
    this.fabricService.addGrid(this.fabricService.canvas); 
    this.fabricService.canvas.loadFromJSON(data, 
                                            this.fabricService.canvas.renderAll.bind(this.fabricService.canvas));     
    this.fabricService.updateModifications(true);
  }  
  console.log(this.fabricService.canvas);
  this.reset();
  this.uploadPromptModal.hide();
   
  }
```
What I'm missing? kindly advise me. 
NB: I think there may be an issue during JSON.stringify(this.canvasJson), which truncates the Extended classes.
