### ISSUE TITLE
TextBox object not working in latest version (1.7.0)

### ISSUE THREAD

**Issue by ssalawria** [kangax/fabric.js#3450]
## Version
1.7.0

## Test Case
https://jsfiddle.net/09dyeL4v/5/

getting an error in console
"fabric.min.js:8 Uncaught TypeError: Cannot read property 'save' of undefined(…)"

## Steps to reproduce
Try to add text box in the canvas 
https://jsfiddle.net/09dyeL4v/5/

## Expected Behavior
textbox should be added in the canvas

**Comment by asturur** [comment]
It has been fixed,, you need to downalod the library and build it from console.
