### ISSUE TITLE
Fabric js - How do i know currently working canvas

### ISSUE THREAD

**Issue by MULLAINATHAN** [kangax/fabric.js#3451]
## Version
1.5.0

## Test Case
<canvas id="canvas1" width="500" height="300">
<canvas id="canvas2" width="500" height="300">
<canvas id="canvas3" width="500" height="300">

var canvas1, canvas2, canvas3 = '';
canvas1 = new fabric.Canvas('canvas1');
canvas2 = new fabric.Canvas('canvas2');
canvas3 = new fabric.Canvas('canvas3');

## Expected Behavior
From here, after adding some objects. Programatically i have to identify which one is active canvas.

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
