### ISSUE TITLE
Objects disappear on zoom out

### ISSUE THREAD

**Issue by b0r3d0m** [kangax/fabric.js#3453]
Subj.

You can take a look at the problem via the following code -- https://jsfiddle.net/t3jkrmn6/ (just use a mouse wheel and you'll notice what I mean).

How can I prevent such behavior?

Is there any way to set a constant width for some elements (for example, `strokeWidth: 1` for lines) no matter how much user zoomed out a canvas? If it's not possible to do via API, what can I change in the library code then?

Thanks in advance.

**Comment by samael205** [comment]
You can the min zoom level, when you do zoom out and zoom in. You can get the actual Zoom with canvas.getZoom() and set the min zoom level and the max zoom level

**Comment by b0r3d0m** [comment]
You mean that I can set the minimum zoom level? Is it the only option?

**Comment by samael205** [comment]
I do not know any other way. At least fabric does not have a minimum zoom property on canvas

**Comment by b0r3d0m** [comment]
Thanks but it's not exactly what I need anyway. I mean, is there any option to set fixed `strokeWidth` for lines? I don't want to zoom in and out specific elements.

**Comment by samael205** [comment]
Ah, ok, It is not related with the zoom. The only whay that i know at this moment, is, re-calculate the ScaleX and ScaleY for the line,

**Comment by b0r3d0m** [comment]
How can I do it? It seems that the `object:scaling` event doesn't fire up when the user tries to zoom a canvas.

**Comment by samael205** [comment]
Not needed, you needs to recalculate when you do mousewheel.

**Comment by b0r3d0m** [comment]
It looks like `element.set({scaleX: 200}); canvas.renderAll();` doesn't change anything at all. Could you please provide an example (or modify the original one -- https://jsfiddle.net/t3jkrmn6/)? It will be really cool!

**Comment by b0r3d0m** [comment]
So I tried something like this:

```
  function restoreElements(elements) {
    for (var i = 0; i < elements.length; ++i) {
      var element = elements[i];
      if (element.type === 'group') {
        restoreElements(element._objects);
        continue;
      }
      if (element.fixedSize) { // My custom attribute
        element.set({scaleX: 200}); // Just for tests
        element.set({scaleY: 200}); // Just for tests
      }
      canvas.renderAll();
    }
  }

  canvasWrapper.mousewheel(function(e) {
    if (e.originalEvent.deltaY < 0) {
      var newZoom = canvas.getZoom() * 1.1;
    } else {
      var newZoom = canvas.getZoom() / 1.1;
    }
    canvas.setZoom(newZoom);
    
    restoreElements(canvas._objects);
  });
```

**Comment by samael205** [comment]
I tried with this, but does not work... Sorry, https://jsfiddle.net/samael205/t3jkrmn6/2/

**Comment by asturur** [comment]
https://jsfiddle.net/t3jkrmn6/4/

in this example the stroke of the line does not disappear when zooming.
That is just an idea to solve your implementation details.
Is not a fabricjs bug so i can close.
