### ISSUE TITLE
1.7.0 canvas.clipTo function 

### ISSUE THREAD

**Issue by Godweed** [kangax/fabric.js#3454]
Canvas.clipTo function problem, looks like clipTo function overlay the object even it is inside the visible area after 1.7.0 update
## Version
1.7.0

## Test Case
with version 1.6.7
http://jsfiddle.net/d7w1nudj/
with version 1.7.0
http://jsfiddle.net/btLfdm0c/

## Expected Behavior
Clip to function do not render object even inside the visible area 
## Actual Behavior
before 1.7.0 objects rendered properly inside canvas.clipTo function

**Comment by ncou** [comment]
Seems like a bug with the cache.
For the moment you can disable the cache function to have the display : 

http://jsfiddle.net/btLfdm0c/1/

**Comment by asturur** [comment]
So this is nothing i can really fix.
The clipTo function works with paths and not with cached images.
So the only way to clip correctly with a shape is to create the shape with `objectCaching: false` so that it will be drawn with normal code and will clip properly.
