### ISSUE TITLE
demo pattern broken

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3456]
Hi,

The pattern demo are broken on the fabric.js website : 

http://fabricjs.com/patterns
and 
http://fabricjs.com/dynamic-patterns

You change the settings and nothing change. you need to froce the refresh by stretching a bit the object to get the good rendering.

Same for the clipping demo.

I think it come from the new "objectCaching" parameter, It's perhaps better to set it to false by default in the fabric.js lib, because the lack of refresh when you change a setting is a bit disturbing.

**Comment by asturur** [comment]
fixed thanks!

**Comment by asturur** [comment]
For the dinamyc patter i set it to off, for the other demo i set statefullCache: true.

And i published docs: `http://fabricjs.com/fabric-object-caching`
