### ISSUE TITLE
TextBox doesn't work in Fabric 1.7.0

### ISSUE THREAD

**Issue by dennisrjohn** [kangax/fabric.js#3457]
## Version
1.7.0

## Test Case
https://plnkr.co/edit/uS1lrCkDOiEUIFFN8hKf?p=preview
In the above plunker, commenting out the fabric 1.7.0 reference and uncommenting the 1.6.7 reference causes the example to work.

## Steps to reproduce
1. Add a TextBox  to any fabric canvas.

## Expected Behavior
The Textbox is displayed.

## Actual Behavior
An error is generated: 
Uncaught TypeError: Cannot read property 'save' of undefined.

Caused by this line:
 _splitTextIntoLines: function() {
      var originalAlign = this.textAlign;
      this.ctx.save(); <--- this.ctx is undefined here

**Comment by asturur** [comment]
is fixed in current master. we did not re release yet.
