### ISSUE TITLE
IText inside modal

### ISSUE THREAD

**Issue by anibalcezarr** [kangax/fabric.js#3460]
## Version
1.7.0

## Steps to reproduce
If you have a canvas inside a modal and when you try to edit the IText inside this canvas, is not possible.

**Comment by janfrs** [comment]
hello, I have the same problem

**Comment by asturur** [comment]
i do not know wich problem, since the issue is so generic and open ended that everything could be. 

open a fiddle with little code and a clear problem and we will reopen the issue and we will try to fix it.
