### ISSUE TITLE
When editing text error in the textbox

### ISSUE THREAD

**Issue by LunevAndrey** [kangax/fabric.js#3461]
## Version
1.7.0

## Test Case
http://jsfiddle.net/Da7SP/257/

## Steps to reproduce
When editing text error in the textbox ( Uncaught TypeError: Cannot read property 'save' of undefined ). And adding text to the form of the first letter down

**Comment by asturur** [comment]
is fixed in current master branch
 re relase did not happen yet.

**Comment by LunevAndrey** [comment]
Fixed in current master branch is adding TextBox. But editing text inside TextBox is not fixed. I checked it in  current master branch.

**Comment by asturur** [comment]
thanks for spotting, i will verify and fix asap
