### ISSUE TITLE
shadow redraw onMouseUp in Freedrawing

### ISSUE THREAD

**Issue by Rad1calDreamer** [kangax/fabric.js#3462]
## Version
1.7.0

## Test Case
http://jsfiddle.net/q0ures6q/

## Steps to reproduce
draw line and mouseUp

## Expected Behavior
shadow are not changing
## Actual Behavior
shadow changed

**Comment by asturur** [comment]
is sort of retina bug in my opinion.
are you on retina enabled screen?

**Comment by Rad1calDreamer** [comment]
no, windows 7 and BENQGL2460

**Comment by asturur** [comment]
ok is just another bug then.
Shadow values are doubled when switching from freeDrawing to final path.

**Comment by Rad1calDreamer** [comment]
thanks!
