### ISSUE TITLE
Image Stroke issue

### ISSUE THREAD

**Issue by DangerD256** [kangax/fabric.js#3464]
A bit weird about image stroke:
https://jsfiddle.net/rwb8cbot/
I i set any stroke width i get unexpected results

But in this case all works fine:
https://jsfiddle.net/rwb8cbot/5/

**Comment by LunevAndrey** [comment]
You  in setStrokeWidth () pass string.
Method accepts a number as an argument

**Comment by asturur** [comment]
yes please use number.
