### ISSUE TITLE
How to reduce selection area padding in text object in fabric js

### ISSUE THREAD

**Issue by Vivek-KT** [kangax/fabric.js#3465]
Hi to all,
Here, we have working in fabric.js with creating design tool.We need to reduce padding for selection area in text object in fabric js. Canvas object text is highlighted/selected and although it is as big as the original size, the selected box stretches over the working area.This is not as user friendly to handle this issue.How to reduce selection area padding size in canvas object. we have tried to added padding in "Canvas.set()" function but it is not response/change in working area.

`objss.set({ `
	`borderColor: 'green',  `
	`cornerColor: 'purple',  `
	`CornerSize: 33,`
         `transparentCorners: false,`
         `strokeWidth: 10,`
         `padding:4,'
`});`
![text_border_1](https://cloud.githubusercontent.com/assets/4013115/20748962/5b34d5f8-b716-11e6-995b-b9e78f6bb368.png)
Kindly review it and let me know your feedback.

THANKS
VIVEK KT.

**Comment by asturur** [comment]
you can just reduce lineHeight to 1
