### ISSUE TITLE
Firefox issue

### ISSUE THREAD

**Issue by DangerD256** [kangax/fabric.js#3467]
Open http://fabricjs.com/kitchensink in latest Firefox, zoom in using mouse wheel and than try to move it using Alt+left mouse click.
In chrome all fine, in firefox it zooms in and stuck.

**Comment by DangerD256** [comment]
Why it's closed? It's a bug definetly

**Comment by asturur** [comment]
not relative to this issue tracker. I will track next time i can update the website.
there is another repository that is fabricjs.com, you can repost it there.

**Comment by DangerD256** [comment]
I have same issue on my website, I'm using version 1.7.1

**Comment by asturur** [comment]
Is not a fabric related issue.
That thing jump because on mouse move the viewport is set to some bad number.
Has something to do on how firefox handles events. i guess .x and .y are not available or are NaN.

**Comment by DangerD256** [comment]
```
  function getPointer(event) {
    event || (event = fabric.window.event);

    var element = event.target ||

```
event is undefined

Yes, on firefox events is not working at all..
