### ISSUE TITLE
Textbox scale controls

### ISSUE THREAD

**Issue by fatlinesofcode** [kangax/fabric.js#3468]
Its seems that only Itext objects add scale controls and Textbox objects add line-width controls. I'd like to have both on the same object.

Is it possible to have both line-width controls and scale controls on a Textbox object. So that line-width controls would be in the left-middle, right-middle and the scale controls would be on the corners only?

**Comment by asturur** [comment]
not now. Text need a rewrite and i guess when i managed to do it they will have.
I see online some fabricjs based app that have this modification.

**Comment by cibehzf** [comment]
i need it
