### ISSUE TITLE
Custom attributes on "Pattern" object [Feature request ?]

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3470]
Hi,

I try to add a custom attribute for the "Pattern" object, I think from the documentation we can add custom attributes, but not really sure (because the attribute seems limited to offsetX/Y...etc), so i tried a few tests with a fiddle :

http://jsfiddle.net/QT3pa/151/

I was thinking adding custom propoterties could be possible on all fabric objects.

If it's not a bug do you think this feature request could be admissible ?

I want to add a custom attribute like for example "code", to be able to identify the pattern used when i will load the exported json data.

Thank you. Keep up the good work.

**Comment by asturur** [comment]
i guess is just on main classes, but i cannot see why not implementing it if not trivial.
