### ISSUE TITLE
Blurrying bug with several lines in a group

### ISSUE THREAD

**Issue by b0r3d0m** [kangax/fabric.js#3471]
## Version
1.7.0

## Test Case
https://jsfiddle.net/90tw8mfs/

## Steps to reproduce
- Open the link above
- Use your mouse wheel to zoom in / zoom out the canvas
- You'll notice that lines in the second group receive blurrying effect eventually (click on the image):
![blurrying](http://i.imgur.com/xKkKXUO.png)

## Expected Behavior
No blurrying should be applied (as for the first group with a single line in it)

## Actual Behavior
Blurrying effect is applied for the second group (the one with several lines)

Why? Is there any workaround?

**Comment by asturur** [comment]
how much did you zoom?
You can complain about blurrying if you have a strokeWidth 2 and a zoom of 50%. Ok in that case maybe something can be improved.
In all other situations if you your line has a final strokeWidth of 3.12657 pixels, the canvas will blur to represent the non full pixel.
Unless you can provide more details about what you think is wrong, i will close this issue.
