### ISSUE TITLE
Build using npm?

### ISSUE THREAD

**Issue by d3nd0h** [kangax/fabric.js#3472]
Hi, I am trying to build the distribution file on my own. How to do that?
What I've tried,
run `node build.js`
from the root folder and fabric folder inside the node_modules
the first one will obviously failed since I don't have the `build.js` file, the later one will produce `HEADER.js is missing` error.

Do I miss any step? The README guide seems to very simple yet I can't get it working, or should I clone the fabric manually? Thanks!

EDIT: this is only happen when I used `npm-install` the reason is I wanted to use fabric like `require('fabric')` from my server-side code, so it will include the distribution file automatically to the frontend (I've read that I could use CDN but this would defy my purpose)

## Version
1.6.4

**Comment by asturur** [comment]
you have to clone the repository to build your own version.

**Comment by d3nd0h** [comment]
Thanks for the info! Maybe this could be included in npm site readme?
