### ISSUE TITLE
Chrome mobile mode

### ISSUE THREAD

**Issue by d3nd0h** [kangax/fabric.js#3481]
Hi I hope this is not a duplicate.
Using Chrome dev mode and set it to mobile device would make fabric object immovable, I've tried it can be selected but it can't be moved.

Is this fabric's bug or chrome's?

## Version
1.6.7

## Test Case
http://128.199.153.83/test.html

## Steps to reproduce
1. try to move around the circle initially on the corners
2. open dev mode and change device to mobile 
3. try the same thing

## Expected Behavior
should work

## Actual Behavior
can't move the objects on mobile mode

**Comment by asturur** [comment]
No idea but on real mobile hardware it works.
It could have something to do with the touch detection.

**Comment by d3nd0h** [comment]
yeah indeed, that's what makes this weird! I tried selected event it works though. Though not vital this could bring a pain for responsive development.

**Comment by asturur** [comment]
you should have a look on how we support touch detection. there is some kind of disabling clicks if touch is supported, if chrome enable touch events but then fires clicks, we may fail. what about firefox same mode?

**Comment by d3nd0h** [comment]
I've also tried set up `isTouchSupported: false` in fabric canvas construction still no good. I might do wrong in disabling the touch support.

Tried in firefox, everything's ok!
