### ISSUE TITLE
When select multi-flipped objects The flipX and flipY will be change...

### ISSUE THREAD

**Issue by Jandou6** [kangax/fabric.js#3482]
## Version
1.7.1

## Test Case
http://fabricjs.com/

## Steps to reproduce
**# 1. select multi-flipped object and you will found that the object flipY is true, but the flipX is false.**

if the flipX or flipY has been change. you will has a error when you fliper the flipped-object again.
look like use that 

```
    obj.setFlipX(!obj.flipX);
```

![err3](http://oage4l7r6.bkt.clouddn.com/err3.jpeg)
![err4](http://oage4l7r6.bkt.clouddn.com/err4.jpeg)
![err5](http://oage4l7r6.bkt.clouddn.com/err5.jpeg)
## Expected Behavior

the flipX and flipY don't be change
## Actual Behavior
the flipX and flipY  has been change

**Comment by asturur** [comment]
we should not care about internal values as long as visually it works consistently.

https://jsfiddle.net/6vg5d3oz/2/

look this fiddle. Every polygon is differently flipped.
Move them around group and ungroup. If it does not make strange things is ok.


Also observe:

step 1:

![image](https://cloud.githubusercontent.com/assets/1194048/20830326/4f5612e0-b880-11e6-8df9-c549d00c7b77.png)

step 2:

![image](https://cloud.githubusercontent.com/assets/1194048/20830342/627b3800-b880-11e6-9fd0-0b50cd547422.png)

step 3:

![image](https://cloud.githubusercontent.com/assets/1194048/20830357/6d766fa4-b880-11e6-8847-9e6b29c67a84.png)

it may change flipX and flipY internally but it rotate the object to compensate.
The ungrouping is going to pick up ONE possible solution from the MANY available to represent the object in that positions.

**Comment by melvynhills** [comment]
I could fix this behaviour for my needs with these changes (not thoroughly tested yet).

As soon as flip values are changed, subtracting 180° from the angle and set back the original flip values seems to do the trick.

```javascript
fabric.Group.prototype.realizeTransform = function(object) {
  var matrix = object.calcTransformMatrix(),
      options = fabric.util.qrDecompose(matrix),
      center = new fabric.Point(options.translateX, options.translateY),
  // custom code start ------------------------------------------------------------------
      originalFlipX = object.flipX,
      originalFlipY = object.flipY;
  // custom code end ------------------------------------------------------------------

  object.flipX = false;
  object.flipY = false;
  object.set('scaleX', options.scaleX);
  object.set('scaleY', options.scaleY);
  object.skewX = options.skewX;
  object.skewY = options.skewY;

  // custom code start ------------------------------------------------------------------
  if (originalFlipX !== object.flipX || originalFlipY !== object.flipY) {
    object.flipX = originalFlipX;
    object.flipY = originalFlipY;
    options.angle -= 180;
  }
  // custom code end ------------------------------------------------------------------

  object.angle = options.angle;
  object.setPositionByOrigin(center, 'center', 'center');

  return object;
};

```
