### ISSUE TITLE
Cloning objects (Textbox issue)

### ISSUE THREAD

**Issue by DangerD256** [kangax/fabric.js#3483]
Try to copy Textbox object (Ctrl+C + Ctrl+V) and edit one of them. Both will be edited. How to prevent this?

http://jsfiddle.net/5m77ogw8/33/
![image](https://cloud.githubusercontent.com/assets/17032489/20831356/44b8ffc0-b88d-11e6-8eb9-7f87f73a320e.png)

...

Also have a check this: https://github.com/kangax/fabric.js/issues/3444

**Comment by asturur** [comment]
an object is cloned using its own clone method.

text.clone(function(cloned) {
  canvas.add(cloned)
});

over fabric.util.object.clone there is written in jsdocs that is not meant to clone fabricObjects, but is an internal util to clone plain javascript objects.
