### ISSUE TITLE
Quadratic demo not working

### ISSUE THREAD

**Issue by jorgeflorez** [kangax/fabric.js#3484]
## Version
1.7.0 1.7.1

## Test Case
https://jsfiddle.net/9k7xhahg/

## Steps to reproduce
run the test case using Fabric.js version 1.7.1

## Expected Behavior
The curve is painted and modified when a circle is dragged.

## Actual Behavior
The curve is not painted. Nothing happens.
If the quadratic demo is run on a version previous to 1.7.0 it works (i.e. the curve is painted and it changes when the circles are moved.). Should a method be called to update the curve on the latest version?

Best Regards,

Jorge

**Comment by asturur** [comment]
disableObject caching.
I guess there is a bug anyway that i will fix tomorrow about the statefullCache that is not working.
Please read here:
http://fabricjs.com/fabric-object-caching

**Comment by asturur** [comment]
fixed.
