### ISSUE TITLE
SetFill bug on fabric.Polygon

### ISSUE THREAD

**Issue by delian7** [kangax/fabric.js#3486]
## Version
1.7.0

## Test Case
http://jsfiddle.net/Da7SP/266/

## Steps to reproduce
Make a new polygon from set of points. 
Attempt to set fill by:

```
canvas.getObjects()[0].setFill("yellow");
canvas.renderAll();
```

## Expected Behavior
After `canvas.renderAll();` the entire polygon should be yellow. Note: When you resize by dragging the controls, the view refreshes and polygon becomes yellow.  

## Actual Behavior
End result is a yellow triangle at the top right.

**Comment by asturur** [comment]
this has to do with internal rendering of the polygon and point translations. very weird.
Top priority.
