### ISSUE TITLE
Font family is not loaded when used with loadfromJSON

### ISSUE THREAD

**Issue by harshakiranKJ** [kangax/fabric.js#3487]
## Version
1.7.0 - 1.7.1

## Test Case
http://jsfiddle.net/fmgXt/652/

## Steps to reproduce
execute the fiddle
## Expected Behavior
the font is abril fatface but is not displayed when loaded from canvas.loadFromJSON
## Actual Behavior
i used 1.6.3, 1.6.7 versions before and it used to work properly.

**Comment by asturur** [comment]
http://jsfiddle.net/fmgXt/653/

Look at your fiddle.
You load AbrilFatface and you provide `Abril Fatface` and you put as SRC instead of a font url, another font face url.

Please check that your code outside fabric is correct before posting an issue.

**Comment by harshakiranKJ** [comment]
Hi! 
sorry for the font issue. i was in a hurry to recreate on the fiddle.
i just updated 1.7.0 in my application yesterday and load from json stopped loading the font family. 
in the fiddle http://jsfiddle.net/fmgXt/653/ the json does not load the font family too. i have to insert any  new text for the changes to take effect. why the font family is not applied immediately after loadfromjson?

**Comment by asturur** [comment]
ops it loads just after a refresh.
Because the font is not loaded yet.
At first time you are gonna paint on canvas the load request will trigger and then it will be available.
Disabling the cache should give you less font loading problems but you should create your own font loading mechanism.
There are some small libs like https://github.com/bramstein/fontfaceobserver super easy to use and that will give you no problem when you use font on canvas.
Loading the font require some time ( some millisecond ) in that time the canvas draws but without your font, will use default one.

**Comment by asturur** [comment]
http://jsfiddle.net/fmgXt/654/  look this example with native fontFace api.
fontface observer is cross browser, fontFace api is just for chrome and firefox for now.

**Comment by niyotaa** [comment]
Hi!
 i think the real problem is if a json contains multiple font families and i try using the loadfromJSON method.
here is the fiddle

http://jsfiddle.net/fmgXt/663/

**Comment by harshakiranKJ** [comment]
Hi!
 i think the real problem is if a json contains multiple font families and i try using the loadfromJSON method.
here is the fiddle

http://jsfiddle.net/fmgXt/663/

**Comment by harshakiranKJ** [comment]
Hi! 
These are my observations

fonts are already loaded when my application starts
1) I dont see the problem when pushing the json data to a database and reading from it later and using the loadfromjson method.

2) The problem comes when i try to read the json file and use the loadfromjson method.

here are my file read methods
    // SAVE JSON : 
    'click #savejson': function(event) {
        var jsonstrings = JSON.stringify(canvas.toDatalessJSON());;
        event.target.href = 'data:plain/text,' + jsonstrings;
    },

    // LOAD JSON
    'change #loadjson': function(e) {

        // Create a reader, read the file and add the json to canvas
        var reader = new FileReader();
        reader.onload = function(event) {
            var data = event.target.result;
            canvas.loadFromJSON(data, canvas.renderAll.bind(canvas), function(o, object) {

            });
        }
        reader.readAsText(e.target.files[0]);
    },

Thanks,
Harsha

**Comment by asturur** [comment]
There is no other problem other than waiting for the fonts to be loaded.
http://jsfiddle.net/fmgXt/664/
Every font loader gives you a callback that gets called when the font finishes loading.
Is not something you can skip at all.
Please read my updated fiddle and read google font loader docs.

**Comment by harshakiranKJ** [comment]
Hi! asturur,

Thank you for the email and follow up.

I figured out the problem is the way i am loading the fonts. The problem occurs only for the fonts which has space in between. Example Abril Fatface

i am attaching my fiddle here 
http://jsfiddle.net/fmgXt/668/

all the fonts in my googleloader which has a space in between has problems. i corrected it with adding + (Abril+Fatface). But i still have the problem.

I am attaching a json with 3 different fonts. only 2 loads and the one with space does not load 
[data (36).txt](https://github.com/kangax/fabric.js/files/634481/data.36.txt)

**Comment by harshakiranKJ** [comment]
http://jsfiddle.net/fmgXt/669/

The data.txt has 8 fonts in the order its requested in the fontloader.

only the fonts with spaces have problems and even adding + didnt solve

[data.txt](https://github.com/kangax/fabric.js/files/634570/data.txt)

**Comment by harshakiranKJ** [comment]
Hi!
i solved the problem i had. Apparently when i save the json as plain text, it removes the spaces. i modified it and it works perfect now.

Thank you so much for the help.

-Harsha
