### ISSUE TITLE
No renders with text or i-text objects: textDecoration, fill, stroke, backgroundColor

### ISSUE THREAD

**Issue by dpmontero** [kangax/fabric.js#3492]
## Version
1.7.1

## Test Case
http://jsfiddle.net/dpmontero/r0tg9yhg/

## Steps to reproduce
![fabric_bug](https://cloud.githubusercontent.com/assets/16160165/20868040/12e85740-ba52-11e6-9a7b-279358aa465c.gif)

## Expected Behavior
No renders with text or i-text objects: textDecoration, fill, stroke, backgroundColor (in my tests those). With fontStyle (italic, bold...), setOpacity... are ok.

**Comment by asturur** [comment]
http://fabricjs.com/fabric-object-caching

Please read this doc.
It will explain you how to get automatic cache invalidation
