### ISSUE TITLE
targetFindTolerance for horizontal/vertical lines is not working

### ISSUE THREAD

**Issue by Uaargh** [kangax/fabric.js#3494]
## Version
1.7.0

## Test Case
http://jsfiddle.net/droeqgro/

## Steps to reproduce
try to select a line with a simple click near the object.

## Expected Behavior
The ability to select an object should be activated within some borders (in this case 15 px before actually moving over the object), because of the targetFindTolerance.

## Actual Behavior
It's not working with horizontal or vertical lines, it is only possible, to select the lines, when the mouse moves directly over the line.

**Comment by asturur** [comment]
The tolerance is activated only inside the line bounding box.
I would suggest you to use padding properties to make line boxes bigger.
Is the only thing you can do wi straight lines.
