### ISSUE TITLE
Stateful canvas throws "TypeError: destination is undefined"

### ISSUE THREAD

**Issue by manni05** [kangax/fabric.js#3498]
## Version
1.7.0
1.7.1

## Test Case
            function run() {
                    fabric.Object.prototype.objectCaching = false;
                    var canvas = new fabric.Canvas('c', {width: 800, height: 600, stateful: true});
                    var circle = new fabric.Circle({
                        radius: 50,
                        fill: '#eef',
                        left: 100,
                        top: 100
                    });

                    var text = new fabric.Text('hello world', {
                        fontSize: 30,
                        left: 150,
                        top: 100
                    });

                    canvas.add(circle);
                    canvas.add(text);
                }

## Steps to reproduce
Create a stateful canvas, add 2 objects, select them an try to move the selection
## Expected Behavior
The selection moves
## Actual Behavior
Gives "TypeError: destination is undefined"
The exception is thrown in function extend while executing function saveProps.

**Comment by asturur** [comment]
would you give me a fiddle please? so i can investigate better.

**Comment by manni05** [comment]
Try https://jsfiddle.net/b8ctv990/
