### ISSUE TITLE
Problem with loadFromJSON: setControlsVisibility is being ignored and the canvas is not being drawn immediately.

### ISSUE THREAD

**Issue by mtickle** [kangax/fabric.js#3503]
## Version
1.7.0

## Test Case
https://jsfiddle.net/mtickle/7ghe4us7/

## Steps to reproduce

1. Create an object and add it to a canvas
2. Use setControlsVisibility to hide all handles for resizing
3. Export canvas to JSON
4. Import JSON to the canvas

## Expected Behavior
The canvas should hydrate with the objects without handles and display the objects

## Actual Behavior

1. The canvas is blank and must be clicked before the objects are shown on the canvas
2. Object with hidden controls (via setControlsVisibility) are drawn with the handles visible. I don't think that loadFromJSON is respecting the setControlsVisibility settings on the objects.

**Comment by ncou** [comment]
Hi,

Here is a working fiddle.

1. You are missing a canvas.renderAll() after the loadJSON.
2. controlsvisibility field is not exported by default, you need to add the propertie to the propertie list to keep => canvas.toJSON(['_controlsVisibility'])
It's the same thing for the properties "hasControls, hasBorders...etc look in the wiki i think there is an article about this.

Close the ticket if the fiddle is ok for you.

**Comment by mtickle** [comment]
That looks awesome. Thanks for your help!

Mike
