### ISSUE TITLE
Export Object to SVG?

### ISSUE THREAD

**Issue by arminbusatlic** [kangax/fabric.js#3504]
Is it possible to export an object to SVG?

I'm using the canvas.toSVG() call to export but it exports the entire canvas.

I could write the object on a separate canvas then export that canvas, but just curious whether there is a better way to achieve this?

Something like object.toSVG() would be great.

Any suggestions?

**Comment by asturur** [comment]
indeed there is an object.toSVG but need tweaks to return something. i guess i just push in current markup all the informations.

**Comment by arminbusatlic** [comment]
My workaround was to write the object on empty canvas which has the same dimensions as the current object. Then I export that canvas.toSVG and get the object as an SVG file :)

**Comment by asturur** [comment]
yes this works also
