### ISSUE TITLE
IText selection area can not see....

### ISSUE THREAD

**Issue by Jandou6** [kangax/fabric.js#3505]
## Version
1.7.1

## Test Case
https://jsfiddle.net/Jandou/xt3b9n5v/

## Steps to reproduce
1. select some of the text.

2. mouseUp that you will found ,the blue selection area was  disappear

3. but if you click the keyword to edit~, you can see the selection is here beacause can edit ,just the selection was disappear.

4. and i found that in the v1.5.0 , the selection area can see,when the mouseup~

![err6](http://oage4l7r6.bkt.clouddn.com/err6.jpeg)
## Expected Behavior
when the text enter selection the selection area does not disappear when mouseUp
## Actual Behavior
the text selection area disappear when mouseUp, but also can edit..

**Comment by zrispo** [comment]
Having the same issue.

This problem also shows up in 1.7.0.

**Comment by rzb** [comment]
Me too. The cursor also disappear not only on mouse up, but also when using the arrow keys, always after the second hit. After some time the cursor is back again, bu the background color (of selected text) is not.

**Comment by fahadnabbasi** [comment]
Any fix yet for 1.7 version?

**Comment by asturur** [comment]
i shoud find some time today for some little bugs and release 1.7.2

**Comment by fahadnabbasi** [comment]
I am glad @asturur you are amazing :)  👍

**Comment by av01d** [comment]
I made another Fiddle that demonstrates an issue with textbox-size-measuring:
https://jsfiddle.net/av01d/eqsehgwr/1/

This used to work fine with 1.6.1, in 1.7.1 the text gets clipped.
If I use "fabric.Object.prototype.objectCaching = false;", things are well again (in 1.7.1).
Is the only solution to disable object caching? I'd really like to have correct textbox-size-measruring *and* object caching? Too much to ask for?

**Comment by asturur** [comment]
The problem are custom font. i have no way to correctly measure those custom fonts.
I will add some padding even if i no like the idea at the end is better for users.

**Comment by teewuane** [comment]
@av01d Thanks for the tip here. I ran into this today. and disabling objectCaching worked for me. @asturur I really wish I could contribute more! Thanks for working on these issues.

**Comment by rzb** [comment]
I'm still facing the same issue on 1.7.2 and disabling objectCaching doesn't help. When exactly do you guys disable it?

In my use case I provide a couple custom fonts for the user to choose from and save his work. Then when I restore the canvas later with loadFromJSON(), all IText objects have that problem.

**Comment by asturur** [comment]
can you make a fiddle isolating the problem? custom just if needed?
i just packaged 1.7.3 but i would like to fit this different fix if we manage to do it.

**Comment by asturur** [comment]
Is not related to this issue if it happens only after a JSON reload

**Comment by rzb** [comment]
Sure, lemme try here.

**Comment by rzb** [comment]
For some reason I couldn't reproduce it in a fiddle, but I just noticed that in my project all fonts get re-rendered when I interact with the canvas, either by selecting, modifying or adding an object. It looks like the font get shorter in width while the object width itself remains the same.

I disabled all my listeners and the problem persists.

Any clue with the above info? I'll keep playing with it in the fiddle to recreate the problem.

**Comment by asturur** [comment]
Because you do not wait for fonts to be loaded.
You just declare them in css and use them, and this is not possible with canvas, or better, it works bad.
You have to use a font loader or something like that.

**Comment by rzb** [comment]
Oh, makes sense. Something like [google's webfontloader](https://github.com/typekit/webfontloader)?

**Comment by rzb** [comment]
I confirm that my issue was caused by FOUT and using webfontloader solved it. Many thanks.
