### ISSUE TITLE
bringToFront

### ISSUE THREAD

**Issue by techtic-chetan** [kangax/fabric.js#3506]
Hello,

https://jsfiddle.net/techticchetan/p638quv8/3/

I want to select rect object when clicking on Cup image.

Please check below link. I want to do something like this.
http://preview.codecanyon.net/item/fancy-product-designer-woocommercewordpress/full_screen_preview/6318393?_ga=1.254133448.1940140524.1450868289

**Comment by ncou** [comment]
Not really sure what you want to do, i guess you want to select the rect "throw" the image click.
use evented = false on the cup image to allow the selection of the rect object.

https://jsfiddle.net/p638quv8/7/

**Comment by techtic-chetan** [comment]
Thanks, It is working.

**Comment by ncou** [comment]
Good news.
Think to close the ticket if all is right.
