### ISSUE TITLE
Clone function since 1.7

### ISSUE THREAD

**Issue by CSI68** [kangax/fabric.js#3507]
Hi,

Since 1.7 there is an update that I don't understand.

In 1.6 my canvas is clipto a svg shape, all worked like a charm. Now nothing is clipped and I don't know why.

Here is the part of code where I think the modif is needed: 

`custengine.support.moveTo(1);

				// Overhand
				custengine.support.clone(function(clone){

					custengine.overhand=clone;

					custengine.overhand.setFill('transparent').setShadow(0).set({
						id:'ctzOverhand',
						perPixelTargetFind: true,
						selectable:false,
						opacity:0.1,
						clipTo: function(ctx) {
							ctx.save();
							ctx.setTransform(1, 0, 0, 1, 0, 0);
							custengine.support.clone(function(c) {
								c.set({
									scaleX: c.getScaleX()*window.devicePixelRatio,
									scaleY: c.getScaleY()*window.devicePixelRatio,
									top: c.getTop()*window.devicePixelRatio,
									left: c.getLeft()*window.devicePixelRatio,
									fill:'transparent',
									shadow:{}
								});
								c.render(ctx);
								ctx.restore();
							});
						}
					});

					if($('#ctz-button-display-overhand').hasClass('active')){
						custengine.overhand.set({visible:true});
					}else{
						custengine.overhand.set({visible:false});
					}
					
					for (var i = 0; i < custengine.overhand.paths.length; i++) {
						custengine.overhand.paths[i].setFill('transparent').set({
							perPixelTargetFind: true,
							shadow:0,
							stroke:'#000000'
						});
					}`

Thanks for your help

**Comment by CSI68** [comment]
Ok I've found the answer : it's a cache behavior #3454 
I've just add objectCaching: false on the clone object

**Comment by asturur** [comment]
it should clip anyway
can you make a fiddle?

**Comment by CSI68** [comment]
Here is an example (not me but same result) : http://jsfiddle.net/btLfdm0c/
Just disable cache and it works
