### ISSUE TITLE
Cannot select or alter line object after altering object.

### ISSUE THREAD

**Issue by monkeytroy** [kangax/fabric.js#3509]
## Version
1.7.1

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/  :)

## Steps to reproduce
Create a line object.
Alter a point on the line using the set() method. 
Call canvas.renderAll();
Using mouse cannot select the line object so it cannot be moved or altered.
If you use canvas.setActiveObject() the selection box appears but it still cannot be drug or altered.

http://jsfiddle.net/monkeytroy/p04cuy8c/

## Expected Behavior
Objects that are selectable but altered using the set() method are still selectable by mouse click.

## Actual Behavior
Objects that are selectable but then altered using the set() method are not selectable by mouse click.

**Comment by ncou** [comment]
Hi,

You need to call the .setCoords() function to recalculate the controls coordinates, since you made a change in the position.

http://jsfiddle.net/p04cuy8c/1/

PS : Your fiddle is using a Fabric.js v0.9 but i suppose it's an error.
Close the ticket if the fiddle is OK for you.

**Comment by monkeytroy** [comment]
Yay.  That did work thank you sir.
