### ISSUE TITLE
Custom fonts issue

### ISSUE THREAD

**Issue by DangerD256** [kangax/fabric.js#3512]
![image](https://cloud.githubusercontent.com/assets/17032489/21023772/a339a200-bd8a-11e6-8aaf-b6b47b2b504d.png)
fabric.Textbox boundaries cuts custom font text

**Comment by ncou** [comment]
Hi,

I think you need to add a jsfiddle to allow a better analyse.
It's perhaps a missing .setCoords() after the font is loaded.

**Comment by asturur** [comment]
Please read this:
http://fabricjs.com/fabric-object-caching

I updated the page to add this common problem. Maybe for custom fonts we can leave an extra space around the canvas to fit those strange ascenders/descenders.

**Comment by DangerD256** [comment]
Sorry for delay, here is that font:
http://jsfiddle.net/ga0dy5h3/2/

But seems like i made something wrong in this example, default font shows until i start typing text..

![image](https://cloud.githubusercontent.com/assets/17032489/21093509/e1075b36-c05a-11e6-84ac-ebc92d6294eb.png)

**Comment by ncou** [comment]
Hi,

Strange but it seems the name of the family is "Great Vibes" with a space character, and not "GreatVibes".
If i add the space char in the name the font is correctly loaded.

PS: You should use a font loader to reload the canvas once the font is loaded. Like in this exemple http://jsfiddle.net/ga0dy5h3/7/

**Comment by DangerD256** [comment]
But there is the same issue with that, some part of fonts is still cropped.
![image](https://cloud.githubusercontent.com/assets/17032489/21128463/ce07f960-c103-11e6-9c2a-f9d4afa7a752.png)

...
And your fiddle also doesn't solves issue with font preloading, but that's not the topic problem (On my app it somehow works fine). (Close page  and open it again and you will get same default font and on firefox just blank field)

**Comment by ncou** [comment]
You set a width at 250px so it's normal the width is bigger, remove this info and the size is fine

**Comment by DangerD256** [comment]
![image](https://cloud.githubusercontent.com/assets/17032489/21157629/aeb25338-c182-11e6-8b25-973fdcb15eca.png)
Seems like you didn't catch what i mean. It cuts text by height and cuts by width a bit when typing.

**Comment by ncou** [comment]
yeah i didn't understand it, now it's more clear, i think like say asturur perhapts fabricjs need to add extra space around the canvas.

**Comment by asturur** [comment]
because is outside the bounding box, and this because canvas api do not get the dimensioms of that particular font. disable object caching gor that textbox and it will work.
