### ISSUE TITLE
Some bugs when moving/zooming canvas

### ISSUE THREAD

**Issue by DangerD256** [kangax/fabric.js#3513]
Can't select object after moving canvas (viewportTransform) (object can only be selected when clicking on region under object)
To reproduce move canvas using alt+mouse click then try to select object.
http://fabricjs.com/kitchensink

Received a lot of complaints from users regarding this issue... (Previously said them not to use Firefox)
Tested in chrome.

In Firefox even zoom in out doesn't works.

**Comment by asturur** [comment]
that zoom function is just a showing of possibility. is dev duty to implement its own controls for use setZoom and panning. is not fabric lib bug.

**Comment by DangerD256** [comment]
But can help me with that?)

**Comment by DangerD256** [comment]
https://www.youtube.com/watch?v=iGyieJuYKqc

Even don't know whats wrong with that...

**Comment by asturur** [comment]
yes i can help. i will find out what is wrong with firefox and tell you.
some event related stuff.

2016-12-08 21:48 GMT+01:00 DangerD256 <notifications@github.com>:

**Comment by DangerD256** [comment]
The main problem is that I showed in video, it's chrome

**Comment by DangerD256** [comment]
Any solution to Chrome?
