### ISSUE TITLE
Wrong position of a scaled object inside a group

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3520]
Hi,

I think there is a bug in the group positionning.
I add 2 objects on a canvas, one of the object have a scale = 1.2 value.

If i select both objects in a group and I enum the objects to get the top value, i got 0 for both objects.

http://jsfiddle.net/yvo89upg/5/

Ok for the scaled object with a top value inside the group = 0, but the non scaled object should have a top value of 15px.

I want to make a function to align top/left/center/right/bottom all the objects inside a selection. It's when i found this problem.

Thanks for your help

**Comment by asturur** [comment]
the object have 0 top because theyr center is exactly in the center of the group since you added them on the canvas at top 150, they are aligned. Theyr center is the center of group and is 0.
