### ISSUE TITLE
fabricjs with ionic2

### ISSUE THREAD

**Issue by vxrai** [kangax/fabric.js#3523]
Im trying to implement fabricjs with ionic 2. Is there any sample project or resource guide available to help with the implementation? Or anything that describes - how to migrate a fabricjs project in ionic2 framework, will be very helpful.

**Comment by asturur** [comment]
no.
i do not know this framework at all.
Fabric is plain javascript, you should be able to just include it and use it.
How do you include other libs in ionic?

**Comment by vxrai** [comment]
@asturur thanks for your prompt reply.
I am just going through this - http://ionicframework.com/docs/v2/resources/third-party-libs/
and trying to import fabric in ionic.

**Comment by asturur** [comment]
oh is typescript.
You have to find a type descriptor for fabricjs, updated.
I'm sorry is not something we do/support/mantain here.

**Comment by entonbiba** [comment]
@asturur @vxrai  it can be found here, it's working great with ionic 2.
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/fabric 

When I get a change I'll come up with a sample on how to use fabric.js with ionic 2. Just testing out typescript with ionic 2 at the moment.

**Comment by lorkel** [comment]
Hey @entonbiba did you ever end up making this tutorial? Any chance I can get a link? Thanks!
