### ISSUE TITLE
Textbox resize 

### ISSUE THREAD

**Issue by superczan** [kangax/fabric.js#3525]
Hi guys, I encountered a bug in 1.7.1. The issue is with textbox resize in group.

## Steps to reproduce

Add multiple textbox on canvas. Select more than one of those textbox. Trying to resize the group creates problems.

## Expected Behavior
 The group should not resize below the longest word length. 

## Actual Behavior
Textbox when resized in groups are unpredictable. The group resize lets the resize to go beyond the smallest word length and even flip the textbox around. Sometimes when resizing the group, textbox in the group arbitrarily expands into infinite length.

**Comment by asturur** [comment]
is a known defect since textbox are out..i do not like the behaviour at all.

**Comment by superczan** [comment]
Ok. Sorry if this is redundant then. Any chance of fix for this defect soon?

**Comment by kuldipem** [comment]
Problem occurs to me also on kitchensink, 

1. add a `textbox` 
2. add other objects 
3. select multiple objects
4. just move the group
5. click on blank canvas

**Comment by kuldipem** [comment]
I was investing about this issue and found something strange, I hope, it will help you

- before moving in group , the `textbox` 's `scaleX`   value was `0.5`
- after moving in group, the `textbox` 's `scaleX`  value was `0.9999999`

# In developer console #
`var tb=canvas.getActiveObject();`
`tb.getScaleX();`
**0.5**
`var tb=canvas.getActiveObject();`
`tb.getScaleX();`
**0.9999999999999999**

**Comment by asturur** [comment]
ok i finally changed this. Text can scale, just in 2.0 release, i m sorry, not going to backport this in the old 1.x branch
