### ISSUE TITLE
Add Fabric to JsDelivr?

### ISSUE THREAD

**Issue by DiegoRBaquero** [kangax/fabric.js#3530]
Hello,

I'm using Fabric and it's totally awesome! Thanks!

I'm currently using it through CDNJS, however it would be great if it could be added to JsDelivr.

https://www.jsdelivr.com/

Thoughts?

Thanks again!

**Comment by asturur** [comment]
i guess if is free there is no problem.
looking at it.

**Comment by asturur** [comment]
ok requires a bit of reading :) i ll try it anyway.

**Comment by asturur** [comment]
i m not finding time to do it. anyone wants to tell me what to do?

**Comment by DiegoRBaquero** [comment]
It just require adding 2 files inside a folder: 

I did a PR a day ago: https://github.com/jsdelivr/jsdelivr/pull/16564/files

Doc: https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md#web-interface-recommended
