### ISSUE TITLE
Possible feature for free drawing ?

### ISSUE THREAD

**Issue by mbaudry** [kangax/fabric.js#3532]
Hello !

I have a question for a possible feature request. Il would like to remove a free drawing element on hover it. But actually, the area of a drawing element is like this:

![feature](https://cloud.githubusercontent.com/assets/15127641/21221775/06fcfa06-c2bf-11e6-829c-a9f302f025a0.png)

So, we remove an element even if "visually" we are not hover the drawing, but we are over the area he takes. It's a little bit confusing for the user.

Is it possible to imagine that the drawing has an area like this:

![feature-fabric](https://cloud.githubusercontent.com/assets/15127641/21221860/598059e4-c2bf-11e6-9c50-e98ba3cb52a2.png)

It permits to detect the hover only if we are precisely hover the drawing, not hover an area which takes much more space.

Thanks you for your response !! And thank you for this awesome tool !

**Comment by asturur** [comment]
One immediate solution would be to activate the transparency check for the path drawn:

fabricjs.com/docs ==> perPixelTargetFind

**Comment by mbaudry** [comment]
Ok, I will try this. Thank you for your quick response !

**Comment by nisserne** [comment]
I have similar wish - basically to allow selecting objects "below" newer objects. I find it the natural way to select smaller objects placed below a newer larger object.

Try making freehand draw in this [Fiddle](https://jsfiddle.net/wxonypqw/); only parts of polygons outside freehand boundry is selectable.

Thanks you for the fantastic tool!

**Comment by asturur** [comment]
there is something like that... try alt click?

**Comment by nisserne** [comment]
Thanks asturur,

But I cannot find any "secret" key combo that changes that polygons can only be selected if clicking outside freehand boundry...!? 

![image](https://user-images.githubusercontent.com/24431571/33035605-0da542e0-ce2c-11e7-9116-cd1900f524a4.png)

**Comment by asturur** [comment]
I know fabricjs is not good with docs and so has some secret feature.
But the feature to set perPixelTargetFind to true on the brush i m sure it does not exist.

https://jsfiddle.net/wxonypqw/2/

you can set that to true on the path just created using the `path:created` event that fires on the end of freeDrawing.

**Comment by nisserne** [comment]
asturur, 

You are a hero! Being new to fabric I did not see that distinction between tool and final path when using the the freehand brush tool.
This does it. Your updated fiddle illustrates it beautifully.

Thanks a lot, asturur.
