### ISSUE TITLE
An 1px gap to the top/left

### ISSUE THREAD

**Issue by wushan** [kangax/fabric.js#3533]
## Version
1.7.1

## Test Case
http://codepen.io/wushan/pen/zoMgaP

## Steps to reproduce
Set an object to left:0, top:0 and another one to -1, -1

## Actual Behavior
As you can see, the blue rect shows 1px border since -1,-1 is the one fulfilled the canvas area.

![unspecified-1](https://cloud.githubusercontent.com/assets/3633628/21255205/5b6ce056-c3a5-11e6-992a-da53b1589d8d.png)

**Comment by ncou** [comment]
Hi,

You need to add "strokeWidth: 0" to the red rect (from my comprehension, there is by default a 1px for the objects for SVG standard, except for image object) :

http://codepen.io/anon/pen/WoLxmW

**Comment by asturur** [comment]
exactly, thanks @ncou.
That gap is the transparent border.
We have 1px border for some reasons.
In images we removed it because the loosing in crispness was too much.
