### ISSUE TITLE
SVG color fill (change color) not working

### ISSUE THREAD

**Issue by kpomservices** [kangax/fabric.js#3534]
SVG color fill / change color is not working with latest fabric js library
This issue exists in 'kitchensink' demo also.
http://fabricjs.com/kitchensink

**Comment by kpomservices** [comment]
Ok i will create a jsfiddle example for this.

**Comment by kpomservices** [comment]
I can see this color change / color fill not working for SVG elements in 'kitchensink' demo, that is the reason i did not create a jsfiddle.
http://fabricjs.com/kitchensink 

I will create a jsfiddle for this.

**Comment by ncou** [comment]
Hi,

It's missing a propertie for the cache (statefullCache).

Here is a fiddle based on the kitchensink demo : 

http://jsfiddle.net/526wC/93/

**Comment by asturur** [comment]
http://jsfiddle.net/526wC/94/

enabling statefullCache is not the best choice.
There is no meaning in my opinion to set fill of a complex object like an svg.
If all the sub objects are the same color, fabric will use the shortcut to color all the subobjects of the fill of the container ( the svg ).

When using the proper setter ```.set({fill: 'xxxxxx'})``` or ```.setFill(xxxx)``` fabric will take care of cache invalidation automatically.

**Comment by ncou** [comment]
Ok, in this case, i suppose the javascript for the kitchensink demo should update the "setActiveStyle()" function from :

`
/*
			    if (object.paths) {
			  		for (var i = 0; i < object.paths.length; i++) {
				      object.paths[i][styleName] = value;
				    }
			    }

			    object[styleName] = value;
 */
`
to
`
			   
			    var option = { };
			    option[styleName] = value;
			    object.set(option);
`

**Comment by asturur** [comment]
yes i plan to give a check to kitchensink so that it has more options exposed and some debug info to understand what is going on. i guess i ll do today.

**Comment by ncou** [comment]
Hi,

Do you made the changes in the kitchen sink demo ? i made a quick check and the fill color seems still KO on the update.

**Comment by asturur** [comment]
i did, they are not pushed. kitchensink looks like this now:

![image](https://cloud.githubusercontent.com/assets/1194048/21628206/f23bdab0-d21d-11e6-9d32-0332d4aa1ba0.png)

![image](https://cloud.githubusercontent.com/assets/1194048/21628215/fd3323e2-d21d-11e6-9245-8f2f60bc31e2.png)

trying to expose more canvas and object properties so that people get ideas or trying bugs is easier.
I have some other fix to do to 1.7.3 version and then i should push it.

Be aware that pathgroup not always take fill and stroke changes. It depends if all the shapes are already same color. This feature is silly and is gonna disappear on 2.0 in favor of some ```setOnObjects('fill', 'red')```  still not made my mind over it.

**Comment by ncou** [comment]
Good news.
It's a good think the futur new demo expose more properties (like cache and controls customisation).

Ps : do you have a date in mind for the future 2.0 version ?

Have a good night.

**Comment by asturur** [comment]
a date not. i guess 1.7.3 is last of  1.x branch and then i ll work on 2.

2.x is mainly about making things more consostent and removal of old unused things that will create backward compatibility break.

So is mainly about sitting down and make choices, and check that nothing is broken and fix demos afterward.

Maybe i should do a poll for some changes.

**Comment by ncou** [comment]
Good news :)
A poll is an interesting idear.

Keep up the good work.

**Comment by SarmadFayyaz** [comment]
> i did, they are not pushed. kitchensink looks like this now:
> 
> ![image](https://cloud.githubusercontent.com/assets/1194048/21628206/f23bdab0-d21d-11e6-9d32-0332d4aa1ba0.png)
> 
> ![image](https://cloud.githubusercontent.com/assets/1194048/21628255/601e4540-d21e-11e6-981c-d3770abf6fb4.png)
> 
> trying to expose more canvas and object properties so that people get ideas or trying bugs is easier. I have some other fix to do to 1.7.3 version and then i should push it.
> 
> Be aware that pathgroup not always take fill and stroke changes. It depends if all the shapes are already same color. This feature is silly and is gonna disappear on 2.0 in favor of some `setOnObjects('fill', 'red')` still not made my mind over it.



I cant Find this Demo
i am still viewing that old demo where you can't change fill/stroke/background color
please Help
