### ISSUE TITLE
[NFR] Provide some kind of link between source of fabric.Image.fromURL() and "oImg" argument of callback

### ISSUE THREAD

**Issue by temuri416** [kangax/fabric.js#3535]
Hi,

The code:

http://codepen.io/tmrczk/pen/WoLMwo

**Given**:

- Two images are placed on canvas via `fabric.Image.fromURL()`
- Image definitions are defined in variable `objects` 
- First image is extremely large, takes several seconds to load
- Second image is tiny

I'm looping over the definition, adding images one by one. Definition contains required image dimensions and positioning on canvas.

**The problem**:
Since first image takes much longer to load, second image ends up in the callback first. It is correctly scaled and positioned. When larger image finally loads, it is formatted with **incorrect** value of `opt` - which was set by the last iteration.

**Request**:
Would it be possible to add a second argument to the function as follows:

`fabric.Image.fromURL(src, callback, userData)`

and then pass `userData` to the properties of `oImg`, so I could do this:

```js
fabric.Image.fromURL(src, function(oImg) {
    oImg.set(oImg.userData); // Sets width=123, height=456
    canvas.add(oImg);
}, {
    width: 123,
    height: 456
});
```

Also, it would be great if `fabric.loadSVGFromString()` had a similar user data argument - I'm facing exactly the same problem there.

Thanks a lot.

**Comment by asturur** [comment]
i guess in this case using a forEach loop is enough. The additional create context will help you mantaining the binding between options and image

```
var canvas  = new fabric.Canvas('c', {
  backgroundColor: "#eeeeee",
  width: 900,
  height: 1162
});

var d = new Date();
var n = d.getTime();

var objects = [
  {
    type: 'image',
    left: 150,
    top: 50,
    width: 300,
    height: 200,
    angle: 30,
    src: 'http://static2.businessinsider.com/image/5654150584307663008b4ed8/this-tech-recruiter-owns-the-most-hipster-cat-on-instagram.jpg'
  },
  {
    type: 'image',
    left: 250,
    top: 250,
    width: 150,
    height: 40,
    angle: 1,
    src: 'https://www.google.ca/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png'
  }
];

objects.forEach(o => {
  var src = o.src + '?rand=' + n;
  fabric.Image.fromURL(src, function(oImg) {
    oImg.set(o);
    canvas.add(oImg);
  }); 
});
```

i would not add features to overcome things that can be done with normal js tools.
let me know what you think.

**Comment by temuri416** [comment]
ok, thank you.

I'd be great if you added this example to wiki section.
