### ISSUE TITLE
the return of group object toDataURL ....

### ISSUE THREAD

**Issue by Jandou6** [kangax/fabric.js#3536]
## Version
1.7.1,
1.5.0

## Test Case
http://jsfiddle.net/Jandou/2ogkbL7p/

## Steps to reproduce
1.run the code in v1.7.1
![e1](http://oage4l7r6.bkt.clouddn.com/e7.jpeg)
![e2](http://oage4l7r6.bkt.clouddn.com/e8.jpeg)

2.and v1.5.0 
![e3](http://oage4l7r6.bkt.clouddn.com/11.jpeg)
![e4](http://oage4l7r6.bkt.clouddn.com/e9.jpeg)

## Expected Behavior
the dataURL has content
## Actual Behavior
but in different version the same code has the different dataURL

**Comment by asturur** [comment]
http://jsfiddle.net/2ogkbL7p/1/

is just wrong order for creating an active group programmatically.
First add object to canvas, then group them in the activegroup, then export to dataurl.
