### ISSUE TITLE
Change behaviour of setSelection style when there is no selection.

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3541]
Hi,

There is a strange behavior with the itext component, if i edit the text, i put my cursor in the middle of the string, i don't select a character, but i change the fill color to "yellow" (because i want to enter some new text with another color).

In this case, when i select the fill color, to next letter (near the right part of the cursor) is colored to yellow and i can't add character, the letters are not added, i need to click after the colored char to be able to press again some keys.

![image](https://cloud.githubusercontent.com/assets/16743322/21287476/b3891008-c46c-11e6-92a9-122724189fcb.png)

no Fiddle, we can reproduc the bug on the official demo :
http://fabricjs.com/kitchensink

Not really sure it's enough clear with my poor english, let me know if i need to explain myself again.

**Comment by asturur** [comment]
Kitchensink has its own function for adding colors, they may no be perfect. To issue a bug would be better to have a clear fiddle.

**Comment by ncou** [comment]
Here is the fiddle :

http://jsfiddle.net/zjuoc3r9/101/

It looks like a "style" problem.

**Comment by asturur** [comment]
mmm good question.
The code is clear: if there is no selection, set the selection of next char. Looks intentional.
Behaviour is not expect as you noticed. I would expect to set NOTHING and change the color of next inserted char.
This has some implication and needs to be checked.
Good point but i m not gonna rush to change a consolidated behaviour for now.

**Comment by ncou** [comment]
good news if the behavior will be changed a day.
Keep up the good work. Fabric.js is an amazing lib.

**Comment by Tennyleaz** [comment]
Sorry for commenting on old issue, but I have similar questions regarding to this issue.

From the kitchensink demo: http://fabricjs.com/kitchensink
If I place the cursor between `b` and `a`, then click the "object" control panel to change style, the next character I type on IText does not change.

![image1](https://user-images.githubusercontent.com/7089271/156684287-bae50ba5-d80b-4a72-92a6-390c6aa0b23f.png)

Seems `setSelectionStyles()` does not affect the next input character?

![Image2](https://user-images.githubusercontent.com/7089271/156684936-c0b1bcb2-9249-4e15-8c3e-99210f1f0986.png)
