### ISSUE TITLE
[DOC] typo error in the caching doc

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3542]
Hi,

Not really a bug, but a little error in the documentation.

http://fabricjs.com/fabric-object-caching

1)
`objectCaching:            objectCaching`
It should be "objectCaching:true"

2)
And for the "noScaleCache" propertie it's indicated `default to **false**` but the default value is **true** except for the textbox object.

Is my statement correct ?

**Comment by asturur** [comment]
For point 1. is wrote like this because for node we set caching as false by default.
For 2. corrected.
