### ISSUE TITLE
Feature Request - pattern object add a "Fill" property ?

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3543]
Hi,

Do you think it's possible to add a "fill" property to the "pattern" object, this value could be used as the canvas background color when you choose a pattern.

Actually if you set a transparent pattern on the canvas using the "setBackgroundColor()" you can't specify a background color :(

What do you think of this idear ? Or perhaps you have a workaround for this situation ?

**Comment by asturur** [comment]
The workaround would be having a rect set as a backgroundImage, filled with the pattern you want. BackgroundColor would be still visible under.
Fabric has a fill operation and a object render operation as background, i think is enought. I would not add more complexity to this.
Fill can be either a pattern , a gradient a color, object can be an image, a rect, or a group with more things inside. So you have all the freedom you want.

**Comment by ncou** [comment]
I was not aware you could use a rect object as backgroundimage, i was thinking it's limited to image object.
The rect solution is perfect for me. i made a quick fiddle and it cover my needs. thank you for your help.

**Comment by ncou** [comment]
Hum, in fact i spoke to quickly.
It seems the transparent pattern is lost :

http://jsfiddle.net/YH9yD/290/

I set a "red" rect, but i lose the fill color when i apply the pattern. Do i need to open a bug ticket ? or i am misusing the lib ?

**Comment by asturur** [comment]
can't you set canvas.backgroundColor and backgroundObject?

**Comment by ncou** [comment]
Here is the working fiddle :
http://jsfiddle.net/YH9yD/291/

by the way it's strange to use the function "setBackgroundImage()" to use a rect object as background.
You used in your message "backgroundObject" is that a futur alias or juste a typo mispelling ?

**Comment by asturur** [comment]
in fabric 2.0 they are renamed in backgroundfill and backgroundObject
