### ISSUE TITLE
includeDefaultValues doesn't work on path subobject of path-group

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3544]
Hi,

It seems there is still some default attribute with v1.7.1 of fabric.js.

It seems it's the sub-objects "path" that are not filtered :
http://codepen.io/anon/pen/pNqqqE?editors=1111

Am i missing something ? Thank you for your help.

**Comment by asturur** [comment]
should act like group.

**Comment by asturur** [comment]
code looks right. did you built latest master? the fix will be in the 1.7.2 version

**Comment by ncou** [comment]
oups I made you loose your time, i was looking in the changelog and thinking the 1.7.2 was released. I made my tests on the 1.7.1.

sorry.

**Comment by asturur** [comment]
anyway i spotted an issue and fixed it. 1.7.2 is out
