### ISSUE TITLE
Pattern as Image background isn't loaded from JSON.

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3548]
Hi,

I can add as backgroundImage a pattern, but if i export it to json and load it again, i lost the pattern.

Here is a fiddle :
http://jsfiddle.net/YH9yD/292/

I try to load in the second canvas, the serialized json from the first canvas.
But the pattern isn't loaded.

**Comment by asturur** [comment]
yes there was an error, i submitted a fix.
There is a problem anyway, fabric does not load the patter syncronously, so the rects get created and cached without the pattern.
After tha canvas is loaded you have to manually set canvas.backgroundImage.dirty = true  to force a re render.

**Comment by asturur** [comment]
taking care of this asyncronos problem, is an open issue since 2013, time to close it.

**Comment by ncou** [comment]
so after the asunchronos problem is resolved, should I still use the property "canvas.backgroundImage.dirty = true" ? or this will be useless ?

**Comment by asturur** [comment]
no will be rendered first time correctly
