### ISSUE TITLE
Possible to override bounding box selection area in fabricjs - controls option

### ISSUE THREAD

**Issue by Vivek-KT** [kangax/fabric.js#3551]
Hi to all,

Here, we are working in fabric.js with creating design tool.We have create custom selection area for canvas object in fabric.js. I read source code in fabric.js, it generates square box for bounding box, but I want change to my custom Selection area appearance.Can please advise me?

HERE SOME DANCING DOTTED SELECTION AREA.

![dancing_dots](https://cloud.githubusercontent.com/assets/4013115/21304988/ed15e0ac-c5ee-11e6-8562-d5dd3bb5d58d.png)

We want custom selection area appearance.

![default_screen](https://cloud.githubusercontent.com/assets/4013115/21305001/fd6ab75c-c5ee-11e6-8790-969e8761cd54.png)
We have tried this code ` context.setLineDash()` for selection area.

```
if (fabric.StaticCanvas.supports('setLineDash') === true) {
    ctx.setLineDash([4, 4]);
}
```
Refer code from [Github](https://github.com/kangax/fabric.js/issues/2700).But won`t working fine for my working area.
How can we create custom selection area in fabric.js?

Thanks in advance

VIVEK KT

**Comment by asturur** [comment]
http://fabricjs.com/fabric-changelog

please refer to changes in version 1.6.2 there are the properties needed to change the selection area.

Also http://fabricjs.com/docs

**Comment by asturur** [comment]
borderDashArray is a property, you set an array to it `[2, 4]` for example.
There is no built in code to animate the selection.
I would suggest of not trying to animate it with fabricjs directly since animation is per object.
You could try to create a top level function with a setInterval that will check if there is a activeObject on canvas. if yes swap the strokeDashArray from `[2, 0, 2, 0]` to `[0, 2, 0, 2]` and see if it works.
If more details are needed please open a stackoverflow question, nothing that we can support here.

**Comment by Vivek-KT** [comment]
HI @asturur .. Thank you for guide me. i am trying based on your idea and also i have create ["Stackoverflow" Question.](http://stackoverflow.com/questions/41218084/possible-to-override-bounding-box-selection-area-in-fabricjs-controls-option). Kindly review it and let me know your feedback.

Thanks 
VIVEK KT

**Comment by cherishh** [comment]
Hi, I have similar needs to this, but I guess it's a little bit harder - I want to customize selection area. I'm developing a drawing tool that one can draw polygon with mouse click, and also modify it. I've successfully achieved this, but my problem is no matter what shape the polygon is, selection area is always the bounding box. So sometimes I click on a blank area, I accidentally selected a polygon. I want to select a polygon only when I actually clicked **on** one.

How can I achieve this? Any help would be appreciated.

**Comment by cherishh** [comment]
I found the solution. https://stackoverflow.com/questions/29203355/how-to-select-the-objects-by-only-clicking-the-actual-contents-by-fabric-js?rq=1

**Comment by asturur** [comment]
you can use the transparency selection for that, please give a look at the docs, should be explained.

`perPixelTargetFind` is called

**Comment by cherishh** [comment]
@asturur Thanks! This is exactly what I needed.
