### ISSUE TITLE
Set Opacity On Object As A Whole?

### ISSUE THREAD

**Issue by arminbusatlic** [kangax/fabric.js#3552]
Is there a way to set the opacity of a fabric text object on entire object instead of each component.

Right now, when I set opacity to 50% and I have a black stroke on white fill, the text will look different than when I generate the PNG file and set its opacity to 50%.

Have a look at the screenshot below. The text at the top is a generated PNG using opacity = 1, then setting opacity on the entire PNG to 50% using CSS.

The text below is the generated fabric text object with opacity: 50%. Since fabric sets the fill at 50% as well, the stroke behind the fill starts to come out.

Is there any way to set the opacity to 50% on fabric but keep the fill at 100%?

![untitled-2](https://cloud.githubusercontent.com/assets/2653785/21327523/94998866-c5fd-11e6-95c0-018e7976a6aa.png)

**Comment by asturur** [comment]
the stroke is over the fill, not behind.
apart from this, now that there is object caching is  half possible  with some heavy custom coding that i cannot provide for a series of reason.
you have to write your own render method.

**Comment by arminbusatlic** [comment]
I understand. My stroke is behind the fill because I overwrote the fabric render text function to the following:

// Override to draw stroke before fill so that stroke appears outside of text
    fabric.Text.prototype._renderText = function( ctx ) {
        this._renderTextStroke(ctx);
        this._setShadow(ctx);
        this._renderTextFill(ctx);
    };

However, even though the text stroke is behind fill, when the fill becomes opaque, the text stroke is more and more visible making it show differently than what I'm trying to achieve.

**Comment by arminbusatlic** [comment]
Is there no way to apply opacity on the object as a whole?

**Comment by asturur** [comment]
no built in. stroke and fill operation are distinct and get applied one over the othere. if you load some strange font like 'pacifico' from google situation is even worse.

**Comment by asturur** [comment]
You should open a stackoverflow question.
Not being a bug and being a non possible feature request ( the code to do this is not few lines and is not going to be part of the core library ) this issue will be closed, stackoverflow will assure a better visibility to your question and maybe someone eager for rep will try to solve your idea.

**Comment by arminbusatlic** [comment]
Ok, thanks for the info. I still appreciate your time and explanation on this. Have a great day! :)
