### ISSUE TITLE
how to use on android or ios

### ISSUE THREAD

**Issue by yanzhou-share** [kangax/fabric.js#3553]
Hi, @kangax 

how to use it on android or ios, because now i want to web and client Synchronized

thanks 👍

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
