### ISSUE TITLE
Textbox cursor keeps drifting away for non-standard fonts

### ISSUE THREAD

**Issue by coolfeature** [kangax/fabric.js#3555]
## Version
1.7.2

## Steps to reproduce
Load a custom font and start typing in a Textbox.

## Expected Behavior
The blinking cursor is accurately positioned at the end of typed text. Single words within text are accurately highlighted on double click.

## Actual Behavior
![abel](https://cloud.githubusercontent.com/assets/6413939/21346008/69109ff2-c69a-11e6-8068-2fe4a0bd5882.png)
The cursor position and text selection works fine for Times New Roman:
![times](https://cloud.githubusercontent.com/assets/6413939/21346049/8e27bb54-c69a-11e6-9b72-b99ff7d10747.png)

**Comment by asturur** [comment]
please add a fiddle to show how you load fonts. probably you are not waiting for the fonts to load

**Comment by coolfeature** [comment]
Yeap, you are right. Closing.
