### ISSUE TITLE
Inconsistent behaviour rendering changed object properties (_dimensionAffectingProps)

### ISSUE THREAD

**Issue by mlev** [kangax/fabric.js#3559]
## Version
1.7.2

## Steps to reproduce
Changing the ```styles``` property of a textfield is not automatically reflected when calling renderAll(). This may be intentional but seems inconsistent with changes to other properties such as ```fontWeight``` and ```charSpacing``` that do get picked up automatically.

Steps:
- Change styles property of Textbox directly (i.e.``` textbox.styles = { new styles }```)
- Call ```canvas.renderAll()```

## Expected Behavior
New styles would be reflected on canvas.

## Actual Behavior
New styles are not rendered until cache manually invalidated.

This is because the ```_dimensionAffectingProps``` property doesn't contain "styles" - but it does contain related items like ```fontWeight``` that can also be set within styles.

## Workaround
There are a couple of workarounds - either by setting the styles property by ```Textbox.set()``` method or by manually invalidating the cache (```textbox.dirty = true```).

**Comment by asturur** [comment]
how are you changing style?

**Comment by mlev** [comment]
When we change specific text styles we use ```setSelectionStyles()``` but sometimes we change or restore all of the styles for the textbox. For this we were updating the ```styles``` property directly.

Now we've changed our code to use the ```set()``` method, which does detect the change and set dirty=true. It's just not obvious given changes to other properties (such as fontWeight) are updated automatically on render.

**Comment by asturur** [comment]
I know is not obvious, that is why i wrote this with 1.7.0 release:
http://fabricjs.com/fabric-object-caching

glad you solved.
