### ISSUE TITLE
Convert object shadows to separate objects

### ISSUE THREAD

**Issue by cincplug** [kangax/fabric.js#3562]
Would it be possible to add a feature allowing us to convert shadow added to object with `object.setShadow()` to a new object, that would preserve shadow's appearance but otherwise become a separate entity like it's parent object?

I actually thought that it is already possible because shapes have their `getShadow()` method, but apparently it is there only to extract those values as parameters.

So, can you think of a way to implement something like:

`Object.getShadow().convertToObject();`

Use of this could be, for example, to add more realistic 3d appearance and animation to objects with shadows, because beside their offset and blur we could manipulate other properties like scale, angle, skew, or opacity.

Why particularly I ask this is because I have a complex shape consisted of several fabric shape objects overlapping each other, and I need to put the their shadows beneath all of shapes, rather than to have shapes casting shadow on each other like now. So, what particularly I need to manipulate is shadows' `z-index`.

However, we can clone our shapes and style them as shadows instead, the only thing is that original shapes themselves don't have `blur` property, it exists only as an image filter. So, adding such functionality to some future release of this beautiful library could be another way to achieve this.

**Comment by asturur** [comment]
This is not possible. There are some caveats and some workarounds.

We are using canvas shadow. Those shadows are the direct product of a drawing operation on the canvas. There is no shadow alone without a shape. A transparent shape do not cast any shadow.

For the complex object you should check if object caching helps you.
A complex group of shapes in fabric 1.7.2 should be draw first time over a secondary canvas where then lives as an image. That image is then rendered as a unique object and it will cast one shadow under it.

What version of fabric are you on?

**Comment by cincplug** [comment]
Thanks for the reply, currently I use 1.6.5, but I'll take care to update and try to render those shapes on secondary canvas. That would probably be wise in terms of performance too.

**Comment by asturur** [comment]
that is the main reason why it has been introduced.
please have a look at
http://fabricjs.com/fabric-object-caching
if you did not already

**Comment by asturur** [comment]
please close the issue if nothing else come out.

**Comment by cincplug** [comment]
Ok thanks a lot, and good luck with future releases!
