### ISSUE TITLE
Unable to edit text

### ISSUE THREAD

**Issue by prince685** [kangax/fabric.js#3566]
Hello ,

I am using modal box. When i added text on canvas then i was unable to edit text and cursor was still showing. No idea what is going on. I have added text  using ITEXT class. Any one can assist me a better solution

Thanks
Prince

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
