### ISSUE TITLE
Appling shadow to a cliped object

### ISSUE THREAD

**Issue by alexandrebarreiros** [kangax/fabric.js#3569]
## Version
1.7.2

## Test Case
http://jsfiddle.net/no737jxd/2/

## Steps to reproduce
Apply a shadow to an object with clipPath

## Expected Behavior
The shadow should be applied to the final form generated by the clipped area and  the shadow itself should not be clipped by the path clip. 
## Actual Behavior
The shadow was clipped

**Comment by asturur** [comment]
Yes this has been already discussed. Sadly clipTo cut everything.
With object caching it should be possible. Let me check if is a quick fix.

**Comment by alexandrebarreiros** [comment]
Thank you very much, this is an essential feature to the application that we are building. Thanks in advance

**Comment by alexandrebarreiros** [comment]
Hi there asturur, did you have the time to check if it's possible?

**Comment by asturur** [comment]
i checked and is possible.but the clipTo function is a complete freedom of clipping and i cannot transfer it to cache because the dev that wrote its its own clipTo could have made it  relative to canvas and not relative to object.
There is in plan to add a clipPath property for obkects with which you can define a series of fabricObjects that will clip the object. Those will be relative to object center and will not clip shadow. those will work with composition more than clipping and will make possible combine more shapes togheter in a way that is easier to understand the final interaction.

i guess you have to disable the caching for now and wait that function to be out ( there is some work already done ).

if you want to patch the code by yourself to have a working prototype for you, as soon as i m back to a full keyboard i ll leave you some suggestions.

**Comment by alexandrebarreiros** [comment]
Hi asturur,
Thank you for the answer, when you can, please give me more info about it, we are doing a big application with image manipulation and i will me need to complete this task as soon as possible. Thanks in advance.

**Comment by asturur** [comment]
I did not have time to test it for real but, consider this code from object.class.js of latest fabric

```javascript

render: function(ctx, noTransform) {
      // do not render if width/height are zeros or object is not visible
      if ((this.width === 0 && this.height === 0) || !this.visible) {
        return;
      }
      ctx.save();
      //setup fill rule for current object
      this._setupCompositeOperation(ctx);
      this.drawSelectionBackground(ctx);
      if (!noTransform) {
        this.transform(ctx);
      }
      this._setOpacity(ctx);
      this._setShadow(ctx);
      if (this.transformMatrix) {
        ctx.transform.apply(ctx, this.transformMatrix);
      }
      this.clipTo && fabric.util.clipContext(this, ctx);
      if (this.objectCaching && !this.group) {
        if (this.isCacheDirty(noTransform)) {
          this.statefullCache && this.saveState({ propertySet: 'cacheProperties' });
          this.drawObject(this._cacheContext, noTransform);
          this.dirty = false;
        }
        this.drawCacheOnCanvas(ctx);
      }
      else {
        this.drawObject(ctx, noTransform);
        if (noTransform && this.objectCaching && this.statefullCache) {
          this.saveState({ propertySet: 'cacheProperties' });
        }
      }
      this.clipTo && ctx.restore();
      ctx.restore();
    },

    /**
     * Execute the drawing operation for an object on a specified context
     * @param {CanvasRenderingContext2D} ctx Context to render on
     * @param {Boolean} [noTransform] When true, context is not transformed
     */
    drawObject: function(ctx, noTransform) {
      this._renderBackground(ctx);
      this._setStrokeStyles(ctx);
      this._setFillStyles(ctx);
      this._render(ctx, noTransform);
    },
```

if you make those changes:

```diff
render: function(ctx, noTransform) {
      // do not render if width/height are zeros or object is not visible
      if ((this.width === 0 && this.height === 0) || !this.visible) {
        return;
      }
      ctx.save();
      //setup fill rule for current object
      this._setupCompositeOperation(ctx);
      this.drawSelectionBackground(ctx);
      if (!noTransform) {
        this.transform(ctx);
      }
      this._setOpacity(ctx);
      this._setShadow(ctx);
      if (this.transformMatrix) {
        ctx.transform.apply(ctx, this.transformMatrix);
      }
-      this.clipTo && fabric.util.clipContext(this, ctx);
      if (this.objectCaching && !this.group) {
        if (this.isCacheDirty(noTransform)) {
          this.statefullCache && this.saveState({ propertySet: 'cacheProperties' });
          this.drawObject(this._cacheContext, noTransform);
          this.dirty = false;
        }
        this.drawCacheOnCanvas(ctx);
      }
      else {
        this.drawObject(ctx, noTransform);
        if (noTransform && this.objectCaching && this.statefullCache) {
          this.saveState({ propertySet: 'cacheProperties' });
        }
      }
-      this.clipTo && ctx.restore();
      ctx.restore();
    },

    /**
     * Execute the drawing operation for an object on a specified context
     * @param {CanvasRenderingContext2D} ctx Context to render on
     * @param {Boolean} [noTransform] When true, context is not transformed
     */
    drawObject: function(ctx, noTransform) {
+      this.clipTo && fabric.util.clipContext(this, ctx);
      this._renderBackground(ctx);
      this._setStrokeStyles(ctx);
      this._setFillStyles(ctx);
      this._render(ctx, noTransform);
+      this.clipTo && ctx.restore();
    },
```

and you enable the caching for the images `fabric.Image.prototype.objectCaching = true;` you could obtain the desired effect.

**Comment by asturur** [comment]
Let me know if you need more details or ideas. I m closing the issue since i already stated i cannot change the behaviour of the library without breaking current apps.

**Comment by alexandrebarreiros** [comment]
Hi asturur,
Thank you very much for your effort in helping me, the code that you sent work perfectly. Thanks again

**Comment by alexandrebarreiros** [comment]
Hi asturur,
Just a question related with the solution that you sent. I had my stroke that was being draw half inside the container and the other half out of it, but with the new code it only draws it clipped, i tried to change the function that render the border without success, do you have any clue? Thanks in advance
