### ISSUE TITLE
multiplier with toDataURL is not working

### ISSUE THREAD

**Issue by amitgaur208** [kangax/fabric.js#3576]
Hey @kangax ,
I have tried multiplier when exporting data but objects are missing from canvas.
Sometimes its working on multiplier=2 but not more than 2
var data = canvas.toDataURL({ format: 'png',multiplier: 3});
Please help. 

## Version
1.7.2

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by asturur** [comment]
please try to understand that without a failing, clear, good written fiddle we cannot do nothing. Not even schedule to time to look at it.
