### ISSUE TITLE
FabricJS loadFromJSON() - is there any way to ignore images that their sources can not be found?

### ISSUE THREAD

**Issue by human-a** [kangax/fabric.js#3578]
## Version
1.6.7

## Test Case
https://jsfiddle.net/human_a/rs8cbxv8/

## Steps to reproduce
My canvas project is saved in the database as a JSON object. Some of these projects have images being added to them from a user uploaded library of images. The problem is that if one of the images in the library is deleted, the entire project would not be loaded, so I am looking for a way to load the rest of the objects into the canvas and ignore the ones that can not be loaded.

After trying to add this issue to a jsfiddle I realized that the loading of the canvas fails only and only if a filter is set on the image.

I make my images ready to have filters applied to them while the images are being added to the canvas using the following method:

```javascript
var filter = new fabric.Image.filters.Brightness({
         brightness: null
})
newImage.filters.push(filter);
newImage.applyFilters(canvas.renderAll.bind(canvas))
```

In [the jsfiddle](https://jsfiddle.net/human_a/pg3scx0c/) inside the JSON object try changing ```"src":"https://fake.fakedoman.fake/fake.jpg"``` to a valid image URL, click on load button and it will start working correctly. Also if you remove ```"filters":[{"brightness":0,"type":"Brightness"}]``` array from the JSON object the loading will work again and just ignores the image with a fake source.

**Comment by bodeva** [comment]
I perform this server-side action in PHP before injecting the JSON stream into the canvas.

public static function sanitize($json){
		
		$i = 0;
		$j = 0;
		
		foreach($json->pages as $pages){
			foreach($pages->value->objects as $object){
				if($object->type === 'image'){
					$file_headers = @get_headers($object->src);
					if($file_headers[0] === 'HTTP/1.0 404 Not Found'){
					   unset($json->pages[$i]->value->objects[$j]);
					}
				}
				$j++;
			}
			$i++;
		}
		
		return $json;
		
	}

**Comment by asturur** [comment]
i think this error should be handled at least in the reviver function passing the error so that you can decide what to do.
We are managing the error in fabric that is custom logged, so we should be able to fix this.

**Comment by asturur** [comment]
Can you recreate the fiddle? there is the fiddle from another issue but not the original one.

**Comment by asturur** [comment]
I made a fiddle by myself and the canvas loads without problem, just the wrong object is missing. Are you sure there is not some other problem? I agree that the reviver is not called in case of error so you cannot remove the empty object from canvas.

**Comment by human-a** [comment]
I edited the question with the [correct link](https://jsfiddle.net/human_a/rs8cbxv8/)

I tested it with different images, in different situations, if you apply filters (like brightness e.g.) it would not load any other objects into the canvas at all.


"In the jsfiddle inside the JSON object try changing ```"src":"https://fake.fakedoman.fake/fake.jpg"``` to a valid image URL, click on load button and it will start working correctly. Also if you remove ```"filters":[{"brightness":0,"type":"Brightness"}]``` array from the JSON object the loading will work again and just ignores the image with a fake source."

**Comment by asturur** [comment]
ok so there is an unmanaged error inside the loadFromObject in case of filters

**Comment by asturur** [comment]
https://github.com/kangax/fabric.js/pull/3586/files those changes should solve this defect

**Comment by human-a** [comment]
That is great. Thanks!

**Comment by human-a** [comment]
I just gave it a try, If I do the changes in the first file on [the link you sent me](https://github.com/kangax/fabric.js/pull/3586/files) Everything works as expected, however by doing the second change:

```javascript
enlivenedObjects[index] = obj;
reviver && reviver(o, enlivenedObjects[index], error);
```

It stops loading all the other objects and it would not set the background color, size etc. on the canvas giving the error of "can not run set of null"

Just wanted to inform you before you publish the changes in the new version.

**Comment by asturur** [comment]
i should not trust unit tests alone. all give a better look.

**Comment by asturur** [comment]
ok i avoid to set the null object in the returned array, as it was before. Still calling the reviver with error so that a dev can figure out wich object errored.

**Comment by human-a** [comment]
@asturur I am experiencing the same issue with groups. Any idea how to resolve that one too?

**Comment by asturur** [comment]
last time you  gave a fiddle and you got help and solution. it worked.
why not coming back with a fiddle directly?

**Comment by human-a** [comment]
@asturur : You are right. However, for some reason, I can not replicate this issue in a fiddle, so this must be caused by something else, although the error that I get in the console is exactly the same as before. I will keep you posted here as soon as I have a presentable fiddle.

**Comment by human-a** [comment]
Here is a working fiddle: https://jsfiddle.net/human_a/63wukwhu/

In addition to the error you can see in the console, I also get the following error on my local machine:


```
fabric.js:17967 Uncaught TypeError: Cannot set property 'group' of undefined
    at klass.initialize (fabric.js:17967)
    at klass.eval [as initialize] (fabric.js:1745)
    at new klass (fabric.js:1793)
    at eval (fabric.js:18450)
    at onLoaded (fabric.js:674)
    at eval (fabric.js:700)
    at eval (fabric.js:19098)
    at HTMLImageElement.img.onerror (fabric.js:644)
```

**Comment by human-a** [comment]
@asturur This issue is still not fixed for groups. I have provided a [working fiddle](https://jsfiddle.net/human_a/63wukwhu/) for it too. Please read the reply above this one.

Any ideas?

**Comment by multivoltage** [comment]
Is so strange but I came here in 2026.
I tried the example in you fiddle (with current new version) and the problems exist today.

**Comment by asturur** [comment]
This PR was supposed to solve it: https://github.com/fabricjs/fabric.js/pull/3586, that is on version 5.
Can you post a fiddle or something i can check online on version 7 and see where it breaks?

**Comment by multivoltage** [comment]
Yes sure. Maybe tomorrow.

**Comment by multivoltage** [comment]
@asturur you can check at https://jsfiddle.net/fozpt8uj/26/

I used 2 equals config, but the second one has a wrong src image (taken fro placeholder).
You can see, after "load wrong canvas" click all is white.
I also put "reviver" calback but it is trigger only with "right" objects

**Comment by asturur** [comment]
it seems that in the conversion between callback and promise we lost this.
Can you open a new issue for this so we can address it? Add your fiddle there.
