### ISSUE TITLE
"after:render" event fires before filters are completed, even with async:true on image

### ISSUE THREAD

**Issue by PatONeil** [kangax/fabric.js#3580]
I would think that the "after:render" event should only fire after all of the filters have completed.  That is not the case with the current release.

I am trying to use canvas.toDataURL() when the image has been completed rendered but it is not working..

**Comment by asturur** [comment]
i think it should work.
open a fiddle so that we can see what is wrong.

**Comment by PatONeil** [comment]
I created a fiddle and it works!!!! http://jsfiddle.net/ob4x7cwL/

However,  when I put alerts in my code similar to the fiddle, the 'after:render' fires before filters are done...

I guess it somewhere in my code... but have no idea where.

**Comment by asturur** [comment]
provably you have some other event that fires a re render.
maybe an object remove?
