### ISSUE TITLE
Itext clone doesn't keep the event function

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3583]
Hi,

It seems to me the event "editing:entered" isn't fired after the clone for an itext object.

Here is a fiddle :
http://jsfiddle.net/5m77ogw8/36/

I click on a the first itext object, the event "entered" is fired, after the clone (click on the button), the new clone doesn't fire the "entered" event.
I tried to call the "initBehavior()" function as mentioned on an old ticket, but without success. => I don't really know what this function do, and if it's still needed, it seems used when you do a clone via the util class.

is there a link with the ticket 3557 (https://github.com/kangax/fabric.js/issues/3557) where the events after the creation af a new itext object is not called ? 

Thank you for your insight.

**Comment by asturur** [comment]
http://jsfiddle.net/5m77ogw8/37/

Well the event you set is on the first text object.
The events do not get cloned with clone function.
If you set the event at canvas level as i did on the fiddle, every text will fire the selection.

there is no actual way to clone functions in fabricjs.
If you need every created text to have some event binded you better create your custom class extending textbox or itext and add the event on the initialize function.

**Comment by ncou** [comment]
Thank you, i was not aware you can set event on object from the canvas level. I have surely missed this when i have looked at the demo.

Thank you for your help and your time. I will keep in mind the fact to use a custom object if i need an even on each object creation.

Have a good day.
