### ISSUE TITLE
inconsistent group coordinate when scale canvas

### ISSUE THREAD

**Issue by deart1mer** [kangax/fabric.js#3585]
## Version
1.6.6

## Test Case
https://jsfiddle.net/t1mer/fctr204h/

## Steps to reproduce
Step 1: Zoomed the canvas(Use zoomToPoint or change viewportTransform).
Step 2: Make all objects in a group and set the group active.
Step 3: Get the current position of the group and print it.
Step 4: After that I changed the group's position and print it.
Step 5: Repeat the Step 2 to Step 5.

I found that `currentPos` **at the second time** was not equal to `movedToPos` **at the first time** . I couldn't figure out why.

![image](https://cloud.githubusercontent.com/assets/10653243/21479776/34f6c0b4-cb92-11e6-9329-728883889e96.png)

**Comment by asturur** [comment]
this does not represent an issue. what is the bug? what is going wrong?

**Comment by deart1mer** [comment]
I set the group to (462, 375) at first. 
Then I got the group's coordinate was (534.9000...1, 438.69999...3). 
It's a wrong coordinate.

**Comment by asturur** [comment]
is there something wrong visually? objects appear in wrong position?

**Comment by deart1mer** [comment]
I print the position in the console. You could see the output in the console.
You'll  find that currentPos at the second time was not equal to movedToPos at the first time.But I have set it.
