### ISSUE TITLE
Rect dimensions are incorrect

### ISSUE THREAD

**Issue by adriaanmeuris** [kangax/fabric.js#3587]
## Version
1.7.2

## Test Case
https://jsfiddle.net/d9rcxzry/

## Steps to reproduce

1. Create a canvas
2. Add a rect with dimensions (e.g. 150x150)
3. Get the dimensions of the rect using getWidth() and getHeight()

## Expected Behavior
Dimensions are 150x150

## Actual Behavior
Dimensions are 151x151

**Comment by asturur** [comment]
getWidth are not normal getters. Is specified in docs:

http://fabricjs.com/docs/fabric.Object.html

search for getWidth

the name is infact confusiong and is gonna be deleted in fabric 2.0 where an api break is tolerable.

**Comment by adriaanmeuris** [comment]
Thanks for your quick reply! Had a look at the docs, the dimensions are correct indeed.

I created this issue because two rects with the same dimensions do seem to be off a little.
I updated the fiddle to illustrate the issue: https://jsfiddle.net/d9rcxzry/2/

Both rects have the same dimensions, but the red rect is visible around the borders of the grey rect:
![screen shot 2016-12-27 at 09 12 45](https://cloud.githubusercontent.com/assets/16230038/21495061/b697330a-cc15-11e6-81f8-72d26a8d367c.png)

I tried various scenarios with/without objectCaching and retinaScaling, but I can't seem to get the dimensions exactly the same. Any idea?

**Comment by asturur** [comment]
![image](https://cloud.githubusercontent.com/assets/1194048/21495275/cf0553ee-cc16-11e6-8462-65011fc10a15.png)

to me are perfectly same.
Did you give stroke to one of 2 in an early try?

**Comment by adriaanmeuris** [comment]
Hi, the screenshot is taken from this latest fiddle so no borders were set.
I did some tests in different environments, it seems this is devicepixelratio dependent.

On a macbook (retina), the issue does not occur. When using an external screen (non-retina) on the same macbook, the issue occurs.

I tried setting enableRetinaScaling to false for testing purposes (https://jsfiddle.net/d9rcxzry/3/), but the issue still occurs.

Did some tests using BrowserStack on Windows (Edge 14). Issue also occurs there (both on my retina / non-retina screen):
![screen shot 2016-12-27 at 09 47 38](https://cloud.githubusercontent.com/assets/16230038/21495724/a056d6d2-cc19-11e6-99e7-551ba3e787d0.png)

**Comment by asturur** [comment]
if you position it at 10.5, 10.5 you ll see the problem disappear. also if you put grey under red you wilp see grey appear under red.

the rect is positionedin a way is on half pixel for some reason and not being possible draw half pixel canvas just aproximate with opacity. at that point you see also some color of the underlying rect.

**Comment by adriaanmeuris** [comment]
this might indeed be an anti-aliasing issue. 

I positioned both rects at 10.5 left and 10.5 top (https://jsfiddle.net/d9rcxzry/5/). Result:
![screen shot 2016-12-27 at 10 04 11](https://cloud.githubusercontent.com/assets/16230038/21496039/dd15f4ca-cc1b-11e6-8641-029885e06285.png)

I also tried position only one rect at 10.5 left and 10.5 top (https://jsfiddle.net/d9rcxzry/6/). Result:
![screen shot 2016-12-27 at 10 05 16](https://cloud.githubusercontent.com/assets/16230038/21496059/fd89a88c-cc1b-11e6-9b69-dd0ee4d2b2bb.png)

It looks they're still off, some I'm not sure what's causing this behaviour. 

Since both rects have exactly the same position and dimensions, I would think the same anti-aliasing would apply to both of them.

**Comment by asturur** [comment]
is for sure an aliasing issue, something normal when you work with canvas. i have difficulties making it disappear, the 10.5 should do the trick but is not doing it.

setting strokeWidth to an even number does, so should do the 0.5 position.

**Comment by adriaanmeuris** [comment]
Alright, do you might have a fiddle I can check out?

I tried applying a stroke to no avail. I did however manage to remove the red border by applying a stroke of 1px and reducing the width and height with 2px: https://jsfiddle.net/d9rcxzry/7/
Result:
![screen shot 2016-12-27 at 10 46 33](https://cloud.githubusercontent.com/assets/16230038/21496851/c0a76548-cc21-11e6-8659-63748f4a711b.png)

Any idea how I could make sure rects are always crisp? I was thinking about the example here, where the [ctx is translated to half a pixel](http://www.rgraph.net/canvas/docs/howto-get-crisp-lines-with-no-antialias.html).

**Comment by adriaanmeuris** [comment]
I did an additional test drawing the rects using the native CanvasRenderingContext2D interface.
See: https://jsfiddle.net/d9rcxzry/9/

It's interesting to see that the same rects don't show any anti-aliasing when using native:
![screen shot 2016-12-27 at 11 15 02](https://cloud.githubusercontent.com/assets/16230038/21497495/bbe3e00a-cc25-11e6-96b2-81ad00ef50a6.png)

Any idea how I could pull this off in Fabric?

**Comment by asturur** [comment]
if you want to lower chance of aliasing in fabric
set strokeWidth to 0, do not allow for user dragging or scaling objects ( use staticCanvas ) do not use setZoom if not with full numbers ( 2, 3, 4) use even number in dimensions.

The native function you used are indeed not movable rects with no strokes.

**Comment by adriaanmeuris** [comment]
Thanks for your feedback. Didn't try setting strokeWidth to 0, I was under impression that this was the default. Anti-aliasing is gone now, see updated example: https://jsfiddle.net/d9rcxzry/12/.

Thanks for your help!

**Comment by Tsourdox** [comment]
This solved the issue for me as well! Why isn't `0` the default value of strokeWidth?

**Comment by Tsourdox** [comment]
This solved the issue for me as well! Why isn't `0` the default value of strokeWidth?
