### ISSUE TITLE
Wrong IText cursor's position in IE 

### ISSUE THREAD

**Issue by Rad1calDreamer** [kangax/fabric.js#3588]
## Version
1.7.2

## Test Case
http://fabricjs.com/test/misc/itext.html 

## Steps to reproduce
clear text on "A bigger text" block
focus in Itext and fast type or hold any button
## Expected Behavior
![chrome](https://cloud.githubusercontent.com/assets/7055577/21495509/f30006c4-cc28-11e6-93f0-61a8bf7c26b7.gif)

cursor in end of Itext and witdth == text width (like Crome)
## Actual Behavior
wrong width of Itext
![ie](https://cloud.githubusercontent.com/assets/7055577/21495517/0430e86e-cc29-11e6-8185-e60826c0c87a.gif)

**Comment by asturur** [comment]
Does it happen in a fiddle with proper font loading?

**Comment by Rad1calDreamer** [comment]
hm....it fixed if i remove  fontFamily: "Verdana" property.
But i need it

**Comment by asturur** [comment]
Can you create a fiddle with this happening when the font is properly loaded?

**Comment by Rad1calDreamer** [comment]
yes, give me a 10 min.

**Comment by Rad1calDreamer** [comment]
http://jsfiddle.net/Rad1calDreamer/3ztLxtct/6/

how i can detected what system fonts are loaded ?

**Comment by Rad1calDreamer** [comment]
and some offtop - how i can make some donate? i use fabricjs in big project and want say "thank" to developers

**Comment by asturur** [comment]
You can put some money on the bountysource program for fabricjs if you want to.

https://www.bountysource.com/teams/fabric.js

**Comment by asturur** [comment]
as soon as i start my win virtual machine i ll try the fiddle.

**Comment by asturur** [comment]
Yes i can reproduce on win 10 ie and edge.
The strange thing is that it happens also with other fonts but not with times New Roman.
I have to check every value returned from measureText and figure out what is going wrong,

**Comment by Rad1calDreamer** [comment]
Hi, did you have any result?

**Comment by StephanBijzitter** [comment]
We're also experiencing this issue, but we're not sure where to start fixing this.
If you need some extra manpower, point us in the right direction and we'll get on it :-)

**Comment by asturur** [comment]
Oh if you could do this experiments:

After textbox/itext is loaded and cursor is wrong, execute from web console, if you have access to fabric object, if not make it:

fabric.charWidthsCache = {};

This will reset caching, then delete content of textbox and write something different.

If then is good, it means that for some reason window is giving us wrong char widths first at some point when the font is not loaded.

**Comment by Rad1calDreamer** [comment]
i add this after adding itext to canvas, after changing fontSize. But it not helps

**Comment by Rad1calDreamer** [comment]
can i somehow help fix this?

**Comment by Rad1calDreamer** [comment]
?

**Comment by asturur** [comment]
i managed to create a workaround to fix it.
MS browsers measure chars with integers.
So a char is either wide 8 or 9 or 10 pixels. This is not ok for small font sizes and errors of 0.5 accumulates during long strings.

Now i created a font cache that is measured just at 200px font size and all the other sizes are obtained by division. this fix the issue most of the time. if you work with  fontSize of 200 or more, the problem may come back.

**Comment by Rad1calDreamer** [comment]
repeating on 2.0 beta7 in chrome
https://youtu.be/eq80eB66VL4

**Comment by asturur** [comment]
I'm pretty confident this is a bad loading use case.
That page does not load anything, and does not wait for loading.
If you refresh a couple of time, then is perfectly fine.
The cursor position is calculated as much as with accuracy as i can do now.
