### ISSUE TITLE
Itext control square present after quitting editing mode

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3591]
Hi,

It seems the control square is still present after quitting the edition of the itext object.

If i double click on the itext object, i enter the edit mode, if i made a single click outside of the object on the canvas, the "blue controls" disapear (and also the editing cursor), but there is still a rect present (cf screenshot), i need to click again on the canvas to made it disapear (i have looked at the events, it seems the deselect event is launched correctly).
http://jsfiddle.net/5m77ogw8/37/

![image](https://cloud.githubusercontent.com/assets/16743322/21504501/c7decf3e-cc5f-11e6-9a62-3b6248a7691b.png)

PS : I am using chrome v55.0.2883.87 m.

Can you confirm this behavior ? Thank you.

**Comment by asturur** [comment]
yes regression from recent cleaning for the text selection that was disappearing on mouse up.
oh dear i need automated visual tests. so much.
