### ISSUE TITLE
Itext delete text is not marked as "Dirty" for clearCache (using Shift+HOME)

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3592]
Hi,

If i enter a text (press a key a long time for example), still in edit mode, select all the text using SHIFT+HOME or SHIFT+END, and press the "Delete" or "Supression" key, the text is still present but the cursor is set at the begining of the textbox (is i press again a key, the text is cleared).

The behavior is correct if i use CTRL+A instead of SHIFT+HOME. 
It looks like the text object is not marked as dirty after a delete using this selection keys

http://jsfiddle.net/Rad1calDreamer/3ztLxtct/6/

**Comment by asturur** [comment]
i do not have those key on this macbook :(

**Comment by asturur** [comment]
ok shift + UP trigger the bug anyway
