### ISSUE TITLE
Freedrawn lines rendered too small in kitchensink

### ISSUE THREAD

**Issue by ingridmarleen** [kangax/fabric.js#3593]
You asked me to come up with a fiddle instead of code in our own application. Well, I didn't need to. In my previous issue I posted a screenshot of the freedraw demo where I have the same problem and now I also have one in the kitchensink. (see picture, the greyish lines had to be thicker black ones, almost straight)
I'm posting this issue to mock at you, It is just a problem I have.
It seems that the rendered object width doesn't add the width of the line when drawing a line that's almost straight.
![kitchensink](https://cloud.githubusercontent.com/assets/13930160/21516161/114d06a6-ccd6-11e6-8a7a-d96eaa39620e.JPG)

**Comment by asturur** [comment]
The point of a fiddle is not to to be belived, is to give us a fast reproducible way to trigger a bug and to see if it is solved.
I cannot sit in front of kitchensink, pulling straight lines, hoping that this will happen also to me so that i have chance to fix it.
There was no need to open an issue the other one is perfectly fine.

**Comment by asturur** [comment]
in object.class.js
```diff
    /**
     * Return the dimension and the zoom level needed to create a cache canvas
     * big enough to host the object to be cached.
     * @private
     * @return {Object}.width width of canvas
     * @return {Object}.height height of canvas
     * @return {Object}.zoomX zoomX zoom value to unscale the canvas before drawing cache
     * @return {Object}.zoomY zoomY zoom value to unscale the canvas before drawing cache
     */
    _getCacheCanvasDimensions: function() {
      var zoom = this.canvas && this.canvas.getZoom() || 1,
          objectScale = this.getObjectScaling(),
          dim = this._getNonTransformedDimensions(),
          retina = this.canvas && this.canvas._isRetinaScaling() ? fabric.devicePixelRatio : 1,
          zoomX = objectScale.scaleX * zoom * retina,
          zoomY = objectScale.scaleY * zoom * retina,
          width = dim.x * zoomX,
          height = dim.y * zoomY;
      return {
+        width: Math.ceil(width) + 2,
+        height: Math.ceil(height) + 2,
-        height: height,
-        width: width,
        zoomX: zoomX,
        zoomY: zoomY
      };
    },
```

something like that.
