### ISSUE TITLE
about path close issue

### ISSUE THREAD

**Issue by jsonformat** [kangax/fabric.js#3597]
I don't want path Head and foot combination, I searched the path docs in API but didn't find what I wanted, hoping to get help, Thank!

**Comment by asturur** [comment]
I m sorry is completely unclear what you are talking about.
Please rephrase your question.

**Comment by jsonformat** [comment]
`var path = new fabric.Path('C30,218,30,218,30,218C30,219,33,219,37,219C42,219,47,219,54,219C61,219,68,219,75,220C81,220,83,222,83,222z')
`
I want to draw bezier, however, `fabric.Path` Let the line end to end,I don't need to be connected.

**Comment by asturur** [comment]
Ok is not fabric related. The answer is very simple if you open a question on stackoverlfow i will help you, here is not the place at all.
