### ISSUE TITLE
not able to get updated points in line?

### ISSUE THREAD

**Issue by ManjunathBiradar** [kangax/fabric.js#3605]
## Version
1.6.3

## Steps to reproduce
1) Draw a line on canvas

2) rotate/drag/modify the line on canvas

3) now try to get the values of x1. y1, x2, y2

## Expected Behavior
It should give me the updated x1, y1, x2, y2

## Actual Behavior
But the values are same as initial values with which line is drawn.

**Comment by ManjunathBiradar** [comment]
@asturur i am in need of same feature as it is provided for polygons to get updated points using the following code : 

 var translatedPoints = polygon.get("points")
        .map(function(p){
          return new fabric.Point(p.x - polygon.minX -polygon.width/2, p.y - polygon.minY - polygon.height/2);
          })
        .map(function(p){
          return fabric.util.transformPoint(p, matrix);
        });

So my question is , is it possible to do same kind of thing for Line Object???

**Comment by asturur** [comment]
Please, if you open a stackoverflow question i will answer there.
This issue tracker is not used for personal help requests, if i decide to help someone i prefer the effort is usefull for other people too.
