### ISSUE TITLE
loadFromJSON is causing images to be filled solid black

### ISSUE THREAD

**Issue by daniellematy** [kangax/fabric.js#3606]
I have a group , and in the group i have 2 objects both images. 

But object 0 is showing the image as solid black rather than the image.

Im using 1.6.7 , but i have tried every version with the same result

this is what im using to load the json 

```
$.getJSON(url+'api/template/'+template_id, function(data){
                console.log('done')
                __canvas.loadFromJSON(data[0].jsonData, __canvas.renderAll.bind(__canvas));
            });
```

this is what im using to save the json
`JSON.stringify(__canvas.toObject(['graphicType']))`

and this is what the json looks like

`{"objects":[{"type":"group","originX":"left","originY":"top","left":0,"top":0,"width":540,"height":540,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"graphicType":"background","objects":[{"type":"image","originX":"center","originY":"center","left":0,"top":0,"width":540,"height":540,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"crossOrigin":"","alignX":"none","alignY":"none","meetOrSlice":"slice","graphicType":"photo","src":"http://graphictool.app//assets/photos/6LvQAVTOLLDdpQHXkFKLpjq9ZRcQ9N7s7w6gRYlX.jpg","filters":[{"type":"Brightness","brightness":0},{"type":"Tint","color":"#000","opacity":0},{"type":"GaussianBlur","radius":1},{"type":"Tint","color":"#3513B0","opacity":0}],"resizeFilters":[]},{"type":"image","originX":"center","originY":"center","left":0,"top":0,"width":540,"height":540,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"crossOrigin":"","alignX":"none","alignY":"none","meetOrSlice":"slice","graphicType":"mask","src":"http://graphictool.app//assets/masks/918237274_18273828.png","filters":[],"resizeFilters":[]}]},{"type":"textbox","originX":"left","originY":"top","left":39,"top":39,"width":355,"height":45.2,"fill":"rgba(0, 0, 0, 1)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":{"color":"rgba(0,0,0,0.0)","blur":20,"offsetX":10,"offsetY":10,"affectStroke":false},"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"Ok this is amaxinf","fontSize":40,"fontWeight":"normal","fontFamily":"'Modak', cursive","fontStyle":"normal","lineHeight":1.16,"textDecoration":"normal","textAlign":"left","textBackgroundColor":"","charSpacing":0,"minWidth":20,"graphicType":"text","styles":{}}],"background":"#fff"}`

**Comment by asturur** [comment]
```{"type":"Brightness","brightness":0}``` this is the cause of black, brightness 0.

This is the cause that let me tell you are using custom code and this is not an issue o fabricjs itself.

```{"type":"GaussianBlur","radius":1}```

**Comment by daniellematy** [comment]
ah right, 

Thanks very much :)
