### ISSUE TITLE
drawImage "InvalidStateError" in IE11 and Edge on specific object

### ISSUE THREAD

**Issue by khmyznikov** [kangax/fabric.js#3607]
## Version
1.7.2

## Test Case
http://jsfiddle.net/p9f9shfj/2/

## Steps to reproduce
Create broken object - downscale him to invisible state.
Call "discardActiveGroup" and "renderAll".

## Expected Behavior
No errors as in Chrome or Safari

## Actual Behavior
InvalidStateError - DOM Exception Error

>  DOMException.INVALID_STATE_ERR 11
The specified node is not attached to the document. Starting with Internet Explorer 10, the error-code string InvalidStateError is returned instead.

## My solution
`drawCacheOnCanvas: function(ctx) {`
     `  ctx.scale(1 / this.zoomX, 1 / this.zoomY);`
  **`    if (!this._cacheCanvas.height)`
   `     this._cacheCanvas.height = 1`
     ` if (!this._cacheCanvas.width)`
      `  this._cacheCanvas.width = 1`**
   `   ctx.drawImage(this._cacheCanvas, -this.cacheWidth / 2, -this.cacheHeight / 2);`
   ` }`

**Comment by asturur** [comment]
This should be fixed in current build because we add  2 pixel to canvas and anyway we do not round it's dimensions but use Math.ceil that should give us an integer bigger than 0.

try the v173 branch, is already built in the dist folder.

https://github.com/kangax/fabric.js/tree/v173

**Comment by asturur** [comment]
1.7.3 is out and main dist/fabric.js is updated.
Could you please try again the fiddle on ie11? i cannot access internet explorer easily

**Comment by khmyznikov** [comment]
@asturur Checked. Looks like all working good now.
