### ISSUE TITLE
Cursor change doesn't remain when right (or left) clicking and dragging (panning)

### ISSUE THREAD

**Issue by ajck** [kangax/fabric.js#3609]
## Version
1.7.2

## Test Case
http://jsfiddle.net/Da7SP/411/

## Steps to reproduce
See jsfiddle above

## Expected Behavior
Cursor should change (e.g. to crosshair, as per jsfiddle above) when user clicks right mouse button (mousedown event), cursor remains changed while user keeps right mouse button held down and pans canvas around (mousemove events), then cursor changes back to default when user releases right mouse button (mouseup event). Furthermore, logically I would expect canvas.defaultCursor and/or the canvas.moveCursor to be set to the changed cursor while it's active.

## Actual Behavior
Cursor does change when user presses right mouse button but as soon as the mouse is moved, the cursor changes back to default. The expected behaviour is seen if the mouse is not moved at all while the right mouse button is pressed.
Note that this same behaviour is also seen if the left mouse button is used instead - change the 2 to a 0 in lines 15 and 16 in the fiddle, in: "if(e.e.button == 2)"

Also, canvas.defaultCursor and canvas.moveCursor are not updated at all (I logged these for each mousemove event and the mouseup event, and they never change).

**Comment by asturur** [comment]
This method temporary set the canvas html element cursor to a value.
It does not do what you think.
http://fabricjs.com/docs/fabric.Canvas.html#setCursor

defaultCursor is not changed by anything if not changing the value of the property itself.
http://fabricjs.com/docs/fabric.Canvas.html#defaultCursor

So either:
On mouse down change defaultCursor to crosshair, or on mousemove setCursor to crossHair.
