### ISSUE TITLE
Use short form in path array

### ISSUE THREAD

**Issue by AlexNomad** [kangax/fabric.js#361]
// w/o letters
var myPath = [
 [0,0], //moveTo, absolute
 [10,50], //lineTo, absolute
 [50,20]  //lineTo, absolute
];

//cnahges in code

_render: function(ctx) {
 //...
 if(path[0].length==2)
   x = path[0][0];
   y = path[0][1];
   ctx.moveTo(x + l, y + t);
   for (var i = 1, len = this.path.length; i < len; ++i) {
        x = path[i][0];
        y = path[i][1];
        ctx.lineTo(x + l, y + t);
   }
}

**Comment by asturur** [comment]
This feature request is either not applicable or based on old needs that are replaced by new functions or features.
The feature also did not receive attention from other developers.
I will reopen by request if other may find it interesting.
