### ISSUE TITLE
is there any way to connect two object with curve point??

### ISSUE THREAD

**Issue by desaikalpesh34** [kangax/fabric.js#3610]
Hello @kangax 
how to add curve point on object.
is there any way to add curve point on object and connect two object.
like [this](http://prntscr.com/drrhya) 

## Version
1.7.2

**Comment by ncou** [comment]
Hi,

I think it's more a stackoverflow question, than an issue.

Have you checked the demo :
http://fabricjs.com/quadratic-curve

If you know the positionning you could made an SVG bezier curve (like in the demo).

If you want to connect points, you could use a "cardinal spline curve" to do an extrapolation :
https://github.com/epistemex/cardinal-spline-js

**Comment by superczan** [comment]
Yup does not seem like an issue to me either.

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
