### ISSUE TITLE
Appling stroke to a cliped object

### ISSUE THREAD

**Issue by alexandrebarreiros** [kangax/fabric.js#3617]
Version

1.7.2

Steps to reproduce
Apply a stroke to an object with clipPath, override the functions:

fabric.Object.prototype.render = function (ctx, noTransform) {
        // do not render if width/height are zeros or object is not visible
        if ((this.width === 0 && this.height === 0) || !this.visible) {
            return;
        }
        ctx.save();
        //setup fill rule for current object
        this._setupCompositeOperation(ctx);
        this.drawSelectionBackground(ctx);
        if (!noTransform) {
            this.transform(ctx);
        }
        this._setOpacity(ctx);
        this._setShadow(ctx);
        if (this.transformMatrix) {
            ctx.transform.apply(ctx, this.transformMatrix);
        }
        //this.clipTo && fabric.util.clipContext(this, ctx);
        if (this.objectCaching && !this.group) {
            if (this.isCacheDirty(noTransform)) {
                this.statefullCache && this.saveState({ propertySet: 'cacheProperties' });
                this.drawObject(this._cacheContext, noTransform);
                this.dirty = false;
            }
            this.drawCacheOnCanvas(ctx);
        }
        else {
            this.drawObject(ctx, noTransform);
            if (noTransform && this.objectCaching && this.statefullCache) {
                this.saveState({ propertySet: 'cacheProperties' });
            }
        }
        //this.clipTo && ctx.restore();
        ctx.restore();
    };

    fabric.Object.prototype.drawObject = function (ctx, noTransform) {
        this.clipTo && fabric.util.clipContext(this, ctx);
        this._renderBackground(ctx);
        this._setStrokeStyles(ctx);
        this._setFillStyles(ctx);
        this._render(ctx, noTransform);
        this.clipTo && ctx.restore();
    };
This is for the shadow not to be cut by the clip, but with it the stroke is cut by the container, see the images:

with the override: http://imageshack.com/a/img923/6428/gKkhFA.png
without the override: http://imageshack.com/a/img924/8006/kKtws5.png

Expected Behavior
The stroke not be cut by the container
Actual Behavior
The stroke is cut by the container

**Comment by asturur** [comment]
Can i see with what are you clipping the object?
are you using objectCaching true or false?

**Comment by alexandrebarreiros** [comment]
Hi Asturur,
For clipping the object i'm using a path, i have diferent shapes possibilities and even the squere is a clip to the container, i'm using objectCaching = true and a fabric.Path to do the clip. 
Example:  `new fabric.Path(pathToReturn, {
                originX: "center",
                originY: "center",
                left: 0,
                top: 0,
                stroke: rgb(0,0,0)
                strokeWidth: 10,
                fill: "rgba(0,0,0,0)",
                strokeLineJoin: 'mitter',
                strokeMiterLimit: 3000,
                objectCaching: false,
                affectStroke: true
            });`
where pathToReturn is a svg path.

**Comment by alexandrebarreiros** [comment]
Hi Asturur, 
Did you have time to check on this issue.

Best Regards
Alexandre

**Comment by alexandrebarreiros** [comment]
Hi There,
Did you have time to check on this issue?

Best Regards
Alexandre

**Comment by alexandrebarreiros** [comment]
Hi Asturur,

Did you see anything wrong on what i was doing?

Best Regards
Alexandre
