### ISSUE TITLE
remove optional deps and add npm flag as impossible to install with webpack

### ISSUE THREAD

**Issue by born2net** [kangax/fabric.js#3618]
Many of the new major libs now use WebPack and JSPM (Angular react etc...) via NPM.
the issue is that Fabric tries to install the optional deps of jsdom and canvas which are a NIGHTMARE to install in Windows. The thing is, you don't even need them as the target env is the browsers.
npm currently only supports ```--no-optional``` only at the npm install level and not at the package installation, so devs of our project always have to install fabric separately.

I am recommending that we remove the optional deps all together...  as I would assume +90% of the users of this project target the browser. 
And for the small % of people who use node-canvas, we can have separate instructions.
But it seems we are making life hard for everyone just to be able to support the few.

Please remove the package.json optional dep,

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by asturur** [comment]
I agree that windows is not a good web dev operating system. I did not manage myself and i went on a small VM just to install fabric from node.

Still fabricjs support node, the main test suite run under node, and node-canvas is not easy to install itslef ( require some lib preinstalled that you cannot install with npm ).

Said so, we are not gonna remove it. Is way easier for you to take fabric and put the file in a dependency folder and instruc webpack what to do with it. Or fork the project, remove the deps, remove node code and publish it as fabric-webonly.

I cannot take the toll of another package to support.

**Comment by born2net** [comment]
understood, tx for the reply,
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean
