### ISSUE TITLE
TypeError: this._setOptions is not a function

### ISSUE THREAD

**Issue by GatoQ** [kangax/fabric.js#3619]
Hi, I am trying to reproduce the Standalone Controls tutorial (http://fabricjs.com/controls), with a very simply html code mostly copied from the tutorial. I got the fabric.js file from the [FabricJS builder](http://fabricjs.com/build/), version 1.7.3,  (I tried selecting only Text and Interaction, and then with all options selected). The html file and javascript are in the same folder in the root of my mockup server running Lighttpd, but if I change the script source to the full path for fabric.min.js, the same behaviour can be seen loading the page using Open File in any browser:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <script src="/fabric.min.js"></script>
</head>
<body>

<canvas id="newcanvas" width="500" height="500" style="border:1px solid red;"></canvas>

<script id="main">(function () {
  var canvas = this.__canvas = new fabric.Canvas('newcanvas');
  fabric.Object.prototype.transparentCorners = false;

  var rect = new fabric.Rect({
    width: 100,
    height: 100,
    top: 100,
   left: 100,
  fill: 'rgba(255,0,0,0.5)'
 });

 canvas.add(rect);
})();
</script>
</body>
</html>
```

However, only the empty canvas gets displayed in the browser, and I get the following errors in the console.

```
TypeError: this._setOptions is not a function
fabric.StaticCanvas<._initOptions()                   fabric.min.js:1
fabric.StaticCanvas<._initStatic()                    fabric.min.js:1
fabric.Canvas<.initialize()                           fabric.min.js:1
i()                                                   fabric.min.js:1
<anonymous>                                           fabric-fullhtml.html:28
<anonymous>
```

I did not see any dependency in the docs, and the only external library in the example is angular, but there is nothing on the code using angular. Is there something else I need to add to the code? 

Thanks

**Comment by asturur** [comment]
urgh in 1.7.3 we have a shared module i did not include in the custom builder. i ll address soon.

**Comment by jossiemathews** [comment]
This happens here too , I was upgrading from 1.6 to the latest, Please resolve the issue.

**Comment by asturur** [comment]
i updated the build system, please check.
Be carefull of the news when moving from 1.6.x to 1.7.3

http://fabricjs.com/fabric-object-caching

**Comment by peleteiro** [comment]
This problem still persists. :(

**Comment by alexdunne** [comment]
@asturur Tried an example with gestures and interactions selected in the build and the issue remains. https://jsfiddle.net/unjm0wmy/1/

**Comment by asturur** [comment]
i'm a bit buys those days.
i will take care of the missing _setOptions asap, i will check gestures later.

I need more info about what is the problem with gestures.

**Comment by alexdunne** [comment]
Understood, thanks for maintaining!

I'm assuming it's part of the same problem. The error from the jsfiddle is `Uncaught TypeError: this._setOptions is not a function` which the same stack trace as the initial issue.

**Comment by asturur** [comment]
Ok i was just editing the wrong part of the file! now the custom build on the website is aligned to the one on the command line.
We should be fine. The exact example of this issue works.

**Comment by asturur** [comment]
the controls tutorial needs updates anyway, is missing lot of new properties

**Comment by alexdunne** [comment]
@asturur Thanks for doing that. Can confirm the build works with gestures (https://jsfiddle.net/unjm0wmy/2/).

Assuming anyone can contribute to the docs I'd be happy to help if you create an issue with what needs improving. I'm not a fabricjs expert but I've used it enough at a high level that I'm sure I can help out in some way.

**Comment by asturur** [comment]
would be nice to update the controls demo with all the new properties. but that wluld require to run a local copy of fabricjs.com to try changes before submitting. if you have mac or linux is easy, if you are on windows let it go. is more pain than other

**Comment by alexdunne** [comment]
My main home computer is Windows. I do have an old laptop running linux I occasionally use for server stuff. I'll give it a go when I get the chance.
