### ISSUE TITLE
When I update the ViewModel with a new Position and call canvas.RenderAll(), the draggable area for the object remains in the old location

### ISSUE THREAD

**Issue by atljoseph** [kangax/fabric.js#3620]
## Scripts & Styling
    <script src="fabric.js" type="text/javascript"></script>
    <style>
        div.canvas-container {
            border: solid black 1px;
        }
    </style>

## Test Case / Code Sample
<html>
    <canvas id="myCanvas" width="500" height="200"></canvas>
    <button id="move1" onclick="moveRight(20);" >Move the Rectangle</button>
   
    <script>
        function moveRight(amount){
            vm.rect1.left += amount;
            canvas.renderAll();
        }

        var vm = {
            rect1: new fabric.Rect({
                left: 100,
                top: 100,
                fill: 'red',
                width: 75,
                height: 75
            })
        };

        // create a wrapper around native canvas element (with id="c")
        var canvas = new fabric.Canvas('myCanvas');
        
        // "add" rectangle onto canvas
        canvas.add(vm.rect1);
    </script>

## Version
1.7.3

## Steps to reproduce
Hit the button to update the position of the rectangle in the view model.
The rectangle will move when the view model is updated.
ISSUE ==> After the rectangle moves, probe around it with the cursor to find that its draggable area is still in the rectangle's old location instead of the new one.

## Expected Behavior
I would expect that if the rectangle moves, then the draggable area would also move.

## Actual Behavior
The interactable, draggable area of the rectangle remains in the rectangle's old location when the rectangle's location is modified by changing its location in the view model.

**Comment by neopheus** [comment]
JSFiddle without ViewModel : http://jsfiddle.net/Da7SP/422/
No problem

**Comment by neopheus** [comment]
JSFiddle with ViewModel : http://jsfiddle.net/Da7SP/424/
No Problem

**Comment by asturur** [comment]
https://github.com/kangax/fabric.js/wiki/Fabric-gotchas

thanks @neopheus

**Comment by atljoseph** [comment]
Did you guys read the bug report?
The comment 'No problem' is not correct. 

Read the bug report again and follow it to the T. The bug still exists in the jsFiddle with viewModel. 

I pointed out the bug in the report very specifically. The fact that the red rectangle loads and is draggable and moves when the button is pressed does not imply no bug. You must check the draggable area of the rectangle after the rectangle has been moved. This effect is more pronounced when the button has been pressed many times in a row. 

Thanks,

JG

**Comment by asturur** [comment]
So the bug report is clear, and is not a bug. Your code changes the left property of the rect, then re render canvas. The interaction area is not updated untill you call rect.setCoords() that you should add to your button. is this not clear in the wiki i linked?
