### ISSUE TITLE
ZoomToPoint object

### ISSUE THREAD

**Issue by Vincent030299** [kangax/fabric.js#3622]
Can you add that you can zoomToPoint on an object not the entire canvas.

**Comment by asturur** [comment]
What is the point of it? can you be more specific? i m sure there is a way with current api/methods to do what you want.

**Comment by samael205** [comment]
What vincent means is that only an object is zoomed from the canvas, not the entire canvas. Or so I think.

You could do it by managing the scaling of that object to simulate the zoom ... Right?

**Comment by Vincent030299** [comment]
I have a badge-editor. And I can upload a picture.

Now I want the user to be able to zoom In/Zoom Out.

![knipsel](https://cloud.githubusercontent.com/assets/15730110/21929912/8dd0cae0-d993-11e6-9d01-0491c884c2d2.PNG)

What I want is that the image scales from the center. And not effect he Circle that surrounds it.

This is what happends now When I Zoom in once:

![knipsel1](https://cloud.githubusercontent.com/assets/15730110/21930031/278ad98c-d994-11e6-9d09-5a014bca85db.PNG)

**Comment by asturur** [comment]
Open a fidde with a similar structure or is not possible to help you.
Consider getting a working stackoverflow fiddle so that you can be helped there.
This is not a support forum.
