### ISSUE TITLE
Object movement has strange offset

### ISSUE THREAD

**Issue by punkoffice** [kangax/fabric.js#3624]
I'm using fabric.js with Babylon.js to lay a dynamic texture onto 3D objects.  Mouse location works fine with hovering over a fabric.js object and I can select the correct object, however, when I push mouse button down and move that object it has a strange offset applied which moves it far from the cursor.  You can see the position of the object in the console logs.  There is a massive jump when it starts moving.  Does anyone know how I can fix it?

Here is the babylon.js playground.  If it says "fabric undefined", just click the "Run" button
[http://www.babylonjs-playground.com/#9U086#114](http://www.babylonjs-playground.com/#9U086#114)

**Comment by punkoffice** [comment]
I checked the _translateObject() function and noticed the "left" and "top" values alternating between valid and invalid numbers like this:
left: 202  top: 710
left: 1180  top: 243
left: 201  top: 710
left: 1179  top: 243

I made a quick fix by filtering out "left" numbers greater than 1,000.  You can see it working here [http://www.babylonjs-playground.com/#9U086#116](http://www.babylonjs-playground.com/#9U086#116)  I'm still trying to find the root of the problem though.

**Comment by asturur** [comment]
I  gave a quick check to code, i m not reading further if you do not point me at the part of code that translates the 2d movement of mouse in 3d coordinates. Who is gonna translate the left and top changes in fabric tranlsation in the good one of the 3d camera?
