### ISSUE TITLE
Creating polygon shapes via mouse drag does not center the shape to its selection border box

### ISSUE THREAD

**Issue by human-a** [kangax/fabric.js#3626]
## Version
1.7.3

## Test Case
https://jsfiddle.net/human_a/twdgya93/

## Steps to reproduce
Click on the green button to go to drawing mode, drag the mouse inside the canvas to start creating the shape, let go of the mouse, then try selecting the newly created shape. The bounding box size matches the size of the new polygon, but it's not positioned correctly.

## Expected Behavior
If instead of polygons I try to create any other type of shapes (rectangles, circles or triangles) It works perfectly fine.

## Actual Behavior
Since polygons use a different method by calculating the points it calculates the width and the height, and since in this method of creating shapes the width/height are being calculated after the shape is created (with `mouse:move` event) the bounding rectangle will not be positioned correctly.

Also even if I try to change the size of the polygon (I don't want to scale the shapes, it's a bad idea) again the bounding rectangle is not positioned correctly, you can try it in the demo above using the number input field right next to the button.

## PS
I did not write the `calcPolygonPoints` function, I found it somewhere on the web a while ago, unfortunately, I could not find its link again to credit the creator of this amazing function.

**Comment by asturur** [comment]
You cannot create an empty polygon and then update it. this is an unsupported feature.
Other than that this falls outside the scope of the issue tracker.
If you replicate the question on stackoverflow and post a link i will answer there.

Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

**Comment by human-a** [comment]
Hi

Thanks for the answer. But even if I change the code to this:

```javascript
const polygon = new fabric.Polygon(calcPolygonPoints(8, Math.abs( origX - pointer.x ) / 2 ), {
			objectCaching: false,
			left: origX,
			top: origY,
			originX: 'center',
			originY: 'center',
			fill: 'rgba(255,255,255, 1)',
			perPixelTargetFind: false,
			strokeWidth: 1,
			strokeDashArray: [0,0],
			objType: 'shape',
			stroke: 'rgba(17,17,17,1)',
			hasControls: false,
			hasBorders: false
		})
		// polygon._calcDimensions()
		canvas.add(polygon).setActiveObject(polygon)
```

The result would still be the same. Unless I have misunderstood the meaning of "empty polygon"
I will post the same question on StackOverflow too.

**Comment by human-a** [comment]
Here is the StackOverflow: http://stackoverflow.com/questions/41678349/creating-polygon-shapes-via-mouse-drag-does-not-center-the-shape-to-its-selectio
