### ISSUE TITLE
Without the interactive module the library does not work

### ISSUE THREAD

**Issue by alexdunne** [kangax/fabric.js#3627]
## Version
1.7.3

## Test Case
https://jsfiddle.net/unjm0wmy/3/

## Steps to reproduce
- Create a build with the builder with no options selected http://fabricjs.com/build/ 

## Expected Behavior
Adding a rectangle to the canvas should show the rectangle.

## Actual Behavior
A `Uncaught TypeError: fabric.Canvas is not a constructor` error is thrown. After console logging the `fabric` object there is no `Canvas` property.

**Comment by asturur** [comment]
fabric.Canvas is part of the interactive module.
Not selecting it means you have just StaticCanvas.
There is another issue anyway, a function necessary to make everything works is in the wrong module. I will move it, but i cannot really do it now.

So with not interactive module active you can get StaticCanvas to work but then the rect fails to draw itself.
https://jsfiddle.net/unjm0wmy/4/

**Comment by alexdunne** [comment]
Oh right, I wasn't aware there was a separation of the two Canvas types at this point. Makes sense now thanks.
