### ISSUE TITLE
Itext cursor is not rendering after selection delete

### ISSUE THREAD

**Issue by Rad1calDreamer** [kangax/fabric.js#3628]
## Version
1.7.3

## Test Case
http://fabricjs.com/test/misc/itext.html

## Steps to reproduce
select some text by mouse and continue typing

## Expected Behavior
selected text removed. cursor rendering
## Actual Behavior
selected text removed. cursor not rendering

**Comment by asturur** [comment]
that is a bug!

**Comment by asturur** [comment]
Ok it happens just if selection is by mouse and not by keyboard. Weird bug anyway

**Comment by mbaudry** [comment]
I still have the problem on fabric 1.7.4...
