### ISSUE TITLE
Selectable background; custom class/hitbox

### ISSUE THREAD

**Issue by JCLengeling** [kangax/fabric.js#3629]
BUG ( if working as intended; possible feature request)
## Version
1.7.3

## Test Case
http://jsfiddle.net/Da7SP/437/

## Steps to reproduce
I am not really sure what is causing the issue. In the example case here: create two objects (one being a "complex" custom object created with fabric.util.createClass and one being some other kind of object (here a circle)). Make sure that the hitbox of the custom created object is bigger than the object itself (basically cause a lot of whitespace which is still part of the hitbox, but which is not part of the "real" object). Make sure that the second object (here the circle) is positioned beneath/behind the custom class object hitbox. Push the second object to the back of the scene useing sendToBack.  

## Expected Behavior
If I click the second object (the circle in the background) it should get selected and I should be able to move rotate scale ... it.

## Actual Behavior
The circle is not selectable; I am not really sure what is the cause of the issue, but I believe that it has to do with the fact that my  custom class is partly selectable (the path isn't, the arrow is) and that setup might cause a issue with the hitbox.

## Why I need it:
In my current project I have maps of countries (SVGs) instead of circles as "background" (sendToBack is used to make sure that they are not in front of other objects (the maps are supposed to be the background)). Within the application users should still be able to interact with the countries (and thus move/rotate/select them even though they are part of the background). Because of the issue described above this is not always possible. So for instance in the image below (I wrote code which selects and thus shows the hitbox of the different canvas objects). The left grey area in the background (the country) is only selectable if I click on it outside of the hitbox of the line. 

![bug1](https://cloud.githubusercontent.com/assets/11597092/21988198/b91a47a6-dc06-11e6-9973-3d822291a275.png)

**Comment by asturur** [comment]
if you want to ignore the hitbox and make an object clickable just over its graphics you have 
canvas.perPixelTargetFind = true.

I think it has some issue in particular situations but works fine most of the time.

**Comment by JCLengeling** [comment]
Cool , thank you very much, wasn't aware of the flac. 
Just tried it and it seems to work  in my situation.
Should I keep the issue open or should I mark it as closed?

**Comment by asturur** [comment]
No i close it.
This is not even an issue. I normally redirect this kind of questions to reading the documentation or to stackoverflow. Other times to do not be too much blunt i answer.

Would be nice to know why the docs where not helpful to make you solve the questions so that we can improve them.

**Comment by JCLengeling** [comment]
I generally have a hard time going trough the fabricjs docs; the tutorials feel rather barebone, the source code links frequently break my browser and finding flags linke the one here isn't easy.  If I now take a look at the documentation for canvas; having possible flags. 

In this case, a more compact list of potential flags/members for canvases within the docs would have helped. The way it is done now is good if you know what you are looking for, if you trying to get an initial overview it becomes kind of hard.  Basically the way the events have been done; imagine being able to read the members the way you are able to read the events; if a member then sounds like something you might be able to use, you can simply ctrl-f the member and read the more detailed documentation beneath in the less compact view.

**Comment by asturur** [comment]
well a nice of meaningfull flags near the events could be added.
