### ISSUE TITLE
Random text characters rendered on a fabric image on Chrome >=54 in combination with >=Win8

### ISSUE THREAD

**Issue by adriaanmeuris** [kangax/fabric.js#3632]
## Version
1.7.3

## Test case
Test case is work in progress, but I'm running into an issue where characters used in my textfield are rendered on the canvas with a aqua background / fuchsia color:

![screen shot 2017-01-17 at 09 54 29](https://cloud.githubusercontent.com/assets/16230038/22013922/a755e8d2-dc9b-11e6-854b-c361593f7bb9.png)

I don't add this myself so I'm wondered why. The textfield is regular text (Arial), only seems to be happening in multi line text on Win10/Chrome55 (not able to repro on MacOS/Chrome55).

I'm still picking up the fabric source, but would be greatly appreciated if anyone could give me some directions where to start looking.
Thanks!

**Comment by adriaanmeuris** [comment]
Managed to finalize the test case, see steps below.
It looks like this only happens on specific browser/os combinations.

## Version
1.7.3

## Test Case
https://jsfiddle.net/adriaanmeuris/4obL7240/

## Steps to reproduce

1. Open **chrome version >=54** in combination with **Windows 8, 8.1 or 10** (or set up a VM or use something like browserstack.com)
2. Open fiddle (first close other tabs, sometimes you can't reproduce it when the fiddle is open in other tabs)
3. There are some random characters printed in the fabric image:
![screen shot 2017-01-18 at 10 50 11](https://cloud.githubusercontent.com/assets/16230038/22059159/024de8ae-dd6c-11e6-8ab3-17297d867282.png)

## Expected Behavior
No random characters are printed in the fabric image.
Please open the fiddle on MacOS, a different browser, or a different OS (works fine on Win7)

## Actual Behavior
Random characters are printed in the Fabric Image.
This only happens when loading the JPG image, the issue does not occur with PNG images.
When dragging the image, characters are moving along with the image:
![screen shot 2017-01-18 at 10 52 57](https://cloud.githubusercontent.com/assets/16230038/22059247/514bc598-dd6c-11e6-9e0f-9ffbc4b246a3.png)

The images in the Fiddle are inlined using base64, but I'm attaching the original files as well (should reproduce the issue as well).

JPG file
![jpg-rect-1300-1300](https://cloud.githubusercontent.com/assets/16230038/22059303/87b85632-dd6c-11e6-9839-21bc37a2e66e.jpg)

PNG file
![png-rect-1300-1300](https://cloud.githubusercontent.com/assets/16230038/22059304/87baae78-dd6c-11e6-95e0-1897c2969c9f.png)

**Comment by asturur** [comment]
https://jsfiddle.net/4obL7240/1/  i changed the way image is loaded just to make it simpler.
I will check on my win 10 Vm

**Comment by asturur** [comment]
can you replicate the bug with some text pattern?
like `bash\nbash\nbash` so a 3 line `bash` text

**Comment by adriaanmeuris** [comment]
no problem, see https://jsfiddle.net/adriaanmeuris/4obL7240/2/
Result:
![screen shot 2017-01-18 at 12 57 16](https://cloud.githubusercontent.com/assets/16230038/22063177/b7690b54-dd7d-11e6-802e-cb1979c37e12.png)

**Comment by asturur** [comment]
LOL :D  this looks like the function used to measure characters is leaking over the image drawing. This is very very weird and could be  related from driver issue to window issue i do not know if it is a chrome issue.

I have no access to source code, nor the skill to interpret it completely.
I would GUESS, just GUESS that:

- if you use the PNG based dataurl it does not happen or happen very less.
- that train of A at the end of the jpeg is causing the mistake
- if you add the text to canvas outside the setSrc callback you are fixed.

is very unlikely i can fix anything here.

**Comment by adriaanmeuris** [comment]
Indeed, only JPG files cause the issue. Also, couldn't repro with smaller JPG's (this is 1300x1300).

Train of A-chars: hm, I'm also able to reproduce without using b64 - so not really sure if that's a cause as well.

Add text outside of setSrc: indeed, however I need to have other objects passed in only if the image is fully loaded. I might try wrapping it in a Promise and check if that helps.

About the source (measure chars), are we talking _initDimensions on fabric.Text?

**Comment by asturur** [comment]
no about chrome ctx.measureText function.
Anyway creating a null image and setSrc is weird logic.
Why you do not just load an image normally and then create the fabric Image with the new element?

**Comment by adriaanmeuris** [comment]
The image is provided via an API using custom request headers, so I'm retrieving a blob using XHR and then converting it to an ObjectURL so I can set the source using setSrc

**Comment by asturur** [comment]
it does not change. I was just suggesting to create a new imageElement every time new Image,
in the image.onload, create new fabric.Image(imageElement). without creating an empty one and reuse it.

Just will make the code simpler ( opinion )

**Comment by adriaanmeuris** [comment]
Agreed, updated the fiddle: https://jsfiddle.net/adriaanmeuris/4obL7240/3/
Issue still remains though
![screen shot 2017-01-18 at 17 35 45](https://cloud.githubusercontent.com/assets/16230038/22073067/95f81998-dda4-11e6-84ee-d18d15c4fe66.png)

**Comment by asturur** [comment]
No one will solve this issue if is microsoft related. I do not think is a fabric problem.
What you can do is create the text BEFORE the image load. Then add it to canvas just when the request is complete. If it does not complete you wasted the cpu power of creating the text element, that is little indeed.

I do not think i have other solutions. You should try to replicate the issue in javascript with no fabric and go over chromium issue tracker. I did for other bugs, sometimes with success, sometime wasting time.

**Comment by adriaanmeuris** [comment]
That's indeed what I'm afraid of :-)

So now I'm simply looking to circumvent the issue. I tried adding the text before the image in an updated Fiddle https://jsfiddle.net/adriaanmeuris/4obL7240/6/
But even then the issue still occurs. Any other ideas are greatly appreciated.

In the meanwhile i'll  try to isolate the issue in the source and if possible repro in a plain canvas

**Comment by adriaanmeuris** [comment]
Okay so I did some trial-and-error testing to find the root of the issue, and ruled out ctx.measureText as a cause.
I've made these steps:

**1. Cloned the fabric repo and build a distro with only text and interaction modules**
```
git clone https://github.com/kangax/fabric.js.git
cd fabric.js/
node build.js requirejs modules=text,interaction
```
**2. Open fabric.js and search for `.measureText`. I've found 3 occurences (in methods: fabric.Text._renderChars, fabric.Text._getWidthOfWords and fabric.Text._measureLine):**
```
width = ctx.measureText(char).width + additionalSpace;
var width = ctx.measureText(word).width, charCount, additionalSpace;
var line = this._textLines[lineIndex], width = ctx.measureText(line).width, additionalSpace = 0, charCount, finalWidth;
```

**3. Commented out these lines and replaced them with fixed values**
```
width = 10 + additionalSpace;
var width = 100, charCount, additionalSpace;
var line = this._textLines[lineIndex], width = 300, additionalSpace = 0, charCount, finalWidth;
```

I've ran the result and you'll see that the text dimensions are not correct due to the fixed values,
but the issue with the image still remains:
![screen shot 2017-01-18 at 19 47 19](https://cloud.githubusercontent.com/assets/16230038/22078050/03640de0-ddb7-11e6-98df-97da4ec644e4.png)

Anyone some guidance where to start looking?

**Comment by asturur** [comment]
replicate in plainJS.
That disposition of characters is made by some software.
May it be the fontManager that put them in some cache to retrieve them.
There is no code in fabric to put the code in that way is some sort of internal caching of some mechanism that is not our.
