### ISSUE TITLE
Object {selectable:false} should not change the cursor on hover

### ISSUE THREAD

**Issue by Rycochet** [kangax/fabric.js#3634]
## Version
1.7.3

## Test Case
https://jsfiddle.net/Rycochet/49ct1n6h/

## Steps to reproduce
Move the mouse over the rectangle (desktop only obviously).

## Expected Behavior
The cursor should not change as it's not an interactive element.

## Actual Behavior
The cursor changes to "all-scroll".

**Comment by tscislo-lingaro** [comment]
You reverted back #1392
