### ISSUE TITLE
Text caching should clear previous text 

### ISSUE THREAD

**Issue by jtweku** [kangax/fabric.js#3636]
## Version
1.7.3

## Test Case
http://fabricjs.com/kitchensink

## Steps to reproduce
* click on the text "foo bar baz"
* make the text italic
* click to make the text normal again
* there is artifact left outside the textbox bounding box 

## Expected Behavior
* there shouldn't be any artifact left

**Comment by LunevAndrey** [comment]
The same behavior when you change the font family (in particular "Plaster") of text. 
When you select the font family for the first time does not change the font.
