### ISSUE TITLE
can't remove all objects

### ISSUE THREAD

**Issue by MadSummer** [kangax/fabric.js#3638]
## Version
1.7.3

## Actual Behavior
i  defined a function liek this:
```
fabric.Canvas.prototype.removeAllObjects = function () {
    this.forEachObject(o => {
      o.remove()
    })
  };
```
but,this is not woking, the result is only some object has removed. i dont know why.

i know there is a 

 `clear()`

 function ,but this not fire 

> object:removed

 event . 
 thank you . fabric is a powerful library

**Comment by MadSummer** [comment]
finally, i tried this to solve the question,but i think there is a better way to do it .
```
fabric.Canvas.prototype.removeAllObjects = function () {
    let objects = this.getObjects();
    let bgi = this.backgroundImage;
    objects.forEach(o => {
      this.fire('object:removed', {
        target:o
      });
    });
    this.clear();
    this.setBackgroundImage(bgi, this.renderAll.bind(this))
  };
```

**Comment by asturur** [comment]
Te point is that forEachObject works on  the _objects array, and remove modify the array itself. This break loop.

You should just do canvas.getObjects().slice().forEach( .... );

the .slice or .slice(0) will create a copy of the array and you will iterate one array and modify the origianal.

**Comment by MadSummer** [comment]
@asturur thank you very much!
