### ISSUE TITLE
Rectangle on Canvas Looks Blurred.

### ISSUE THREAD

**Issue by edufelipe** [kangax/fabric.js#3639]
## Version
1.7.3

## Test Case
http://jsfiddle.net/ux7tsnqq/

## Steps to reproduce
Create a canvas, add a rectangle to it.

## Expected Behavior
The corners of the rectangle should end in a full pixel, making the rectangle look sharp.

## Actual Behavior
The corners of the rectangle end in a half-pixel, making it look blurred.

![screen shot 2017-01-20 at 1 51 19 pm](https://cloud.githubusercontent.com/assets/106633/22155789/e2cb2c6e-df17-11e6-834a-82524f9b8a26.png)

**Comment by asturur** [comment]
Well, there is a problem here, that is not really a problem or a  bug, i repetead it in various issues, but no one search the old ones or if he does, they are often opened with titles that do not resemble the problem.

The rect is 50 wide + 1 of stroke.
So is 51 wide.

This means that is 0.5 stroke, 50, 0.5 stroke horizontally and the same vertically.

This is not necessarly wrong is something you have to know and you have to live with it.

In the docs you can see that the rect as strokeWidth default at 1.
You either inizialize the rect with 0 strokeWidth or set 0 in the object.prototype and you should be fixed.
