### ISSUE TITLE
Setting selectable false should remove selection on calling renderAll

### ISSUE THREAD

**Issue by basilinjoe** [kangax/fabric.js#3642]
## Version
1.7.3

## Test Case
http://jsfiddle.net/basilin/Lr1x632n/3/

## Steps to reproduce

1. Create an object and add it to canvas
2. Set it as active object using `setActiveObject`
3. Make the object as nonselectable by setting property `selectable` as false
4. Call `canvas.renderAll()`

## Expected Behavior
Selection must be removed
## Actual Behavior
Selection persist

**Comment by asturur** [comment]
that is not true.
selectable will just stop your mouse interaction to set the object at selected. it does not modify anything on the object.

activeObject and selectable are 2 separate properties
