### ISSUE TITLE
IText cursor position is wrong for Indian languages in presence of diacritical marks

### ISSUE THREAD

**Issue by sunu** [kangax/fabric.js#3644]
## Version
1.7.3

## Test Case
https://jsfiddle.net/hhgmrmrn/

## Steps to reproduce
If [Devanagari](https://en.wikipedia.org/wiki/Devanagari) or similar Indian language text with [matra](https://en.wikipedia.org/wiki/Diacritic) is entered into a textbox, the cursor shifts to the right of the expected position with every matra.

**Comment by sunu** [comment]
The cause of this seems to be [this line](https://github.com/kangax/fabric.js/blob/9e37f9b3c10a6c2f5ea78072d2a15ac4c7c06d77/src/mixins/itext_behavior.mixin.js#L654). Instead of considering number of grapheme clusters, we are considering number of characters (which is higher than number of grapheme clusters in presence of diacritical marks)

**Comment by sunu** [comment]
If using an external library like [grapheme-splitter](https://github.com/orling/grapheme-splitter) to figure out number of grapheme clusters, is an acceptable solution to this issue, then I can put a PR together.

**Comment by ajck** [comment]
Seconded. Applies to any language using diacritics/combining marks (e.g. Arabic, and many others). Cursor is always in the wrong place as soon as the user enters any characters using diacritics. Be great to see this solved once and for all! Thanks.

**Comment by asturur** [comment]
If those character are in the multilanguage plane of UTF enconding, switching to .charAt(x) should be enough. something i m already doing.

**Comment by sunu** [comment]
Hi @asturur
I'm not sure I understand. `charAt()` doesn't help in counting number of grapheme clusters afaik. I have an example here.
```
> a = "मुखपृष्ठ"
"मुखपृष्ठ"
> a.charAt(0)
"म"
> a.charAt(1)
"ु"
```
`मु` is the first grapheme cluster here, not `म`.

**Comment by asturur** [comment]
i do not think i can go as far as grapheme with the text rework i m doing.
```javascript
function getWholeChar(str, i) {
  var code = str.charCodeAt(i);

  if (Number.isNaN(code)) {
    return ''; // Position not found
  }
  if (code < 0xD800 || code > 0xDFFF) {
    return str.charAt(i);
  }

  // High surrogate (could change last hex to 0xDB7F to treat high private
  // surrogates as single characters)
  if (0xD800 <= code && code <= 0xDBFF) {
    if (str.length <= (i + 1)) {
      throw 'High surrogate without following low surrogate';
    }
    var next = str.charCodeAt(i + 1);
      if (0xDC00 > next || next > 0xDFFF) {
        throw 'High surrogate without following low surrogate';
      }
      return str.charAt(i) + str.charAt(i + 1);
  }
  // Low surrogate (0xDC00 <= code && code <= 0xDFFF)
  if (i === 0) {
    throw 'Low surrogate without preceding high surrogate';
  }
  var prev = str.charCodeAt(i - 1);

  // (could change last hex to 0xDB7F to treat high private
  // surrogates as single characters)
  if (0xD800 > prev || prev > 0xDBFF) {
    throw 'Low surrogate without preceding high surrogate';
  }
  // We can pass over low surrogates now as the second component
  // in a pair which we have already processed
  return false;
}
```

i will for sure use this function to fix at least emoticons and some general more common use cases.
I have to do things in steps, text has so many problem now.

**Comment by ajck** [comment]
How about the method mentioned here: [https://mathiasbynens.be/notes/javascript-unicode#accounting-for-astral-symbols](https://mathiasbynens.be/notes/javascript-unicode#accounting-for-astral-symbols)
(section called "Accounting for astral symbols" if link doesn't work)

I think the countSymbols() function gives a quick easy way of getting correct string length, in terms of where to position the cursor? (this is the main problem I think).

**Comment by asturur** [comment]
please check #3680
