### ISSUE TITLE
Custom filter plugin works when adding filters to images, but fails to load the canvas via JSON

### ISSUE THREAD

**Issue by human-a** [kangax/fabric.js#3645]
## Version
1.7.3

## Test Case
http://jsfiddle.net/human_a/uhe70ju7/

## Steps to reproduce
Click on the green button to load a canvas via JSON (```const json2```) and then click on the blue button to add StackBlur to the image inside the project. You can see that the StackBlur filter works fine.

Now click on the red button, it tries to load the other JSON (```const json1```) which contains an image with StackBlur filter assigned to it. But this time it fails to load the project completely, no errors shown.

## Expected Behavior
If the StackBlur filter works when assigning it to the image, it should also work when loading a saved project via JSON.

## Actual Behavior
It fails to load a canvas if it contains any elements with StackBlur filter assigned to them.

## PS
I created this StackBlur filter plugin based on the following projects:
 https://gist.github.com/pierrickouw/2ab679159beee9d80ca6
 http://www.quasimondo.com/StackBlurForCanvas/StackBlurDemo.html

You can see my gist here:
https://gist.github.com/human-a/25b7f58565b89de4e999ef2f4de1982c

**Comment by asturur** [comment]
There are 2 mistakes in your custom filter:
1) the fromObject function does not has a paramter the object itself coming from the JSON file
2) the fromObject function does not have a callback a second parameter.

a standard function to restore filter is the one from baseFilter classe.

see updated fiddle.
http://jsfiddle.net/uhe70ju7/7/

**Comment by human-a** [comment]
Thank you very very much.

**Comment by asturur** [comment]
fabric should get soon its own blur. both with webgl and without and should be faster than stackblur from my simple tests

**Comment by human-a** [comment]
@asturur That is great news, especially the addition of WebGL which is something I am doing with a lot of dirty hacks in my project, but a native support for it would be fantastic, any ideas on the release date?

**Comment by asturur** [comment]
i m very busy with everything now.
The code can be checked here:
www.shutterstock.com/editor.

Enter in editor, load a picture, there are some basic filters for now ( brigthness, contrast, saturation and something else ) that are webgl by default.
If you disable webgl acceleration in chrome and reload the app you will see the plain javascript version. As soon as i have time to package that base code of filtering in the fabric i can release it since it has been decided to release for open source.

**Comment by wangyong991** [comment]
can i define a filter and the fragmentSource can accept three parameters?

**Comment by asturur** [comment]
yes you can. More than 3 parameters 3 uniform locations. there is a boilerplate empty filter to start
