### ISSUE TITLE
toDataURL custom font not loading on Microsoft Edge

### ISSUE THREAD

**Issue by arminbusatlic** [kangax/fabric.js#3646]
We have received many complaints by our users stating that their fonts are not loading, only to discover that all of those users are using the Microsoft Edge browser.

So we took a look into the issue and found that the toDataURL would not load the custom font correctly. Canvas itself loads the custom font and the object has it set correctly, but when doing toDataURL on Microsoft Edge, custom font will not load.

Is this a bug or are we doing something wrong here?

**Comment by arminbusatlic** [comment]
Resolved: The issue with Microsoft Edge and canvas was that if the canvas DOM didn't exist on the page, the font would not render. This is still considered a bug, but the workaround is to ensure to add the Canvas DOM to the page before calling toDataURL.

**Comment by asturur** [comment]
is this considered a  bug from microsoft?

if the canvas is in Dom with display none, does it work?

**Comment by asturur** [comment]
i need to verify this because i have an app that rely very much on custom fonts and render offscreen. i do not know of problems with edge.

**Comment by Clemweb** [comment]
Any news about this issue ?

@arminbusatlic my canvas is already in the DOM and I need to export font layer with toDataUrl() by an ajax call but it doesn't works on Edge only.

**Comment by asturur** [comment]
95% of those issues are fonts not loaded in the canvas.

**Comment by Clemweb** [comment]
@asturur what do you mean 'not loaded in the canvas' ? i use webfontloader lastest version.
Is there something to do more ?

Thanks

**Comment by asturur** [comment]
No maybe it is not loading properly. Custom fonts works with canvas elements.
Are you able to reproduce the issue in a fiddle that can be run in edge and reproduce the bug 100%?

**Comment by Clemweb** [comment]
Unbelievable https://jsfiddle.net/709k7abu/
It works on the fiddle, on my code nop.....
I don't understand why the process is the same.

**Comment by Clemweb** [comment]
@asturur what is the best solution for exporting a text in high resolution ?

**Comment by asturur** [comment]
There are 2 things to take in consideration:
1) disabled object caching when you are about to export text. WIll this save you from the max cache size
2) i did not get ( you see not presenting fiddles.... ) that the dataurl was text related. In that case it may be that the new canvas created for exporting has not the necessary font loaded for any reason. Of this i m not sure.

https://jsfiddle.net/709k7abu/1/

look my fiddle in chrome, to me looks pretty good export.

**Comment by Clemweb** [comment]
OK but your fiddle doesn't work in Edge....

**Comment by Clemweb** [comment]
Is a Edge bug ?

**Comment by asturur** [comment]
maybe i exagerated with thr 30x multiplier.
i ll try on my windows machine.

**Comment by Clemweb** [comment]
It is not the multiplier, in my Fiddle it is working because the toDatURL take cache preview to generate file.
But when we disable caching the font is not loading. Only on Edge.
I think it's a bug...

**Comment by asturur** [comment]
maybe yes, but from edge. Why it should load the font again is a mistery to me.

**Comment by Clemweb** [comment]
Yep same thing on IE11
