### ISSUE TITLE
Rectangle stroke set to black renders as gray

### ISSUE THREAD

**Issue by delian7** [kangax/fabric.js#3648]
## Version
1.7.3

## Test Case
http://jsfiddle.net/Da7SP/449/

## Steps to reproduce
1. Hold down mouse and drag to create a rectangle. 

## Expected Behavior
1. Setting the stroke to 'black' should render a black stroke not a gray one. 

## Actual Behavior
When stroke is set to black the rendered stroke is gray at `strokeWidth: 1`. 
![screen shot 2017-01-25 at 12 20 39 pm](https://cloud.githubusercontent.com/assets/4530694/22307788/49a6b982-e2f9-11e6-8b32-fe8a3200175c.png)

**Comment by asturur** [comment]
as in isse #3639 the stroke is across 2 pixels. I cannot do anything about that
What version of fabric was rendering it good?

**Comment by delian7** [comment]
1.7.1 had the stroke color as black but rendered inconsistently. See http://jsfiddle.net/Da7SP/450/
![screen shot 2017-01-25 at 1 55 50 pm](https://cloud.githubusercontent.com/assets/4530694/22310951/0871c56c-e306-11e6-876c-f5bbe263c864.png)

**Comment by asturur** [comment]
i guess with strokewidth of 2 is black.

Even if i wanted to take in consideration the idea of using a different approach for the rect / object size, i could divide between odd and even pixels but there are an infinity of other dimiensions with decimal pixels that would not be fixed.

Borders drawn across pixels are fuzzy and black becomes grey, red pink, and so on.
I cannot do that much, you should use a strokeWidth of 2 or odd dimensions and odd stroke.

**Comment by asturur** [comment]
you can try to disable object caching and see if it helps.

**Comment by delian7** [comment]
`objectCaching: false` didn't help. what's weird is that I have a circle tool, triangle tool, and a line tool that don't behave like this but the rectangle tool does.

**Comment by asturur** [comment]
being on a retina screen i m not able to reproduce.
incrementing the stroke to 2 does solve?

**Comment by asturur** [comment]
if you want to work with stroke 1 and straight lines, use an offset of 0.5 pixel and it will look better.

http://jsfiddle.net/Da7SP/452/
