### ISSUE TITLE
Kindly check your VIDEO sample

### ISSUE THREAD

**Issue by AUSdomgarcia** [kangax/fabric.js#3649]
## Version
Using latest version

## Test
(http://fabricjs.com/video-element)[Not working]

**Comment by asturur** [comment]
![devbuild](https://cloud.githubusercontent.com/assets/1194048/22330131/ebda01f2-e3c4-11e6-9f0e-fd770c209ad3.gif)

**Comment by AUSdomgarcia** [comment]
thanks sir :D
