### ISSUE TITLE
Filters don't apply after load canvas from JSON

### ISSUE THREAD

**Issue by xxorax** [kangax/fabric.js#365]
When you save and load the canvas in JSON, the filters on the objects don't be apply until you call an async renderAll on the canvas, by refreshing it with canvas.renderAll() or by clicking inside the canvas.

See an exemple :
http://www.xorax.info/labs/misc/canvas/fabricjs-issue-loadAndFilter.php

Apply the greyscale filter, click save to save the JSON in the input, and
- click to Load button to load the JSON in the input and click on the canvas to refresh it
- or click to Load and refresh button to load and call Load and refresh after 500ms

It seems there is an async break somewhere.

**Comment by asturur** [comment]
i think that from some recent changes the applyfilter works good when restoring from object.
What is the point?

load image , apply filter, then load back with a save/restore json?
if this work can we close?

**Comment by jitendrapawar** [comment]
How to apply resize filters(lanczos etc...)?

**Comment by asturur** [comment]
https://github.com/kangax/fabric.js/pull/3210

I made this:
The callback of loadFromObject that we uses to trigger the "objectLoaded" event and then count all the object restored, is passed down to applyfilters and called from there.
At this point the object will take longer to restore ( add filter rendering time ) but that should solve the callback issue.
