### ISSUE TITLE
how to set the height correctly?

### ISSUE THREAD

**Issue by StekolschikovV** [kangax/fabric.js#3650]
I use fabris.js factories to work with objects canvas. If you change the height of a separate mouse or separate field - it works. If you change the mouse first, then field - to work with well-read false values.

[Full code](http://jsfiddle.net/millerish/fb7y8sfs/2/)
[A bug in the video.](https://www.youtube.com/watch?v=L0d202oDNVw&feature=youtu.be)

Line 83, 84. Setting values:

```
canvas.getActiveObject().setHeight(parseInt(heightElInput.value));
canvas.getActiveObject().height = parseInt(heightElInput.value)
```

Please help to fix.

**Comment by asturur** [comment]
Please make a shorter fiddle. Is not clear what are you asking for, on top of that i do not understand russian.

Consider this issue tracker is not made for help, so if you need help try to be as concise and as efficent as possible.
