### ISSUE TITLE
Export ToSVG does not include font family

### ISSUE THREAD

**Issue by LunevAndrey** [kangax/fabric.js#3653]
## Version
1.7.3

## Test Case
http://fabricjs.com/kitchensink

## Steps to reproduce

Set IText active. Change font-family at "Plaster". Rasterize canvas to SVG.

## Expected Behavior
Font-Family should be "Plaster" and text don't change

## Actual Behavior
font-family "Plaster" changes on a default font-family

**Comment by asturur** [comment]
So there is a property you have to manually fill up if you want your svg to be filled up with  fontFace definitions. 
I do not have a documentation for it, you should check in merged PRs there is something

**Comment by asturur** [comment]
https://github.com/kangax/fabric.js/pull/2797

here it is.

**Comment by LunevAndrey** [comment]
Thank for is
