### ISSUE TITLE
Error on move / resize objects on touchscreen

### ISSUE THREAD

**Issue by mbaudry** [kangax/fabric.js#3654]
## Version
1.7.3

## Test Case
http://fabricjs.com/kitchensink

## Steps to reproduce
Put your browser in touchscreen mode (like ipad) if you want to test this very simply. If you move objects on the canvas, you can see this error:

![capture du 2017-01-27 14-44-26](https://cloud.githubusercontent.com/assets/15127641/22372944/cc12d41c-e49f-11e6-9400-7364bc42b095.png)

And when I try to resize my object, the browsers is down...

Thanks for your help !

**Comment by asturur** [comment]
is a chrome 56 breaking change.
Is addressed in current build, you have to wait next release.
