### ISSUE TITLE
strokeDashArray not working with webfonts?

### ISSUE THREAD

**Issue by ajck** [kangax/fabric.js#3655]
## Version
1.7.3

## Test Case
https://jsfiddle.net/765doq2b/12/

## Steps to reproduce
Run the fiddle linked above to try default Arial font. Also select either Google web font from the drop down menu.

## Expected Behavior
ITexts (and TextBox) with a strokeDashArray property should render their fonts with dashes as per the example near the bottom of this page: http://fabricjs.com/test/svg_export/stroke.html

## Actual Behavior
Both the default font in the fiddle (Arial), and the two Google Webfonts you can select from the dropdown menu, render without any dashes. If you open the developer console in your browser you can see that the stokeDashArray property is indeed applied to the IText

Tested on Windows 7 with Google Chrome 55, IE 11, Opera 42, Firefox 50.1

**Comment by asturur** [comment]
https://jsfiddle.net/765doq2b/13/

![image](https://cloud.githubusercontent.com/assets/1194048/22397893/221f6f50-e57c-11e6-9a87-8c176d58b027.png)
