### ISSUE TITLE
How to get the area?

### ISSUE THREAD

**Issue by StekolschikovV** [kangax/fabric.js#3658]
Hello,

I need to know the area of all elements of the group. Is there a ready-made solution? Perhaps you know the area excluding the imposition?

```
window.canvas = new fabric.Canvas('fabriccanvas');

var circle1 = new fabric.Circle({
  radius: 50,
  fill: 'red',
  left: 0
});
var Rect = new fabric.Rect({
 	left: 50,
  top: 50,
  height: 20,
  width: 20,
  fill: 'green'
});
var circle2 = new fabric.Circle({
  radius: 20,
  fill: 'black',
  left: 70,
  top: 80
});
var group = new fabric.Group([ circle1, circle2, Rect ], {});
window.canvas.add(group);
```

**Comment by ncou** [comment]
Hi,

Look at the function "getBoundingRect" in the group documentation : http://fabricjs.com/docs/fabric.Group.html

@asturur : by the way, the "boundingrect" demo is not working if you select a group of objects.

**Comment by asturur** [comment]
no there is not a function. you can build a calcArea for every object, but still you have to figure out the overlapping parts.
