### ISSUE TITLE
Can't delete text after marking all

### ISSUE THREAD

**Issue by MichaelJDK** [kangax/fabric.js#3661]
## Version
1.7.3

## Test Case
https://jsfiddle.net/noeytn5x/

## Steps to reproduce
Mark all the text inside the textfield and click the delete key (or any key really)

## Expected Behavior
The text is deleted

## Actual Behavior
Nothing happens

It however works fine if I mark all by double-clicking

**Comment by asturur** [comment]
i cannot replicate.
I have no delete button just the backspace since i m on a mac.
Can you replicate with backspace?
Can you replicate building the latest version on github? ( needs building the lib )

**Comment by mbaudry** [comment]
I have the same issue. You can reproduce it if you try to delete the text in two steps. First select a part of the text, then click on delete key. Then, select the last remaining part, and try to delete it. It does not work.

**Comment by asturur** [comment]
Delete on PC or MAC?

**Comment by mbaudry** [comment]
Delete PC. On Mac it works well

**Comment by entonbiba** [comment]
@asturur @mbaudry yea it lost focus once the delete button is clicked in the text and dragging to the end of the text. 

This might be causing the issue
````
setSelectionStart: function(index) {
      index = Math.max(index, 0);
      this._updateAndFire('selectionStart', index);
    },

setSelectionEnd: function(index) {
      index = Math.min(index, this.text.length);
      this._updateAndFire('selectionEnd', index);
    },
````

**Comment by asturur** [comment]
still i cannot understand.
Can we have some more detail on reproduce? i cannot reproduce on windows neither.
OS, browser, key pressed

If we manage to replicate it by code is even better

**Comment by entonbiba** [comment]
@asturur selecting the full text and pressing delete doesn't remove it. 
https://jsfiddle.net/noeytn5x/

This works:
![image](https://cloud.githubusercontent.com/assets/5193884/22550749/87acc754-e91f-11e6-985f-5b4a877a6f1d.png)

This doesn't: 
![image](https://cloud.githubusercontent.com/assets/5193884/22550770/a6f89f34-e91f-11e6-8405-0bd4f1ee2d9c.png)

**Comment by MichaelJDK** [comment]
For the record, backspace also doesn't delete the text.

**Comment by asturur** [comment]
i tried on macos vmware with windows 10. i cannot replicate.
Which browser anyway?

**Comment by mbaudry** [comment]
I have the same problem on ubuntu 10.04 - Chrome 56

**Comment by entonbiba** [comment]
@asturur it happens on all browsers as long as you select the text using mouse. The only thing that can cause the issue is the `selectionEnd`. There is also this closed issue with the same problem #1402

````
setSelectionStart: function(index) {
      index = Math.max(index, 0);
      this._updateAndFire('selectionStart', index);
    },

setSelectionEnd: function(index) {
      index = Math.min(index, this.text.length);
      this._updateAndFire('selectionEnd', index);
    },
````

**Comment by asturur** [comment]
at time of issue number 1402 fabric was pretting different. i ll try again to replicate again. i have no luck.

**Comment by entonbiba** [comment]
@asturur I'll record a gif today

**Comment by asturur** [comment]
is not about gif, it does not mean i do not trust you.
i need a way to replicate it or i do not know what to fix

**Comment by entonbiba** [comment]
@asturur ok do the following

1) click at the start of the text with your mouse
![image](https://cloud.githubusercontent.com/assets/5193884/22952885/c9040d36-f2dc-11e6-8127-8f102f76a448.png)

2) click and drag from the start to the end of the text and a bit outside it, now let go of the mouse click
![image](https://cloud.githubusercontent.com/assets/5193884/22952924/f38052fe-f2dc-11e6-9a12-b6a65f871c90.png)

3) press delete or backspace on your keyboard
Nothing should happen since you have left the textbox input range or the selected text.

**Comment by ncou** [comment]
Hi,

@entonbiba i can't reproduce it with your steps (win7+chrome 56.0.2924.87).

But if i click at the end of the end of the text (red dot), and select all the text i can reproduce it.

1. double click on the red dot
2.Press left button and select ALL the text
3.Press DEL or SUPR button and the text is still remaining.

![image](https://cloud.githubusercontent.com/assets/16743322/22974297/fa0d28fe-f381-11e6-8b82-c0e47f5659e8.png)

Hope it's help.

**Comment by asturur** [comment]
when you say press left button you mean mouse or keyboard?

**Comment by ncou** [comment]
Sorry, for (2.) it's press the mouse left button (selection button).
I will edit my msg

**Comment by ncou** [comment]
Hum, erratum, in fact it seems like when i select the text and release my selection with the cursor near the border of the jsfiddle, the itext component lose the focus and the delete press button doesn't work.

If i deselect the text in the same iframe all is working fine.

**Comment by asturur** [comment]
you may have centered the problem. that would be great
