### ISSUE TITLE
dont fire 'mouse:up' after touchcancel

### ISSUE THREAD

**Issue by Rad1calDreamer** [kangax/fabric.js#3663]
Hi, i detect it on IPAD. In my app i draw object (rect\line\path) by 'mouse:move' and if i open Control Center on IPad (swipe from down to up on border of screen) 
![cccontrols-ipad](https://cloud.githubusercontent.com/assets/7055577/22539011/c2af9df6-e927-11e6-93fc-ec7791530026.jpg)
fabric fired 'mouse:move', but dont fire 'mouse:up'. For fix i add touchcancel on canvas.container and fire in it 'mouse:up'

**Comment by asturur** [comment]
thanks for info. Can you post some actual code to be more clear?
i guess i can figure it out, but if you help is better.

**Comment by Rad1calDreamer** [comment]
no problem, but i don't know how it can help =)
this  - my 'editor' objects.
this.canvas - fabricjs canvas


`this._touchCancelHandler = function(){ 
   this.canvas && this.canvas.fire('mouse:up')
};
window.addEventListener('touchcancel', this._touchCancelHandler);
`

**Comment by asturur** [comment]
to be handled in #3869
