### ISSUE TITLE
exitEditing from text should clear the caret

### ISSUE THREAD

**Issue by mbaudry** [kangax/fabric.js#3666]
## Version
1.7.3

## Test Case

https://jsfiddle.net/noeytn5x/7/

## Steps to reproduce

Double click on the text box to show the caret. Then, click on the "deactivate all" Button

## Expected Behavior

the caret must disappear.

## Actual Behavior

the caret is still present

**Comment by asturur** [comment]
i see the upper part does not get cleared.
Well deactivateAll should just deactivate. i will change the title in `exitEditing from text should clear the caret`

**Comment by asturur** [comment]
while i search if we need a proper fix, you can still call


canvas.getActiveObject().exitEditing(); before calling deactivateAll, of course you have to check that the activeObject isEditing before.

**Comment by mbaudry** [comment]
ok, thanks !
