### ISSUE TITLE
Zooming in causes objects to "drift"

### ISSUE THREAD

**Issue by Lee-Taylor** [kangax/fabric.js#3668]
I have a simple demo in two varieties. The first one uses version fabricJS 1.4.13, the second uses the latest (1.7.3).

There is a black rectangle positioned at (0, 0).

I have created a StackOverflow question, the demos are runnable there.

http://stackoverflow.com/questions/41993805/zoom-issue-with-latest-version-of-library

When zooming in on the 1.4.13 version this works fine, when zooming in on the 1.7.3 you will notice that the black square starts to drift. You can see this as the background colour starts to show through on the left and the top.

The error gets progressively worse the more you zoom in.

I'm not sure which version of the library first exhibited this behaviour. I can research this if necessary.

Any ideas?

**Comment by asturur** [comment]
I answered you there.
Thanks for opening first there and for a detailed, clear snippet.

**Comment by Lee-Taylor** [comment]
Many thanks to you!

Has been driving me crazy. Only found out that it was a difference in library versions after trying everything else!

I would still see this as a bug/oddity as, per the instructions in http://fabricjs.com/fabric-intro-part-1#objects

(the part about Default options)

Even with using the latest version of fabric, calling:

rect.getStroke(); // null

still returns null.

Also, the property "strokeWidth" of the rect seems to be tucked away so it's not obvious when you debug in developer tools. 

Perhaps the tutorial needs updating? Thoughts?

**Comment by asturur** [comment]
Well stroke is null. if we write `transparent` i think the canvas renders it and is a waste.

So the page requires an update, i do not have so much time.

strokeWidth you do not see it because is in the prototype, so you miss it.

I should update it, i just do not have time.
