### ISSUE TITLE
IText kerning broken when styling different characters

### ISSUE THREAD

**Issue by svenraju** [kangax/fabric.js#3669]
Hello, 

it seems that IText can't handle font kerning when styling separate characters. 

Here is an example
without styles: http://cloud.aku.co/j0Q9
with styles: http://cloud.aku.co/j0kH

is there any solution for this?

thanks

**Comment by asturur** [comment]
Hello.
Can i ask you to point me to a software that can handle that? any. It has not be be web based.

**Comment by svenraju** [comment]
I only need to change the color of characters in the middle of the string. And IText seems to be the only thing that can handle that, which is nice! But the kerning goes off

Sketch and CSS can both handle this, if thats what you asked.

**Comment by asturur** [comment]
i m going to check Sketch.

**Comment by svenraju** [comment]
https://jsfiddle.net/r55zjynq/
Made the fiddle aswell

**Comment by asturur** [comment]
a solution is in the work to rewrite text and enable also this.
It will take time, no eta.
Different ideas comes and go and i have no plan yet. 
i will open a general issue to take care of them all
