### ISSUE TITLE
How to create 360 degree spinner 

### ISSUE THREAD

**Issue by pranavcp** [kangax/fabric.js#3670]
Hi Kagnax,
I was reviewing your website and tool also.
Will you please guide what tools you have used to implement to make this 360 degree spinner?

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
