### ISSUE TITLE
Animate multiple properties

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3674]
Hi,

In the doc there is a possibility to animate multiple properties if you use an object. And the values are also an object.

For example if i want to animate opacity value and left value.
This doesn't seems to work :
I made a quick fiddle using an array with the properties.

https://jsfiddle.net/11ouLgkj/29/

In the fabric code, if the arg[s0] is an object it loop on the array, but it it seems to use args[1] for the value, no iteration.

Is that a bug ? a problem in the fiddle ? in the doc ? 

Thank you.

**Comment by asturur** [comment]
https://jsfiddle.net/11ouLgkj/30/

i think is supposed to be used like that.
Can you point me to the tutorial or jsdoc that is confusing?

**Comment by ncou** [comment]
Thank you, i have tried a few combinations but without succes, i suppose i was also feeding the "value" param.

A)
There is the jsdoc for the Object animate propertie, the "value" parameter is not indicated as optional it's written : "Value to animate ... or options object" with a type of "string or object".

B)
And in the doc (http://fabricjs.com/fabric-intro-part-2#animation) there is no reference of the use of objects, only examples with string to animate one propertie.

C)
I think an update for the demo on the fabric.js site to demonstrate the use of multiple properties animation could be usefull for the users.

Have a good day. I close the ticket but i will check if you do an answer.
