### ISSUE TITLE
JSON.stringify() incomplete after extending object with properties 

### ISSUE THREAD

**Issue by awehring** [kangax/fabric.js#3677]
This issue is with Version 1.7.3, in Version 1.6.3 it works flawless.

I'm extendig the fabric.Object prototype with new, application specific properties. I use the technique proposed by kangax here: http://stackoverflow.com/questions/19444196/in-fabric-js-how-do-i-modify-the-object-class-so-all-sub-classes-will-have-a-new

With the current version the result from `JSON.stringify()` and `canvas.toObject()` is incomplete. E.g. with a circle the "radius", "startAngle", "endAngle"  properties are missing.

´loadFromJSON()´ fails afterwards more or less.

## Version
1.7.3

## Test Case
http://jsfiddle.net/awehring/Da7SP/468/

## Steps to reproduce
1. Run the jsfiddle.
2. Inspect the console.log output, which shows `JSON.stringify()`, `canvas.toObject()`, and `stateProperties` of the circle.

## Expected Behavior
The result from `JSON.stringify()` and `canvas.toObject()` should contain the properties "radius", "startAngle", "endAngle", as well as the additional property "temp_id".

## Actual Behavior
 "radius", "startAngle", "endAngle" are missing, the additional property "temp_id" is here.

If you load the string back with ´loadFromJSON()´, a circle is created, but stays invisible, because it has radius=0;

## Earlier Version 1.6.3 works correct
With Version 1.6.3 the result from `JSON.stringify()` and `canvas.toObject()` it correct. Even when "temp_id" is not added to the stateProperties array (as suggested by kangax in the stackoverflow-link).
The idea to add new properties to stateProperties is from the Tutorial Part 3, just at the end of Serialization.

**Comment by ncou** [comment]
Hi,

Here is a working fiddle :
http://jsfiddle.net/Da7SP/469/

You need to pass an array to the "toJSON()" function to keep your custom attributes.

**Comment by asturur** [comment]
the point is that radius, startAngle and endAngle are not custom.

**Comment by asturur** [comment]
ok i sew fiddle now. you substituted the original toObject function with a custom one and you broke it.

The original function is able to keep tempid, please consult docs

www.fabricjs.com/docs

**Comment by awehring** [comment]
Thank you for the hint, now it works.   :-)
