### ISSUE TITLE
IText font of a group alternates fuzzy or crisp when setting the group's location.

### ISSUE THREAD

**Issue by wangxianzhe015** [kangax/fabric.js#3678]
## Version
1.7.1

## Test Case
https://jsfiddle.net/Miron/24ph9o5x/

## Stackoverflow Question
http://stackoverflow.com/questions/42095045/fabric-js-itext-font-fuzzy-according-to-position

## Expected Behavior
All fonts are expected to be as crisp as possible whether its group's location.

## Actual Behavior
When calling group's set() function to set left and top properties, font becomes crisp or fuzzy, not sure why.

**Comment by asturur** [comment]
can we make a fiddle demo with the same  fonts without all the exagon or moving steps?
keep it minimal or i will never find time to watch it.

**Comment by wangxianzhe015** [comment]
I tried to do so, but it's the minimal, I think. Point is that the text becomes fuzzy or crisp, when the text is in group. Consider the left and top properties, if they are not met a condition, text becomes fuzzy, doesn't it?

**Comment by ncou** [comment]
Hi,

There is problem between Chrome and firefox.

On the left FF, on the right it's Chrome.
![image](https://cloud.githubusercontent.com/assets/16743322/22764277/eeabbce0-ee69-11e6-97fd-c44a798c0e27.png)

It's probably a subpixel issue, you are using some round numbers for the top values ("Math.sqrt(3) * radius / 2").

I have add a round for the values, the result it's better, but in the jsfiddle i updated the library to v1.7.3 to totaly fix you problem (i think asturur fixed something like an antialising problem in this version cf changelog "Fix: add 2 extra pixels to cache canvases to avoid aliasing cut").

Here is a working fiddle. Close your ticket if it's ok, and post the answer on stackoverflow, i don't have an accound on this site.
https://jsfiddle.net/24ph9o5x/4/

**Comment by wangxianzhe015** [comment]
@ncou , thanks for your advice.
But it doesn't work even with version1.7.3.
I will try to fix the location as you said as just integer numbers. Actuallly, as you can see, origin properties are center, so the left or top might be infinite values.
Thanks.

**Comment by asturur** [comment]
i cannot test the fuzzyness on the macbook because of retina everything is crisp.

**Comment by asturur** [comment]
i m trying to help on SO since this is a particular app case and we have other 188 issues here to look at

**Comment by ncou** [comment]
Not really sure i can help because i can't reproduce it with my latest jsfiddle.
Perhaps try to disable the cache object with the code :

fabric.Object.prototype.set({
  objectCaching: false
});

I will try on other browsers and set an answer on Stackoverflow if i made some progress.

**Comment by ncou** [comment]
I think disable the cache could help. I could reproduce something near your issue :

![image](https://cloud.githubusercontent.com/assets/16743322/22826376/6b95e5f4-ef92-11e6-8814-2b06ec72e73f.png)

If i made a group throw selection, the text became crisppy.
If i disable caching on the IText object the text is always crispy (with or without selection).

**Comment by wangxianzhe015** [comment]
Thanks, @ncou 
It solved the problem to disable cache object. Could you explain me how it can solve the problem?

**Comment by asturur** [comment]
did you check your stack  overflow question? there is a full explanation there.
