### ISSUE TITLE
setOpacity for group objects is maxed at the original opacity of the objects in the group.. not to the full 0-1 range. 

### ISSUE THREAD

**Issue by monkeytroy** [kangax/fabric.js#3679]
## Version
1.7.3

## Test Case
http://jsfiddle.net/e7frnkta/

## Steps to reproduce
Create a group with a starting opacity less than 1.  For this example set to 0.5.
Opacity of the group is now maxed at that original opacity of 0.5.  
Select the object and try to change the opacity.
Using canvas.getActiveObject().setOpacity(1) then renderAll on canvas. 
The opacity of the selected object/group are only set to the original opacity or 0.5

The fiddle I created creates one group of two rectangles with an opacity of 0.5, a second group with an opacity of 1 and a single rectangle with an opacity of 0.5

On mouse down the selected active object's opacity is set to 0.25 and on mouse up it is set back to 1.  

The left group will set to 0.25 but when it is set to 1 it only actually goes back to 0.5.

The 2nd group starts at 1.. so it correctly goes to 0.25 and then back to 1. 

The single rectangle starts at 0.5... is set to 0.25 correctly and then goes to 1 correctly. 

## Expected Behavior
Setting the opacity to 1 for a group object sets all the objects opacity to 1. 

## Actual Behavior
Setting the opacity to 1 for a group object leaves the opacity set to the original opacity when created.

**Comment by asturur** [comment]
opacity of group gets multiplicated by the opacity of objects.
it has to be like that.

**Comment by monkeytroy** [comment]
For rendering I can see that.. but when I set the group and the objects in the group to opacity 1... they should all be opaque and they are not.  Seems like a bug.

**Comment by monkeytroy** [comment]
Cause.. 1*1=1

**Comment by morrowsend** [comment]
I am having the same issue with a freedrawing with a shadow. Yes, 1*1=1, but I can't go over that. If something was originally 50% opacity, I can't make it dark again by setting opacity = 2. It never goes beyond 100% of the 50%. any suggestions?

**Comment by asturur** [comment]
there is 2 way to have opacity. One is an opaque color, and another is the opacity of the object.
One cannot compensate the other.
