### ISSUE TITLE
Pressing right alt + a on Windows selects whole text instead of making custom letter, like ą

### ISSUE THREAD

**Issue by rlach** [kangax/fabric.js#3681]
The bug happens on Polish(Programmers) and English settings, reproduced on multiple windows machines with different settings. It doesn't happen on Japanese IME. On Linux and Mac pressing right alt + a produces custom letter(like á on Enlish(United Kingdom).

Tested on newest Firefox, Chrome, Edge and Safari on macs. The behavior is consistent trough browsers depending on OS.

I debugged the code a bit and it seems for some reason on windows right alt is interpreted both as ctrl and alt at the same time, which means ctrl+a(select all) keyboard shortcut triggers.

## Version
1.7.3

## Test Case
http://jsfiddle.net/Da7SP/479/ 

## Steps to reproduce
Click twice on iText to enter edit mode, press right alt + a.

## Expected Behavior
depending on keyboard settings á or ą or another symbol appears

## Actual Behavior
Whole text gets selected. When user tries to enter longer sentence containing this letter he usually ends up deleting his whole text with next keypress.

**Comment by asturur** [comment]
i link this issue to the text refactor.
I will close it, and keep a reference there.
I have stopped doing small fixes to itext for a rewrite.

Are you aware if there are selection events on the textarea?

**Comment by asturur** [comment]
#3680

**Comment by rlach** [comment]
I catch 'text:selection:changed' since I need to update interface when it happens. But I'm not sure how that could help with the issue. Could I use the event to ignore ctrl+a somehow?

**Comment by rlach** [comment]
For the time being I just run this after fabric.js is loaded:
```
function () {
    fabric.util.object.extend(fabric.IText.prototype, {
      onKeyDown: function (e) {
        if (!this.isEditing) {
          return;
        }
        if (e.keyCode in this._keysMap) {
          this[this._keysMap[e.keyCode]](e);
        }
        else if ((e.keyCode in this._ctrlKeysMapDown) && ((e.ctrlKey || e.metaKey) && !e.altKey)) {
          this[this._ctrlKeysMapDown[e.keyCode]](e);
        }
        else {
          return;
        }
        e.stopImmediatePropagation();
        e.preventDefault();
        if (e.keyCode >= 33 && e.keyCode <= 40) {
          // if i press an arrow key just update selection
          this.clearContextTop();
          this.renderCursorOrSelection();
        }
        else {
          this.canvas && this.canvas.renderAll();
        }
      }
    });
  }
```

Basically I just added changed (e.ctrlKey || e.metaKey) to (e.ctrlKey || e.metaKey) && !e.altKey). Doesn't seem to break anything. Once text rewrite is complete I'll just remove this.
