### ISSUE TITLE
IText bug in (de)selection if cursor at the end of line

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3682]
Hi,

There is a bug in the selection.

Steps :
Go to
http://fabricjs.com/test/misc/itext.html

Edit text with a dblclick => put the cursor at the end of a word or at the end of the sentence.

Press mousse down to select the text.
* move the mose on the left the text is selected with a blue overlay.
* without releasing the mouse press, now move the mouse on the right to deselect what you have selected.

=> There a bug, the last character is not deselected.

**Comment by asturur** [comment]
i made some effort to normalize the cursor behaviour like google doc. maybe i broke something. i hope is a quick fix.

**Comment by asturur** [comment]
is already fixed in latest master, verified.
