### ISSUE TITLE
event "deselected" on object is not fired if you change selection

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3685]
Hi,

The "deselected" object is not fired if you change the active object for another one.
It seems from the source code, the event "deselected" is fired, in the same situation as when the event "selection:cleared" is fired.

So the event "deselected" is fired when i click in the background of the canvas (equal destroying the selection), so it's OK.
But if i select another object, the event "deselected" from the previous activeObject is not fired.

Is that normal ? or a bug ? shouldn't we have in the function setActiveObject() a test so check if the new activeobject if different from the old activeobject (using this._activeObject) and then fire the "deselected" event if it's not the same object ?

Thank you for your insights.

**Comment by asturur** [comment]
the deselected event is quite new.

it should fire when an objects get deselected, that is more often than when
a selection is destroyed.

why i did not do it immediately i do not remember.

**Comment by ncou** [comment]
yes the event is quite new, and very usefull :) strange it's not fired more often in the source code. I hope this return could help and improve this event.

Have a good day.

**Comment by ncou** [comment]
Whaouu great efficiency. Thank you.
