### ISSUE TITLE
subTargetCheck doesn't work if group if "selectable"

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3686]
Hi,

I want to detect the object clicked, even if the object is in a group.

I use the "subTargetCheck" propertie and it work like a charm if my group is "selectable=false", if set it to selectable=true. it always return me the first clicked object and seems to be locked on this value.

Here is the codepen, i show in the console the color of the clicked rect object.
But if you change the value "selectable=true" line 20, you got the rect value on the first click, after you need to deselect the shape and click on the other rect to get the value.

http://codepen.io/anon/pen/zNyYEE

Is this normal ? an i clear enough ?
Thank you for your help.

PS : I was thinking the findtarget() with the skipGroup paramter could do the samething but i always got the object "group" as finded target. Am i a bit lost on the use of this method, can you enlighten me ?
Thank you.

**Comment by asturur** [comment]
skipgroup is for internal use. is used only for activegroup selection to return the objects inside.

i should specify in the docs that is not meant for dev use, at least you cannot do something really useful from it.

**Comment by asturur** [comment]
subTargetCheck should work, no idea what is the problem

**Comment by asturur** [comment]
ok, fabric uses a shortcut to return earlier in case of activeObject click.
So you gain some bullshit improvement in speed and we loose a feature.
I guess i'm fixing this.
