### ISSUE TITLE
Re-instantiating multiple times causes Safari to Crash on iOS

### ISSUE THREAD

**Issue by homerlex** [kangax/fabric.js#3693]
We have a react app using fabricjs that crashes Safari if the fabricCanvas object is instantiated too many times (appears to be a memory issue).  The jsfiddle mentioned below is plain vanilla javascript that simulates what happens in our app over time.  You will notice that in Safari on OSX is doesn't fail.  Also in Chrome on Windows its fine.

I was under the impression that the dispose() method would clean things up but it doesn't do any good in this situation.

## Version
1.7.4

## Test Case
http://jsfiddle.net/vcubzdgo/1/

## Steps to reproduce
Run the above fiddle in Safari on an iPad (I'm on 10.2) and it "crashes"

## Expected Behavior
No Crash

## Actual Behavior
Crashes  in Safari on an iPad

**Comment by asturur** [comment]
Start to make the code simpler.

http://jsfiddle.net/vcubzdgo/2/

ipad is a very limited memory device and you are resetting canvas sizes lot of times, this create memory allocation that needs to get garbaged.

Other than that disable retina scaling in case. a 2000x2000 canvas is 4000x4000 on an ipad at least, and is 64Megs of memory just one canvas. then you have an upper canvas that gets created every time you initialize the canvas that is another 16megs.

How much ram an ipad has? how fast the garbage collector is?

You should not initialize an app 100 times...

**Comment by homerlex** [comment]
I'm using an iPad Pro with 2GB memory.  Obviously my fiddle shows an extreme case to cause the issue quickly.  In our actual app it takes more time to get to the point of crashing.  It seems that garbage collection never happens.

Is it recommended that instead of reinstantiating the fabricCanvas object I simply keep the same instance for the life of the app?

**Comment by asturur** [comment]
in your demo example everything runs on the main thread with no pauses.
so GC cannot kick in. ( i can be wrong )

what is your app doing and why it requires the canvas to reinitialize so much?

the canvas element at some point has to allocate memory for pixels. i suppose it does it when you set width and height or when you getContext(), all things that fabric do twice at every new Canvas.

a reference to a disposed canvas element can survive in a fabric.Object reference that is handled differently, but just one, not all of them.

also there are limits on the canvas elements for apple mobile devices, with 2000x2000 and retina scaling you are near i guess.

**Comment by asturur** [comment]
http://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element

please follow the links to apple resources and check before what apple says about ipad pro.

**Comment by homerlex** [comment]
Our real app is a react application.  Every time a component with a canvas is mounted we were instantiating the fabric the object and disposing of it as the component unmounted.  After a certain number of mounts (like 20-ish) the browser would crash.  If we keep a global fabric instance we don't run into the same problem so I'm guessing that is the way to go.  I just expected that GC would have cleaned things up after our component unmounted.

**Comment by zspitzer** [comment]
I have referenced this issue in the webkit bug tracker https://bugs.webkit.org/show_bug.cgi?id=172533

**Comment by zspitzer** [comment]
a new bug has been created for this specific issue https://bugs.webkit.org/show_bug.cgi?id=172728

**Comment by skrosoft** [comment]
@zspitzer What about this bug? Still no solution?

**Comment by RudiX** [comment]
also interested in this

**Comment by brunolm** [comment]
If I refresh a page it re-creates all canvas elements.

1. firs time, I have 4 canvas
2. refresh, 8 canvas (4 active; and I can see the previous 4 in Safari `canvas` tab)
3. refresh, 12 canvas (4 active; 8 in the canvas tab)

And it goes on until it starts complaining about canvas memory and nothing else works.

I didn't find a way to prevent canvas from accumulating there. I don't even know how to clear it.

**Comment by witek** [comment]
Same problem here. Initialization of a canvas works exactly once. Trying another time, crashes with something like this:
`TypeError: null is not an object (evaluating 'u.clearRect')`
I never call `u.clearRect()`, it is some internal code.

**Comment by mhieupham1** [comment]
try clear cache canvas, in my app on ipad 7th, fabricjs can add many objects rect, textbox horizontal, vertical, images without crash
