### ISSUE TITLE
Canvas to dataurl on 4k creates double size image

### ISSUE THREAD

**Issue by deepak-trimantra** [kangax/fabric.js#3699]
When i am doing canvas to dataurl to save image from canvas this generates datauri.
I tried this on 4k monitor i don't know why this generates double size image
At first image size is 50x50 but at 4k it gives 100x100 image.

here's jsfiddle demo, see console for output
https://jsfiddle.net/rx1budtc/1/

**Comment by asturur** [comment]
i think is you os. what are you using?

**Comment by deepak-trimantra** [comment]
How OS going to play role in this? This happens in jsfiddle also. FYI, i am using LAMP Web Server. (Ubuntu 16.04, Apache 2.4, PHP 7)

**Comment by asturur** [comment]
the client you are using, does it have some sort of display scaling at 4k? like font scaling for interface or dpi scaling?

console.log your fabric.devicePixelRatio and check if is a number bigger than 1

**Comment by deepak-trimantra** [comment]
At normal it shows 1 and at 4K it shows 2.
Is it possible to set fabric.devicePixelRatio always 1?

**Comment by asturur** [comment]
you have just to disable the property retina scaling, or export to dataurl without retina scaling. i guess the docs cover this.

you can also set the property to 1 manually but retina users won t be happy about this

**Comment by deepak-trimantra** [comment]
yes i tried setting fabric.devicePixelRatio = 1; this works fine. 
I tried canvas.enableRetinaScaling = false; before dataToUrl and again canvas.enableRetinaScaling = true;
this not works. Can you tell me how to export to dataurl without retina scaling or how to display retina scaling.
