### ISSUE TITLE
Sending multiple objects forward changes their order (z-index)

### ISSUE THREAD

**Issue by Lee-Taylor** [kangax/fabric.js#3708]
So, 2 squares on a canvas, drag select those squares, then click "send forward". The squares switch places.

See the following question.

http://stackoverflow.com/questions/42287830/sending-multiple-objects-forward-changes-their-order-z-index

Thanks.

**Comment by asturur** [comment]
i answered you there with a working fiddle. not sure if the solution is what the library needs.

**Comment by Lee-Taylor** [comment]
Many thanks.
