### ISSUE TITLE
 can you please fix a small bug on line number 17886.  orignalPaths  shoud be originalPaths. One i is missed in original.

### ISSUE THREAD

**Issue by by12** [kangax/fabric.js#3710]
hello,
    can you please fix a small bug on line number 17886.  orignalPaths  shoud be originalPaths. One i is missed in original.

fabric.PathGroup.fromObject = function(object, callback) {
    var originalPaths = object.paths;
    delete object.paths;
    // remove this pattern from 2.0 accepts only object
    **# if (typeof orignalPaths === 'string') {**
      fabric.loadSVGFromURL(originalPaths, function (elements) {
        var pathUrl = originalPaths;
        var pathGroup = fabric.util.groupSVGElements(elements, object, pathUrl);
        object.paths = originalPaths;
        callback(pathGroup);
      });
    }
    else {
      fabric.util.enlivenObjects(originalPaths, function(enlivenedObjects) {
        var pathGroup = new fabric.PathGroup(enlivenedObjects, object);
        object.paths = originalPaths;
        callback(pathGroup);
      });
    }
  };

**Comment by asturur** [comment]
this code you reported is not available  in current master
