### ISSUE TITLE
event "deselected" not fired on change activeObject

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3714]
Hi,

the problem from the deselected event not fired, should have been fixed in the last version of Fabric. (cf closed issue : https://github.com/kangax/fabric.js/issues/3685)

But there is still the problem of the event "deselected" not fired when you select another object.
http://jsfiddle.net/S9sLu/1603/

Step to reproduce : select the rect object, click on the circle object, the event is not fired (cf console.log not showing).

Am i missing something ?

**Comment by asturur** [comment]
maybe in rush of doing something i did wrong. i ll double check today.

**Comment by asturur** [comment]
i fixed it i think!
will be on 1.7.7 as soon as i can release it.
I m mainly working on text changes when i find the time and on terrible bugs.

I tanked you on twitter for the effort on finding and reporting bugs in a way that is usefull to me.
Do you have a twitter account by the chance?

**Comment by ncou** [comment]
great news :)
no i don't have a twitter account.

I am happy to help to make this library more and more better.
