### ISSUE TITLE
Text renders blurry in 1.7.6 compared to 1.7.2

### ISSUE THREAD

**Issue by piieers** [kangax/fabric.js#3720]
## Version
1.7.6

## Test Case
https://jsfiddle.net/g6rkcuqy/6/ (v. 1.7.2)
https://jsfiddle.net/g6rkcuqy/7/ (v 1.7.6)
https://jsfiddle.net/g6rkcuqy/8/ (v 1.7.6 with border and border-box box-model)

## Steps to reproduce
I am using Chrome 56.0.2924.87.
1. Open first fiddle, text renders good.
2. Open second fiddle, text is blurry.
3. Open third fiddle, text is even blurrier.

## Expected Behavior
Non-blurry text.

## Actual Behavior
Blurry text.

**Comment by ncou** [comment]
Hi,

With Chrome (56.0.2924.87) i got the same disply for the 2 first fiddle.
With Firefox, i got a bit of blur on the second canvas, but with the cache disabled the result is more crisppy.
=> I think it's the same explanation than this issue : https://github.com/kangax/fabric.js/issues/3678

But for the third canvas, it seems it's the CSS attribute "box-sizing: border-box;" who add the blur.
It's perhaps an antialiasing when it scale the 502x502px canvas to the 500x500 container.

Adding the "box-sizing" to the div class "canvas-container" seems to solve the problem and keep the canvas to 500x500px.
https://jsfiddle.net/g6rkcuqy/9/

**Comment by asturur** [comment]
if you resize canvas with css everything will be blurried out. you should not do that.

the differencies between 1.7.2 and 1.7.6 i ll check them asap

**Comment by asturur** [comment]
Yes i see a small blurriness also on retina. that's bad.
I have to do some diff to figure out what changed.

**Comment by asturur** [comment]
the blurrines comes from 1.7.3

**Comment by asturur** [comment]
Ok the line that causes the blurriness is the one that reduce the cache canvas dimension to an integer. This is necessary at some point because you cannot have a canvas that is  34.16 pixels. either is 34 or 35. I think something can be done in some way.

**Comment by asturur** [comment]
actual kitchensink
![image](https://cloud.githubusercontent.com/assets/1194048/23103980/c6288c68-f692-11e6-8c02-ae221957cebc.png)

![image](https://cloud.githubusercontent.com/assets/1194048/23103996/1bce90e0-f693-11e6-9eae-6492dc49449a.png)

fixed code
![image](https://cloud.githubusercontent.com/assets/1194048/23103983/d3daec34-f692-11e6-8ac8-26c4ce033922.png)

![image](https://cloud.githubusercontent.com/assets/1194048/23103993/12eb35be-f693-11e6-9257-44344c954479.png)

**Comment by asturur** [comment]
fixed, will be out in 1.7.7 i do not want to release immediately, i wait for some more possible little fixes.
