### ISSUE TITLE
How to zoom in out objects from center (Zoom in/out objects instead of entire canvas).

### ISSUE THREAD

**Issue by jrishna** [kangax/fabric.js#3723]
## Version
1.7.6

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by jrishna** [comment]
1)canvas.zoomToPoint(new fabric.Point(canvas.width / 2, canvas.height / 2),canvas.getZoom() * 1.1);
.canvas.renderAll();
2 also tried viewport

both not working as expected.

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

**Comment by jrishna** [comment]
Thanks alot for your quick response.
Please check below fiddle url. 
http://jsfiddle.net/ux16013L/2/
click on + and - for zoom in and zoom out. the objects are zoom but its going down side.
I want to zoom all objects from center.please help.

**Comment by Kienz** [comment]
@jrishna http://jsfiddle.net/Kienz/2Luoaxv4/

**Comment by jrishna** [comment]
Hi Kienz,
Thanks a tone.Really appreciate your support.

**Comment by jrishna** [comment]
Hi,
I can zoom in/out  objects from center point using this http://jsfiddle.net/Kienz/2Luoaxv4/ link,but i want to zoom in/out objects from center point using following code.

  var objects = canvas.getObjects();
    for (var i in objects) {
      var scaleX = objects[i].scaleX;
      var scaleY = objects[i].scaleY;
      var left = objects[i].left;
      var top = objects[i].top;

      var tempScaleX = scaleX * factor;
      var tempScaleY = scaleY * factor;
      var tempLeft = left * factor;
      var tempTop = top * factor;

      objects[i].scaleX = tempScaleX;
      objects[i].scaleY = tempScaleY;
      objects[i].left = tempLeft;
      objects[i].top = tempTop;
      objects[i].setCoords();
    }
    canvas.renderAll();
    canvas.calcOffset();

I unable to zoom in/out objects from center point.Please help.

**Comment by kidsit** [comment]
@Kienz , as ghost say, i also want zoom in/out objects, not zoom canvas. I want the canvas size not changed, only objects zoom/scle in center, how to make that work?

**Comment by asturur** [comment]
http://fabricjs.com/fabric-intro-part-5#pan_zoom

**Comment by juzhiyuan** [comment]
> @Kienz , as ghost say, i also want zoom in/out objects, not zoom canvas. I want the canvas size not changed, only objects zoom/scle in center, how to make that work?

Hi @asturur , the link above seems to zoom the canvas with objects together 🤔 

## Original
![image](https://user-images.githubusercontent.com/2106987/95680960-d145fe00-0c0f-11eb-8337-893c8a26ce25.png)

## After 1 zoom
![image](https://user-images.githubusercontent.com/2106987/95680996-0a7e6e00-0c10-11eb-8d7a-f75e8f16a17b.png)

```ts
    const scaleFactor = 1.2;
    canvas.getObjects().forEach((obj) => {
      const { scaleX = 1, scaleY = 1, left = 0, top = 0 } = obj;
      obj.scaleX = scaleX * scaleFactor;
      obj.scaleY = scaleY * scaleFactor;
      obj.left = left * scaleFactor;
      obj.top = top * scaleFactor;
      obj.setCoords();
    });
    canvas.calcOffset()
```

**Comment by juzhiyuan** [comment]
The object's position is not right, not like `canvas.setZoom(zoom)` 🤔 Maybe I should recalculate every object's position by using their center points.

**Comment by asturur** [comment]
i m not sure what are you trying to do, but if you want to zoom an entire scene use the zoom functions. What is going on with normal zoom thay you do not like?

**Comment by asturur** [comment]
You can also group them, scale the group, ungroup

**Comment by juzhiyuan** [comment]
I implement the visible area using this answer[1], now I want to do a Zoom in/out action, when I use canvas.setZoom, it will zoom the entire canvas (yellow zone, the actual canvas), but I only want to zoom those objects :D

![image](https://user-images.githubusercontent.com/2106987/95702770-d93d8680-0c7f-11eb-96b9-d81255af1741.png)

[1] https://stackoverflow.com/a/44454016
[2] related issue: https://github.com/fabricjs/fabric.js/issues/6325#issuecomment-704666699
