### ISSUE TITLE
SVG Group Opacity Parsing

### ISSUE THREAD

**Issue by chryton** [kangax/fabric.js#3727]
## Version
1.7.6

## Test Case
https://jsfiddle.net/chryton/6cs7r8q0/1/

## Steps to reproduce
Have an SVG with a group with an opacity and child elements beneath it with a different opacity.

In the fiddle, see the canvas being rendered incorrectly and the two SVGs beneath rendering correctly.

## Expected Behavior
Group opacity should be read along with child opacity

## Actual Behavior
Group opacity is being ignored 

## Notes
I could be completely wrong about what the issue is here but it seems that something with the group opacity is either being read incorrectly or just straight up ignored. The SVGs were exported from Illustrator and run through SVGO; the original, non-optimized SVG have the exact same problem.

**Comment by asturur** [comment]
https://jsfiddle.net/6cs7r8q0/4/

The fiddle should be as minimal as possible.

I reduced the fiddle to something smaller with just one SVG.

There seems to be a bug.
