### ISSUE TITLE
Is there a way to use padding in fabric.Textbox, as currently text goes in-line with background.

### ISSUE THREAD

**Issue by Repensek** [kangax/fabric.js#3731]
## Version
1.7.6

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by brijeshb42** [comment]
Here is a solution that I implemented - 

```js
var TextboxWithPadding = fabric.util.createClass(fabric.Textbox, {
  _renderBackground: function(ctx) {
    if (!this.backgroundColor) {
      return;
    }
    var dim = this._getNonTransformedDimensions();
    ctx.fillStyle = this.backgroundColor;

    ctx.fillRect(
      -dim.x / 2 - this.padding,
      -dim.y / 2 - this.padding,
      dim.x + this.padding * 2,
      dim.y + this.padding * 2
    );
    // if there is background color no other shadows
    // should be casted
    this._removeShadow(ctx);
  }
});
```
`this.left` and `this.top` will also have to be taken into account.
But with new fabric updates, this method will have to be synced with that of `fabric.object`.

**Comment by howtomakeaturn** [comment]
@brijeshb42 I've been researching on this for a few days... your solution really helps me a lot...!

Thanks so much ... you are the best ...!

**Comment by howtomakeaturn** [comment]
my working code snippet based on the above solution:

https://gist.github.com/howtomakeaturn/4855a886363085d3067f2f3cbbf36c72

**Comment by SakifKhan98** [comment]
@howtomakeaturn thanks for your comment. It really helped. I created a custom text box as per your solution. But facing some errors when I am trying to load the custom object in canvas using loadFromJSON function of FabricJS. Can you put some light on this matter? Did you face any kind of problems with your code?

The ERROR:

**TypeError: klass.fromObject is not a function**

**Comment by brijeshb42** [comment]
I have not used this library since the last time I commented here. You'll have to look through the source to see what's wrong.
