### ISSUE TITLE
ClipTo not working for masking image in the polygon

### ISSUE THREAD

**Issue by sysadminpws** [kangax/fabric.js#3733]
## Version
1.6.0

## Test Case
http://jsfiddle.net/o9f4dqjn/47/

## Steps to reproduce
Change the fabricjs version from 1.5.0 to any of the latest version or add the latest fabricjs version in the external resources & click on the run, pug image is not showing at all & if you click on the pug image it shows only the control boxes. I don't know what is changed in the newer versions. Please help me.

## Expected Behavior
Pug image should show in the polygon & if we scale/move the image out of the polygon, it should mask/hide the image & show the controls as it is showing correctly with version 1.5.0

## Actual Behavior
If you add latest version of fabricjs, it shows only the control boxes in the polygon that too if you select that pug image.

When i compared both the versions, i found that there is a difference in "_calcDimensions" function.

Please help me in this. I am struggling with this since last week.

**Comment by drave** [comment]
Any update on this?

**Comment by asturur** [comment]
is how you render the polygon starting from its points.
That clipByName function comes from a series of bad examples that people copy paste around.
Is a terrible way of clipping.

If you want to reset the clipping area when you draw an object, you have to apply a neutral transform to canvas, then retina scaling, then draw the path.
