### ISSUE TITLE
Groups dont render in latest fabric

### ISSUE THREAD

**Issue by virror** [kangax/fabric.js#3734]
## Version
1.7.6

## Test Case
https://jsfiddle.net/15m7xf3b/2/

## Steps to reproduce
Run the fiddle

## Expected Behavior
Grid to show

## Actual Behavior
Nothing shows

This code is from my project, and it worked just fine before updating, was running 1.6.5.

**Comment by asturur** [comment]
Hello Victor, you need to give the group some kind of dimensions.
Would be better if you first build an array of object and then you create the group with the filled array instead of add stuff to group with `add`

`add` does not change group dimension.

Or you can swap add with `addWithUpdate` but that will recalculate group dimensions every object you add.

**Comment by asturur** [comment]
please verify and then close this issue.

**Comment by virror** [comment]
Is this something thats changed, cause it used to work as i wrote in 1.6.5?

**Comment by virror** [comment]
It only partly solves the issue.
Adding height/width wiull make the grid show, but it will also make the grid show in the wrong place.
See the updated fiddle: https://jsfiddle.net/15m7xf3b/3/

**Comment by virror** [comment]
Its possible to get it to show correctly by using:
left: -gridWidth,
top: -gridHeight,
width: gridWidth * 2,
height: gridHeight * 2,

But this seems like a bug to me?

**Comment by asturur** [comment]
So this is the solution 1
https://jsfiddle.net/15m7xf3b/4/

this is the solution 2 ( best i think )
https://jsfiddle.net/15m7xf3b/5/

this is solution 3 ( worst )
https://jsfiddle.net/15m7xf3b/6/

what changed after 1.6.7 is the cache.
If object has not correct dimensions, it will render bad, while before it was rendering just out of controls box

**Comment by virror** [comment]
Thank you for the explanation, makes sense now : )
I agree that solution 2 is the best one.
Sorry for bothering, case closed! : )
