### ISSUE TITLE
Panning Without Going Off Canvas??

### ISSUE THREAD

**Issue by SmboBeast** [kangax/fabric.js#3736]
## Version
1.7.6

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by SmboBeast** [comment]
Hi guys,

Is there a way to pan but have things be constrained to the boundaries of the canvas, instead of just being able to go completely off in any different direction?

Thanks

**Comment by paulcredmond** [comment]
Can you share your solution for this?

**Comment by nitaskenderi** [comment]
Hi @SmboBeast, can you share your solution for this?

**Comment by SmboBeast** [comment]
Actually guys, I closed this out because luckily our specs changed, and this wasn't needed anymore (for me anyway).
