### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by kob-e** [kangax/fabric.js#3737]
I've started to develop the RTL support for Text and IText.
i need help from the community, please test my development and i keep work on it, at the end i will do it clean and provide it as a module.
 
https://github.com/kob-e/fabric.js

**Comment by asturur** [comment]
thanks for your efforts!
Text part is current in rewrite, would be nice to see what you do to support RTL so that i could fix it in the rewrite.

**Comment by kob-e** [comment]
Helo @asturur , i am writing the BIDI algorithm that takes LTR text and transform it to LTR.
but, i might think that i am doing extra work, consider this example that works perfect (RTL) with plain JS:
https://plnkr.co/edit/vG3ulkRm2nAbvDgubUGp?p=preview

**Comment by kob-e** [comment]
For your question, the algorithm classify the text for a sets, rtl set, ltr set and neutral set, then join all together all sets with the right direction for each one.

**Comment by onassar** [comment]
Has there been progress here?

**Comment by kob-e** [comment]
I still work on it.
i have working edition on iText RTL mode.

**Comment by onassar** [comment]
Okay looking forward to it.

**Comment by kob-e** [comment]
@onassar you can check with this repo: https://github.com/kob-e/fabric.js , after downloading look at index.html for examples

**Comment by ShahramCodeDeveloper** [comment]
Hi kob-e

Have you reached the conclusion?

**Comment by YaakovHatam** [comment]
Duplicate of #2374
