### ISSUE TITLE
iText is out of bounds in case if fontStyle is italic

### ISSUE THREAD

**Issue by ashvardanyan** [kangax/fabric.js#3739]
Hello

Thank you for awesome library! Our entire [logo-maker](https://logo-maker.ucraft.com) is based on your project and we are very happy that we have chosen fabric.js for our needs!

We have a problem with iText which you can also see on the link above and I have also created [jsfiddle](http://jsfiddle.net/ashvardanyan/ramtroy1/4/).
So when the text is "italic" I guess the font width is not calculated correctly and the object is out of bounds (text is cut in the generated image if I use bounds to trim) and also the cursor position is not generated correctly, in case of bold it is working fine.

Thanks,
Ash

**Comment by asturur** [comment]
So the canvas api returns that kind of dimensions for italic text.
We cannot do anything about it.
There is a text rewrite in progress that will make it easier to plug your custom font measurement.

I cannot really fix anything here.
