### ISSUE TITLE
Example of drawing iamge on canvas from official docs not working

### ISSUE THREAD

**Issue by beelio** [kangax/fabric.js#3740]
I'm trying to use fabric.js for drawing an image on a canvas.

I followed the documentation [here](http://fabricjs.com/fabric-intro-part-1#images) , but is does not work as expected.

## Test Case
http://jsfiddle.net/Vp6wa/372/

## Steps to reproduce
- Go to jsfiddle
- Click run
## Expected Behavior
- image should be rendered on canvas

## Actual Behavior
- image are not rendered

![skarmavbild 2017-02-24 kl 15 10 18](https://cloud.githubusercontent.com/assets/7048562/23306331/63435bae-faa3-11e6-9e75-ff2d9c6a3ba5.png)

**Comment by asturur** [comment]
http://jsfiddle.net/Vp6wa/373/

the image load slowly and is not ready when you run the code.
You should wait for image to be loaded before using them, load them explicitly if you want have full control.
