### ISSUE TITLE
Grouping objects resize some of them

### ISSUE THREAD

**Issue by ghs** [kangax/fabric.js#3741]
## Version
1.7.6
Same happens with 1.7.3

## Test Case
https://jsfiddle.net/77jjuuek/
https://jsfiddle.net/87vrf6b9/

## Steps to reproduce
For case one, just add two lines to a group: one vertical and one horizontal.
For the second case, group a text box with another object and then select the group. The text will resize.

## Expected Behavior
In case one, the line shouldn't be resized.
In case two, the text box must keep its dimensions.

## Actual Behavior
The one of the lines is resized and is looking blurred.
In case two, when the group becomes an active object (simply by selecting the group), the text box resizes itself.

**Comment by asturur** [comment]
that is the weird textbox interaction with groups.
Is gonna be deleted in the text refactor.
Actually a textbox is not meant to be scaled. There is no really a reason, it has been just shipped like this.
It will be different.
I link this to the main issue.

**Comment by ghs** [comment]
@asturur thank you for the information about the textbox refactoring, but there is the other problem with the lines. think closing directly the issue is not a solution.

**Comment by asturur** [comment]
i do not see the line resizing at all. can you make it more visible? or can you tell.me what to look at?

**Comment by ghs** [comment]
Now when you said that you don't see it, I've opened the fiddle from a 1440px screen and there is a little to not visible "resize", which creates this kind of glow/blur effect around the line.
To see it more clear on smaller screens you should take a screenshot and zoom it:
![screen](https://cloud.githubusercontent.com/assets/94248/23332067/a1f9c5f2-fb72-11e6-9e71-0612201602d9.png)

This gets bigger when the screen resolution is higher. Can attach another screen at monday when I'm back at the office if you want and don't have a bigger screen.

This "effect" is not happening when the lines are not grouped, but once you group them (in my example I've grouped 2 vertical and 2 horizontal) all horizontal lines are becoming that way.

So, just like the textbox example from the issue, if you have objects separated everything is fine, but once you group, the lines are clearly and visible resized as the textbox.

**Comment by asturur** [comment]
guys blurring will always be there.
i will make a page on the website talking about blurring. cache does not improve it, make things worse. you can still disable cache completely.

**Comment by ghs** [comment]
But why only when grouping and on specific objects and not on all?
I understand if a large number of objects are in the canvas and to save some some memory, but here is an example of two simple lines.

**Comment by asturur** [comment]
is not me saving memory, is how canvas works. you can ask canvas to do not blurry pixels at all, i ll check the setting for it.
