### ISSUE TITLE
Fabric JS Scaling Grouped Objects

### ISSUE THREAD

**Issue by rananthan3** [kangax/fabric.js#3744]
I have an issue trying to keep the green circles at the vertices when scaling a group of squares up or down.  The dimensions of the rectangle do not change when I check either

1) canvas._objects
2) canvas.getObjects()

![a](https://cloud.githubusercontent.com/assets/5447156/23336210/64afd5cc-fb97-11e6-9864-fe8e4562a348.png)

![scaling](https://cloud.githubusercontent.com/assets/5447156/23336212/742b4a0e-fb97-11e6-958d-c0e0b4cdf772.png)

## Version
1.7.6

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by asturur** [comment]
This looks more a stackoverflow question. I ll wait a bit to see if some clarification change this idea, or i ll close the issue

**Comment by rananthan3** [comment]
http://stackoverflow.com/questions/42463587/fabric-js-object-scaling

**Comment by ncou** [comment]
the answer on stackoverflow seems to solve the problem @rananthan3 i suppose you can close this ticket ?

**Comment by asturur** [comment]
Would be nice to have some fiddle in the answers.
Stackoverflow is a de facto resource for this kind of problems, the more is clear how to solve, the less the people will ask again.
