### ISSUE TITLE
shadow effect with angle browser problem.

### ISSUE THREAD

**Issue by hasanmumin** [kangax/fabric.js#3750]
## Version
1.7.6

## Test Case
http://jsfiddle.net/hasanmumin/b0u18ozr/1/
http://fabricjs.com/shadows

## Steps to reproduce
- Adding shadow and angle to rect element (also image have same problem). 
- Test with chrome v49

## Expected Behavior
chrome v56
<img width="1376" alt="screen shot 2017-02-27 at 13 34 05" src="https://cloud.githubusercontent.com/assets/6329984/23358106/4fe0836e-fce9-11e6-878d-08005bba7efd.png">

## Actual Behavior
chrome v49
<img width="1142" alt="screen shot 2017-02-27 at 13 33 51" src="https://cloud.githubusercontent.com/assets/6329984/23358115/649c44dc-fce9-11e6-9c1e-5339bda68659.png">

**Comment by asturur** [comment]
Chrome 48 and 49 if i remember good are bugged.
Shadow did not display for images.
If you want to see images for shapes and text disable the image caching of fabric.

www.fabricjs.com/fabric-object-caching
