### ISSUE TITLE
Keyboard shorcuts 

### ISSUE THREAD

**Issue by timmy63** [kangax/fabric.js#3751]
Hi,

I would like to add keyboard shortcut to manage object management in a Kitchensink like app. Like : enter to exit selected objet, delete to remove an object or arrows to move an object. Is it natively support by fabricJS ?

Thanks

**Comment by asturur** [comment]
no because key management is something you have to build with your app.
is not something fabricjs can provide in one way.

you probably want to append the events to specific element and not to fabric canvas only.
