### ISSUE TITLE
getWidth function adding 1 or 2 extra pixel from 1.7.x

### ISSUE THREAD

**Issue by cksachdev** [kangax/fabric.js#3753]
I am working on a editor using fabricjs. I upgraded from version 1.6.0-rc.1 to 1.7.3. I noticed one specific issue with getWidth. If I create an object of 100x100 in 1.6, I was getting the same dimensions back but in 1.7.3 I am getting few extra pixels e.g. 100.42 x 100.42. 
Could you please mention if there are any specific changes done in getWidth related to rounding or something.

## Version
1.7.6

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by asturur** [comment]
Since 1.6.0 ( i thought it was 1.5.0 really ) the strokewidth is included.

getWidth is a wrong named method that will be finally removed in 2.0
it looks a getter of width but it isn't. It is a shortcut for the full dimension of the bounding box of the object.

use get('width') or .width for the width.

**Comment by cksachdev** [comment]
@asturur Thanks for your response. It works when I add a new object. But when I scale the object, the .width or get('width') still returns the initial values, the updated value I get only with getWidth() function. Any solution for this?

**Comment by asturur** [comment]
so what you need is '._getTransfromedDinensions().x'

the low dash will be removed in 2.0 so that looks like a public methid

**Comment by cksachdev** [comment]
@asturur @kangax 

To remove the stroke issue, I am currently doing this
```
editorObj.getHeight() - editorObj.getStrokeWidth()
editorObj.getWidth() - editorObj.getStrokeWidth()
```
Would you recommend using this or I should rely only on _getTransfromedDinensions()?

**Comment by asturur** [comment]
depends what you want to have.
What do you need this measurement for?

width is a property that makes little sense. you can also you this.width * this.scaleX. depends what you need that value for.
