### ISSUE TITLE
loadFromJSON loading objects upside down

### ISSUE THREAD

**Issue by dudzio** [kangax/fabric.js#3760]
I created canvas and added some objects IText, Image, SVG and exported it to JSON with canvas.toJSON().

When I'm creating new canvas and adding those saved objects with loadFromJSOM() they are upside down. This is funny because controls are in normal positions (rotate handle is in top). In exported JSON setting "angle" is set to 0.

What could it be? Maybe images are loaded in wrong way? This is the only issue I can think of.

Fiddle:
http://jsfiddle.net/gosc8mck/

Another issue with object not showing after loadFromJSON(), even with callback with rederAll().
Shouldn't it fire after every image in objects done loading?

**Comment by asturur** [comment]
can you create a fiddle? Issues without fiddle are not handled

**Comment by dudzio** [comment]
Hey! I added fiddle - sorry.

**Comment by dudzio** [comment]
The issue was trivial in fact. Look at the JSON and values for flipX and flipY. Both are set to "false"...

Always remember to use JSON.parse() and JSON.stringify().

Thanks for your time. Issue can be closed.

**Comment by asturur** [comment]
you got flipx and flipy why evaluated as true being strings.

the strange thing is that i rememberd that fabric could autoparse. but if i send that json object as string it does not work.

**Comment by asturur** [comment]
'''
var serialized = (typeof json === 'string')
      ? JSON.parse(json)
      : fabric.util.object.clone(json);
'''

weird....

**Comment by asturur** [comment]
http://jsfiddle.net/gosc8mck/3/

i would expect this to work

**Comment by dudzio** [comment]
I don't think so - it will work without quotes or boolean values 0/1.
