### ISSUE TITLE
Unexpected behavior when setting strokeDashArray of object's border to [1, 1] and strokeWidth to 1

### ISSUE THREAD

**Issue by make2514** [kangax/fabric.js#3761]
Hi guys,

I have just encountered this issue when setting object's strokeDashArray  to [1, 1] and object's strokeWidth to 1.
Expected behavior: there is dotted border (similar to this line: https://jsfiddle.net/make2514/557s89bz/).
Actual behavior of fabricjs canvas: a solid border is shown (https://jsfiddle.net/make2514/sggznpak/1/).

Any insight would be appreciated!

**Comment by asturur** [comment]
happy to help if you reduce the fiddle to 1 shape and little code.

**Comment by make2514** [comment]
Thank you for your reply, asturur! The fiddle is updated as you suggested.

**Comment by asturur** [comment]
i see a dotted dash indeed on the square shape.
what do you see and in what browser?

**Comment by make2514** [comment]
This is what I see (http://imgur.com/a/1nTEC),  and I am using Google Chrome - version 55.0.2883.87 (64-bit)

**Comment by make2514** [comment]
It seems that the solid line appears only when I first load the square into fabric canvas. If I resize the square, the dotted border is shown instead.

**Comment by asturur** [comment]
look like blurring artifact to me. are you on latest 1.7.7?

**Comment by make2514** [comment]
Yes, I am.
I tested on an other laptop and saw the dotted line from the beginning. I think it could it be because of my laptop's graphic card or OS. I am sorry for raising this issue without testing further myself.

**Comment by asturur** [comment]
of you are using native resolution that may be the cause. 1:1 with pixels
