### ISSUE TITLE
Rendering on transparent canvas is messed up on Chrome OS beta

### ISSUE THREAD

**Issue by oktayacikalin** [kangax/fabric.js#3762]
## Version
1.7.6

## Test Case
http://fabricjs.com/bounding-rectangle
http://fabricjs.com/kitchensink
Toshiba CB 2 (older one)
Version 57.0.2987.85 beta (64-bit)
Plattform 9202.43.0 (Official Build) beta-channel swanky
Firmware Google_Swanky.5216.238.5

## Steps to reproduce
Open the first URL above

## Expected Behavior
See a green rectangle and a squirrel.

## Actual Behavior
See 2 squirrels and a rectangle.
After clicking on a squirrel, the one on the top left disappears.

![screenshot 2017-03-04 at 07 07 28](https://cloud.githubusercontent.com/assets/687189/23576564/433e30b6-00a9-11e7-9c06-bf9a034fa17e.png)

The kitchen sink demonstrates problems with transparent text elements too. When setting transparency of a text to 0.5 and moving a filled white(!) rectangle below it, the color of the text is different on the transparent canvas and the rectangle. Plus it seems like when showing the selection bounding box the colors shift a bit.
White rectangle partly(!) behind the text "foo bar baz quux":
![screenshot 2017-03-04 at 07 11 33](https://cloud.githubusercontent.com/assets/687189/23576583/efea8292-00a9-11e7-87f5-1af1b9c677eb.png)

**Comment by asturur** [comment]
Since is a beta, we should worry to replicate this in plain javascript and show on chromium issue tracker.
If it creates errors i belive they already noticed.

**Comment by oktayacikalin** [comment]
Sounds reasonable.

I'm a Python/PHP guy (JavaScript is my secondary skill), so I would love to ask you to check and if necessary create a proper test case for/with them.

I also tried to replicate this on an older MacBook Air running OSX 10.9.5, but it worked fine. So it might be some hardware related code that does this.
As far as I can remember, I noticed this bug about a week ago.

For me it's important that this bug won't slip into stable because I'm developing a print shop at https://www.screenart.media, which is using fabric and other stuff to give the customer the opportunity to design and order their print material without the usual hoops and hassle. So I'm motivated to support you as much as I can :).

**Comment by oktayacikalin** [comment]
Video about playing with the kitchen sink: https://drive.google.com/file/d/0B8GQnTRW-JUbYlFzVk5UT2doM1E/view

Video about playing with the squirrels: https://drive.google.com/file/d/0B8GQnTRW-JUbcHJqM3ZEazJtWUE/view

**Comment by asturur** [comment]
did next chrome come out? how is the situation?

**Comment by oktayacikalin** [comment]
I'm now on:

Version 57.0.2987.100 beta (64-bit)
Plattform 9202.51.0 (Official Build) beta-channel swanky
Firmware Google_Swanky.5216.238.5

Same problem.

It seems like it doesn't clear the canvas properly, leaving artifacts behind and finally painting the new stuff on top - resulting in multiple squirrels, hard shadows and overall wrong transparency...

**Comment by oktayacikalin** [comment]
Just updated to:

Version 58.0.3029.31 beta (64-bit)
Plattform 9334.18.0 (Official Build) beta-channel swanky
Firmware Google_Swanky.5216.238.5

And the artefacts are gone :)
