### ISSUE TITLE
Deserialised objects have previously hidden control handles restored 

### ISSUE THREAD

**Issue by paulcredmond** [kangax/fabric.js#3766]
## Version
1.7.6

## Test Case
http://codepen.io/paulcredmond/pen/RpoWrX?editors=1010

## Steps to reproduce
- Add an SVG to the canvas using the addsvg button
- Note: `hasControls` has been set to `false`
- If you select the object, you can see it has no controls	
- Now undo, and redo

## Expected Behavior
When removed and added back, the object should still have no control handles

## Actual Behavior
The object's control handles have been restored

**Comment by ncou** [comment]
Hi,

The controls data are not exported with the json (you can see this if you do a console.log).

You can keep the "hasControls" value if you add it to the toJSON function params like this : 

myjson = canvas.toJSON(['hasControls']);

http://codepen.io/anon/pen/evBpqb?editors=1011

I think you can also use somethink like : fabric.PathGroup.prototype.hasControls = false;

At the start of you code to always disable the hasControls on all the svg objects.

**Comment by asturur** [comment]
correct

**Comment by paulcredmond** [comment]
Great info, thank you.

@asturur You think it could be worth having the option to save control visibility on a per-object basis when serialising/deserialising?

**Comment by asturur** [comment]
Not really.
Serialization should bring outside what you need to restore a particular
canvas situation visually.
While controls and other things are usually per app settings.

I guess you can still output the value of each control in the JSON output.
do not remember exactly. if it is not possible to output or restore it
using the additionalProperties parameter then we should fix something.

2017-03-07 14:38 GMT+01:00 Paul Redmond <notifications@github.com>:

**Comment by paulcredmond** [comment]
Okay, thanks. Good info!

**Comment by paulcredmond** [comment]
@ncou To use it with stringify, would this be the best approach?

`JSON.stringify(canvas.toDatalessJSON(['hasControls']));`

**Comment by asturur** [comment]
it depends what do you do with that json object.
if you save it on a db and recover after is probably ok to keep the object.
if you are using it in a js app and is referenced somewhere and some deep
keys can be changed by references, better you stringfy it.

is just a reference/value problem

2017-03-07 15:08 GMT+01:00 Paul Redmond <notifications@github.com>:
