### ISSUE TITLE
Not able to change the corner radius for fabric js Rectangle 

### ISSUE THREAD

**Issue by anshunarayan** [kangax/fabric.js#3768]
For fabric js Reactangle - Not able to change corner radius at run time. I am using 1.7.3 version of fabric js. It supports with 1.6.1 version.

Version :
1.7.3

Test Case :
https://jsfiddle.net/anshyan/5zsc2oos/11/

Steps to reproduce :
 - I have button that assigns the corner radius.

Expected Behavior : 
 - As soon as the button is clicked, the rectangle corner should be updated with respective value. 

Actual Behavior : 
 - Unless and untill rectangle is resized the corner radius value doesn't changes.

**Comment by asturur** [comment]
i agrre that should work.

**Comment by anshunarayan** [comment]
Thanks for responding. But its not working for me. Am i missing something.

**Comment by asturur** [comment]
i labeled.as bug, needs a fix
