### ISSUE TITLE
Fabric.js taints the Canvas in IE11

### ISSUE THREAD

**Issue by ParthibanSugumar** [kangax/fabric.js#3769]
Hi @kangax,

I am using HTML2Canvas to capture screenshot of my html page and save it as image in server. My Html contains a d3.js chart and html elements. d3.js chart is generated as svg. So to capture svg, I use **Fabric.js** to convert svg to canvas element. After this process is complete, I use Html2Canvas to capture the entire web page as image and save it in server.

The whole process is working fine in Chrome and FF. Problem is when using IE. In IE 11, everything else in the page is captured except the chart canvas element.

I found out that using **Fabric.js** in IE < Edge will taint the canvas as soon as an SVG image has been drawn to it. Due to this issue the canvas converted SVG is not captured in html2canvas js. 

Please help me to fix this issue.

Thanks.

## Version
1.7.6

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by asturur** [comment]
if some image get loaded without cours, the canvas is tainted.
This is more something related to HTML2Canvas maybe, or to your particular SVG with maybe extarnal links.
Since we already have an issue for SVG with external links, i will close this.

**Comment by ParthibanSugumar** [comment]
I found the root cause for this issue to be another svg icon which was embedded inside the chart. Replacing the svg icon with png image fixed this issue.

Sorry for the inconvenience.
Hope it helps someone in future.

**Comment by asturur** [comment]
is a svg limitation. svg does not support crossOrigin for the external resources
