### ISSUE TITLE
ability to set larger offset for scale action corners

### ISSUE THREAD

**Issue by vitaly-zdanevich** [kangax/fabric.js#3771]
On a small iPad it is sometimes difficult to hit the corner for zooming canvas.

As I understand it can be simple two params to the `setCoords()` that can affect values of `offsetX` and `offsetY`; if it is ok I can make pull request for this.

**Comment by asturur** [comment]
we have parameters for this. you want bigger corners or what?

**Comment by vitaly-zdanevich** [comment]
I want bigger active area for zooming and rotating.

**Comment by vitaly-zdanevich** [comment]
I found that I need to edit `_setCornerCoords()` for that - or update values after mouseUp.

**Comment by asturur** [comment]
this.cornerSize is not enough?
