### ISSUE TITLE
TouchMove events are slowing everything way down (at least in Angular 2)

### ISSUE THREAD

**Issue by bramdeba** [kangax/fabric.js#3776]
## Version
1.7.6

## Test Case
Used Plunker instead of JSFiddle due to the Angular 2 framework in which the bug is occurring.
https://embed.plnkr.co/ubFifMr7jc5Da3wT5XZx/

## Steps to reproduce
Using a touchscreen, try to drag the red rectangle. No problem there. Now tap the red rectangle for 5-10 times. Then try to drag it. You'll notice lots and lots of lag. The more you tap/touch/drag the canvas, the more lag when trying to drag the red rectangle.

## Expected Behavior
Smooth dragging at any time. Check out this plunker: https://embed.plnkr.co/y2WwmF2Y80cFNlatR7rb/
I commented out the following lines in fabric.js:
```
10498       addListener(fabric.document, 'touchmove', this._onMouseMove, { passive: false });
...
10527       addListener(this.upperCanvasEl, 'touchmove', this._onMouseMove, { passive: false });
```
With these changes, it actually works just the way you'd expect. This is on a Dell XPS 15 with touchscreen though. I haven't read all of the fabric code, so I've got no clue whether removing these lines breaks touch on other devices or not... The bug also only occurs when using fabric alongside Angular 2.

## Actual Behavior
Lots of lag.

I'd appreciate it if someone with a little bit more knowledge and expertise could take a look and try to fix this (in a perhaps better way).

**Comment by asturur** [comment]
i have 0 knowledge of angular 2. did you find the root cause?

**Comment by asturur** [comment]
to be handled in #3869

**Comment by yadue** [comment]
Just to let you know that every event triggered by any library triggers angular2 zone.js event. You have to explicity run fabricjs outside zone.js
