### ISSUE TITLE
Assertion failed: (!scaled_font->cache_frozen), function _cairo_scaled_glyph_page_destroy, file cairo-scaled-font.c, line 459.

### ISSUE THREAD

**Issue by playground** [kangax/fabric.js#3777]
for some unknown reason, it started throwing this error after calling loadFromJSON

    canvas.loadFromJSON(json, cb);

I was on 1.6.4 and just switched to 1.7.7 and am getting the same error.  The funny thing is that in my current workspace the app continues to work.  However, if I delete node_modules and run npm install again.  It's throw that error.  I compared the new node_modules and old node_modules they look identical.  Any idea why?  Thanks.

=============
package.json
  "dependencies": {
    "body-parser": "^1.15.2",
    "canvas": "^1.6.2",
    "cookie-parser": "^1.4.3",
    "dotenv": "^2.0.0",
    "express": "^4.14.0",
    "fabric": "^1.7.7",
    "jsonfile": "^2.4.0",
    "morgan": "^1.7.0",
    "rxjs": "^5.2.0",
    "s3-image-uploader": "^1.0.7",
    "winston": "^2.3.0",
    "winston-slack-transport": "^2.0.0"
  },
  "devDependencies": {
    "babel-cli": "^6.5.1",
    "babel-core": "^6.14.0",
    "babel-loader": "^6.2.5",
    "babel-node-debug": "^2.0.0",
    "babel-polyfill": "^6.13.0",
    "babel-preset-es2015": "^6.14.0",
    "babel-preset-stage-3": "^6.11.0",
    "babel-register": "^6.18.0",
    "babel-tape-runner": "^2.0.1",
    "colortape": "^0.1.1",
    "eslint": "^3.9.0",
    "eslint-config-google": "^0.7.0",
    "faucet": "0.0.1",
    "isparta": "^4.0.0",
    "nodemon": "^1.10.2",
    "proxyquire": "^1.7.10",
    "tap": "^7.1.2",
    "tape": "^4.6.2"
  }

**Comment by playground** [comment]
I think I found the issue.  Installing Fabricjs now pulls in canvas 1.6.4 which builds with nodeVersion 7.5.0

  "_from": "canvas@>=1.6.2 <2.0.0",
  "_id": "canvas@1.6.4",
  "_inCache": true,
  "_installable": true,
  "_location": "/canvas",
  "_nodeVersion": "7.5.0",
  "_npmOperationalInternal": {
    "host": "packages-12-west.internal.npmjs.com",
    "tmp": "tmp/canvas-1.6.4.tgz_1488134763111_0.7420994041021913"
  },
  "_npmUser": {
    "email": "linus@folkdatorn.se",
    "name": "linusu"
  },
  "_npmVersion": "4.1.2",
  "_phantomChildren": {},
  "_requested": {
    "name": "canvas",
    "raw": "canvas@^1.6.2",
    "rawSpec": "^1.6.2",
    "scope": null,
    "spec": ">=1.6.2 <2.0.0",
    "type": "range"
  },
  "_requiredBy": [
    "/",
    "/fabric"
  ],

Whereas my working project was using canvas 1.6.2, replacing node_modules with this canvas version fixed the issue and app runs without errors.  Is this a bug got introduced into fabricjs with the latest canvas update?

  "_from": "canvas@>=1.6.2 <2.0.0",
  "_id": "canvas@1.6.2",
  "_inCache": true,
  "_installable": true,
  "_location": "/canvas",
  "_nodeVersion": "6.7.0",
  "_npmOperationalInternal": {
    "host": "packages-18-east.internal.npmjs.com",
    "tmp": "tmp/canvas-1.6.2.tgz_1477855890935_0.3815066539682448"
  },
  "_npmUser": {
    "email": "linus@folkdatorn.se",
    "name": "linusu"
  },
  "_npmVersion": "3.10.7",
  "_phantomChildren": {},
  "_requested": {
    "name": "canvas",
    "raw": "canvas@^1.6.2",
    "rawSpec": "^1.6.2",
    "scope": null,
    "spec": ">=1.6.2 <2.0.0",
    "type": "range"
  },
  "_requiredBy": [
    "/"
  ],

**Comment by asturur** [comment]
is a node canvas installation issue, nothing to do with fabric itself.

**Comment by playground** [comment]
@asturur are you saying this is a node-canvas issue?

**Comment by playground** [comment]
This is actually an installation in fabricjs.  When will support for using [canvas-prebuilt](https://github.com/chearon/node-canvas-prebuilt/issues/4) be released?
My app is now broken when a docker image needs to be created. Is there an interim solution?

**Comment by asturur** [comment]
finishing work on text and releasing a fabric 2.0 alpha.

**Comment by playground** [comment]
@asturur is 2.0 available for me to try?

**Comment by silviolorusso** [comment]
Sorry, I'm still getting this error and have no idea how to avoid it (I'm using fabric@2.1.0 and canvas@1.6.9 on MacOS High sierra) Please help.
