### ISSUE TITLE
getPointer error Ungroup text and image object 

### ISSUE THREAD

**Issue by ucandoit1010** [kangax/fabric.js#3779]
## Version
1.7.7 , 1.7.6 , 1.7.5

## Test Case
pleash watch private video first
https://youtu.be/bfN1h_jN6fQ

my jsfiddle demo
https://jsfiddle.net/taiwanhotdog/57rxjucf/

## Steps to reproduce
1. click button 1
2. click button 2
3. drag and select text and image.
4. click button 3
5. select object.
6. click button 4 and then click text object.

## Expected Behavior
no error displayed
## Actual Behavior
click text object got error : Uncaught TypeError: Cannot read property 'getPointer' of undefined.

**Comment by ncou** [comment]
Hi,

Here is a working example : 
https://jsfiddle.net/57rxjucf/1/

Your group function is breaking the object because you need to use the "clone()" function on the object, not the fabric.utils.clone function.

**Comment by ucandoit1010** [comment]
Thank you sir !
