### ISSUE TITLE
Standard method of getting containing box?

### ISSUE THREAD

**Issue by Lee-Taylor** [kangax/fabric.js#3784]
I'm trying to see if there is a common way to get an object's "containing box"

I would like to be able to get the red boxes from the following:
![image](https://cloud.githubusercontent.com/assets/12070079/23967083/8547b166-09b5-11e7-8296-5dba7b9440f5.png)

I know about getBoundingRect, but this gives me the following red boxes : 
![image](https://cloud.githubusercontent.com/assets/12070079/23967118/a325ed1a-09b5-11e7-8f7b-3a9fa357a968.png)

I have added this question on StackOverflow
http://stackoverflow.com/questions/42800125/standard-method-of-getting-containing-box

Is there any way to get the containing box? I am trying to write some code to align multiple objects with each other, but without knowing their "top" or "left", e.g., this is not so straightforward. Other than writing code for each shape/object type, is there a standard way of doing this?

**Comment by asturur** [comment]
http://stackoverflow.com/questions/42800125/standard-method-of-getting-containing-box

we can continue here.
