### ISSUE TITLE
ToData url not works when using image pattern to IText 

### ISSUE THREAD

**Issue by yjose** [kangax/fabric.js#3785]
## Version
1.7.7
i use exemple in documentation
```
 function loadPattern(url) {
    fabric.util.loadImage(url, function(img) {
      text.fill = new fabric.Pattern({
        source: img,
        repeat: document.getElementById('repeat').value
      });
      canvas.renderAll();
    });
  }
```
## Jsfiddle
     https://jsfiddle.net/yjose/6c7u82vj/
## Expected Behavior
     generate png image 
## Actual Behavior
    Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

**Comment by asturur** [comment]
probably a crossOrigin issue.
Please provide a jsfiddle

**Comment by yjose** [comment]
hi @asturur   jsfiddle exemple :
https://jsfiddle.net/yjose/6c7u82vj/

**Comment by asturur** [comment]
https://jsfiddle.net/6c7u82vj/2/

the options are explained in the docs:

http://fabricjs.com/docs/fabric.util.html  search for loadImage

**Comment by yjose** [comment]
https://jsfiddle.net/yjose/6c7u82vj/3/
