### ISSUE TITLE
canvas.dodataURL is giving "canvas tainted" error on canvas created from datalessJSON

### ISSUE THREAD

**Issue by niyotaa** [kangax/fabric.js#3786]
## Version
1.7.6

## Test Case
http://jsfiddle.net/7gvJG/162/

## Steps to reproduce

run the fiddle example
## Expected Behavior

should be able to download the image
## Actual Behavior
giving this error

Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

**Comment by niyotaa** [comment]
Here are my CORS policy on amazon S3

<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
	<CORSRule>
		<AllowedOrigin>*</AllowedOrigin>
		<AllowedMethod>PUT</AllowedMethod>
		<AllowedMethod>POST</AllowedMethod>
		<AllowedMethod>GET</AllowedMethod>
		<AllowedMethod>HEAD</AllowedMethod>
		<MaxAgeSeconds>3000</MaxAgeSeconds>
		<AllowedHeader>*</AllowedHeader>
	</CORSRule>
</CORSConfiguration>

**Comment by niyotaa** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
	<CORSRule>
		<AllowedOrigin>*</AllowedOrigin>
		<AllowedMethod>PUT</AllowedMethod>
		<AllowedMethod>POST</AllowedMethod>
		<AllowedMethod>GET</AllowedMethod>
		<AllowedMethod>HEAD</AllowedMethod>
		<MaxAgeSeconds>3000</MaxAgeSeconds>
		<AllowedHeader>*</AllowedHeader>
	</CORSRule>
</CORSConfiguration>

**Comment by asturur** [comment]
please extract the image link from json and make a simple fiddle. if loadfromjson is failinh and cors are good, loading the image alone will work.
if it does not, is a cors problem

**Comment by niyotaa** [comment]
http://jsfiddle.net/7gvJG/163/

yes, i still have the same problem saying tainted canvas. 

Here is our cors policy on amazon bucket. can anyone please comment if they are good or anything needs to be changed?

<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
	<CORSRule>
		<AllowedOrigin>*</AllowedOrigin>
		<AllowedMethod>PUT</AllowedMethod>
		<AllowedMethod>POST</AllowedMethod>
		<AllowedMethod>GET</AllowedMethod>
		<AllowedMethod>HEAD</AllowedMethod>
		<MaxAgeSeconds>3000</MaxAgeSeconds>
		<AllowedHeader>*</AllowedHeader>
	</CORSRule>
</CORSConfiguration>

**Comment by niyotaa** [comment]
<CORSRule>
		<AllowedOrigin>*</AllowedOrigin>
		<AllowedMethod>PUT</AllowedMethod>
		<AllowedMethod>POST</AllowedMethod>
		<AllowedMethod>GET</AllowedMethod>
		<AllowedMethod>HEAD</AllowedMethod>
		<MaxAgeSeconds>3000</MaxAgeSeconds>
		<AllowedHeader>*</AllowedHeader>
	</CORSRule>

**Comment by niyotaa** [comment]
everything works in this example. http://jsfiddle.net/7Akuf/142/

i am not sure what is the error i am making

**Comment by asturur** [comment]
http://jsfiddle.net/7gvJG/165/

you have to load an image as crossorigin, setting the header on server is not enough.

**Comment by niyotaa** [comment]
thank you for the help. yes that solved the issue.
