### ISSUE TITLE
allowTouchScrolling broken since 1.7.4

### ISSUE THREAD

**Issue by khmyznikov** [kangax/fabric.js#3789]
## Version
1.7.4 - 1.7.8

## Test Case
http://jsfiddle.net/e4fp9xts/3/

## Steps to reproduce
Try to scroll on touch device - android for example.

## Expected Behavior
Successfully scrolled canvas inside small box.

## Actual Behavior
Nothing happened. You can scroll only through tiny invisible scrollbars like on PC. 

## Solution
Remove 'touch-action': 'none' line.

```
_applyCanvasStyle: function (element) {
            var width = this.getWidth() || element.width,
                height = this.getHeight() || element.height;

            fabric.util.setStyle(element, {
                position: 'absolute',
                width: width + 'px',
                height: height + 'px',
                left: 0,
                top: 0,
                'touch-action': 'none'
            });
            element.width = width;
            element.height = height;
            fabric.util.makeElementUnselectable(element);
        }
```

**Comment by asturur** [comment]
so that touch-action: none should be available just when allowTouchScrolling is false. Right?

And when we do canvas.set('allowTouchScrolling', bool) we should attach / detach that style property.

I try to support mobile, i have no devices to do that.
I do not want to bother with my phone really.

**Comment by khmyznikov** [comment]
@asturur Lack or bad mobile support its a bad idea in our time.

**Comment by asturur** [comment]
i m not superman!
when i ll get sone device i will spend time on it. i do not have any now.

**Comment by asturur** [comment]
to be handled in #3869
