### ISSUE TITLE
Flip Object

### ISSUE THREAD

**Issue by mariusturcu1** [kangax/fabric.js#3795]
## Version
1.7.6

## Test Case
https://ufile.io/206db

If you flip a object in x coordonate, after that select 2 or more objects, deselect, seems like flipX is 0 and flipY becomes 1... but the render is still good, only the controls are not good
Same problem using images or custom shapes

**Comment by asturur** [comment]
that is normal. When ungrouping fabric takes one of the possible math solution to your problem.

Probably a flipx can be represented with a flipy + a 180 rotation.

Nothing we are gonna change since is an edge case and transformations are equivalent.

**Comment by melvynhills** [comment]
I could fix this behaviour for my needs with these changes (not thoroughly tested yet).

As soon as flip values are changed, subtracting 180° from the angle and set back the original flip values seems to do the trick.

```javascript
fabric.Group.prototype.realizeTransform = function(object) {
  var matrix = object.calcTransformMatrix(),
      options = fabric.util.qrDecompose(matrix),
      center = new fabric.Point(options.translateX, options.translateY),
  // custom code start ------------------------------------------------------------------
      originalFlipX = object.flipX,
      originalFlipY = object.flipY;
  // custom code end ------------------------------------------------------------------

  object.flipX = false;
  object.flipY = false;
  object.set('scaleX', options.scaleX);
  object.set('scaleY', options.scaleY);
  object.skewX = options.skewX;
  object.skewY = options.skewY;

  // custom code start ------------------------------------------------------------------
  if (originalFlipX !== object.flipX || originalFlipY !== object.flipY) {
    object.flipX = originalFlipX;
    object.flipY = originalFlipY;
    options.angle -= 180;
  }
  // custom code end ------------------------------------------------------------------

  object.angle = options.angle;
  object.setPositionByOrigin(center, 'center', 'center');

  return object;
};

```
