### ISSUE TITLE
Styles not updating correctly since 1.7.7

### ISSUE THREAD

**Issue by mlev** [kangax/fabric.js#3796]
I've started to get some weird text style behaviour since 1.7.7. This can be reproduced in Kitchen Sink Demo.

- Some styles are retained when you select and type over text
- Applying styles like bold/italic apply to an entire text block rather than the selected character

See video below for a demo.

## Version
1.7.7+

## Steps to reproduce
![fabric_styles](https://cloud.githubusercontent.com/assets/3466386/24230674/67d7d91a-0fd4-11e7-87f6-fa0e68abac51.gif)

**Comment by asturur** [comment]
can you describe better the input sequence?

**Comment by mlev** [comment]
Here are the steps to reproduce:
- Select all of the text in the textbox shown from Kitchen sink demo
- Type over the selection entering multiple lines (Problem 1: Lines 2 and 3 are blue)
- Select one letter of the second line and apply Bold styling (Problem 2: Bold is applied to all of lines 2 & 3 not just the selected character.
- Enter a new line between 2 and 3. Select a character and remove bold style. (Problem 3: Bold removed from entire line)
