### ISSUE TITLE
Place holder functionality in new itext module rewrite

### ISSUE THREAD

**Issue by ajck** [kangax/fabric.js#3797]
Just thought I'd ask :) @asturur, as new text module is being written as the moment.

It would just mean a placeholder text (e.g. "Enter text" in e.g. light grey colour) was displayed in empty ITexts which would disappear as soon as any characters are typed, and reappear if user deletes all the characters in the IText. Placeholder text and the colour would be defined in the IText call.

Thanks.

**Comment by asturur** [comment]
this is a specific application functionality that we do not want to support.
Try to implement with subclassing and ask help on stackoverflow if there is something that is hard to do.
You can ping me directly as @AndreaBogazzi
