### ISSUE TITLE
Carriage return with space are inserted instead of space for inline text editing in Google Crome v57

### ISSUE THREAD

**Issue by pavelKozlov** [kangax/fabric.js#3798]
This bug can be reproduced only with Google Chrome version 57.
I did some investigation and looks like this bug appears for any fabricjs version starting from 1.6.0. 

## Version
fabricjs >= 1.6.0
Google Chrome 57

## Test Case
works ok: https://jsfiddle.net/28sdvzoz/ with fabric 1.5.0
bug reproduces: https://jsfiddle.net/ttbsfgxt/ with fabric 1.6.0 and higher

## Steps to reproduce
1. set cursor anywhere in text but first and last position (e.g. in "Some text" string, set cursor after "m" character)
2. press and release space key

## Expected Behavior
Space is inserted and text becomes
"Som e text"

## Actual Behavior
Carriege return with space are inserted and text becomes
"Som
 e text"

**Comment by asturur** [comment]
is a chrome bug.
https://bugs.chromium.org/p/chromium/issues/detail?id=702926

would be nice to contribute to bug confirmation there after trying the fiddle i left.

Also there is a workaround in a branch called `newtext` here in the `initHiddenTextarea` function. grab the  style for the textarea from that function. i will hotfix in 1.7.9 as soon as i have some time.

**Comment by onassar** [comment]
@asturur which commit in `newtext` branch addresses this Chrome bug?

**Comment by asturur** [comment]
i committed lot of stuff all togheter.
check the function `initHiddenTextarea` and pick up updated style for textarea

**Comment by onassar** [comment]
Can you point me to the file where I can view the code?

**Comment by asturur** [comment]
![image](https://cloud.githubusercontent.com/assets/1194048/24257769/fd6b166a-0feb-11e7-84ac-e92c67c89082.png)

**Comment by pavelKozlov** [comment]
Changing width and height of hidden textarea from 0 to1 pix fixed the issue. Thanks, @asturur.

**Comment by onassar** [comment]
Thanks. Are you saying that the style `cssText` property having the value that it does fixes this Chrome bug?

**Comment by asturur** [comment]
you have also to use whitespace nowrap. changing width and height will just move the problem to more space pressed

**Comment by onassar** [comment]
Great thanks that fixed it for now. Hope Chrome fixes it soon as well

**Comment by rajdeeptayde** [comment]
> Changing width and height of hidden textarea from 0 to1 pix fixed the issue. Thanks, @asturur.

can you please specify your code I am getting th same issue ut i dont know how t solve it

**Comment by asturur** [comment]
this fix was inserted in the main library, you should not need it.
