### ISSUE TITLE
using div or other HTML element for controlling corners 

### ISSUE THREAD

**Issue by evolutionjay** [kangax/fabric.js#3800]
canvas obj controlling always has a problem:

<img width="461" alt="wx20170324-150647 2x" src="https://cloud.githubusercontent.com/assets/4468540/24284068/30f8e008-10a4-11e7-9f8e-98f393878d89.png">

can it be using  div or Other outside canvas for controlling the object. than we can fixed the problem  like this :

<img width="448" alt="wx20170324-150841 2x" src="https://cloud.githubusercontent.com/assets/4468540/24284076/3a7f2fce-10a4-11e7-83eb-3a2cb939f6f8.png">

**Comment by asturur** [comment]
hey @jay as a side note, the new text with good chinese/japanese support is ready.

outside canvas is not  possible to draw things. you can fake a bigger canvas with an opaque container for example.

**Comment by evolutionjay** [comment]
@asturur  I mean  change  the `controlling corners`  like this example 
[Fabric.js demos · Interaction with objects outside canvas](http://fabricjs.com/interaction-with-objects-outside-canvas)

```
the new text with good chinese/japanese support is ready.
 ```
This is awesome !!! 👍

**Comment by asturur** [comment]
I do not think the effort is worth. You can overlay some html div to make controls on the object. but then you have to emulate all the controls, is very hard.

You can still draw a bounding box using the object.getCenter() + canas offset to know where to position the div and the object.angle to set some css transform and rotate it.

Or simpler you can draw an svg using the 4 object.oCoords().

Nothing we want to support really out of scope.

**Comment by zhengjunxin** [comment]
@asturur Is there any other way to operate the controller besides creating a large canvas?
