### ISSUE TITLE
Shadows are clipped within the objects container - see screenshot

### ISSUE THREAD

**Issue by jonofarrow** [kangax/fabric.js#3805]
I just updated to 1.7.9 (custom build) and noticed that when I apply shadow the shadow is clipped inside of the objects bounding rect. please help! my apps depend on this.

<img width="285" alt="screen shot 2017-03-25 at 4 05 41 pm" src="https://cloud.githubusercontent.com/assets/4098006/24326119/62d249da-1175-11e7-8ef6-d2d766a59bb8.png">

**Comment by jonofarrow** [comment]
I just need a version with working shadows, gesture support, and the calcTransformMatrix function. Please help!

**Comment by jonofarrow** [comment]
fixed this issues with objectCaching = false;
not sure if this is the correct way though.

**Comment by asturur** [comment]
shouldn't.

how does it look like the shape without shadow? can you paste the path here?

**Comment by jonofarrow** [comment]
The shape looks fine without shadow. Its an svg inside of a pathgroup.
"m 337.73381,606.24658 c 0,0 -26.1194,18.20213 -26.1194,40.45033 0,13.71457 12.08239,19.47772 15.16172,29.96447 4.67449,16.26511 -13.77343,21.31878 -21.51213,12.27265 -5.28932,-6.55521 -9.51528,-31.81849 -9.51528,-31.81849 0,0 -10.89316,15.27077 -11.75315,27.97313 -0.86,12.70237 2.14767,24.22297 9.77359,32.75836 7.62592,8.5354 22.00005,14.77452 36.89203,11.52303 14.89198,-3.25145 32.15841,-13.96628 33.19197,-40.14277 0,-24.92451 -29.39479,-43.85285 -31.66691,-60.79056 -2.27208,-16.9377 5.54756,-22.19015 5.54756,-22.19015 z"

**Comment by asturur** [comment]
i need to see your fabric code

**Comment by blobinabottle** [comment]
I have a bug similar. Shadows behave weird if applied to a group and if you group select 2 or more objects. You can see it here: 
http://jsfiddle.net/7gvJG/169/

![screen shot 2017-03-30 at 10 42 10](https://cloud.githubusercontent.com/assets/8090162/24495544/c87cd1b0-1535-11e7-9d52-d9d96ddaa99f.png)

**Comment by asturur** [comment]
this last one is a bug.

**Comment by blobinabottle** [comment]
Do you want me to create a new github issue just for that bug? Or is it already ongoing? Don't hesitate to ask, if I can help you.

**Comment by asturur** [comment]
i need to update the caching logic. if a group has a child with shadow with offsets different from 0, the group cannot be cached.
