### ISSUE TITLE
DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported

### ISSUE THREAD

**Issue by halilozanyilmaz** [kangax/fabric.js#3810]
Hi All,

I am using fabricjs 1.2.0 and having this issue. Can you help me?

Details: 
http://stackoverflow.com/questions/43090008/domexception-failed-to-execute-todataurl-on-htmlcanvaselement-tainted-canv

**Comment by asturur** [comment]
no. on 1.2.0 no.

crossOrigin was not implemented maybe, please  upgrade to 1.7.9

i ll help you upgrade in case
