### ISSUE TITLE
Uncaught TypeError: Cannot create property 'style' on string 'wtd_background_image'

### ISSUE THREAD

**Issue by halilozanyilmaz** [kangax/fabric.js#3811]
My plugin works with fabric.js 1.2.0, When I change it to work with fabric.js 1.7.9 then it throws the error:

> Cannot create property 'style' on string 'wtd_background_image'

on the following line:

`  canvasObj= new fabric.Canvas('wtd_background_image');`

What should I do? 

![image](https://cloud.githubusercontent.com/assets/25062864/24456355/6f769e56-149b-11e7-9b23-5a8d268b8e63.png)

Please let me know if you need more details

**Comment by asturur** [comment]
wtd_background_image  is the id of a canvas right?

**Comment by halilozanyilmaz** [comment]
yes, I have realized that this function is inside

`jQuery(document).ready(function()`

and it was initiated to work in all pages, I understand that it is not working in 1.7.9 because there is no "wtd_background_image" on the pages other than the plugin page, however It is still a mystery for me why it was not giving an error while using 1.2.0.

I have solved the issue by adding an if statement to make the plugin work only on plugin's default page where wtd_background_image exists.

**Comment by asturur** [comment]
Probably a statement like your was in earlier version of fabric.
I do not remember but if i found it, i for sure removed it.
The api is clear, you need to send an id of a canvas or a canvas, so we
should not check that you did it properly.

Let me know if you have more issues. 1.2.0 was a long time ago, and we did
not use semver before, and we use it loosely now.

2017-03-30 10:21 GMT+02:00 halilozanyilmaz <notifications@github.com>:

**Comment by aspentreemedia** [comment]
I ran into this tonight on an angular app, I was attempting to use a fabric canvas in a popup and if I tried to use the fabric canvas too early I would get this error. So I had to make sure the popup was ready before attempting to instantiate the fabric canvas.

**Comment by maxhudson** [comment]
@aspentreemedia has identified the source of this issue correctly. Appending DOM elements can be asyncronous because of the render frame they need (see first comment here: https://stackoverflow.com/questions/6068955/jquery-function-after-append).

One solution could be waiting for the element to be added with `requestAnimationFrame` or `setTimeout`, but those are not synchronous.

However, a better solution that I seem to have stumbled upon, is appending the `canvas` element to the body (which is instant + fully synchronous for some reason):

```javascript
var $canvas = $('<canvas width="0" height="0" id="cvs">');

document.body.appendChild($canvas[0]); //Hack to get fabric to play along

var fabricCanvas = new fabric.Canvas('cvs');

$('some element inside <body>').append(fabricCanvas.wrapperEl);
```
