### ISSUE TITLE
Possible 'object:selected' event problem.

### ISSUE THREAD

**Issue by JerrodV** [kangax/fabric.js#3812]
Hello all,
 I think I might have found a bug in the newest(1.7.8) version.

The issue is present in the following Fiddle: [https://jsfiddle.net/awnue417/](https://jsfiddle.net/awnue417/)

Briefly, when a group is being created by holding the shift key and clicking canvas objects, the event data passed in the object:selected function is not present after the first object is added to the group (or the second item you click on while forming the group). The target data is, of course, but I am not, for instance, able to check the event and see if the alt key was being pressed while the group is being formed.

It seems to me that some of the data passed in that mouse-down event would be pretty important. 

Thanks,
Jerrod

**Comment by asturur** [comment]
ok i will check it.

**Comment by JerrodV** [comment]
I found a little time to run a test against the now latest version 1.7.9 and the problem still seems to be there.
[jsfiddle.net/Jevolz/pj5jg5Le/1/](https://jsfiddle.net/Jevolz/pj5jg5Le/1/)

**Comment by JerrodV** [comment]
Thanks for following up. :)
