### ISSUE TITLE
Font Family does not work at first time in MAC System Safari.

### ISSUE THREAD

**Issue by mukeshcp** [kangax/fabric.js#3813]
Hi,
I have checked in fabric version 1.5 & 1.6.2  in my project. But while change fontFamily at first time, it does not work in MAC System Safari. Text does not effected at first time. if we change same font at second, then it will work.

I have also checked Kitchensink Demo - http://fabricjs.com/kitchensink  . Same Issue happen in it.

kangax @ can you please do needful for it ?

Anybody - Please Do needful to fix this issue.

![mac_safari_fontfamilyissue](https://cloud.githubusercontent.com/assets/12266888/24493638/1f67699c-154d-11e7-9060-eecdfb8f703b.png)

**Comment by asturur** [comment]
you have to wait for font load.
The kitchensink demo is a lazy demo that does not do it.

use a font loader such as fontfaceobserver or the fontload api from browser

**Comment by mukeshcp** [comment]
asturur @ But it works in other browsers like mozilla & chrome.

**Comment by asturur** [comment]
because they are bit faster in setting the font on canvas. is not a fabric bug nor something i can fix sadly

you have to ensure the font is loaded before drawing

**Comment by mukeshcp** [comment]
asturur, thank a lot for providing info.
