### ISSUE TITLE
Font color difference between browser and node-canvas

### ISSUE THREAD

**Issue by antucg** [kangax/fabric.js#3814]
Hello guys, I am working on an application that uses fabricjs and node canvas. In the browser we are using fabricjs to create some images. In the backend we use fabric + node-canvas to generate those images. One of the issues I have detected is that the color of the font is slightly different between both platforms. The format of the color is rgb(r,g,b).
In the frontend I use fabric (1.7.6), Chrome and is running on OSX.
In the backend I use fabric (1.7.6), node-canvas (1.6.4) and is running on Linux.
My guess is that the difference is because of the frontend uses HTML canvas, and backend uses node-canvas with cairo, pango, etc.
Has anybody else observed this problem before? Is there a way of avoiding it?

Thanks.

**Comment by asturur** [comment]
please post a screenshot, code of image export ( format, compression? )
Post the file produced by node-canvas and the file produced by the app canvas.

thanks

**Comment by antucg** [comment]
Screenshot from the browser canvas:
![screen shot 2017-03-30 at 09 33 38](https://cloud.githubusercontent.com/assets/2089578/24495171/484604a2-152c-11e7-86d1-9ae7386353a1.png)

When I use the Digital Color Meter from OSX and I hover the red color I get: R: 205, G: 51, B: 51.

Generated image (PNG):
![b83ace70-148f-11e7-b965-230bfaac25c0](https://cloud.githubusercontent.com/assets/2089578/24495335/b6e7436c-152c-11e7-98bc-2bdb4279c3ad.png)

When I use the Digital Color Meter from OSX and I hover the red color I get: R: 201, G: 49, B: 53.

**Comment by asturur** [comment]
this in macos happens across safari/chrome/firefox?

i m wondering if there is some color correction happening from the OS for some weird reason.

The other culprit can be png compression code.
You did not tell yet wich is the correct one. what do you set text.fill to?

**Comment by antucg** [comment]
Text fill is set to #CD3333. There is no correct and wrong. The first one is what I see in the canvas. The rgb for that is 205,51,51. The second one is the actual PNG, generated with node-canvas. If I open both images in photoshop, colors match. If I use the preview and Digital Color Meter tool from OSX then both colors don't match.

**Comment by asturur** [comment]
Yes there is correct and wrong.
if you set #CD3333 and you get 205,51,51, that is correct. the other rgb is wrong.

So if photoshop is opening the both PNGS ( from canvas and node ) and using a colorpicker you get the correct value, there is no issue for fabric/node.

I have no idea what a digital color meter is... is a software or an hardware tool?

**Comment by antucg** [comment]
Is a software tool to capture colors from the content of the screen. The thing is that Photoshop displays the colors correctly. But in the preview they are not. Anyway I think thare are too many variables here, how browser renders color, how photoshop renders colors and how preview renders colors. So I think that given that photoshop is ok I can skip this for now.

Thanks for the quick replies!!

**Comment by asturur** [comment]
please deactivate macosx color.correction on screen, the color profile. i guess it will normalize it
