### ISSUE TITLE
Bug on action inside _getActionFromCorner object extension

### ISSUE THREAD

**Issue by Rqplo** [kangax/fabric.js#3815]
Hello, I think I encounter a bug when extending fabricjs objects.

**## Version**
1.7.9 but the issue seems to be present since the 1.6.3 version.

**## Test Case**
https://jsfiddle.net/wsnsd9gd/ on 1.7.9
https://jsfiddle.net/wsnsd9gd/1/ on 1.6.2

**## Steps to reproduce**
Just click on the bottom left corn to see the issue.

**## Expected Behavior**
Normally, this should erase the object.

**## Actual Behavior**
In fact, the object is removed from the canvas when I look at the console, but I need to click inside the canvas for the deletion be visually effective.

I hope not to look stupid by having posted this, I do not have great programming skills so really sorry if it is not a real bug.

See you soon, Rqplo.

**Comment by asturur** [comment]
the extension is not supported directly by us.
Probably we still need the canvas reference for some mouseup actions after the object has been removed. no idea how to help.
