### ISSUE TITLE
 for android wechat,  touch will timout

### ISSUE THREAD

**Issue by LemonStudioZeus** [kangax/fabric.js#3817]
for android wechat,  touch will timout,

 should add  e.preventDefault() in __gesturesRenderer

code:

__gesturesRenderer: function() {

             if (this.__gesturesParams === null || this._currentTransform === null) {
                 return;
             }

             var self = this.__gesturesParams.self,
                 t = this._currentTransform,
                 e = this.__gesturesParams.e;

             e.preventDefault();  // should add 

             t.action = 'scale';
             t.originX = t.originY = 'center';
             this._setOriginToCenter(t.target);

             this._scaleObjectBy(self.scale, e);

             if (self.rotation !== 0) {
                 t.action = 'rotate';
                 this._rotateObjectByAngle(self.rotation, e);
             }

             this._setCenterToOrigin(t.target);

             this.renderAll();

             t.action = 'drag';
         },

**Comment by asturur** [comment]
i m sorry i have no idea what is android wechat... can you please be more specific?

**Comment by LemonStudioZeus** [comment]
http://www.wechat.com/en/

**Comment by asturur** [comment]
to be handled in #3869.
