### ISSUE TITLE
drawBorders() and drawBordersInGroup() broken is called directly

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3818]
Hi,

These 2 public functions doesn't work if you call them for the given object.

The border is always draw on the top left of the canvas. It seems to me it's because there is a missing translation for the viewport.

The renderControls is correctly positionned because the instruction "translate" (based on the matrix viewport) is used :

`ctx.translate(options.translateX,options.translateY);`

But this instruction is missing for the drawBorder() function so the positionning is false.

Hope i am clear enough. I can open a fiddle if necessary.

**Comment by asturur** [comment]
well drawborders  and drawcontrols, eveb if are public are really not meant to be called outside the render cycle. i will check what i can do if it is possible to make them self indipendendet i ll do.

**Comment by ncou** [comment]
Thank you, i think thoses functions are usefull if a user want to implement a "visual effect" when you hover an object with your cursor.

**Comment by asturur** [comment]
i would do this:

drawControls and drawBorders are  meant to be called in the rendering pipeline.
they exit automatically if you do not have controls or borders
they draw on the properties of the object.

_renderControls translates and rotates. drawBorders and drawControls just renders the box and the small controls.

i would move the early return check outside the functions.

so that fabric do not call _renderControls on an object if it is not active, but you can still call it.
you can still call drawBorders on an object without switching on and off the hasBorders property.

call just renderControls that do the translation and add a parameter to override the default value, soething like forceBorders, forceControls

**Comment by ncou** [comment]
Seems like a good idear.
If i understand in the v2.x of the library, it will be possible for example :

- to call on an object : object.renderControls(forceBorders:true, forceControls:false) to display only the borders.
- to call object.renderControls(forceBorders:false, forceControls:false) to hide the borders of this same object.

And in anycase when the mouse is hovering an object the actual renderControls will be called (with or without borders and controls depending of the original settings for this object).

Does the drawControls and drawBorders will be moved as private functions (renamed with an "_" at the beginning of the function name) ?

In any case thank you for your work.

**Comment by asturur** [comment]
so the obejcts controls will render normally during the normal interaction with mouse and selections.

if you want to make extra drawing on mouse over for example, you can call object.renderControls(....) to render something without doing:

```
objectOriginalHasControls = object.hasControls
object.hasControls = false
object.renderControls()
object.hasControls = objectOriginalHasControls
```
for the method name with or without the lower dash, i have to see how much time it takes.
I do not really care to put it in front as long as i can add in the docs the specification `@private`. Those are not really private methods, are more things that do not work as expected if used by the dev.

For sure something that i should improve.

**Comment by asturur** [comment]
this is a starting idea #3887

**Comment by ncou** [comment]
good news i will try the compiled once it's merged in the dist folder.

**Comment by ncou** [comment]
I could build successfully build the lib from the controls_test branch and do a test.

i do something like this :

`
canvas.on('mouse:over', function(e) {

			  	setTimeout(function() {
			  		var object = e.target;
			  		if (object) {
						object._renderControls(canvas.contextTop); 
						canvas.contextTopDirty = true;					
					}
			  	}, 125);	
			});

			canvas.on('mouse:out', function(e) {
			  	canvas.renderTop();
			});
`
I needed to use a setTimeout at 125ms, because if i move some other objects there is bunch of renderAll who are waiting to be executed so in some case if i move an object and quickly mouseover another object, the borders are cleared by the renderAll().

PS : I use a renderTop() to clear the borders when the mouse is out.

Is my implementation on the right way ?

Thanks.

**Comment by asturur** [comment]
one way can be this:
```
canvas.on('after:render', function() {
  if (this._hoveredTarget) { this._hoveredTarget._renderControls(this.contextContainer);
}
});

canvas.on('mouse:over', function() {
 canvas.renderAll();
});

canvas.on('mouse:out', function() {
 canvas.renderAll();
});
```

another could be

```
canvas.on('mouse:over', function(opt) {
 if (opt.target) {
opt.target._renderControls(this.contextContainer);
}
});

canvas.on('mouse:out', function() {
 canvas.renderAll();
});
```

or

```
canvas.on('mouse:over', function(opt) {
 if (opt.target) {
opt.target._renderControls(this.contextTop);
}
});

canvas.on('mouse:out', function() {
 this.clearContext(this.contextTop);
});
```
they all work with latest branch

**Comment by asturur** [comment]
```
canvas.on('mouse:over', function(opt) {
 if (opt.target) {
opt.target._renderControls(this.contextContainer);
}
});

canvas.on('mouse:out', function() {
 canvas.renderAll();
});
```

i guess this one is the best. drawing on contextTop gives weird result when dragging the object
