### ISSUE TITLE
unused var in the group object 'originalState'

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3819]
Hi,

Not a bug, but there is still a var named "originalState" in the "Group" object.
This var is not used (since the cleaning for using "_stateProperties" instead of "originalState").

Have a good day.

**Comment by asturur** [comment]
@ncou could you double check and in case open a pr to remove it? if tests passes is ok.

**Comment by ncou** [comment]
Hi,

I do the pull request, i couldn't made the test run.
I installed the qunit module + jsdom and used "npm test" as indicated in the wiki for the contribution, but i got an error [Error: Cannot read property 'devicePixelRatio' of undefined].

I still got the error with and without my modification.

If i look at the pull request panel, it looks like there is automaticly a build for the travis CI test. So i suppose i don't need to run them localy ?

**Comment by asturur** [comment]
normally you would. I can run them locally, but i have to reinstall/rebuild when i switch between master branch and 1.7.9
