### ISSUE TITLE
run time Error?

### ISSUE THREAD

**Issue by evolutionjay** [kangax/fabric.js#3820]
## Dev Error

I try to run a fabric demo on my windows platform via webpack, and when I installed fabirc and ran `npm run dev`, I suggested this, but after I installed the components, I still can not run it. What is the reason?

```bash
 ERROR  Failed to compile with 4 errors

These dependencies were not found:

* jsdom in ./src/assets/fabric.min.js
* canvas in ./src/assets/fabric.min.js
* fs in ./src/assets/fabric.min.js
* xmldom in ./src/assets/fabric.min.js

To install them, you can run: npm install --save jsdom canvas fs xmldom
> Listening at http://localhost:8080
```

**Comment by asturur** [comment]
@evolutionjay what node version and fabric version are you using?
