### ISSUE TITLE
Fabric hosted in Android WebView misses touch events sporadically

### ISSUE THREAD

**Issue by daveespo** [kangax/fabric.js#3822]
## Version
1.7.9 (the current version being hosted in the demos)

## Test Case

When loading the following URL on the Chrome (or system) Web Browser on Android (Marshmallow, Nougat, etc), the ability to use a stylus to capture handwriting is responsive and accurate

http://fabricjs.com/freedrawing

However, loading the same URL in a Cordova or other Android app that hosts an android.webkit.WebView, the same implementation of FabricJS loses glyphs when writing with a stylus

This is a sample Android app that loads the same URL:

AndroidManifest.xml
````
<?xml version="1.0" encoding="utf-8"?>
<manifest package="xyz.web"
          xmlns:android="http://schemas.android.com/apk/res/android">

	<uses-permission android:name="android.permission.INTERNET" />
	<application
		android:allowBackup="true"
		android:icon="@mipmap/ic_launcher"
		android:label="@string/app_name"
		android:roundIcon="@mipmap/ic_launcher_round"
		android:supportsRtl="true"
		android:theme="@style/AppTheme">
		<activity android:name=".MainActivity">
			<intent-filter>
				<action android:name="android.intent.action.MAIN"/>

				<category android:name="android.intent.category.LAUNCHER"/>
			</intent-filter>
		</activity>

	</application>

</manifest>
````

activity_main.xml
````
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
	xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:app="http://schemas.android.com/apk/res-auto"
	xmlns:tools="http://schemas.android.com/tools"
	android:layout_width="match_parent"
	android:layout_height="match_parent"
	tools:context="xyz.web.MainActivity">

	<WebView
		android:id="@+id/web_view"
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		tools:layout_editor_absoluteX="8dp"
		tools:layout_editor_absoluteY="8dp"/>

</LinearLayout>
````

MainActivity.java
````
package xyz.web;

import android.app.Activity;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.Window;
import android.webkit.WebChromeClient;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity {

	private WebView webView;
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);

		getWindow().requestFeature(Window.FEATURE_PROGRESS);

		setContentView(R.layout.activity_main);
		webView = (WebView)findViewById(R.id.web_view);

		webView.getSettings().setJavaScriptEnabled(true);

		final Activity activity = this;
		webView.setWebChromeClient(new WebChromeClient() {
			public void onProgressChanged(WebView view, int progress) {
				// Activities and WebViews measure progress with different scales.
				// The progress meter will automatically disappear when we reach 100%
				activity.setProgress(progress * 1000);
			}
		});
		webView.setWebViewClient(new WebViewClient() {
			public void onReceivedError(WebView view, int errorCode, String description, String failingUrl) {
				Toast.makeText(activity, "Oh no! " + description, Toast.LENGTH_SHORT).show();
			}
		});


	}

	@Override
	protected void onResume() {
		super.onResume();
		webView.loadUrl("http://fabricjs.com/freedrawing");
	}
}
````

Below are two screen shots from my brand new Samsung Galaxy Tab S3 (though these results have been achieved using a Google Nexus 9 and a few other tablets as well). You'll see how many characters were dropped as I wrote. (pardon the sloppy handwriting .. it should be "How much wood could a woodchuck chuck if a woodchuck could chuck wood?")

## WebView (dropped glyphs)
![fabricjs in android webview](https://cloud.githubusercontent.com/assets/233309/24629598/94cb4a5e-1887-11e7-8366-13ac7b4c8609.jpg)

## System web browser (no problems)
![fabricjs in system web browser](https://cloud.githubusercontent.com/assets/233309/24629604/98dff8ce-1887-11e7-98cb-0f2e9b85f80d.jpg)

Additionally, I created a version of your Demo site that was a 2 liner to make sure that there wasn't other javascript running on the page that could be affecting performance. No dice. Even with a stripped down page such as this, it still exhibited the dropped characters:

````
<script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.7.9/fabric.min.js" type="application/javascript"></script>
<canvas id="c" width="1000" height="600" style="border:1px solid blue;"></canvas>

<script>
	(function() {
		var $ = function(id){return document.getElementById(id)};

		var canvas = this.__canvas = new fabric.Canvas('c', {
			isDrawingMode: true,
      allowTouchScrolling: false,
		});
	})();

</script>
````

How can I help debug this further? Is there an event listener that I can add to try to detect which events are being omitted in a clean room test?

**Comment by daveespo** [comment]
One further note: We have not observed the same problem in iOS/Cordova. We have a few happy users that use their Apple Pencil to write on a Fabric canvas inside of our Cordova app. This problem is isolated to Android.

**Comment by asturur** [comment]
how is hard to make an apk from a local copy of kitchensink? html + js.
we should start from there to debug those things

**Comment by daveespo** [comment]
Is there a way to download an encapsulated version of kitchensink? I tried saving the demo site at http://fabricjs.com/kitchensink using Chrome to the local file system but there are too many external dependencies to get it to be fully functional.

**Comment by asturur** [comment]
i would build a script that from the website repo can build the apk. is this doable?
If we cannot test the apk on dev code, so changing events and stuff and repackaging fast, this is very hard to do.

you can clone the repo fabricjs.com. on mac osx is very easy to get the site up and working on localhost.

**Comment by daveespo** [comment]
It sounds like you'd like all of the resources (javascript and HTML) to be loaded from a remote host vs. compiled directly into the Android APK binary

If so, this is easy -- I forked the fabricjs.com github repo and had to doctor up a bunch of absolute URLs in the project so that kitchensink would boot successfully here:

https://ninesummer.github.io/fabricjs.com/kitchensink

I've compiled an APK for the Android app -- you should be able to install it directly onto your tablet once you enable the 'install untrusted apps' setting in Settings

https://github.com/ninesummer/aloe-webview/blob/master/fabric.apk

When the app boots, it loads the above URL and you can compare the behavior writing with a stylus within the Android app vs. loading the same URL in the system browser on Android

Additionally, I've granted you committer access to our fork of the fabricjs.com repo so that you can make any changes for debugging you wish

**Comment by daveespo** [comment]
Just checking in to see if you've had any luck reproducing the issue given the materials I provided -- or any further instrumentation you can suggest for narrowing the root of the problem?

As a comparable, we are seeing no lost glyphs when trying out the PaperJS demo here within the Android WebView: http://paperjs.org/examples/path-simplification/

**Comment by asturur** [comment]
this last two weeks i did not have time to work on fabricjs. the issue count is over 200 while normally is between 170 and 180. i have to catch up yet.

**Comment by homerlex** [comment]
I have a [PR](https://github.com/kangax/fabric.js/issues/3860) that fixes this behavior.  One thing to note is that I could duplicate the problem in the standard Chrome browser on Android.  With the patch, free drawing works much better in Chrome and in the webview.

The "system web browser" that @daveespo talks about is the "Samsung Internet Browser" (5.2.02-94).  That browser did not exhibit the same problem as the Chrome browser.

**Comment by asturur** [comment]
to be handled in #3869

**Comment by Argon2-ffi** [comment]
@asturur https://lnkr.fun/ef7eb0e
