### ISSUE TITLE
Changing object Fill, Transparency, Text Font Styles ( Color , Alignment, Font Style, Size ), Layer Ordering (Send To Back, Bring To Front, etc...) do not trigger "object:modified"

### ISSUE THREAD

**Issue by Jplus2** [kangax/fabric.js#3823]
## Version
1.7.9

## Test Case
I'm trying to create an undo capability with a current fabric.js based app I am currently working on and I found out that some "state changes" to elements are not firing "object:modified" ( check the title of these state changes.

However the state changed is persisted on the object ( the object data is actually changed ) but for some reason, I checked fabric code, its not firing "object:modified" on these instances, ex. _setFillStyles (correct me if I am wrong but I assume this is the code in charge of setting fill styles? 

I need that trigger fired for me to know when an object is "modified" so I can adjust or add the old state data to the history stack.

## Expected Behavior
Whenever those canvas element state are changed, "object:modified" should be fired.

## Actual Behavior
Its not firing

**Comment by ncou** [comment]
the object:modified is fired if you change the object using the controls.
Else you could activate the param "stateful : true" (by default it's set to false) on the canvas, and the event will be triggered if a property in the "stateProperties" list is modified (there is opacity, fill....etc).

**Comment by asturur** [comment]
exactly, thanks @ncou
I do not suggest you to do that since is costly for your app.
Since you change that props with your own code, please just do `object.fire('modified')` by yourself

**Comment by Jplus2** [comment]
Doesn't seem to work even though I set the stateful poperty to true on canvas

`canvas = new fabric.Canvas( 'canvasid' , { stateful : true } );`

Ive changed one of the shapes fill color and "object:modified" still isn't fired.
am I missing anything?

**Comment by ncou** [comment]
strange. i will try do do a fiddle to reproduce this behavior if i found time during the weekend.

**Comment by asturur** [comment]
@ncou can i have your email?

**Comment by ncou** [comment]
@asturur i send you an email on your gmail adress. Let me know if you doesn't receive it.

**Comment by asturur** [comment]
@Jplus2  yes, it will fire modified just after you end a transformation. 
It i will not fire modified setting a property.
Since you set a property, you can fire the event by yourself.

**Comment by Jplus2** [comment]
Ah ok so mutating object property wouldn't trigger or fire "object:modified".
Any chance of adding that in the future? Seems to make sense right?
Anyways thanks for the clarification @asturur 
Thanks for the help too @ncou
