### ISSUE TITLE
High CPU usage in custom animated component

### ISSUE THREAD

**Issue by solomax** [kangax/fabric.js#3824]
Question on StackOverflow: http://stackoverflow.com/questions/43154142/high-cpu-usage-in-custom-animated-component

## Version
1.7.8

## Test Case
http://jsfiddle.net/solomax666/x0zbz3sm/

## Steps to reproduce
 - Open Google Chrome task manager, sort by CPU
 - Create multiple pointers using JsFiddle above
 - wait until all disappear

## Expected Behavior
CPU usage is minimal after there is no objects on the canvas

## Actual Behavior
Both CPU and GPU usage is high

**Comment by ncou** [comment]
Hi,

In your fiddle you do 2 times the renderAll() function, for each animation.
You can remove one "onChange" instruction and all will work the same and with less CPU.

You call an animation while the animation is running perhaps it's mess with the "cancelAnimationFrame" function.

In your case, you should look at the demo http://fabricjs.com/particles
There is separation beetween the object positionning and the repaint.

**Comment by solomax** [comment]
Thanks a lot for the review @ncou,
I need to animated circles in the group,
I'm newbie (using this library for 2 weeks)
As I understand I need to implement my own animate method, instead of using internal one?
Maybe you can help me with this?

**Comment by asturur** [comment]
i m happy to help you reduce the fiddle to something very simple, like a couple of animating object.
Define what you mean by usage high please.

**Comment by solomax** [comment]
Thanks a lot!
In current fiddle I'm creating multiple pointers (10-20)
Wait until all disapper
Open Google Chrome task manager and check Fiddle Tab CPU usage
its 15-18% (both CPU and GPU) while None objects are on the canvas .....

**Comment by asturur** [comment]
but can you simplify the fiddle so that you obtain that same problem with just animating objects and not mouse up and mouse down interactions?

**Comment by solomax** [comment]
Sure, here you are: http://jsfiddle.net/solomax666/esdjdx8x/
Thanks in advance!

**Comment by asturur** [comment]
http://jsfiddle.net/esdjdx8x/3/  i remove the useless stuff ( image, text, originX and originY).
The problem looks like the animation is still going ( empty ) for the empty canvas. Since no one stopped it.

The problem is a general programming problem. at cnt < 1 you remove the group from canvas, but you start another animation and you for cnt 0, cnt -1, cnt -2, cnt -3 .... till end of days.
Adding an else in the animation code fixes the cpu usage

**Comment by solomax** [comment]
Thanks a million @asturur!
You save my day :)
