### ISSUE TITLE
Get content bounding box rather than selection box(actual drawing area)

### ISSUE THREAD

**Issue by vijaygurjar** [kangax/fabric.js#3825]
Hello,

I need help regarding object bounding box. Currently fabricjs provide selection bounding box. Is there any way to get content bounding box(only drawing area) of each and every objects of canvas(like Textbox, shape). 

Regards,
Vijay

**Comment by asturur** [comment]
can  you provide an example?

**Comment by vijaygurjar** [comment]
Hi asrutur,

[](http://jsfiddle.net/vijaygurjar/yjg7j5Lh/ )

in this example when object selection box goes outside canvas then selection box border set to red.
But i need when text box content goes to outside canvas then selection border set to red.
Rather then selection box i need warning on text content(in rotation case also).

**Comment by asturur** [comment]
oh ok, that is not a thing we do here, helping with custom app code, unless there is some general utility for fabricjs. Text bounding box is square, and is as large as you pull it, there is no code to know how big is text. You can inspect this._lineWidths[index] but it will require some custom work

**Comment by vijaygurjar** [comment]
Thanks asturur,
I have done it for text element without rotation stage, but object is rotated then calculation goes to wrong.

**Comment by asturur** [comment]
http://stackoverflow.com/questions/42800125/standard-method-of-getting-containing-box/42830279#42830279

i wrote this so answer some time ago, give it a check. you should be able to use it using the real text width instead of box width

**Comment by vijaygurjar** [comment]
Thanks for your help may be it helps me
