### ISSUE TITLE
Reserved key word char used as variable in code in several placed, needs to be changed to _char as done in the rest of the code. Prevents YAI compiler from merging fabric_min.js

### ISSUE THREAD

**Issue by ricksturgeon** [kangax/fabric.js#3828]
## Version
1.7.6

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by ricksturgeon** [comment]
Reserved key word char used as variable in code in several placed, needs to be changed to _char as done in the rest of the code. Prevents YAI compiler from merging fabric_min.js

**Comment by asturur** [comment]
why did you close it? find solution?

**Comment by ricksturgeon** [comment]
I did not mean to close. It needs fixed. I edited the source and works fine, but you need to correct in about 10 places grouped in 2 routines

**Comment by ricksturgeon** [comment]
Do you want me to reopen it?
