### ISSUE TITLE
Reserved key word char used as variable in code in several placed, needs to be changed to _char as done in the rest of the code. Prevents YUI compiler from merging fabric_min.js

### ISSUE THREAD

**Issue by ricksturgeon** [kangax/fabric.js#3829]
## Version
1.7.9

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Steps to reproduce
Comple with YUI
## Expected Behavior
To Compile
## Actual Behavior[ERR] C2009: YUI Parse Error (invalid property

Reserved key word char used as variable in code in several placed, needs to be changed to _char as done in the rest of the code. Prevents YUI compiler from merging fabric_min.js

**Comment by asturur** [comment]
according to es5 specs char is not a reserved keyword. is more a  YUI bug than other.

i m open to change it as soon as i cleared the other bugs.

please check if yui can accept ecmascript version as argument

**Comment by ricksturgeon** [comment]
Here are the changes required in fabric.js
line 21932from:var shortM = method.slice(0, -4), char, width;to:var shortM = method.slice(0, -4), _char, width;

line 21945
from:char = chars[i];
width = ctx.measureText(char).width + additionalSpace;
ctx[method](char, left, top);to:_char = chars[i];
width = ctx.measureText(_char).width + additionalSpace;
ctx[method](_char, left, top);
line: 23389from:for (var j = 0, len = chars.length, char; j < len; j++) {
  char = chars[j];
  shouldFill && ctx.fillText(char, left + charWidth, top);
  shouldStroke && ctx.strokeText(char, left + charWidth, top);
  _charWidth = ctx.measureText(char).width + additionalSpace;
to:for (var j = 0, len = chars.length, _char; j < len; j++) {
  _char = chars[j];
  shouldFill && ctx.fillText(_char, left + charWidth, top);
  shouldStroke && ctx.strokeText(_char, left + charWidth, top);
  _charWidth = ctx.measureText(_char).width + additionalSpace;

as far as your question on yui and ecmascript I could not figure out the answer.
Thanks for fixing this.
Rick      From: Andrea Bogazzi <notifications@github.com>
 To: kangax/fabric.js <fabric.js@noreply.github.com> 
Cc: Rick Sturgeon <rick.sturgeon@yahoo.com>; Author <author@noreply.github.com>
 Sent: Friday, April 14, 2017 4:44 AM
 Subject: Re: [kangax/fabric.js] Reserved key word char used as variable in code in several placed, needs to be changed to _char as done in the rest of the code. Prevents YUI compiler from merging fabric_min.js (#3829)
   
according to es5 specs char is not a reserved keyword. is more a YUI bug than other.i m open to change it as soon as i cleared the other bugs.please check if yui can accept ecmascript version as argument—

**Comment by asturur** [comment]
this has been fixed on latest master and latest 1.x branch. Please have a try,

**Comment by ricksturgeon** [comment]
Please change lines char to _char22313,22315,22322, 22323, 22334, 22335
FROM:/**
 * measure and return the width of a single character.
 * possibly overridden to accomodate differente measure logic or
 * to hook some external lib for character measurement
 * @private
 * @param {String} char char to be measured
 * @param {Object} charStyle style of char to be measured
 * @param {String} [previousChar] previous char
 * @param {Object} [prevCharStyle] style of previous char
 */
_measureChar: function(char, charStyle, previousChar, prevCharStyle) {
  // first i try to return from cache
  var fontCache = this.getFontCache(charStyle), fontDeclaration = this._getFontDeclaration(charStyle),
      previousFontDeclaration = this._getFontDeclaration(prevCharStyle), couple = previousChar + char,
      stylesAreEqual = fontDeclaration === previousFontDeclaration, width, coupleWidth, previousWidth,
      fontMultiplier = charStyle.fontSize / CACHE_FONT_SIZE, kernedWidth;

  if (previousChar && fontCache[previousChar]) {
    previousWidth = fontCache[previousChar] * fontMultiplier;
  }
  if (fontCache[char]) {
    kernedWidth = width = fontCache[char] * fontMultiplier;
  }
  if (stylesAreEqual && fontCache[couple]) {
    coupleWidth = fontCache[couple] * fontMultiplier;
    kernedWidth = coupleWidth - previousWidth;
  }
  if (!width || !previousWidth || !coupleWidth) {
    var ctx = this.getMeasuringContext();
    this._setTextStyles(ctx, charStyle);
  }
  if (!width) {
    kernedWidth = width = ctx.measureText(char).width;
    fontCache[char] = width / fontMultiplier;
  }
  if (!previousWidth && stylesAreEqual && previousChar) {
    previousWidth = ctx.measureText(previousChar).width;
    fontCache[previousChar] = previousWidth / fontMultiplier;
  }
  if (stylesAreEqual && !coupleWidth) {
    // we can measure the kerning couple and subtract the width of the previous character
    coupleWidth = ctx.measureText(couple).width;
    fontCache[couple] = coupleWidth / fontMultiplier;
    kernedWidth = coupleWidth - previousWidth;
  }
  return { width: width, kernedWidth: kernedWidth };
},
TO:/**
 * measure and return the width of a single character.
 * possibly overridden to accomodate differente measure logic or
 * to hook some external lib for character measurement
 * @private
 * @param {String} char char to be measured
 * @param {Object} charStyle style of char to be measured
 * @param {String} [previousChar] previous char
 * @param {Object} [prevCharStyle] style of previous char
 */
_measureChar: function(_char, charStyle, previousChar, prevCharStyle) {
  // first i try to return from cache
  var fontCache = this.getFontCache(charStyle), fontDeclaration = this._getFontDeclaration(charStyle),
      previousFontDeclaration = this._getFontDeclaration(prevCharStyle), couple = previousChar + _char,
      stylesAreEqual = fontDeclaration === previousFontDeclaration, width, coupleWidth, previousWidth,
      fontMultiplier = charStyle.fontSize / CACHE_FONT_SIZE, kernedWidth;

  if (previousChar && fontCache[previousChar]) {
    previousWidth = fontCache[previousChar] * fontMultiplier;
  }
  if (fontCache[_char]) {
    kernedWidth = width = fontCache[_char] * fontMultiplier;
  }
  if (stylesAreEqual && fontCache[couple]) {
    coupleWidth = fontCache[couple] * fontMultiplier;
    kernedWidth = coupleWidth - previousWidth;
  }
  if (!width || !previousWidth || !coupleWidth) {
    var ctx = this.getMeasuringContext();
    this._setTextStyles(ctx, charStyle);
  }
  if (!width) {
    kernedWidth = width = ctx.measureText(_char).width;
    fontCache[_char] = width / fontMultiplier;
  }
  if (!previousWidth && stylesAreEqual && previousChar) {
    previousWidth = ctx.measureText(previousChar).width;
    fontCache[previousChar] = previousWidth / fontMultiplier;
  }
  if (stylesAreEqual && !coupleWidth) {
    // we can measure the kerning couple and subtract the width of the previous character
    coupleWidth = ctx.measureText(couple).width;
    fontCache[couple] = coupleWidth / fontMultiplier;
    kernedWidth = coupleWidth - previousWidth;
  }
  return { width: width, kernedWidth: kernedWidth };
},      From: Andrea Bogazzi <notifications@github.com>
 To: kangax/fabric.js <fabric.js@noreply.github.com> 
Cc: Rick Sturgeon <rick.sturgeon@yahoo.com>; Author <author@noreply.github.com>
 Sent: Sunday, April 23, 2017 5:33 AM
 Subject: Re: [kangax/fabric.js] Reserved key word char used as variable in code in several placed, needs to be changed to _char as done in the rest of the code. Prevents YUI compiler from merging fabric_min.js (#3829)
   
Closed #3829.—

**Comment by asturur** [comment]
you have to rebuild, is changed in the main source, i just can't rebuild dist every commit.

**Comment by asturur** [comment]
https://github.com/kangax/fabric.js/commit/1e057a0bbf8df56fedc387e03e009a2747138ece

**Comment by ricksturgeon** [comment]
I will update my code Next time then when released, I have not been able to rebuild for some reason. I will get someone to help me. Thanks for making the changes
