### ISSUE TITLE
Possible Problem Ungrouping Objects

### ISSUE THREAD

**Issue by JerrodV** [kangax/fabric.js#3830]
Version
1.7.7

I have noticed some irregular behavior when dealing with groups. If I create a group by holding the shift key, then programmatically break the group. I am not able to regroup the objects without side effects.

I have created a test case
[jsfiddle.net/Jevolz/Lo54398u/14/](https://jsfiddle.net/Jevolz/Lo54398u/14/)

To reproduce
(Steps also available in the fiddle)
Form a group by holding the shift key and clicking all three rectangles in any order.

Move the group on the page so the canvas 'object:modified' event fires. The event handler will ungroup the objects.

Re-group the objects as in step 1. When the third object is added to the group, the objects in the group are kicked outside the bounding rect and only the last item remains in the correct position.

Alternatively, once the objects are ungrouped (step 2) manipulate the objects independently, which should give fabric a chance to update the top/left of the objects to their correct position if they were not when the group was broken. Then perform step 3 and notice the same outcome.

I would expect that I should be able to group, ungroup, then regroup without objects jumping around the canvas.

#Update 1 (4-5-2017): I forked that fiddle and altered the fabric library back to 1.7.1 and this behavior is not present.
[jsfiddle.net/r2pcq0nw/1/](https://jsfiddle.net/r2pcq0nw/1/)
*Note that the second fiddle also appears to show a second bug that the first does not, as the group is not being removed. When you break the group, you can then reform it, but if you then move that group, it reveals the original objects under the ones added after the group was broken.
To Reproduce, select all thee objects in any order. Move the group so the object:modified event fires and breaks the group. Then, move the objects without reforming the group. It will reveal the failure to remove the objects. This can only be reproduced in 1.7.1 and not in 1.7.7

#Update 2 (4-6-2017): Today I found some time to run another little test. I forked the second fiddle and bumped the fabric version to 1.7.9. In that fiddle [here](https://jsfiddle.net/Jevolz/swdymy3f/1/), the problems I was in both other fiddles seem to be gone. I did alter the code slightly in that last fiddle. I am no longer adding the objects that were group and just calling 'canvas.discardActiveGroup().remove(obj);' which seems to now handle adding the grouped objects back to the canvas. I assume this was a feature addition between 1.7.1 and 1.7.7.

I'm not sure if it is worth keeping this bug report open if the issues have been fixed in the latest (1.7.9) release.

Thanks,
Jerrod

**Comment by asturur** [comment]
there should be an easier way to do that. i ll try to find out it today and see if there was a bug.  in my opinion calling discardActiveGroup should be enough, or alternatively canvas.deactivateAll(). should be plain simple

**Comment by ncou** [comment]
using discardActiveGroup seems enough :
https://jsfiddle.net/swdymy3f/2/

**Comment by JerrodV** [comment]
Thanks for proving this out in my own code. 
Also, thank you (and your team) for all your good work. Not enough people let you know well you are actually doing. Props.
