### ISSUE TITLE
How to use _CalcBounds() ? (Migration issue fabricjs 1.2.0 to 1.7.9)

### ISSUE THREAD

**Issue by halilozanyilmaz** [kangax/fabric.js#3831]
I have a custom function named `setText(variable)` for creating a curved text on canvas, it works fine with `1.2.0`, but when I use `1.7.9`, the text becomes corrupted. Here is screenshot. 

**setText First Call:** 
![image](https://cloud.githubusercontent.com/assets/25062864/24755635/a8532084-1ae3-11e7-8019-09543f72e7fb.png)

**setText Second Call:** 
![image](https://cloud.githubusercontent.com/assets/25062864/24755660/bc3b1408-1ae3-11e7-9f9f-3339155b6538.png)

Then I did some debugging, and I believe that this is related to  `_CalcBounds()` inside my `setText `function.
I googled it and found no documentation, and no examples of how it is used.  (**see bottom of the page for source code**)

If I remove it from the `setText`, this is what shows when `setText` is called:

![image](https://cloud.githubusercontent.com/assets/25062864/24755783/1d462d1e-1ae4-11e7-9726-0917f7b3518e.png)

So what is this `_CalcBounds()` function? Is there an alternate way of doing this ? 

 **My `setText `function:**     
      
      CurvedText.prototype.setText = function( newText ) {
      this.opts.top=this.group.top;
      this.opts.left=this.group.left;    
        
      while ( newText.length !== 0 && this.group.size() >= newText.length ) {
        this.group.remove( this.group.item( this.group.size()-1 ) );
      }
      
      for ( var i=0; i<newText.length; i++ ){
        if ( this.group.item(i) === undefined ){
          var letter = new fabric.Text(newText[i], {
            selectable: true
          });
          this.group.add( letter );
        }
        else{
          this.group.item(i).text = newText[i];
        }
      }

        var curAngle=0,angleRadians=0, align=0, tt, ll;    
        
        for ( var i=0; i<this.group.size(); i++) {
          curAngle = (i * parseInt( this.opts.spacing, 10)) - align;
          angleRadians = curAngle * (Math.PI / 180);
          this.group.item(i).set( 'top', (-Math.cos( angleRadians ) * this.opts.radius) );
          this.group.item(i).set( 'left', (Math.sin( angleRadians ) * this.opts.radius) ) ;
          tt = this.group.item(i).top;
          ll = this.group.item(i).left;
            
          this.group.item(i).setAngle( curAngle );
        }        
        
        
      this.opts.text = newText;
      this.group._calcBounds();
      this.group._updateObjectsCoords();
      this.group.top = this.opts.top;
      this.group.left = this.opts.left;        
      this.group.saveCoords();      
      this.canvas.renderAll();
    };`

Here you may find the difference between `1.2.0 _CalcBounds `vs `1.7.9 _CalcBounds`:

`1.2.0:`

![image](https://cloud.githubusercontent.com/assets/25062864/24756868/48d602ae-1ae6-11e7-8327-378f32a7727b.png)

`1.7.9`

![image](https://cloud.githubusercontent.com/assets/25062864/24756952/574e8540-1ae6-11e7-970f-948e7f1f2dd6.png)

**Comment by halilozanyilmaz** [comment]
I will further investigate, I think this issue is not related to _calcBounds

**Comment by asturur** [comment]
So _calcBounds before 1.7.something was calling setcoords with the screen coordinates, while now is use absolute coordinates. the real difference is setCoords(true) vs setCoords().
This should influence only grouping.

Share your custom curved text plugin, i ll give a look.

**Comment by halilozanyilmaz** [comment]
@asturur Hi astutur, I have closed this issue because I have realized that this was not related to _calcBounds, below is the updated topic of me. You may check that one.

https://github.com/kangax/fabric.js/issues/3834
