### ISSUE TITLE
groups and toDatalessJSON does not leverage sourcePath

### ISSUE THREAD

**Issue by dvideby0** [kangax/fabric.js#3832]
I am attempting to add labels to objects using groups (as outlined in the tutorials). Unfortunately when the object is an SVG group and you leverage `toDatalessJSON()` the sourcePath is ignored.

gif of expected vs actual - [http://recordit.co/g9SHJJiv5S](http://recordit.co/g9SHJJiv5S)

## Version
1.7.6

## Test Case
https://jsbin.com/pogiwur/2/edit?js,output

## Steps to reproduce
```javascript
var canvas = new fabric.Canvas('map');

var text = new fabric.Text('OBJ-0329', {
  fontSize: 10,
  originX: 'center',
  originY: 'center'
});

fabric.loadSVGFromString('<?xml version="1.0" encoding="UTF-8" standalone="no"?><svg xmlns="http://www.w3.org/2000/svg" width="96px" height="42px" viewBox="0 0 96 42" version="1.1">    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">        <g stroke="currentColor">            <rect x="0" y="0" width="96" height="42"></rect>            <path d="M0.5,3.5 L95.5,3.5" stroke-linecap="square"></path>            <path d="M0.5,38.5 L95.5,38.5" stroke-linecap="square"></path>            <path d="M3.5,0.5 L3.5,3.5" stroke-linecap="square"></path>            <path d="M92.5,0.5 L92.5,3.5" stroke-linecap="square"></path>            <path d="M92.5,38.5 L92.5,41.5" stroke-linecap="square"></path>            <path d="M3.5,38.5 L3.5,41.5" stroke-linecap="square"></path>        </g>    </g></svg>', function(objects, options) {
  var svgId = '123454321';
  objects.forEach(object => {
    object.id = svgId;
  });
  var svgGroup = fabric.util.groupSVGElements(objects, options);
  svgGroup.originX = 'center';
  svgGroup.originY = 'center';
  svgGroup.sourcePath = 'https://google.com';
  var group = new fabric.Group([ svgGroup, text ], {
  left: 150,
  top: 100
  });
  canvas.add(group); // swap out with svgGroup to see sourcePath work
  console.log(canvas.toDatalessJSON(['sourcePath']));
});
```
## Expected Behavior
The sourcePath should replace the **paths** array with a url
## Actual Behavior
The sourcePath is ignored

**Comment by asturur** [comment]
i will check the whole sourcePath situation. i was about to remove it from the api completely. Does not make sense to me to output a json representation that needs to be reparsed with the svg parser.

**Comment by dvideby0** [comment]
I hope you keep it in there. I use it because it dramatically reduces the size when trying to store in a DB.

**Comment by asturur** [comment]
sure, but is a weird thing in my opinion. i think you should try excluding default values, that reduces size as well by much but keep the data structure parsed.

**Comment by dvideby0** [comment]
All of our objects come from SVGs. How would I exclude the `paths` and be able to re-render?

**Comment by asturur** [comment]
you have to keep the paths. no way around it. or reparse the URL but at that point it does not really make sense to me. i understand the necessity, i ll see if i can keep it in. I think is the master branch is already removed. I do not like an api in wich you can restore a pathGroup passing the object form or the url. With an ad-hoc method loadFromJSON will not work.

**Comment by dvideby0** [comment]
Yea I mean we actually hit the upper bounds of what size records MongoDB can hold when we keep the paths. Since any given canvas can hold thousands of objects. I assume you must have other users in similar situations where they rely on this feature.

**Comment by asturur** [comment]
probably yes. while i will try to restore it, can you give a shot at how much the includeDefaults reduce the space? just to figure out since you have a large data use case.

**Comment by dvideby0** [comment]
Just to be clear, are you wondering the size difference between with and without paths for our fabric instances?

**Comment by asturur** [comment]
no with and without default values with the options `includeDefaults`

**Comment by dvideby0** [comment]
ok I will try that out and get back to you.

**Comment by dvideby0** [comment]
I tried on both our PathGroups and on the canvas itself. The difference was not noticeable. I wonder if it is because we export with so many fields specified that it renders this useless. BTW, any luck with the sourcepath and groups? I have tried to create a workaround where I destroy and rebuild the groups (destroy to save and then rebuild so that the UI is still usable) but I am running into some weird behaviors. You can see the logic from the JSBin that I used in another issue (https://jsbin.com/zuludav/7/edit?html,js,output) with the export and restore functions.

**Comment by asturur** [comment]
did not have time yet. i think i will restore it or at least provide a method in the canvas restore if not in the object.

i still think that is a wrong db approach, since for whatever big can be the json, if javascript can handle it, is mongodb in defect.

can you pull 1.7.9 in nmeantime? i see you talk about 1.7.6 and i would like to figure oit if you build it from current master branch

**Comment by dvideby0** [comment]
Thank you! I have bumped our version to 1.7.9 and everything appears to be working as expected except this specific issue of course.

**Comment by asturur** [comment]
i verified that group does not have a toDatalessObject to moved down the toDatalessObject request to sub objects. fixing it.
