### ISSUE TITLE
Not able to select object which behind not selecteable object

### ISSUE THREAD

**Issue by vijaygurjar** [kangax/fabric.js#3833]
Hi,

I am not able to select object which is behind another object which is selecteable=false.
i have added two rect on same position. Top rect selectable property is false still i m not select another object by mouse down.
http://jsfiddle.net/vijaygurjar/msodah0r/

**Comment by ncou** [comment]
Hi,

You need to add "evented: false" to have the ability to click "throw" the unselectable object.

http://jsfiddle.net/msodah0r/1/

Is that what you are trying to do ?

**Comment by vijaygurjar** [comment]
Thanks ncou,

is it possible by other way?

**Comment by asturur** [comment]
is really a documentation problem
I see the utility of having an object unselectable but still firing events ( mouseup, mousedown ) and a way to make it transparent to mouse actions.

**Comment by ncou** [comment]
I don't know another way to do this. Why do you ask ? does the "evented:false" doesn't fit your needs ?

**Comment by vijaygurjar** [comment]
yes it is not fulfill my requirement, I need to stop listening only mouse events only

**Comment by asturur** [comment]
set that object as evented = false.

**Comment by hga77** [comment]
Yes, this is a very good question and it has not been solved. This is needed in situations where for example you need to implement a context menu with lock/unlock objects. If the object is locked, you still need to be able to right-click on it to display the context menu. Also, when locked, you want to be able to click objects under the locked objects.

How do you do this? https://github.com/fabricjs/fabric.js/issues/6734
