### ISSUE TITLE
Q: why doesn't group.add() simply reparent ? why use clone() ?

### ISSUE THREAD

**Issue by dmccuskey** [kangax/fabric.js#3838]
i'm not sure i understand the reasoning behind needing to clone() an item in order to move to another Container.

from your docs (http://fabricjs.com/fabric-intro-part-3#groups):

```
// create a group with copies of existing (2) objects
var group = new fabric.Group([
  canvas.item(0).clone(),
  canvas.item(1).clone()
]);

// remove all objects and re-render
canvas.clear().renderAll();

// add group onto canvas
canvas.add(group);
```

i have briefly looked through the code and can't see any reason why this wouldn't be possible.

this seems like a very heavy-handed and unwieldy way to essentially move an object to another parent. for example, i would imagine that calling group.add() on an object would check to see if that object already has a parent, if so, disassociate it and re-parent to new group.

**Two reasons for this:**

1. it makes the dev user experience much simpler.

  we can essentially replace the above 5 lines of code with 1.

2. improves speed, memory management

say i'm rendering a scrolling-list UI component and showing 10 rows. i don't want to continually create and destroy table row items, i just want to reuse them. this is because the process of creating a destroying objects is very intensive and completely unnecessary. you can see a mobile device pause/struggle while it's doing all of the work to create and garbage collect.

so in my case, i may have created more rows than i need for display. so i simply re-parent the unused items to another group – one which is not viewable (thus, nor its children). so i effectively have a hidden storage area. 

i have a pretty extensive background using the Corona SDK 2D game engine. i used this technique a lot to implement object caching.

in fabricjs, i have to clone() each object – so creating more work, more memory, then garbage collecting the old items. but i should be able to simply re-use them as they are.

**Current Project**

another example: for my current project, i'm working on a charting component for a stock market trading app. for the same chart – in some cases i may render 30 candles, other cases i may render 60. but i'd rather just keep some of the candles around for reuse instead of destroying and creating them over again.

**Comment by asturur** [comment]
you can do:

canvas.remove(item)
group.addWithUpdate(item)

no need to clone.

Important is that you do not have an item on canvas and on group at the same time.

I should update that part 3 intro.
