### ISSUE TITLE
Loading SVG from url with embedded image renders a black box

### ISSUE THREAD

**Issue by basilinjoe** [kangax/fabric.js#3839]
loading an SVG containing `<image>` tag having `href` as `base64` encoded image not rendering correctly
## Version
1.7.9
## Test Case
http://plnkr.co/edit/RIETOl?p=preview

## Steps to reproduce

1. Load SVG from url using `fabric.loadSVGFromURL(url,cb)`

2. Add it to canvas

## Expected Behavior
Loads the actual SVG

## Actual Behavior
Loads a black box

**Comment by asturur** [comment]
this is an svg with pattern.
pattern parsing is not supported.

**Comment by basilinjoe** [comment]
@asturur is there any way around ?

**Comment by asturur** [comment]
the workaround is not using patterns. in that particular case try to give the use tag the url for #c1 instead of #c2. not that much i can do for now.

**Comment by asturur** [comment]
we have another issue for svg pattern parsing. i closing this
