### ISSUE TITLE
render issues using isOnScreen for pathGroup inside of a Group and zooming to point

### ISSUE THREAD

**Issue by dvideby0** [kangax/fabric.js#3840]
## Version
1.7.9

## Test Case
https://jsbin.com/zuludav/7/edit?html,js,output

## Steps to reproduce
Open up the test case and click zoom to point. To see expected behavior either comment out the optimization code that checks `isOnScreen()` or use the normal zoom
## Expected Behavior
When zooming to point the objects should render correctly
## Actual Behavior
when zooming to point the pathgroup disappears
## Additional Notes
If you comment out the optimization code above everything works fine. Also, if you use normal Zoom function everything works as expected as well.

**Comment by asturur** [comment]
https://jsfiddle.net/63tx5fn3/2/

this is a simplified fiddle of your jsbin ( please prefer fiddle over jsbin if you can ).

Setting the offScreen render with the proper option, everything looks like working.

**Comment by dvideby0** [comment]
Works like a champ. I was using the previous cade based on zooming performance just a couple of months ago. It's really impressive you already have an option now. Thanks again for your timely response.
