### ISSUE TITLE
Canvas (non-static) blocks browser zooming/scrolling on touch devices

### ISSUE THREAD

**Issue by simonbaev** [kangax/fabric.js#3841]
## Version
1.7.9

## Test Case
https://jsfiddle.net/simonbaev/rpnerLj0/4/

## Steps to reproduce
Add a canvas element and create Canvas object with fixed dimensions. Add some other fixed size element on the same page. Add <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=2.0'> to the head of the HTML document to enforce max zoom factor of 2.0

## Expected Behavior
Use browser's zooming to pinch and zoom content of the canvas regardless which part of the page was used for the pinching/zooming gesture. 

## Actual Behavior
Zooming gesture works only if applied over non-canvas element. It appears that canvas intercepts all touch events and doesn't allow them to be properly handled. 

## Comments
I found StackOverflow post at http://stackoverflow.com/questions/28605076/canvas-fabricjs-block-web-browser-zooming-and-moving-on-mobiles that discusses similar problem. The author offers solution to use "canvas.allowTouchScrolling = true;" but that didn't work for me.

**Comment by ncou** [comment]
Hi,

Which mobile device are you using ?

**Comment by simonbaev** [comment]
Hi,

I tried it on Android in Chrome browser on Samsung Galaxy J3 and Google
Pixel.

--
Simon

**Comment by ncou** [comment]
Hi,

I don't really understand what you are trying to do. Do you need to interract with the canvas ?
If you just want to use the browser pinch and zoom on the canvas, and there is n interactions, you can :

1) Disable the touch events in the canvas with the param : allowTouchScrolling = false
In this case the canvas will behave like your div for the pinch and zoom because the touchevents are not intercepted by the fabric lib.
https://jsfiddle.net/rpnerLj0/5/

2) Or you can use a "StaticCanvas" instead of an Canvas object who doesn't have the gesture lib. 
https://jsfiddle.net/rpnerLj0/7/

Does this answer your needs ?

**Comment by asturur** [comment]
i need to buy a tablet to fix those things. any suggestion?

**Comment by ncou** [comment]
I think that with a basic Android tablet you could have the possibility to test and fix these type of things.

But in some rare cases it's also good to have an ipad near you to tests some specific cases (the elastick scroll sometimes disturb the way touch event should be handled)

**Comment by simonbaev** [comment]
Hi,

I am using Fabric to maintain 2 canvases: one real (has corresponding HTML
tag) and one virtual (created in JS). I load a stack of images to the
"real" Canvas and one image (color map) into the virtual. When the "real"
canvas is tapped somewhere I get the coordinate from the touch event and
identify color at the matching point on the context of the "virtual"
canvas. Each color is associated with one particular image from the stack
on "real" canvas that has to be pushed all the way up.

So yes, I do interact with the canvas and I cannot use StaticCanvas in
place of Canvas (I already tried it). It solves the problem with zooming
but it doesn't handle mouse:move and mouse:down events that I use to
capture coordinates.

I could provide a link to the real app that demonstrates the process if
needed.

--
Simon

**Comment by ncou** [comment]
ok i understand.

could you try to test this solution :
 https://github.com/kangax/fabric.js/issues/3756#issuecomment-284185019

This will use the touchmove event for all the document, and avoid fabric.js to capture this event.
The touchstart will still be captured by fabric.js (this will event is the same as the mouse click).

**Comment by simonbaev** [comment]
I did the following:

   1. Added *{allowTouchScrolling: true}* as the second argument to Canvas
   constructor. It didn't affect anything (from scrolling perspective). I
   removed it from the call to constructor.
   2. I added *$('.canvas-container').on('touchmove', function(evt){
   evt.preventDefault(); }); *after creating Canvas object (immediately
   after call to constructor). I actually added small alert at the beginning
   of the event handler to see when this event gets fired. It appears that
   single tap doesn't trigger the event but *multi-touch* tap or
   *tap-and-swipe* do. I then removed the alert. Anyway it didn't fix the
   issue.
   3. I am not sure I understand the CSS part of the solution... I
added *position:
   fixed; overflow: hidden *to both html and body, and I then added *overflow:
   auto;*  to *.canvas-container* Again, I'm not sure that I did it right,
   but it also didn't fix the issue.
   4. I temporally disabled event handlers on canvas (both 'mouse:move' and
   'mouse:down') and it also didn't fix the issue.
   5. I tried combining above 4 items but it also didn't help.

So far no luck...

**Comment by simonbaev** [comment]
Would it be possible to place a transparent "glass" (*div* with transparent
background and matching size) in front of *.canvas-container* (to give that
div a higher *z-index* in CSS) and make it not to pass any touch events
except those that are used for *mouse:move* and *mouse:down*?

How about *pointer-events* CSS property, can it be used in this context (I
tried it but it never worked for me)?

Thanks.

**Comment by ncou** [comment]
Can you send me a link to your app so i can understand which gesture is needed.

On mobile device there is no such thing as mouse:move and mouse:down.
Only touchstart/end/cancel/leave/move

if you want to disable some event do the same trick as previous post for the "touchmove" event.
Use `.preventDefault()` to disable the browser native action, and `.stopPropagation()` to avoid other components to get this event.

**Comment by asturur** [comment]
i m very busy those days. i m planning to buy a tablet and check those things to enable proper support fortl touch or pointer events, whatever is more standard

**Comment by simonbaev** [comment]
Here is a link to the part of the app in question:
http://stapps.gswcm.net/~simon.baev/Homunculus/

I could send sources if needed but all of them are "client-side" so could
be accessed directly in browser.

--
Simon

**Comment by asturur** [comment]
to be handled in #3869
