### ISSUE TITLE
selectionBackgroundColor still present when using image with toDataURL()

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3842]
Hi,

If i set the parameter "selectionBackgroundColor" for an object, this color is still present on the exported image. It should not appear on the export (like the other "selection" items are not presents : corners, selection rect border...etc).

Steps to reproduce : 
http://jsfiddle.net/j229j5b4/1/
Select the red rect, and click on the 'todataurl' button.

You can see the selectionBackground rect, while the other selection items (corners...etc) are not exported.
The "fillStyle" should be made transparent and not using the backgroundcolor before the image export ? no ?

**Comment by asturur** [comment]
this looks like a regression. agree is a bug
