### ISSUE TITLE
SVG Mask doesn't applying to the image in fabric since 1.7.0

### ISSUE THREAD

**Issue by eugene-ilyin** [kangax/fabric.js#3843]
Hello

In my application, I have a functionality to apply the SVG mask to the image on the canvas. After updating the fabricjs to a version 1.7.9 this functionality doesn't work.

I've tried to sort out with it, but I can't find a solution.
I've prepared a JSfiddle. As you can see http://jsfiddle.net/m3ba39pk/ - mask successfully applied to the image.
This JSfiddle uses fabric v1.6.7 (in external resources). If you will change the version of fabric to 1.7.0, you will see only a gray square. No image and no mask. Is it a bug of fabric, or the algorithm to set a mask has been changed? If there is some documentation how to do this with fabric 1.7.0+, please give me a link. Or please give me an advice, to solve this problem.

Thanks in advance.

**Comment by asturur** [comment]
http://jsfiddle.net/m3ba39pk/2/

this is complete custom code.
Please look in the _renderPathCommand function that gives you the ability to use a path to clip a canvas. I deleted most of the unused stuff and i left the relevant code only.

**Comment by eugene-ilyin** [comment]
Thank you for such quick answer. It really helpful. One more questions - is there a way to scale a mask for now? Methods setWidth/setHeight and setScaleX/setScaleY don't help, but they worked before.

**Comment by asturur** [comment]
since you are working ont the context, scale the context directly. 

use ctx.scale(x, y) before calling renderPathCommands. this scaling will be center based.

**Comment by eugene-ilyin** [comment]
Great! My problems are solved. Thanks a lot!

**Comment by eugene-ilyin** [comment]
@asturur Hello, your advice works great, but I've faced with this issue http://stackoverflow.com/questions/44016043/how-to-move-clipped-image-inside-of-the-group-but-keep-clip-line-as-static Could you help me a little additionally, please?

**Comment by jigs-bc** [comment]
Hi, We are using fabric.loadSVGFromURL() for SVG image mask and then getting mask data from fabric.util.groupSVGElements(objects, options) function and then implemented below code for clipping :
mask.set({
                left: 0,
                top: 0,
                scaleY: canvas.height / mask.height,
                scaleX: canvas.width / mask.width,
                fill: 'transparent',
                opacity: 0,
            });
            canvas.clipTo = function (ctx) {
                mask.render(ctx);
            };
It is working fine below 1.6.7 but for 1.7.*, it is failed. can anyone suggest?

**Comment by asturur** [comment]
sure, try to do `mask.objectCaching = false` when you create it. This will allow it to draw in standar way and should clip.

**Comment by jigs-bc** [comment]
Hi asturur,
Thanks for your prompt response. Yes, it works for me.

**Comment by jigs-bc** [comment]
Hi again. My issue has been resolved for 1.7.0 but when i am using latest fabric above issue again persists. can you please help me out?

**Comment by jigs-bc** [comment]
It is working for 1.7.9 after that it is not

**Comment by jigs-bc** [comment]
Hi, can someone update me on my above concern?
Thanks

**Comment by asturur** [comment]
can you put up a fiddle with this code and the 1.7.15

**Comment by nitin-bc** [comment]
Hi Asturur,

Sorry for late response. I have prepared fiddle for masking feature. 
Working with 1.7.9 : https://fiddle.jshell.net/dc367z71/
Not working with  1.7.17 : https://fiddle.jshell.net/gs2qca0u/

Can you please check and let me know the issue?

Thanks

**Comment by nitin-bc** [comment]
Hi,
Any update for me?

**Comment by nitin-bc** [comment]
Also, is it possible to have multiple masking into one canvas?

**Comment by nitin-bc** [comment]
Hi, Did someone get a chance to check my concern please?

**Comment by asturur** [comment]
So In version 1.7.17 or .16 as an effort to improve performance, not visible objects skip rendering process.
Setting opacity to 0 is the reason why is not working.

using clipTo is not that easy ( reason why is getting removed in favor of something smoother ).
If you do not want to change your current code to have the path transparent, just use opacity 0.00001. is an hack sadly.

**Comment by asturur** [comment]
To answer the other question, the nature of clip to does not make easy to clip with more than one path. You have to use one beginPath argument to make it works.
That means that using more than one fabric shape will not work out.

**Comment by nitin-bc** [comment]
Hi, can you please confirm the todataurlwithmultiplier feature works fine with masking feature in version 1.7.9? I am getting blank object. Is it solved in higher versions?

**Comment by nitin-bc** [comment]
I have tried with 1.7.16 also. This is pre-built fiddle, i have just added the latest fabric but todataurlwithmultiplier is not returning the proper result

**Comment by asturur** [comment]
you mean this fiddle? https://fiddle.jshell.net/gs2qca0u/ ?

**Comment by nitin-bc** [comment]
Sorry i missed to add the fiddle. I am asking for this one: http://jsfiddle.net/natchiketa/gXZJf/. Created by any other user or by your support.

**Comment by asturur** [comment]
http://jsfiddle.net/gXZJf/424/

 I have seen that fiddle in many ways.
This is another way to make it work.

the takeaway points are:

1) if something has to behave as a clipping path, it should have objectCaching disabled.
2) reverse transforming the canvas coordinates is not easy, you cannot try to reverse rotation, scale and position in any order, it will give weird results.

**Comment by nitin-bc** [comment]
Thanks for your response. Please check this fiddle. I have disabled objectcaching and also didn't make any changes in object. But still i am getting weird result.
https://fiddle.jshell.net/dc367z71/

**Comment by asturur** [comment]
https://fiddle.jshell.net/dc367z71/2/

i think i answered this before.
If you se opacity to 0 you are not getting any shape anywere. keep opacity bigger than 0.

**Comment by nitin-bc** [comment]
I have set the opacity to 1 but still not working.

**Comment by asturur** [comment]
my fiddle works.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/29446793-6af05ddc-83ee-11e7-8a01-1e6bbb41f076.png)

**Comment by nitin-bc** [comment]
Sorry but i am not asking for masking issue on canvas. I am not getting proper result todataurlwithmultiplier function when i use masking on canvas. Checkt this please @ https://fiddle.jshell.net/dc367z71/3/

**Comment by asturur** [comment]
Can you console.log a dataurl and expect i understand is wrong?

**Comment by asturur** [comment]
https://fiddle.jshell.net/dc367z71/5/

your fiddle was not working because:
missing CORS
not waiting for the image to load before generating dataurl.

**Comment by nitin-bc** [comment]
Yes i get it but this is working for only todataurl not for todataurlwithmultiplier

**Comment by nitin-bc** [comment]
Also, i need to export the output outside the fromurl function. I can't get the result on the basis of single object, In your fiddle. This is working fine for me. https://fiddle.jshell.net/dc367z71/8/ but i need working for this https://fiddle.jshell.net/dc367z71/9/
Hope you understand

**Comment by asturur** [comment]
https://fiddle.jshell.net/dc367z71/10/

I understand that you miss the basic functionality of the async behaviour.
You have to wait both the image and the mask to load, then you can dataurl.
My diffle output winnie the pooh in a mobile phone cover, multiplied by 3.

**Comment by nitin-bc** [comment]
Okay i got it. I will try this solution. Thank you. I have one more concern regarding select all object feature. Once i move the group object then fabric returns the left position in negative for individual object. Can you please confirm this issue?
http://jsfiddle.net/softvar/mRA8Z/

**Comment by unitedsol** [comment]
can any one tell me how to add watermark on fabric js canvas either its image water mark of text.

Thanks in advance
