### ISSUE TITLE
Events stop being triggered after Polygon attributes are updated

### ISSUE THREAD

**Issue by simplynail** [kangax/fabric.js#3846]
## Version
1.7.9

## Test Case
https://jsfiddle.net/pez6dnwt/6/

## Steps to reproduce
comment/uncomment line 66 to turn bug off/on

## Expected Behavior
updating Polygon attributes with set({ }) should not affect events being triggered on this particular Polygon (ei hover action for this particular polygon)

## Actual Behavior
when I update Polygon attributes on existing polygons with:
`poly.set({ left: /some float/, top: /some float/})`
events (ie. canvas.on('mouse:over' ...) ) stop being handled and I get
`e.target is null`
or
`e.target is undefined`
depending whether I do mouse over/out on **whole** canvas

**Comment by asturur** [comment]
you have to call setCoords if you want the mouse interaction to be adjusted accordingly
