### ISSUE TITLE
How to pause animation running?

### ISSUE THREAD

**Issue by zzbo** [kangax/fabric.js#3847]
I want to stop the animation when I click the 'pause' button and run the animation when I click the 'continue'.

**Comment by asturur** [comment]
can you open a question on stackoverflow? the issue tracker is for bugs or features.
post link to the question here

**Comment by utiq** [comment]
Hi @zzbo, I'm trying to accomplish the same, could you do it?

**Comment by zzbo** [comment]
@utiq  I have no idea for it.
