### ISSUE TITLE
Old version of jsdom in 1.7.9 package.json 

### ISSUE THREAD

**Issue by themadcreator** [kangax/fabric.js#3848]
## Version
1.7.9

## Steps to reproduce
Examine package.json dependencies

## Expected Behavior
https://github.com/kangax/fabric.js/blob/master/package.json#L50
Refers to latest jsdom 9.x.x

## Actual Behavior
https://github.com/kangax/fabric.js/blob/v179/package.json#L50
Refers to ancient jsdom 3.x.x

Ran into this while trying to install fabric@1.7.9 and jsdom@3.x.x's dependency on contextify failed to build via node-gyp. According to their docs, contextify is no longer necessary after node >= 0.12 (!!!!)

**Comment by asturur** [comment]
branch 1.x of fabricjs is based on jsdom 3.x since it has to work from node 0.12 up.

a new version will come that supports just node 4 up and will.use latest jsdom
