### ISSUE TITLE
setOverlayImage and toDataURL scale with browser zoom

### ISSUE THREAD

**Issue by versable** [kangax/fabric.js#3852]
setOverlayImage and toDataURL use scaled canvas size (class lower-canvas) instead of spezified canvas size (when zoomed in). This became apparent when using font DPI scaling on Windows and Linux.

## Version
1.7.6

## Test Case
https://jsfiddle.net/qb5tgj9v/

## Steps to reproduce
- Load fiddle
- Canvas sets overlay as expected
- Alert box shows expected image dimensions
- Zoom in with used browser
- Reload Fiddle

## Expected Behavior
- setOverlayImage and toDataURL work independently of the browsers zoom factor

## Actual Behavior
- setOverlayImage and toDataURL take browser zoom factor into consideration

**Comment by asturur** [comment]
disable retina scaling if you do not want the browser zoom to bother you. sadly they are on the same window variable. window.devicepixelratio

**Comment by versable** [comment]
Issue persists with retina scaling disabled, see updated jsfiddle: https://jsfiddle.net/qb5tgj9v/1/

**Comment by asturur** [comment]
https://jsfiddle.net/qb5tgj9v/2/

**Comment by asturur** [comment]
yes the enableRetinaScaling needs to be passed at constructor time, or takes effect after a resize
