### ISSUE TITLE
textbox - space in middle of a word generates a line break in google chrome

### ISSUE THREAD

**Issue by bvalgas** [kangax/fabric.js#3854]
## Version
1.7.6

## Steps to reproduce
in google chrome(ver 57+)
insert a text box and write a word
put the cursor in the middle of the word and insert an space.
the textbox makes a linebreak

**Comment by asturur** [comment]
use v 1.7.9 where this has been fixes.
is a chrome bug that  chrome dev do not really admit that is weird.
We went around it with css on textarea.
