### ISSUE TITLE
Imagearea select by fabricjs rect

### ISSUE THREAD

**Issue by vijaygurjar** [kangax/fabric.js#3855]
Hello,

can we implement imagearea select tool by fabricjs for image crop.

Regards,
Image

**Comment by asturur** [comment]
image cropping will probably be included in fabric 2.0 you have to wait a bit and you will get a cropping functionality. THen you can implmente your interface on top of it.

**Comment by asturur** [comment]
i m merging the cropX and cropY functionalities.
This will not give you any crop area tool, but you can set effectively a cropX, cropY for an image, set width and height and have a nice crop for it.
