### ISSUE TITLE
Rotating group fabricjs objects with snapangle property set, produces incorrect individual object angles

### ISSUE THREAD

**Issue by OutrageousSoftware** [kangax/fabric.js#3857]
## Version
1.7.8

## Test Case
http://jsfiddle.net/Outrageous/a50nrcv0/

## Steps to reproduce
1) Run this jsfiddle... http://jsfiddle.net/Outrageous/a50nrcv0/ 
 2) Click the "Show Angle" button. (it should read 0 degrees, and it does) 
 2) Select both text objects ("text1" and "text2") with your mouse. 
 3) Rotate the selected group 90 degrees to the right. 
 4) Click on the canvas to Un-Select the text box group. 
 5) Click the "Show Angle" button. (it should read 90 degrees, and it does) 
 6) Select both text objects ("text1" and "text2") with your mouse. 
 7) Rotate the selected group 90 degrees to the left (to return the text boxes back to a 0 degree angle). 
 8) Click on the canvas to Un-Select the text box group. 
 9) Click the "Show Angle" button. (it should read 0 degrees and instead reads -1.4033418597069752e-14 degrees) 

From here on out all of the angles are off when rotating via a group - The angle of the objects show -1.4033418597069752e-14 degrees instead of 0 degrees when rotating objects as a group. Note: this code uses a snapThreshold: 45, and a snapAngle: 90 so I wouldn't think this would happen. When I rotate the objects individually the angles correct themselves. I have tried using the setCoords() with no luck. This issue doesn't happen when only rotating in a positive direction, only in a negative direction.  Also, I have noticed that the object.left and object.top values change slightly as well after performing the steps above.

## Expected Behavior
The angle of the objects should be 0 degrees.
## Actual Behavior
The angle of the objects show -1.4033418597069752e-14 degrees instead of 0 degrees.

**Comment by asturur** [comment]
may be some snap angle problem or a calculation error of ungrouping.
There is a missing precision inherited from how floats are done.

-1.4 x 10 ^ -14 is basically 0: 0.000000000000014033.

If is not a snapping bug, i cannot fix it.

**Comment by asturur** [comment]
so the error is that Math.cos never gives 0 for 90 deg or 270 degrees...

**Comment by OutrageousSoftware** [comment]
Thank you Andrea for the quick turn around on that.  Fabric.js is amazing!
