### ISSUE TITLE
fabric.Path is not drawn on canvas

### ISSUE THREAD

**Issue by pavelKozlov** [kangax/fabric.js#3859]
I use an example from fabric introduction page http://fabricjs.com/fabric-intro-part-1

## Version
1.7.0 and higher

## Test Case
http://jsfiddle.net/4ycgsovr/

## Steps to reproduce
var canvas = new fabric.Canvas('c');
var path = new fabric.Path('M 0 0 L 300 100 L 100 300 z', {originX: 0, originY: 0});
canvas.add(path);

## Expected Behavior
svg path is drawn on canvas:
http://jsfiddle.net/bnz4osxv/
this jsfiddle uses fabric version 1.6.7

## Actual Behavior
svg path is not visible

**Comment by asturur** [comment]
i m able to see the path with both fiddles.

**Comment by pavelKozlov** [comment]
Looks like it's a problem with default color.
If you set `fill` to fabric.Path, it renders ok.
But without `fill` you will able to see path only when select it as invisible on canvas and then resize.
![screenshot from 2017-04-21 16-23-02](https://cloud.githubusercontent.com/assets/1263270/25279398/fc586244-26ae-11e7-9220-30cf5ed7c690.png)

**Comment by asturur** [comment]
on what browser are you?

**Comment by pavelKozlov** [comment]
Google Chrome version 57.0.2987.133 (64-bit) and Firefox 52.0.2 on Ubuntu 16.
I have also tried in on Windows with Chrome 57 and Firefox.
The same result for all these browsers.

**Comment by asturur** [comment]
is see them perfectly on both fiddles. chrome 58 on macosx

**Comment by p3ndu** [comment]
Hi,

I can confirm that this bug reproduces on Chrome Version 57.0.2987.110 (64-bit) / Firefox 45.2.0 on CentOS 6.8.

**Comment by pavelKozlov** [comment]
I can confirm that on MacOS with Chrome 57 it works ok.

**Comment by ncou** [comment]
There is the same behaviors in the Chrome version 57.0.2987.113

If i add one of those properties the shape is draw :

- fill: 'none'
or
-strokeWidth:0

**Comment by asturur** [comment]
a linux bug? i do not have a vm here to test.

**Comment by pavelKozlov** [comment]
It also reproduses on Windows.

**Comment by asturur** [comment]
i see on windows edge does not work ( i m on a VM ) if you rescale it then it works.

**Comment by asturur** [comment]
ok i got it :D 
There was a small fundamental design flaw in the cache.
The object gets initializated at status dirty: false.
If nothing change before first rendering, it does not draw anything.

on my macbook worked because adding to a retina enabled canvas after initialization, doubled the cache dimensions and a redraw was triggered.

i m fixing it.
