### ISSUE TITLE
Wrong objects position

### ISSUE THREAD

**Issue by alexandrebarreiros** [kangax/fabric.js#3861]
## Version
1.7.7

## Test Case
https://jsfiddle.net/nLL1ntfg/0/ - wrong behavior version 1.7.7
https://jsfiddle.net/nLL1ntfg/1/ - correct behavior version 1.5.0

## Steps to reproduce
set position X of tow objects one exactly next to the other
## Expected Behavior
Don't any gap between the 2 objects
## Actual Behavior
There is a gap between them

**Comment by ncou** [comment]
Hi,

I think there is a stroke by default on the objects (except the images) in v1.7, you need to add strokeWidth:0 to have the same behaviors as in v1.5

https://jsfiddle.net/nLL1ntfg/2/

Close the ticket if it's ok for you.

**Comment by asturur** [comment]
Sure, is because at 1.5 the stroke was not counted in the size.
