### ISSUE TITLE
Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by halilozanyilmaz** [kangax/fabric.js#3865]
I am using `fabricjs 1.7.9`, and I get error:

> Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

on following line:  `var data = canvasObj.toDataURL()`          

**Code below causes this error, how should I fix it ?** 

            var imgObj = new Image();
            imgObj.src = jQuery( this ).find( 'img' ).attr( 'src' );
            imgObj.setAttribute('crossOrigin', 'anonymous');  
            imgObj.onload = function () {                
                var image = new fabric.Image( imgObj );
                var getRatio = scaleSize( 100, 110, image.getWidth(), image.getHeight());
                image.setWidth( getRatio[0] );
                image.setHeight( getRatio[1] );

                image.set({
                    left:canvasObj.getWidth()/2,
                    top:canvasObj.getHeight()/2,
                    itemName:'art'
                });

                canvasObj.add( image );
                canvasObj.setActiveObject( image );                
            }`

**Comment by asturur** [comment]
you have to set crossOrigin before setting src. refer to stackoverflow for further details
