### ISSUE TITLE
When does selection:cleared fires?

### ISSUE THREAD

**Issue by wearehappybits** [kangax/fabric.js#3867]
I have quite a big app and I can see that event selection:cleared fires on app load 2 times. When does this event is emitted? Or for what I could possibly look for in the codebase? So far looked for canvas.fabric.deactivateAll().renderAll(); only

Thanks.

**Comment by asturur** [comment]
search for 'selection:cleared' inside fabricjs. you will find it 3 or 4 times. is mostly fired from mousedown or mouseup events and deactivateAll OR setActiveObject.
