### ISSUE TITLE
canvas.toObject not returning expected data

### ISSUE THREAD

**Issue by bocajspear1** [kangax/fabric.js#3873]
## Version
1.7.6

## Test Case
http://jsfiddle.net/7yuxaqeo/6/

## Steps to reproduce
Add an object and set properties such as `hasControls` and `selectable`, and run `canvas.toObject()`

## Expected Behavior
According to http://fabricjs.com/fabric-intro-part-3, I should be getting properties such as `selectable` and `hasControls`

Example output from the documentation.
```
'{"objects":[{"type":"rect","left":50,"top":50,"width":20,"height":20,"fill":"green","overlayFill":null,"stroke":null,"strokeWidth":1,"strokeDashArray":null,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"selectable":true,"hasControls":true,"hasBorders":true,"hasRotatingPoint":false,"transparentCorners":true,"perPixelTargetFind":false,"rx":0,"ry":0}],"background":"rgba(0, 0, 0, 0)"}'
```

## Actual Behavior
The expected properties are not present. I can force the properties by adding them to `propertiesToIncludeopt` but the documentation seems to indicate they are there by default. (The documentation doesn't say anything about `lockMovementY` and `lockMovementX` but it seems reasonable to assume that they would be included in the `toObject` output.)

**Comment by asturur** [comment]
no they are not. you have to include them with the includeProperties array.

**Comment by bocajspear1** [comment]
Could the documentation be updated to reflect this? Thanks.

**Comment by asturur** [comment]
As soon as i have time i will update the tutorials. They are kind of outdated in many parts.
