### ISSUE TITLE
Fabric 1.7.9 activeGroup issue

### ISSUE THREAD

**Issue by ashkot123** [kangax/fabric.js#3875]
Hi all,
I recently upgraded to v1.7.9 which I believe is the latest version, and in my code I am sub classing images and adding them to the canvas. Code used to work fine but now I am getting an error as follows:

0x800a138f - JavaScript runtime error: Unable to get property '_activeGroup' of undefined or null reference

Can someone please help me understand what this error really means and what the fix for this could be?

Thanks in advance.

**Comment by asturur** [comment]
Please show a fiddle with your failing code.
