### ISSUE TITLE
SVG Loading is broken in Fabric 1.7.10 & 2.0

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3876]
It seems that since the v1.7.10 the SVG loading function is broken.

http://jsfiddle.net/526wC/93/

There is an error on the cache : `TypeError: this.group.isCaching is not a function`

**Comment by asturur** [comment]
i did not create isCaching for pathGroup. can you do:

fabric.PathGroup.prototype.isCaching = fabric.Group.prototype.isCaching;

**Comment by ncou** [comment]
I added the code snippet you mention, but the SVG is not correctly rendered.
It seems a part of the shape is not displayed.

For the moment, i have disabled the cache to continue to test.

**Comment by asturur** [comment]
i ll fix shortly. as sson as i go to pc.
