### ISSUE TITLE
Fix for iText hidden textarea not positioning correctly on FF

### ISSUE THREAD

**Issue by TeRMiNaTe** [kangax/fabric.js#3883]
The hidden textarea that gets added when editing an iText object doesn't have valid x and y properties. After some debugging I found that this line inside _calcTextareaPosition returns a string instead of an integer, which causes the issue:
```
charHeight = this.getCurrentCharFontSize(lineIndex, charIndex),
```
Adding a parseFloat will sort the issue:
```
y: boundaries.top + boundaries.topOffset + parseFloat(charHeight)
```

**Comment by asturur** [comment]
can you verify that the code is still good for latest master? all whole new text has been added

**Comment by TeRMiNaTe** [comment]
`_calcTextareaPosition` hasn't been modified afaik and the issue still persists in the latest version. Using `parseFloat` won't break anything, since that variable is only used for calculations within the function.

**Comment by asturur** [comment]
would you open a pr with necessary changes?

**Comment by asturur** [comment]
getCurrentCharFontSize return a number, precisley it returns object.fontSize that has to be a number. I cannot get the wrong position in firefox. how do you trigger this? can you reproduce in a fiddle?
