### ISSUE TITLE
fabric.js:12689 Uncaught TypeError: CreateListFromArrayLike called on non-object

### ISSUE THREAD

**Issue by prabhakaran3492** [kangax/fabric.js#3884]
I retrieve all object from DB with their own properties. But in rendering its throws error in core fabric js. I need your guidance sir.

# **PHP File**

/**
* [loadsingledesignAction description]
* @return [array] [save design load builder page]
*/
public function loadsingledesignAction() {
$customerData = Mage::getSingleton('customer/session')->getCustomer();
$id = $this->getRequest()->getPost('id');
$customDesigns = Mage::getModel('appcustomizer/customdesigns')->load($id);
if(count($customDesigns) > 0) {
$designdata = $customDesigns->getData();
$data = array('product' => $designdata['product_id'],'customdesign' => unserialize($designdata['design']), 'customdesign2' => unserialize

($designdata['design2']), 'design_id' => $designdata['id']);
$output = json_encode(['status' => true, 'html' => $data], JSON_NUMERIC_CHECK);
$output = str_ireplace('"false"', 'false', $output);
$output = str_ireplace('"true"', 'true', $output);
}
$this->getResponse()->setHeader('Content-type', 'application/json');
$this->getResponse()->setBody($output);
}

# **Js File**
![screenshot from 2017-04-25 17 17 06](https://cloud.githubusercontent.com/assets/22974008/25384081/82d3731a-29dc-11e7-98e2-5854b3d286b1.png)

# **Otuput**
![screenshot from 2017-04-25 17 11 22](https://cloud.githubusercontent.com/assets/22974008/25384088/8f256632-29dc-11e7-9d58-28e9e370ed5d.png)

**Comment by asturur** [comment]
please replicate the problem on a jsfiddle or we will close this issue.
You can understand that is not possible to help with no running code.
