### ISSUE TITLE
space pretends as enter in chrome

### ISSUE THREAD

**Issue by archirayan3** [kangax/fabric.js#3891]
## Version
1.6.3

## Test Case
https://jsfiddle.net/mh1gwnow/1/

## Steps to reproduce
open fiddle link on chrome
try to edit textbox
set cursor position at middle of some text
now hit space
you will see that text goes to new line
## Expected Behavior
it should make space between two character

**Comment by asturur** [comment]
chrome bug, avoidable updating to 1.7.9+ or modifying the css of your textarea for input. i suggest you to update.
