### ISSUE TITLE
How to draw straight line in Fabric

### ISSUE THREAD

**Issue by nitintomer** [kangax/fabric.js#3893]
Please correct me if I am wrong, lines in fabric are drawn as joining two diagonal ends of a rectangle. This make drawing a purely vertical or horizontal line very tough if not impossible.

Is there any way, I can do that?

Regards

Nitin

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
