### ISSUE TITLE
object:modified does not fire when modify object by touch gesture on android 

### ISSUE THREAD

**Issue by skywards1910** [kangax/fabric.js#3895]
I built a custom verstion of fabricjs 1.7 with choosing Gestures option.  Gesture functions acted well in mobile when I used two fingers to scale, rotate object. But event 'object:modified' was not fired. 

What event will be fired if I modify object by gesture?

**Comment by asturur** [comment]
it should fire. can you share a fiddle?

**Comment by asturur** [comment]
can you share a fiddle that demonstrate the problem?
