### ISSUE TITLE
scaleToWidth(x).animate

### ISSUE THREAD

**Issue by bl00mber** [kangax/fabric.js#3897]
Can I animate scaleToWidth for svg files? Or how svg files should be scaled with animation?

**Comment by asturur** [comment]
you can animate the scaleX and scaleY property. Please check animation example on fabric website.

**Comment by bl00mber** [comment]
scaleX and scaleY used relative scaling. Is there any possibility for scaling to pixel sizing, as in scaleToWidth?

**Comment by asturur** [comment]
scaleToWidth increment changes scaleX and scaleY. once you know what is the scale factor you need, animate them to that value. no other way
