### ISSUE TITLE
toSVG() method generate tspan with wrong value of X

### ISSUE THREAD

**Issue by gpisrtandel** [kangax/fabric.js#3904]
## Version
1.7.11

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Steps to reproduce
1) Create any Text Element
2) Insert Text and just align to Right or Center
3) generate SVG using toSVG() and check tSpan node X value that may be wrong.

## Expected Behavior
We need correct X value in toSVG()  result.
Like TextBox width is 250. and inserted text width is 80
then tSpan result will be mention below
For Lfft align x = -125
For Center align x = -40
For Right align x = 45

## Actual Behavior
Like TextBox width is 250. and inserted text width is 80
then tSpan result will be mention below
For Lfft align x = -125
For Center align x = 0
For Right align x = 125

**Comment by asturur** [comment]
you should expose a fiddle where the bug shows up with minimal code possible. thanks

**Comment by asturur** [comment]
Please create a fiddle with the problem so that we can check it.
