### ISSUE TITLE
Event fire on objects inside group

### ISSUE THREAD

**Issue by alexandrebarreiros** [kangax/fabric.js#3905]
## Version
1.7.7

## Test Case
https://jsfiddle.net/v7xyke0p/0 - wrong behaviour
https://jsfiddle.net/v7xyke0p/1 - correct behaviour

## Steps to reproduce
When i add objects to previous group the new objects don't fire the events, if i add the objects at the same time i create the group it works

## Expected Behavior
It shoud fire the events on both ways
## Actual Behavior
It won't fire the event

**Comment by asturur** [comment]
very strange. i think addWithUpdate should perform an additional .setCoords. ill check it.
