### ISSUE TITLE
Fabric Group SubTarget inconsistent behaviour

### ISSUE THREAD

**Issue by kevinfarrugia** [kangax/fabric.js#3906]
## Version
1.7.11

## Test Case
http://jsfiddle.net/896futf0/4/

## Steps to reproduce
1. Create a canvas
2. Create an object
3. Create another object
4. Add both objects to a group and set `subTargetCheck: true`
5. Add an event listener to each item
6. Click on either item
7. Click on either item again (without deselecting)

(Note that it works well if the group is set to `selectable: false`

## Expected Behavior
Event should trigger twice in total, once on each mouse down.

## Actual Behavior
Event is triggering multiple times when object is active without consistency.

**Comment by asturur** [comment]
yes the mouse move is interfering with it. i will try to fix it. the event is fired hundres of time.
