### ISSUE TITLE
Big Canvas and "skipOffscreen" param slow render

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3913]
Hi,

I  got a high CPU and Ram use, and some slow animations in my software (on a new piece of new code and with the beta 2.0) when i create a big canvas and i change the dimensions to reduce the rendered area, even if i use the "skipOffscreen" parameter.

Before opening a jsfiddle with a part of my code, i want to confirm i doesn't do something wrong.

Here is the situation :
In my editor i want to have a fullscreen canvas, but only the 700x500px area in the center of this wanvas will be used in the render page (it's another page).

- I doesn't set width or height on the canvas css style for the editor page.
- I create a canvas of 2000x2000px using new Fabric.Canvas parameters and (skipOffscreen=true, retina=false)
- I change the canvas size using .setDimensions() to the width and height of the monitor resolution.
- I do an absolutePan() to center the canvas.
- [I also add an overlay box to indicate visualy to the user the area who will be keeped in the viewer page (the 700x500 pix to keep in the center of the editor)].

The used can now add some objects (mostly images) and add some animations.
There is not really some slowdown in the editor page (but some frames seems to skip in the animation), the slowdonw are mostly in the "viewer page".

Once the user have saved his work in the "editor" page he can see the result in the "viewer" page.

In this page I :
- Create a 700x500px Static Canvas with the parameter "skipOffscreen=true" (and retina=false)
- Load the JSON with all the objects (there is also a background color and an image background in this json)
- do an absolutePan(1000,1000) to center the view in the canvas. 
- Play the animations, and the render() function seems to use an enorme amount of CPU.
=> The render is slow and with hight CPU usage, the browser seems to use a large amount of memory.

I was thinking using setDimensions() allow to render only this area (700x500px). But it seems it's all the 2000x2000px who is rendered, even with the parameter "skipOffscreen".
=> Is that normal ? perhaps the lib need to load the big canvas and render it even if it's only to show a part of the big canvas ?
=> If not i will try to create a fiddle with these steps.

To sumup, in my editor i need to create a fullscreen canvas, save the json, and in my viewver page, load the json in a smaller canvas (but from the point of view of the center of the editor canvas, not from top/left).

PS : I fix the width and height because the setDimensions() resize from the top left corner and not the center of the canvas, so il need to know how many pixel i should do the "pan" to center, i could store the center point based on the screen resolution, but i want to avoid to store this info. So it's a bit "lame" but it's the only way i have found.

Sorry for my poor english.

**Comment by asturur** [comment]
@ncou to debug this viewing the app would be helpfull. Is not possible to understand from what the perf issue is coming. is the editor available somewhere?

**Comment by ncou** [comment]
hi,

The editor is not yet available on internet. I will try to quickly relaease a version to allow a debuging.
I have check the code and normaly the object is nor rendered (render will do a return if the object is outside the screen size) if it's outside the canvas. Perhaps my background image & color is messing the render.

Normaly a resized and panned canvas (to 700x500pix for example) should have the same perf as an initial canvas (initialised to 700x500px) for the same width and height ? I am right ?

Thanks for your efforts.

**Comment by asturur** [comment]
@ncou can we close this?

**Comment by ncou** [comment]
Yes, i have made a few code changes and i need to check if the perf are better. I will open a ticket later if i pinpoint the problem.
