### ISSUE TITLE
Calling twice canvas.addEventListener("handleDrop

### ISSUE THREAD

**Issue by vxrai** [kangax/fabric.js#3916]
We are dynamically adding images through ajax in 2 different divs 

After the images are fetched from the server we iterate them and apply the code below
The code below is applied twice. Once for each ajax request/ div

if (Modernizr.draganddrop) {
    // Browser supports HTML5 DnD.

    // Bind the event listeners for the image elements
    var images = document.querySelectorAll('.images img.newimg');
    
    [].forEach.call(images, function (img) {
      
        img.addEventListener('dragstart', handleDragStart, false);
        img.addEventListener('dragend', handleDragEnd, false);
      
    });

    // Bind the event listeners for the canvas
 
    var canvasContainer = document.getElementById('canvas-container');

    canvasContainer.addEventListener('dragenter', handleDragEnter, false);
    canvasContainer.addEventListener('dragover', handleDragOver, false);
    canvasContainer.addEventListener('dragleave', handleDragLeave, false);
    canvasContainer.addEventListener('drop', handleDrop, false);
 
} else {
    // Replace with a fallback to a library solution.
    alert("This browser doesn't support the HTML5 Drag and Drop API.");
}

———
We addEventListerner to the canvas twice as the above code runs twice while dynamically adding images in two different divs one by one.

The problem that we face is that when we drag and then drop the image on the canvas - code below -
for some reason the handleDrop function is called twice for images in 2nd div. 
First   var newsrc = $(img).data(“src”); -> first returns null and then the actual image src.
If i don’t canvas.addEventlistener again while adding images in 2nd div, handle drop doesn’t work.

function handleDrop(e) { 
  

    var img = document.querySelector('.images img.img_dragging');

      var newsrc = $(img).data(“src”);

     fabric.Image.fromURL(img.src, function(image) {
        canvas.setActiveObject(image.set({
          left: e.layerX,
          top: e.layerY,
           scaleX: 1,
           scaleY: 1,
        
        })
        );
  
      canvas.add(image);   
 
    });

 return false;
}

I assume handleDrop is called twice on dropping images from 2nd div on canvas, because this code -

  var canvasContainer = document.getElementById('canvas-container');

    canvasContainer.addEventListener('dragenter', handleDragEnter, false);
    canvasContainer.addEventListener('dragover', handleDragOver, false);
    canvasContainer.addEventListener('dragleave', handleDragLeave, false);
    canvasContainer.addEventListener('drop', handleDrop, false);

is called twice , once while serving the 1st ajax request to add images in DIV1 and again while serving the 2nd ajax request to add images in DIV2.
How to unbind/removeEventListener from DIV2 images to avoid hitting the handleDrop function twice while dropping images from DIV2.

Any help to fix this one will be really helpful.

**Comment by asturur** [comment]
please open a question o  stackoverflow and link it here. with a working snippet.
