### ISSUE TITLE
Object controls broken when viewport has some rotation through transformation matrix

### ISSUE THREAD

**Issue by rathaiahy** [kangax/fabric.js#3917]
## Version
1.7.11

## Test Case
http://jsfiddle.net/7fsw81mp/45/

## Steps to reproduce
Please go to above jsfiddle and try to select the rectangle on the Canvas. You can observe that controls are broken. 

## Expected Behavior
When viewport has some rotation, I expect all objects on the canvas are rotated with view port and  every object should be interacted as usual with out any issues. 

## Actual Behavior
It seems the geometry and objects interaction logic around it is not considering the view port rotation.

**Comment by asturur** [comment]
there is no support for  canvas viewport transform other than scale and translate.
