### ISSUE TITLE
Double click support

### ISSUE THREAD

**Issue by ashkot123** [kangax/fabric.js#3918]
hi all,
could someone please point me in the direction for how to enable double click on fabric images? i came across this solution 

http://stackoverflow.com/questions/23418055/fabricjs-double-click-on-objects

I am trying to not use FabicjsEx

but i am unable to get anything to work correctly. can someone please let me know the best way to accomplish this?

**Comment by asturur** [comment]
probably move the code from iText to Object.
Check the code in IText for doubleclick simulation.

i shuld add the real doubleClick event.
