### ISSUE TITLE
Documentation: Full parameter table

### ISSUE THREAD

**Issue by Andrioden** [kangax/fabric.js#3919]
Would love a full parameter table for the object types (Line, etc..)

Se top of: http://fabricjs.com/docs/fabric.Line.html
Versus top of: https://konvajs.github.io/api/Konva.Path.html

**Comment by asturur** [comment]
how do i do that in jsdoc? any example?

**Comment by Andrioden** [comment]
Never worked with Jsdoc. But it seem to be related to the constructor. Look at http://fabricjs.com/docs/fabric.Color.html. Here you can see it has a parameter "new Color(color)", while many of the other subobjects does not, Rect, Line, Circle, Path, etc. Seems to be a lot of object types that is missing this documenation.

As a new user of Fabric.js and very fond of good documentation it was one very concrete thing i was looking for.

**Comment by asturur** [comment]
is not missing, is just documented over the properties.
That would be actual a double documentation for ease of presentation.

**Comment by asturur** [comment]
this can't really be done without tricking jsdoc
