### ISSUE TITLE
Safari adding no-break-spaces instead of spaces in IText

### ISSUE THREAD

**Issue by mlev** [kangax/fabric.js#3920]
## Version
1.7.11

## Test Case
Kitchen Sink Demo

## Steps to reproduce
1. Open Kitchen Sink Demo in Safari
2. In IText/Text box enter some text with spaces
3. Inspect text in Hex editor

## Expected Behavior
Regular spaces are entered (0x20)

## Actual Behavior
No break spaces are entered (0xC2A0)

## Notes
- This seems due to the "whitespace: nowrap" css on the hidden textarea (I know this was added recently to fix wrapping bug in Chrome).
- Adding textarea attribute wrap="off" and removing "whitespace: nowrap" seems to work ok in Safari and Chrome (not tested other browsers).

**Comment by asturur** [comment]
what if i add wrap="off" and leave whitespace: nowrap?

**Comment by mlev** [comment]
Just retried and that still enters no-break-spaces in Safari.

**Comment by asturur** [comment]
Ok i made the change and i ll publish it in 2.0 beta4.
