### ISSUE TITLE
Accents on MAC Operating System

### ISSUE THREAD

**Issue by pauloferreira89** [kangax/fabric.js#3921]
## Version
1.7.7

## Test Case
http://jsfiddle.net/o6L9y2fc/2/

## Steps to reproduce
1. Enter on the test case using MAC Operating System using PT ISO keyboard
2. Try to write some character using accents (ex: é)

## Expected Behavior
Should be render "é".

## Actual Behavior
It is being rendered "´";

**Comment by asturur** [comment]
fabric 1.x is not compatible with those kinds of input. please try to switch to the new beta branch.
available here on the master branch or on npm.
