### ISSUE TITLE
problem with import and background

### ISSUE THREAD

**Issue by Exlord** [kangax/fabric.js#3925]
## Version
1.7.11 and 2.0.0.beta

## Test Case
I am updating a second canvas using the exported data from the first canvas.It works until I try to undo the changes to a previews state.
I am keeping a array of states. Every time something is changed in the first canvas, I get a export and save it to the history array.
On undo I get the previews state from the history and import it to the canvas.(I have the full undo/redo future in my code, but for simplicity I'm only using the length-2 of the history array)
when Undo changes the first canvas the modified events fires and updates the second canvas.
http://jsfiddle.net/Exlord/nc2exg1y/

## Steps to reproduce
press **setBackground** -> **add object** -> **add object** -> **undo**

## Expected Behavior
The second canvas to look exactly like the first one

## Actual Behavior
The second canvas looses its background color/image.

**Comment by asturur** [comment]
you have a chain reaction of events with your event canvas:added and the loadFromJson that is adding lot of objects.
This is some problem of your app and not a fabricjs specific issue.
i suggest you to disable the event handlers during the restore.
