### ISSUE TITLE
overlay text on images and also clear it

### ISSUE THREAD

**Issue by ashkot123** [kangax/fabric.js#3926]
there several images on a canvas and i am using using fabricjs. what i would like is a way to add some text on the image such as in the center and i should be able to remove it as well.

i am wondering if there is a way to directly write over the image or do i have to create another layer and write onto it.

any ideas of how this could be done? i revived several discussions where it's not as clear, how it could be done.

any pointers would be most appreciated.

**Comment by asturur** [comment]
Please refer to docs examples or stackOveflow for this kind of questions.
