### ISSUE TITLE
Rich text layout framework for FabricJS

### ISSUE THREAD

**Issue by cksachdev** [kangax/fabric.js#3927]
Looking for rich text editing component, which can allow to do the following:

1. Bold/Italic/Underline at character level
2. Add actions at character level
3. Animation
4. Indentation
5. Fontsize/font family

txtjs looks promising but not sure how well it will integrate with fabricjs.

Below are 2 links for reference:
http://bergie.iki.fi/blog/hallo-editor/ 
https://www.froala.com/wysiwyg-editor/inline

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

**Comment by asturur** [comment]
Those are html editor, you need to build all the canvas render logic on your own then.
Fabric already support

Bold/Italic/Underline at character level
Fontsize/font family
and Indentation can be built with some little effort.
