### ISSUE TITLE
bug with new version of fabricjs

### ISSUE THREAD

**Issue by fix2015** [kangax/fabric.js#3930]
Hi, after update version of fabricjs, i have bug with IE-10,11 and mobile device on other all fine
![screenshot_8](https://cloud.githubusercontent.com/assets/3988392/26100767/78c525ce-3a37-11e7-852c-b3541196280b.png)

**Comment by fix2015** [comment]
so it added 2 border in bottom and rigtht, but i can't understand why, because i did nothing

**Comment by fix2015** [comment]
i found pb, its this code for retina 
`  if( window.devicePixelRatio !== 1 ){
      var c = canvas.getElement(); // canvas = fabric.Canvas
      var w = c.width, h = c.height;
      c.setAttribute('width', w*window.devicePixelRatio);
      c.setAttribute('height', h*window.devicePixelRatio);
      c.getContext('2d').scale(window.devicePixelRatio, window.devicePixelRatio);
}
`
do we need still this code, or you already it added to library???

**Comment by asturur** [comment]
is not easy to help in this way.
What is the problem? can you make a fiddle?
If you added some code that scales the main fabric context outside fabric knowledge, like that function, i highly suggest you to remove it.

Fabric does indeed support retina since 1.5.0

From what version are you updating?

**Comment by fix2015** [comment]
@asturur i had version 1.5.0 and now update to 1.7.11, and before i need this code for retina i took it from  here   [so](https://gist.github.com/paulkaplan/6050309), but if you said that not no need this func i will delete it, thx
