### ISSUE TITLE
Fabric application related queries

### ISSUE THREAD

**Issue by bijugit** [kangax/fabric.js#3931]
Hi,

We need to know about the fabric.js application with wordpress integration. is this work with wordpress application?

can we create any kind of shape dynamically ?

Regards,
Biju.                 

## Version
1.7.6

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by asturur** [comment]
fabricjs is a javascript library that nothing has to do with wordpress.
You can of course develop a wordpress plugin to do something with it.
But we cannot help with that here.
I have just basic capabilities with wordpress.

**Comment by bijugit** [comment]
Hi,

Thanks for your reply,

We need to create layout like http://prntscr.com/f8fu2i , is this javascript library support for creating layout structure creation dynamically.
Please give your valid feedback as soon as possible.

Regards,

**Comment by asturur** [comment]
Yes you can create a vector editor with fabricjs.
There are no things such arrows or dynamic measurement of objects, those are things you have to build by yourself.
