### ISSUE TITLE
Import with gestures

### ISSUE THREAD

**Issue by peteringram0** [kangax/fabric.js#3932]
Is there a way to import fabric.js with gestures and the other custom parts?

At the moment im doing the following but it does not include gestures. The only way i can find is to produce a custom ES5 build. Ideally i would like to import the custom parts i need.

````javascript
import {fabric} from 'fabric';
````

Thanks

**Comment by asturur** [comment]
i think that having the file somewhere and doing:

import 'src/mixins/canvas_gestures.mixin.js' would solve.
