### ISSUE TITLE
viewportTransform with value null

### ISSUE THREAD

**Issue by fix2015** [kangax/fabric.js#3934]
Does anyone had bug where canvas.viewportTransform = [null,0,0,null,null]?

**Comment by asturur** [comment]
please open a fiddle showing some code.
This is is not a forum.
I read it with a couple of people, is just for fixing bugs or proposing features

**Comment by fix2015** [comment]
@asturur but i can't show because it happened only sometimes code is too easy,  just load canvas and that after fabrcijs is initialize i run this canvas.viewportTransform and it show me [null,0,0,null,null]

**Comment by asturur** [comment]
if is not replicable, cannot put time on it.
