### ISSUE TITLE
 .jsdom is not a function error  in server side rendering

### ISSUE THREAD

**Issue by shinov** [kangax/fabric.js#3936]
Hi i am facing one issue with below require, when i am compiling code with webpack. 
jsdom version mentioned in the fabric.js  package.json is  **"jsdom": "3.x.x",**, it not available in npm and  its throwing **.jsdom is not a function**  error

**fabric.document = require("jsdom")
    .jsdom(
      decodeURIComponent("%3C!DOCTYPE%20html%3E%3Chtml%3E%3Chead%3E%3C%2Fhead%3E%3Cbody%3E%3C%2Fbody%3E%3C%2Fhtml%3E")
    );**

**Comment by asturur** [comment]
jsdom IS available in npm. maybe you cannot install because you are in node higher than 6?

**Comment by shinov** [comment]
@asturur  My node Version is v5.10.0.  jsdom IS available in npm but the version mentioned in fabric.js package.json is not installing the jsdom.

**Comment by SoniaBalodi12** [comment]
Hi,
Getting this error when trying to include react-fabricjs in react code, server side rendering.
C:\MSP_Designer\msp.designerui\node_modules\fabric-webpack\dist\fabric.js:18
    .jsdom("<!DOCTYPE html><html><head></head><body></body></html>");
     ^
TypeError: require(...).jsdom is not a function
    at Object.<anonymous> (C:\MSP_Designer\msp.designerui\node_modules\fabric-we
bpack\dist\fabric.js:18:6)

https://www.npmjs.com/package/fabric-webpack uses fabric.js inturn.

Please suggest !..  

Regards,
Sonia

**Comment by asturur** [comment]
guys is something webpack related.
when you talk about server side rendering is unclear what you refer to, if canvas rendering or dom rendering.

**Comment by shinov** [comment]
@astururl, leave the server-side rendering, if I am trying to install fabric@1.7.11 npm module, in normal scenario jsdom npm module should get installed inside node_modules folder( as per my knowledge), but that is not happening in the fabric instillation. Do you have any idea why that is not happening?

**Comment by asturur** [comment]
no. i can install it normally. on node from 0.10 to 6 on linux. on macos i tried 4 and 6.

**Comment by Sreevedvp** [comment]
# i am facing an issue when i am trying to import the library which i created to the project 
Uncaught TypeError: jsdom.JSDOM is not a constructor
in the console

i am using node version 19 and fabric 5.3.0
