### ISSUE TITLE
italic not working in 1.7.11 ,nodejs version:0.10.3

### ISSUE THREAD

**Issue by tangzicheng** [kangax/fabric.js#3938]
I use the node version : 0.10.3 ,fabric.js version : 1.7.11. 

when I use the fabric.js to draw text which fontStyle is 'italic' in nodejs, but I found it's not working, when I set fontWeight is 'bold', then It will working

**Comment by asturur** [comment]
please provide an example to run.

**Comment by tangzicheng** [comment]
bash code
`#!/bin/bash
node app2.js '{"objects":[{"type":"text","originX":"left","originY":"top","left":50,"top":50,"width":25.47,"height":15.82,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"text","fontSize":14,"fontFamily":"Arial","fontStyle":"italic","fontWeight":"bold","textBackgroundColor":"","textDecoration":"normal","lockMovementX":false,"lockMovementY":false}],"background":"white"}'
`

**Comment by tangzicheng** [comment]
app2.js

`var fabric = require('fabric').fabric;
var fs = require('fs');

function save(canvas) {
  var out = fs.createWriteStream(__dirname + '/tmp.png');
  var stream = canvas.createPNGStream();
    stream.on('data', function(chunk) {
      out.write(chunk);
  });
  stream.on('end', function() {
      out.end();
  });
}


var json = JSON.parse(process.argv[2]);

var canvas = fabric.createCanvasForNode(400, 400);
var ctx = canvas.getContext('2d');
ctx.antialias = 'none';
ctx.imageSmoothingEnabled = false;

canvas.loadFromDatalessJSON(json);
var objects = canvas.getObjects();
canvas.renderAll();
canvas.setBackgroundColor('white');

save(canvas);
`

**Comment by tangzicheng** [comment]
when I set "fontWeight":"normal" and "fontStyle":"italic", the text will italic,  but when I set "fontWeight":"bold" and "fontStyle":"italic", it is not works

**Comment by tangzicheng** [comment]
when I use "npm install -g fabric@1.6.7", It will works very good
