### ISSUE TITLE
setVisible not updating the visibility of object until renderAll() is called

### ISSUE THREAD

**Issue by vin-dev** [kangax/fabric.js#3940]
## Version
1.7.11

## Test Case
http://jsfiddle.net/ucm964hz/

## Steps to reproduce
Click on hide button

## Expected Behavior
Circle should be hidden immediately

## Actual Behavior
Circle is not hidden until renderAll() is called on fabric canvas

For my usecase, there will be  a lot of fabric shapes on canvas and I will be selectively hiding some of them. I feel calling a renderAll() for this would have performance implications. So is there a better way to do this or this is by design?

**Comment by ncou** [comment]
Hi,

I think renderAll() is used to redraw the canvas, so if you change the canvas (using visible=false for example), you need to redraw it.

There is a cache mechanism in fabric.js so even if you redraw a bunch of objects, there should have a performance slow down.

**Comment by vin-dev** [comment]
@ncou 
 I guess you meant, since there is a caching mechanism, there should not be a performance slow down. If that is the case, I am good to go with this approach.

**Comment by asturur** [comment]
you have no other choice.
You change a bunch of properties in the object, as many as you want. Then you redraw once.

So you can switch visibility on and off of all your object and then you have to redraw at least once.
Redrawing for every object during a loop would be wrong for example.
