### ISSUE TITLE
Wrong image when using object.toDataURL and clipping

### ISSUE THREAD

**Issue by radykal** [kangax/fabric.js#3942]
## Version
1.7.6

## Test Case
http://jsfiddle.net/ZxYCP/796/

## Steps to reproduce
I used one of these codes for correct clipping, which is working fine. But now I would like to export a single object with todataURL() and cropping. The cropping will be calculated by the clipping object, but how to calculate the correct offset?

**Comment by asturur** [comment]
Please if still unsolved, move to stackoverflow with a working snippet.
