### ISSUE TITLE
Issue with LoadFromDatalessJSON and Custom Filter

### ISSUE THREAD

**Issue by Tsunami2069** [kangax/fabric.js#3943]
Hello every1.

First of all, as always, congratulations on a excelent library. FabricJS has been amazing for a project of mine.

Now my issue...
My project uses a custom filter that hasn't been added to fabricJS, which is Hue.
It also has a feature where i switch from different pages by saving the current pages canvas.toDatalessJSON , storing it, resetting / clearing the canvas and loading the next page with canvas.loadFromDatalessJSON

Now everything has been working fine, including the filter itself UNTIL I tried to switch pages to a page that has an image with this custom Hue filter applied.
When the new page has an image with the Hue Filter applied to it, the loadFromDatalessJSON doesn't work, the images aren't added and callback isn't, well, called :).

I have tried this with other filters and when it's other filters, the loadFromDatalessJSON works fine, images are added WITH the filters.

Could this be an issue with my filter or an issue with the loadFromDatalessJSON?
You can find the filter on the fiddle.

Version being used: 1.7.11
Fiddle: https://jsfiddle.net/8s7g6s48/6/

How to reproduce:
Clicking the Apply Saturation button will apply the saturate filter to the image. After that, click the "To Dataless JSON & Clear" to save the dataless json and clear the canvas. Then click the "Load From JSON" button to reload the canvas with the dataless json. You will notice the image is added back without problem (you even get a "loaded" alert).
Repeat the same process but instead of clicking the "Apply Saturation" button, click the "Apply Hue". You will notice that, after clicking the "Load From JSON", the images are not added and we get no "loaded" alert (showing that the callback isn't called).

**Comment by asturur** [comment]
Please check any of our filter fromObject method and copy it.
It should solve.

Also consider this PR https://github.com/kangax/fabric.js/pull/3915
And check if you want to propose a HUE filter in the new format.

**Comment by asturur** [comment]
Customs filter will require an update for fabric 2.0

**Comment by Tsunami2069** [comment]
Hello @asturur 
First of all thanks for the help and feedback.

I fixed the filter with ur advice (replacing my fromObject with a similar one to the other filters).

As for proposing a hue filter in the new format, do you mean suggesting a hue filter to be added on a new version of fabricjs? If so, how can i do that?

Thanks once more.

**Comment by asturur** [comment]
og on the link i posted before, from the list of file changed, pickup the brightness filter for example and check what it does and how. then do a similar file for the hue.

**Comment by Tsunami2069** [comment]
Alright, will do... 

Thank you once more.
