### ISSUE TITLE
text in newer versions is much more blur than in versions since 1.6.7

### ISSUE THREAD

**Issue by astw** [kangax/fabric.js#3947]
Add itext into canvas,  and call   canvas.centerObject(txtBox),   text added became blur. 
This does exist before version 1.6.7. 

## Version
 > [1.6.7]
##   reproduce 
[http://jsfiddle.net/astw/gs6u95fj/](http://jsfiddle.net/astw/gs6u95fj/)  

## sample image
result:
[https://drive.google.com/file/d/0B9pql9Aco21PTDdvYlJRNXZQMTA/view?usp=sharing](https://drive.google.com/file/d/0B9pql9Aco21PTDdvYlJRNXZQMTA/view?usp=sharing)

Environment: windows 2008, Chrome 58.*

**Comment by asturur** [comment]
we solved it a bit, we cannot solve it completely. the only alternative is disabling objectCaching for your project.

**Comment by asturur** [comment]
http://fabricjs.com/fabric-object-caching

**Comment by astw** [comment]
I works,  Thank you @asturur
