### ISSUE TITLE
LoadFromJSON with custom class throws exception 

### ISSUE THREAD

**Issue by astw** [kangax/fabric.js#3948]
Call loadFromJSON using a string with customized class throw exception.  

Uncaught TypeError: text.split is not a function  
 
## Version
1.7.8， 1.7.9，1.7.11， 2.0.0-beta.1

## Test Case
http://jsfiddle.net/astw/Da7SP/547/

**Comment by ncou** [comment]
Hi,

Could you try this : https://github.com/kangax/fabric.js/issues/3851

By the way, it seems to me the textbox object will soon be removed from the code (in v2.x version).

**Comment by asturur** [comment]
http://jsfiddle.net/Da7SP/552/

please check other text fromObject method, you will see it is different.
