### ISSUE TITLE
Working code in 1.6.7 stops working in version >= 1.7.0

### ISSUE THREAD

**Issue by AlessandroDM** [kangax/fabric.js#3949]
Good Day,
I have a code snipped that used to work without problem.

## Version
Any version >= 1.7.0

## Test Case
Working Code (in this fiddle it is using 1.5.0 but it works until 1.6.7)
https://jsfiddle.net/j7n4jhaa/

Exact same code (in this fiddle it is using 1.7.7 but it stops working from 1.7.0)
https://jsfiddle.net/zdc3q5sz/

## Steps to reproduce
Rotate the group on screen.

## Expected Behavior
The event on "object:rotating" sets the text orientation (Angle) back to original
(keeping the text horizontal while rotating).

## Actual Behavior
The text rotates with the shape regardless of the routine in place.

I have no idea why this happens and if I have made some mistake somewhere.

Thank you.

**Comment by ncou** [comment]
Hi,

There is in v1.7.0 a cache mecanisum. Check the documentation.

Here is a working example :
https://jsfiddle.net/zdc3q5sz/1/

Close your ticket if it's soved.

**Comment by AlessandroDM** [comment]
Hello Ncou,
Thank you for your quick answer.
One would think that setting the "angle" programmatically would follow the cache settings and continue to work (by painting in the hidden canvas first and copying as it does when caching is on).

Anyway since disabling the object caching indeed resolved the issue, ticket closed.

Thanks again.

Ticket Closed.

**Comment by asturur** [comment]
Instead of disabling the cache, you can:

set the text as dirty with `obj.set('dirty', true)` (obj.dirty=true won't work)
Then you can override the group function that calculate the cache size to give it a bit more space to fit the horizontal text. Or recalculate the group bounds at every rotation but seems expensive to me.

**Comment by AlessandroDM** [comment]
Hello Asturur,
Adding obj.set('dirty', true) also worked with the benefit of keeping the cache speedup (before I was disabling the cache for the whole canvas).

How does one know when marking dirty the specific object is necessary? 
Is this needed only when changing objects properties inside fabric "events" like in my case or there are other situations?

Grazie.

**Comment by asturur** [comment]
So we try to save the render operation as much as possible.
Fabric has 2 way to decide when is time to re render an object and are described in the link
http://www.fabricjs.com/fabric-object-caching
If you take 5 minutes and read it slowly ( underling obscure point would be helpfull ) it will gives you information on how this cache system works.

If you are heavily subclassing the objects you may need to subclass the cache relative functions to get a bigger cache size ( to draw things that get out of object bounding box ).

Keep in mind that i introduced in 1.7.0 and till 1.7.11 i tried to refine it. There are still some more adjustments i have to do, trying to get both of performance and non blurriness on downloads.

You want to set an object to dirty everytime you change a property if you want to save on cpu time, or let fabric understand reading the cacheProperties array if something is changed.
When the dirty prop is true, fabric will rerender and skip cache checks.

**Comment by AlessandroDM** [comment]
I guess I can work with the rule "always set object to Dirty after property change" (as well as disabling the cache for stuff that does not need to be blistering fast).

P.S. I read "slowly" the part of the doc you mentioned. It explains clearly how it works although I think that it still not really clear in which case should be used (bear in mind I have not read the fabric code, I just use the library and I may be a bit slow myself :-) )
By the way there's a little typo there "Live sampes" instead of "Live samples" and the right canvases in the docs don't show much (or not at all) on my browsers (Chrome, Firefox, Safari).
Not a criticism by all means, just highlighting since you asked :-)

In any case, I think I can stop bothering you for this item now, you guys have been of great help and gave me 2 ways of solving the problem, thank you so much.

**Comment by asturur** [comment]
yeah that canvas broke recentely, due to `refinements`.

Cache should be always used, you should understand when is better disabling it instead of going crazy. That is the thumb rule.
