### ISSUE TITLE
'clipTo' running 2 times? Is that normal?

### ISSUE THREAD

**Issue by josefano** [kangax/fabric.js#3954]
Hi,

I noticed that when adding a 'clipTo' function to an object, the function runs 2 times, sometimes it runs 3 times. I wanted to know if that is a bug or is it is normal and there is a logic behind.

FabricJs version :
1.7.9

Demo Fiddle  :

https://jsfiddle.net/josefano09/4cfmnvnk/

Check the console and you will see 'testing' being displayed 2 times

**Comment by asturur** [comment]
Yes, one fore canvas.add and one for canvas.renderAll
