### ISSUE TITLE
Picuture doesn't display until manually change the textbox size.

### ISSUE THREAD

**Issue by astw** [kangax/fabric.js#3955]
I am not sure if this is a feature or bug,  because it did not exist in older versions (<1.7.0). 
Only after I resize the text control,  the picture displays. 

## Version
1.7.11 and newer

## Test Case
http://jsfiddle.net/bu3y8q5n/2/

To reproduce, 
Click the text and resize the text.  The picture shows up.

**Comment by samael205** [comment]
Try change the last line

`canvas.loadFromJSON(jsono, canvas.renderAll.bind(canvas)());
canvas.renderAll();`

**Comment by astw** [comment]
Works,  thank you so much!
