### ISSUE TITLE
Textbox Text Decoration Issue

### ISSUE THREAD

**Issue by ImTheMark** [kangax/fabric.js#3956]
## Version
2.0.0-beta1

## Test Case
http://jsfiddle.net/p3g2L774/

## Steps to reproduce
Please check the jsfiddle provided. The fabric canvas will contain a rectangle and a textbox.
The code provided is based on the http://fabricjs.com/fabric-intro-part-2#text.

## Expected Behavior
The textbox should appear underlined.

## Actual Behavior
The textbox does not appear underlined.

**Comment by asturur** [comment]
http://jsfiddle.net/p3g2L774/2/

As 2.0 is not ready yet for docs and examples, one thing that changed is that textDecoration has been removed.
In place we have:  .underline, .overline, .linetrought  each of them with a true or false.
