### ISSUE TITLE
Text loses smoothing after animation

### ISSUE THREAD

**Issue by Lomkex1** [kangax/fabric.js#3957]
I use GIF encoder to convert canvas animation to GIF.
I came across to an issue where after the first frame text loses smoothing and appears as `imageSmoothingEnabled` is set to false when it's set to true
this image shows the first frame of the animation
<img src = "http://i.imgur.com/Kk4kSdX.png" >
this one shows how the next frames look
<img src = "http://i.imgur.com/g8Vg7uV.png" >
as you can see smoothing is disabled

**Comment by asturur** [comment]
please open a fiddle with relevant code
