### ISSUE TITLE
Is there a way to add html elements in a fabric container? 

### ISSUE THREAD

**Issue by cksachdev** [kangax/fabric.js#3958]
Considering canvas doesn't have support for rich text features e.g. bulleted list, tables etc. Is there a way to contain html markup in a fabricjs container, which will take care of the following:
1. Getting fabricjs handles for the div
2. Handles double click event
3. Div is bound to the canvas boundaries

**Comment by asturur** [comment]
no.
if your main concern is text, better stay with just html and rich text and forget canavs.

or you have to build this components. bullet list is not hard, table may be a bit of work more. i do not see other options.

**Comment by cksachdev** [comment]
@asturur Is there a container in fabric, where I can add dom elements/markup? Such that I get fabricjs handles to move the object, rotate etc.?

**Comment by cksachdev** [comment]
something similar to EaselJS DOM element.
createjs.com/demos/easeljs/DOMElement.html

**Comment by samael205** [comment]
You need to handle the DOM element without fabricjs using jQuery for example. Fabricjs only can handle the canvas context. Are elements totally different.
In your Example, the div are above the canvas, and not inside.

**Comment by cksachdev** [comment]
@samael205 Please do a view source, sharing the snippet below from createJS:
```
var stage, container;

	function init() {
		// create a new stage and point it at our canvas:
		canvas = document.getElementById("testCanvas");
		stage = new createjs.Stage(canvas);

		container = new createjs.Container();
		stage.addChild(container);

		var frame = new createjs.Shape();
		frame.graphics.beginFill("#F00").drawRect(0, 0, 300, 300);
		frame.regX = 150;
		frame.regY = 150;

		var content = new createjs.DOMElement("foo");
		content.regX = 140;
		content.regY = 140;
		//content.visible = false;

		container.addChild(frame, content);
		container.x = 480;
		container.y = 150;
		container.alpha = 0.8;
		container.rotation = -45;
		//container.visible = false;

		createjs.Ticker.timingMode = createjs.Ticker.RAF;
		createjs.Ticker.addEventListener("tick", tick);
	}

	function tick(event) {
		container.rotation += event.delta * 0.01;
		container.alpha = 0.5 * (1 + Math.cos(container.rotation * 0.01));
		stage.update(event);
	}
```
You can see that DOMElement is added in the container.

**Comment by samael205** [comment]
Fabricjs does not suport that functionality, you must handle DIV element DOM with jQuery or pure JS

**Comment by asturur** [comment]
![image](https://cloud.githubusercontent.com/assets/1194048/26398517/04cd22a4-407a-11e7-8508-5ae6cad4a76f.png)

The point that they underline that is not rendered on the canvas means it cannot be exported.
As of now the highest value of fabricjs, beside interaction, is export to png/jpeg/svg at high resolution.
What cannot enter in this flow is not worh having for the library. You can build yourself on top of it.

I guess you can create an html element, and apply to it a css-transform matrix property with the matrix got from `.calcTransformMatrix`

**Comment by asturur** [comment]
is really out of scope of the library, also as a feature request.

**Comment by Hew007** [comment]
![image](https://github.com/fabricjs/fabric.js/assets/26536518/314313aa-e7bb-4cef-9cdd-6b7d8bd95aab)
You can refer to the official example：[interaction-with-objects-outside-canvas](http://fabricjs.com/interaction-with-objects-outside-canvas)
Custom elements are displayed on the fibric canvas by position
