### ISSUE TITLE
can't use the public fonction "drawSelectionBackground" for an object

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#3961]
Hi,

It's not a bug, more of a feature request.
For the moment, we can't call the "drawSelectionBackground()" function on the object if the object is not "active = true".

This limit the use of this function. Especially if you want to use it on the object, when hovering the object with the mouse over event.

there is a bunch of controls at the start of the function to exit if : there is no selectioncolor, or if it's a group or if it's not active.

Here is the code :
```javascript
drawSelectionBackground: function(ctx) {
      if (!this.selectionBackgroundColor || this.group || !this.active ||
        (this.canvas && !this.canvas.interactive)) {
        return this;
      }
      ctx.save();
      var center = this.getCenterPoint(), wh = this._calculateCurrentDimensions(),
          vpt = this.canvas.viewportTransform;
      ctx.translate(center.x, center.y);
      ctx.scale(1 / vpt[0], 1 / vpt[3]);
      ctx.rotate(degreesToRadians(this.angle));
      ctx.fillStyle = this.selectionBackgroundColor;
      ctx.fillRect(-wh.x / 2, -wh.y / 2, wh.x, wh.y);
      ctx.restore();
      return this;
    }
```

Why not dispatch it in 2 functions : 
1) rename the actual fuction to '_drawSelectionBackground()' [use underscore to keep in mind it's private use only] and keep the controls + call the public function.
2) check in all the code the reference to rename the calls to this function.
2) Create a new function with the public name 'drawSelectionBackground()' to draw the selection background without doing controls, so this function can be used publicly.

This could be somethink like this :

```
_drawSelectionBackground: function(ctx) {
      if (!this.selectionBackgroundColor || this.group || !this.active ||
        (this.canvas && !this.canvas.interactive)) {
        return this;
      }
      this.drawSelectionBackground(ctx);
    },

drawSelectionBackground: function(ctx) {
      ctx.save();
      var center = this.getCenterPoint(), wh = this._calculateCurrentDimensions(),
          vpt = this.canvas.viewportTransform;
      ctx.translate(center.x, center.y);
      ctx.scale(1 / vpt[0], 1 / vpt[3]);
      ctx.rotate(degreesToRadians(this.angle));
      ctx.fillStyle = this.selectionBackgroundColor;
      ctx.fillRect(-wh.x / 2, -wh.y / 2, wh.x, wh.y);
      ctx.restore();
      return this;
}
```

What do you think ?

**Comment by asturur** [comment]
this has the same problem of the renderControls, i stumbled in the same problem and i will make some fix.

**Comment by ncou** [comment]
Great news. Thanks :)

**Comment by ncou** [comment]
By the way, I use this thread to ask a question related to the "renderControl" function.

for the renderControls, we can pass an overide "bordersStyle" parameter.
Is that wanted we can't overide the "hasBorders", "hasControls", "hasRotatingPoint" values ? because in the code, there is check in the overidestyle values but also on the "this.hasXXX" value with an OR separator ?

**Comment by asturur** [comment]
i opened another issue for this to tackle it.
Regarding your last comment, i stepped into that 2 days ago, and i fixed it. I have just to push up the fix.
