### ISSUE TITLE
Recent renderControls override is not working great

### ISSUE THREAD

**Issue by asturur** [kangax/fabric.js#3964]
Some parameters cannot be override good.

Also need a way to draw the selection background area on request. ( this is not easy since is below the object stack.

The whole point of those overrides is to render object controls without changing the objects properties:
active, hasControls, hasBorders, and relative colors and strokes and shapes, and have to  restore them afterwards.

Investigate also the chance to give an activegroup a selection background. ( this also for 1.7.12 )

**Comment by asturur** [comment]
@ncou fixing this

**Comment by ncou** [comment]
thanks, it's now working fine.
