### ISSUE TITLE
How can i create a grid object using fabricJs

### ISSUE THREAD

**Issue by chandandas** [kangax/fabric.js#3968]
Hi ,

I have a requirement where i need add object as grid. Scaling this grid automatically increase and decrease grid cells.

Anyone has any ideas on how to do it? Even a quick tip would be very helpful.

**Comment by butch2k** [comment]
Yes, create a rect with a repetitive grid pattern, snap it to top left corner and set its height/width props to your canvas width/height.

It's fast but line width scale as well.

![image](https://cloud.githubusercontent.com/assets/961507/26553309/55b89670-448b-11e7-9efc-35a89d1dd1c4.png)
![image](https://cloud.githubusercontent.com/assets/961507/26553342/7b136706-448b-11e7-8991-9bf4b49244a4.png)

**Comment by chandandas** [comment]
Ok. Thanks

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
