### ISSUE TITLE
_fabric2.default.Canvas is not a constructor

### ISSUE THREAD

**Issue by gimyboya** [kangax/fabric.js#3970]
## Version
1.7.11

## Test Case
I am using electron-forge with node 7.9.0 i have installed `fabricjs` by using `npm install --save` everything was fine but when i try to use it i get the following error

![Imgur](http://i.imgur.com/d2emdLu.png)

## Steps to reproduce
maybe as i mentioned abouve
## Expected Behavior
start playing with the canvas!!
## Actual Behavior
i can't play with the canvas 😞

**Comment by asturur** [comment]
so please share some detail about electron forge and how you setup the app.
otherwise i cannot really help.woth anything.

**Comment by gimyboya** [comment]
i have fixed this by using the web version in staid of the node version.

**Comment by Olgagr** [comment]
I have the same problem using fabric in electron when installed via npm. I imported it like this:

```
import fabric from 'fabric';
```

I got an error:

```
Uncaught TypeError: _fabric2.default.Canvas is not a constructor
```

Finally, I made it work by importing it like that:

```
import 'fabric';

// later use it in the standard way
const canvas = new fabric.Canvas('c');
```

**Comment by asturur** [comment]
@Olgagr the right way to import it is

`import { fabric } from 'fabric'`;

as a side effect fabric will be anyway appended to window, that you may or may not want to happen.

There is a specific build parameter to disable appending the object to the window.

**Comment by Olgagr** [comment]
@asturur Yeah, you're right. I'm not sure why I was convinced that there is a default export :)
