### ISSUE TITLE
Calling canvas.initialize() more than once leaks window "resize" event listeners, and thus entire canvases

### ISSUE THREAD

**Issue by smfr** [kangax/fabric.js#3971]
## Version
1.7.6

## Test Case
http://jsfiddle.net/vcubzdgo/1/

## Steps to reproduce
Load http://jsfiddle.net/vcubzdgo/1/ on iPad

## Expected Behavior
Page finishes loading.

## Actual Behavior
Safari web content is jettisoned because of high memory use.

This was reported as a WebKit issue (https://bugs.webkit.org/show_bug.cgi?id=172728) and the analysis we did suggests a bug in fabric.

The fiddle is creating canvases in a loop like this:

      canvas = new fabric.Canvas();
      canvas.initialize(canvasElement, {height:2000, width: 2000})

This pattern causes _initEventListeners() to get called twice for each canvas object, so _bindEvents() is called twice. On the first call, _onResize is bound:

`this._onResize = this._onResize.bind(this); `

and then registered as an event listener on the window:

`addListener(fabric.window, 'resize', this._onResize);`

On the second call, the binding and registration happens again, which will register a second event listener on 'resize' on the window object. However, disposal only removes the second one:
`removeListener(fabric.window, 'resize', this._onResize);`

so the code leaks a registered event listener on the window object. This listener keeps the entire canvas object alive, which in turn keeps its <canvas> elements and their large backing stores alive.

The fix should be to make it harmless to call canvas.initialize() more than once, by saving some state about whether event listeners have been registered.

**Comment by asturur** [comment]
i need time to digest this, i m very busy, i ll do the best to see if there is a bug or not

**Comment by asturur** [comment]
Just to be clear, the analysis looks good, 99% there is a bug to fix, just i do not know how fast i can do this.

**Comment by asturur** [comment]
The leak would happen because the resize handler carry a reference to the context of the fabric Canvas instance, and so reference to all elements inside?
We are not talking of one function leak right?

**Comment by smfr** [comment]
> The leak would happen because the resize handler carry a reference to the context of the fabric Canvas instance ( because of the binding ), and so reference to all elements inside?
We are not talking of one function leak right?

That's right. Basically with this double initialize you're doing:

window.addEventListener("resize", _results of first bind_)
window.addEventListener("resize", _results of second bind_)

then dispose does:
window.removeEventListener("resize", _results of second bind_)

so you've left a resize event listener on the window with a function that you've lost the reference to. That function entrains 'this' which keeps the fabric Canvas alive, and then it keeps alive everything it references.

You already doing some "delete' in the dispose, and we need to analyze why that doesn't seem to release all the canvases in WebKit. However, you're still going to leak the fabric Canvas objects. The best fix is to avoid the double-registration of event handlers.

**Comment by asturur** [comment]
sure. that i can do. also i should avoiding to need that event at all.
thanks for the analysis you saved me at least 3 hours of search.

**Comment by asturur** [comment]
@smfr check #3983, let me know if it looks good. Actually testing it
