### ISSUE TITLE
TypeError on image dragging

### ISSUE THREAD

**Issue by jidel** [kangax/fabric.js#3972]
## Version
2.0.0-beta2

## Test Case
https://jsfiddle.net/jidel/j81mxey0/5/

## Steps to reproduce
Move the image with the mouse

## Expected Behavior
Image moves

## Actual Behavior
Image disappears and JS error:
``Uncaught TypeError: Cannot read property 'length' of undefined``

## Fix
This [line ](https://github.com/kangax/fabric.js/blob/master/src/shapes/image.class.js#L476):
```js
 if (this.isMoving === false && this.resizeFilters.length && this._needsResize()) {
```
should be:
```js
 if (this.isMoving === false && this.resizeFilter && this._needsResize()) {
```

**Comment by asturur** [comment]
thanks for spotting this!

**Comment by asturur** [comment]
i fixed it, for now not republishing on NPM, i'll try to make more changes and push a beta 3.

**Comment by c0bra** [comment]
Oh thank you so much. Just ran into this and was very very confused.
