### ISSUE TITLE
textDecoration is undefined

### ISSUE THREAD

**Issue by wearehappybits** [kangax/fabric.js#3978]
Before I was using this code:

  ```
toggleTextDecoration: function(value) {
                var text = this.getTextObject();
                console.log("text", text)
                      console.log("text", text.textDecoration)
                var current = text.textDecoration.trim();
                //font style
                if (value == 'italic') {
                    if (text.fontStyle.indexOf('italic') > -1) {
                        text.setFontStyle('normal');
                    } else {
                        text.setFontStyle('italic');
                    }
                }

                //text decoration
                else {
                    if (current.indexOf(value) > -1) {
                        current = current.replace(value, '').trim();
                    } else {
                        current += ' '+value;
                    }

                    if (text.setTextDecoration) {
                        text.setTextDecoration(current);
                    }
                }

                canvas.fabric.renderAll();

                var decorations = text.fontStyle+' '+text.textDecoration.trim();

                return decorations.split(' ');
            },
```

After moving to latest fabric version I get that in here          var current = text.textDecoration.trim(); textDecoration is undefined. How I should handle this right now?

getTextObject is basically  var active = canvas.fabric.getActiveObject();

For sure, could somebody provide an example on how to set, lets say, underline to text with newest fabric.js. Thanks.

**Comment by ncou** [comment]
Hi,

The italic and bold mecanisum hasn't changed in the latest function, but for underline and linethrow have been modified to use a boolean.

I think something like : object.underline = true or object.set('underline', true) should work.

I think the documentation will soon be updated by asturur, once the beta period is finished.

**Comment by asturur** [comment]
yes.

underline: true/false
lineTrough (or whatever the correct spell is): true/false
overline: true/false

**Comment by prabhathAmila** [comment]
Hi Asturur,
In this example, you gave, [https://jsfiddle.net/jq23y1vm/](https://jsfiddle.net/jq23y1vm/)
How can I apply boldly, underline or italic only selected text only not whole text (text edit mode)
please help.
Thank you
