### ISSUE TITLE
Textbox adjust font size according to height set

### ISSUE THREAD

**Issue by michaelbukachi** [kangax/fabric.js#3979]
Does the Textbox object automatically adjust the font size according to the size of the Textbox? I've tried googling around but there is no clear answer.

**Comment by asturur** [comment]
no it does not.
no mouse action can change fontSize

**Comment by michaelbukachi** [comment]
@asturur I'm not using the mouse, but rather programmatically

**Comment by asturur** [comment]
No it does not do it.
Increasing the fontSize will increase the height.
if you want to do by yourself you have to do some proportions.
check the current height and current fontSize and multiply fontSize for the ration of newHeight/oldHeight.

Should work.

**Comment by andrea11** [comment]
You can try to watch this : https://stackoverflow.com/questions/41279855/fabricjs-textbox-make-the-text-shrink-to-fit

**Comment by michaelbukachi** [comment]
I did manage to implement a workaround to make this work for me. Here's the link:
https://gist.github.com/michaelbukachi/65efa9ad5289000866bc4c18f391e746.js
