### ISSUE TITLE
1.7.12 and filters not working

### ISSUE THREAD

**Issue by Tsunami2069** [kangax/fabric.js#3990]
Hello... 

My project has image filters that have been working perfectly.

After updating fabric to the latest version (1.7.12), they stopped working and i'm getting the following error: 
Uncaught TypeError: filters.filter is not a function
at klass.applyFilters (fabric.js:18745)

Hope it helps and keep up the great work.

**Comment by asturur** [comment]
urgh. on what browser?

**Comment by asturur** [comment]
I m sorry but there is no filters.filter on fabric.js 1.7.12 whole file. Are you sure you are not using the 2.0 beta?

**Comment by Tsunami2069** [comment]
Oh WoW, don't I feel stupid now :)
Yeah, sorry, i was using the 2.0 dist by mistake.

Sorry for wasting your time :)
Closing it...

**Comment by asturur** [comment]
please try a rebuild of the latest branch i hope we fixed it.

**Comment by Tsunami2069** [comment]
@asturur 
Oh yeah, i downloaded an actual 1.7.12 dist and yeah, filters are still working perfectly.
Thank you once more.

**Comment by evolutionjay** [comment]
how to use filter in Fabricjs 2.x beta???
