### ISSUE TITLE
DrawImage - TypeError: Image or Canvas expected

### ISSUE THREAD

**Issue by gopiss** [kangax/fabric.js#3991]
# drawImage function not working in node fabric library.

## Version
1.7.12

### _I am getting this error while call drawImage methode_
         ctx.drawImage(canvas.toDataURL(), 0, 0);
	^

	TypeError: Image or Canvas expected
	at TypeError (native)
	at e:\testCanvas\index.js:47:9
	at createImageAndCallBack (e:\testCanvas\node_modules\fabric\dist\fabric.js:26729:30)
	at IncomingMessage. (e:\testCanvas\node_modules\fabric\dist\fabric.js:26687:13)
	at emitNone (events.js:91:20)
	at IncomingMessage.emit (events.js:185:7)
	at endReadableNT (_stream_readable.js:974:12)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
## _here is my code to reproduce error_
       `	var fabric = require('fabric').fabric;
		var canvas = fabric.createCanvasForNode(150, 150);
		var canvas2 = fabric.createCanvasForNode(1000, 1000);
		var ctx = canvas.getContext('2d');
		fabric.util.loadImage('http://fabricjs.com/assets/escheresque_ste.png', function (img) {
			var rect = new fabric.Rect({
				width: 150,
				height: 150,
				fill: '#29477F'
			});
			rect.setPatternFill({
				source: img,
				repeat: 'repeat'
			});
			canvas.add(rect);
			ctx.drawImage(canvas.toDataURL(),0,0); //here is a problem.

		});`

## Expected Behavior
 I need to draw image from fabric canvas object to html canvas element. In my code consider canvas2 as normal html canvas object.
## Actual Behavior
Issue with loading image into normal html canvas form fabric canvas object.

**Comment by asturur** [comment]
```
ctx.drawImage(canvas.lowerCanvasEl,0,0);
```

i may lack context to answer this question, but this is not a support forum.
Please try the above snippet or go on stackoverflow for this kind of help.

**Comment by rokenchou** [comment]
same issue
