### ISSUE TITLE
Resizing/Modifying shapes looks somewhat broken in the 1.7.x version

### ISSUE THREAD

**Issue by tobiasvogel** [kangax/fabric.js#4001]
## Version
1.7.x

## Test Case
https://jsfiddle.net/bdzp4kzn/1/embedded/result/

## Steps to reproduce
When I recently switched from 1.4.13 to 1.7.11, I noticed modifying and especially scaling shapes looks somewhat broken. Use the link (yes, the _embedded_-link above is indeed intentional!) to see, the difference. 

## Expected Behavior
Same smooth resizing behaviour as in 1.4. versions.

## Actual Behavior
Still works, but looks somewhat broken.

**Comment by asturur** [comment]
https://jsfiddle.net/3hm8ax4t/2/

You cannot use noScaleCache in this kind of resizing.
Something that should be addressed.

You are not scaling the shape properly, you are doing something else.

If the problem is the scaling stroke, better you just divide the strokeWidth maybe?

**Comment by jpadula** [comment]
I have the same error when update from 1.6 to 1.7.x

**Comment by asturur** [comment]
I cannot fix this, you will have to use `fabric.Object.prototype.noScaleCache = false` or set to false just for the objects you intend to scale in this way.
