### ISSUE TITLE
[Bug] Image scaling is different in generated SVG

### ISSUE THREAD

**Issue by andrewblomquist** [kangax/fabric.js#4011]
## Version
1.7.7 
(version used in fiddle, though bug is also present in 1.7.13)

## Test Cases
Square image with no scaling - https://jsfiddle.net/geexter42/y12yLvgv/
This could be considered a base case. The fiddle shows that the generated SVG is the same as the canvas when the image has no scaling applied to it.

Square image with scaling - https://jsfiddle.net/geexter42/32ndm4t5/
A 3000x3000 image is used here. It is scaled down when placed on the canvas. We can see that the generated SVG is different than what is seen on the canvas.

Square image with scaling v2 - https://jsfiddle.net/geexter42/fe1q4LzL/
The same 3000x3000 image is used, but is not scaled down as much. We can see that the difference between the canvas and the SVG is smaller.

Rectangular image with scaling - https://jsfiddle.net/geexter42/ym5fp6cy/
Just to show that it is not exclusive to square images.

## Expected Behavior 
Each canvas and SVG should have no differences.

## Actual Behavior
The SVG appears to scale images a bit smaller than seen on the canvas.

## Caveat
This may not be an issue with FabricJS. While I've yet to confirm this, I'm worried that while FabricJS can accurately scale these large images, SVGs lack the precision to do so.

**Comment by asturur** [comment]
hey thank you for the perfect fiddles.
Gonna look into this asap

**Comment by asturur** [comment]
found!

https://jsfiddle.net/32ndm4t5/4/

i could remember without going deep in debugging.
There is a parameter that is called

fabric.Object.NUM_FRACTION_DIGITS that starts at 2.
to get hi fidelty SVGS you should use an higher number of digits.

that's all!

**Comment by andrewblomquist** [comment]
Thanks for looking into this!
