### ISSUE TITLE
Ability to set background of fabric canvas from a native canvas element

### ISSUE THREAD

**Issue by gunnsth** [kangax/fabric.js#4013]
In cases where multiple canvases are being rendered and copied around, it would be effective to be able to use another canvas as an input to setBackgroundImage, rather than converting to a data url via the toDataURL method.

For such applications this would generate a significant performance boost as evident by the following jsperf:  https://jsperf.com/copying-a-canvas-element

I am suggesting this as it would be beneficial for my own use case where I have multiple canvas instances using more than 1 library to render to a canvas, and then using fabricjs on top of that.
I do not really have a good sense if this is a very common use case and I understand that it may be out of scope for fabricjs.

If so, I would appreciate if you could recommend which function to overwrite in order to create this functionality. Perhaps the _renderBackground function of static_canvas.class.js ?

PS. Thanks for the excellent library.

-Gus

**Comment by asturur** [comment]
https://stackoverflow.com/questions/44434944/adding-canvas-inside-another-canvas-obj-setcoords-is-not-a-function-fabric-js/44563211#44563211

Create an Image and set the ._originalElement to that canvas. it should work.

**Comment by gunnsth** [comment]
Seems to work with the following code (typescript):

let data = new fabric.Image(otherCanvasEl);
fabricCanvas.setBackgroundImage(data);

The performance definitely appears to have improved as a result.

Thanks!
