### ISSUE TITLE
Cancel Editing for IText

### ISSUE THREAD

**Issue by Exlord** [kangax/fabric.js#4015]
I want to be able to cancel the editing of a text box on `esc` key press and return it to its before edit state.

I tried to keep a clone of the object when it enters editing and restore it when `esc` key is pressed.<br/>
BUT hiddentextare has a event listener for `keydown` and it prevent propagation to the parent element.<br/>
I even tried attaching the `keydown` event handler to the hiddentextare itself directly, It gets fired on other keys but not `esc`.

So it would be nice to consider `esc` key as canceling the edit, or at least to fire another event on `esc` key like `text:editing:canceled` or somehow allow to listening for `esc` keydown event on a `IText` when its on editing mod.

Is there any quick fix for this at the moment?

**Comment by asturur** [comment]
i think a right and quick fix is to expose that binding between key and functions so that you can write your own esc binding.

**Comment by Exlord** [comment]
I fix my problem for now with a kind of dirty solution, but it would be nice to have internal support.

```
  fabric.IText.prototype._keysMap[27]  = 'cancelEditing';
  fabric.IText.prototype.cancelEditing = function (e) {
    this.exitEditing();
    if (this.canvas) {
      this.canvas.fire('text:editing:canceled', { target: this });
    }
  };
```
```
    _onEditingEntered(e) {
      this._textBoxTemp = e.target.clone();
    }
```
```
    _onEditingCanceled(e) {
      let obj = this.canvas.getActiveObject();

      if (obj && obj.type == 'i-text' && this._textBoxTemp) {
        let props = {};
        for (let prop in this._textBoxTemp) {
          if (this._textBoxTemp.hasOwnProperty(prop)) {
            if (!Util.isFunction(this._textBoxTemp[prop]))
              props[prop] = this._textBoxTemp[prop];
          }
        }

        obj.set(props);
        this.canvas.renderAll();
        this._textBoxTemp = null;
      }
    }
```

would this have any side effects that I am not seeing?

**Comment by asturur** [comment]
Your solution is completely OK.
Infact i just made public that object map and added a comment that is possible to override the behaviour.

i suggest:

```
_onEditingEntered(e) {
      this._textBoxTemp = e.target.toObject();
    }
```

so that will stay sync. the clone is no more sync in fabric 2.0
Also it will keep just the meaningfull things, you will not need to check for functions in the restore moment. a single  obj.set( this._textBoxTemp) will be fine.
