### ISSUE TITLE
CharSpacing and custom fonts

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4016]
Hi,

Here is a strange behaviors with custom font and charSpacing.
I don't know if it's a bug, it's probably more of a font problem, or a lack of knowledge from me.

Look at the "k" letter, it's changing if the charSpacing is 0 or another value (-1 or +1 or XX value) :
https://jsfiddle.net/awjmh5a1/4/

I got a few glitch for the custom font i use when i move my slider to change the charSpacing value.

tested with FF and Chrome.

**Comment by asturur** [comment]
that's weird
Is for sure some font feature we do not understand:

![image](https://user-images.githubusercontent.com/1194048/27276763-7a6caf72-54dc-11e7-98ef-24689148eb23.png)

depending on the work, the k changes.

Charspacing makes everything draw one letter at time, so it behaves like the k is alone.
Never seen something like that. But i m sure is not a fabric.js problem.

![image](https://user-images.githubusercontent.com/1194048/27276873-d0dd92d6-54dc-11e7-86c3-9cc3a6307d6a.png)

**Comment by ncou** [comment]
Very strange.

this custom font is weird, i have the same problem with the "o" letter in this example.
https://jsfiddle.net/awjmh5a1/5/

I close the ticket, it's not a fabric.js bug.

**Comment by teohhanhui** [comment]
Not a bug, at least as far as CSS / SVG `letter-spacing` is concerned:

> When the resultant space between two characters is not the same as the default space, user agents should not use ligatures.

https://www.w3.org/TR/2008/REC-CSS2-20080411/text.html#propdef-letter-spacing

**Comment by asturur** [comment]
this causes also problem with measurement, so you know that.
The cursor position will not be perfect.
