### ISSUE TITLE
Noise filter does not work properly in fabric 2.0 beta

### ISSUE THREAD

**Issue by human-a** [kangax/fabric.js#4019]
Hi

Noise filter does not work properly in fabric 2.0 beta, instead of adding noise it increases the brightness. [It works here](http://fabricjs.com/image-filter-webgl) but the fabric.js file included on that page seems to be different from the on in the dist folder of fabric on Github.

## Version
fabricjs 2.0 beta

## Test Case
https://plnkr.co/edit/EqZhR2?p=preview
(The cdnjs version of fabric 2.0 beta seems to be missing the `new fabric.WebglFilterBackend()` as a constructor and fails with the error `WebglFilterBackend is not a constructor` so I created a plunker and included the latest file from dist folder on Github)

## Steps to reproduce
Please open the link above, wait for plunker to run the app and show the canvas with an image inside it, use the range slider below the canvas to change the noise value. (You can see the code for this in the index.js file on the left sidebar)

## Expected Behavior
It should be adding noise to the image as a filter just like the [demo here](http://fabricjs.com/image-filter-webgl)

## Actual Behavior
It appears to be increasing the brightness of the image.

**Comment by asturur** [comment]
it should be fixed in the master branch if you do a rebuild.

**Comment by asturur** [comment]
i do not rebuild every change or the commit log would be unreadable

**Comment by human-a** [comment]
Thanks, I will do a rebuild manually :)

**Comment by human-a** [comment]
The latest build also has the same problem:
https://plnkr.co/edit/EqZhR2?p=preview

I cloned the repository, and run node build.js modules=ALL in the terminal, then replaced the minified file in my plunker with the newly built one.

**Comment by asturur** [comment]
i definitely broke something. I ll check asap

**Comment by asturur** [comment]
Ok i swapped width / height in gl filters for stepW , stepH that is 1/width , 1/height since we need always that and is one division less.
I left the process in the middle and probably broke all filters that requires it: pixelate, noise to name at least 2.

**Comment by human-a** [comment]
Thanks for looking into it, if possible plz let me know when you push new update so that I can pull here, run the build again and test it out.

**Comment by human-a** [comment]
Just to confirm, the issue is even worse on pixelate (haven't yet tried the rest)
If you add pixelate filter with blocksize of 0 it completely destroys the image turning it into a solid color image. I hope the info is useful.

**Comment by asturur** [comment]
sure, with broken uniforms, just by luck noise is doing something.

**Comment by human-a** [comment]
I will try the rest of the filters and if I find more issues I will report here. So far the following are working as expected:

blur
brightness
contrast
saturation

**Comment by asturur** [comment]
no worries when i can sit on it, with a search replace, i should fix it.

**Comment by asturur** [comment]
i think i fixed it, did not have time to try, please let me know.

**Comment by human-a** [comment]
I did [test Noise and Pixelate](https://plnkr.co/edit/EqZhR2?p=preview) again. Here are the issues:

1) Pixelate is now working almost as expected, although it has to be set to at least 1, I checked and it does not affect the quality of the image in a noticeable way so my guess is that it's a requirement of this particular filter, since setting the value of this filter to 0 will turn the image into solid color, this is also true for the [main demo of WebGL filters](http://fabricjs.com/image-filter-webgl). But this makes the filters experience a little bit inconsistent overlay.

2) Noise still has the same problem, it increases the brightness of the image instead of adding noise. please check [the plunker](https://plnkr.co/edit/EqZhR2?p=preview) for the demo.

**Comment by asturur** [comment]
1) pixelate must be set to integers from 1 up ( 1, 2, 3, 4, ,5 ,6, ..... and so on )
it could be builded in completely different way, saying like `divide the image in a grid of X by Y pixels, but is not built like that )

2) you are right is still broken. i ll try later again, this time i ll double check that it works.

**Comment by human-a** [comment]
I understand, thanks.

**Comment by human-a** [comment]
@asturur Another issue I found was with blend-color filter. While it works as expected the filter is being applied or when it's value is being updated, however if you save your canvas via JSON (I do that in database) when loading your canvas from that JSON object all the saved filters will load except for blend-color filter.

If this explanation is vague, let me know and I will create a plunkr for it.

**Comment by human-a** [comment]
I found the reason why blend color does not load from saved canvases. the filter class for blend color does not return the `type: "BlendColor"` it just returns the following:

```javascript
return {
    color: this.color,
    mode: this.mode,
    alpha: this.alpha
}
```

changing that code to the following will fix the issue:

```javascript
return {
    type: this.type,
    color: this.color,
    mode: this.mode,
    alpha: this.alpha
};
```

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/27496925-4ef0dd1c-5858-11e7-8c83-670f935bc7fa.png)


ok this time works, also added the type to blend filter.
Thanks for your time
pushing up.

You will notice the webgl noise is uglier than the plain javascript one. is because there is no a random equivalent. Maybe it will be refined, but is not a priority for now.

**Comment by human-a** [comment]
Thank you, works as expected.
