### ISSUE TITLE
I-Text - Open Sans font doesn't render until text edited in Safari, Chrome

### ISSUE THREAD

**Issue by kelvin-im** [kangax/fabric.js#4021]
## Version
1.7.9+

## Test Case
https://jsfiddle.net/fjzcdt7h/

## Steps to reproduce
1. Add I-Text object with Open Sans font, add with any text.
2. Save and reload the page (may have to reload the page a few times). Notice the object text or font style does not render when reloaded.
3. Edit the text field by adding or removing a letter. The font will then change to Open Sans with text values.

## Expected Behavior
The fonts and text object should be displayed properly when canvas is loaded or reloaded.

## Actual Behavior
The I-Text object itself does not render the font or text, until the object is re-edited. 

In Chrome, the objects seem to default to Times New Roman.
![chrome_2017-06-20_12-01-48](https://user-images.githubusercontent.com/26411642/27343981-b3deb18e-55b2-11e7-92d8-ee082703b374.png)

However, in Safari, the object text is completely replaced with question marked blocks.
![bs_macsie_safari_10 1](https://user-images.githubusercontent.com/26411642/27343982-b634a34e-55b2-11e7-8301-bd62381ccf19.jpg)

In both cases after editing the font, the font and text reappears and works properly, but it causes issues when saving and loading the canvas.

**Comment by asturur** [comment]
You have to be sure the font is loaded before using it.
Fabric is not gonna do it for you. Please add a fiddle with a font loader
(this is easy to use https://github.com/typekit/webfontloader ) and it should work always.

**Comment by kelvin-im** [comment]
https://jsfiddle.net/fjzcdt7h/1/

Adding webfontloader has resolved the issue. I've done some investigating on my project and found an older version of webfontloader was being used as well. I've since updated to the latest version, and the text displays as expected. Wanted to comment back in case this helps anyone else.

Thanks for the help! :)

**Comment by jobiekirkwood** [comment]
I recreated this in jsfiddle.net, here:  https://jsfiddle.net/xt4gohz7/2/
However, locally the same code, with or without the WebFont.load _active_ function, does not show the correct font until the text has been edited. (Files attached).

Is it something to do with the way the links/references/libraries are added?

[testFabricHTML.txt](https://github.com/fabricjs/fabric.js/files/5560895/testFabricHTML.txt)
[styleCSS.txt](https://github.com/fabricjs/fabric.js/files/5560896/styleCSS.txt)

**Comment by asturur** [comment]
@jobiekirkwood in your fiddle it does not seems you are waiting for the font to be loaded. You start the load, but you do not wait.

**Comment by jobiekirkwood** [comment]
Hi, it does here: https://jsfiddle.net/jfzecm56/1/
And it does in the local files but doesn't work in the local files.
