### ISSUE TITLE
.animate onChange callback is rather useless

### ISSUE THREAD

**Issue by mbaierl** [kangax/fabric.js#4027]
I just noticed that the onChange callback for the .animate function is not really providing any useful data. "this" is set to something useless, and there are no parameters passed. See src/mixins/animation.mixin.js, line 214:
`options.onChange && options.onChange();`

It would be amazing if this could be changed to include the current value of the animations property, the current animation progress (a value between 0 and 1) and/or the current time... 

Thanks for considering this!

**Comment by asturur** [comment]
it does send the current value. At least i m using it somewhere. 
Are you talking about fabric.util.animate or object.animate?

**Comment by mbaierl** [comment]
In this case it was the object.animate. I tried to log the 'this' variable, which did not contain anything useful....

**Comment by mbaierl** [comment]
Hi @asturur,
here is some sample code: https://jsfiddle.net/4sv0eefc/
You'll see in the console that there is no data passed to the onChange function...

**Comment by ncou** [comment]
Hi,

You can access directly the object like this : 
https://jsfiddle.net/4sv0eefc/1/

But it think having the "this" property = actual target could be a more cleanner solution.

By the way it seems to me there will be a new function "requestRenderAll()" in the future release who could be used in the onChange event to refresh the canvas with maintening a 60fps refresh framerate.

PS : Just my 2 cents opinion, but the name "onChange" could be renamed as "onUpdate" who seems more clear (at least to me :)). And having a new "onStart" event could be a plus (as we have already a onComplete event). used for example to disable interractions before an animation start, and re-activated the interactions at the end of the animation with the onComplete event.

**Comment by mbaierl** [comment]
@ncou : thanks, but what would be great to really extend the animations is to get the current animation value (between 0 and 1) in the callback as argument and a proper "this" would also be helpful. 

Regarding your 2 cents - since I worked a lot with animations now and used ScrollMagic before (based on GSAP) - there is some of room for improvement ;-)

**Comment by asturur** [comment]
there must be some missing connection between  fabric.util.animate and object.animate. i m aure we can pass the current value in

**Comment by mbaierl** [comment]
@asturur - should not be that hard, I see two changes that are needed:

1) in the fabric.util.animate function do not only pass on the current value, but also the percentage: `onChange(easing(currentTime, startValue, byValue, duration), currentProgressInPercent);`
To get the value some calculation is needed.

2) in the animation.mixin.js replace `options.onChange && options.onChange();`
with `options.onChange && options.onChange.call(this, currentProgressInPercent, otherUsefulValues);`

Thx.

**Comment by asturur** [comment]
I can add the current progress to onchange to fabric.util.animate

Object.animate inherits it, but consider that when animating multiple properties, just one callback will fire.

**Comment by mbaierl** [comment]
Thank you @asturur !
