### ISSUE TITLE
Broken Sliding Ladybugs demo

### ISSUE THREAD

**Issue by unpollito** [kangax/fabric.js#4030]
Hi,

I have just opened the Sliding Ladybugs demo http://fabricjs.com/ladybug and it seems to be broken: it just crashes randomly after a few seconds. Apparently, these lines fail:

```
    canvas.forEachObject(function(obj) {
      obj.left += (obj.movingLeft ? -1 : 1);
      ...
    };
```

For some reason, the callback for canvas.forEachObject is being executed with an undefined object as a parameter. While a workaround for the demo is trivial (just checking if obj is truthy), I find it weird that there would be an undefined object in the canvas and that it would be passed as a parameter when iterating over the canvas' objects.

**Comment by Tsunami2069** [comment]
I have tried it and it also crashes on my side.
I'm using Chrome updated to the latest version.

**Comment by asturur** [comment]
i fixed a bunch of demos and then with a wrong git command i lost all the work. then did not bother anymore.

So the whole canvas.forEachObject is a bit pointless. I bet performance wise is exactly equal to 

canvas.getObjects().forEach(function(obj, index ) { });

undefined objects can happen, not sure why they are happening on that demo. i ll fix it.

**Comment by asturur** [comment]
it breaks because the forEachObject use a for loop and removing objects while you are in the middle of a for loop breaks things.

Fixed pushing up.
