### ISSUE TITLE
Enter key in Chrome 58 reverts new line to original fontsize

### ISSUE THREAD

**Issue by jilster** [kangax/fabric.js#4041]
I think the Chrome 57 carriage return bug is back in Chrome 58, see https://github.com/kangax/fabric.js/issues/3796, i have a similar problem.

I am using Chrome 58.0.3029.110 (64-bit)
I can't reproduce the bug in Safari 10.1.1

## Version
1.7.14

## Test Case
http://fabricjs.com/kitchensink

## Steps to reproduce
In the Kitchensink:
- Add a textbox to the canvas
- Enter editing mode and select all text
- Change the fontsize (for example make the text a lot smaller)
- Set the cursor to a random position in the text 
- Hit the enter key twice

## Expected Behavior
The new line that is created should have the fontsize that was set for the whole text

## Actual Behavior
The new line that is created has the fontsize that the text had before it was changed

**Comment by asturur** [comment]
can you try to replicate on a fiddle that is based on the master branch? old text version is unmantained.

**Comment by jilster** [comment]
https://jsfiddle.net/7g4k1rrf/4/

I can't replicate the bug using the master branch. I guess i have to switch to the master branch and rewrite some code 😄

**Comment by asturur** [comment]
look the master branch is way better of the 1.x.
May be not perfect yet, and some things may be still changed before freezing.
Definitely worth a switch if your app is still in development.

**Comment by jilster** [comment]
Yes, my app is still in development so i will switch. The only thing is that i created my own multi-column text support based on 1.x. But i've managed once so i'll manage again on the master branch. I guess this ticket can be closed. Thanks for your help and thanks for this great library!

**Comment by asturur** [comment]
well fabric 2.x manages text very differently.
Please ask questions if you need to understand some logic.
