### ISSUE TITLE
Detecting canvas boundary after setZoom

### ISSUE THREAD

**Issue by neilliang** [kangax/fabric.js#4042]
I'm using following code to detect whether current active object is out of boundary. It works find before zoom in/out. How should I get it work after I zoom in/out the canvas? Thanks for the help.

```
canvas.on('object:modified', function (e) {
    let obj = e.target;
    let boundingRect = obj.getBoundingRect(true);
    if (boundingRect.left < 0
        || boundingRect.top < 0
        || boundingRect.left + boundingRect.width > this.getWidth()
        || boundingRect.top + boundingRect.height > this.getHeight()) {		

            console.log('out of range')	
	
    }
```

**Comment by asturur** [comment]
what you want to detect exactly?
Fabricjs offers you a method `.isOnScreen()` that tells you if the object has a corner on the viewable are of the canvas. is this what you want?

**Comment by neilliang** [comment]
Thank you for the reply and sorry for replying late. 
.isOnScreen() is not really what I need but it's good to know though , thanks. 
I need to know whether the object is completely in the canvas. 

Demo video
Youtube: https://goo.gl/7Cgqbk

It works find but after zoom in/out something mess up.

**Comment by asturur** [comment]
so you have a way.
Every object has aCoords, like oCoords but without padding for controls and not zoom infuenced ( absolute coords )

Canvas has vptCoord ( that get refreshed on render automatically, or there is also a method to refresh them, search for it in docs, i do not remember it ).
vpt coords represent the 4 point of the canvas that are at edge of screen ( canvas element ) in absolute coordinates.
They equal to 0,0 and width,height when the zoom is 1 and no translations, they change with the viewport.

if the 4 aCoords are contained in the vptCoords,the object is in the screen. That is the fastest way to calculate it.

**Comment by neilliang** [comment]
Alright, sounds really good.  I'll try it later. 
Thanks a lot.

**Comment by shaehn** [comment]
I spent an inordinate amount of time trying to get code to keep an object inside the canvas grid boundary when zoom mode was set to something other than 1. I am going to share that code so that others don't have to waste similar amounts of time. The function I wrote is called 'corral', as in keeping a herd of animals inside a given area. In my application, I had code listen to keyboard events (associated with selected/active objects) to apply a delta change in position and object:moving events (for when selected/active objects are being dragged with mouse). In both cases, corral was used to make sure that the object(s) could not be moved off of the canvas. Also, I had special cases where some objects were using 'center' positioning, while the remainder were using the normal 'left' positioning. So the algorithm handles that also.

```
corral(object, canvas) {
    let iMtx;
    let bottom = canvas.height;
    let rightEdge = canvas.width;
    let zoom = canvas.getZoom();

    // =================================================
    // The canvas size is affected by zoom. Consequently, to get original
    // canvas size when zoom is not in effect, need to apply viewport
    // transformation to bottom, right corner.
    // =================================================
    if (zoom !== 1) {
      iMtx = fabric.util.invertTransform(perimeter.viewportTransform);
      const brPt = new fabric.Point(rightEdge, bottom);
      const xfrmPt = fabric.util.transformPoint(brPt, iMtx);

      bottom = xfrmPt.y;  // now have canvas size when zoom = 1;
      rightEdge = xfrmPt.x;
    }

    // Ignore object when too big for given perimeter
    if (object.height > bottom || object.width > rightEdge) {
      return;
    }

    object.setCoords(); // in case they have not yet been set

    // ============================================
    // Note, the bounding rectangle coordinates and dimensions
    // are affected by the zoom. Consequently, need to recompute
    // bounding box data as if no zoom is in effect.
    // ============================================
    const body = object.getBoundingRect();

    if (zoom !== 1) {
      const bpt = new fabric.Point(body.left, body.top);
      const bwh = new fabric.Point(body.width, body.height);
      const xbpt = fabric.util.transformPoint(bpt, iMtx);
      const xbwh = fabric.util.transformPoint(bwh, iMtx);

      body.top = Math.round(xbpt.y);         // want to keep numbers as integers
      body.left = Math.round(xbpt.x);
      body.width = Math.round(xbwh.x);
      body.height = Math.round(xbwh.y);
    }

    // =============================================================
    // Now all object references are effectively without zoom  
    // such that the tests below will work appropriately.
    // =============================================================

    // top-left corner of canvas
    if (body.top < 0) {
      object.top = Math.floor(Math.max(object.top, object.top - body.top));
    }

    if (body.left < 0) {
      object.left = Math.floor(Math.max(object.left, object.left - body.left));
    }

    // bottom-right corner of canvas
    if (body.top + body.height > bottom) {
      const h = object.originY === 'center' ? body.height / 2 : body.height;
      object.top = Math.floor(bottom - h);
    }

    if (body.left + body.width > rightEdge) {
      const w = object.originX === 'center' ? body.width / 2 : body.width;
      object.left = Math.floor(rightEdge - w);
    }

    object.setCoords(); // in case modification occurred above
  }
```

**Comment by asturur** [comment]
@shaehn when you talk about keeping an object in the canvas grid, you mean onscreen? or inside an arbitrary area that is not the visible area in that moment?

**Comment by asturur** [comment]
I leave you some info that may help or not help to mantain less code:

`http://fabricjs.com/docs/fabric.Object.html#getBoundingRect`

getBoundingRect support 2 arguments, booleans:
absolute and calculate.
If both set to true, you will get a set of coordinates (tl, br, tr, bl ) that are zoom independent, and are the one that the object would get when the canvas has zoom = 1.
If calculate is true, the coordinates are calculated in that moment, otherwise the cached one get used.

using `const body = object.getBoundingRect(true, true);` could eliminate the use of setCoords and all the zoom related code.

**Comment by shaehn** [comment]
@asturur, Thanks for the information, I tried it out and it worked as desired. Here is an update to the code.

```
corral(object, canvas) {
    let bottom = canvas.height;
    let rightEdge = canvas.width;
    let zoom = canvas.getZoom();

    // ========================================================
    // The canvas size is affected by zoom. Consequently, to get original
    // canvas size when zoom is not in effect, need to apply viewport
    // transformation to bottom, right corner.
    // ========================================================
    if (zoom !== 1) {
      const iMtx = fabric.util.invertTransform(perimeter.viewportTransform);
      const brPt = new fabric.Point(rightEdge, bottom);
      const xfrmPt = fabric.util.transformPoint(brPt, iMtx);

      bottom = xfrmPt.y;  // now have canvas size when zoom = 1;
      rightEdge = xfrmPt.x;
    }

    // Ignore object when too big for given perimeter
    if (object.height > bottom || object.width > rightEdge) {
      return;
    }

    object.setCoords(); // in case they have not yet been set

    const body = object.getBoundingRect(true, true);

    // =============================================================
    // Now all object references are effectively without zoom  
    // such that the tests below will work appropriately.
    // =============================================================

    // top-left corner of canvas
    if (body.top < 0) {
      object.top = Math.floor(Math.max(object.top, object.top - body.top));
    }

    if (body.left < 0) {
      object.left = Math.floor(Math.max(object.left, object.left - body.left));
    }

    // bottom-right corner of canvas
    if (body.top + body.height > bottom) {
      const h = object.originY === 'center' ? body.height / 2 : body.height;
      object.top = Math.floor(bottom - h);
    }

    if (body.left + body.width > rightEdge) {
      const w = object.originX === 'center' ? body.width / 2 : body.width;
      object.left = Math.floor(rightEdge - w);
    }

    object.setCoords(); // in case modification occurred above
  }
```

**Comment by abrichr** [comment]
@shaehn thanks for the code. Can you please clarify what is `perimeter` referring to?

**Comment by shaehn** [comment]
@abrichr I fixed the code above. 'perimeter' was copied from some other code I had. It is really the 'canvas' parameter passed in.

**Comment by abrichr** [comment]
Thank you for the quick reply. Unfortunately this code did not work for me.

I have implemented a complete working solution here: https://github.com/fabricjs/fabric.js/discussions/7052

**Comment by Kwaysi** [comment]
@shaehn Thanks a lot been trying to figure this out all day! Do you know how I can modify this to also work when scaling? i.e Prevent objects from scaling out of the canvas?
