### ISSUE TITLE
Generating Image in Rails from JSON Data?

### ISSUE THREAD

**Issue by homerlex** [kangax/fabric.js#4043]
We have a web app that allows the user to draw with fabricjs.  We store the JSON output server side with a Rails application.

We'd like to generate PDFs (server side) that include the user's drawings.  One thing we've been trying is to use ExecJS with the fabricjs code.  This has been challenging but haven't quite given up on it yet.  That said, I'm wondering if there are other possible ways we might go about rendering the JSON as an image using ruby libraries.  We do not want to send the image from the client along with the json.

Thoughts are greatly appreciated.

**Comment by asturur** [comment]
nodejs with limits, is the only way for now.

depends on how much you are using custom fonts.
The rest should be straight forward.

**Comment by homerlex** [comment]
You are suggesting we have a node server setup that our Rails server makes requests to (passing in the json and getting the image in the response)?

**Comment by asturur** [comment]
Well Fabricjs works in browser or in node ( and not even perfectly in node ).
You can use something like phantomjs maybe.
The alternative is building your own server side version of fabricjs in the language you want, but you would need a canvas/cairo lib. At that point you would use node + node-canvas.

**Comment by asturur** [comment]
You may also try SVG export and svg render server side, if you are not using too much image and filters. If you are using filters then you get lot of dataurl and at that point is expensive to send to server.
