### ISSUE TITLE
Converting canvas to dataurl using toDataURL increases the image size then the original image.

### ISSUE THREAD

**Issue by ppriyank40** [kangax/fabric.js#4044]
Hi,
I am converting canvas to image with toDataURL function.But the size of the image is so much larger than the original image. So, please can you help me how to keep the size of the image to original one.

**Comment by ncou** [comment]
Hi,

There is a "multiplier" and a "quality" parameter in the toDataURL() function. You can use this to decrease the ouput image size.
This ticket is not a bug, please open a stackoverflow thread if you have some problem to use the toDataUrl() function, i or other members will try to help you.

**Comment by ppriyank40** [comment]
Hi,
I want to keep the quality of the image same as the original one.So, will multiplier will work for it?

**Comment by asturur** [comment]
you are probably working on an hdpi device. ( retina? ) By default toDataUrl gives you the retina enahanced version. if you disable retina or use a mutiplier of 0.5 you ll get the same visual size but a perceived less quality.

**Comment by ppriyank40** [comment]
So, this means that there is no way to keep the image as original one without size and quality compromise.

**Comment by asturur** [comment]
are you working on a retina screen?

**Comment by ppriyank40** [comment]
No, my web app is going to run on all screens with retina or without retina display.

**Comment by asturur** [comment]
in the one without retina the quality is identical, n retina screen the dataurl is twice bigger

**Comment by ppriyank40** [comment]
Yes, my image size icreased from 23kb to almost 200kb.

**Comment by asturur** [comment]
ok if you are talking about kilobytes size that is currently out of your control.
You can use jpeg compression a bit, but quality will never be the same after a recompression.
