### ISSUE TITLE
cornerSize no refresh in the control demo

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4046]
Hi,

I think there is a minor bug in the demo for the control customization. If you go directly on the "cornerSize" slider and change the value, the square controls box disapears. You need to stretch the object to force the redrawing of the controls.

http://fabricjs.com/controls-customization

I think the control demo will be modified soon for v2.0, so this bug is perhaps already corrected.

**Comment by asturur** [comment]
i fixed it in the website of the 2.0 adding the additional properties for controls ( colors, strokeDash, style )
