### ISSUE TITLE
Why fabricjs adds additional transform and x, y shifting when nothing is actually shifted?

### ISSUE THREAD

**Issue by AlexanderTserkovniy** [kangax/fabric.js#4049]
Hi guys,

Take a look at this example: https://codepen.io/albl/pen/LLYXJe?editors=0010

I have exported this basic fabric example to SVG and it seems like the fabric adds some weird random numbers, why is that?

This is SVG output:

```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="300" height="500" viewBox="0 0 300 500" xml:space="preserve">
<desc>Created with Fabric.js 1.7.11</desc>
<defs>
</defs>
<g transform="translate(150 150)">
<image xlink:href="http://fabricjs.com/lib/pug.jpg" x="-150" y="-150" style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" width="300" height="300" preserveAspectRatio="none"></image>
</g>
</svg>
```

What is `translate(150 150)`, and why `x="-150" y="-150"` is added? It is needless and moreover is mistaken, because if you save this output to .svg file and open in any svg reader you will notice that it is opened incorrectly. How to avoid adding this weird numbers?

P.S. Tried to ask in google group, but had no luck, nobody answered, though it was another question, but anyway decided to write here.

**Comment by asturur** [comment]
Well the numbers are not weird nor useless. They match the fabric transformation logic so we can build an SVG as we build the canvas.

What svg viewer are you using that is not able to handle a translation?

**Comment by asturur** [comment]
they match:

svg:
![image](https://user-images.githubusercontent.com/1194048/27761582-f221262a-5e5e-11e7-80ff-3201523bebb6.png)

canvas:
![image](https://user-images.githubusercontent.com/1194048/27761584-fc8ba81a-5e5e-11e7-823a-f599f5818c88.png)

**Comment by AlexanderTserkovniy** [comment]
Nothing is shifted in the example above. The dog is just in the 0, 0, so why do you need these 150 shiftings both on image and on group element?

**Comment by asturur** [comment]
they match fabricjs transform logic.
fabric works like that.

you can pass to SVGO maybe it will remove it, or write a different toSvG method to use in your project.

is too hard to write semplified transform.


what svg reader are you using that ha ls problem with a transform?

**Comment by AlexanderTserkovniy** [comment]
Ah I see, okay.

I use Adobe Illustrator CC 2017.

**Comment by asturur** [comment]
latest illustrator cannot handle transform? that's bad. can you post a screenshot? just for curiosity

**Comment by AlexanderTserkovniy** [comment]
Here is screenshot: http://prntscr.com/fqftg1.

**Comment by asturur** [comment]
i heard illustrator was bad with svgs... but that bad....

**Comment by AlexanderTserkovniy** [comment]
Agree dude, anyway, thanks :-)
