### ISSUE TITLE
OriginX/Y for all objects (using prototype) is broken in v2.x

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4056]
Hi,

There seems to be a regression in the v2.0 beta2, for the SVG file (pathgroup) if you use the object.prototype to redefine the OriginX or Y value.

In the example below, i set the origin to center (for all objects), but if you click on the object (the black SVG rect) the origin is still top&left (check in the console), for the other shape the origin is correct.

http://jsfiddle.net/S9sLu/1799/

If i try this fiddle with the lib v1.7.9 the originX&Y is overridden by the prototype value (correct behavior).
I think the "pathgroup" object has been removed in v2.0 so it looks like a regression.

Can you confirm ?

Thank you.

**Comment by asturur** [comment]
so PathGroup is removed, you will get a normal Group.
i thought i left originX  and originY untouched.
Are you on latest?

**Comment by asturur** [comment]
The point is that SVG is top-left
PathGroup was top-left internally.
Maybe we can solve it, but for now is low priority.
I mark for a followup release.

Is not hard to fix, the point is that at object creation i have to set top-left.
Then i can switch to the prototype values, but wich prototype?

Someone could rely on Object.prototype, other could set Circle.prototype in center and other in top-left. There is no a right why to pick up the default position.

**Comment by ncou** [comment]
Yes, no problem, for the moment, i set the originX&Y value, when i create the object. I prefered to point this change in the behaviors when i updated the lib in v2.x version.

**Comment by asturur** [comment]
found a fix, was easy enough!
