### ISSUE TITLE
Textbox not working properly with latest versions of fabric.js in safari browser of Mac.

### ISSUE THREAD

**Issue by nksingh2** [kangax/fabric.js#4069]
On Mac safari browser if you press double enter and then try to input some text in Textbox then it seems
to be blocked and we can not put any text into it.Its working fine with earlier version like 1.7.9 and with the latest version from 1.7.11 onward it seems to be not working.Its also working fine with beta version 	
v2.0.0-beta.1. Could you please check.
https://jsfiddle.net/nrk9n8no/1/

Regards,
Nitin Singh

https://jsfiddle.net/nrk9n8no/1/

## Version
1.7.6

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by asturur** [comment]
safari 10.1.1 fabricjs 1.7.15 works

**Comment by nksingh2** [comment]
Hi Asturur,

I am able to reproduce the issue in the provided fiddle link.I am sharing the video of my test can you please
look into it.

Tested with  Safari Version 10.1.1 (12603.2.4)
https://files.fm/u/29fyybvv

**Comment by nksingh2** [comment]
Hi Asturur,

Please let me know if you are able to replicate the issue.I have share the video of my testing  in above comment.

**Comment by nksingh2** [comment]
Hi,
Please check and let me know.Once again I am sharing the video of test performed by me.

Tested with Safari Version 10.1.1 (12603.2.4)
https://files.fm/u/29fyybvv

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/28303758-eef97bf8-6b94-11e7-980d-4d428f21011a.png)

everything works fine to me.
Using 1.7.15 to fiddle.

Please provide a replicable failing case

**Comment by asturur** [comment]
ok now i see that, i m sorry but i do not watch movies of bugs, and from the description was totally unclear.

**Comment by nksingh2** [comment]
Ok thanks.

**Comment by asturur** [comment]
looks fixed with the removal of `white-space: nowrap css attribute.`
So it will be fixed in 1.7.17
