### ISSUE TITLE
fabric for algorithmic image processing 

### ISSUE THREAD

**Issue by Berserk82** [kangax/fabric.js#4074]
See below.

**Comment by Berserk82** [comment]
Hello. 
I'm trying to get real time image processing, mainly for games, and I'd like to know what is possible with fabric.js from what is listed here:

https://docs.gimp.org/2.8/en/gimp-tools-color.html
https://docs.gimp.org/2.8/en/filters.html
https://docs.gimp.org/2.8/en/gimp-concepts-layer-modes.html

I'd also like to apply the above to single image channels  (RGBA).

Does fabric support this?

Thanks in advance for either. 

Cheers.

**Comment by asturur** [comment]
Well fabricJS is not a gimp replacement in JS. It does not support all that function, but it offers a nice interface to build your own filters with not so much effort.

Please checkt the brightness filter in source code and give a look.

**Comment by Berserk82** [comment]
In truth I'm not interested in gimp, I just would like to use those 3 features procedurally. 
But, the more is already available, the better. 
So, again, what is already available? 
Can you point me to examples/feature list/whatever or just list here?
Note this can be useful as future reference.

**Comment by Berserk82** [comment]
As for color management, I actually find useful *only* the following:
https://docs.gimp.org/2.8/en/gimp-tool-curves.html
https://docs.gimp.org/2.8/en/gimp-tool-posterize.html
https://docs.gimp.org/2.8/en/gimp-tool-levels.html

**Comment by asturur** [comment]
http://fabricjs.com/image-filter-webgl

this is what is built so far.
Those 3 functions are not available, you can build them.

**Comment by Berserk82** [comment]
Ok, let's suppose I'm willing doing so.
How can I do? 
Note I'm not even a js dev, imagine how far can I go writing filters.
I'd need some kind of ready sdk

**Comment by Berserk82** [comment]
And what about blend modes for overlapping images?

**Comment by asturur** [comment]
if you are not a JS dev that is not the right place, since this is a library to develop things, not a ready product.

Please read the brightness filter and see if you can get some idea on how it works.
You will need to write a code version and a webgl version.

https://github.com/kangax/fabric.js/blob/master/src/filters/brightness_filter.class.js

**Comment by Berserk82** [comment]
In truth, I were looking for which language to learn.
I guess I should use whatever language supports graphicsmagick, ffmpeg and sox.

**Comment by asturur** [comment]
those are command line tools mainly
or wrapped in libraries by many languages


learn JS probably if you have to start from 0 on anything.

but this is a debated topic and this is not the right place to do it.
