### ISSUE TITLE
Observable cannot fire with falsy arguments

### ISSUE THREAD

**Issue by jfdesgagne** [kangax/fabric.js#4075]
## Version
1.7.6

## Steps to reproduce
In the Observable mixin, calling fire with an argument like 0 or false will change it to a new object.

See https://github.com/kangax/fabric.js/blob/master/src/mixins/observable.mixin.js#L105

I would suggest to check if the value is undefined before changing it to a new object.

**Comment by asturur** [comment]
or just fire what is it. no reason to provide a default value.

**Comment by asturur** [comment]
did not forget about this.
The point is that the doc says that you have to pass an optional object.
Optional object means an object or nothing, not a boolean, number.
So i think firing `false` is wrong.

**Comment by asturur** [comment]
there may be reason to pass an object as parameter, like for example adding information in the fired function from the fire system itself.
I do not want make the object optional, is easier for you to put your falsy value in a key of the object.
