### ISSUE TITLE
Image resizing on 2.0.0 beta 3

### ISSUE THREAD

**Issue by dragondgold** [kangax/fabric.js#4084]
## Version
2.0.0 beta 3

## Test Cases
 - fabric.js 2.0.0 beta 1: [https://jsfiddle.net/owf3hkfb/](https://jsfiddle.net/owf3hkfb/)
 - fabric.js 2.0.0 beta 3: [https://jsfiddle.net/v4h0f7gh/1/](https://jsfiddle.net/v4h0f7gh/1/)

## Steps to reproduce
Create a canvas and add and image on it which size is bigger than the created canvas.

## Expected Behavior
On `2.0.0 beta 1` when setting the width and height of `fabric.Image` the image will stretch to the specified dimensions but on `2.0.0 beta 3` only a portion of the image will be shown and it won't be resized to the given width and height.

## Actual Behavior
Is this the expected behavior or a bug? I went through the changes in `2.0.0 beta 3` but I couldn't find anything related to it. This is affecting `fabric.Images` and background images on the canvas.

**Comment by asturur** [comment]
Is an expected change.
The image is as big as the element.
Using cropX, cropY, width and height, you can actually display a cropped part of the image. this is a new feature that let's you crop images.

Use the scaleX, scaleY properties to achive the dimension change, or use the scaleToWidth() or scaleToHeight() methods

**Comment by dragondgold** [comment]
Great, thank you very much @asturur!
