### ISSUE TITLE
Text decoration underline - rendering issue

### ISSUE THREAD

**Issue by paulcredmond** [kangax/fabric.js#4087]
## Version
1.7.8 & 2.0 beta3

## Test Case
https://codepen.io/paulcredmond/pen/EXOXMr

## Steps to reproduce
Click toggle underline button

## Expected Behavior
You see underline being toggled on or off

## Actual Behavior
You do not see underline being applied, however, if the textDecoration property has been applied, it will show if you click one of buttons to enable italic or bold text.

**Comment by asturur** [comment]
https://jsfiddle.net/jq23y1vm/

I move to jsfiddle that i m more proficient with.

So there are 2-3 things to keep in mind
1) read this http://fabricjs.com/fabric-object-caching
2) when setting a font to bold, it may be that the bold font is not loaded yet for whatever reason, fabric fails in get the new widths of the chars, the width of the whole object does not change, and fabric do not re render a trigger. in this case, as i did, using the fabricObject set method will flag the object for re render
3) if you cannot use the set method, saying object.dirty = true is good enough
4) in fabric 2.0.0 there is no more textDecoration = string but you get underline = true/false, overline = true/false, lineTrought = true/false

**Comment by paulcredmond** [comment]
Thanks @asturur - that's really great info.

**Comment by prabhathAmila** [comment]
Hi Asturur,
In this example, you gave, [https://jsfiddle.net/jq23y1vm/](https://jsfiddle.net/jq23y1vm/)
How can I apply boldly, underline or italic only selected text only not whole text (text edit mode)
please help.
Thank you
