### ISSUE TITLE
Bug with _restoreObjectsState, groups (?) and 1.7.15

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4088]
## Version
1.7.15

## Test Case
http://jsfiddle.net/3z19qj11/7/

## Steps to reproduce
Double click on the group to ungroup. Works well in fabricjs 1.7.7. Under 1.7.15 it display nothing (but the objects are there, just invisible)

## Expected Behavior
Should work as in fabricjs 1.7.7 
If you remove _restoreObjectsState the behaviours are the same between 1.7.7 and 1.7.15 (but objects lose their grouped position so I really need the _restoreObjectsState :-)) => or maybe there is another method to use instead of _restoreObjectsState with the new versions?

**Comment by asturur** [comment]
You need to set objects as dirty when you ungroup them.

**Comment by blobinabottle** [comment]
I confirm it's working now:
http://jsfiddle.net/3z19qj11/8/

Many thanks for your time & help!

**Comment by asturur** [comment]
i was sure i linked a modified fiddle. i did mot want to be criptic.
