### ISSUE TITLE
Backspace reverts 1 character to old style (setSelectionStyles)

### ISSUE THREAD

**Issue by jilster** [kangax/fabric.js#4091]
## Version
Master

## Test Case
https://jsfiddle.net/7g4k1rrf/7/

## Steps to reproduce
In the fiddle above:
- Select the text object
- Click the "change fontsize using setSelectionStyles" button
- Enter editing mode in the text object and set the cursor somewhere in the middle of a word
- Use backspace

## Expected Behavior
The character to the left of the cursor should disappear

## Actual Behavior
The character to the left disappears, but the character to the right gets reverted to its original style. Every time the backspace is used, one more character is reverted.
Using the set method (instead of setSelectionStyles) works normally, as shown in the fiddle.

I did't have the chance to test the delete button as well, because i am on a macbook. The mac shortcut for delete (CMD + backspace) seems to be used in fabric to delete everything left of the cursor. So maybe you can check the delete button as well.

**Comment by asturur** [comment]
So if you enter in editMode before apply the set, this does not happen.
This is weird, i will address in some way, either fixing the bug or being esplicit in the docs that this does not work ( i hope it can be fixed easier ).

**Comment by jilster** [comment]
For me the order in which you enter editMode and apply the set did not make any difference. But i think i found a solution!

I was debugging the removeStyleFromTo function and i noticed that when you (in this case) remove a character using backspace or delete, the corresponding entry is removed from the styleObj object. But afterwards, the keys in styleObj are not reset. For example if you remove the 4th character, the 4th entry of styleObj is removed. The 5th character is now the 4th, but it's style is still in the 5th entry of styleObj. The 4th entry is empty, so the 5th character gets the default text object's style.
I also noticed that the styleObj is not used to overwrite the corresponding this.styles entry. I fixed this by adding this code:

```
        // remove and shift left on the same line
        if (this.styles[lineStart]) {
          styleObj = this.styles[lineStart];
          var diff = charEnd - charStart;
          for (i = charStart; i < charEnd; i++) {
            delete styleObj[i];
          }
          for (i = charEnd; i < this._textLines[lineStart].length; i++) {
            //shifting
            if (styleObj[i]) {
              styleObj[i - diff] = styleObj[i];
              delete styleObj[i];
            }
          }

          var newStyleObj = {};
          var k = 0;
          for(var j=0; j < Object.keys(styleObj).length; j++) {
              console.log(styleObj[j]);
              if(styleObj[j]) {
                  newStyleObj[k] = styleObj[j];
                  k++;
              }
          }

          this.styles[lineStart] = newStyleObj;
```
This fixes the gaps in the object entries and sets them in this.styles

**Comment by asturur** [comment]
i do not understand the fix. you are switching to a line style of possible:

{ 4 , 8 , 10 } to one of { 0, 1 , 2 }.

Does not make sense to me

**Comment by asturur** [comment]
Can you try again with the same fiddle? to me looks like it work flawlessy now with latest changes

**Comment by jilster** [comment]
I can still reproduce using the fiddle:

1. enter editing mode
2. click 'change fontsize using setselectionstyles'
3. place your cursor somewhere in the text en use backspace

steps 1 and 2 can be switched. Does it work normally when you do the same?

The fix works because the gaps in the keys where giving me troubles, i'll try to explain.

If you have a text object with a fontsize of 40, with the text 'abcd', and all characters have a fontsize of 20 that is set through setselectionstyles, the this.styles object looks like:

0: fontsize 20, 
1: fontsize 20, 
2: fontsize 20, 
3: fontsize 20 

In the current situation, when you remove the letter b from the text element, key 1 from this.styles is removed, so it now looks like:

0: fontsize 20, 
2: fontsize 20, 
3: fontsize 20 

In the text object, this happens:

letter a uses this.styles entry 0, so becomes fontsize 20
letter c uses this.styles entry 1, which is empty, so it defaults to fontsize 40
letter d uses this.styles entry 2, so becomes fontsize 20

By remapping the keys, my problem is solved. As far as i know by testing, i didn't create any new problems.

I am using MacOS and i tried Chrome, FireFox, Safari and IE, i can reproduce on all those browsers . I also tried Windows computers and other Macs. I can't figure out what's wrong

**Comment by asturur** [comment]
you create the problem that if the text was first letter, red then blu, green, yellow, then purple with spaces of unsitled letters in the middle, remapping the indexes will just move everything.

**Comment by jilster** [comment]
Hm, i tried making all letters different colours and that problem is not created, with my fix it works perfectly. Would you like me to make a big fiddle with my fix and multiple use cases?

And is it correct that the bug is gone for you when you use the original fiddle?

**Comment by jilster** [comment]
By the way, if this is getting annoying for you, you can just close this issue and i'll keep using my fix. I don't want to bother you and it's no use if i am the only person encountering this bug.

**Comment by asturur** [comment]
no i need to find the bug, that i saw with my eyes, but can t replicate anymore. but i m sure your fix is wrong with texts that have just some style sparse on the line

**Comment by jilster** [comment]
You are right, im my use case all characters have corresponding entries in this.styles, because i used selectAll and then setSelectionStyles. If i select and change only 1 or a couple of characters, and then i use backspace, all styles are ruined.

I hope you eventually find a way to recreate and fix this. I am a bit desperate now, because i am working on a application now for almost 2 years, and this is the only issue left for me to fix before i can release. The application i am replacing currently has 425.000 users

**Comment by asturur** [comment]
I think i fixed it.

**Comment by jilster** [comment]
yes you did, thank you so much!

**Comment by asturur** [comment]
oh what app are you replacing?
