### ISSUE TITLE
Setting stroke after creating object

### ISSUE THREAD

**Issue by dragondgold** [kangax/fabric.js#4092]
## Version
2.0.0 beta 3

## Test Case
[http://jsfiddle.net/Da7SP/573/](http://jsfiddle.net/Da7SP/573/)

## Steps to reproduce

1. Create an object
2. Add it to the canvas
3. Change the stroke after the object is added to canvas

## Expected Behavior

The stroke changes after `canvas.renderAll()` is called

## Actual Behavior

The stroke doesn't update anymore, you have to recreate the object to change the stroke

**Comment by asturur** [comment]
Please read here http://fabricjs.com/fabric-object-caching

**Comment by dragondgold** [comment]
Well yeah, it seems like caching is the problem, now stroke is cached too? This didn't happen in `2.0.0 beta 2`

**Comment by asturur** [comment]
i guess it was. Everything is cached. The shape is painted somewhere and it does not get refreshed unless you choose to do the things that are described in the link.
I suggest to use the .set('stroke', blue) is better than having the object properties inspected each render

**Comment by dragondgold** [comment]
Gotcha, thank you very much @asturur
