### ISSUE TITLE
How to improve performance with large number of objects in old version?

### ISSUE THREAD

**Issue by daer-ru** [kangax/fabric.js#4095]
## Version
1.6.3
I can't update to last version in my project :(

## Actual Behavior
In my project i can add on canvas over 10000 objects.
But i have performance problem even with 1000 when i try move objects or zoom canvas.

## Expected Behavior
I  tried update to latest version 1.7.16, part of my project was broken, but performance was much better when i try move objects.

Sory, i can't make a fiddle because json is to large :(
But i can show you json file:
[scheme.json.zip](https://github.com/kangax/fabric.js/files/1145068/scheme.json.zip)

**Comment by asturur** [comment]
You have to update to lastest.
If project was broken, check what is broken and fix it.

**Comment by daer-ru** [comment]
@asturur i can't update now because of some reasons. If update the only way for improve performance... it's very bad for me.

**Comment by asturur** [comment]
I'm sorry. I have no idea how to draw more than 300 objects on a 2d canvas without using the 1.7.x caching. Also in that situation it can be slow.

**Comment by asturur** [comment]
If you want to update and post what is breaking we can move on. Or we can close the issue.

**Comment by daer-ru** [comment]
@asturur Thanks, i tested all 1.7.* versions and chose 1.7.11, now i try to fix all bugs, maybe i can do this (i don't know yet :) )

**Comment by asturur** [comment]
you have to pick up latest. 1.7.12, 13, 14, 15, 16 has been made to fix stuff.

**Comment by daer-ru** [comment]
1.7.11 much better than 1.6.3. With 1.7.12, 13, 14, 15, 16 i have to many broken parts and i afraid i don't have enough time to fix. I will try to do it later.

**Comment by daer-ru** [comment]
@asturur hi, i have a small question :) I tried different variant to show many objects on canvas.
For example:
I have 2400 objects.
When i add their on canvas directly - perfomance is not good.
But when i add same 2400 objects to group and then add group on canvas - performance is much better.

First i thought problem could be with mouse events on object, but if i off all events probelm is stay.
I can't understand why it works like this ( Maybe i missed something in doc.

**Comment by asturur** [comment]
is a problem of number of drawing operations.

without any kind of sibling caching, 200+ objects are a problem

**Comment by daer-ru** [comment]
But number of drawing operations same in both variant (2400). Difference only in group (objects in group and objects without group).

**Comment by asturur** [comment]
No are not.
When grouped, you get one draw operation.
To be more precise you execute 2400 drawing operation to create the group, then is just one.
WIthou sibling caching will be slow, i did not implement it yet and i have no idea when i can do it.
