### ISSUE TITLE
Removing arbitrary pixels from canvas

### ISSUE THREAD

**Issue by tnguyen94** [kangax/fabric.js#4100]
For my project, I'm adding fabric.Image elements one by one next to each other on the fabric. 
Each image element is part of a larger image. My issue is that as the number of elements grows, the browser slows down and eventually crashes. Is there a way of removing a square chunk from the fabric before adding a new Image on top of the removed section? If not, is there a better way of managing memory?

**Comment by asturur** [comment]
Well you have the main problem that the canvas can go up to 12kx12k or bigger in some browser.
With how many images and how big are yuo working?

**Comment by tnguyen94** [comment]
I am working with hundreds of images and the canvas is 1000x600. The performance issue arises when the number of fabric.Image elements reaches ~600. I am printing the number of elements using canvas.getObjects().length.

**Comment by asturur** [comment]
sure you have 600 images loaded, how big are those images?
you have 600 images to paint. can you group some togheter? i m fine helping with performances problem but having a snippet to understand would be nice.

**Comment by tnguyen94** [comment]
They image sizes are inconsistent unfortunately. I don't think I can group them together as the images are received one by one and must be displayed as they come in (like streaming). Here's a snippet of the code that is adding the fabric.Image objects to the fabric. This function is called every time my app receives a new image to add on the canvas from a server.

display.loadFragment = async function( aURL, aVariable, aSection, anXCoord, aYCoord )
	{  
		var update = new Image();
		update.onload = function() {
			var img = new fabric.Image(update);
			img.set({
				selectable: false,
				lockUniScaling: true,
				centeredScaling: true,
				left: anXCoord - display.xOffset,
				top: aYCoord - display.yOffset 
			});
			display.fabric.add(img);
			display.fabric.renderAll();
		};
		update.src = "/SGWPD/image_fragment" + aURL + "?VAR=" + aVariable + "&SECT=" + aSection;
	}

**Comment by asturur** [comment]
so if the canvas is 1000x600, 600k pixels. 600images, they are all small or they are really zoomed out.
They are not selecatble so probably grouping is a good idea, updating the group is not expensing and then it will be just one render

**Comment by tnguyen94** [comment]
You're suggesting I create a group and with each update, I add the new image to the group? Then I do canvas.add(group)? Will this allow the images to show up one-by-one on the fabric? That is important for this project.

**Comment by asturur** [comment]
sure.
Try:
create empty group, add to canvas.
load an image
when loaded give the image the props you need
group.addWithUpdate(image);
group.isDirty = true;
re render.

**Comment by asturur** [comment]
if you want to optimize more you need a custom class that instead of redrawing everything will redraw just the new image on group

**Comment by tnguyen94** [comment]
Thank you so much! You've improved my performance significantly already but it still slows down a little after many elements are added to the group. Do you mean group.dirty = true? I couldn't find a isDirty on the group API. Also, is there a way of an element in the group before I replace it with another image? There are boxes around the images when I add them to the group. Is there a way to fix that? Here's an image.
![image](https://user-images.githubusercontent.com/22102133/28220050-12fc2548-688c-11e7-8f31-99f2bc85bcaa.png)

**Comment by asturur** [comment]
if you are doing something that is completely on some pattern, really think of some custom class, it will help you so much.
So your use case is a map like.

Are you zooming? can you share 5-6 images and  the code you are using so far to add them?

**Comment by tnguyen94** [comment]
I don't actually have access to any of the images since they're being sent from a remote server. Each box in the above screenshot is an individual image. Yes, I zoomed in to take this screen shot. It is a function I implemented. Here is the code: 

`var smooshed = new fabric.Group();
		smooshed.dirty = true;
		smooshed.selectable = false;
		display.fabric.add(smooshed);
		update.onload = function() {
			//var bg = new fabric.Image(background);
			var img = new fabric.Image(update);
			img.set({
				selectable: false,
				lockUniScaling: true,
				centeredScaling: true,
				left: anXCoord - display.xOffset,
				top: aYCoord - display.yOffset 
			});
//			display.fabric.add(img);
			smooshed.addWithUpdate(img);
			
			
			applyZoom();
			display.fabric.renderAll();
		};
		update.src = "/SGWPD/image_fragment" + aURL + "?VAR=" + aVariable + "&SECT=" + aSection;`

**Comment by asturur** [comment]
that white borders could come from some rounding of the cache that is misplacing the images. Without an handfull of images we can test. save what you download

**Comment by tnguyen94** [comment]
I actually removed the borders by doing `group.padding = 0`. Is there a way of removing the first added item to the group or canvas? Something like group.getObjects().remove(first_element)?

**Comment by asturur** [comment]
you can remove the object at the bottom of group stack doing

group.removeWithUpdate(group.item(0))

if the removal will not change group dimensions you can use remove instead of removeWithUpdate

**Comment by tnguyen94** [comment]
I was not able to resolve my problem using groups but I was able to find a work-around using the code you provided above. I removed the object at the bottom of the canvas when the number of elements passes a certain point. Thank you so much, as I would not have gotten this without you!
