### ISSUE TITLE
Rotate angle change the position of object

### ISSUE THREAD

**Issue by jigs-bc** [kangax/fabric.js#4103]
Hi,

I have added a object and rotated with some angle when i use this pre-loaded object using previous data then position get changed.

**Comment by asturur** [comment]
Please add a fiddle to support the issue.

**Comment by jigs-bc** [comment]
Hi Asturur,

Sorry for late response. I have created fiddle for my issue regarding rotation angle issue. I have set the top and left position for 100 px but left position is not working properly. Please refer https://fiddle.jshell.net/zqshx6zd/

Can you please let me know what i am doing wrong?

Thanks
