### ISSUE TITLE
setOverlayImage and excludeFromExport = true

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4104]
Hi,

Tested with the v2.0b3

I set an overlay object, but i don't want it to be exported in json.
I was thinking the parameter "excludeFromExport = true" on the object used as overlay could result in an empty json node for the "overlayImage" tag. But the node is still present with the object even if the parameter "excludeFromExport" is set to true for the object.

Is that a bug, or a wanted behavior ?

Let me know if a jsfiddle is needed to confirm this ticket.

Thank you.

**Comment by asturur** [comment]
is a bug.

**Comment by asturur** [comment]
The function is `__serializeBgOverlay` in static_canvas.class.js.
Is very easy to fix for both bgImage and overlayImage.

If you have time and want to propose a fix ( with a test case ) i will not be able to do it untill tomorrow.

**Comment by ncou** [comment]
Hi,

Not really sure if i could find some times tonight.
I looked at the source code, and i think there is 2 possibilities (but i didn't test it).

I could change line 1157 the two "if" like this (to add a check on the excludeFromExport value) : 

```javascript
if (this.backgroundImage && !this.overlayImage.excludeFromExport) {
        data.backgroundImage = this._toObject(this.backgroundImage, methodName, propertiesToInclude);
      }
      if (this.overlayImage && !this.overlayImage.excludeFromExport) {
        data.overlayImage = this._toObject(this.overlayImage, methodName, propertiesToInclude);
      }
```

But perhaps a more cleanner solution is to change the __toObject() function (there is already a filter in the "__toObject**s**()" function) in the static_canvas class.
add at the start of the function something like this :
`if (instance.excludeFromExport) {
 return;
}`

PS : I don't really know how to handle the "test case", can you point me a "good" example i could reuse ? I will use Google later to better understand this part.

**Comment by asturur** [comment]
yes maybe adding an early exit to _toObject is better.
Remove the filter statement over the objects array.

I'll point you to a test case. There is no rush to fix this.

**Comment by ncou** [comment]
When you said "Remove the filter statement over the objects array.

You mean removing the statement `.filter(function(object) {
        return !object.excludeFromExport;
      })` code in the __toObjectS function (because there will be an early exit in the __toObject() function) ? is that right ?

**Comment by ncou** [comment]
I made a quick test and it work fine (tested with the propertie "excludeFromExport" : true and false for the overlay object, not tested yet for the backgroundimage object).

Here are the changes i made (remove the .filter function, and add an early exit in the _toObject function).

```javascript
_toObjects: function(methodName, propertiesToInclude) {
      return this.getObjects().map(function(instance) {
        return this._toObject(instance, methodName, propertiesToInclude);
      }, this);
    },

    _toObject: function(instance, methodName, propertiesToInclude) {
      var originalValue;
      if (instance.excludeFromExport) {
      	return;
      }
      .........
    },
```

Is there some tools or preset to use to format the fabric.js code ?

**Comment by asturur** [comment]
ok i ll open a PR with this changes and closing the issue

**Comment by asturur** [comment]
i had to make the longer fix since we are not outputting null properties to object. so returning null would require extra code to then remove the empty objects or props.

**Comment by ncou** [comment]
Strange, because with the modification i tested above, i didn't get 'null' in the outputed json, the node was not present.
