### ISSUE TITLE
Why do I always need to click two clicks to delete？

### ISSUE THREAD

**Issue by jsonformat** [kangax/fabric.js#4105]
Why do I always need to click two clicks to delete？
[link](https://stackoverflow.com/questions/45031060/canvas-click-the-picture-to-generate-the-fork)
I try to use the plugin **fabricjs-customise-controls-extension**
[link](https://jsfiddle.net/Charles_/r9ytud3o/)
But the result is the same.
This problem has been bothering me for a long time.
I hope someone can help me.
Appreciate!!

**Comment by asturur** [comment]
The fiddle that is posted on SO works.

**Comment by jsonformat** [comment]
I do not quite understand what you mean
Can you say a little more or give me a link?
:)

**Comment by asturur** [comment]
https://jsfiddle.net/sb2z1jq1/

this fiddle works

**Comment by jsonformat** [comment]
__I follow the dome in the project inside the application__

<img width="996" alt="qq20170717-234130 2x" src="https://user-images.githubusercontent.com/18202503/28276694-53df07d0-6add-11e7-84dc-b83db8333caf.png">

The code went here to output some information

<img width="682" alt="qq20170717-234317 2x" src="https://user-images.githubusercontent.com/18202503/28276770-836d5baa-6add-11e7-8e1d-25d12b3716fd.png">

Output information to see no problem
Normally run this code picture should be deleted


<img width="1182" alt="qq20170717-234341 2x" src="https://user-images.githubusercontent.com/18202503/28276806-a20e0f14-6add-11e7-8699-fdaa61557c9f.png">

But that's not the case

**Comment by asturur** [comment]
Can you create a failing fiddle? This is completely out of the fabricjs issue tracker scope.
On your SO question there is a working fiddle and a question why it is not working. Please provide a fiddle that effectively requires the double click

**Comment by jsonformat** [comment]
[dome](https://jsfiddle.net/Charles_/mvgj6rfL/6/)
Almost the same situation as the project.
But dome is fine.
There's something wrong with my project.
Can't find the reason.
No language...

**Comment by jsonformat** [comment]
May be set up fabric.Object.prototype.renderOnAddRemove = false
I try not to set this property to normal delete
Most of the time

**Comment by asturur** [comment]
to me looks renderOnAddRemove ( that is on canvas not on object ) being false, the canvas do not get rendered and the object looks like is still there.
