### ISSUE TITLE
Where is 2.0.0-beta2?

### ISSUE THREAD

**Issue by human-a** [kangax/fabric.js#4106]
Hi

I recently update to beta-3 to test the changes for text element, but this new version is introducing a host of new issues including the rendered image sizes outputted from the canvas, sometimes the canvas.toDaraUrl renders only a white image as the output and some other issues I encountered and there are so many that I could not create a fiddle for it.

I understand that these are the beta versions and these issues are supposed to happen, I wanted to roll back to the beta-2 that only has some issues with the text but apparently it does not exist anymore. Is there any way I could get my hands on that particular version? (2.0.0-beta2)

**Comment by asturur** [comment]
i guess is just on NPM. I forgot to tag it here.
Maybe i can find the commit and tell you.

Please tell me those issues because i m unaware of them and i will end up pushing them to release.

**Comment by asturur** [comment]
Also be aware of this: https://github.com/kangax/fabric.js/pull/4076

**Comment by human-a** [comment]
Could not find it on NPM, please let me know if you find it.

I was trying to create a fiddle the issues, but I had to include a large portion of the project I am working on, I will try to dissect the issues into smaller parts and share them one by one, for now the most important one is the rendered images sizes, I will share the link here as soon as I can recreate them.

**Comment by asturur** [comment]
https://github.com/kangax/fabric.js/blob/ec2a716344c12986e89a3f9f28d4d489bcd15dd8/dist/fabric.js 

This is when i tagged beta2. Is not that i paid more attention, just that i pulled in some stuff and decided to update.
If you can just describe the bugs i ll try to find where the problem could come from.

I m gonna update all the website on the 2.0 beta so that i can work on docs easier and kitchensink will help identify stuff.

Is too hard to work on new version and keep alive the old one on the website.

**Comment by human-a** [comment]
Thanks for the link, last night I realized that the reason I could not find it on NPM was that there is a dot before that last 2 on version numbers on npm so the ```2.0.0-beta2``` is actually ```2.0.0-beta.2``` when you wanna pull it from npm repo. I search it via ```npm view fabric```

About the issues, I will try to make a fiddle or plunkr to demonstrate them, but it will take some time since I have to recreate parts of my application. You can close this issue. I will create new issues based on the issues one by one once I have the fiddle ready.

As always thank you very much for your help.

**Comment by human-a** [comment]
And by the way, that version of beta.2 that you sent me the link to is the one where Noise filter was not working. With the npm version of beta 2 I get an error when I select an image, here is the error:
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at klass._render (fabric.js:18795)
    at klass.drawObject (fabric.js:12727)
    at klass.render (fabric.js:12688)
    at klass._renderObjects (fabric.js:6886)
    at klass.renderCanvas (fabric.js:6864)
    at klass.renderAll (fabric.js:8787)
    at klass.eval (aligning_guidelines.js:197)
    at klass.fire (fabric.js:215)
    at klass._handleEvent (fabric.js:10523)
    at klass.__onMouseUp (fabric.js:10499)
```

I know there should be a fiddle and I am working on it ;)

**Comment by asturur** [comment]
the one i linked has not the image error.

**Comment by human-a** [comment]
Yes, but the noise filter is NOT working in that version. It increases the brightness instead of adding noise, which fixed it here: https://github.com/kangax/fabric.js/issues/4019

**Comment by asturur** [comment]
so pull down that moment and build it.

copy the commit code, clone the repo, git checkout hash.
the build

**Comment by human-a** [comment]
The result is the same, downloaded the moment, ran the node build on it, still, the Noise filter is not working.
