### ISSUE TITLE
Fabric 2.0 : Space removed by toSVG in multiple style text

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4116]
## Version
2.0 beta 3

## Test Case
http://jsfiddle.net/S9sLu/1836/

## Steps to reproduce
Select the word "world" hit ctrl-b to make it bold.
Hit btn "export SVG"

## Expected Behavior
See the sentence "Hello world man" with all the right space.
In fabric 1.7.15 it's ok.
<img width="351" alt="screen shot 2017-07-21 at 15 07 49" src="https://user-images.githubusercontent.com/8090162/28464698-a5a023e6-6e26-11e7-9823-11a358c03160.png">

## Actual Behavior
We wee "Hello worldman" 
<img width="313" alt="screen shot 2017-07-21 at 15 07 21" src="https://user-images.githubusercontent.com/8090162/28464656-73e07a7c-6e26-11e7-9a55-c30871af054d.png">

**Comment by asturur** [comment]
Fixed! I m making a beta4 today fixing a bit of things

**Comment by blobinabottle** [comment]
Thanks that was awesomely fast!

**Comment by blobinabottle** [comment]
It seems this bug is back in beta 6 in Safari ?

**Comment by asturur** [comment]
Can you paste here a full svg i can try in safari?

**Comment by blobinabottle** [comment]
Is this ok? Do you see the bug?
```<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="300" height="300" viewBox="0 0 300 300" xml:space="preserve">
<desc>Created with Fabric.js 2.0.0-beta6</desc>
<defs>
</defs>
	<g transform="translate(185.5 123.1)">
		<text xml:space="preserve" font-family="Times New Roman" font-size="40" font-style="normal" font-weight="normal" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1; white-space: pre;" >
			<tspan x="-175" y="12.57" >Hello </tspan>
			<tspan x="-76.13" y="12.57" style="font-weight: bold; ">world</tspan>
			<tspan x="23.87" y="12.57" > man</tspan>
		</text>
	</g>
</svg>

**Comment by asturur** [comment]
i ll try to open it in safari. if safari does not support the whitespace
attribute the other way is swapping spaces with non breakable spaces but i
would be sad to see safari so dumb

**Comment by blobinabottle** [comment]
Shouldn't we reopen this ticket? Did you find if the bug come from safari or fabric? :-)

**Comment by asturur** [comment]
did not open safari yet.

**Comment by asturur** [comment]
Looks like safari is ok if we put the style white-space to each tspan.
![image](https://user-images.githubusercontent.com/1194048/30154215-7d5a02ae-93b9-11e7-8f10-e5e5ff6b68af.png)

**Comment by blobinabottle** [comment]
okay cool, so you think it could be "easy" to fix?

**Comment by asturur** [comment]
yes it is.

**Comment by nitin-bc** [comment]
Hi, 
I am facing the same issue in 1.7.9. Please refer attached image for SVG and try to open it with browser and image viewer and see the difference. [](https://www.justsign.nl/pub/media/productdesigner/designs/catalog/product/orig/des_5738cf99e0.svg)

Thank You.

**Comment by nitin-bc** [comment]
[](https://www.justsign.nl/pub/media/productdesigner/designs/catalog/product/orig/des_5738cf99e0.svg)

**Comment by nitin-bc** [comment]
[https://www.justsign.nl/pub/media/productdesigner/designs/catalog/product/orig/des_5738cf99e0.svg](https://www.justsign.nl/pub/media/productdesigner/designs/catalog/product/orig/des_5738cf99e0.svg)

**Comment by asturur** [comment]
@nitin-bc  we cannot take care of differences between browser and image-viewer. Only fabricjs related issue or svg non conformities.

**Comment by nitin-bc** [comment]
Yes, I can understand your concern and I am not asking to compare them both. I just want to convey you that space is being removed while generating the SVG image.

Hope you are getting me.

**Comment by nitin-bc** [comment]
Hi @asturur, would you please update me on this if possible?

**Comment by nitin-bc** [comment]
Hi Everyone,

Is there any update on this for me? It would be great if someone can help me out as soon as possible.

Thank You.

**Comment by asturur** [comment]
You are using 1.7.9 and not latest 1.7.22 and we do not have a reproducible case for it. We can t really help in this way

**Comment by nitin-bc** [comment]
I have used the latest one and seems working fine. Thank you. But in this case for masking feature, I can't see the added image to the canvas, even I have set the "Objectcaching:false" already
