### ISSUE TITLE
Disposing Fabric object within 400 milliseconds after mouse up causes exception

### ISSUE THREAD

**Issue by alex-shevchenko** [kangax/fabric.js#4117]
## Version
1.7.16

## Test Case
http://jsfiddle.net/Da7SP/578/

## Steps to reproduce
Disposing Fabric object on mouse:up event or within 400 milliseconds afterward will cause an exception in timeout set by _onMouseUp handler, that will try to add event listener to destroyed element.

**Comment by asturur** [comment]
thabks for the info, may be related to a bug i need to check.

**Comment by asturur** [comment]
thanks fixed!

**Comment by kingpalethe** [comment]
I am having this exact same issue, I can reproduce it with this same fiddle:

http://jsfiddle.net/Da7SP/578/

This fiddle seems to be using 2.6, the most recent version of Fabric.js

**Comment by asturur** [comment]
ok i see the point now.
No there is no a way to stop the event from finishing and i do not think we should do it.
But since you are disposing an deleting all the contexts, we could safeguard the render code to avoid move on if there are no more valid contexts.

I assume you could avoid disposing the canvas and just clear it or reload the items on top of it, i m not sure how the app works and i do not know if this is the best pattern.

**Comment by kingpalethe** [comment]
@asturur thanks. It looks like I should, as you say, not attempt to `.dispose()` the Fabric canvas after each drawing, but instead should be using `.clear()`

**Comment by asturur** [comment]
still disposing would be legit. Is also ok to assume after an event there
is dev code that has been run and something should be checked again.

i want to see if it can be done fullproof

**Comment by Vuliniar** [comment]
@asturur this is still happening. One way is to check if contextTop exist, but still that's not always going to be accurate. Should we add something like state/status: 'painted', 'disposing' or something similar?

**Comment by asturur** [comment]
does it happen on the last version?

**Comment by asturur** [comment]
i think we need to go point by point and make the code safer.
Or explain clearly how the developer can avoid falling in this kind of traps
