### ISSUE TITLE
toDataURL broken in beta4

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4124]
Hi,

I mentioned a few days ago that the toDataurl function seemed broken when i made a custom build.
Looks like this bug is still present in the official beta4 :

Beta3 => Work ok
http://jsfiddle.net/9WWtV/31/

Beta4 => empty toDataURL result
http://jsfiddle.net/9WWtV/32/

PS : the deactivateAll and deactivateAllWithDispatch functions seems to have been removed, it could be interesting to add it to the wiki for the incompat section for the v2 lib.

**Comment by asturur** [comment]
Sure the full braking changes description is coming.
setActiveObject, discardActiveObject, getActiveObject.

Added getActiveObjects ( gives you an array with selection of 1 or more object ).

**Comment by asturur** [comment]
not using the the multiplier fixes it, that makes the search area restricted. Going to look into it tomorrow.

**Comment by ncou** [comment]
Thank you. I see the new ActiveSelection object to replace the group selection, "risk of riots" as you said in the push comments :-)

**Comment by asturur** [comment]
Found and fixed
