### ISSUE TITLE
image "width" related to "scale factor" changed in v2.x ?

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4125]
Hi,

Not really an issue, but just to confirm if it's the normal behavior.

In v2.0b4 if i set a "width" value lower than the original width , it will crop the image.
https://jsfiddle.net/bsuLr54b/56/

With v1.7.17 the width value will adjust the scaleX factor to reach the specified width :
https://jsfiddle.net/bsuLr54b/57/

Is that normal (a change of behavior in v2) or is it bug ?

**Comment by asturur** [comment]
is a wanted effect.

in 2.0 you can crop images using cropX, cropY, width and height.

in 1.x you could scale an image using width and height because drawimage was doing that, scaleX and scaleY were not touched.
