### ISSUE TITLE
selectable=false and hoverCursor

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4131]
Hi,

When an object is selectable=false, the hoverCursor is still set on the "move cursor".
Is that normal ? the object can't be selected or moved, so shouldn't the "default cursor" be showed instead of the move cursor ?

PS : If the evented parameter = false the cursor is set to default.

Shouldn't this be related to the change of cursor in some peculiar cases ? like mentionned in this ticket : https://github.com/kangax/fabric.js/issues/4063 ?

**Comment by asturur** [comment]
If an object is not selectable is still clickable. so dev can show the cursor that he prefer.
(setting hoverCursor to what he want)

at the end is a hovering is not a 'i will select'.

there was a discussion on the previous setting ( default cursor on unselectable ) and this looked like best solution

**Comment by hga77** [comment]
But how do you have an object that:
1. Needs the 'mousedown' event
2. Needs to allow the mouse to click objects under it

In other words, without setting evented tofalse, how can I make an object not reactive to the mouse hover so I can click objects under it, while still allow for right-click event ('mousedown button=3')?
