### ISSUE TITLE
Microsoft Egde fabric canvas rendering freeze/not responding > 1.7.13

### ISSUE THREAD

**Issue by E75** [kangax/fabric.js#4138]
When you load (many rectangles in the canvas) in Microsoft Edge with the updated fabric.js (version 1.7.14 above), the whole page is not responding for about 40 seconds. 

The old version (version 1.7.13) has no problems with Microsoft Edge!. The whole canvas (rendering) is in 5 seconds finished!

Maybe new functionalities (fixes) on Microsoft Edge have broke something with canvas rendering!

**Comment by asturur** [comment]
how many are those many rectangles?

**Comment by E75** [comment]
@asturur 100 x 100 (Pixel width/height = 10)

A piece of the whole canvas

![rectangles](https://user-images.githubusercontent.com/9724772/28658475-cf4b5326-72ab-11e7-8b5c-016830c89653.PNG)

**Comment by asturur** [comment]
so ten thousands rect? are those lines or rects? can you share the code?

**Comment by E75** [comment]
```
data.forEach(function (cell) {
var newRectangle = new window.fabric.CustomRectangle(
                {
                    left: cell.L,
                    top: cell.T,
                    stroke: 'rgba(0, 0, 0, 0.3)',
                    strokeWidth: 1.0,
                    fill: 'rgba(0,0,0,0)',
                    width: cell.Width,
                    height: cell.Height,
                    hasRotatingPoint: false,
                });
            canvas.add(newCell);
    });
canvas.renderAll()
```

**Comment by asturur** [comment]
10.000 rects will be slow.
Group them togheter to get a great boost.

**Comment by E75** [comment]
Thanks for your tip, but this does not solve the problem entirely. Why renders the canvas in version 1.7.13 much faster in Edge then the later versions. Maybe a bug or something?

**Comment by asturur** [comment]
please post a fiddle with the rendering code.

**Comment by E75** [comment]
@asturur I'm on vacation now. When i'm back, then i will post a fiddle with the rendering code
