### ISSUE TITLE
It looks your MIT license file misses one line compared with the original MIT license

### ISSUE THREAD

**Issue by yunboliu27** [kangax/fabric.js#4139]
## Version
1.7.6

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by yunboliu27** [comment]
It misses "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."

**Comment by asturur** [comment]
Yes is true.
Do not what to do. Adding it know would mean that people should start including the license everywhere, while before was not asked.
That would make a change as a major version.

**Comment by asturur** [comment]
The license is like this from 2010.
I'm not going to change it now adding a restriction on top of it of having to include the copyright note around. I can see if i can leave the copyright notice in the build js in the minified version automatically.
