### ISSUE TITLE
Memory leak when we add a canvas with webgl context to a fabric.js canvas

### ISSUE THREAD

**Issue by subhasishdash** [kangax/fabric.js#4140]
## Version
1.7.6

## Test Case
http://jsfiddle.net/Subhasish2015/tzxozx4b/5/ (CPU version adding 2d canvas to fabric.js) (No leak)
http://jsfiddle.net/Subhasish2015/tzxozx4b/11/ (GPU version adding a webgl canvas to fabric.js) (leaks badly)

## Steps to reproduce
-Open Google Chrome.
-Open Task Manager using Shift + Esc , enable/check GPU memory by right clicking.

-Create a canvas having webgl context (we can get it using getContext('webgl')).
-Add a image/texture to that webgl canvas.
-Now, add the canvas to the fabric.js Canvas as a image.
```
webglCanvas = document.createElement('canvas')
webglCanvas.width = 1000;
webglCanvas.height = 500;
var gl = webglCanvas.getContext('webgl');

//code to add a texture to the canvas

fcFabric = new fabric.Canvas(fc);
    oImg = new fabric.Image(webglCanvas,
	{
		selectable : false,
		width : webglCanvas.width,
		height : webglCanvas.height,
		left : 0,
		top : 0,
		lockUniScaling: true,
		centeredScaling: true,
                alignX : 'mid',
		alignY : 'mid'
	});
        fcFabric.add(oImg);
        fcFabric.renderAll();
//clear 
if(gl.getExtension('WEBGL_lose_context')) {
    	gl.getExtension('WEBGL_lose_context').loseContext();	
 }
```

## Expected Behavior
If you observe the Chrome's task manager, there is a leak in GPU memory. But if I simply use a 2d canvas instead of webgl canvas, there is absolutely no leak. 
Fabric.js is not releasing the webgl canvas properly whereas it removes perfectly in case of 2d canvas.

## Actual Behavior
The GPU memory leak should not happen.
Because if I don't use fabric.js there is no leak at all and we as a team are now deciding upon whether to continue using fabric.js or not. 
Because our app crashes in 1-2 hours of continuous run.

**Comment by asturur** [comment]
I m sorry, i cannot be given 2 fiddles with a ton of gl code and start to search a problem in fabricjs.

How are you cleaning the memory? from my experience if the canvas is still referenced, and the texture does not get removed, the memory stays allocated.

Where are you trying to release the webglcanvas? from what i read you create a fabricImage around it and you add it to canvas.

**Comment by subhasishdash** [comment]
ok let's make it simple :+1: 
Image -> 2dCanvas -> Fabric.js Canvas(No leak)
Image -> WebGlCanvas ->Fabric.js Canvas (Leak)

I am clearing the memory using gl.getExtension('WEBGL_lose_context').loseContext(), which works fine and deletes the memory without any leaks if I don't use fabric.js
In stepwise pattern,
Image -> WebGLCanvas -> gl.getExtension('WEBGL_lose_context').loseContext()  (No Leak)
Image -> WebGLCanvas -> fabric.js canvas -> gl.getExtension('WEBGL_lose_context').loseContext()  (Leak exists)

I am saying canvas.dispose() to clear all fabric.js resources but no use.

**Comment by asturur** [comment]
let me study some doc about `gl.getExtension('WEBGL_lose_context').loseContext()` and i ll circle back.

Can you point me at how you are see the leak with a screenshot of dev tools? for me it says gpu memory 0.

**Comment by subhasishdash** [comment]
Attached few screenshots for proving GPU  leak. I just uploaded a 150KB texture and you can see from the screenshots . Before rendering the webgl canvas using fabric.js GPU memory was 4196KB, which became 32698KB  after adding the webgl canvas to fabric.js canvas. And finally after clicking clear memory, it became 16321KB. 
Does that make sense?
![afterclearingeverything](https://user-images.githubusercontent.com/3872365/28742680-360465cc-7454-11e7-8a7c-7cc46bc5484b.PNG)
![afterloadingasmallimage](https://user-images.githubusercontent.com/3872365/28742681-3610b26e-7454-11e7-947a-e26902b9a87c.PNG)
![Uploading afterloadingpage.PNG…]()

**Comment by asturur** [comment]
![testp](https://user-images.githubusercontent.com/1194048/28744832-aff13832-7469-11e7-9a57-9c4f686264e8.gif)

This is my memory changes when i open the fiddle without doing anything.
When i hit 160megs is when i click on load image.

In my opinion this is not the way to detect a leak of any kind, and since fabricjs keeps a reference to the webglcanvas before you clear it, would be better to first clear fabricCanvas and then clear webglcanvas.

If you can detect what resource is leaking, we can search what reference is keeping it alive.

Be also aware that any image in page is going to be loaded on gpu memory since the gpu composition is gonna behave in that way.

I think the fabric canvas element, cleared or not, is stored in a texture for the browser to do faster things with it.

If you get better information about this leak we will reopen the issue.

**Comment by subhasishdash** [comment]
Your screenshot is a blank image, can you upload the correct one.
And as far as checking the GPU memory is concerned, Chrome task manager works properly.
Please open http://jsfiddle.net/Subhasish2015/tzxozx4b/11/ , upload a high resolution or any  image using the file browser, click clear memory , then refresh the page , add another image , do that for 5-10 times, you will see that the memory from 4-5MB gets increased to around 100 MB and stays there until you close the tab/browser. 

But, if I simply use a 2D canvas instead of a webgl  canvas, and just refresh without even clicking clear memory, the GPU memory stays @ 4-5MB only and the same case happens if I don't use fabric.js (don't add webgl canvas to fabric.js) and say gl.getExtension('WEBGL_lose_context').loseContext(). 

Also, as per your suggestion I cleared fabric.js before clearing GPU memory, but still same issue exists.. 
plz advice

**Comment by asturur** [comment]
I see that the recording on the screen went bad. IT was an animated gif of the memory going up and down.

**Comment by asturur** [comment]
I have no advice for this. Try to find out which function is allocating and where the resource is kept.

**Comment by asturur** [comment]
And please take care that
loseContext is not for clearing the memory.
https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_lose_context/loseContext

is a simulator of gl context lost.

**Comment by subhasishdash** [comment]
okay will need to debug fabric.js , will raise a pull request if I find the solution

**Comment by subhasishdash** [comment]
Hi,
I found another cause. 
Might be helpful to you as you guys are migrating to WebGL.

So, if I add a webgl canvas with texture to either a 2D canvas or fabric.js canvas there is memory leak.
So, fabric.js is not the culprit here, it's the drawImage method that copies the WebL canvas and allocates memory in GPU somehow.

Also, You can see it(issue in fiddle) more properly by disabling GPU acceleration in chrome://flags (3rd option)

Thanks
