### ISSUE TITLE
Text Stroke is offset is compositionOperation "destination-out"

### ISSUE THREAD

**Issue by keyboSlice** [kangax/fabric.js#4142]
I am trying to create some nice text underlines (animated on hover, cleared descenders etc) using fabric to draw the underline. I am clearing the descenders by drawing the text on the canvas with a stroke and the globalCompositeOperation set to "destination-out".

I am finding that the area that is cut away seems to be to the right of the expected mask area.

I've got some screenshots to illustrate the problem:

<img width="305" alt="screen shot 2017-07-27 at 17 10 28" src="https://user-images.githubusercontent.com/2470557/28681105-45312e5a-72f0-11e7-9756-270d12a595f1.png">

<img width="284" alt="screen shot 2017-07-27 at 17 09 57" src="https://user-images.githubusercontent.com/2470557/28681104-45304472-72f0-11e7-9051-f2bc92e5a5be.png">

The first screenshot shows the area that is being masked by the text stroke.
The second shows the globalCompositeOption set to default, without a stroke applied. You can see that except for some Y axis positioning discrepancy, the characters on the canvas are well aligned, so I would expect that an equal stroke around those characters would result in even masking of the underline in the first screenshot?

Is there something causing the stroke to offset that I might be missing? 

Thanks for any help

**Comment by asturur** [comment]
Can you add some code of HOW you perform this task?

I do not see any code modification, there is no different globalComposite setting for stroke and fill, so i assume you have 2 objects with the same text that you are overlaying to achieve the effect.

If this is the case are you giving the the same strokewidth? Because if not, you will have an offset as big as strokewidth from the position of the object.

**Comment by keyboSlice** [comment]
Hi, thanks for getting back to me, sorry I didn't reply over the weekend as I was away. 

My apologies, I do not think I was clear with my initial description of the problem, I'll attempt to describe it better here. 

The text in orange is not rendered on canvas, the canvas is absolutely positioned over this text. 
The first screenshot is showing me drawing the orange text on the canvas, except I set the globalCompositeOperation to "destination-out" and apply a stroke. 

I do this with the following code:

firstly to get the font styles from the element:

```javascript
        getElementStyles(el) {
        
            let baselinePositionRatio = baselineRatio (el);
            let computedStyles = window.getComputedStyle (el, null);
        
            return {
                lineHeight:  parseFloat (computedStyles.getPropertyValue ("line-height")),
                width:       (el.getElementsByTagName ("span") [0].getBoundingClientRect ().width + (parseInt (computedStyles.getPropertyValue ("font-size")) * .1)),
                height:      el.getElementsByTagName ("span") [0].getBoundingClientRect ().height,
                parentWidth: el.parentNode.getBoundingClientRect ().width,
                fontFamily:  computedStyles.getPropertyValue ("font-family"),
                fontSize:    computedStyles.getPropertyValue ("font-size"),
                fontStyle:   computedStyles.getPropertyValue ("font-style"),
                fontWeight:  computedStyles.getPropertyValue ("font-weight"),
                baselinePositionRatio: baselineRatio (el),
                canvasLeft:  el.parentNode.offsetLeft - el.offsetLeft,
                textIndent:  el.offsetLeft - el.parentNode.offsetLeft,
                letterSpacing: computedStyles.getPropertyValue ("letter-spacing")
            }
        },
```

and then to repeat the text on the canvas with a stroke applied:

```javascript
      let charSpacing = Math.round ((parseFloat (this.elementStyles.letterSpacing) / parseInt (this.elementStyles.fontSize)) * 1000);

        let text = new fabric.Text (this.text, {

            top: parseInt (this.elementStyles.fontSize) * .05,
            left: 0,
            lineHeight: this.elementStyles.lineHeight,
            fontWeight: this.elementStyles.fontWeight,
            fontFamily: this.elementStyles.fontFamily,
            fontSize: parseInt (this.elementStyles.fontSize),
            charSpacing,
            globalCompositeOperation: "destination-out",
            stroke: "white",
            strokeWidth: this.strokeWidth,
            fill: "black"
        });

        this.fabricCanvas.add (text);
```

The desired affect of this is that the orange line (which is also drawn on the canvas) is masked by the stroke on the descenders of the canvas text.

The crux of the problem is that the orange line is not masked equally to the left and right of the descenders of the orange text, even though screenshot 2 shows that if I use the same code but without a stroke and the globalCompositeOperation unchanged, the black canvas text overlays the orange text beneath almost perfectly. This being the case, why is the stroke so heavily to the right of the descender? 

This is the code I use to generate the black text.

```javascript
    drawText () {

        let charSpacing = Math.round ((parseFloat (this.elementStyles.letterSpacing) / parseInt (this.elementStyles.fontSize)) * 1000);

        let text = new fabric.Text (this.text, {

            top: parseInt (this.elementStyles.fontSize) * .05,
            left: 0,
            lineHeight: this.elementStyles.lineHeight,
            fontWeight: this.elementStyles.fontWeight,
            fontFamily: this.elementStyles.fontFamily,
            fontSize: parseInt (this.elementStyles.fontSize),
            charSpacing,
            // globalCompositeOperation: "destination-out",
            // stroke: "white",
            // strokeWidth: this.strokeWidth,
            fill: "black"
        });

        this.fabricCanvas.add (text);
    }
```

Thanks again for taking a look at this issue

**Comment by asturur** [comment]
my answer was that you have to remove from your top left half of the strokeWidth probably.

**Comment by asturur** [comment]
did you get a chance to try my answer? can we close?

**Comment by keyboSlice** [comment]
Hi thanks for looking at this again - I've set the left property when creating the text to negative half the stroke width, it's not quite perfect but it corrects the misalignment to within an acceptable margin of error.
