### ISSUE TITLE
how to draw a image in SpritesImages?

### ISSUE THREAD

**Issue by leeseean** [kangax/fabric.js#4144]
I just want to draw an image in Sprite

## Version
1.7.6

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by ncou** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
http://fabricjs.com/docs Or try on StackOverflow forum.

If you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

**Comment by ncou** [comment]
Have you looked at the demo : http://fabricjs.com/animated-sprite
Try to open a stackoverflow thread if you want some help, and i will try to help you.
