### ISSUE TITLE
Resized SVG Cannot be grabbed from certain spots

### ISSUE THREAD

**Issue by otterslide** [kangax/fabric.js#4146]
## Version
1.7.6

## Test Case
http://jsfiddle.net/otterotter/Da7SP/580/

## Steps to reproduce
Click the 'click' button at the top
Try to move the heart, by grabbing it at the very bottom of it.  It cannot be 'grabbed' in the bottom half portion.  Only the top half.

## Expected Behavior
Object should be able to grab from everywhere it exists.

## Actual Behavior
Object can only be grabbed from the top half.

**Comment by ncou** [comment]
Here is a working fiddle.
http://jsfiddle.net/Da7SP/581/

use ".setCoords()" on the object once scaled to ensure the controls are rightly displayed

**Comment by otterslide** [comment]
Thanks.  I knew of setCoords() and tried it, but I must've been doing something else wrong in my code.  I forgot to try it in the fiddle.

**Comment by ncou** [comment]
No problem, glad this could help.
