### ISSUE TITLE
Group/ungroup problem with beta4

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4147]
Hi,

Here is a fiddle to group/ungroup selection.
http://jsfiddle.net/anwjhs2o/66/

If i select :
1-select the objects
2-click on GROUP => a group if formed from the selection => OK
3-click on UNGROUP => the objects are ungrouped, and the selection is OK.
4-click again on GROUP => Error the objects are deleted.

Is that a bug ? or I am missing something in the group/ungroup functions.

Thanks for your help.

**Comment by asturur** [comment]
i fixed this, i have still a problem. when grouping/ungrouping the corners are not clickable.
