### ISSUE TITLE
Bug with Rect with stroke and opacity in group 

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4149]
## Version
1.7.1 & up

## Test Case
https://jsfiddle.net/bL4cpLvz/66/

## Steps to reproduce
One of the rect is directly added on the canvas, stroke is "cropped" by the fill (you don't see transparency effect).
The other rect is in a group on the canvas. You see fill through the stroke.

## Expected Behavior
For me both are valid at some point. In my case I'd like to be able to crop the fill by the stroke => this allow me to simulate and stroke positioned "outside" (instead of center).

**Comment by blobinabottle** [comment]
Note: in 1.5 it's coherent behavior (transparency effect on both case).

**Comment by asturur** [comment]
I have no idea if is possible to achieve that with cache, without making very hard to read and mantain code.

I think you should probably disable caching for that object if you want that effetc.

**Comment by blobinabottle** [comment]
Thanks indeed it will be hard to achieve keeping it simple. I think it's more robust to create a group of two rects. I'm closing this as it's more a generic dev topic.
