### ISSUE TITLE
For : Rotate angle change the position of object #4103

### ISSUE THREAD

**Issue by nitin-bc** [kangax/fabric.js#4153]
Hi Asturur,

Sorry for late response on ticket #4103 . I have created fiddle for my issue regarding rotation angle issue. I have set the top and left position for 100 px but left position is not working properly. Please refer https://fiddle.jshell.net/zqshx6zd/

Can you please let me know what i am doing wrong?

Thanks

**Comment by asturur** [comment]
i saw the fiddle on the other issue, what is wrong with it? can you give explanations?

**Comment by nitin-bc** [comment]
Thanks for response. Please refer below steps i am doing :
1. Add one image on clip-art without rotation
2. Rotate that image and save the design into my server.
3. Now load this design again into same canvas then position gets changed.

Please let me know if you get it

**Comment by nitin-bc** [comment]
Hi,
Any update for me?

**Comment by nitin-bc** [comment]
Hi,
Any update for me?
I closed this ticket by mistake.

**Comment by asturur** [comment]
So i do not think the restore from JSON is broken, but everything can be.
Can you please provide your saved JSON to see what happen when we load it back?

**Comment by nitin-bc** [comment]
Hi,
thanks for your response. I have checked the json already. It is proper. You can refer this
{"id_1501501385189":{"url":"http:\/\/192.168.1.70\/Project\/rsma-magento\/pub\/media\/productdesigner\/designs\/catalog\/product\/layers\/layer_e71a16e.png","product_id":"67","top":230.5,"left":156,"tab":"design","clipartid":"37","objFilters":[{"type":"RemoveWhite","threshold":40,"distance":140}],"type":"image","text":"","textObj":{"type":"image","originX":"center","originY":"center","left":156,"top":230.5,"width":25,"height":25,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":149.01,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"crossOrigin":"","alignX":"none","alignY":"none","meetOrSlice":"meet","src":"http:\/\/192.168.1.70\/Project\/rsma-magento\/pub\/media\/productdesigner\/clipart\/\/s\/q\/squre_icon.png","filters":[{"type":"RemoveWhite","threshold":40,"distance":140}],"resizeFilters":[]},"name":"","arc":0,"oldFontSize":0,"image_id":"4996","designarea_id":"@4996","price":"null","resized_url":"","filtercolor":null,"filtercolorname":null,"filtercolorposition":null,"image_side":"1","height":25,"width":25,"scalex":1,"scaley":1,"zIndex":0,"angle":149.01419960577,"wInnerWidth":1543,"isCenter":"","resizeobject":""}}

**Comment by nitin-bc** [comment]
Hi, Did someone get a chance to check my concern please?

**Comment by asturur** [comment]
No. i did not.
The point is that you have to provide a fiddle that demonstrates that you create a json, you load it back and loading it back gives wrong results.
Clean tickets get prioritized because they are easier to verify and eventually fix.

**Comment by nitin-bc** [comment]
okay sure, I will provide fiddle for that by tomorrow,

**Comment by nitin-bc** [comment]
Hi, sorry for late response. I have created multiple instances to explain the issue better. Please refer below:
1. https://fiddle.jshell.net/k8z23a5y/
Above fiddle is created without rotation.
2. https://fiddle.jshell.net/cL6muaqg/
Above fiddle is created with rotation (angle). Please compare both ones. Both objects are on same position.
3. https://fiddle.jshell.net/8he0xcfe/
Above fiddle is create by using Json format we are using. We have kept all co-ordinates same as in fiddle 2 but object position has been changed. Can you please compare all fiddles and check what i am doing wrong?

Please let me know as soon possible, my client is waiting for this.

Thank you for your support.

**Comment by asturur** [comment]
I m putting all myself to make it clear:

https://fiddle.jshell.net/8he0xcfe/1/

i made a fiddle with loadFromJSon and random angles.
If you manage to make this fiddle fail then there is a bug i can watch at, otherwise not.

I m pretty confident there is not since i use loadFromJSON everyday on commercial application and i would have notice.

Other than that please consider that fabric 1.6.7 is not supported anymore, i still support 1.7.x branch and i fix bug on that branch but definetely not 1.6.x

Also i m happy to help when i can, but your customer problems are something that are outside the scope of an open source free project.

I close the issue, i get notified of answers anyway, i will reopen it if i see a failing fiddle.
