### ISSUE TITLE
New image editor project

### ISSUE THREAD

**Issue by ange007** [kangax/fabric.js#4154]
Hi!
I have begun development of the new editor of images on a basis **fabric.js**.
Possibly it will be interesting to someone!

![chrome_2017-08-01_15-53-38](https://user-images.githubusercontent.com/2736539/28839706-3420b566-76fd-11e7-931c-4cc2927ef22c.png)

This editor is a free analog of [Pixie](https://codecanyon.net/item/pixie-image-editor/10721475) which is also made on **fabric.js**.

**Comment by asturur** [comment]
go on fabricjs.com, on the demos section, the first one is `built with fabric.js` please file your project there.

**Comment by ange007** [comment]
Thanks!
