### ISSUE TITLE
Cannot use shift+click to deselect in activeSelection (beta4)

### ISSUE THREAD

**Issue by miyasudokoro** [kangax/fabric.js#4157]
## Version
2.0.0-beta4

## Steps to reproduce

1. Make a multi-selection of objects.
2. Hold the Shift key and click on an object that is among the multi-selection of objects.
3. The object does not get removed from the activeSelection.

## Expected Behavior
The object should get removed from the activeSelection.

## Actual Behavior
Nothing happens.

## Source of the problem
I believe that in the function fabric.Canvas.prototype._handleGrouping, the if-statement in the second line is still following the logic from back before activeObject could be an activeSelection object. Either that, or something needs to set the `__corner` property in the activeSelection object. At this point, it is undefined, and therefore the function returns early. 

```
var activeObject = this._activeObject;
if (activeObject.__corner !== 0) {
     return;
}
```

This is what makes it work for me. I'm not going to do a pull request because I'm not sure what `__corner` is for, so I'm not confident this is actually the correct fix.
```
var activeObject = this._activeObject;
if (!activeObject || (activeObject.type !== 'activeSelection' && activeObject.__corner !== 0)) {
    return;
}
```

**Comment by asturur** [comment]
http://fabricjs.com/kitchensink

on kitchensink is currently working. I can select/deselect with shift.
Can you replicate there?

**Comment by asturur** [comment]
The corner logic is valid also for activeSelection, .__corner indicates what corner is actually hovered. Strange is undefined.
Either we should loose the condition with a lazy truthy/falsy check or be sure that is properly initializated.

**Comment by miyasudokoro** [comment]
How to replicate in kitchensink:

1. Select one text box.
2. Shift-click the other text box, so a multi-selection is formed.
3. Without mousing out of the text box, shift-click it again. It is not removed from the multi-selection. A debug point in _handleGrouping shows that activeObject.__corner is undefined at this time, and the function does an early return.
4. Mouse out of the text box and back in again, and then shift-click will work to remove it. A debug point in _handleGrouping shows that activeObject.__corner is 0 at this time.

**Comment by asturur** [comment]
thanks!

**Comment by asturur** [comment]
ok the bug is that a mouse move has to happen. i m inclined to define the .__corner to 0 and explain what is it in the object class.
So is never undefined.

**Comment by asturur** [comment]
Thanks for the nice clear issue with debug information.

**Comment by asturur** [comment]
By the way, what are you doing with fabricjs at ricoh japan? if you are doing some interesting project, please add to the `built with fabric.js list` here https://devpost.com/software/built-with/fabric-js
