### ISSUE TITLE
Request maxScaleLimit

### ISSUE THREAD

**Issue by huiralb** [kangax/fabric.js#4159]
I'm glad there's a ```instImg.minScaleLimit``` property, but I do not find the ```maxScaleLimit``` property.
Is it possible to create for the ```maxScaleLimit``` ?

**Comment by asturur** [comment]
there is not.
i arrived here that minScaleLimite was already introduced, there are no docs about it.
I think is about not getting objects that small that are then unusable or with scale = 0 that will get everything down to 0.

I do not think ti was meant to be a feature

**Comment by huiralb** [comment]
Oke. Thank for your response

**Comment by asturur** [comment]
anyway you can implement it quite easily.

Define an high maxScaleLimit

```
fabric.Object.prototype.maxScaleLimit = 1000;
```

Add a onScaling event:

```
object.on('scaling', function(options) {
  if (options.target.scaleX > target.maxScaleLimit) {
    target.scaleX =  target.maxScaleLimit;
  }
  /// and same for scaleY
});
