### ISSUE TITLE
Objects grouping is not working correctly

### ISSUE THREAD

**Issue by gourabxz** [kangax/fabric.js#4161]
I am having problem with grouping multiple objects on canvas. When I select objects using holding down shift key and then if I make a group of those objects, the newly added group has incorrect z-index of it's items. Pleas follow the jsfiddle link bellow to understand the problem. Please select green box first, then select blue and then red while the shift key is pressed. Then clik on Group button to see the problem.

[Fiddle link](https://jsfiddle.net/cLp0xm58/)

I have also asked this problem on [stackoverflow](https://stackoverflow.com/questions/45465078/fabric-js-objects-grouping-is-not-working-correctly) with code snippet.

**Comment by miyasudokoro** [comment]
Please see my answer to your stackoverflow question.

**Comment by asturur** [comment]
i added some specification to @miyasudokoro  answer.
