### ISSUE TITLE
[2.0] SVG text import then convert to I-text but couldnt edit

### ISSUE THREAD

**Issue by duyhung85** [kangax/fabric.js#4162]
Hi,

In 1.7.x when I import SVG (text) and convert it to Itext to add to canvas, then I can edit the text just like normal itext object. In fabric 2.0 its not working anymore, Im just not sure its a bug or a breaking change in 2.0. Here is my fiddle

[https://jsfiddle.net/duyhung85/p0vxj09p/1/](url)

Also, just a side question, I know fabric 2.0.0.4beta API changes but I have this function to check the active group
`activeGroup = this.getActiveGroup();`
what is the new function replaces getActiveGroup() in fabric 2?

Thanks,
Hungnd,

**Comment by asturur** [comment]
https://jsfiddle.net/p0vxj09p/2/

for some reason you are setting the styles as null in your new itext.
Not sure if is a bug or not.

i need to check.

The getActiveGroup is no more, just use getActiveObject. if the activeObject is of type `activeSelection` is like an activeGroup.

**Comment by asturur** [comment]
fixed

**Comment by duyhung85** [comment]
Thank you @asturur, its working now when edit the text. But in case I have 2 text objects, I copy the second one and paste in in the end of first on to concatenate them, its not working. 

Here is the updated fiddle:
https://jsfiddle.net/duyhung85/p0vxj09p/3/

My steps:
1. Select the whole second text( yellow ) one and cut it
2. Select the first text  and paste it at the end -> error shown in console

In the 1.7x it concatenates 2 texts as expected.

**Comment by duyhung85** [comment]
Hi, I apply the same fix with the styles object. So I put this:
`if (!this.styles[lineIndex]) {
                this.styles[lineIndex] = {};
            }`

below the fix @asturur did:

`if (!this.styles) {
                this.styles = {};
            }`

Hope it helps
