### ISSUE TITLE
[2.0] Grouping & Active Selection Position Bug

### ISSUE THREAD

**Issue by jrking4** [kangax/fabric.js#4163]
## Version
2.0 Beta 4

## Test Case
https://jsfiddle.net/L16kzxzh/

## Steps to reproduce
1. Position Bug - Select 2 of the rectangles in an active selection and click group button.  Now 2 of the rectangles should be grouped. And one should not be grouped.  Now click and drag your mouse to make an active selection of the rectangle group and the remaining rectangle.  The grouped objects get moved to the upper left corner of canvas. 
2. Ungrouping bug - Select the rectangles into an activeSelection and click group button.  Now the rectangles are in a group. Now click ungroup and move the rectangles out of the way.  The old group remains.
## Expected Behavior
1 - The objects should be selected and not moved.
2 - The group you convert to an activeSelection should be removed from canvas
## Actual Behavior
1 - The object group is moved to the top left corner of canvas
2- The old group and objects still remain after ungrouping

**Comment by asturur** [comment]
I can verify just 1.
Can you check 2 again?

**Comment by asturur** [comment]
Ok not a bug, mainly because new docs are not yet ready.

toGroup and toActiveSelection do not return anything, they just do the necessary operations to move a group to activeSelection and viceversa

```
$(".group").on('click', function() {
  var activeObject = canvas.getActiveObject();
  if (activeObject.type === 'activeSelection') {
    activeObject.toGroup();
    canvas.renderAll();
  }
});
```

**Comment by jrking4** [comment]
On issue #2 I see that it clones the group to an active selection, and works as expected if i delete the group after.

But for issue #1 (position bug), i still see the group getting moved to top left corner when i try and make an active selection. I see you have verified the bug, but why is the issue closed?  Thanks!

**Comment by asturur** [comment]
did you read my message?

**Comment by asturur** [comment]
do not know, looked solved to me.

**Comment by jrking4** [comment]
This is the one im still having an issue with:

Position Bug - Select 2 of the rectangles in an active selection and click group button. Now 2 of the rectangles should be grouped. And one should not be grouped. Now click and drag your mouse to make an active selection of the rectangle group and the remaining rectangle. The grouped objects get moved to the upper left corner of canvas.

**Comment by asturur** [comment]
https://jsfiddle.net/L16kzxzh/1/

if you do it simpler it works, but i have to check why

**Comment by jrking4** [comment]
yes that seems to work.  thank you for the help!

**Comment by asturur** [comment]
Ok i found the answer i can remove the issue.
You are adding the object to the canvas twice.
When you multiselect by dragging, the object enter twice in the multiselection.
The coordinates get addjusted first one then another time from the group center and the object get's displaced too much.

Is just this.

adding the object to canvas twice is wrong and does not need a fix.
