### ISSUE TITLE
Cannot change the text cursor location via mouse click (beta4)

### ISSUE THREAD

**Issue by miyasudokoro** [kangax/fabric.js#4164]
## Version
2.0.0-beta4

## Steps to reproduce

1. Enter editing on an IText or Textbox object.
2. Try to click elsewhere in the text object to change the cursor position.
3. The text object becomes deactivated.
I checked this in Kitchensink and was able to reproduce it consistently.

## Expected Behavior
The cursor location can be changed by clicking in a different location in the text.

## Actual Behavior
The text object becomes deactivated.

## Source of the problem
The `fabric.Canvas.prototype.__onMouseDown` function calls `discardActiveObject` in line 10671 because the text object has `selectable` set to false during editing. In my project, the problem is solved by changing line 10670 to an else-if checking for `isEditing`:
```
else if(!target.isEditing){
      this.discardActiveObject();
}
```

**Comment by asturur** [comment]
i think i should remove that else condition entireli.
Thanks for the info.

Clicking on a non selectable target, and discarding active object is handled by the function shouldClearSelection.

**Comment by asturur** [comment]
Thanks for the nice clear issue with debug information.
