### ISSUE TITLE
setBackgroundImage ignores width and height

### ISSUE THREAD

**Issue by jilster** [kangax/fabric.js#4169]
## Version
Master

## Test Case
https://jsfiddle.net/7g4k1rrf/8/

## Steps to reproduce
Open the provided fiddle

## Expected Behavior
The backgroundimage should have the same dimensions as the canvas

## Actual Behavior
The backgroundimage uses the dimensions of the image instead of the dimensions of the canvas

**Comment by asturur** [comment]
Not in the new master version 2.0 beta.
You can read it, actually image is the only part i already wrote about:

http://fabricjs.com/v2-breaking-changes#image

**Comment by jilster** [comment]
i didn't see that, sorry. could you please give a simple example of how to resize an image using filters? I really don't understand what i am doing wrong, i am now trying:

https://jsfiddle.net/7g4k1rrf/10/

The fiddle is using beta5

**Comment by asturur** [comment]
looking at your fiddle i see there is some bug around.

**Comment by asturur** [comment]
Ok, so resize filters are not ready yet on webgl.

https://jsfiddle.net/7g4k1rrf/11/

if i disable the webgl you see it works.

**Comment by rluckez** [comment]
I'm facing same issue, @jilster did you solve it?

**Comment by asturur** [comment]
So since fabric 2.0, you can't really resize with width and height, you have to use scaleX and scaleY to modify the image size

**Comment by rluckez** [comment]
@asturur I tried with scale, but, i got lower resolution images than using fabric 1.X width and height.

**Comment by asturur** [comment]
this should not be the case.
Can you show it in a fiddle?
