### ISSUE TITLE
fabric.util.createCanvasElement does not always return a canvas element

### ISSUE THREAD

**Issue by miyasudokoro** [kangax/fabric.js#4171]
## Version
2.0.0-beta5

## Steps to reproduce
1. Use `var canvas = new fabric.Canvas('idOfElementNotInDocument');` 
2. An unhandled error occurs because `canvas.lowerCanvasEl` is equal to the string `idOfElementNotInDocument`.

## Expected Behavior
The lowerCanvasEl should always be an HTMLCanvasElement.

## Actual Behavior
The lowerCanvasEl is set to anything truthy but incorrect that is passed in to the constructor.

## More details
I am upgrading a project from fabric version 1.4.7 to 2.0.0, and my unit tests failed instantly because there is no canvas element of the given ID in the document during the unit tests. In 1.4.7, a canvas element was created if the element of the given ID was not found. 

I think the main issue is, the function `fabric.util.createCanvasElement` assumes that any truthy parameter is an HTMLCanvasElement. I believe this is a bug because a util function called `createCanvasElement` really should always return a canvas element, rather than just returning any truthy parameter without checking it. Suggested code change:

```
fabric.util.createCanvasElement: function(canvasEl) {
      if(typeof canvasEl === 'HTMLCanvasElement') {
          return canvasEl;
      }
      return fabric.document.createElement('canvas'));
},
```

**Comment by asturur** [comment]
Very happy to help with any transition from the old 1.4
Would be best if we find time to discuss it with a list of thing.

Going on a per issue basis can be time consuming.

So the point of createCanvasElement is just to provide a swappable function for nodejs where the code `fabric.document.createElement('canvas')` is not enough.

The JSDOC over the function does not make sense to be honest because it was there for the excanvas library.

This thing must be addressed with something more than i type guard ( that i do not like that much since the docs says to pass a canvas ).

I'll check where this function is used and propose a fix.

**Comment by miyasudokoro** [comment]
Now that I understand better about the nodejs support, then I'll point you to the place earlier on where I was also thinking a change could be made, which is in fabric.StaticCanvas.prototype._createLowerCanvas:

`this.lowerCanvasEl = fabric.util.getById(canvasEl) || this._createCanvasElement(canvasEl);`

I think you could consider changing it to this: 

`this.lowerCanvasEl = this._createCanvasElement(fabric.util.getById(canvasEl));`

This is because `fabric.util.getById` will return undefined if `canvasEl` is a string that is not the ID of an element in the document. Therefore, no more strings of any kind will be passed into `this._createCanvasElement`. However, if `canvasEl` is anything other than a string, it will be passed through without any change. Additionally, if `fabric.util.getById(canvasEl)` actually returns a canvas element, then that canvas element will also pass through correctly. 

Thank you for your offer of help, but I am pretty much done with transitioning from 1.4 to 2.0, as far as I can tell. Recently, I was given permission to post bug reports to you, so I have been passing on the ones that I am sure are applicable to other users. I have been working extensively with fabric 1.4 for this project for the last three years, so I am glad to be able to give back to the community a bit. I was able to do a workaround to get my unit tests passing, but it would be nice to be able to take that back out again and use simpler code.

**Comment by asturur** [comment]
Please if you have expertise on fabricjs your opinion on API is important. knowing  what does not meet up expectations from developers is a good point of improvement.
So if you have some bad experience with the new code, regardless of bugs, share it.
