### ISSUE TITLE
Fabric beta 2, group opacity not correct?

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4173]
## Version
2.0 beta 4

## Test Case
https://jsfiddle.net/bL4cpLvz/68/

## Steps to reproduce
Change opacity of a group containing a rect. Change opacity of a rect (not in a group). You don't get the same visual result. 

## Expected Behavior
Group opacity should get the same result as when changing object opacity.

## Actual Behavior
Seems the difference is exponential. The lower the opacity, the more the difference is visible. 

Thanks for your help.

**Comment by blobinabottle** [comment]
Forget to say, if you change to 1.7.15 the behavior is correct (group & rect got the same opacity).

**Comment by asturur** [comment]
you have to use the `.set('opacity', value)` OR manually set the group as dirty when you modify children

**Comment by asturur** [comment]
Thanks i ll look into it.

**Comment by blobinabottle** [comment]
Thanks for your quick follow up! I did try the dirty & .set method but still the result is different.

**Comment by asturur** [comment]
My previous answer was given by a misreading of the problem

**Comment by asturur** [comment]
found, it was an easy fix!
