### ISSUE TITLE
Drawing on a fabric canvas inside a viewport div container with scrollbars behaves strangely

### ISSUE THREAD

**Issue by coulix** [kangax/fabric.js#418]
Tested with latest version (7 feb 2013).

It seems that we are listening on mousemove with fabric.document, therefore catching the events outside of wrapper ?

    <div class="wrapper" style="width: 500px; height: 300px; border: 2px solid black; margin:30px; overflow: auto;">
        <canvas id="mycanvas" width="1000px" height="1000px"/>
    </div>

http://jsbin.com/ibeseh/14/edit

**Video evidence I: handDrawing**

http://www.screenr.com/4r47

**Video evidence II: resize & move**

http://www.screenr.com/kr47

**Comment by asturur** [comment]
Checked on firefox and Chrome and not an issue.
@kangax we close?

**Comment by kangax** [comment]
Yep

**Comment by coulix** [comment]
I think I found this issue with the itext tool when double clicking on chrome it scrolls down a bit the canvas by itself. Investigating.
