### ISSUE TITLE
Errors with Ctrl+V in IText object with no styles set

### ISSUE THREAD

**Issue by miyasudokoro** [kangax/fabric.js#4180]
## Version
2.0.0-beta5

## Steps to reproduce
1. In Kitchensink, create a new IText object. (This problem does not happen for a text object that has some styles already set in it.)
2. Select some text from the middle of it and use Ctrl+C.
3. Place cursor in different locations in the same text object and use Ctrl+V repeatedly.
4. In some cases of Ctrl+V, `this.styles[lineIndex]` is undefined at line 25887.

## Expected Behavior
Ctrl+V works consistently.

## Actual Behavior
Ctrl+V does not work consistently.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/29109567-bea5495e-7ce3-11e7-873a-db120ad8f8ab.png)

how does it do, there is a if guarding an undefined copied style.

**Comment by asturur** [comment]
i fixed it, and i found another bug.
that will require more to fix. 
For now i'm pushing up this change.
