### ISSUE TITLE
Images (emojis/emoticons/etc) inline inside IText ?

### ISSUE THREAD

**Issue by ajck** [kangax/fabric.js#4182]
Is there some way (feature request or hack/workaround) to include images inline in an editable text (IText/Textbox) ? Most messenger type apps and sites allow the user to insert e.g. an emoji (or other custom image) inline in the middle of their text while they're typing. I want to copy this idea using Fabric JS. Ideally allowing any image to be inserted, but also copy/pasted/deleted, like any other text character.

So, the equivalent of this: https://stackoverflow.com/questions/29579557/images-inside-an-input-text/29611863#29611863 (click the blue "Run Code Snippet" button below the code to see a working example), but in Fabric.

Thanks.

**Comment by asturur** [comment]
Fabric has nothing comparable with contentEditable.
You can insert emoticons since those are supported.
You can write a custom renderChar that listen to some particular char sequences and swap them with images.

But nothing that gets supported here.

**Comment by neerajthakur3283** [comment]
Hi all,
I have also one requirement similar to this. I just want to add emoji and animoji on my website 
![image](https://user-images.githubusercontent.com/21279371/34659427-91cc96ce-f45e-11e7-9e74-a07f99c9fb4a.png) like this so any one has any example or demo related to this.
Thank you
