### ISSUE TITLE
Fonts naming bug?

### ISSUE THREAD

**Issue by dragondgold** [kangax/fabric.js#4183]
## Version
2.0.0-beta3

## Test Case
- Non-working font: [http://jsfiddle.net/vvL6f/171/](http://jsfiddle.net/vvL6f/171/)
- Working font: [http://jsfiddle.net/vvL6f/172/](http://jsfiddle.net/vvL6f/172/)

## Steps to reproduce
Open the "Non-working font" fiddle, resize the text so the font is refreshed because it probably was not loaded before the canvas rendered, the font is not the desired one.
Now open the "Working font" fiddle and do the same, the font is the intended one. The only change is in the font family name replacing "&" by "and".

## Expected Behavior
The font should render correctly with the "&" in the font family name.

## Actual Behavior
The font won't render with an "&" in the font family name, is this a fabric.js issue or a Canvas issue? Are there any other characters that could exhibit the same behavior? I couldn't find anything related information.

**Comment by asturur** [comment]
You should try in plain canvas. Did you try?

**Comment by asturur** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/font-family

it should work if quoted.
I do not think we are quoting it right now.

**Comment by asturur** [comment]
http://jsfiddle.net/vvL6f/173/

in this ways works. i ll add to docs it, but not change any js. i remember it was breaking either node or safari.

**Comment by dragondgold** [comment]
Great, thank you very much @asturur!
