### ISSUE TITLE
Layer Controls - BringToFront, SendToBack, SendBackwards, SendForward

### ISSUE THREAD

**Issue by jrking4** [kangax/fabric.js#4187]
## Version
2.0

## Test Case
KitchenSink Demo

## Steps to reproduce
Select an object and click the BringToFront, SendToBack, SendBackwards, SendForward buttons on the kitchen sink demo. Nothing happens.

## Expected Behavior
The object's layer position should be moved.
## Actual Behavior
The object's layer position is not moved

**Comment by asturur** [comment]
Nothing happens because by default fabricjs does not preserve the stack during selection. If you go on canvas tab and enable preserve stacking, the effect is more evident.
