### ISSUE TITLE
Space bar in text lines and areas acts like enter key

### ISSUE THREAD

**Issue by pgiworldwide** [kangax/fabric.js#4188]
I originally came across this with a Wordpress plugin called Fancy Product Designer. I have also replicated it on the design ninja site thats listed as a user of Fabric.js

Hitting the space bar while typing produces a line break when trying to edit text on the stage/canvas. I am hoping this bug can be fixed soon as any product design software using fabric.js becomes somewhat ineffective if the customer cannot type on canvas. 

Below is video of the issue
https://www.screencast.com/t/1qPNeSZg

Seems to only happen in Chrome and Opera. Firefox and Safari work fine. 

Fancy Product designer said its out of there hands and in yours so I thought I would give it a shot.

**Comment by asturur** [comment]
what version of fabric it uses?

**Comment by pgiworldwide** [comment]
Im not sure. There customer support didnt give me much info other than "Our apologies, this is caused by the current version of fabrics.js we are using. We have already contacted it's developers and are waiting for a fix. We'll implement it as soon as we have it."

A day later or so they emailed the following: "The developer suggests, that maybe using normal text-layers instead of text boxes should help - not sure how useful that is for you." 

I tried the suggestion of normal text layers vs text box but with the same results.

**Comment by asturur** [comment]
what developer they contacted i have no idea. But if you open your browser tools and in the window you should be able to write fabric.version and get the version

**Comment by pgiworldwide** [comment]
my page source says "fabric.min.js?ver=1.6.1'" does that help?

**Comment by asturur** [comment]
yes that version is not fixed, you need the latest.
to be clear the bug is a chrome bug, does jot happens in any browser. introduce by chrome some version ago and that they will not fix it apparently.

**Comment by pgiworldwide** [comment]
Yea I tested 5 different browsers. I can only replicate in chrome and opera. I am assuming the developers of Fancy Product Designer are just choosing not to use the latest version for other reasons and I am kind of screwed at this point. Thanks for your insight Asturur

**Comment by asturur** [comment]
I can give you the link to the chrome bug and the solution for it.
But regarding the fancy prodict desigber  have no idea if they will fix it, they should just update to latest available of 1.x.

**Comment by pgiworldwide** [comment]
Ill take the link, thanks for the help!

**Comment by pgiworldwide** [comment]
I downloaded the latest version and uploaded the following files myself
fabric.js and fabric.min.js to the Product Designer assets folder and that seems to have solved the issue.

**Comment by pgiworldwide** [comment]
yea. I guess Ill just have to test it out and see. The guys at FancyProductDesigner made it sound like they had no plans on changing the version they were on so there must be a huge reason keeping them from upgrading.

**Comment by asturur** [comment]
For now i close since there is no bug to fix here. If you have problems post here, we know is not fabricjs problem, if i can help i will.

**Comment by pgiworldwide** [comment]
Ok thanks again.
