### ISSUE TITLE
FreeDraw adds only dots on mobile

### ISSUE THREAD

**Issue by pipriles** [kangax/fabric.js#4189]
## Version
1.7.17

## Test Case
[Test!](http://fabricjs.com/freedrawing.)

## Steps to reproduce
Enable mobile mode on Chrome and try to draw.

## Expected Behavior
I expect to draw properly with mobile mode on Chrome

## Actual Behavior
It only adds dots on Chrome with mobile mode.
However i can draw with my Galaxy Nexus.
Any ideas why this happens?

**Comment by asturur** [comment]
duplicate of #3869 and all the touch thing
