### ISSUE TITLE
[2.0] Remove Group not working

### ISSUE THREAD

**Issue by jfizz** [kangax/fabric.js#4195]
## Version
2.0 Beta 4

## Test Case
https://jsfiddle.net/5jwqkdth/

## Steps to reproduce
1) Wait for SVG to load
2) Click the delete button

## Expected Behavior
1) The object should be removed from the canvas

## Actual Behavior
1) Object remains

**Comment by asturur** [comment]
i think you found an api inconsistency.

object.remove is different from group.remove.

I think object.remove should be deleted as method

**Comment by jfizz** [comment]
Yeah, I believe that is confusing. In the fiddle above, what is the correct way to remove the group?

**Comment by asturur** [comment]
the way to remove something is

canvas.remove(object)
or
group.remove(object in group)

then the basic object class has

object.remove => canvas.remove(this)  but is not worth to have

**Comment by jfizz** [comment]
Got it. I appreciate the help!

**Comment by asturur** [comment]
removing it now, perfect for a 2.0beta stage. later is not possible anymore.
