### ISSUE TITLE
BROKEN FREE DRAWING

### ISSUE THREAD

**Issue by asturur** [kangax/fabric.js#4201]
Broken free drawing.
Need to check this commit:

https://github.com/kangax/fabric.js/commit/77632c6e0ef20cac499d79c27c775d30d09d9bae

**Comment by chukwu** [comment]
Free hand drawing offsets after drawing on both x and y positions. This is with exceptions to pattern modes such SPRAY.

You can see it at the demo
`[](http://fabricjs.com/freedrawing)`
