### ISSUE TITLE
use Convolute bug

### ISSUE THREAD

**Issue by unsilence** [kangax/fabric.js#4203]
use fabric.Image.filters.Convolute will receive error 
let filter = new fabric.Image.filters.Convolute({ matrix: [0, -1, 0, -1, 0.5, -1, 0, -1, 0] });
var obj = canvas.getActiveObject();
    obj.filters[0] = filter;
    obj.applyFilters();
   canvas.renderAll();

**Comment by asturur** [comment]
What is the error? can you create a fiddle please?

**Comment by unsilence** [comment]
![error](https://user-images.githubusercontent.com/7327717/29342817-a848c79a-825f-11e7-9cb9-62843648dba9.png)
@asturur

**Comment by unsilence** [comment]
But what puzzles me is that the example given by the official can run. Is it my fault?

**Comment by asturur** [comment]
no is broken also there.
