### ISSUE TITLE
Gradient & toSVG weird in beta 2

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4210]
## Version
2.0.6

## Test Case
http://jsfiddle.net/526wC/142/

## Steps to reproduce
Click load SVG then click export to SVG button.

## Expected Behavior
Gradients should match.

## Actual Behavior
Gradient in SVG is slightly moved.
In Fabric 1.7.15 it's ok.

**Comment by asturur** [comment]
can you post some screen of the differences?
before/after

I cannot use that fiddle i get no output

**Comment by blobinabottle** [comment]
Ah sorry, seems to work in Safari only. Don't know why.
What you see in canvas:
<img width="261" alt="screen shot 2017-08-16 at 17 24 50" src="https://user-images.githubusercontent.com/8090162/29371158-dc1bb0e4-82a7-11e7-9d66-71867d17284a.png">
What you see as svg:
<img width="292" alt="screen shot 2017-08-16 at 17 24 43" src="https://user-images.githubusercontent.com/8090162/29371203-01821d0a-82a8-11e7-8399-c6d72734f4e0.png">

**Comment by asturur** [comment]
take note that window.open(dataurl) has been removed almos everywhere.

**Comment by asturur** [comment]
can you post the original svg with gradients here?

**Comment by blobinabottle** [comment]
You can get it here https://www.dropbox.com/s/4l05i4cwrismdz8/glass.svg?dl=1
Thanks for the tip on window.open(dataurl)!

**Comment by asturur** [comment]
looks like a generic path problem. I ll fix it asap.

**Comment by asturur** [comment]
this should be solved now.

**Comment by asturur** [comment]
i have a better fix for this. uploading it asap.
