### ISSUE TITLE
Issue while setting Gradient 

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4211]
## Version
1.7.x & 2.0.6

## Test Case
http://jsfiddle.net/526wC/148/

## Steps to reproduce
Click on load SVG. 
Click fill (we loop into the _objects and replace all fills with a new one while saving previous fills as a clone). 
Click unfill (we restore the previous fill that we cloned).

## Expected Behavior
While selecting svg 2 it's the correct behavior. The fills are reset correctly with the previous color.

## Actual Behavior
But with svg 1 (which has gradients), the fills reset to black. 
And in our app if we just reload the json of the canvas, it's then correct, it shows the gradients again (I can't reproduce this behavior in a jsfiddle). 

So I'm probably doing something wrong. Or maybe there is a bug with gradients?
Maybe I could do this in a more simple way?
Thanks for your time/help.

**Comment by asturur** [comment]
I do not think you can use lodash clone deep on fabricObjects with gradients.

The class either gets cloned with all the prototype chain or without.
If without it will not work later.

the fill you cloned with the object is not a gradient is something else.

Use fill.toObject() if is a gradient, to get a copy that you can use back with setGradient('fill')
or just reference the fill somewhere, since you are overriding the fill with another value, you do not need to clone a copy of it. Just save a reference and use it later.

I should check better why it fails, i have not time now but the main culprit looks like using lodash cloneDeep on live instances.

**Comment by blobinabottle** [comment]
Thanks, I'm trying what you say (I think):
http://jsfiddle.net/526wC/150/
So now if you clic load, then fill, then unfill you'll get an error while setting the gradient.
But the gradient object seems correct to me. 

Can you guide me a little bit more?

**Comment by blobinabottle** [comment]
I think there is a problem in the fill.toObject().
Here I'm reworking the object to set the colorStops with just 1 value and it's working:
http://jsfiddle.net/526wC/151/

**Comment by asturur** [comment]
http://jsfiddle.net/526wC/154/

i did it in this way. starting on your original fiddle and changing 4 lines.

Please next time those kind of questions are better done on stackoverflow, so that someone else can use them.

```diff
var canvas = window._canvas = new fabric.Canvas('c');
// LOAD SVG
function loadSVG(id) {
  var elem = document.getElementById(id),
    svgStr = elem.innerHTML;

  fabric.loadSVGFromString(svgStr, function(objects, options) {
    var loadedObject = fabric.util.groupSVGElements(objects, options);
    canvas.add(loadedObject);
    canvas.setActiveObject(loadedObject);
    loadedObject.center().setCoords();
    canvas.renderAll();
  });
}
document.getElementById('svg-load').addEventListener('click', function() {
  var elem = document.getElementById('svg-select'),
    value = elem.options[elem.selectedIndex].value;
  loadSVG(value);
});
// FILL 
document.getElementById('fill').addEventListener('click', function() {
  var shape = canvas.getActiveObject();
  var colorSet = '#339999';
  if (shape._objects) {
+    shape.prevObjsFills = shape._objects.map(obj => obj.fill);
+    shape.prevObjsStrokes = shape._objects.map(obj => obj.stroke)
    for (var i = 0; i < shape._objects.length; i++) {
      if (shape._objects[i].fill) {
        shape._objects[i].set('fill', colorSet);
      }
    
      if (shape._objects[i].stroke) {
        shape._objects[i].set('stroke', colorSet);
      }
    }
    canvas.renderAll();
  }
});
/// UNFILL
document.getElementById('unfill').addEventListener('click', function() {
  var shape = canvas.getActiveObject();
  shape._objects.forEach(function(obj, index) {
+    obj.set('fill', shape.prevObjsFills[index]);
+    obj.set('stroke', shape.prevObjsStrokes[index]);
  });
  
  canvas.renderAll();
});
/// TOSVG
document.getElementById('toSvg').addEventListener('click', function() {
  var svg = canvas.toSVG();
  var data = "data:image/svg+xml," + encodeURIComponent(svg);
  window.open(data);
});

```

**Comment by blobinabottle** [comment]
Awesome. Thanks. I'll post this jsFiddle on stack.

**Comment by asturur** [comment]
Wait isn't fixed?

**Comment by AvaelKross** [comment]
I'm having a very similar issue. Basically I need a way to dump and then restore `fill` attribute with gradient inside.

Using `toObject()`, I'm getting the same error as in this fiddle - http://jsfiddle.net/526wC/150/. 

If I just save `fill` value and then set it back with `set('fill', gradient)`, I get full-black shape without a gradient. Do you think something else can cause black fill? I confirmed that my element has correct `fabric.Gradient` object as `fill` value.

**Comment by asturur** [comment]
i do not remember exactly what was going on.
So if you do a simple fiddle with:
```
var actualFill = object.fill;
object.set('fill', 'red');
canvas.renderAll();
```

later...
```
object.set('fill', actualFill);
canvas.renderAll();
```

it does not work?
