### ISSUE TITLE
No SVG URI with mask displayed in FF (working fine in Chrome, or if using directly the URL)

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4212]
Hi,

I made a quick codepen example to illustrate the problem.
There is a difference when loading a .svg file directly or when using the uri data (note there is an svg mask in my file).

In Chrome both of the picture are displayed (on the top using the URL, on the bottom using the data uri string).
But in FF, only the top image is displayed...

PS : If i remove the string 'mask="url(#hole)"' in the data uri string it will display on FF, but both images are the same (from url or from uri). 
Is that coming from a problem in my code ? or from the browser/svg parser ?

https://codepen.io/anon/pen/OjzjEr

Thank you for your help.

**Comment by asturur** [comment]
I think your dataurl is wrong.

https://codepen.io/asturur/pen/qXoddj

It was not url encoded. Did you generate it manually or copy pasted somewhere?

Encoding `#` as %23 Solved the problem. Could not find and specific reference to it.

**Comment by ncou** [comment]
I think i get the example browsing on the internet.

=> IE11 doesn't display anything (both the example on the top and the bottom), but i think it's perhaps a limitation of the browser (even if generaly IE could display SVG files).

**Comment by asturur** [comment]
ie11 has problems with utf8 encoding. removing utf8 word and coma after it could make it display.
