### ISSUE TITLE
toDataURL broken in beta6 for the "StaticCanvas" object

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4213]
Hi,

I got a problem with the latest version and the browser FF.
I got 2 canvas one over another (one for the main canvas, and another below for the animated background).
In IE and FF the background canvas is not displayed. It seems to me the "cancelAnimFrame" prevent the rendering of the second canvas. If i put this code line in comments, all workfine (the second canvas is draw).

```javascript
renderAll: function () {
      var canvasToDrawOn = this.contextContainer;
      if (this.isRendering) {
        **fabric.util.cancelAnimFrame(this.isRendering);**
      }
      this.renderCanvas(canvasToDrawOn, this._objects);
      return this;
    },
```

I could do a fiddle later if this help.

**Comment by ncou** [comment]
Happy you didn't do the jsfiddle because the problem is not on the 2 layered canvas.
In fact my below canvas is a StaticCanvas, and it's the toDataURL function who is broken, it will clear the canvas, so when my app generated the thumbnail it cleared the background canvas.
I didn't have this behavior with Chrome, perhaps a cache problem.

Here is a fiddle :
http://jsfiddle.net/eA3xH/186/

PS : The toDataURL workfine with the "Canvas" object, it seems broken for the "StaticCanvas" object.

**Comment by asturur** [comment]
Try to leave a functional fiddle with the example.
It can be that toDataUrl has some problem with the recent renderAllRequest vs renderAll

Let's try to understand what is it.

**Comment by asturur** [comment]
oh well is clear. we are killing the bg color.

**Comment by asturur** [comment]
http://jsfiddle.net/eA3xH/187/

So another renderAll is required after the dataUrl.
This is wrong.
I ll try to fix it.

**Comment by asturur** [comment]
ok found the error!
i ll push it up with some cumulative fixes
