### ISSUE TITLE
[Question] bringForward/sendBackward and "intersecting" parameter.

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4217]
Hi,

Just a quick question/reflexion about the "intersecting" parameter used in the bringForward/sendBackward functions.

Shouldn't this parameter simply be considered like an "accelerator" to "jump" more quickly to the index+1 or index-1 for the max/min index in the stack ? but to still calculate a new index even if there is no objects to intersect with.

Today once you reach the peak of the stacked object you can't continue to increase the index by using the "bringForward(intersecting=true)" function. Because if you have no intersection the code will not increase the index, even if there is other objects on another part of the canvas with a bigger index.

I think i could be more natural to see this parameter as "shorticut" to jump to the max index, but if there is no (or no more) intersections, the function could continue to calculate a new index.

What do you think about this ?

This behaviors is not problematic, it's just a little bit strange (at least for me), especialy since I added the layer number (=index) in my app.

I understand it's working fine so closing this ticket is an option if you think thing should stay like this.

**Comment by asturur** [comment]
Well i think we are 50%  with this.
You may be right.
I will not change the actual behaviour since in this chaos of transitioning between 1.x and 2.x this adds more chaos and bring no benefit.

A better explanation on what the parameter does is necessary on the other side.

**Comment by ncou** [comment]
Yes no problem it's not blocking, i only bring this discussion to uderstand better this parameter.

**Comment by asturur** [comment]
Most of the methods may have made sense one day.
Then some parameter got added, something else changed and the sense gets lost.
That is way i'm more and more carefull in adding new stuff.

For the avarage dev a good explanation is more important that something that makes sense, the important is that the function respect the description. We should write clearly, no intersection, no zindex change.
