### ISSUE TITLE
Text in group doesn't align as expected

### ISSUE THREAD

**Issue by kcaporaso** [kangax/fabric.js#4219]
## Version
1.7.6, 1.7.17

## Test Case
http://jsfiddle.net/qq29Lycn/

## Steps to reproduce
1. Run the Fiddle as is and notice how the three Text objects align themselves. They are shifted to the right from what should be a left: 1 (relative to the group which is also left: 1).  Notice the group itself has not moved off of left:1, click on it and you'll see the bounding controls.

2. Remove the Group's width: 300 line, I put a comment in there to draw attention.

3. Run the Fiddle now, notice how the Text objects do the correct thing and they are now left: 1 (relative to the group).

## Expected Behavior
Expected behavior is that the text will still start at left:1 even when the width of a group is specified.

## Actual Behavior
Text objects shift away from left:1 relative to the group.  The point of the width on the Group is to constrain the inner Text objects, the fact that they shift around when a width parameter is introduced seems like a bug to me.  They should stay anchored to left:1. Perhaps there is a work around?

Thanks for any help on the issue and I really do love the fabricjs library - it's made my job easier.

-Kevin

**Comment by asturur** [comment]
There is a wrong expectation, that is the one of being able to set the group width.

The group width is calculated from the content, if then it gets overridden manually, the objects keep the position they would have inside the group.
The group keep its top and left position and the bigger width push everything more right as a side effect of the rendering with the new width.

Groups are not meant to have custom dimensions, so there is nothing i can really fix.

What is your use case for setting the width manually?

**Comment by kcaporaso** [comment]
@asturur, thanks for the fast response with explanation!

The use case is in this revised Fiddle (http://jsfiddle.net/qq29Lycn/1/), where I have purple Text4 anchored outside of the group and I don't want extra text running over it from the neighboring group.
Essentially, with the group width set manually, it would cut it off before it reached the Text4, or an image for example.  I want the width of the group controlled so I can control the layout of objects.  The Text objects inside the group are dynamic in length and change as a user types in information so I would prefer the group either a) wrap when it hits the width integer or b) cuts it off so the user would know he hit the end and needs to change the text he's typing. Is there another way to control the width of a "group" of Text objects?
Thanks for any suggestions.

**Comment by asturur** [comment]
There is no one line way to achieve this.

The logic steps would be to me:

get the positon of group.
get the ration between current width and widht you want to set.
ungroup
modify width of the textboxs with the same ratio, assuming they can wrap ( single word no wrap )
put all the textbox one near the other
regroup
put the group in the old position

**Comment by asturur** [comment]
If those hints do not help, let's move the conversation on stackoverflow.
In case open a question and post the link in this issue.
