### ISSUE TITLE
The selected object can only be dragged in a range. What should I do?

### ISSUE THREAD

**Issue by unsilence** [kangax/fabric.js#4221]
Such as the title，The selected object can only be dragged in a range. What should I do?

Example：create a Rect （50，50，100，100）only dragged in the range rect(20,20,400,400),thanks.

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
