### ISSUE TITLE
1 Unicode character in the b6 source ?

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4222]
Hi,

I used the latest b6 source in my localhost to do a test, and it seems there is an invalid char line 26277 for the builded file. With SublimeText this char appear like a space, if i remove it and add a new space it work fine.

Do you need a PR for this ?

![image](https://user-images.githubusercontent.com/16743322/29455174-733d72fa-8410-11e7-9311-1ddd61e7a5a0.png)

**Comment by asturur** [comment]
I may have pressed SPACE when the keyboard was on japanese katakana.
Yes please fix it.

**Comment by asturur** [comment]
just in the file, no need to rebuild for now.

**Comment by ncou** [comment]
PR is pushed

**Comment by ncou** [comment]
Ticket closed after the PR merge
