### ISSUE TITLE
How to position an object on the canvas in absolute coordinates?

### ISSUE THREAD

**Issue by mlukasch** [kangax/fabric.js#4227]
Let's say I have x and y coordinates on the canvas.
And I want to render an object at this coordinates.
left and top dont work unfortunately.

## Version
1.7.6

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by jilster** [comment]
This does not work for you?

http://jsfiddle.net/muokpxu6/

**Comment by asturur** [comment]
I would like to handle help request on stackoverflow.
