### ISSUE TITLE
The Tutorial is broken

### ISSUE THREAD

**Issue by erwzqsdsdsf** [kangax/fabric.js#4230]
Introduction to Fabric.js. Part 5.

the url is: http://fabricjs.com/fabric-intro-part-5

![cd](https://user-images.githubusercontent.com/3872983/29485578-9ef26f26-8506-11e7-9a4a-1be877a50966.png)

**Comment by ncou** [comment]
Hi,

I think this tutorial is still a work in progress, it looks like the 9nth point from this checklist : https://github.com/kangax/fabric.js/issues/3966

**Comment by asturur** [comment]
i think i pushed it up by error.
i m giving priority to docs on changed things.

then i will add more generic tutorials, ther pan and zoom i have no idea what
