### ISSUE TITLE
Could not display a line which was created by new fabric.Line(options)?

### ISSUE THREAD

**Issue by dongkai1993** [kangax/fabric.js#4233]
## Version
2.0.0 -beta6

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/
```js
var a = new fabric.Line([100,200,200,500],{stroke:'black'});
canvas.add(a);
var json = a.toJSON();
var b = new fabric.Line(json);
canvas.add(b)
```

## Steps to reproduce
1. Create a line and add to canvas
2. Get json of the line
3. Create a new line by the json and add to canvas

## Expected Behavior
1. Could get two objects from canvas by `getObjects()`.
2. Two lines were displayed on the canvas.
## Actual Behavior
1. work well.
2. Only one line was displayed.

**Comment by asturur** [comment]
the toObject, toJSON method is not meant for direct restore.

Use  
```javascript
fabric.Line.fromObject(json, function(line) {
   canvas.add(line)
});
```
