### ISSUE TITLE
Importing each items from SVG separately?

### ISSUE THREAD

**Issue by olfibits** [kangax/fabric.js#4234]
Hello to all,
first - I am German, please excuse my bad English :)

I've been working with fabricjs for a short period and it works very good. I use it for a visual online designer. Everything works well - storing and saving on the server as well as resizing and moving the items on the canvas. Now it comes to the feature of re-opening the saved files, and I found a tutorial in which all the items are imported to one group.
Frankly, that's not exactly what I want. I need to give the users the feature of resizing and moving every single item after saving and re-importing. Is there any way - possibly with a for-construct or do-while-construct - to import the graphical items from the SVG file, item for item? I do not have any idea to get the items. What I know is adding them to the canvas that way:

canvas.add( *** THE CONTROL HANDLE I NEED TO GET ***);      
      canvas.item(c).set({
        borderColor: 'red',
        cornerColor: 'green',
        cornerSize: 6,
        transparentCorners: true
      });
      canvas.setActiveObject(canvas.item(c));

Working with the iterator **c** is working properly.

Thanks,
Florian

**Comment by olfibits** [comment]
Hello again,

from another tutorial I found a solution by editing the code.

What the code previously did:
There was an array group[]. The main callback function created a group, the other function with the parameters (item, object) pushed any item to the group.

What I did:
I removed the array group[] as well as the callback function. The parameter turned from function(objects, options) { // code ... } to function(objects,options){}
After that, I added the items to the canvas separately (my thought: if I was able to add them item for item to the group - why not to the canvas.) And it worked.

My solution for anyone:

canvas = new fabric.Canvas('designer');    
    fabric.loadSVGFromURL('data:image/svg+xml;base64,<?php echo $CONTENT; ?>', function(objects, options) {            
      
    },function(item, object) {
            object.set('id',item.getAttribute('id'));
            canvas.add(object);
    });

**SOLVED**

Greetings,
florian

**Comment by asturur** [comment]
So 2 things:
1) SVG are not good for saving and restore, use the toJSON methods that is made explicitly for that.
2) the new fabric 2.0 the svg can be imported/exported as multiple objects without tweaks.

**Comment by olfibits** [comment]
to 1. -> As I already told, I am making a visual designer. I thought that SVG is the only solution for that. Another advantage for me, I can easily preview the SVG file or let it be saved, exported or printed.
to 2. -> I am working with Fabric 2.0.0 beta. Sorry, but I don't understand what you mean.

And coming to why I posted that solution, there are many issues at stackoverflow.com or similar boards with similar issues, so sorry for posting a solution for that... I thought that is better if writing nothing or just writing "Oh, found a solution, so OK for now...".

**Comment by asturur** [comment]
Maybe i cannot read good your question.
The restoring from SVG in fabric 2.0 comes ungrouped by default, no code should be needed.
