### ISSUE TITLE
External images inside SVG not loading

### ISSUE THREAD

**Issue by gprasanth** [kangax/fabric.js#4237]
## Version
1.7.15

## Test Case
https://jsfiddle.net/21frxw12/

## Steps to reproduce
Assign an svg (with an image tag) as fill pattern to a rectangle.

## Expected Behavior
Rendered pattern should have images loaded.

## Actual Behavior
External images fail to load.

**Comment by asturur** [comment]
https://jsfiddle.net/21frxw12/1/

it does not look like a fabric only problem.
No even an image tag can load it correctly.

While a dataURL can display it in another tab/window.

**Comment by gprasanth** [comment]
This is a browser level limitation it seems like. Simply put, an image can't load another image. So, there's nothing that can be done from svg/html/js/fabric end to get this to work.
