### ISSUE TITLE
Error on canvas.getActiveGroup after updating to beta6

### ISSUE THREAD

**Issue by sandor** [kangax/fabric.js#4238]
I am getting an error while calling canvas.getActiveGroup after updating to beta6:

`controller.js:39 Uncaught TypeError: canvas.getActiveGroup is not a function
    at copy (controller.js:39)
    at Object.method (index.html:571)
    at dispatch (keymaster.js:106)
    at HTMLDocument.<anonymous> (keymaster.js:267)`

This is my definition in the controller.js

```
function copy() {
	var activeObject = canvas.getActiveObject(),
		activeGroup = canvas.getActiveGroup();

	if (activeGroup) {
		_clipboard = activeGroup;
	} else if (activeObject) {
		_clipboard = activeObject;
	}
	return false;
}
```

**Comment by asturur** [comment]
http://fabricjs.com/v2-breaking-changes-2

Please refere to this document and generally to this link:

http://fabricjs.com/changelog

for all the changes that happened in 2.0

The selection process has been simplified by much and some methods have been removed.

there is also this little demo on managing the selection programmatically

http://fabricjs.com/manage-selection
