### ISSUE TITLE
link to the corresponding canvas

### ISSUE THREAD

**Issue by InStrive** [kangax/fabric.js#4242]
I want to know how to do:More than a new canvas,The new canvas in the top drawer,Every create a canvas real-time generate a thumbnail,Was elected a thumbnail in the jump to the corresponding canvas,Every canvas is independent of each other.i am try to used "target.id" idea , but i'm failure , i can't get the fabric.canvas ID, how can i do please tell me.

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
