### ISSUE TITLE
Textbox styles disappearing for wrapped lines

### ISSUE THREAD

**Issue by mlev** [kangax/fabric.js#4243]
When adding or removing carriage returns in the wrapped text of a textbox the styles can disappear. I think it's something to do with shiftLineStyles - when adding or removing the new lines the styles and styleMap get out of sync.

This doesn't happen in Kitchen Sink demo - but we're not ready to upgrade to 2.0 yet.

## Version
1.7.17

## Test Case
https://jsfiddle.net/mlev/72p96mfs

## Steps to reproduce

Scenario 1:

1. In Fiddle put cursor somewhere in 1st wrapped line (i.e. line 2). Press enter and then press backspace. The last char of the word “lines” loses its bolding.
2. Rerun fiddle. Put cursor in 2nd wrapped line, press enter and then backspace. The last 2 chars now lose their styles.
3. Same with 3rd line - this loses 3 characters.

Scenario 2:

1. In fiddle put the cursor before the word “wrapped”. Press enter twice and then backspace once.
2. Lines before the cursor lose their styles.

## Expected Behavior

Styles retained

## Actual Behavior

Styles are lost

**Comment by asturur** [comment]
Hello mantaining the old text code was so hard that i rewrite it all, starting fabric 2.0

I do not think i will be able to solve the issue, otherwise i would not have started a new text.

I can try to help you out identify the issue but i will not find time to work on it.

**Comment by mlev** [comment]
Ah ok - I thought you might say that! We're definitely looking to move to 2.0 soon - but not quite ready yet (unfortunately need to wait for it to be out of beta). I'll take another look tomorrow.

**Comment by asturur** [comment]
I m going to holiday tomorrow. Expect no improvements from tomorrow till sept 6.

**Comment by mlev** [comment]
I think I’ve got a solution - at least I’m struggling to break it now.

**Issue 1 - removing lines:**
`Textbox._getTextOnPreviousLine` wasn’t including the “soft-wrap” character but that char is included in the styles. This leads to a char position miscalculation and so styles get shifted incorrectly. 

For now I’m just adding a space into the returned text when combining wrapped lines:

```
textOnPreviousLine = this._textLines[lIndex - 2] + ' ' + textOnPreviousLine;
```

**Issue 2 - adding lines:**
`Textbox.shiftLineStyles` maps from a wrapped lineIndex to a real line index. When called from Textbox.insertNewlineStyleObject this mapping has already happened so the lookup can be incorrect.

Not pretty but my fix for now is to ignore the lineIndex passed to shiftLineStyles and lookup the lineIndex from cursor location instead.

```
const cursorLocation = this.get2DCursorLocation();
const map = this._styleMap[cursorLocation.lineIndex];
```

**Comment by mlev** [comment]
@asturur unfortunately resurrecting this one as we're seeing this in V2 now too. Seems like in `removeStyleFromTo` it's calculating the lineStart/charStart ignoring the wrapping but when deleting styles it's using the wrapped `_textLines`. e.g.
```
        if (this.styles[lineStart]) {
          for (i = charStart; i < this._textLines[lineStart].length; i++) {
            delete this.styles[lineStart][i];
          }
        }
```

Changing to use `this._unwrappedTextLines` seems to fix things for me so far.

**Comment by mlev** [comment]
Forgot to say that you can recreate this in Kitchen Sink. Add a Textbox with 2 bold, wrapped lines, then delete the line break to create a single wrapped line. The trailing styles are cleared.

**Comment by asturur** [comment]
can you prepare a failing kitchenaink example, save the json from the tab and paste it here?

**Comment by mlev** [comment]
Try this. Put the cursor at start of Line 2 and press backspace/delete:
```
{"version":"2.0.0-rc.3","objects":[{"type":"textbox","version":"2.0.0-rc.3","originX":"left","originY":"top","left":269.08,"top":211.57,"width":190.85,"height":101.25,"fill":"#f11b9e","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":359.88,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"Line 1 styles wrapped\nLine 2 styles wrapped","fontSize":20,"fontWeight":"","fontFamily":"helvetica","fontStyle":"normal","lineHeight":1.16,"underline":false,"overline":false,"linethrough":false,"textAlign":"left","textBackgroundColor":"","charSpacing":0,"minWidth":20,"styles":{"0":{"0":{"fontWeight":"bold"},"1":{"fontWeight":"bold"},"2":{"fontWeight":"bold"},"3":{"fontWeight":"bold"},"4":{"fontWeight":"bold"},"5":{"fontWeight":"bold"},"6":{"fontWeight":"bold"},"7":{"fontWeight":"bold"},"8":{"fontWeight":"bold"},"9":{"fontWeight":"bold"},"10":{"fontWeight":"bold"},"11":{"fontWeight":"bold"},"12":{"fontWeight":"bold"},"13":{"fontWeight":"bold"},"14":{"fontWeight":"bold"},"15":{"fontWeight":"bold"},"16":{"fontWeight":"bold"},"17":{"fontWeight":"bold"},"18":{"fontWeight":"bold"},"19":{"fontWeight":"bold"},"20":{"fontWeight":"bold"},"21":{"fontWeight":"bold"}},"1":{"0":{"fontWeight":"bold"},"1":{"fontWeight":"bold"},"2":{"fontWeight":"bold"},"3":{"fontWeight":"bold"},"4":{"fontWeight":"bold"},"5":{"fontWeight":"bold"},"6":{"fontWeight":"bold"},"7":{"fontWeight":"bold"},"8":{"fontWeight":"bold"},"9":{"fontWeight":"bold"},"10":{"fontWeight":"bold"},"11":{"fontWeight":"bold"},"12":{"fontWeight":"bold"},"13":{"fontWeight":"bold"},"14":{"fontWeight":"bold"},"15":{"fontWeight":"bold"},"16":{"fontWeight":"bold"},"17":{"fontWeight":"bold"},"18":{"fontWeight":"bold"},"19":{"fontWeight":"bold"},"20":{"fontWeight":"bold"}}}}]}
```

**Comment by asturur** [comment]
yeah good catch you noticed what is broken, i just corrected it.

**Comment by fahadnabbasi** [comment]
@asturur can you please help with part 2 of the this problem in 1.7.17 version?  I mean how will I be able to get the actual styles of the line to apply now that the lines are changed after wrapping

@mlev the const thing is not working, can you please post the solution here? i.e. in which function you converted the var into const and how you use it?

I need it in 1.7.17

Thanks in advance

**Comment by asturur** [comment]
Look, rewrite and changes in 2.0 were NECESSARY because mantaining text in 1.7 was impossible for me.
I really do not know how to fix 1.7 text or i would not have been rewriting it.

**Comment by fahadnabbasi** [comment]
@asturur I totally understand it but I was just looking for some pointers as to write the solution for 1.7 myself as I cannot move to 2 yet

**Comment by fahadnabbasi** [comment]
@asturur or is there any way I can copy all the text things from v2 to v1? e.g.
Text, IText, Textbox and string utlity functions etc, will that work?

**Comment by asturur** [comment]
it could, you would need to overwrite lot of files. but it could

text.class, itext.class, textbox.class and in the mixinfolder the text related.

Plus the missing util functions that should be one or two functions.

**Comment by KhalidRudo** [comment]
Any chance you all are willing to share the above updates? I'm also working with 1.x version that is having a problems with formatting remaining in instances of text wrapping but I'm not prepared to upgrade to 2.x.
