### ISSUE TITLE
fabric.Rect borderColor not visible unless rectangle is clicked on

### ISSUE THREAD

**Issue by tnguyen94** [kangax/fabric.js#4244]
Hello, for a project I'm working on, I want to make a cursor using a fabric.Rect that highlights an area of a canvas that is about to change when a new item is added. Here's a snippet of code I've been working with: https://jsfiddle.net/wtrftauz/ 

The issue I'm having is that the borderColor isn't applied unless I click on the rectangle. I'd like the rectangle to be just the perimeter pixels of the Rect. I can already make the inner pixels transparent by setting opacity to 0 but I need the borderColor to persist without having to click on it. Thanks ahead of time.

**Comment by jilster** [comment]
BorderColor is not the correct property, what you need to use is stroke. The border around the rect that you see when you click it is to show that you selected it.

**Comment by tnguyen94** [comment]
When I use stroke and set the opacity to 0, the border disappears as well.
Is there a way around this?

**Comment by tnguyen94** [comment]
I've figured out how to use it by setting fill to rgba(0,0,0,0). Thanks very much for the push in the right direction!
