### ISSUE TITLE
MANTAINER ON HOLIDAY. YOU WILL LIKELY GET NO ANSWER TILL SEPT 6.

### ISSUE THREAD

**Issue by asturur** [kangax/fabric.js#4247]
I'm sorry guys, i m out for a bit.
When i will come back i will probably full of issues to check.
The issues that are well written, well explained, with a fiddle, will probably get my attention.

What it will look like a random question will not.
Do not be offended, but managing time is becoming harder and harder.
Just help me to help you.

**Comment by jilster** [comment]
enjoy!

**Comment by blobinabottle** [comment]
Have fun and come back full of ideas :D

**Comment by asturur** [comment]
Holidays gone!
