### ISSUE TITLE
fabricjs call to canvas.toDataURL() resizes the dimensions of the canvas

### ISSUE THREAD

**Issue by joemanfoo** [kangax/fabric.js#4252]
I've posted this behavior on stackoverflow here: https://stackoverflow.com/questions/45908772/fabricjs-call-to-canvas-todataurl-resizes-the-dimensions-of-the-canvas

and per @asturur answer I'm creating an issue for the bug.

I'm using fabricjs 1.7.17 and have seen this issue below on IE Edge, Chrome and Firefox.

where the canvas is being set with a width and height in HTML of 768px.

Within my fabricjs canvas init I've got:
```
editor.canvas = new fabric.Canvas('editor')
editor.canvas.setDimensions({
  width: 1080,
  height: 1080,
  allowTouchScrolling: false,
  backgroundColor: 'rgba(55, 55, 55, .33)',
  rotationCursor: 'url(/static/img/rotate.cur) 10 10, crosshair'
}, {backstoreOnly: true})
```

The problem is when you call the editor.canvas.toDataURL() method the size of the goes from 768px to 1080px

If you call the browser's native canvas.toDataURL() method there isn't a jump in size.

Anyone bump into this and have a possible fix?

Here's a simplified jsfiddle: https://jsfiddle.net/m8dhmbtu/23/

Click on the "Native Canvas.toDataURL()" and you'll get the results to console.log and there will be no change to the displayed canvas in the preview window.

Click on the "Fabricjs canvas.toDataURL()" and you'll also get the results (the same correct png data) to console.log however; you'll also get a jump in the size of the in the preview window...this is what I'm trying to prevent.

**Comment by asturur** [comment]
Hello, i answered your question on stackoverflow.
I believe there is something to fix, i ll do when i m back from holiday probably.

there are 2 things to take in account:

who does not resize the canvas can use the same logic is in place now with a simple fix.

who resize the canvas can as well use the current logic adding backstore dimensions only resize, fixing the problem but at cost of an unefficent twice resize and cache invalidation.

so a simple fix is very simple and consist of adding the backstoreOnly true to the 2 resizes in the toDataUrlWithMultiplier function if you want to give it a shot.

**Comment by joemanfoo** [comment]
@asturur - that fixed the issue. Thank you!
I don't know how to make a pull request into this repo - (git neophyte here) - but can sort that out when you return from your holiday. Thank you greatly for taking a look while you are on holiday
