### ISSUE TITLE
Dimensions are wrong

### ISSUE THREAD

**Issue by dnish** [kangax/fabric.js#4255]
## Version
2.0.0-beta.6

When setting the following dimension, I get a wrong scaled picture of my video:

```
     let width = video.videoWidth;
     let height = video.videoHeight;
     this.fCanvas.setDimensions({width,height});
```

<img width="531" alt="bildschirmfoto 2017-08-29 um 10 19 42" src="https://user-images.githubusercontent.com/7636313/29811490-f2ad89d0-8ca3-11e7-9db4-3bc7dfb8b8e7.png">

The CSS values doesn't match with the object attributes. Our video image has a wrong aspect ratio. When we use the following native code, everything works fine:

```
       var video = $("#cameraVideo").get(0);
        var canvas = $("#snapshot").get(0);
        var ctx = canvas.getContext('2d');


        var width = video.videoWidth;
        var height = video.videoHeight;

        $("#snapshot").attr({width: width + "px", height: height + "px"});
        ctx.drawImage(video, 0, 0, width, height);
```

**Comment by asturur** [comment]
you are probably working on an hdpi screen.
Try to disable retina scaling from fabric or try to post a failing fiddle explaining what is wrong
