### ISSUE TITLE
Official way for creating and submitting Demos?

### ISSUE THREAD

**Issue by sandor** [kangax/fabric.js#4256]
Is there an "oficcial" way to creat and submit a demo? Did not found anything related to this here in the repo... 

Meanwhile I just copied one of the demo pages and edited the content in a way I suppose that it "should" be working.

Copy and Paste Demo for v. 2.x – I left the Group and Ungroup features from my original Fiddle inside. I think it is relevant to show/demo that grouped objects are also copied and pasted as they should.

See a Gist with the edited HTML content:

https://gist.github.com/sandor/b6bbdcf2bfdedb5c0d61149b74ed8097

See the original Fiddle:

https://jsfiddle.net/sharksinn/wta4pdpz/2/

**Comment by asturur** [comment]
the only way is to make the website run on your pc and try the demo and open a PR on fabricjs.com

on what operating system are you?

**Comment by sandor** [comment]
I am on OSX. But: do I am missing something? Are the files for the website in this repository? Sorry for ignorance!

**Comment by asturur** [comment]
so from ```github.com/kangax/fabricjs.com``` start your fork.

on your osx clone your new repo with the address github provides you.

once cloned you should be in the gh-pages branch. try to run the command ```jekyll serve``` this should start a local server with a copy of the website.

at that point there is a demos folder and a _posts subfolder where you can add a demo starting from another.

**Comment by sandor** [comment]
I have cloned the repo and added a new demo HTML file in posts>demos>_posts
Also added a prview png in site_assets folder with the same name like the html file

Have not tested the files but should be working: I can not use jekyll on my system – would have to install all the ruby stuff that I am not using and I really not know...

sorry for asking this, but I don't know how to create a Pull Request. The first time I am doing this. Usually I am working with Github Desktop on my own repository. When I am trying to create a Pull Request I am redirected to compare my changes. I can commit my changes but can not pull them....

**Comment by asturur** [comment]
if you move back to github.com on your clone, a button 'new pull request' should do it for you.

the ruby stuff was sort of super easy to install on mac. and coming from windows i see the system does not suffer from being trashed from installing things.

Did you start from a github.com clone?

**Comment by sandor** [comment]
Yeah, I started from a github.com clone...

I think now I have done something stupid and created a new Branch "New_Demo" :-(
But I can start again from scratch by cloning out again from github... Should I? And thanks again for your time!

I'll try that ruby stuff later.

**Comment by asturur** [comment]
![screenshot_20170829-130235](https://user-images.githubusercontent.com/1194048/29817978-71cad1b2-8cba-11e7-89c8-3b5fbb785975.png)

if you forked fabricjs.com fron github it should appear in your repo list.

once yoir fork is there is easy to share PRs

**Comment by sandor** [comment]
I just cloned the project and made my additions in the local folder... Do I must to fork the project and not clone it (sorry again for all this stupid questions!!!)?

BTW: I have installed jekyll now. The webserver is running fine locally. Are there any additional files that I have to edit to make my demo appear on the demos page?

**Comment by asturur** [comment]
it should appear automatically.

i ll try to check it later

**Comment by sandor** [comment]
OK. Thanks! I think I have managed now to make my first pull request :-) Thanks for patience!

**Comment by ncou** [comment]
after group or ungroup, is the call to "requestRenderAll()" necessary ? a "renderAll()" could be enough, no ?

**Comment by asturur** [comment]
generally for user facing apps, requestRenderAll is the suggested method.
if you are doing a batch processing for some file output you still use renderAll.

we moved this discussion in the PR in fabricjs.com let s keep it there.
