### ISSUE TITLE
Brightness not working on 2.0.0 beta

### ISSUE THREAD

**Issue by nitsbikash** [kangax/fabric.js#4260]
Hi, in new version Brightness is not working can't find why not working. Here is my code

 ```
       var obj = canvas.getActiveObject();
        obj.filters.push(new fabric.Image.filters.Brightness({
            brightness: parseFloat(20)
        }));
          
        obj.applyFilters();
        canvas.renderAll();
```
I have tried last release version 1.7.17 brightness is working fine. But on this version Gamma is not working it is showing error:-

Error: fabric.Image.filters.Gamma is not a constructor

Please help me on this, which version I should use?

**Comment by asturur** [comment]
In version 1.7.17 gamma filter is not available.

Brightness is probably not working because you are adding 20 to it. i could be wrong but the docs says that brightness move from -1 to 1.
