### ISSUE TITLE
ActiveSelection + single click => strange behaviors with borders & corners

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4261]
Hi,

I got a strange behaviors, perhaps related to the ticket : https://github.com/kangax/fabric.js/issues/4218

If i go to the following page :
http://fabricjs.com/manage-selection

And ;
- select all the shapes with my mouse.
- I do a single click on the top left part of the selection, without moving the mouse (just a single click).
- The border & corners got half transparent => as if i was going to move the objects.
=> From memory, the borders and corners changes only when you let the mouse down pressed (=> as when you want to move the objects).

Expected behaviors :
- The corners and borders should go back to "normal" when you release the mouse button.

Hope i am clear enough.
Cheers.

**Comment by asturur** [comment]
mmm i can't replicate.

**Comment by ncou** [comment]
Hum i can't reproduce it again :( but my chrome build version increased.
I will try in another browser and update the ticket later.

**Comment by ncou** [comment]
ok, can't reproduce it. closing the ticket.
