### ISSUE TITLE
how to get an object z-index ?

### ISSUE THREAD

**Issue by zhishaofei3** [kangax/fabric.js#4266]
how to get an object z-Index ?

I use canvas.getObjects() to try get objects index

https://codepen.io/zhishaofei3/pen/KvboNo

````javascript
var canvas = new fabric.Canvas('c', {preserveObjectStacking: true})

  //红1 绿2 圆3 三角4

  var rect = new fabric.Rect({
    left: 100,
    top: 100,
    fill: 'red',
    width: 50,
    height: 50
  })
  canvas.add(rect)

  var rect2 = new fabric.Rect({
    left: 100,
    top: 100,
    fill: '#5FF00F',
    width: 150,
    height: 150
  })
  canvas.add(rect2)

  var circle = new fabric.Circle({
    radius: 50, fill: 'green', left: 100, top: 100
  })
  canvas.add(circle)

  setTimeout(function () {
    rect2.bringToFront()

    console.log(canvas.getObjects())
    //how to get current rect2 z-index ??
  }, 5000)
````

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
