### ISSUE TITLE
Lost of controls after grouping objects (in b6)

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4268]
Hi,

I got a strange behaviors with the latest b6 from master when i group a bunch of objects i lost the controls (no more interactions with the corner controls).

I can't reproduce it with the lib used on the official website (fabricjs.com), while both are tagged beta6.

Here are the 2 fiddle.

1) 
fiddle with the lib beta6 from the master branch from github.
step : select 2 objects, and click on the group button, then go to the top left corner => the cursor is missing [like when setCoords is not called]) :
https://jsfiddle.net/wta4pdpz/3/

2)
Here is the same fiddle with the b6 from the fabric.js website. => in this case the group work ok when you put your cursor on the top/left corner.
https://jsfiddle.net/wta4pdpz/4/

Tested with chrome 60.
PS : adding a setCoords after doesn't seems to enable again the controls. You need to deselect and select again the object.

**Comment by ncou** [comment]
@asturur In fact this behaviors looks like your comment on the previous b4 :
https://github.com/kangax/fabric.js/issues/4147#issuecomment-318825641

So perhaps it has been already fixed in the futur beta7 ?

**Comment by asturur** [comment]
if it works with the version on fabricjs.com it means it works good in latest code.
thanks.

**Comment by blobinabottle** [comment]
I still have the bug on the master.

**Comment by asturur** [comment]
let me recover from headache and check this and that new shadow bug.

**Comment by asturur** [comment]
i think this bug here is just about the fiddle.
