### ISSUE TITLE
new Group interaction coordinates have broken

### ISSUE THREAD

**Issue by khmyznikov** [kangax/fabric.js#4269]
## Version
2.0-beta6

## Test Case
http://jsfiddle.net/Da7SP/592/

## Steps to reproduce
Create some objects on canvas.
Wrap all to one Group.
Try to select and drag .

## Expected Behavior
I have next example of code http://jsfiddle.net/Da7SP/593/, it work good on 1.7.17.
But on 2.0 i can't select and move all of my object, interaction coordinates are broken, i see objects on right place but can't move it.

## Actual Behavior
I need to know how i can work around this issue or maybe you create new opportunity to select and move objects at once from code.

**Comment by ncou** [comment]
Can you explain a bit more ? you can't use selection in v2 of fabric.js ?
if it's that, the fact to create a group for selection has been removed in v2
http://fabricjs.com/v2-breaking-changes-2

**Comment by khmyznikov** [comment]
@ncou Only setActiveGroup and getActiveGroup removed. Group object still exist. In previous versions you can make a group from some of object and move it on canvas. So, how i can do it now? Iterate all objects one by one and set new coords?

**Comment by khmyznikov** [comment]
@ncou Thanks you for link, i got all what i need. The solution is:
`var selection = new fabric.ActiveSelection([rect1, rect2], {
  canvas: canvas
});
canvas.setActiveObject(selection);`
Thanks again!

**Comment by ncou** [comment]
Ha ok i understand.

There is multiple possibility,

Loop on the objects (looks like a clean solution to me)
http://jsfiddle.net/Da7SP/595/

Or create an active selection instead of a group and select, move, deselect
http://jsfiddle.net/Da7SP/596/
