### ISSUE TITLE
[Question] Shouldn't the "Object.setOption()" function return this ?

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4270]
Hi,

Most of the functions in fabric.js could be chained, is that normal the "Object.setOptions()" doesn't return the instance of the object ?

This could serve mostly when there is a change of the coords top/left using the setOptions function, and we can chain the call to setCoords for example.

What do you think ?

**Comment by asturur** [comment]
in one of the latest commits i digged into it.

setOptions is a functions that call many other functions.

the set method is chainable, take an object as input, i would just use that.

**Comment by ncou** [comment]
ok, it was just a possible shortcut, but if there is multiple functions behind it's a big risk to try to change this.
Yes the set method is chainable, it was just a question for a possible homogenisation.

Thanks for the answer.
