### ISSUE TITLE
Polygon point update issue

### ISSUE THREAD

**Issue by sreekanthssr** [kangax/fabric.js#4272]
Hi,

I am facing and issue after dynamically updated point of polygon. When i move, scale or rotate i am calculating the point using transform matrix, then i reassigning the point to the polygon. After that the bounding box and the polygon shape in different position.

Kindly help me in this issue 

Regads
Sreekanth

**Comment by asturur** [comment]
this case fit in stackoverflow.

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

**Comment by asturur** [comment]
feel free to post your question link here.
document the question with code and a premade stackoverflow snippet

**Comment by sreekanthssr** [comment]
Hi,

Thanks for your reply Asturur.

Please check the URL [demo](https://jsfiddle.net/sreekanthssr/swcjzsea/4/) of my issue. 
One solution for this issue to recreate the polygon. But in my case i am binding so many event on polygon so i need to again binding those event. 
So can you please suggest any anther way to do this.

Regards
Sreekanth S

**Comment by asturur** [comment]
i would try to help on stackoverflow.com so everyone can learn from it
