### ISSUE TITLE
There is no way to catch an error from loadSVGFromURL if svg file contais errors

### ISSUE THREAD

**Issue by HATyCEHKA** [kangax/fabric.js#4278]
There is no way to catch an error from loadSVGFromURL if svg file contais errors (for example, font-weight="400"). Callback function is not called! Error only appears in console.

## Version
2.0.0-beta.3

## Test Case
http://jsfiddle.net/emhvz1sw/1/

**Comment by asturur** [comment]
Can you provide that SVG not encoded so that i can see from what the error come from? it should be possible to catch it an call the callback with 0 objects or something else.

**Comment by HATyCEHKA** [comment]
Callback with 0 objects will be good.
You can write to any svg with text element font-weight="400" and get the
error.

**Comment by asturur** [comment]
I was sure i answered this, something went wrong.
I can load the SVG just fine with no errors.
Can you give me a way to get this error?

**Comment by HATyCEHKA** [comment]
I use version 2.0.0-beta.3.
You can see error in jsfiddle in console http://jsfiddle.net/emhvz1sw/1/
![image](https://user-images.githubusercontent.com/26141774/30152235-275d091c-93bb-11e7-8d7b-b0c26d2ab6d9.png)

**Comment by HATyCEHKA** [comment]
Problem is that callback function is not called, but not the error itself.

**Comment by asturur** [comment]
ok this errror has been solved long ago between betas.
fontWeight is converted to string and then lowerCased.

Still is true there is no try / catch managment, but errors should not happen in this way.

We can manage errors from http request or similar.

**Comment by asturur** [comment]
please use latest beta. ( try to push beta7, today )
