### ISSUE TITLE
draw image map from cords fabric.js

### ISSUE THREAD

**Issue by scionable** [kangax/fabric.js#4280]
My task is to get an image from an input and draw it on canvas. Then the user puts dots in the image that are connected in a fugure, I so understood what it calls a polygon. The task is to create an image map by points, and highlight these areas when hovering. What i have at this time, oh forgot to say i'm using fabric.js
` /*TAKE ELEMENTS FROM PAGE*/
let input       = document.getElementById('file-upload');
let label       = document.getElementById('file-upload-btn');
let btnDel      = document.getElementById('btn-del');
let cursorCords = [];

/*INITIALIZE FABRIC CANVAS*/
let canvas = new fabric.Canvas('canvas');
canvas.setWidth(0);
canvas.setHeight(0);

/*ADD COMPLECX FOTO FROM INPUT ON PAGE START*/
function addFoto(e) {
    let reader = new FileReader();

    reader.onload = function (event) {
        let imgObj = new Image();

        imgObj.src = event.target.result;

        imgObj.onload = function () {
            let image = new fabric.Image(imgObj);
            canvas.setWidth(858.67);
            canvas.setHeight(image.height);

            image.set({
                left: 0,
                top: 0
            });
            canvas.setBackgroundImage(image);
        }
    };

    label.style.display = 'none';
    reader.readAsDataURL(e.target.files[0]);
    canvas.getObjects();
    canvas.renderAll();
    console.log(canvas.getObjects())
}

input.addEventListener('change', addFoto);
/*ADD COMPLECX FOTO FROM INPUT ON PAGE END*/

/*DEL FOTO BUTTON START*/
function deleteFoto() {
    label.style.display = 'block';
    input.value = '';
    canvas.clear().renderAll();
    canvas.setWidth(0);
    canvas.setHeight(0);
}

btnDel.addEventListener('click', deleteFoto);
/*DEL FOTO BUTTON END*/

/*GET MOUSE CLICK COORDS START*/
function getMouseCoords(event) {
    let pointer = canvas.getPointer(event.e);
    let posX = Math.floor(pointer.x);
    let posY = Math.floor(pointer.y);
    cursorCords.push(posX);
    cursorCords.push(posY);
    console.log(cursorCords);
}

canvas.on('mouse:down', getMouseCoords);
/*GET MOUSE CLICK COORDS END*/`

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
