### ISSUE TITLE
Can't edit IText text from bootstrap 3 modal on firefox

### ISSUE THREAD

**Issue by janoonaj** [kangax/fabric.js#4281]
## Version
2.0.0 beta 4
Firefox 55.0.3 (32-bit) - Windows 10

## Steps to reproduce
Launch bootstrap3 modal window with a canvas on it. 
Add IText
Try to edit text

## Expected Behavior
Keys of the keyboard should write when text is selected.

## Actual Behavior
Text can be selected, but when keys are pressed there are no changes on text. If you press back button, it goes to the previous webpage (like loosing focus).

**Comment by asturur** [comment]
https://github.com/kangax/fabric.js/issues/3695

We already discussed the thing here.
Sadly the bootstrap modal is managing the keystroke for you. the textarea is appeneded outside the modal and is not getting the keystrokes.
Can you understand if the hiddenTextarea is focused or not?

**Comment by asturur** [comment]
we can keep discussion there anyway. no need for a duplicate.

**Comment by wgerro** [comment]
Remove `tabindex="-1"` in html class `modal fade`, it is should working

from:
`<div class="modal fade" id="exampleModal" **tabindex="-1"** role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">`

to:
`<div class="modal fade" id="exampleModal" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">`
