### ISSUE TITLE
Problem with the function to split internal Text lines

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4282]
Hi,

There seems to have a bug in the "_splitTextIntoLines()" function who doesn't handle correctly the line break and the delete key press.

I use the array in the "_textLines" var who is calculated by the previous function, and the content is not correct about the number of lines (the size of the array should be equals to the number of lines)

http://jsfiddle.net/zukJh/38/
Steps to reproduce :
- Edit the textbox and put the selection on the end of the text.
- Press the space bar, to force the fire of the "text:changed" event to display in the console the content of the var "_textLine".
- In our case, the array displayed in the console show the number 3 (because we have 3 lines).
- Press enter => the console display "3 elements in the array" it's wrong there should be 4 elements.
- Press enter again => the console display "4 elements in the array" it's wrong there should be 5 elements.
- Press delete => the console display "5 elements in the array" it's wrong there should be 4 elements.

Perhaps a problem in the regex to detect line breaks ?

**Comment by blobinabottle** [comment]
Maybe related but I noticed a bug when you try to reach the end of a line with the mouse:
https://cl.ly/2M3G3X3D460t
It was ok in fab 1.7.x

**Comment by ncou** [comment]
Perhaps, i also experienced a problem like that when there is line break, some time when you want to select the line, the cursor go on the line below. And in some rare cases the caret stop to blink.

**Comment by asturur** [comment]
So when text:changed fires, the lines are not updated yet.
You could update them in your code running
```
      if (this._shouldClearDimensionCache()) {
        this.initDimensions();
      }
```

In this way at the next render, this would not happen again ( since you just did it )
You would just execute something earlier and not do it twice.

**Comment by asturur** [comment]
trying if i can quickfix the cursor, i was aware of it, then i forgot.

**Comment by Soham03** [comment]
I am still facing this error in fabric js version 5. When we add text inside fabric js textbox at line end, after pressing spacebar the cursor moves to the next line, during this time the object.textLines array length is getting updated and displaying the number of lines properly but object.styles array length is not updated properly. It is unable to recognise the line break when cursor moves to next line using spacebar instead of enter key.
