### ISSUE TITLE
fromObject error on loadFromJSON by loading rectangle shape

### ISSUE THREAD

**Issue by darxx** [kangax/fabric.js#4284]
## Version
2.0.0-beta6 and v1.6.7 has same issues

## Test Case
http://jsfiddle.net/darxx/7qqvcvtd/1/

1.6.7
 Cannot read property 'async' of undefined error

## Steps to reproduce
Test case link is best example

## Expected Behavior
rectangle to be drown 
## Actual Behavior
rectangle is not drown error message -  Cannot read property 'fromObject' of undefined

**Comment by asturur** [comment]
you have a type 'rectangle' that does not exist.

is type 'rect'
