### ISSUE TITLE
charSpacing doesn't seems to respect the steps

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4285]
Hi,

In my app, i got a slider to increase/decrease the space beetween characters. There is a little jump when the value is === 0.

As you can see in this fiddle, from top to bottom the text size should be incremental.
But the text with the charSpacing = -1 is longer than the text with charSpacing= 0 (text in the middle).

http://jsfiddle.net/tQCTd/76/

From my understanding the char are draw separately when the is a charSpacing value, perhaps this behaviors come from this.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/30150685-a750b81c-93ac-11e7-972f-8502e4545db4.png)

**Comment by asturur** [comment]
Seems ok to me. There are combination of chars that make this wrong ( like a sequence of ones )

**Comment by ncou** [comment]
Here is what i see : 
![image](https://user-images.githubusercontent.com/16743322/30152793-a3654cba-93b4-11e7-89ce-6a3c6f51c370.png)

I got the problem even with a word, i used a sequence to enlight the behaviors.

**Comment by asturur** [comment]
This can be an issue between different implementation of canvas. hardly i can do something about it.

**Comment by asturur** [comment]
The real problem is that with charSpacing 0 and all black, we render all the text in one pass and the browser do what it want to do.
With charspacing set, we render one char at time, and result my differ.

**Comment by ncou** [comment]
yes it's what i have been thinking when reading the code.

There doesn't seems to have the same behaviors between differents browsers.

Here is what i got with IE11 :

![image](https://user-images.githubusercontent.com/16743322/30153049-79b18f40-93b5-11e7-921b-dcb691e71268.png)

PS : Chrome & FF behave the same. I am under windows7.

**Comment by ncou** [comment]
If there is nothing to do, let's live with it :)
