### ISSUE TITLE
Video is not rendered inside group

### ISSUE THREAD

**Issue by solomax** [kangax/fabric.js#4286]
## Version
1.7.17

I'm trying to create video player using fabric.js.
First task is to create play/pause button.
Change button style on mouseover is not working due to #4115 :(
Somehow video is not being rendered inside group :(

## Test Case
https://jsfiddle.net/solomax666/r2nuv845/

## Steps to reproduce
* Run jsfiddle above
* press 'Play' button
* wait couple of seconds

## Expected Behavior
Video is being played on canvas

## Actual Behavior
There is the sound but video frames are not being updated
Frame-by-frame animation can be created by continuously clicking play/pause button

**Comment by solomax** [comment]
Additional question: is it possible to display `poster` of video tag?

**Comment by asturur** [comment]
https://jsfiddle.net/r2nuv845/7/

The problem is that you should disable the cache for that Group containing video and buttons.
The Group will change every frame and every render, so there is no reason to keep it cached.
(i added objectCaching: false to group creation)

**Comment by asturur** [comment]
What is poster of video tag?

**Comment by solomax** [comment]
Thanks!

Here is the description of the poster: https://www.w3schools.com/tags/att_video_poster.asp

**Comment by solomax** [comment]
I just have checked, adding `objectCaching: false` fixes playback issue, but play/pause button stops working :(
With caching it correctly changes visibility of inner objects. With ching off this button is always 'play' and never 'pause' :(

**Comment by solomax** [comment]
OK, play/pause issue is solved by disable caching for both groups
Thanks a lot for helping with this!

**Comment by asturur** [comment]
so poster is an attribute.
You have to parse it and display it by yourself as an image. There is no real video support in fabricjs.

**Comment by solomax** [comment]
OK, Will try. Thanks a lot!
