### ISSUE TITLE
 about the color of the fabric.Image object

### ISSUE THREAD

**Issue by Jsonzhuli** [kangax/fabric.js#4289]
## Version
all
## Steps to reproduce
load a pure black(#000000) Image Object.  
contrast the colors  of the Image Object and image
## Expected Behavior
Object and image have the same color
## Actual Behavior
the color of the Image Object has changed(#010001)

**Comment by asturur** [comment]
Could you please make a fiddle? i do not get what is the problem in this way.

**Comment by Jsonzhuli** [comment]
fiddle  https://jsfiddle.net/uv0drtpv/1/

**Comment by Jsonzhuli** [comment]
My English is not very good.   sorry

**Comment by asturur** [comment]
@Jsonzhuli  how do you check the color of the image?

**Comment by Jsonzhuli** [comment]
@asturur just use color picker

**Comment by asturur** [comment]
what color picker from where? i have chrome or firefox, then?

**Comment by Jsonzhuli** [comment]
chrome color picker.  pick the color of the image and image object. compare the RGB values of them

**Comment by asturur** [comment]
i have no idea where is it.
How do i open it?

**Comment by Jsonzhuli** [comment]
open chrome developer tools(F12). select elements with color styles and click to open color picker!
sample:
[http://aimg.edobee.com/0c9b2aea4d604ceea3641505ba87ce07/de72056093a911e795345fb3bab92d26.png](url)

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/30154980-e495b812-93bb-11e7-9c21-412d54128ae2.png)

does not happen in chrome.
Be aware that may be:
 - your screen color profile
-  your browser and retina scaling ( the canvas is downsized to be in a smaller area, and so image is resampled on screen )

Fabric has no code to render the image other than drawImage. Nor it can change pixel values without use of filters.

Definitely a problem between the browser and the screen but i do not think we can attribute it to fabricjs.

**Comment by Jsonzhuli** [comment]
@asturur I see,  thank you very much!
