### ISSUE TITLE
Objects have no controls and disappear after "ungrouping"

### ISSUE THREAD

**Issue by WillemStaels** [kangax/fabric.js#4290]
## Version
1.7.7

## Test Case
https://jsfiddle.net/WillemStaels/w9j3qwg0/3/

## Steps to reproduce

- Create group with objects
- "Ungroup" and add objects back to canvas

## Expected Behavior

- Ungrouped objects should act like normally added objects
- Objects should not disappear

## Actual Behavior

- When trying to select one of the objects, the controls are not showing
- When trying to make a selection (drag a square around the circles), the selection box + controls show again
- When deselecting (clicking on the canvas), all the objects become invisible, however the are still there (try to make the same selection again while dragging)
- After rotating, scaling or any transformation it looks like "Expected behavior" is back for the single object.

**Comment by asturur** [comment]
The problem lies in how you are ungrouping.
Please since here we support latest 1.7.17 or version 2 beta, could you move this question on stackoverflow?

**Comment by WillemStaels** [comment]
Ok no problem, just posted it on SO. Is there any tutorial or guide that I've missed? I already read all of the docs multiple times....

**Comment by ncou** [comment]
Here you have an example about grouping/ungrouping made by sandor.

https://jsfiddle.net/wta4pdpz/14/

**Comment by asturur** [comment]
just give me the SO link, i ll reply there.

2017-09-06 15:43 GMT+02:00 ncou <notifications@github.com>:

**Comment by WillemStaels** [comment]
https://stackoverflow.com/questions/46076682/unable-to-ungroup-with-fabric-js

@ncou with the "master" version I can get it working like the example, but not on 1.7...

**Comment by asturur** [comment]
https://stackoverflow.com/questions/46076682/unable-to-ungroup-with-fabric-js/46077425#46077425

I answered.
Thanks for the clean question with the snippet. Makes things faster.

This issue highlighted a small bug i think.
