### ISSUE TITLE
Error in the Group.toObject() after a cloning of the ActiveSelection object.

### ISSUE THREAD

**Issue by ncou** [kangax/fabric.js#4291]
Hi,

There is an error in the copy/paste demo (https://jsfiddle.net/wta4pdpz/14/) there is an error in the toObject for the group object (perhaps a reference from the cloning). Not really sure why i can't check the code of the group object for the moment.

Steps :
- Select 2 objects.
- Press copy and paste => the object is correctly pasted.
- Deselect the object
- Press paste button => error in the toObject() function for the group object.

**Comment by asturur** [comment]
this belongs to fabricjs.com where we have that PR open. Let's not smash all here or i will not be able to handle it.
I'll review that demo today.
