### ISSUE TITLE
Removing all elements from specific layer of canvas

### ISSUE THREAD

**Issue by tnguyen94** [kangax/fabric.js#4292]
Hello, is it possible to remove all of the elements from a certain layer of the canvas? I think this involves something with z-indices but I'm not completely sure. My application is constantly adding fabric.Image elements onto the canvas one-by-one, next to each other. Eventually, the number of images grows too large and the browser runs out of memory and crashes. I'd like to control the amount of memory used by removing the entire bottom layer of items from the canvas at certain points in time. Is what I'm looking to do feasible with the current library?

**Comment by asturur** [comment]
fabricjs has no layer concept.
It mostly depends on how are you stacking those images.
You say next to each other, but then you say `bottom layer`.
Does not feel right.

**Comment by tnguyen94** [comment]
Sorry, let me clarify a bit more. Each image I am adding to the canvas is a piece of a larger image. Say each piece of the larger image is represented by a single number. My application will load the images one-by-one like this on the canvas:
1 2 3
4 5 6
7 8 9

Once I receive a new large image to display, I will add its pieces to the canvas in the same way:
10 11 12
13 14 15
16 17 18  
Image 10 will overlap image 1, image 11 will overlap image 2, and so forth. My question is how do I remove images 1-9 once I have overlapped them with images 10-18? Does this clarify at all?

**Comment by asturur** [comment]
I think this is an application problem you can solve in many ways.

You can assign to props to an image, layer and tile.

When layer X, tile Y is loaded and placed on canvas, search for the canvas objects, identify all the objects that have tile equal to Y and layer lesser than X and remove them.

I think is an ok way to do it, and not something that fabricjs should solve as a library.
