### ISSUE TITLE
Mouseup events are duplicated in case preserveObjectStacking is ON

### ISSUE THREAD

**Issue by solomax** [kangax/fabric.js#4296]
## Version
1.7.17

## Test Case
https://jsfiddle.net/solomax666/r2nuv845/

## Steps to reproduce
1) run the fiddle
2) push 'Start' button on video
3) push 'Pause' button on video

## Expected Behavior
Video should pause

## Actual Behavior
Video continue playing

With debugger I find out on mouseup is being called twice due to mouseup target gets duplicated. This is not the case when preserveObjectStacking is OFF (line 2 of fiddle is commented out)

**Comment by asturur** [comment]
i see the bug in findTarget.
Before i get mad reading all your fiddle, can you explain me how the things are grouped in your use case:

Video + controls are a group?

**Comment by solomax** [comment]
There are 2 groups:
One is `Play button`: circle, triangle and 2 rects
Another one: everything else: poster image, video, and 2 rects to display progress

**Comment by asturur** [comment]
the 2 groups are grouped togheter?

**Comment by solomax** [comment]
Yep, Main group, contains 'Play' group

**Comment by solomax** [comment]
I can try to 'clean up' the fiddle. The issue can easily be debugged if you put breakpoint into 'mouseup' handler

Surprisingly 'mousedown' seems to be not affected

**Comment by asturur** [comment]
i found the problem, i just needed the situation to write a test so that
the bug can be catched in future

**Comment by solomax** [comment]
I'll try to simplify the fiddle and will let you know

**Comment by asturur** [comment]
is ok i have the info i need.

**Comment by solomax** [comment]
OK, Thanks!
Please let me know if there is anything I can do

**Comment by asturur** [comment]
Well to be honest 100% i did not try the solution. but i m confident it works

**Comment by solomax** [comment]
I have applied your patch locally, seems to work as expected
Thanks a lot!

**Comment by solomax** [comment]
Was able to build it :)
Thanks a lot for the quick fix!
