### ISSUE TITLE
Mirror effect on a modification's picture don't work every time

### ISSUE THREAD

**Issue by BezMaster** [kangax/fabric.js#4301]
Hi,
When i use the selection tool in the top right corner of a picture and i move it in all directions. Sometimes the pictures is inverted and sometimes not.

With this sample we can repoduce the bug easily.
http://fabricjs.com/bounding-rectangle

Do you know this behaviour ?

Best regards Seb

**Comment by asturur** [comment]
Hello @BezMaster is a bit unclear what are you asking.
Please if you think you found a bug, give a easy way to replicate it trought a fiddle.

**Comment by BezMaster** [comment]
With the following sample on fabrics js you can reproduce it easily.

http://fabricjs.com/bounding-rectangle

Step to reproduce
1) Grab the selection tool in the top/right corner of the squirrel picture.
2) Drap it under the bottom left corner and don't release your click.
3) Repeat the movement sereral times.

Defect:
Sometimes the squirrel is displayed as a mirror. And sometimes not.

Do you see what i mean ?

**Comment by asturur** [comment]
yes probably a bug in some interaction code.

**Comment by asturur** [comment]
Fixed!

**Comment by BezMaster** [comment]
Thanks a lot for your reactivity ;). From which version can i get this fix ?

**Comment by asturur** [comment]
This is in 1.7.19 out now
