### ISSUE TITLE
How to rotate image  smoothly

### ISSUE THREAD

**Issue by chandandas** [kangax/fabric.js#4304]
Hi
I have an image and rotate it using setAngle method but it the image jumps between points. This does not look good. How can rotate the image smoothly.

Regards,
Chandan

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

Please on stackoverflo prepare a fiddle, with your rotation code, explain correctly why it looks bad.
Post your question link, i will help then.
