### ISSUE TITLE
[2.0] Svg_parser: Render incorrect postion when load from URL

### ISSUE THREAD

**Issue by duyhung85** [kangax/fabric.js#4305]
Hi,

I'm trying to parse SVG from URL but some of the objects render in incorrect position. Here is one of the example, you can see the background image is misplaced:

[https://jsfiddle.net/duyhung85/cwwbnowb/](url)

When I test it on fabricjs kitchen-sink with SVG string , it seems to work though.

**Comment by asturur** [comment]
https://jsfiddle.net/cwwbnowb/1/

you should not remove transformMatrix on your own.
Is a process made from fabricjs svg import.

**Comment by duyhung85** [comment]
Thank you!
