### ISSUE TITLE
Shadow bug with group on zoomed canvas.

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4309]
## Version
2.0.6

## Test Case
https://jsfiddle.net/L16kzxzh/2/

## Steps to reproduce
Select all object then group them. And ungroup them. You see the shadow offset/blur changing (related to zoom on canvas)

## Expected Behavior
The zoom should have no impact on shadow offset/blur when grouping ungrouping.

## Actual Behavior
When you ungroup, the shadow offset and blur seems related to the zoom set on the canvas.

**Comment by asturur** [comment]
good find! this needs a fix.

**Comment by asturur** [comment]
https://jsfiddle.net/L16kzxzh/4/

with actual latest code is fixed.
(copy pasted whole lib in the fiddle, very slow)

**Comment by blobinabottle** [comment]
Awesome!
