### ISSUE TITLE
Canvas updates itself only on "mouseup"

### ISSUE THREAD

**Issue by kpudlik** [kangax/fabric.js#4321]
## Version
1.7.19

## Test Case
https://jsfiddle.net/qejsvc5o/1/

## Steps to reproduce
Move red rectangle, then try to scale down red rectangle.

## Expected Behavior
I want black rectangle to fill the gap between red rectangle and top canvas border. It works correctly when I move red rect:

![moving](https://media.giphy.com/media/xT9IgAeHYTHPZNXzna/giphy.gif)

It should work in the same way for scaling red rectangle down. Once red rectangle is resized then black rectangle should immediately fill the gap.

## Actual Behavior
The correct result is showed only after `mouseup`. During `mousedown`calculations are broken.

![resizing](https://media.giphy.com/media/l378kwwAgRORzAXUk/giphy.gif)

**Comment by neopheus** [comment]
Hi,

It's a cache problem
Fix : https://jsfiddle.net/qejsvc5o/2/
