### ISSUE TITLE
Flip broken in beta 7

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4325]
## Version
2.0 beta 7

## Test Case
https://jsfiddle.net/5cg75two/3/

## Steps to reproduce
Scale the triangle very small. With lockScalingFlip set true, it's not working: the object disappear at some point.

## Expected Behavior
The object should stay like in beta 6 with handles visible.

## Actual Behavior
The object disappear when really small. Or sometimes jump in top left corner.

**Comment by asturur** [comment]
I noticed 15 minutes after release. Combination of 2 different fixes.
Going to fix it now.

We really need a test system that include mouse interaction, at least simulated

**Comment by blobinabottle** [comment]
Good idea but this kind of test is not easy to implement I guess...

**Comment by blobinabottle** [comment]
Seems the bug is still there. We are using the last update merge https://github.com/kangax/fabric.js/pull/4339  
I don't know how to get this version on JS fiddle to test and be able to show you.

**Comment by asturur** [comment]
i ll put it on fabricjs.com and we can try there

**Comment by asturur** [comment]
http://fabricjs.com/kitchensink  i added the latest build, included the lockscalingflip button. For me the problem is not there. Please have look

**Comment by blobinabottle** [comment]
Indeed. That's weird. I'll check what we do wrong. Sorry for taking your time about this!

**Comment by asturur** [comment]
no worries, better to be sure i fixed it.

**Comment by melvynhills** [comment]
We were using the master branch at the latest commit, but without building from source so it was actually stuck at the release tag. It's indeed fixed, all good 👍
