### ISSUE TITLE
free drawing is moved after mouse up

### ISSUE THREAD

**Issue by russon77** [kangax/fabric.js#4329]
## Version
2.0 beta

## Test Case

sorry, it only happens within the site. i can host the bugged full application, if that's acceptable.

## Steps to reproduce

1. free draw on canvas
2. note location of drawing

## Expected Behavior

drawing is located where it was drawn.

## Actual Behavior

drawing is moved half of its width left and half of its height up. the wider the line, the more left and likewise for height and up.

i'm looking for any ideas or suggestions to resolve this, it's the base line fabric canvas with drawing enabled. canvas is set to full screen height and width in js before initialization fabric.

**Comment by asturur** [comment]
i think you are not on latest beta7. because it has been fixed.
Can you replicate on freedrawing of fabricjs.com?

**Comment by russon77** [comment]
@asturur thank you so much!!!! it's fixed now 🎆
