### ISSUE TITLE
setDimensions is async?

### ISSUE THREAD

**Issue by dnish** [kangax/fabric.js#4330]
## Version
Latest 2.0 beta

Hey,
I'm having the following function:

```
    formatCanvas(source,width,height) {

        let ctx = this.fCanvas.getContext('2d');

        this.fCanvas.setDimensions({width,height},{backstoreOnly:true});
        ctx.drawImage(source, 0, 0, width, height);



        return this.fCanvas.toDataURL("image/jpeg");

    },

```

When I execute the function, I only get a black screen after rendering. When I add 

```
setTimeout(() =>  ctx.drawImage(source, 0, 0, width, height),3000);
```

the image gets added properly.

**Comment by asturur** [comment]
so i have no idea why are you drawing with drawimage an image outside a fabric context.

That is not the right approach.

Anyway setDimensions has an async renderAll, to avoid it call canvas.renderAll() right after the setDimensions, this will cancel the async and execute sync.
