### ISSUE TITLE
Add or prompt a similar function of the native canvas CanvasRenderingContext2D.isPointInPath()

### ISSUE THREAD

**Issue by VictorV96** [kangax/fabric.js#4333]
Hello! I can not find a solution for a long time. I have a path (for example "M126,38 ....."), and objects that are added dynamically. Everything works fine, but I need that when moving objects inside the path, the edge of the object should not go outside the path. I used the solution ctx.getcontext ("2d") and it was done with clip (path2d ("M126,38 .....")). In principle, I'm happy, but there is no way to move and zoom in ... And on a smartphone this method does not work correctly. I tried using canvas.findTarget (e.e) while moving the object, but it does not work well at certain intervals ... and it tracks the mouse cursor, and the object inside the path goes up to 95% in all directions.

**Comment by asturur** [comment]
If this is a feature request, please be more specific on the use cases and how do you think it could solve some issues.

As it stands now this looks like an help request and cannot be handled here.

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
