### ISSUE TITLE
can we use 'setOverlayImage' for fabric shapes?

### ISSUE THREAD

**Issue by monis01** [kangax/fabric.js#4334]
I am not able to find the solution don't know if whether possible with fabric or not? basically I have two shapes one outer shape and another bleed shape but smaller size. shapes can be (circle, triangle, square, , polygons etc.) all I want :
1. Make bleed layer at the top, so that I can move objects and shows bleed shape boundary over that object.
2. Clip the whole region around outer shape and to save it into DB  (export, import) for future versions of (edit, save ) products.
I have been able to achieved that but problem comes when I am doing 'canvas.toDataURL()' thing all get misplaced on canvas with introducing one more extra shape.
Is it possible to overlay shape(any shape instead of image) on top without things getting messed up when I have to export and show it again on canvas?
PS: my original question 
[stackoverflow](https://stackoverflow.com/questions/46298252/how-can-i-manage-to-move-object-between-various-layers)
I got similar problem [fiddle1](https://jsfiddle.net/0LrxLyLj/3/) circle -> clear - > export.
Is it possible with `setOverlayImage` or some other way already in fabric and I am picking up wrong fruit from the basket?
Thanks

**Comment by ncou** [comment]
you can create a shape using fabric.js and use it as parameter for the "setOverlayImage" function.
Not only an image.

I think the "setoverlayimage" function will be renamed in the futur relase.
