### ISSUE TITLE
Text losing its style

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4335]
## Version
2.0 beta

## Test Case
https://cl.ly/1Z3k3c2k3v2q

## Steps to reproduce
Select part of a multi-styled text with the mouse. Replace it with a longer word, some other part of the text will lose its format.
It's on demo kitchensink, but also in beta 6 or 7 (and I think it's also like that in 1.7.x).

## Expected Behavior
Only change text that are selected.

Thanks for your support!

**Comment by asturur** [comment]
urgh this is bad.
I hoped we were out of this style mess forever.

**Comment by asturur** [comment]
So it looks like it depends from the speed you write.

![testp](https://user-images.githubusercontent.com/1194048/30739222-dc4c6bf6-9f8c-11e7-9dd6-11ad5d879a0a.gif)

To me if i write very fast i manage to make it happen, at different lengths of text.

If i write slow, it never happens.

This let me thing is sort of managing of the oninput event or also the async requestRenderAll.

**Comment by asturur** [comment]
Can you confirm that the behaviour is semi random?

**Comment by blobinabottle** [comment]
True it seems related to the speed you're typing.
