### ISSUE TITLE
iText - Event listeners are not binded on hiddenTextArea on full screen mode on IE11

### ISSUE THREAD

**Issue by anubhav-aggarwal129** [kangax/fabric.js#4337]
## Version
2.0.0-beta5

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Steps to reproduce
Browser: IE11
Mode: Full screen canvas
1. Add iText with default text.
2. Click on text to edit.
3. It call initHiddenTextArea() function where it attaches all listeners
4. Try adding / editing text.

## Expected Behavior
onKeydown() or onKeyUp() event should be fired as soon as the key is pressed

## Actual Behavior
No event is fired. I've defined a global event handler on canvas, the event is propagated to that handler instead of specific event handlers mentioned in initHiddenTextArea()

**Comment by asturur** [comment]
the hiddenTextarea is not attacched to canvas.
So should not interfere.
Can you create a fiddle to show it?

**Comment by anubhav-aggarwal129** [comment]
Please take a look at the live example:
1. On IE11, go to https://meet.stage.greenjobinterview.net/join/liveMeeting?id=103514 and add any name to enter the room.
2. Click on the second icon from left above 'Meeting Information' to open whiteboard.
3. Hit 'Full Screen' option from tool bar
4. Hit 'Text' option from tool bar, dummy text object will be added to canvas.
5. Try editing the text by using 'backspace' or 'delete' key from keyboard.

Actual Behavior:
Our custom method to delete selected object is called instead of fabric.js onKeyUp() method. Ideally, this method should not be called as the focus is inside hidden text area.
However, if you exit full screen mode and do the same, it calls fabric.js onKeyUp() method.

Note:
The above behavior works fine on Chrome and Firefox browsers (both small and full screen mode)

**Comment by asturur** [comment]
I need to pick up an ie11 and i ll try to check.
The problem should arise also on a plain html page in fullscreen, without all your custom software.

**Comment by anubhav-aggarwal129** [comment]
Hi @asturur,

Any update on this issue?

**Comment by asturur** [comment]
Yes i loaded it in ie11 and the full screen mode of the browser works just fine.
What is doing you full screen button to the app is something that you should specify and me searching.
That button is doing something to events, because if i put the browser in full screen mode using F11, everything is ok.

**Comment by asturur** [comment]
I'm closing this unless you can prove that the fullscreen mode is the standard ie11 and not your custom app mode.
