### ISSUE TITLE
lockScalingFlip is not locking when resizing from corners

### ISSUE THREAD

**Issue by iongion** [kangax/fabric.js#4338]
See this fiddle https://jsfiddle.net/wta4pdpz/21/

It works from middle points but not from corners and when using corners, the size and position break.

**Comment by asturur** [comment]
This has been discovered and patched 4 hours after beta 7 was packaged and released.
Please download the latest library and build it to have it solved.

relevant commit
https://github.com/kangax/fabric.js/commit/ea93c288e8afb50642eedf431fcad388589eaf46
