### ISSUE TITLE
canvas preview get's messed up when canvas.clipTo() is applied 

### ISSUE THREAD

**Issue by monis01** [kangax/fabric.js#4341]
Hi 
I need little help, I am in midst of my work and the current issue stopped me in moving forward, I tried to google and stackoverflow on this issue but got very little info, here is my question : 
[stackoverflow](https://stackoverflow.com/questions/46379441/canvas-clipto-messed-up-preview-of-the-canvas-on-doing-canvas-todataurl-fab).All I need is to clip the region and safely save all the data inside that region and to send it to server.
PS: I am new to fabric and my current work requires to fix things quickly so myself don't know If I am  having right approach or there is already an issue with it .
Thanks

**Comment by ncou** [comment]
I think you should add a fiddle if you think there is a bug in the toDataURL() when the canvas is clipped.

**Comment by monis01** [comment]
Hi, 
Sorry been busy these days and was on different issue, here is the fiddle [shapeClip](https://jsfiddle.net/monis/9mpLyuak/6/).
The fiddle is working fine as required, but in my code it is having a strange behaviour, here are the images :
(1) my working area, image is properly clipped inside the shape
![issue1](https://user-images.githubusercontent.com/7036532/31126081-3bbd2baa-a868-11e7-8fb7-ce99535fc1d5.png)

(2) when I preview the shape, it  went to the corner
![issue2](https://user-images.githubusercontent.com/7036532/31126139-635dbef4-a868-11e7-8ddc-b78c5d8301ce.png)
![errro22](https://user-images.githubusercontent.com/7036532/31126169-77f35e1e-a868-11e7-9402-6c0d2c9f8a0d.png)

to preview the image this is the code:
`window.frontViewImagBased64 = canvasCopy.toDataURL();
 firstviewSVG = canvasCopy.toSVG();
 firstviewJSON = JSON.stringify(canvasCopy.toJSON(extraFieldsForJson));
 $('#viewThumb1 img').attr("src", window.frontViewImagBased64);`

I Know from this we cannot exactly figure out, but I an unable to understand the cause for this to look into it, if any idea what can be the problem or what should I share with you 
Thanks

**Comment by ncou** [comment]
Without a failing fiddle we can't really help you.
Looks like a custom app problem.

I can't figure out where the problem could come. If you use a zoom or a pan feauture try without it.

**Comment by monis01** [comment]
Thanks for the suggestion, will again look into it or try to create same scenario in fiddle.

**Comment by monis01** [comment]
Hi @ncou 
The problem is solved now for this particular case, after trying fiddle and actual code it comes out that you said right it was some zooming issue. After more debugging it comes out to be some one has changed this value :
`toDataURL: function(options) { ... multiplier = options.multiplier || 3, ... } `
If I am not wrong it should be 1, someone has changed this value to produce bigger image.
so changing back to 1, it worked. All I did was on doing `canvas.toDataURL({multiplier:1})`, and It worked like a charm.
Still I don't understand how it was affecting clippinng case if we have higher multiplier value.
But it has solved my this issue. 
Thanks @ncou
