### ISSUE TITLE
Issues loading google fonts in fabric js

### ISSUE THREAD

**Issue by suriya-mca91** [kangax/fabric.js#4345]
Hi @kangax

**Comment by suriya-mca91** [comment]
I have to load Libre Barcode 128 font family in to fabric canvas. But Barcode doesn't view on canvas. How to set Libre Barcode 128 font family in fabric js canvas?

`var text;
var canvas;
document.addEventListener("DOMContentLoaded", function() {
    canvas = new fabric.Canvas('c');
    setTimeout(function(){
     text = new fabric.Text("Text", {
     fontSize: 70,
     left: 100,
      top: 0,
      fill: '#sew3435' 
    });

    canvas.add(text).setActiveObject(text);
    canvas.getActiveObject().set("fontFamily",'Libre Barcode 128');
    canvas.renderAll();     
    },1000) 
    });`

**Comment by blobinabottle** [comment]
You should use webfontloader https://github.com/typekit/webfontloader

**Comment by ncou** [comment]
use a font loader before loading the font family :

add your css file for the font :
<link href="https://fonts.googleapis.com/css?family=Libre+Barcode+128" rel="stylesheet">

and use a font loader like the one pointed by blobinabottle or this one :
https://github.com/bramstein/fontfaceobserver

open a stackoverflow question if you encounter some problems.

**Comment by suriya-mca91** [comment]
Font family loaded but not apply in canvas

**Comment by asturur** [comment]
either fiddle with the bug happening or we cannot do anything.
If you want help from someone, do the boring part, prepare a fiddle, put a canvas, load the font family font-face, setup a text object.

So that the person that wants to help you can concentrate on the problem and not on the circumstances.
