### ISSUE TITLE
Padding: Top, Left, Bottom and Right on bounding box

### ISSUE THREAD

**Issue by redlive** [kangax/fabric.js#4347]
Hi,

There is no way to assign different padding on a border of a bounding box.
Currently:
```
this.set({
   padding: 10
});
```

Expecting:
```
this.set({
   paddingTop: 10,
   ...
});
```
or 
```
this.set({
   padding:  [t, r, b, l],
});
```

**Comment by asturur** [comment]
no is not a feature at all.
the padding is just to make controls larger by a bit it does not do more than this.

you can still override the method that render the controls to achieve what you want.

**Comment by redlive** [comment]
Tnx.
I've overridden the **drawControls** function and it shows the border and corners in the proper place except for one thing... when I mouseover on a corner it shows control icon and click event on "old" coordinate... What I missed? Could you please tell me what function is responsible for this logic; if it needs to be overridden either?
Tnx

**Comment by asturur** [comment]
i think you have to override setCornerCoords

**Comment by redlive** [comment]
This function doesn't return anything. Maybe it's something else?

**Comment by asturur** [comment]
it does not return anything but sets the points for interacting with corners

**Comment by friday** [comment]
I haven't actually tried, but something like this should work if top/bottom and left/right are the same.

```js
fabric.Text.prototype.set({
  _getNonTransformedDimensions() { // Object dimensions
    return new fabric.Point(this.width + (this.paddingX || this.padding), this.height + (this.paddingY || this.padding));
  },
  _calculateCurrentDimensions() { // Controls dimensions
    return fabric.util.transformPoint(this._getTransformedDimensions(), this.getViewportTransform(), true);
  }
});
```
