### ISSUE TITLE
How to raise the level of an fabric canvas object?

### ISSUE THREAD

**Issue by yuanvolcano** [kangax/fabric.js#4349]
for example , I have drawed a fabric Rect on the Canvas，I want to draw another fabric  Rect  covered over the last one.  In general, I can set the z-index of  property in the CSS to achieve the effect. how should I use fabric.js to reach similar effect ?

**Comment by awehring** [comment]
Look in the documentation for canvas.moveTo().

But the issues here are for reporting bugs. A good place to look for help is stackoverflow.

**Comment by yuanvolcano** [comment]
thank you for disabusing
