### ISSUE TITLE
Dynamic values for object width and height

### ISSUE THREAD

**Issue by imransohail1983** [kangax/fabric.js#4351]
Hi 

i am trying to achieve this. Is it possible that i can generate a shape of custom width and height

My  code is

HTML

<div id="select-frames">
<h3>Select Frames</h3>
	<span class="fa fa-address-card" id="addmore" data-can-width-first="262" data-can-height-first="460" data-can-left-first="20" data-can-top-first="20" data-can-width-second="478" data-can-height-second="460" data-can-left-second="300" data-can-top-second="20">
	</span>
</div>

JQUERY

$('#addmore').bind('click',function(){
		var top_fir = $(this).attr('data-can-top-first');
		var lft_fir = $(this).attr('data-can-left-first');
		var width_fir = $(this).attr('data-can-width-first');
		var height_fir = $(this).attr('data-can-height-first');
		addFrame(top_fir,lft_fir,width_fir,height_fir);
	});
	
	
	function addFrame(a,b,c,d){
		alert(''+a+'');

		var red = new fabric.Rect({top:a, left:b, width:c, height:d, fill: '#ff0000' });
		var blue = new fabric.Rect({top:20, left:300, width:478, height:460, fill: '#ff0000' });

		canvas.add(red, blue);
		canvas.renderAll();
	}

the html span attributes im sending, get an alert in addFrame(), but does not apply to "var red"

struggling with this so thanks in advance

**Comment by marcohamersma** [comment]
Not sure considering I don't actually see the html code, but it could be that you need to add `parseInt()` around each of the variables you're creating in your click handler. That way you convert the values from strings to actual numbers. That could be why it doesn't work. Not really a fabric.js issue if that is the problem.

By the way, it's always useful to create a [jsFiddle](https://jsfiddle.net/) or [codepen](https://codepen.io/) for your issue, so it's easy for people to get a picture of what you're trying to do and tweak your code :)

**Comment by asturur** [comment]
please consider the docs states you have to input number and input boxes from html gives you strings.
