### ISSUE TITLE
Safari bug: path edges cut off

### ISSUE THREAD

**Issue by marcohamersma** [kangax/fabric.js#4352]
## Version
2.0 beta, also tested with 1.7.19 and earlier 
Mac OS Safari v11 (not tested on other versions, but does not seem to occur on iOS)

## Test Case
http://fabricjs.com/freedrawing

## Steps to reproduce
Open the link above in Safari, and draw some lines, (from right to left typically does it).

## Expected Behavior
All the brush strokes have round edges

## Actual Behavior
As soon as the mouse button is released, some edges of the paths get cut off:

![drawing](https://user-images.githubusercontent.com/577144/30870251-4eef109a-a2db-11e7-91aa-b42d7ae13b92.gif)

**Comment by asturur** [comment]
i think is an hardware acceleration problem.
The same thing happens to text in chrome when some big stroke bend over itself.
I do not think i can fix anything here.

**Comment by blobinabottle** [comment]
Not having this issue on my side (safari 11.0.2, OS X high Sierra & Sierra on 2 MacBooks)

**Comment by asturur** [comment]
i think i misunderstood the problem. could have been fixed with freedrawing changes

**Comment by AvaelKross** [comment]
safari 10.1.2, osx sierra - i can confirm the bug.

**Comment by asturur** [comment]
@AvaelKross what version are you using?

**Comment by AvaelKross** [comment]
I've just tested on http://fabricjs.com/freedrawing. Actually it's not that bad for me(not like on the gif attached to this post), but if I try to draw curved line a bit faster, some corners are getting cut off. Probably not the 100% same issue, but similar.

**Comment by asturur** [comment]
i can replicate with safari 11 latest vesion.

What i see is that safari has some problem bending big strokes. unsure i can fix it.

**Comment by asturur** [comment]
the original issue has been fixed
