### ISSUE TITLE
Convolute function bug

### ISSUE THREAD

**Issue by eugene1983** [kangax/fabric.js#4354]
Hi,
I have found a bug probablly.
Or may be i do something wrong?

## Version
2.0.7 beta (even tested on 2.0.4 and 2.0.6)

## Test Case
https://jsfiddle.net/xeufaL8b/

## Steps to reproduce
run

## Expected Behavior
filter working

## Actual Behavior
in my real application (image editor) i have this error in console:

> Uncaught Error: Fragment shader compile error for "${this.type}": ERROR: 0:1: '[' : syntax error

in my test fiddle i have error (in console):
Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The cross-origin image at http://fabricjs.com/lib/pug.jpg may not be loaded.
    at WebglFilterBackend.createTexture (https://rawgit.com/kangax/fabric.js/master/dist/fabric.js:19463:12)
    at WebglFilterBackend.getCachedTexture (https://rawgit.com/kangax/fabric.js/master/dist/fabric.js:19485:28)
    at WebglFilterBackend.applyFilters (https://rawgit.com/kangax/fabric.js/master/dist/fabric.js:19349:30)
    at klass.applyFilters (https://rawgit.com/kangax/fabric.js/master/dist/fabric.js:18876:28)
    at http://fiddle.jshell.net/_display/:71:10
    at https://rawgit.com/kangax/fabric.js/master/dist/fabric.js:19079:19
    at HTMLImageElement.img.onload (https://rawgit.com/kangax/fabric.js/master/dist/fabric.js:845:30)

**Comment by asturur** [comment]
looks a bug

**Comment by asturur** [comment]
https://jsfiddle.net/xeufaL8b/1/

No wait, the original error is because you are using an older beta that had the code for convolute wrong.
The second message is because you are not loading crossOrigin.

**Comment by eugene1983** [comment]
this worked! Thank you!
i used this in:

>         fabric.Image.fromURL('imgpath', function (oImg) {
>             ...
>         }, { crossOrigin: 'Anonymous' });

And what is 'crossOrigin' option means?

**Comment by eugene1983** [comment]
I have another question:
In my project i have to use Gradient filter to an image object and it doesn't work. Gradient only worked with rects, circles, etc. Is this true, or am i doing something wrong?

**Comment by asturur** [comment]
so crossOrigin is a web standard and you have to definitely learn what it is and why is there. Is necessary for a project working with images and is not a fabric thing.

Gradient is not a filter, is a filling option.
you cannot really fill an image with a gradient but you can blend it.

what effect are you looking for?

**Comment by eugene1983** [comment]
i have to apply semi-transparent gradient fill to an Image object. So i did it this way:
- make a rectangle with the same size and position as the Image,
- apply gradient to this rectangle,
- bring this rect to Front
So i had to make some code to be able to apply gradient by every angle form 0 to 360 degrees, with ability to change offset and intensity. 
You talk about 'blend', do you mean the same thing?

And I have another question about convolute.
I made sharpen filter using appropriate matrix like it pointed in Docs. It worked perfect. 
But i only can apply filter and not being able to change something like strength of this filter (to change filter's impact). Is it possible to make any variant of changing sharpen filter's strength?
