### ISSUE TITLE
Shapes not getting rendered in safari but fine in Chrome

### ISSUE THREAD

**Issue by vc1202** [kangax/fabric.js#4359]
I am developing a Algorithm drawing library on top on fabricjs but the functions I created are not drawing anything on Safari,but they are working fine in Chrome.

## Version
2.0 beta

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by asturur** [comment]
Can you create a fiddle that fails on safari and work on chrome? if not let's close this issue.
