### ISSUE TITLE
Mention version in documentation

### ISSUE THREAD

**Issue by joakimgrr** [kangax/fabric.js#4360]
I think the version to which the documentation on fabric website applies should be clearly mentioned in documentation (atleast i didn't find this). 

The documentation is already reflecting the 2.0 version, even though its still in beta. I think its fine, but it should be mentioned since its doesn't apply to the latest stable release and might cause some confusion. 

Thoughts? :)

**Comment by asturur** [comment]
Sure. Changing the jsdoc template is not fast, do you know how to do it? in case you can contribute a PR to the fabricjs.com repository.

**Comment by speyburn** [comment]
@asturur i'm not super familiar but can definitely do the homework and submit a PR :) I would rather submit a fixing PR than submit an issue, but didn't realise that fabricjs.com had it's own repo 😆

**Comment by asturur** [comment]
I can't find a way to explicitly put the version in the docs unless i do it manually.

**Comment by asturur** [comment]
looks ugly but i did it
![image](https://user-images.githubusercontent.com/1194048/33232853-86c8cfd6-d20d-11e7-96f4-e4baa36f6892.png)
