### ISSUE TITLE
setActiveObject is not working properly

### ISSUE THREAD

**Issue by DerekLiang** [kangax/fabric.js#4362]
## Version
2.0 beta 7

## Test Case
https://jsfiddle.net/DerekLiang/dszj6fq8/ -- not working
same code, works in 1.7.19.

## Steps to reproduce
click on the refresh button in the codepen

## Expected Behavior
The object is selected.

## Actual Behavior
The object is not selected.

**Comment by asturur** [comment]
codepen do not work for me. they flash all the time. please make a fiddle.

**Comment by DerekLiang** [comment]
As mentioned in #4145 , you need to call renderAll after setActiveObject.
