### ISSUE TITLE
strokeLinecap is not rendering as dotted

### ISSUE THREAD

**Issue by redlive** [kangax/fabric.js#4365]
There is no way to set stroke-linecap as **butt, round** or **square** when create a new element.
It always renders as regular squared style.

http://jsfiddle.net/redlive/dzfy6vzb/

|Expected
|--
|butt \| round \| square

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linecap

**Comment by asturur** [comment]
Where? on Canvas? on SVG output? importing from SVG?

Please reproduce with a fiddle.

**Comment by redlive** [comment]
Sorry... forgot to add.

http://jsfiddle.net/redlive/dzfy6vzb/3/

Elements: Rect, Ellipse, Line

**Comment by asturur** [comment]
http://fabricjs.com/docs/fabric.Object.html

Please check the correct spelling for the object property that regulate the line caps

**Comment by redlive** [comment]
@asturur Tnx you.
Would you help me with one more thing? Please take a look at my comment about Toolbar (last comment from 3 days ago)
Thank you again.

**Comment by asturur** [comment]
Toolbar?

**Comment by redlive** [comment]
Well… Not really about toolbar… I’m wondering how to apply some style on part of the text…
