### ISSUE TITLE
Builder not working/only beta available

### ISSUE THREAD

**Issue by danielocdh** [kangax/fabric.js#4366]
## Version
1.7.19

## Test Case
http://fabricjs.com/build/

## Steps to reproduce
Try to build the script on firefox, chrome, edge

## Expected Behavior
Get a built script

## Actual Behavior
Nothing gets build, I get this error on chrome console:
(index):273 Uncaught TypeError: Cannot read property 'checked' of null
    at ifSpecifiedInclude ((index):273)
    at collectFilesName ((index):279)
    at build ((index):438)
    at HTMLButtonElement.document.getElementById.onclick ((index):464)

I understand you are busy but would it be possible to just have an old working version of the builder for now? Also non beta please, I'm guessing that mostly custom builds don't really go to development but for final production uses.

I have been trying to install npm canvas on windows for the last 2 hours without success, I understand is really easy on linux but I just can't get it to work here.

Thanks

**Comment by asturur** [comment]
i updated the builder

**Comment by danielocdh** [comment]
I needed a non beta build so after so many hours I finally managed to build on a VM with linux, I think the main thing I did different was to NOT install fabricjs with npm/bower, just downloaded the github files instead. Still had to do the cairo install and some other dependencies, I don't remember the exact steps, I just googled every time I got an error.
