### ISSUE TITLE
scaleToWidth() only by width. Is it possible?

### ISSUE THREAD

**Issue by eugene1983** [kangax/fabric.js#4371]
Hello!
I need to scale image to sertain width and height manually, not by using controls.
But 

> Scales an object to a given height/width, with respect to bounding box (scaling by x/y equally)

.
Is it possible to scale by one side only?

**Comment by willKo** [comment]
Not sure but maybe this can help you? 

scaleX :Number
Object scale factor (horizontal)
http://fabricjs.com/docs/fabric.Object.html

**Comment by eugene1983** [comment]
Thanks for help willKo. I really can scale by one side! But i need to scale to sertain width or height.

**Comment by jparkrr** [comment]
This question would be better on stackoverflow, but you can do it like this:

```js
object.set('scaleX', desiredWidth / object.width)
```
