### ISSUE TITLE
FreeDrawingBrush starts round with square line cap

### ISSUE THREAD

**Issue by nathand8** [kangax/fabric.js#4373]
## Version
1.7.19

## Test Case
https://jsfiddle.net/a6fcfugw/1/

## Steps to reproduce
- Set up free drawing on a canvas
- Use a wide brush (10+)
- Use strokeLineCap = 'square';
- Draw from right to left.

## Expected Behavior
I would expect to see strokes with square corners (as I see when drawing left to right)

## Actual Behavior
I see rounded corners on the right side when drawing right to left.
![fabricjs freedraw bug](https://user-images.githubusercontent.com/10536367/31196600-99b1c290-a90b-11e7-92e1-6a01cd8a29b8.gif)

**Comment by asturur** [comment]
Fixing in master, backporting to 1.x when i have time

**Comment by nathand8** [comment]
@asturur, Thank you for the fix! Any idea when this will be backported to 1.x?

**Comment by asturur** [comment]
mmm today.
ping me again if tomorrow you do not see the commit.

**Comment by nathand8** [comment]
Here's a ping for you @asturur :) I appreciate you working on this

**Comment by nathand8** [comment]
Hey @asturur, any chance you can backport this to 1.x?

**Comment by asturur** [comment]
i think i did. didn't i? did you try 1.7.20?

**Comment by nathand8** [comment]
Ah ok. I'll give it a shot

**Comment by nathand8** [comment]
Yes you did! Sorry I didn't see that. Thank you! :D
