### ISSUE TITLE
Problem TEXT cursor with new font

### ISSUE THREAD

**Issue by EnguerranMeens** [kangax/fabric.js#4378]
Hello , 

Today I encounter a problem with an ITEXT and i really don't know how to fix it , it's happen when i try to add a font . I try with an TEXT and a TEXTBOX but same problem :\ 

Screen : http://prntscr.com/gvn6xf

Someone can help me ? 
Thanks .

**Comment by ncou** [comment]
Can you add a failing jsfiddle to your issue ?

**Comment by asturur** [comment]
I need to create a small article on how to load fonts.
Link in the issue template.
