### ISSUE TITLE
perPixelTargetFind not removing the bounding rectangle

### ISSUE THREAD

**Issue by atul-shimpi** [kangax/fabric.js#4379]
I have set perPixelTargetFind to false.
However, object detection is not happening accurately.

When i clicked on the actual object, event target is wrong.
I am trying this for last 1-2 weeks, without any success.

Below is my code.

journey_title_attrs.strokeWidth = 3;
    journey_title_attrs.perPixelTargetFind = true;
    journey_title_attrs.hasControls = false;
    journey_title_attrs.targetFindTolerance = 12;
    journey_title_attrs.hasBorders = false;
    journey_title_attrs.selectable = false;
    journey_title_attrs.selection = false;
    
    station_.platforms.forEach(function (platform_) {
      journey_title_attrs.top = top - 150;
      var platform = new fabric.Rect(journey_title_attrs);

**Comment by ncou** [comment]
Can you add a jsfiddle example please ?
