### ISSUE TITLE
FabricJS gradient color values

### ISSUE THREAD

**Issue by monis01** [kangax/fabric.js#4380]
I am looking for gradient range (area it covers) for all four directions in case of linear gradient . Details :

[Gradient range](https://stackoverflow.com/questions/46706855/fabricjs-gradient-color-values) and fiddle :  [fiddle1](https://jsfiddle.net/monis/vtvdcnp5/7/) and [fiddle2](https://jsfiddle.net/monis/vtvdcnp5/8/)

Thanks

**Comment by asturur** [comment]
answering o SO.
