### ISSUE TITLE
Image#clipTo has no closure after canvas#loadFromJSON

### ISSUE THREAD

**Issue by kinglywork** [kangax/fabric.js#4386]
## Version
1.7.19

## Test Case
http://jsbin.com/zojorec/edit?html,js,output

## Steps to reproduce
In the demo above, click export button to export canvas as json,  click the clear button to clear the canvas and then click the import button to import the json just exported.
The exported json can not import because of an error 'img is not defined' in clipTo method.

if clipTo method depends on some var in closure scope like the demo above, how to fix the error?

**Comment by asturur** [comment]
That is why clipTo has a deprecation mark.
Has many limitation, it cannot depend of things outside the function itself and is unsafe to restore. ( someone could inject any function that would be executed by your browser in a design some way )

You cannot actually restore a function that depends from something that is not inside the function.

**Comment by onoranzefunebricloud** [comment]
@asturur What function should we use for cropping?

**Comment by asturur** [comment]
you should switch to clipPath:
http://fabricjs.com/clippath-part1
