### ISSUE TITLE
Create an article on how to load fonts on fabricjs.com, insert the link on the issueTemplate.MD

### ISSUE THREAD

**Issue by asturur** [kangax/fabric.js#4389]
Create an article/demo on fabricjs.com that demonstrate a google font laod with fontfaceobserver or some fontloader.

Link it here in the issue template

**Comment by jilster** [comment]
I use Google fonts in my Fabric project. I also made a small font preloader. Would you like me to turn it into a tutorial or demo or describe it?

**Comment by asturur** [comment]
i would prefer to explain how to use a couple of existing preloaders
pointing them to the resources adn giving a working example how load fonts with them.
If the loader has a place to go where you have some problem is better.

If you want to start a tutorial yes please do it

**Comment by jilster** [comment]
OK, i will. Are there any existing preloaders you are thinking of?

**Comment by asturur** [comment]
i used fontFaceObserver from brmstein on github and i know it works.
Anything else is good.
With callbacks or promises, i do not really care, as long as it works.

**Comment by jilster** [comment]
http://jsfiddle.net/vkLvn9xk/5/

I used Font Face Observer and made this example. There is also some explanation of why font preloading is necessary. It's in the comment section of the JS.

It actually works better (faster) than the custom preloader i made for myself, so i am switching to this one as well.

If you need help with stuff like this, please let me know. I like testing, documenting, creating examples and tutorials etc.

**Comment by asturur** [comment]
i ll make a small demo somewhere on fabricjs.com so that i can directly link there when someone open another issue for it

If you like helping in this area and you know fabric a bit, just check fabricjs.com and propose area of improvements. there are many.

**Comment by asturur** [comment]
do you have a twitter nick? i m pushing this on the website and wanted to tweet it.

**Comment by jilster** [comment]
Nice. I don't have twitter myself, and the companies twitter is rarely used.

I am going to look at some propositions for fabricjs.com soon, i'm glad to help in any way i can.

**Comment by asturur** [comment]
demo is here

http://fabricjs.com/loadfonts

i had to slightly change it adding load on demand, just to not freak out people that wants to use all existing google fonts.

**Comment by pidugusundeep** [comment]
@asturur I see that there is no code sample for `// Load all fonts using Font Face Observer` in the link ( http://fabricjs.com/loadfonts ) which you shared Please let me know how can I load the font face observer?

**Comment by asturur** [comment]
the example left from @ghost here is very good.
