### ISSUE TITLE
Problem with calcLinePoints in toJSON

### ISSUE THREAD

**Issue by Exlord** [kangax/fabric.js#4390]
## Version
1.7.19

## Test Case
http://jsfiddle.net/Exlord/L01t1kLm/

## Steps to reproduce
See the code sample its simple

## Expected Behavior
the drawn line in canvs2 to be identical to canvas1

## Actual Behavior
the drawn line in canvas2 has incorrect position and size

I need to update identical canvases in clients using the main canvas in operator, so when on object is modified O convert the object to json string and transfer it to the client and add or modify the object in the client.
Other shapes works fine but line is problematic, it loses position and size when any property is changed, try moving the line in the top canvas.
Circle is ok but line is not!

**Comment by durga598** [comment]
Try setting left and top value of original obj to drawn line in second canvas. Here is [Demo](http://jsfiddle.net/durga598/L01t1kLm/10/).

**Comment by asturur** [comment]
http://jsfiddle.net/asturur/L01t1kLm/11/

look here for use of proper built in clone method.

http://fabricjs.com/docs/fabric.Object.html
