### ISSUE TITLE
Negative coordinates in fabric canvas

### ISSUE THREAD

**Issue by vikaskallidantheyil** [kangax/fabric.js#4391]
How to have negative coordinates in canvas.

i need to show some objects on negative coordinates. how i am suppose to get that.

i need to achieve some thing like image attached .
![001](https://user-images.githubusercontent.com/30237830/31768375-c5fde65c-b4ec-11e7-81bf-d2c5bc9946eb.png)

is that possible using fabric canvas.?

currently i have done using svg view box.

**Comment by asturur** [comment]
apply a viewportTransform with a translation attribute.
Or simply pan the canvas.

Please check the docs or open a proper question on stackoverflow and i ll help there after you post the link question here.
I can't use the issue tracker as support forum.
