### ISSUE TITLE
Wrong element placement on Canvas by using different origins .

### ISSUE THREAD

**Issue by redlive** [kangax/fabric.js#4395]
## Version
2.0 beta

## Test Case
http://jsfiddle.net/redlive/201y9s3m/2/

## Expected Behavior
To have same Left and Top position despite on element's origins
<img width="417" alt="screen shot 2017-10-19 at 6 41 38 pm" src="https://user-images.githubusercontent.com/5912122/31801469-4235ce00-b4fd-11e7-8c00-a21bbba46783.png">

## Actual Behavior
Initial value for Left (for example 50) "shifts" after changing originX ( same  with the Top )
<img width="429" alt="screen shot 2017-10-19 at 6 41 49 pm" src="https://user-images.githubusercontent.com/5912122/31801465-3b6d6178-b4fd-11e7-8da1-0ac31b59158c.png">

**Comment by asturur** [comment]
Sure.
Left and top should have been called x,y.

But when they named it, originX and originY was not an option, was just based on center.

If you want to keep the same position after switching you have to use

setPositionByOrigin(position, 'originX', 'originY')  and fabric will update the top and left to make the object do not move

(please confirm with docs)

**Comment by redlive** [comment]
I tried that solution, but it doesn't really work... Could you please take a look on that one and tell me what I've missed? 
http://jsfiddle.net/201y9s3m/5/

**Comment by asturur** [comment]
so top and left are called like that because when they are introduced, at the start of fabric, origin could not be changed. using top and left as a property when you can place origin in the bottom right is confusion.

is unclear to me what you want to accomplish.

So the code is right for me.

you have desired cord of 100,50.
you have a rect that is positioned by center
you ask fabric to position it so that the top left corner is in 100, 50.
fabric does calculation, and pick up 150.5, 200.5 for the center coordinates so that it can repsect your request.

What is that you were searching for?

**Comment by redlive** [comment]
I understand that, but here is a scenario.

My application has two components: one is a canvas itself, and another is kind of Attributes/Position Panel where you can change the left of an element. 
The LEFT number comes from backend and this is an actual number which should be represented in the Attributes Panel.
So, to get the left I'm using **this.getLeft()** function which returns a Left based on its OriginX. 
If its set to Center, then we get, like you say,  150.5 by 200.5, but take a look, it's a CENTER, not LEFT... 
So in my scenario, the Input will display a value of 150.5, not 100 and to make it right I'll need to substruct a half on a width (and then add half of the width later)...

So, what I think should be the correct way is to have an object of coordinates or something like that, where LEFT is a LEFT, a center is a center etc despite their origins...

Make sense? Any thoughts?

Tnx

**Comment by asturur** [comment]
I need this answer before i can give any suggestion.
Why you need centered origin to use centered rotation?

Are you using the named accessor to set the angle?

**Comment by redlive** [comment]
Because if I'll will rotate an object programmatically without specifying a center origin, it will rotate it based on top left corner.

**Comment by asturur** [comment]
Are you using setAngle with the named accessor to set the angle?

**Comment by redlive** [comment]
Here is the link to JSFiddler... you can see what I'm using to achieve the goal...
http://jsfiddle.net/redlive/gjq7gmt9/5/

Please get down to **updateYellowPosition** function. Basically, I'm trying to set Yellow element with proper angle on top of red's background image.

The code may look messy, but I did fast for presentation purpose... Sorry :)

**Comment by asturur** [comment]
I really cannot understand.
Is really confusing because the problem shift every message to something different.

in fabric:
- top and left are two bad names to indicate the position of the object. 
- setting the angle with .angle or .setAngle with set the angle with the object origin in mind.
- using .rotate will allow you to set the rotation on the object in the center regardless of the origin
- to get the corner you want at anytime, you can use `getPositionByOrigin` specifing the origin you would like to know
- or you can access the .aCoords object to read tl, tr, br, bl corners position in absolute coordinates ( without zoom )

**Comment by redlive** [comment]
Well, the problem doesn't shift; it's still same, which is rotation based on origin, but anyways... 
I almost achieve the desired result except for one thing... The element continuously rotates with some extra angle. Looks like the angle accumulates all the time to the previous angle...

http://jsfiddle.net/redlive/gjq7gmt9/14/

Back to your comments... I really appreciate your time in helping me,  but I still have some concerns about them.

- **Top & Left** - Not sure what you mean by that. I understand that names aren't proper, but those used to create elements... There is no such an attribute X and Y.

- **setAngle** - I can't use this function. because by rotating a red element it's background position coordinates change for the yellow one (for the red one they remain same... I agree... it's just an angle changes...) So it sounds like I must to use **fabric.util.rotatePoint function**

So, I still think that **getLeft** function should return LEFT corner coordinate, not CENTER...

If you have a time, please see my rotation issue and let me know if you have any tips or notes about it... From my understanding, it shouldn't accumulate an angle...

Tnx

**Comment by asturur** [comment]
did you use `.rotate()` ?

**Comment by redlive** [comment]
Nope... I can't... no? I have to also translate element, so I'm using **rotatePoint** function.

**Comment by asturur** [comment]
provided that you are using fabric 2 latest beta,
setAngle is just setting the angle, while rotate is rotating the object on the center, modifying top and left accordingly.

**Comment by redlive** [comment]
To modify left and top I have to get their new coordinates, so that's why I'm using rotatePoint function... it returns new coordinates based on **point, origin, radians**

**Comment by asturur** [comment]
https://stackoverflow.com/questions/46936572/fabricjs-continues-rotation-on-object-rotation-event/46949814#46949814

is this answer to one of your question helping also this problem here?
