### ISSUE TITLE
The fabric module export its api indirectly

### ISSUE THREAD

**Issue by kputh** [kangax/fabric.js#4399]
## Version
1.7.19

## Description
I use fabric.js with yarn and webpack. When I do

```
import * as fabric from 'fabric';
var canvas = new fabric.Canvas('c');
```

I get a runtime error because `fabric.Canvas` does not exist. The module `fabric` does not export `Canvas`. Instead, it exports `fabric.Canvas`. So I need to do this

```
import * as fabric from 'fabric';
var canvas = new fabric.fabric.Canvas('c');
```

It's the same for the rest of the library. It deviates from the official documentation and isn't common sense. Please fix it.

**Comment by asturur** [comment]
The correct way to import it is:

`import { fabric } from 'fabric';`

using the destructuring assignment.

**Comment by kputh** [comment]
This definitely belongs in the documentation.

**Comment by asturur** [comment]
added a note in the node examples
