### ISSUE TITLE
Shapes (or their bounding boxes) do not scale correctly

### ISSUE THREAD

**Issue by mmbit** [kangax/fabric.js#4401]
## Version

2.0.0-beta7

## Test Case

https://jsfiddle.net/27u4ebg1/5/

## Steps to reproduce

Scale up any fabric.Rect, fabric.Circle, fabric.Triangle. This issue does not seem to affect fabric.Image.

## Expected Behavior

While scaling...

- The bounding box matches the size of the shape (as drawn on the canvas) (+1 px on every side)
- The top/left coordinates of the shape (as drawn on the canvas) do not shift

## Actual Behavior

- The shape's bounding box seems to start out half a pixel larger than it should, on all sides. This difference is multiplied by `scaleX` or `scaleY`, and `canvas.getZoom()`. So at scale 10, there's a 5 pixel-distance between the shape and its bounding box, on all sides.

- The shape itself has the right size, but stays centered in its oversized bounding box. Consequently, the object isn't drawn in the correct position. Compare the red squares in the JSFiddle, they should be aligned horizontally.

**Comment by asturur** [comment]
that is the stroke.
Set the strokeWidth to 0 and the border will not be there.

**Comment by mmbit** [comment]
Huh, yes, that works. Thanks very much! :) Though I'm not sure that should be happening, since the `stroke` field is set to `null`. But I'll take it.

**Comment by asturur** [comment]
because stroke is actually stroke color. but the border is there. it wasn t like that before but svg import got really improved when we switched to this different approach.

**Comment by mmbit** [comment]
Ah, fair enough :) Thank you for the explanation.

The docs/rendering code still sort of imply `null` means disabling the stroke altogether. Minor point, but that being the default, this does seem like an easy mistake to make and overlook... in fact, the shapes on the fabricjs.com front page have this invisible stroke too.

**Comment by HATyCEHKA** [comment]
I have the same problem.
I import different svg files created in illustrator to fabric. If figure has no stroke it has empty margins in fabric but in illustrator or inkskape it has no margins.

**Comment by asturur** [comment]
this is how illustrator draw its bounding box, fabric draws it around the
object size and the stroke, even if transparent, has a size.

**Comment by HATyCEHKA** [comment]
I found that problem appears only if imported svg has only one shape.
![screenshot_6](https://user-images.githubusercontent.com/26141774/34638732-e9996256-f2e2-11e7-9889-83b1341c36a2.jpg)
![screenshot_7](https://user-images.githubusercontent.com/26141774/34638733-e9b5e8fe-f2e2-11e7-8633-21e91ef23ad9.jpg)
