### ISSUE TITLE
shadow doesn't render the same in chrome vs safari

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4402]
## Version
2.0 beta

## Test Case
http://jsfiddle.net/7gvJG/207/

## Steps to reproduce
Check the shadow in safari vs chrome. Chrome is less blurry than Safari. From our test it seems Safari is more coherent with the same shadow props in html/CSS. 

## Safari Behavior
<img width="314" alt="screen shot 2017-10-23 at 13 37 59" src="https://user-images.githubusercontent.com/8090162/31887181-a3baafa4-b7f7-11e7-8ba0-0fec82b3df19.png">

## Chrome Behavior
<img width="304" alt="screen shot 2017-10-23 at 13 38 06" src="https://user-images.githubusercontent.com/8090162/31887188-ad479d48-b7f7-11e7-96eb-725a3d76eefe.png">

**Comment by asturur** [comment]
Is a browser issue i found out some months ago, for which i can do little for now.

https://jsfiddle.net/asturur/ot2s2Lja/3/

open this fiddle in chrome, firefox, safari and IE and check the different results of shadow blur across browsers.

CHROME
![image](https://user-images.githubusercontent.com/1194048/31928721-76985042-b899-11e7-92b9-037079aa5cb5.png)

SAFARI
![image](https://user-images.githubusercontent.com/1194048/31928747-9270e694-b899-11e7-97b9-7849b5a8bccb.png)

FIREFOX
![image](https://user-images.githubusercontent.com/1194048/31928751-97ff8002-b899-11e7-8e5c-01542bde7ea5.png)

**Comment by blobinabottle** [comment]
Thanks. We'll check if we can find the magic numbers to make all browser match. Could be useful I guess.

**Comment by asturur** [comment]
Internet explorer and edge do different also.
Not sure is worth trying to fix some multiplier so that are all happy.
Fabric zooming often brings you in situations where you have high numbers

updated the fiddle to better show what happens
https://jsfiddle.net/asturur/ot2s2Lja/5/

chrome
![image](https://user-images.githubusercontent.com/1194048/31941596-acc14e98-b8c2-11e7-907e-9a449e2d6a68.png)

safari
![image](https://user-images.githubusercontent.com/1194048/31941620-c0c38de8-b8c2-11e7-990b-fb2054cd97f4.png)

firefox
![image](https://user-images.githubusercontent.com/1194048/31941634-ce249702-b8c2-11e7-9a1e-1eb98a79f9b6.png)

As you see firefox has a wider blur, but is immediately capped.

**Comment by asturur** [comment]
each pixel of that image represent a shadowblur value.

**Comment by melvynhills** [comment]
This is my current solution, which uses user-agent to determine the blur value to use.
Dirty but does the job.

```javascript
fabric.Object.prototype._setShadow = function(ctx) {
  if (!this.shadow) {
    return;
  }

  var multX = (this.canvas && this.canvas.viewportTransform[0]) || 1,
      multY = (this.canvas && this.canvas.viewportTransform[3]) || 1,
      scaling = this.getObjectScaling();
  if (this.canvas && this.canvas._isRetinaScaling()) {
    multX *= fabric.devicePixelRatio;
    multY *= fabric.devicePixelRatio;
  }
 

  //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  // CUSTOM CODE START
  //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

  var isEdge = /Edge/.test(navigator.userAgent);
  var isChrome = /Chrome/.test(navigator.userAgent) && /Google/.test(navigator.vendor);
  var isSafari = /Safari/.test(navigator.userAgent) && /Apple/.test(navigator.vendor);
  var isFirefox = /Firefox/.test(navigator.userAgent);
  var isIE = /MSIE|Trident/.test(navigator.userAgent);

  var shadowBlurMultiplier = 1;
  if (isEdge) {
    shadowBlurMultiplier = 1.75;
  } else if (isChrome) {
    shadowBlurMultiplier = 1.5;
  } else if (isSafari) {
    shadowBlurMultiplier = 0.95;
  } else if (isFirefox) {
    shadowBlurMultiplier = 0.9;
  }
  ctx.shadowBlur = this.shadow.blur * shadowBlurMultiplier * (multX + multY) * (scaling.scaleX + scaling.scaleY) / 4;

  //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  // CUSTOM CODE END
  //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


  ctx.shadowColor = this.shadow.color;
  ctx.shadowOffsetX = this.shadow.offsetX * multX * scaling.scaleX;
  ctx.shadowOffsetY = this.shadow.offsetY * multY * scaling.scaleY;
},
```

---

Not sure yet how to implement it cleanly in the library…Maybe something like a variable on `fabric` object such as `browserShadowBlurConstant`, by default set to 1?
If you do think it's a good idea, I can submit a PR that exposes that variable so everyone can use their own browser detection logic if they want it.

**/HEADER.js**
```javascript
fabric.browserShadowBlurConstant = 1;
```

**/src/shapes/object.class.js**
```javascript
_setShadow: function(ctx) {
  ...
  ctx.shadowBlur = this.shadow.blur * fabric.browserShadowBlurConstant * (multX + multY) * (scaling.scaleX + scaling.scaleY) / 4;
  ...
},
```

**custom code**
```javascript
  var isEdge = /Edge/.test(navigator.userAgent);
  var isChrome = /Chrome/.test(navigator.userAgent) && /Google/.test(navigator.vendor);
  var isSafari = /Safari/.test(navigator.userAgent) && /Apple/.test(navigator.vendor);
  var isFirefox = /Firefox/.test(navigator.userAgent);
  var isIE = /MSIE|Trident/.test(navigator.userAgent);

  if (isEdge) {
    fabric.browserShadowBlurConstant = 1.75;
  } else if (isChrome) {
    fabric.browserShadowBlurConstant = 1.5;
  } else if (isSafari) {
    fabric.browserShadowBlurConstant = 0.95;
  } else if (isFirefox) {
    fabric.browserShadowBlurConstant = 0.9;
  }
```

**Comment by asturur** [comment]
this does not solve the cap problem that i think is unsolvable.
I would avoid browser sniffing if possible in the library, but this is a solution that works for the apps that uses fabric.

Just exposing browserShadowBlurConstant, default to 1 in the HEADER.js i think is an ok change. Helps everyone and everyone can support also future browsers if any ( or changes in canvases that may happen if they switch the drawing library cairo or other )

I would also add the costants you discovers in a comment right over the variable declaration.
