### ISSUE TITLE
Feature Request: locking the aspect ratio

### ISSUE THREAD

**Issue by kputh** [kangax/fabric.js#4403]
## Feature Request
I'd like to be able to lock the aspect ratio of an image or group, so it can be scaled equally along all axes, but not stretched along any single axis.

The API could look like this
```
var imgInstance = new fabric.Image(imgElement, {
  left: 100,
  top: 100,
  lockAspectRatio: true
});
```

**Comment by jilster** [comment]
What you need is 'lockUniScaling', see https://github.com/kangax/fabric.js/wiki/Preventing-object-modification

**Comment by asturur** [comment]
yes!

**Comment by kputh** [comment]
Thanks. I found 'lockUniScaling' before I opened this issue, but it didn't seem to work. Now it does. I must have made a mistake while testing it.

**Comment by fpolli** [comment]
Hi, I notice that lockUniScaling is no longer an option. So how do we lock the aspect ratio?
