### ISSUE TITLE
Object Scalling issue 

### ISSUE THREAD

**Issue by durga598** [kangax/fabric.js#4404]
**Version** 
2.0.0-beta7

[jsFiddle](https://jsfiddle.net/durga598/x5s1vojs/)

Try scalling with cornors (tr,tl,br,bl), if the width is almost zero that time whole object disapperas. Values(left,top,scaleX,scaleY,cacheHeight,cacheWidth,zoomX,zoomY), all becomes NaN.

**Comment by asturur** [comment]
argh i was sure we fixed this.

**Comment by asturur** [comment]
http://fabricjs.com/kitchensink

the problem does not appear here.
I guess we fixed it next day of beta7 release since it was obviously broken.
Can you double check and in case close the issue?

**Comment by durga598** [comment]
Yes `fabric.js` script used for kitchensink is working , but the script which is in `dist/` its not working.

**Comment by asturur** [comment]
that we will be rebuilt with next beta or rc.
