### ISSUE TITLE
Applying filters to updated Image objects (with new image) shows old image

### ISSUE THREAD

**Issue by thomastuts** [kangax/fabric.js#4405]
## Version
`2.0.0-beta7`

## Test Case
http://jsfiddle.net/Da7SP/710/

## Steps to reproduce
Click the 'Randomize image' button (you might have to click it several times since it's using a random src URL)

## Expected Behavior
The image should change to a new image, and have the Sepia filter applied to it

## Actual Behavior
The _dimensions_ get updated, but the old _image_ is still displayed. I want the new image to show up with a Sepia filter applied to it as well. As noted in the test case code, commenting line 56 results in the new image showing up just fine, but without the Sepia filter applied. I tried clearing the filters using `.applyFilters([])`, but that didn't work either.

**Comment by asturur** [comment]
looks a but, like if setElement is not clearing the old filteredElement.

Needs a fix.

**Comment by asturur** [comment]
it is a webgl problem, the texture cached at first filtering wasn't being cleared.
