### ISSUE TITLE
Circle is selectable when multi-select objects even if isSelectable = false

### ISSUE THREAD

**Issue by jfgouda** [kangax/fabric.js#4407]
Circle is selectable when multi-select objects even if isSelectable = false

## Version
1.7.9

## Test Case
https://jsfiddle.net/jgouda/f12bLkkh/5/

## Expected Behavior
Any element set isSelectable to false should not be selected when multi-select

## Actual Behavior
If two or more circles included in the multi-select objects will be selectable even though isSelectable = false. However if you try to select a circle and rect none will be selected

Beside that, to workaround the problem, i tried to deselect the object on selection:created but no API to deselect a single element, I don't want to deselect all! I searched everywhere, I can deselect all elements or groups, but I cannot deselect a single given object.

**Comment by jfgouda** [comment]
I just found that setting  selectable: false would make the circle unselectable even in mult-select, however my app need to select in special cases, to better explain see this fiddle, https://jsfiddle.net/jgouda/x0un01jv/ I need to allow the user to multi-select but also a control circle is need to move lines, so if selection is enabled for circle i can select all of them and move them away. if selection is disabled i cannot drag the line. so how can I solve the issue? a workaround I can think of is to deselect a single item but no api to perform a single deselection.

**Comment by asturur** [comment]
to me look that the problem is still undefined.
Do you want to:
 - disable multi selection to do not kill the stick man shape
 - find a way to do not select circles other than in single selections
 - fix the code so that you can multi select circles and move them and the line will follow.

**Comment by jilster** [comment]
What is 'isSelectable'? Isn't this problem caused by the fact you are using that instead of 'selectable'?

**Comment by jfgouda** [comment]
I'm sorry folks, I was confused with selectable and isSelectable and I don't even know where it came from. So this is **Not a Bug** for sure. But the current selection behavior is affecting my app needs. Not sure if I need to move question somewhere else?

For instance, global canvas selection is needed so the user can select multiple items added by user, such as a rectangle or line. But my app is generating shapes when it starts, user should not be able to select these generated items which can be solved by setting selectable to false. But one of those generated shapes is the stick man. Setting selectable to those circles will prevent the user from dragging the circles and stick man concept become useless. Setting selectable to true then when user multi-select he can drag these circles.

One way I think would solve the issue, is on selection:created event I can deselect an item if its app generated. But fabric JS doesn't provide any API to deselect a single element, I can discard all, but I cannot deselect an element by setting its active to false, or selected to false.

Thanks

**Comment by asturur** [comment]
So fabric provides you a method called onSelect and onDeselect to fire special logic on item selection, before the selection happens.
Is currently not bound to multiselection with drag and with shiftclick, but it will soon.

Other than that, why you just do not fix the stickman to work with multi selection?

**Comment by jfgouda** [comment]
Hi asturur, in my world the stickman is a gas line that end user need to move it around to adjust how the gas line is moving from main gas line to house, so in order to provide custom gas line that user can adjust, i need to keep the circles selectables so user can move them, but also I need to add custom shapes such as rectangles and circles, and allow user to move them around, so in multi-select, I know which element in canvas is custom shapes and which is gas-line lines or circles. All I need from Fabric Js is to allow me to deselect an single object!! I wonder Fabric js is really huge and awesome how come there is no API to deselect a single object? On Selection created even, i wanna go through selected elements and keep what I want to be selected to and dump what what I want. Simply I cannot :)

**Comment by asturur** [comment]
on selection:created, inspect the activeGroup class, pick up what you want, recreate the new activeGroup as you want.
Or simply remove from the activeGroup using `removeWithUpdate` the objects are not of your interest.
