### ISSUE TITLE
PNG with transparency Image clipTo problem

### ISSUE THREAD

**Issue by claudiomedina** [kangax/fabric.js#4408]
Hi,
Please have a look at this. I can't find a way to clip PNG images with transparency without loosing their alpha.

Thank you all for the great work that's been done with fabricjs.

## Version
2.0 beta 7

## Test Case
https://jsfiddle.net/cbjq11oe/

## Steps to reproduce
Load PNG (with transparency) Image 
Add clipTo rectangle to image object

## Expected Behavior
The image transparent pixels stay transparent

## Actual Behavior
The image transparent pixels become opaque

**Comment by asturur** [comment]
You should spend a little bit reading the rect render code in full.
Here are missing 2 concepts:
- the _render function of an object create just the shape of the object itself and ask for rendering, is not setting any color on the canvas
- the canvas default fill color is black.

in your case fill and background are not taking any effect.

https://jsfiddle.net/asturur/cbjq11oe/1/

**Comment by asturur** [comment]
if you want to clip just with a rect and you are using 2.0 beta,

.cropX, .cropY offer a better way to do it.
