### ISSUE TITLE
Resize rect during scaling:object gives drawing issues

### ISSUE THREAD

**Issue by bramchi** [kangax/fabric.js#4412]
## Version
1.7.19 & 2.0 beta

## Test Case
http://jsfiddle.net/qauvp3m1/

## Steps to reproduce
Resize the rectangle into a bigger or smaller rectangle, using one of the handles on the sides or the corners

## Expected Behaviour
The rectangle grows or shrinks smoothly while dragging the handles, and the border width stays the same.

## Actual Behavior
When the rectangle grows in size while dragging the handles, the border starts to disappear.
When the rectangle shrinks in size while dragging the handles, the border is duplicated visually.
When the mouse is released, things look normal again.

**Comment by asturur** [comment]
http://fabricjs.com/fabric-object-caching

Please read this page till the very end.
The answer is there with lot of other usefull informations.

**Comment by bramchi** [comment]
Thanks for pointing me in the right direction!
