### ISSUE TITLE
text.split is not a function with nodejs

### ISSUE THREAD

**Issue by albertyou2** [kangax/fabric.js#4416]
OS: centos 7.2 
node canvas : 1.6.7 
fabric.js: v2.0.0-beta.0~7 

@kangax 
I found that an error comes out randomly.the message is here:

TypeError: text.split is not a function\n    at klass._splitTextIntoLines (/usr/local/bin/app/crawler/node_modules/_fabric@2.0.0-beta0@fabric/dist/fabric.js:22742:24)\n    at klass.initDimensions (/usr/local/bin/app/crawler/node_modules/_fabric@2.0.0-beta0@fabric/dist/fabric.js:21891:27)\n    at klass.initialize (/usr/local/bin/app/crawler/node_modules/_fabric@2.0.0-beta0@fabric/dist/fabric.js:21795:12)\n    at klass.initialize (/usr/local/bin/app/crawler/node_modules/_fabric@2.0.0-beta0@fabric/dist/fabric.js:1727:52)\n    at new klass (/usr/local/bin/app/crawler/node_modules/_fabric@2.0.0-beta0@fabric/dist/fabric.js:1791:23)\n    at /usr/local/bin/app/crawler/node_modules/_fabric@2.0.0-beta0@fabric/dist/fabric.js:13293:37\n    at onLoaded (/usr/local/bin/app/crawler/node_modules/_fabric@2.0.0-beta0@fabric/dist/fabric.js:834:23)\n    at /usr/local/bin/app/crawler/node_modules/_fabric@2.0.0-beta0@fabric/dist/fabric.js:856:11\n    at Array.forEach (<anonymous>)\n    at Object.enlivenPatterns (/usr/local/bin/app/crawler/node_modules/_fabric@2.0.0-beta0@fabric/dist/fabric.js:847:16)' 

I have not found how to  reproduce this issue.

I just run fabric.js like this : 
 
while(1){
       ......
        let jsonObjStr = getObjFromQueue();
        canvas.clear();
        canvas.loadFromJSON(jsonObjStr, () => {
            if (!loadingError) {
                    canvas.renderAll();
                    // to buffer 
                    let bufPng = canvas.nodeCanvas.toBuffer();
                  ......
                }else{
                   ....
                }
            },(o,object,err) =>{
                ....
            });
}

I found that sometimes the error will occur but sometimes will not with a same json object.
Did someone meet this?

**Comment by albertyou2** [comment]
I guess this issue may raise up when  text object json got a number type content in "text" section.
Just like this:
...
"text":128,  // compare to  ->> "text":"128"  
...

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/32092685-dbcba1aa-baf9-11e7-9254-de90f692ff49.png)

fabricjs saves it as a string.
Could be some problem you have in json manipulation somewhere?

**Comment by albertyou2** [comment]
I think this is caused by  -> "text":128 

The json string of objects is created by hand and someone make a mistake.:)
thanks

**Comment by luisgwapo** [comment]
what the fuck?
