### ISSUE TITLE
Should "disable" browser requires for http/https

### ISSUE THREAD

**Issue by thheller** [kangax/fabric.js#4423]
Affects the latest release and latest beta.

https://github.com/kangax/fabric.js/blob/a090a980d06908cba4b7c930e005b440ff6b306b/dist/fabric.js#L27590-L27601

The `./dist/fabric.js` bundle contains a block of conditional JS at the end which is never executed when `document` and `window` are defined (ie. the browser).

The conditional requires however are not properly detected by common bundlers such as `webpack` or `browserify`. Even though the code will never be executed the dependencies established by `require("http")` and `require("https")` will still be bundled.

https://github.com/kangax/fabric.js/blob/a090a980d06908cba4b7c930e005b440ff6b306b/package.json#L23-L28

Some requires are already properly "disabled" for the browser. Consider adding `http` and `https` since they bring in otherwise unused dependencies for packages built by `webpack` and others.

Better yet don't include the conditional block at the end at all for browser builds and create a separate browser bundle.

**Comment by asturur** [comment]
why you left 'url' out of it?

**Comment by thheller** [comment]
Good question. I just didn't see it to be honest. :)
