### ISSUE TITLE
toSVG() result : The position and size of the image are slightly incorrect.

### ISSUE THREAD

**Issue by leesc81** [kangax/fabric.js#4425]
## Version
1.7.19, 2.0 beta

## Test Case
http://jsfiddle.net/SooChangLee/19udf045/5/
![testimage](https://user-images.githubusercontent.com/16448526/32148421-10b2d2b6-bd3a-11e7-8465-9fee27488ac1.png)

# Steps to Reproduce
When you select an image file, it will be displayed at the top of the red rectangle.
After the image is displayed on the top canvas, the toSVG () method is drawn on the bottom canvas.

# Expected behavior
Left and Top of the image are assigned to the upper left side of the rectangle, and the horizontal size is the same as the horizontal size of the rectangle.

## Actual behavior
The top canvas and bottom canvas (toSVG ()) must be the same.
However, the position and size of the image are slightly incorrect.

The larger the image, the better the difference.
(Tested on images of size 5312x2988)

I use fabricjs 1.7.19, but fabricjs 2.0 will also see the same problem.
same result displayed when loaded into Adobe Illustrator.
![test](https://user-images.githubusercontent.com/16448526/32148747-b7d5b6f4-bd3e-11e7-837e-d8b5717ae89c.png)

**Comment by asturur** [comment]
please check fabric docs http://fabricjs.com/docs/fabric.Object.html
for `NUM_FRACTION_DIGITS`.

this issue has been already opened in the past and closed with the same answer.
Always do a full search before opening a new one.
