### ISSUE TITLE
Stretch the background image to canvas size not working with 2.0.0-beta7

### ISSUE THREAD

**Issue by dhavalsisodiya** [kangax/fabric.js#4427]
## Version
2.0.0-beta7

## Test Case
http://jsfiddle.net/dhavalsisodiya/8vLo882n/3

## Steps to reproduce
Add background image in above JSfiddle.  The background image is not stretching with canvas size.

## Expected Behavior
The background image should stretch. 

## Actual Behavior
The background image does not stretch.

Its working the previous version 1.7.19. 
JS fiddle: http://jsfiddle.net/dhavalsisodiya/8vLo882n/4/

**Comment by asturur** [comment]
please check the latest fabricjs changes.

http://fabricjs.com/changelog

in particular the image part:

width and height are used for cropping, use scaleX and scaleW to scale your image to desired dimensions.

**Comment by dhavalsisodiya** [comment]
I have checked the fabric.Image part, but not sure which part should i change?  If you can, please check the question on StackOverflow:
https://stackoverflow.com/questions/47010467/fit-the-background-image-to-canvas-size-with-fabric-js
