### ISSUE TITLE
Object cannot be selected after adding it to the canvas

### ISSUE THREAD

**Issue by Bono-jean** [kangax/fabric.js#4429]
Hey,

Hope the author still answers to issue after all these years!

Here is the context:
I bought a plugin using fabric canvas. For some reasons the plugin uses only one canvas to render two faces of a product (in the demo it's a tee-shirt).

This system doesn't work for me so I had to create a second canvas to display the two faces of my product.

It worked great so far until i noticed that on the second canvas once the image is uploaded it can't be resized and also cannot be selected again.
On the other hand on the first canvas it's working perfectly, i can resize, move and rotate my image, unselect and select again easily without problem. 

The plugin is a little complicated, hope the code below is enough to explain the problem.

_JS: Original canvas creation_
`
canvasObj = new fabric.Canvas('wnpd_background_image');
if( screen.width >200 && screen.width <= 500 )
  {
    canvasObj.setWidth(280);
    canvasObj.setHeight(250);
  }
  else if( screen.width > 500 && screen.width <= 800 )
  {
    canvasObj.setWidth(370);
    canvasObj.setHeight(320);
  }
  else
  {
    canvasObj.setWidth(650);
    canvasObj.setHeight(432);
  }
 //alert(screen.width);
  canvasObj.on( 'selection:cleared', wnpd_clearPanel );
  canvasObj.on( 'object:selected', wnpd_viewObject );
`

_JS: Duplicated canvas creation_

`
canvasObjFront  = new fabric.Canvas('wnpd_background_image_front');
canvasObjFront.setWidth(650);
canvasObjFront.setHeight(432);
    canvasObjFront.selectable = true;
    canvasObjFront.on( 'selection:cleared', wnpd_clearPanel );
    canvasObjFront.on( 'object:selected', wnpd_viewObject );
    if(jQuery('#wnpd_background_image_front').length>0)
    {
        canvasObjFront.setBackgroundImage('someImageUrl', canvasObjFront.renderAll.bind(canvasObjFront));
    }
`

**Comment by asturur** [comment]
please add a working fiddle with a minimal reproducible case
