### ISSUE TITLE
Certain hardware doesn't support WebGL precision highp fragment shader

### ISSUE THREAD

**Issue by ozooner** [kangax/fabric.js#4432]
## Version
2.0 beta

## Test Case
Turns out certain hardware does not support WebGL `precision highp float;`
For given hardware shader with `mediump` or `lowp` works fine

## Steps to reproduce
Amazon Fire TV stick Gen 2
CPU: Mediatek MT8127D 4x ARM Cortex-A7 @ 1.3 GHz
GPU: Mali 450 MP4

## Expected Behavior
To render WebGL filters

## Actual Behavior
![screenshot_20171031_204357](https://user-images.githubusercontent.com/2709373/32243420-de0f4d5e-be7d-11e7-930f-ba9680d99ba1.png)

**Comment by asturur** [comment]
oh well. how to detect that? will be mediump enough for filters? what can we really do with an amazon fire tv stick?

**Comment by ozooner** [comment]
Just a second, creating PR

**Comment by ozooner** [comment]
https://github.com/kangax/fabric.js/pull/4433

**Comment by ozooner** [comment]
So in my test case, only highp isn't supported, however there could be hardware that: 

- doesn't support highp and mediump, only lowp
- passes the webGL supported test, but doesn't support any hardware

So the PR takes care of these hypothetical scenarios as well
