### ISSUE TITLE
is there a way to set timout of http request in  canvas.loadFromJSON (NODE JS) ?

### ISSUE THREAD

**Issue by albertyou2** [kangax/fabric.js#4435]
@kangax 
Here is my json string of objs:
{"objects":[{"height":800,"width":800,"left":0,"src":"https://img10.360buyimg.com/imgzone/jfs/t11716/195/199326543/142848/61622ddd/59e9a0dbN8227bfe4.jpg", ... }
....
]}
There are  many remote images in it.

I found that somtimes the "canvas.loadFromJSON "  gets "stucked " for a long time ( 10 min  + ) and can recovered it's self.

I guess that is because some http request for loading those remote images  is not finished in "loadFromJSON".

If it is so, is there a way to set timeout for  "loadFromJSON"?
Or any global http request timeout setting  here?

Thanks !

**Comment by asturur** [comment]
So we are not doing an http request in the strict sense of the term, we are using the image.src = '' event to trigger the load mechanism in the browser.

while in node we use this other approach:

```javascript
  fabric.util.loadImage = function(url, callback, context) {
    function createImageAndCallBack(data) {
      if (data) {
        img.src = new Buffer(data, 'binary');
        // preserving original url, which seems to be lost in node-canvas
        img._src = url;
        callback && callback.call(context, img);
      }
      else {
        img = null;
        callback && callback.call(context, null, true);
      }
    }
    var img = new Image();
    if (url && (url instanceof Buffer || url.indexOf('data') === 0)) {
      img.src = img._src = url;
      callback && callback.call(context, img);
    }
    else if (url && url.indexOf('http') !== 0) {
      requestFs(url, createImageAndCallBack);
    }
    else if (url) {
      request(url, 'binary', createImageAndCallBack);
    }
    else {
      callback && callback.call(context, url);
    }
  };
```
Depending on what version are you, you are using jsdom 3 or 9, and that would be different since we could use the JSDOM inner image element emulation.

In your case you are using the line `request(url, 'binary', createImageAndCallBack);`

this function here:
```
  function request(url, encoding, callback) {
    var oURL = URL.parse(url);

    // detect if http or https is used
    if ( !oURL.port ) {
      oURL.port = ( oURL.protocol.indexOf('https:') === 0 ) ? 443 : 80;
    }

    // assign request handler based on protocol
    var reqHandler = (oURL.protocol.indexOf('https:') === 0 ) ? HTTPS : HTTP,
        req = reqHandler.request({
          hostname: oURL.hostname,
          port: oURL.port,
          path: oURL.path,
          method: 'GET'
        }, function(response) {
          var body = '';
          if (encoding) {
            response.setEncoding(encoding);
          }
          response.on('end', function () {
            callback(body);
          });
          response.on('data', function (chunk) {
            if (response.statusCode === 200) {
              body += chunk;
            }
          });
        });

    req.on('error', function(err) {
      if (err.errno === process.ECONNREFUSED) {
        fabric.log('ECONNREFUSED: connection refused to ' + oURL.hostname + ':' + oURL.port);
      }
      else {
        fabric.log(err.message);
      }
      callback(null);
    });

    req.end();
  }
```

so you are using  `HTTP = require('http'), HTTPS = require('https'),` which i have no idea how they can be configured.

**Comment by albertyou2** [comment]
@asturur  
I know this issue is closed.But I found a temp solution for this problem : use NPM request module to replace the native HTTP and HTTPS module. Http request with request module can set timeout and even can be cancled ! 
 
I modified  your "request" function as below : 
...
/* 
 notice you can use the name "request" for module request because you already have a name "request" here!
*/
var requestImg = require('request'); 
...

 /** @private */
  function request(url, encoding, callback) {
    /* albertyou */

    let options = {
        "url":url, 
        "method":"GET",
        "timeout":15000, // request timeout in million seconds
        "encoding":null  // important , 
    }

    requestImg(options, function (error, response, body) {
       if(!error && response.statusCode == 200){
           callback(body);
       }
      else{
           callback(null);
      }
    });

i have not much time to do enough test yet , but it seems work fine for me .
Hope this can help someone that meet the same problem like me .

By the way the request module is much convenience  than nodejs native http/https module , you can use request to avoid some strange iusses. Just a suggestion for you.

have a nice day and thank you again!
