### ISSUE TITLE
canvas getting not clear completely on canvas.clear()

### ISSUE THREAD

**Issue by monis01** [kangax/fabric.js#4436]
Hi
I am using fabric and creating various shapes (circle, traingle etc.) sometimes I need to clear my canvas, so I have used `canvas.clear()` option, it shows empty array on doing ` canvas.getObjects()`  but shapes still visible on canvas.
Circle shape
![errz1](https://user-images.githubusercontent.com/7036532/32365594-65d85482-c0a0-11e7-8a5b-239c6ac44fb8.png)
 
`canvas.getObjects()` shows two objects
![errz1 copy](https://user-images.githubusercontent.com/7036532/32365622-840196f8-c0a0-11e7-98ba-a66ec88a0faa.png)

`canvas.clear()` and then `canvas.getObjects()`
![errz2](https://user-images.githubusercontent.com/7036532/32365646-a1626db2-c0a0-11e7-9d60-7c64e8396865.png)

still shape is visible 
![errz2 another copy](https://user-images.githubusercontent.com/7036532/32365663-b9987c00-c0a0-11e7-830b-b1be1a51758b.png)

sometimes, there is extra shape as well
![errz3](https://user-images.githubusercontent.com/7036532/32365675-caae4b82-c0a0-11e7-83c4-fc5c7cf08451.png)

I have checked if there is any reference issue, but no only one `canvas` object.

can anyone give direction what can be the reason, or I have missed something.

Thanks

**Comment by monis01** [comment]
Actually I have some **UNDO** and **REDO** activity to do, so this extra shape comes when value like `{"objects":[],"background":{}}` is passed to `canvas.loadFromJSON`

**Comment by asturur** [comment]
What version of fabricjs are you working?
Can you isolate and replicate on small fiddle?
like clear + consequent loadFromJSON is creating the problem?

Consider loadFromJSON clear by itself if i'm not wrong.

**Comment by monis01** [comment]
Hi 
thanks for the reply.
I have checked  for version but that's minified file we are using unable to find version
Unable to replicate in fiddle, will try again
**clear + consequent loadFromJSON is creating the problem?**  yes sort of 
on various counter  we have snapshot  of various canvas activity(adding object, scaling object, rotating objects etc.) in JSON string values, so on going a step behind or forward, 
1. clear the canvas
2. some checks
3. load that JSON on canvas and then some checks 

so sometimes when it reaches to `canvas.getObjects().length` to `0` it still shows the shape as well as extra boundaries

**Comment by asturur** [comment]
to see the version use the browser console and type `fabric.version`.  it should popout

**Comment by monis01** [comment]
thanks 
Fabric version is : "1.6.2"

**Comment by asturur** [comment]
Is really to old to remember what was wrong. Probably a reference to activeObject is still around.
You should upgrade if you are still working on the project in an active way.

**Comment by monis01** [comment]
Thanks for the reply

After more debugging it comes out to be some overlay issue and clipping. When I create the shape I need some overlaying and clipping around shape.

So I set the property again once the JSON is loaded ( loadFromJSON ). It workded fine.

But Thanks for your help

**Comment by asturur** [comment]
glad you solved.
I'm sorry i have really no time to support anything than 2.0 and altest 1.x

**Comment by monis01** [comment]
Np
I understand, all I need was a direction what it can be, so I turned here and that refernce part helps me to debug more and more.
Thanks

**Comment by JonathanDn** [comment]
@asturur I tried to clear the canvas like so - `canvas.getObjects().length` to `0` but it did not work.

Using FabricJS v 2.6.4

**Comment by asturur** [comment]
what is wrong with canvas.clear()?

or `canvas.remove.apply(canvas, cnavas.getObjects())`
