### ISSUE TITLE
How to change Image starting position without losing Boundary area in Fabricjs

### ISSUE THREAD

**Issue by Vivek-KT** [kangax/fabric.js#4438]
Here, i have to achieve Image resizing within boundary/selected area in fabric-JS. I have create Replace existing Image with New Image with using Fabric-JS.

[JsFiddle](http://jsfiddle.net/vivekkt91/r09mxdyc/1/)

```
var canvas = new fabric.Canvas('c');

function addImage(imgLink) {
    fabric.Image.fromURL(imgLink, function(img) {
        img.set({ 'left': 50 });
        img.set({ 'top': 50 });
        img.scaleToWidth(100);
        img.scaleToHeight(100);

        var objs = canvas.getObjects();
        if (objs.length) {
            objs.forEach(function(e) {
                if (e && e.type === 'image') {
                    e._element.src = imgLink;
                    canvas.renderAll();
                }
            });
        } else canvas.add(img);
    });
}

addImage('http://fabricjs.com/lib/pug.jpg');

// file upload
var span = document.querySelector('#span');
span.onchange = function(e) {
    var file = e.target.files[0];
    var reader = new FileReader();
    reader.onload = function(file) {
        addImage(file.target.result);
    }
    reader.readAsDataURL(file);
}
```
But, I need to Upload Image and modify its position without changing selected area.
![initial_picture](https://user-images.githubusercontent.com/4013115/32405035-5b6cabea-c183-11e7-80a4-7ff941ec5dfe.png)
Original Image:
![next_picture](https://user-images.githubusercontent.com/4013115/32405044-8834bc76-c183-11e7-87a9-fdb071007560.png)
I need to zoom-in/resize position of image without changing Selected/Boundary area. For example, One image have 50x50 pixels but its will changes position within 50x50 pixel.Is it possible in fabricjs events?.

Thanks for your advance help

**Comment by asturur** [comment]
Please let's handle this on stackoverflow. open a question and post the link here. It does not look like a library bug problem
