### ISSUE TITLE
more space appear on RTL text

### ISSUE THREAD

**Issue by palize** [kangax/fabric.js#4439]
Hi,
Thank for this great work.
on rtl text appear spaces on side of text.

![image](https://user-images.githubusercontent.com/2226899/32409533-f2c8d24a-c1c2-11e7-9053-185ea6df4671.png)

**Comment by asturur** [comment]
what version of fabric are you using?

**Comment by palize** [comment]
1.7.6

**Comment by palize** [comment]
fixed in new version.

**Comment by asturur** [comment]
while RTL as an input is not supported, the spacing and cursor of text that is composed of graphemes is working now.

the issue you had was not rtl related.

**Comment by YaakovHatam** [comment]
@palize  please look at the issue #2374 i am developing a RTL version please test it
