### ISSUE TITLE
Rectangle base corner and corner at the cursor does not preserver their location, see video

### ISSUE THREAD

**Issue by Kampii** [kangax/fabric.js#4443]
The base point of the rectangle is not preserved after moving the mouse. Also, the 2nd corner of the rectangle does not stick with the mouse. Please see this video: https://www.dropbox.com/s/kzvu6k2gbku0qm6/FabricjsRectangleBug.mov?dl=0. 

## Version
2.0.0-beta

## Test Case
http://jsfiddle.net/a7mad24/aPLq5/

## Steps to reproduce
Just like in video

## Expected Behavior
Base point always remains at the some coordinate. The 2nd point always sticks with the mouse cursor.

## Actual Behavior
See the video

**Comment by asturur** [comment]
please this is not a bug with the library but your application code.
Open a question on stackoverflow inserting the snippet there in the stackoverflow snippet system and let's fix it there after you post here the question link

**Comment by Kampii** [comment]
Hi @asturur, I posted the question [here](https://stackoverflow.com/questions/47203298/rectangle-base-corner-and-corner-at-the-cursor-does-not-preserver-their-location)
