### ISSUE TITLE
fabric group does't work with the subTargetCheck attribute

### ISSUE THREAD

**Issue by jefybai** [kangax/fabric.js#4444]
Create a group and set subTargetCheck as true, 
then convert it to json,and reload the Json,
fabric does not work.

let svgGroup = new fabric.Group(svgs, Object.assign({}, {
                utype: 'svg',
                left: canvas.width / 2, top: canvas.height / 2,
                subTargetCheck: true,
                id: Date.now() + String.fromCharCode(65 + Math.floor(Math.random() * 26))})
            );

        canvas.toObject(['subTargetCheck', 'utype']);

--------------------------------------------------------
    then reload the json

      let draftingObj = canvas.getObjects().filter(item => item.utype == 'svg')[0];
                    draftingObj.on('mousedown', (e) => {
               
                            })

fabric.require.js:3 Uncaught TypeError: Cannot read property 'tl' of null
    at klass._getImageLines (fabric.require.js:3)
    at klass.eval [as _getImageLines] (makeAssimilatePrototype.js:15)
    at klass.containsPoint (fabric.require.js:3)
    at klass.eval [as containsPoint] (makeAssimilatePrototype.js:15)
    at klass.containsPoint (fabric.require.js:3)
    at klass._checkTarget (fabric.require.js:3)
    at klass._searchPossibleTargets (fabric.require.js:3)
    at klass._searchPossibleTargets (fabric.require.js:3)
    at klass.findTarget (fabric.require.js:3)
    at klass.__onMouseMove (fabric.require.js:3)
_getImageLines @ fabric.require.js:3
(anonymous) @ makeAssimilatePrototype.js:15
containsPoint @ fabric.require.js:3
(anonymous) @ makeAssimilatePrototype.js:15
containsPoint @ fabric.require.js:3
_checkTarget @ fabric.require.js:3
_searchPossibleTargets @ fabric.require.js:3
_searchPossibleTargets @ fabric.require.js:3
findTarget @ fabric.require.js:3
__onMouseMove @ fabric.require.js:3
_onMouseMove @ fabric.require.js:3

**Comment by asturur** [comment]
interesting.
i think i know where the bug is. i ll flag as a bug and see if i can fix it.
Should be a problem of 1.7 too to backport.

**Comment by asturur** [comment]
What version are you using?

**Comment by jefybai** [comment]
I'm using version: "1.7.17", but the latest version have same problem

**Comment by takaobaltazar** [comment]
Hi,

I was also encountering this issue, using the latest version of fabric : 1.7.19.

[https://stackoverflow.com/questions/47207180/sub-target-property-of-fabric-js-group-is-not-being-exported](url)

**Comment by durga598** [comment]
[Working](https://jsfiddle.net/durga598/n1zs07rw/2/) in 1.7.3 , not after that.

**Comment by takaobaltazar** [comment]
Hi @durga598 ,

I tried the 1.7.3 version of fabric, and it works. Thanks for this info.

**Comment by ThakurKarthik** [comment]
@asturur I currently see this issue in 3.6.2 version.We are trying to migrate from 1.5.0 to this stable version 😃
```
TypeError: Cannot read property 'tl' of null
    at klass._getImageLines (fabric.js:15366)
    at klass.containsPoint (fabric.js:15289)
    at klass.containsPoint (fabric.js:9857)
    at klass._checkTarget (fabric.js:10593)
    at klass._searchPossibleTargets (fabric.js:10622)
    at klass.findTarget (fabric.js:10573)
    at klass.__onMouseMove (fabric.js:11913)
    at klass._onMouseMove (fabric.js:11492)
```
Iam just drawing a line.

**Comment by asturur** [comment]
can you replicate this in a minimal fiddle? it deserves a new issue.

**Comment by itsdeekay** [comment]
Hi I am facing same issue with latest fabric. Code can be checked at https://jsfiddle.net/L09qmbu8

**Comment by asturur** [comment]
@itsdeekay your fiddle is so much elaborate.
What is acutally the problem, can you focus around it instead of blurring and doing other things?
