### ISSUE TITLE
No provision to select a object which inside another object?

### ISSUE THREAD

**Issue by ManjunathBiradar** [kangax/fabric.js#4446]
## Version
1.6.3

## Steps to reproduce

1.  Draw a small traingle
2.  Draw  a sqaure
3. Make triangle fit within the bounding box of square.
4. Now try to select a triangle.

## Expected Behavior
Any object within another object's boundary should be selectable(Active state).
## Actual Behavior
Any object within another object's boundary is not selectable and only larger object gets activated upon click.

**Comment by asturur** [comment]
We are not supporting version older than 1.7.19 or 2.0 beta.

If the triangle is under the square you cannot select it, the square will be selected.
