### ISSUE TITLE
fabric.Object.clone rounds the scaleX, scaleY values 

### ISSUE THREAD

**Issue by Luca-A-Mueller** [kangax/fabric.js#4447]
## Version
1.7.14

## Test Case
http://jsfiddle.net/fm65kgpq/

## Steps to reproduce

1. create Image
2. clone Image
3. add the cloned object to the Canvas

## Expected Behavior

The cloned objects properties are preserved druing a cloning operation. 

## Actual Behavior

fabric.Object.clone has the sideeffect of rounding the objects scaleX, scaleY values when cloning very large images. This results in an unwanted scaling of cloned objects. A simple workaround is to reuse the scale values of the old object.

`cloned.scaleX =  old.scaleX;
 cloned.scaleY =  old.scaleY;`

**Comment by asturur** [comment]
Hi,
object.clone() and object.toObject(), round everything to 2 decimals.

Having higher precision is a feature, no work around needed.

please check here: http://fabricjs.com/docs/fabric.Object.html

right after `_uid`
