### ISSUE TITLE
Unable to set different line height to different lines

### ISSUE THREAD

**Issue by ranjeetrajputv2** [kangax/fabric.js#4448]
Unable to set different line height to different lines

**Comment by asturur** [comment]
please add a reproducible issue case.

**Comment by ncou** [comment]
Not really sure what you are asking, but the settings for the line height is applyed on all the lines in the text component. You can't use different line height value.

**Comment by asturur** [comment]
i m amazed you understood he is speaking about text. i was sure we were talking about fabric.Line.

**Comment by asturur** [comment]
nicolas did you request a fabricjs sticker?

**Comment by ncou** [comment]
no i didn't requested a sticker, how can i do this ?

**Comment by asturur** [comment]
send me your address by email, i still did not ship yet.

**Comment by ranjeetrajputv2** [comment]
Yes, I am talking about TextBox.  can I build this functionality over fabricJs to set different lineHeight of different text lines in TextBox

**Comment by asturur** [comment]
You have to build it by yourself, is not a supported feature. And is not very easy.
