### ISSUE TITLE
setShadow should not render shadow for transparent background of PNGs

### ISSUE THREAD

**Issue by uschmann** [kangax/fabric.js#4458]
Hi,
 
we upgraded fabricJS from version 1.4.12 to 1.7.19.
We offered the option to the user to apply a dropshadow to 
a transparent image object.

The behaviour of setShadow seems to have changed.
Since the update the dropshadow is also rendered for the transparent
pixels of the image. I attach two screenshots to make it more clear.

## Version
1.7.19

## Steps to reproduce
Create a image element from a PNG with transparent background
and apply a shadow to the object.

## Expected Behavior
The shadow should have the form of the non transparent pixels of the image,

![image1](https://user-images.githubusercontent.com/4057692/32717180-fd19f886-c858-11e7-8975-06bbf60a3e0a.png)

## Actual Behavior
The shadow is also generated for the transparent background of the image.

![image2](https://user-images.githubusercontent.com/4057692/32717184-00568384-c859-11e7-8916-821b78dcbbbf.png)

This is the image we used to test:
![605920](https://user-images.githubusercontent.com/4057692/32717203-0d501dca-c859-11e7-8afa-82b9bd85ab98.png)

We used *fabric.Image.fromURL* to load the image.

This is the code to set the shadow:
```javascript
this.img.setShadow({
                        color: hexToRGBA(this.templateElement.shadow_color, this.templateElement.shadow_opacity),
                        blur: parseFloat(this.templateElement.shadow_blur),
                        offsetX: parseInt(this.templateElement.shadow_x),
                        offsetY: parseInt(this.templateElement.shadow_y)
                    });
```

**Comment by asturur** [comment]
https://jsfiddle.net/04bbmbat/1/

looks perfectly fine to me.
Please replicate with a fiddle or close the issue. thanks.
You are probably doing something else in the application in addition to set the shadow. Some pixel is drawn or fabric could not pull out a shadow.
