### ISSUE TITLE
After change font size / coordonate of cursor mouse and resize position is false

### ISSUE THREAD

**Issue by timactive** [kangax/fabric.js#4459]
## Version
1.7.2

## Test Case
![issue_fabricjs_coordonate_cursor](https://user-images.githubusercontent.com/3832141/32731189-761dd0e2-c889-11e7-9e30-9380950530f1.gif)

## Steps to reproduce

1 Go to http://fabricjs.com/kitchensink

2 Select first object to have active object selected

3 Execute the custom code

```
var obj = canvas.getActiveObject();
obj.set("fontSize", 12).setCoords();
canvas.renderAll();
```

4 See the cursor corner position is false and also resize cursor is not display

![capture d ecran de 2017-11-13 15-50-48](https://user-images.githubusercontent.com/3832141/32731557-797ea210-c88a-11e7-8570-cfe4036d170d.png)

**Comment by asturur** [comment]
if you are on 1.7.2 i cannot really fix it.
Please could you verify that the problem persist on newer 1.7.20?

**Comment by asturur** [comment]
Ignore my last message, i see you refer to kitchensink and i have no idea why you reported 1.7.2

I just pushed up a fix on fabricjs.com, can you see if your problem is fixed too?

**Comment by timactive** [comment]
Hi,
Work fine with your fix! 
thank @asturur (i will contribute(financial) on project when the projet is finish).
