### ISSUE TITLE
How to compute path coordinates / position inside a fabric Group after an object:modified event ?

### ISSUE THREAD

**Issue by takaobaltazar** [kangax/fabric.js#4460]
## Version
1.7.20

## Test Case
https://jsfiddle.net/w4wzgvLq/

## Steps to reproduce
Move a fabric Group which consist of path.

## Expected Behavior
Auto or Manual compute of coordinate / position of path inside a fabric Group after an object:modified event (e.g. rotate, move, scale)

## Actual Behavior
Path inside the group does not compute automatically for its new coordinates / position.

**Comment by asturur** [comment]
you want to update top and left to current canvas position?

**Comment by takaobaltazar** [comment]
Hi astuur, 

Yep. I actually wanted to automatically compute for the path updated top and left position , when group is moved in canvas.

The purpose is that, I have a feature wherein I can manipulate the path (through edit of head, center and tail) while on panning mode.

**Comment by asturur** [comment]
to do that, you need to get the group transformMAxtri

```var m = group.calcTransformMatrix();```

then take your path top and left

```var point = new fabric.Point({ x: path.left, y: path.top });```

then transform it:

```var canvasPoint = fabric.util.transformPoint(point, m);```

**Comment by designlook** [comment]
Thanks @asturur  very useful!
