### ISSUE TITLE
Weird things at resize

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4461]
## Version
2.0 beta 7 (last commit)

## Test Case
https://cl.ly/3t1m1h21201q

## Steps to reproduce
In our app but also in kitchen (see video in test case) we have an issue at resize: objects are top-left but they react like center. Then after a while they start doing crazy stuff (moving a little bit), and become unselectable (canvas rendering problem)

## Expected Behavior
This issue is as this since several commit. We add to roll back to around start of October to get a version of Fabric that's ok, like you can resize objects and they don't move without reason. 

Do you have an idea where this can come from?

Thanks!

**Comment by asturur** [comment]
i never noticed it.
does it happen with textbox only?

**Comment by blobinabottle** [comment]
We also have it on shapes (in our app), but we reset the scale to 1 on the scaling event. I could not reproduce it with shapes in kitchenDemo

**Comment by blobinabottle** [comment]
To give you an idea this is what we do in our app:
https://jsfiddle.net/mt96ko6g/1/
We do that to avoid the bug with the controls borders that have a weird inconsistent padding when scaling. But with last version (built using the last commits, it doesn't work anymore, the scaling become crazy).

**Comment by blobinabottle** [comment]
If you remove the scaling function, you'll end up with something like this when scaling objects. A padding that's not correct (It's -1, not 1 or 10).
![capture d ecran 2017-11-14 a 18 42 04](https://user-images.githubusercontent.com/8090162/32795281-881097e8-c96b-11e7-88cf-dfd6a88f5458.png)

**Comment by asturur** [comment]
i ll be on this asap, got busy days.
I have no idea what is the `bug with the controls borders that have a weird inconsistent padding when scaling` is.
can you specify better? i'll look at the fiddle to.

( do you use the stroke in your app? if you do not use it, do you set it to 0 ? that helps a lot, the strange padding is often a transparent stroke much scaled )

**Comment by blobinabottle** [comment]
AAaaah you're right. If I set strokeWidth to 0, I don't get the strange padding. Thanks!

**Comment by blobinabottle** [comment]
I reproduced my original issue on shapes too. Copy paste this in kitchenSink and then resize rect or circle. It's moving weirdly... On our older build of fabric beta 2 it's working. So do you recommend we change our logic or do you think it's a bug somewhere? 
```
canvas.clear();
canvas.remove(canvas.getActiveObject());

var rect = new fabric.Rect({
  width: 50,
  height: 50,
  left: 50,
  top: 50,
originX:'left',
originY:'top',
  fill: 'rgb(255,0,0)'
});

var circle = new fabric.Circle({
  radius: 40,
  left: 50,
  top: 50,
  fill: 'rgb(0,255,0)',
  opacity: 0.5

});

canvas.add(rect, circle);

canvas.on("object:scaling", function(e){
var obj = e.target
obj.set({width: obj.width* obj.scaleX, height: obj.height* e.target.scaleY});
obj.scaleX = obj.scaleY = 1;
obj.setCoords();
canvas.requestRenderAll();
});
```

**Comment by asturur** [comment]
So regarding this issue:
 - the padding -1 should not exist, the strange border is the stroke that is transparent. This is something that deserver a page of `common mistakes` on the fabricjs websites

 - the code you give me behaves good if you disable the `noscaleCache`. Since the object is scaling, cache is not changed (because noscaleCache is true) but you are resetting scale and changing width and height so the code cannot really help you in this case. This will be added on the object_cache page. please try this code in kitchensink

```javascript
canvas.clear();
canvas.remove(canvas.getActiveObject());

var rect = new fabric.Rect({
  width: 50,
  height: 50,
  left: 50,
  top: 50,
originX:'left',
originY:'top',
  fill: 'rgb(255,0,0)',
  noScaleCache: false,
});


canvas.add(rect);

canvas.on("object:scaling", function(e){
var obj = e.target
obj.set({width: obj.width* obj.scaleX, height: obj.height* e.target.scaleY});
obj.scaleX = obj.scaleY = 1;
obj.setCoords();
});
```

this solves the drawing problem, but the jumping and wrong coordinate problem is still there. There is nothing wrong in your scaling handler, i think we introduced some bug. it happens just for corners MB, MR and BR.

I'll try to figure out.

**Comment by blobinabottle** [comment]
I confirm everything is cool except the jumping on MB,MR, BR. I hope you'll find this nasty bug :)
