### ISSUE TITLE
Text and Textbox shared the same reference to _dimensionAffectingProps

### ISSUE THREAD

**Issue by JSteunou** [kangax/fabric.js#4464]
## Version
1.7.x & 2.0 beta

## Test Case
http://jsfiddle.net/zrkwzzk1/2/

## Steps to reproduce
follow the fiddle ;)

## Expected Behavior
properties should not be affected across classes

## Actual Behavior
properties are affected across classes

I'm afraid that's a big bug affecting a lot of classes and properties because of inheritance. Array and Object should never be define as class attribute because of the nature of inheritance like fabric does (it's the same issue with Backbone.js extend for those familiar with Backbone) but always created during the `initialize` call.

Text is quite affected by Textbox on `_dimensionAffectingProps` which is used to compute `shouldClear` and affect `render`.

Using hundreds of objects it has severe performance penalty. I have a personal use case with nearly ~100% performance difference, because `shouldClear` is involved in `saveState` call which loop over every objects: this lead to a multiple nested loop.

Unfortunately maybe other bugs and perf issues are hidden in the hood of this shared reference issue. All classes should be reviewed.

**Comment by asturur** [comment]
we can just clone the array on a per class basis!
should be fine.

**Comment by asturur** [comment]
![testp](https://user-images.githubusercontent.com/1194048/32962248-0b25fad0-cbcc-11e7-8c5c-73198e7dd1e3.gif)
