### ISSUE TITLE
2.x add object not centering when canvas zoomed

### ISSUE THREAD

**Issue by h3786010** [kangax/fabric.js#4474]
## Version
2.0

## Test Case
http://jsfiddle.net/Da7SP/727/
## Steps to reproduce
1. new some object
2. setZoom() not equal "1"
3. call centerObject()
4. add()
## Expected Behavior
http://jsfiddle.net/Da7SP/729/
Ref: https://github.com/kangax/fabric.js/pull/2021/commits

**Comment by asturur** [comment]
Please can you explain yourself better?

**Comment by asturur** [comment]
http://fabricjs.com/docs/fabric.StaticCanvas.html

Please read the methods that start with `viewportCenter`
