### ISSUE TITLE
toDataUrl modifies original canvas

### ISSUE THREAD

**Issue by mattboll** [kangax/fabric.js#4477]
## Version
1.7.19

## Test Case
https://jsfiddle.net/okuLm4or/1/

## Steps to reproduce
I set css dimensions, width and height on canvas, i use toDataUrl with a multiplier for high dpi screens and the original canvas is "multiplied" too, i have to reset css dimensions to have the right canvas size
Comment canvas.toDataURL in jsfiddle to see the right size.

## Expected Behavior
not modifying the original canvas when using toDataUrl

**Comment by asturur** [comment]
i think we fixed this in 2.0 and being a bug we should backport it to 1.7 too.

Please if you are developing a new app or even just playing around with fabricjs use the new 2.0 version

**Comment by mattboll** [comment]
Yes you're right it's working fine with 2.0. I didn't want to use a not released version but I'll try it.

**Comment by asturur** [comment]
i fixed it in the 1.7 version now.
A question, why are you setting different css size for hidi? fabricjs does it automatically.

**Comment by mattboll** [comment]
what do you mean ? I don't use different css for hidpi

**Comment by asturur** [comment]
fabric read the hidpi value from window.devicePixelratio.
then scales the canvas and keep css smaller.

so when you create a canvas that is 1000x1000 on a macbook pro you get a 2000x2000 canvas fitted in a 1000x1000 space. unless you ask differently setting `enableRetinaScaling: false`

**Comment by mattboll** [comment]
I need to have a big canvas because I need a good quality of images but I also need it to appears fully on screen so I set the same css value for hi dpi or normal dpi screens

**Comment by asturur** [comment]
you will loose lot of performances in this way.

to get a bigger image use the dataUrl multiplier function.

also the effect is multiplied on hidpi screens.
that means that with your current solution you are using twice the hdipi resolution

**Comment by mattboll** [comment]
My full usecase is : I import images to canvas, move them, convert canvas to image, print the image.

if I import a 1800x1200 image to canvas and then use dataUrl multiplier, from 600x400 to 1800x1200 the image will be a lot uglier, unless I'm wrong the quality should be the same with my solution (for my use case, quality is much more important than performance as long as it is usable)

Actually I've disabled high dpi right now because I don't need a double size dpi for retina and it adds specific work to manage it.

**Comment by asturur** [comment]
dataurl gets re rendered from scratch.

so if you draw shapes and images on a 100x100 canvas and then export to 10.000 x 10.000,
the final result is like if you worked with the same assets on 10.000 x 10.000

this is good to know, nothing happen if you work all the time with a bigger canvas

**Comment by mattboll** [comment]
oh, ok thanks for the information :)
