### ISSUE TITLE
Freehand drawing prevents drawing of point

### ISSUE THREAD

**Issue by newtriks** [kangax/fabric.js#4480]
## Version
2.0

## Test Case
https://jsfiddle.net/q6hw8m3n/

## Steps to reproduce
Configure canvas with `drawingMode` enabled. Click on the canvas.

## Expected Behavior
A single point to have been drawn on the canvas.

## Actual Behavior
A single point flickers briefly into view then disappears. 

This actually worked in V1 https://jsfiddle.net/oz31LqLq/1/ so I'd suggest this as a regression. Funnily enough I have vague recollections of this being an issue at one point in a previous V1 build but cannot find a corresponding issue, but may have missed it?

**Comment by asturur** [comment]
https://github.com/kangax/fabric.js/commit/b1f0f67669b054a515c72353bb9fedde5f30c717

i may have done something wrong in this commit.
I first fixed the point not being a point but an oval in a commit, then i went to fix the edges that were overlapping and i may have introduced a regression.
