### ISSUE TITLE
ActiveSelection moving objects

### ISSUE THREAD

**Issue by wferris722** [kangax/fabric.js#4482]
## Version
2.0.0_rc1

## Test Case
http://jsfiddle.net/wferris722/gv7z18kq/

## Steps to reproduce
Select all items, deselect triangle

## Expected Behavior
All items remain in same canvas relative position

## Actual Behavior
Items still in selection (square, circle) are moved down by 1/2 the difference in ActiveSelection bounding box height.
Only happens when removing an object that defines the bottom edge of the bounding box. 

## Before
![image](https://user-images.githubusercontent.com/10579271/33048390-78f19e62-ce0f-11e7-8e78-d3e6eb1765a5.png)

## After
![image](https://user-images.githubusercontent.com/10579271/33048400-8420851e-ce0f-11e7-989a-548da8f86cac.png)

**Comment by wferris722** [comment]
Update: 
Issue does not occur if selection is scaled prior to deselecting triangle

**Comment by asturur** [comment]
i think the root cause is the same as #4461, verifying
