### ISSUE TITLE
_removeCharsFromTo is not a function

### ISSUE THREAD

**Issue by redlive** [kangax/fabric.js#4483]
## Version
2.0

## Test Case
http://jsfiddle.net/redlive/17kvcudu/

## Steps to reproduce
Run JSFiddler and open a console.

## Expected Behavior
Chars between  SelectionStart and SelectionEnd should be removed.

## Actual Behavior
Throws a JS error
**_this._removeCharsFromTo is not a function_**

![screen shot 2017-11-21 at 3 48 03 pm](https://user-images.githubusercontent.com/5912122/33102816-67a15bb0-ced3-11e7-9441-1c8f769f6cd3.png)

![screen shot 2017-11-21 at 3 55 03 pm](https://user-images.githubusercontent.com/5912122/33102999-659b27e6-ced4-11e7-9355-7d39fb697dec.png)

**Comment by asturur** [comment]
ahi this is a blocker.
Going to check what i can do. i belive this was supposed to be removed since it was supporting the user input on del/backspace that now are handled differently.

Going to check if i can do something for it today

**Comment by asturur** [comment]
I m working on a fix.
Is important to understand that that method was bound to deletion key pressing and was not really meant to be called alone.

I think the best thing to do is to change removeChars(e) in removeChars(start, end).

This would be a breaking change. Being the method broken i think i can consider it doable.

**Comment by redlive** [comment]
Thank you for working on the bug. removeChars(start, end) would even better.

**Comment by asturur** [comment]
i have to move it on the Text.prototype

**Comment by asturur** [comment]
mmm is too much work.
I'll move it later since is not breaking.
Many Itext methods can be used on Text too, without interactivity since Text support style.

**Comment by redlive** [comment]
So when you think **removeChars(start, end)** function will be available?

**Comment by asturur** [comment]
i pushed it out yesterday. try latest version on npm or here on the release
section.

**Comment by redlive** [comment]
Thank you... Working well for now...
Quick question... Since I've switched the library version to _**2.0.0-rc.3**_, what will be the right function to use instead of removeChars()? 
Is it **insertNewStyleBlock** ?

**Comment by asturur** [comment]
removeChars should still be there, fixed to work with start, end and not
with this.selectionStart and this.selectionEnd.

Can't you find it?

**Comment by redlive** [comment]
Sorry... I mean insertChars

Best regards,
Eugene Vilder
