### ISSUE TITLE
Resize textbox event

### ISSUE THREAD

**Issue by msbir** [kangax/fabric.js#4485]
What is the event that handles the textbox resize?

When writing a text in Hebrew (RTL) and changing the font (I register the fonts) the width of the textbox is not changing but the text width is getting changed.
When resizing the textbox (bigger or smaller) the width of the textbox is getting fixed by the text width

![hebrewtext](https://user-images.githubusercontent.com/29798064/33140744-8dcbd0e0-cfb9-11e7-83b0-5f0ee53baf74.png)

In english text it all looks good

![englishtext](https://user-images.githubusercontent.com/29798064/33140759-93fad254-cfb9-11e7-86fa-ffb1e58bb81f.png)

I am trying to handle this problem.
any suggestions?

**Comment by asturur** [comment]
can you inspect the '_text' property? how does ot looks like?

**Comment by msbir** [comment]
Do you mean this?

![screen shot 2017-11-22 at 19 49 45](https://user-images.githubusercontent.com/29798064/33142288-94ff8104-cfbe-11e7-8a7e-a06688d707a7.png)

**Comment by asturur** [comment]
If you are using 1.7, there is no way around it.
You can try with 2.0

Please specify the version as suggested in the  issue template

**Comment by msbir** [comment]
Sorry about that
I am using 1.7.6

**Comment by msbir** [comment]
Can you tell me what the event that triggers the resize the textbox?

It seems that when adding the text and resize the textbox the text seems to handle itself to fix the textbox width

**Comment by asturur** [comment]
there is an onscale event.
you are using iText not textbox looks loke

fabric 1.7 badly support text outside english/latin.

i close the issuse, since there is nothing to solve, continue to post if you need
