### ISSUE TITLE
Possible bug in Version 2 RC1

### ISSUE THREAD

**Issue by jfgouda** [kangax/fabric.js#4486]
## Version
2.0 RC1

Try to drag the green circle around the line is not following the circle coords:
**JS fiddle with version 2 RC-1**: http://jsfiddle.net/jgouda/3d2yahw2/1/ 

Working good
**JS fiddle with version 2 Beta-7**: http://jsfiddle.net/jgouda/3d2yahw2/
**JS fiddle with version 1.7.20**: http://jsfiddle.net/jgouda/2quqy8y9/

Thanks

**Comment by asturur** [comment]
same bug as #4461
