### ISSUE TITLE
Events with a container and stopPropagation or preventDefault

### ISSUE THREAD

**Issue by ombr** [kangax/fabric.js#4487]
I am trying to integrate a FabricJS Canvas inside a viewer.
I would expect the FabricJS Canvas to catch mouse/touch events so the container viewer does not see them.

## Version
1.7.20

## Test Case
https://codepen.io/Lucboissaye/pen/LOmjzq

## Steps to reproduce
Try to draw, it will only display a point.

## Expected Behavior
I should be able to draw and do not get any logs from the container.

## Actual Behavior
FabricJS does not work and the event listener on the container is called.

Is there any way to work around this behavior ?

**Comment by asturur** [comment]
can you make a fiddle with simple JS? no CS or Sass

**Comment by ombr** [comment]
@asturur here is the jsfiddle pure JS/CSS/HTML version (you can always see the compiled version on codepen :wink::

https://jsfiddle.net/phdmuuwy/

**Comment by asturur** [comment]
Yes is true i can see the non transpiled version.
But i can't change it.

90% of the request reason is that i move faster with jsfiddle and i prefer to work on that.

**Comment by ombr** [comment]
I understand :wink:

**Comment by asturur** [comment]
https://jsfiddle.net/phdmuuwy/4/

i removed the jquery handling layer and everything works.
I have no idea what jquery does with the event and how it manages it.
Removing e.stopPropagation was not helping.

In this fiddle the events are registered normally, they get processed by the container and everything else flow normally.
