### ISSUE TITLE
How to set transparent background on Text when background was changed.

### ISSUE THREAD

**Issue by lachezargrigorov** [kangax/fabric.js#4488]
## Detailed description
When I add a Text object with default options. The text is black on transparent background.

```javascript
{
fill : '#000000',
backgroundColor : '#ffffff'
}
```

If I change the backgroundColor once I can't make it transparent again even if I set it to #ffffff again. It may have background color opacity option but I can't find it neither in the documentation nor in the Text Object itself.  

<img width="248" alt="screen shot 2017-11-23 at 1 33 20" src="https://user-images.githubusercontent.com/3510976/33154304-1f0a8f16-cff0-11e7-801e-e31e9f3cad9b.png">

## Question
How to set text background color opacity or transparent background?

**Comment by asturur** [comment]
why not `backgroundColor=''` ?

**Comment by lachezargrigorov** [comment]
'',null and transparent do the job. Thank you!

How can I change the text background color opacity?  I've tried with rgb(255,255,255,0.2) already but it just set it to black and ignore the alpha channel.

**Comment by asturur** [comment]
because ` rgb(255,255,255,0.2) ` is an invalid color.

` rgba(255,255,255,0.2) ` should work
