### ISSUE TITLE
Drag and Drop Image issue on 2.0.0-beta.7 version

### ISSUE THREAD

**Issue by dhavalsisodiya** [kangax/fabric.js#4489]
## Version
2.0.0-beta.7

## Test Case
http://jsfiddle.net/dhavalsisodiya/w8kkc/412/

## Steps to reproduce
Drag & Drop the image in canvas.

## Expected Behavior
http://jsfiddle.net/Ahammadalipk/w8kkc/185/

## Actual Behavior
After Drag & Drop, you can see that whole image isn't included in canvas. Only the part of it was included.

**Comment by asturur** [comment]
is a breaking change of 2.0
You cannot set width/height of the image but you have to use the scale factor to make it smaller.
If you need help to translate that old 1.5 code, please open  a question on StackOverflow and post it here.

**Comment by dhavalsisodiya** [comment]
https://stackoverflow.com/questions/47456523/drag-and-drop-image-issue-on-new-fabric-js

Also one more request, where can i find the examples of new version (like how to add image etc.) or related document? 
As i have refer this: http://fabricjs.com/docs/fabric.Image.html but not able to understand that.

**Comment by asturur** [comment]
Those docs are plain api description, may need also some cleanup.
The code is similar between 1.x and 2.0, some things have changed.

Please start from http://fabricjs.com i think i updated almost everything.
