### ISSUE TITLE
Textbox hoverCursor is wrong after changing text

### ISSUE THREAD

**Issue by taras-d** [kangax/fabric.js#4493]
## Version
2.0

## Test Case
https://jsfiddle.net/qhn3jv35/2/

## Steps to reproduce
- Create text box with `hoverCursor: 'pointer'`
- Hover over text - the mouse cursor is _pointer_ as expected
- Change text, unfocus text and hover over text again - the mouse cursor **is not _pointer_**

## Expected Behavior
Hover cursor saved and restored after text change

## Actual Behavior
Hover cursor is not saved after text change

**Comment by asturur** [comment]
i think i fixed it with a commit of yesterday. can you check on fabricjs.com?

**Comment by taras-d** [comment]
I checked it in latest version **2.0.0-rc.1**

**Comment by taras-d** [comment]
Looks like there is a typo in [_restoreEditingProps](https://github.com/kangax/fabric.js/blob/0df3f55dc3763af5d613369de6a80858862ec920/src/mixins/itext_behavior.mixin.js#L575) function.

this._savedProps.**overCursor** _should be_ this._savedProps.**hoverCursor**

**Comment by asturur** [comment]
please verify if the problem persist on fabricjs.com/kitchensink

**Comment by taras-d** [comment]
Problem still persist

**Comment by asturur** [comment]
i misunderstood the problem.
Fix coming

**Comment by asturur** [comment]
fixed
