### ISSUE TITLE
Node-Canvas support

### ISSUE THREAD

**Issue by Sparki2002** [kangax/fabric.js#4494]
Hi,
I'm using (have to use) version 2.0.0 rc1
Can you please add node-canvas support again?

**Comment by asturur** [comment]
Hi,
node-canvas support is there.
Hasn't be removed.
You do not need anymore to us `createCanvasForNode` but just use standar code
`var canvas = new fabric.StaticCanvas()`

What is the problem actually?

**Comment by Sparki2002** [comment]
If I try it
```js
const fabric = require("fabric").fabric;
const fcanvas = new fabric.StaticCanvas();

const rect = new fabric.Rect({
  left: 50, top: 50, originX: "center", originY: "center", fill: "red", width: 50, "height": 50
});
fcanvas.add(rect);

console.log(fcanvas.createPNGStream());
```
I get this error
`fcanvas.createPNGStream is not a function`

**Comment by asturur** [comment]
ok maybe createPNGStream was a rush deletion. coming back.

**Comment by asturur** [comment]
trying to release rc2 today with those fixes.

**Comment by Sparki2002** [comment]
Thank you very much

**Comment by asturur** [comment]
May not be possible to restore now.
I asked for support to JSDOM.
If you need to access the data as a buffer, can you use the toBlob method or is not possible?

**Comment by asturur** [comment]
Canvas.lowerCanvasEl.toBlob
