### ISSUE TITLE
Draw line with mouse is not working after updating to v2

### ISSUE THREAD

**Issue by solomax** [kangax/fabric.js#4496]
## Version
2.0rc1

## Test Case
https://jsfiddle.net/solomax666/exzhjLbd/

## Steps to reproduce
* left click-and-hold on canvas
* move mouse to bottom right corner
## Expected Behavior
Only one side of the line moving
## Actual Behavior
Both sides of the line are moving

The picture is extra weird when after left click and hold you move mouse on the ...

**Comment by solomax** [comment]
Rectangle behave the same

**Comment by asturur** [comment]
in the fiddle posted i cannot see any line drawing code.
Anyway yesterday has been fixed a similar bug.
Please try your code on kitchensink demo ore wait for rc2 release ( today/tomorro)

**Comment by solomax** [comment]
Thanks for the quick response!
The line is added to canvas on mouseDown and updated on mouseMove.

I'll double-check using latest sources and will report back

**Comment by asturur** [comment]
i think you just linked wrong fiddle.

**Comment by solomax** [comment]
My bad, "Update+Set as base" silently fails
The link is now points to the correct code

**Comment by asturur** [comment]
that looks the bug fixed yesterday

**Comment by solomax** [comment]
Just have checked using latest sources
The issue is fixed!
Sorry for the noise (was unable to find original issue)

**Comment by solomax** [comment]
BTW latest release of v1 seems also be affected

**Comment by asturur** [comment]
i may have backported the bug and not the fix. i ll check
