### ISSUE TITLE
Fabric2.0 Usage

### ISSUE THREAD

**Issue by user-softway** [kangax/fabric.js#4501]
## Version
2.0

## Test Case
Hi, I wanted to build tool like SVG-Edit
https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/svg-editor.html
for my production site using fabric.js 2.0, will fabric.js be able to handle all kind of SVG templates?

**Comment by asturur** [comment]
I have no idea if it would able to handle ALL of them.
As of now NOT.
I'm working on clipPath support that is a big issue missing.
If you need full SVG support, an svg based editor is still better in my opinion.

**Comment by asturur** [comment]
Feel free to continue asking, but this is not an issue of the library itself, so i'm keeping it closed
