### ISSUE TITLE
'shifted' problem of free drawing

### ISSUE THREAD

**Issue by jefybai** [kangax/fabric.js#4502]
## Version
1.7.20

## Test Case
http://jsfiddle.net/pk70aLdz/

Hi:
I use ‘free drawing’ to draw a line on canvas. When I finish drawing, the line is shifted and changed location automatically.

 with the following code:

       fabric.Object.prototype.originX = fabric.Object.prototype.originY = 'center';

       canvas.freeDrawingBrush = new fabric.PencilBrush(canvas);
       canvas.freeDrawingBrush.color = '#DFDFDF';
       canvas.freeDrawingBrush.width = 5;

I have not found this problem in version 1.7.17, but in version 1.7.20 this problem is triggered by following code:

        fabric.Object.prototype.originX = fabric.Object.prototype.originY = 'center';

**Comment by asturur** [comment]
I cannot replicate on latest 2.0
The fiddle you opened is on 2.0

**Comment by jefybai** [comment]
@kangax 
I tried again, I confirmed that the problem occurred in the latest version of 1.7.20


Test Case

http://jsfiddle.net/pk70aLdz/
