### ISSUE TITLE
SVG radial-gradient issue 

### ISSUE THREAD

**Issue by user-softway** [kangax/fabric.js#4503]
## Version
2.0

## Test Case
http://jsfiddle.net/Da7SP/734/

## Steps to reproduce
when I am trying render this svg I am getting error like 

**Uncaught DOMException: Failed to execute 'createRadialGradient' on 'CanvasRenderingContext2D': The r0 provided is less than 0.**

`<svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 150" ver="4" width="600" height="800">
  <defs>
    <radialGradient id="fill_id0" spreadMethod="pad" gradientUnits="objectBoundingBox">
      <stop stop-color="#fff2b2" offset="0%"/>
      <stop stop-color="#fff2b2" offset="23%"/>
      <stop stop-color="#dbc269" offset="29%"/>
      <stop stop-color="#5a2f03" offset="40%"/>
      <stop stop-color="#5a2f03" offset="50%"/>
      <stop stop-color="#ffffff" offset="53%"/>
      <stop stop-color="#e0effc" offset="65%"/>
      <stop stop-color="#5996ed" offset="97%"/>
      <stop stop-color="#5996ed" offset="100%"/>
    </radialGradient>
  </defs>
  <image id="background" fill="none" transform="matrix(0.41322314739227295 0 0 0.41208791732788086 0 0)" x="0" y="0" width="726" height="364" xlink:href="https://scrutinizer-ci.com/images/logo.png"/>
  <rect fill="#ff0000" x="65.5" y="32.7" width="123.7" height="82.2"/>
  <text fill="url(#fill_id0)" transform="matrix(1.847671627998352 0 0 1.847671627998352 68.3 93.75)" html="&lt;P ALIGN=&quot;LEFT&quot;>&lt;FONT FACE=&quot;Franklin Gothic&quot; SIZE=&quot;32&quot; COLOR=&quot;#000000&quot; LETTERSPACING=&quot;0&quot; KERNING=&quot;0&quot;>Hello&lt;/FONT>&lt;/P>" version="4">
    <tspan x="0" y="0" font-family="Franklin Gothic" font-size="32" align="left" d="M1.504 0 L7.408 0 L7.408 -9.568 L12.032 -9.568 L12.032 0 L17.936 0 L17.936 -23.328 L12.032 -23.328 L12.032 -14.288 L7.408 -14.288 L7.408 -23.328 L1.504 -23.328 L1.504 0 M24.758 -10.192 L24.758 -10.192 Q24.758 -11.552 25.222 -12.528 Q25.686 -13.504 26.726 -13.504 Q27.942 -13.504 28.31 -12.624 Q28.694 -11.728 28.726 -10.192 L24.758 -10.192 M33.638 -7.04 L33.638 -8.16 Q33.638 -10.464 32.95 -12.432 Q32.262 -14.4 30.71 -15.616 Q29.158 -16.848 26.758 -16.848 Q24.982 -16.848 23.606 -16.176 Q22.214 -15.504 21.286 -14.32 Q20.358 -13.136 19.91 -11.584 Q19.446 -10.032 19.446 -8.256 Q19.446 -6.496 19.894 -4.96 Q20.342 -3.408 21.27 -2.192 Q22.182 -0.976 23.59 -0.288 Q24.982 0.4 26.822 0.4 Q28.95 0.4 30.374 -0.464 Q31.798 -1.344 32.502 -2.384 Q33.206 -3.408 33.398 -4.08 L29.83 -5.392 Q29.59 -4.384 28.854 -3.76 Q28.102 -3.136 27.142 -3.136 Q24.758 -3.136 24.758 -7.04 L33.638 -7.04 M35.03 0 L40.342 0 L40.342 -23.328 L35.03 -23.328 L35.03 0 M42.73 0 L48.042 0 L48.042 -23.328 L42.73 -23.328 L42.73 0 M55.15 -8.288 L55.15 -8.288 Q55.15 -11.216 55.55 -12.368 Q55.95 -13.504 57.054 -13.504 Q58.158 -13.504 58.558 -12.368 Q58.958 -11.216 58.958 -8.288 Q58.958 -6.224 58.75 -5.072 Q58.558 -3.904 58.142 -3.424 Q57.726 -2.944 57.054 -2.944 Q56.366 -2.944 55.966 -3.424 Q55.55 -3.904 55.358 -5.056 Q55.15 -6.224 55.15 -8.288 M49.646 -8.288 L49.646 -8.288 Q49.646 -5.696 50.462 -3.728 Q51.278 -1.776 52.942 -0.688 Q54.606 0.4 57.054 0.4 Q59.518 0.4 61.182 -0.688 Q62.846 -1.776 63.646 -3.728 Q64.462 -5.696 64.462 -8.288 Q64.462 -10.784 63.63 -12.736 Q62.798 -14.672 61.134 -15.76 Q59.454 -16.848 57.054 -16.848 Q54.67 -16.848 52.99 -15.76 Q51.326 -14.672 50.478 -12.736 Q49.646 -10.784 49.646 -8.288"><![CDATA[Hello]]></tspan>
  </text>
</svg>`

## Expected Behavior
It should render like the png attached here 
![cc61f3e7048c12909d93215356ce8c66_b](https://user-images.githubusercontent.com/33518051/33255989-08fcd286-d376-11e7-863c-4c43588a4dd2.png)

**Comment by panthar1** [comment]
I am not even sure what's wrong with those jsfiddles from #3808 and #3806 in the first place, not sure why their not displaying any objects on the canvas now with fabric 2.0. But, I do know radial gradients are broken, in my project which means their also broken in toSVG() perhaps you just need to fix the gradient, and the toSVG() will work again, I don't know.

**Comment by panthar1** [comment]
Unless there is some difference in browser, both those JS fiddles from 3808 and 3806 are broken. I am using chrome.

**Comment by ncou** [comment]
Everything seems fine in the radial gradiant. 
And the mentionned issues run with the lib v2.0 in the mentionned fiddle.

Here is a working fiddle in your case : http://jsfiddle.net/Da7SP/780/

I used as svg the outputed result from your fixSVG function, i encoded the "#" character as %23, i removed the background image for the test. You also use a custom font, i think you need to do something special in fabric.js like attachFont() or something like that, read the doc for this case.

Close the ticket if it's OK.

**Comment by asturur** [comment]
@ncou did you ever get the stickers? no one got them i sent like 50 of them

**Comment by ncou** [comment]
@asturur : sorry i didn't received the sticker :(
