### ISSUE TITLE
Possible memory leak using WebglFilterBackend

### ISSUE THREAD

**Issue by gelibolue** [kangax/fabric.js#4506]
http://jsfiddle.net/9bLhqnrj/11/

I'm trying to generate some random colored images like in this fiddle. When i'm done with the images i'm clearing the canvas and generate some more. With every loop my RAM usage in Task Manager gets bigger and bigger until WebGL crashes. How can i dispose images properly?

## Steps to reproduce
Open fiddle and wait, it'll generate new set of images every 10 seconds then webgl crashes.

**Comment by asturur** [comment]
Hello sorry for not answering.
Loading an image from URL makes you create a new texture everytime.

When clearing the canvas i do not think we call any dispose method for the image.

I also do not remember if there is a dispose method for the image.
Is something that need a fix.

Should be easy and i should try to do it today

**Comment by asturur** [comment]
also canvas.clear() will not be enough.

You have to dispose assets manually calling  image.dispose()
