### ISSUE TITLE
Missing method for inserting text programmatically

### ISSUE THREAD

**Issue by redlive** [kangax/fabric.js#4509]
## Version
2.0

## Test Case
http://jsfiddle.net/redlive/jvuvm2qg/

## Steps to reproduce
1. Open JSFiddler link
2. Open dev tool
3. Run code

Basically, issue consists of 2 bugs:
1. Style js error  ( Cannot convert undefined or null to object )
2. A text does not insert

![screen shot 2017-11-27 at 10 18 14 am](https://user-images.githubusercontent.com/5912122/33282310-18b58ad8-d35d-11e7-9de5-08a37503096e.png)

PS. It's unclear what function has replaced **_insertChars()_**

## Expected Behavior
New text and its style should be inserted in proper position.

## Actual Behavior
JS error

**Comment by asturur** [comment]
no function has replaced insertChars.
Fabricjs never had developer facing method to insert text.
What it had were methods used by keyboard events, not meant to be used on themselves.


insertNewStyleBlock is used by the onInput event and should be declared private, things that i missed to do.
it takes insertedText as a reference for adding new lines.

There is not the method you are searching for as today.

**Comment by redlive** [comment]
It used to have at least in version 1.7.19
https://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.7.19/fabric.js
Please search for this function... Line 24900

```
/**
     * Inserts characters where cursor is (replacing selection if one exists)
     * @param {String} _chars Characters to insert
     * @param {Boolean} useCopiedStyle use fabric.copiedTextStyle
     */
    insertChars: function(_chars, useCopiedStyle) {
      var style;

      if (this.selectionEnd - this.selectionStart > 1) {
        this._removeCharsFromTo(this.selectionStart, this.selectionEnd);
      }
      //short circuit for block paste
      if (!useCopiedStyle && this.isEmptyStyles()) {
        this.insertChar(_chars, false);
        return;
      }
      for (var i = 0, len = _chars.length; i < len; i++) {
        if (useCopiedStyle) {
          style = fabric.util.object.clone(fabric.copiedTextStyle[i], true);
        }
        this.insertChar(_chars[i], i < len - 1, style);
      }
    },
```

**Comment by redlive** [comment]
@asturur would it be considered to develop this function? if it does then how long it could take?
I wondering because I've kind of stacked with my project for now and must take a decision what to do either to wait or develop/add it by myself (which I have no time actually for doing that...)
Tnx

**Comment by asturur** [comment]
trying to take care of this

**Comment by asturur** [comment]
this thing is taking long because inserting the text programmatically is surfacing bugs of the styles handling logic

**Comment by redlive** [comment]
Tnank you
