### ISSUE TITLE
object:selected event only firing on first selection

### ISSUE THREAD

**Issue by mlev** [kangax/fabric.js#4510]
## Version
2.0.0-rc.3

## Test Case
http://fabricjs.com/events

## Steps to reproduce
Can be reproduced in event inspector - selected event only fired for first item selected on the canvas.
- Select an object -> check events fired
- Select another object -> check events fired

## Expected Behavior
object:selected event will be fired each time an object is selected

## Actual Behavior
object:selected only first for first selection - i.e. going from nothing selected to item selected.

**Comment by mlev** [comment]
OK - I've found the new event "selection:updated" that helps our use case for this event (tracking the active selection) but still seems odd that I can select an object and the event isn't fired consistently.

**Comment by asturur** [comment]
is fired differently.

please read the page:
http://fabricjs.com/v2-breaking-changes-2

object:selected is left just to do not make people rewrite lot of code, is deprecated and will be removed in next major version.

**Comment by mlev** [comment]
Ok thanks - I'd not seen that page - only breaking changes Part 1.
