### ISSUE TITLE
Image disappears when moved outside of canvas.

### ISSUE THREAD

**Issue by eugene1983** [kangax/fabric.js#4511]
## Version
2.0

## Test Case
https://jsfiddle.net/eugene1983/c2y31c04/7/

## Steps to reproduce
Move image object outside of canvas. Then press "Center" button to move it back.
At this point image became invisible until it get rescaled.
Is it bug or I missed something? And what should be done to make is visible?
(Image's isOnScreen() method returns false after image centred. Why?)

Thanks much!

**Comment by eugene1983** [comment]
I have found solution myself: `setCoords()` with `renderAll()` solve this problem.
So, is it bug or not?
https://jsfiddle.net/eugene1983/c2y31c04/8/

**Comment by asturur** [comment]
The reason why the image is not rendering is because when the user with the mouse drags it out, the object is tagged as offscreen and not rendered.

The object.center() updates the coordinates but does not do any other work, you have to call setCoords to make the canvas aware of its new position.

if centerObject is render automatically it should also recalculate the coords, or is a bug

**Comment by eugene1983** [comment]
I had to make function and call it in canvas.on('after:render') event.
var bugMustBeFixed = false;
function checkForBugFix() {
    if (!canvas.item(0).isOnScreen()) 
        bugMustBeFixed = true;
        
    if (bugMustBeFixed) 
        canvas.item(0).setCoords();
        if (canvas.item(0).isOnScreen()) {
            bugMustBeFixed = false;
            canvas.renderAll();
        }
    }
}

**Comment by asturur** [comment]
if setCenter has an automatic render but not a setCoords, this needs a fix

**Comment by asturur** [comment]
added setCoords to _centerObject().
Not really about of doing extra stuff automatically but the connection between aCoords and rendering is hard to grasp, since is just one setCoords, is better to just to do it

**Comment by eugene1983** [comment]
Tnx!
But i have to say something.
Even if you don't use `centerObject` for placement changing and use `top` and `left` properties of image instead - problem still remains.
I  have updated fiddle: https://jsfiddle.net/eugene1983/c2y31c04/9/. Now you can try to return image in canvas  using top and left inputs.

**Comment by asturur** [comment]
sure everytime you modify top and left you should call setCoords for interactivity. that is a known fabric logic.

what is weird is that staticCanvas never needed it before while now if you went offscreen and called setCoorda offscreen you need to call it again when you come back onscreen.

you can disable the outofscreen object detection if you do not make great use of zooming and panning

**Comment by eugene1983** [comment]
> ... while now if you went offscreen and called setCoords offscreen you need to call it again when you come back onscreen.

true

tnx for the answer!

**Comment by leacoleaco** [comment]
I having the same question, and I also found image disappears when zoom to a large size.   
thanks @eugene-g13 ,  this code finally solve my problem:
`
 canvas.on('after:render', function() {
      const item = canvas.item(0)
      if (!item.isOnScreen()) {
        item.setCoords()
      }
    })
`
