### ISSUE TITLE
Create a tutorial for brush documentation

### ISSUE THREAD

**Issue by Mahmoud-Alsayed** [kangax/fabric.js#4512]
## Version
1.7.19
## Test Case
https://jsfiddle.net/xey0ro3r/1/
## Steps to reproduce
just pass in a string literal as value for the width property of the free drawing brush
## Expected Behavior
You shouldn't get this blurriness
## Actual Behavior
You get a blurriness!
[This StackOverFlow Question](https://stackoverflow.com/questions/47513240/free-drawing-on-canvas-becomes-blurry) contains an image that demonstrate what I mean by 'blurriness'

**Comment by asturur** [comment]
Well is a documentation issue.
You have to pass a number.
If is not stated on the property with jsdoc i ll do it.

**Comment by Mahmoud-Alsayed** [comment]
But why blurriness? And not always? just sometimes when you draw you get a blurriness? This is weird isn't it?

**Comment by asturur** [comment]
it is.
but if it solved passing a number as requested, we should just move on.

**Comment by Mahmoud-Alsayed** [comment]
OK, let's move on then! I hate not getting a scientific detailed logical answer! But in this context it's pointless and time wasting!
Thank you mate I think this issue is resolved, someone should add this into the documentation!
Cheers!

**Comment by asturur** [comment]
added in the jsdocs.
I leave this page open as `create a custom brush tutorial` that  i need to do anyway

**Comment by asturur** [comment]
ok i have already an issue for that some lines below. closing this
