### ISSUE TITLE
V2 is slower at rendering simple text

### ISSUE THREAD

**Issue by JSteunou** [kangax/fabric.js#4514]
v1 has a bypass for empty styles that v2 has not causing lines is twice longer to render. When using fabric use a log of text shapes this is a 100% perf hit compared to v1.

Temporary solution: using cache on those shapes (which improve perf a lot but add a little blur when scaling up and down)

Backport solution: porting the v1 check and logic into v2 like

```js
      if (this.isEmptyStyles()) {
        return this._renderCharsFast(method, ctx, line, left, top);
      }
```

**Comment by asturur** [comment]
When scaling the blurriness comes from noScaleCache, that you can disable.

**Comment by JSteunou** [comment]
Already disabled :( 

But it's still better than v1!

**Comment by asturur** [comment]
that is strange. i would not expect the text to be blurred after a scale.
Can you post the JSON object of one of your groups?

like `canvas.getActiveObject().toObject()` so that i can try it

**Comment by JSteunou** [comment]
I cannot reproduce the tiny blur effect with simple fabric usage so I withdraw my remark, it's on my side :(
