### ISSUE TITLE
Problem building a fabric app with webpack and babel

### ISSUE THREAD

**Issue by pvanliefland** [kangax/fabric.js#4516]
## Version
2.0 rc3

## Test Case

Not applicable

## Steps to reproduce

Use webpack with babel-loader to transpile a project that include fabric.

## Expected Behavior

No ES6 code is included in the build.

## Actual Behavior

Non-transpiled ES6 code from jsdom is included in the build (and crashes the app in older browsers).

-----------------------------------------------------------------------------

I think the problem lies in this commit: https://github.com/kangax/fabric.js/commit/71b36f6228c4d56d3e0d41942cb2ce4e3bfb1f90#diff-f38f28902dcbc587be375ebd446c5341.

If you inspect what lies in `jsdom/lib/jsdom/living/generated/utils`, you can see that there is some ES6 code:

```javascript
module.exports.mixin = function mixin(target, source) {
  const keys = Object.getOwnPropertyNames(source);
  for (let i = 0; i < keys.length; ++i) {
    if (keys[i] in target) {
      continue;
    }

    Object.defineProperty(target, keys[i], Object.getOwnPropertyDescriptor(source, keys[i]));
  }
};
```

Problem is, when you build your app with webpack, you typically don't transpile code from `node_modules` - you expect it to be free from ES6 code.

**Comment by asturur** [comment]
the problem is that when you build your app with webpack you do not expect JSDOM to finish inside. JSDOM is node only, or if it run in the browser is not something you generally want in.

requiring that function in that way is confusing webpack i presume since it runs on node and so `isLikelyNode` is on.

Do you have an idea how to solve it?

**Comment by asturur** [comment]
summoning @stefanhayden a notorius webpack expert

**Comment by stefanhayden** [comment]
yeah I'm really no webpack expert.

I can think of a few ways to solve this. 

One would be for fabric to have a web and node build.

Perhaps the easiest way is to ignore the jsdom module using `new webpack.IgnorePlugin(/jsdom/)`. http://remarkablemark.org/blog/2017/02/25/webpack-ignore-module/

I've not tried it myself but is seem to be perfect for this situation. If it does work as advertised it might be worth updating some docs on how to do this.

**Comment by pvanliefland** [comment]
The web build and node build is probably the best solution.

The ignorePlugin might work but as explained in the article, it will also require defining a variable using the definePlugin, such as "ignoreJSDom" or "runInBrowser". `HEADER.js` would need to be adapted so that it uses this variable, otherwise the `require('jsdom/lib/jsdom/living/generated/utils').implForWrapper` line will fail.

**Comment by stefanhayden** [comment]
@pvanliefland well fabric has a check for that here: https://github.com/kangax/fabric.js/blob/master/HEADER.js#L8

it would probably much easier to add something to that logic then a possible breaking change to fabric with different node and web builds.

**Comment by sconix** [comment]
The suggested IgnorePlugin fix is bad since for example angular-cli build system wont allow changing the webpack configuration. So would be nice to have some other fix than that.

**Comment by asturur** [comment]
why it does not allow to change it?

**Comment by sconix** [comment]
That I do not know why they want to keep webpack as blackboxed, but my guess is to keep the build system standard and keep the problems to minimum.

**Comment by asturur** [comment]
well... can a package json have a main file for web and a main file for node? if not i do not have any solution. i can't keep doing 2 packages.

Also maybe starting publishing the src in the package and let people do a custom build on a post install step would help.
I do not like the idea of publishing built and unbuilt files tho.

**Comment by sconix** [comment]
At least angular-cli webpack configuration has this list as the mainFields: ['browser', 'module', 'main']

So I guess it should work if you have different index set for browser. I can quickly test this to verify if it would work.

**Comment by JSteunou** [comment]
#4576 should fix it
