### ISSUE TITLE
Image resize to fit canvas/objects

### ISSUE THREAD

**Issue by DangerD256** [kangax/fabric.js#4517]
2.0 b3

## Test Case
https://jsfiddle.net/bLn363j1/

1.7.20
https://jsfiddle.net/kun1h9ms/
Works fine

How i can stretch now images to canvas size?
Same issue with replacing images on image objects...

**Comment by asturur** [comment]
http://fabricjs.com/v2-breaking-changes#image

There are changes on how we handle image width and height.

Please use scaleX and scaleY to make an image bigger
