### ISSUE TITLE
bug in svg export of text, empty spaces are rendered. 

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4521]
## Version
2.0 (and all since forever I think :-)) 

## Test Case
http://fabricjs.com/test/svg_export/text.html
Or any text exported as SVG
![screen shot 2017-11-30 at 16 11 00](https://user-images.githubusercontent.com/8090162/33437712-1403775a-d5e9-11e7-8389-7f0caa93766d.png)

## Steps to reproduce
Try select the text, you'll see a white space used for nothing.
This can be really problematic with fonts like 
https://fonts.google.com/specimen/Zilla+Slab+Highlight
You clearly see a useless rectangle on top of everything : 
![screen shot 2017-11-30 at 16 09 31](https://user-images.githubusercontent.com/8090162/33437649-e7d7a6b0-d5e8-11e7-9a9b-578d9e6ccacb.png)

And I saw in the svg code that the before the first <tspan> there is some white spaces, if we remove these spaces, the rectangle disappear and you get a clean svg text rendered. 

I hope you'll see how to fix this! :-)

Thanks!

**Comment by asturur** [comment]
probably the new lines and tabs for svg formatting do not help.
Also we need a better way to handle text-wrap and white space props.

**Comment by asturur** [comment]
i do not really like it but first thing we should do is stop pretty formatting the svg in the text.
And this i am doing. All the tabs and newlines get rendered.

**Comment by asturur** [comment]
is from when we inserted the white-space preserve, is a 2.0 thing

**Comment by blobinabottle** [comment]
Ah yes, the white-space preserve is for Safari compatibility right?

**Comment by asturur** [comment]
is for keeping spaces between tspans, and multiple spaces that would be otherwise eaten by svg.

if you write `A  B` and `A ` is red and ` B` is blue, a tspan with ` B` inside is rendered as `B`.

Svg stuff....
