### ISSUE TITLE
Bug in freeDrawing

### ISSUE THREAD

**Issue by Ronalses** [kangax/fabric.js#4522]
I'm not sure if this is a bug.

But I have this problem in my project when updating the size of the canvas.
The line turns black and changes its thickness.

## Version
2.0

## Test Case
https://jsfiddle.net/ronalses/jretapud/

**Comment by asturur** [comment]
oh well, that happens because resize wipe the canvas and gives you a new how, everything get lost.
Can be fixed in some way but is a very edgy case.

**Comment by Ronalses** [comment]
Do you know any way to solve it?
Thank you very much for answering.

**Comment by asturur** [comment]
yes, is not a big deal, i wonder if is safe what are you doing in general.
I can add in the resize method to add again the current width and color of the brush. should be quick

**Comment by asturur** [comment]
can you tell me which is the real use case? why are you resizing in the middle of a drawing?

**Comment by Ronalses** [comment]
I have to adjust the size when zooming in on another canvas.
Then the sizes should be adjusted.

**Comment by Ronalses** [comment]
Should I add the width and color of the brush each time I update the canvas?
I think that does not work.

**Comment by asturur** [comment]
you have to wait me for write a small test, which i m actually trying to do, and release a rc4 version or build by yourself
