### ISSUE TITLE
Object selected event not fires after selecting another object

### ISSUE THREAD

**Issue by DangerD256** [kangax/fabric.js#4534]
Not sure if this is a bug, maybe you have some solution?

2.0

## Test Case
http://fabricjs.com/image-filters

## Steps to reproduce
Select object, apply filter, select another object. Checkboxes are not updates because object:selected was not fired.

## Expected Behavior
object:selected event firing when selecting another object not only when no any object selected.

**Comment by asturur** [comment]
it should be fired, while deprecated, for compatibility reason.
I'll check it.

the flow as described here:
http://fabricjs.com/v2-breaking-changes-2

should provide you selection:created and selection:updated, selection:cleared

i ll check what is wrong in the filter demo.

**Comment by DangerD256** [comment]
Clear with that, but how can i attach 2 events at same time?
```
canvas.on('selection:updated selection:created', function(e){
canvas.on('selection:updated, selection:created', function(e){
```
That doesn't works...

**Comment by asturur** [comment]
let me check, i normally create the handler in a function and i do

canvas.on('event:a', handler);
canvas.on('event:b', handler);

the events may also have different signature since event:updated can tell you what has been removed or added from the selection ( think of shift + click )

**Comment by asturur** [comment]
you have 2 ways to do that, both require to declare the handler.
other the one i already wrote, there is this other:

canvas.on({ 'event:a': handler, 'event:b':handler });

**Comment by DangerD256** [comment]
Works, but had to rewrite code...

**Comment by asturur** [comment]
well keeping the handler in a function is the only way to deregister it correctly.

about rewroting code that is necessary sometimes to fix stuff. The old object selected should fire anyway, is a thing to be investigated.

**Comment by DangerD256** [comment]
I had to rewrite
`canvas.on('selection:updated selection:created', function(e){`
`canvas[index].on({ 'selection:created': selection, 'selection:updated':selection });`
and in selection function i had to change a lot of strings with e.target.
So better to allow multiple event hooks in one string for better backward compatibility:
`canvas.on('selection:updated selection:created', function(e){`

**Comment by asturur** [comment]
we never had multiple event hooks in one string.
in what sense it improves backward compatibility?
