### ISSUE TITLE
loadSVGFromString and  toSVG does not generate the same output.

### ISSUE THREAD

**Issue by ombr** [kangax/fabric.js#4536]
When I import/export a SVG, I get a small position difference in groups.

## Version
2.0-rc-3 and 1.7

## Test Case

Here is a sample you can run on http://fabricjs.com/kitchensink:

```js
fabric.loadSVGFromString("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\" ?>\n<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" width=\"640\" height=\"640\" viewBox=\"0 0 640 640\" xml:space=\"preserve\">\n<desc>Created with Fabric.js 2.0.0-rc.3</desc>\n<defs>\n</defs>\n\t<g transform=\"translate(434.1 275.29)\">\n\t\t<text xml:space=\"preserve\" font-family=\"Times New Roman\" font-size=\"54\" font-style=\"normal\" font-weight=\"normal\" style=\"stroke: rgb(255,0,0); stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(255,0,0); fill-rule: nonzero; opacity: 1; white-space: pre;\" ><tspan x=\"-37.49\" y=\"16.96\" >test</tspan></text>\n\t</g>\n</svg>", function(objects, options){
          canvas.clear();
          canvas.add.apply(canvas, objects);
          canvas.renderOnAddRemove = true;
          canvas.renderAll();
          console.log(canvas.toSVG());
});
```

## Steps to reproduce

Run the code and read the transform in the logs.

The input `transform="translate(434.1 275.29)"` becomes `translate(471.59 261.48)`

## Expected Behavior

It should export the same svg which was imported (or at least with no difference in rendering)

## Actual Behavior

The exported SVG has differences in positions.

**Comment by asturur** [comment]
So creating an svg with text produces TSPANS.
TSPANS are not re-importable.

This is  a long unsopported feature in fabricjs and will probably be addressed sooner or later.

There is a dedicate issue for TSPANs
