### ISSUE TITLE
Some default properties when subclassing are not set

### ISSUE THREAD

**Issue by JSteunou** [kangax/fabric.js#4538]
* When subclassing a Circle with a property `radius` set to 10 for example, default 0 is taken because of https://github.com/kangax/fabric.js/blob/master/src/shapes/circle.class.js#L59
* When subclassing a Triangle with a property `width` set to 2 for example, default 100 is taken because of https://github.com/kangax/fabric.js/blob/master/src/shapes/triangle.class.js#L35

I did not check others but seems there are some issues regarding default & options.

**Comment by asturur** [comment]
does line do not make sense at all.
Could you please remove the circle one and triangle one? but we need to add the default values in the triangle properties just to do not break anything.

**Comment by asturur** [comment]
i'll double verify but if _setOptions is called, the radius is set if present.
if not present setting it to 0 has the only meaning of setting also width/height to 0 as default.

if object does not have width/height as 0 by default, they should be added i believe.

**Comment by JSteunou** [comment]
I'll make a fiddle tomorrow to show you but in short, something like

```js
const MyCircle = fabric.utils.createClass(fabric.Circle, {
  // my default radius
  radius: 10,
});
```

Does not work because `radius` get erased during the `initialized` by https://github.com/kangax/fabric.js/blob/master/src/shapes/circle.class.js#L59

**Comment by asturur** [comment]
I'm fixing this, the point is that if you create a circle with subclass radius 10, you have to take care of setting width/height to 20 in the subclass too.

**Comment by JSteunou** [comment]
Ho i did not though about this, of course it makes sense.
