### ISSUE TITLE
Get clipped shape coordinates

### ISSUE THREAD

**Issue by monis01** [kangax/fabric.js#4539]
Hi
can we fonund relative corrdinates of the clipped shape relative with other elements or canvas?
[Get clipped shape coordinates](https://stackoverflow.com/questions/47693882/get-clipped-shape-coordinates)

**Comment by asturur** [comment]
Fabric offers helpers for line intersecting polygon at best.
There is nothing for complex paths like ovals and beizers.

the question here differs from the one you posted, and is hard to understand for me.

What do you mean with relative coordinates?
Can you rewrite that question adding a working snippet of something that should detect the intersection of?
