### ISSUE TITLE
centeredRotation flag doesn't appear to work when using .set('angle')

### ISSUE THREAD

**Issue by ConnorTCM** [kangax/fabric.js#4543]
## Version
1.7.19

When drawing a new rectangle on the canvas I want the originX to be 'left' and originY to be 'top' (default values) to allow the most natural drag and drop drawing experience. When clicking a 'rotate' button I want to rotate around the center of the object. The gif below shows how manually calling `.set('angle')` (button is out of frame) rotates the object around the origin point whereas using the rotation point correctly rotates around the center.

![rotation](https://user-images.githubusercontent.com/19690264/33766157-2e6bd03e-dc14-11e7-813d-d5cdda85e7de.gif)

```
// Default values
new fabric.Rect({
  borderColor: 'green',
  cornerColor: 'green',
  cornerSize: 8,
  hasRotatingPoint: true,
  centeredRotation: true,
  left: startX,
  top: startY,
  customProps: item,
  fill: 'yellow',
  opacity: 0.3,
})

// Called when manually clicking a 'rotate' button
const currentAngle = itemToRotate.angle;
const rotateIncrement = 45;
let rotateDirection = currentAngle + rotateIncrement;
if (options && options.counterClockwise === true) {
  rotateDirection = currentAngle - rotateIncrement;
}
itemToRotate.set('angle', rotateDirection).setCoords();
fabricCanvas.renderAll();
```

**Comment by durga598** [comment]
you need to use `object.rotate()`. Here is a [fiddle](http://jsfiddle.net/ADukg/16659/)

**Comment by durga598** [comment]
you need to use `object.rotate()`. Here is a [fiddle](http://jsfiddle.net/ADukg/16660/).
Version 2.0.0
