### ISSUE TITLE
Cloning an object results in scaling being mirrored

### ISSUE THREAD

**Issue by ConnorTCM** [kangax/fabric.js#4544]
## Version
1.7.19

I need to deep clone an object as there are custom properties which need to be retained (hence why I'm using `fabric.util.object.clone()` instead of `object.clone()` which as I understand does a shallow copy. My desired result is having each duplicate decoupled and independent from each other after the clone has been performed. 

All appears to work fine except for scaling which is mirrored once the cloned object is deselected. Note that rotating the object doesn't get mirrored.

![clone](https://user-images.githubusercontent.com/19690264/33769358-c8d87840-dc21-11e7-900a-11bde3d01d49.gif)

```
// Initial object
new fabric.Rect({
  borderColor: this.state.borderColor,
  cornerColor: this.state.borderColor,
  cornerSize,
  hasRotatingPoint: false,
  left: startX,
  top: startY,
  customProps: item,
  fill: colors.YELLOW,
  opacity: 0.3,
})

// Duplicate action
const activeItem = fabricCanvas.getActiveObject();
const duplicate = fabric.util.object.clone(activeItem);
duplicate.set({ top: activeItem.top + 5, left: activeItem.left + 5 }).setCoords();
fabricCanvas
  .discardActiveObject()
  .add(duplicate)
  .setActiveObject(duplicate)
  .renderAll();
```

**Comment by asturur** [comment]
you cannot clone a fabric instance with fabric.util.object.clone
That is for cloning javascript objects, and in particular options objects for internal fabric structure.

http://fabricjs.com/docs/fabric.Object.html#clone
