### ISSUE TITLE
Superfluous lines

### ISSUE THREAD

**Issue by laof** [kangax/fabric.js#4545]
## Version
* fabric.js version: 2.0.0-rc.3
* Chrome version:61.0.3163.79

## Test Case
http://fabricjs.com/

## Steps to reproduce
Ask one thing, when the object is rotated, there are two lines appearing. As shown in the picture，
How to solve it, help ，thank you！
## Expected Behavior
![line](https://user-images.githubusercontent.com/8061178/33772086-6188a078-dc6e-11e7-9ad7-efe14e197f96.png)

![gw](https://user-images.githubusercontent.com/8061178/33772220-e182211e-dc6e-11e7-9107-89424a22b910.png)

**Comment by asturur** [comment]
I do not see those lines.
Do you see on other browsers or simply other computer too?

what OS are you on?

**Comment by JSteunou** [comment]
never seen those glitch too, but I know that sometimes weird things can happen with Windows and bad graphic drivers.

**Comment by asturur** [comment]
Also please replicate turning off  the hw accell from chrome, if they disappear is a driver issue

**Comment by laof** [comment]
I'm sorry, I forgot to say, I'm using Windows 7. There's the same problem on desktop and laptop computers. I can make sure that the phone is normal

**Comment by asturur** [comment]
please try with hw acceleration turned off

**Comment by laof** [comment]
OK, I will give it a try

**Comment by laof** [comment]
# Version
2.0.0-rc.3

# Test Case
http://fabricjs.com/

# describe

I tested it with two computers and got some data. It's easy to find it related to hardware acceleration. It's not a good way to configure the switch. What should we do now? Thanks

# Actual Behavior
<html>
  <table width="668" border="0" cellpadding="0" cellspacing="0" style="width:501.00pt;border-collapse:collapse;table-layout:fixed;">
   <colgroup><col width="208" class="xl65" style="mso-width-source:userset;mso-width-alt:6656;">
   <col width="163"  style="mso-width-source:userset;mso-width-alt:5216;">
   <col width="113"  style="mso-width-source:userset;mso-width-alt:3616;">
   <col width="184"  style="mso-width-source:userset;mso-width-alt:5888;">
   <col width="219" span="16379"  style="mso-width-source:userset;mso-width-alt:7008;">
   <col width="219"  style="mso-width-source:userset;mso-width-alt:7008;">
   </colgroup><tbody><tr height="28" style="height:21.00pt;mso-height-source:userset;mso-height-alt:420;">
    <td  height="28" width="208" style="height:21.00pt;width:156.00pt;" x:str="">Browser<span style="mso-spacerun:yes;">&nbsp;</span></td>
    <td  width="163" style="width:122.25pt;" x:str="">Hw acceleration</td>
    <td  width="113" style="width:84.75pt;" x:str="">Finally</td>
    <td  width="184" style="width:138.00pt;" x:str="">OS</td>
   </tr>
   <tr height="28" style="height:21.00pt;mso-height-source:userset;mso-height-alt:420;">
    <td  height="56" rowspan="2" style="height:42.00pt;border-right:.5pt solid windowtext;border-bottom:.5pt solid windowtext;" x:str="">Chrome 55.0.2883.87</td>
    <td  x:str="">OFF</td>
    <td class="xl67" x:str="" style="color: #00B050;font-weight: 700;">√</td>
    <td  rowspan="10" style="border-right:.5pt solid windowtext;border-bottom:.5pt solid windowtext;" x:str="">Window 7</td>
   </tr>
   <tr height="28" style="height:21.00pt;mso-height-source:userset;mso-height-alt:420;">
    <td  x:str="">ON</td>
    <td class="xl68" x:str="" style="color: red;font-weight: 700;">×</td>
   </tr>
   <tr height="28" style="height:21.00pt;mso-height-source:userset;mso-height-alt:420;">
    <td  height="56" rowspan="2" style="height:42.00pt;border-right:.5pt solid windowtext;border-bottom:.5pt solid windowtext;" x:str="">Chrome 61.0.3163.79</td>
    <td  x:str="">OFF</td>
    <td class="xl67" x:str="" style="color: #00B050;font-weight: 700;">√</td>
   </tr>
   <tr height="28" style="height:21.00pt;mso-height-source:userset;mso-height-alt:420;">
    <td  x:str="">ON</td>
    <td class="xl68" x:str="" style="color: red;font-weight: 700;">×</td>
   </tr>
   <tr height="28" style="height:21.00pt;mso-height-source:userset;mso-height-alt:420;">
    <td class="xl69" height="56" rowspan="2" style="height:42.00pt;border-right:.5pt solid windowtext;border-bottom:.5pt solid windowtext;" x:str="">Firefox&nbsp;48.0.2</td>
    <td  rowspan="4" style="border-right:.5pt solid windowtext;border-bottom:.5pt solid windowtext;" x:str="">OFF/ON</td>
    <td class="xl67" rowspan="4" style="border-right:.5pt solid windowtext;border-bottom:.5pt solid windowtext;color: #00B050;font-weight: 700;" x:str="" >√</td>
   </tr>
   <tr height="28" style="height:21.00pt;mso-height-source:userset;mso-height-alt:420;">
   </tr><tr height="28" style="height:21.00pt;mso-height-source:userset;mso-height-alt:420;">
    <td  height="56" rowspan="2" style="height:42.00pt;border-right:.5pt solid windowtext;border-bottom:.5pt solid windowtext;" x:str="">Firefox Quantum 57.0.2<span style="mso-spacerun:yes;">&nbsp;</span></td>
   </tr>
   <tr height="28" style="height:21.00pt;mso-height-source:userset;mso-height-alt:420;">
   </tr><tr height="28" style="height:21.00pt;mso-height-source:userset;mso-height-alt:420;">
    <td  height="112" rowspan="4" style="height:84.00pt;border-right:.5pt solid windowtext;border-bottom:.5pt solid windowtext;" x:str="">Chrome 63.0.3239.84</td>
    <td  x:str="">OFF</td>
    <td class="xl67" x:str="" style="color: #00B050;font-weight: 700;">√</td>
   </tr>
   <tr height="28" style="height:21.00pt;mso-height-source:userset;mso-height-alt:420;">
    <td  x:str="">ON</td>
    <td class="xl68" x:str="" style="color: red;font-weight: 700;">×</td>
   </tr>
   <tr height="28" style="height:21.00pt;mso-height-source:userset;mso-height-alt:420;">
    <td  rowspan="2" style="border-right:.5pt solid windowtext;border-bottom:.5pt solid windowtext;" x:str="">OFF/ON</td>
    <td class="xl67" rowspan="2" style="border-right:.5pt solid windowtext;border-bottom:.5pt solid windowtext;color: #00B050;font-weight: 700;" x:str="" >√</td>
    <td  rowspan="2" style="border-right:.5pt solid windowtext;border-bottom:.5pt solid windowtext;" x:str="">OS X Yosemite 10.10</td>
   </tr>
  </tbody></table>
</html>

**Comment by laof** [comment]
Find out the problem, look at the merge request

**Comment by asturur** [comment]
so that closePath is effectively extra. and can be removed being a straight line.
outo f curiosity what hardware you tested? what videocard?

**Comment by laof** [comment]
The mistake I found in the project. The third point of the triangle is the central coordinates of the canvas, not random . videocard is Intel (R) HD Graphics

**Comment by asturur** [comment]
there is no real mistake. happy to have removed that useless line if it helps.

The point is that if do

beginPath, moveTo(p1), lineTo(p2) i do not need to closePath at all, but if i do the closing is in p1 again, the first point i moved to.

Intel HD graphics has some other bugs around, definitely a driver issue.
