### ISSUE TITLE
Unnatural when adjusting size on smartphone with multi touch(Resize filter applied) 

### ISSUE THREAD

**Issue by leesc81** [kangax/fabric.js#4546]
When applying resizeFilter with multi-touch on touch device, lag occurs severely.
(android chrome and internal webview tested)

It is a burr when performing multi-touch scaling and rotating.
(Scaling with the control does not cause any problems)

The js file hosted in https must be imported into jsfiddle,
I can not host the js file that contains the Gestures module because I do not have an https server.

Below is the source I used.

fabric.Image.fromURL(img_url, function(img) {
img.setOptions({
scaleX: 0.25,
scaleY: 0.25
});

img.resizeFilters.push(new fabric.Image.filters.Resize({
resizeType: 'hermite',
}));

canvas.add(img);
canvas.centerObject(img);

img.setCoords();
}, {
crossOrigin: 'Anonymous'
});

**Comment by asturur** [comment]
Can you add a reproducible fiddle?
Webgl has just one type of resize and is lanczos, so if you are using hermite you are probably using the before 2.0 version, and that is going to be very slow, nothing we can do about it.

**Comment by leesc81** [comment]
The ability to use webgl to improve performance has been supported since 2.0.x ...
okay ..

However, apart from the performance issue, the movement lag will occur before you release your finger when you are multi-touching.

For example
Normally, when you use the control to scale, the filter is applied when you release your finger.
However, when you scale with multi touch, movement lag occurs even if you do not remove your finger.

When scaling with multi-touch
The resize filter seems to work several times(or some processing).

my code(Check it out on smartphones like Android Chrome)
http://mac.soochang.pe.kr:8080/fiddle_resize_issue_github.jsp

Thank you

**Comment by leesc81** [comment]
@asturur 
The ResizeFilter performance of fabricjs 2.0 is pretty good.
(seems to be using webgl ...)

There seems to be a lot of improvements in fabricjs 2.0, but the clipTo function has been removed 
so i can not be upgrad.

I found a search result, but I have not tested it.
https://stackoverflow.com/questions/44963677/how-to-deal-with-fabric-js-image-mask
https://stackoverflow.com/questions/35463613/fabric-js-how-to-clip-by-image/35477758#35477758

If the clipTo function is supported, i will be upgrad.

What is the correct way to implement clipTo functionality in fabricjs 2.0.0?

**Comment by asturur** [comment]
so clipTo is deprecated meaning that it works as 1.x version, is not supported anymore, it won't be improved.
A new system will be developed to take care of clip funcionalities and as soon we switch to some new breaking changes, clipTo will be removed.

New breaking changes could be the deprecation of node4, in april 2018.

**Comment by leesc81** [comment]
Thank you for your support.
Thank you
