### ISSUE TITLE
1.7.20+ / 2.0+: Drawing dots is not possible on mobile (iOS / Android)

### ISSUE THREAD

**Issue by jonathanherdt** [kangax/fabric.js#4552]
## Version
1.7.20+

## Test Case
Using 1.7.20: https://codepen.io/jonathanherdt/pen/ypBXRG

## Steps to reproduce
Open the first linked codepen on a mobile device (tested on iOS and Android). Try to draw a dot by tapping and releasing (no dragging).

## Expected Behavior
A dot appears on the canvas

## Actual Behavior
No dot appears on the canavas.

## Remark
This issue was introduced in 1.7.20. You can try out the same behavior under 1.7.19 here: https://codepen.io/jonathanherdt/pen/PEYjNb

**Comment by jonathanherdt** [comment]
Might be related to #4374

**Comment by durga598** [comment]
This has been fixed [#4480](https://github.com/kangax/fabric.js/issues/4480)
