### ISSUE TITLE
apply filter of a scaled image

### ISSUE THREAD

**Issue by styloInt** [kangax/fabric.js#4553]
I apply a filter to my image where I modify each pixel. The issue is when I change the scale of an image, fabricjs give always the original image (before scale) to the input of the filter. Then, I cannot modify each pixel of the new data (after scale).  Does somebody know how to do that? or it's not possible?
if it's not possible, I think it would be nice to be able to do that

**Comment by asturur** [comment]
you should start explaining how you modify the pixels of the image.

**Comment by styloInt** [comment]
I do that by assigning pixel from another image.
But I don't want to resize this other image.

here the code of the filter

 `applyTo2d: function(options) {
    	var imageData = options.imageData,
        	resources = options.filterBackend.resources,
        	data = imageData.data, iLen = data.length,
        	width = options.imageData.width,
        	height = options.imageData.height,
        	tr, tg, tb, ta,
    		r, g, b, a,
        	canvas1, context, image = this.image, blendData;

    var board = this.board;
    var centerX = pattern.left;
    var centerY = pattern.top;
    var heightScaled = pattern.height;// * pattern.scaleY;
    var widthScaled = pattern.width;// * pattern.scaleX;

    var init_pxTop = Math.round(pattern.top - heightScaled/2);
    var init_pxLeft = Math.round(pattern.left - widthScaled/2);

		if (!resources.blendImage) {
			resources.blendImage = document.createElement('canvas');
		}
    	canvas1 = resources.blendImage;
    	if (canvas1.width !== image.width || canvas1.height !== image.height) {
    		canvas1.width = image.width;
    		canvas1.height = image.height;
    	}
    	context = canvas1.getContext('2d');
      console.log("before width image : ", image.width, "height image : ", image.height, "scaleX : ", image.scaleX, "scaleY : ", image.scaleY)

      var scale = 1
      var scaleX = image.scaleX * scale;
      var scaleY = image.scaleY * scale;
      // image.set({"scaleX":scaleX, "scaleY":scaleY})


      // console.log("after width image : ", image.width, "height image : ", image.height, "scaleX : ", image.scaleX, "scaleY : ", image.scaleY)
    	context.setTransform(image.scaleX, 0, 0, image.scaleY, 0, 0);
    	context.drawImage(image._element, 0, 0, image.width, image.height);
    	blendData = context.getImageData(0, 0, board.width*board.scaleX, board.height*board.scaleY).data;

      iLen = data.length


      var pxTop = init_pxTop-1, pxLeft = init_pxLeft-1;
    	for (var i = 0; i < iLen; i += 4) {


  			if (i % (widthScaled * 4) == 0) {
  				pxTop += 1;
  				pxLeft = init_pxLeft;

  			}
  			else {
  				pxLeft++;
  			}

        if (i == 0)
        {
          console.log("width : ", width, "pattern width", pattern.width, "height : ", height,"widthScaled : ", widthScaled, "heightScaled : ", heightScaled, "iLen", iLen);
        }

        var angleRotation = pattern.angle * Math.PI / 180;//radian

        var newPxTop = Math.round((pxTop-centerY) * Math.cos(angleRotation) + (pxLeft-centerX) * Math.sin(angleRotation)) + centerY;
        var newPxLeft = Math.round(-(pxTop-centerY) * Math.sin(angleRotation) + (pxLeft-centerX) * Math.cos(angleRotation)) + centerX;
      
  			a = data[i + 3];
  			
  			if (a > 0) {
  				if (newPxTop >= 0 && newPxTop < board.height*board.scaleY && newPxLeft >= 0 && newPxLeft < board.width*board.scaleX) {

            var top_bdi = (board.width * board.scaleX) * newPxTop;
            var left_bdi = newPxLeft;
  					var bdi = top_bdi * 4 + left_bdi * 4;
  					
  					data[i] = blendData[bdi];
  					data[i + 1] = blendData[bdi + 1];
  					data[i + 2] = blendData[bdi + 2];
  					//data[i + 3] = blendData[bdi + 3];
  					
  					if (blendData[bdi + 3] == 0)
  						data[i + 3] = 0;
  					
  				}
  			}


    	}`

**Comment by asturur** [comment]
i can't read all that code and undersand.

if you are using a fabricjs filter to modify the picture, the resize will
start from the filtered one.

can you make up a jsfiddle?

**Comment by styloInt** [comment]
here the jsfiddle : https://jsfiddle.net/styloInt/t91tvu6a/4/. I think you'll understand what I'm trying to do and the issue now. 

I have two object of same size with different texture and a pattern. I want the pattern to take object1 pixel value when it's not transparent, and object2 pixel value when it is.

**Comment by asturur** [comment]
i think that if you build a proper filter, and looks like apart webgl you did, the resize filter has to place nicely with it.
Are you aware that if you are using webgl your filter is doing nothing?

**Comment by asturur** [comment]
no, did you disable webgl manually? otherwise you are running the webgl version of the baseFilter class that does nothing.

**Comment by styloInt** [comment]
my filter is doing something . you"re not able to run  it ? https://jsfiddle.net/styloInt/kyf7q38j/#&togetherjs=3RdUB6553B

The issue is when scalling, it works for rotation and moving

**Comment by asturur** [comment]
no fiddle does not run

**Comment by styloInt** [comment]
hmmmmm it works for me. I think it wasn't public. [fiddle](https://jsfiddle.net/styloInt/8tjfgfeb/ ). Now it should work. Try to move the object, you'll see the effect I want to have. 

The actual solution is a little tricky, but I didn't find another way. For now, I Ioop over each pixel of my pattern, if it's transparent, I modify the color by the color of the object2 at the same position on the screen. I compute the coordinate using cosinus and sinus because I didn't find an easiest way to do that in fabricjs . If you have others ideas don't hesitate, thanks a lot for your time :)

**Comment by styloInt** [comment]
I solved my issue. Instead of applying my filter to the pattern, I apply the filter to the object. It does the trick. 

But I really think it would be nice to be able to apply a filter to the new data after scale.

I close the issue.

**Comment by asturur** [comment]
the blendImage filter does exactly that, it does not offer controls over positioning, and you have to handle it by yourself

**Comment by styloInt** [comment]
Yes i Know, the position and rotation was handled. The issue was with scaling, because imageData is alaways of the same size whatever the scale.
