### ISSUE TITLE
padding is not the same between one selected and multiple selected elements

### ISSUE THREAD

**Issue by JSteunou** [kangax/fabric.js#4567]
When setting a padding on a shape, it is totally respected when this shape is selected, but ignored when the shape is part of an active selection group.

http://jsfiddle.net/wu5dLo6q/1/

Thus it's not possible to have a consistent border

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/34099708-8a0b5b84-e3e0-11e7-9fdb-b88acef00343.png)

maybe the internal border in the active selection should have a different property to be colored.
Padding for active selections will not be introduced back, padding is not supposed to scale, while object inside a group does. Padding is an exclusive feature of the control of the object more than the object itself.

I believe maybe we need a separate style for inner object of a selection, without padding, with a different color and weight
