### ISSUE TITLE
fabric.Image.filters.Mask is removed in 2.0.0-rc3.

### ISSUE THREAD

**Issue by troeglazov** [kangax/fabric.js#4571]
Hello, I have updated my fabricjs version from 1.7.11 to 2.0.0-rc3. As I see class "filters.Mask" was removed in the new version. Is it a mistake or if no how I can apply masks in 2.0.0-rc3? Also in docs "Mask" class still exists http://fabricjs.com/docs/. Thank you.

**Comment by asturur** [comment]
Well i have no idea why docs still reports it, but i think we can put the mask option in blendImage filter and add a translation guide like for the other filters.

**Comment by asturur** [comment]
well it looks like i already got this idea, i just forgot. 
You can create a BlendImage filter, passing the old mask option as image option.

http://fabricjs.com/fabric-filters
