### ISSUE TITLE
fabricjs render all objects then adding object hides all other expect the new object. then clicking on canvas shows them all

### ISSUE THREAD

**Issue by tomonsoejang** [kangax/fabric.js#4572]
## Version
2.0.0-rc

## Steps to reproduce
https://stackoverflow.com/questions/47881947/fabricjs-render-all-objects-then-adding-object-hides-all-other-expect-the-new-ob

## Expected Behavior
all object in the canvas is rendered, then on adding new object, should display along with other canvas

## Actual Behavior
all object in the canvas is rendered, then on adding new object, old objects are hidded, new is shown, 
on clicking the canvas, shows all objects again

**Comment by asturur** [comment]
your code has nothing wrong with fabricjs, may look like some kind of vue.js edge case, but nothing we can help here.

**Comment by tomonsoejang** [comment]
after adding a new object, the clicking the canvas shows them up. is there anything linked with the click event in fabricjs

**Comment by asturur** [comment]
probably a re-render. But you should not loose the previous drawing at all.
Can be that angular is resizing the canvas?

**Comment by tomonsoejang** [comment]
thank you. the issue was not in fabricjs
