### ISSUE TITLE
Cannot export Tainted Canvas with images from s3

### ISSUE THREAD

**Issue by Sashkan** [kangax/fabric.js#4573]
I'd like to add some images to my canvas, and then export the whole canvas as png.

Code is pretty straightforward : 
```
    fabric.Image.fromURL(url, (oImg) => {
      oImg.scaleToWidth(this.canvas.getWidth() / 2)
      this.canvas.add(oImg);
      oImg.bringToFront()
    });
```

and

 ```

	var image = new Image();
	image.src = canvas.toDataURL("image/png");
	return image;
```

Now, as first I could add images to my canvas, but when I tried to export the canvas as png, I got the Tainted Canvars CORS error. So, according to #1386 , I replaced my first snippet of code with this : 
```
    fabric.Image.fromURL(url, (oImg) => {
      oImg.scaleToWidth(this.canvas.getWidth() / 2)
      this.canvas.add(oImg);
      oImg.bringToFront()
    }, {crossOrigin:'Anonymous'});
```
But now, since my image has an anonymous crossOrigin, it cannot be loaded from s3 anymore : my first snippet of code results in a 

```
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
```

Is there a way to get the best of both world, loading the image from s3 and getting an exportable canvas ?

**Comment by asturur** [comment]
yes, you have to configure your s3 server to provide the CORS headers to images.
Is configurable, i have no idea how.

**Comment by asturur** [comment]
I close the issue since is not a fabricjs problem.
Is a generic html canvas problem and a s3 aws configuration problem.

**Comment by Sashkan** [comment]
I thought so, unfortunately my s3 is configured to allow all origins. As I said, if I do not specify the crossOrigin attribute as third parameter, the image is loaded without any CORS error.

**Comment by asturur** [comment]
is loaded but the canvas is tainted.
This is a generic problem, you have to reconfigure your s3.
There is no escape is an HTML5 thing.

**Comment by Sashkan** [comment]
As I said, it's not about S3 : I get the same Tainted Canvas error when loading an image from any url

I suppose that this should work : 

```js
    fabric.Image.fromURL("http://www.freeiconspng.com/uploads/team-icon-21.png", (oImg) => {
      oImg.scaleToWidth(this.canvas.getWidth() / 2)
      this.canvas.add(oImg);
      oImg.bringToFront()
    }, {
      crossorigin: 'anonymous'
    });
```

but it doesn't. Any image from any origin will trigger the tainted canvas error, even when setting the crossOrigin as third parameter. Maybe I messed up when setting up my canvas, here is the whole code :

```js

      var canvas = document.querySelector('#canvas')
      var ctx    = canvas.getContext('2d')
      this.canvas = new fabric.Canvas('canvas');


    fabric.Image.fromURL(url, (oImg) => {
      this.canvas.add(oImg);
      oImg.bringToFront()
    }, {
      crossorigin: 'anonymous'
    });

    window.open(canvas.toDataURL('png'));
```

**Comment by asturur** [comment]
can i get one url of one of your s3 images?

**Comment by asturur** [comment]
https://jsfiddle.net/cb1utxwm/9/

it works with the PNG, please paste here the s3 response/request headers

**Comment by Sashkan** [comment]
here is one of my URLs : http://s3.eu-central-1.amazonaws.com/balibart-s3/Designs/5a2fae5a5f19905262d229f2/design.png

**Comment by asturur** [comment]
https://jsfiddle.net/cb1utxwm/10/  ti works.

**Comment by asturur** [comment]
what i can tel you is that your code is right, toDataurl and crossOrigin works in fabricjs.

**Comment by Sashkan** [comment]
I'm dumb as sand. if anyone ever get this problem, just empty your cache. Thank you so much for your help @asturur

**Comment by asturur** [comment]
Some sand is smart!!
![image](https://user-images.githubusercontent.com/1194048/34159267-edc724d0-e4c8-11e7-924e-d19ea1d359de.png)

**Comment by ducvu91** [comment]
Hi i have same issue
https://jsfiddle.net/cb1utxwm/11/

**Comment by ParthGoyal1508** [comment]
Hi, I am facing the same issue.
@Sashkan @asturur can you please help me out.

**Comment by asturur** [comment]
You need to setup your s3 storage correctly.

**Comment by ParthGoyal1508** [comment]
The CORS configuration of my bucket is 
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>Authorization</AllowedHeader>
</CORSRule>
</CORSConfiguration>

I am able to load the image on canvas and able to show it on browser but when i use canvas.toDataUrl() it throws "Cannot export Tainted Canvas"

**Comment by juzhiyuan** [comment]
Maybe you should check your local cache, could you please have a try on a new browser? Maybe in privacy mode?

**Comment by asturur** [comment]
The error is in your code.

```javascript
canvas.setBackgroundImage("http://tg-bucket-123098.s3.ap-south-1.amazonaws.com/Youtube/ZyJ4_UxpP68.jpg", canvas.renderAll.bind(canvas), {
				scaleX: canvas.width / 200,
				scaleY: canvas.height / 200
			})
			var link = document.createElement('a');
			link.download = 'filename.png';
			link.href = canvas.toDataURL();
			link.click();
		}
```

canvas.setBackgroundImage will reload the image from URL, and you have to specify cors for it.

http://fabricjs.com/docs/fabric.StaticCanvas.html#setBackgroundImage

**Comment by Lebski** [comment]
> https://jsfiddle.net/cb1utxwm/10/ ti works.

Hey! 
This doesn't work anymore and loads only a white canvas. 

I updated it to create the download on click and it fails with the same error as stated above 

See: 
https://jsfiddle.net/uxdv70j8/5/
