### ISSUE TITLE
jsdom utils is imported even for browsers at build

### ISSUE THREAD

**Issue by JSteunou** [kangax/fabric.js#4575]
Some part of jsdom are included for nodejs but it has some side effect on browser build https://github.com/kangax/fabric.js/blob/master/HEADER.js#L21

1. useless code is included
2. it is not ES5 compatible and generally not transpile by babel as it is inside node_modules

**Comment by asturur** [comment]
we have an issue open, building with webpack.
If there was some kind of universal fix i would gladly use it.
It looks like webpack is not on the list of my best skills, and also @stefanhayden that is my webpack guru has not clear idea on what to do.

Do you have any hint?

**Comment by JSteunou** [comment]
Yep, PR on the way

**Comment by asturur** [comment]
god bless you

**Comment by JSteunou** [comment]
Dont know if god is related to any of that, but hey, no problem :D 

Do you think you could make a RC4 with that? This issue is blocking for browsers not supporting some ES6 statements :/

**Comment by asturur** [comment]
i have to wrap it up. not gonna change any code i should release as it is, just i did not finish docs
