### ISSUE TITLE
An editable area is set in the canvas as a whole. Is there a API that can be called?

### ISSUE THREAD

**Issue by mengfei2611** [kangax/fabric.js#4581]
The canvas loads a T - shirt and then draws an editable area for editors. After adding the picture, it is displayed only in the editable area.

**Comment by asturur** [comment]
I do not understand the question. Please make an example

**Comment by mengfei2611** [comment]
感谢您的回复。我想要的效果是创建一个画布，中间能不能再画出一个可编辑区域。就像这个http://udz.com/_design里面的应用。

**Comment by asturur** [comment]
This is even more outside my reach.

**Comment by mengfei2611** [comment]
这个应用就是使用了fabric.js，但是我不知道是怎么实现，在T恤上规定一个可以编辑的区域。能帮助我一下吗？万分感谢！

**Comment by mengfei2611** [comment]
![image](https://user-images.githubusercontent.com/22373868/34319369-9c76b69e-e81b-11e7-9e7f-a3cf2cc3d84e.png)就是这个样子的。

**Comment by asturur** [comment]
For this kind of question let's use stackoverflow.com

Open a question following stackoveflow guidelines, then post the link here, i ll try to help, many other people will do if the question is well written with an example

post the link to the question here so i can see it.
