### ISSUE TITLE
Draw SprayBrush / CircleBrush - Uncaught TypeError: this.freeDrawingBrush._render

### ISSUE THREAD

**Issue by AlexSergey** [kangax/fabric.js#4583]
## Version
2.0-rc.4

## Test Case
http://fabricjs.com/freedrawing

## Steps to reproduce
1. Set SprayBrush / Circle
2. Draw

## Actual Behavior
Uncaught TypeError: this.freeDrawingBrush._render is not a function
at klass.renderAll (fabric.js:9182)
at klass.renderAndReset (fabric.js:7131)

**Comment by asturur** [comment]
Weird error, everything looks like working. I'll try to fix it today.

**Comment by AlexSergey** [comment]
Do you have any updates?

**Comment by asturur** [comment]
i went for holidays and did not make in time.
i need to add a render method to all brushes and also restrict the cases in which  the render is called.

nothing long, just i m still out.

**Comment by AlexSergey** [comment]
Happy holidays!
