### ISSUE TITLE
Mouse position is off when the zoom level of HTML Body is modified

### ISSUE THREAD

**Issue by emre-aki** [kangax/fabric.js#4584]
## Version
2.0

## Test Case
https://jsfiddle.net/L3hs7pxg/2/

## Steps to reproduce
1. Zoom in or out.
2. Try to do anything on the canvas that involves mouse.

## Expected Behavior
Correct reading of the mouse position.

## Actual Behavior
Incorrect reading of the mouse position, so the coordinates read are off depending on the current zoom level.

**Comment by asturur** [comment]
Arbitrary css transform over the canvas are not supporterd.
If you need a zoom functionality please use the setZoom method from fabric.js
