### ISSUE TITLE
Bug regression: excludeFromExport in overlayImage and bgImage is not working again

### ISSUE THREAD

**Issue by salomonsanz** [kangax/fabric.js#4587]
## Version
1.20

## Description
The bug/feature  "excludeFromExport" in overlayImage and backgroundImage in version 1.7.17

> Fix: avoid exporting bgImage and overlayImage if excludeFromExport = true #4119

But is failing again, ignoring this property and the overlayImage is exported to svg
https://jsfiddle.net/vkLt8938/1/

**Comment by asturur** [comment]
The exclude from export is supposed to work for toObject for serialize / deserialize purpose.
It does not involve toSVG process nor toDataURL.

**Comment by asturur** [comment]
I close the issue since there is nothing to fix, the topic is open if you want to talk about something else.

**Comment by salomonsanz** [comment]
in the docs says that includes also SVG serialization:

http://fabricjs.com/docs/fabric.Object.html#excludeFromExport

> When `true`, object is not exported in SVG or OBJECT/JSON since 1.6.3

So, or is wrong the docs, or is a bug. 

It makes sense that it works this way, affecting both.

**Comment by asturur** [comment]
well hard call then.
I think that png and svg export should be same.

**Comment by asturur** [comment]
updated docs
