### ISSUE TITLE
IText isn't editable at 1.7.21 (Cannot read property 'save' of undefined)

### ISSUE THREAD

**Issue by finom** [kangax/fabric.js#4588]
## Version
1.7.21

## Test Case
https://jsfiddle.net/76puy8m7/

## Steps to reproduce
Try to edit text

## Expected Behavior
Should work as it worked at 1.7.20 https://jsfiddle.net/snrL82u4/

## Actual Behavior
Edition throws the error

![image](https://user-images.githubusercontent.com/1082083/34420386-e39dc428-ec11-11e7-91f5-67304cb8acef.png)

**Comment by baiwenhao** [comment]
Did not find it wrong，How to reproduce your problem?

**Comment by asturur** [comment]
A last minute change that went wrong. Reverting and republishing as 1.7.22

**Comment by asturur** [comment]
i published 1.7.22 is on NPM and on the cdn in about 15 minutes, i tagged it now.

**Comment by finom** [comment]
@asturur thank you!

@baiwenhao I'd happy to, but we have quite complex legacy app, and simple upgrade to v2 give us a lot of exceptions.

**Comment by asturur** [comment]
please confirm me the fix is working. i did not have a chance.

**Comment by finom** [comment]
@asturur just noticed your comment. It works, thank you!
