### ISSUE TITLE
Char Spacing on Itext and Textbox not working.

### ISSUE THREAD

**Issue by duyhung85** [kangax/fabric.js#4591]
I test on kitchen sink on fabricjs website:

[http://fabricjs.com/kitchensink]()

- The 2 default itext objects are working as expected when I move the charspacing ranger

-  I then add a new text/itext/text box and try to move the charspacing , it seems only make the box bigger or smaller, but not increasing the space between characters.

**Comment by asturur** [comment]
i see the problem.
Is the text shortcut for performances.
Needs a fix, is an easy one.
