### ISSUE TITLE
Can you please tell me how to set opacity of setOverlayImage.

### ISSUE THREAD

**Issue by unitedsol** [kangax/fabric.js#4592]
Hello kangax,

Hope you are doing fine can you please tell me how to set the opacity of setOverlayImage., I want to add a watermark on my canvas so need to know how to add watermark of image on canvas, I use this setOverlayImage function to add image with no controls that work fine but opacity not working with make issue on background image. 

Thanks in advance .

Regard
Unitedsol

**Comment by asturur** [comment]
please add a minimal jsfiddle to demonstrate the bug.

**Comment by unitedsol** [comment]
https://jsfiddle.net/unitedsol/tmcrf6jy/ here is the jsfiddle can you please tell me how to add the opacity on this image.

**Comment by asturur** [comment]
fiddle is empty?

**Comment by unitedsol** [comment]
its working https://jsfiddle.net/unitedsol/tmcrf6jy/6/

**Comment by unitedsol** [comment]
here is the code i only add the opacity in this image. I can use setOverlayImage fabric.js function 

`var url = 'https://assets.servedby-buysellads.com/p/manage/asset/id/61450';

canvas.setOverlayImage(url, function() {
    console.log('overlayImage callback function');
    canvas.overlayImage.scaleX = canvas.width  / 800;
    canvas.overlayImage.scaleY = canvas.height / 800;
    canvas.renderAll();
});`

**Comment by asturur** [comment]
i think you did not even read the docs.
is canvas.overlayImage.opacity = number
