### ISSUE TITLE
Free drawing Rect 

### ISSUE THREAD

**Issue by alikhan126** [kangax/fabric.js#4599]
I have created free drawing rectangle using mouse or courser but now when i resize the existing rectangle the place i where i click make another rectangle.
first i want to remove this.
here is the code i have used.

<-- Code -->
      
      var Rectangle = (function(){
			function Rectangle(canvas){
				var inst = this;
				this.canvas = canvas;
				this.className = 'Rectangle';
				this.isDrawing = false;
				this.bindEvents();
			}

			Rectangle.prototype.bindEvents = function() {
				var inst = this;
				inst.canvas.on('mouse:down',function(o){
					inst.onMouseDown(o);
				});
				inst.canvas.on('mouse:move',function(o){
					inst.onMouseMove(o);
				});
				inst.canvas.on('mouse:up',function(o){
					inst.onMouseUp(o);
				});
				inst.canvas.on('object:moving',function(o){
					inst.disable();
				})
			};
			Rectangle.prototype.onMouseUp = function(o) {
				var inst = this;
				inst.disable();
			};

			Rectangle.prototype.onMouseMove = function(o) {
				var inst = this;

				if (!inst.isEnable()) {return;}
				console.log("Mouse Moving Rectangle");
				var pointer = inst.canvas.getPointer(o.e);
				var activeobj = inst.canvas.getActiveObject();

				activeobj.stroke = 'red';
				activeobj.strokeWidth = 5;
				activeobj.fill = 'transparent';

				if (origX > pointer.x) {
					activeobj.set({left: Math.abs(pointer.x) });
				}
				if (origY > pointer.y) {
					activeobj.set({top: Math.abs(pointer.y) });
				}

				activeobj.set({ width: Math.abs(origX - pointer.x) });
				activeobj.set({ height: Math.abs(origY - pointer.y) });

				activeobj.setCoords();
				activeobj.renderAll();

			};

			Rectangle.prototype.onMouseDown = function(o){
				var inst = this;
				inst.enable();

				var pointer = inst.canvas.getPointer(o.e);
				origX = pointer.x;
				origY = pointer.y;

				var rect = new fabric.Rect({
					left:origX,
					top:origY,
					originX:'left',
					originY:'top',
					width: pointer.x - origX,
					height: pointer.y - origY,
					angle: 0,
					transparentCorners: false,
					hasBorders: false,
					hasControls: false
				});

				inst.canvas.add(rect).setActiveObject(rect);
			};

			Rectangle.prototype.isEnable = function(o) {
				return this.isDrawing;
			};

			Rectangle.prototype.enable = function(o) {
				return this.isDrawing = true;
			};

			Rectangle.prototype.disable = function(o){
				return this.isDrawing = false;
			};

			return Rectangle;

		}());

		

		var canvas = new fabric.Canvas('canvas');
		var arrow = new Rectangle(canvas);

<-- End -->

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

**Comment by shuraim-hassan** [comment]
how to use this code in HTML file
