### ISSUE TITLE
Fabricjs.com Searching on Google Broken

### ISSUE THREAD

**Issue by sneilan** [kangax/fabric.js#4600]
When searching using the google function in http://fabricjs.com/docs/fabric.util.html#.getKlass

The documentation appears above the google search results.

![https://seanneilan.com/download/Screen%20Shot%202018-01-01%20at%2012.53.22%20PM.png](https://seanneilan.com/download/Screen%20Shot%202018-01-01%20at%2012.53.22%20PM.png)

**Comment by asturur** [comment]
this has been fixed. thanks for sharing

**Comment by sneilan** [comment]
<3
