### ISSUE TITLE
Pixelated edges in scale

### ISSUE THREAD

**Issue by evolutionjay** [kangax/fabric.js#4603]
## Version
2.0

Image Pixelated edges in scale

I want to use filter to fix this problem , but I  can't understand  the Tutorial  , the Examples is too hard to understand .

**Comment by asturur** [comment]
what example are you referring to?

**Comment by evolutionjay** [comment]
I want to write a demo for rc-4 , but rc-4 no  cdn  host, only 1.7.22

**Comment by asturur** [comment]
you can use the link to dist folder in github

**Comment by evolutionjay** [comment]
@asturur  No I can,t , github raw file is text / pain

**Comment by asturur** [comment]
let me search the link, everyone does it with master branch

**Comment by asturur** [comment]
https://rawgithub.com/kangax/fabric.js/master/dist/fabric.js

this link works in fiddle and gives you access to rc4 now and rc5 later
