### ISSUE TITLE
How can I know if the object is modified or not?

### ISSUE THREAD

**Issue by santosmken** [kangax/fabric.js#4604]
Scenario: I have multiple images on the canvas, if I select one of it using `canvas.getActiveObject` I'm getting the right object. After that I added this line of code `this.canvas.on('object:modified', (options) => { myFunction()});` which doing the updating of X,Y coordinates for the selected object. I tried putting `return` statement before the object:modified ends but it doesn't work.

Problem: If I click the object it fires the event for updating the X,Y which should be not execute. So technically if the user only click the object it will show a modal but if it moves to a new location it will trigger the updating of x,y coordinates without opening the modal.

**Comment by asturur** [comment]
please create a fiddle that demonstrate the problem.

a minimal code sample that reproduce the problem  you are describing.
