### ISSUE TITLE
Text displacement issue.

### ISSUE THREAD

**Issue by mirshokraie** [kangax/fabric.js#4608]
The text 'y' location in node canvas is different from the browser canvas. I'm using fabricjs 1.7.11 and node canvas 1.6.x. Downgrading node canvas to 1.3.16 solved the issue, but I'm not sure whether the root cause of the problem is in fabric or node canvas.

## Version
1.7.11

**Comment by asturur** [comment]
is in node canvas for sure, but you should provide a fiddle to node-canvas or here to show the difference. a plain non fabricjs code that show different results
