### ISSUE TITLE
Why? It's not clear to print the paper

### ISSUE THREAD

**Issue by ligl** [kangax/fabric.js#4615]

**Comment by jilster** [comment]
Very well formulated issue.. maybe you should look into the basics of DPI before making stupid accusations

**Comment by asturur** [comment]
Cool that you could find any accusation in here.

**Comment by jilster** [comment]
He is basically saying that content on a Fabric canvas is not clear when it is printed out on paper, which is not a Fabric related issue, but a issue with almost everything that is projected on a screen. Basic knowledge of screen DPI vs print DPI should have made that obvious. If that is not what he meant, he should have used more words 🤣

**Comment by asturur** [comment]
@ligl if you feel like adding more details i will reopen the issue.
