### ISSUE TITLE
3000 or more lines in a group causes distorted colors and blurry lines

### ISSUE THREAD

**Issue by odyth** [kangax/fabric.js#4616]
The fiddle attached is 1.7.20, but this happens for 1.7.22 and latest 2.0.0 alpha as well.  1.7.7 through 1.7.13 work (didn't try before 1.7.7).  This seems to have stopped working as of 1.7.14 from my testing.

If you set MAX_SIZE to 1024 the lines will look correct, however anything over 1500 and you see the lines become darker in some places than others and become blurry, which is very strange.  If you don't put the lines in a group you don't get this behavior, but you instead have awful performance as there are 6000 lines on the canvas.  

Thanks,

https://jsfiddle.net/csq83jsf/2/

**Comment by asturur** [comment]
http://fabricjs.com/fabric-object-caching

Please read that page fully to understand how caching works.
You can enlarge the maximum size of caching in order for it to look good.

Think a bit why you need that grid.
if you need as a grid an nothing else, you could get away with a pattern that fills a rect.

The rect would be cached anyway, so real time speed would not change, but serialization, deserialization would be fast, provided you have a link for your basic grid cell.

**Comment by mudin** [comment]
@odyth Did you make it work using caching? Could you share new working jsfiddle?

**Comment by odyth** [comment]
I discovered (probably read somewhere) that if you use an image rather than drawing it, things work much better. I upgraded to "2.0.0-rc.4" and drew my grid like this

```
var rect = new fabric.Rect({
        top: 0,
        left: 0,
        width: MAX_WIDTH,
        height: MAX_HEIGHT,
        selectable: false,
        evented: false,
        objectCaching: false
    });
    _canvas.add(rect);
    _canvas.sendToBack(rect);

    fabric.util.loadImage(imageUrls.GRID_IMAGE,
        function (img)
        {
            rect.set("fill",
                new fabric.Pattern({
                    source: img,
                    repeat: "repeat"
                }));
            _canvas.renderAll();
        });
```

MAX_WIDTH = 3000, MAX_HEIGHT = 3000
imageUrls.GRID_IMAGE = ![grid-background](https://user-images.githubusercontent.com/947020/56845465-73382600-6876-11e9-8f7f-3922785af82a.png)

**Comment by mudin** [comment]
@odyth thanks a lot! [Here](https://jsfiddle.net/mudin/Lm0yj6xa/14/) is my grid with zoom based on your solution.
