### ISSUE TITLE
Demo Svg-caching in fabricjs.com/demos. When click to "toggle cache" all images freezed or disappear.

### ISSUE THREAD

**Issue by blucobalto** [kangax/fabric.js#4622]
Hi,
in demo Svg-caching (fabricjs.com/demos),
when click to "toggle cache" all images freezed or disappear.

Thanks a lot,
Blu

## Version
2.0 rc4

## Test Case
http://fabricjs.com/svg-caching

## Steps to reproduce
Click "toggle cache" button

## Expected Behavior
All images visible and rotated.

## Actual Behavior
All images freezed (IE11) or disappear (Firefox/Chrome)

**Comment by asturur** [comment]
thank you for reporting.
i see they are not re rendered, and each frame take more than one second, something is going wrong

**Comment by asturur** [comment]
fixed
