### ISSUE TITLE
patternTransform not saving via canvas.toJSON

### ISSUE THREAD

**Issue by DangerD256** [kangax/fabric.js#4625]
patternTransform not saving via canvas.toJSON.
Any way to change that?

**Comment by asturur** [comment]
yes with a fix.

**Comment by DangerD256** [comment]
omg, instant reply, what a fix?

**Comment by asturur** [comment]
I was on computer i got email, i replied.
If is not in the toJSON is wrong, i need to fix it.

**Comment by asturur** [comment]
Should be fairly easy, look at the pattern.class.js toObject method,you probably have to just add it there.

**Comment by DangerD256** [comment]
Added, works fine. Add it please to next release =)

**Comment by asturur** [comment]
why you just do not open a PR and make a contribution? can you do it?

**Comment by DangerD256** [comment]
Done, first time did pr =)

**Comment by DangerD256** [comment]
Another question with saving propertys, i have group of svg images with id's, when saving svg transforms to path and id's are lost. Any way to keep them without changing library?

**Comment by asturur** [comment]
so ids should be really exported by default since many people uses it, anyway the standard supported way is to do:

```canvas.toObject(['id'])``` this is going to export the additional property 'id' for each object.
you can also add more ```canvas.toObject(['id', 'otherProp', 'anotherProp'])```
