### ISSUE TITLE
Added JSON Objects To Canvas Are Not Resizeable

### ISSUE THREAD

**Issue by jrking4** [kangax/fabric.js#4628]
## Version
2.0

## Test Case
http://jsfiddle.net/Da7SP/800/

## Steps to reproduce
Move mouse to scaling controls on corner of newly created activeSelection. The handles do not work. Only when you deselect objects and then reselect them with your mouse will you be able to scale the activeSelection as desired

## Expected Behavior
The created objects & active selection should be able to be resized/scaled as needed.
## Actual Behavior
The objects are able to be moved, however scaling does not seem to work. Also rotate doesn't seem to work either

**Comment by asturur** [comment]
Hello @jrking4, please check here:
http://fabricjs.com/v2-breaking-changes-2

where it says how to create a multiselection.
That will solve.

**Comment by jrking4** [comment]
Thanks for the help and support! I added the canvas option to the ActiveSelection that is helpful.  However the problem is still there when I try and position the object using setPositionByOrigin. 
Look in the updated fiddle 

http://jsfiddle.net/Da7SP/803/

Notice a few issues and observations:
-The scale handles and rotate handles dont work. 
-If you grab the top left or bottom left puzzle piece object. It moves on its own and the rest of the objects stay in place.
-If you grab the top right or bottom right puzzle piece objects. The whole selection moves as it should. Once you move it a little the scale and rotate handles seem to become active

**Comment by jrking4** [comment]
Calling setCoords() seems to fix any issue after moving the object with setPositionByOrigin
