### ISSUE TITLE
Better error message when new is missing from object initialization.

### ISSUE THREAD

**Issue by jsjolen** [kangax/fabric.js#4630]
## Version
1.7.22

## Test Case
https://jsfiddle.net/xq239zwy/

## Steps to reproduce
Run the above code

## Expected Behavior

An error message similar to "Perhaps you forgot to write new?"

## Actual Behavior

TypeError: Cannot read property 'apply' of undefined
    at Object.klass (/home/loredge/src/LoredgeClient/node_modules/fabric/dist/fabric.js:2012:22)

**Comment by asturur** [comment]
Hello @jsjolen,
i thought about this a bit.

Probably fabric will get some error management for devs, with a special build.

But those errors are common JS errors, putting new in front an instance creation is not a fabric option, is just how things works in JS.

Nothing i can help about

**Comment by jsjolen** [comment]
@asturur , thank you for your quick reply :-)!
