### ISSUE TITLE
Text fill color not updating.

### ISSUE THREAD

**Issue by RobArbor** [kangax/fabric.js#4632]
## Version
2.0
latest dev verison of fabric.js (https://rawgithub.com/kangax/fabric.js/master/dist/fabric.js)
can also reproduce this in 1.7.22

## Test Case
http://jsfiddle.net/8ca6pfnd/1/

## Steps to reproduce
1.  Fill in a hex color for example #F00
2.  Notice the color is not updated.
3. Change size.
4. Notice the size and color is updated.

## Expected Behavior
When changing the fill of the text, the color should be updated after `canvas.renderAll();`

## Actual Behavior
Color is not updated.

Tested in the following browsers:
Firefox: 57.0.3
Chrome: 63.0.3239.132

**Comment by asturur** [comment]
please read the doc relative to object caching on the website.

fabricjs.com/fabric-object-caching

**Comment by RobArbor** [comment]
Thanks i missed that part.

Changed `text.fill = val;` to `text.set('fill', val);`
and my issue is fixed 👍

**Comment by angular2-custom-componen** [comment]
> please read the doc relative to object caching on the website.
> 
> fabricjs.com/fabric-object-caching





https://brody-redskin12.github.io/variables/
