### ISSUE TITLE
why set translation feature looks very slow.

### ISSUE THREAD

**Issue by lightnightlee** [kangax/fabric.js#4638]
## Version
2.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Steps to reproduce
I build all components in the websit.
test.html

defined two button link to following function.
  
 "canvastest2()"  move (button)
  "canvas_test()"  create (button)

<script>
function canvas_test(){

	// create a wrapper around native canvas element (with id="c")
		canvas = new fabric.Canvas('c');
		// create a rectangle object
		rect = new fabric.Rect({
		  left: 10,
		  top: 10,
		  fill: 'red',
		  width: 20,
		  height: 20
		});
		canvas.add(rect);
		rect.set({ left: 100, top: 100 })
	}
	function canvastest2(){

		rect.set({ left: 100, top: 200 })
		//debugger
		//setTimeout("canvastest2()", 2000);
	}
</script>
## Expected Behavior

I click the "create" button it will create the rect correctly and move the 100, 100.
I click the "move" button, it will move the rect to 100,200.
## Actual Behavior

"create" button behavior correctly.
When I click the "move" button, most of the time, it didn't have corresponding behavior.
sometime, it will move the right coordinate. 
if I enable the "setTimeout("canvastest2()", 2000);", the rect didn't move at all.

**Comment by lightnightlee** [comment]
sorry, reformat the question.
I build all components in the websit.

test.html
    #<button onclick="canvastest2()">move</button>
    #<button onclick="canvas_test()">create</button>

<script> function canvas_test(){
// create a wrapper around native canvas element (with id="c")
	canvas = new fabric.Canvas('c');
	// create a rectangle object
	rect = new fabric.Rect({
	  left: 10,
	  top: 10,
	  fill: 'red',
	  width: 20,
	  height: 20
	});
	canvas.add(rect);
	rect.set({ left: 100, top: 100 })
}
function canvastest2(){

	rect.set({ left: 100, top: 200 })
	//debugger
	//setTimeout("canvastest2()", 2000);
}
</script> 
## Expected Behavior 
I click the "create" button it will create the rect correctly and move the 100, 100. I click the "move" button, it will move the rect to 100,200.
 ## Actual Behavior
 "create" button behavior correctly. When I click the "move" button, most of the time, it didn't have corresponding behavior. sometime, it will move the right coordinate. if I enable the "setTimeout("canvastest2()", 2000);", the rect didn't move at all.

**Comment by asturur** [comment]
Can you reformulate this question with a better fiddle and eventually failing case?

I will in case reopen it.
