### ISSUE TITLE
this.canvas is undefined error thrown when removing IText inside mouse:down event

### ISSUE THREAD

**Issue by rkrueger11** [kangax/fabric.js#4640]
## Version
at least 1.7.7 -> 2.0.0-rc4

## Test Case
https://jsfiddle.net/rkrueger11/yghu8dbq/

## Steps to reproduce
1. Open the browser js console.
2. Click on the rectangle to remove.
 - Notice no error is thrown.
3. Click on the text to remove.
 - Note the error thrown.
4. Click anywhere else on the canvas.
 - Note the second error thrown.

## Expected Behavior
No errors should be thrown.

## Actual Behavior
Two `this.canvas is undefined` errors are thrown which prohibit further execution of code in the stack.

**Comment by asturur** [comment]
thanks for the clear fiddle.
I'll post a fix today or tomorrow if i found the bug and release the version
It will be fixed on 2.x only probably

**Comment by asturur** [comment]
The default event handler for mouse down gets excuted after the generic canvas mousedown.
Removing the object from the canvas makes the mousedown event handler fail.
i safeguarded it with a check that the object is on a canvas before executing.

**Comment by rkrueger11** [comment]
No problem. Hm.. it seems that fiddle continues to fail on v2.0.2.  Do I need to override that handler now?

**Comment by asturur** [comment]
what a shame.... is failing somewhere else later in the chain.
:(
