### ISSUE TITLE
Add an object to a transformed group

### ISSUE THREAD

**Issue by sajjad-shirazy** [kangax/fabric.js#4642]
Hi there,

I wanna add an object to a transformed group and have it as others transformed.
for example i wanna place the new green rect to the top left of the blue rect. which works in the not transformed state:
http://jsfiddle.net/75rahr91/
but when i scale and rotate the group a bit i faced that this does not work right anymore:
http://jsfiddle.net/3szsfyj9/
i want the new green rect exactly like the prev but rotated and scaled in the local space of the group like the other object.

Is any solution?
thanks

**Comment by asturur** [comment]
http://fabricjs.com/using-transformations

i think this should help in working with those use cases
