### ISSUE TITLE
Ungrouping of grouped object not working

### ISSUE THREAD

**Issue by archirayan3** [kangax/fabric.js#4643]
## Version
2.0

## Test Case
http://jsfiddle.net/anwjhs2o/84/

## Expected Behavior
It should separate all grouped objects from there.
## Actual Behavior
Its just hides the grouped objects and only remain selection box.

Basically i have old working code like this,

  ```
var items = activeObject._objects;
  activeObject._restoreObjectsState();
  canvas.remove(activeObject);
  for(var i = 0; i < items.length; i++) {
    canvas.add(items[i]);
    canvas.item(canvas.size()-1).hasControls = true;
  }
  canvas.remove(activeObject);
  canvas.renderAll();
```

This was working before i migrated to V2. Now i just want a solution to solve this. Please help.

**Comment by asturur** [comment]
http://fabricjs.com/manage-selection

FabricJS has 2 new methods

`group.toActiveSelection()
`
and

`activeSelection.toGroup()
`

change your group in active selection and then deselect it.

**Comment by archirayan3** [comment]
thank you so much :)

**Comment by gaooyao** [comment]
Very useful,thank you. @asturur

**Comment by Alphacapitan** [comment]
Thank you so much @asturur. However, are there any way to preserve objects z-index when using toActiveSelection function ?
