### ISSUE TITLE
object:scaling

### ISSUE THREAD

**Issue by hongxiang110** [kangax/fabric.js#4644]
this.canvas.on("object:scaling",e=>{
    const scaleX = object.scaleX;
    const scaleY = object.scaleY;
    const scale = scaleX>scaleY?scaleX:scaleY;
    object.set({strokeWidth:1/scale});
 })
when go to flip repeatedly,object will show error,stroke will be wide.
![a2](https://user-images.githubusercontent.com/32892562/35319480-f6e88360-011a-11e8-963b-0f6887d62269.png)

**Comment by asturur** [comment]
Please provide a fiddle that errors.
