### ISSUE TITLE
'shifted' problem of free drawing

### ISSUE THREAD

**Issue by jefybai** [kangax/fabric.js#4646]
## Version
Latest version

## Test Case
http://jsfiddle.net/Da7SP/812/

Hi:
I use ‘free drawing’ to draw a line on canvas. When I finish drawing, the line is shifted and changed location automatically.

 with the following code:

       fabric.Object.prototype.originX = fabric.Object.prototype.originY = 'center';

       canvas.freeDrawingBrush = new fabric.PencilBrush(canvas);
       canvas.freeDrawingBrush.color = '#DFDFDF';
       canvas.freeDrawingBrush.width = 5;

I have not found this problem in version 1.7.17, but in Latest version this problem is triggered by following code:

        fabric.Object.prototype.originX = fabric.Object.prototype.originY = 'center';

**Comment by asturur** [comment]
latest version is 1.7.22

**Comment by jefybai** [comment]
@kangax Yes, 1.7.22,  have this problem .

**Comment by asturur** [comment]
with 1.7.22 it works good
http://jsfiddle.net/Da7SP/814/
