### ISSUE TITLE
fabric.Group with fabric.Circle are shown incorrect (fabric.loadSVGFromString / fabric.loadSVGFromURL)

### ISSUE THREAD

**Issue by Kienz** [kangax/fabric.js#4648]
## Version
2.0.0-rc.4

## Test Case
http://jsfiddle.net/Kienz/9z2m7Ly6/4/

## Steps to reproduce
Load the jsfiddle and you see it. the green circle should be placed centered. If you load the same svg string on http://fabricjs.com/kitchensink it works as expected.

## Expected Behavior
Green circle should be placed centered - see http://fabricjs.com/kitchensink

**Comment by asturur** [comment]
@Kienz  is fixed in the latest master.
I cleaned up the circle constructor, and i did not notice that our .setRadius was indeed overriding the width and height that were incorrectly leaking from svg import from the document.

Now i stopped the props leaking from document to inner element.

**Comment by asturur** [comment]
I think on kitchensink there is the very latest master, since i updloaded a small tutorial and with it the latest library.
