### ISSUE TITLE
SVG behaving odd when loadfromjson

### ISSUE THREAD

**Issue by archirayan3** [kangax/fabric.js#4654]
## Version
2.0

## Test Case
http://jsfiddle.net/fmgXt/1087/

## Steps to reproduce
I have old json code from my old fabric site. so i used your given patch to make "path-group" to "group", that is worked ok first time. but when i load it using loadfrom json then it cause the issue.
load this fiddle and then click on "get json" button. Then after that click on put json button. you will see the difference there.

## Expected Behavior

it should not change the path-group

## Actual Behavior

as you can see it is changing the pathgroup.

**Comment by asturur** [comment]
i see the problem. I think i need some time to figure out why it display good and save wrong
