### ISSUE TITLE
How could I use other units like 'mm'?

### ISSUE THREAD

**Issue by Leonewu** [kangax/fabric.js#4655]
## Version
2.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Steps to reproduce
i saw the source code . there is a fn : parseUnit  , but it seems that the fabrci doesn't use this fn when I initialize fabric object ? Does it just support the 'px'?

**Comment by asturur** [comment]
The unit support is just for SVG parsing.

what you can do is for example:

rect.width = fabric.util.parseUnit('30mm')

but this will work with fixed DPI of 96 ( or 72 i do not remember )

**Comment by Leonewu** [comment]
I just think that maybe I can write like this:
var rect = new fabric.Rect({
        width : '150 mm',
        height : '100 mm',
        fill : red
    });
or  there maybe has a global config when I initialize the object ,like 
 var rect = new fabric.Rect({
        width : '150',
        height : '100',
        fill : red,
        unit : 'mm',
        DPI : 96
    });
I am writing a label printer so i have to change the 'px'  to 'mm' for printer then change the 'mm' to 'px' for user. 
Thanks for your answer !

**Comment by asturur** [comment]
so the canvas produce a 72DPI sized file in PNG.
If you need conversions those are on the app side of the things, and you should do them by yourself.

Nothing that is really fabric related.
