### ISSUE TITLE
Blend Image Filter does nothing in demo page

### ISSUE THREAD

**Issue by superdav42** [kangax/fabric.js#4658]
## Version
2.0 rc4

## Test Case
http://fabricjs.com/image-filters

## Steps to reproduce
Click an Image, Click "Blend Image" 
## Expected Behavior
Image appears as a blend of two images.
## Actual Behavior
Image disappears

Maybe disappearing is the correct action for the code in the demo. In which case the demo should be updated show something useful for understanding how image blending works.

**Comment by asturur** [comment]
ahhh is broken.
Thanks for reporting

**Comment by asturur** [comment]
bug in fabrics, fixing.
