### ISSUE TITLE
canvas.toSVG() with shadow and custom fonts is not working fine.

### ISSUE THREAD

**Issue by nitin-bc** [kangax/fabric.js#4665]
Hi,

We are using canvas.toSVG() function to get the vector output. Everything looks fine. But when we use the shadow or outline for text and use custom fonts and open the generated SVG image in illustrator or coral draw then we can't see the shadow effect there. Once we open it as an image viewer or in the browser, it works well.

Is someone can help me out regarding the same?

Thank you.
[svg.zip](https://github.com/kangax/fabric.js/files/1688118/svg.zip)

**Comment by aggrosoft** [comment]
First, you should ask this question on stackoverflow - second, what version of illustrator are you trying? Maybe using the most recent version will render the shadows correctly? If the browser shows it and your graphics program does not then maybe the graphics program just does not render all of the SVG features.

**Comment by asturur** [comment]
There is no such thing as `shadow` in svg.
If you look closely at the generated SVG, is made with a filter effect, way too complicated.
Verify that corel draw and illustrator ( illustrator does not really play nice with SVGs ) support filters.
Nothing we can really help here with.
