### ISSUE TITLE
Error : setText is not a function

### ISSUE THREAD

**Issue by archirayan3** [kangax/fabric.js#4669]
## Version
2.0

## Test Case
http://jsfiddle.net/anwjhs2o/89/

## Steps to reproduce
Please go to the fiddle link above.
open the console
and click on the change text 

## Expected Behavior
the textbox should change the text.
please let me know what should be the alternate function of setText if its changed.

## Actual Behavior
it shows an error with setText is not a function.

**Comment by asturur** [comment]
http://fabricjs.com/changelog

Read the change about named setter and getters.
You need a custom build to use them, or you need to stop using them in favor of:

set('text', value)

**Comment by archirayan3** [comment]
is there some detailed document on getters and setter for more understanding ?

as mentioned in the link above "Named setters/getters are optional and disabled by default".
so do i need to enable that by something ?

or i have to make a custom function, and have to find text in the object and replace that.
for change the text ?
