### ISSUE TITLE
Fee drawing path saved to variable, how to create new path from data?

### ISSUE THREAD

**Issue by paulcanning** [kangax/fabric.js#4670]
I'm struggling with something I feel is quite simple.

I am using the free drawing mode to create paths. The path is saved on the path:created event to a variable.

At any point, I'd like to be able to make a new Path, using the saved path data.

How do I do this?

**Comment by asturur** [comment]
Can you show your code? the pencil brush create exactly paths and fabric.Paths.

How are you using it?

**Comment by paulcanning** [comment]
On my mobile right now but I'm literally saving the event data from "path:created" and that's where I got to.

So I have the full path data saved in a variable. But what then? How do I reset add it to the canvas? I looked at fabric.path but that seems to want the path coordinates written out?

**Comment by asturur** [comment]
what you get in path:created is an easy to use fabric.Path.

**Comment by paulcanning** [comment]
I don't know what else to say. I do not understand how to make the path using the saved data.

Is it just canvas.add(savedData)? Can you make a JS fiddle to help me?

**Comment by asturur** [comment]
http://jsfiddle.net/Da7SP/820/

GIve a check to this fiddle, i have no idea if this is what are you searching for.

**Comment by asturur** [comment]
not being an issue with code and library i ll close this, fill free to continue asking.

**Comment by KonMost** [comment]
this is very interesting. I would like to track the width of each individual path point, to update the path width dynamically.
would you suggest adding the width into the path:created array?
