### ISSUE TITLE
textBakgroundColor not covering whole text when changing object property

### ISSUE THREAD

**Issue by satendra02** [kangax/fabric.js#4671]
I have added a `Textbox` object to canvas, when i am trying to change _fontFamily_ and _fontWeight_ of `Textbox`, sometimes the `textBackgroundColor` not cover the whole text.

<img width="376" alt="screen shot 2018-01-28 at 3 23 30 pm" src="https://user-images.githubusercontent.com/6327702/35766898-a2726046-0906-11e8-98c9-c7a2fd1b8dbf.png">

I have created a [jsfiddle](https://jsfiddle.net/2yL3mvrx/10/) to showcase this issue.
Also asked same question on [StackOverflow](https://stackoverflow.com/questions/48485058/fabric-js-textbakgroundcolor-not-covering-whole-text-when-changing-object-proper)

**Steps to reproduce:**

- Select textbox object, change fontFamily from Merriweather to Lato

- Then change fontWeight from normal to bold

Thanks for the help.

**Comment by asturur** [comment]
can i ask you to briefly try also with a browser that is not chrome? there is some bad chrome bug right now

**Comment by asturur** [comment]
Is a font loading problem, i answered you on stackoverflow
