### ISSUE TITLE
Free drawn path edges clipped and blurring

### ISSUE THREAD

**Issue by paulcanning** [kangax/fabric.js#4672]
Using the free drawing mode, and a slider to change the path width, I am seeing some odd issues.

1. Using a large width, the edges of the path appear clipped to a bounding box
2. Sometimes the path is drawn and is heavily pixelated

Screenshot attached

<img width="729" alt="screen shot 2018-02-03 at 20 14 57" src="https://user-images.githubusercontent.com/1275739/35771134-a9c07a72-091f-11e8-8e34-fd5c01be51d7.png">

**Comment by asturur** [comment]
I need a fiddle that reproduce the problem.
Can you reproduce it constantly?
please also avoid chrome 64 until is fixed.

**Comment by paulcanning** [comment]
https://jsfiddle.net/omkap4hb/

Use the slider to change the pen size (right = larger) and draw in the canvas. The path will be drawn correctly, but after letting go of the mouse button, the edges get clipped.

**Comment by asturur** [comment]
i think is a 1.7.x problem only. i ll mark as it and try to figure out why.

any reason that my usefull to me about why not starting with 2.0?

**Comment by paulcanning** [comment]
Just tried v2 rc4 - same issues :(

Why would my code do this when the demo is fine? :/

**Comment by asturur** [comment]
oh wait... wait.
are you sure you are putting a number and not a string that looks like a number?
Docs says numbers, html input give back strings.

**Comment by paulcanning** [comment]
:|

I've now parsed the value to an integer.

Why does it even partially work, letting me use a string value and actually drawing the paths with the selected size?

I think you need to define the parameter types to stop stuff like this?

**Comment by asturur** [comment]
I prefer to not add code to handle those things. As devs we are all supposed to read docs, but we do not read doc often, me included. But we should do.

It works partially because the width get to NaN or to string, and the minimum cache size probably win over those 2 things.

A dev layer is planned for fabricjs but requires lot of time to setup properly.
