### ISSUE TITLE
isOnScreen makes mistakes when zooming

### ISSUE THREAD

**Issue by karcass** [kangax/fabric.js#4673]
## Version
2.0b4

## Fiddle

This is totally ugly, but:
https://jsfiddle.net/karcass/a6bw1thu/15/

## Repro

There's a black + through the center of the canvas, and a green + that tracks the mouse cursor.  If you two-finger swipe up/down, you will zoom in/out.  If you zoom in too far, the green + will vanish, even though it will continue to intersect the screen.

## Speculation

It looks to me like zooming requires that 
(a) the `intersectsWithRect` call in `isOnScreen` should incorporate the parameter `calculate`
(b) `calculate` needs to be `true` in order to pick up changes to zooming

I'm not 100% sure if this is the best possible fix, but it definitely fixed my problem (which did not exists in 1.x).

## Patch that fixed it for me

```
homsar:drafty max$ git diff lib/fabric.js 
diff --git a/lib/fabric.js b/lib/fabric.js
index efb4d31c..e48fb666 100755
--- a/lib/fabric.js
+++ b/lib/fabric.js
@@ -12869,7 +12869,7 @@ fabric.util.object.extend(fabric.StaticCanvas.prototype, /** @lends fabric.Stati
       if (this.isNotVisible()) {
         return;
       }
-      if (this.canvas && this.canvas.skipOffscreen && !this.group && !this.isOnScreen()) {
+      if (this.canvas && this.canvas.skipOffscreen && !this.group && !this.isOnScreen(true)) { 
         return;
       }
       ctx.save();
@@ -14116,7 +14116,7 @@ fabric.util.object.extend(fabric.StaticCanvas.prototype, /** @lends fabric.Stati
         }
       }
       // no points on screen, check intersection with absolute coordinates
-      if (this.intersectsWithRect(pointTL, pointBR, true)) {
+      if (this.intersectsWithRect(pointTL, pointBR, true, calculate)) { 
         return true;
       }
       // worst case scenario the object is so big that contains the screen
@@ -24665,7 +24665,7 @@ fabric.Image.filters.BaseFilter.fromObject = function(object, callback) {
       if (!this.visible) {
         return;
       }
-      if (this.canvas && this.canvas.skipOffscreen && !this.group && !this.isOnScreen()) {
+      if (this.canvas && this.canvas.skipOffscreen && !this.group && !this.isOnScreen(true)) {
         return;
       }
       if (this._shouldClearDimensionCache()) {

```

**Comment by asturur** [comment]
So isOnScreen works with absolute coordinates for objects.
The canvas for corners get calculated at each render anyway
When fiddling with viewport (zoom and pan) the absolute coordinates do not change, so this should not be an issue.

Something else is going on. How do you replicate this problem?

**Comment by karcass** [comment]
Updated with fiddle.  _shakes tiny fist_

I am rending many hundreds of objects without perceivable performance degradation, but I'd be delighted if you figure out a better answer.

**Comment by asturur** [comment]
I would like to try. What is actually going wrong with your fiddle? the green cross hair is making mistakes?

**Comment by asturur** [comment]
Are you changing some top and left or width, height, scaleX, scaleY, angles during CUSTOM mouse events?
In that case calling `setCoords()` on the modified objects should fix all your isOnScreen mistakes.

**Comment by karcass** [comment]
Ok, looks like I wasn't being aggressive enough with setCoords.  User error.

**Comment by asturur** [comment]
setCoords is like using true in the other place, just you do on request per object and not automatically every frame every object.

**Comment by karcass** [comment]
Do you have a PayPal address?  I want to send you a couple bucks for
wasting your time.

**Comment by asturur** [comment]
do not worry! if you want to contribute put a couple of bucks on an open
issue you like with bountysource or write a tutorial.

Thanks anyway!

**Comment by revilofr** [comment]
> Ok, looks like I wasn't being aggressive enough with setCoords. User error.

The Fiddle is not working anymore but thx for this answer it helped me a lot

I am in a Pannable/Zoomable canvas scenario.

I was in the case where I was moving a partially onScreen object from the edge of the canvas to the center. This Object has some other object linked with (not onScreen)

My problem was that when I moved the partially onScreen objects  toward the center of the screen the canvas didn't displayed the objects that were linked with it (because they were not onScreen Previously)

A simple setCoords() on object:move for those previously offScreen objects fixed that.

Hope it will help someone.
