### ISSUE TITLE
Redrawn paths are added in the wrong place

### ISSUE THREAD

**Issue by paulcanning** [kangax/fabric.js#4675]
It appears that thicker paths are being drawn in the wrong place on my canvas.

Notice that the thin (1px) lines are fine, but the thicker line has moved.

To redraw the path, I've supplying the path data and the strokewidth, so why would it be out of place?

Before, original drawing:
<img width="632" alt="screen shot 2018-02-04 at 13 48 39" src="https://user-images.githubusercontent.com/1275739/35778174-9226c2e8-09b2-11e8-818b-d5a364773726.png">

After, redrawn path:
<img width="633" alt="screen shot 2018-02-04 at 13 48 53" src="https://user-images.githubusercontent.com/1275739/35778181-a06b3b5e-09b2-11e8-8065-9335d29ea4db.png">

**Comment by asturur** [comment]
on which fabricjs version? there was something fixed between rc4 and now on strokewidths

**Comment by paulcanning** [comment]
I'm back on to 1.7.21

**Comment by asturur** [comment]
please at least 1.7.22, i do not remember what was fix when

**Comment by paulcanning** [comment]
Still seems apparent in 1.7.22

**Comment by asturur** [comment]
Does this happen on mouse up or after some operation?

What do you mean by redraw,

**Comment by paulcanning** [comment]
So I'm drawing the paths using free draw mode. Everything is fine.

I am saving the path data to the server and when you reload the page, all saved paths are added back to the canvas. It is at this point that the paths are drawn correctly but offset. 

Thicker paths seem to be affected more, so maybe strokewidth is doing something? 

But it happens in all versions.

**Comment by asturur** [comment]
i really need a fiddle to flag it as a bug.

Every action that bring to a bugfix requires time and we need share the load. 

I do not know how else can i do.

**Comment by paulcanning** [comment]
Could be tricky as I'm relying on data stored by the server. I'll see what I can do to help you to see what's going on.

Just a quick Q - after adding a path (regardless of where the data comes from) should I be doing anything after the `canvas.add()` operation?

**Comment by asturur** [comment]
no, if you take a path from the canvas doing Path.toObject(), and you add to canvas a path doing:

new fabric.Path(object.path, object), you should get the exact same result.

If it does not happen, that is something to solve.

**Comment by paulcanning** [comment]
Hmm, I was not using Path.toObject(), but instead was using the data from the path created event.

**Comment by asturur** [comment]
That is an object instance, and is not meant to be saved.
Is full of stuff that is not usefull.

**Comment by gitfrb** [comment]
I experienced a similar problem as that of paulcanning. I am writing an app that uses free drawing and I added your code to the place where I handle the path:created event. Indeed some (not all) paths are added at a different place. From the left value in the javascript developer tools and the drawing I would derive that the created path already has wrong left/top values. And when the path is added again it is drawn at these wrong coordinates.
Here ist the code I used (hope I did make the right calls like you suggested):
this.fabricjsCanvas is the fabric canvas.

    let objects = this.fabricjsCanvas.getObjects();
    let lastObject = objects[objects.length-1];
    let object = lastObject.toObject();
    this.fabricjsCanvas.add(new fabric.Path(object.path, object))

The file shows the effect of the drawing. I tried to draw simple numbers. The 1 is drawn at a different place. The 2, 3, and 4 are drawn (almost?) in the same place. 5 and 6 are offset again. 5 only in x direction but 6 in x and y direction.

Does this help you with that problem?

First time this problem occured when I serialized the canvas and deserialized it again. Probably it is the same effect as described above.
![drawing](https://user-images.githubusercontent.com/36382322/36077757-04470902-0f6f-11e8-8844-3bec6074c31d.png)

**Comment by asturur** [comment]
Can we have a fiddle that reproduces the problem 100%?

**Comment by gitfrb** [comment]
I built a fiddle but wasnt't able to reproduce the error. Currently I can't figure out why my application behaves this way and the fiddle doesn't. If I'll be able to find a solution I'll let you know.
Do you have any idea what might be the reason? I'm writing a fairly standard react/redux app.

**Comment by asturur** [comment]
@paulcanning how it ended? do you have still ths problem? did you manage to reproduce it 100%?

**Comment by paulcanning** [comment]
I ended up leaving it as I am unable to easily make a JSFiddle to show the issue. It was still apparent but I have moved to PaperJS for my project due to the better Path tools.

**Comment by asturur** [comment]
i love paperjs intersection and union in paths.

**Comment by paulcanning** [comment]
Ideally I'd want PaperJS path tools inside Fabric, as PaperJS SVG handling is a bit crap :(

**Comment by asturur** [comment]
ideally is possible, but requires understanding on who to port them, i wanted to do so, but i have a roadmap in mind and sticking to it for now. contribution are welcome.

**Comment by paulcanning** [comment]
I'd love to, but this is way out of my depth 😄

**Comment by gitfrb** [comment]
I found my bug. I assigned a string e.g. '1' to the width of the free drawing brush instead of an integer. Once I changed that everything worked fine. However, I'm not able to reproduce it in a fiddle. Rather strange.

**Comment by mvpick** [comment]
> I experienced a similar problem as that of paulcanning. I am writing an app that uses free drawing and I added your code to the place where I handle the path:created event. Indeed some (not all) paths are added at a different place. From the left value in the javascript developer tools and the drawing I would derive that the created path already has wrong left/top values. And when the path is added again it is drawn at these wrong coordinates. Here ist the code I used (hope I did make the right calls like you suggested): this.fabricjsCanvas is the fabric canvas.
> 
> ```
> let objects = this.fabricjsCanvas.getObjects();
> let lastObject = objects[objects.length-1];
> let object = lastObject.toObject();
> this.fabricjsCanvas.add(new fabric.Path(object.path, object))
> ```
> 
> The file shows the effect of the drawing. I tried to draw simple numbers. The 1 is drawn at a different place. The 2, 3, and 4 are drawn (almost?) in the same place. 5 and 6 are offset again. 5 only in x direction but 6 in x and y direction.
> 
> Does this help you with that problem?
> 
> First time this problem occured when I serialized the canvas and deserialized it again. Probably it is the same effect as described above. ![drawing](https://user-images.githubusercontent.com/36382322/36077757-04470902-0f6f-11e8-8844-3bec6074c31d.png)

I fixed like you, thank you very much.
