### ISSUE TITLE
Image Filters

### ISSUE THREAD

**Issue by TanmayCoder** [kangax/fabric.js#4678]
Hi,
I am creating a new demo on image Filters (in html not angular )and other image related operations
I have added jquery min file as well as fabric jas min file 
but still it is giving error
Uncaught TypeError: fabric.WebglFilterBackend is not a constructor

I think i am missing any js
please let me know which js need to include

**Comment by asturur** [comment]
there are info here:
http://fabricjs.com/fabric-filters

read till the end
