### ISSUE TITLE
Image : setSrc() and src value

### ISSUE THREAD

**Issue by woltek** [kangax/fabric.js#4679]
Hi,

I have a question, when i use the setSrc() method on a image : 

The image is correctly update itself but in the object, the "src" value is still on the old  value.

Is there any way to refresh this value from js ?

Here is a fiddle : https://jsfiddle.net/woltek/sf1gbt69/2/
(the image showing up is not the same as the src value)

Hope you can help,

**Comment by jilster** [comment]
This is caused because you are not waiting for the callback of the setSrc(), i updated the fiddle and placed the code that shows the JSON into the callback, and now it is working:

https://jsfiddle.net/sf1gbt69/3/

**Comment by asturur** [comment]
thank you for looking into this @jilster
