### ISSUE TITLE
freedrawing slowly on low-profile phone.

### ISSUE THREAD

**Issue by boomyao** [kangax/fabric.js#4680]
```
for (i = 1, len = this._points.length; i < len; i++) {
        // we pick the point between pi + 1 & pi + 2 as the
        // end point and p1 as our control point.
        var midPoint = p1.midPointFrom(p2);
        ctx.quadraticCurveTo(p1.x, p1.y, midPoint.x, midPoint.y);

        p1 = this._points[i];
        p2 = this._points[i + 1];
      }
```

this is the way to free draw at mousemove event, but i think it's a bad way to draw on canvas.

**Comment by asturur** [comment]
Do you have suggestions to improve it?

**Comment by boomyao** [comment]
i found a better idea from drawingboard.js
https://github.com/Leimi/drawingboard.js/blob/92e2cfae33735efdd29885a0f564578055299293/js/board.js#L580

**Comment by asturur** [comment]
A pr to fix it is welcome.

**Comment by fredguth** [comment]
I will take a look at the suggested idea.  I am finally working on #4664.
