### ISSUE TITLE
CSS border rule affect canvas blurriness

### ISSUE THREAD

**Issue by jfgouda** [kangax/fabric.js#4681]
## Version
1.7 to 2.0

## Test Case
1st: Canvas with CSS border rule: http://jsfiddle.net/jgouda/154xs4gd/  
2nd: Canvas without CSS border rule: http://jsfiddle.net/jgouda/154xs4gd/1/

## Steps to reproduce
Mouse left click and drag to show selection, and notice the border of selection rectangle. 1st fiddle the selection rectangle border is a little thick. 2nd fiddle when canvas->border rule is removed the line is crisp and sharp. Its not only the selection.

For instance drawing grid, or adding rectangles and other shapes is getting affected.

## Expected Behavior
Adding border to the canvas should not affect object's sharpness.

**Comment by jfgouda** [comment]
Thank you, will research on that.

**Comment by asturur** [comment]
```box-sizing: content-box;``` should do it.

2018-02-06 0:06 GMT+01:00 John <notifications@github.com>:
