### ISSUE TITLE
Dynamic Fabric gird on canvas,

### ISSUE THREAD

**Issue by unitedsol** [kangax/fabric.js#4682]
Hello everyone here i have a question i am using this code for draw a grid line on fabric js canvas 

`var grid = 20;
function CanvasGrid() {
    for (var i = 0; i < (800 / grid); i++) {
        canvas.add(new fabric.Line([i * grid, 0, i * grid, 800], {
            stroke: '#ccc',
            selectable: false
        }));
        canvas.add(new fabric.Line([0, i * grid, 800, i * grid], {
            stroke: '#ccc',
            selectable: false
        }));
    }
}`

it works fine with the canvas width 800 max but what if we have a dynamic width and height so how we can cover the whole canvas with fabric grid line ?

any suggestion please thanks in advance.

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
