### ISSUE TITLE
Maintaining objects position on a higher image resolution

### ISSUE THREAD

**Issue by santosmken** [kangax/fabric.js#4683]
Hi, I have a question if you already did some work around for maintaining objects position if the user replace the image with a higher resolution. So it is like a picture of a garden wherein you place a bunch of bees on different positions. Now what I want to achieve is when I upload a new picture of garden (same image just different resolution might be smaller/bigger) the bees that was added before should stay on the same coordinates.

Hope you can help,

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

**Comment by asturur** [comment]
Please feel free to open a stackoverflow question, well written, with a starting fiddle of 2 images link and a couple of bees, and post the link here.
