### ISSUE TITLE
Crop Function:  Undo & Redo

### ISSUE THREAD

**Issue by chugah** [kangax/fabric.js#4692]
## Version
1.7.11

## Test Case
http://jsfiddle.net/Da7SP/835/

## Steps to reproduce
Ability to crop image and then undo and redo cropping. 

## Expected Behavior
When redo crop is selected, the image should be cropped again.

## Actual Behavior
When redo crop is selected, the image is not cropped again but the rectangle used to guide the cropping is cropped.

**Comment by jilster** [comment]
FYI, you are not using v1.7.11 in your fiddle, but master, which is 2.0.0 right now. I tried some thing in your fiddle but i can't seem to understand what is going on either.

**Comment by chugah** [comment]
Thanks for looking into it and I can't figure out what's going on with the redo crop function. Thanks for pointing out v2.0.0 is being used. I forgot that I quieted the script tag in the HTML to the v1.7.11 because I used the provided fiddle template and did not update it in the request.

**Comment by asturur** [comment]
This is better handled on stackoverflow.
Please open a question that is paired with a native stackoveflow fiddle and post the link here.

**Comment by chugah** [comment]
Thanks for your response.  Here is the link to this redo crop question using fabric js posted on stackoverflow:

https://stackoverflow.com/questions/48748850/redo-crop-functionality-with-fabric-js
