### ISSUE TITLE
Can't see search result at official doc hompage

### ISSUE THREAD

**Issue by pycraft114** [kangax/fabric.js#4694]
## Version
2.0

## Test Case
<img width="1431" alt="2018-02-09 2 05 46" src="https://user-images.githubusercontent.com/24728657/36012625-b1d9b944-0da2-11e8-8060-0c4f36c72f02.png">

## Actual Behavior

Can't see search result at official doc hompage

**Comment by jilster** [comment]
The <div class="gsc-results-wrapper-overlay gsc-results-wrapper-visible"> should be placed higher up into the body, like right after the <body> tag, to make this work

**Comment by asturur** [comment]
I fixed it, it was strange, i had to actually set the main body to z-index -1, no way to make it work otherwise.
I ll push it up shortly with new fabricjs
