### ISSUE TITLE
Custom _render: ctx.fillStyle vs this.fill

### ISSUE THREAD

**Issue by nickasd** [kangax/fabric.js#4695]
I have a custom object that extends the `_render` method as outlined in the tutorial in order to apply a fill color dependent on the object's state. The tutorial makes use of `ctx.fillStyle` to set a custom fill color, but when exporting the canvas to SVG it is necessary to set the object's `fill` property in order for it to draw correctly. Setting the `fill` property inside the `_render` function also doesn't seem to work properly.

Is it really necessary to set both properties when customising an object, or is there a better way?

## Version
2.0

## Test Case
http://jsfiddle.net/Da7SP/836/

## Steps to reproduce
1. Click the "toSVG" button. The SVG looks correct.
2. Select the square and click the "Change color" button.
3. Click the "toSVG" button again.

## Expected Behavior
The SVG should look as the canvas.

## Actual Behavior
The square in the new SVG has not changed color as in the canvas.

**Comment by asturur** [comment]
So your customization is strange.
Why you need to use a different prop to write the fill?

The toSVG methods are made to match the standard classes, and the SVG is not that much customizable, it renspond to FILL. so you can render your canvas coloring your object using `myProp` but then you have to create a toSVG method that sets the myProp value in the SVG fill property.

Maybe you should unfold more details on what are you trying to achieve.

**Comment by nickasd** [comment]
myProp is a property which determines how the object should render. In my case it just determines the fill color, so in my code there will be an expression inside the `_render` method that calculates it.

Maybe that's the wrong approach and I should instead create a separate function for that expression that sets the fill color so that it works for both render and SVG? Although I'm thinking that there might be more elaborate cases where just setting the fill color is not enough. I didn't test it but I would think that the example in the tutorial with the text inside the rectangle is not correctly exported to SVG. What do you think is the best approach to do so?

**Comment by asturur** [comment]
The approach is fine, as long as you are able to produce the necessary svg text strings to replicate the same effect on the SVG.
There is no automatic binding between canvas code and svg code, you have to make it happen.

your myRect class will have a custom made toSVG method

**Comment by nickasd** [comment]
Ok, I see your point and it makes sense. But I'm wondering if it would be possible to change the code so that setting properties inside the `_render` method would still work? Currently even if I just want to dynamically set the fill color I have to use `ctx.fillStyle`.
