### ISSUE TITLE
getBoundingRect() inside object:moving outputs initial data

### ISSUE THREAD

**Issue by jilster** [kangax/fabric.js#4696]
This is either a bug that has been around for ages, or it is not working as i expected. Or maybe i am doing something wrong. I checked the docs and searched Google but i can't find anything about this.

On object:moving, the objects position is updated continuously, but the objects getBoundingRect() always shows the initial properties of the starting position before moving. At first i thought i had to disable objectCaching, but that was not the solution.

## Version
Tested with 2.0.0, 1.7.22 and 1.6.0

## Test Case
http://jsfiddle.net/Da7SP/838/

## Steps to reproduce
- Open the fiddle
- Drag the rectangle and watch the inputs above the canvas
- Release the rectangle
- Drag the rectangle again

## Expected Behavior
- getBoundingRect() shows the updated properties during moving

## Actual Behavior
- getBoundingRect() shows the initial properties before moving

**Comment by jilster** [comment]
It seems that changes in width and height of the bounding box are not visible either on object:scaling. See http://jsfiddle.net/Da7SP/838/

**Comment by asturur** [comment]
```javascript
    /**
     * Returns coordinates of object's bounding rectangle (left, top, width, height)
     * the box is intented as aligned to axis of canvas.
     * @param {Boolean} [absolute] use coordinates without viewportTransform
     * @param {Boolean} [calculate] use coordinates of current position instead of .oCoords / .aCoords
     * @return {Object} Object with left, top, width, height properties
     */
    getBoundingRect: function(absolute, calculate) {
      var coords = this.getCoords(absolute, calculate);
      return fabric.util.makeBoundingBoxFromPoints(coords);
    },

```

You can call it with a boolean to specify if you want an immediate calculation for the updated boundingRect
