### ISSUE TITLE
About REACT and ANGULAR and other JS frameworks

### ISSUE THREAD

**Issue by rravithejareddy** [kangax/fabric.js#4704]

**Comment by asturur** [comment]
There is no need of official support.
I use react, i use fabricjs and i did not need any special code that it was not because of my particular application.

In React create your component, create a canvas element, and initialize fabricjs over it.
You do not need special react bindings.

**Comment by jilster** [comment]
I now use Angular and before this i used jQuery. It worked out of the box as well.

**Comment by rravithejareddy** [comment]
Thanks for information!
