### ISSUE TITLE
SVG output does not respect Image crop attributes 

### ISSUE THREAD

**Issue by semiadam** [kangax/fabric.js#4708]
Below fiddle uses height, width, cropX and cropY attributed in the way V2 suggests. Cropping happens correctly on canvas but upon downloading the SVG, the entire image is shown.

## Version
2.0

## Test Case
http://jsfiddle.net/Da7SP/841/
## Expected Behavior
Image must be cropped in SVG similar to canvas
## Actual Behavior
Entire image is shown in SVG

**Comment by asturur** [comment]
Yep need a fix.
