### ISSUE TITLE
discardActiveGroup() not working

### ISSUE THREAD

**Issue by semiadam** [kangax/fabric.js#4710]
I used discardActiveGroup() in my V1 code which now breaks after V2 upgrade. Couldn't find anything related to this in [breaking changes](http://fabricjs.com/v2-breaking-changes).

What's the equivalent in V2? I used this to remove the selection marks after I deleted selected items upon user request. Now the selection marks remain on canvas when the objects are deleted. Here's a fiddle:

http://jsfiddle.net/Da7SP/843/

**Comment by jilster** [comment]
There is also a breaking changes part 2, see: http://fabricjs.com/v2-breaking-changes-2

It changed to `discardActiveObject()`

**Comment by asturur** [comment]
Yes that page was temporary, but stayed like it was.
Keeping on docs is not that easy. Is harder than making the lib.

**Comment by semiadam** [comment]
Thanks guys!
