### ISSUE TITLE
fabric.require.js missing on v2.0.1

### ISSUE THREAD

**Issue by meriturva** [kangax/fabric.js#4713]
We cannot use new version because AMD compatible file is missing on 2.0.1 dist folder.
Thanks.

**Comment by asturur** [comment]
I intentionally removed it because is a double up build and github diff for 0 difference in code.
I thought it was safe to get rid of it.

**Comment by asturur** [comment]
i think that all you need is to have this code after fabricjs inclusion:

```javascript
window.fabric = fabric;

if (typeof define === 'function' && define.amd) {
  define([], function() { return fabric; });
}

```

**Comment by meriturva** [comment]
i see! thanks!

**Comment by asturur** [comment]
@meriturva i m adding back the footer with the 2.1.0 release.
Please note that i m doing it assuming it does not create problems to non requirejs users.
So fabric.js and fabric.min.js will have the footer.

If i found problems, i ll have to remove it.

**Comment by meriturva** [comment]
I will check as soon as possible. Anyway there is no fabric.min.js file on package. am i right?

**Comment by asturur** [comment]
should me min.js done with uglify and normal file

**Comment by meriturva** [comment]
I mean on file: https://registry.npmjs.org/fabric/-/fabric-2.1.0.tgz there is no min.js on dist folder.

**Comment by asturur** [comment]
this is an error.

**Comment by meriturva** [comment]
I checked and min.js file is not present on new version (2.2). Do i have to open a new issue just to keep it tracked?
Thanks

**Comment by asturur** [comment]
i double checked, lost track of this issue to comment.
The min.js was never in the npm package.
Probably because often npm installations and imports module, often means a custom build process.
I have no idea of the reason of not including the min.js file in the past, but is not a new problem
