### ISSUE TITLE
Drawing a polygon over an image 

### ISSUE THREAD

**Issue by zaidsheriff786** [kangax/fabric.js#4714]
## Version
2.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Expected Behavior
This piece of code runs perfectly in fabric js 1.5.the same fuctionality should be supported in newer version of fabricjs
## Actual Behavior
It not working in newer versions of fabric like 1.7.21 and higher.

**Comment by zaidsheriff786** [comment]
https://jsfiddle.net/u3bfscom/6/
This piece of code runs perfectly in fabric js 1.5 but not working in newer versions of fabric like 1.7.21 and higher.Please fix this issue.

**Comment by ncou** [comment]
please open a v2 or v1.7.x fiddle to show the error. 
and read the incompatibility changes beetween the v1.7 and v2.0.

**Comment by asturur** [comment]
not a bug. please ask help on stackoveflow for this kind of things
