### ISSUE TITLE
Version 1.7.17 suddently started giving issues on Chrome

### ISSUE THREAD

**Issue by atul-shimpi** [kangax/fabric.js#4717]
## Version
1.7.17

Hello,
I am using 1.7.17 in my application. 7 - 8 days back it was working fine on Chrome. However, recently
during load time when i m loading farbic js and using it to draw, chrome becomes unresponsive. On IE its working fine. Only chrome giving issues. On the browser console nothing error or exceptions are logged (either by chrome or farbic js). Strange thing is, i have not even changed the code in last 8 days.
Previosuly it was working. Just recently started giving issues.

**Comment by asturur** [comment]
You just updated chrome to a broken one.
That they are not fixing until chrome 65

**Comment by atul-shimpi** [comment]
ok. Thank you very much for update.

**Comment by asturur** [comment]
http://fabricjs.com/fabric-object-caching

try bump up minCacheSideLimit to 512

**Comment by asturur** [comment]
You can work around bumping the cacheSideLimit to 512.

**Comment by atul-shimpi** [comment]
OK. Let me try. That will really help


With warm regards,
============================================================================
Atul Shimpi
Mobile : 9890979429 | Skype : shimpiatul | www.HiAtul.com


________________________________
