### ISSUE TITLE
Limit numbers that are almost 0

### ISSUE THREAD

**Issue by Hatzas** [kangax/fabric.js#4719]
## Version
2.0.0-rc.1 to 2.0.1

## Test Case
http://jsfiddle.net/Da7SP/855/

## Steps to reproduce
See fiddle test case

## Expected Behavior
{"top":0,"left":0}

## Actual Behavior
{"top":7.105427357601002e-15,"left":0}

Regardless of the transformations, i would expect to use getBoundingRect() to get the correct top/left of the object relative to the canvas. 
For width and height, the correct dimensions are obtained by using strokeWidth = 0. 
Still, is there anything i'm missing for obtaining the correct top/left?

Note that this issue appears for any type of object (tested with triangle, circle, image). Also tested with getBoundingRect(absolute, calculate) and got same result.

**Comment by asturur** [comment]
That is some magic calculation happening.
Probably the cosin or sin of something that should give us 0 but is giving a weird number because of javascript float problems.

I'm planning to write a custom sin/cos function that give us the correct result for known angles.

**Comment by asturur** [comment]
I create a Pr to fix this. If it does not fix, there is nothing else i can think of to fix it.

**Comment by asturur** [comment]
So the PR effectively fix those weird numbers, when possible, when there is no angle.
I took an enormous amount of work and trial and errors, fabric math is really complicated and delicate.
