### ISSUE TITLE
How to use FontAwesome

### ISSUE THREAD

**Issue by Faha98** [kangax/fabric.js#4720]
Hello there, great project, i love how easy it's working with canvas!

I want to implemenet adding cliparts in my project, so fisrt lib with icons/cliparts which is comming to my mind is FontAwesome, is there any proper way using it with fabric js?(in internet therer is only one question about this, with no answer)

If it's not possible yet, what sollutions could you recommend me?

**Comment by asturur** [comment]
Open a question on stackoverflow please, and post the link there.
If there is just one question with no answer in all the internet, is better to talk about this in a more visible place.
