### ISSUE TITLE
How to rotate sprite image in 360 degree view in fabric js

### ISSUE THREAD

**Issue by zaidsheriff786** [kangax/fabric.js#4723]
## Version
2.0

## Test Case
https://jsfiddle.net/iamzaidsheriff/hk278r3b/

## Expected Behavior
When the user moves the mouse on right the frame on right side should moved and when the user moves on left the left side of the frames should me moved iam not able to implement this in fabric js.I want this rotation based on user interaction
## Actual Behavior
But the problem is iam not able to rotate the sprite image based on user interaction.What i have done is just rotating the sprite image onmouse move.Expected output i want is like this :https://codyhouse.co/demo/360-degrees-product-viewer/index.html

**Comment by zaidsheriff786** [comment]
This is my code:
<script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.7.21/fabric.js"></script>
<canvas id="canvas"></canvas>

var URL = 'https://codyhouse.co/demo/360-degrees-product-viewer/img/alfa.png';
var canvas = new fabric.Canvas('canvas');
var positions = {
  topSteps: 1,
  leftSteps: 16
};
var y = 0;
var x = 0;
var topStep;
var leftStep;
canWalk(URL, positions);
function canWalk(URL, positions) {
  var myImage = new Image();
  myImage.src = URL;
  //var mDown = false;      
  //onloadevent
  myImage.onload = function () {
    topStep = myImage.naturalHeight / positions.topSteps;
    leftStep = myImage.naturalWidth / positions.leftSteps;
    var docCanvas = document.getElementById('canvas');
    docCanvas.height = topStep;
    docCanvas.width = leftStep;
    fabricImageFromURL(x, y);
  };
}
//mouseevents 
canvas.on('mouse:out', function (event) {
  console.log("mouseout")
  /*  x=0;
  y=0;
  fabricImageFromURL(x,y);*/
});
canvas.on('mouse:move', function (event) {
  resetvalue();
  setTimeout(function () {
    console.log('value of x in start', x)
    console.log('positions.leftSteps', positions.leftSteps)
    if (x == positions.leftSteps) {

      y = 1;
      fabricImageFromURL(-y * topStep, -x * leftStep)
    }
    else {

      fabricImageFromURL(-y * topStep, -x * leftStep)
      if (x < positions.leftSteps) {
        x++;
      }

    }

  }, 50);

});

function resetvalue() {
  if (x == positions.leftSteps) {
    x = 0;
    y = 0;
    console.log("x and y value reset to0")
  }

}
function fabricImageFromURL(top, left) {
  console.log('fabricImageFromURL value', top, left);
  fabric.Image.fromURL(URL, function (oImg) {
    oImg.set('left', left).set('top', top);
    oImg.hasControls = false;
    oImg.hasBorders = false;
    oImg.selectable = false;
    canvas.add(oImg);
    canvas.renderAll();
  }, { "left": 0, "top": 0, "scaleX": 1, "scaleY": 1 });
}

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

**Comment by asturur** [comment]
What does it mean? I cannot understand.

**Comment by rajesh0608** [comment]
Hi,

reference - https://packlane.com/customize/mailer-box?quantity=250

If you select side. BOX rotate in different angle. Looking for this.
