### ISSUE TITLE
[Suggestion] Export unique objects

### ISSUE THREAD

**Issue by samael205** [kangax/fabric.js#4724]
Export objects

I do not know if this can be done, but I think it would be a good way to start a draft on the Clone Tampon.

*The idea would be to export a simple object, in this case, a polygon, created by the user, so that it can be stored in a database, for example.

Next, the user could load that object from fabric, with canvas.addObject.*

**Comment by asturur** [comment]
What is the difference with the current functionality  toObject -> fromObject?

**Comment by samael205** [comment]
ahh, so it's done. Thank you
