### ISSUE TITLE
Is it possible to clone object to another canvas? And guide me to it.

### ISSUE THREAD

**Issue by aschente** [kangax/fabric.js#4728]
I'm a newbie in canvas. Actually I'm want to clone the state of the canvas so I can just clone the canvas and I don't know if its possible and how to do it.

**Comment by aggrosoft** [comment]
you are more likely to get an answer on stackoverflow

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

**Comment by asturur** [comment]
you can post the opened question here.
