### ISSUE TITLE
Images dropping in to fabric canvas in react.

### ISSUE THREAD

**Issue by rravithejareddy** [kangax/fabric.js#4730]
I am using fabric with react, there i am trying to drop images on to canvas, but images are adding to lower-canvas only, and also drag event is not working on lower-canvas, events are working on upper canvas, i am struggling with this issue from 2 days, can you please help me to sort it out. please check below code.

 class Flow extends Component {
    constructor() {
        super()
         }
    componentDidMount() {
 
        window.fabricCanvas = new fabric.Canvas();
        var el = this.refs.objectsCanvas;
        fabricCanvas.initialize(el, {
            height: 800,
            width: 800,
        });
    }
    componentDidUpdate() {

    }

  drop(e) {
    e.preventDefault();
        var x = e.clientX;
        var y = e.clientY;
        var imagesOnCanvas = [];
        //  var image = new Image();
        //   image.width = 100;
        //   image.height = 100;
        var image = e.dataTransfer.getData("image_id");
        fabric.Image.fromURL(image, function (myImg) {
            myImg.set({
                left: x,
                top: y,
                padding: 10,
                cornersize: 10
            })

            fabricCanvas.add(myImg);
        }.bind(this));
        var mouse_position_x = e.dataTransfer.getData("mouse_position_x");
        var mouse_position_y = e.dataTransfer.getData("mouse_position_y");

        var images = [];
        images.push({
            image
        });
        this.setState({ imagesOnCanvas: images })
   }

    render() {
        return (
            <div>
                    <canvas ref="objectsCanvas" style={{ backgroundColor: 'rgb(106,110,123)' }}
                        onDrop={this.drop.bind(this)} >

                    </canvas>
                </div>
           
        );
    }

}

export default Flow;

**Comment by redlive** [comment]
I think you shouldn't create an issue.
Please create a "workig" jsFiddler and ask this question in Stackoverflow by adding **fabricjs** keyword.
They'll answer you and try to help.
👌

**Comment by asturur** [comment]
You can't really do it like this.
We have an ongoing work for drop events, i think now we can also finish and merge it.

**Comment by asturur** [comment]
Hey please try the drop/drag events that are merged since fabric 2.1.0 and let us know if they make your problem simpler.
