### ISSUE TITLE
Is it possible to clone this to another canvas?

### ISSUE THREAD

**Issue by aschente** [kangax/fabric.js#4731]
I have a canvas with images, text and etc. Is it possible to clone them to another canvas.

This is the canvas 1
![download](https://user-images.githubusercontent.com/8470020/36337074-f27af5b2-13c9-11e8-85c2-58ec9a91aefe.png)

`canvas2.loadFromJSON(JSON.stringify(canvas1), function(){
    	canvas2.renderAll()
}); `

its only showing the white background but not whole objects inside the canvas.

**Comment by jilster** [comment]
See https://github.com/kangax/fabric.js/issues/4728

**Comment by asturur** [comment]
var jsonString = JSON.stringify(canvas1.toObject());

canvas2.loadFromJSON(jsonString)... should work.

Verify kitchensink demo http://fabricjs.com/kitchensink  there is a json tab that allows you to save and restore
