### ISSUE TITLE
2.0.1 object:selected event not working properly

### ISSUE THREAD

**Issue by tkinali** [kangax/fabric.js#4732]
`object:selected` event of canvas works well in v1.7.22 but don't works properly in v2.0.1. It only triggers once and nothing happens afterwards.

Here you can find example: https://jsfiddle.net/tkinali/jwmtanba/11/
Select an object and try another object.

And same codes with v1.7.22 is working properly: https://jsfiddle.net/tkinali/x3mqe705/4/

**Comment by jilster** [comment]
See http://fabricjs.com/v2-breaking-changes-2, the part about events. You need selection:created and selection:updated now

**Comment by tkinali** [comment]
Thanks for your help @jilster,

I wasn't aware of the existence of such a link until you told me.

**Comment by pera** [comment]
This wiki pages needs to be updated: https://github.com/kangax/fabric.js/wiki/Working-with-events
