### ISSUE TITLE
Image setSrc, setElement and width/height value

### ISSUE THREAD

**Issue by scriptspry** [kangax/fabric.js#4733]
## Version
2.0.1

## Test Case

Tried to load the same image with exact same code and got different outputs.

v1.7.22 - [Code](https://jsfiddle.net/10t7b7kh/) - [Output](https://user-images.githubusercontent.com/19214202/36344091-37b49af4-143b-11e8-946d-24c8631facf7.png)

v2.0.1 - [Code](https://jsfiddle.net/huby9uuy/) - [Output](https://user-images.githubusercontent.com/19214202/36344093-3fd8a89c-143b-11e8-849a-9e53470c030a.png)

## Expected Behavior

Expected the full image to be rendered.

## Actual Behavior

Only got 1/4th? of the image rendered.

---

First off, I do have a "working" solution for even v2.0.1 [here](https://jsfiddle.net/a27dozgb/). But, it is a hack. Also, I have already gone through the v1 to v2 breaking changes documents, and read and understood the parts about fabric.Image and fabric.Image.fromObject.

Now, I have already spent a couple of hours of time on this, and came to a conclusion that library is misbehaving. Here's why:

1. width = 128 & scaleX = 1 !== width = 256 & scaleX = 0.5 !!!

If the width and scaleX semantics for other shapes: rect, circle etc are rendering same output for both cases. Why does Image behave differently? Is it not an inconsistency with interpretation of what width and scaleX values are?

2. We can almost never have scaleX as 1 for fabric.Image instances, except when image's width, height match fabric.Image object's width height.

This feels like a painful and limiting enforcement.

**Comment by scriptspry** [comment]
Hit command enter while editing by mistake and this got posted. Kindly allow me to edit this. Really sorry.

**Comment by asturur** [comment]
please have a look at the changelog here:
http://fabricjs.com/v2-breaking-changes#image

ScaleX and scaleY are the properties to us to shrink / enlarge an image.

**Comment by asturur** [comment]
The situation is what is stated in the docs.
If you need a picture, big 512px to display in 128px, use `scaleToWidth(128)`. That was the correct procedure also on 1.7

I do not see the inconsistency. Can you be more clear?

**Comment by asturur** [comment]
So on your end loading the image as empty and then setting the src, is complocating things. Probably setSrc should reset wodth/height bit this would wipe crop information.

**Comment by asturur** [comment]
Taking an image and doing set Src or swapping the element to draw, is something that generally is part of a custom logic. Maybe setSrc should also reset the image width and height to the one available for the  image.

**Comment by asturur** [comment]
Let's change title and keep.open for discussion.

**Comment by scriptspry** [comment]
@asturur After a little more lingering I found discussion about my exact problem at #4235 from last year.

Seems like @ozooner had already [fixed](https://github.com/kangax/fabric.js/issues/4235#issuecomment-339961727) this in their branch.

Here's the [updated fiddle](https://jsfiddle.net/pw3vy1qu/) that works with the forked v2 fabric build found in fiddle referenced in the comment.

It would be great to get the fix into the library. Image asset size should not effect (de)serialisation IMO.

**Comment by asturur** [comment]
So the deserialization from 1.7 is incompatible with 2.0, so the major version bump.
I posted a guide to restore images from pre 2.0

Here the problem is if a setSrc, should also fix width/height to full image or not.

**Comment by salomonsanz** [comment]
I agree with @scriptspry  i have the same problem when migrating from 1 to 2 version.
In my fabric app, in order to optimize the users bandwidth and load speed, when user scales up an image, i recalculate the src to get a bigger one with more quality, but when i make the "setSrc" with the new image quality, fabric "crops" the new image. In v1 this works ok.

**Comment by asturur** [comment]
definitely setSrc should reset width/height information and set cropX, cropY to 0.
