### ISSUE TITLE
is working this method fabric.loadSVGFromString with crossOrigin: 'anonymous' for Images?

### ISSUE THREAD

**Issue by rcarrionl** [kangax/fabric.js#4735]
I'm having a problem running canvas.toDataURL because console it shows me the Contaminated Canvas error, so I want to try to establish for my image crossOrigin, Is this possible?.

## Versión
Fabric js 2.0.1

## Test Case
https://jsfiddle.net/axzb3939/24/

## Steps to reproduce
Load the jsfiddle and press the export button.

## Expected Behavior
The image should be downloaded but it shows me the following error:
Error: Tainted canvases may not be exported.
-according to what I was reading is cause of crossorigin - Contaminated Canvas 

thanks.

**Comment by asturur** [comment]
This is not how to open an issue.
Please respect the request template you see when opening an issue. Including the fiddle

**Comment by rcarrionl** [comment]
hi @asturur , I updated my template and create an example.

**Comment by asturur** [comment]
Hi @rcarrionl  i updated your fiddle like this

https://jsfiddle.net/axzb3939/31/

i added support to the svg loader to load image with crossOrigin. But it looks like your hosting is not providing crossOrigin headers correctly.

I'll close the issue for now, continue to write in this issue if that change does not help you, but i cannot help you with generic cors problem if that is the root issue.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/36376122-450a8c58-1572-11e8-96cf-9ed2780563ca.png)

this error i get means i m correctly requesting the crossOrigin sharing, but the server is negating it.
If the server allows it, the export should then work.

**Comment by rcarrionl** [comment]
thank u so much asturur,you were right the server was denying it because of the CORS issue
![image](https://user-images.githubusercontent.com/36579196/36389546-5b831a72-156d-11e8-908e-6a9378b76e95.png)

So I decided to add this to my project, and it is working correctly with your correction in my example.
![image](https://user-images.githubusercontent.com/36579196/36389608-9f76ed80-156d-11e8-8d22-d9d64802e2da.png)

Thanks.
