### ISSUE TITLE
Text cursor position is incorrect after changing fonts (using font face observer)

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4739]
## Version
2.0.1

## Test Case
http://jsfiddle.net/blobinabottle/xsLgppan/16/

## Steps to reproduce
Change the text to Roboto and check last words of the fist line, the text cursor got an incorrect position. 
<img width="157" alt="screen shot 2018-02-18 at 18 22 37" src="https://user-images.githubusercontent.com/8090162/36354724-fa817f00-14d8-11e8-817a-92dea8f22820.png">

It's worst if you select pacifico (I'm selecting SIT :-)). 
![image](https://user-images.githubusercontent.com/8090162/36354731-060660f2-14d9-11e8-9a68-ce6bc795dbce.png)

## Expected Behavior
Cursor should be a the right position.

Is there anything to do to avoid this situation? I tried clearFabricFontCache but not sure I've done it right.

**Comment by blobinabottle** [comment]
fabricjs.com/loadfonts it's the same issue in this demo, just by switching to pacifico.

**Comment by blobinabottle** [comment]
The only way to get it working correctly I found, is by bypassing the cache system in the text:
http://jsfiddle.net/blobinabottle/xsLgppan/42/

Is that really important for perf? When is it called?

**Comment by asturur** [comment]
Very weird.
What do you mean bypassing the cache system? that you return always empty object and force fabric to calculate every time?

I do not understand whey calculation should fail just from the cache.

**Comment by blobinabottle** [comment]
yes in my getFontCache, I always return empty object... But I don't understand why it's working like that.

**Comment by blobinabottle** [comment]
Ok the culprit is here. We change the fontCache[_char] and I see this value changing with no reason for the same character in a same text block :
```
// try to fix a MS browsers oddity
        if (kernedWidth > width) {
          var diff = kernedWidth - width;
          fontCache[_char] = kernedWidth;
          fontCache[couple] += diff;
          width = kernedWidth;
        }
```

If I comment this it's working.

**Comment by asturur** [comment]
What is weird is that it does not happens with all fonts.
Pacifico is a particular weird font.

Look this gif i recorded
![testp](https://user-images.githubusercontent.com/1194048/36472480-41dab392-16f2-11e8-9cd1-eadff1267896.gif)


As you can see each gliph change to follow the next one, is like a kerning, inverse. This may bring to some kind of problem in measurement logic.

But needs to verified

**Comment by asturur** [comment]
Maybe when we measure the single char we should measure it with a space in front?

**Comment by blobinabottle** [comment]
yes I see what you mean, but I think the font measurement is correct. 
When the IE fix is removed everything is working fine (didn't get it again with many different fonts). Not sure to understand what the IE fix is doing ?

**Comment by asturur** [comment]
can you show me here the IE fix?

**Comment by blobinabottle** [comment]
It's in _measureChar method. I can't find it in GitHub UI (only in the raw file if I search for "// try to fix a MS browsers oddity")

**Comment by asturur** [comment]
just make a copy paste of your file, for reference here.

**Comment by blobinabottle** [comment]
jsfiddle.net/xsLgppan/72/ I updated the fiddle with the change.

**Comment by asturur** [comment]
i m sorry you already posted the fix here:

```
// try to fix a MS browsers oddity
        if (kernedWidth > width) {
          var diff = kernedWidth - width;
          fontCache[_char] = kernedWidth;
          fontCache[couple] += diff;
          width = kernedWidth;
        }
```

so what is happening is that MS measure fonts in pixels.
So a font of 11.1 is big 11 a font of 11.9 is big 12
Sometimes kerned Width was a little bit bigger because:

a = '11.3' => 11
b = '11.3 => 11

ab = 22.6 => 23

b kerned was then ab - b = 12.

and this was normally wrong.

But we see that with pacifico this is a possible use case.

So we need a better logic.

**Comment by blobinabottle** [comment]
Okay I understand now. So a little difference accumulates on long lines even with simple font like Roboto. And I see some discussion about it already happened long time ago :D https://github.com/Automattic/node-canvas/issues/331

**Comment by blobinabottle** [comment]
Are you sure this fix really worth it? Testing on IE without the fix, and this is the worst I can get in terms of offset... Very small.
![image](https://user-images.githubusercontent.com/8090162/36484337-3b8874b2-1719-11e8-8637-779ba492bd3f.png)

**Comment by blobinabottle** [comment]
With font yellowtail on IE 11.0 with the fix, it's pretty bad. Without it it's working quite well.

**Comment by asturur** [comment]
After that fix i inserted another safety measure about ie

CACHE_FONT_SIZE = 200

so i measure everything at 200 so that rounding measurement are a bit killed in this way.
i think i can bump it up to bigger and remove the IE fix maybe.

**Comment by blobinabottle** [comment]
indeed. And this is a smarter fix than the other condition

**Comment by asturur** [comment]
LOL is easy to say what fix is smarter when you did not had to find them in the first place :D  :D  :D  :D

**Comment by blobinabottle** [comment]
:-D In fact you already fixed all the bugs in advance, you just forget you did it :-D
