### ISSUE TITLE
SVG flickering transparency

### ISSUE THREAD

**Issue by luchomatic** [kangax/fabric.js#4745]
## Version
It happens in every version

## Test Case
http://jsfiddle.net/po9zw10g/

## Steps to reproduce
Add an SVG to the canvas and resize it or move it around

## Expected Behavior
It should be constant in terms of transparency

## Actual Behavior
The transparency flickers when moving or resizing the SVG

**Comment by asturur** [comment]
So safari and firefox do not have the left globe light, and they do not flicker.
Do you have chance to try it on some MS browser?

**Comment by asturur** [comment]
(it does not look like a fabric problem, more a browser related problem)

**Comment by luchomatic** [comment]
I think you're right, I'm reporting this to chrome

**Comment by Aubron** [comment]
Can confirm with latest IE and Edge, as well as viewing the SVG in browser. Left globe light is not part of the original SVG in that position, chrome is the only browser with broken rendering.

Browser bug

**Comment by asturur** [comment]
is that light at least a gradient or just a rendering problem?

**Comment by Aubron** [comment]
That light is nowhere immediately obvious, looking through the visual representation and source of the SVG. I'm not going to rule out that it might be a malpositioned element from somewhere I'm not looking, but if you remove the box this is the render on all browsers:

![screen shot 2018-02-22 at 11 45 03 am](https://user-images.githubusercontent.com/1171076/36551563-dcc40bdc-17c5-11e8-9ae0-4192def2ab2f.png)

**Comment by Aubron** [comment]
Much more minimal test case, with a very small svg.

http://jsfiddle.net/po9zw10g/13/

```
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="482pt" height="419pt" viewBox="0 0 482 419" version="1.1">
<path style=" stroke:none;fill-rule:nonzero;fill:rgb(12.220764%,30.929565%,63.66272%);" d="M 100.324219 141.222656 L 243.324219 200.722656 L 383.34375 141.347656 C 383.34375 63.535156 320.261719 0.457031 242.449219 0.457031 C 164.640625 0.457031 101.558594 63.535156 101.558594 141.347656 "/>
</svg>
```

I don't claim to be an SVG expert, but if we have some of those, that's your best bet for clues as to what is dying here. More likely a chrome bug than a malformed SVG though, especially given their recent issues.

**Comment by Aubron** [comment]
http://jsfiddle.net/Na6X5/1602/

^ Not a fabric bug.

**Comment by asturur** [comment]
i m going to close this. looks really hw acceleration related.
