### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined with compiling custom

### ISSUE THREAD

**Issue by manu89ftt** [kangax/fabric.js#4747]
Hi,
if I compiling with this parameters:

node build.js modules=ALL exclude=text,itext,easing,node,freedrawing

I see this error:

fabricBeta.js?t=165111111211:25092 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at fabricBeta.js?t=165111111211:25092
    at fabricBeta.js?t=165111111211:25420

Thankyou!

**Comment by asturur** [comment]
when you exclude text and itext, you have to exclude textbox too
