### ISSUE TITLE
SubTargets in custom group is empty

### ISSUE THREAD

**Issue by blucobalto** [kangax/fabric.js#4752]
Hi,
I created a custom group.

`var fabric.CustomGroup = fabric.util.createClass(fabric.Group, {
    type : 'CustomGroup',
    ...
});`

 I added several items to the group (line, circle, group, rect ...).

I set subTargetCheck = true.

Problem:
when I click on the object (CustomGroup) subTargets is always empty.

In fabric.js (version: '2.0.2' line: 10109) I read the following code:

`if (target.type === 'group' && target.subTargetCheck) {...
`
But target.type is equal to "CustomGroup".

Please, how can I solve this problem?
Thanks a lot,
Blu

**Comment by asturur** [comment]
That line must be changed in   target instanceof fabric.Group

After have verified that it works on ie10
