### ISSUE TITLE
setSelectionStyle stopped working in 2.0.x ?

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4755]
## Version
2.0.3

## Test Case
In 2.0.3 http://jsfiddle.net/blobinabottle/yab4fk2z/3/
Vs 1.7.20 http://jsfiddle.net/blobinabottle/yab4fk2z/2

## Steps to reproduce
Select some texts and the end of paragraph and hit bold. On 1.7.20 it's ok. Not in 2.0.3

## Expected Behavior
Text should go bold. Selection start & end are correct. 

## Actual Behavior
Text do nothing.

Note: in 2.0 rc3 it's working. Don't see what changes could have an impact on this...

**Comment by asturur** [comment]
i wonder what unit tests are doing

**Comment by blobinabottle** [comment]
And if you set it by code on a defined range, it can go super crazy: 
http://jsfiddle.net/blobinabottle/yab4fk2z/10/

But seems ok if the style is only set on the first line....

**Comment by asturur** [comment]
that crazy part is the one in the other ticket.
That thing is unfixable.
Everytime you fix a bit you break it somewhere else

**Comment by blobinabottle** [comment]
But here it's setSelectionStyles that's messing things up. I just called textbox.setSelectionStyles({fontWeight:'bold'},100, 115); 
15 characters, and it set the whole line in bold. It doesn't know what's bold or not...

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/36509448-146f7a0a-1760-11e8-9754-aa68e9bd0864.png)

on kitchensink works, looking at the code i see it has failures points.

**Comment by asturur** [comment]
This is the straight forward kitchensink code

```javascript
function setActiveStyle(styleName, value, object) {
  object = object || canvas.getActiveObject();
  if (!object) return;

  if (object.setSelectionStyles && object.isEditing) {
    var style = { };
    style[styleName] = value;
    object.setSelectionStyles(style);
    object.setCoords();
  }
  else {
    object.set(styleName, value);
  }

  object.setCoords();
  canvas.renderAll();
};
```

**Comment by asturur** [comment]
Ok i see the error but i cannot fix it now since it needs some thinkering.
This should fix also the error when extending.

If you want to try by yourself:

file: text_style.mixin.js, function _extendStyles, line ```var loc = this.get2DCursorLocation(index);```  becomes ```var loc = this.get2DCursorLocation(index, true);```

and function getStyleAtPosition same change.

**Comment by blobinabottle** [comment]
Seems to already var loc = this.get2DCursorLocation(index, true); in fabric 2.0rc3 that we are using (and that doesn't have the issue).

**Comment by blobinabottle** [comment]
It appeared in RC4

**Comment by asturur** [comment]
i think i messed up something, i did not fix it yet because i  want to understand how i broke it.

**Comment by blobinabottle** [comment]
https://github.com/kangax/fabric.js/commit/c96bb927054e3f52a48980259a4a82aaef994572 this is this shortcut thing

**Comment by blobinabottle** [comment]
http://jsfiddle.net/yab4fk2z/42/ now it's working if I remove the shortcut variable

**Comment by asturur** [comment]
maybe isEmptyStyles is broken, the shortcut is just rendering all in a place.
Probably isEmptyStyles is working with the wrapped/unwrapped lines and the style is written with the opposite unwrapped/wrapped.

Need to make it straight once for all.
Ideally rendering should have methods for checking wrapped lines.
While style manipulation works better with unwrapped ones.

The more we can make it work with unwrapped code, the less code duplication with textbox.

**Comment by blobinabottle** [comment]
Indeed isEmptyStyles is not working well with wrapped/unwrapped lines.

**Comment by blobinabottle** [comment]
I think we should transform in _renderChars() the following:
`shortCut = !isJustify && this.isEmptyStyles(lineIndex);`
into :
`shortCut = !isJustify && this.isEmptyStyles();`

isEmptyStyles() is doing his job (to what I understand). But we pass it a wrong lineIndex...

**Comment by asturur** [comment]
So if isEmptyStyles is bound to full style, the optimization never work.
At that point i would remove it.
I prefer to fix isEmptyStyles.

**Comment by asturur** [comment]
Would you mind checking with the patch in the #4762 PR?
I could solve this and maybe also: #4740

**Comment by blobinabottle** [comment]
Awesome. That's working!
