### ISSUE TITLE
Demo fiddle for setBackgroundImage not updated

### ISSUE THREAD

**Issue by josefanostylus** [kangax/fabric.js#4758]
The current demo js fiddle for "setBackgroundImage"(http://fabricjs.com/docs/fabric.StaticCanvas.html#setBackgroundImage) is not working. 

http://jsfiddle.net/fabricjs/YH9yD/

I updated the fiddle made it compatible with latest fabric version at: 
http://jsfiddle.net/josefano09/djnr8o7a/1/

## Version
2.0.2

**Comment by asturur** [comment]
thanks i updated the doc
