### ISSUE TITLE
Bower: fabric.require.js is missing

### ISSUE THREAD

**Issue by JPAhnen** [kangax/fabric.js#4759]
## Version
2.0.*

## Steps to reproduce
install fabric from bower

## Expected Behavior
a js file containing
` if (typeof define === "function" && define.amd) {
   define([], function() {
       return fabric;
   });
}`
at the end (as it was before version 2).

Now I have to manually "fix" the `fabric.js` file to get it to work through requirejs.

It would be nice if you could put that file back in the repo. 

Additionally, would it be possible to release the "front-end" fabric which doesn't contain the cairo dependency to npm too? Maybe in a subfolder in the current package? So we could override our path in gulp/webpack/whatever to the desired file?

**Comment by asturur** [comment]
we were talking of require in #4713, i do not want to keep a double file just for a different line.
If this line does not bother the normal commonJS i can just add to the normal file.

I'm just unsure how AMD works and if still a thing today or everyone uses commonJS, babel or just a script tag in the index.html

**Comment by asturur** [comment]
Our package.json should have a list of modules disabled for webpack, the browser property in the file, has a list of excluded dependency.
That does not work?

**Comment by JPAhnen** [comment]
I have no chance to add the missing code as in #4731 mentioned during the build process. 
I would think that commonJS ignores that, since the `if` wouldn't get executed.

I'm not using webpack, but I get errors when installing fabric via yarn because I don't have cairo installed.

**Comment by asturur** [comment]
you get error yes, but is marked as optional dependency, it should not make everything fail

**Comment by JPAhnen** [comment]
Ok, yes, that works. I just had to add
`if (typeof define === "function" && define.amd) { define([], function() { return fabric; }); }` manually to the `fabric.js` file in the `node_modules` folder and now it works fine.

It would be great if that code would make it into the official package - until then I'll try to use a script to manipulate the file to add that line as a prebuild step.

**Comment by asturur** [comment]
I do not understand why we had 2 files before.
If i can find someone that can confirm me is ok, i ll just put it back in the normal file, without the .require.js middle name.

**Comment by asturur** [comment]
Hey i m adding back the footer with the 2.1.0 release.
Please note that i m doing it assuming it does not create problems to non requirejs users.
So fabric.js and fabric.min.js will have the footer.

If i found problems, i ll have to remove it.
