### ISSUE TITLE
Bad behavior in clone Line

### ISSUE THREAD

**Issue by samael205** [kangax/fabric.js#4766]
## Version
2.1.0

## Test Case
http://jsfiddle.net/samael205/Da7SP/989/

## Steps to reproduce
Click & Drag to create a new Line
Select the line, and see the X1, X2, Y1, Y2 Coordinates
With the line selected, click on Copy, then Click on Paste
Select the new Line and see X1, X2, Y1, Y2 Coordinates
## Expected Behavior
X1, X2, Y1, Y2 (Line A) | X1, X2, Y1, Y2 (Line B) Coords must be the same
## Actual Behavior
X1, X2, Y1, Y2 (Line A) | X1, X2, Y1, Y2 (Line B) Coords are different

**Comment by asturur** [comment]
@samael205 it does not look like a minimal fiddle to me.
Is complicated to understand what the code is doing, can you at least try to explain it with words?

**Comment by samael205** [comment]
[New jsFiddle](http://jsfiddle.net/Da7SP/1002/)
The variable additional properties, are the custom properties that I want to copy to the new object
the prepareCopy () function clones the objects
the managecopy function adds the copied objects to the canvas
the mousedown function creates a new line and adds it to the canvas
the mousemove function modifies the final coordinates of the line so that the creation of the line is seen
the mouseup function ends the creation of the line

@asturur My problem is that the coordinates of X1, X2, Y1, Y2 of the copy are not the same as the coordinates of the original object

**Comment by samael205** [comment]
Any news for this?

**Comment by asturur** [comment]
So what the clone do is giving you an object that is rendered same.
The points may change during export for some internal logic, but this is not a bug.
Feel free to open a PR and try to modify the behaviour, is not a priority at all for fabricJS.
