### ISSUE TITLE
Editing IText causes DOM to jump around unexpectedly for dynamic sized Canvas

### ISSUE THREAD

**Issue by nateevans** [kangax/fabric.js#4767]
## Version
2.1.0

## Test Case
https://jsfiddle.net/nateevans/8k4qogkc/10/
(note that this fiddle has a patch in place for the **_calcTextareaPosition** function. Using clientWidth and clientHeight instead of just width and height from upperCanvas seems to fix this issue. PR coming)

## Steps to reproduce

1. Style the canvas so that it is larger than its container but will be dynamically sized to max-width: 100%, max-height: 100%
1. Add an i-text object to the canvas
1. Move the i-text object somewhat close to one of the edges of the canvas
1. Double click to edit the i-text

## Expected Behavior
i-text will enter editing mode with no other changes to the canvas DOM display

## Actual Behavior
DOM around the canvas will shift, apparently to compensate for when the i-text **hiddenTextarea** DOM element is added. When you stop editing i-text, the **hiddenTextarea** node is removed and the DOM styling returns to normal.

**Comment by asturur** [comment]
I understand the problem.
I wonder if we can have instead of a patch for the positioning of hiddenTextarea only, a way to have available that client size without recurring to dom querying every single keypress.

That size changes when you call setDimenions or when you do something with the canvas, in any case you are in control since you are the dev.

Probably we should modify setDimensions to annotate that size somewhere or the calcOffset that already does dom interaction.

**Comment by asturur** [comment]
Referring to the PR, what do you mean by dynamic? how often is this canvas resized?

**Comment by nateevans** [comment]
So as far as being "dynamic", in our use case, we are wanting a JPEG after designing that has specific dimensions. In the fiddle above, the canvas is actually 1600 w X 1200 h and will give a jpeg that size when using toDataURL. **But** we are displaying and working with the canvas in a viewport that is sometimes smaller than what the canvas is configured to be, so it is "dynamically" sized with CSS, essentially making the canvas responsive. 

In regards to what you mentioned about updates to **setDimensions**: any adjustments to the browser size can resize the canvas on-the-fly. We're not calling setDimensions on browser resize, but letting CSS deal with the resizing of the canvas. (You can see this working in the fiddle if you resize the display pane or the browser.) All the parts of Fabric we have used so far seems to work fine with this CSS responsive sizing of the canvas, as far as correct relative coordinates, etc.

Are you thinking that the PR I submitted will have some other unexpected effects or negative performance impact?

**Comment by nateevans** [comment]
Also, not sure what you meant by this:

> a way to have available that client size without recurring to dom querying every single keypress.

Are you saying that with **upperCanvas.width** & **upperCanvas.height** it doesn't query the DOM but with **upperCanvas.clientWidth** & **upperCanvas.clientHeight** it does?

**Comment by asturur** [comment]
No your pr leave performances as they are, swapping width for clientWidth and vice versa.
Maybe clientWidth is a different getter, and could be calculated on demand, but that is really non influent for me.

Also fabric has some sort of window resize related event that maybe we could use.

Your pr does the job of fixing the problem, and do not introduces problems i can think of.
If we merge it without evaluating alternatives that can help other problem like this, we loose a discussion opportunity.

Also for your particular use case, you could avoid resizing with CSS you pay the performance of rendering a 1600x1200 canvas even when maybe you are in a 300x400 space, 1600x1200 becomes 3200x2400 on retina screens if you do not disable it manually.

When you request a dataURL you can zoom the canvas on the fly using the dataUrl with multiplier fabricjs option ( this is another topic and is not related to your PR, is just an information )

**Comment by nateevans** [comment]
Good point about the scaling, especially for retina, thanks.

I did think about dataUrl with multiplier, but was unsure of what impact that has on scaling raster assets when we upload images to the canvas.

**Comment by asturur** [comment]
it has the same impact, since the multiplier under the hood is changing canvas size, re rendering, exporting, resizing back and re rendering again.

**Comment by minzojian** [comment]
i don't know as if it is the same issue i faced before, i just adjust the hiddentextarea position style from "absolute" into "fixed", then canvas stopped jumped when call enterEdit()

```
fabric.IText.prototype.initHiddenTextarea= function() {
        this.hiddenTextarea = fabric.document.createElement("textarea");
        this.hiddenTextarea.setAttribute("autocapitalize", "off");
        this.hiddenTextarea.setAttribute("autocorrect", "off");
        this.hiddenTextarea.setAttribute("autocomplete", "off");
        this.hiddenTextarea.setAttribute("spellcheck", "false");
        this.hiddenTextarea.setAttribute("data-fabric-hiddentextarea", "");
        this.hiddenTextarea.setAttribute("wrap", "off");
        var style = this._calcTextareaPosition();
        //this.hiddenTextarea.style.cssText = "position: absolute; top: " + style.top + "; left: " + style.left + "; z-index: -999; opacity: 0; width: 1px; height: 1px; font-size: 1px;" + " line-height: 1px; paddingｰtop: " + style.fontSize + ";";
        this.hiddenTextarea.style.cssText = "position: fixed; top: " + style.top + "; left: " + style.left + "; z-index: 999; opacity: 1; width: 300px; height: 300px; font-size: 10px;" + " paddingｰtop: " + style.fontSize + ";";
        fabric.document.body.appendChild(this.hiddenTextarea);
        fabric.util.addListener(this.hiddenTextarea, "keydown", this.onKeyDown.bind(this));
        fabric.util.addListener(this.hiddenTextarea, "keyup", this.onKeyUp.bind(this));
        fabric.util.addListener(this.hiddenTextarea, "input", this.onInput.bind(this));
        fabric.util.addListener(this.hiddenTextarea, "copy", this.copy.bind(this));
        fabric.util.addListener(this.hiddenTextarea, "cut", this.copy.bind(this));
        fabric.util.addListener(this.hiddenTextarea, "paste", this.paste.bind(this));
        fabric.util.addListener(this.hiddenTextarea, "compositionstart", this.onCompositionStart.bind(this));
        fabric.util.addListener(this.hiddenTextarea, "compositionupdate", this.onCompositionUpdate.bind(this));
        fabric.util.addListener(this.hiddenTextarea, "compositionend", this.onCompositionEnd.bind(this));
        if (!this._clickHandlerInitialized && this.canvas) {
            fabric.util.addListener(this.canvas.upperCanvasEl, "click", this.onClick.bind(this));
            this._clickHandlerInitialized = true;
        }
    }
```

**Comment by bodeva** [comment]
For each version of fabric i add this to the _calcTextareaPosition function:

_calcTextareaPosition: function() {
            
            /*HACK*/
            var multiplier = parseFloat(this.canvas.upperCanvasEl.style.width.replace("px","") / this.canvas.width);
            
            if (!this.canvas) {
                return {
                    x: 1,
                    y: 1
                };
            }
            var desiredPostion = this.inCompositionMode ? this.compositionStart : this.selectionStart, boundaries = this._getCursorBoundaries(desiredPostion), cursorLocation = this.get2DCursorLocation(desiredPostion), lineIndex = cursorLocation.lineIndex, charIndex = cursorLocation.charIndex, charHeight = this.getValueOfPropertyAt(lineIndex, charIndex, "fontSize") * this.lineHeight, leftOffset = boundaries.leftOffset, m = this.calcTransformMatrix(), p = {
                x: boundaries.left + leftOffset,
                y: boundaries.top + boundaries.topOffset + charHeight
            }, upperCanvas = this.canvas.upperCanvasEl, maxWidth = upperCanvas.width - charHeight, maxHeight = upperCanvas.height - charHeight;
            p = fabric.util.transformPoint(p, m);
            p = fabric.util.transformPoint(p, this.canvas.viewportTransform);
            if (p.x < 0) {
                p.x = 0;
            }
            if (p.x > maxWidth) {
                p.x = maxWidth;
            }
            if (p.y < 0) {
                p.y = 0;
            }
            if (p.y > maxHeight) {
                p.y = maxHeight;
            }
            p.x += this.canvas._offset.left;
            p.y += this.canvas._offset.top;
            
            /*HACK*/        
            return { 
                left: parseInt(multiplier*p.x) + 'px', 
                top: parseInt(multiplier*p.y) + 'px', 
                fontSize: charHeight + "px",
                charHeight: charHeight 
            };
            
        }
