### ISSUE TITLE
When load canvas from JSON the alignText is wrong.

### ISSUE THREAD

**Issue by blucobalto** [kangax/fabric.js#4770]
Hi,
when load canvas from JSON the alignText is wrong (fabric.Text object).

Thanks a lot,
Blu

## Version
2.1.0

## Test Case
http://jsfiddle.net/Da7SP/1007/

## Steps to reproduce
Click button "load from JSON".
## Expected Behavior
Text centered.
## Actual Behavior
Text is not centered

**Comment by blucobalto** [comment]
Ok. From doc:

> With one-line text, the width of bounding box is always exactly matching that line's width, so there's nothing to align.

Thanks a lot,
Blu

**Comment by asturur** [comment]
There is this insonsistency between fabric shapes in which generally width and height are consequences of the property of the object, but not for rect, textbox, and now image too.

Maybe i should mark them as readonly in jsdocs
