### ISSUE TITLE
How to show object even outside clipping area.

### ISSUE THREAD

**Issue by aschente** [kangax/fabric.js#4771]
I need to show the object even if its outside the clipping area. See the image below.

![download](https://user-images.githubusercontent.com/8470020/36795051-f5560ae4-1cdc-11e8-8c7b-755592d6ec7f.png)

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
