### ISSUE TITLE
setLeft setTop not supported anymore?

### ISSUE THREAD

**Issue by bschelling** [kangax/fabric.js#4773]
just updated fabric.js to the latest version. i was using v2 rc4 and there svgfromurl/svgfromstring was broken. after update to latest version svgfromurl works again but setLeft/setTop breaks.  
## Steps to reproduce
var rect = new fabric.Rect({ width: 10, height: 20, fill: '#f55'});
rect.setLeft(100);
## Expected Behavior
move the rect to the left  100px.
## Actual Behavior
uncaught TypeError: rect.setLeft is not a function

**Comment by asturur** [comment]
setLeft and setTop are optional, you can add the back with a custom build:
![image](https://user-images.githubusercontent.com/1194048/36820724-a8079a56-1cef-11e8-8cf9-d4d6ec4b9f2a.png)

here: http://fabricjs.com/build/

or you can use the normal getters object.set(options) or object.set('top', 100)

**Comment by bschelling** [comment]
thanks 👍
