### ISSUE TITLE
I want to change the corner icon, how can i do that?

### ISSUE THREAD

**Issue by CoderKwong** [kangax/fabric.js#4776]
Hello , I want to use an image instead of this corner, how can i do that?
![image](https://user-images.githubusercontent.com/12517739/36837002-fae51ec0-1d75-11e8-8205-342515551dd5.png)

**Comment by blobinabottle** [comment]
Some inspiration, I think this should still work
https://codepen.io/elhoussinelaidi/pen/RRrLzv

**Comment by CoderKwong** [comment]
got it. thanks
