### ISSUE TITLE
build.js - should minifier be set to uglify-js?

### ISSUE THREAD

**Issue by marc-personeni** [kangax/fabric.js#4777]
## Version
2.1.0

## Test Case
Not applicable, this is a build issue.

## Steps to reproduce
> git clone https://github.com/kangax/fabric.js.git
> npm install
> node build
Built distribution to dist/fabric.js
Minification failed using uglifyjs with uglifyjs  --compress --mangle --output fabric.min.js fabric.js
Minifier error output:
Error: Command failed: uglifyjs  --compress --mangle --output fabric.min.js fabric.js
/bin/sh: uglifyjs: command not found

## Expected Behavior
If changing build.js line 19 to match package.json like so:
var minifier = buildArgsAsObject.minifier || 'uglify-js';)

AUSMOB03:fabric.js marcpersoneni$ node build
Built distribution to dist/fabric.js
Minified using uglify-js to dist/fabric.min.js
Built distribution to dist/fabric.require.js (requirejs-compatible)
Gzipped to dist/fabric.min.js.gz

## Actual Behavior
See steps to reproduce

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/37268217-12b5d100-25c5-11e8-8ddd-99a003529445.png)

i have the opposite problem, for me uglifyjs work with no dash.
on What SO are you?

**Comment by marc-personeni** [comment]
Well guessed! 
I am on Mac OSX Sierra and I was running an old version of cairo...
I reinstalled macports, got the new cairo and now it works with 'uglifyjs' (that is without the dash)
THIS IS NOT AN ERROR IN THE BUILD SCRIPT.

I dont know what the etiquette is here. My inclination is to close the issue; but I let you decide.
Thanks

**Comment by asturur** [comment]
just for someone else that my end up here, macports gives you cairo and libs for node-canvas, all the other stuff get installed by npm.
