### ISSUE TITLE
Fabric.js IE11 issue with multiply images 

### ISSUE THREAD

**Issue by vladimirlukyanov** [kangax/fabric.js#4779]
Hi Fabric.js developers !

Kindly ask to have a look this issue at http://bit.ly/2oLpi7m
Application has multiply images added to canvas using **fabric.Image.fromURL**
Images are passed through **fabric.Image.filters.BlendColor** filter
Everything works fine, expect IE11 – have no idea, why it's not working properly at this browser.
Suppose, some sort of browser specific bug.

Thanks

**Comment by jilster** [comment]
If you provide a fiddle that replicates the error, and tell us a bit more in detail what exactly isn't working properly, it is easier for us to help you

**Comment by vladimirlukyanov** [comment]
Hi @jilster !
You can close ticket – i've changed render to canvas and it's working now. Not sure, why WebGL renderer is not working properly in IE 11 / Edge

**Comment by jilster** [comment]
Ok good, i actually can't close the ticket, i think you can do it yourself. Or else @asturur can do it.
