### ISSUE TITLE
subclass fabric class instance cannot be loaded into canvas

### ISSUE THREAD

**Issue by astw** [kangax/fabric.js#4781]
## Version
2.1.0

## Test Case
http://jsfiddle.net/astw/xmt4zzhg/35/

## Steps to reproduce
1.  in the jsfiddle above, click 'Add text' button,  a subclass text (TextExt) instance will be added into the canvas
2.  click 'Load text' button,  this will save canvas content into a string variable,  then clear the canvas ,
     then load the string into the canvas. 

 You can see the canvas is empty.  The subclass text instance is not loaded. 

Put a breakpoint into TextExt implementation,  I can see the instance is created successfully, but for some reason, it is now showing up.

**Comment by astw** [comment]
@asturur  Can you have a look if it is a bug?

**Comment by asturur** [comment]
http://jsfiddle.net/xmt4zzhg/43/

in the fromObject function, the callback is mandatory
