### ISSUE TITLE
Can't select added object is using zoom/scroll

### ISSUE THREAD

**Issue by DangerD256** [kangax/fabric.js#4782]
## Version
2.1.0

## Test Case
https://jsfiddle.net/ngbdhkkq/20/

## Steps to reproduce
Zoom in canvas using Ctrl+mouse wheel than scroll canvas viewport down using mouse wheel (so image became out of view ) and press "Add img" button.
## Expected Behavior
Added image is selectable.
## Actual Behavior
Can't select added image...

Also i have an issue with already added objects, after zooming in/out moving they're sometimes also cannot be selected, but i have so steps to reproduce as it acts randomly (when clicking on one object, upper is being selected for example)

**Comment by asturur** [comment]
i do not see any bug, till the image is inside the viewport, is selectable properly.

**Comment by DangerD256** [comment]
https://www.youtube.com/watch?v=Onh-9zHFWD8
Check video, scroll image out of view with mouse scroll before adding new one.

**Comment by DangerD256** [comment]
Checked also in Firefox and IE, issue reproduces in both browsers...

**Comment by DangerD256** [comment]
Please help, it works ugly, this is a stopper for me, it works totally randomly, as selection is broken objects are bouncing from time to time when trying to move them, can't select them even when they are in view, helps zooming in/out several times

**Comment by DangerD256** [comment]
Check also this video:
https://youtu.be/hnP8_92ZrS4

**Comment by asturur** [comment]
This happens because you modify the vieport but you do not call setCoords on the object.
At the end of scrolling or during scrolling, if you modify viewport you have to let fabric recalcuate the new interactive position of the object

**Comment by DangerD256** [comment]
So after changing viewport I need to call setCoords for all objects?
obj.setCoords(); without parameters for each object?

**Comment by DangerD256** [comment]
Thanks, that worked!

**Comment by DangerD256** [comment]
Maybe should add this to core?

**Comment by asturur** [comment]
No, setCoords is better to be called manually.
If instead of modifying the viewport directly you call setViewport(viewport) , that should happen automatically.

http://fabricjs.com/docs/fabric.StaticCanvas.html#setViewportTransform
