### ISSUE TITLE
when reset property of the subclass, the result wasn' change and the function of subclass, _render()  wasn't invoked

### ISSUE THREAD

**Issue by swancai** [kangax/fabric.js#4784]
## Version
2.0.3

## Test Case
https://jsfiddle.net/swancai/s4e0th10/13/

## Expected Behavior
After 3 second, the textRect's text is 'trololo'. 

## Actual Behavior
After 3 second,  the textRect's text is still 'test'. 

So, what can i deal with this problem ?

**Comment by asturur** [comment]
https://jsfiddle.net/s4e0th10/16/

yo have to inform fabricJS of what properties change the render aspect of your object in order to make it auto re render.

Or set it manually to dirty every time you change something

**Comment by swancai** [comment]
Thanks very much.
