### ISSUE TITLE
Feature request: Moving controls to upper canvas

### ISSUE THREAD

**Issue by semiadam** [kangax/fabric.js#4787]
The fact that upper canvas and main canvas are separate is great and opens up a lot of opportunity. For example, I inject several layers in between the two canvases to show guides and masks to the user. The problem is, when I inject a mask to cover certain parts of the art canvas, it also covers the control visuals. For example, in the attach screenshot, the bottom right control is covered by the injected diecut mask. I was thinking now that the event listeners are on the upper canvas, why not move the visuals to upper canvas too? Any thoughts?

![image](https://user-images.githubusercontent.com/5418638/37052898-8d6ccb0a-212f-11e8-95a1-366c7017fd70.png)

**Comment by asturur** [comment]
controls are definitely gonna be moved there as soon as is retina enabled and as soon i can imagine an api to draw there what you need with a minimum control.

suggestions are welcome.

**Comment by semiadam** [comment]
Great to hear! As part of that effort it may be worth considering more flexible visuals for controls, for example using SVG for handles. Also, ability to add arbitrary handles and connect them to custom event listeners would be very helpful.

**Comment by asturur** [comment]
control customization is a major rewrite that i have no idea how much is worth now.

i m aiming at more flexibility of rendering and more feature in rendering.
