### ISSUE TITLE
fabric object undefined by importing syntax in React

### ISSUE THREAD

**Issue by loserford** [kangax/fabric.js#4789]
## Version
2.1.0

Before v2.1.0, I could import fabric and use it in react.
`import { fabric } from 'fabric'`
but from v2.1.0,  the variable `fabric` is undefined after importing

**Comment by loserford** [comment]
@asturur

**Comment by asturur** [comment]
well this is bad. can you spot some relevant change from the diffs?

**Comment by loserford** [comment]
2.1.0 has below change at the end of fabric.js. when I remove it, it works.
`
if (typeof define === "function" && define.amd) {
    define([], function() {
        return fabric;
    });
}
`

**Comment by loserford** [comment]
@astw @asturur 
Yes, it works without destruction. Thanks!

`import fabric from "fabric"`

**Comment by asturur** [comment]
Fixing this with a 2.2.1 release now.
I moved the code in a way that i hope makes work both of them.
At least it restores the old fabricjs import way.
