### ISSUE TITLE
setOverlayImage is not resizing the image.

### ISSUE THREAD

**Issue by LostInVelvet** [kangax/fabric.js#4790]
## Version
2.2.0

## Test Case
http://jsfiddle.net/LostInVelvet/s5wxbcde/

## Expected Behavior
I expected the overlay image to stretch to the size of the canvas. 
This is a working example in 1.7.20: http://jsfiddle.net/LostInVelvet/9dbkgk9o/

## Actual Behavior
The overlay is ignoring the set width and height. It's retaining the original dimensions of the image instead.

**Comment by jilster** [comment]
Image width/height changed in 2.x, see http://fabricjs.com/v2-breaking-changes#image. You should now look at the images naturalWidth/naturalHeight, compare those with the canvas width/height, and then set scaleX/scaleY to make it fit

**Comment by LostInVelvet** [comment]
Thanks! I did read through the v2 breaking changes, but I didn't realize it changed for this case. 
The documentation here http://fabricjs.com/docs/fabric.Canvas.html#setOverlayImage will need updated then since it still shows doing it the way I had it.

**Comment by jilster** [comment]
No problem. the naturalWidth is found in `img._originalElement.naturalWidth`.

I updated your fiddle to make it work: http://jsfiddle.net/106utcjo/15/

**Comment by LostInVelvet** [comment]
Thanks again!
