### ISSUE TITLE
Setting fill by hex value without pound sign doesn't work in all browsers

### ISSUE THREAD

**Issue by cawjustin** [kangax/fabric.js#4791]
## Version
2.0.2

## Test Case
https://jsfiddle.net/n6j3mkra/

The button in the fiddle to turn it green will only work in Safari.

## Steps to reproduce
- Set an object's fill using a hex value without the pound sign
- e.g. `.set("fill", "00a651")`

## Expected Behavior
It is my understanding that the pound sign is optional when passing hex colour values. Therefore the fill should successfully apply. Though I'm struggling to find the documentation that said it was an acceptable hex value.

## Actual Behavior
It will *only* successfully recolor in Safari. Chrome and FF will ignore it (or sometimes turn it black).

**Comment by jilster** [comment]
I think that if you set a property directly, a pound sign is needed for it to work consistently. If you use the Color class, the pound sign is not needed, see http://fabricjs.com/docs/fabric.Color.html.

Just to be sure i would always use the pound sign when directly setting a property, at least that's what i do and i never have problems with browser compatibility.

**Comment by asturur** [comment]
what are the canvas specs for it?
i think fillStyle understands css colors.

is the string without the pound a css color?

**Comment by jilster** [comment]
I searched through the fabric sourcecode, and everywhere where fillStyle is used, it just uses the input value of the user, there is no validation or checking for the existence of the pound sign. So i guess in that case it is up to the browser if it is seen as a valid css color or not.

I think it is not a valid css color without the pound sign. W3schools does never mention that you can leave out the pound sign, and always uses it in examples (for example https://www.w3schools.com/cssref/css_colors_legal.asp). Wikipedia says `in HTML, CSS, SVG, and other computing applications "#" is used to identify a color specified in hexadecimal format, e.g., #FFAA00` (https://en.wikipedia.org/wiki/Number_sign#In_computing).

So i think there are 2 options:
- Say in the docs that for the best result, hex color codes should contain a pound sign
- Make fabric detect with a regex if a hex code without a pound sign was used, and add it

I would go for the first option

**Comment by asturur** [comment]
https://www.w3.org/TR/2dcontext/#fill-and-stroke-styles

needs a css color. without pound is not.

we can add this link on top of the propertie's jsdocs.
