### ISSUE TITLE
Image cuts from the right when applying Pixelate filter with cropX and CropY

### ISSUE THREAD

**Issue by ilyaLibin** [kangax/fabric.js#4792]
version 2.2.0
Hi, I'm trying to make a tool that allows deleting private info from screenshots.

I want to pixelate parts of the image as shown on the attached image.

Here is my approach:
1. set canvas background to the spoken image.
2. Draw image object on top of it with following settings:

  ```
  fabric.Image.fromURL(url, function(img) {

      img.set({
        opacity: 0.9,
        left: offsetX,
        top: offsetY,
        cropX: offsetX / ratioX,
        cropY: offsetY / ratioY,
        scaleX: ratioX,
        scaleY: ratioY
      });

      // apply filters and re-render canvas when done
      // add image onto canvas (it also re-render the canvas)
      canvas.add(img);
      img.filters.push(new fabric.Image.filters.Pixelate({blocksize:7}));
      img.applyFilters();
    },
    { crossOrigin: 'Anonymous' }
    );
```

The problem is that when I apply the filter, the image cuts from the right and I just have no idea why.

If I comment applyFilters part, the image displayed in correct position full width, correctly cropped.

Any idea why it happens?
![image](https://user-images.githubusercontent.com/12880486/37108062-b122c472-223e-11e8-9040-b55adf35f06b.png)

**Comment by ilyaLibin** [comment]
Visualization of the problem:
ONe image is a background and another one is a image on top of it. as you see it cuts from the right.
![image](https://user-images.githubusercontent.com/12880486/37108369-97fd1366-223f-11e8-8899-9105b092b5bc.png)

**Comment by jilster** [comment]
You did not provide a fiddle, so this is just a wild guess, but i suspect this has something to do with texture size (assuming you enable WEBGL). See http://fabricjs.com/fabric-filters.

You could try to set the texture size higher with for example `fabric.textureSize = 2048`.

**Comment by asturur** [comment]
we need to see the full code in order to understand if is a bug or just a wrong code setup.
Can you reproduce a small fiddle, without too much application logic?

**Comment by ilyaLibin** [comment]
@asturur @jilster 
https://jsfiddle.net/pvwue1y0/24/

I set it up with two images. Seems like it works with small not scaled image and doesn't work with large scaled images.

Please see in Fiddle example with photo1 and photo2
```

    const photo1 = 'https://picpi.pe/Ft-MRQ/image-for-fiddle.png';
    const photo2 = 'https://i.pinimg.com/originals/1c/ae/da/1caedad3055dc1ffed690af605a0b5dc.jpg';

```

**Comment by asturur** [comment]
how big is the large image in pixels?

**Comment by ilyaLibin** [comment]
@asturur You can check it in fiddle, it's ~1000px width. it scales down.

**Comment by asturur** [comment]
https://jsfiddle.net/pvwue1y0/58/  ( i changed some unrelated code, just for fun )

i can't understand the problem really i cannot see the bug. The fiddle is far too complicated.
If the pixellated filter has some problem with the image, you should provide the fiddle with just code for the filter and one image, all the rest is smoke in the eyes when you search for a bug

**Comment by marc-personeni** [comment]
@ilyaLibin Have you found a solution?
If not, I think this is not really a bug and your code is correct.
The pixelate filter looks right and down and introduces a "visual half-block shift" because of that.
Again, not really a bug. But an additional filter option to control the pixelation mode would allow choosing the best effect. Something along the lines of {"h": "right", "v": "bottom"} or  {"h": "left", "v": "top"} and I think the one you would be after would be {"h": "centre", "v": "centre"}.
I am really busy until the end of the week, but I can give it a crack during the week-end.

**Comment by ilyaLibin** [comment]
@asturur Looks great! 
Well looks like it works with all my images. Not sure why it didn't work before. 

@marc-personeni @asturur  I'm closing the issue. Thanks for the help!

**Comment by ilyaLibin** [comment]
@asturur Check out the same code you wrote but with another image https://jsfiddle.net/6f2sxorx/
