### ISSUE TITLE
Group selection starting from within a non selectable rectangle

### ISSUE THREAD

**Issue by njofce** [kangax/fabric.js#4795]
## Version
2.0.2

## Test Case
https://jsfiddle.net/jut5z3ky/7/

## Steps to reproduce

Trying to select the group with "Text" by starting the selection from inside the bigger rectangle(which is un-selectable)

## Expected Behavior

The group with "Text" should be selected

## Actual Behavior

Selection box doesn't appear. It only appears if you start selecting from outside of that rectangle.

**Comment by asturur** [comment]
this thing has been fixed sometimes ago. The fiddle you show is based on an old fabricJS version, not 2.0.2
