### ISSUE TITLE
Newline at end of text does not display correctly in textbox

### ISSUE THREAD

**Issue by minzojian** [kangax/fabric.js#4798]
## Version
2.2.0

## Test Case

http://jsfiddle.net/minzojian/4c2bs1b8/2/

## Steps to reproduce

case1:
just add a simple textbox and write some words
then press enter key to break lines
case2:
add some style for selection,like change the color of it
in the end of the word, press enter

## Expected Behavior

case1:
new line can created correctly
case2:
new line should keep the style of prev  character 

## Actual Behavior

case1:
only one new line created and besides the textbox's height is not ok
case2:
style of new line just lost last style

i displayed the hidden textarea, as you press enter key, you can see new lines ceated in the textarea,but there is no new line ceated in textbox

**Comment by redlive** [comment]
+1

**Comment by asturur** [comment]
fixed with incoming PR.
The loss of style is normal in those cases in fabricJS.
There is not yet a current style logic in fabricJS.

**Comment by minzojian** [comment]
did you notice another bug in case2 ?
style lost when line break, is that the same bug?

**Comment by asturur** [comment]
no the style when hitting new line is empty, i think it has always been like that. was different in 1.7?
