### ISSUE TITLE
Emoji color version in bigger sizes

### ISSUE THREAD

**Issue by DamianImrich** [kangax/fabric.js#4799]
Hello,
I want export text with emoji in high resolution.
When change fontSize or scale above some value emoji is changed to black/white version.
How can I force emoji to stay in original design?

## Version
2.0.2

## Test Case
http://jsfiddle.net/Da7SP/1098/

## Steps to reproduce
Scale or change fontSize of text with emoji

## Expected Behavior
Emoji stay in original colorful state

## Actual Behavior
Emoji changed to black and white at some scale/fontsize

**Comment by asturur** [comment]
this is a canvas bug, at low level, that are not fixing since long.
Emoji can be rendered up to 96font size ( more or less ) with color font, then they do not work, in windows you get the bw version, that does not exist in other S.O.
