### ISSUE TITLE
Inconsistency in Canvas Zoom and SVG Background behavior

### ISSUE THREAD

**Issue by semiadam** [kangax/fabric.js#4801]
It seems to me that the goal of toSVG() is to replicate the current view of the canvas, including its zoom level, and because of that, setZoom() impacts SVG viewBox in the output. 

The problem is, if setBackgroundcolor() is used, the background <rect> element stays the same size, regardless of the zoom level, so for cases that zoom is less than 1, the SVG output looks different that canvas view (background is small):
http://jsfiddle.net/Da7SP/1127/

Canvas view:
![image](https://user-images.githubusercontent.com/5418638/37248516-2f5e8dd4-2489-11e8-8f22-37002a98a23a.png)

SVG View:
![image](https://user-images.githubusercontent.com/5418638/37248519-3e1db17e-2489-11e8-845d-cfc41d89a021.png)

A related issue is, if user sets a custom viewBox for SVG output, the background color won't be extended all the way to the edge of the viewBox.

If confirmed as a bug, I think the easiest fix is to change width and height of background <rect> to 100%, so both of the above use cases will be covered. 

`<rect x="0" y="0" width="100%" height="100%" fill="red"></rect>`

**Comment by semiadam** [comment]
@asturur do you have any suggestions on this?

**Comment by asturur** [comment]
i agree that being the color a color, and supposed to fill, the 100% fix is completely OK.

**Comment by asturur** [comment]
just to add that this behaviour of the full viewport is optional with the boolean
```canvas.svgViewportTransformation```
