### ISSUE TITLE
[BUG] calling toDataURL() with a multiplier, hides the selection box

### ISSUE THREAD

**Issue by semiadam** [kangax/fabric.js#4814]
I have an app that sends fabric output to a preview tool after each render. When I call `toDataURL()` after each `after:render `event , the selection box (the one the appears when dragging your mouse to select multiple items) disappears. If multiplier is 1, this issue won't happen. Here's a fiddle: 

http://jsfiddle.net/Da7SP/1154/

Any suggestions? As a workaround, is there a way to mute `after:render` event when selection box is in place?

**Comment by asturur** [comment]
Well in toDataURL the selection box should be hidden always.
So the bug is that it does not get hidden on the case of zoom equal 1.

What version of fabricJS?

also to mute your after:render events you need to make your event check for an activeObject a return immediately instead of doing is job.

**Comment by semiadam** [comment]
@asturur sorry I think I didn't explain it well. The problem is _not_ about toDataURL() output. That output is always correct and never contains the selection box, no matter what multiplier is used.

The problem is about the canvas view on user screen. When toDataURL() is called, the selection box disappears from the canvas view, so if user is in the middle of selecting elements, they suddenly lose their selection box. This problem doesn't exist with other controlling visuals (like resize handles, etc.) i.e.e they always stay visible when toDataURL() is called. I think if a similar treatment is applied to selection box the problem could be resolved.

**Comment by asturur** [comment]
i am sorry, what is selection box? can you make a screenshot of before and after?

**Comment by semiadam** [comment]
@asturur  I'm not sure what I should call it. I'm referring the the box that appears on the canvas when you click and drag your mouse to select multiple objects. This thing:

![image](https://user-images.githubusercontent.com/5418638/37538577-4737f2d6-290e-11e8-8de5-e2da66a095c7.png)

What's the right name to refer to this anyway?

I updated my fiddle: http://jsfiddle.net/Da7SP/1190/

There are two canvases now. Try to drag and select on each. You'll notice you won't be able to see the selection on the second canvas because toDataURL is constantly called on it.

**Comment by asturur** [comment]
Understood, this is the selection box, i did not get it immediately.
This happens because the canvas gets resized and the content wiped. Maybe there is a way to restore easily after the operation, let me see...
