### ISSUE TITLE
Multiplying on TODAtaUrl breaks clipped objects

### ISSUE THREAD

**Issue by Sashkan** [kangax/fabric.js#4818]
## Version
2.0.2

## Steps to reproduce

Pretty straightforward : on any canvas with a clipped object and a backgroundImage, use ToDataurl to get a png out of the canvas, using the ```multiplier``` option to get a custom size for the png. This is a picture of my canvas 
![screenshot from 2018-03-14 11-26-37](https://user-images.githubusercontent.com/6276267/37397809-d728dc04-277c-11e8-9fa9-4bdd9a0aa393.png)

## Expected Behavior

All objects are rendered on the png, clipped as in the canvas. (This is a the resut of toDataURL without using the multiplier option)

![mockup](https://user-images.githubusercontent.com/6276267/37397842-e9b322d0-277c-11e8-859c-6e442ceeba3b.png)

## Actual Behavior

I only get the background image, none of the clipped objects are rendered

![mockup 1](https://user-images.githubusercontent.com/6276267/37397908-1e72802e-277d-11e8-84fe-844326a8812e.png)

**Comment by asturur** [comment]
is your clipping function working with canvas zoom? the multiplier is obtained with zoom, you need to be sure your clipTo function is aware of it.

**Comment by Sashkan** [comment]
Here's the clipTo function : 
`         
      
    clipTo: (ctx) => {
          img.setCoords();
          var clipRect = y.getObjects().filter(p => p.clipFor === 'layer')[0]
          var scaleXTo1 = (1 / img.scaleX);
          var scaleYTo1 = (1 / img.scaleY);
          ctx.save();

          var ctxLeft = -(img.width / 2) + 1;
          var ctxTop = -(img.height / 2) + 1;

          ctx.translate(ctxLeft, ctxTop);
          ctx.scale(scaleXTo1, scaleYTo1);
          ctx.rotate((img.angle * -1)* (Math.PI / 180))

          ctx.beginPath();
          ctx.rect(
              clipRect.left - img.oCoords.tl.x,
              clipRect.top - img.oCoords.tl.y,
              clipRect.width,
              clipRect.height
          );
          ctx.closePath();
          ctx.restore();
        },`

So I have to apply my canvas zoom ratio to every single height and width-related variables in there ?

**Comment by asturur** [comment]
Is unclear if your clipping function is for the canvas or for the object.
I m pretty sure on stackoverflow i answere already and made the `clipFor` code that started from some fiddle, working with both canvas zoom and retina scaling.
