### ISSUE TITLE
[Suggestion] Take into account the displacement of the viewport in the centering of the object

### ISSUE THREAD

**Issue by samael205** [kangax/fabric.js#4819]
Hello @Asturur,

Could you add a parameter, for example a Boolean, that allows you to center the object on the screen, with a viewport shift ?, Because it is not implemented, the object is always positioned in the same place regardless of whether the viewport

I did not do it, because internally I do not know how the object is centered

EDIT:
To calculate the center, you calculate it on the size of the canvas, but when there is an offset of the viewport (which means that you have done panning on the viewport), this calculation is totally invalidated

**Comment by scriptspry** [comment]
@samael205 a test case or a fiddle would really help understand what it is you are expecting the center function to do differently.

**Comment by asturur** [comment]
i think there are already methods:
http://fabricjs.com/docs/fabric.Object.html#viewportCenter

**Comment by samael205** [comment]
Thanks
