### ISSUE TITLE
Tracking horizontal mouse wheel (touchpad or mouse with 2 wheels)

### ISSUE THREAD

**Issue by DangerD256** [kangax/fabric.js#4822]
## Test Case
https://jsfiddle.net/ngbdhkkq/34/

## Steps to reproduce
Issue, when using mouse wheel horizontally (touchpad horizontal scroll)
opt.e.shiftKey becames true in this case and deltaY is changes.
```
canvas.on('mouse:wheel', function(opt) {
opt.e.shiftKey - Why it's true?
```

## Expected Behavior
deltaX changed

## Actual Behavior
deltaY changes and opt.e.shiftKey becames true

**Comment by scriptspry** [comment]
Unable to reproduce this issue... shiftKey never becomes true here (except when shift is actually pressed).

**Comment by asturur** [comment]
is not a fabricJS problem, is related on how browser tranlslate the scrollwhell.

I have a mouse with horizontal scrollWheel and a trackpad too and i get deltaX changes.
Some other poor device can probably emulate it as SHIFT + deltaY.
I think is a device problem and not browser/OS issue.
