### ISSUE TITLE
Curved Text problem

### ISSUE THREAD

**Issue by AwaisGee** [kangax/fabric.js#4824]
I am facing this error, when i have curved text in canvas while using fabricjs 2.0.3

"Uncaught (in promise) TypeError: Cannot read property 'fromObject' of undefined"

Any Solutions?

**Comment by asturur** [comment]
Curved text is not a fabricJS supported feature, i m sorry.
Someone has to update it for vesion 2.
We are planning text on a path.

**Comment by p-glynn** [comment]
@asturur - have been learning to use fabric.js and loving it. do you have any potential timeline for the text on a path feature you mention? where can i begin looking at updating curved text for version 2 as you mentioned above?
cheers!
