### ISSUE TITLE
IText cursor misaligned on an empty IText object or on the next line

### ISSUE THREAD

**Issue by mdcuesta** [kangax/fabric.js#4826]
![image](https://user-images.githubusercontent.com/208169/37500115-9fcc2c66-2902-11e8-97e9-b6752bc0b3b1.png)

## Version
2.0.2

## Test Case
http://jsfiddle.net/Da7SP/1187/

**Comment by asturur** [comment]
hi @mdcuesta i think in the current master ( maybe not build ) this has been solved.

**Comment by mdcuesta** [comment]
Just did a build of master.  Issue is still apparent.

**Comment by asturur** [comment]
i tried just now, it works fine for me.
What do you do to make it happen?
