### ISSUE TITLE
fabric.Object origin attributes are modified during rotation

### ISSUE THREAD

**Issue by scriptspry** [kangax/fabric.js#4829]
## Version
2.2.1

## Test Case
https://jsfiddle.net/wuzdsyj3/

## Steps to reproduce
Click on the rotate control.
Notice the current origin - left bottom
Try to rotate the rectangle.
Notice the origin get changed to - center center
Leave the rotate control.
Notice the origin change back to - left bottom

## Expected Behavior

originX, originY to not change

## Actual Behavior

originX, originY change.

---

The implementation of centred rotation should be done with out changing the origin attributes for the sake of being consistent. The object is an inconsistent state during rotation because of the change in the origin attributes.

**Comment by asturur** [comment]
I agree that we could change the rotation implementation.
While not a priority i ll mark it as a possible feature.
