### ISSUE TITLE
Textbox won't update scales (x and y), when resize fabric group.

### ISSUE THREAD

**Issue by rafaellrochaa** [kangax/fabric.js#4833]
## Test Case
http://jsfiddle.net/Da7SP/1213/

## Steps to reproduce
Resize rect, and look at the font of textbox group stretch though scaleX and scaleY dont update,
(console test with 2 scales when event scaling is fired shows this)

## Expected Behavior
Textbox font don't stretch.

## Actual Behavior
Textbox group is stretching

**Comment by asturur** [comment]
Objects in group do scale.
The group is scaled and so they scale because of him.
Groups work in this way.

**Comment by rafaellrochaa** [comment]
All right, in version 2.x. But in version 1.7, I would get handle the size os letter when group is scaling, like this http://jsfiddle.net/Da7SP/1254/.
Have no way to do that in the last version of fabric js?
Thank you.

**Comment by asturur** [comment]
no that was an intentionally removed beahviour, it did not make sense and created a lot of edge cases.
You still have the onGroupScale function that you can override to put the code you want.

**Comment by asturur** [comment]
You should check the old scale handler in 1.7 and verify what it was doing
