### ISSUE TITLE
Overlay Image is not exported in JSON nor in ToDataURL

### ISSUE THREAD

**Issue by Sashkan** [kangax/fabric.js#4838]
SE, Overlay image is properly rendered in canvas, and appears on top of everything, but unfortunately, if I export my canvas as PNG, or load another canvas with the JSON, the overlayImage is gone.

**Comment by radiolondra** [comment]
Just a question:
Could you show the code u used?
Just to give a chance to kangax to better understand your problem and give help... :)
You know... a sample is better than thousands of words.

**Comment by Sashkan** [comment]
Sure, my bad !

Here is the sample of code used to apply the overlayImage :  




     fabric.Image.fromURL(url, (img) => {
        img.scaleToWidth(this.canvas.getWidth());
        img.set({
          originX: 'left',
          originY: 'top',
        })
         this.canvas.setOverlayImage(img, this.canvas.renderAll.bind(this.canvas))
      }, {
        crossOrigin: 'anonymous',
        objectCaching: false,
      })

Once added, I save the canvas JSON to load it later like this : 

Saving : 

     var savedJson = this.canvas.toJSON(['height']) // also saving height

Loading : 

      const json = product.json //I made sure it wasn't empty, though all other items are properly loaded and rendered
      this.canvas.loadFromJSON(json, () => {
        this.canvas.renderAll()
      })

And I also generate a png with ToDataURL as follow : 


        const mockupImg = y.toDataURL({
          format: 'png',
        })
        const mockupData = mockupImg.replace(/^data:image\/\w+;base64,/, '')
        const mockupBuf = new Buffer(mockupData, 'base64')

But the overlay Image does not appear anywhere, neither in the json loaded canvas nor in the ToDataUrl png

**Comment by asturur** [comment]
was an async problem between loading and exporting?
