### ISSUE TITLE
Missing v2.2.2 tag on repository

### ISSUE THREAD

**Issue by idelsink** [kangax/fabric.js#4842]
The latest tag (2.2.2) of the release is missing. I guess that you guys forgot to push the latest tag to the repository.

This may sound a bit annoying but I have an automated build process that builds using the latest tag. And it still fails with the v2.2.1 build.
See the following issue I made a few days ago: https://github.com/kangax/fabric.js/issues/4806

**Comment by asturur** [comment]
yes i forgot.
i pushed on npm but didn t do on github nor i updated the changelog on website.

**Comment by asturur** [comment]
Tagged!

**Comment by idelsink** [comment]
Great, thanks!
