### ISSUE TITLE
Emoticons/Emojis Disappear When Scaling The Text

### ISSUE THREAD

**Issue by brittonk** [kangax/fabric.js#4845]
When I enter an emoji into a textbox on the fabric canvas, it appears. When I scale or change the text size the emojis vanish but the background color is still there.

Any thoughts?

Thanks :D

**Comment by asturur** [comment]
Its a cairo/blink bug, do not know exactly.
Emoji and color fonts disappear after a certain size, nothing we can really fix.
If there would be a workaround i would document it, but not include in the library since this is a browser bug. You have the same problem on google docs, enter an emoji and then assign a super sized font, or in libreoffice too ( at least this was the result of my research one year ago )

**Comment by brittonk** [comment]
Actually mine are disappearing at any size. If I use IText instead of texbox, they don't disappear when scaling... BUT... on the rendered image, they are gone no matter which fabric text option I use.

I'm switching to Fabric from some stuff I had scripted with canvases since your object based script lets me scale/drag and drop a lot better than I could ever hope to accomplish with my Snapchat style text on canvas app... so, I know that emojis/emoticons COULD be able to be drawn onto and saved with canvas but for some reason they just disappear with FabricJS. I could post screenshots if that would help...

**Comment by asturur** [comment]
Sure! Post a screenshot of the biggest emoji you can render on a canvas with and without fabricjs, and let's see where the problem is.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/37821874-210010d6-2e85-11e8-89d7-5c26fa8832a6.png)
 this is gdocs for me, till 96px is ok, after disappear. if i zoom the page with zoom controls, 96px too disappears.

**Comment by brittonk** [comment]
Actually, I think you're right. I thought there was something else going on since they were failing for me well below 96px but then I remembered in order to get FabricJS to work with my other 1920x1080 layers of canvas, I had to zoom Fabric by 3... which is what is making the emojis fall out of the displayable range.

Some research to this shows it is patched in the latest Google Chrome/chromium release ( https://bugs.chromium.org/p/chromium/issues/detail?id=719648#c13 ) but since it was released this month it isn't pushed to phones yet. I guess since its already fixed and just not live yet, outside of dev versions, there is no reason for us to do any kind of work around or hack to make it work in Fabric. Thanks for your time on this and for creating a great script! (Also, any idea why I have to zoom x 3 for the 1920x1080 fabricjs to match the other no fabricjs canvases in size?)

**Comment by asturur** [comment]
no idea what yuo mean about the scaling.
Fabricjs has retina enabled, but i think it disables it on export.

Can you reproduce this matching on a fiddle?

Also if you are working with emoji, cross OS emoji is a problem.
Windows has shitty emoji, macos/iphone nice, android better.

i made a little package on npm, taking from the google font, that is called asturur-noto-emoji that has SVG assets for the emojis.

**Comment by brittonk** [comment]
The problem is, I guess, not the emoji bug as first thought but actually the retina/zoom on phones. The canvas displays properly during editing but when I render and ToDataURI it gets tripled in size making it much larger than the same sized canvas (user photo) it overlays. (So, since the canvas size triples... the edited portion of it shrinks)

Here is a selfie where I just hold my finger up and then type a fire emoji over it. In the app, it looks fine and is large and immediately above my finger tip... but when toDataURI is called, the fabric canvas triples in size. I can fix this by adding:
"canvas.setZoom(3);" 
before the render event... but doing this pushes the emojis into glitch size and I'm also worried that doing this would break it for other devices I have not tested on yet.

![britton_152185150547](https://user-images.githubusercontent.com/141741/37858593-d111aa76-2ed4-11e8-90fc-705f5be6f7bf.jpg)

**Comment by brittonk** [comment]
Just in case anyone else working on a mobile app encounters this scaling issue and finds this issue thread... I found online where someone else ran into the issue and this seems to fix it.
(The desired size is 1080x1920)
        `<canvas id="canvas4" width="1080" height="1920"></canvas>`
...
       `var canvas = new fabric.Canvas("canvas4", {
            enableRetinaScaling: false,
        });`

       canvas.setDimensions({ width: '100vw', height: '100vh' }, { cssOnly: true });
