### ISSUE TITLE
textAnchor not converting to svg

### ISSUE THREAD

**Issue by dhavalsisodiya** [kangax/fabric.js#4847]
## Version
Fabric.js 2.0.0-beta7

## Steps to reproduce
Add a text and then apply the "Text Align"

https://codepen.io/dhavalsisodiya/pen/gvQooL

var activeObj = canvas.getActiveObject();
activeObj.set({
           textAlign : 'center',
           textAnchor : 'middle'
 });

The issue is i am trying to apply properties so object should be align middle no matter what. Let's say i have created one card in which i have added one variable, let's say {name} and applied the textAnchor  middle property into it. Then i am changing {name} with user's actual name. So it should also remain center.
But when i am generating the svg, but the resulted svg doesn't have "text-anchor" in it.

So what should i do so text-anchor will be in resulted svg?

SO Question: for more detail:
https://stackoverflow.com/questions/49429319/how-to-use-text-anchor-middle-in-fabric-js

**Comment by asturur** [comment]
resolved on stackoverflow, and not in scope as a fabricjs feature for now.
