### ISSUE TITLE
memory usage tops 512mb when using loadFromJSON() multiple times

### ISSUE THREAD

**Issue by silviolorusso** [kangax/fabric.js#4848]
Hi, I have an app on Heroku in which I generate a PDF from a series of canvases but it often tops the  memory quota of 512mb, even when the canvases are empty. Here's the code I use. Any help is highly appreciated. 

    doc = new PDFDocument({size:[pageWidth, pageHeight]})

    for (var i = 1; i < 9; i++) {
      canvas = new fabric.StaticCanvas()
      canvas.setWidth(canvasWidth)
      canvas.setHeight(canvasHeight)
      if ( publication && publication.pages.hasOwnProperty('p' + i) ) { // if not empty
        canvas.loadFromJSON(publication.pages['p' + i])
        delete publication.pages['p' + i]
        SVGtoPDF(doc, canvas.toSVG(), 0, 0)
        canvas.clear()
        canvas.dispose()
        if (i != 8) {
          doc.addPage()
        }
      }
      delete publication
      delete canvas
    }

    doc.pipe(res).on('finish', function() {
      console.log('single page pdf was successfully created by ' + process.pid)
    })

    doc.end()

**Comment by asturur** [comment]
Hey i publisehd a memory leak fix today for node. Can you try to build the latest master and update if the problem is exactly the same?

You should for sure remove that canvas.clear() from your loop, it does not make sense exactly before a canvas.dispose.

Also loadFromJson enforce a render, and this is completely unnecessary in your use case, i wonder if this should be avoided with an option.

**Comment by silviolorusso** [comment]
Hi, I tried to use the new build and maybe I'm making some mistakes since I get the following error:

`TypeError: fabric.util.requestAnimFrame is not a function`

Also, how do I prevent loadFromJson from enforcing a render? I don't see an option I can add.

**Comment by asturur** [comment]
There is not option.
mmm how is possible you get an error?
How did you build it?

**Comment by silviolorusso** [comment]
I hid the directory of the fabric.js i had with a dot in front of its name; downloaded the current master; put it in the node_modules directory; run `build.js`. Output:

    Built distribution to dist/fabric.js
    Minified using uglifyjs to dist/fabric.min.js
    Gzipped to dist/fabric.min.js.gz

**Comment by silviolorusso** [comment]
Output of the following is

    The script uses approximately 42.406883239746094 MB
    The script uses approximately 37.76110076904297 MB
    The script uses approximately 44.76299285888672 MB
    The script uses approximately 38.17701721191406 MB
    The script uses approximately 33.385108947753906 MB
    The script uses approximately 40.14579772949219 MB
    The script uses approximately 31.496063232421875 MB
    The script uses approximately 38.27465057373047 MB

  const fabric = require('fabric').fabric

    for (var i = 1; i < 9; i++) {
      const canvasWidth = 450
      const canvasHeight = 636
      canvas = new fabric.StaticCanvas()
      canvas.setWidth(canvasWidth)
      canvas.setHeight(canvasHeight)

      canvas.loadFromJSON({ background: 'white',
      objects:
       [ { minWidth: 20,
           charSpacing: 0,
           textBackgroundColor: '',
           textAlign: 'center',
           linethrough: false,
           overline: false,
           underline: false,
           lineHeight: 1.1,
           fontStyle: 'normal',
           fontFamily: 'AGaramondPro, serif',
           fontWeight: 'bold',
           fontSize: 30,
           text: 'Untitled',
           skewY: 0,
           skewX: 0,
           transformMatrix: null,
           globalCompositeOperation: 'source-over',
           paintFirst: 'fill',
           fillRule: 'nonzero',
           backgroundColor: '',
           clipTo: null,
           visible: true,
           shadow: null,
           opacity: 1,
           flipY: false,
           flipX: false,
           angle: 0,
           scaleY: 1,
           scaleX: 1,
           strokeMiterLimit: 10,
           strokeLineJoin: 'miter',
           strokeLineCap: 'butt',
           strokeDashArray: null,
           strokeWidth: 1,
           stroke: null,
           fill: '#777',
           height: 33.9,
           width: 450,
           top: 120,
           left: 0,
           originY: 'top',
           originX: 'left',
           version: '2.0.1',
           type: 'textbox' },
         { y2: 0,
           y1: 0,
           x2: 125,
           x1: -125,
           skewY: 0,
           skewX: 0,
           transformMatrix: null,
           globalCompositeOperation: 'source-over',
           paintFirst: 'fill',
           fillRule: 'nonzero',
           backgroundColor: '',
           clipTo: null,
           visible: true,
           shadow: null,
           opacity: 1,
           flipY: false,
           flipX: false,
           angle: 0,
           scaleY: 1,
           scaleX: 1,
           strokeMiterLimit: 10,
           strokeLineJoin: 'miter',
           strokeLineCap: 'butt',
           strokeDashArray: null,
           strokeWidth: 1,
           stroke: '#222',
           fill: 'rgb(0,0,0)',
           height: 0,
           width: 250,
           top: 160,
           left: 100,
           originY: 'top',
           originX: 'left',
           version: '2.0.1',
           type: 'line' },
         { minWidth: 20,
           charSpacing: 0,
           textBackgroundColor: '',
           textAlign: 'center',
           linethrough: false,
           overline: false,
           underline: false,
           lineHeight: 1.1,
           fontStyle: 'normal',
           fontFamily: 'AGaramondPro, serif',
           fontWeight: 'normal',
           fontSize: 20,
           text: 'Anonymous',
           skewY: 0,
           skewX: 0,
           transformMatrix: null,
           globalCompositeOperation: 'source-over',
           paintFirst: 'fill',
           fillRule: 'nonzero',
           backgroundColor: '',
           clipTo: null,
           visible: true,
           shadow: null,
           opacity: 1,
           flipY: false,
           flipX: false,
           angle: 0,
           scaleY: 1,
           scaleX: 1,
           strokeMiterLimit: 10,
           strokeLineJoin: 'miter',
           strokeLineCap: 'butt',
           strokeDashArray: null,
           strokeWidth: 1,
           stroke: null,
           fill: '#777',
           height: 22.6,
           width: 450,
           top: 180,
           left: 0,
           originY: 'top',
           originX: 'left',
           version: '2.0.1',
           type: 'textbox' } ],
      version: '2.0.1' })

      const used = process.memoryUsage().heapUsed / 1024 / 1024;
      console.log(`The script uses approximately ${used} MB`);
    }

**Comment by asturur** [comment]
The output does not suggest a leak.
The garbage collector is not obligated to clear anything after each iteration.

**Comment by silviolorusso** [comment]
So is this a normal behavior, meaning that if I have a series of canvases with several images I can't avoid topping the memory quota?

**Comment by jilster** [comment]
@silviolorusso Sorry for being selfish and asking you a question without actually helping you, but what are you using to create the PDF's? I am curious because i am working with TCPDF at the moment and it doesn't really go well.

**Comment by silviolorusso** [comment]
@jilster pdfkit

**Comment by jilster** [comment]
@silviolorusso thnx! good luck

**Comment by asturur** [comment]
my preferred way of doing pdfs is still fpdf in php. in js i cannot find anything good. Still dreaming of doing a serious pdf export for fabric

**Comment by asturur** [comment]
going back to memory usage, everything takes space. so a canvas of 500x600 less than 2 megs. 512 megs could be enough to do anything, depends on your code, 40 megs to iterate that code looks too much to me. But between font loading and font measurement, cairo lib, jsdom and node canvas, everything can be.  remove text objects and add Rects, see if it goes down significantly in this specific example.

**Comment by silviolorusso** [comment]
Canvas with only one rectangle:

    The script uses approximately 41.70698547363281 MB
    The script uses approximately 36.499183654785156 MB
    The script uses approximately 42.97254180908203 MB
    The script uses approximately 35.83888244628906 MB
    The script uses approximately 30.63581085205078 MB
    The script uses approximately 36.89453125 MB
    The script uses approximately 27.707313537597656 MB
    The script uses approximately 33.985328674316406 MB

Script:

    const fabric = require('fabric').fabric

    for (var i = 1; i < 9; i++) {
      const canvasWidth = 450
      const canvasHeight = 636
      canvas = new fabric.StaticCanvas()
      canvas.setWidth(canvasWidth)
      canvas.setHeight(canvasHeight)

      canvas.loadFromJSON({ background: 'white',
      objects:
       [ { background: 'white',
      objects:
       [ { ry: 0,
           rx: 0,
           skewY: 0,
           skewX: 0,
           transformMatrix: null,
           globalCompositeOperation: 'source-over',
           paintFirst: 'fill',
           fillRule: 'nonzero',
           backgroundColor: '',
           clipTo: null,
           visible: true,
           shadow: null,
           opacity: 1,
           flipY: false,
           flipX: false,
           angle: 0,
           scaleY: 1,
           scaleX: 1,
           strokeMiterLimit: 10,
           strokeLineJoin: 'miter',
           strokeLineCap: 'butt',
           strokeDashArray: null,
           strokeWidth: 5,
           stroke: 'rgba(34,177,76,1)',
           fill: 'rgba(255,127,39,1)',
           height: 50,
           width: 50,
           top: 50,
           left: 50,
           originY: 'center',
           originX: 'center',
           version: '2.0.1',
           type: 'rect' } ],
      version: '2.0.1' }]})

      canvas.dispose()

      const used = process.memoryUsage().heapUsed / 1024 / 1024;
      console.log(`The script uses approximately ${used} MB`);
    }

**Comment by asturur** [comment]
well this memory looks too much for me for just a rect, but apart from that 512megs is not that much for a server, you can expect to have constrains on concurrency with high level languages.

I have no idea if 30 megs are much or little, how much memory takes fabric once parsed? and cairo and png libs? and jsdom? really i do not know.

**Comment by asturur** [comment]
this is on my macbook:
![image](https://user-images.githubusercontent.com/1194048/37837273-1af3732e-2eb5-11e8-8493-a11f49963a44.png)

and look at the script:

```
const { fabric } = require('fabric');

setInterval(() => {
  const used = process.memoryUsage().heapUsed / 1024 / 1024;
  console.log(`The script uses approximately ${used} MB`);
}, 1000);
```

after a bit, the GC decided to clean stuff:

![image](https://user-images.githubusercontent.com/1194048/37837333-3e1c9902-2eb5-11e8-8578-5760be451723.png)

So why you do not expose the gc in the script, and run the gc after the requires and then at the end of each loop iteration and measure the memory usage in that way?
