### ISSUE TITLE
Support events for objects in group [$35]

### ISSUE THREAD

**Issue by thulka** [kangax/fabric.js#485]
http://jsfiddle.net/citykid/NSD4P/

the fiddle creates 3 rect objects

component
  body
  port

events for the inner rects, body and port do not fire.

**Comment by bsjaffer** [comment]
any workaround for this one?

**Comment by asturur** [comment]
I had a nearly working demo. but did not finish it yet.

**Comment by bsjaffer** [comment]
can you share that please or any other quick work around to get it done? Please

**Comment by asturur** [comment]
is not in my repo anymore, i hope i have on some disk home.
anyway the core was this:

```
_searchPossibleTargets: function(e, objects) {
      // Cache all targets where their bounding box contains point.
      var target, subTarget,
          pointer = this.getPointer(e, true),
          i = objects.length;
      while (i--) {
        if (!objects[i].oCoords) {
          objects[i].setCoords();
        }
        if (this._checkTarget(e, objects[i], pointer)){
          this.relatedTarget = objects[i];
          target = objects[i];
          break;
        }
      }

      if (target && this.findTargetInGroup && (target.type === 'group' || target.type === 'path-group')) {
        this.relatedTarget = this._searchPossibleTargets(e, target._objects || target.paths);
      }
      return target;
    },
```

but something was missing. You can start from this or from your own idea of course.

**Comment by bsjaffer** [comment]
Thanks will look on it.

**Comment by asturur** [comment]
probably the problem was that i was returning target and not this.relatedTarget?
maybe is just this stupid thing.

**Comment by asturur** [comment]
i got it :)

**Comment by asturur** [comment]
@jafferhaider  i spent lot of time on this yesterday. If you need a fix quick, a way could be this:

```
_searchPossibleTargets: function(e, objects) {
      // Cache all targets where their bounding box contains point.
      var target, subTarget,
          pointer = this.getPointer(e, true),
          i = objects.length;
      while (i--) {
        if (!objects[i].oCoords) {
          objects[i].setCoords();
        }
        if (this._checkTarget(e, objects[i], pointer)){
          this.relatedTarget = objects[i];
          target = objects[i];
          break;
        }
      }

      if (target && this.findTargetInGroup && (target.type === 'group' || target.type === 'path-group')) {
        // here calculate transformMatrix of the group with scale, rotate, translate.
        // transform cursor with this matrix inverted, be aware of group center
        // check for target with this changed pointer, is easier than changing the output of setcoords.
        target = this._searchPossibleTargets(e, target._objects || target.paths);
      }
      return target;
    },
```

to calculate the group transformMatrix:
you can take the functions from the parser of svgs.
I will try to do in the weekend, cause i started to like the idea, but if you need it faster, this is an hint.

**Comment by asturur** [comment]
I have so much problem inverting rotation.
I get to the point where:

![image](https://cloud.githubusercontent.com/assets/1194048/6546315/dc3ebd08-c5af-11e4-9a79-9d13a37b3815.png)

I transform the local pointer in differences between center point of target and local position , with scale inverted.
Now i should just UN-rotate the coords by - target.angle.
But this does not work.
I have tried to invert the rotation transformMatrix or create a transformMatrix of -angle.

Coords just fucks up.

**Comment by asturur** [comment]
if group is not rotated, the sub targeting works.

**Comment by kirkchris** [comment]
@asturur would you mind sharing updated code of the working sub targeting (minus the rotations)? just hit a use case for this on a project I am building and would love to use it and help out if I can.

**Comment by asturur** [comment]
https://github.com/asturur/fabric.js/pull/4

for whom may be interested before this future is supported ( if it will ever be ) there is a partial PR with 90% work done.

**Comment by nullpart** [comment]
I had problem with finding objects in rotated groups and added a small modification to calcRotateScaleMatrix that seems to work:

    calcRotateScaleMatrix: function() {
        var rotAngle = fabric.util.degreesToRadians(this.angle);
        var n = rotAngle ? -1 : 1;

        return fabric.util.multiplyTransformMatrices(
          [n * Math.cos(rotAngle), Math.sin(rotAngle), -Math.sin(rotAngle), n * Math.cos(rotAngle), 0, 0],
          [n * this.scaleX * (this.flipX ? -1 : 1), 0, 0, n * this.scaleY * (this.flipY ? -1 : 1), 0, 0]
         );

    }

**Comment by asturur** [comment]
On what version of fabric did you have the problem?
The problem on rotation was coming from a wrong multiply on "fabric.util.transformPoint" and not on the matrix itself.
in your code, if rotAngle = 0, n is 1, but the rotation is useless on angle 0, you can fully skip rotation.

**Comment by nullpart** [comment]
Hi, I use version 1.4.13.
Yes you are totally right about that, might as well skip the rotation on angle 0. :) thanks

**Comment by asturur** [comment]
So please check if you are missing this:
https://github.com/kangax/fabric.js/commit/8747ed1bd62c6024e02b8838587328c4c4d47408

and probably the rotation matrix is correct without the added minus sign.
The above correction is important because it influences ALL the transformation that have index 2 and 3 different from 0 ( rotation, skewing )

**Comment by damiangill** [comment]
I do hope fabric supports group item events in the near future.  The features fabric does support (interactive text, interactive transform on objects) are very nicely done, and a huge time saver.  The group event semantics are too limiting however.

As for the need being app specific, it is quite a common framework requirement.  Most Gui/scene-graph frameworks allow items to exist in groups for positioning but delegate events to group members if a handler has been set.  The dom/svg, paper.js and create.js, for instance, allows for handlers to exist on both group and item level.  This is resolved through a capture/bubble mechanism described at http://www.quirksmode.org/js/events_order.html.  A child can stop an event from propagating to it's parent by calling of a method like stopPropagation() on an event object.

**Comment by dud3** [comment]
+1 I think this will be really useful as well.

**Comment by dud3** [comment]
I haven't tested this, but it should work till some extend.

```js
var $canvas = {};
$canvas.activePaths = [];

function onMouseDown = function (options) {

    var mousePos = canvas.getPointer(options.e);
    mousePos.x = parseInt(mousePos.x);
    mousePos.y = parseInt(mousePos.y);

    var width =  canvas.getWidth();
    var height = canvas.getHeight();

    var pixels = canvas.getContext().getImageData(0, 0, width, height);
    var pixel = (mousePos.x + mousePos.y * pixels.width) * 4;

    var activePathsColor = new fabric['Color']('rgb(' + pixels.data[pixel] + ',' + pixels.data[pixel + 1] + ',' + pixels.data[pixel + 2] + ')');
    var colorHex = '#' + activePathsColor.toHex().toLowerCase();

    var activeObject = canvas.getActiveObject();
    var activePath = [];

    if(activeObject.type == 'group') {

          for (var i = 0; i < activeObject.getObjects().length; i++) {
            var path = activeObject.getObjects()[i];
            if (path.getFill().toLowerCase() == colorHex) {
                $canvas.activePaths.push(path);
            }
        }

    }

}

function warpActivePaths() {
    for(var i = 0; i < $canvas.activePaths.length; i++) {
        canvas.add(
            new fabric.Rect({
                left: $canvas.getActiveObj().left + ($canvas.activePaths[i].left),
                top: $canvas.getActiveObj().top + ($canvas.activePaths[i].top),
                fill: '',
                width: $canvas.activePaths[0].width,
                height: $canvas.activePaths[0].height,
                stroke: 'white', 
                opacity: 1 
            })
    );
    }
}
```

Maybe it'll help someone :)/

**Comment by asturur** [comment]
for whom is still interested look at #2729

**Comment by asturur** [comment]
I need also suggestion if we want a single target approach ( check target inside group, if not found return group, otherwise return sub target ) or a multiple target approach ( return group, sub group and sub  sub target )

**Comment by yezongyang** [comment]
+1; I think this will be really useful for map

**Comment by NikitaPirat** [comment]
Hi,
I tried to realize this functionality (selecting of a single object in a group). I wrote something like this:

`fCanvas.on('mouse:down', function(options) {

				if (options.target){
					var thisTarget = options.target; 
					var mousePos = fCanvas.getPointer(options.e);
					if (thisTarget.isType('group') && thisTarget.hasOwnProperty('name') 
							&& thisTarget.name.indexOf('cross_') > -1) {
						thisTarget.forEachObject(function(obj){
							var corners = obj.get('oCoords');
							// my own function (containsPoint doesn't work) 
							if (isPointInLocation(mousePos.x,mousePos.y, 
								[ {x: thisTarget.left + corners.tl.x, y: thisTarget.top + corners.tl.y},
								  {x: thisTarget.left + corners.tr.x, y: thisTarget.top + corners.tr.y}, 
								  {x: thisTarget.left + corners.bl.x, y: thisTarget.top + corners.bl.y},
								  {x: thisTarget.left + corners.br.x, y: thisTarget.top + corners.br.y}]))
							{
								fCanvas.setActiveObject(obj);
							}							
						});
					}
				}
			});` 

It works, but after group rotation the .oCoords property hasn't been changed. Is there any solution?

Thanks.

**Comment by asturur** [comment]
Please check the changes here for a solution that works with rotation and anything else:
https://github.com/kangax/fabric.js/pull/2729/files

it will be completed soon.

**Comment by satanworker** [comment]
I'm sorry is there any way to use your solution or test it? I'm just getting over with the same problem, for the second week, thank you

**Comment by asturur** [comment]
its marked for 1.6.3, i m gonna finish and merge this. help trsting is aporeciated

**Comment by let4be** [comment]
so... 3 years later, everything stills the same?
can't find any way to get mouse events for specific objects in groups/groups itself

**Comment by let4be** [comment]
Any update here?... 
Spent 3 hours trying to find a solution for getting events for particular object within the group

**Comment by asturur** [comment]
the pr is on the list, i will merge it as soon as i can test regressions

**Comment by pablopaul** [comment]
@asturur Any idea if 1.6.3 will be released approx. in 3 weeks, 3 months or 3 years? 😄

**Comment by asturur** [comment]
i would like to fix #3021 and give a check to current things merged to be sure we added as little as possible regressions ( i hope no regression at all).

**Comment by nirmal4343** [comment]
I have a rect inside the group, after scaling/modify of a group i need to find the new coordinates of rect inside the group, what is the possible ways to find the rect coordinated within the group?

**Comment by asturur** [comment]
take oCoords of the object and multiply them by the group transformmatrix
that you can get with calcTransformMatrix

**Comment by dhaalves-uel** [comment]
Is this working on 1.6.3 now? any example?

**Comment by dhaalves-uel** [comment]
Well, i find out how to do it.
Here is a sample http://jsfiddle.net/2Y587/80/

**Comment by fuvizzo** [comment]
ghost I used your sample and it was pretty helpful however I noticed that, on my old iphone 4 (iOS 7) with safari, a weird issue arises.

If I click for example on  polygon 1  and than I click on another different polygon, say 3, mouse:up event stil return, as target, polygon 1. 
Are you aware of that? Is there any fix?

Thanks

**Comment by asturur** [comment]
can you make a fiddle that reproduce this?

**Comment by fuvizzo** [comment]
The fiddle I used is the same ghost suggested
 http://jsfiddle.net/2Y587/80/
I found out the behaviour I reported on a code I developed, then I tried the same ghost's script cos I thought the issue could depend on my code, but the behaviour was the same. But I repeat, that happened only on my iphone 4. This afternoon I tried on an IPhone 6 and there were no problems on it
