### ISSUE TITLE
Cannot resize as in 1.x

### ISSUE THREAD

**Issue by iongion** [kangax/fabric.js#4854]
## Version
2.2.2

## Test Case
Custom element which is a wrapper against Image:
```js
const Type = 'data-image';
const Element = fabric.util.createClass(fabric.Group, {
  type: Type,
  initialize: function(userOptions) {
    const self = this;
    const options = { ...userOptions };
    let image = options.image;
    const initAsync = function() {
      const elementImage = new fabric.Image(
        image,
        {
          ...options,
          width: options.width,
          height: options.height,
        }
      );
      options.children = [ elementImage ];
      self.elementImage = elementImage;
      self.updateSize = (withRender) => {
        const sX = self.scaleX, sY = self.scaleY;
        const width = self.width * sX;
        const height = self.height * sY;
        self.elementImage.set({
          width,
          height,
          scaleX: 1,
          scaleY: 1,
          top: -height / 2,
          left: -width / 2
        });
        self.elementImage.setCoords();
        self.set({ width, height, scaleX: 1, scaleY: 1 });
        self.setCoords();
        if (withRender && self.canvas) {
          self.canvas.renderAll();
        }
      };
    const image = options.image;
    if (!image && options.dataURL) {
      image = new Image();
      image.onload = function() {
        initAsync();
      };
      image.src = options.dataURL;
    } else {
      initAsync();
    }
  },
);
```

## Steps to reproduce
Resize does not work as expected

## Expected Behavior
The self.elementImage resizes like 1.x, which is rescale with no aspect ratio constraints(deform!)
The code above works properly in 1.x branch.

## Actual Behavior
It acts as a crop and not resize

**Comment by asturur** [comment]
Custom classes based on Image really needs to be updated.
I can try to help if the code is not too much

**Comment by iongion** [comment]
This is fabric 1.x

https://jsfiddle.net/x3c5dff6/34/

This is fabric 2.x

https://jsfiddle.net/4tuodw0e/6/

It is almost the same code, but for **fabric 2.0** the image is not as big as the parent group.

**Comment by iongion** [comment]
In the end, I have something work for **2.0** https://jsfiddle.net/4tuodw0e/14/ is it safe enough ?

**Comment by iongion** [comment]
But if I want to have scaling to 1 to have pixel measurements, I hook into the object scaling and modified:

For **fabric 1.x** https://jsfiddle.net/x3c5dff6/40/
For **fabric 2.x** https://jsfiddle.net/4tuodw0e/17/

For **2.x** I don't understand what am I supposed to do to have identical scaling as in **1.x**

**Comment by iongion** [comment]
With more trial and error than understanding what is actually going on, I came up to this https://jsfiddle.net/4tuodw0e/25/ but don't know how safe it is.

Feel free to close this whenever you want!

**Comment by asturur** [comment]
we will close it when we understand if is osmething that we can help or not.

**Comment by asturur** [comment]
so you have a group, with no objects. This group has internally an image that you want to grow with the scale of the group, but you want the group to be always scaleX and scaleY to 1, and widht and height the real size.

let's see if i can make a cleaner example.

**Comment by asturur** [comment]
https://jsfiddle.net/4tuodw0e/27/

this is a different example that uses setOnGroup callback on the inner image.
Is not cleaner or better, is just different.

Your fiddle is fine too, nothing wrong there.

**Comment by iongion** [comment]
Thank you, excellent!
