### ISSUE TITLE
I can not find out the length of an array of objects on canvas?

### ISSUE THREAD

**Issue by jtag86** [kangax/fabric.js#4859]
I can not find out the length of an array of objects on canvas when on canvas are images.
console.log writes:
![screenshot from 2018-03-22 13-00-03](https://user-images.githubusercontent.com/16097555/37984562-643917c6-3218-11e8-882d-64314096aa2d.png)

When i write 

> console.log(array.length)

. The length of array is zero!
Please help.

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
