### ISSUE TITLE
Images filters demo broken

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4862]
## Version
2.2

## Test Case
http://fabricjs.com/image-filters

## Steps to reproduce
It's throwing errors 
````
fabric.js:10057 Uncaught TypeError: Cannot read property 'canvas' of undefined
    at Object.copyGLTo2DDrawImage (fabric.js:10057)
    at WebglFilterBackend.chooseFastestCopyGLTo2DMethod (fabric.js:9869)
    at WebglFilterBackend.setupGLContext (fabric.js:9841)
    at new WebglFilterBackend (fabric.js:9831)
    at image-filters:227
    at image-filters:498
```

**Comment by asturur** [comment]
On what part? i cannot make it happen.

**Comment by blobinabottle** [comment]
Ah that's weird I get it by default. 
I'm on Chrome Version 65.0.3325.181 (Official Build) (64-bit)
Let me check if I can isolate the issue then...

**Comment by blobinabottle** [comment]
OK after Chrome restart it's ok. I think it's related to my external eGPU and OS X. The browser thinks I have a dedicated graphic card but I'm back with the integrated card (until I restart it)... 

Sorry I guess we can close this.

**Comment by asturur** [comment]
well... strange anyway! if you can replicate it constantly, removing webgl from the demo with the checkbox, does solve the issue?

**Comment by blobinabottle** [comment]
Good idea. I can check in a few hours.

**Comment by blobinabottle** [comment]
The last update of macos X fixed the issue, I can't reproduce it now....

**Comment by asturur** [comment]
are those external gpus good for gaming?

**Comment by blobinabottle** [comment]
I don't know about games, but in 3D apps it runs pretty well (Zbrush, Blender, etc).

**Comment by fahadnabbasi** [comment]
broken for me, restarted browser, computer
windows 10, chrome Version 66.0.3359.117 (Official Build) (64-bit)

**Comment by blobinabottle** [comment]
The problem is not fabric this time.

**Comment by asturur** [comment]
Does the demo work?

2018-04-25 17:24 GMT+02:00 Blob <notifications@github.com>:

**Comment by fahadnabbasi** [comment]
@asturur nope, demo is not working for me

**Comment by asturur** [comment]
What do you do, what do you expect and what happens?

**Comment by blobinabottle** [comment]
@asturur does the demo work for you? Here there is nothing working. Safari or Chrome latest macOS (with or without egpu).

**Comment by asturur** [comment]
i did not try, i would like to understand where the problem is
@blobinabottle i invited you in the fabricjs org, but i can't see you in.

**Comment by blobinabottle** [comment]
I dont see the invite... weird
