### ISSUE TITLE
GIFs on Fabric JS

### ISSUE THREAD

**Issue by SaveskulSviatoslav** [kangax/fabric.js#4863]
## Version
2.0.2

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by SaveskulSviatoslav** [comment]
Hello.
I'm currently working with Fabric JS. 
I've got a problem and I hope you can help me with solving it. 
The thing is that I've tried to add to the canvas file in GIF format. The canvas doesn't display it in the motion (in the moving format). And also, after saving the background image from the canvas along with the GIF file on it this GIF image is static.
I'm wondering whether you have plans to implement in close future these abilities I've described you before.

**Comment by asturur** [comment]
There is no really way to animate a gif programmaticaly.
Some browser will animate it if you call requestRenderAll continuosly.

But is not a feature now, not a planned feature.

**Comment by SaveskulSviatoslav** [comment]
Thank you for the response.

2018-03-31 23:24 GMT+03:00 Andrea Bogazzi <notifications@github.com>:

**Comment by itubiaoge** [comment]
Do fabric play HTML5video to call requestRenderAll ?

**Comment by samael205** [comment]
http://fabricjs.com/video-element, See this example
