### ISSUE TITLE
Selected Item in foreground

### ISSUE THREAD

**Issue by c-gross** [kangax/fabric.js#4864]
## Version
2.2.1

https://jsfiddle.net/5fqs2cmb/3/

When I add 2 images to my canvas and select the image which is in the background it will be visible in the foregound until I deselect it. I want to avoid to bring the selected item in the foregound.

It's not a bug but different to the older fabric.js versions. I guess there is an option to change the behavior but I couldn't find it so far.

**Comment by samael205** [comment]
The option exists, it is called preseveObjectStacking, and you have to indicate when initializing the canvas with fabric in this way

var canvas = new fabric.Canvas ('c', {preserveObjectStacking: true});

[preserveObjectStacking Fidddle Example](https://jsfiddle.net/samael205/5fqs2cmb/7/)

**Comment by c-gross** [comment]
Oh nice, thanks alot!
