### ISSUE TITLE
FreeDrawing is still shifted when mouse is up!

### ISSUE THREAD

**Issue by mmfouda** [kangax/fabric.js#4865]
I tested it with many releases but I believe the freedrawing is shifted when the mouse goes up. May be because the canvas size is 250x250 but even though it should not shift. The test case is below with version 2.0.2. You may try some curvy arcs to notice it.

## Test Case
https://jsfiddle.net/vw6bydq8/1/

**Comment by mckhoi** [comment]
http://fabricjs.com/freedrawing has also this bug
I also tested and have to take back the version 2.7.0

**Comment by asturur** [comment]
3.1.0 is fixed.
I did not update the website yet

**Comment by mckhoi** [comment]
Great. I tested and version 3.1.0 works. Thank you for your support.
