### ISSUE TITLE
Fabricjs 2.0 How to set underline to substring of the Textbox

### ISSUE THREAD

**Issue by KalpeshVenturit** [kangax/fabric.js#4870]
## Version
2.0.2

## Steps to reproduce
I have Textbox with text "This is test textbox", i want to set underline to only word "test" not the whole textbox text. How do i set underline to the substring?

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

This is basic doc reading.
There is a method called setSelectionStyles that can operate on a selection. You can also create a virtual selection using selectionStart and selectionEnd.

For more details please open a SO question, and post the link here.
