### ISSUE TITLE
Question: activeSelection using perPixelTargetFind

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4871]
Not really a bug, but a question:
is it possible to set æll activeSelection to use perPixelTargetFind (so it doesn't mess up with the mouse over events). 

Using the hovering demo here is an example of the issue I try to fix:
https://cl.ly/1F2V3l0B3F1b
As you can see the hover only happens outside the activeSelection boundaries.

Thanks!

**Comment by asturur** [comment]
did you try with ```fabric.ActiveSelection.prototype.perPixelTargetfind = true``` ?

**Comment by asturur** [comment]
i m unsure it works correctly, i know there is some bug when caching + transparency + something else is activated

**Comment by blobinabottle** [comment]
https://jsfiddle.net/blobinabottle/1nhtfepr/12/ ha it seems to be almost ok :-) Thanks!

**Comment by blobinabottle** [comment]
Working pretty well until now. I think it's safe to close it.
