### ISSUE TITLE
Position corners on object

### ISSUE THREAD

**Issue by misantronic** [kangax/fabric.js#4873]
Is there a way to position the corners on an object?

<img width="339" alt="screen shot 2018-03-30 at 17 24 53" src="https://user-images.githubusercontent.com/6033531/38143132-6c45c36e-343f-11e8-895f-5a70f20bd982.png">

I would like to position them inside the rectangle inside the corners to avoid overlapping.

**Comment by asturur** [comment]
well you can try with padding negative number, but is an unsupported
feature, if it works, good, if it does not, i cannot really help.

2018-03-30 17:26 GMT+02:00 David Skx <notifications@github.com>:
