### ISSUE TITLE
loadFromJSON does not restore the correct canvas width and height values

### ISSUE THREAD

**Issue by sxe** [kangax/fabric.js#4876]
Hi, 
I use **toJSON** and **loadFromJSON** to serialize the canvas and noticed that when restoring the canvas size it does not work as expected.

I have a simple canvas with one text object.

1. I have to add width and height to the toJSON call
2. These values are not restored automatically, I have to manually use **setWidth** and **setHeight** to make it work. I would have expected that this happens automatically.
3. Even when doing step 2. the wrong size is restored. The stored text object width and height is used and not the width and height from the canvas we stored before.

I am not super experienced with fabricjs so maybe I am doing it wrong. 
Would be great if someone could have a look.

## Version
2.2.2

## Test Case
http://jsfiddle.net/6d5YC/58/

## Steps to reproduce

- Click the toJson button. The canvas changes size and is serialized and cleared afterwards.
- Check the console to see that the correct canvas size is stored in the exported JSON

- Click fromJson button 
- Check console to see that the wrong width and height are used to restore the canvas size. 

## Expected Behavior
The previously stored correct canvas size is restored.

## Actual Behavior
The canvas size is restored to the text object size which is inside the canvas.

Cheers

**Comment by asturur** [comment]
hi @sxe, great profile pic. The hero of my childood.

So loadFromJson is for the objects and background and not for the canvas itself.
This is not written anywhere, is just how the library behaves, zoom and pan information are not stored/restored too.

You can think of it as if that canvas size and vieport information are an application setting, while the objects and background are data on the canvas. Data is restored, settings not.

**Comment by sxe** [comment]
Haha, yeah mine too. :)

ok, good to know. I mean, the values are present in the JSON, so i will simply restore them manually before calling **loadFromJson**.

You can close the issue then, thx for the quick reply.

Cheers
