### ISSUE TITLE
IText letter-spacing support for SVG (revisit)

### ISSUE THREAD

**Issue by brentcappello** [kangax/fabric.js#4879]
SVG has the presentation attribute letter-spacing. It would be nice if we could easily access this while loading in an SVG. I think it would be beneficial to add access the attribute in the parsers attributeMap. CharSpacing works great great but ideally we still need to access the standard specification considering most the vector programs use this on SVG export. It looks like this was proposed in PR  #3718 but never fully resolved. I dug around and couldn't find a complete solution. Perhaps, I missed it?

I tried working with the reviver to access the attribute but couldn't easily navigate my way to the letter-spacing presentation attribute. I also attempted parsing my way through the signature referenced in issue #899. I'm all ears if you have another solution to handle access to character spacing data coming from an outside SVG. Cheers.

**Comment by asturur** [comment]
i think i may have missed that that PR contained import more than export. Let me see if it works good i can add it back

**Comment by asturur** [comment]
https://github.com/kangax/fabric.js/pull/3718

i cleaned up the old PR so that we can give the correct attribution to who did the work

**Comment by asturur** [comment]
merged
