### ISSUE TITLE
Binding of  properties to the wrapper element of canvas

### ISSUE THREAD

**Issue by krupatj** [kangax/fabric.js#4883]
How can I bind a property to the  wrapper (div) element of canvas?
I am using fabricj s in an angular 4 project

## Version
2.2.3

## Scenario
When a custom context menu is to be displayed only within the canvas container and I want to bind the property to the native div 'canvas-container', the same way as done in any other div.
`<div id="canvasContainer" [contextMenu]="customizingMenu"></div>
<context-menu #customizingMenu>
    <ul class="dropdown-menu">
         <ng-template contextMenuItem [visible]="true" [enabled]="true">Option 1</ng-template>
         <ng-template contextMenuItem [visible]="true" [enabled]="true">Option 2</ng-template>
    </ul>
</context-menu> -->`
In the above case the context menu will be visible only within the container 'canvasContainer', like wise 
how can I bind the property [contextMenu]="customizingMenu", fo rthe 'canvas-container'??

**Comment by asturur** [comment]
so the div canvas container gets created automatically by fabricjs and is not managed from react or angular.

This may be changed, meaning that, we could allow fabric to initialize on a container with a canvas, adding only the uppercanvas and letting frameworks like angular and react customize the container.

why you can't wrap your canvas in another div and let your menu exist there?

**Comment by krupatj** [comment]
Thankyou.
The issue was fixed by wrapping the canvas in another div and binding the property into that div?

**Comment by asturur** [comment]
@krupatj i m unsure why there is a questionmark at the end of your post.

**Comment by krupatj** [comment]
My bad. 
That was a mistake.
