### ISSUE TITLE
CRITICAL !!! - Canvas on object:selected event bug

### ISSUE THREAD

**Issue by redlive** [kangax/fabric.js#4886]
## Version
2.2.3

## Test Case
https://jsfiddle.net/redlive/ao2xwvhb/

## Steps to reproduce
Click on the Red element (you'll get an alert), release and then click on the Green.

## Expected Behavior
The `object:selected `event should fire every time when clicking on an element.

## Actual Behavior
Event onSelect fires only for the first time. After that, the event will work only if you click somewhere outside of the selected object on the canvas. The event also not working if "switching" between elements.

**Comment by aramir** [comment]
+1, this is a showstopper

**Comment by durga598** [comment]
Here is updated [fiddle](https://jsfiddle.net/durga598/ao2xwvhb/7/) and the [change log](http://fabricjs.com/v2-breaking-changes-2) mentioned. You need to use `selection:created` and
`selection:updated`.

**Comment by asturur** [comment]
@durga598 is right.
Please check the difference between v1 an v2 in those posted link.
