### ISSUE TITLE
lineline intersection faq?

### ISSUE THREAD

**Issue by myrecs** [kangax/fabric.js#4891]
is it possible to get explanation for "lineline intersection" algorithm, specifically for this equations
```
    fabric.Intersection.intersectLineLine = function(a1, a2, b1, b2) {
        var result,
            uaT = (b2.x - b1.x) * (a1.y - b1.y) - (b2.y - b1.y) * (a1.x - b1.x),
            ubT = (a2.x - a1.x) * (a1.y - b1.y) - (a2.y - a1.y) * (a1.x - b1.x),
            uB = (b2.y - b1.y) * (a2.x - a1.x) - (b2.x - b1.x) * (a2.y - a1.y);
```
what method from  math is used for this?
thanks.

**Comment by asturur** [comment]
I do not know or remember.
I'm sorry.

**Comment by myrecs** [comment]
wierd answer)

**Comment by asturur** [comment]
I can be wierd, but i do not even remember when the code was written.
Can be as far as 2010.

You are interested in the answer and you have the code under your eyes, can't you reverse it?

**Comment by myrecs** [comment]
no i cant' because it's about Math and as far as i know Math formulas i can't find anything that could satisfy that code.

**Comment by asturur** [comment]
https://stackoverflow.com/a/35457290/2655678
