### ISSUE TITLE
[2.2.3] ungroup adds "invisible" object

### ISSUE THREAD

**Issue by fredguth** [kangax/fabric.js#4892]
## Version
2.2.3

## Test Case
https://codepen.io/fredguth/pen/dmQjZo
## Steps to reproduce
draw a 2 segments forming a cross
click in group
click in ungroup
## Expected Behavior
ungroup would become 2 objects, the lines of the cross
## Actual Behavior
ungroups 3 objects, 2 lines and a box.

**Comment by asturur** [comment]
Is some kind of problem in your code, since group/ungroup is not a fabricJS feature.
Please move it to stackoverflow.com, eventually put the link here.

**Comment by fredguth** [comment]
https://stackoverflow.com/questions/43521002/how-do-i-make-all-objects-on-a-fabricjs-canvas-active-but-as-a-group/49713137#49713137
