### ISSUE TITLE
The picture in the canvas was dragged or scaled by me, and the picture disappeared into the canvas, that is, outside of the canvas, what do I do to move it to the middle of the canvas?

### ISSUE THREAD

**Issue by QianSu** [kangax/fabric.js#4896]
var canvas = new fabric.Canvas('canvas');
                    canvas.selection = false;
                    fabric.Image.fromURL(ret.base64, function (img) {
                        //console.log(img)
                        // .scale(0.3)
                        img.set({
                            width:document.querySelector('#canvas').width,
                            height:document.querySelector('#canvas').width/img.width*img.height,
                            left: 0,
                            top: 0,
                            angle: 0,
                            // perPixelTargetFind:true,
                            hasControls:false,
                            minScaleLimit:0.3,
                            lockScalingFlip:true,
                            centeredScaling:true,
                            lockRotation:true,
                        
                            isControlVisible:function(name){
                                console.log(name)
                                return true
                            }
                         

                        });
                 
                        canvas.add(img).setActiveObject(img);
                    });

                 

                    canvas.on({
                        'touch:gesture': function () {
                         
                          //  console.log(11)
                        },
                        'touch:drag': function (a,b,c) {
                        
                          console.log(a)
                          console.log(b)
                          console.log(c)
                        }
                   
                    });

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

**Comment by asturur** [comment]
Please for help request use stackoverlow, and eventually post the question link in this topic.
You usually get faster help for those kind of things
