### ISSUE TITLE
Update text in activeSelection: can't reset the activeSelection correctly

### ISSUE THREAD

**Issue by blobinabottle** [kangax/fabric.js#4901]
## Version
2.1 +

## Test Case
https://jsfiddle.net/blobinabottle/ha7fxjL1/

## Steps to reproduce
The jsFiddle is a bit silly, but we are changing text to uppercase in our real life issue. 
The idea is to update texts of all selected objects. In some cases the text object are growing, but not the activeSelection.

Even if we discard it, and re-create it based on the new objects.

## Expected Behavior
ActiveSelection should grow according to its content.

## Actual Behavior
ActiveSelection doesn't grow.

**Comment by asturur** [comment]
So, yes and no.

If you do ```Text.set('text', value)``` fabric will know that you are changing something that is dimension related and will basically call setDimensions/initDimension by itself.

This is the suggested pattern.

If you are doing ```Text.set('text', value)``` ```Text.set('fontFamily', value)``` ```Text.set('fontSize', value)``` ```Text.set('fontStyle', value)```  this will happen 4 times and maybe is too much.

In that case you can still fallback to:

```
Text.set({
  text: value,
  fontSize: value,
  fontFamily: value,
});
```

this will trigger the update once.
