### ISSUE TITLE
Text width incorrect with certain characters

### ISSUE THREAD

**Issue by tehmaestro** [kangax/fabric.js#4902]
Hi, I updated to the latest version of fabric js 2.2.3 from version 1.7.3, and it seems the following greek text causes issues when calculating the width: `Af̱tos menei ekei ta savvatokyriaka.` . The issue seems to be with the `f̱` which causes the bug.
  In my app, the text does not appear.
  Anyone else having this issue? Thanks.

**Comment by asturur** [comment]
i wonder if our grapheme splitter recognize it.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/38575416-a87bb04a-3cfb-11e8-8dda-52e6eece2e74.png)

definitely a grapheme split problem.
You need to find a good grapheme splitter and plug it in. I did overridable in an easy way because i can't and i do not want to support an official grapheme splitter.

**Comment by tehmaestro** [comment]
OK, I'll try and look into that. Is this because of individual character styling? I don't need it right now, any way I could disable it and temporarily bypass the issue? Thanks.

**Comment by asturur** [comment]
There is no way to bypass it.
that char under the f, i do not know the name, should be recognized as a part of the f itself but it isn't.

https://github.com/orling/grapheme-splitter

this takes a string as input and return an array of graphemes that is what you need.

you take fabric.util.graphemeSplitter and you change it with something that is using this package. Should be really easy.

**Comment by tehmaestro** [comment]
Hi, Thanks for the info. The issue is that I support many languages, and the suggested splitter simply is too big. I will revert to an older version of fabric for now until I figure out what do to. Thanks.

**Comment by asturur** [comment]
old version of fabric are way worse with multibyte and multi language if
you need interactivity.

**Comment by tehmaestro** [comment]
I did the revert. I do not need interactivity at all, so I'm kinda stuck. If anybody has a solution for version 2.x, that would be great :)
