### ISSUE TITLE
Unable to copy/paste (clone) subclassed objects

### ISSUE THREAD

**Issue by iranor** [kangax/fabric.js#4903]
Hello,

I am using the latest version of FabricJS. Using the Copy/Paste example on the website, and the LabeledRect example, I am unable to copy one object (or multiple objects). It does work with a regular Rect.

When I call the clone method on the ActiveSelection, the callback is never fired.

    canvas.getActiveObject().clone(function(cloned){
          console.log('Cloned');
    })

You may try both here (rect / labeledrect): https://jsfiddle.net/ncaq24ab/14/

I added the fromObject, but it doesn't seems to do the trick.

**Comment by asturur** [comment]
Your fromObject function is wrong, please check how other object's fromObject function is done.
