### ISSUE TITLE
Is there a way to collect keyboard events on the canvas? [Suggestion]

### ISSUE THREAD

**Issue by samael205** [kangax/fabric.js#4907]
Is there a way to collect keyboard events on the canvas?

It would be nice that as we collect mouse events as mouse: wheel and mouse: click, or mouse: dblclick, to collect the events of the keyboard.
Could it be done?
I say this because we could make the event management of the keyboard more bearable only when the canvas has the focus.

I give you an example:

In my application I have programmed the action of copying and pasting with Ctrl + C and Ctrl + V. (Copy / Paste), this I pick it up in the following way:

    `$ (document) .keydown (function (e) {
        if (ctrlDown && e.keyCode == cKey) {
            // <% 'Do not need to be aware of if I already had objects in my clipboard, for each time I do it I am going to change the content I had%>
            // <% 'FDNSCADA0722%>
            prepareCopy();
        }
        if (ctrlDown && e.keyCode == vKey) {
            copying = true;
            // <% 'FPJSCADA0653'%>
            saveState (true);
            // <% 'FPJSCADA0716'%>
            manageCopy ();

            saveState (true); // It is necessary to save the state just after copying
        }
    });`

The problem with doing this with this method is that when I'm going to copy and paste an element that is not from the canvas, for example a text, and I'm in the application, if I have an element of the canvas copied because I've done Ctrl + C, and I execute the action Ctrl + V the object in question is added to the canvas, and the contents of the clipboard are pasted as expected where I pasted it.

Would it be possible to link keyboard events that only work when I have the focus inside the canvas?

This is what the mouse can do with the dblclick, but not with the keyboard.

**Comment by bschelling** [comment]
why not only attach the keydown event to the canvas instead of the document? wouldn't that solve your problem?

**Comment by bschelling** [comment]
you can't attach a keydown event to a canvas. -> except you add contenteditable that is :) 
https://jsfiddle.net/bschelling/an6hL3wr/7/
its a weird hack and i don't know if it would mess with something else but its worth trying out...

**Comment by samael205** [comment]
Thanks, This works fine with tabindex

**Comment by samael205** [comment]
Another question asturur, why the classname of the upper-canvas is "upper-canvas "?
