### ISSUE TITLE
Pattern image on stroke

### ISSUE THREAD

**Issue by Clemweb** [kangax/fabric.js#4908]
Hello,

Is it possible to apply a pattern only on stroke ?

I use this to apply pattern on element : 

`fabric.util.loadImage(imageurl, function(img){
	obj.setPatternFill({
	source: img,
	repeat: 'repeat'
});
custengine.canvas.renderAll();
});`

On a rectangle, but it apply only on the whole rectangle, so my rectangle is transparent, only stroke is there. I need this to create frame on picture.

By the way I can't apply the pattern only on the stroke.

**Comment by asturur** [comment]
setPatternFill is a survived method that should have disappeared in 2.0

You can use ```object.set('stroke', new fabric.Pattern(options))``` where options is the object you were passing in the setPatternFill as first argument
