### ISSUE TITLE
rotatingPointOffset + cornerSize ignoring zoom

### ISSUE THREAD

**Issue by bschelling** [kangax/fabric.js#4910]
rotatingPointOffset + cornerSize are ignoring the zoom level (using  canvas.zoomToPoint(point, factor));

**Comment by asturur** [comment]
please prepare a fiddle showing the prpblem

**Comment by bschelling** [comment]
sure. https://jsfiddle.net/bschelling/j2kgj9mf/4/
i added the zoom to the mousewheel, does this work?
https://jsfiddle.net/bschelling/j2kgj9mf/4/

**Comment by asturur** [comment]
please try to explain what you expect to see and what is now working.

**Comment by bschelling** [comment]
Expectation: zooming in should adjust rotatingpoint offset and cornersize in relation to object size.
Current implementation: the cornersize and the rotatingpoint offset are fixed. this creates the effect that the more you zoom out, the more the rotatingpoint offset moves away from the object. zooming in has the opposite effect (rotatingpoint seems to come closer). the cornersize always stays the same regardless of zoom level.

**Comment by asturur** [comment]
ok i checked the fiddle.
There is no problem here.
Zoom is at canvas level were controls are not supposed to zoom at all.
Is how the library is made and built.

You can try to emulate it yourself, multiplying the cornerSize and the offset by current zoom level.

**Comment by bschelling** [comment]
@asturur thanks for checking it out. could you give me some insight why this was made this way? that might help me to explain to our client...

**Comment by asturur** [comment]
Because when it has done, it was done like this.
When you zoom you zoom the design and what is on canvas, the objects.
Controls are not objects, controls are a layer of interactivity over the objects and are not part of the final export neither.
As i said, you can still modify it at your will, the library is enough easy to get modified by devs, is not a black box.

**Comment by bschelling** [comment]
ok thx I'll give it a shot :)
