### ISSUE TITLE
ctx.setTransform adds padding on shape moving

### ISSUE THREAD

**Issue by mjseyyedi** [kangax/fabric.js#4916]
in a part of my app , I need to upload image inside an active shape. I solved it using the answer of [this question.](https://stackoverflow.com/questions/44743369/fabricjs-image-object-clipto-shape-object-issue)
this is my piece of code :

```
               var shape = canvas.fabric.getActiveObject();
                shape.image = url;
                shape.objectCaching = false;

                var fillImage = new Image();
                fillImage.onload = function (img) {

                    var photo = new fabric.Image(fillImage);

                    canvas.fabric.add(photo);
                    photo.clipTo = function (ctx) {
                        ctx.save();
                        ctx.setTransform(1, 0, 0, 1, 0, 0);
                        shape.render(ctx);
                        ctx.restore();
                    };
                    //canvas.fabric.remove(shape);
                    canvas.fabric.renderAll();
                };
                fillImage.src = url;
```

in the following images , you can see the result:
[result 1](https://i.stack.imgur.com/7Zq0b.png)

but when I move the shape and image, I have the problem below:
[result 2](https://i.stack.imgur.com/dC1Gk.png)

as you see , I have a gap between real shape and its showing area!!!!

could please help me on this???

**Comment by mjseyyedi** [comment]
I produced a jsfiddle project , but I don't have that bug in it!!! :|
http://jsfiddle.net/ADukg/23351/

**Comment by asturur** [comment]
So the problem is somewhere else.
What is missing in the fiddle from your project?

**Comment by asturur** [comment]
This is really something we can t help with. I m alone and i must work on bugs and new features. If is not reproducible is not a bug. When you can isolate the problem in a small fiddle, there is chance you see the solution immediately or simply is easier for me to look at.
