### ISSUE TITLE
Line coordinates after movement not changing

### ISSUE THREAD

**Issue by Melcus** [kangax/fabric.js#4917]
## Test Case  - Fabric 1.7.20
http://jsfiddle.net/j0xbr739/6/

## Steps to reproduce
    Move / Rotate a line object.
## Expected Behavior
   Get the updated x1, x2 , y1, y2 after the line was moved / rotated.
## Actual Behavior
   The old coordinates are being returned.

Did anyone find a way around this ? Thank you.

**Comment by samael205** [comment]
See this [Bad behavior in clone Line](https://github.com/kangax/fabric.js/issues/4766), it is related about your issue

**Comment by asturur** [comment]
guy you can write a method for line called `get current points` but is not an issue, not a `bad behavior`
It works like that.

If you want updated coordinates you have to calculate them
