### ISSUE TITLE
BlendColor Filter for large images not working in V2.+

### ISSUE THREAD

**Issue by radykal** [kangax/fabric.js#4918]
## Version
2.2.3

## Test Case
https://jsfiddle.net/snaz6sh9/3/

## Steps to reproduce
If you use a BlendColor filter on large images, in my demo the image is very wide, it does not display the new rendered image well. In Chrome the right side of the image is cut off, in Safari the whole image becomes transparent.

## Expected Behavior
I test it with an older version 1.6.7 and there I had no issues with the Tint filter.

**Comment by asturur** [comment]
Please check the breaking changes documentation about how to handle large images.
http://fabricjs.com/fabric-filters
