### ISSUE TITLE
transform fails in loadSVGFromURL for image and tspan elements

### ISSUE THREAD

**Issue by f1fe** [kangax/fabric.js#502]
Similar to issue #420 

This SVG https://hungercrunch-uploads.s3.amazonaws.com/uploads/hcproduct/svg/66/hc.svg was created using fabric and canvas.toSVG(). It renders correctly in Safari and Chrome but fails in http://fabricjs.com/kitchensink/

I think it's the transform operation that is failing.

**Comment by asturur** [comment]
This issue can be closed.
TSPAN has its own thread.
All items are supported correctly, what fails is because it does not have the resources available anymore.
