### ISSUE TITLE
activeGroup object sort is incorrect

### ISSUE THREAD

**Issue by Kienz** [kangax/fabric.js#508]
The zIndex of activeGroup objects is wrong.

objects before activeGroup selection:
<img src="https://s3-eu-west-1.amazonaws.com/kienzle.geschaeft/projects/fabricjs/objects_before_activeGroup.png"/>

objects in activeGroup selection:
<img src="https://s3-eu-west-1.amazonaws.com/kienzle.geschaeft/projects/fabricjs/objects_activeGroup.png" />

**Comment by jagi** [comment]
Issue still exists 
![fabric1](https://cloud.githubusercontent.com/assets/1051229/6062505/9e4470c8-ad50-11e4-849b-2c563ee00220.png)
![fabric2](https://cloud.githubusercontent.com/assets/1051229/6062511/a1c0951a-ad50-11e4-9d02-39cb0dae00db.png)

The problem is in rendering order not placing group into `canvas._objects`.
Here are fixes to code that will make it work properly:

```js
fabric.Canvas.prototype.renderAll = function(allOnTop) {
  var canvasToDrawOn = this[(allOnTop === true && this.interactive) ? 'contextTop' : 'contextContainer'],
    activeGroup = this.getActiveGroup();

  if (this.contextTop && this.selection && !this._groupSelector) {
    this.clearContext(this.contextTop);
  }

  if (!allOnTop) {
    this.clearContext(canvasToDrawOn);
  }

  this.fire('before:render');

  if (this.clipTo) {
    fabric.util.clipContext(this, canvasToDrawOn);
  }

  this._renderBackground(canvasToDrawOn);
  this._renderObjects(canvasToDrawOn, activeGroup);
  // this._renderActiveGroup(canvasToDrawOn, activeGroup);

  if (this.clipTo) {
    canvasToDrawOn.restore();
  }

  this._renderOverlay(canvasToDrawOn);

  if (this.controlsAboveOverlay && this.interactive) {
    this.drawControls(canvasToDrawOn);
  }

  this.fire('after:render');

  return this;
};

fabric.Canvas.prototype._renderObjects = function(ctx, activeGroup) {
  var i, length;

  if (!activeGroup || this.preserveObjectStacking) {
    for (i = 0, length = this._objects.length; i < length; ++i) {
      this._draw(ctx, this._objects[i]);
    }
  } else {
    for (i = 0, length = this._objects.length; i < length; ++i) {
      if (this._objects[i] && !activeGroup.contains(this._objects[i])) {
        this._draw(ctx, this._objects[i]);
      } else { // ADD THIS...
        this._renderActiveGroup(ctx, activeGroup);
      }
    }
  }
};
```

I've checked it and it works.

**Comment by asturur** [comment]
The screen you capture is not really a fix, we do not want the controls to be under any object. Controls are always over.

**Comment by jagi** [comment]
So, there is one more error because right now it looks like this
![fabric-selection-error](https://cloud.githubusercontent.com/assets/1051229/6066953/35e77a7c-ad71-11e4-95db-62a78435fcae.png)

I'm working on the fix

**Comment by jagi** [comment]
Ok I've made another pull request. Now code got much simpler.

http://jsbin.com/dejiwu/3/edit?js,output

![fabric-selection-fixed](https://cloud.githubusercontent.com/assets/1051229/6067271/a33e684a-ad73-11e4-938b-fbe42dbf3b0e.png)

I've noticed another bug but not related with rendering controls. The error occurs when hovering mouse on the control point of the object that is behind another object. Try [here](http://jsbin.com/dejiwu/3/edit?js,output) selecting green circle and clicking right bottom control point.

**Comment by asturur** [comment]
maybe o was wrong? i will check current situation

**Comment by asturur** [comment]
I think main problem here is this:

https://github.com/kangax/fabric.js/blob/master/src/static_canvas.class.js#L888
```diff
    /**
     * @private
     * @param {CanvasRenderingContext2D} ctx Context to render on
     * @param {fabric.Group} activeGroup
     */
    _renderActiveGroup: function(ctx, activeGroup) {

      // delegate rendering to group selection (if one exists)
      if (activeGroup) {

        //Store objects in group preserving order, then replace
        var sortedObjects = [];
        this.forEachObject(function (object) {
          if (activeGroup.contains(object)) {
            sortedObjects.push(object);
          }
        });
-       activeGroup._set('objects', sortedObjects);
+       activeGroup._set('_objects', sortedObjects);
        this._draw(ctx, activeGroup);
      }
    },
```

We are ordering the activeGroup objects but then we are putting them in object array , while rendering uses just the _objects.
@kangax @Kienz, is this possible?
