### ISSUE TITLE
No events fired after resize with pinch zoom.

### ISSUE THREAD

**Issue by mmb** [kangax/fabric.js#510]
After resizing an object using pinch zoom on a touch device, no events are fired. Should object.modified be fired after gestureend?

**Comment by jafferhaider** [comment]
Hey @kangax, here's a fix for this issue. I noticed this too. The gestures code wasn't firing `rotating` or `scaling` events nor the `modified` event at the end. The commit below in my fork fixes this:
https://github.com/PosterMyWall/fabric.js/commit/667a7d3b6e238aba5ea9b84a063ebdd6b4e0dd72

**Comment by kangax** [comment]
Hey @jafferhaider, thanks! Any chance you could send a PR? That would be amazing.
