### ISSUE TITLE
activeGroup removeObject (shiftKey) did not work if perPixelTargetFind = true

### ISSUE THREAD

**Issue by Kienz** [kangax/fabric.js#532]
<p>In the following jsfiddle you can see the behavior of activeGroup with <code>perPixelTargetFind = true</code> (left canvas) and activeGroup with <code>perPixelTargetFind = false</code> (right canvas).</p>

<p>Select all objects and try to deselect one of the group objects with shiftKey. On the left canvas it doesn't work.<br><a href="http://jsfiddle.net/Kienz/62AXX/">http://jsfiddle.net/Kienz/62AXX/</a></p>

<p>The problem is that absolute pointer coordinates are used for target with relative coordinates (group object). I tried to normalizePointer (_normalizePointer) =&gt; this worked only for objects with positive relative left/top parameters.</p>

<p>The other thing i tried is to use whole group object for check if target is transparent:<br><code>var isTransparent = this._isTargetTransparent(activeGroup &amp;&amp; this.containsPoint(e, activeGroup) ? possibleTargets[j].group : possibleTargets[j], pointer);</code><br><a href="https://github.com/kangax/fabric.js/blob/master/src/canvas.class.js#L749">https://github.com/kangax/fabric.js/blob/master/src/canvas.class.js#L749</a></p>

<p>This works but maybe there is some performance problem for large groups (all objects have to be renderd on cacheContext).</p>

**Comment by asturur** [comment]
Actually i cannot deselect in any grouped object. with shift. not with perPixelTarget, not normal.

**Comment by asturur** [comment]
@kangax @kienz i just tested, i cannot  deselect any selection created active group using shift key.
I really do not know if this is a new issue

**Comment by kangax** [comment]
@asturur @Kienz looks like a regression (it worked before)

**Comment by asturur** [comment]
https://github.com/kangax/fabric.js/commit/9e1a93db5a37d814fd9110e4fdddda21aae37047#diff-9dc132ed9a0787568f773999ba577e2bR813

**Comment by asturur** [comment]
No restoring that line those not change situation
