### ISSUE TITLE
Calling object.set({...}); doesn't fire "object:modified" event

### ISSUE THREAD

**Issue by choxnox** [kangax/fabric.js#616]
While I understand event "object:modified" is fired whenever object is moved, scaled or rotated, in my opinion calling e.g. object.set({fillColor: "#000"}); should also fire "object:modified" since object is modified in some way (in this case it's the change of fill color).

I'm now working on web application which is similar to Photoshop, and I'm displaying small thumbnail image for each layer (object). This thumbnail changes whenever object is modified to reflect the changes in real time. Problem arises when I need to change properties for object because I have to manually fire "object:modified" each time properties is changed via object.set() function. 

The only modification to the current code base would be to simply add one line to the object.set() function which triggers "object:modified" event.

**Comment by asturur** [comment]
With stateful true this should happen at every renderAll.
Also using object.fill = 'red';
At the next renderAll you get firing of object:modified.
You can add to state_properties wathever you need also.
