### ISSUE TITLE
Old resize + scale behavior (simultaneous)

### ISSUE THREAD

**Issue by sitemind** [kangax/fabric.js#623]
I see some demo's on the web from old Fabric.js versions where you can rotate and resize with a single handle. I understand you removed this feature because of unwanted rotating objects while scaling. But I actually need this feature and rotate my objects in steps of 45 degrees, so there is always an easy option to align the object horizontally.

Is this functionality removed accidentally or intentionally, as Kienz questioned in this discussion (https://groups.google.com/d/msg/fabricjs/_kKoitQrReo/7G3CQkqb_ysJ)?

Maybe the stepwise rotation is already possible, I see some <code>straighten</code> functions inside fabric.js?

**Comment by asturur** [comment]
This feature request is either not applicable or based on old needs that are replaced by new functions or features.
The feature also did not receive attention from other developers.
I will reopen by request if other may find it interesting.
