### ISSUE TITLE
Control over sync/asnyc cloning.

### ISSUE THREAD

**Issue by aleph1** [kangax/fabric.js#684]
When creating clones and applying filters it would be ideal if we could control whether the code executes synchronously/asynchronously. We could maintain the current method and simply detect whether callback is a specific value (for example,  === true) to force the code to execute synchronously. This would alleviate the need to create numerous callback functions which are sometimes unnecessary and require more code.

I suppose a similar approach could be used for the applyFilters method of the image class.

Personally I would find this change very useful and it wouldn't break existing code that relies upon Fabric.js.
##

**Comment by asturur** [comment]
there is a way to clone an image syncronously, giving it canvas elements as a source instead of img tags.
I guess it can be left to some sort subclassing to the user.
