### ISSUE TITLE
Curve Text SVG not loading correctly

### ISSUE THREAD

**Issue by robinflyhigh** [kangax/fabric.js#820]
Try and load the curve text SVG into kitchen sink demo using below steps and it does not render the svg correctly:

1.) Visit http://fabricjs.com/kitchensink/
2.) Select Load SVG Tab
3.) Copy paste the content from http://sharetext.org/aq9p into the textarea and click Load button
4.) Text is straight :)

Wrap works, try SVG code @ http://sharetext.org/6mU5

Trying to digg into the issue...

**Comment by kangax** [comment]
Closing as duplicate of #1280
