### ISSUE TITLE
fabric.Group.addWithUpdate() re-applies transform matrix to existing group objects

### ISSUE THREAD

**Issue by lorenzopolidori** [kangax/fabric.js#833]
When using `fabric.Group.addWithUpdate()` to add existing canvas objects to a group on which some transformations have been applied, the same transformation matrix is applied again on the existing group objects, resulting in a double rotation and scaling.

This behavior can be reproduced using [this jsFiddle](http://jsfiddle.net/lorenzopolidori/cjUdb/) - just click on the <kbd>group first two</kbd> button and then on the <kbd>group third</kbd> one.

I suppose the correct behavior is to apply the group transformation only to the object added last and leave the existing ones untouched.

**Comment by asturur** [comment]
http://jsfiddle.net/cjUdb/3/  see updated fiddle for solution.
