### ISSUE TITLE
Give API Docs a column for methods like underscore.js

### ISSUE THREAD

**Issue by clouddueling** [kangax/fabric.js#911]
I was going through the docs and thought a great improvement would be to add a column for pages like: 
http://fabricjs.com/docs/fabric.Circle.html

that would look like:
http://bootstrap.harp.io/
http://underscorejs.org/
https://stripe.com/docs/api#coupons

Is there a way I could do this?

**Comment by asturur** [comment]
closable with this: 
added scrollbar for the column, added option to hide inheriteds.
https://github.com/kangax/fabricjs.com/pull/113
