### ISSUE TITLE
setBackgroundColor semantic sense.

### ISSUE THREAD

**Issue by zba** [kangax/fabric.js#913]
I commented on the commit.

[please check here](https://github.com/kangax/fabric.js/commit/6777c500120a6d8429d9266fc7225b5a468bb43c#diff-e043717eeb1106354d4cb8a776e53767R5687)

**Comment by asturur** [comment]
Denitely needs a fix for 2.0
And we cannot use a gradient yet.

for my mind it make more sense:
setBackground accept color or gradient
setBackgroundImage accept IMAGE ( in element, string or fabric.Image or patterFormat ) and as a flag that says 'repeat' or 'useAsPattern'
The point is one rendering should exclude the other? in which priority?

Or maybe we could have a background array, where we can store various background in the form of fabric classes and just render them all.

**Comment by asturur** [comment]
@kangax @kienz i made a branch fabric2 and i start do those things.
Why we do not give for consistency a property 'fill' to canvas that can keep a color or a gradient or a pattern, and then we leave a setBackground that can keep a fabricObject ( image , group , whatever ) that behave like a background.

Please answer me i like to hear your opinion.
