### ISSUE TITLE
Support svg mask

### ISSUE THREAD

**Issue by mohhad** [kangax/fabric.js#930]
This issue is created since there is no support for svg mask as shown in this screenshot.
![test1](https://f.cloud.github.com/assets/5013058/1415271/a919a498-3ef0-11e3-989b-6723fed85145.png)

You can download the SVG file under study from this Link:
http://www.mediafire.com/download/bzl5k86cv19l7dd/TestSvg.svg

**Comment by asturur** [comment]
duplicate of #1360.
which has better description and same title
