### ISSUE TITLE
Load from JSON is not working with Patterns in the latest version of Fabric.js

### ISSUE THREAD

**Issue by jhonPeterson** [kangax/fabric.js#935]
When am trying to load the JSON data onto the canvas, every shape is getting loaded but the patterns that are filled in the shapes are loaded only after I click on the shape.

Could some one please explain why this is happening? I even checked this:

canvas2.loadFromJSON(json,canvas2.renderAll.bind(canvas2));
Also, the same problem is with the clone() function: the object is duplicated. But the pattern filled in the object is shown only after I click on the object.

I am using version 1.3.7.
##

**Comment by asturur** [comment]
i m changing the fromObject from the classes.
I added a callback in the pattern init, every object fromJSON has its own callback.
I will check if the object has a stroke or fill property like patterns, enlive patterns before object, enlive object with patterns ready, then fire the callback of the object. In this way we should solve.

**Comment by asturur** [comment]
/cc: @ncou from #3548 

This is a working solution. The forceAsync parameter is going to disappear in 2.0 where objects will be enlived just with callbacks. Now i cannot break the api since i plan a 1.7.3 release with this fix.

```javascript
  /**
   * Returns {@link fabric.Rect} instance from an object representation
   * @static
   * @memberOf fabric.Rect
   * @param {Object} object Object to create an instance from
   * @param {Function} [callback] Callback to invoke when an fabric.Rect instance is created
   * @param {Boolean} [forceAsync] Force an async behaviour trying to create pattern first
   * @return {Object} instance of fabric.Rect
   */
  fabric.Rect.fromObject = function(object, callback, forceAsync) {
    if (forceAsync) {
      fabric.util.enlivenPatterns([object.fill, object.stroke], function(patterns) {
        object.fill = patterns[0];
        object.stroke = patterns[1];
        var rect = new fabric.Rect(object);
        callback && callback(rect);
      });
    }
    else {
      var rect = new fabric.Rect(object);
      callback && callback(rect);
      return rect;
    }
  };
```
