### ISSUE TITLE
Group behavior (mouse area and bounding rect) is problematic when there are invisible objects within

### ISSUE THREAD

**Issue by raichu** [kangax/fabric.js#980]
(This is originally the *unfixed* bug #952, which is closed with the cryptic message

> Visible objects still respond to mouse, they're just not visible. 

which isn't really a reply/solution to the original report, and even after a jsfiddle demonstrating the bug, it wasn't reopened, so here I go again.)

I have a group with several objects, and I made all the objects invisible. Still, they respond to mouse, as demonstrated by:

http://jsfiddle.net/8U5V4/1/

Furthermore, when you have two objects in the group, one visible and one invisible, the selectable area covers both, not just the visible one: http://jsfiddle.net/nmY25/

**Comment by asturur** [comment]
everything works fine, there is nothing to fix here.
The fiddle has some errors that makes something works crazy:

object added both on group and on canvas separtely
normal group set as activeGroup ( creating problems when you click outside of it )
