### ISSUE TITLE
Add support for IText SVG import/export

### ISSUE THREAD

**Issue by kangax** [kangax/fabric.js#987]

**Comment by asturur** [comment]
itext Svg Export is done, can we close this issue?

**Comment by kangax** [comment]
Yep!

**Comment by hamsarao** [comment]
Hi 

When Itext is edit the tspan value changes and the text moves out of canvas. Please suggest a solution

**Comment by nikhleshjhawar** [comment]
Hello i wont to edit to text in svg cat it posiable please send me njhawar@flair-solution.com
